const fs = require('fs');
const path = require('path');

const BASE = 'C:/Users/nicol/Desktop/Curiosita';

function coursePage({title, disciplineTitle, disciplineFile, hubTitle, hubFile, breadcrumbDiscipline, breadcrumbHub, tagDomain, time, introText, introHighlight, introText2, courseH3s, quizQuestions, prevCourse, nextCourse, siblings, currentFile}) {
  const totalQ = quizQuestions.length;
  const quizBlocks = quizQuestions.map((q, i) => {
    const opts = q.opts.map((o, oi) => `              <button class="option" onclick="answer(this,${oi === q.ans ? 'true' : 'false'})">${o}</button>`).join('\n');
    return `          <div class="question-block${i===0?' active':''}" data-q="${i}">
            <p class="q-num">Question ${i+1} / ${totalQ}</p>
            <p class="q-text">${q.q}</p>
            <div class="options">
${opts}
            </div>
            <div class="q-feedback">${q.expl}</div>
          </div>`;
  }).join('\n');

  const courseContent = courseH3s.map(s => `        <h3>${s.title}</h3>\n${s.paragraphs.map(p => `        <p>${p}</p>`).join('\n')}`).join('\n\n');

  const sidebarSiblings = siblings.map(s => {
    if (s.file === currentFile) return `    <a class="sidebar-link active" href="#">${s.name}</a>`;
    return `    <a class="sidebar-link" href="${s.file}">${s.name}</a>`;
  }).join('\n');

  const navPrev = prevCourse ? `      <a href="${prevCourse.file}">
        <span class="course-nav-label">Cours precedent</span>
        <span class="course-nav-title">&larr; ${prevCourse.name}</span>
      </a>` : '      <div></div>';
  const navNext = nextCourse ? `      <a href="${nextCourse.file}" class="next">
        <span class="course-nav-label">Cours suivant</span>
        <span class="course-nav-title">${nextCourse.name} &rarr;</span>
      </a>` : '';

  const exercices = `    <section class="content-section" id="exercices">
      <div class="section-header">
        <div class="section-num">04</div>
        <div class="section-info"><h2>Exercices</h2><p>Mettez en pratique vos connaissances</p></div>
      </div>
      <div class="course-content">
        <details>
          <summary>Exercice 1 &mdash; Analyse</summary>
          <p>Choisissez une oeuvre etudiee dans ce cours et redigez une analyse de 200 mots couvrant : le contexte historique, les techniques utilisees et l'impact sur la discipline.</p>
        </details>
        <details>
          <summary>Exercice 2 &mdash; Comparaison</summary>
          <p>Comparez deux artistes ou oeuvres mentionnes dans ce cours. Identifiez les points communs, les differences et l'influence de l'un sur l'autre.</p>
        </details>
        <details>
          <summary>Exercice 3 &mdash; Recherche</summary>
          <p>Recherchez un artiste ou une oeuvre non mentionne(e) dans ce cours mais appartenant a la meme periode ou au meme mouvement. Presentez-le/la en un court paragraphe.</p>
        </details>
      </div>
    </section>`;

  return `<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="${introText.replace(/<[^>]+>/g,'').substring(0,155)}">
<link rel="icon" href="../../../favicon.svg" type="image/svg+xml">
<title>${title} — ${hubTitle} — Curiosita</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=DM+Sans:wght@300;400;500&family=Lora:ital,wght@0,400;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../../../style.min.css?v=4">
<link rel="stylesheet" href="../../../sr-style.min.css?v=4">
<style>
:root { --accent: #e87a7a; --accent2: #f09090; --accent-dim: rgba(232,122,122,0.08); --accent-hero: rgba(232,122,122,0.04); }
</style>
</head>
<body>
<nav>
  <a href="../../../index.html" class="logo">Curiosita.</a>
  <div class="breadcrumb">
    <a href="../index.html">${breadcrumbDiscipline}</a> &rsaquo; <a href="../${hubFile}">${breadcrumbHub}</a> &rsaquo; <span>${title}</span>
  </div>
</nav>
<div class="hero hero--course">
  <div class="hero-meta">
    <span class="tag-domain">${tagDomain}</span>
    <span class="tag-level">Debutant &rarr; Intermediaire</span>
    <span class="tag-time">&#9201; ~${time} min</span>
  </div>
  <h1><em>${title}</em></h1>
  <p class="hero-desc">${introText.substring(0, 120)}...</p>
</div>
<div class="layout">
  <aside class="sidebar">
    <a class="sidebar-link" href="../${hubFile}" style="color:var(--accent);margin-bottom:0.5rem;font-weight:500;">&larr; ${hubTitle}</a>
    <p class="sidebar-title">Ce cours</p>
    <a class="sidebar-link active" data-section="introduction" onclick="goTo('introduction',this)">&#128214; Introduction</a>
    <a class="sidebar-link" data-section="cours" onclick="goTo('cours',this)">&#128221; Le cours</a>
    <a class="sidebar-link" data-section="quiz" onclick="goTo('quiz',this)">&#127919; Quiz</a>
    <a class="sidebar-link" data-section="exercices" onclick="goTo('exercices',this)">&#9999;&#65039; Exercices</a>
    <p class="sidebar-title">Autres cours</p>
${sidebarSiblings}
  </aside>
  <main class="main">
    <section class="content-section" id="introduction">
      <div class="section-header">
        <div class="section-num">01</div>
        <div class="section-info"><h2>Introduction</h2><p>${title}</p></div>
      </div>
      <p class="resume-text">${introText}</p>
      <div class="highlight-box">
        <p>${introHighlight}</p>
      </div>
      <p class="resume-text">${introText2}</p>
    </section>
    <section class="content-section" id="cours">
      <div class="section-header">
        <div class="section-num">02</div>
        <div class="section-info"><h2>Le cours</h2><p>${title}</p></div>
      </div>
      <div class="course-content">
${courseContent}
      </div>
    </section>
    <section class="content-section" id="quiz">
      <div class="section-header">
        <div class="section-num">03</div>
        <div class="section-info"><h2>Quiz</h2><p>Testez votre comprehension</p></div>
      </div>
      <div class="quiz-container">
        <div class="quiz-header">
          <span class="quiz-title-text">Quiz &mdash; ${title}</span>
          <span class="quiz-score">Score : <span id="scoreDisplay">0</span> / <span id="totalDisplay">${totalQ}</span></span>
        </div>
        <div class="quiz-body" id="quizBody">
${quizBlocks}
        </div>
        <div class="quiz-result" id="quizResult">
          <div class="result-score-big" id="resultScore">0/${totalQ}</div>
          <div class="result-msg" id="resultMsg"></div>
          <button class="btn-retry" onclick="resetQuiz()">&#8634; Recommencer</button>
        </div>
        <div class="quiz-nav">
          <button class="btn-quiz btn-prev" onclick="prevQ()" id="btnPrev" disabled>&larr; Precedent</button>
          <div class="q-dots" id="qDots"></div>
          <button class="btn-quiz btn-next" onclick="nextQ()" id="btnNext" disabled>Suivant &rarr;</button>
        </div>
      </div>
    </section>
${exercices}
    <div class="course-nav">
${navPrev}
${navNext}
    </div>
  </main>
</div>
<footer class="site-footer">
  <div class="footer-links">
    <a href="../../../index.html">Accueil</a>
    <a href="../../../cours.html">Cours</a>
    <a href="../../../apprendre.html">Apprendre</a>
  </div>
  <p>&copy; 2025 Curiosita</p>
</footer>
<script src="../../../curiosita.min.js?v=4" defer></script>
<script src="../../../sr-course.min.js?v=4" defer></script>
</body>
</html>`;
}

// ==================== CINEMA COURSES ====================

const cinemaCourses = {
  histoire: {
    hubTitle: 'Histoire du cinema',
    hubFile: 'histoire.html',
    siblings: [
      {name:'Naissance du cinema', file:'naissance.html'},
      {name:"Age d'or hollywoodien", file:'hollywood.html'},
      {name:'La Nouvelle Vague', file:'nouvelle-vague.html'},
      {name:'Cinema mondial', file:'cinema-mondial.html'},
      {name:'Cinema contemporain', file:'contemporain.html'}
    ],
    courses: [
      {
        file:'naissance.html', title:'Naissance du cinema', time:'40',
        introText:"Le cinema naît officiellement le <strong>28 decembre 1895</strong>, lorsque Auguste et Louis Lumiere organisent la premiere projection publique payante au Salon indien du Grand Cafe, boulevard des Capucines a Paris. Mais cette date celebre ne marque que l'aboutissement d'un long processus d'invention.",
        introHighlight:"<strong>L'idee cle :</strong> Le cinema n'a pas un seul inventeur. Il est le fruit de decennies de recherches sur la decomposition et la restitution du mouvement, menees simultanement dans plusieurs pays.",
        introText2:"Avant les Lumiere, Eadweard Muybridge decompose le galop du cheval (1878), Etienne-Jules Marey invente le chronophotographe, Thomas Edison et William Dickson creent le Kinetoscope (1891). La contribution des Lumiere est d'avoir invente un appareil unique — le <strong>Cinematographe</strong> — qui sert a la fois de camera, de tireuse et de projecteur.",
        courseH3s: [
          {title:"Les precurseurs de l'image en mouvement", paragraphs:["Les premiers dispositifs d'images animees remontent au debut du XIXe siecle. Le <strong>thaumatrope</strong> (1825), le <strong>phenakistiscope</strong> (1832) de Joseph Plateau et le <strong>zootrope</strong> (1834) de William Horner exploitent tous la persistance retinienne pour creer l'illusion du mouvement a partir d'images fixes.", "En 1877, <strong>Emile Reynaud</strong> invente le praxinoscope, puis le Theatre optique (1892), qui permet de projeter des animations narratives devant un public — trois ans avant les Lumiere. Reynaud est ainsi le veritable premier animateur de l'histoire du cinema."]},
          {title:"Les freres Lumiere et la naissance du spectacle", paragraphs:["Auguste (1862-1954) et Louis (1864-1948) Lumiere, fils d'un industriel de la photographie lyonnais, inventent le Cinematographe en 1895. Leur appareil, leger et portable (5 kg contre 250 kg pour le Kinetoscope d'Edison), revolutionne la prise de vue et la projection.", "Leurs premiers films — <em>La Sortie de l'usine Lumiere</em>, <em>L'Arrivee d'un train en gare de La Ciotat</em>, <em>L'Arroseur arrose</em> — durent moins d'une minute et capturent des scenes de la vie quotidienne. Mais leur impact est immense : pour la premiere fois, le public voit des images en mouvement projetees sur grand ecran."]},
          {title:"Georges Melies, l'inventeur du spectacle", paragraphs:["<strong>Georges Melies</strong> (1861-1938), prestidigitateur de metier, comprend immediatement le potentiel narratif et spectaculaire du cinema. Il construit le premier studio de cinema a Montreuil-sous-Bois et invente les <strong>trucages cinematographiques</strong> : arret de camera, surimpression, fondus.", "Son chef-d'oeuvre, <em>Le Voyage dans la Lune</em> (1902), est le premier film de science-fiction de l'histoire. Avec ses decors peints, ses costumes elabores et ses effets speciaux novateurs, Melies pose les bases du cinema comme art de l'illusion et de la narration."]},
          {title:"L'essor mondial du cinema muet", paragraphs:["Dans les annees 1900-1920, le cinema se developpe dans le monde entier. En France, <strong>Charles Pathe</strong> et <strong>Leon Gaumont</strong> creent les premiers empires cinematographiques. Aux Etats-Unis, <strong>D.W. Griffith</strong> invente la grammaire du montage narratif avec <em>Naissance d'une nation</em> (1915), film techniquement revolutionnaire mais moralement problematique par son racisme.", "Le cinema muet atteint sa maturite artistique dans les annees 1920 avec des chefs-d'oeuvre comme <em>Le Cuirasse Potemkine</em> (Eisenstein, 1925), <em>Metropolis</em> (Fritz Lang, 1927) et les comedies de <strong>Charlie Chaplin</strong>, Buster Keaton et Harold Lloyd. Le langage cinematographique — gros plans, montage, mouvements de camera — est desormais pleinement constitue."]}
        ],
        quizQuestions: [
          {q:"En quelle annee a eu lieu la premiere projection publique des freres Lumiere ?", opts:["1888","1895","1900","1903"], ans:1, expl:"La premiere projection publique payante des freres Lumiere a eu lieu le 28 decembre 1895 au Salon indien du Grand Cafe a Paris."},
          {q:"Qui a realise Le Voyage dans la Lune (1902) ?", opts:["Les freres Lumiere","D.W. Griffith","Georges Melies","Charles Pathe"], ans:2, expl:"Georges Melies, prestidigitateur devenu cineaste, a realise Le Voyage dans la Lune en 1902, premier film de science-fiction."},
          {q:"Quel appareil les freres Lumiere ont-ils invente ?", opts:["Le Kinetoscope","Le Cinematographe","Le Phenakistiscope","Le Praxinoscope"], ans:1, expl:"Le Cinematographe, invente en 1895, servait a la fois de camera, de tireuse et de projecteur, pesant seulement 5 kg."},
          {q:"Qui est considere comme le premier animateur de l'histoire ?", opts:["Walt Disney","Emile Reynaud","Georges Melies","Emile Cohl"], ans:1, expl:"Emile Reynaud, avec son Theatre optique (1892), projetait des animations narratives devant un public trois ans avant les Lumiere."},
          {q:"Quel realisateur a invente la grammaire du montage narratif ?", opts:["Eisenstein","Melies","D.W. Griffith","Chaplin"], ans:2, expl:"D.W. Griffith a formalise les techniques fondamentales du montage narratif, notamment dans Naissance d'une nation (1915)."}
        ]
      },
      {
        file:'hollywood.html', title:"Age d'or hollywoodien", time:'45',
        introText:"L'<strong>age d'or d'Hollywood</strong> (environ 1930-1960) correspond a l'ere du systeme des studios, ou cinq grandes compagnies — les <em>Big Five</em> (MGM, Paramount, Warner Bros., 20th Century Fox, RKO) — controlent la production, la distribution et l'exploitation des films aux Etats-Unis et dans le monde.",
        introHighlight:"<strong>Le systeme des studios :</strong> Chaque studio possede ses propres plateaux, ses techniciens, ses scenaristes et ses stars sous contrat exclusif. Ce modele industriel produit une qualite et une quantite de films sans equivalent.",
        introText2:"Cette periode voit l'emergence des grands <strong>genres cinematographiques</strong> : le western, le film noir, la comedie musicale, le melodrame, le film d'aventure. Chaque genre possede ses codes, ses stars et ses metteurs en scene attitres. Le <strong>star-system</strong> transforme les acteurs en icônes mondiales.",
        courseH3s: [
          {title:"Le systeme des studios", paragraphs:["Le studio system repose sur l'<strong>integration verticale</strong> : les studios possedent les moyens de production, les reseaux de distribution et les salles de cinema. Ce monopole leur permet de controler toute la chaîne cinematographique.", "Le <strong>Code Hays</strong> (1934-1968) impose une censure stricte sur le contenu des films : pas de nudite, pas de violence excessive, les criminels doivent toujours etre punis. Ces contraintes poussent les realisateurs a developper un langage visuel subtil pour suggerer ce qu'ils ne peuvent montrer."]},
          {title:"Les grands genres classiques", paragraphs:["Le <strong>western</strong> incarne le mythe fondateur americain. John Ford (<em>La Chevauchee fantastique</em>, 1939) en est le maître inconteste, avec ses paysages de Monument Valley et ses heros solitaires incarnes par John Wayne.", "Le <strong>film noir</strong> (1940-1958) se distingue par son esthetique sombre, ses intrigues complexes et ses personnages ambigus. Billy Wilder (<em>Assurance sur la mort</em>, 1944) et John Huston (<em>Le Faucon maltais</em>, 1941) en sont les figures majeures. Le genre est profondement influence par l'expressionnisme allemand."]},
          {title:"Les grands realisateurs", paragraphs:["<strong>Alfred Hitchcock</strong> (1899-1980) est le maître absolu du suspense. Ses films — <em>Fenetre sur cour</em> (1954), <em>Sueurs froides</em> (1958), <em>Psychose</em> (1960) — explorent les peurs et les obsessions avec une maîtrise technique et narrative inegalee.", "<strong>Orson Welles</strong> revolutionne le cinema avec <em>Citizen Kane</em> (1941), realise a seulement 25 ans. Sa profondeur de champ, ses plongees et contre-plongees, sa narration fragmentee influencent tout le cinema moderne. Billy Wilder, Howard Hawks et John Huston comptent parmi les autres grands noms de cette ere."]}
        ],
        quizQuestions: [
          {q:"Quels sont les 'Big Five' du systeme des studios hollywoodiens ?", opts:["Disney, Universal, Columbia, Fox, Warner","MGM, Paramount, Warner Bros., 20th Century Fox, RKO","MGM, Disney, Universal, Columbia, Paramount","Warner, Fox, RKO, United Artists, Universal"], ans:1, expl:"Les Big Five qui dominaient Hollywood etaient MGM, Paramount, Warner Bros., 20th Century Fox et RKO."},
          {q:"Quel realisateur est le maître du western classique ?", opts:["Alfred Hitchcock","Billy Wilder","John Ford","Howard Hawks"], ans:2, expl:"John Ford est le maître inconteste du western, avec des films comme La Chevauchee fantastique (1939) et La Prisonniere du desert (1956)."},
          {q:"En quelle annee Orson Welles a-t-il realise Citizen Kane ?", opts:["1939","1941","1945","1948"], ans:1, expl:"Citizen Kane est sorti en 1941, realise par Orson Welles alors age de seulement 25 ans."},
          {q:"Qu'est-ce que le Code Hays ?", opts:["Un systeme de notation des films","Un code de censure morale","Une methode de montage","Un contrat type pour acteurs"], ans:1, expl:"Le Code Hays (1934-1968) etait un code de censure morale imposant des restrictions strictes sur le contenu des films hollywoodiens."},
          {q:"Quel genre cinematographique est influence par l'expressionnisme allemand ?", opts:["La comedie musicale","Le western","Le film noir","Le melodrame"], ans:2, expl:"Le film noir est profondement influence par l'esthetique de l'expressionnisme allemand : jeux d'ombres, angles obliques et atmosphere oppressante."}
        ]
      },
      {
        file:'nouvelle-vague.html', title:'La Nouvelle Vague', time:'40',
        introText:"La <strong>Nouvelle Vague</strong> est le mouvement cinematographique le plus influent de la seconde moitie du XXe siecle. Ne en France a la fin des annees 1950, il revolutionne la facon de faire et de penser le cinema en affirmant la figure du <strong>realisateur-auteur</strong>.",
        introHighlight:"<strong>La politique des auteurs :</strong> Theorisee dans les Cahiers du cinema par Francois Truffaut (1954), elle affirme que le realisateur est le veritable auteur du film, au meme titre qu'un ecrivain ou un peintre.",
        introText2:"Les cineastes de la Nouvelle Vague rejettent le <strong>cinema de qualite francaise</strong> qu'ils jugent academique et litteraire. Ils privilegient le tournage en decors reels, la lumiere naturelle, les acteurs peu connus, le montage audacieux et l'improvisation. Leurs films, tournes avec des budgets reduits, renouvellent completement le langage cinematographique.",
        courseH3s: [
          {title:"Les origines : les Cahiers du cinema", paragraphs:["La Nouvelle Vague naît dans les pages des <em>Cahiers du cinema</em>, revue fondee par Andre Bazin en 1951. De jeunes critiques — Truffaut, Godard, Chabrol, Rohmer, Rivette — y developpent la <strong>politique des auteurs</strong>, rehabilitant des cineastes hollywoodiens (Hitchcock, Hawks, Ford) et affirmant que le style visuel d'un realisateur constitue sa signature artistique.", "L'article fondateur de Truffaut, <em>Une certaine tendance du cinema francais</em> (1954), attaque violemment le cinema francais traditionnel et appelle a un renouveau radical."]},
          {title:"Les films fondateurs", paragraphs:["<em>Les 400 coups</em> de <strong>Francois Truffaut</strong> (1959) et <em>A bout de souffle</em> de <strong>Jean-Luc Godard</strong> (1960) sont les deux films fondateurs du mouvement. Le premier raconte l'enfance difficile d'Antoine Doinel avec une tendresse et une liberte de ton inedites. Le second, avec ses <strong>jump cuts</strong> audacieux et sa nonchalance narrative, reinvente la grammaire cinematographique.", "<strong>Agnes Varda</strong>, souvent consideree comme la « grand-mere de la Nouvelle Vague », realise <em>Cleo de 5 a 7</em> (1962), film qui suit une chanteuse pendant deux heures en temps reel dans les rues de Paris."]},
          {title:"L'heritage mondial", paragraphs:["La Nouvelle Vague influence directement le <strong>Nouvel Hollywood</strong> (Coppola, Scorsese, Spielberg), le cinema independant americain, le cinema d'auteur mondial et les mouvements de renouveau dans de nombreux pays. Ses innovations formelles — camera a l'epaule, montage decontinu, adresse au spectateur — sont devenues le vocabulaire courant du cinema contemporain.", "L'idee que le cinema est un art aussi noble que la litterature ou la peinture, et que le realisateur en est l'auteur, reste l'heritage le plus durable de la Nouvelle Vague."]}
        ],
        quizQuestions: [
          {q:"Qui a ecrit 'Une certaine tendance du cinema francais' en 1954 ?", opts:["Jean-Luc Godard","Andre Bazin","Francois Truffaut","Claude Chabrol"], ans:2, expl:"Francois Truffaut a publie cet article fondateur dans les Cahiers du cinema en 1954, attaquant le cinema francais traditionnel."},
          {q:"Quel est le film fondateur de Godard dans la Nouvelle Vague ?", opts:["Les 400 coups","Le Mepris","A bout de souffle","Pierrot le Fou"], ans:2, expl:"A bout de souffle (1960) de Jean-Luc Godard, avec ses jump cuts et sa liberte narrative, est considere comme l'un des films fondateurs de la Nouvelle Vague."},
          {q:"Qu'est-ce que la 'politique des auteurs' ?", opts:["Une loi sur le droit d'auteur","Le realisateur comme auteur du film","Une politique culturelle d'Etat","Un syndicat de scenaristes"], ans:1, expl:"La politique des auteurs affirme que le realisateur est le veritable auteur du film, imprimant sa vision personnelle a travers son style visuel."},
          {q:"Qui est considere comme la 'grand-mere de la Nouvelle Vague' ?", opts:["Marguerite Duras","Agnes Varda","Anna Karina","Jeanne Moreau"], ans:1, expl:"Agnes Varda, avec des films comme Cleo de 5 a 7 (1962), est souvent consideree comme une precurseur et figure majeure de la Nouvelle Vague."},
          {q:"Quelle revue a ete le berceau intellectuel de la Nouvelle Vague ?", opts:["Positif","Les Cahiers du cinema","Premiere","Telerama"], ans:1, expl:"Les Cahiers du cinema, fondes par Andre Bazin en 1951, ont ete le berceau intellectuel de la Nouvelle Vague."}
        ]
      },
      {
        file:'cinema-mondial.html', title:'Cinema mondial', time:'45',
        introText:"Le cinema ne se reduit pas a Hollywood et a la France. Des les annees 1940, des cineastes du monde entier creent des oeuvres majeures qui enrichissent le <strong>langage cinematographique</strong> de traditions culturelles et de sensibilites narratives differentes.",
        introHighlight:"<strong>L'universalite du cinema :</strong> Le cinema est un art universel dont les plus grandes oeuvres transcendent les barrieres linguistiques et culturelles. Kurosawa, Bergman, Fellini, Satyajit Ray ont touche des millions de spectateurs partout dans le monde.",
        introText2:"Le cinema mondial se deploie en vagues successives : le <strong>neorealisme italien</strong> (1943-1955), le cinema japonais de l'apres-guerre, le cinema scandinave de Bergman, la nouvelle vague tcheque, le cinema bresilien du Cinema Novo, puis plus recemment les cinemas coreen, iranien et africain.",
        courseH3s: [
          {title:"Le cinema japonais", paragraphs:["<strong>Akira Kurosawa</strong> (1910-1998) est le cineaste japonais le plus celebre en Occident. <em>Rashomon</em> (1950) revolutionne la narration en montrant un meme evenement de quatre points de vue contradictoires. <em>Les Sept Samourais</em> (1954) influence directement le western hollywoodien.", "<strong>Yasujiro Ozu</strong> (1903-1963) developpe un style radicalement different : camera fixe a hauteur de tatami, plans vides, tempo lent. Ses films sur la famille japonaise (<em>Voyage a Tokyo</em>, 1953) sont des meditations sur le temps et la perte."]},
          {title:"Le cinema europeen", paragraphs:["<strong>Ingmar Bergman</strong> (1918-2007), cineaste suedois, explore les grandes questions existentielles — la mort, la foi, l'amour, la solitude — dans des films d'une intensite rare : <em>Le Septieme Sceau</em> (1957), <em>Persona</em> (1966), <em>Cris et chuchotements</em> (1972).", "<strong>Federico Fellini</strong> (1920-1993) incarne le genie du cinema italien. <em>La Dolce Vita</em> (1960) et <em>8 1/2</em> (1963) melent realite et fantasme dans un tourbillon visuel qui a invente le mot « fellinien ». Le neorealisme italien, avec De Sica et Rossellini, avait ouvert la voie des les annees 1940."]},
          {title:"Les nouvelles vagues mondiales", paragraphs:["Le cinema contemporain est enrichi par des cinematographies nationales vibrantes. Le <strong>cinema coreen</strong> (Bong Joon-ho, Park Chan-wook), le <strong>cinema iranien</strong> (Abbas Kiarostami, Asghar Farhadi) et le <strong>cinema africain</strong> (Ousmane Sembene, Abderrahmane Sissako) apportent des regards et des recits irreductiblement originaux.", "L'emergence du cinema coreen illustre parfaitement cette mondialisation : <em>Parasite</em> de Bong Joon-ho (2019) est le premier film non anglophone a remporter l'Oscar du meilleur film, consacrant l'excellence d'une cinematographie longtemps meconnue en Occident."]}
        ],
        quizQuestions: [
          {q:"Quel film de Kurosawa montre un evenement sous quatre points de vue ?", opts:["Les Sept Samourais","Rashomon","Yojimbo","Ran"], ans:1, expl:"Rashomon (1950) d'Akira Kurosawa revolutionne la narration en presentant un meme evenement selon quatre perspectives contradictoires."},
          {q:"Quel cineaste suedois a realise Le Septieme Sceau ?", opts:["Carl Dreyer","Lars von Trier","Ingmar Bergman","Victor Sjostrom"], ans:2, expl:"Ingmar Bergman a realise Le Septieme Sceau (1957), film emblematique ou un chevalier joue aux echecs avec la Mort."},
          {q:"Quel mouvement cinematographique italien utilise des decors reels et des acteurs non professionnels ?", opts:["Le Futurisme","Le Neorealisme","L'Expressionnisme","La Commedia all'italiana"], ans:1, expl:"Le neorealisme italien (1943-1955) se caracterise par le tournage en decors reels, l'utilisation d'acteurs non professionnels et les sujets sociaux."},
          {q:"Quel realisateur japonais est connu pour ses plans a hauteur de tatami ?", opts:["Kurosawa","Mizoguchi","Ozu","Kitano"], ans:2, expl:"Yasujiro Ozu est celebre pour sa camera fixe placee a hauteur de tatami, creant une esthetique contemplative unique."},
          {q:"Quel realisateur italien a donne son nom a l'adjectif 'fellinien' ?", opts:["Visconti","De Sica","Antonioni","Fellini"], ans:3, expl:"Federico Fellini, par son style onirique et baroque, a inspire l'adjectif 'fellinien' pour decrire un univers entre reve et realite."}
        ]
      },
      {
        file:'contemporain.html', title:'Cinema contemporain', time:'40',
        introText:"Le <strong>cinema contemporain</strong> (des annees 1990 a aujourd'hui) est marque par la revolution numerique, la mondialisation des productions et l'emergence de nouvelles formes de diffusion. Le passage de la pellicule au numerique transforme radicalement la creation, la distribution et la consommation des films.",
        introHighlight:"<strong>La revolution numerique :</strong> Le numerique democratise la creation cinematographique en reduisant drastiquement les coûts de production. N'importe qui disposant d'une camera et d'un ordinateur peut desormais realiser un film de qualite professionnelle.",
        introText2:"L'avenement des <strong>plateformes de streaming</strong> (Netflix, Amazon, Disney+) bouleverse l'industrie. La frontiere entre cinema et television s'estompe avec des series au budget et a l'ambition cinematographiques. Les festivals internationaux (Cannes, Venise, Berlin) restent cependant les arbitres du cinema d'auteur mondial.",
        courseH3s: [
          {title:"La revolution numerique", paragraphs:["Le passage au <strong>numerique</strong> commence dans les annees 1990 avec les effets speciaux (<em>Jurassic Park</em>, 1993 ; <em>Toy Story</em>, 1995) et s'acheve dans les annees 2010 avec l'abandon quasi total de la pellicule. Le numerique offre une liberte creative sans precedent : tournage en basse lumiere, post-production illimitee, distribution instantanee.", "Des realisateurs comme <strong>David Fincher</strong> (<em>Zodiac</em>, 2007), <strong>Steven Soderbergh</strong> et <strong>Michael Mann</strong> adoptent tres tôt le numerique, tandis que d'autres comme <strong>Christopher Nolan</strong> et Quentin Tarantino defendent obstinement la pellicule comme medium artistique superieur."]},
          {title:"Les nouvelles voix", paragraphs:["Le cinema contemporain se distingue par la diversification des voix et des recits. Des cineastes comme <strong>Celine Sciamma</strong> (<em>Portrait de la jeune fille en feu</em>, 2019), <strong>Barry Jenkins</strong> (<em>Moonlight</em>, 2016) et <strong>Chloe Zhao</strong> (<em>Nomadland</em>, 2020) apportent des perspectives jusqu'alors marginalisees.", "<strong>Bong Joon-ho</strong> et le cinema coreen illustrent la mondialisation du cinema d'auteur : <em>Parasite</em> (2019) transcende les barrieres culturelles et linguistiques pour devenir un phenomene mondial, demontrant que le cinema n'a pas de frontiere."]},
          {title:"L'ere du streaming", paragraphs:["L'apparition de <strong>Netflix</strong>, Amazon Prime Video et autres plateformes transforme la distribution cinematographique. Des realisateurs majeurs comme Martin Scorsese (<em>The Irishman</em>, 2019) et Alfonso Cuaron (<em>Roma</em>, 2018) tournent pour ces plateformes, posant la question fondamentale : qu'est-ce qu'un film quand il n'est plus projete en salle ?", "Cette evolution s'accompagne d'un âge d'or des <strong>series televisees</strong>, qui adoptent des formats et des ambitions cinematographiques. La frontiere entre cinema et television, autrefois etanche, est devenue poreuse."]}
        ],
        quizQuestions: [
          {q:"Quel film de 1993 a marque le debut de la revolution des effets numeriques ?", opts:["Terminator 2","Jurassic Park","The Matrix","Avatar"], ans:1, expl:"Jurassic Park (1993) de Steven Spielberg a revolutionne les effets speciaux avec ses dinosaures en images de synthese."},
          {q:"Quel realisateur defend obstinement la pellicule a l'ere numerique ?", opts:["David Fincher","Steven Soderbergh","Christopher Nolan","Danny Boyle"], ans:2, expl:"Christopher Nolan est l'un des plus fervents defenseurs de la pellicule, tournant ses films en IMAX et 70mm."},
          {q:"Quel film de Martin Scorsese a ete produit par Netflix ?", opts:["Les Affranchis","The Wolf of Wall Street","The Irishman","Gangs of New York"], ans:2, expl:"The Irishman (2019) de Scorsese a ete produit et distribue par Netflix, marquant l'entree de la plateforme dans le cinema d'auteur."},
          {q:"Quelle realisatrice a signe Portrait de la jeune fille en feu ?", opts:["Agnes Varda","Celine Sciamma","Claire Denis","Julia Ducournau"], ans:1, expl:"Celine Sciamma a realise Portrait de la jeune fille en feu (2019), film acclame pour sa mise en scene et sa delicatesse narrative."},
          {q:"En quelle annee Parasite a-t-il remporte la Palme d'or ?", opts:["2017","2018","2019","2020"], ans:2, expl:"Parasite de Bong Joon-ho a remporte la Palme d'or a Cannes en 2019 puis l'Oscar du meilleur film en 2020."}
        ]
      }
    ]
  },
  realisation: {
    hubTitle: 'Realisation', hubFile: 'realisation.html',
    siblings: [
      {name:"Ecriture de scenario", file:'scenario.html'},
      {name:'Mise en scene', file:'mise-en-scene.html'},
      {name:"Direction d'acteurs", file:'direction-acteurs.html'},
      {name:'Cinematographie', file:'cinematographie.html'},
      {name:'Son et musique de film', file:'son-musique.html'}
    ],
    courses: [
      {file:'scenario.html', title:'Ecriture de scenario', time:'35',
        introText:"Le scenario est le <strong>fondement</strong> de tout film. C'est le document ecrit qui raconte l'histoire, decrit les personnages, les dialogues et les actions. Sans un bon scenario, meme le meilleur realisateur et les meilleurs acteurs ne peuvent produire un bon film.",
        introHighlight:"<strong>La structure en trois actes :</strong> La plupart des films suivent une structure en trois actes : l'exposition (mise en place), la confrontation (developpement du conflit) et la resolution (denouement). Cette structure, heritee d'Aristote, reste le modele dominant.",
        introText2:"L'ecriture de scenario est un metier a part entiere, avec ses regles de formatage strictes, ses techniques narratives specifiques et ses outils (arcs de personnages, scenes de confrontation, retournements). Les grands scenaristes — Billy Wilder, Charlie Kaufman, Aaron Sorkin — sont des architectes du recit.",
        courseH3s:[
          {title:"La structure narrative", paragraphs:["La <strong>structure en trois actes</strong> divise le recit en exposition (25%), confrontation (50%) et resolution (25%). L'acte I pose le monde, les personnages et le conflit. L'acte II developpe les obstacles et les retournements. L'acte III resout le conflit central.", "Le <strong>point de non-retour</strong> (ou turning point) est le moment ou le protagoniste ne peut plus revenir en arriere. Dans <em>Star Wars</em>, c'est la destruction de la ferme de Luke. Dans <em>Le Parrain</em>, c'est le meurtre de Sollozzo par Michael Corleone."]},
          {title:"La creation de personnages", paragraphs:["Un personnage reussi possede un <strong>arc narratif</strong> : il evolue entre le debut et la fin du film. Walter White dans <em>Breaking Bad</em> passe de professeur timide a baron de la drogue. Cette transformation est le moteur du recit.", "La technique du <strong>show, don't tell</strong> (montrer, ne pas dire) est fondamentale : le comportement d'un personnage revele son caractere plus efficacement qu'un dialogue explicatif. Les meilleurs scenaristes creent des personnages dont les actes contredisent parfois les paroles."]},
          {title:"Les dialogues cinematographiques", paragraphs:["Les dialogues au cinema sont fondamentalement differents des dialogues theatraux. Ils doivent etre <strong>naturels mais significatifs</strong>, chaque replique faisant avancer l'action ou revelant le personnage. Le sous-texte — ce que les personnages veulent dire sans le dire — est souvent plus important que le texte.", "Les meilleurs dialoguistes — <strong>Aaron Sorkin</strong> (The Social Network), <strong>Quentin Tarantino</strong> (Pulp Fiction), <strong>Nora Ephron</strong> (Quand Harry rencontre Sally) — creent des echanges memorables qui semblent spontanes mais sont minutieusement construits."]}
        ],
        quizQuestions:[
          {q:"Quelle structure narrative domine le cinema classique ?", opts:["Structure en 5 actes","Structure en 3 actes","Structure circulaire","Structure episodique"], ans:1, expl:"La structure en trois actes (exposition, confrontation, resolution) est le modele dominant du cinema narratif classique."},
          {q:"Qu'est-ce qu'un 'arc narratif' de personnage ?", opts:["Le decor ou evolue le personnage","L'evolution du personnage au fil du recit","Le trajet physique du personnage","La voix du personnage"], ans:1, expl:"L'arc narratif designe l'evolution psychologique ou morale d'un personnage entre le debut et la fin du film."},
          {q:"Que signifie 'show, don't tell' ?", opts:["Montrer plutot qu'expliquer","Utiliser des sous-titres","Filmer en plan large","Eviter les dialogues"], ans:0, expl:"'Show, don't tell' signifie montrer les emotions et le caractere a travers les actions plutot que de les expliquer par les dialogues."},
          {q:"Quel scenariste est celebre pour ses dialogues rapides et ciselés ?", opts:["Charlie Kaufman","Aaron Sorkin","Diablo Cody","Quentin Tarantino"], ans:1, expl:"Aaron Sorkin est celebre pour ses dialogues rapides, intelligents et rythmes, dans des films comme The Social Network et Steve Jobs."},
          {q:"Qu'est-ce que le sous-texte dans un dialogue ?", opts:["Les sous-titres","Ce que le personnage veut dire sans le dire","Les didascalies","Les pensees en voix off"], ans:1, expl:"Le sous-texte est le sens cache derriere les mots, ce que le personnage pense ou ressent sans l'exprimer directement."}
        ]
      },
      {file:'mise-en-scene.html', title:'Mise en scene', time:'40',
        introText:"La <strong>mise en scene</strong> est l'art de transformer un scenario ecrit en images vivantes. Elle englobe le placement des acteurs, le choix des decors, le decoupage en plans, les mouvements de camera et la composition de chaque image.",
        introHighlight:"<strong>Le decoupage technique :</strong> Avant le tournage, le realisateur prepare un decoupage — la traduction du scenario en plans numerotes, avec pour chaque plan l'echelle, l'angle, le mouvement de camera et les indications de jeu.",
        introText2:"La mise en scene distingue le grand cinema du cinema ordinaire. Deux realisateurs filmant le meme scenario produiront des films radicalement differents selon leurs choix de cadrage, de rythme et de direction d'acteurs.",
        courseH3s:[
          {title:"L'echelle des plans", paragraphs:["L'<strong>echelle des plans</strong> est le vocabulaire de base du cinema : plan general (PG), plan d'ensemble (PE), plan moyen (PM), plan americain (PA), plan rapproche (PR), gros plan (GP), tres gros plan (TGP). Chaque valeur de plan cree un effet emotionnel et narratif different.", "Le <strong>gros plan</strong> revele l'emotion intime d'un personnage. Le <strong>plan general</strong> situe l'action dans un espace vaste. Le choix de l'echelle est l'une des decisions les plus fondamentales du realisateur."]},
          {title:"Les mouvements de camera", paragraphs:["Les mouvements de camera — <strong>panoramique</strong> (rotation horizontale ou verticale), <strong>travelling</strong> (deplacement de la camera sur rails ou dolly), <strong>steadicam</strong> (stabilisateur porte), <strong>grue</strong> (mouvement vertical) — ajoutent une dynamique a l'image.", "Chaque mouvement a un sens narratif : un travelling avant cree l'immersion, un zoom arriere l'eloignement ou la revelation. Stanley Kubrick et ses couloirs de <em>Shining</em> filmes en steadicam sont devenus une reference absolue."]},
          {title:"La composition de l'image", paragraphs:["La <strong>composition</strong> cinematographique herite de la peinture : regle des tiers, lignes directrices, symetrie, cadre dans le cadre. Wes Anderson est celebre pour ses compositions symetriques obsessionnelles. Denis Villeneuve privilegie les compositions monumentales qui ecrasent les personnages.", "La <strong>profondeur de champ</strong> est un outil de composition majeur : une grande profondeur (tout est net) permet de raconter plusieurs histoires dans le meme plan, comme Orson Welles le fait magistralement dans Citizen Kane."]}
        ],
        quizQuestions:[
          {q:"Que designe le 'plan americain' ?", opts:["Un plan cadre a mi-cuisse","Un plan typiquement hollywoodien","Un plan large sur un paysage","Un plan en contre-plongee"], ans:0, expl:"Le plan americain cadre le personnage a mi-cuisse. Son nom vient du western americain ou il permettait de voir le colt a la ceinture."},
          {q:"Qu'est-ce qu'un travelling ?", opts:["Un rotation de la camera sur son axe","Un deplacement physique de la camera","Un zoom optique","Un changement de mise au point"], ans:1, expl:"Le travelling est un deplacement physique de la camera sur rails, dolly ou vehicule, creant un mouvement fluide dans l'espace."},
          {q:"Quel realisateur est celebre pour ses compositions symetriques ?", opts:["Wes Anderson","Christopher Nolan","David Fincher","Denis Villeneuve"], ans:0, expl:"Wes Anderson est connu pour ses compositions obsessionnellement symetriques, devenues sa signature visuelle."},
          {q:"Qu'est-ce que le steadicam ?", opts:["Un trepied fixe","Un stabilisateur de camera porte","Un logiciel de montage","Un eclairage mobile"], ans:1, expl:"Le Steadicam est un systeme de stabilisation qui permet de filmer en mouvement avec une fluidite comparable au travelling."},
          {q:"Quel film est celebre pour sa profondeur de champ revolutionnaire ?", opts:["Psychose","Citizen Kane","Casablanca","Le Magicien d'Oz"], ans:1, expl:"Citizen Kane (1941) d'Orson Welles est celebre pour son utilisation revolutionnaire de la profondeur de champ."}
        ]
      },
      {file:'direction-acteurs.html', title:"Direction d'acteurs", time:'35',
        introText:"La <strong>direction d'acteurs</strong> est l'une des competences les plus cruciales et les moins enseignables du metier de realisateur. Elle consiste a guider les comediens vers la justesse emotionnelle que le film exige.",
        introHighlight:"<strong>Le paradoxe de l'acteur :</strong> Un acteur doit etre a la fois spontane et controle, naturel et precis. Le realisateur doit creer les conditions qui permettent cette contradiction feconde.",
        introText2:"Les methodes de direction varient enormement d'un realisateur a l'autre. Certains, comme <strong>Kubrick</strong>, multiplient les prises (parfois plus de 70) jusqu'a obtenir exactement ce qu'ils veulent. D'autres, comme <strong>Clint Eastwood</strong>, preferent la premiere ou la deuxieme prise pour capturer la spontaneite.",
        courseH3s:[
          {title:"Les grandes methodes de jeu", paragraphs:["La <strong>Methode</strong> (Method Acting), developpee par Lee Strasberg a l'Actors Studio de New York, demande a l'acteur de puiser dans ses propres emotions et souvenirs pour nourrir son personnage. Marlon Brando, Robert De Niro et Daniel Day-Lewis en sont les plus celebres adeptes.", "L'approche <strong>brechtienne</strong> propose l'inverse : la distanciation. L'acteur ne s'identifie pas a son personnage mais le montre, le commente, le met a distance. Cette approche influence des cineastes comme Jean-Luc Godard et Lars von Trier."]},
          {title:"La relation realisateur-acteur", paragraphs:["Les grands <strong>tandems</strong> realisateur-acteur produisent souvent les meilleurs films : Scorsese et De Niro (puis DiCaprio), Kurosawa et Mifune, Bergman et Ullmann, Truffaut et Leaud. La confiance mutuelle permet d'atteindre une profondeur emotionnelle impossible autrement.", "Le realisateur doit adapter sa methode a chaque acteur. Certains comediens ont besoin de liberte et d'improvisation, d'autres de precision et de repetition. La sensibilite du metteur en scene a ces differences est un talent fondamental."]},
          {title:"Le casting et la preparation", paragraphs:["Le <strong>casting</strong> est la decision la plus importante du film. Comme le dit Sidney Lumet : « Le casting, c'est 90% du travail de mise en scene. » Un acteur mal choisi peut ruiner le meilleur scenario. Un acteur parfait peut transcender un scenario mediocre.", "La <strong>preparation</strong> varie selon les realisateurs : certains organisent des semaines de repetitions (Mike Leigh), d'autres refusent toute repetition pour preserver la spontaneite (Terrence Malick). Le travail de table — lecture et discussion du scenario avec les acteurs — est une etape classique."]}
        ],
        quizQuestions:[
          {q:"Qu'est-ce que la Method Acting ?", opts:["Une technique de cascades","Le jeu fonde sur les emotions personnelles","Le mime cinematographique","La doublure d'acteurs"], ans:1, expl:"La Method Acting, developpee par Lee Strasberg, demande a l'acteur de puiser dans ses propres emotions pour incarner son personnage."},
          {q:"Quel acteur est l'un des plus celebres adeptes de la Methode ?", opts:["Tom Hanks","Daniel Day-Lewis","Tom Cruise","Harrison Ford"], ans:1, expl:"Daniel Day-Lewis est celebre pour sa pratique extreme de la Methode, restant dans son personnage pendant des mois entiers."},
          {q:"Quelle est l'approche brechtienne du jeu d'acteur ?", opts:["L'identification totale","La distanciation critique","L'improvisation libre","Le mime silencieux"], ans:1, expl:"L'approche brechtienne propose la distanciation : l'acteur montre et commente son personnage plutot que de s'y identifier."},
          {q:"Quel realisateur est celebre pour multiplier les prises ?", opts:["Clint Eastwood","Stanley Kubrick","Steven Spielberg","Woody Allen"], ans:1, expl:"Stanley Kubrick etait celebre pour multiplier les prises (parfois plus de 70) jusqu'a obtenir la performance exacte qu'il recherchait."},
          {q:"Selon Sidney Lumet, le casting represente quel pourcentage du travail ?", opts:["50%","70%","90%","100%"], ans:2, expl:"Sidney Lumet affirmait que le casting represente 90% du travail de mise en scene."}
        ]
      },
      {file:'cinematographie.html', title:'Cinematographie', time:'45',
        introText:"La <strong>cinematographie</strong> (ou direction de la photographie) est l'art de creer l'image du film. Le directeur de la photographie (DP ou chef operateur) est responsable de la lumiere, du cadrage, du choix des objectifs et de l'atmosphere visuelle de chaque scene.",
        introHighlight:"<strong>La lumiere est le materiau du cinema.</strong> Sans lumiere, pas d'image. Le DP sculpte la lumiere comme un peintre utilise ses couleurs, creant l'ambiance emotionnelle de chaque scene.",
        introText2:"Les grands directeurs de la photographie — <strong>Roger Deakins</strong>, <strong>Emmanuel Lubezki</strong>, <strong>Robert Richardson</strong> — sont des artistes a part entiere dont le travail contribue autant au film que celui du realisateur.",
        courseH3s:[
          {title:"La lumiere au cinema", paragraphs:["La lumiere cinematographique se divise en categories : lumiere <strong>naturelle</strong> (soleil, ciel couvert) et <strong>artificielle</strong> (projecteurs, practicals). Le choix entre les deux depend de l'ambiance recherchee : la lumiere naturelle cree du realisme, la lumiere artificielle permet un controle total.", "L'<strong>eclairage trois points</strong> (key light, fill light, back light) est le schema de base : une lumiere principale modele le sujet, une lumiere de remplissage attenue les ombres, un contre-jour detoure le sujet du fond. Les variations infinies de ce schema creent des ambiances radicalement differentes."]},
          {title:"Les objectifs et le cadrage", paragraphs:["Le choix de l'<strong>objectif</strong> determine la perspective de l'image. Un grand-angle (courte focale) deforme legerement l'espace et cree une sensation d'immersion. Un teleobjectif (longue focale) compresse les distances et isole le sujet de son environnement.", "Le <strong>ratio d'aspect</strong> (format de l'image) est un choix expressif : le 1:1.85 (standard americain), le 1:2.35 (CinemaScope, format large) ou le 1:1.33 (format classique, carre) creent des compositions et des sensibilites differentes."]},
          {title:"Les grands directeurs de la photographie", paragraphs:["<strong>Roger Deakins</strong> est considere comme l'un des plus grands DP vivants. Son travail avec les freres Coen (<em>No Country for Old Men</em>) et Denis Villeneuve (<em>Blade Runner 2049</em>) se distingue par une lumiere naturelle sublimee et une composition impeccable.", "<strong>Emmanuel Lubezki</strong> a revolutionne la cinematographie avec ses longs plans-sequences en lumiere naturelle dans <em>The Revenant</em> (2015) et <em>Gravity</em> (2013). Sa collaboration avec Terrence Malick produit des images d'une beaute quasi picturale."]}
        ],
        quizQuestions:[
          {q:"Qu'est-ce que l'eclairage trois points ?", opts:["Un triangle de cameras","Key light, fill light, back light","Trois projecteurs identiques","Un eclairage en trois phases"], ans:1, expl:"L'eclairage trois points utilise une lumiere principale (key), une lumiere de remplissage (fill) et un contre-jour (back light)."},
          {q:"Quel effet produit un grand-angle ?", opts:["Il compresse les distances","Il cree une immersion et deforme legerement","Il isole le sujet","Il floute l'arriere-plan"], ans:1, expl:"Un grand-angle (courte focale) cree une sensation d'immersion et deforme legerement la perspective spatiale."},
          {q:"Quel directeur de la photographie a travaille sur Blade Runner 2049 ?", opts:["Emmanuel Lubezki","Janusz Kaminski","Roger Deakins","Robert Richardson"], ans:2, expl:"Roger Deakins a signe la photographie de Blade Runner 2049, pour laquelle il a remporte l'Oscar de la meilleure photographie."},
          {q:"Qu'est-ce que le ratio 2.35:1 ?", opts:["Le format standard TV","Le CinemaScope (format large)","Le format carre classique","Le format IMAX"], ans:1, expl:"Le ratio 2.35:1 correspond au CinemaScope, un format panoramique large utilise pour les films a grande echelle visuelle."},
          {q:"Quel DP est celebre pour ses plans-sequences en lumiere naturelle ?", opts:["Roger Deakins","Emmanuel Lubezki","Gordon Willis","Vittorio Storaro"], ans:1, expl:"Emmanuel Lubezki est celebre pour ses longs plans-sequences filmes en lumiere naturelle, notamment dans The Revenant et Gravity."}
        ]
      },
      {file:'son-musique.html', title:'Son et musique de film', time:'35',
        introText:"Le <strong>son</strong> represente la moitie de l'experience cinematographique. La conception sonore et la musique de film contribuent autant que l'image a creer l'emotion, le suspense, la peur ou la joie chez le spectateur.",
        introHighlight:"<strong>Le son invisible :</strong> Paradoxalement, le meilleur travail sonore est celui qu'on ne remarque pas consciemment. Le son immerge le spectateur dans l'univers du film sans qu'il en soit pleinement conscient.",
        introText2:"La creation sonore d'un film comprend plusieurs couches : les <strong>dialogues</strong>, les <strong>bruitages</strong> (effets sonores recrees en studio), les <strong>ambiances</strong> (fond sonore continu) et la <strong>musique</strong> (originale ou preexistante). Chaque couche est concue separement puis assemblee lors du mixage final.",
        courseH3s:[
          {title:"La conception sonore", paragraphs:["Le <strong>sound design</strong> consiste a creer l'univers sonore du film. Walter Murch, pionnier du sound design pour Coppola et Lucas, a invente le metier avec <em>Apocalypse Now</em> (1979), dont l'helicoptere au debut du film utilise des sons superposes en plus de 70 couches.", "Le <strong>bruitage</strong> (Foley) est l'art de recreer les sons du quotidien en studio : pas, vetements, objets. Un bruiteur reproduit chaque son en synchronisation avec l'image, ajoutant une texture sonore realiste que le son direct ne peut pas toujours capter."]},
          {title:"La musique de film", paragraphs:["La musique de film a ses grands compositeurs : <strong>John Williams</strong> (Star Wars, Indiana Jones, Schindler's List), <strong>Ennio Morricone</strong> (Le Bon, la Brute et le Truand, Cinema Paradiso), <strong>Hans Zimmer</strong> (Inception, Interstellar), <strong>Bernard Herrmann</strong> (Psychose, Sueurs froides).", "La musique peut etre <strong>diegetique</strong> (audible par les personnages, comme une radio dans la scene) ou <strong>extra-diegetique</strong> (ajoutee pour le spectateur, comme une bande originale orchestrale). Le choix entre les deux cree des effets radicalement differents."]},
          {title:"Le mixage et la spatialisation", paragraphs:["Le <strong>mixage</strong> est l'etape finale : equilibrer dialogues, bruitages, ambiances et musique dans un ensemble coherent. Un bon mixage rend chaque element audible au bon moment, guidant l'attention du spectateur par le son aussi bien que par l'image.", "La <strong>spatialisation</strong> (son surround, Dolby Atmos) place les sons dans un espace tridimensionnel. Le spectateur entend les helicopteres au-dessus de sa tete, les voitures defiler de gauche a droite, les murmures venir de derriere lui."]}
        ],
        quizQuestions:[
          {q:"Qui est le pionnier du sound design cinematographique ?", opts:["John Williams","Ben Burtt","Walter Murch","Gary Rydstrom"], ans:2, expl:"Walter Murch a invente le concept de sound design pour Apocalypse Now (1979), creant un univers sonore d'une complexite inedite."},
          {q:"Qu'est-ce que le bruitage (Foley) ?", opts:["La musique de film","La recreation de sons en studio","L'enregistrement sur le plateau","Le doublage des voix"], ans:1, expl:"Le bruitage Foley est l'art de recreer les sons quotidiens (pas, vetements, objets) en studio, en synchronisation avec l'image."},
          {q:"Quel compositeur a cree la musique de Star Wars ?", opts:["Hans Zimmer","Ennio Morricone","John Williams","Howard Shore"], ans:2, expl:"John Williams a compose la musique de Star Wars, l'une des bandes originales les plus celebres et reconnaissables de l'histoire du cinema."},
          {q:"Qu'est-ce qu'un son diegetique ?", opts:["Un son ajoute en post-production","Un son audible par les personnages","Un son de musique orchestrale","Un son inaudible"], ans:1, expl:"Un son diegetique fait partie de l'univers du film : il est audible par les personnages (une radio, un klaxon, une conversation)."},
          {q:"Qu'est-ce que le Dolby Atmos ?", opts:["Un type de camera","Un format de pellicule","Un systeme de spatialisation sonore","Un logiciel de montage"], ans:2, expl:"Le Dolby Atmos est un systeme de spatialisation sonore qui place les sons dans un espace tridimensionnel autour du spectateur."}
        ]
      }
    ]
  },
  montage: {
    hubTitle: 'Montage et post-production', hubFile: 'montage.html',
    siblings: [
      {name:'Principes du montage', file:'principes.html'},
      {name:'Montage narratif', file:'narratif.html'},
      {name:'Effets visuels', file:'effets-visuels.html'},
      {name:'Etalonnage', file:'etalonnage.html'},
      {name:'Post-production sonore', file:'post-son.html'}
    ],
    courses: [
      {file:'principes.html', title:'Principes du montage', time:'35', introText:"Le montage est l'art de selectionner, organiser et assembler les plans tournes pour construire la narration du film. C'est lors du montage que le film trouve son <strong>rythme</strong>, son sens et son emotion.", introHighlight:"<strong>L'effet Koulechov :</strong> Dans les annees 1920, Lev Koulechov a demontre qu'un meme plan d'un visage neutre, monte avec des images differentes (un bol de soupe, un cercueil, un enfant), est interprete differemment par le spectateur.", introText2:"Les principes fondamentaux du montage — continuite, rythme, raccords — constituent la grammaire invisible du cinema. Quand le montage est reussi, le spectateur l'oublie completement et se laisse porter par l'histoire.",
        courseH3s:[{title:"Les types de coupe", paragraphs:["La <strong>coupe franche</strong> (cut) est la transition la plus courante : passage instantane d'un plan a l'autre. Le <strong>fondu enchaîne</strong> superpose brievement deux plans pour marquer le passage du temps. Le <strong>fondu au noir</strong> marque une coupure nette, souvent entre les sequences.", "Le <strong>jump cut</strong>, coupe brutale dans un meme plan, a ete popularise par Godard dans A bout de souffle. Le <strong>match cut</strong> relie deux plans par un element visuel commun, comme le celebre raccord os/vaisseau dans 2001 de Kubrick."]},{title:"Les raccords", paragraphs:["Le <strong>raccord regard</strong> montre un personnage qui regarde, puis ce qu'il voit. Le <strong>raccord mouvement</strong> poursuit un geste d'un plan a l'autre. Le <strong>raccord dans l'axe</strong> passe d'un plan large a un plan serre sur le meme axe.", "La <strong>regle des 180 degres</strong> impose de ne pas franchir la ligne imaginaire reliant deux personnages en dialogue, pour maintenir la coherence spatiale. Le franchissement de cette ligne desoriente volontairement le spectateur."]},{title:"Le rythme du montage", paragraphs:["Le rythme du montage — la duree de chaque plan et la vitesse des coupes — cree l'emotion. Un montage rapide (plans courts) genere la tension et l'action. Un montage lent (plans longs) installe la contemplation et le suspense.", "Les grands monteurs — <strong>Thelma Schoonmaker</strong> (Scorsese), <strong>Walter Murch</strong> (Coppola), <strong>Sally Menke</strong> (Tarantino) — sont des artistes a part entiere dont le travail est indissociable de la vision du realisateur."]}],
        quizQuestions:[{q:"Qu'est-ce que l'effet Koulechov ?", opts:["Un effet special optique","Le sens change selon le plan adjacent","Un defaut de pellicule","Un type de fondu"], ans:1, expl:"L'effet Koulechov demontre qu'un meme plan prend un sens different selon le plan qui le precede ou le suit."},{q:"Qu'est-ce qu'un jump cut ?", opts:["Un saut dans le temps","Une coupe brutale dans un meme plan","Un raccord mouvement","Un fondu au noir"], ans:1, expl:"Le jump cut est une coupe brutale au sein d'un meme plan continu, popularisee par Godard dans A bout de souffle."},{q:"Quelle regle maintient la coherence spatiale en dialogue ?", opts:["La regle des tiers","La regle des 180 degres","La regle des 30 degres","La regle du plan-sequence"], ans:1, expl:"La regle des 180 degres interdit de franchir la ligne imaginaire entre deux interlocuteurs pour maintenir la coherence spatiale."},{q:"Qui est la monteuse attitrée de Martin Scorsese ?", opts:["Sally Menke","Thelma Schoonmaker","Anne V. Coates","Dede Allen"], ans:1, expl:"Thelma Schoonmaker est la monteuse de Martin Scorsese depuis Raging Bull (1980), avec plusieurs Oscars a son actif."},{q:"Quel raccord relie deux plans par un element visuel commun ?", opts:["Raccord regard","Jump cut","Match cut","Raccord dans l'axe"], ans:2, expl:"Le match cut relie deux plans par une similarite visuelle, comme le celebre raccord os/vaisseau dans 2001 de Kubrick."}]
      },
      {file:'narratif.html', title:'Montage narratif', time:'40', introText:"Le <strong>montage narratif</strong> est l'art de construire un recit coherent a partir de fragments filmes. Il determine l'ordre chronologique ou non-lineaire des evenements, gere les ellipses temporelles et cree les arcs dramatiques du film.", introHighlight:"<strong>Le montage est la derniere reecriture du scenario.</strong> A cette etape, des scenes entieres peuvent etre supprimees, l'ordre des sequences modifie, et le sens du film completement transforme.", introText2:"Les formes de montage narratif sont multiples : <strong>montage lineaire</strong> (chronologique), <strong>montage parallele</strong> (deux actions simultanees), <strong>flashback</strong> (retour en arriere), <strong>flashforward</strong> (saut dans l'avenir), <strong>montage alterne</strong> (suspense crescendo).",
        courseH3s:[{title:"Le montage parallele et alterne", paragraphs:["Le <strong>montage parallele</strong>, invente par D.W. Griffith, alterne entre deux actions simultanees pour creer du suspense ou un contraste thematique. Le climax de <em>Le Parrain</em> (bapteme/meurtres) en est l'exemple le plus celebre.", "Le <strong>montage alterne</strong> (cross-cutting) est une variante du montage parallele ou la vitesse des coupes augmente progressivement, creant un crescendo dramatique. Christopher Nolan en fait un usage magistral dans <em>Inception</em>, alternant entre quatre niveaux de reve simultanement."]},{title:"Les structures non-lineaires", paragraphs:["Le cinema contemporain explore des structures narratives non-lineaires complexes. <em>Pulp Fiction</em> (Tarantino, 1994) presente ses scenes dans un ordre non chronologique, creant des ironies dramatiques impossibles avec un recit lineaire.", "<strong>Memento</strong> (Nolan, 2000) raconte son histoire a l'envers, chaque scene revelant ce qui s'est passe avant. <em>Eternal Sunshine of the Spotless Mind</em> (Gondry, 2004) melange souvenirs et realite dans une structure en spirale."]},{title:"L'ellipse et le temps cinematographique", paragraphs:["L'<strong>ellipse</strong> est le saut temporel qui permet de condenser le temps. La plus celebre est celle de <em>2001</em> : un os lance en l'air par un hominide se transforme en vaisseau spatial — quatre millions d'annees en une seule coupe.", "Le montage manipule constamment le temps : il peut <strong>condenser</strong> (montage-sequence), <strong>dilater</strong> (ralentis, plans multiples d'un meme instant) ou <strong>inverser</strong> (flashbacks) le temps reel. Le spectateur accepte ces manipulations comme des conventions du langage cinematographique."]}],
        quizQuestions:[{q:"Qui a invente le montage parallele ?", opts:["Eisenstein","D.W. Griffith","Koulechov","Melies"], ans:1, expl:"D.W. Griffith est le pionnier du montage parallele, alternant entre deux actions simultanees pour creer du suspense."},{q:"Quel film de Tarantino presente une narration non chronologique ?", opts:["Kill Bill","Pulp Fiction","Django Unchained","Les Huit Salopards"], ans:1, expl:"Pulp Fiction (1994) est celebre pour sa structure narrative non chronologique qui redistribue les scenes dans un ordre original."},{q:"Quel film de Nolan raconte son histoire a l'envers ?", opts:["Inception","Tenet","Memento","Interstellar"], ans:2, expl:"Memento (2000) raconte son histoire a rebours, chaque scene revelant ce qui s'est passe avant."},{q:"Quelle est l'ellipse la plus celebre du cinema ?", opts:["Le saut dans Matrix","L'os devenant vaisseau dans 2001","Le fondu de Casablanca","Le jump cut de Godard"], ans:1, expl:"L'ellipse la plus celebre est le raccord os/vaisseau de 2001 de Kubrick, couvrant quatre millions d'annees en une coupe."},{q:"Qu'est-ce qu'un montage-sequence ?", opts:["Un plan-sequence monte","Une serie de plans courts condensant le temps","Un montage en temps reel","Un montage sans musique"], ans:1, expl:"Le montage-sequence est une serie de plans courts condenses par la musique pour montrer une evolution dans le temps (entrainement, voyage, transformation)."}]
      },
      {file:'effets-visuels.html', title:'Effets visuels', time:'40', introText:"Les <strong>effets visuels</strong> (VFX) sont les manipulations numeriques de l'image realisees en post-production. Du fond vert a la motion capture, les VFX sont devenus un element incontournable du cinema contemporain.", introHighlight:"<strong>Les meilleurs VFX sont ceux qu'on ne voit pas.</strong> Contrairement a l'idee recue, la majorite des effets visuels servent non pas a creer des creatures fantastiques, mais a effacer des elements indesirables ou a modifier subtilement des decors reels.", introText2:"L'industrie des VFX a transforme le cinema depuis <em>Jurassic Park</em> (1993) et <em>The Matrix</em> (1999). Des studios comme <strong>ILM</strong> (Industrial Light & Magic, fonde par George Lucas), <strong>Weta Digital</strong> (Le Seigneur des Anneaux) et <strong>Framestore</strong> repoussent constamment les limites du possible.",
        courseH3s:[{title:"Les techniques de VFX", paragraphs:["Le <strong>fond vert</strong> (chroma key) permet de remplacer un arriere-plan uni par n'importe quelle image ou environnement 3D. Les acteurs jouent devant un ecran vert, et le fond est remplace numeriquement en post-production.", "La <strong>motion capture</strong> (performance capture) enregistre les mouvements d'un acteur pour les appliquer a un personnage numerique. Andy Serkis a revolutionne cette technique en incarnant Gollum dans Le Seigneur des Anneaux et Caesar dans La Planete des Singes."]},{title:"L'evolution des effets speciaux", paragraphs:["Avant le numerique, les effets speciaux etaient <strong>mecaniques</strong> : maquettes, animatroniques, pyrotechnie, maquillages prothétiques. Ray Harryhausen et ses creatures en stop-motion (Jason et les Argonautes, 1963) representent l'apogee de cette ere.", "Le tournant numerique arrive avec <em>Terminator 2</em> (1991) et ses effets de morphing liquide, puis <em>Jurassic Park</em> (1993), premier film a utiliser des creatures CGI realistes. <em>Avatar</em> (2009) de James Cameron pousse la technologie 3D et la performance capture a un niveau sans precedent."]},{title:"Les VFX invisibles", paragraphs:["La majorite des VFX modernes sont <strong>invisibles</strong> : effacement de cables et equipements, extension numerique de decors, correction de la meteo, rajeunissement ou vieillissement d'acteurs. Des films comme <em>The Social Network</em> utilisent massivement les VFX sans que le spectateur s'en doute.", "L'<strong>intelligence artificielle</strong> transforme progressivement les VFX : deepfakes, generation d'environnements, animation procedurale. Ces technologies soulèvent des questions éthiques importantes sur la manipulation de l'image."]}],
        quizQuestions:[{q:"Quel studio a ete fonde par George Lucas ?", opts:["Weta Digital","Framestore","Industrial Light & Magic","Digital Domain"], ans:2, expl:"Industrial Light & Magic (ILM), fonde par George Lucas en 1975, est le studio de VFX le plus celebre et le plus influent de l'histoire."},{q:"Quel acteur a revolutionne la motion capture ?", opts:["Mark Ruffalo","Andy Serkis","Benedict Cumberbatch","Josh Brolin"], ans:1, expl:"Andy Serkis a revolutionne la motion capture en incarnant Gollum dans Le Seigneur des Anneaux avec une performance d'une expressivite inedite."},{q:"Quel film a marque le debut des creatures CGI realistes ?", opts:["Terminator 2","Jurassic Park","The Matrix","Avatar"], ans:1, expl:"Jurassic Park (1993) est le premier film a presenter des creatures CGI d'un realisme saisissant, melangees a des animatroniques."},{q:"Qu'est-ce que le chroma key ?", opts:["Un type de camera","La technique du fond vert","Un filtre de couleur","Un logiciel de montage"], ans:1, expl:"Le chroma key (fond vert) permet de remplacer un arriere-plan de couleur unie par n'importe quel environnement numerique."},{q:"Quel film de Cameron a repousse les limites de la 3D ?", opts:["Titanic","Terminator","Avatar","Aliens"], ans:2, expl:"Avatar (2009) de James Cameron a repousse les limites de la 3D stereoscopique et de la performance capture."}]
      },
      {file:'etalonnage.html', title:'Etalonnage', time:'30', introText:"L'<strong>etalonnage</strong> (color grading) est l'etape de post-production qui consiste a ajuster, corriger et styliser les couleurs de chaque plan du film. C'est l'etalonnage qui donne au film son <strong>identite visuelle</strong> finale.", introHighlight:"<strong>La couleur raconte une histoire.</strong> Un film bleutre evoque la froideur et la solitude. Des tons chauds suggerent la nostalgie ou la passion. L'etalonnage est un outil narratif aussi puissant que le montage.", introText2:"L'etalonnage numerique a revolutionne le processus : autrefois realise photochimiquement sur pellicule, il se fait desormais sur ordinateur avec des logiciels comme <strong>DaVinci Resolve</strong>, offrant un controle pixel par pixel sur chaque image du film.",
        courseH3s:[{title:"Correction vs etalonnage creatif", paragraphs:["La <strong>correction colorimetrique</strong> (primary correction) uniformise l'exposition, la balance des blancs et le contraste entre les plans d'une meme scene. C'est un travail technique qui assure la coherence visuelle.", "L'<strong>etalonnage creatif</strong> (secondary grading) est le travail artistique : creer un look specifique, modifier les teintes de la peau, isoler et modifier une couleur particuliere. C'est cette etape qui donne au film de Michael Bay ses teintes orange/turquoise ou aux films des freres Coen leur palette desaturee."]},{title:"Les looks cinematographiques celebres", paragraphs:["Le <strong>teal and orange</strong> (bleu-vert et orange) est le look cinematographique le plus repandu a Hollywood : les tons chauds des peaux humaines se detachent sur des fonds froids, creant un contraste visuel agreable.", "<em>Mad Max: Fury Road</em> (2015) utilise un etalonnage extreme : ciel turquoise, sable orange, nuits bleues. <em>The Matrix</em> (1999) a son celebre filtre vert pour les scenes dans la Matrice et un filtre bleu pour le monde reel. <em>Amelie Poulain</em> (2001) est entierement baigne dans des teintes vertes et rouges chaudes."]},{title:"Le workflow numerique", paragraphs:["Le workflow d'etalonnage commence par le <strong>dailies</strong> (visionnage des rushes avec un premier etalonnage) et s'acheve par le <strong>mastering</strong> (version finale pour le cinema, la television et le streaming, chacun avec ses specificites techniques).", "Les etaloneurs professionnels travaillent dans des salles calibrees avec des ecrans de reference pour garantir que les couleurs seront reproduites fidelement dans les salles de cinema du monde entier."]}],
        quizQuestions:[{q:"Qu'est-ce que l'etalonnage cinematographique ?", opts:["Le reglage des cameras","L'ajustement des couleurs du film","Le calibrage du son","La synchronisation des pistes"], ans:1, expl:"L'etalonnage est l'etape de post-production ou l'on ajuste, corrige et stylise les couleurs de chaque plan du film."},{q:"Quel logiciel est la reference en etalonnage ?", opts:["Adobe Premiere","Final Cut Pro","DaVinci Resolve","Avid Media Composer"], ans:2, expl:"DaVinci Resolve de Blackmagic Design est le logiciel de reference pour l'etalonnage professionnel."},{q:"Qu'est-ce que le look 'teal and orange' ?", opts:["Un filtre Instagram","Le contraste bleu-vert et orange","Un type de pellicule","Un eclairage de studio"], ans:1, expl:"Le teal and orange est un look qui oppose les tons chauds des peaux (orange) aux fonds froids (bleu-vert), tres repandu a Hollywood."},{q:"Quel film utilise un filtre vert pour ses scenes dans la Matrice ?", opts:["Blade Runner","Tron","The Matrix","Avatar"], ans:2, expl:"The Matrix (1999) utilise un filtre vert pour les scenes a l'interieur de la Matrice et un filtre bleu pour le monde reel."},{q:"Qu'est-ce que la correction colorimetrique primaire ?", opts:["Un choix artistique de couleur","L'uniformisation technique entre les plans","L'ajout de filtres creatifs","Le passage en noir et blanc"], ans:1, expl:"La correction colorimetrique primaire uniformise l'exposition, la balance des blancs et le contraste entre les plans pour assurer la coherence visuelle."}]
      },
      {file:'post-son.html', title:'Post-production sonore', time:'35', introText:"La <strong>post-production sonore</strong> couvre l'ensemble du travail audio realise apres le tournage : montage des dialogues, creation des bruitages, design sonore, enregistrement de la musique et mixage final.", introHighlight:"<strong>Le son represente 50% de l'experience cinematographique.</strong> Un film avec un mauvais son sera percu comme un mauvais film, meme si les images sont exceptionnelles. Le son est la composante la plus sous-estimee du cinema.", introText2:"La chaîne de post-production sonore comprend le <strong>montage dialogues</strong>, le <strong>ADR</strong> (re-enregistrement en studio), le <strong>Foley</strong> (bruitages), le <strong>sound design</strong>, la <strong>musique</strong> et le <strong>mixage</strong> final. Chaque etape est realisee par des specialistes differents.",
        courseH3s:[{title:"Le montage dialogues et l'ADR", paragraphs:["Le <strong>montage dialogues</strong> nettoie et organise les pistes audio enregistrees sur le plateau. Bruits de fond, parasites et imperfections sont elimines ou attenues pour obtenir des dialogues clairs et precis.", "L'<strong>ADR</strong> (Automated Dialogue Replacement) ou postsynchronisation consiste a re-enregistrer les dialogues en studio lorsque le son direct est inutilisable (bruit de fond, avion, vent). L'acteur refait ses repliques en regardant sa performance a l'ecran, synchronisant ses levres avec l'image."]},{title:"Le Foley et le sound design", paragraphs:["Le <strong>Foley</strong> (bruitage) recree en studio tous les sons du quotidien : pas sur differentes surfaces, froissements de vetements, manipulation d'objets, contacts physiques. Le bruiteur travaille dans un studio equipe de surfaces variees (gravier, bois, metal, terre) et d'une collection d'objets.", "Le <strong>sound design</strong> cree les sons qui n'existent pas dans la realite : le rugissement du T-Rex de Jurassic Park (melange de bebe elephant, alligator et tigre), le sabre laser de Star Wars (interference de projecteur TV et cable haute tension), le son du TARDIS de Doctor Who."]},{title:"Le mixage final", paragraphs:["Le <strong>mixage</strong> est l'etape ultime : equilibrer dialogues, bruitages, ambiances et musique dans un ensemble coherent. Le mixeur repartit chaque element dans l'espace sonore (gauche/droite, avant/arriere, haut/bas en Dolby Atmos) et ajuste les niveaux pour chaque scene.", "Le mixage se fait sur une <strong>console de mixage</strong> dans une salle calibree qui reproduit les conditions d'une salle de cinema. Le resultat est ensuite adapte pour differents supports : cinema (5.1 ou 7.1 ou Atmos), television, casque et enceintes portables."]}],
        quizQuestions:[{q:"Que signifie ADR ?", opts:["Audio Digital Recording","Automated Dialogue Replacement","Advanced Dynamic Range","Audio Design Room"], ans:1, expl:"ADR (Automated Dialogue Replacement) designe le re-enregistrement des dialogues en studio quand le son direct est inutilisable."},{q:"Qu'est-ce que le Foley ?", opts:["Un type de musique de film","La recreation de bruitages en studio","Un micro directionnel","Un format audio"], ans:1, expl:"Le Foley est l'art de recreer les bruitages (pas, contacts, manipulations d'objets) en studio, en synchronisation avec l'image."},{q:"Comment le son du sabre laser a-t-il ete cree ?", opts:["Synthese electronique pure","Melange de projecteur TV et cable haute tension","Enregistrement d'une epee reelle","Generateur de frequences"], ans:1, expl:"Ben Burtt a cree le son du sabre laser en combinant l'interference d'un projecteur TV et le bourdonnement d'un cable haute tension."},{q:"Qu'est-ce que le Dolby Atmos ?", opts:["Un micro de studio","Un systeme de son 3D immersif","Un logiciel de mixage","Un format de compression"], ans:1, expl:"Le Dolby Atmos est un systeme de son immersif qui positionne les elements sonores dans un espace tridimensionnel incluant la hauteur."},{q:"Quelle est la derniere etape de la post-production sonore ?", opts:["Le Foley","L'ADR","Le sound design","Le mixage final"], ans:3, expl:"Le mixage final est la derniere etape, ou tous les elements sonores sont equilibres et spatialises pour creer la bande-son definitive."}]
      }
    ]
  },
  animation: {
    hubTitle: 'Animation', hubFile: 'animation.html',
    siblings: [
      {name:'Animation traditionnelle', file:'traditionnelle.html'},
      {name:'Animation 3D', file:'animation-3d.html'},
      {name:'Stop motion', file:'stop-motion.html'},
      {name:'Animation japonaise', file:'japonaise.html'},
      {name:'Animation numerique', file:'numerique.html'}
    ],
    courses: [
      {file:'traditionnelle.html', title:'Animation traditionnelle', time:'35', introText:"L'<strong>animation traditionnelle</strong> (ou animation cel) est la technique originelle du dessin anime : chaque image est dessinee a la main, une par une. A 24 images par seconde, un film de 90 minutes necessite plus de 100 000 dessins.", introHighlight:"<strong>Les 12 principes de l'animation :</strong> Definis par Frank Thomas et Ollie Johnston (Disney) dans The Illusion of Life (1981), ces principes — squash and stretch, anticipation, timing... — restent la base de toute animation, meme numerique.", introText2:"L'animation traditionnelle a ete inventee par <strong>Emile Cohl</strong> (Fantasmagorie, 1908, premier dessin anime sur pellicule) et perfectionnee par les studios <strong>Disney</strong> a partir de Blanche-Neige (1937), premier long-metrage d'animation de l'histoire.",
        courseH3s:[{title:"La technique du cel animation", paragraphs:["Dans l'animation traditionnelle, chaque image est dessinee sur un <strong>celluloide</strong> (feuille transparente) superpose a un decor peint. Les personnages bougent sur des cels differents tandis que le decor reste fixe, economisant un travail considerable.", "Le processus comprend plusieurs etapes : <strong>storyboard</strong> (planches de croquis), animation cle (key frames), intercalation (in-betweens), encrage, coloriage et filmage sous camera. Chaque etape est realisee par des equipes differentes de specialistes."]},{title:"L'âge d'or de Disney", paragraphs:["<strong>Walt Disney</strong> revolutionne l'animation avec <em>Blanche-Neige et les Sept Nains</em> (1937), prouvant que l'animation peut raconter des histoires emotionnellement complexes. Suivent <em>Pinocchio</em> (1940), <em>Fantasia</em> (1940) et <em>Bambi</em> (1942).", "La <strong>Renaissance Disney</strong> des annees 1990 — <em>La Petite Sirene</em> (1989), <em>Le Roi Lion</em> (1994), <em>La Belle et la Bete</em> (1991) — ramene l'animation traditionnelle au sommet avant le basculement vers la 3D."]},{title:"L'animation traditionnelle aujourd'hui", paragraphs:["Bien que la 3D domine le cinema d'animation commercial, l'animation traditionnelle survit dans le cinema d'auteur et l'animation independante. Des films comme <em>Persepolis</em> (Satrapi, 2007), <em>Ernest et Celestine</em> (2012) et les oeuvres du Studio Ghibli prouvent la vitalite du dessin anime.", "L'animation 2D numerique (dessin sur tablette graphique) a remplace le dessin sur papier et celluloide, mais les principes artistiques restent identiques. La main de l'artiste reste au coeur du processus creatif."]}],
        quizQuestions:[{q:"Quel est le premier long-metrage d'animation de l'histoire ?", opts:["Pinocchio","Fantasia","Blanche-Neige et les Sept Nains","Bambi"], ans:2, expl:"Blanche-Neige et les Sept Nains (1937) de Walt Disney est le premier long-metrage d'animation de l'histoire du cinema."},{q:"Combien d'images par seconde compte l'animation cinema ?", opts:["12","24","30","60"], ans:1, expl:"Le cinema d'animation standard utilise 24 images par seconde, bien que l'animation 'on twos' (une image dessinee pour deux photogrammes) soit courante."},{q:"Qui a defini les 12 principes de l'animation ?", opts:["Walt Disney","Hayao Miyazaki","Frank Thomas et Ollie Johnston","Chuck Jones"], ans:2, expl:"Frank Thomas et Ollie Johnston, animateurs legendaires de Disney, ont defini les 12 principes dans The Illusion of Life (1981)."},{q:"Qui a realise le premier dessin anime sur pellicule ?", opts:["Walt Disney","Emile Cohl","Winsor McCay","Max Fleischer"], ans:1, expl:"Emile Cohl a realise Fantasmagorie en 1908, considere comme le premier dessin anime sur pellicule."},{q:"Quel film marque le debut de la Renaissance Disney ?", opts:["Le Roi Lion","Aladdin","La Petite Sirene","La Belle et la Bete"], ans:2, expl:"La Petite Sirene (1989) marque le debut de la Renaissance Disney, relancant l'animation traditionnelle au sommet."}]
      },
      {file:'animation-3d.html', title:'Animation 3D', time:'40', introText:"L'<strong>animation 3D</strong> (images de synthese) a revolutionne le cinema d'animation depuis Toy Story (1995). Elle repose sur la creation de personnages et d'environnements en trois dimensions dans un espace virtuel, animes par ordinateur.", introHighlight:"<strong>La 3D n'est pas plus facile que le dessin :</strong> Si l'ordinateur realise le rendu, l'animateur 3D doit maîtriser les memes principes de mouvement, de timing et d'emotion que l'animateur traditionnel. L'outil change, pas l'art.", introText2:"Les studios leaders de l'animation 3D — <strong>Pixar</strong>, <strong>DreamWorks Animation</strong>, <strong>Illumination</strong>, <strong>Blue Sky</strong> — ont produit certains des films les plus rentables de l'histoire du cinema. Pixar, fonde par Ed Catmull et John Lasseter (avec Steve Jobs comme investisseur), reste le studio le plus influent.",
        courseH3s:[{title:"Le pipeline 3D", paragraphs:["La creation d'un film en 3D suit un <strong>pipeline</strong> (chaîne de production) en plusieurs etapes : modelisation (creation des formes), texturing (application des materiaux), rigging (creation du squelette), animation (mouvement), eclairage, rendu et compositing.", "La <strong>modelisation</strong> cree les formes 3D a partir de polygones. Le <strong>rigging</strong> dote ces formes d'un squelette articule que l'animateur peut manipuler. Le <strong>rendu</strong> calcule l'image finale en simulant la lumiere, les ombres, les reflets et les transparences."]},{title:"Pixar et la revolution", paragraphs:["<strong>Pixar</strong> a invente le long-metrage d'animation 3D avec <em>Toy Story</em> (1995). Leur philosophie — l'histoire d'abord, la technologie au service du recit — a produit des chefs-d'oeuvre comme <em>Le Monde de Nemo</em> (2003), <em>Les Indestructibles</em> (2004), <em>Ratatouille</em> (2007) et <em>Coco</em> (2017).", "Le studio se distingue par la qualite emotionnelle de ses films. <em>Là-haut</em> (2009) ouvre par une sequence de dix minutes racontant toute une vie de couple, sans dialogue, consideree comme l'une des scenes les plus emouvantes de l'histoire du cinema."]},{title:"Les innovations techniques", paragraphs:["L'animation 3D progresse constamment : simulation de cheveux et de fourrure (Monstres et Cie), simulation de tissu et de liquides, eclairage global (global illumination), rendu realiste (photorealisme) ou stylise (NPR — non-photorealistic rendering).", "L'animation en <strong>temps reel</strong> (moteurs de jeu comme Unreal Engine) ouvre de nouvelles possibilites : prevision (previsualization) sur le plateau, films interactifs et production acceleree. La frontiere entre cinema, jeu video et realite virtuelle s'estompe."]}],
        quizQuestions:[{q:"Quel est le premier long-metrage entierement en images de synthese ?", opts:["Shrek","Toy Story","Monstres et Cie","L'Âge de glace"], ans:1, expl:"Toy Story (1995) de Pixar est le premier long-metrage d'animation entierement realise en images de synthese 3D."},{q:"Qu'est-ce que le rigging en animation 3D ?", opts:["La modelisation des formes","La creation du squelette articule","Le rendu des textures","L'eclairage de la scene"], ans:1, expl:"Le rigging consiste a doter un modele 3D d'un squelette articule que l'animateur peut manipuler pour creer le mouvement."},{q:"Qui a cofonde Pixar ?", opts:["Walt Disney","Steve Jobs et Ed Catmull","George Lucas","John Lasseter seul"], ans:1, expl:"Pixar a ete cofonde par Ed Catmull et Alvy Ray Smith, avec Steve Jobs comme investisseur principal apres le rachat a Lucasfilm."},{q:"Quel film Pixar simule pour la premiere fois la fourrure ?", opts:["Ratatouille","Rebelle","Monstres et Cie","Le Monde de Nemo"], ans:2, expl:"Monstres et Cie (2001) a represente un defi technique majeur avec la simulation de la fourrure de Sully, composee de millions de poils animes."},{q:"Qu'est-ce que le rendu en animation 3D ?", opts:["Le dessin des personnages","Le calcul de l'image finale avec lumiere et ombres","Le montage du film","L'animation des mouvements"], ans:1, expl:"Le rendu est le calcul informatique qui transforme la scene 3D en image 2D finale, en simulant la lumiere, les ombres et les materiaux."}]
      },
      {file:'stop-motion.html', title:'Stop motion', time:'30', introText:"Le <strong>stop motion</strong> (animation en volume) est la technique qui anime des objets reels — marionnettes, pate a modeler, papier decoupe — en les photographiant image par image, avec un leger deplacement entre chaque prise.", introHighlight:"<strong>La magie du tangible :</strong> Le stop motion possede une qualite tactile unique que ni le dessin anime ni la 3D ne peuvent reproduire. La legerete des imperfections — un doigt marque dans la pate, un mouvement legerement saccade — donne aux films une chaleur artisanale irrempla?able.", introText2:"Le stop motion a une longue histoire, de <strong>Willis O'Brien</strong> (King Kong, 1933) a <strong>Ray Harryhausen</strong> (Jason et les Argonautes, 1963), puis aux studios contemporains comme <strong>Aardman</strong> (Wallace et Gromit) et <strong>Laika</strong> (Coraline, Kubo).",
        courseH3s:[{title:"Les techniques du stop motion", paragraphs:["L'animation en <strong>pate a modeler</strong> (claymation) permet de deformer les personnages entre chaque prise, creant des expressions faciales et des mouvements fluides. Aardman Animations (Wallace et Gromit, Chicken Run) en est le maître inconteste.", "L'animation de <strong>marionnettes articulees</strong> utilise des figurines avec un squelette metallique interne (armature) permettant des poses precises. Tim Burton (L'Etrange Noel de Monsieur Jack, 1993) et Wes Anderson (Fantastic Mr. Fox, 2009) excellent dans cette technique."]},{title:"Les grands studios et artistes", paragraphs:["<strong>Aardman Animations</strong> (Bristol, Royaume-Uni), fonde par Peter Lord et David Sproxton, est celebre pour Wallace et Gromit et Shaun le Mouton. Leur style allie humour britannique et animation d'une fluidite remarquable.", "<strong>Laika</strong> (Portland, USA) repousse les limites du stop motion avec des films ambitieux : <em>Coraline</em> (2009), <em>ParaNorman</em> (2012), <em>Kubo et l'Armure magique</em> (2016). Le studio utilise l'impression 3D pour creer des milliers de visages interchangeables, combinant artisanat et technologie."]},{title:"Le stop motion contemporain", paragraphs:["Wes Anderson a contribue a la renaissance du stop motion avec <em>Fantastic Mr. Fox</em> (2009) et <em>L'Île aux chiens</em> (2018), prouvant que la technique peut porter des recits sophistiques pour adultes.", "Le stop motion reste un art profondement artisanal : chaque seconde de film necessite 12 a 24 photos, chaque photo demande de minuscules ajustements manuels. Un animateur produit en moyenne 3 a 5 secondes de film par jour."]}],
        quizQuestions:[{q:"Quel studio est celebre pour Wallace et Gromit ?", opts:["Laika","Aardman","Studio Ghibli","Pixar"], ans:1, expl:"Aardman Animations (Bristol, UK) est le studio derriere Wallace et Gromit, Chicken Run et Shaun le Mouton."},{q:"Quel film de Tim Burton est en stop motion ?", opts:["Batman","Edward aux mains d'argent","L'Etrange Noel de Monsieur Jack","Charlie et la Chocolaterie"], ans:2, expl:"L'Etrange Noel de Monsieur Jack (1993), produit par Tim Burton et realise par Henry Selick, est un classique du stop motion."},{q:"Combien de photos faut-il pour une seconde de stop motion cinema ?", opts:["8","12 a 24","30","60"], ans:1, expl:"Une seconde de stop motion necessite 12 a 24 photos (une par image), selon que l'animation est 'on twos' ou 'on ones'."},{q:"Quel studio utilise l'impression 3D pour les visages ?", opts:["Aardman","Pixar","Laika","DreamWorks"], ans:2, expl:"Laika utilise l'impression 3D pour creer des milliers de visages interchangeables, permettant des expressions faciales d'une finesse inedite."},{q:"Quel realisateur a relance le stop motion au cinema avec Fantastic Mr. Fox ?", opts:["Henry Selick","Tim Burton","Wes Anderson","Nick Park"], ans:2, expl:"Wes Anderson a relance le stop motion avec Fantastic Mr. Fox (2009), puis L'Île aux chiens (2018)."}]
      },
      {file:'japonaise.html', title:'Animation japonaise', time:'40', introText:"L'<strong>animation japonaise</strong> (anime) est un phenomene culturel mondial. Avec ses conventions esthetiques distinctives, ses recits souvent complexes et ses themes matures, l'anime constitue un univers artistique a part entiere, distinct de l'animation occidentale.", introHighlight:"<strong>L'anime n'est pas un genre, c'est un medium.</strong> Il couvre tous les genres — action, romance, science-fiction, horreur, comedie, drame psychologique — et s'adresse a tous les publics, des enfants aux adultes.", introText2:"L'anime naît dans les annees 1960 avec <strong>Osamu Tezuka</strong> (Astro Boy, 1963) et atteint une reconnaissance mondiale avec les films de <strong>Hayao Miyazaki</strong> et du <strong>Studio Ghibli</strong>, ainsi que les series a succes comme Dragon Ball, Naruto et L'Attaque des Titans.",
        courseH3s:[{title:"L'esthetique de l'anime", paragraphs:["L'anime se distingue par des conventions visuelles reconnaissables : <strong>grands yeux expressifs</strong> (herites du style de Tezuka, lui-meme influence par Disney), lignes dynamiques, decors detailles et couleurs vives. Ces conventions permettent une expressivite emotionnelle intense.", "L'animation japonaise utilise souvent l'<strong>animation limitee</strong> (limited animation) : moins d'images par seconde que l'animation occidentale, compensees par des cadrages dynamiques, des effets de speed lines et des poses-cles expressives. Cette contrainte economique est devenue une signature esthetique."]},{title:"Le Studio Ghibli et Miyazaki", paragraphs:["Le <strong>Studio Ghibli</strong>, cofonde par <strong>Hayao Miyazaki</strong> et <strong>Isao Takahata</strong> en 1985, est le studio d'animation le plus respecte au monde. Miyazaki cree des univers d'une beaute et d'une profondeur incomparables : <em>Mon voisin Totoro</em> (1988), <em>Princesse Mononoke</em> (1997), <em>Le Voyage de Chihiro</em> (2001).", "<em>Le Voyage de Chihiro</em> est le premier (et longtemps le seul) film d'animation a remporter l'Ours d'or a Berlin (2002) et l'Oscar du meilleur film d'animation (2003). L'oeuvre de Miyazaki se distingue par son respect de la nature, ses heroines fortes et son refus du manichéisme."]},{title:"L'anime contemporain", paragraphs:["L'anime contemporain est un phenomene mondial porte par le streaming (Crunchyroll, Netflix). Des series comme <em>L'Attaque des Titans</em> (Hajime Isayama), <em>Demon Slayer</em> et <em>Jujutsu Kaisen</em> attirent des millions de spectateurs dans le monde entier.", "De nouveaux realisateurs comme <strong>Makoto Shinkai</strong> (<em>Your Name</em>, 2016 — plus gros succes du cinema d'animation japonais hors Ghibli) et <strong>Mamoru Hosoda</strong> (<em>Belle</em>, 2021) portent l'anime a de nouveaux sommets artistiques et commerciaux."]}],
        quizQuestions:[{q:"Qui est considere comme le 'pere du manga et de l'anime' ?", opts:["Hayao Miyazaki","Akira Toriyama","Osamu Tezuka","Isao Takahata"], ans:2, expl:"Osamu Tezuka (1928-1989), createur d'Astro Boy, est considere comme le pere du manga et de l'anime modernes."},{q:"Quel film du Studio Ghibli a remporte l'Oscar du meilleur film d'animation ?", opts:["Princesse Mononoke","Mon voisin Totoro","Le Château ambulant","Le Voyage de Chihiro"], ans:3, expl:"Le Voyage de Chihiro (2001) de Hayao Miyazaki a remporte l'Oscar du meilleur film d'animation en 2003."},{q:"Qu'est-ce que l'animation limitee ?", opts:["Animation avec moins d'images par seconde","Animation sans couleur","Animation pour enfants uniquement","Animation sans son"], ans:0, expl:"L'animation limitee utilise moins d'images par seconde, compensant par des cadrages dynamiques et des poses-cles expressives."},{q:"Quel film de Makoto Shinkai a ete un phenomene mondial ?", opts:["Weathering with You","Your Name","The Garden of Words","5 Centimeters per Second"], ans:1, expl:"Your Name (Kimi no Na wa, 2016) de Makoto Shinkai est devenu le plus gros succes du cinema d'animation japonais hors Studio Ghibli."},{q:"En quelle annee le Studio Ghibli a-t-il ete fonde ?", opts:["1978","1985","1992","2001"], ans:1, expl:"Le Studio Ghibli a ete fonde en 1985 par Hayao Miyazaki, Isao Takahata et le producteur Toshio Suzuki."}]
      },
      {file:'numerique.html', title:'Animation numerique', time:'30', introText:"L'<strong>animation numerique</strong> englobe les nouvelles formes d'animation nees avec les outils informatiques : motion design, animation web, animation procedurale, realite virtuelle et creation pour les reseaux sociaux.", introHighlight:"<strong>L'animation est partout.</strong> Au-dela du cinema, l'animation numerique est omnipresente : interfaces d'applications, publicites, infographies animees, clips musicaux, contenus pour les reseaux sociaux. C'est l'un des metiers les plus demandes du numerique.", introText2:"Les outils se sont democratises : <strong>After Effects</strong> (motion design), <strong>Blender</strong> (3D gratuit et open source), <strong>Procreate</strong> (animation 2D sur iPad) permettent a quiconque de creer des animations de qualite professionnelle.",
        courseH3s:[{title:"Le motion design", paragraphs:["Le <strong>motion design</strong> (motion graphics) anime des elements graphiques — typographie, formes geometriques, pictogrammes, infographies — pour communiquer des informations de maniere dynamique et engageante. C'est le domaine le plus commercial de l'animation numerique.", "Les generiques de films sont l'une des formes les plus celebres du motion design. <strong>Saul Bass</strong> (Vertigo, Psychose, Anatomie d'un meurtre) a invente le generique comme oeuvre d'art a part entiere dans les annees 1950-60. Kyle Cooper (Se7en, 1995) a relance cet art a l'ere numerique."]},{title:"L'animation procedurale et l'IA", paragraphs:["L'<strong>animation procedurale</strong> genere du mouvement par des algorithmes plutot que par l'animation manuelle : simulation de foules, physique des fluides, croissance de vegetation, destruction de bâtiments. Ces techniques sont utilisees massivement dans les films a effets speciaux et les jeux video.", "L'<strong>intelligence artificielle</strong> commence a transformer l'animation : interpolation automatique entre les images-cles, generation de mouvements realistes, creation de personnages animes par texte (text-to-video). Ces outils soulèvent des questions ethiques sur l'avenir du metier d'animateur."]},{title:"Les nouveaux supports", paragraphs:["La <strong>realite virtuelle</strong> (VR) et la <strong>realite augmentee</strong> (AR) ouvrent de nouveaux territoires pour l'animation. Des experiences comme <em>Dear Angelica</em> (Oculus, 2017) permettent au spectateur de se deplacer a l'interieur d'une animation peinte a la main en 3D.", "L'animation pour les <strong>reseaux sociaux</strong> (TikTok, Instagram, YouTube Shorts) cree de nouveaux formats : boucles de quelques secondes, GIF animes, stickers, filtres AR. Ces micro-animations touchent des millions de personnes et representent un marche considerable."]}],
        quizQuestions:[{q:"Qu'est-ce que le motion design ?", opts:["L'animation de personnages 3D","L'animation d'elements graphiques","Le design de vehicules","La creation de logos"], ans:1, expl:"Le motion design anime des elements graphiques (typographie, formes, infographies) pour communiquer de maniere dynamique et engageante."},{q:"Quel designer a invente le generique de film comme forme d'art ?", opts:["Kyle Cooper","Saul Bass","Maurice Binder","Pablo Ferro"], ans:1, expl:"Saul Bass a revolutionne les generiques de films dans les annees 1950-60, creant des oeuvres graphiques memorables pour Hitchcock et Preminger."},{q:"Quel logiciel gratuit est devenu la reference en animation 3D ?", opts:["Maya","3ds Max","Blender","Cinema 4D"], ans:2, expl:"Blender, logiciel libre et gratuit, est devenu une reference en animation 3D grâce a sa communaute active et ses fonctionnalites professionnelles."},{q:"Qu'est-ce que l'animation procedurale ?", opts:["Animation dessinee a la main","Animation generee par algorithmes","Animation en stop motion","Animation en temps reel"], ans:1, expl:"L'animation procedurale genere du mouvement par des algorithmes : simulation de foules, physique des fluides, destruction de bâtiments."},{q:"Quel nouveau support ouvre des territoires pour l'animation ?", opts:["La television","La realite virtuelle","Le vinyle","La radio"], ans:1, expl:"La realite virtuelle permet au spectateur de se deplacer a l'interieur d'animations, ouvrant de nouveaux territoires pour la creation."}]
      }
    ]
  }
};

// Generate all cinema course pages
for (const [hubKey, hub] of Object.entries(cinemaCourses)) {
  for (let i = 0; i < hub.courses.length; i++) {
    const c = hub.courses[i];
    const prev = i > 0 ? {name: hub.courses[i-1].title, file: hub.courses[i-1].file} : null;
    const next = i < hub.courses.length - 1 ? {name: hub.courses[i+1].title, file: hub.courses[i+1].file} : null;
    const html = coursePage({
      title: c.title,
      disciplineTitle: 'Cinema & Audiovisuel',
      disciplineFile: 'cinema-page.html',
      hubTitle: hub.hubTitle,
      hubFile: hub.hubFile,
      breadcrumbDiscipline: 'Cinema',
      breadcrumbHub: hub.hubTitle,
      tagDomain: '&#127916; Cinema',
      time: c.time,
      introText: c.introText,
      introHighlight: c.introHighlight,
      introText2: c.introText2,
      courseH3s: c.courseH3s,
      quizQuestions: c.quizQuestions,
      prevCourse: prev,
      nextCourse: next,
      siblings: hub.siblings,
      currentFile: c.file
    });
    const filePath = path.join(BASE, 'cinema', hubKey, c.file);
    fs.writeFileSync(filePath, html, 'utf-8');
    console.log('Created: ' + filePath);
  }
}

console.log('\\nAll cinema course pages created!');
console.log('Total cinema courses: ' + Object.values(cinemaCourses).reduce((s, h) => s + h.courses.length, 0));
