/**
 * Curiosita — Build Script
 * Concatenates source JS files into production bundles.
 *
 * Usage:  node scripts/build.js
 *
 * Produces:
 *   curiosita.js  — utils + quiz + mobile  (loaded by all 808+ pages)
 *   sr-app.js     — 6 SR scripts           (loaded by apprendre.html)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// ── Bundle definitions ──────────────────────────────────
const bundles = [
  {
    name: 'curiosita.js',
    header: '// AUTO-GENERATED by scripts/build.js — ne pas modifier.\n// Source: utils.js + quiz.js + mobile.js\n',
    sources: ['utils.js', 'quiz.js', 'mobile.js'],
  },
  {
    name: 'sr-app.js',
    header: '// AUTO-GENERATED by scripts/build.js — ne pas modifier.\n// Source: sr-engine.js + sr-extract.js + sr-courses.js + sr-ui.js + sr-progress.js + sr-methode.js\n',
    sources: [
      'sr-engine.js',
      'sr-extract.js',
      'sr-courses.js',
      'sr-ui.js',
      'sr-progress.js',
      'sr-methode.js',
    ],
  },
];

// ── Build each bundle ───────────────────────────────────
let allOk = true;

bundles.forEach(bundle => {
  const parts = [];

  for (const src of bundle.sources) {
    const filePath = path.join(ROOT, src);
    if (!fs.existsSync(filePath)) {
      console.error(`[ERROR] Missing source: ${src}`);
      allOk = false;
      return;
    }
    parts.push(fs.readFileSync(filePath, 'utf-8'));
  }

  const output = bundle.header + '\n' + parts.join('\n\n');
  const outPath = path.join(ROOT, bundle.name);
  fs.writeFileSync(outPath, output, 'utf-8');

  const sizeKB = (Buffer.byteLength(output, 'utf-8') / 1024).toFixed(1);
  console.log(`  ✓ ${bundle.name}  (${sizeKB} KB)  ← ${bundle.sources.join(' + ')}`);
});

if (allOk) {
  console.log('\nBuild complete.');
} else {
  console.error('\nBuild finished with errors.');
  process.exit(1);
}
