#!/usr/bin/env python3
"""Enrichissement des articles design — remplacement complet du contenu générique."""
import json, re, sys, os

sys.stdout.reconfigure(encoding='utf-8')
BASE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content'

ENRICHMENTS = {

"industriel/grands-designers": """<h3>Les pionniers du design industriel : du Bauhaus aux années 1950</h3>
<p>Le design industriel moderne naît au croisement de la révolution industrielle et des avant-gardes artistiques du début du XXe siècle. Le <strong>Bauhaus</strong> (Dessau, 1919-1933), fondé par Walter Gropius, forge l'idéal du designer comme artisan-artiste capable de penser l'objet de usage quotidien comme une œuvre : Marcel Breuer conçoit la chaise Wassily (1925) en tubes d'acier tubulaire, Wilhelm Wagenfeld la lampe de table WG24 (1924). Ces objets combinent esthétique moderniste et production industrielle.</p>
<p>Charles et Ray <strong>Eames</strong> représentent le sommet du design américain des années 1940-60. Leur chaise DCM (1946) en contreplaqué moulé, développée avec Eero Saarinen pour un concours du MoMA, résout brillamment le problème de la forme organique en production industrielle. Leurs recherches sur le contreplaqué, la fibre de verre et l'aluminium coulé mènent à la chaise de salon Eames (1956), symbole de confort bourgeois éclairé et objet de collection mondial.</p>
<div class="highlight-box"><p>Dieter <strong>Rams</strong>, directeur du design chez Braun de 1961 à 1995, formule en 1976 ses <strong>dix principes du bon design</strong> — dont « le bon design est aussi peu design que possible ». Son minimalisme fonctionnel influence directement Jony Ive, chief designer d'Apple, qui reconnaît explicitement cette dette dans l'esthétique de l'iMac, de l'iPod et de l'iPhone.</p></div>
<h3>Philippe Starck et le design comme communication</h3>
<p>Philippe <strong>Starck</strong> (né en 1949) transforme le design en spectacle médiatique. Son presse-citron Juicy Salif pour Alessi (1990) — sculpture en aluminium coulé plus décorative que fonctionnelle — symbolise un design qui assume sa dimension symbolique et narrative. Starck travaille à toutes les échelles : du manche de brosse à dents Fluocaril aux intérieurs de l'hôtel Royalton (New York), du scooter Aprilia aux éoliennes résidentielles.</p>
<p>Son influence consacre le designer comme personnalité publique et communicateur culturel. Cette star-ification du design — qui fait des noms propres des marques commerciales — est à double tranchant : elle valorise la discipline mais risque de réduire le design à de l'esthétisme superficiel déconnecté des usages.</p>
<h3>Jony Ive et l'ère du design numérique</h3>
<p>Jonathan <strong>Ive</strong> (né en 1967), directeur du design chez Apple de 1996 à 2019, a redéfini les standards du design produit à l'ère numérique. L'iMac G3 (1998) avec son boîtier transparent en Bondi Blue rompt avec l'esthétique beige de l'informatique des années 1980-90. L'iPod (2001), avec sa molette tactile et son blanc immaculé, réinvente le baladeur. L'iPhone (2007) supprime tout le hardware au profit d'une surface de verre : le design comme disparition dans l'usage.</p>
<p>Le succès commercial colossal d'Apple transforme le design en avantage concurrentiel stratégique et incite toutes les industries à investir dans le design comme différenciateur de marque. La notion de <em>design thinking</em> — le design comme méthode de résolution créative de problèmes applicable bien au-delà des objets — se diffuse dans le management et l'innovation à partir des années 2000.</p>""",

"industriel/ergonomie": """<h3>Définitions et origines de l'ergonomie</h3>
<p>L'<strong>ergonomie</strong> — du grec <em>ergon</em> (travail) et <em>nomos</em> (loi) — est la science qui étudie les interactions entre les êtres humains et les systèmes techniques pour optimiser le bien-être des personnes et la performance globale des systèmes. Née formellement en Grande-Bretagne en 1949 avec la fondation de la première société d'ergonomie (Ergonomics Society), elle hérite de traditions antérieures : le taylorisme scientifique du travail (Frederick Taylor), la physiologie du travail et la psychologie expérimentale.</p>
<p>L'ergonomie distingue deux grandes approches. L'<strong>ergonomie de conception</strong> intègre les contraintes humaines dès la phase de création d'un produit, d'un espace ou d'un système. L'<strong>ergonomie corrective</strong> améliore des situations existantes qui génèrent inconfort, erreurs ou accidents. Ces deux approches sont complémentaires : la correction des défauts nourrit la conception future.</p>
<div class="highlight-box"><p>La notion d'<strong>utilisateur moyen</strong> est un mythe scientifiquement réfuté : l'armée américaine a découvert dans les années 1950 que sur un échantillon de 4 063 pilotes, aucun ne correspondait à la moyenne sur les dix dimensions corporelles mesurées. Cette découverte a révolutionné le design des postes de pilotage, imposant l'ajustabilité plutôt que la normalisation.</p></div>
<h3>Les dimensions de l'ergonomie</h3>
<p>L'ergonomie physique étudie les capacités et limites du corps humain : anthropométrie (mesures corporelles), biomécanique, postures, gestes répétitifs et fatigue. Elle vise à prévenir les troubles musculo-squelettiques (TMS) — première cause de maladie professionnelle dans les pays développés — par la conception d'outils, de postes de travail et de procédures adaptés.</p>
<p>L'ergonomie cognitive s'intéresse aux processus mentaux : attention, mémoire de travail, prise de décision, charge cognitive. Elle s'applique à la conception des interfaces numériques, des panneaux de contrôle et des systèmes d'information. La conception de l'<em>affordance</em> — les propriétés d'un objet qui suggèrent son usage — est au cœur de ce domaine, théorisé par Donald Norman dans <em>The Design of Everyday Things</em> (1988).</p>
<h3>UX Design et ergonomie numérique</h3>
<p>L'<strong>UX Design</strong> (<em>User Experience Design</em>) est l'application des principes ergonomiques aux interfaces numériques. Il englobe l'architecture de l'information (organisation des contenus), le design d'interaction (comportement des éléments), l'accessibilité (usage par des personnes en situation de handicap) et la recherche utilisateur (observation, entretiens, tests).</p>
<p>Les méthodes de recherche UX — tests d'utilisabilité (observation de vrais utilisateurs accomplissant des tâches), <em>eye tracking</em> (suivi du regard), cartes de chaleur, entretiens contextuels — permettent de valider empiriquement les choix de design. Ces méthodes, inspirées de la psychologie expérimentale, ont transformé le design numérique en discipline rigoureuse fondée sur des données plutôt que sur l'intuition.</p>""",

"industriel/ecoconception": """<h3>Principes et enjeux de l'écoconception</h3>
<p>L'<strong>écoconception</strong> intègre les considérations environnementales dès la phase de conception d'un produit, d'un service ou d'un bâtiment. Elle vise à réduire l'impact environnemental global sur l'ensemble du <strong>cycle de vie</strong> : extraction des matières premières, fabrication, transport, utilisation et fin de vie (recyclage, valorisation ou élimination). Cette approche systémique s'oppose à l'optimisation partielle qui améliore une étape au détriment d'une autre.</p>
<p>L'outil central de l'écoconception est l'<strong>Analyse du Cycle de Vie</strong> (ACV), méthode normalisée (ISO 14040-44) qui quantifie les flux de matières et d'énergie et les impacts environnementaux associés pour chaque étape du cycle de vie. Une ACV révèle souvent des résultats contre-intuitifs : le recyclage du verre est moins avantageux que celui de l'aluminium (énergie de fusion beaucoup plus élevée pour le verre), et les sacs en coton « écologiques » ont une empreinte eau et carbone très supérieure aux sacs plastiques si on intègre leur cycle de production.</p>
<div class="highlight-box"><p>Le concept d'<strong>économie circulaire</strong>, popularisé par la Fondation Ellen MacArthur depuis 2013, va plus loin que le recyclage : il vise à maintenir les matériaux dans des boucles d'usage (réemploi, réparation, remise à neuf, recyclage) en évitant la mise en décharge. Ce paradigme redéfinit la relation entre design et fin de vie dès la conception.</p></div>
<h3>Stratégies d'écoconception</h3>
<p>La hiérarchie des stratégies d'écoconception, de la plus efficace à la moins efficace, suit la règle des 3R-5R : <em>Refuser</em> (ne pas créer ce qui n'est pas nécessaire), <em>Réduire</em> (diminuer la matière et l'énergie utilisées), <em>Réutiliser</em> (concevoir pour un usage prolongé ou multiple), <em>Réparer</em> (faciliter la maintenance), <em>Recycler</em> (valoriser en fin de vie). La conception pour la durabilité (choix de matériaux durables, facilité de réparation, évolutivité) est souvent plus efficace que l'optimisation des processus de fin de vie.</p>
<p>La <strong>conception modulaire</strong> — diviser un produit en modules remplaçables indépendamment — est une stratégie clé. Le smartphone modulaire Fairphone, dont l'écran, la batterie et les composants sont remplaçables par l'utilisateur, illustre ce principe. À l'opposé, les produits dont les composants sont soudés ou collés deviennent irréparables et obsolescents.</p>
<h3>Réglementation et normes</h3>
<p>L'écoconception fait l'objet d'une réglementation croissante, notamment en Europe. La <strong>directive Ecodesign</strong> de l'Union européenne impose des exigences d'efficacité énergétique et de durabilité à de nombreuses catégories de produits (appareils électroménagers, équipements informatiques, éclairage). Le règlement sur l'<strong>indice de réparabilité</strong>, appliqué en France depuis 2021, oblige les fabricants à afficher une note de réparabilité sur les smartphones, téléviseurs et lave-linge.</p>
<p>Ces réglementations transforment progressivement les pratiques industrielles, mais font face à des résistances liées aux modèles économiques fondés sur l'obsolescence programmée et le renouvellement fréquent des produits. La tension entre impératifs environnementaux et logiques de croissance économique est au cœur des débats sur la durabilité.</p>""",

"industriel/materiaux-procedes": """<h3>Les grandes familles de matériaux et leurs propriétés</h3>
<p>Le designer industriel choisit ses matériaux en fonction d'un ensemble de propriétés physiques, mécaniques, thermiques et esthétiques, mais aussi de critères de coût, de disponibilité, de transformabilité et d'impact environnemental. Les grandes familles de matériaux sont les <strong>métaux</strong> (acier, aluminium, cuivre, titane), les <strong>polymères</strong> (plastiques thermodurcissables et thermoplastiques), les <strong>céramiques</strong> (verre, porcelaine, matériaux techniques), les <strong>composites</strong> (fibres de carbone, kevlar) et les <strong>matériaux naturels</strong> (bois, coton, cuir, bambou).</p>
<p>L'<strong>aluminium</strong> illustre la complexité des choix matériaux. Léger (2�⁄³ du poids de l'acier), recyclable à l'infini sans perte de propriétés, résistant à la corrosion et formable par extrusion, il est idéal pour les structures légères et les boîtiers électroniques. Mais sa production primaire est extrêmement énergivore (13 kWh/kg contre 0,7 kWh/kg pour le recyclage) — ce qui en fait un matériau « vertueux » uniquement si son recyclage est assuré.</p>
<div class="highlight-box"><p>La fibre de carbone — légère, rigide et résistante — coûte 20 à 100 fois plus cher que l'acier. Son usage s'est démocratisé dans le sport (vélos, raquettes, skis) et l'aéronautique, mais sa recyclabilité reste un défi majeur : les fibres de carbone recyclées perdent une partie de leurs propriétés mécaniques, et les résines qui les lient sont difficiles à séparer.</p></div>
<h3>Les procédés de mise en forme</h3>
<p>Les principaux procédés de mise en forme des métaux incluent le <strong>moulage</strong> (coulée de métal liquide dans un moule), le <strong>forgeage</strong> (déformation à chaud ou à froid pour renforcer la structure cristalline), l'<strong>usinage</strong> (enlèvement de matière par outils coupants), l'<strong>emboutissage</strong> (formage par pression d'une feuille métallique) et l'<strong>extrusion</strong> (passage d'un matériau à travers une filière pour obtenir un profilé continu). Chaque procédé implique des contraintes de conception spécifiques : épaisseurs minimales, dépouilles, raccordements, tolérances.</p>
<p>Pour les polymères, les procédés dominants sont l'<strong>injection</strong> (remplissage d'un moule sous pression — idéal pour les grandes séries), l'<strong>extrusion-soufflage</strong> (bouteilles et emballages), le <strong>rotomoulage</strong> (pièces creuses de grande taille) et l'<strong>impression 3D</strong> (prototypage rapide et petites séries). L'impression 3D a révolutionné les phases de prototypage en réduisant les délais de jours à heures, mais reste limitée pour la production en série par ses coûts et sa vitesse.</p>
<h3>Matériaux émergents et innovation</h3>
<p>Les <strong>matériaux biosourcés</strong> — issus du vivant — connaissent un essor important : PLA (acide polylactique) à base de maïs, PHA (polyhydroxyalcanoates) produits par des bactéries, matériaux à base de champignons (<em>mycelium composites</em>), cuir végétal à base d'ananas (Piñatex) ou de champignons (Mylo). Ces alternatives aux plastiques pétrochimiques et aux cuirs animaux ouvrent de nouvelles possibilités esthétiques et environnementales.</p>
<p>Les <strong>matériaux intelligents</strong> — qui répondent à des stimuli (température, lumière, champ magnétique) en modifiant leurs propriétés — ouvrent des perspectives fascinantes : alliages à mémoire de forme (utilisés en orthodontie et en chirurgie), matériaux thermochromes (changeant de couleur selon la température), électroluminescents (intégrés dans les vêtements connectés) et piézoélectriques (générant de l'électricité sous pression mécanique).</p>""",

"industriel/histoire-design": """<h3>De l'artisanat à l'ère industrielle</h3>
<p>Avant la révolution industrielle, la distinction entre art, artisanat et design n'existait pas : l'artisan concevait et fabriquait l'objet, ajustant le design à chaque pièce selon les commandes et les matériaux. La mécanisation et la production en série du XIXe siècle séparent radicalement la conception de la fabrication, créant la nécessité d'une discipline qui pense l'objet avant qu'il soit fabriqué.</p>
<p>La <strong>Grande Exposition</strong> de Londres (Crystal Palace, 1851) révèle l'abîme esthétique de la production industrielle : les machines produisent en grande quantité des objets surchargés d'ornements mal assimilés, sans cohérence formelle. Cette crise de goût provoque les premières réflexions sur le design industriel. Les Arts and Crafts Movement de William Morris (1860s) réagit en valorisant l'artisanat traditionnel, mais cette réponse reste élitiste et anti-industrielle.</p>
<div class="highlight-box"><p>Le <strong>Deutscher Werkbund</strong> (1907), fondé par Hermann Muthesius, est la première organisation à réconcilier industrie et qualité esthétique en Allemagne. Sa devise — <em>Vom Sofakissen zum Städtebau</em> (Du cousin de canapé à l'urbanisme) — définit le champ d'action du design industriel. Il prépare le terrain au Bauhaus fondé douze ans plus tard.</p></div>
<h3>Le design fonctionnaliste et le modernisme</h3>
<p>Le <strong>modernisme</strong> en design, dont le Bauhaus est l'emblème, pose le principe que « la forme suit la fonction » (Louis Sullivan, 1896). Cette formule, souvent mal comprise comme un programme d'ascétisme esthétique, signifie que la forme d'un objet doit découler logiquement de son usage — mais cela n'exclut pas la beauté, qui résulte de l'adéquation parfaite entre forme et fonction.</p>
<p>Le <strong>style international</strong> (International Style), dominant de l'après-guerre aux années 1970, décline ces principes à l'échelle mondiale : meubles tubulaires, architectures de verre et d'acier, typographies sans empattement. L'essor économique des <em>Trente Glorieuses</em> fait du design un outil de démocratisation : les meubles Ikea (fondé en 1943), les appareils électroménagers Braun, les voitures Volkswagen portent le good design aux classes moyennes.</p>
<h3>Le postmodernisme et l'ère contemporaine</h3>
<p>Le <strong>postmodernisme</strong> en design (Memphis Group, fondé par Ettore Sottsass à Milan en 1981) réagit contre la sévérité fonctionnaliste par l'exubérance décorative, les couleurs vives et les références pop. Memphis produit des meubles délibérément dysfonctionnels et joyeusement kitsch qui bouleversent les catégories du bon goût.</p>
<p>Le design contemporain est marqué par la pluralité des approches : design durable (William McDonough, <em>Cradle to Cradle</em>, 2002), design inclusif (conception pour tous les utilisateurs, y compris les personnes handicapées), design social (résolution de problèmes dans les pays en développement), design spéculatif (Dunne & Raby — objets critiques qui questionnent nos futurs possibles). Ces approches révèlent que le design est intrinsèquement politique : il incarne des valeurs et des visions du monde.</p>""",

"interieur/eclairage": """<h3>La lumière naturelle et ses qualités</h3>
<p>La <strong>lumière naturelle</strong> est le référent absolu de l'éclairage intérieur. Elle varie en intensité, en couleur et en direction selon l'heure, la saison et l'orientation géographique. L'orientation d'une pièce détermine fondamentalement son rapport à la lumière : les pièces nord reçoivent une lumière douce et constante, idéale pour les ateliers d'artistes (lumière froide sans éblouissement direct) ; les pièces sud reçoivent une lumière chaude et abondante mais nécessitent des protections solaires ; les pièces est et ouest connaissent des variations importantes selon l'heure.</p>
<p>Le <strong>facteur de lumière du jour</strong> (FLJ) mesure le pourcentage de lumière extérieure qui pénètre à l'intérieur. Les réglementations actuelles imposent un FLJ minimal dans les espaces habités. L'architecture bioclimatique optimise la lumière naturelle par le choix des orientations, la dimensionnement des baies, les protections solaires (brise-soleil, débords de toiture, végétation) et les matériaux réfléchissants.</p>
<div class="highlight-box"><p>La <strong>température de couleur</strong> de la lumière se mesure en Kelvins (K). Une lumière chaude (2 700-3 000 K, blanc chaud) crée une atmosphère cosy et relaxante, adaptée aux espaces de vie. Une lumière froide (4 000-6 500 K, blanc neutre à blanc lumière du jour) favorise la concentration et la vigilance, adaptée aux espaces de travail et aux cuisines.</p></div>
<h3>Les sources lumineuses artificielles</h3>
<p>La révolution technologique de l'éclairage artificiel s'est accélérée dans les années 2010 avec le triomphe de la diode électroluminescente (<strong>LED</strong>). Par rapport aux ampoules à incandescence qu'elles ont largement remplacées, les LED consomment 80 à 90% d'énergie en moins pour un flux lumineux équivalent, durent 25 à 50 fois plus longtemps (25 000 à 50 000 heures) et ne contiennent pas de mercure (contrairement aux ampoules fluorescentes compactes).</p>
<p>La qualité colorimétrique d'une source lumineuse est mesurée par l'<strong>indice de rendu des couleurs</strong> (IRC), de 0 à 100. Un IRC de 100 correspond au soleil. Les LED de haute qualité atteignent un IRC de 90+, garantissant une restitution fidèle des couleurs — essentielle dans les musées, les ateliers d'artistes, les boutiques de luxe et les espaces médicaux.</p>
<h3>Scénarios lumineux et design d'éclairage</h3>
<p>Le <strong>design d'éclairage</strong> est une discipline à part entière, à la frontière de l'architecture, du design intérieur et du génie électrique. Il distingue trois types de lumière complémentaires : l'<em>éclairage général</em> (lumière ambiante qui illumine uniformément l'espace), l'<em>éclairage d'accentuation</em> (met en valeur un objet, une œuvre ou un détail architectural) et l'<em>éclairage de tâche</em> (lumière fonctionnelle pour lire, cuisiner, travailler).</p>
<p>Les systèmes de <strong>domotique lumineuse</strong> permettent de programmer des scénarios (ambiance cinéma, dîner aux chandelles, réveil progressif) et de moduler instantanément l'intensité et la couleur de chaque source. Le concept de <em>human centric lighting</em> (éclairage centré sur l'humain) adapte dynamiquement la lumière au rythme circadien : lumière froide et vive le matin pour stimuler l'éveil, lumière chaude et tamisée le soir pour préparer le sommeil.</p>""",

"interieur/mobilier": """<h3>Histoire du mobilier occidental</h3>
<p>L'histoire du mobilier occidental reflète les transformations économiques, sociales et techniques de chaque époque. Le mobilier médiéval est rare, fonctionnel et mobile (les coffres servent de sièges, de tables et de rangements) ; sa rareté témoigne de la précarité des intérieurs avant la sédentarisation du confort domestique. La Renaissance voit l'apparition des grandes pièces de menuiserie sculptée — buffets, armoires, lits à baldaquin — qui définissent l'espace représentatif des intérieurs aristocratiques.</p>
<p>Le XVIIIe siècle est l'âge d'or de l'ébénisterie française. Les <em>menuisiers-ébénistes</em> parisiens — André-Charles Boulle avec ses incrustations d'écaille et de cuivre, Jean-François Oeben et Jean-Henri Riesener avec leurs mécanismes ingénieux — créent des pièces d'une sophistication technique et esthétique inégalée. Le bureau du Roi de Riesener (1769, Versailles) cumule les fonctions d'un bureau, d'un secrétaire et d'un classeur dans un meuble dont le mécanisme de fermeture simultanée est un chef-d'œuvre d'horlogerie appliqué au mobilier.</p>
<div class="highlight-box"><p>La distinction entre <strong>menuisier</strong> (assemblage de panneaux de bois) et <strong>ébéniste</strong> (décoration par placage de bois précieux, incrustation et marqueterie) date de 1743 en France. Cette spécialisation reflète la sophistication croissante du mobilier parisien, devenu une industrie de luxe exportée dans toute l'Europe.</p></div>
<h3>La révolution moderniste et ses icônes</h3>
<p>Le XXe siècle transforme radicalement le mobilier à travers deux révolutions simultanées : celle des matériaux (tube d'acier, contreplaqué moulé, fibre de verre, mousse polyuréthane) et celle des principes esthétiques (fonctionnalisme, abstraction géométrique). La chaise <strong>Cantilever</strong> de Mies van der Rohe (1927) en tube d'acier chromé — dont le siège « flotte » sans pied arrière — incarne la rencontre entre ingénierie structurelle et esthétique moderniste.</p>
<p>Le mobilier scandinave des années 1950-60 (Hans Wegner, Arne Jacobsen, Alvar Aalto) développe une troisième voie : fonctionnalisme tempéré par la chaleur des matériaux naturels et l'attention portée au confort ergonomique. La chaise 3107 d'Arne Jacobsen (1955) — dite « la chaise de profil Christine Keeler » — est le siège le plus vendu de toute l'histoire du design, avec plus de 5 millions d'exemplaires.</p>
<h3>Le mobilier contemporain : entre artisanat et numérique</h3>
<p>Le mobilier contemporain navigue entre des tendances contradictoires. Le retour à l'artisanat et aux matériaux naturels — en réaction à la globalisation du mobilier industriel — valorise les savoir-faire locaux et les essences de bois certifiées. Dans le même temps, l'<strong>impression 3D</strong> et la <strong>découpe numérique</strong> (CNC) permettent des formes impossibles à réaliser par les techniques traditionnelles et démocratisent la customisation de masse.</p>
<p>Les plateformes comme <strong>Ikea Hackers</strong> et la communauté makers illustrent une tendance au Do-It-Yourself qui réapproprie et transforme les objets produits industriellement. Cette culture du détournement, en dialogue permanent avec les designers professionnels, contribue à redéfinir les frontières entre consommation et création dans la culture matérielle contemporaine.</p>""",

"interieur/principes-amenagement": """<h3>Les fondamentaux de la composition spatiale</h3>
<p>L'aménagement intérieur repose sur des principes compositionnels hérités de l'architecture et des arts plastiques. L'<strong>échelle</strong> définit le rapport entre les dimensions des éléments et celles de l'espace : une erreur d'échelle (trop grand, trop petit) perturbe immédiatement la perception de la pièce. La <strong>proportion</strong> concerne les rapports dimensionnels entre les éléments entre eux et avec l'espace — le ratio d'or (1:1,618) est souvent cité comme proportion harmonieuse, mais son application rigide au design intérieur est un mythe.</p>
<p>L'<strong>équilibre</strong> peut être symétrique (axes de composition clairs, disposition en miroir) ou asymétrique (équilibre visuel par compensation de poids visuels différents). L'équilibre symétrique suggère la formalité, l'ordre et le classicisme ; l'équilibre asymétrique la modernité, la dynamisme et la décontraction. L'un et l'autre sont des outils selon l'ambiance recherchée.</p>
<div class="highlight-box"><p>Le concept de <strong>circulation</strong> en design d'intérieur désigne les chemins empruntés pour se déplacer dans l'espace. Une bonne circulation dégagée (au moins 90 cm de passage, idéalement 120 cm) est la condition de base d'un aménagement fonctionnel. La circulation primaire (axes de déplacement principaux) doit être libre ; la circulation secondaire peut être plus contrainte.</p></div>
<h3>Couleurs, lumières et matériaux : la cohérence sensorielle</h3>
<p>La <strong>couleur</strong> est l'un des outils les plus puissants — et les plus mal maîtrisés — de l'aménagement. Les règles classiques de composition colorée (couleurs complémentaires, couleurs analogues, règle 60-30-10) fournissent des cadres utiles : 60% de la couleur dominante (murs, sols), 30% d'une couleur secondaire (mobilier, textiles), 10% de couleur accent (accessoires, plantes, œuvres). Ces proportions peuvent varier, mais leur déséquilibre crée souvent une impression de désordre visuel.</p>
<p>La cohérence entre <strong>matériaux</strong> — au-delà de la seule couleur — est fondamentale. Les textures, les brillances et les masses visuelles des matériaux doivent dialoguer. Un espace cohérent mélange généralement deux à trois familles de matériaux (bois + métal + textile, ou béton + verre + cuir) plutôt qu'une accumulation disparate. La répétition des matériaux crée la continuité visuelle et la sérénité spatiale.</p>
<h3>Tendances contemporaines et pratiques professionnelles</h3>
<p>Le design d'intérieur contemporain est marqué par le <strong>biophilic design</strong> — l'intégration de la nature dans les espaces intérieurs (plantes, matériaux naturels, vues sur extérieur, lumière naturelle) pour améliorer le bien-être et la productivité. Des études ont montré que la présence de végétation en intérieur réduit le stress, améliore la concentration et diminue l'absentéisme dans les espaces de travail.</p>
<p>Le développement du travail hybride depuis 2020 a considérablement modifié les exigences des espaces domestiques, devenus bureaux à temps partiel. Cette nouvelle donne a relancé la demande en design d'intérieur pour des espaces multifonctionnels, des solutions acoustiques et des éclairages adaptés au travail sur écran — révélant l'impact direct des modes de vie sur les pratiques du design.</p>""",

"interieur/couleurs-materiaux": """<h3>La théorie des couleurs appliquée à l'intérieur</h3>
<p>La <strong>roue chromatique</strong>, développée par Itten au Bauhaus, est l'outil de base de la composition colorée. Elle organise les couleurs primaires (rouge, jaune, bleu), secondaires (orange, vert, violet) et tertiaires en un cercle continu qui permet de visualiser les relations harmoniques. Les <em>couleurs complémentaires</em> (opposées sur la roue) créent un contraste maximal et vibrant ; les <em>couleurs analogues</em> (voisines sur la roue) créent une harmonie douce et cohérente.</p>
<p>La psychologie des couleurs, bien que culturellement variable, reconnaît quelques constantes. Le bleu est universellement associé à la sérénité, la confiance et la profondeur — c'est la couleur la plus appréciée dans le monde. Le rouge stimule l'appétit et l'énergie (d'où son usage dans les restaurants et les cuisines). Le vert évoque la nature, le calme et la santé. Ces associations influencent les choix des designers d'intérieur, même si une interprétation rigide serait réductrice.</p>
<div class="highlight-box"><p>Le concept de <strong>valeur</strong> (clarté ou obscurité d'une couleur) est souvent plus important que la teinte elle-même dans la perception d'un espace. Les couleurs claires agrandissent visuellement les petits espaces et amplifient la lumière ; les couleurs sombres créent des cocons intimes mais nécessitent une lumière artificielle généreuse pour éviter la dépression visuelle.</p></div>
<h3>Les matériaux de revêtement et leurs caractéristiques</h3>
<p>Les <strong>parquets</strong> en bois massif ou contrecollé (couche de bois noble sur support aggloméré) sont appréciés pour leur chaleur, leur durabilité et leur capacité à être ponçés et rehuilés plusieurs fois. Les essences les plus communes sont le chêne (résistant, aux tonalités chaudes), le frêne (grain fin, couleur claire) et le noyer (brun chocolat, luxueux). L'orientation de la pose (parallèle, perpendiculaire, en biais, en chevrons) modifie significativement la perception de l'espace.</p>
<p>Le <strong>carrelage</strong> — grès cérame, faïence, pierre naturelle — offre une durabilité et une résistance à l'eau incomparables pour les espaces humides. Le format des carreaux influence la perception : les grands formats (60×60 cm et plus) minimisent les joints et agrandissent visuellement les petits espaces ; les petits formats (10×10 cm, mosaïques) créent de la texture et peuvent suivre des formes courbes.</p>
<h3>Tendances et évolutions des matériaux</h3>
<p>Les tendances des dernières années montrent un retour aux matériaux <strong>naturels et non traités</strong> : béton brut, terre cuite non vernissée, pierre calcaire, lin et coton naturels, bois massif aux nœuds apparents. Cette esthétique du wabi-sabi japonais — qui embrasse l'imperfection et la patine du temps — réagit contre la perfection froide des surfaces industrielles.</p>
<p>Les <strong>peintures à la chaux</strong>, les enduits argile et les badigeons à la caséine connaissent un renouveau important : leurs propriétés respirantes régulent l'humidité de l'air et créent des surfaces vivantes aux variations de couleur selon la lumière, impossibles à reproduire avec des peintures synthétiques. Ces matériaux anciens, revisités par des artisans contemporains, répondent à une demande d'authenticité et de liens avec les matières naturelles.</p>""",

"interieur/styles-decoration": """<h3>Les grands styles historiques et leur évolution</h3>
<p>L'histoire de la décoration intérieure est une suite de styles qui reflètent les goûts esthétiques, les valeurs sociales et les possibilités techniques de chaque époque. Le style <strong>baroque</strong> (XVIIe siècle) caractérise les intérieurs aristocratiques par l'exubérance ornementale, les dorures, les velours cramoisis et les trompe-l'œil. Versailles est son archétype : chaque surface est décorée, chaque meuble sculpté, chaque plafond peint. Ce style d'apparat vise à impressionner et à manifester la puissance du commanditaire.</p>
<p>Le style <strong>rococo</strong> (XVIIIe siècle) allège et féminise le baroque : les ornements se font plus légers, les couleurs plus pastel (rose, vert d'eau, lilas), les formes plus sinueuses. L'<em>asymétrie</em>, introduite comme principe décoratif, rompt avec la rigueur symétrique du baroque. Le salon de la Princesse à l'Hôtel de Soubise (1740, Paris) en est l'un des plus beaux exemples français.</p>
<div class="highlight-box"><p>La distinction entre <strong>style</strong> (ensemble de caractéristiques formelles d'une période ou d'un courant) et <strong>tendance</strong> (mode éphémère du moment) est fondamentale en décoration. Un style historique peut être réinterprété indéfiniment ; une tendance passe et rend rapidement les intérieurs datés. La connaissance des styles historiques protège contre la servitude aux tendances.</p></div>
<h3>Les styles contemporains : minimalisme, scandinave, industriel</h3>
<p>Le style <strong>minimaliste</strong>, héritage du modernisme et du zen japonais, réduit la décoration à l'essentiel : surfaces nues, mobilier sobre, peu d'objets, couleurs neutres. « Less is more » (Mies van der Rohe) est sa devise. Ce style, porté par des marques comme Muji, Aesop et certains intérieurs de maisons d'architecture, valorise l'espace vide comme élément de composition à part entière.</p>
<p>Le style <strong>scandinave</strong> (hygge) mêle fonctionnalisme moderniste et chaleur domestique : bois clair, textiles doux, bougies, végétaux, couleurs douces. Ce style, porté par Ikea mais aussi par une tradition d'artisanat danois et suédois de haute qualité, est devenu l'un des plus diffusés mondialement — sa lisibilité et son accessibilité en font un référentiel universel.</p>
<p>Le style <strong>industriel</strong> réhabilite les codes des espaces de travail du XIXe siècle : béton brut, métal apparent, briques rouges, conduits de ventilation visibles, mobilier de récupération ou de chantier. Né dans les lofts new-yorkais des années 1980, il s'est démocratisé dans les appartements urbains et les restaurants branchés des années 2000-2010.</p>
<h3>Éclectisme et personnalisation : vers un style personnel</h3>
<p>Le style <strong>éclectique</strong> — mélange assumé de références, d'époques et d'origines — est souvent la réalité des intérieurs les plus réussis. La règle n'est pas de suivre un style unique mais de créer une cohérence à travers des choix personnels : répétition de couleurs, d'une famille de matériaux ou d'un esprit commun entre des objets apparemment disparates.</p>
<p>Les réseaux sociaux (Instagram, Pinterest) ont transformé la façon dont les tendances décoratives circulent et s'imposent, créant une accélération des cycles de mode et un risque d'uniformisation des intérieurs. La résistance à cette uniformisation, par la valorisation des objets personnels, hérités ou chiné, est une des réactions les plus saines à la dictature des tendances.</p>""",

"graphique/design-numerique": """<h3>Fondements du design d'interface : UI et UX</h3>
<p>Le <strong>design numérique</strong> recouvre l'ensemble des pratiques de conception visuelle destinées aux médias numériques : sites web, applications mobiles, logiciels, interfaces embarquées. Il se divise en deux grandes disciplines complémentaires. L'<strong>UI Design</strong> (<em>User Interface</em>) s'occupe de l'apparence visuelle : couleurs, typographie, icônes, mise en page, hiérarchie visuelle. L'<strong>UX Design</strong> (<em>User Experience</em>) s'occupe de l'expérience globale : facilité d'usage, fluidité des parcours, accessibilité, satisfaction de l'utilisateur.</p>
<p>La distinction entre UI et UX est fondamentale mais parfois artificielle : une belle interface mal pensée frustre l'utilisateur autant qu'une interface fonctionnelle mais laide. Les meilleurs designers numériques maîtrisent les deux dimensions. Des outils comme Figma, Sketch et Adobe XD permettent de concevoir à la fois les visuels (UI) et les flux d'interaction (UX) dans un même environnement collaboratif.</p>
<div class="highlight-box"><p>Le principe de <strong>hiérarchie visuelle</strong> — organiser les éléments visuels selon leur importance relative — est la règle d'or du design d'interface. La taille, la couleur, le contraste, l'espacement et la position guident l'œil de l'utilisateur dans l'ordre voulu par le designer. Une hiérarchie bien conçue rend l'interface lisible en quelques secondes, même sans lire un mot.</p></div>
<h3>Le design responsive et l'ère mobile-first</h3>
<p>Depuis 2016, le trafic mobile dépasse le trafic desktop sur internet. Cette réalité impose une approche <strong>mobile-first</strong> : concevoir d'abord pour les petits écrans et enrichir progressivement pour les grands écrans, plutôt que l'inverse. Le <strong>design responsive</strong> (Ethan Marcotte, 2010) adapte automatiquement la mise en page aux dimensions de l'écran via des grilles fluides, des images flexibles et des media queries CSS.</p>
<p>La conception pour mobile impose des contraintes spécifiques : les zones tactiles doivent être suffisamment grandes (minimum 44×44 pixels selon les guidelines Apple et Google), les contenus doivent être chargés rapidement (optimisation des images, lazy loading), et la navigation doit être utilisable d'une seule main. Ces contraintes ont conduit à une simplification générale des interfaces numériques, bénéfique pour l'accessibilité tous publics.</p>
<h3>Design systems et composants réutilisables</h3>
<p>Les <strong>design systems</strong> — bibliothèques de composants UI réutilisables (boutons, formulaires, cartes, navigation) accompagnées de règles d'usage et de guidelines — sont devenus essentiels dans les équipes produit modernes. Les design systems publics de Google (Material Design), Apple (Human Interface Guidelines) et Airbnb ont défini les standards visuels et interactifs de millions d'applications.</p>
<p>L'avènement de l'<strong>IA générative</strong> dans le design numérique (outils comme Midjourney, DALL-E, Adobe Firefly) transforme profondément les workflows : génération d'images, création de variantes colorées, suggestion de layouts. Ces outils accélèrent certaines phases du design mais soulèvent des questions sur la valeur ajoutée des designers humains et sur les droits d'auteur des images d'entraînement.</p>""",
}

def replace_course_content(content_html, new_content_html):
    """Replace all content inside .course-content div in the contenu section."""
    start_marker = '<div class="course-content">'
    end_marker_quiz = '<section class="content-section" id="quiz">'

    start_idx = content_html.find(start_marker)
    if start_idx == -1:
        return content_html

    quiz_idx = content_html.find(end_marker_quiz)
    if quiz_idx == -1:
        return content_html

    # Find the last </div> before quiz — closes .course-content
    closing_div_idx = content_html.rfind('</div>', 0, quiz_idx)
    if closing_div_idx == -1:
        return content_html

    content_start = start_idx + len(start_marker)
    new_content = (content_html[:content_start] + '\n' +
                   new_content_html + '\n      ' +
                   content_html[closing_div_idx:])
    return new_content


path = os.path.join(BASE, 'design.json')
with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
modified = 0

for key, new_content_html in ENRICHMENTS.items():
    if key not in pages:
        print(f'MISSING: {key}')
        continue
    page = pages[key]
    old_len = len(page['content'])
    page['content'] = replace_course_content(page['content'], new_content_html)
    new_len = len(page['content'])
    print(f'  {key}: {old_len} → {new_len} ({new_len-old_len:+d})')
    modified += 1

print(f'\nTotal modifié : {modified}')

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Fichier sauvegardé.')
