import json

ENRICHMENTS_COMM = {
"theorie-communication/modeles-fondateurs": """
<h3>Shannon, Wiener et la révolution de l'information</h3>
<p class="resume-text">En 1948, Claude Shannon publie <em>A Mathematical Theory of Communication</em>, posant les bases de la théorie de l'information. Il y définit l'information comme une réduction de l'incertitude, mesurable en bits, et formalise les concepts de canal, de bruit, de redondance et d'entropie informationnelle. Le modèle de Shannon-Weaver (émetteur → encodage → canal → décodage → récepteur, avec perturbation par le bruit) est devenu le modèle de référence technique de la communication, fondement de l'ingénierie des télécommunications et d'internet.</p>
<p class="resume-text">Norbert Wiener développe simultanément la <strong>cybernétique</strong> (1948) — science du contrôle et de la communication dans les êtres vivants et dans les machines. Il introduit le concept de rétroaction (feedback) : toute communication efficace inclut un mécanisme par lequel le récepteur informe l'émetteur de l'effet de son message, permettant l'ajustement. Ce concept a profondément influencé les théories de la communication humaine, les systèmes de management et la conception des interfaces informatiques.</p>
<div class="highlight-box"><p>Le modèle de Shannon est souvent mal interprété : il porte sur la transmission d'un signal, pas sur la signification d'un message. Shannon lui-même avertissait que « les problèmes sémantiques de la communication sont indépendants du problème technique ». Cette distinction fondamentale entre signal (information technique) et sens (information sémantique) est au cœur de toutes les théories de la communication humaine.</p></div>
<h3>Lasswell, Lazarsfeld et les effets des médias</h3>
<p class="resume-text">Harold Lasswell synthétise en 1948 la communication en cinq questions : Qui dit quoi, par quel canal, à qui, avec quel effet ? Ce schéma linéaire, orienté vers l'analyse des effets de la propagande, domine les premières recherches en communication de masse. Il présuppose un émetteur actif et un récepteur passif — une vision que les recherches empiriques vont progressivement nuancer.</p>
<p class="resume-text">Paul Lazarsfeld, sociologue autrichien émigré aux États-Unis, conduit avec ses collègues les premières grandes études d'effets médiatiques par sondage (étude d'Erie County sur l'élection présidentielle de 1940). Ses conclusions surprennent : les médias ont des effets limités sur les convictions politiques des individus ; ce sont les <strong>leaders d'opinion</strong> (influenceurs locaux dans les groupes sociaux primaires — famille, voisins, collègues) qui relaient et amplifient — ou filtrent — les messages médiatiques. Ce modèle du <strong>flux à deux étages</strong> (two-step flow of communication) relativisait considérablement la toute-puissance supposée des médias de masse.</p>
<div class="highlight-box"><p>L'étude de Lazarsfeld sur la radio et les effets de la propagande a conduit à une conclusion paradoxale pour l'époque : les médias renforcent généralement les convictions existantes plutôt qu'ils ne les changent. C'est la théorie de l'<strong>exposition sélective</strong> : les individus tendent à s'exposer aux médias qui confirment leurs préjugés. Cette tendance est amplifiée à l'ère des algorithmes de recommandation qui créent des chambres d'écho.</p></div>
<h3>L'École de Palo Alto : une communication comme interaction</h3>
<p class="resume-text">Gregory Bateson, Paul Watzlawick et leurs collègues du Mental Research Institute de Palo Alto proposent dans les années 1960-1970 une révolution conceptuelle : la communication n'est pas une transmission linéaire d'information mais une <strong>interaction circulaire et permanente</strong>. Leur postulat le plus connu — « on ne peut pas ne pas communiquer » — souligne que tout comportement (y compris le silence et l'immobilité) véhicule une information dans une situation de co-présence.</p>
<p class="resume-text">L'École de Palo Alto distingue deux niveaux dans tout message : le <strong>contenu</strong> (ce qui est dit) et la <strong>relation</strong> (comment c'est dit, ce que le locuteur signale sur la nature de sa relation avec l'interlocuteur). Les paradoxes communicatifs — comme la double contrainte (double bind), injonction contradictoire mise en évidence dans les familles de schizophrènes — illustrent comment des dysfonctionnements de communication peuvent provoquer des pathologies psychiques. Cette approche systémique de la communication a profondément influencé la thérapie familiale et la communication organisationnelle.</p>
""",

"theorie-communication/semiologie-et-signes": """
<h3>Ferdinand de Saussure et la linguistique structurale</h3>
<p class="resume-text">Ferdinand de Saussure, dans son <em>Cours de linguistique générale</em> (1916, cours posthumes de ses étudiants), pose les bases de la linguistique structurale qui va révolutionner les sciences humaines au XXe siècle. Il distingue la <strong>langue</strong> (système abstrait et social) de la <strong>parole</strong> (usage individuel et concret), et le <strong>signifiant</strong> (image acoustique, forme sonore d'un mot) du <strong>signifié</strong> (concept mental auquel il renvoie). Le signe linguistique est arbitraire : aucun lien naturel n'unit le son « arbre » au concept d'arbre — c'est la convention sociale qui les associe.</p>
<p class="resume-text">La notion de <strong>valeur différentielle</strong> est centrale chez Saussure : chaque signe acquiert son sens non pas positivement (par ce qu'il désigne) mais négativement (par ce qu'il n'est pas). « Chat » signifie ce qu'il signifie parce qu'il s'oppose à « chien », « tigre », « félin », etc. Cette idée que le sens est produit par des différences et des oppositions sera au cœur du structuralisme en anthropologie (Lévi-Strauss), en littérature et en philosophie.</p>
<div class="highlight-box"><p>L'<strong>opposition syntagme/paradigme</strong> de Saussure éclaire la structuration du langage : sur l'axe syntagmatique (horizontal), les mots se combinent selon des règles syntaxiques (« le chat mange la souris ») ; sur l'axe paradigmatique (vertical), chaque mot pourrait être remplacé par un autre terme de la même catégorie grammaticale. Roman Jakobson a étendu cette distinction à toute la communication humaine, y compris la littérature et la musique.</p></div>
<h3>Charles Sanders Peirce et la triade sémiotique</h3>
<p class="resume-text">Le philosophe américain Charles Sanders Peirce développe une sémiotique différente de Saussure : ternaire et dynamique. Pour Peirce, tout signe met en jeu trois termes : le <strong>representamen</strong> (la forme physique du signe), l'<strong>objet</strong> (ce à quoi le signe se réfère) et l'<strong>interprétant</strong> (le sens produit dans l'esprit du récepteur). Peirce distingue trois types de signes selon leur relation à l'objet : l'<strong>icône</strong> (ressemblance, comme une photo), l'<strong>indice</strong> (lien existentiel, comme la fumée signalant le feu) et le <strong>symbole</strong> (convention arbitraire, comme un mot).</p>
<p class="resume-text">Cette trichotomie est devenue un outil d'analyse sémiotique très utilisé : une carte routière est une icône, une flèche directionnelle est un indice, un panneau stop est un symbole. Dans la communication publicitaire, les marques combinent ces trois types de signes : le logo iconique, l'indice d'authenticité (certification), le nom symbolique. La semiotique peircéenne, contrairement à celle de Saussure focalisée sur la langue, vise une théorie générale de tous les signes, des signes naturels (symptômes médicaux) aux signes culturels (rites, codes vestimentaires).</p>
<div class="highlight-box"><p>Le sémiologue français Roland Barthes a popularisé l'analyse sémiotique dans <em>Mythologies</em> (1957) et <em>Éléments de sémiologie</em> (1964). Il distingue deux niveaux de signification : la <strong>dénotation</strong> (sens littéral, premier degré) et la <strong>connotation</strong> (sens second, culturellement construit). La photo d'un enfant souriant connote l'innocence et la joie au-delà de sa dénotation littérale. Les mythes modernes (le steak-frites comme symbole d'identité française, la DS Citroën comme objet magique) fonctionnent en naturalisant des constructions culturelles historiquement situées.</p></div>
<h3>La sémiotique de l'image et des médias visuels</h3>
<p class="resume-text">L'analyse sémiotique des <strong>images publicitaires</strong> est l'un des champs les plus développés de la sémiotique appliquée. Une image publicitaire combine simultanément un message linguistique (le texte), un message iconique codé (les connotations culturelles des éléments visuels) et un message iconique littéral (la dénotation de l'image). Roland Barthes, dans son article fondateur « Rhétorique de l'image » (1964), montre comment la publicité pour les pâtes Panzani mobilise des associations culturelles (couleurs de l'Italie, fraîcheur des produits frais, sens de la fête) pour construire un univers de sens au-delà du simple produit commercial.</p>
<p class="resume-text">La <strong>sémiotique du cinéma</strong> (Christian Metz, <em>Essais sur la signification au cinéma</em>, 1968) a analysé les codes spécifiques du langage cinématographique : le gros plan qui signifie l'émotion, le fondu enchaîné qui signifie le passage du temps, le point de vue subjectif qui crée l'identification au personnage. Ces codes ne sont pas innés mais appris culturellement — un enfant non familiarisé avec le cinéma ne comprend pas automatiquement qu'une image floue signifie un souvenir ou qu'un fondu au noir signifie une ellipse temporelle.</p>
""",

"theorie-communication/communication-de-masse": """
<h3>L'histoire des médias de masse</h3>
<p class="resume-text">L'histoire des médias de masse est une histoire de ruptures technologiques successives. La <strong>presse Gutenberg</strong> (milieu du XVe siècle) révolutionne la communication en permettant la reproduction à grande échelle de textes, démocratisant l'accès à l'information et rendant possible la Réforme protestante. Les <strong>gazettes</strong> du XVIIe siècle (Gazette de France, 1631) inaugurent la presse périodique d'information. La <strong>presse de masse</strong> du XIXe siècle (penny press américaine, puis journaux à grand tirage comme Le Petit Parisien) atteint des millions de lecteurs grâce à la rotative, la publicité et la baisse des prix.</p>
<p class="resume-text">La <strong>radio</strong> (années 1920) crée pour la première fois un média synchrone atteignant simultanément des millions de personnes — révolution considérable pour la propagande politique (discours radiodiffusés de Roosevelt, de De Gaulle, d'Hitler), le divertissement de masse (feuilletons, musique) et l'information. La <strong>télévision</strong> (années 1950-1960) ajoute l'image et l'émotion, transformant l'expérience politique (débat Kennedy-Nixon, 1960) et culturelle (cérémonies mondiales retransmises en direct). Internet et les réseaux sociaux (années 2000-2010) brouillent la distinction entre émetteur et récepteur, entre professionnel et amateur, entre information et opinion.</p>
<div class="highlight-box"><p>Le <strong>modèle de McCombs et Shaw</strong> sur l'agenda-setting (1972) a montré empiriquement que si les médias ne disent pas aux gens quoi penser, ils déterminent largement sur quoi ils pensent. Les sujets couverts abondamment par les médias deviennent les préoccupations principales du public. L'agenda-setting de second niveau (framing) précise que les médias influencent non seulement l'importance accordée aux sujets mais aussi comment ces sujets sont cadrés et interprétés.</p></div>
<h3>Médias de masse et espace public</h3>
<p class="resume-text">Jürgen Habermas, dans <em>L'Espace public</em> (1962), analyse l'émergence au XVIIIe siècle d'un espace public bourgeois où des citoyens privés débattent publiquement de questions d'intérêt général. Les cafés, les salons et la presse émergente constituent les lieux de ce débat rationnel qui fonde la légitimité démocratique. Habermas diagnostique ensuite la dégradation de cet espace public au XXe siècle : la concentration des médias, la commercialisation de l'information et la société du spectacle transforment les citoyens délibérants en consommateurs passifs.</p>
<p class="resume-text">Cette analyse nourrit les critiques contemporaines des <strong>médias dominants</strong> et des <strong>réseaux sociaux</strong>. Si internet et les réseaux sociaux semblaient initialement promettre un renouveau de l'espace public démocratique (printemps arabes, mouvements sociaux en réseau), les espoirs ont été déçus par la fragmentation en bulles de filtre, la viralité des fausses informations, la polarisation des débats et la colonisation de l'attention par des logiques commerciales. La question de savoir comment les démocraties peuvent réguler les plateformes numériques sans censurer le débat public est l'un des grands défis politiques du XXIe siècle.</p>
<div class="highlight-box"><p>Marshall McLuhan, dans <em>Pour comprendre les médias</em> (1964), formule sa célèbre thèse : <strong>« Le médium, c'est le message. »</strong> Ce n'est pas le contenu d'un média qui est important mais le médium lui-même, qui reconfigure les perceptions et les structures sociales. La télévision ne transforme pas la société parce qu'elle diffuse tel ou tel contenu, mais parce qu'elle crée une forme d'expérience collective synchrone et passive. L'extension de cette thèse à internet et aux smartphones a produit une littérature abondante sur les effets neurologiques et sociaux des technologies numériques.</p></div>
<h3>L'économie politique des médias</h3>
<p class="resume-text">Les médias sont à la fois des industries culturelles et des institutions politiques. Leur structure de propriété influence leur contenu éditorial. La <strong>concentration des médias</strong> — quelques grands groupes contrôlant une part croissante de la production d'information — soulève des questions sur la diversité des voix et l'indépendance éditoriale. En France, des milliardaires comme Vincent Bolloré (CNews, Europe 1, JDD), Patrick Drahi (BFM, L'Express, RMC), Xavier Niel (Le Monde) possèdent les principales chaînes d'information et journaux, ce qui alimente un débat persistant sur l'indépendance des rédactions.</p>
<p class="resume-text">Noam Chomsky et Edward Herman, dans <em>La fabrication du consentement</em> (1988), proposent un modèle de propagande pour analyser les médias américains : cinq filtres (propriété des médias, publicité, sources officielles, représailles, anti-communisme) sélectionnent l'information qui atteint le public, produisant un consensus favorable aux élites économiques et politiques. Cette analyse marxisante est contestée pour son déterminisme, mais elle pointe des mécanismes réels de sélection de l'information qui ne relèvent pas nécessairement de la censure directe mais de l'auto-censure et de la normalisation éditoriale.</p>
""",

"theorie-communication/communication-interpersonnelle": """
<h3>La communication non verbale</h3>
<p class="resume-text">Albert Mehrabian a popularisé dans les années 1960 l'idée que la communication interpersonnelle serait composée à 7% de mots, 38% de ton et 55% de langage corporel. Cette règle « 7-38-55 » est en réalité une simplification abusive de recherches limitées portant spécifiquement sur les communications d'émotions, mais elle reflète une intuition juste : le <strong>para-verbal</strong> (intonation, rythme, volume, timbre) et le <strong>non-verbal</strong> (posture, gestes, expressions faciales, distance interpersonnelle) jouent un rôle crucial dans la communication humaine.</p>
<p class="resume-text">Edward Hall a développé le concept de <strong>proxémique</strong> (1966) — étude de l'utilisation sociale de l'espace. Il distingue quatre zones de distance interpersonnelle dans la culture américaine : la zone intime (0-45 cm, réservée aux proches), la zone personnelle (45-120 cm, relations amicales), la zone sociale (120-360 cm, relations professionnelles formelles), et la zone publique (au-delà de 360 cm, discours public). Ces distances varient significativement selon les cultures : les Français et les Méditerranéens ont des zones intime et personnelle plus petites que les Nord-Européens et les Japonais.</p>
<div class="highlight-box"><p>Les <strong>micro-expressions faciales</strong>, étudiées par Paul Ekman depuis les années 1960, sont des expressions fugitives (1/5 à 1/25 de seconde) révélant des émotions réelles que la personne tente de masquer. Ekman a identifié six émotions universelles (joie, tristesse, colère, peur, dégoût, surprise) qui s'expriment de façon identique dans toutes les cultures humaines, suggérant une base biologique pour l'expression émotionnelle. Ses travaux ont influencé les techniques d'interrogatoire policier, la formation des douaniers et la conception des personnages de synthèse dans les films d'animation.</p></div>
<h3>La communication dans les organisations</h3>
<p class="resume-text">La communication organisationnelle est un champ interdisciplinaire qui étudie comment la communication structure et est structurée par les organisations. Les travaux pionniers d'Elton Mayo (expériences d'Hawthorne, 1924-1932) ont montré que la productivité des ouvriers était influencée non seulement par les conditions physiques de travail mais aussi par les relations sociales et la communication au sein des groupes de travail — donnant naissance aux <strong>relations humaines</strong> comme champ de management.</p>
<p class="resume-text">La distinction entre <strong>communication formelle</strong> (circuits officiels hiérarchiques et fonctionnels) et <strong>communication informelle</strong> (bouche-à-oreille, couloir, réseaux d'affinité) est fondamentale dans les organisations. La communication informelle peut être plus rapide et plus riche que les circuits officiels, mais elle est aussi plus sujette aux rumeurs et aux déformations. La gestion de la communication de crise en entreprise illustre les enjeux de cette dualité : une communication officielle crédible est essentielle pour éviter que la communication informelle ne crée la panique ou la défiance.</p>
<div class="highlight-box"><p>L'<strong>intelligence émotionnelle</strong>, concept popularisé par Daniel Goleman dans les années 1990, désigne la capacité à percevoir, comprendre et gérer ses propres émotions et celles des autres. Elle comprendrait cinq dimensions : la conscience de soi émotionnelle, la maîtrise de soi, la motivation intrinsèque, l'empathie et les compétences sociales. Bien que le concept soit controversé sur le plan psychométrique, il a eu une influence considérable sur les pratiques de management et de leadership, revalorisant les compétences relationnelles dans les organisations.</p></div>
<h3>La communication interculturelle</h3>
<p class="resume-text">Geert Hofstede a conduit dans les années 1970 une étude comparative dans 72 pays sur les valeurs culturelles au travail, impliquant des employés d'IBM. Il en a dégagé initialement quatre puis six <strong>dimensions culturelles</strong> : distance hiérarchique (acceptance de l'inégalité de pouvoir), individualisme vs collectivisme, masculinité vs féminité (orientation compétition vs coopération), évitement de l'incertitude, orientation à long terme vs court terme, indulgence vs retenue. Ces dimensions permettent de prédire les styles de communication, de management et de négociation selon les cultures.</p>
<p class="resume-text">La <strong>communication interculturelle</strong> s'est développée comme champ académique et pratique avec la mondialisation des entreprises. Des modèles comme le <strong>Trompenaars Cultural Dimensions Model</strong> ou la <strong>carte culturelle</strong> d'Erin Meyer (<em>The Culture Map</em>, 2014) aident les managers internationaux à anticiper les malentendus culturels. Meyer distingue par exemple des cultures de communication directe (Néerlandais, Israéliens, Allemands) et indirecte (Japonais, Coréens, Chinois), des cultures à haut contexte (où le non-dit est essentiel) et bas contexte (où tout est explicite). Ces typologies sont des outils de sensibilisation, non des stéréotypes rigides.</p>
""",

"theorie-communication/rhetorique-et-persuasion": """
<h3>Aristote et les trois modes de persuasion</h3>
<p class="resume-text">Aristote, dans sa <em>Rhétorique</em> (IVe siècle av. J.-C.), systématise l'art oratoire en distinguant trois types de preuves rhétoriques : l'<strong>ethos</strong> (crédibilité et caractère de l'orateur), le <strong>pathos</strong> (appel aux émotions de l'auditoire) et le <strong>logos</strong> (argumentation logique et factuelle). Un discours persuasif efficace mobilise les trois dimensions : l'orateur doit d'abord établir sa crédibilité (ethos), toucher émotionnellement son auditoire (pathos) puis convaincre par des arguments solides (logos). La préséance relative de ces trois registres varie selon les cultures et les contextes.</p>
<p class="resume-text">Aristote distingue aussi trois genres oratoires : le <strong>judiciaire</strong> (accusation et défense devant un tribunal), le <strong>délibératif</strong> (conseil sur l'action future dans les assemblées politiques) et l'<strong>épidictique</strong> (éloge et blâme dans les cérémonies). Cette classification reste pertinente pour analyser les discours contemporains : un débat télévisé est principalement délibératif, un discours d'investiture est épidictique, un réquisitoire judiciaire est judiciaire — avec des emprunts à chaque registre.</p>
<div class="highlight-box"><p>Robert Cialdini, dans <em>Influence : The Psychology of Persuasion</em> (1984), identifie six principes universels d'influence sociale : la réciprocité, la rareté, l'autorité, la cohérence, la preuve sociale et l'appréciation (sympathie). Ces principes, issus de recherches empiriques en psychologie sociale, expliquent les tactiques de vente, de marketing politique et de manipulation. Ils sont enseignés dans les écoles de commerce et utilisés — parfois de façon manipulatoire — dans le marketing numérique et la communication politique.</p></div>
<h3>La propagande et ses techniques</h3>
<p class="resume-text">Edward Bernays, neveu de Sigmund Freud et fondateur des relations publiques modernes, a théorisé dans <em>Propaganda</em> (1928) comment les techniques de manipulation des masses peuvent être utilisées à des fins commerciales et politiques. Il a orchestré pour l'American Tobacco Company une campagne faisant des cigarettes des symboles d'émancipation féminine (les Torches of Freedom, 1929) — un exemple canonique de manipulation symbolique. Bernays affirmait que la manipulation invisible de l'opinion publique était nécessaire dans une démocratie où la masse n'était pas capable de raisonner correctement.</p>
<p class="resume-text">La propagande politique du XXe siècle a raffiné ces techniques. Le ministère de la Propagande nazi dirigé par Goebbels combinait contrôle total des médias, répétition systématique des messages clés, appel aux émotions et à l'identité, désignation d'un ennemi commun et mise en scène spectaculaire (rallyes de Nuremberg filmés par Leni Riefenstahl). L'<strong>Institut pour l'analyse de la propagande</strong> américain (1937) avait identifié sept techniques de propagande : name calling (étiquettes négatives), glittering generalities (généralités séduisantes), transfer (transfert d'autorité), testimonial, plain folks (identification au peuple), card stacking (argumentation partiale) et bandwagon (tout le monde le fait).</p>
<div class="highlight-box"><p>La notion de <strong>désinformation</strong> se distingue de la propagande par son caractère délibérément trompeur : la propagande peut être partisane sans être nécessairement fausse, la désinformation diffuse de fausses informations intentionnellement. La distinction avec la <em>misinformation</em> (fausses informations non intentionnelles) et la <em>malinformation</em> (informations vraies utilisées à des fins néfastes) est importante pour analyser l'information polluted information environment contemporain.</p></div>
<h3>La rhétorique à l'ère numérique</h3>
<p class="resume-text">Les réseaux sociaux ont transformé les pratiques rhétoriques politiques. La brièveté imposée par Twitter (280 caractères) favorise les formules chocs au détriment de l'argument développé. La viralité récompense les contenus émotionnellement engageants — indignation, humour, identité tribale — plutôt que les analyses nuancées. Les <strong>mèmes politiques</strong> et les <strong>formats courts</strong> (TikTok, Reels) sont devenus des vecteurs rhétoriques majeurs, adaptant à la culture numérique des techniques de persuasion ancestrales.</p>
<p class="resume-text">La <strong>communication politique computationnelle</strong> (Computational Political Communication) utilise les données massives des réseaux sociaux, le ciblage algorithmique et parfois des armées de bots pour influencer l'opinion publique à grande échelle. Les révélations sur Cambridge Analytica (2018) ont montré comment les données de Facebook avaient été utilisées pour un micro-ciblage politique personnalisé lors du Brexit et de l'élection Trump. Ces pratiques posent des questions fondamentales sur la démocratie à l'ère des données et la manipulation algorithmique du discours public.</p>
""",

"journalisme/histoire-de-la-presse": """
<h3>Des gazettes aux journaux de masse</h3>
<p class="resume-text">La <strong>presse moderne</strong> naît au XVIIe siècle avec les premières publications périodiques. La <em>Gazette de France</em> (1631), fondée sous le patronage de Richelieu, est l'une des premières publications d'information régulière en France, reflétant dès ses origines la tension entre information et pouvoir politique. En Angleterre, les <em>newsbooks</em> de la Révolution puritaine (1640) marquent une libéralisation de la presse. John Milton, dans son <em>Areopagitica</em> (1644), formule pour la première fois un plaidoyer théorique pour la liberté de la presse — argument repris par John Stuart Mill au XIXe siècle.</p>
<p class="resume-text">La <strong>presse à un penny</strong> (penny press) américaine des années 1830 révolutionne le modèle économique : en réduisant le prix au niveau des classes populaires et en finançant le journal par la publicité plutôt que par les abonnements, elle crée le premier vrai journalisme de masse. Le <em>New York Sun</em> (1833) et le <em>New York Herald</em> (1835) inaugurent un journalisme orienté vers le sensationnel, les faits divers et les informations locales plutôt que vers les commentaires politiques partisans. Ce modèle économique — lecteurs massifs vendus aux annonceurs — restera dominant jusqu'à internet.</p>
<div class="highlight-box"><p>La bataille entre William Randolph Hearst (<em>New York Journal</em>) et Joseph Pulitzer (<em>New York World</em>) pour les lecteurs dans les années 1890 a donné naissance au terme <strong>yellow journalism</strong> (journalisme jaune) : presse sensationnaliste, partiale, exploitant émotions et scandales pour vendre des journaux. La couverture de la guerre hispano-américaine (1898) est souvent citée comme exemple de presse ayant influencé, voire manipulé, l'opinion publique pour précipiter une guerre.</p></div>
<h3>La presse et la démocratie</h3>
<p class="resume-text">La presse libre est traditionnellement considérée comme le « quatrième pouvoir » — contrepoids aux trois pouvoirs constitutionnels (exécutif, législatif, judiciaire). La théorie normative de la presse libérale (John Stuart Mill, Walter Lippmann, Walter Williams) lui attribue trois fonctions démocratiques : <strong>informer</strong> les citoyens (leur fournir les informations nécessaires pour exercer leur jugement), <strong>surveiller</strong> le pouvoir (chien de garde de la démocratie, watchdog journalism), et <strong>faciliter le débat</strong> public (offrir un forum aux différentes opinions).</p>
<p class="resume-text">Cette vision normative contraste avec la réalité économique et politique des médias. La <strong>concentration de la propriété des médias</strong>, la dépendance à la publicité (qui oriente les contenus vers les audiences les plus rentables pour les annonceurs), les liens entre propriétaires de médias et pouvoir économique et politique — ces facteurs structurels limitent l'indépendance réelle de la presse. Les théories critique et économique politique des médias (Chomsky, Herman) soulignent que la presse « libre » peut paradoxalement produire un conformisme idéologique plus efficace que la censure directe, car il est auto-construit et invisible.</p>
""",

"journalisme/deontologie-journalistique": """
<h3>Les chartes déontologiques et leurs principes</h3>
<p class="resume-text">La déontologie journalistique s'est structurée au cours du XXe siècle à travers des chartes professionnelles nationales et internationales. La <strong>Charte de Munich</strong> (1971), adoptée par des syndicats de journalistes européens et référence française, définit dix devoirs du journaliste : respecter la vérité, défendre la liberté de l'information, ne publier que les informations dont l'origine est connue, ne pas supprimer informations essentielles, ne pas recourir à des méthodes déloyales, ne pas divulguer les sources confidentielles, ne pas confondre journalisme et publicité, refuser toute pression et ne jamais confondre le fait avec l'opinion.</p>
<p class="resume-text">La <strong>Société des journalistes</strong> (Society of Professional Journalists) américaine a adopté des principes similaires articulés autour de quatre valeurs : chercher la vérité et la rapporter, minimiser les préjudices (harm minimization), agir de façon indépendante, et être responsable et transparent. Ces principes doivent être appliqués dans des situations concrètes souvent complexes : comment identifier une source anonyme qui ment ? Comment couvrir une victime sans l'instrumentaliser ? Jusqu'où peut-on aller dans le journalisme d'investigation pour obtenir des documents confidentiels ?</p>
<div class="highlight-box"><p>Le <strong>off the record</strong> et ses variantes (background, deep background) sont des conventions cruciales du journalisme qui permettent aux sources de fournir des informations confidentielles sans être citées. Ces conventions non écrites, fondées sur la confiance mutuelle, sont essentielles pour l'accès aux informations sensibles mais créent aussi des risques : manipulation des journalistes par des sources intéressées, récits non vérifiables, confusion entre information et rumeur officielle.</p></div>
<h3>Les conflits d'intérêts et l'indépendance éditoriale</h3>
<p class="resume-text">L'indépendance éditoriale est le principe selon lequel les décisions rédactionnelles doivent être prises par les journalistes selon des critères journalistiques, sans interférence des propriétaires, des actionnaires, des annonceurs ou des pouvoirs politiques. En pratique, cette indépendance est menacée de multiples façons : pressions directes des actionnaires sur les rédacteurs en chef (comme lors des controverses autour de CNews en France), autocensure des journalistes qui anticipent les réactions de leur direction, influence des dépenses de publicité institutionnelle des grandes entreprises sur les sujets traités.</p>
<p class="resume-text">Le conflit entre <strong>information et publicité</strong> est une tension permanente dans les médias commerciaux. Les <strong>publireportages</strong> (contenu éditorial payé par des annonceurs) et le <strong>native advertising</strong> (publicité conçue pour ressembler à un article journalistique) brouillent les frontières entre information et promotion commerciale. La réglementation impose en général une signalisation claire (mention « publicité » ou « communiqué »), mais la reconnaissance par les lecteurs reste insuffisante, selon de nombreuses études.</p>
""",

"journalisme/journalisme-investigation": """
<h3>Les grandes enquêtes qui ont changé le monde</h3>
<p class="resume-text">Le journalisme d'investigation a marqué quelques moments majeurs de l'histoire contemporaine. L'affaire du <strong>Watergate</strong> (1972-1974) est le cas d'école : deux jeunes journalistes du <em>Washington Post</em>, Bob Woodward et Carl Bernstein, guidés par la source mystérieuse Deep Throat (qui s'avérera être le directeur adjoint du FBI, Mark Felt), ont remonté la piste de l'effraction au siège du Parti démocrate jusqu'au président Nixon, le contraignant à démissionner. Cette enquête a établi pour plusieurs générations l'idéal du journalisme d'investigation comme gardien de la démocratie.</p>
<p class="resume-text">Les <strong>Panama Papers</strong> (2016), <strong>Paradise Papers</strong> (2017) et <strong>Pandora Papers</strong> (2021) illustrent l'évolution vers le journalisme d'investigation collaboratif à grande échelle : le Consortium international des journalistes d'investigation (ICIJ) réunit des centaines de journalistes de dizaines de pays pour analyser en parallèle des ensembles massifs de données financières fuités. Les Panama Papers (11,5 millions de documents de 214 000 sociétés offshore) ont exposé les structures de dissimulation fiscale et d'enrichissement illicite de dirigeants politiques, hommes d'affaires et sportifs du monde entier, provoquant des démissions et des poursuites judiciaires.</p>
<div class="highlight-box"><p>L'enquête <strong>#MeToo</strong> du <em>New York Times</em> (Jodi Kantor, Megan Twohey) et du <em>New Yorker</em> (Ronan Farrow) sur Harvey Weinstein (2017) illustre le journalisme d'investigation au service des victimes. Plus de 80 femmes ont témoigné d'agressions et de harcèlement sexuels. Cette enquête a déclenché le mouvement #MeToo à l'échelle mondiale, forçant une prise de conscience sur les comportements prédateurs dans les industries du spectacle, de la presse, de la politique et bien au-delà.</p></div>
<h3>Les défis du journalisme d'investigation à l'ère numérique</h3>
<p class="resume-text">Internet a à la fois renforcé et fragilisé le journalisme d'investigation. D'un côté, les lanceurs d'alerte peuvent transmettre des gigantesques quantités de documents numériques (Edward Snowden avec 1,7 million de fichiers de la NSA, Chelsea Manning avec les dossiers diplomatiques de WikiLeaks) ; les bases de données ouvertes et les registres en ligne permettent des recherches plus rapides ; la collaboration internationale facilite les grandes enquêtes transfrontalières. De l'autre côté, la crise du modèle économique de la presse (chute des revenus publicitaires avec internet) a drastiquement réduit les ressources allouées aux enquêtes longues et coûteuses.</p>
<p class="resume-text">La <strong>protection des sources</strong> est devenue plus difficile à l'ère de la surveillance numérique. Les métadonnées téléphoniques, les emails tracés, les logs de connexion permettent aux gouvernements de retrouver des sources que les journalistes pensaient protégées. Des journalistes ont été arrêtés et poursuivis pour espionnage (James Risen aux États-Unis, des journalistes en France via le secret défense). L'utilisation d'outils de communication chiffrés (Signal, SecureDrop) est devenue une nécessité pour les journalistes d'investigation travaillant sur des sujets sensibles.</p>
""",

"journalisme/photojournalisme": """
<h3>L'histoire du photojournalisme</h3>
<p class="resume-text">La photographie entre dans la presse illustrée avec l'invention de la similigravure (halftone process) dans les années 1880, permettant pour la première fois de reproduire des photos dans les journaux. Les premières agences photos naissent dans les années 1920-1930 : Wide World Photos (1919), AP Photos, puis Magnum Photos (1947), cofondée par Henri Cartier-Bresson, Robert Capa, David Seymour et Georges Rodger, tous vétérans de la Seconde Guerre mondiale. Magnum, coopérative de photographes, incarne un modèle original où les photographes conservent leurs droits et s'imposent des standards éthiques exigeants.</p>
<p class="resume-text">La <strong>photographie de guerre</strong> a produit certaines des images les plus puissantes de l'histoire contemporaine : la photo de Robert Capa du Milicien mort (Guerre civile espagnole, 1936), le Napalm Girl de Nick Ut (Vietnam, 1972), la Petite fille vulture de Kevin Carter (Soudan, 1993, prix Pulitzer). Ces images ont-elles changé l'histoire ? La question est débattue. Susan Sontag, dans <em>Sur la photographie</em> (1977) et <em>Devant la douleur des autres</em> (2003), analyse la façon dont les images de souffrance peuvent provoquer la compassion mais aussi engourdir les spectateurs par surexposition et créer une esthétisation du malheur.</p>
<div class="highlight-box"><p>La <strong>controverse sur la photo de Kevin Carter</strong> — un vautour attendant la mort d'un enfant au Soudan — illustre les dilemmes éthiques du photojournalisme. Carter a reçu le prix Pulitzer pour cette image (1994) mais a été critiqué pour ne pas avoir aidé l'enfant. Quelques mois après la remise du prix, il s'est suicidé, en proie à la dépression. Cette affaire a relancé le débat : où s'arrête la responsabilité du témoin et où commence la responsabilité du citoyen ?</p></div>
<h3>L'ère numérique et la vérification des images</h3>
<p class="resume-text">La démocratisation des appareils photo numériques et des smartphones a transformé le photojournalisme. Les témoins ordinaires capturent maintenant des événements avant les professionnels (vidéo de l'arrestation de George Floyd par un passant, 2020). Les agences et les rédactions reçoivent des milliers d'images par heure lors d'événements majeurs. Cette abondance crée un défi de <strong>vérification</strong> : distinguer les images authentiques des images truquées, datées et géolocalisées de façon erronée, ou sorties de leur contexte.</p>
<p class="resume-text">La <strong>vérification (fact-checking) visuelle</strong> est devenue une compétence journalistique essentielle. Des outils comme Google Reverse Image Search, TinEye, InVID ou FotoForensics permettent de retrouver l'origine d'une image, détecter des manipulations et vérifier la cohérence de la géolocalisation et de la date. Les cellules de vérification (Bellingcat, BBC Verify, AFP Factuel, Les Décodeurs du Monde) se sont spécialisées dans ce travail. L'essor des deepfakes — images et vidéos synthétiques générées par IA — rend ce travail de vérification de plus en plus difficile et urgent.</p>
""",

"journalisme/avenir-du-journalisme": """
<h3>La crise du modèle économique de la presse</h3>
<p class="resume-text">Le <strong>modèle économique de la presse</strong> est sous pression depuis l'essor d'internet. Les revenus publicitaires, qui finançaient l'essentiel du journalisme commercial, ont migré vers Google et Facebook (les deux plateformes captent environ 70% des dépenses publicitaires numériques mondiales), laissant les médias traditionnels avec des ressources drastiquement réduites. Les ventes de journaux en kiosque s'effondrent dans tous les pays développés. Les journaux américains ont perdu les deux tiers de leurs salariés entre 2004 et 2020. En France, le secteur bénéficie d'aides publiques considérables (700 millions d'euros par an), mais celles-ci ne compensent pas la baisse des revenus commerciaux.</p>
<p class="resume-text">Les <strong>nouveaux modèles économiques</strong> qui émergent sont variés : abonnement numérique (<em>New York Times</em>, <em>Le Monde</em>), modèle de contribution libre (<em>The Guardian</em>), fondations philanthropiques (<em>ProPublica</em>, <em>The Conversation</em>), membership (<em>Mediapart</em>), financement participatif (Ulule, Kickstarter), subventions gouvernementales directes ou indirectes. Ces modèles expriment une fragilité commune : aucun ne génère les ressources suffisantes pour financer un journalisme d'investigation robuste à grande échelle.</p>
<div class="highlight-box"><p><strong>Substack</strong> et les newsletters à abonnement représentent une désintermédiation croissante du journalisme : des journalistes individuels construisent leur lectorat directement, sans passer par une rédaction. Cette tendance offre une indépendance éditoriale maximale et peut être économiquement viable pour des créateurs à forte audience, mais elle fragmente l'information et réduit les ressources collectives (fact-checking, réseaux de correspondants) que seules les grandes rédactions peuvent mobiliser.</p></div>
<h3>Intelligence artificielle et avenir des professions journalistiques</h3>
<p class="resume-text">L'<strong>intelligence artificielle générative</strong> (ChatGPT, Gemini, Claude) représente un défi existentiel pour certaines formes de journalisme. Des articles financiers standardisés (résultats d'entreprises, bulletins météo, résultats sportifs) sont déjà produits automatiquement par des logiciels (Automated Insights, Narrative Science) depuis les années 2010. Les grands modèles de langage peuvent désormais produire des articles informatifs de bonne qualité sur des sujets larges en quelques secondes.</p>
<p class="resume-text">Face à cette automatisation, les journalistes sont incités à se concentrer sur ce que l'IA ne peut pas faire : l'enquête de terrain (aller voir, interviewer, fouiller des archives), le jugement éditorial (qu'est-ce qui est important ?), la contextualisation et l'analyse de sujets complexes, la narration engageante, le dialogue avec les sources et les sujets. Les rédactions expérimentent l'<strong>IA comme outil d'assistance</strong> — aide à la vérification, transcription automatique, recherche documentaire — plutôt que comme substitut au journaliste. La réglementation des médias produits par IA (obligation de signalement, responsabilité en cas d'erreur) est un chantier législatif en cours dans de nombreux pays.</p>
""",

"medias-numeriques/histoire-internet": """
<h3>Des origines militaires à la démocratisation</h3>
<p class="resume-text">Internet trouve ses origines dans l'<strong>ARPANET</strong> (Advanced Research Projects Agency Network), réseau financé par le département américain de la Défense dans les années 1960 pour permettre des communications décentralisées résistant à une attaque nucléaire. Le premier message d'ARPANET (octobre 1969) connectait l'université UCLA à Stanford Research Institute : il s'agissait du mot « login » dont les deux premières lettres avaient été transmises avant que le système ne plante. Les protocoles TCP/IP (1974, Vint Cerf et Bob Kahn) unifient ensuite les réseaux hétérogènes en un réseau des réseaux.</p>
<p class="resume-text">Le <strong>World Wide Web</strong>, inventé par Tim Berners-Lee au CERN (1989-1991), transforme internet en espace de publication et de navigation accessible au grand public, via les navigateurs (Mosaic, 1993, puis Netscape). La commercialisation d'internet au début des années 1990 et la bulle internet (1995-2000) accélèrent son expansion mondiale. Le Web 2.0 (milieu des années 2000) marque le passage d'un web de consultation à un web de participation : wikis, blogs, réseaux sociaux, YouTube permettent à tous de produire et partager du contenu. L'essor des smartphones (iPhone, 2007) rend internet omniprésent et permanent.</p>
<div class="highlight-box"><p>L'<strong>économie des plateformes</strong> (GAFAM — Google, Apple, Facebook, Amazon, Microsoft) a concentré une part croissante de la valeur économique et de l'attention en ligne dans quelques entreprises américaines. Ces plateformes sont des acteurs politiques, économiques et culturels d'une puissance sans précédent historique : Facebook (Meta) réunit 3 milliards d'utilisateurs actifs mensuels, YouTube est consulté chaque minute pour 500 heures de vidéos uploadées. Cette concentration soulève des questions antitrust, de souveraineté numérique et de responsabilité dans la régulation des contenus.</p></div>
<h3>La fracture numérique</h3>
<p class="resume-text">Malgré la diffusion rapide d'internet, la <strong>fracture numérique</strong> (digital divide) persiste à plusieurs niveaux. La fracture d'accès : en 2023, environ 2,7 milliards de personnes n'ont toujours pas accès à internet, concentrées en Afrique subsaharienne, en Asie du Sud et dans les zones rurales mondiales. La fracture d'usage : même avec un accès, les compétences numériques (littératie numérique) varient considérablement selon l'âge, le niveau d'éducation et le milieu social. La fracture de qualité : l'accès via un smartphone 3G en Afrique et l'accès via la fibre optique en Corée du Sud sont techniquement « internet » mais représentent des expériences très différentes.</p>
<p class="resume-text">Les <strong>politiques d'inclusion numérique</strong> tentent de réduire ces fractures : déploiement de la fibre et de la 4G/5G, équipement des écoles, formation aux usages numériques. Des initiatives privées comme le <em>Free Basics</em> de Facebook (internet gratuit mais limité à certains services) ont suscité des controverses sur la neutralité du net : proposer un accès gratuit mais partiel revient à favoriser certains services au détriment d'autres, ce qui viole le principe selon lequel tout contenu doit être accessible dans les mêmes conditions.</p>
""",

"medias-numeriques/reseaux-sociaux": """
<h3>L'histoire des réseaux sociaux numériques</h3>
<p class="resume-text">Les réseaux sociaux numériques ont une histoire plus longue que leur popularisation grand public ne le suggère. Les premières communautés en ligne émergent dès les années 1970-1980 avec les BBS (Bulletin Board Systems) et Usenet (1980). Les réseaux sociaux modernes naissent dans les années 1990-2000 : SixDegrees (1997), premier site permettant la création d'un profil et la connexion avec des amis ; Friendster (2002) ; MySpace (2003, qui domine le marché avant d'être dépassé par Facebook) ; LinkedIn (2003, réseau professionnel) ; Facebook (2004, d'abord réservé aux étudiants d'Harvard puis universellement accessible dès 2006).</p>
<p class="resume-text">Chaque nouvelle plateforme a apporté une innovation dans les formats de communication sociale : Twitter (2006) avec le microblogging en 140 puis 280 caractères ; Instagram (2010) avec la primauté de l'image carrée filtrée ; Snapchat (2011) avec l'éphémère et les stories ; TikTok (2016) avec les vidéos courtes verticales et l'algorithme de recommandation qui dépasse le réseau social pour devenir un réseau d'intérêts. Chaque plateforme crée ses propres normes de communication, ses codes esthétiques et ses dynamiques sociales spécifiques.</p>
<div class="highlight-box"><p>Le <strong>rôle des réseaux sociaux dans les mouvements politiques</strong> est complexe. Les Printemps arabes (2010-2011) ont popularisé l'image de la révolution par Facebook et Twitter. Des analyses ultérieures ont nuancé ce récit : les réseaux sociaux ont facilité la coordination des manifestants mais les révolutions avaient des causes profondes économiques et politiques indépendantes d'internet. De même, les mouvements autoritaires utilisent les mêmes outils pour surveiller, contre-mobiliser et réprimer.</p></div>
<h3>L'économie de l'attention et le modèle publicitaire</h3>
<p class="resume-text">Le modèle économique dominant des réseaux sociaux est la <strong>publicité ciblée</strong> : les plateformes offrent des services gratuits aux utilisateurs en échange de leurs données comportementales, qu'elles utilisent pour vendre des audiences ultra-ciblées aux annonceurs. Ce modèle, souvent résumé par la formule « si c'est gratuit, c'est vous le produit », repose sur la maximisation du temps passé sur la plateforme. Les algorithmes de recommandation sont optimisés pour l'engagement — la réaction émotionnelle, la durée de visionnage, la probabilité de partager — ce qui favorise les contenus extrêmes, clivants et émotionnellement activants.</p>
<p class="resume-text">Shoshana Zuboff nomme <strong>« capitalisme de surveillance »</strong> ce régime économique dans lequel les données comportementales des individus — collectées massivement, analysées par IA et transformées en prédictions comportementales — sont vendues à des clients qui veulent influencer les comportements (annonceurs commerciaux, partis politiques). Cette analyse radicale dépasse la simple critique publicitaire pour pointer vers une transformation du rapport entre individus et grandes entreprises technologiques, où les entreprises détiennent plus d'informations sur les individus que les individus eux-mêmes.</p>
""",

"medias-numeriques/algorithmes-et-filtres": """
<h3>Comment fonctionnent les algorithmes de recommandation</h3>
<p class="resume-text">Les <strong>algorithmes de recommandation</strong> sont des systèmes d'apprentissage automatique qui sélectionnent et ordonnent les contenus présentés à chaque utilisateur en fonction de ses comportements passés. Ils analysent des milliers de signaux : clics, durée de visionnage, partages, commentaires, listes d'amis, localisation géographique, heure de connexion. Ces systèmes de <strong>filtrage collaboratif</strong> et de <strong>filtrage basé sur le contenu</strong> sont combinés pour prédire ce qui gardera l'utilisateur engagé le plus longtemps sur la plateforme.</p>
<p class="resume-text">Les algorithmes de TikTok, réputés pour leur efficacité presque hypnotique, fonctionnent différemment des réseaux sociaux classiques : plutôt que de recommander du contenu de votre réseau social, ils recommandent du contenu susceptible de vous plaire basé sur votre comportement de visionnage, indépendamment de votre réseau. Ce système de « graphe d'intérêts » plutôt que « graphe social » permet à TikTok de créer une expérience hyper-personnalisée qui maximise l'engagement mais favorise aussi l'exploration de niches très spécifiques — qu'il s'agisse d'oiseaux rares, de cuisine régionale ou de théories complotistes.</p>
<div class="highlight-box"><p>La <strong>bulle de filtre</strong> (filter bubble), théorisée par Eli Pariser dans <em>Filter Bubble: What the Internet Is Hiding from You</em> (2011), décrit comment les algorithmes personnalisent l'information au point que chaque utilisateur vit dans une bulle informationnelle adaptée à ses préférences, sans être exposé aux points de vue divergents. Des études empiriques montrent cependant que l'effet est plus nuancé : les algorithmes peuvent aussi exposer les utilisateurs à des contenus inattendus et la polarisation observée en ligne reflète parfois des clivages sociaux préexistants plutôt qu'elle ne les crée.</p></div>
<h3>La régulation des algorithmes</h3>
<p class="resume-text">La régulation des algorithmes de recommandation est devenue un enjeu politique majeur. Le <strong>Digital Services Act</strong> (DSA) européen, adopté en 2022 et entré en vigueur en 2024, impose aux très grandes plateformes (plus de 45 millions d'utilisateurs dans l'UE) des obligations d'évaluation des risques systémiques (désinformation, violences, effets sur la santé mentale des mineurs) et de transparence sur leurs algorithmes. Les plateformes doivent désormais offrir des systèmes de recommandation non profilés (sans personnalisation) comme alternative.</p>
<p class="resume-text">La <strong>transparence algorithmique</strong> est difficile à mettre en oeuvre : les algorithmes des grandes plateformes sont des boîtes noires complexes que même leurs ingénieurs ne comprennent pas entièrement dans leurs effets. Les entreprises arguent que la divulgation de leurs algorithmes permettrait de les manipuler. Les chercheurs indépendants qui tentent d'auditer les algorithmes se heurtent à des obstacles d'accès aux données. Des approches alternatives à la régulation par transparence sont proposées : audit par des tiers de confiance, interopérabilité forcée, interdiction de certains types de design persuasif (dark patterns).</p>
""",

"medias-numeriques/desinformation": """
<h3>Anatomie de la désinformation</h3>
<p class="resume-text">La <strong>désinformation</strong> est intentionnellement produite et diffusée pour tromper. Elle prend des formes variées : faux articles imitant des sources d'information légitimes, comptes ou pages d'apparence normale mais opérés de façon coordonnée (coordinated inauthentic behavior), vidéos sorties de leur contexte, synthèses sélectives qui déforment la réalité sans mentir sur les faits. La <strong>mésinformation</strong> (misinformation) est diffusée sans intention malveillante mais peut avoir les mêmes effets. La <strong>malinformation</strong> est vraie mais utilisée à des fins malveillantes (divulgation d'informations privées, doxxing).</p>
<p class="resume-text">Le chercheur Sam Woolley, du Computational Propaganda Project d'Oxford, a documenté l'ampleur des <strong>campagnes de manipulation systématique</strong> sur les réseaux sociaux : armées de bots automatisés, comptes coordonnés de trolls rémunérés, usines à trolls (comme l'Internet Research Agency russe, qui a interféré dans les élections américaines de 2016). Ces opérations, souvent commanditées par des États, exploitent les algorithmes de recommandation pour amplifier des messages diviseurs et créer une fausse impression de consensus social autour de positions extrêmes.</p>
<div class="highlight-box"><p>Une étude du MIT (Vosoughi, Roy, Aral, 2018) a analysé 126 000 chaînes de diffusion sur Twitter et montré que les fausses nouvelles se propagent <strong>six fois plus vite</strong> que les vraies et touchent un public 35% plus large. Les fausses nouvelles sont plus nouvelles, plus originales et suscitent plus de surprise, de peur et de dégoût que les vraies — des émotions qui stimulent le partage. Cette viralité asymétrique en faveur de la désinformation est un défi structurel pour toute politique d'information saine.</p></div>
<h3>Les stratégies de lutte contre la désinformation</h3>
<p class="resume-text">Les stratégies de <strong>fact-checking</strong> ont proliféré depuis les années 2000 : AFP Factuel, Les Décodeurs du <em>Monde</em>, Libération CheckNews, PolitiFact, FactCheck.org, Snopes. Ces organisations vérifient des affirmations spécifiques et publient leurs conclusions avec un niveau de preuve. Certaines plateformes (Facebook, Instagram, Twitter/X) ont intégré des fact-checkers tiers qui apposent des étiquettes d'avertissement sur les contenus identifiés comme faux ou trompeurs. L'efficacité de ces interventions est débattue : les avertissements peuvent réduire le partage des fausses informations mais peuvent aussi produire un effet de légitimation pour les contenus non étiquetés (implied truth effect).</p>
<p class="resume-text">La <strong>prébunking</strong> (inoculation cognitive) est une approche alternative au debunking (réfutation après coup) : exposer à l'avance les techniques de manipulation (appel à l'émotion, faux experts, conspiration) renforce la résistance cognitive à la désinformation future, même sur des sujets inconnus. Des jeux en ligne (Bad News, Harmony Square) permettent de s'exercer à identifier ces techniques. La <strong>media literacy</strong> (éducation aux médias) est présentée comme la solution structurelle : apprendre aux citoyens, dès l'école, à évaluer les sources, à reconnaître les biais et à distinguer opinion et information.</p>
""",

"medias-numeriques/culture-numerique": """
<h3>L'identité numérique et les avatars</h3>
<p class="resume-text">Internet a créé de nouvelles formes d'<strong>identité numérique</strong> — les façons dont les individus se présentent et se construisent en ligne. Sherry Turkle, dans <em>Life on the Screen</em> (1995), a analysé comment les MUDs (Multi-User Dungeons, jeux de rôle en ligne précurseurs) permettaient aux joueurs d'explorer des identités multiples et fluides, préfigurant les questions d'identité en ligne dans les réseaux sociaux. En ligne, les individus gèrent soigneusement leur présentation de soi : sélection des photos, curation des opinions, construction d'une persona cohérente avec leurs aspirations identitaires.</p>
<p class="resume-text">La <strong>culture des mèmes</strong> est un phénomène culturel spécifiquement numérique. Richard Dawkins avait forgé le terme « mème » (1976) pour désigner une unité d'information culturelle se propageant par imitation. Le mème internet en est une réalisation spécifique : une image, une vidéo ou un format de communication qui se réplique avec des variations, souvent humoristiques, à travers les plateformes. Les mèmes sont à la fois vecteurs de culture populaire, d'humour, d'appartenance communautaire et, de plus en plus, d'arguments politiques difficilement réfutables car enrobés dans l'humour.</p>
<div class="highlight-box"><p>Le concept de <strong>FOMO</strong> (Fear Of Missing Out — peur de rater quelque chose) décrit l'anxiété sociale liée à la crainte de ne pas participer à des expériences partagées que les autres vivent. Amplifié par les réseaux sociaux qui mettent en scène la vie sociale des autres en permanence, il est associé à des effets négatifs sur la santé mentale et à une dépendance accrue aux plateformes. La connexion permanente (always-on) que permettent les smartphones a transformé les frontières entre vie privée et vie sociale, entre temps de travail et temps libre.</p></div>
<h3>Les communautés en ligne et la culture participative</h3>
<p class="resume-text">Henry Jenkins a théorisé la <strong>culture participative</strong> à l'ère numérique : une culture dans laquelle les fans et les consommateurs de médias ne se contentent plus de consommer passivement mais créent, transforment et redistribuent des contenus. Les fan fictions, les vidéos remixées, les wikis collaboratifs (Wikipédia), les commentaires et discussions sur les forums sont des manifestations de cette culture participative. Jenkins oppose la culture participative à la culture de convergence où de grandes entreprises tentent de concentrer les médias et les contenus.</p>
<p class="resume-text">Les <strong>communautés en ligne</strong> organisées autour d'intérêts communs (Reddit, Discord, forums spécialisés) créent des espaces sociaux alternatifs aux communautés géographiques traditionnelles. Ces communautés ont leur propre culture, leurs codes, leurs normes sociales et parfois leurs langages spécifiques. Elles peuvent être sources d'entraide, de créativité collective et d'appartenance sociale pour des individus isolés géographiquement. Elles peuvent aussi devenir des espaces de radicalisation (forums d'extrême droite, espaces incel), de harcèlement collectif ou de manipulation politique.</p>
""",

"publicite/histoire-publicite": """
<h3>Des réclames aux campagnes intégrées</h3>
<p class="resume-text">La publicité moderne naît au XIXe siècle avec l'essor de la presse de masse et de la production industrielle. Les premières agences de publicité américaines (N.W. Ayer, 1869 ; J. Walter Thompson, 1878) professionnalisent la création et le placement d'annonces. La révolution industrielle crée une nécessité nouvelle : des millions de produits standardisés doivent être différenciés de leurs concurrents dans l'esprit du consommateur. La <strong>marque</strong> (brand) et le <strong>slogan</strong> émergent comme outils de différenciation symbolique.</p>
<p class="resume-text">Le <strong>XXe siècle</strong> est l'âge d'or de la publicité de masse. La radio (années 1930) et la télévision (années 1950) offrent des médias synchrones atteignant des millions de foyers simultanément. Les <strong>agences de Madison Avenue</strong> (New York) développent les techniques créatives modernes : le positionnement de marque (Rosser Reeves et son USP — unique selling proposition), la recherche motivationnelle (Ernest Dichter, psychanalyste autrichien qui applique Freud à la consommation), le concept publicitaire total (Leo Burnett, agence fondée en 1935). David Ogilvy synthétise les meilleurs pratiques dans <em>Confessions of an Advertising Man</em> (1963).</p>
<div class="highlight-box"><p>La révolution <strong>Don Draper</strong> (des années 1960, incarnée dans la série Mad Men) correspond au passage d'une publicité purement rationnelle-informative à une publicité émotionnelle et symbolique. La campagne « Think Small » de Volkswagen (1959, agence DDB), qui célébrait la petitesse et l'économie de la Coccinelle dans l'Amérique du gigantisme, est considérée comme l'une des meilleures publicités de l'histoire car elle assumait le paradoxe au lieu de le nier.</p></div>
<h3>Les grands courants créatifs de la publicité</h3>
<p class="resume-text">La créativité publicitaire s'est structurée en <strong>grandes écoles de pensée</strong>. La <strong>révolution créative</strong> des années 1960 (Bill Bernbach, DDB) rompt avec le modèle rationnel-vendeur pour proposer des publicités insolentes, intelligentes et respectant l'intelligence du consommateur. Le <strong>branding émotionnel</strong> (Kevin Roberts, Saatchi & Saatchi, <em>Lovemarks</em>, 2004) pousse le raisonnement jusqu'à l'extrême : les marques les plus puissantes créent un attachement émotionnel irrationnel (amour + respect) qui les rend irremplaçables dans la vie des consommateurs. Apple illustre parfaitement ce concept.</p>
<p class="resume-text">Le <strong>storytelling publicitaire</strong> est devenu la modalité créative dominante dans les années 2000-2010. Plutôt que d'argumenter les bénéfices d'un produit, les marques racontent des histoires : une philosophie de vie, une vision du monde, une communauté d'appartenance. Dove (campagnes Real Beauty depuis 2004), Nike (Just Do It et ses déclinaisons), Patagonia (militantisme environnemental) ont construit des récits de marque cohérents sur le long terme. Ce storytelling peut être authentique ou manipulatoire selon que la promesse narrative correspond à une réalité d'entreprise ou à un <strong>greenwashing</strong> et un <strong>woke-washing</strong> superficiels.</p>
""",

"publicite/comportement-consommateur": """
<h3>Les théories de la motivation du consommateur</h3>
<p class="resume-text">La psychologie du consommateur mobilise plusieurs cadres théoriques pour comprendre les motivations d'achat. La <strong>hiérarchie des besoins de Maslow</strong> (1943) a été adaptée au marketing : les produits de première nécessité (nourriture, vêtements basiques) satisfont les besoins physiologiques ; les assurances et alarmes satisfont les besoins de sécurité ; les marques de luxe visible satisfont les besoins d'appartenance et d'estime sociale. Cette hiérarchie est cependant critiquée pour son universalisme occidental et sa linéarité.</p>
<p class="resume-text">La <strong>théorie de la dissonance cognitive</strong> (Leon Festinger, 1957) explique un phénomène paradoxal : après un achat important, les consommateurs cherchent activement à renforcer leur conviction d'avoir fait le bon choix, en évitant les informations négatives sur le produit acheté et en accordant plus d'importance aux informations positives. Ce mécanisme de réduction de la dissonance post-achat oriente les stratégies de marketing après-vente : satisfaction client, loyauté et programme de fidélité visent à renforcer la conviction que le consommateur a bien fait d'acheter.</p>
<div class="highlight-box"><p>Le <strong>nudge</strong> (coup de pouce) est une approche comportementale qui guide les individus vers des choix souhaitables sans les contraindre, en jouant sur l'architecture des choix (choice architecture). Richard Thaler et Cass Sunstein, dans <em>Nudge</em> (2008), montrent comment la présentation par défaut (opt-in vs opt-out), l'ordre des options, la saillance des informations influencent les décisions sans modifier les incitations économiques. Les politiques publiques (santé, épargne retraite, écologie) et le marketing commercial utilisent largement ces principes.</p></div>
<h3>L'économie comportementale et les biais du consommateur</h3>
<p class="resume-text">Daniel Kahneman et Amos Tversky ont révolutionné la compréhension de la prise de décision économique en montrant que les humains ne sont pas des agents rationnels mais des êtres aux capacités cognitives limitées (bounded rationality) qui utilisent des heuristiques (raccourcis mentaux) et sont sujets à des biais systématiques. Dans <em>Thinking, Fast and Slow</em> (2011), Kahneman distingue le <strong>Système 1</strong> (pensée rapide, intuitive, émotionnelle) du <strong>Système 2</strong> (pensée lente, délibérative, rationnelle). La publicité exploite massivement le Système 1 : associations d'images, musiques, couleurs, célébrités — tout ce qui déclenche des réponses émotionnelles automatiques.</p>
<p class="resume-text">Le <strong>biais d'ancrage</strong> (le premier prix vu influence la perception de tous les prix suivants), l'<strong>effet de rareté</strong> (les objets rares sont perçus comme plus désirables), la <strong>preuve sociale</strong> (on fait ce que font les autres), l'<strong>aversion à la perte</strong> (la peur de perdre est plus forte que le désir de gagner l'équivalent) — ces biais sont systématiquement exploités dans le marketing numérique. Les <strong>dark patterns</strong> (designs trompeurs dans les interfaces) manipulent les utilisateurs pour leur faire acheter ce qu'ils n'auraient pas voulu, s'abonner accidentellement ou accepter des conditions défavorables.</p>
""",

"publicite/marketing-digital": """
<h3>SEO, SEM et le référencement</h3>
<p class="resume-text">L'<strong>optimisation pour les moteurs de recherche</strong> (SEO — Search Engine Optimization) est l'art et la science d'améliorer la position d'un site web dans les résultats organiques des moteurs de recherche. Google, qui gère environ 93% des recherches mondiales, utilise un algorithme (PageRank, créé par Larry Page et Sergey Brin) qui évalue des centaines de critères : pertinence du contenu, popularité (liens entrants), vitesse de chargement, compatibilité mobile, sécurité (HTTPS), expérience utilisateur. L'industrie du SEO (blogs spécialisés, consultants, agences) cherche constamment à comprendre et optimiser ces critères.</p>
<p class="resume-text">Le <strong>marketing des réseaux sociaux</strong> (Social Media Marketing) a transformé les pratiques publicitaires. La possibilité de cibler des audiences très précises (par démographie, centres d'intérêt, comportements, localisation) et de mesurer précisément les effets de chaque campagne représente une rupture avec la publicité de masse traditionnelle. Les formats évoluent rapidement : publicités dans le fil (native ads), stories, Reels, influencer marketing. Les marques doivent maintenant gérer une présence éditoriale continue sur plusieurs plateformes, avec des codes esthétiques et des tonalités adaptés à chaque réseau.</p>
<div class="highlight-box"><p>Le <strong>marketing d'influence</strong> est devenu une industrie à part entière, représentant plus de 20 milliards de dollars en 2022. Des célébrités aux nano-influenceurs (1 000 à 10 000 abonnés), des YouTubeurs aux TikTokeurs, les marques paient des créateurs pour présenter leurs produits à leur communauté. L'authenticité perçue des influenceurs — supérieure à celle de la publicité classique pour leurs abonnés — est leur principal atout, mais elle est fragilisée quand les collaborations commerciales deviennent la norme sans transparence suffisante.</p></div>
<h3>Le marketing automation et la personnalisation</h3>
<p class="resume-text">Le <strong>marketing automation</strong> désigne l'ensemble des outils et plateformes permettant d'automatiser les actions marketing selon des scénarios préétablis : email de bienvenue déclenché à l'inscription, relance automatique après abandon de panier, recommandations personnalisées basées sur l'historique de navigation. Des plateformes comme Salesforce, HubSpot ou Marketo permettent de gérer des millions de contacts avec des communications ultra-personnalisées à grande échelle.</p>
<p class="resume-text">La <strong>personnalisation algorithmique</strong> pousse cette logique à l'extrême : chaque visiteur d'un site e-commerce voit une page d'accueil, des recommandations et des offres différentes, calculées en temps réel par des algorithmes de machine learning. Amazon a été pionnier de cette approche : 35% de ses ventes seraient générées par son moteur de recommandations. Cette personnalisation améliore l'expérience utilisateur mais soulève des questions sur la discrimination algorithmique (les prix variables selon les profils) et la manipulation des choix (orienter les achats vers les produits les plus profitables plutôt que les plus adaptés au besoin).</p>
""",

"publicite/branding-identite": """
<h3>L'architecture de marque et la gestion du portefeuille</h3>
<p class="resume-text">La <strong>stratégie de marque</strong> (brand strategy) définit l'identité, le positionnement et la vision d'une marque sur le long terme. L'<strong>architecture de marque</strong> organise les relations entre une marque maison et ses sous-marques : la stratégie marque-produit (une marque par produit, comme P&G), la stratégie ombrelle (une marque pour tous les produits, comme Michelin), et les architectures hybrides. L'exemple emblématique est LVMH, qui possède plus de 75 marques de luxe (Louis Vuitton, Moët & Chandon, Hennessy, Dior, Givenchy) maintenues délibérément indépendantes pour préserver leur identité spécifique.</p>
<p class="resume-text">Le <strong>positionnement de marque</strong> (Al Ries et Jack Trout, <em>Positioning: The Battle for Your Mind</em>, 1981) consiste à occuper une position distinctive et mémorable dans l'esprit du consommateur. Cette position doit répondre à trois questions : pour qui est la marque ? En quoi est-elle différente des concurrents ? Sur quels bénéfices (rationnels ou émotionnels) met-elle l'accent ? Volvo = sécurité ; Apple = créativité et design ; Ikea = accessibilité avec style ; Patagonia = authenticité environnementale. Ces positionnements, quand ils sont cohérents et durables, créent une forte valeur de marque (brand equity).</p>
<div class="highlight-box"><p>La <strong>valeur de marque</strong> est mesurée à plusieurs niveaux : la notoriété (spontanée et assistée), l'image (associations mentales), la préférence (intention d'achat) et la fidélité (comportement répété). Interbrand publie chaque année un classement des marques les plus précieuses : Apple (en tête depuis 2013), Google, Amazon, Microsoft. Ces marques valent des centaines de milliards de dollars — bien au-delà de leurs actifs tangibles — en raison de leur capital immatériel : confiance, désirabilité, loyauté des consommateurs.</p></div>
<h3>L'identité visuelle et le design de marque</h3>
<p class="resume-text">L'<strong>identité visuelle</strong> d'une marque comprend son logo, sa palette de couleurs, ses typographies, ses formes et ses patterns — autant d'éléments qui doivent être cohérents sur tous les supports et reconnaissables immédiatement. Les couleurs ont des significations culturelles codées : le rouge évoque l'énergie et l'urgence (Coca-Cola, YouTube), le bleu la confiance et la fiabilité (Facebook, LinkedIn, Samsung), le vert la nature et la santé (Whole Foods, Spotify), le noir le luxe et l'exclusivité (Chanel, Apple Store). Ces codes ne sont pas universels (le blanc évoque la pureté en Occident mais le deuil en Chine) et doivent être adaptés pour les marques globales.</p>
<p class="resume-text">Le rebranding est l'une des décisions les plus risquées pour une marque établie. Des exemples de rebranding réussis (Burberry qui a transformé son image populaire ternie en luxe désirable dans les années 2000, Apple qui a abandonné le trait arc-en-ciel pour un Apple monochrome plus épuré) coexistent avec des échecs retentissants (Gap qui a dû renoncer à son nouveau logo en quelques jours en 2010 face au tollé des consommateurs ; Tropicana qui a perdu 20% de ses ventes après avoir changé son packaging iconique en 2009). Ces cas illustrent le capital affectif des marques familières et le risque de rupture avec une identité établie.</p>
""",

"publicite/ethique-publicitaire": """
<h3>Publicité et manipulation : les limites éthiques</h3>
<p class="resume-text">La publicité est structurellement orientée vers la persuasion, ce qui la situe dans une zone grise éthique permanente. La distinction entre <strong>persuasion légitime</strong> (présenter les avantages réels d'un produit de façon attrayante) et <strong>manipulation</strong> (créer de faux désirs, exploiter des vulnérabilités psychologiques, tromper sur les qualités du produit) est au cœur des débats éthiques du secteur. Les codes de déontologie professionnels (ICC Code of Advertising, codes nationaux de l'ARPP en France) interdisent la publicité mensongère, trompeuse, comparative illicite et les messages ciblant de façon indue les enfants.</p>
<p class="resume-text">La publicité ciblant les <strong>enfants et les adolescents</strong> est particulièrement sensible : leur capacité de discernement publicitaire est en développement, ce qui les rend plus vulnérables à la manipulation. La France interdit la publicité aux heures de grande écoute des programmes pour enfants depuis 2018 sur les chaînes publiques. Le marketing des sodas, junk food et jeux d'argent est réglementé dans de nombreux pays face à des crises de santé publique (obésité infantile, addictions). La publicité pour l'alcool et le tabac fait l'objet de restrictions variables selon les pays.</p>
<div class="highlight-box"><p>Le <strong>greenwashing</strong> (écoblanchiment) est l'une des pratiques publicitaires les plus critiquées : des marques revendiquent des vertus environnementales non fondées pour capter un marché de consommateurs soucieux de l'écologie. La Commission européenne a proposé en 2023 une directive anti-greenwashing interdisant les allégations environnementales vagues (« vert », « naturel », « éco-friendly ») sans preuve scientifique vérifiable. Des autorités de régulation britanniques, néerlandaises et françaises ont sanctionné des marques pour publicités environnementales trompeuses.</p></div>
<h3>La publicité à l'ère de la surveillance</h3>
<p class="resume-text">La <strong>publicité comportementale ciblée</strong> (behavioral targeting advertising) soulève des questions éthiques majeures sur la surveillance et la vie privée. Le modèle publicitaire de Facebook, Google et de milliers de plateformes plus petites repose sur la collecte massive de données comportementales — pages visitées, achats effectués, recherches effectuées, localisations, contacts sociaux — pour cibler chaque utilisateur avec des publicités ultra-personnalisées. Cette surveillance généralisée a conduit au Règlement général sur la protection des données (RGPD) européen (2018), qui impose le consentement explicite pour la collecte de données et a généré des amendes de plusieurs milliards pour Google et Meta.</p>
<p class="resume-text">La <strong>publicité programmatique</strong> — achat et vente automatisée d'espaces publicitaires en temps réel via des enchères électroniques — a transformé l'industrie publicitaire. En quelques millisecondes, des algorithmes décident quel annonceur paie le plus pour atteindre un utilisateur spécifique sur une page web donnée. Ce système, opaque pour les annonceurs comme pour les éditeurs, a créé des marchés opaques où les publicités d'entreprises sérieuses peuvent se retrouver côte à côte avec des contenus extrémistes ou de désinformation — le problème de la sécurité de la marque (brand safety) est devenu une préoccupation majeure des annonceurs.</p>
""",

"relations-publiques/fondements-rp": """
<h3>Définitions et périmètre des relations publiques</h3>
<p class="resume-text">Les <strong>relations publiques</strong> (RP) sont définies par la Société européenne des RP (CERP) comme « l'effort délibéré, planifié et soutenu pour établir et maintenir une compréhension mutuelle entre une organisation et son public ». Cette définition souligne trois éléments : le caractère intentionnel et stratégique (vs communication spontanée), la notion de durée (vs campagne ponctuelle) et la réciprocité (vs communication à sens unique). Les RP s'appliquent à toutes les organisations — entreprises, administrations, ONG, personnalités publiques — dans leurs relations avec leurs diverses parties prenantes.</p>
<p class="resume-text">Les RP se distinguent de la publicité en ce qu'elles visent à influencer les publics via des <strong>tiers légitimants</strong> (journalistes, influenceurs, experts) plutôt que par des messages payants directement contrôlés. Un article favorable dans un journal crédible a plus d'impact qu'une publicité équivalente, précisément parce qu'il est perçu comme indépendant. Cette logique de l'earned media (couverture médiatique méritée par les actions et le contenu vs paid media acheté) est au cœur des RP traditionnelles, bien que les frontières soient de plus en plus poreuses avec l'essor du branded content et du marketing d'influence.</p>
<div class="highlight-box"><p>La distinction entre <strong>spin</strong> (manipulation de l'information à des fins favorables) et RP éthiques est une tension permanente du secteur. Edward Bernays, considéré comme le père des RP modernes, assumait ouvertement la dimension de manipulation dans ses pratiques. Des approches plus récentes (Tim Traverse-Healy, Jim Grunig) plaident pour un modèle de RP bidirectionnel symétrique — où les organisations adaptent leurs comportements en réponse aux préoccupations de leurs publics, plutôt que de simplement gérer les perceptions sans changer les pratiques.</p></div>
<h3>Les publics et les parties prenantes</h3>
<p class="resume-text">La gestion des <strong>parties prenantes</strong> (stakeholder management) est une approche RP stratégique issue des travaux de R. Edward Freeman (<em>Strategic Management: A Stakeholder Approach</em>, 1984). Freeman définit une partie prenante comme tout individu ou groupe pouvant affecter ou être affecté par les objectifs d'une organisation : actionnaires, employés, clients, fournisseurs, communautés locales, régulateurs, médias, ONG. Cartographier les parties prenantes selon leur pouvoir d'influence et leur intérêt pour l'organisation permet de prioriser les efforts de communication.</p>
<p class="resume-text">La <strong>communication corporate</strong> (communication d'entreprise) englobe les RP, la communication financière (relations avec les investisseurs et actionnaires), les affaires publiques (lobbying et relations avec les pouvoirs publics), la communication interne et la gestion de la réputation. La réputation d'entreprise, actif immatériel de plus en plus valorisé dans l'économie contemporaine, dépend de la cohérence entre les valeurs proclamées et les comportements réels. L'écart entre discours et actes (say/do gap) est rapidement exposé à l'ère des réseaux sociaux et du journalisme d'investigation.</p>
""",

"relations-publiques/communication-crise": """
<h3>Typologies des crises et facteurs d'aggravation</h3>
<p class="resume-text">Les crises d'organisation peuvent être classifiées selon leur origine (technique/accidentelle, humaine/comportementale, naturelle), leur prévisibilité (crises prévisibles évitables, prévisibles inévitables, imprévisibles) et leur évolution temporelle (crise soudaine comme un accident industriel, crise couvante qui s'aggrave progressivement, crise cyclique qui revient périodiquement). Le cabinet Burson-Marsteller distingue les crises smouldering (qui couvent pendant des mois avant d'exploser médiatiquement, comme les scandales de harcèlement sexuel longtemps étouffés) des crises soudaines (accidents, catastrophes).</p>
<p class="resume-text">Plusieurs facteurs aggravent structurellement les crises : le <strong>mensonge</strong> initial (qui double la crise en y ajoutant une crise de confiance quand la vérité émerge), le <strong>silence prolongé</strong> (qui laisse la parole aux sources hostiles sans contre-narration), la <strong>communication contradictoire</strong> (quand différents porte-paroles tiennent des discours incompatibles), et la <strong>mauvaise évaluation de la gravité</strong> (sous-estimer une crise sérieuse ou sur-réagir à un incident mineur). L'affaire Volkswagen (Dieselgate, 2015) illustre l'aggravation maximale : mensonge délibéré sur les émissions suivi d'une gestion chaotique de la révélation.</p>
<div class="highlight-box"><p>Le <strong>modèle SCCT</strong> (Situational Crisis Communication Theory) de Timothy Coombs distingue les stratégies de réponse en crise selon la responsabilité organisationnelle perçue. Si l'organisation est perçue comme peu responsable (victime d'un événement externe), elle peut nier ou minimiser. Si sa responsabilité est accidentelle, elle doit s'excuser et compenser. Si elle est perçue comme intentionnellement fautive, seule une reconnaissance totale et des actions correctrices crédibles peuvent restaurer la confiance.</p></div>
<h3>La communication de crise à l'ère des réseaux sociaux</h3>
<p class="resume-text">Les réseaux sociaux ont radicalement transformé la gestion des crises d'organisation. L'<strong>amplification instantanée</strong> d'un incident — une vidéo montrant un comportement répréhensible peut devenir virale en quelques heures — a réduit le temps disponible pour évaluer et répondre. Le <strong>cancelculture</strong> (culture de l'annulation) — boycott collectif en ligne d'une personnalité ou d'une marque suite à un comportement jugé inacceptable — peut avoir des effets économiques et réputationnels sévères avant même qu'une investigation équitable soit menée.</p>
<p class="resume-text">La communication de crise efficace à l'ère numérique exige une <strong>veille permanente</strong> (monitoring des réseaux sociaux, des médias, des forums), des <strong>protocoles de réponse pré-définis</strong> (dark sites prêts à activer, porte-parole formés, messages clés préparés pour différents scénarios), et une <strong>stratégie multicanale</strong> (répondre sur les mêmes plateformes où la crise se développe, pas seulement dans un communiqué de presse). L'authenticité de la réponse est cruciale : les publics des réseaux sociaux détectent rapidement le discours corporate vide et récompensent la transparence et l'humilité.</p>
""",

"relations-publiques/relations-presse": """
<h3>L'évolution des relations presse à l'ère numérique</h3>
<p class="resume-text">Les <strong>relations presse</strong> traditionnelles reposaient sur un écosystème médiatique stable : quelques journaux nationaux influents, quelques chaînes de télévision, des journalistes spécialisés connus. Les attachés de presse cultivaient des relations personnelles durables avec des journalistes identifiés, leur fournissant des informations exclusives en échange de couverture favorable. Cet écosystème a été bouleversé par la fragmentation numérique : les médias se sont multipliés (web, réseaux sociaux, podcasts, newsletters) tandis que les rédactions s'amaigrissaient, réduisant le temps des journalistes pour les relations avec les entreprises.</p>
<p class="resume-text">Le <strong>newsroom numérique</strong> travaille à un rythme de publication continue 24/7, cherchant des contenus multimédia, des angles originaux et des histoires virales plutôt que des communiqués de presse standard. Les RP ont dû s'adapter : storytelling multimédia (vidéos, infographies, podcasts), <strong>média owned</strong> (blogues d'entreprise, chaînes YouTube, comptes réseaux sociaux qui permettent de publier directement sans intermédiaire), et maîtrise des analytics pour démontrer le retour sur investissement des actions presse (earned media value, portée, engagements).</p>
<div class="highlight-box"><p>Le <strong>journalisme citizen</strong> et les influenceurs non-journalistes ont créé de nouvelles relations pour les RP. Des blogueurs, des créateurs YouTube, des Instagrameurs et des TikTokeurs ont des audiences parfois supérieures aux médias traditionnels dans leur niche. Les attachés de presse doivent maintenant gérer des listes de contacts qui mêlent journalistes professionnels et influenceurs, avec des pratiques et des attentes très différentes.</p></div>
""",

"relations-publiques/communication-interne": """
<h3>Les fonctions de la communication interne</h3>
<p class="resume-text">La <strong>communication interne</strong> remplit plusieurs fonctions essentielles dans les organisations. La fonction <strong>informative</strong> — tenir les collaborateurs informés de la stratégie, des résultats, des changements — est la plus immédiatement visible. La fonction <strong>fédératrice</strong> crée un sentiment d'appartenance, partage les valeurs de l'entreprise et aligne les comportements sur la stratégie. La fonction <strong>dialogique</strong> facilite la remontée d'informations du terrain vers la direction (communication ascendante) et les échanges latéraux entre équipes (communication transversale). La fonction <strong>motivante</strong> reconnaît les contributions individuelles et collectives, célèbre les succès.</p>
<p class="resume-text">L'<strong>engagement des collaborateurs</strong> (employee engagement) est devenu un enjeu stratégique majeur depuis les travaux montrant sa corrélation avec la productivité, la rétention des talents et la satisfaction client. Une étude Gallup de 2023 estime que seulement 23% des salariés dans le monde se sentent engagés au travail. La communication interne efficace est l'un des leviers identifiés pour améliorer cet engagement : clarté de la vision et du sens du travail, reconnaissance, sentiment d'être écouté et informé, confiance dans les dirigeants.</p>
<div class="highlight-box"><p>La <strong>communication de changement</strong> est la forme la plus difficile de communication interne. Les transformations organisationnelles (restructurations, fusions-acquisitions, transformations digitales) génèrent de l'incertitude et des résistances. La courbe du deuil de Kübler-Ross — adaptée au changement organisationnel — décrit les phases par lesquelles passent les individus confrontés au changement : déni, colère, marchandage, dépression, acceptation. Une communication accompagnant ces phases, anticipant les craintes et associant les collaborateurs à la co-construction du changement, améliore significativement les taux de réussite des transformations.</p></div>
<h3>Les outils de la communication interne</h3>
<p class="resume-text">L'<strong>intranet</strong> est longtemps resté l'outil central de la communication interne en entreprise — portail documentaire, actualités, annuaire. Sa transformation en <strong>digital workplace</strong> (environnement de travail numérique) intègre désormais outils collaboratifs (Microsoft Teams, Slack), gestionnaire de projet, accès aux applications métier et espaces communautaires. La pandémie de Covid-19 a accéléré massivement cette transition avec le télétravail généralisé, révélant à la fois la puissance et les limites des outils numériques pour maintenir la cohésion et la culture d'entreprise à distance.</p>
<p class="resume-text">Les <strong>réseaux sociaux d'entreprise</strong> (Yammer, Workplace by Meta, Teams) créent des espaces de communication latérale et ascendante plus informels que l'intranet classique. Ils peuvent renforcer la transversalité et briser les silos organisationnels, mais leur adoption est inégale selon les cultures d'entreprise. La frontière entre espace professionnel et espace personnel est questionnée : dans quelle mesure les collaborateurs doivent-ils être accessibles en dehors des heures de travail via les outils numériques ? Le droit à la déconnexion, inscrit dans la loi française depuis 2017, tente de répondre à cette question.</p>
""",

"relations-publiques/communication-politique": """
<h3>La communication électorale moderne</h3>
<p class="resume-text">La <strong>communication électorale</strong> a été révolutionnée par la télévision (depuis le débat Kennedy-Nixon de 1960), puis par internet et les réseaux sociaux. La télévision a fait du charisme visuel, de l'image physique et de la maîtrise des émotions des compétences politiques centrales. La célèbre accroche de Marshall McLuhan — « le médium, c'est le message » — s'est vérifiée : la même prestation politique peut être évaluée très différemment selon qu'on l'a vue à la télévision (défavorable pour le visage fatigué de Nixon) ou entendue à la radio (jugée favorable pour son argumentation).</p>
<p class="resume-text">La <strong>campagne présidentielle américaine de 2008</strong> d'Obama est considérée comme la première grande campagne numérique : utilisation intensive d'internet pour la levée de fonds (petits dons agrégés via la plateforme), la mobilisation des bénévoles, la communication directe avec les électeurs. La campagne Trump de 2016, puis les campagnes suivantes, ont montré la puissance des réseaux sociaux (Twitter en particulier) pour contourner les médias traditionnels et communiquer directement avec les bases électorales en termes très directs, voire agressifs — une stratégie de communication disruptive qui transgresse délibérément les normes de la communication politique conventionnelle.</p>
<div class="highlight-box"><p>La <strong>communication de gouvernement</strong> est distincte de la communication de campagne : une fois élu, un dirigeant doit communiquer en son nom institutionnel (et pas seulement personnel), rendre compte de son action (accountability), et maintenir une relation de confiance avec l'ensemble des citoyens, pas seulement son électorat. Le Service d'information du gouvernement (SIG) en France, le Cabinet Office Communication Team au Royaume-Uni ou les équipes de communication de la Maison Blanche illustrent cette institutionnalisation de la communication gouvernementale.</p></div>
<h3>Le spin doctoring et la gestion des récits politiques</h3>
<p class="resume-text">Le <strong>spin doctoring</strong> (de spin — faire tourner, mettre en valeur) désigne les pratiques de conseillers en communication politique qui cherchent à contrôler le récit médiatique en faveur de leur client politique. Les spin doctors travaillent sur le cadrage (framing) des événements, la gestion des médias (briefings, exclusivités, off the record), la mise en valeur des atouts et la minimisation des erreurs. Des conseillers comme Alastair Campbell (pour Tony Blair), Roger Ailes (pour Nixon, Reagan, Bush), Karl Rove (pour George W. Bush) ont acquis une réputation de manipulateurs de génie — parfois controversée.</p>
<p class="resume-text">Le <strong>storytelling politique</strong> est devenu un outil central de communication des dirigeants. Les politiques les plus efficaces sont ceux qui maîtrisent le récit de leur propre trajectoire (Barack Obama avec son récit d'ascension de l'Amérique multiculturelle, Emmanuel Macron avec son récit de renouvellement du champ politique) et qui savent raconter une histoire du collectif national (le récit de nation, le futur désirable vers lequel ils veulent emmener le pays). George Lakoff a théorisé l'importance des <strong>cadres cognitifs</strong> (frames) qui structurent inconsciemment la perception politique : parler de « relief fiscal » (tax relief) plutôt que de « réduction d'impôts » active des structures cognitives très différentes.</p>
""",
}

def enrich_page(content, extra_html):
    idx = content.rfind('</section>')
    if idx == -1:
        return content + extra_html
    return content[:idx] + extra_html + content[idx:]

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

enriched = 0
for key, extra in ENRICHMENTS_COMM.items():
    if key in data['pages']:
        page = data['pages'][key]
        original_len = len(page['content'])
        page['content'] = enrich_page(page['content'], extra)
        new_len = len(page['content'])
        print(f'  {key}: {original_len} -> {new_len} chars')
        enriched += 1

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Check
with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'r', encoding='utf-8') as f:
    data2 = json.load(f)
pages = [(k, len(p['content'])) for k,p in data2['pages'].items() if p.get('type') in ('course','lesson')]
above15 = sum(1 for k,l in pages if l >= 15000)
above14 = sum(1 for k,l in pages if l >= 14000)
below = [(k,l) for k,l in pages if l < 14000]
print(f'\nTotal enriched: {enriched}')
print(f'COMM STATE: {above15}/{len(pages)} >= 15k, {above14}/{len(pages)} >= 14k')
for k,l in sorted(below, key=lambda x: x[1]):
    print(f'  SHORT: {l} {k}')
