import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

enrichments = {}

enrichments['electronique/composants-electroniques'] = (
    '<h3>Composants passifs : résistances, condensateurs, bobines</h3>'
    '<p class="resume-text">Les <strong>résistances</strong> s\'opposent au passage du courant électrique selon la loi d\'Ohm : V = R·I. Les résistances à couche métallique offrent une précision de 0,1% et une faible dérive thermique, indispensables dans les circuits de mesure. Les résistances CMS (composants montés en surface) au format 0402 (1mm × 0,5mm) équipent les cartes électroniques modernes. Les thermistances (NTC/PTC) varient leur résistance avec la température — utilisées comme capteurs de température et sondes de protection.</p>'
    '<p class="resume-text">Les <strong>condensateurs</strong> stockent de l\'énergie sous forme de champ électrique. La capacité C détermine la charge stockée Q = C·V. Les condensateurs céramiques multicouches (MLCC) sont compacts et fonctionnent à haute fréquence — indispensables pour le découplage d\'alimentation. Les condensateurs électrolytiques offrent de grandes capacités (1 à 10 000 μF) pour le filtrage des alimentations. Les condensateurs supercapacités (1 à 3000 F) stockent 100 fois plus d\'énergie que les condensateurs classiques mais sont limités en tension.</p>'
    '<p class="resume-text">Les <strong>bobines et transformateurs</strong> s\'opposent aux variations de courant. Associées aux condensateurs, les bobines forment des circuits LC résonnants utilisés dans les filtres, les oscillateurs et les antennes radio. Les transformateurs à ferrite haute fréquence (MHz) sont au cœur des alimentations à découpage (phone chargeurs, ordinateurs). Les ferrites de mode commun (câbles USB, HDMI) bloquent le bruit haute fréquence sans atténuer le signal utile.</p>'
    '<div class="highlight-box"><p>La trilogie R, L, C constitue la base de tous les circuits électroniques — leur association crée des comportements remarquables : filtrage, oscillation, résonance, qui sont exploités dans chaque appareil électronique.</p></div>'
    '<h3>Semiconducteurs : diodes et transistors</h3>'
    '<p class="resume-text">La <strong>diode</strong> est une jonction P-N qui permet le passage du courant dans un seul sens. En polarisation directe, la barrière de potentiel est franchie et le courant circule librement. La diode Zener exploite le claquage contrôlé pour réguler une tension. Les LED (Light Emitting Diodes) émettent de la lumière par recombinaison radiative — leur efficacité lumineuse dépasse 200 lm/W, contre 15 lm/W pour l\'ampoule incandescente. La photodiode (capteur) opère en polarisation inverse, générant un courant proportionnel à la lumière reçue.</p>'
    '<p class="resume-text">Le <strong>transistor bipolaire</strong> (BJT) contrôle un courant collecteur important par un faible courant de base (gain β = 100 à 500). Les <strong>MOSFET</strong> sont contrôlés par tension (résistance d\'entrée quasi infinie), ce qui les rend parfaits pour les circuits logiques CMOS à faible consommation. Les MOSFET de puissance (100A, 650V) contrôlent les variateurs de vitesse, les onduleurs solaires et les voitures électriques. Les IGBT combinent les avantages des BJT et MOSFET pour les applications haute tension et fort courant.</p>'
    '<p class="resume-text">À l\'échelle nanométrique, les <strong>FinFET</strong> et GAA (Gate All Around) FET remplacent les MOSFET planaires dans les processeurs modernes. Les processeurs en 3nm (Apple M3, TSMC N3) contiennent plus de 15 milliards de transistors dans un chip de quelques cm² — chaque transistor est 10 000 fois plus fin qu\'un cheveu humain. Le packaging avancé (chiplets, stacking 3D) prolonge les gains de densité au-delà des limites de la lithographie.</p>'
    '<div class="highlight-box"><p>Un processeur Apple M3 en 3nm contient plus de 25 milliards de transistors dans un chip de 18 mm² — une densité d\'intégration qui aurait semblé magique aux pionniers de l\'électronique des années 1960.</p></div>'
    '<h3>Circuits intégrés et FPGA</h3>'
    '<p class="resume-text">Les <strong>circuits intégrés</strong> (CI) intègrent des milliers à des milliards de composants dans un chip de silicium. Les CI analogiques (amplificateurs op, références de tension, convertisseurs) coexistent avec les CI numériques (microprocesseurs, mémoires, FPGA). La conception d\'un CI ASIC en 7nm coûte 50 à 500 millions d\'euros rien qu\'en frais de conception et de masques de lithographie — réservée aux volumes de production élevés.</p>'
    '<p class="resume-text">Les <strong>FPGA</strong> (Field-Programmable Gate Array) sont des circuits reconfigurables constitués de milliers de blocs logiques connectables par une matrice de commutation programmable. Contrairement aux ASIC gravés définitivement, les FPGA se reprogramment à la demande pour implémenter n\'importe quelle fonction numérique. Les FPGA Xilinx Virtex et Intel Stratix équipent les radios logicielles (SDR), les accélérateurs IA et les prototypes d\'ASIC. Leur consommation et coût sont plus élevés qu\'un ASIC de même fonction, mais leur flexibilité est sans équivalent.</p>'
    '<p class="resume-text">Les <strong>circuits RF intégrés</strong> (RFIC) intègrent toute la chaîne de traitement radio (LNA, mélangeur, synthétiseur de fréquence, PA) dans un seul chip. Un chip WiFi 802.11ax (WiFi 6) en 28nm intègre des centaines de millions de transistors qui gèrent simultanément 8 flux spatiaux (MIMO 8×8), le codage OFDMA et la synchronisation temporelle à la nanoseconde. La densité d\'intégration de ces SoC (System on Chip) de communication a rendu possible le smartphone moderne.</p>'
    '<div class="highlight-box"><p>Le SoC Apple A17 Pro (téléphone) intègre CPU, GPU, Neural Engine, modem 5G et contrôleurs mémoire dans un chip de 107 mm² — un niveau de complexité qui nécessite des milliers d\'ingénieurs et plusieurs années de développement.</p></div>'
)

enrichments['electronique/circuits-analogiques'] = (
    '<h3>Amplificateurs opérationnels et applications</h3>'
    '<p class="resume-text">L\'<strong>amplificateur opérationnel</strong> (AO) est un circuit intégré à deux entrées et une sortie, avec un gain en boucle ouverte très élevé (10⁵ à 10⁶). En montage inverseur, le gain est -R2/R1 ; en non-inverseur, 1 + R2/R1. Le montage <strong>suiveur</strong> (gain unité) est utilisé pour l\'adaptation d\'impédance : la haute impédance d\'entrée isole la source de la charge. L\'AO idéal a une impédance d\'entrée infinie, une impédance de sortie nulle et une bande passante infinie.</p>'
    '<p class="resume-text">Les <strong>filtres actifs</strong> associent AO et composants passifs pour réaliser des fonctions de transfert précises. Le filtre de Sallen-Key réalise un filtre du second ordre avec deux résistances et deux condensateurs autour d\'un AO. Les filtres de Butterworth (réponse plate en bande passante), de Chebyshev (transition raide) et de Bessel (phase linéaire) correspondent à différents compromis selon l\'application. En cascade, ces filtres du 2e ordre réalisent des filtres d\'ordre élevé (8e, 10e ordre) pour les applications audio et de mesure.</p>'
    '<p class="resume-text">Les <strong>applications spécialisées</strong> des AO incluent le convertisseur courant-tension (transimpédance, pour les photodiodes et capteurs de courant), l\'intégrateur (antidérive servo-moteurs), le détecteur de valeur de crête et le générateur de signaux (triangulaire, carré). Les amplificateurs d\'instrumentation (INA128, AD620) offrent une excellente rejection du mode commun (CMRR &gt; 120 dB) pour les mesures de faibles signaux sur fond de bruit commun (ECG, jauges de déformation).</p>'
    '<div class="highlight-box"><p>L\'amplificateur opérationnel est le composant analogique le plus polyvalent — seule la configuration du câblage externe change son rôle d\'amplificateur, intégrateur, filtre ou générateur de signal.</p></div>'
    '<h3>Alimentations à découpage et gestion de l\'énergie</h3>'
    '<p class="resume-text">Les <strong>alimentations à découpage</strong> (SMPS — Switched-Mode Power Supply) utilisent un transistor de puissance commutant à haute fréquence (50 kHz à 2 MHz) pour transférer l\'énergie de l\'entrée vers la sortie via un transformateur ou une bobine. Leur rendement (90-97%) est bien supérieur aux régulateurs linéaires (40-60%). Les topologies buck (abaisseur de tension), boost (élévateur) et buck-boost couvrent tous les besoins de conversion DC-DC. Les chargeurs rapides (GaN — nitrure de gallium) des smartphones 65W tiennent dans le volume d\'un cube de 4cm grâce au GaN qui commute à 1 MHz.</p>'
    '<p class="resume-text">La <strong>gestion de batterie</strong> (BMS — Battery Management System) surveille tension, courant et température de chaque cellule pour maximiser la durée de vie et la sécurité. L\'équilibrage actif transfère l\'énergie des cellules les plus chargées vers les moins chargées, améliorant la capacité utilisable de 5 à 15%. Les algorithmes de SOC (State of Charge) et SOH (State of Health) utilisent des modèles électrochimiques et des filtres de Kalman pour estimer précisément l\'état de la batterie en temps réel.</p>'
    '<p class="resume-text">Les <strong>convertisseurs AC-DC</strong> (rectifieurs, PFC — Power Factor Correction) et DC-AC (onduleurs) assurent l\'interface entre le réseau électrique et les équipements électroniques. Les onduleurs solaires transforment le courant continu des panneaux PV en courant alternatif synchronisé avec le réseau. Les variateurs de fréquence industriels (ABB, Schneider, Danfoss) contrôlent la vitesse des moteurs AC en générant une tension et fréquence ajustables grâce à des ponts d\'IGBT commandés en MLI (Modulation de Largeur d\'Impulsion).</p>'
    '<div class="highlight-box"><p>Les chargeurs GaN (nitrure de gallium) ont remplacé le silicium dans les chargeurs rapides de smartphones : 3 fois plus petits et 5% plus efficaces pour les mêmes spécifications de puissance.</p></div>'
    '<h3>Traitement du signal et conditionnement de capteurs</h3>'
    '<p class="resume-text">Le <strong>conditionnement de signal</strong> prépare les signaux de capteurs (thermocouples, jauges de déformation, capteurs de pression) pour leur numérisation. Il inclut l\'amplification, le filtrage anti-repliement et l\'isolation galvanique. La boucle courant 4-20 mA est le standard industriel pour la transmission sur longue distance : insensible aux chutes de tension dans les câbles, le signal "4 mA au repos" permet de détecter une rupture de câble. Ces interfaces équipent les capteurs de pression, les débitmètres et les analyseurs industriels.</p>'
    '<p class="resume-text">Les <strong>oscilloscopes et analyseurs de spectre</strong> sont les outils fondamentaux du prototypage électronique. Les oscilloscopes numériques modernes (Keysight, Tektronix) échantillonnent à 20-100 GSPS avec 12 bits de résolution, capturant des phénomènes de quelques picosecondes. L\'analyse spectrale (FFT) révèle les composantes fréquentielles d\'un signal. Les analyseurs de réseau vectoriels (VNA) mesurent les paramètres S des circuits RF en magnitude et phase — outil indispensable pour les antennes et filtres 5G.</p>'
    '<p class="resume-text">La <strong>CEM</strong> (Compatibilité ÉlectroMagnétique) est la discipline qui assure qu\'un équipement électronique n\'émet pas de perturbations excessives et fonctionne correctement en présence de celles des autres. Les normes CE (Europe), FCC (USA) et CISPR imposent des limites d\'émission et des niveaux d\'immunité. Les techniques de filtrage (ferrites, condensateurs X/Y), de blindage (cages de Faraday) et de routage des circuits imprimés (plans de masse, paires différentielles) sont les outils du concepteur CEM.</p>'
    '<div class="highlight-box"><p>La norme CE marquant un produit électronique européen garantit sa conformité à la directive CEM — sans cette certification, l\'appareil ne peut pas être commercialisé en Europe, quelle que soient ses fonctionnalités.</p></div>'
)

enrichments['electronique/signaux-numeriques'] = (
    '<h3>Logique combinatoire et séquentielle</h3>'
    '<p class="resume-text">La <strong>logique combinatoire</strong> produit une sortie uniquement fonction des entrées actuelles. Tables de vérité, équations booléennes et diagrammes de Karnaugh (K-map) simplifient ces fonctions. Le théorème de De Morgan (¬(A·B) = ¬A + ¬B) est fondamental pour la conception en portes NAND ou NOR. Les décodeurs, multiplexeurs, additionneurs et comparateurs sont des fonctions combinatoires de base des ALU (Arithmetic Logic Unit) des processeurs.</p>'
    '<p class="resume-text">La <strong>logique séquentielle</strong> introduit la mémoire via les bascules D, JK et RS. Les registres (alignements de bascules) et les compteurs (registres auto-incrémentés) sont les blocs de base des machines d\'états. Une FSM (Finite State Machine) de Moore ou Mealy décrit tout système numérique séquentiel : protocoles de communication, séquenceurs d\'automates, circuits de contrôle. L\'outil VHDL ou Verilog permet de décrire et simuler ces machines avant leur synthèse en FPGA ou ASIC.</p>'
    '<div class="highlight-box"><p>La loi de Moore prédisait le doublement du nombre de transistors tous les 18-24 mois depuis 1965 — cette progression a permis de passer des premiers microprocesseurs 4 bits aux puces à 25 milliards de transistors actuelles.</p></div>'
    '<h3>Convertisseurs analogique-numérique et numérique-analogique</h3>'
    '<p class="resume-text">Le <strong>convertisseur analogique-numérique</strong> (ADC) quantifie un signal analogique en valeur numérique. La résolution (nombre de bits) détermine la précision : un ADC 16 bits divise la plage en 65536 niveaux. La fréquence d\'échantillonnage doit respecter le théorème de Shannon-Nyquist : au moins le double de la fréquence maximale du signal. Les ADC SAR (successive approximation) offrent un bon compromis résolution/vitesse ; les ADC Sigma-Delta atteignent 24-32 bits pour les mesures de précision.</p>'
    '<p class="resume-text">Les <strong>convertisseurs numériques-analogiques</strong> (DAC) reconstituent un signal analogique depuis sa représentation numérique. Les DAC R-2R (réseau en échelle de résistances) sont simples et précis. Dans les télécommunications modernes, des DAC à 16 bits fonctionnant à 100 GSPS génèrent les signaux modulés 5G à des débits dépassant plusieurs Gbit/s par canal. L\'interpolation numérique (overshooting, filtrage en bande de base) et les algorithmes de prédistorsion compensent les non-linéarités des convertisseurs haute vitesse.</p>'
    '<p class="resume-text">Les <strong>systèmes de traitement numérique du signal</strong> (DSP) exécutent des opérations de filtrage, transformée de Fourier rapide (FFT) et corrélation à haute vitesse. Les DSP Texas Instruments (TMS320) et les FPGA en mode traitement signal (Xilinx, Intel) sont les plateformes standard. Le traitement numérique a remplacé presque entièrement l\'analogique dans les communications (modems, WiFi, 5G), l\'audio (égaliseurs, effets), l\'imagerie médicale et la radar.</p>'
    '<div class="highlight-box"><p>Toute interface entre le monde physique (analogique) et le numérique passe par un ADC — du thermomètre numérique au scanner IRM, en passant par les microphones de smartphone et les haut-parleurs Bluetooth.</p></div>'
    '<h3>Protocoles de communication numérique</h3>'
    '<p class="resume-text">Les <strong>protocoles série synchrones</strong> SPI et I2C sont omniprésents dans les microcontrôleurs. SPI (4 fils, maître/esclaves) atteint 80 Mbit/s pour les mémoires Flash et écrans ; I2C (2 fils, adressage 7 bits) convient pour les capteurs à faible débit sur bus partagé. L\'UART (Universal Asynchronous Receiver Transmitter) assure la communication série asynchrone entre microcontrôleurs et ordinateurs depuis les origines de l\'informatique embarquée.</p>'
    '<p class="resume-text">L\'<strong>USB</strong> (Universal Serial Bus) est la référence pour l\'interface homme-machine et le transfert de données. USB 2.0 (480 Mbit/s), USB 3.2 (20 Gbit/s) et USB4 (40 Gbit/s, basé sur Thunderbolt) couvrent tous les besoins de débit. La négociation de puissance USB Power Delivery (USB-PD) jusqu\'à 240W a unifié les chargeurs de laptops, smartphones et tablettes. Le connecteur USB-C réversible est devenu le standard universel de l\'électronique grand public.</p>'
    '<p class="resume-text">L\'<strong>Ethernet</strong> domine les réseaux filaires depuis 50 ans. Du 10BASE-T (10 Mbit/s, 1990) au 400GbE (400 Gbit/s, 2018) en passant par l\'omniprésent Gigabit Ethernet (1000BASE-T, câble CAT5e), sa longevité repose sur une évolution continue des couches physique (modulation PAM-4 pour le 400G) et logicielle (IEEE 802.3). L\'Ethernet industriel (PROFINET, EtherCAT, TSN — Time-Sensitive Networking) apporte le déterminisme temps réel nécessaire aux réseaux d\'automatisme.</p>'
    '<div class="highlight-box"><p>USB-C est devenu le connecteur universel de l\'électronique moderne — données à 40 Gbit/s, puissance à 240W, vidéo 8K et audio dans un seul petit connecteur réversible, simplifiant radicalement la connectique.</p></div>'
)

enrichments['electronique/microprocesseurs'] = (
    '<h3>Architecture des processeurs modernes</h3>'
    '<p class="resume-text">Un <strong>microprocesseur</strong> comprend l\'unité arithmétique et logique (UAL), les registres, l\'unité de contrôle et les interfaces mémoire. Les architectures CISC (x86) ont des instructions complexes et variables ; les architectures RISC (ARM, RISC-V) ont des instructions simples de taille fixe, plus faciles à optimiser. Le <strong>pipeline</strong> parallélise les étapes d\'exécution (Fetch, Decode, Execute, Memory, Writeback). Un pipeline à 5 étages peut traiter presque 5 instructions par cycle — les processeurs modernes exécutent 4 à 8 instructions simultanément.</p>'
    '<p class="resume-text">La <strong>prédiction de branchement</strong> est cruciale car les instructions conditionnelles brisent le pipeline. Les prédicteurs modernes atteignent 99% de précision en exploitant l\'historique d\'exécution. La faille de sécurité Spectre (2018) a révélé que cette optimisation peut être exploitée pour lire des données privées — illustrant la tension entre performance et sécurité. Les correctifs matériels et logiciels ont réduit les performances de 5 à 30% selon les configurations.</p>'
    '<div class="highlight-box"><p>Un processeur Apple M4 exécute jusqu\'à 10 instructions par cycle à 4 GHz, soit 40 milliards d\'opérations par seconde dans un seul cœur — et jusqu\'à 400 milliards pour les 10 cœurs combinés.</p></div>'
    '<h3>Hiérarchie mémoire et cache</h3>'
    '<p class="resume-text">La <strong>hiérarchie mémoire</strong> compense le fossé entre la vitesse du processeur (cycles de 0,25 ns à 4 GHz) et la latence de la RAM (50-100 ns). Les caches L1 (32 KB, 1 cycle), L2 (256 KB, 5 cycles) et L3 (jusqu\'à 64 MB dans les serveurs, 30 cycles) gardent les données fréquemment accédées. La règle du 80/20 (80% des accès concernent 20% des données) rend les caches très efficaces — un programme bien optimisé s\'exécute 10 à 100 fois plus vite qu\'un programme qui ignore la hiérarchie mémoire.</p>'
    '<p class="resume-text">La <strong>cohérence de cache</strong> pose problème dans les systèmes multi-cœurs. Les protocoles MESI (Modified, Exclusive, Shared, Invalid) gèrent les états et ordonnent les transferts entre caches. La mémoire non-uniforme (NUMA) des serveurs multi-processeurs impose des précautions dans le placement des données. Les benchmarks de performance sont fortement influencés par les effets de cache — un algorithme de tri peut être 10x plus lent simplement parce qu\'il accède à la mémoire dans le mauvais ordre.</p>'
    '<p class="resume-text">La <strong>mémoire virtuelle</strong> donne à chaque processus l\'illusion d\'un espace d\'adressage privé continu. La MMU (Memory Management Unit) traduit les adresses virtuelles en physiques via des tables de pages, avec le TLB (Translation Lookaside Buffer) pour accélérer les traductions fréquentes. Les mécanismes de protection mémoire (lecture seule, NX — No eXecute) sont la base de la sécurité des OS modernes : un processus ne peut ni lire ni modifier la mémoire d\'un autre processus.</p>'
    '<div class="highlight-box"><p>Sans hiérarchie de cache, les processeurs modernes passeraient 99% de leur temps à attendre la mémoire — les caches sont le secret de leurs performances réelles, bien au-delà de la fréquence d\'horloge.</p></div>'
    '<h3>GPU et processeurs spécialisés</h3>'
    '<p class="resume-text">Le <strong>GPU</strong> (Graphics Processing Unit) est un processeur massivement parallèle avec des milliers de cœurs simples (CUDA cores pour NVIDIA), optimisé pour les opérations de calcul sur tableaux (matrices, vecteurs). Un NVIDIA H100 dispose de 16 896 cœurs CUDA et peut effectuer 3958 TFLOPS en précision TF32 — 100 fois plus qu\'un CPU haut de gamme pour les calculs de réseaux de neurones. Les frameworks PyTorch et TensorFlow abstrait le GPU pour les chercheurs en IA.</p>'
    '<p class="resume-text">Les <strong>NPU</strong> (Neural Processing Units) spécialisés pour l\'inférence de réseaux de neurones offrent une efficacité énergétique 10 à 100 fois supérieure aux GPU pour les calculs fixes. Apple Neural Engine (6,5 TOPS à 0,5W), Google TPU v4 (275 TFLOPS), Qualcomm Hexagon — ces accélérateurs sont intégrés dans les SoC des smartphones, voitures et serveurs cloud pour l\'IA embarquée. Leur architecture (systolic arrays, MAC en entiers 8 bits, mémoire on-chip) est radicalement différente du CPU général.</p>'
    '<p class="resume-text">Les <strong>RISC-V</strong> ouvrent l\'ère du processeur ouvert et personnalisable. Cette architecture ISA (Instruction Set Architecture) libre de droits permet à tout développeur de concevoir son propre processeur sans payer de licence. Les startups (SiFive, Esperanto), les géants (Western Digital, Alibaba) et les académiques utilisent RISC-V pour des processeurs embarqués, des extensions spécialisées (crypto, IA) et des puces souveraines. La Chine investit massivement dans RISC-V pour s\'émanciper des licences Intel/ARM.</p>'
    '<div class="highlight-box"><p>Un cluster de GPU NVIDIA H100 alimente ChatGPT — chaque réponse générée nécessite des milliards de calculs matriciels effectués par ces cartes à 30 000$ chacune, consommant des dizaines de kWh par heure d\'utilisation.</p></div>'
)

enrichments['electronique/systemes-embarques'] = (
    '<h3>Systèmes d\'exploitation temps réel (RTOS)</h3>'
    '<p class="resume-text">Un <strong>RTOS</strong> garantit que les tâches critiques s\'exécutent dans leur fenêtre temporelle. FreeRTOS (le plus déployé, open-source), VxWorks (aviation, espace) et QNX (automobiles, médical) sont les références. L\'ordonnancement préemptif à priorité fixe (Rate Monotonic) assigne les priorités selon les fréquences : la tâche la plus fréquente a la plus haute priorité. L\'analyse de faisabilité garantit mathématiquement que toutes les échéances seront respectées.</p>'
    '<p class="resume-text">La <strong>communication inter-tâches</strong> (files de messages, sémaphores, mutex) synchronise les tâches concurrentes. L\'inversion de priorité est un piège classique : une tâche haute priorité attend un mutex détenu par une tâche basse priorité bloquée par des tâches intermédiaires. Ce bug a failli compromettre la sonde Mars Pathfinder en 1997 — et illustre la complexité des systèmes temps réel. Le protocole d\'héritage de priorité corrige ce problème en élevant temporairement la priorité du détenteur du mutex.</p>'
    '<div class="highlight-box"><p>Le bug d\'inversion de priorité de Mars Pathfinder (1997) a nécessité une correction depuis la Terre à 80 millions de km de distance — un exemple historique des défis des systèmes temps réel embarqués.</p></div>'
    '<h3>Protocoles de communication embarqués</h3>'
    '<p class="resume-text">Le <strong>CAN bus</strong> (Controller Area Network, Bosch 1986) permet à des dizaines d\'ECU de communiquer sur un bus partagé à deux fils. Son arbitrage non-destructif et sa détection d\'erreurs robuste le rendent idéal pour les environnements bruités. Une voiture moderne contient jusqu\'à 100 ECU interconnectés par CAN, CAN-FD (débits jusqu\'à 8 Mbit/s) et Ethernet embarqué (100BASE-T1 pour les flux vidéo). Le CAN est aussi utilisé dans l\'aéronautique, l\'industrie et les robots.</p>'
    '<p class="resume-text">Pour les <strong>objets connectés</strong>, les protocoles sans fil incluent Zigbee (réseaux maillés, domotique), BLE 5.0 (wearables), LoRaWAN (LPWAN, longue portée, faible débit), NB-IoT (cellulaire, infrastructure opérateur) et Matter (standard unifié Google/Apple/Amazon). Le choix dépend du compromis portée/débit/consommation : un capteur agricole sur batterie solaire utilisera LoRaWAN, un écouteur Bluetooth choisira BLE, une alarme connectée préférera NB-IoT pour sa couverture opérateur.</p>'
    '<p class="resume-text">L\'<strong>Ethernet industriel temps réel</strong> (PROFINET, EtherCAT, TSN) apporte le déterminisme et la haute disponibilité aux réseaux d\'automatisme. EtherCAT (Beckhoff) traite 1000 axes en 30 μs sur un seul réseau. TSN (Time-Sensitive Networking, IEEE 802.1Qbv) réserve des créneaux temporels pour les trames critiques dans un Ethernet standard. Ces protocoles unifient les réseaux d\'automatisme (PROFIBUS, DeviceNet) sous une infrastructure Ethernet commune dans les usines Industrie 4.0.</p>'
    '<div class="highlight-box"><p>Un véhicule électrique moderne contient plus de 100 ECU échangeant plusieurs gigabits de données par seconde sur CAN, CAN-FD et Ethernet embarqué — les protocoles embarqués sont le système nerveux de l\'automobile contemporaine.</p></div>'
    '<h3>Sécurité fonctionnelle et cybersécurité</h3>'
    '<p class="resume-text">La <strong>sécurité fonctionnelle</strong> (IEC 61508, ISO 26262 automobile, DO-178C avionique) vise à garantir le fonctionnement correct même en présence de défaillances. Les niveaux d\'intégrité SIL/ASIL définissent les exigences selon le risque. Les techniques de redondance matérielle (triplex, TMR) et logicielle (versions diversifiées) sont obligatoires pour les systèmes critiques. Les calculateurs de vol Airbus utilisent trois canaux redondants en technologies différentes pour éviter les défaillances de mode commun.</p>'
    '<p class="resume-text">La <strong>cybersécurité des systèmes embarqués</strong> est devenue critique avec la connectivité croissante. En 2015, des chercheurs ont pris le contrôle à distance d\'une Jeep Cherokee via son système multimédia connecté — déclenchant le rappel de 1,4 million de véhicules. Les techniques de défense incluent le démarrage sécurisé (secure boot, vérification cryptographique), la mise à jour sécurisée OTA (Over The Air), la segmentation réseau et les HSM (Hardware Security Modules) pour la gestion des clés cryptographiques.</p>'
    '<p class="resume-text">L\'<strong>edge computing</strong> déplace le traitement des données vers les appareils en périphérie du réseau plutôt que vers le cloud. Pour les systèmes embarqués, cela signifie exécuter localement des algorithmes d\'IA (inférence sur capteurs caméra, microphone), réduire la latence (de 100ms réseau à 1ms local) et améliorer la confidentialité (données traitées sans quitter l\'appareil). Les microcontrôleurs TinyML (ARM Cortex-M avec NPU, comme STM32N6 ou Nordic nRF9160) permettent des inférences neuronales dans des budgets de 1 mW.</p>'
    '<div class="highlight-box"><p>Les microcontrôleurs TinyML exécutent des réseaux de neurones compressés (quantifiés en INT8) sur des puces à 1 mW — permettant à un capteur sur batterie de reconnaître des anomalies sonores ou vibratoires sans connexion cloud.</p></div>'
)

# Apply enrichments
count = 0
for key, extra in enrichments.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (electronique section)")
