#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement botanique-zoologie - batch 1 (11 pages)."""

import json, re

FILE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/botanique-zoologie.json"

ENRICHMENTS = {
"zoologie/anatomie-comparee": """
<h3>L'homologie et l'analogie : deux types de ressemblances</h3>
<p class="resume-text">L'anatomie comparée distingue deux types fondamentaux de ressemblances morphologiques entre espèces. L'homologie désigne des structures qui partagent une même origine évolutive, même si elles ont divergé en forme et en fonction : le bras de l'homme, l'aile de la chauve-souris, la nageoire pectorale du dauphin et la patte avant du cheval sont des structures homologues — toutes dérivées du même membre antérieur de l'ancêtre tétrapode commun. L'analogie, en revanche, désigne des structures qui remplissent la même fonction sans partager d'origine commune : l'aile d'un insecte et l'aile d'un oiseau sont analogues (convergence évolutive vers le vol) mais absolument pas homologues.</p>
<p class="resume-text">La distinction homologie/analogie est fondamentale pour reconstruire l'arbre du vivant. La systématique phylogénétique (cladistique), développée par Willi Hennig dans les années 1950, repose sur l'identification de "caractères dérivés partagés" (synapomorphies) — des homologies qui permettent de regrouper les espèces selon leur histoire évolutive. Les ressemblances analogiques (homoplasies), dues à la convergence évolutive, peuvent induire en erreur l'analyse phylogénétique si elles ne sont pas identifiées comme telles. La phylogénomique (utilisation des séquences d'ADN) a permis de résoudre de nombreux débats phylogénétiques en s'affranchissant des confusions analogie/homologie.</p>
<div class="highlight-box"><p>L'œil des vertébrés et l'œil des céphalopodes (pieuvres, calmars) sont l'exemple classique de convergence évolutive : deux organes visuels d'une complexité remarquable, quasi identiques en apparence, mais d'origines embryologiques totalement différentes et donc analogues. L'œil des céphalopodes est même "mieux conçu" que celui des vertébrés : il ne possède pas de tache aveugle, car ses photorécepteurs sont orientés vers la lumière, contrairement à ceux des vertébrés.</p></div>

<h3>Les grands plans d'organisation du règne animal</h3>
<p class="resume-text">Le règne animal est organisé selon des plans corporels (Baupläne) qui définissent les grands groupes. La symétrie corporelle est un premier critère : les éponges (Porifera) sont asymétriques ; les cnidaires (méduses, coraux) possèdent une symétrie radiale ; la grande majorité des animaux ont une symétrie bilatérale (gauche-droite identiques), qui est associée à la céphalisation (concentration des organes sensoriels à l'avant) et à la locomotion directionnelle. L'existence ou non d'un coelome (cavité corporelle interne) divise les bilatériens en acoelomates (plathelminthes), pseudocoélomates (nématodes) et coelomates (vers annélides, mollusques, échinodermes, vertébrés).</p>
<p class="resume-text">Le développement embryonnaire révèle deux grandes lignées de coelomates : les protostomiens (où le blastopore embryonnaire devient la bouche) comprenant les arthropodes, les mollusques et les annélides ; et les deutérostomiens (où le blastopore devient l'anus et la bouche se forme secondairement) comprenant les échinodermes et les chordés. Cette distinction, fondée sur le développement, est confirmée par les données moléculaires modernes. Le séquençage ARN a récemment révélé d'importantes réorganisations dans l'arbre du vivant animal, regroupant par exemple les arthropodes, les nématodes et les tardigrades dans le clade des Ecdysozoaires (animaux à mue).</p>
<div class="highlight-box"><p>Les tardigrades ("oursons d'eau"), de minuscules animaux de 0,1 à 1,5 mm, possèdent l'une des anatomies les plus simplifiées parmi les animaux à plan d'organisation complexe. Leur résistance extraordinaire (ils survivent dans le vide spatial, aux radiations, à des températures de -273 °C et +150 °C en état de cryptobiose) en font des organismes modèles pour l'astobiologie et la recherche sur la résilience du vivant.</p></div>
""",

"zoologie/evolution-animale": """
<h3>Les grandes extinctions et leur rôle dans l'évolution animale</h3>
<p class="resume-text">L'histoire de la vie sur Terre est ponctuée de cinq grandes extinctions de masse qui ont profondément reconfiguré la diversité animale. La plus dévastatrice, la crise Permo-Trias (252 Ma), a éliminé environ 96 % des espèces marines et 70 % des espèces terrestres en moins de 60 000 ans — probablement causée par un volcanisme gigantesque en Sibérie (Trapps de Sibérie) qui a libéré d'immenses quantités de CO₂ et provoqué un réchauffement et une acidification des océans. La crise Crétacé-Paléogène (66 Ma), attribuée à l'impact d'un astéroïde à Chicxulub (Mexique), a éliminé les dinosaures non-aviens et 75 % des espèces, ouvrant la voie à la diversification des mammifères.</p>
<p class="resume-text">Ces extinctions, catastrophiques pour leurs contemporains, ont été des "opportunités évolutives" pour les groupes survivants. Après l'extinction Permo-Trias, les archosaures (dont les dinosaures) ont dominé les écosystèmes terrestres du Trias. Après la crise K-Pg, les mammifères placentaires ont explosé en diversité en 10 millions d'années (radiation adaptative), colonisant toutes les niches écologiques laissées vacantes par les dinosaures. Cette dynamique extinction-radiation est un moteur majeur de la macroévolution.</p>
<div class="highlight-box"><p>Nous vivons actuellement la sixième extinction de masse, la première causée par une espèce biologique : l'Homo sapiens. Le taux d'extinction actuel est estimé 100 à 1 000 fois supérieur au taux naturel. Contrairement aux extinctions passées (causes abiotiques), celle-ci est réversible si les activités humaines sont modifiées — ce qui la rend à la fois plus tragique et plus urgente à enrayer.</p></div>

<h3>La spéciation : comment naissent les nouvelles espèces</h3>
<p class="resume-text">La spéciation est le processus par lequel une population ancestrale donne naissance à deux ou plusieurs espèces distinctes. Le mécanisme le plus fréquent est la spéciation allopatrique : une barrière géographique (chaîne de montagnes, bras de mer, désert) isole deux populations qui évoluent indépendamment jusqu'à devenir génétiquement incompatibles. Les Galápagos sont un laboratoire mondial de spéciation allopatrique : chaque île a ses propres espèces de pinsons, d'iguanes et de tortues géantes, issues d'ancêtres communs qui ont colonisé les différentes îles.</p>
<p class="resume-text">La spéciation sympatrique (sans isolement géographique) est plus controversée mais documentée : elle peut résulter d'une spécialisation écologique (deux populations exploitant différentes ressources dans le même habitat), d'une polyploïdisation (doublement du nombre de chromosomes, fréquent chez les plantes), ou de mécanismes de sélection sexuelle (les femelles préférant un type de mâle crée un isolement reproductif progressif). Les cichlidés des lacs africains (Victoria, Malawi, Tanganyika) illustrent des radiations adaptatives fulgurantes : plusieurs centaines d'espèces ont évolué en 15 000 ans dans le lac Victoria à partir de quelques espèces colonisatrices.</p>
<div class="highlight-box"><p>Le concept d'"espèce", apparemment intuitif, est scientifiquement difficile à définir. Le concept biologique d'espèce (Ernst Mayr, 1942) — "groupe de populations naturelles effectivement ou potentiellement interfécondes et reproductivement isolées des autres groupes" — s'applique mal aux organismes asexués, aux fossiles et aux populations géographiquement séparées. Plus de 20 définitions alternatives de "l'espèce" coexistent en biologie évolutive.</p></div>

<h3>La sélection sexuelle : Darwin et les ornements extravagants du vivant</h3>
<p class="resume-text">Darwin a proposé dès 1871, dans "La descendance de l'homme et la sélection sexuelle", que certains traits apparemment désavantageux pour la survie (la queue du paon, les bois démesurés de l'élan mégalocéros, le plumage éclatant des oiseaux de paradis) pouvaient évoluer si ils augmentaient le succès reproducteur. La sélection sexuelle opère selon deux mécanismes : la compétition intrasexuelle (les mâles se battent entre eux pour l'accès aux femelles — sélection intrasexuelle) et le choix du partenaire (les femelles choisissent les mâles selon leurs attributs — sélection intersexuelle).</p>
<p class="resume-text">Le paradoxe de la queue du paon — pourquoi une femelle "rationnel" choisirait-elle un mâle encombré d'une queue qui le rend vulnérable aux prédateurs ? — a été résolu par plusieurs hypothèses. Le "principe du handicap" d'Amotz Zahavi propose que seuls les mâles génétiquement supérieurs peuvent se permettre le luxe d'un tel handicap, qui est donc un signal honnête de qualité génétique. L'hypothèse du "fils sexy" propose que les femelles qui choisissent les mâles ornementés auront des fils eux-mêmes attractifs — un avantage indirect. Ces mécanismes de sélection sexuelle expliquent une large gamme d'ornements, comportements et structures dans le règne animal.</p>
<div class="highlight-box"><p>L'oiseau jardinier (Ptilonorhynchus violaceus) d'Australie construit des berceaux ou tonnelles décorés avec une précision et un goût artistique qui fascinent les biologistes : il sélectionne soigneusement des objets bleus (plumes, baies, bouchons de bouteilles) pour séduire les femelles, et crée des illusions d'optique en disposant les objets pour faire paraître sa tonnelle plus grande vue depuis l'intérieur. Cette "esthétique" animale soulève des questions philosophiques sur les origines du sens artistique humain.</p></div>
""",

"ethologie/comportement-animal": """
<h3>Les fondateurs de l'éthologie : Lorenz, Tinbergen et von Frisch</h3>
<p class="resume-text">L'éthologie, étude scientifique du comportement animal dans son milieu naturel, s'est constituée comme discipline dans les années 1930-1960. Karl von Frisch a décrypté le "langage" des abeilles (la danse en huit qui encode direction et distance des sources de nourriture), Konrad Lorenz a étudié l'empreinte chez les oies (le jeune animal s'attache au premier objet mobile qu'il voit à l'éclosion) et décrit les mécanismes déclencheurs innés, Nikolaas Tinbergen a proposé ses quatre questions fondamentales qui structurent encore l'éthologie moderne : causalité immédiate (quel mécanisme déclenche le comportement ?), développement ontogénétique, valeur adaptative, et origine évolutive. Ces trois chercheurs ont partagé le prix Nobel de physiologie ou médecine en 1973.</p>
<p class="resume-text">La sociobiologie, inaugurée par E.O. Wilson avec "Sociobiology : The New Synthesis" (1975), a cherché à expliquer le comportement social des animaux (et par extension de l'homme) en termes de sélection naturelle et génétique. Les travaux de William Hamilton sur la "valeur inclusive" (inclusive fitness) ont formalisé l'altruisme apparent : un animal peut favoriser la transmission de ses gènes en aidant des parents proches qui partagent une partie de son génome (règle de Hamilton : r × B > C, où r = coefficient de parenté, B = bénéfice pour le bénéficiaire, C = coût pour le donneur).</p>
<div class="highlight-box"><p>Konrad Lorenz a découvert l'empreinte filiale en observant des oies cendréées : les oissons qui s'attachent au premier objet mobile qu'ils perçoivent à l'éclosion peuvent "s'imprimer" sur un être humain si Lorenz est la première chose qu'ils voient. Il a ainsi étudié des familles d'oies qui le suivaient partout comme une mère oie — un exemple devenu emblématique des périodes critiques de développement comportemental.</p></div>

<h3>Comportements innés et comportements appris</h3>
<p class="resume-text">La distinction entre comportements innés (instinctifs, génétiquement programmés) et comportements appris (acquis par l'expérience) est un axe fondamental de l'éthologie. Les comportements innés se manifestent sans apprentissage préalable : la toile de l'araignée, le chant d'alarme inné des oiseaux, les migrations des saumons vers leur rivière natale. Ils sont souvent déclenchés par des "stimuli-clés" très spécifiques : un rouge sur la gorge d'un modèle de rouge-gorge suffit à déclencher une attaque territoriale. La superstimulation (super-stimulus) révèle la mécanique de ces déclencheurs : une oie préférera couver un œuf géant artificiel à ses propres œufs normaux si il est plus grand et plus moucheté.</p>
<p class="resume-text">Les comportements appris sont plus flexibles et coûteux : ils nécessitent une structure cérébrale plus développée, du temps et des ressources. L'habituation (cesser de répondre à un stimulus non significatif), le conditionnement classique (Pavlov), le conditionnement opérant (Skinner), l'apprentissage par imitation et l'apprentissage par insight (résolution soudaine d'un problème nouveau, comme les singes de Köhler qui empilent des caisses pour atteindre des bananes) forment un gradient de complexité cognitive. La culture animale — transmission sociale de comportements appris — a été documentée chez les chimpanzés, les orques, les dauphins et les oiseaux chanteurs.</p>
<div class="highlight-box"><p>Le poulpe, avec seulement 500 millions de neurones (contre 86 milliards chez l'humain), est capable d'apprentissage par observation : des poulpes témoins qui voient un congénère entraîné choisir un objet d'une certaine couleur apprennent à faire le même choix, sans avoir été eux-mêmes entraînés. Ces capacités cognitives chez un mollusque invertébré remettent en question notre compréhension de l'origine de l'intelligence.</p></div>

<h3>La cognition animale : des découvertes qui bousculent nos préjugés</h3>
<p class="resume-text">Les recherches des dernières décennies ont révélé des capacités cognitives insoupçonnées chez de nombreux animaux. Les corbeaux (Corvus corax) fabriquent et utilisent des outils plus complexes que ceux des grands singes : ils taillent des baguettes d'Araucaria pour extraire des larves, ils "cachent" de la nourriture en vérifiant qu'ils ne sont pas observés (théorie de l'esprit rudimentaire), ils se souviennent des visages humains menaçants et les transmettent à leurs descendants (tradition culturelle). Les dauphins ont un nom propre — un sifflement spécifique qui fonctionne comme une signature individuelle reconnue par les autres dauphins.</p>
<p class="resume-text">Les éléphants manifestent des comportements considérés comme spécifiquement humains : deuil des défunts (restent auprès du cadavre, revisitent les ossements des années après), conscience de soi (se reconnaissent dans un miroir — test du miroir), coopération altruiste, et possiblement des émotions comme la joie et la compassion. Les abeilles ont été démontrées capables de comprendre le concept de zéro — elles placent le zéro à gauche d'une série numérique croissante, comme le font les humains et les primates dans des expériences de numération, malgré leur cerveau d'un million de neurones.</p>
<div class="highlight-box"><p>La pieuvre Inky, détenue à l'aquarium national de Nouvelle-Zélande, a en 2016 glissé hors de son réservoir légèrement ouvert, traversé le sol de l'aquarium, s'est faufilée dans un tuyau de drainage de 50 m et a rejoint la mer. Cet "évasion" illustre les remarquables capacités cognitives et physiques des céphalopodes — et soulève des questions éthiques sur la détention d'animaux aussi intelligents.</p></div>
""",

"ethologie/communication-animale": """
<h3>Les modalités de la communication animale</h3>
<p class="resume-text">La communication animale utilise tous les sens : visuelle (couleurs, postures, signaux lumineux), acoustique (chants, cris, ultrasons, infrasons), chimique (phéromones, allomones, kairomones), tactile (toilettage, vibrations) et électrique (poissons électriques). Chaque modalité présente des avantages et inconvénients selon l'environnement : la communication chimique est persistante dans le temps et efficace la nuit mais non directionnelle ; la communication acoustique peut traverser des obstacles et couvrir de longues distances mais révèle la position de l'émetteur ; la communication visuelle est très informative mais nécessite la lumière et une ligne de vue directe.</p>
<p class="resume-text">La communication chimique (sémiochimie) est la plus ancienne et la plus répandue dans le règne animal, y compris chez les organismes unicellulaires. Les phéromones, composés chimiques émis par un individu et détectés par un congénère, modulent les comportements sexuels (phéromones sexuelles des papillons, détectables en nanogrammes à plusieurs kilomètres), d'alarme (les fourmis libèrent des phéromones d'alarme qui mobilisent les congénères), de piste (formic acid trails des fourmis), et de cohésion sociale. Les marquages territoriaux (urines des carnivores, sécrétions des glandes anales des rongeurs) transmettent des informations sur l'identité, le statut social et le cycle reproducteur de leur auteur.</p>
<div class="highlight-box"><p>Les éléphants d'Afrique communiquent par infrasons (sons inférieurs à 20 Hz, inaudibles pour l'homme) qui peuvent voyager à travers le sol sur plusieurs dizaines de kilomètres. Ces vibrations sismiques sont détectées par les pieds et la trompe, permettant aux éléphants de coordonner leurs déplacements sur de vastes distances. Des chercheurs ont montré que les éléphants ressentent ces vibrations et les distinguent selon leur source.</p></div>

<h3>Le langage des primates : entre communication et proto-langage</h3>
<p class="resume-text">Les recherches sur les capacités linguistiques des grands singes ont suscité des débats passionnés depuis les années 1960. Washoe, une chimpanzée élevée par les époux Gardner dès 1966, a appris à communiquer en langue des signes américaine (ASL) et a enseigné spontanément certains signes à son fils adoptif. Kanzi, un bonobo élevé dans le laboratoire de Sue Savage-Rumbaugh, comprend l'anglais parlé et communique via un clavier de lexigrammes avec des compétences syntaxiques élémentaires. Ces expériences suggèrent que les grands singes ont une capacité proto-linguistique (utilisation de symboles arbitraires, compréhension de règles syntaxiques simples) que la sélection naturelle n'a pas développée en plein langage faute de structures vocales adaptées.</p>
<p class="resume-text">Les oiseaux chanteurs fournissent un modèle d'apprentissage vocal fascinant : leurs chants sont partiellement innés (gabarit génétique) et partiellement appris (sensibles aux modèles acoustiques entendus pendant une période critique). La plasticité du chant des oscines (passereaux chanteurs) a été utilisée pour modéliser l'apprentissage du langage humain. Le perroquet Alex, étudié pendant 30 ans par Irene Pepperberg, a démontré une compréhension conceptuelle (couleurs, matériaux, nombres jusqu'à 6, absence/présence d'objets) qui dépasse de loin la simple imitation.</p>
<div class="highlight-box"><p>Les cétacés (dauphins et baleines) ont des systèmes de communication parmi les plus complexes du règne animal. Les baleines à bosse chantent des "chansons" qui peuvent durer jusqu'à 20 heures, évoluer au fil de la saison, et se diffuser à travers les océans comme des "modes culturelles" — les mâles d'une région adoptant les variations introduites par les voisins. Ces chansons, transmises culturellement et non génétiquement, sont considérées comme l'analogue animal le plus proche de l'art musical humain.</p></div>
""",

"ethologie/migration-animale": """
<h3>Les mécanismes de navigation : boussoles et cartes internes</h3>
<p class="resume-text">La navigation des animaux migrateurs est l'un des phénomènes biologiques les plus fascinants. Les oiseaux migrateurs utilisent plusieurs systèmes de navigation complémentaires : une "boussole magnétique" détectant le champ magnétique terrestre (via des cristaux de magnétite dans les becs ou des radicaux libres dans la rétine — la cryptochrome-4 détecte les photons liés au champ magnétique), une "boussole stellaire" calibrée sur les étoiles circumpolaires pendant la période critique de développement, une "boussole solaire" qui requiert une horloge circadienne interne pour compenser le déplacement apparent du soleil, et des repères géographiques visuels.</p>
<p class="resume-text">Les saumons (Salmo salar, Oncorhynchus spp.) réalisent une navigation encore plus spectaculaire : après 2 à 7 ans en mer, ils retrouvent exactement la rivière et même l'affluent où ils sont nés, guidés par la signature chimique unique de leur cours d'eau natal qu'ils ont mémorisée pendant leur période d'empreinte larvaire. Cette "mémoire olfactive" du milieu natal est tellement précise que les saumons détectent leur rivière d'origine à des concentrations de molécules de l'ordre du nanogramme par litre d'eau de mer. Les lamproies marines utilisent une navigation similaire basée sur des phéromones.</p>
<div class="highlight-box"><p>La sterne arctique (Sterna paradisaea) détient le record de migration : elle parcourt chaque année environ 70 000 km entre ses aires de nidification arctiques et ses quartiers d'hivernage antarctiques, profitant de l'été dans les deux hémisphères. Sur une vie de 30 ans, une sterne arctique parcourt l'équivalent de 3 voyages vers la Lune et retour — le plus long voyage de toute la biosphère.</p></div>

<h3>Migrations altitudinales et mouvements de dispersion</h3>
<p class="resume-text">Toutes les migrations ne sont pas des voyages intercontinentaux. Les migrations altitudinales — descente des montagnes en hiver, remontée au printemps — sont pratiquées par de nombreuses espèces. Le bouquetin des Alpes descend des sommets pour trouver des zones de nourriture dégagées de neige ; la mésange noire (Parus ater) des Alpes descend en vallée lors des hivers rigoureux. Ces migrations altitudinales sont sensibles au changement climatique : des espèces comme la perdrix des neiges remontent à des altitudes de plus en plus élevées à mesure que la ligne des neiges s'élève.</p>
<p class="resume-text">La dispersion (mouvement des juvéniles quittant leur lieu de naissance) diffère conceptuellement de la migration (mouvement saisonnier régulier) mais joue un rôle crucial dans la génétique des populations. La dispersion évite la consanguinité et permet la colonisation de nouveaux habitats. Chez les lions, ce sont les mâles juvéniles qui dispersent loin du groupe natal ; chez les hyènes, ce sont les femelles. Le loup gris peut se disperser sur 1 000 km pour trouver un territoire non occupé — un exploit récent documenté en France avec le loup "M49" qui traversait les Alpes en zigzag.</p>
<div class="highlight-box"><p>Les migrations de papillons monarques (Danaus plexippus) sont parmi les plus remarquables du règne animal : des millions de papillons voyagent chaque automne depuis les Grands Lacs du Canada jusqu'aux forêts de sapins oyamels du Michoacán mexicain, sur plus de 4 000 km. Chaque individu n'effectue ce trajet qu'une fois — aucun n'a vu la destination. La migration est guidée par une combinaison de boussole solaire et de magnétisme, et le site d'hivernage est trouvé sans expérience préalable.</p></div>

<h3>Impact du changement climatique sur les migrations</h3>
<p class="resume-text">Les migrations animales sont parmi les phénomènes biologiques les plus sensibles au changement climatique. Les oiseaux migrateurs arrivent de plus en plus tôt en Europe au printemps (en avance de 2 à 3 semaines comparé aux années 1970), mais cette avance ne correspond pas toujours à celle du pic d'abondance des insectes dont ils se nourrissent pour l'élevage des poussins — un décalage phénologique (mismatch) qui réduit le succès reproducteur. La mésange charbonnière aux Pays-Bas, étudiée pendant 30 ans par Piet Visser, présente ce décalage : les oiseaux arrivent plus tôt, mais les chenilles de chêne (leur nourriture principale pour les poussins) ont elles aussi avancé leur pic, et la mésange ne s'adapte pas assez vite.</p>
<p class="resume-text">La distribution géographique des espèces migratoires se déplace vers les pôles et en altitude. Des espèces méditerranéennes comme le héron pourpré ou l'aigrette garzette colonisent des régions de plus en plus septentrionales. La grande aigrette, rarissime en France dans les années 1970, niche désormais régulièrement au-delà de la Loire. Ces changements de répartition modifient les écosystèmes de destinations (nouvelles espèces prédatrices ou compétitrices) et perturbent les chaînes alimentaires dans les sites d'hivernage traditionnels devenus plus chauds et donc moins attractifs.</p>
<div class="highlight-box"><p>Le gypaète barbu, vautour des hautes montagnes alpines et pyrénéennes, illustre comment les migrations courtes peuvent être perturbées par l'activité humaine : son déclin au XIXe-XXe siècle (chasse, empoisonnement) a été suivi d'une réintroduction réussie à partir de 1986 dans les Alpes (programme Life Gypaète), avec aujourd'hui plus de 60 couples nicheurs en France. Sa réintroduction a nécessité une gestion coordonnée à l'échelle des Alpes et des Pyrénées.</p></div>
""",

"ethologie/vie-sociale": """
<h3>Les théories évolutives de la sociabilité animale</h3>
<p class="resume-text">Pourquoi vivre en groupe plutôt que solitairement ? La théorie évolutive propose plusieurs réponses non exclusives. La "détection de prédateurs" est améliorée en groupe : plus d'yeux et d'oreilles réduisent le risque d'être surpris ; l'effet de "dilution du risque" signifie que chaque individu a une probabilité moindre d'être la victime choisie. La "chasse coopérative" permet de capturer des proies plus grandes ou plus rapides que ce qu'un individu pourrait obtenir seul : les lions en groupe chassent le buffle, inaccessible à un seul prédateur. La "défense collective" contre les prédateurs est spectaculaire dans les bancs de poissons ou les troupeaux de bœufs musqués qui forment un cercle protecteur.</p>
<p class="resume-text">Cependant, la vie en groupe engendre aussi des coûts : compétition accrue pour les ressources, risques accrus de transmission de maladies et de parasites, visibilité augmentée pour les prédateurs (un troupeau se détecte de plus loin qu'un individu isolé). L'optimum social résulte d'un équilibre entre ces bénéfices et coûts, qui varie selon les conditions écologiques. L'"hypothèse du cerveau social" (Robin Dunbar) propose que la complexité des interactions sociales dans les grands groupes de primates est le principal moteur de l'augmentation du néocortex — la pression sélective sur l'intelligence serait avant tout sociale.</p>
<div class="highlight-box"><p>Le nombre de Dunbar (environ 150) désigne la taille maximale du groupe social que le cerveau humain peut maintenir avec des liens sociaux réels. Cette limite, dérivée de l'étude des primates, semble s'appliquer aux sociétés humaines préindustrielles (villages, compagnies militaires, réseaux de contacts actifs). L'omniprésence des réseaux sociaux numériques n'a pas augmenté ce plafond cognitif : les utilisateurs de Facebook ont en moyenne 338 "amis" mais des relations profondes avec seulement 4 à 5 d'entre eux.</p></div>

<h3>Les systèmes de reproduction et les structures sociales associées</h3>
<p class="resume-text">Les systèmes de reproduction (monogamie, polygynie, polyandrie, promiscuité) sont liés aux structures sociales et aux stratégies parentales. La monogamie (un mâle, une femelle) est la forme dominante chez les oiseaux (environ 90 % des espèces), associée aux soins biparentaux indispensables à l'élevage des poussins altriciaux. Mais les analyses génétiques (ADN des poussins) ont révélé que même chez des espèces "socialement monogames", les infidélités sont fréquentes : chez les rouges-gorges, 15 à 30 % des poussins ont un père différent du mâle dominant du nid.</p>
<p class="resume-text">La polygynie (un mâle, plusieurs femelles) est fréquente chez les mammifères où les mâles investissent peu dans les soins parentaux. Le dimorphisme sexuel (différences de taille et d'ornements entre mâles et femelles) est un marqueur de l'intensité de la sélection sexuelle : les gorilles mâles dos argenté pèsent deux fois plus que les femelles (haute polygynie), tandis que les gibbons sont monomorphes (monogamie stricte). La polyandrie (une femelle, plusieurs mâles) est rare mais documentée chez les jacanas, les phalaropes et les lions de mer femelles de certaines populations.</p>
<div class="highlight-box"><p>Les méerkats (Suricata suricatta) illustrent l'altruisme apparent en structure de groupe : les individus sentinelles se perchent en hauteur et émettent des cris d'alarme spécifiques (différents selon le type de prédateur — aérien ou terrestre) qui avertissent le groupe, au prix d'une exposition accrue au danger. Ce comportement s'explique par la sélection de parentèle (les individus qui se sacrifient protègent leurs proches parents) et la réciprocité (les sentinelles se relaient).</p></div>
""",

"ethologie/cognition-animale": """
<h3>Les tests de cognition : méthodologies et biais</h3>
<p class="resume-text">L'étude de la cognition animale est méthodologiquement complexe : comment séparer la véritable compréhension conceptuelle des simples associations stimulus-réponse apprises par renforcement ? Le test du miroir (mark test), où un animal découvre s'il reconnaît le reflet de son propre corps en réagissant à une marque colorée placée sur lui et visible uniquement dans le miroir, est utilisé comme indicateur de conscience de soi. Il est réussi par les grands singes, les dauphins, les éléphants, les pies et les pieuvres, mais pas par les chiens malgré leur haute sociabilité — ce qui illustre que le test mesure un type spécifique de conscience et non l'intelligence globale.</p>
<p class="resume-text">Le biais anthropomorphique (attribuer des états mentaux humains aux animaux) et le biais anthropocentrique (nier toute vie mentale aux animaux) sont tous deux des obstacles à l'étude rigoureuse de la cognition animale. La "règle de Morgan" (C. Lloyd Morgan, 1894) recommande de ne pas invoquer une faculté mentale supérieure pour expliquer un comportement si une explication plus simple suffit. Cependant, cette règle peut conduire à sous-estimer les capacités cognitives réelles si elle est appliquée trop rigidement : il ne faut pas plus supposer la plus grande simplicité que la plus grande complexité.</p>
<div class="highlight-box"><p>La chèvre Ben, étudiée par Christian Nawroth, a montré qu'elle pouvait comprendre le pointage humain (regarder dans la direction pointée du doigt) pour trouver de la nourriture cachée — une compétence longtemps considérée comme spécifique aux humains et aux chiens. Cette découverte suggère que cette compétence de "cognition sociale" peut évoluer chez toute espèce ayant une histoire de cohabitation avec des humains, pas seulement les espèces "cognitives" en général.</p></div>

<h3>La fabrication et l'utilisation d'outils chez les animaux</h3>
<p class="resume-text">L'utilisation d'outils, longtemps considérée comme un privilège humain, est maintenant documentée chez des dizaines d'espèces. Jane Goodall a révélé en 1960 que les chimpanzés fabriquent des "pêches à termites" (baguettes façonnées pour extraire les termites des termitières) — forçant la redéfinition de "l'Homme" par son mentor Louis Leakey ("Il nous faut maintenant redéfinir l'outil, redéfinir l'homme, ou accepter les chimpanzés comme humains"). Les corbeaux calédoniens (Corvus moneduloides) sont des fabricants d'outils particulièrement sophistiqués : ils façonnent des crochets à partir de brindilles d'Araucaria pour extraire des larves, améliorent leurs outils au fil de l'expérience et transmettent culturellement ces techniques.</p>
<p class="resume-text">Des espèces inattendues ont rejoint le club des utilisateurs d'outils. Des dauphins de Shark Bay (Australie) portent des éponges marines sur leur rostre pour fouiller les fonds sableux sans se blesser — une technique transmise culturellement de mère en fille dans certaines lignées. Le poulpe ramasse des coques de noix de coco abandonnées, les transporte sous son corps et les assemble en abri — une utilisation proactuelle (ramasser un outil en prévision d'un usage futur), comportement considéré comme une marque de planification. Des ours brun utilisent des pierres pour ouvrir des coquillages. Le verdict : l'utilisation d'outils a évolué indépendamment de nombreuses fois dans des lignées phylogénétiques très différentes.</p>
<div class="highlight-box"><p>Le rat "Rattus norvegicus" excelle dans les tâches cognitives en laboratoire, mais ses capacités sont depuis peu étudiées sous un angle nouveau : des recherches publiées en 2007 ont montré que des rats expriment quelque chose d'analogue à l'empathie — ils libèrent un congénère piégé, même si cela ne leur apporte aucune récompense directe, et partagent spontanément de la nourriture avec lui après sa libération.</p></div>

<h3>La conscience animale : un débat philosophique et scientifique</h3>
<p class="resume-text">La question de la conscience animale — l'expérience subjective, le "quelque chose que c'est d'être une chauve-souris" (Thomas Nagel, 1974) — est à la frontière de la philosophie et des neurosciences. La Cambridge Declaration on Consciousness (2012) affirme que les mammifères, les oiseaux et de nombreux autres animaux possèdent les substrats neurologiques nécessaires à la conscience. Mais la "conscience" est-elle un phénomène à seuil (présent ou absent) ou un continuum (plus ou moins développé) ? Et comment distinguer scientifiquement un être conscient d'un "zombie philosophique" — un être qui se comporte comme s'il était conscient sans avoir d'expérience subjective ?</p>
<p class="resume-text">Les études de neuroimagerie (IRMf, EEG) chez des animaux éveillés révèlent des patterns d'activité cérébrale similaires à ceux observés chez les humains pendant des états émotionnels, des rêves (phases REM enregistrées chez les chiens, les rats et les pieuvres) et des expériences de plaisir ou de douleur. Les corvides (corbeaux, geais) montrent des comportements suggérant des pensées sur le futur (planification, économie de nourriture selon les besoins anticipés) et le passé (mémoire épisodique — "quoi, où, quand"). Ces données ne prouvent pas la conscience mais indiquent des processus cognitifs proches de ceux que nous associons à la conscience chez les humains.</p>
<div class="highlight-box"><p>Le géai buissonnier (Aphelocoma californica) peut rappeler ce qu'il a caché, où et quand (mémoire épisodique ou "voyages mentaux dans le temps"). Plus remarquable encore, si un géai est observé en train de cacher de la nourriture par un congénère, il reviendra secrètement déplacer ses réserves — ce qui implique qu'il sait que l'observateur sait, et qu'il peut anticiper le vol potentiel : une "théorie de l'esprit" élémentaire.</p></div>
""",

"entomologie/monde-des-insectes": """
<h3>La morphologie des insectes : une architecture d'une efficacité remarquable</h3>
<p class="resume-text">Les insectes partagent un plan corporel commun : trois tagmes (têtes, thorax, abdomen), trois paires de pattes locomotrices attachées au thorax, et le plus souvent deux paires d'ailes également fixées au thorax. La tête porte les pièces buccales, diversifiées selon le régime alimentaire : broyeuses (criquets, coléoptères), suceuses (papillons), piqueuses-suceuses (moustiques, punaises), léchantes-suceuses (abeilles). Les antennes sont des organes sensoriels polyvalents, captant les odeurs, les vibrations mécaniques et parfois la chaleur et l'humidité. Les yeux composés, constitués de centaines à milliers d'ommatidies, offrent un large champ visuel et une excellente détection du mouvement, mais une résolution inférieure à l'œil des vertébrés.</p>
<p class="resume-text">L'exosquelette de chitine est à la fois la force et la limite des insectes : il protège contre les prédateurs et la dessiccation, mais nécessite des mues (ecdysis) pour que l'animal puisse grandir. La cuticule des insectes présente une imperméabilité remarquable grâce à une couche de cire lipidique : des coléoptères désertiques collectent l'eau de brouillard sur leur dos rugueux, des scarabées polaires survivent à des températures de -40 °C grâce à des protéines antigivrantes incorporées dans leur cuticule. La respiration se fait par un système de trachées (tubes ramifiés) qui amènent directement l'oxygène aux cellules — efficace à petite taille mais facteur limitant de la taille maximale des insectes.</p>
<div class="highlight-box"><p>À l'ère carbonifère, l'oxygène atmosphérique atteignait environ 35 % (contre 21 % aujourd'hui), permettant à des libellules géantes (Meganeura, avec une envergure de 70 cm) de voler. La taille maximale des insectes est en effet limitée par l'efficacité de diffusion de l'oxygène dans les trachées — à haute teneur atmosphérique en O₂, des tailles géantes deviennent possibles.</p></div>

<h3>La diversité des régimes alimentaires et des niches écologiques</h3>
<p class="resume-text">Les insectes ont colonisé pratiquement toutes les niches alimentaires disponibles dans les écosystèmes terrestres. Les phytophages (herbivores) sont les plus nombreux : chenilles de lépidoptères, pucerons, cochenilles, criquets, charançons dévorent feuilles, racines, tiges et graines. Les prédateurs (coccinelles, carabes, libellules, mantidés) régulent les populations d'autres insectes. Les détritivores (bousiers, vers de la farine, dermestes) recyclent les matières organiques mortes. Les nécrophages (mouches à chair) participent à la décomposition des cadavres — des enquêteurs en médecine légale utilisent la succession des espèces de mouches sur un cadavre (entomologie légale) pour déterminer la date de décès.</p>
<p class="resume-text">Les symbioses entre insectes et micro-organismes sont omniprésentes et souvent indispensables. Les termites digèrent le bois grâce à des communautés de protistes, bactéries et champignons dans leur intestin. Les pucerons hébergent Buchnera aphidicola, une bactérie endosymbiote transmise verticalement depuis 80 millions d'années qui synthétise les acides aminés essentiels absents de la sève dont se nourrissent les pucerons. Les bourdons hébergent des microbiomes intestinaux spécifiques qui influencent leur comportement de forage des fleurs et leur résistance aux parasites.</p>
<div class="highlight-box"><p>La mante religieuse (Mantis religiosa) est fameuse pour sa "copulation cannibale" : la femelle dévore parfois le mâle pendant ou après l'accouplement. Bien que spectaculaire, ce comportement n'est pas systématique (il survient dans 25 % des accouplements en conditions naturelles) et représente un cas fascinant de conflit sexuel évolutif — le mâle "sacrifié" augmente la fécondité de la femelle et donc le nombre de ses descendants.</p></div>
""",

"entomologie/coleopteres": """
<h3>L'extraordinaire diversité des coléoptères</h3>
<p class="resume-text">Les coléoptères (Coleoptera) constituent l'ordre d'insectes le plus diversifié avec environ 400 000 espèces décrites — soit environ 25 % de toutes les espèces animales connues. Cette extraordinaire diversité a inspiré la boutade attribuée au biologiste J.B.S. Haldane : à qui lui demandait ce que l'étude de la nature lui avait appris sur Dieu, il aurait répondu que Dieu avait "une affection particulière pour les coléoptères". Leur succès évolutif repose sur leur adaptabilité remarquable et sur les élytres (ailes antérieures durcies en étuis) qui protègent les ailes membraneuses postérieures, permettant de vivre dans des environnements abrasifs (bois, sol).</p>
<p class="resume-text">La famille des Curculionidae (charançons et scolytes) est à elle seule l'une des plus grandes familles du règne animal avec plus de 60 000 espèces. Les Staphylinidae (staphylins) en comptent plus de 63 000. À l'opposé, certaines espèces sont rarissimes : le coléoptère du genre Nannophya de moins de 1 mm dans les mousses tropicales, ou le titan cerambyx (Titanus giganteus), le plus grand coléoptère du monde avec ses 16 cm de long, qui n'a jamais été observé vivant à l'état adulte par les scientifiques et reste une énigme biologique.</p>
<div class="highlight-box"><p>Le scarabée bousier (Scarabaeus satyrus) utilise la Voie lactée pour s'orienter la nuit — le seul animal non humain connu qui navigue grâce à notre galaxie. Des expériences en planétarium ont montré que les scarabées roulant leurs boules de fumier sous un ciel étoilé artificiel se désorienter quand on masque la Voie lactée, même si des étoiles individuelles restent visibles.</p></div>

<h3>Les coléoptères saproxyliques : gardiens du bois mort</h3>
<p class="resume-text">Les coléoptères saproxyliques (qui dépendent du bois mort à différents stades de leur cycle) sont parmi les insectes les plus menacés d'Europe. Le grand capricorne des chênes (Cerambyx cerdo) est protégé en France et dans toute l'UE : ses larves creusent des galeries dans les vieux chênes pendant 3 à 5 ans avant la nymphose. Le lucane cerf-volant (Lucanus cervus), le plus grand coléoptère d'Europe, passe 3 à 7 ans en larve dans les vieilles souches de chênes avant d'émerger pour 2 à 8 semaines de vie adulte. Ces espèces emblématiques dépendent de vieilles forêts avec de nombreux arbres sénescents et du bois mort debout — des habitats devenus rares dans les forêts gérées intensivement.</p>
<p class="resume-text">Le processus de décomposition du bois est un des cycles biogéochimiques les plus importants des forêts. Les coléoptères saproxyliques y jouent un rôle central : ils inoculent des champignons dans le bois lors de la ponte, créent des galeries qui aèrent le bois et permettent la pénétration des spores fongiques, et leurs fèces enrichissent les cavités arboricoles. Une forêt naturelle contient jusqu'à 30 % de son volume ligneux sous forme de bois mort (debout ou à terre), habitat pour des centaines d'espèces saproxyliques, contre moins de 5 % dans les forêts exploitées conventionnellement.</p>
<div class="highlight-box"><p>Le programme européen de conservation des vieux arbres "Ancient Tree Hunt" a recensé plus de 130 000 vieux arbres remarquables au Royaume-Uni. Ces arbres vénérables (chênes centenaires, ifs millénaires, hêtres séculaires) abritent des communautés saproxyliques uniques et irremplaçables — certaines espèces ne colonisent un nouvel arbre qu'après des siècles de maturation. Leur conservation est incompatible avec une sylviculture à courte rotation.</p></div>

<h3>Coléoptères utiles et coléoptères ravageurs</h3>
<p class="resume-text">Les coléoptères entretiennent des relations très diverses avec l'agriculture et les forêts. Les coccinelles (Coccinellidae) sont parmi les auxiliaires les plus utiles : une coccinelle à 7 points (Coccinella septempunctata) consomme jusqu'à 5 000 pucerons en une vie. Les carabes (Carabidae) sont des prédateurs nocturnes généralistes qui régulent les populations de larves phytophages dans le sol. Les staphylins participent activement à la décomposition de la matière organique et à la régulation des nématodes. Ces espèces sont sensibles aux pesticides et au travail du sol — leur abondance est un indicateur de la santé biologique des agrosystèmes.</p>
<p class="resume-text">À l'inverse, plusieurs coléoptères sont des ravageurs majeurs. Le scolyte de l'écorce de l'épicéa (Ips typographus) est le "terroriste des forêts" : ses populations explosent lors des sécheresses et des tempêtes (bois stressé ou tombé), créant des foyers qui peuvent tuer des milliers d'hectares de forêt. En Europe centrale (Bavière, République tchèque, Pologne), des millions d'hectares ont été détruits lors des épidémies de 2018-2022, favorisées par la sécheresse. La question de l'intervention (coupes sanitaires) ou de la non-intervention (laisser les forêts traverser la crise naturellement) divise les gestionnaires forestiers et les écologues.</p>
<div class="highlight-box"><p>Le scarabée rhinocéros du Japon (Trypoxylus dichotomus) est l'un des insectes les plus forts du monde toutes proportions gardées : il peut soulever 850 fois son propre poids. Utilisé dans des combats traditionnels au Japon (où il est élevé comme animal de compagnie), il illustre comment des caractères qui semblent extrêmes ont souvent une explication adaptative : sa force est utilisée pour combattre les mâles concurrents pour l'accès aux femelles.</p></div>
""",

"entomologie/pollinisation-insectes": """
<h3>La biologie de la pollinisation : fleurs, pollinisateurs et co-évolution</h3>
<p class="resume-text">La pollinisation par les insectes est l'une des interactions biologiques les plus importantes de la biosphère terrestre, impliquant environ 80 % des plantes à fleurs. La co-évolution entre plantes et pollinisateurs a produit des adaptations spectaculaires de part et d'autre. Les orchidées du genre Ophrys imitent si précisément les femelles de certaines espèces d'abeilles sauvages (forme, couleur, texture veloutée, et même phéromones sexuelles mimétiques) que les mâles tentent de s'accoupler avec la fleur (pseudocopulation), ramassant ainsi le pollen avant de recommencer avec une autre fleur. Cette spécialisation extrême fait de chaque espèce d'Ophrys la dépendante d'un seul pollinisateur.</p>
<p class="resume-text">Les syndromes de pollinisation décrivent les ensembles de caractères floraux associés à différents types de pollinisateurs. Les fleurs entomophiles (pollinisées par les insectes) offrent du nectar et/ou du pollen comme récompenses, et présentent des formes et couleurs adaptées : bleues/mauves pour les abeilles qui voient dans l'UV, rouges pour les papillons diurnes, blanches et odorantes la nuit pour les sphinx et les papillons nocturnes. Les fleurs cantharophiles (pollinisées par les coléoptères) sont souvent blanches, à fleurs ouvertes, riches en pollen. Les fleurs de Magnolia, l'une des familles les plus anciennes, sont typiquement cantharophiles — un vestige de l'ère où les abeilles n'existaient pas encore.</p>
<div class="highlight-box"><p>Le figuier et le figuier de Barbarie (Ficus et Blastophaga) illustrent la spécialisation extrême de la pollinisation mutualiste : un minuscule parasitoïde femelle (guêpe Blastophaga psenes, 1,5 mm) entre dans le figuier par un ostiole (petit orifice), pollinise les fleurs femelles en déposant le pollen récolté dans un autre figuier, pond ses œufs dans les fleurs à galles, et meurt à l'intérieur. Les mâles aptères s'accouplent avec les femelles avant qu'elles émergent, et les femelles sortent chargées de pollen pour un nouveau figuier. Plus de 800 espèces de Ficus ont chacune leur guêpe Blastophaga spécifique — un exemple de coévolution à l'état pur.</p></div>

<h3>Le déclin des pollinisateurs : causes et conséquences</h3>
<p class="resume-text">Le déclin des pollinisateurs est l'une des crises écologiques les plus documentées du XXIe siècle. En Europe, les populations d'abeilles sauvages ont décliné de 17 % entre 2006 et 2016 selon le réseau ALARM, et plusieurs études régionales font état de baisses de 70 à 80 % sur 30 ans. Les papillons des prairies européens ont perdu 39 % de leurs effectifs entre 1990 et 2011. Ce déclin est multifactoriel : perte d'habitat (disparition des prairies fleuries, des haies, des jachères), pesticides (néonicotinoïdes systémiques, fongicides qui réduisent l'efficacité des traitements contre Varroa chez les abeilles domestiques), maladies (Varroa, Nosema), changement climatique (désynchronisation floraison-émergence).</p>
<p class="resume-text">Les conséquences économiques sont considérables : la FAO estime que les pollinisateurs contribuent à la production de 75 % des cultures alimentaires mondiales pour une valeur de 235 à 577 milliards de dollars par an. Le service de pollinisation fourni par les abeilles sauvages seule est évalué à plusieurs dizaines de milliards d'euros en Europe. La disparition des pollinisateurs menacerait directement la production de nombreux fruits (pommes, cerises, fraises, amandes, kiwis), légumes (tomates, courgettes, concombres) et cultures oléagineuses (colza, tournesol).</p>
<div class="highlight-box"><p>Des agriculteurs de la région de Maoxian (Chine) pollinisent leurs pommiers et poiriers manuellement depuis les années 1990 : équipés de bâtonnets poudrés de pollen récolté et séché, des travailleurs pollinisent fleur par fleur les vergers, car les abeilles ont disparu suite à l'usage intensif de pesticides. Un seul arbre fruitier nécessite plusieurs heures de pollinisation manuelle — une illustration dramatique du coût économique de la perte de services écosystémiques.</p></div>
""",

"entomologie/societes-insectes": """
<h3>L'eusocialité : définition et gradients</h3>
<p class="resume-text">L'eusocialité est la forme la plus développée d'organisation sociale dans le règne animal. Elle est définie par trois critères : coopération dans les soins aux jeunes, présence de castes reproductives et non-reproductives, et chevauchement de générations au sein du groupe. Les fourmis, les abeilles mellifères, les guêpes sociales, les bourdons et les termites sont les exemples les plus connus. Mais l'eusocialité a évolué indépendamment au moins 12 fois dans le règne animal — chez les crustacés (crevettes Synalpheus), les hyménoptères (fourmis, abeilles, guêpes), les isoptères (termites) et les mammifères (rats-taupes dorés, Heterocephalus glaber).</p>
<p class="resume-text">Le rat-taupe doré (Heterocephalus glaber), découvert en 1842 mais étudié en détail depuis les années 1970, est le seul mammifère pleinement eusocial connu : une colonie de 70 à 300 individus est dominée par une unique femelle reproductrice (la reine) qui s'accouple avec 1 à 3 mâles. Tous les autres individus sont des ouvriers non reproducteurs qui creusent les tunnels, défendent la colonie et nourrissent les jeunes. Les recherches ont montré que les rats-taupes dorés sont quasi insensibles à la douleur, n'ont pas de thermorégulation, et semblent être résistants au cancer — des adaptations liées à leur vie en milieu souterrain hypoxique.</p>
<div class="highlight-box"><p>Une colonie de fourmis leafcutter (Atta cephalotes) peut comprendre 8 millions d'individus et 4 castes morphologiquement distinctes : les minimes (0,7 mm, jardinent le champignon), les médias (2-6 mm, coupent les feuilles), les soldats (12-14 mm, défendent la colonie), et les reproducteurs ailés. Ces fourmis cultivent des champignons (Leucoagaricus gongylophorus) depuis 50 millions d'années — plus ancienne agriculture connue. Le champignon reçoit du substrat végétal et produit des gongylidies, structures nutritives consommées par les fourmis.</p></div>

<h3>Organisation et communication dans les colonies d'insectes sociaux</h3>
<p class="resume-text">Les colonies d'insectes sociaux sont des systèmes autoorganisés : des règles simples suivies individuellement produisent des comportements collectifs complexes sans chef ni contrôle centralisé. Les fourmis de genre Lasius (fourmis jaunes des prairies) construisent des nids thermorégulés en se basant sur des règles simples de dépôt de terre : déposer de la terre là où il y a déjà de la terre, s'arrêter si la concentration devient trop élevée. Ces règles locales produisent des nids complexes avec des chambres, des galeries et des zones à températures différentes. Ce phénomène d'"intelligence collective émergente" inspire les algorithmes de fourmis utilisés en informatique pour résoudre des problèmes d'optimisation (Ant Colony Optimization).</p>
<p class="resume-text">Les phéromones sont le principal medium de communication dans les sociétés d'insectes. Les fourmis utilisent des dizaines de phéromones différentes pour signaler des pistes alimentaires (acide formique, hydrocarbures), des alarmes (composés volatils émis par les soldats), la reconnaissance de colonie (hydrocarbures cuticulaires spécifiques à chaque colonie), et le statut reproducteur de la reine (phéromone "royale" qui inhibe le développement ovarien des ouvrières). Chez les abeilles, la phéromone royale 9-ODA (acide 9-oxo-décénoïque) produite par la reine inhibe la construction de cellules royales et maintient la cohésion de la colonie.</p>
<div class="highlight-box"><p>Lors d'un essaimage (division de la colonie), les abeilles en grappe sur une branche délibèrent collectivement sur le choix du nouveau site de nidification. Des éclaireuses dansent pour promouvoir leur site découvert ; d'autres éclaireuses visitent les sites proposés et dansent à leur tour si elles approuvent. Le site gagnant est celui qui atteint un quorum d'environ 15 exploratrices simultanées — un processus démocratique décrit par le biologiste Thomas Seeley comme une "démocratie des abeilles" dont certains aspects pourraient inspirer la prise de décision humaine.</p></div>
""",

"entomologie/metamorphose": """
<h3>Métamorphose complète versus incomplète : deux stratégies évolutives</h3>
<p class="resume-text">Les insectes se divisent en holométaboles (métamorphose complète : œuf-larve-nymphe-adulte) et hémimétaboles (métamorphose incomplète : œuf-nymphe-adulte). La métamorphose complète, apparue il y a environ 300 millions d'années, est une innovation évolutive majeure : en séparant radicalement les stades larvaire et adulte dans leur morphologie, leur régime alimentaire et leur niche écologique, elle réduit la compétition interspécifique au sein d'une même espèce. La chenille et le papillon adulte exploitent des ressources totalement différentes, ne se font pas concurrence.</p>
<p class="resume-text">Au stade nymphal (chrysalide chez les lépidoptères, pupe chez les mouches), l'insecte semble en apparence inerte mais vit une transformation radicale : la majorité des tissus larvaires sont histolysés (dissous) par les enzymes, libérant une masse de cellules souches (histoblastes) qui reconstruisent entièrement l'organisme adulte. Des expériences remarquables ont montré que des papillons adultes "se souviennent" de conditionnements opérés au stade larvaire (ex : aversion à une odeur apprise par la chenille) — prouvant que certaines connexions neuronales survivent à la métamorphose malgré la réorganisation radicale du système nerveux.</p>
<div class="highlight-box"><p>La chrysalide dorée de certaines espèces de papillons (comme Heliconius charithonia) est l'une des curiosités les plus remarquables de l'entomologie : réellement métallisée, la nymphe réfléchit la lumière comme de l'or. Cette dorure, produite par des cristaux de guanine dans les téguments, pourrait mimer des gouttelettes d'eau ou brouiller les signaux visuels des prédateurs — mais son rôle précis reste débattu.</p></div>

<h3>Les stades larvaires et leur diversité</h3>
<p class="resume-text">Les larves d'insectes holométaboles présentent une diversité morphologique extraordinaire, reflet de leur adaptation à des niches spécifiques. Les larves de lépidoptères (chenilles) ont des fausses-pattes abdominales (propodes) couvertes de crochets pour se maintenir sur les feuilles, des mandibules broyeuses puissantes pour consommer les végétaux, et sont souvent protégées par des poils urticants (processionnaire du pin) ou par des couleurs aposématiques (la chenille de l'écaille du séneçon, jaune et noire, avertit qu'elle est toxique). Les larves de mouches (asticots) sont apodes et vermiformes, adaptées à la vie dans des substrats liquides ou semi-liquides (cadavres, fruits, fèces).</p>
<p class="resume-text">Les larves aquatiques constituent un monde à part entière : les larves de libellules (nymphes) sont des prédateurs féroces des étangs, capables de projeter leur lèvre (labium extensible) à grande vitesse pour capturer des têtards et même de petits poissons. Les larves de phryganes (Trichoptera) construisent des fourreaux protecteurs avec des éléments du milieu (grains de sable, débris végétaux, coquilles), adaptés à la vitesse du courant — une "architecture" entomologique qui fascine les artistes (certains artistes font construire leurs fourreaux avec des pépites d'or ou de pierres précieuses pour en faire des bijoux). Les larves de moustiques (vermicelles) filtrent les micro-organismes à la surface de l'eau.</p>
<div class="highlight-box"><p>La vermiculture (élevage de larves de mouche soldat noire, Hermetia illucens) représente une filière émergente de l'économie circulaire : les larves transforment des déchets organiques (restes alimentaires, fumier, biodéchets) en protéines et lipides de haute valeur pour l'alimentation animale. Une tonne de déchets produit environ 100 kg de larves fraîches (100 kg de protéines sèches équivalentes). L'Union européenne a autorisé en 2017 l'utilisation des larves d'insectes comme alimentation pour les poissons, puis les volailles et les porcins.</p></div>

<h3>Les phénomènes de diapause et de dormance</h3>
<p class="resume-text">La diapause est un état de dormance programmée génétiquement qui permet aux insectes de traverser des périodes défavorables (hiver, saison sèche). Déclenchée par des signaux environnementaux (photopériode, température), elle peut survenir à n'importe quel stade : œuf (sauterelle Locusta migratoria), larve (processionnaire du pin), nymphe (certains coléoptères), adulte (coccinelle, reine de bourdon qui hiberne). La physiologie de la diapause implique une accumulation de réserves lipidiques, une réduction du métabolisme, la synthèse de protéines antigel (tréhalose, glycérol) et une résistance accrue au dessèchement.</p>
<p class="resume-text">Les insectes sont les maîtres de la cryptobiose — la suspension presque totale de l'activité métabolique en réponse à des conditions extrêmes. Des chironomides (moucherons) du genre Polypedilum vanderplanki peuvent survivre à une dessiccation complète (moins de 3 % d'eau corporelle), au vide spatial, aux radiations gamma et à des températures de -270 °C à +103 °C à l'état desséché — reprenant leur activité normale lors de la réhydratation. Ces adaptations extrêmes inspirent la recherche sur la préservation de tissus biologiques et sur les possibilités de vie dans des environnements extraterrestres.</p>
<div class="highlight-box"><p>La cigale, symbole de la fable de La Fontaine, chante effectivement tout l'été sans travailler — mais les larves passent 2 à 17 ans (selon les espèces) sous terre à se nourrir de sève racinaire avant d'émerger pour quelques semaines de vie adulte consacrées à la reproduction. Les cigales périodiques nord-américaines (Magicicada), synchronisées sur des cycles de 13 ou 17 ans (nombres premiers), émergent toutes en même temps pour "saturer" les prédateurs — une stratégie anti-prédation collective par la masse.</p></div>
"""
}

def inject_before_quiz(content, new_text):
    pattern = r'(</section>\s*\n\n<section[^>]*id="quiz")'
    result = re.sub(pattern, new_text + r'\1', content)
    if result == content:
        pattern2 = r'(</section>\s*<section[^>]*id="quiz")'
        result = re.sub(pattern2, new_text + r'\1', content)
    return result

with open(FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

modified = 0
for key, enrichment in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        if page.get('type') in ('course', 'lesson'):
            orig = len(page['content'])
            page['content'] = inject_before_quiz(page['content'], enrichment)
            new = len(page['content'])
            print(f"  {key}: {orig} -> {new} (+{new-orig})")
            modified += 1

with open(FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone. {modified} pages modified.")
with open(FILE, 'r', encoding='utf-8') as f:
    check = json.load(f)
pages = check['pages']
short = [(k, len(pages[k].get('content',''))) for k in pages if pages[k].get('type') in ('course','lesson') and len(pages[k].get('content','')) < 10000]
print(f"Pages still < 10000: {len(short)}")
for k,l in short:
    print(f"  {l:6d} | {k}")
print("JSON valid.")
