#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

PATH = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/logique.json'

ENRICHMENTS = {}

ENRICHMENTS['logique-predicats/modeles'] = (
    '<h3>Structures et interpretations formelles</h3>'
    '<p class="resume-text">Un modele (ou structure) pour un langage du premier ordre L est un couple M = (D, I) ou D est un ensemble non vide (domaine) et I est une interpretation qui associe a chaque symbole de constante un element de D, a chaque symbole de fonction n-aire une fonction Dⁿ → D, et a chaque symbole de relation n-aire un sous-ensemble de Dⁿ. Par exemple, le modele standard de l\'arithmetique est (ℕ, I) ou I interprete 0 par l\'entier 0, s par la fonction successeur, + et x par l\'addition et multiplication. Un meme ensemble d\'axiomes peut avoir des modeles tres differents.</p>'
    '<p class="resume-text">La satisfaction φ dans M (notee M ⊨ φ) est definie recursivement selon la structure de φ. Cette definition (Tarski 1933) est la base de la semantique formelle. Un modele M est dit modele de T (ensemble d\'axiomes) si M ⊨ φ pour tout axiome φ de T. La theorie des groupes a comme modeles (ℤ, +), (ℝ\{0}, ×), les groupes de permutations, les groupes de matrices, etc. — toutes les structures satisfaisant les axiomes de groupe. Chaque modele est une realisation concrete des axiomes abstraits.</p>'
    '<div class="highlight-box"><p><strong>Modeles non isomorphes :</strong> Deux modeles peuvent satisfaire les memes axiomes sans etre isomorphes. L\'arithmetique de Peano a des modeles non standards contenant des elements "plus grands que tout entier standard". Ces modeles satisfaisant tous les axiomes du premier ordre de PA mais ne ressemblant pas a ℕ revelent les limites expressives du premier ordre et sont au cœur de l\'analyse non standard de Robinson.</p></div>'
    '<h3>Theoremes fondamentaux de la theorie des modeles</h3>'
    '<p class="resume-text">Le theoreme de completude de Godel (1930) : si T est une theorie consistante (ne prouve pas ⊥), alors T a un modele. Reciproquement, si φ est vraie dans tout modele de T, alors T ⊢ φ (completude). Ces deux directions forment la completude semantique/syntaxique du premier ordre, etablissant l\'equivalence entre la notion semantique de consequence logique (T ⊨ φ) et la notion syntaxique de prouvabilite (T ⊢ φ). C\'est l\'un des resultats les plus importants de la logique mathematique du XXe siecle.</p>'
    '<p class="resume-text">Le theoreme de Lowenheim-Skolem (descendant et ascendant) etablit que toute theorie avec un modele infini a des modeles de toute cardinalite infinie. Le paradoxe de Skolem en decoule : la theorie ZF, qui "prouve" l\'existence des reels non denombrables, a un modele denombrables (du point de vue externe). Dans ce modele, l\'ensemble "R" est "non denombrables" au sens ou aucune bijection R → ℕ n\'existe dans le modele — mais de l\'exterieur, les deux ensembles sont denominables. La notion de denominabilite est relative au modele, revelant la relativity profonde de certains concepts mathematiques.</p>'
    '<div class="highlight-box"><p><strong>Compacite et applications :</strong> Si Γ ⊨ φ (φ decoule de Γ), alors il existe un sous-ensemble fini Γ₀ ⊆ Γ tel que Γ₀ ⊨ φ. Ce theoreme, consequence du theoreme de completude, a des applications en algebre (tout groupe localement fini est la reunion filtrante de sous-groupes finis) et en analyse (l\'analyse non standard). La compacite garantit que le "fini" domine toujours : une consequence logique n\'utilise jamais vraiment une infinite d\'hypotheses simultanement.</p></div>'
    '<h3>Categories de modeles et theorie des modeles moderne</h3>'
    '<p class="resume-text">Une theorie T est categorique si tous ses modeles sont isomorphes. Les theories categoriques sont rares pour le premier ordre (par Lowenheim-Skolem). Mais une theorie peut etre κ-categorique : tous ses modeles de cardinalite κ sont isomorphes. La theorie des corps algebriquement clos de caracteristique 0 est κ-categorique pour tout κ > ℵ₀ (theoreme de Morley, 1965) — un resultat profond qui lanca la theorie des modeles stable.</p>'
    '<p class="resume-text">La stabilite (Shelah, 1969-1978) est une propriete centrale des theories en theorie des modeles moderne. Une theorie est stable si elle n\'a pas "trop" de modeles, au sens ou le nombre de modeles non isomorphes de cardinalite κ est au plus 2^κ. Les theories stables ont une structure modelee-theorique riche : elles admettent une notion de "dimension" et de "genericite". Cette theorie, developpee dans l\'ouvrage monumental "Classification Theory" de Shelah, est aujourd\'hui un domaine majeur des mathematiques fondamentales avec des applications en geometrie algebrique (la preuve de la conjecture de Mordell-Lang par Hrushovski utilise la theorie des modeles).</p>'
    '<div class="highlight-box"><p><strong>Applications en geometrie :</strong> Hrushovski utilisa la theorie des modeles pour prouver la conjecture de Mordell-Lang (1996) : sur un corps de caracteristique 0, l\'intersection d\'un sous-groupe d\'un groupe algebrique avec une sous-variete algebrique est une reunion finie de translates de sous-groupes. Cette preuve improbable — utilisant la theorie des modeles stables pour demontrer un theoreme de geometrie algebrique — illustre les connexions profondes entre logique et mathematiques "pures".</p></div>'
)

ENRICHMENTS['paradoxes/russell'] = (
    '<h3>Formulation precise et impact sur la theorie des ensembles</h3>'
    '<p class="resume-text">Le paradoxe de Russell (1901, publie 1903) decoula de l\'analyse des Grundgesetze de Frege. L\'axiome de comprehension de Frege permettait de former l\'ensemble {x | P(x)} pour n\'importe quel predicat P. En prenant P(x) = x ∉ x, on forme R = {x | x ∉ x}. Alors : si R ∈ R, alors R satisfait sa condition de non-appartenance, donc R ∉ R — contradiction. Si R ∉ R, alors R ne satisfait pas sa condition, donc R ∈ R — contradiction. L\'ensemble R ne peut ni appartenir ni ne pas appartenir a lui-meme. Frege apprit le paradoxe par une lettre de Russell quelques semaines avant la publication du second volume des Grundgesetze — il dut ajouter en hate une appendice avouant que les fondements etaient ebranles.</p>'
    '<p class="resume-text">Cantor avait pressenti un probleme similaire avec "l\'ensemble de tous les ensembles" : si U est l\'ensemble de tous les ensembles, alors P(U) (ensemble des parties de U) devrait etre plus grand que U par le theoreme de Cantor (|P(A)| > |A|), mais P(U) ⊆ U puisque U contient tout — contradiction. Ce "paradoxe de Cantor" montre que l\'axiome de comprehension illimitee est intenable. La resolution necessita de reformuler entierement les fondements de la theorie des ensembles.</p>'
    '<div class="highlight-box"><p><strong>Lettre de Russell a Frege :</strong> "Il y a un seul point ou j\'ai rencontre une difficulte..." La lettre de Russell (1902) demontrait le paradoxe en deux lignes. La reponse de Frege revela une integrite intellectuelle rare : il admit immediatement que le fondement de son oeuvre etait detruit, ajoutant "L\'arithmetique vacille" au colophon du volume 2. Frege ne trouva jamais de solution satisfaisante et abandonna partiellement ses ambitions de fonder l\'arithmetique sur la logique.</p></div>'
    '<h3>Solutions : theorie des types et axiomatique ZF</h3>'
    '<p class="resume-text">Deux grandes solutions emergerent. Russell lui-meme proposa la theorie des types (1908, elaboree dans les Principia Mathematica avec Whitehead, 1910-1913) : les objets sont stratifies en types — les individus sont de type 0, les ensembles d\'individus de type 1, les ensembles d\'ensembles d\'individus de type 2, etc. L\'appartenance x ∈ y n\'est bien formee que si le type de y est le type de x plus 1. Ainsi R = {x | x ∉ x} est illicite car x ∈ x violerait la stratification des types. La theorie des types, bien que complexe, est la base des fondements logicistes et du lambda-calcul type.</p>'
    '<p class="resume-text">Zermelo (1908) puis Fraenkel proposerent l\'axiomatique ZF : remplacer la comprehension illimitee par l\'axiome de separation (on peut former {x ∈ A | P(x)} seulement en partant d\'un ensemble existant A) et l\'axiome du remplacement (l\'image d\'un ensemble par une fonction est un ensemble). La definition R = {x | x ∉ x} est illicite car elle n\'est pas relative a un ensemble existant. ZF+Choix (ZFC) est devenu le systeme fondationnel standard des mathematiques, suffisant pour formaliser toutes les mathematiques ordinaires sans produire de paradoxes connus.</p>'
    '<div class="highlight-box"><p><strong>Choix et consequences controversees :</strong> L\'axiome du choix (AC) est independant de ZF (Godel 1938, Cohen 1963). AC implique le theoreme de Banach-Tarski : une sphere solide peut etre decomposee en un nombre fini de parties et reassemblee en deux spheres de meme volume. Ce resultat paradoxal (mais non contradictoire) montre qu\'AC permet des constructions tres non-constructives. Les mathematiciens constructivistes (comme Bishop) rejettent AC pour cette raison, obtenant des mathematiques plus proches des constructions effectives.</p></div>'
    '<h3>Heritage : theorie des types et fondements informatiques</h3>'
    '<p class="resume-text">La theorie des types de Russell, raffinee par Church (lambda-calcul type, 1940), Martin-Lof (theorie des types intuitioniste, 1975) et Girard (systeme F, 1972), est devenue le fondement des langages de programmation fonctionnels et des assistants de preuve. En Haskell, le systeme de types interdit l\'auto-application non typee qui menait au paradoxe de Russell. Les types dependants de Coq et Agda permettent d\'exprimer des proprietes mathematiques dans les types eux-memes, recombinant logique et programmation via la correspondance de Curry-Howard.</p>'
    '<p class="resume-text">Le paradoxe de Russell est aussi a l\'origine de la distinction ensemble/classe propre en theorie des ensembles. Une classe propre comme "l\'ensemble de tous les ensembles" ou "l\'ensemble de tous les groupes" n\'est pas un ensemble — elle est trop grande pour l\'etre (par le paradoxe de Cantor-Burali-Forti). En theorie des categories (Mac Lane, Eilenberg, 1945), cette distinction est fondamentale : la categorie de tous les ensembles, Set, est une classe propre. Grothendieck introduisit les "univers" pour manipuler ces collections sans tomber dans les paradoxes — technique adoptee par la geometrie algebrique moderne.</p>'
    '<div class="highlight-box"><p><strong>Rust et securite memoire :</strong> Le systeme de types lineaires de Rust (inspire de la logique lineaire de Girard, elle-meme liee a la theorie des types) elimine statiquement les bugs de memoire (use-after-free, double-free, data races) qui affectent C et C++. Chaque valeur a un unique "proprietaire" — directement le principe d\'ensembles bien fondes de ZF transporte dans les types. La regle de propriete de Rust est, en un sens, une solution pragmatique au paradoxe de Russell appliquee aux references memoire.</p></div>'
)

ENRICHMENTS['paradoxes/zenon'] = (
    '<h3>Les paradoxes et leur contexte philosophique</h3>'
    '<p class="resume-text">Les paradoxes de Zenon d\'Elee (Ve s. av. J.-C.) sont des arguments philosophiques contre la realite du mouvement et de la pluralite, defenses de la these de Parmenide que l\'etre est un et immobile. Achille et la tortue : si la tortue a une avance de 100m sur Achille, quand Achille parcourt 100m, la tortue est a 10m devant ; quand Achille parcourt ces 10m, la tortue est a 1m devant ; etc. Achille doit franchir une infinite de distances, ce qui semble impossible. La dichotomie : pour franchir une distance, il faut d\'abord en franchir la moitie, puis la moitie du reste, etc. — une infinite de taches.</p>'
    '<p class="resume-text">La fleche : a chaque instant, une fleche en vol occupe un espace egal a elle-meme, donc est immobile. La somme d\'une infinite d\'immobilites est une immobilite. Le stade : des rangees de soldats se deplacent en sens contraire devant une rangee immobile. Un soldat face a la rangee mobile passe devant deux soldats ennemis pour chaque soldat immobile depasse — les vitesses relatives sont incoherentes. Ces paradoxes forcerent les Grecs a reflechir a la nature de l\'infini, du continu et de la mesure, questions que seuls le calcul infinitesimal et la theorie des ensembles resoudront 2000 ans plus tard.</p>'
    '<div class="highlight-box"><p><strong>La reponse aristotelicienne :</strong> Aristote distingua l\'infini actuel (un tout infini existant simultanement) de l\'infini potentiel (une suite sans fin). Pour lui, le temps et l\'espace sont infiniment divisibles en puissance mais pas en acte — Achille traverse une infinite de distances en puissance, mais cela ne l\'empeche pas de le faire en temps fini. Cette solution evite le probleme mais ne le resout pas mathematiquement : il faudra attendre Cauchy et Weierstrass pour une reponse rigoureuse.</p></div>'
    '<h3>Resolution mathematique : series et limites</h3>'
    '<p class="resume-text">La resolution mathematique des paradoxes de Zenon repose sur la convergence des series geometriques. La serie Σ(1/2)ⁿ pour n=0 a l\'infini vaut exactement 2 (formule de la serie geometrique : a/(1-r) pour |r|<1). Achille traverse 100 + 10 + 1 + 0.1 + … = 100/(1-0.1) ≈ 111m en temps total 111m/vitesse_Achille — fini. La somme d\'une infinite de termes peut etre finie. Ce fait, que les Grecs ne pouvaient pas formaliser, est rendu rigoureux par la definition epsilon-delta de la limite par Cauchy et Weierstrass au XIXe siecle.</p>'
    '<p class="resume-text">Le calcul integral (Newton, Leibniz, XVIIe s.) formalisa l\'idee de somme d\'une infinite de quantites infiniment petites. L\'integrale de Riemann decompose une surface en une infinite de rectangles infiniment etroits dont la somme converge. La theorie de la mesure de Lebesgue (1902) generalisa encore : on peut mesurer des ensembles tres "irreguliers" (ensembles de Cantor, fractales) en sommant des contributions infinitesimales. Ces theories resoudent formellement les paradoxes de Zenon : l\'infini est dompte par les notions rigoureuses de limite, de serie convergente et de mesure.</p>'
    '<div class="highlight-box"><p><strong>Ensemble de Cantor :</strong> L\'ensemble de Cantor — construit en retirant iterativement le tiers central de chaque intervalle — a une mesure de Lebesgue nulle (la somme des longueurs retirees est 1/3 + 2/9 + 4/27 + … = 1) mais est non denombrables. C\'est un "ensemble de Zenon" : une infinite de points sans longueur. Il illustre que l\'infini des mathematiques modernes va bien au-dela de ce que les paradoxes de Zenon interrogeaient.</p></div>'
    '<h3>Paradoxes de Zenon en informatique et physique</h3>'
    '<p class="resume-text">En informatique, le paradoxe de Zenon apparait dans les systemes temps reel et les simulations numeriques. La discretisation du temps (pas de simulation dt) transforme les "infinites" d\'etapes en sommes finies, evitant le paradoxe. Mais les systemes hybrides — alternant evolution continue et evenements discrets — peuvent produire un nombre infini d\'evenements en temps fini (phenomene de "Zeno" dans les automates hybrides). Un thermostat qui rebondit infiniment rapidement entre chaud et froid est un systeme Zenon : il est impossible a simuler exactement sur ordinateur et doit etre regularise.</p>'
    '<p class="resume-text">En physique quantique, le paradoxe de Zenon quantique (Misra et Sudarshan, 1977) est un effet reel : mesurer frequemment un systeme quantique instable ralentit sa desintegration. La mesure "projette" continument le systeme dans son etat initial, et a la limite de mesures infiniment frequentes, le systeme ne se desintegre jamais — un veritable effet Zenon observable en laboratoire. L\'effet anti-Zenon est aussi possible : certains systemes se desintegrent plus vite si mesures frequemment. Ces effets ont des applications en calcul quantique pour la correction d\'erreurs.</p>'
    '<div class="highlight-box"><p><strong>Effets Zenon quantiques :</strong> L\'effet Zenon quantique a ete observe experimentalement pour la premiere fois en 1989 avec des ions Be+ (Itano et al., NIST). Des impulsions micro-ondes jouant le role des "mesures" reduisirent significativement le taux de transition entre niveaux d\'energie. En calcul quantique, l\'effet Zenon peut etre utilise pour "geler" un etat quantique et le proteger de la decoherence — une strategie pour la preservation d\'etats logiques dans les ordinateurs quantiques.</p></div>'
)

ENRICHMENTS['paradoxes/newcomb'] = (
    '<h3>Enonce et structure du paradoxe</h3>'
    '<p class="resume-text">Le paradoxe de Newcomb (propose par William Newcomb ~1960, popularise par Nozick en 1969) met en scene deux boites : A (transparente, contient 1000€) et B (opaque, contient soit 1 000 000€, soit rien). Un predicateur a rempli B apres avoir predit votre choix avec fiabilite parfaite : si il predisait "un seul boite", B contient 1 M€ ; si il predisait "deux boites", B est vide. Vous choisissez : prendre seulement B (un seul choix) ou prendre A et B (deux boites) ? Les deux raisonnements dominants menent a des conclusions opposees.</p>'
    '<p class="resume-text">L\'argument dominance : A contient toujours 1000€ de plus que B seul, donc prendre les deux boites domine strictement. L\'argument esperance : si vous prenez une seule boite, vous esperez 1 M€ * probabilite haute de prediction correcte. Si vous prenez les deux, vous esperez 1000€ + presque rien (car le predicateur a predit "deux boites" et a laisse B vide). L\'esperance de "une seule boite" est largement superieure si le predicateur est fiable. Ces deux arguments sont valides et conduisent a des conclusions opposees — c\'est le paradoxe.</p>'
    '<div class="highlight-box"><p><strong>Sondage philosophique :</strong> Nozick nota que parmi les philosophes, les reactions etaient violemment partagees. Certains trouvent la reponse "deux boites" evidente (le predicateur a deja agi, rien ne peut changer B) ; d\'autres trouvent "une boite" evidente (statistiquement, les preneurs d\'une boite gagnent presque toujours 1M€). Ce desaccord profond entre experts revele une ambiguite fondamentale dans nos intuitions sur la decision, la causalite et la prevision.</p></div>'
    '<h3>Theories de la decision : causale vs probatoire</h3>'
    '<p class="resume-text">Le paradoxe separe deux theories de la decision rationnelle. La theorie de la decision causale (Gibbard et Harper, 1978) : choisir l\'action qui maximise l\'utilite en considerant ses effets causaux futurs. Puisque la prediction est deja faite, mon choix ne cause rien dans B — je dois prendre les deux boites pour maximiser causalement. La theorie de la decision probatoire (Jeffrey) : choisir l\'action qui maximise l\'esperance conditionnelle a l\'evidence. "Je prends une boite" est une forte evidence que B contient 1M€ — l\'esperance conditionnelle de "une boite" est maximale, donc choisir une boite.</p>'
    '<p class="resume-text">Des extensions du paradoxe distinguent plus finement les approches. Le fumeur morbide (Egan) : supposer que fumer est un indicateur fiable d\'un gene qui cause a la fois l\'envie de fumer et des maladies cardiaques, mais que fumer ne cause pas directement les maladies. La theorie probatoire recommande de ne pas fumer (evidence de gene sain), mais la decision causale dit que fumer n\'ayant pas d\'effet causal sur les maladies, on peut fumer si on le desire. Des intuitons sont a nouveau divisees, revelant que les deux theories capturent des aspects differents de la rationalite pratique.</p>'
    '<div class="highlight-box"><p><strong>Intelligence artificielle et agents :</strong> Le paradoxe de Newcomb est central dans la conception d\'agents IA rationnels. Les "agents CDC" (Causal Decision-Correlated agents) resoudent des variantes du paradoxe de Newcomb en cooperant dans des jeux iteratifs. Les recherches MIRI (Machine Intelligence Research Institute) sur la "decision theory" visent a concevoir des agents dont la rationalite reste coherente meme face a des predicteurs parfaits — question cruciale pour des IA suffisamment avancees pouvant prevoir les actions d\'autres agents.</p></div>'
    '<h3>Connections : jeu du prisonnier et equilibres de Nash</h3>'
    '<p class="resume-text">Le dilemme du prisonnier itere est structurellement lie au paradoxe de Newcomb : si deux agents rationnels "trahissent toujours" (equilibre de Nash dominant), ils obtiennent des resultats sous-optimaux. Si des agents mecaniques ont la propriete d\'etre mutuellement predictibles, la cooperation emerge comme solution rationnelle — un resultat proche de "une seule boite" dans Newcomb. Les travaux d\'Axelrod (The Evolution of Cooperation, 1984) montrent que "Tit-for-Tat" (cooperer d\'abord, puis imiter) gagne les tournois de dilemme du prisonnier itere — une forme de rationalite probatoire emergente.</p>'
    '<p class="resume-text">La theorie de la decision transparente (Hofstadter, 1985) propose que deux agents suffisamment intelligents et similaires qui reconnaissent leur similarite doivent cooperer dans le dilemme du prisonnier, car "ma decision est une evidence sur sa decision". Cette idee — que l\'identite ou la similarite entre agents cree des correlations qui justifient le raisonnement probatoire — est au coeur des debats modernes sur la cooperation et la rationalite collective. Les recherches en ethique de l\'IA sur le comportement cooperatif des agents LLM explorent ces questions experimentalement.</p>'
    '<div class="highlight-box"><p><strong>Omega-consistency et previsibilite :</strong> Une variante du paradoxe de Newcomb ou le predicateur est un agent IA capable de simuler parfaitement votre raisonnement pose des questions fondamentales : si l\'IA peut predire votre choix avec certitude, votre choix est-il libre ? La question rejoint celle du determinisme et du libre arbitre, mais dans un cadre precis et calculable. Les theoriciens de la decision informatique (Bostrom, Yudkowsky) voient ces paradoxes comme des tests theoriques essentiels pour la conception d\'IA "super-intelligentes" agissant de maniere coherente dans des environnements strategiques.</p></div>'
)

ENRICHMENTS['paradoxes/semantiques'] = (
    '<h3>Le paradoxe de Berry et l\'autoreference</h3>'
    '<p class="resume-text">Le paradoxe de Berry (attribue a G. G. Berry, ~1906, rapporte par Russell) : "Le plus petit entier naturel non descriptible en moins de treize mots." Cette description fait elle-meme moins de treize mots mais pretend decrire un entier qui, par definition, ne peut pas etre decrit en moins de treize mots — contradiction. Le paradoxe depend de la notion vague de "descriptible", qui n\'est pas formellement definie. Comme le paradoxe du menteur, il expose les limites de l\'autoreference dans le langage naturel.</p>'
    '<p class="resume-text">Le paradoxe de Grelling-Nelson (1908) porte sur la propriete d\'etre "heterologique" : un adjectif est heterologique s\'il ne s\'applique pas a lui-meme. "Court" est long, donc heterologique. "Francais" est ecrit en francais, donc autologique. "Heterologique" est-il heterologique ? Si oui, il s\'applique a lui-meme, donc il est autologique — contradiction. Si non, il ne s\'applique pas a lui-meme, donc il est heterologique — contradiction. Ce paradoxe est l\'analogue pour les predicats du paradoxe de Russell pour les ensembles.</p>'
    '<div class="highlight-box"><p><strong>Kolmogorov et complexite :</strong> La complexite de Kolmogorov K(n) d\'un entier n est la longueur du plus court programme qui produit n. Le paradoxe de Berry formalise en theorie de l\'information : "le plus petit entier dont la complexite de Kolmogorov depasse L mots" est exprimable en O(log L) symboles mais a une complexite > L — contradiction pour L grand. Ce paradoxe est au coeur de la preuve que K est non calculable : supposer K calculable permettrait de construire un tel entier algorithmiquement.</p></div>'
    '<h3>Paradoxes pragmatiques et performatifs</h3>'
    '<p class="resume-text">Les paradoxes pragmatiques concernent non pas le contenu mais l\'acte de communication. "Je mens toujours" est un paradoxe semantique. "Je ne peux pas dire un mot" (dit) est un paradoxe pragmatique. "Cet ordre ne doit pas etre obeyi" est un paradoxe performatif : pour obeir, il faut desobeir. Ces paradoxes apparaissent en psychologie de la communication (double lien de Bateson), en droit (lois qui s\'abrogent elles-memes), et dans les systemes informatiques autoreferents.</p>'
    '<p class="resume-text">Le paradoxe de Buridan (une variante du paradoxe du menteur attribuee a Jean Buridan, XIVe s.) : Socrate dit "Ce que Platon dit est faux" ; Platon dit "Ce que Socrate dit est vrai." Si Socrate dit vrai, Platon dit vrai, donc Socrate dit faux — contradiction. Si Socrate dit faux, Platon dit faux, donc Socrate dit vrai — contradiction. Ce paradoxe a deux propositions mutuellement autoreferentes montre que l\'autoreference peut impliquer plusieurs enonces interdependants, pas seulement un seul, et que la hierarchie de Tarski doit s\'appliquer globalement.</p>'
    '<div class="highlight-box"><p><strong>Double lien et schizophrenie :</strong> Gregory Bateson (1956) proposa que les doubles liens — situations ou deux messages contradictoires et inechappables sont envoyes simultanement — pourraient etre un facteur contribuant a la schizophrenie. Exemple : une mere qui dit verbalement "viens me voir" mais dont le langage corporel dit "eloigne-toi". L\'enfant ne peut ni obeir ni desobeir sans violer un des messages. Ce paradoxe pragmatique aurait des consequences psychologiques profondes selon la theorie systemique de la communication.</p></div>'
    '<h3>Paradoxes et frontières de l\'expressivité</h3>'
    '<p class="resume-text">Les paradoxes semantiques revelent les limites de l\'expressivite des langages. Tarski montra que la verite pour L ne peut pas etre definie dans L. Church montra que la validite du premier ordre est semi-decidable mais pas decidable. Turing montra que l\'arret est indecidable. Godel montra que la coherence d\'un systeme ne peut pas etre prouvee dans ce systeme. Ces resultats forment une coherence : les paradoxes d\'autoreference signalent des proprietes au bord de l\'expressivite d\'un langage — ce qu\'il peut decrire mais pas completer.</p>'
    '<p class="resume-text">En informatique theorique, ces limites ont une traduction precise. Le probleme de l\'arret est au bord de ce que les machines de Turing peuvent decider. Les problemes recursivements enumerables (RE) sont ceux dont les instances positives sont decidables (le programme s\'arrete sur cette entree), mais les instances negatives peuvent ne jamais etre decidees (le programme boucle — comment savoir si c\'est temporaire ou definitif ?). Cette frontiere entre RE et co-RE (complementaire) est precisement la frontiere entre les paradoxes "productifs" (generateurs de nouvelles verites par diagonalisation) et les paradoxes "destructifs" (contradictions pures).</p>'
    '<div class="highlight-box"><p><strong>Theoreme de Rice :</strong> Toute propriete non triviale des fonctions calculees par des programmes est indecidable (theoreme de Rice, 1953). "Ce programme termine-t-il toujours ?" "Ce programme produit-il la bonne sortie ?" sont indecidables. La preuve utilise une diagonalisation similaire au paradoxe de Berry : supposer un decideur pour la propriete permettrait de construire un programme qui satisfait la propriete si et seulement si il ne la satisfait pas — contradiction directement issue des paradoxes semantiques de Zenon et Russell.</p></div>'
)

ENRICHMENTS['godel/indecidabilite'] = (
    '<h3>L\'indecidabilite de l\'arithmetique et le theoreme de Church</h3>'
    '<p class="resume-text">Le theoreme de Church (1936) etablit que le probleme de la validite du premier ordre est indecidable : il n\'existe pas d\'algorithme qui, donne une formule du premier ordre, determine en temps fini si elle est valide (vraie dans tous les modeles). Ce resultat est obtenu par reduction : on montre que si la validite etait decidable, le probleme de l\'arret le serait aussi. Church et Turing prouvaient independamment ce resultat la meme annee, Turing via les machines de Turing et Church via le lambda-calcul — etablissant leur equivalence (these de Church-Turing).</p>'
    '<p class="resume-text">La theorie de l\'arithmetique du premier ordre (PA) est indecidable : aucun algorithme ne peut determiner si une formule du premier ordre sur l\'arithmetique est vraie dans ℕ. Ce resultat est plus fort que l\'incompletude : non seulement il existe des formules non prouvables dans PA, mais meme la question "est-ce vrai dans ℕ ?" est algorithmiquement indecidable. En revanche, certaines theories du premier ordre sont decidables : la geometrie elementaire (Tarski 1948), la theorie des corps algebriquement clos (Lefschetz, Chevalley), et la theorie additive des entiers (Presburger 1929).</p>'
    '<div class="highlight-box"><p><strong>Arithmetique de Presburger :</strong> En eliminant la multiplication de l\'arithmetique (ne gardant qu\'addition, egalite, et predicats x ≡ k (mod m)), on obtient une theorie decidable. L\'algorithme de Presburger (1929) decide la validite en temps doublement exponentiel. Les compilateurs utilisent l\'arithmetique de Presburger pour l\'analyse de tableaux (verifier que les indices restent dans les bornes) — exploitant l\'un des rares fragments decidables de l\'arithmetique.</p></div>'
    '<h3>Hierarchie arithmetique et degres de Turing</h3>'
    '<p class="resume-text">La hierarchie arithmetique classifie les proprietes des entiers selon leur decidabilite. Σ₁ : proprietes de la forme ∃x P(x) avec P decidable (recursivements enumerables). Π₁ : negations des Σ₁ (co-RE). Σ₂ : ∃x∀y Q(x,y) avec Q decidable. Π₂ : ∀x∃y Q(x,y). Et ainsi de suite. Le probleme de l\'arret est Σ₁-complet. La coherence de PA est Π₁ (si PA est incoherente, on peut le verifier — mais pas si elle est coherente, par le second theoreme de Godel). L\'hypothese du continu, relativement aux axiomes de ZFC, est ni dans Σₙ ni dans Πₙ pour aucun n fini.</p>'
    '<p class="resume-text">Les degres de Turing organisent les problemes selon leur "difficulte relative" — un probleme A est Turing-reductible a B si un oracle pour B permettrait de decider A. Le degre 0 contient les problemes decidables. Le degre 0\' contient le probleme de l\'arret (K). Le degre 0\'\' contient l\'arret du probleme de l\'arret. Cette hierarchie est infinie et dense — entre deux degres il y en a toujours un autre. La theorie des degres de Turing est un domaine riche reliant logique, calculabilite et theorie de la mesure (theorie des ensembles definissables).</p>'
    '<div class="highlight-box"><p><strong>Oracles et hyperCalcul :</strong> Un oracle pour le probleme de l\'arret permettrait de decider toutes les proprietes Σ₁. Mais avec cet oracle, de nouveaux problemes deviendraient Σ₁ (et donc decidables), et ainsi de suite. Cette progression transfinite — le saut de Turing — peut etre itere sur tous les ordinaux. L\'hyperCalcul, ou calcul avec oracle, est un modele theorique explorant ce que pourrait calculer une machine avec acces a des oracles de plus en plus puissants — une question fondamentale en theorie de la calculabilite qui relie directement logique et informatique theorique.</p></div>'
    '<h3>Indecidabilite en pratique informatique</h3>'
    '<p class="resume-text">L\'indecidabilite affecte directement l\'informatique pratique. Par le theoreme de Rice, aucune propriete semantique non triviale des programmes n\'est decidable : verifier si un programme termine, s\'il produit la bonne sortie, s\'il contient des boucles infinies, s\'il est equivalent a un autre programme. Ces problemes sont fondamentalement non decidables. Les analyses statiques de programmes (lint, analyse de flot, verifications de types) approchent ces problemes par des sur-approximations decidables : si l\'outil dit "pas de bug possible", c\'est sur ; mais il peut dire "bug possible" pour un programme correct (faux positif).</p>'
    '<p class="resume-text">En securite informatique, les limites de l\'indecidabilite sont exploitees par les malwares polymorphes : ils mutent leur code a chaque execution pour echapper a la detection, exploitant le fait que la question "est-ce un malware ?" est indecidable en general. Les antivirus utilisent des heuristiques et des empreintes (signatures) pour approximer cette detection, mais peuvent toujours etre contournes par un malware suffisamment sophistique. La course entre malwares et antivirus est, en un sens, une course dans l\'indecidabilite — les antivirus cherchent des fragments decidables, les malwares exploitent les zones indecidables.</p>'
    '<div class="highlight-box"><p><strong>Verification formelle et ses limites :</strong> Les outils de verification formelle (Frama-C, Astrée, Infer) utilisent des interpretations abstraites — des sur-approximations decidables de la semantique des programmes. Astrée a ete utilise pour verifier l\'absence d\'erreurs runtime dans le logiciel de vol de l\'Airbus A380 (environ 130 000 lignes de C). Si l\'outil trouve zero alarme, le programme est correct. Mais pour des programmes generaux, l\'indecidabilite garantit que ces outils produiront toujours des faux positifs ou auront des faux negatifs dans certains cas.</p></div>'
)

ENRICHMENTS['godel/turing'] = (
    '<h3>La machine de Turing comme modele de calcul universel</h3>'
    '<p class="resume-text">Alan Turing (1936) definit un modele de calcul abstrait : une machine avec une tete de lecture/ecriture sur un ruban infini de cases, un etat interne parmi un ensemble fini, et une table de transition determinant la prochaine action (ecrire un symbole, deplacer la tete, changer d\'etat). Ce modele minimaliste capture toute la puissance du calcul algorithmique. La these de Church-Turing affirme que tout ce qui est intuitivement calculable est calculable par une machine de Turing — une these non prouvable (car "intuitivement calculable" n\'est pas defini formellement) mais universellement acceptee, soutenue par l\'equivalence avec le lambda-calcul, les fonctions recursives, les machines RAM, les langages de programmation modernes.</p>'
    '<p class="resume-text">La machine de Turing universelle (UTM) simule toute machine de Turing donnee en entree avec ses donnees. Elle est la demonstration formelle qu\'un seul programme peut simuler tous les autres — le fondement theorique du concept d\'ordinateur a programme enregistre. L\'ordinateur de von Neumann (1945), qui stocke programme et donnees dans la meme memoire, est la realisation physique de ce concept. La puissance de l\'UTM — etre universellement simulante — est aussi sa limite : elle peut simuler n\'importe quelle machine, mais cette universalite est exactement ce qui la rend indecidable sur des proprietes generales.</p>'
    '<div class="highlight-box"><p><strong>Turing et la cryptographie :</strong> Pendant la Seconde Guerre mondiale, Turing travailla a Bletchley Park pour dechiffrer Enigma. Il concepit la "Bombe" — une machine electromecanique realisee sur la base de principes qu\'il avait formalises theoriquement. Le succes du dechiffrement (Operation Ultra) contribua decisvement a la victoire alliee. Le travail de Turing illustre la connexion directe entre theorie pure (calculabilite) et applications pratiques (cryptanalyse) — une connexion caracteristique de l\'informatique theorique.</p></div>'
    '<h3>Le probleme de l\'arret et ses consequences</h3>'
    '<p class="resume-text">Le theoreme de l\'indecidabilite de l\'arret de Turing (1936) affirme qu\'il n\'existe pas de machine de Turing H qui, donnee une machine M et une entree w, decide si M(w) s\'arrete. La preuve est la diagonalisation : construire D(M) = si H(M,M) dit "arrete" alors boucle, sinon s\'arrete. Evaluer D(D) mene a une contradiction (D s\'arrete si et seulement si il ne s\'arrete pas). Ce raisonnement est isomorphe au paradoxe du menteur et au premier theoreme d\'incompletude de Godel — les trois sont des instances du lemme de diagonalisation.</p>'
    '<p class="resume-text">A partir du probleme de l\'arret, on peut prouver par reduction l\'indecidabilite de tres nombreux problemes : l\'equivalence de deux programmes, la satisfaisabilite du premier ordre, le probleme du bout du monde (tiling), le probleme des mots pour les semi-groupes. La technique de reduction (si X etait decidable, on pourrait decider Y qui est connu indecidable) est l\'outil fondamental de la theorie de la calculabilite — analogue aux reductions polynomiales de la theorie de la complexite pour prouver la NP-completude.</p>'
    '<div class="highlight-box"><p><strong>Correspondance de Post :</strong> Le probleme de correspondance de Post (PCP) : donnees des paires de mots (uᵢ, vᵢ), existe-t-il une sequence d\'indices i₁,…,iₙ telle que u_i₁…u_iₙ = v_i₁…v_iₙ ? PCP est indecidable par reduction depuis l\'arret. Il est tres utile pour prouver l\'indecidabilite de proprietes de grammaires hors-contexte (ambiguite, intersection vide avec un langage regulier) et de problemes de reachabilite dans les systemes de remplacement. C\'est l\'outil standard en theorie des langages formels pour prouver les indecidabilites.</p></div>'
    '<h3>Test de Turing et intelligence artificielle</h3>'
    '<p class="resume-text">Dans "Computing Machinery and Intelligence" (1950), Turing proposa le test de Turing (ou "jeu d\'imitation") : si un evaluateur humain, conversant par texte avec un humain et avec une machine, ne peut pas distinguer laquelle est la machine apres un interrogatoire suffisant, la machine peut etre consideree comme "pensante". Turing reformulait la question "les machines peuvent-elles penser ?" (vague) en une question comportementale precise et testable, anticipant le fonctionnalisme en philosophie de l\'esprit.</p>'
    '<p class="resume-text">Le test de Turing est devenu central en IA, mais reste controverse. Le programme ELIZA (Weizenbaum, 1966) trompait des utilisateurs naifs en imitant un psychotherapeute — mais personne ne le considerait pensant. Les grands modeles de langage actuels (GPT-4, Claude) passent facilement le test original mais echouent des variantes "adversariales" detectant des failles typiques des LLM. Searle objecta (argument de la chambre chinoise, 1980) que la simulation du comportement cognitif ne constitue pas la cognition : un humain suivant des regles de manipulation de symboles chinois pourrait "comprendre" le chinois sans le comprendre vraiment. Ce debat philosophique est toujours ouvert.</p>'
    '<div class="highlight-box"><p><strong>LLM et test de Turing :</strong> En 2023, des evaluateurs humains ne pouvaient plus distinguer GPT-4 des humains dans des conversations libres. Pourtant, ces memes modeles echouent sur des tests simples de raisonnement spatial, d\'arithmetique elementaire, et de bon sens physique — des competences triviales pour les humains. Cela suggere que le test de Turing original mesure surtout la fluence linguistique, non la comprehension generale. Des tests alternatifs (Winograd schemas, ARC challenge) visent a evaluer le raisonnement generalise que Turing avait en tete.</p></div>'
)

ENRICHMENTS['godel/church'] = (
    '<h3>Le lambda-calcul de Church</h3>'
    '<p class="resume-text">Alonzo Church developpa le lambda-calcul (1932-1936) comme fondement formel pour les fonctions mathematiques, independamment des machines de Turing. Un terme lambda est soit une variable x, soit une abstraction λx.M (fonction prenant x en parametre et retournant M), soit une application (M N) (appliquer la fonction M a l\'argument N). La reduction beta (λx.M) N → M[N/x] (substituer N pour x dans M) definit le calcul. La reduction eta λx.(M x) → M (si x n\'est pas libre dans M) est une extensionalite : deux fonctions egales sur toutes les entrees sont la meme fonction.</p>'
    '<p class="resume-text">Church encode les entiers naturels dans le lambda-calcul pur : n est represente par λf.λx.fⁿ x (appliquer f n fois a x). L\'addition devient λm.λn.λf.λx. m f (n f x), la multiplication λm.λn.λf. m (n f). Church montra que toutes les fonctions recursives sont lambda-definissables et que le probleme de l\'equivalence de deux termes lambda (beta-equivalence) est indecidable — un resultat parallele a celui de Turing, publie la meme annee, etablissant l\'equivalence des deux modeles.</p>'
    '<div class="highlight-box"><p><strong>Numeraux de Church en Haskell :</strong> En Haskell, les numeraux de Church sont des fonctions d\'ordre superieur : zero = \\f x -> x ; un = \\f x -> f x ; succ n = \\f x -> f (n f x). L\'addition church_add m n = \\f x -> m f (n f x). Ces definitions, issues du lambda-calcul de Church (1936), sont exactement le code Haskell idiomatique — Haskell est litteralement un lambda-calcul type implementé. La correspondance entre theorie pure et langage pratique est ici quasi-litterale.</p></div>'
    '<h3>These de Church-Turing et ses variantes</h3>'
    '<p class="resume-text">La these de Church-Turing affirme que tout ce qui est "intuitivement calculable" (par un humain suivant un algorithme mecanique) est calculable par une machine de Turing (ou equivalement, lambda-definissable, ou fonctions recursives partielles generales). Cette these n\'est pas un theoreme mathematique (car "intuitivement calculable" n\'est pas formellement defini) mais une assertion empirique, soutenue par l\'equivalence prouvee de tous les modeles formels de calcul proposes — machines de Turing, lambda-calcul, fonctions recursives, machines RAM, langages de programmation modernes, automates cellulaires (jeu de la vie de Conway).</p>'
    '<p class="resume-text">Des variantes de la these ont ete proposees. La these de Church-Turing forte : les cerveaux humains sont des machines de Turing (et ne peuvent donc pas calculer plus qu\'elles). Penrose contesta cette these via les theoremes de Godel. La these Church-Turing physique : tout processus physique est simulable par une machine de Turing — remise en question par les modeles de calcul quantique (qubits, algorithme de Shor) qui resoudent certains problemes exponentiellement plus vite mais restent dans la meme classe de decidabilite. L\'hyperCalcul postule des machines physiques qui decident le probleme de l\'arret en utilisant des effets relativistes ou quantiques — reste speculatif.</p>'
    '<div class="highlight-box"><p><strong>Calcul quantique et these de Church-Turing :</strong> Un ordinateur quantique universel peut simuler toute machine de Turing (avec un overhead polynomial) — il ne calcule pas plus de fonctions, mais certaines peuvent etre calculees exponentiellement plus vite. L\'algorithme de Shor factorise en temps polynomial (quantique) un entier qui demanderait un temps exponentiellement long sur une machine classique. Cela ne contredit pas la these de Church-Turing (les deux calculent les memes fonctions) mais refute sa variante "les complexites sont les memes", ouvrant une nouvelle dimension : la complexite quantique.</p></div>'
    '<h3>Lambda-calcul et langages fonctionnels modernes</h3>'
    '<p class="resume-text">Le lambda-calcul est le fondement theorique de tous les langages de programmation fonctionnels. LISP (McCarthy, 1958) implementa pour la premiere fois les lambdas en machine. ML (Milner, 1973) ajouta l\'inference de types via l\'algorithme W (unification de types, isomorphe a l\'unification de Robinson). Haskell (1990) adopta le lambda-calcul pur type avec paresse et classes de types. OCaml, F#, Scala, Kotlin, et les aspects fonctionnels de Python, Java, JavaScript et C++ sont tous des descendants directs du lambda-calcul de Church. La notation (x → x+1) en Python ou (x) => x+1 en JavaScript est littéralement la notation lambda de Church adapte syntaxiquement.</p>'
    '<p class="resume-text">L\'evaluation paresseuse (lazy evaluation) de Haskell correspond a la strategie de reduction normal-order du lambda-calcul (evaluer l\'argument le plus externe en premier). La stricte (eager) correspond a l\'applicative-order. Church prouva la confluence du lambda-calcul (theoreme de Church-Rosser) : si un terme peut etre reduit de deux facons differentes, les deux reductions menent au meme terme normal — garantissant la coherence du calcul quel que soit l\'ordre d\'evaluation. Ce resultat theorique (1936) justifie que Haskell peut evaluer les expressions dans n\'importe quel ordre sans changer le resultat final.</p>'
    '<div class="highlight-box"><p><strong>Monades et logique modale :</strong> La correspondance de Curry-Howard relie la logique modale S4 aux monades en Haskell. Une monade M est un funteur avec des operations return : a → M a et bind : M a → (a → M b) → M b satisfaisant les lois monadiques — exactement les axiomes de la logique modale. Les monades permettent de structurer des effets de bord (IO, etat, exceptions) dans un langage purement fonctionnel. Eugenia Cheng (2008) montra que les lois monadiques sont les memes que les lois d\'une algebre de Kleisli, reliant monades Haskell, theorie des categories et logique modale en un seul edifice conceptuel.</p></div>'
)

ENRICHMENTS['godel/consequences'] = (
    '<h3>Impact sur les fondements des mathematiques</h3>'
    '<p class="resume-text">Les theoremes d\'incompletude de Godel signerent la fin du programme de Hilbert (1900-1930) : il n\'existe pas de systeme formel recursivements axiomatisable, coherent et complet pour les mathematiques. Ce resultat est souvent mal compris : il ne dit pas que les mathematiques sont incoherentes ou arbitraires, mais qu\'elles ne peuvent pas etre completement capturees par aucun systeme formel fixe. En pratique, les mathematiciens travaillent dans ZFC, qui est suffisamment fort pour toutes les mathematiques ordinaires et dont l\'incompletude ne se manifeste que dans des enonces tres particuliers (hypothese du continu, grands cardinaux).</p>'
    '<p class="resume-text">L\'incompletude a genere de nouvelles disciplines. La theorie des ordres de preuve (proof theory) etudie la force des systemes formels, mesuree par les ordinaux de Gentzen : la force de PA est ε₀, celle de PA + ε₀-induction est ε₁, etc. La theorie des modeles (Tarski, Robinson, Shelah) etudie les relations entre theories et leurs modeles — independamment de la prouvabilite. La theorie des ensembles descriptive (Moschovakis) etudie les ensembles definissables et leur complexite. Toutes ces disciplines sont nees des questions soulevees par l\'incompletude de Godel.</p>'
    '<div class="highlight-box"><p><strong>Programmes de reverse mathematics :</strong> Harvey Friedman (annees 1970-) etudie quels axiomes sont necessaires et suffisants pour prouver les theoremes ordinaires des mathematiques. La plupart des theoremes de l\'analyse standard sont prouvables dans WKL₀ (Weak König Lemma) — un systeme bien plus faible que ZFC. La "reverse mathematics" determine la force logique minimale de chaque theoreme, cartographiant le paysage des forces axiomatiques entre l\'arithmetique de Peano et ZFC.</p></div>'
    '<h3>Consequences en philosophie et sciences cognitives</h3>'
    '<p class="resume-text">Philosophiquement, les theoremes de Godel ont nourri trois positions opposees. Le platonisme mathematique (Godel lui-meme, Kurt Godel, Penrose) : les verites mathematiques existent independamment des systemes formels, et l\'incompletude prouve que l\'intuition mathematique humaine transcende toute formalisation. Le nominalisme (Field) : les mathematiques sont des fictions utiles, et l\'incompletude montre que les "verites" mathematiques ne sont que des consequences de nos axiomes arbitrairement choisis. Le structuralisme (Hellman, Shapiro) : les mathematiques decrivent des structures possibles, et l\'incompletude montre que differentes structures peuvent satisfaire les memes axiomes.</p>'
    '<p class="resume-text">En sciences cognitives, Roger Penrose (L\'Esprit, l\'ordinateur et les lois de la physique, 1989, Le Grand, le Petit et l\'Esprit Humain, 1997) argua que les theoremes de Godel prouvent que la conscience humaine transcende les algorithmes : un mathematicien "voit" la verite de G alors qu\'aucun systeme formel ne peut la prouver. Cette these fut vivement contestee : un humain dans PA ne peut pas non plus prouver G dans PA ; c\'est seulement depuis un meta-systeme qu\'il voit sa verite. Hofstadter (Godel, Escher, Bach, 1979) repondit que les boucles etranges de l\'autoreference, presentees dans le livre, sont le substrat de la conscience — une vision plus nuancee.</p>'
    '<div class="highlight-box"><p><strong>Godel, Escher, Bach :</strong> Le livre de Douglas Hofstadter (prix Pulitzer 1980) explore les boucles etranges de Godel (incompletude), Escher (tableaux avec des boucles visuelles impossibles), et Bach (fugues avec des boucles musicales). Hofstadter argue que ces boucles sont constitutives de la conscience et de l\'identite. L\'idee centrale : "Je" est une boucle etrange — une autoreference qui, comme la phrase de Godel, transcende ses propres niveaux hierarchiques. Ce livre est l\'une des reflexions philosophiques les plus influentes sur l\'esprit, les mathematiques et la physique du XXe siecle.</p></div>'
    '<h3>Applications actuelles et recherche en logique</h3>'
    '<p class="resume-text">L\'incompletude de Godel a des consequences directes en informatique. Toute verification formelle de logiciels complexes doit se faire dans un meta-systeme plus fort que le systeme verifie. Les preuves de coherence des langages de programmation (soundness) sont necessairement faites dans un systeme exterieur. Les assistants de preuve comme Coq operent dans une theorie des types dependants (Calcul des Constructions inductives) dont la coherence est prouvee dans un meta-systeme plus fort, mais dont la coherence de ce meta-systeme est a son tour assumee — une regression infinie fondamentalement incontournable par le second theoreme de Godel.</p>'
    '<p class="resume-text">La theorie des ensembles de grand cardinalite (grand cardinal axioms) etend ZFC avec des axiomes d\'existence d\'ordinaux tres grands : cardinaux inaccessibles, cardinaux de Mahlo, cardinaux mesurables, supercompacts. Ces axiomes forment une hierarchie de force croissante, chacun prouvant la coherence du systeme precedent (contournant le second theoreme de Godel via des meta-systemes plus forts). L\'hypothese du continu est decidable dans certains de ces systemes etendus. Woodin a propose des axiomes definitifs pour decider toutes les questions indeterminees par ZFC — un programme ambitieux visant a "completer" les mathematiques que Godel avait montre incompletables.</p>'
    '<div class="highlight-box"><p><strong>Axiomes de grand cardinalite :</strong> Un cardinal mesurable (Ulam, 1930) est un cardinal κ admettant une mesure non triviale sur ses sous-ensembles. L\'existence d\'un cardinal mesurable implique la coherence de ZFC — donc, par le second theoreme de Godel, cette existence n\'est pas prouvable dans ZFC. Pourtant, la plupart des set-theorists croient a leur existence, sur la base de l\'absence de contradiction trouvee et de la "belle theorie" qu\'ils generent. C\'est la pratique de Godel elle-meme : accepter de nouveaux axiomes sur la base de leur coherence et fecondite, non de leur derivabilite.</p></div>'
)

ENRICHMENTS['logique-predicats/completude'] = (
    '<h3>Enonce et signification du theoreme de completude</h3>'
    '<p class="resume-text">Le theoreme de completude de Godel (1930) affirme : si T est une theorie consistante du premier ordre (ne derive pas ⊥), alors T a un modele. Equivalement, si T ⊨ φ (φ est vraie dans tout modele de T), alors T ⊢ φ (φ est prouvable dans T). Ce double enonce etablit que la notion semantique de consequence logique (vrai dans tous les modeles) coincide exactement avec la notion syntaxique de prouvabilite (derivable dans un systeme formel). La semantique et la syntaxe sont parfaitement alignees pour le premier ordre — un resultat non evident a priori.</p>'
    '<p class="resume-text">La preuve de Godel (amelioree par Henkin en 1949) est constructive : elle exhibe explicitement un modele pour toute theorie consistante. La construction "canonique" de Henkin utilise les termes clos de la theorie elle-meme comme elements du domaine — une idee d\'autoreference productive. Pour chaque formule ∃x φ(x) non prouvablement fausse, on ajoute un "temoin de Henkin" c tel que φ(c) est vraie dans le modele. Ce processus, itere transfiniment, construit un modele maximal-consistant. La completude est en contraste saisissant avec l\'incompletude de Godel (1931) : la completude s\'applique a la validite universelle, l\'incompletude aux systemes specifiques comme PA.</p>'
    '<div class="highlight-box"><p><strong>Completude vs completude :</strong> Deux theoremes de Godel, publie a un an d\'intervalle, portent des noms similaires mais expriment des verities orthogonales. La completude (1930) : toute formule logiquement valide (vraie dans toutes les structures) est prouvable. L\'incompletude (1931) : dans PA, certaines formules vraies dans ℕ ne sont pas prouvables. La completude parle de validite universelle (toutes structures), l\'incompletude de verite dans un modele specifique (ℕ). Ces deux theoremes coexistent sans contradiction.</p></div>'
    '<h3>Compacite et ses applications</h3>'
    '<p class="resume-text">Le theoreme de compacite est un corollaire direct de la completude : si tout sous-ensemble fini de T est satisfaisable, alors T est satisfaisable. La preuve : si T est insatisfaisable, par completude elle est inconsistante (derive ⊥). Toute derivation est finie, donc utilise un sous-ensemble fini de T. Mais ce sous-ensemble fini etait satisfaisable par hypothese — contradiction. La compacite est l\'un des outils les plus puissants de la theorie des modeles, permettant de "passer a la limite" sur des systemes infinis.</p>'
    '<p class="resume-text">Applications de la compacite : (1) Toute theorie avec des modeles finis arbitrairement grands a un modele infini (prendre T plus {il existe au moins n elements} pour tout n — chaque fini est satisfaisable, donc le tout l\'est). (2) Tout graphe dont tout sous-graphe fini est k-colorable est k-colorable (theorie de colorabilite, compacite). (3) L\'analyse non standard de Robinson : les reels non standards existent car la theorie "il existe ε > 0 plus petit que 1/n pour tout entier standard n" est finiment satisfaisable (dans ℝ pour n fixe). Ces applications font de la compacite un outil quotidien des logiciens et des algebristes.</p>'
    '<div class="highlight-box"><p><strong>Compacite et graphes :</strong> Le theoreme de compacite prouve que tout graphe infini dont tout sous-graphe fini est k-colorable est k-colorable (theoreme d\'Erdős-De Bruijn, 1951). La preuve classique sans compacite etait longue et difficile ; avec compacite, elle tient en trois lignes. Ce contraste illustre la puissance des outils logiques pour simplifier des preuves combinatoires, une technique couramment utilisee par les combinatoristes modernes.</p></div>'
    '<h3>Completude en logique propositionnelle et algorithmique</h3>'
    '<p class="resume-text">En logique propositionnelle, le theoreme de completude prend une forme encore plus forte : la completude est decidable et calculable. Le systeme de Hilbert (avec les axiomes de Łukasiewicz et le modus ponens) derive exactement les tautologies propositionnelles. La completude propositionnelle fut prouvee par Post (1921) en meme temps que la decidabilite. Cela donne un algorithme : pour toute formule propositionnelle, verifier si elle est une tautologie (par table de verite) et si oui, elle est prouvable dans le systeme de Hilbert.</p>'
    '<p class="resume-text">La resolution de Robinson (1965) est un systeme de preuve refutationnel complet pour la logique du premier ordre : si Γ ⊨ φ, alors Γ ∪ {¬φ} est insatisfaisable, et la resolution trouvera une derivation de la clause vide. Cette completude, combinee aux heuristiques de recherche (strategies de selection de clauses, ordonnancement), fonde les demonstrateurs automatiques modernes. Vampire (Riazanov, Voronkov), Prover9, et E-prover sont des systemes de resolution complets qui prouvent automatiquement des miliers de theoremes mathematiques, bien que la completude garantisse seulement de trouver une preuve si elle existe, pas en temps borne.</p>'
    '<div class="highlight-box"><p><strong>Semi-decidabilite et exhaustivite :</strong> La completude de la resolution pour le premier ordre garantit la semi-decidabilite : si φ est valide, la resolution le trouvera en temps fini (mais on ne sait pas combien de temps). Si φ n\'est pas valide, la recherche peut ne jamais s\'arreter. C\'est l\'asymetrie fondamentale de la logique du premier ordre : on peut prouver les verites logiques mais pas prouver les non-verites. Les demonstrateurs pratiques fixent des limites de temps et de profondeur de recherche, acceptant d\'echouer sur des formules tres difficiles.</p></div>'
)

ENRICHMENTS['logique-predicats/herbrand'] = (
    '<h3>Le theoreme d\'Herbrand et la methode</h3>'
    '<p class="resume-text">Le theoreme d\'Herbrand (1930) est un resultat fondamental reliant la satisfaisabilite du premier ordre a la satisfaisabilite propositionnelle. Soit φ une formule universelle (sans quantificateur existentiel, apres skolemisation) sur une signature L. Alors φ est insatisfaisable si et seulement si un ensemble fini d\'instances ground de φ (obtenues en substituant des termes clos a toutes les variables) est insatisfaisable en logique propositionnelle. L\'univers d\'Herbrand est l\'ensemble de tous les termes clos sur L, et les instances ground sont toutes les formules obtenues en substituant des elements de cet univers.</p>'
    '<p class="resume-text">La methode d\'Herbrand permet de reduire la satisfaisabilite du premier ordre a une sequence de problemes propositionnels croissants. On enumere les instances ground dans un ordre quelconque, et pour chaque ensemble fini, on teste la satisfaisabilite propositionnelle (decidable). Par le theoreme d\'Herbrand, si la formule est insatisfaisable, on finira par trouver un ensemble fini insatisfaisable. Ce processus est semi-decidable : si la formule est satisfaisable, l\'enumeration ne s\'arrete jamais. C\'est le fondement de la methode de resolution de Robinson (1965) et de tous les demonstrateurs automatiques modernes.</p>'
    '<div class="highlight-box"><p><strong>Theoreme de completude :</strong> Le theoreme d\'Herbrand implique la completude de la logique du premier ordre (prouvee aussi par Godel en 1930) : si Γ ⊨ φ, on peut trouver une preuve finie. La preuve passe par la construction d\'instances ground et la detection d\'une insatisfaisabilite propositionnelle. Herbrand mourut a 23 ans dans un accident d\'alpinisme en 1931, un an apres sa these — l\'une des pertes les plus regrettables de la logique mathematique du XXe siecle.</p></div>'
    '<h3>Resolution, unification et demonstrateurs automatiques</h3>'
    '<p class="resume-text">La methode de resolution de Robinson (1965) combine Herbrand et unification pour eviter l\'enumeration explicite de l\'univers d\'Herbrand. Au lieu de generer toutes les instances ground, on unifie directement les clauses pour trouver les substitutions pertinentes. La regle de resolution : de (A ∨ C) et (¬A ∨ D), si A et ¬A s\'unifient avec la substitution θ, deriver (Cθ ∨ Dθ). Cette regle est complete (par Herbrand) et sound (preserves la satisfaisabilite). La resolution est le fondement logique de Prolog : chaque etape de Prolog est une resolution unitaire avec backtracking.</p>'
    '<p class="resume-text">Les demonstrateurs de theoremes modernes combinent resolution, paramodulation (gestion de l\'egalite), superposition (pour les theories equationnelles) et strategies de selection de clauses. Vampire utilise la saturation par clauses avec strategie d\'Age/Poids pour selectionner les clauses les plus prometteuses. E-prover (Schulz) utilise des heuristiques d\'apprentissage pour adapter sa strategie en cours de preuve. Ces systemes ont prouve des theoremes difficiles non triviaux : un lemme cle de la conjecture de Robbins (Prover9, 1996), des resultats de geometrie algebrique, et des theoremes combinatoires de la bibliotheque MIZAR.</p>'
    '<div class="highlight-box"><p><strong>Prolog et Herbrand :</strong> Prolog est literalement la methode d\'Herbrand implementee avec SLD-resolution (resolution lineaire selective descendante). La base de faits Prolog est l\'univers d\'Herbrand du probleme. La requete Prolog demande si une formule est une consequence logique de la base de faits via resolution. L\'unification au cœur de Prolog est exactement l\'algorithme de Robinson (1965), le meme qui generalisait la methode d\'Herbrand. Prolog est ainsi la realisation directe de soixante ans de logique mathematique (Herbrand 1930 → Robinson 1965 → Prolog 1972).</p></div>'
    '<h3>Extensions : theories de l\'egalite et superposition</h3>'
    '<p class="resume-text">La resolution standard ne gere pas efficacement l\'egalite. Le calcul de superposition (Bachmair et Ganzinger, 1990) etend la resolution a des theories equationnelles : les litteraux d\'egalite peuvent etre utilises pour remplacer des sous-termes, analogue a la congruence. La superposition est complete pour la logique du premier ordre avec egalite et sous-tend les demonstrateurs modernes (Vampire, E-prover). Elle permet de prouver des theoremes algebriques comme la commutativity-decidabilite dans les groupes abeliens ou des proprietes des anneaux commutatifs.</p>'
    '<p class="resume-text">La methode de Knuth-Bendix (1970) est une version orientee de la superposition pour les systemes de reecriture : elle complete un ensemble d\'equations en un systeme de reecriture convergent (confluent et terminant). Si elle reussit, le systeme de reecriture decide le probleme des mots dans l\'algebre presentee par les equations. La methode KBC fonde les demonstrateurs pour les theorie equationnelles et est implementee dans Maude, ACL2, et les systemes de verification de protocoles cryptographiques (Tamarin, ProVerif) qui verifient des proprietes de securite comme le secret de cle et l\'authenticite.</p>'
    '<div class="highlight-box"><p><strong>ProVerif et protocoles cryptographiques :</strong> ProVerif (Blanchet) utilise la resolution Horn clausale pour verifier automatiquement des proprietes de securite de protocoles comme TLS, SSH et OAuth. Il modelise le protocol comme un ensemble de clauses Prolog/Herbrand et verifie par resolution si un attaquant (Dolev-Yao) peut obtenir un secret. Des protocoles utilises par des milliards d\'utilisateurs quotidiennement ont ete verifies formellement avec cet outil, illustrant la chaine directe Herbrand (1930) → Resolution (1965) → securite du web (2020).</p></div>'
)

ENRICHMENTS['preuves-formelles/axiomatique'] = (
    '<h3>Le concept de systeme axiomatique</h3>'
    '<p class="resume-text">Un systeme axiomatique est defini par : (1) un langage formel (alphabet, regles syntaxiques), (2) des axiomes (formules acceptees sans demonstration), et (3) des regles d\'inference (schemas de derivation de nouvelles formules). Euclide (Ēlēments, ~300 av. J.-C.) proposa les cinq postulats de la geometrie euclidienne et tenta de deriver toutes les propositions geometriques a partir de ces seuls postulats. Ce programme, partiellement reussi, est le modele fondateur de la methode axiomatique — reproduit ensuite dans toutes les mathematiques modernes.</p>'
    '<p class="resume-text">Les proprietes desirees d\'un systeme axiomatique sont : la coherence (no ⊥ derivable), la completude (toute verite du domaine est prouvable), et l\'independance des axiomes (aucun axiome ne devrait etre prouvable depuis les autres). La coherence est vitale — un systeme incoherent permet de tout prouver (ex falso quodlibet). La completude est souhaitee mais, par le theoreme de Godel, impossible pour les systemes suffisamment forts. L\'independance permet de minimiser les axiomes — verifier si le cinquieme postulat d\'Euclide etait independant des quatre premiers motiva deux millenaires de geometrie.</p>'
    '<div class="highlight-box"><p><strong>Le cinquieme postulat :</strong> Le postulat des paralleles d\'Euclide (par un point exterieur a une droite, il passe exactement une parallele) parut toujours suspect — plus "theoreme" qu\'axiome. Des siecles de tentatives echouees de le deriver des quatre premiers postulats aboutirent, au XIXe siecle, a la decouverte des geometries non euclidiennes (Bolyai, Lobatchevski, Riemann) ou la negation du postulat est coherente. La geometrie de Riemann, ou aucune parallele n\'existe, decrit precisement la surface de la Terre et est fondamentale en relativite generale.</p></div>'
    '<h3>La crise des fondements et les grandes axiomatisations</h3>'
    '<p class="resume-text">Le XIXe siecle vit la revision critique des fondements. Weierstrass et Cantor formaliserent l\'analyse, eliminant les infinitesimaux intuitifs et fondant le calcul sur les nombres reels et les limites. Peano axiomatisa l\'arithmetique (1889) en cinq axiomes. Zermelo (1908) et Fraenkel axiomatiserent la theorie des ensembles (ZF), formalisant la base de toutes les mathematiques. Frege tenta de fonder l\'arithmetique sur la logique pure dans les Grundgesetze, mais le paradoxe de Russell montra que son axiome de comprehension illimitee etait incoherent. Ces crises conduisirent a la recherche d\'axiomatiques plus solides.</p>'
    '<p class="resume-text">Hilbert proposa son programme (1920) : formaliser toutes les mathematiques dans un systeme axiomatique finiste, puis prouver la coherence de ce systeme par des moyens finistes (sans appel a l\'infini actuel). La preuve de coherence de la geometrie euclidienne par Hilbert lui-meme (Grundlagen der Geometrie, 1899) fut un premier succes : la geometrie euclidienne est coherente si et seulement si l\'arithmetique des reels l\'est. Mais les theoremes de Godel (1931) montrerent que la coherence de l\'arithmetique ne peut pas etre prouvee finistement — detruisant la partie la plus ambitieuse du programme de Hilbert.</p>'
    '<div class="highlight-box"><p><strong>Geometrie euclidienne et reels :</strong> Hilbert prouva que la geometrie euclidienne est coherente si et seulement si l\'arithmetique des nombres reels l\'est — reduisant la coherence de la geometrie a celle de l\'algebre. Reciproquement, on peut modeliser les reels geometriquement (comme longueurs de segments). Cette equivalence fut un resultat majeur : les fondements de la geometrie et de l\'arithmetique sont les memes probleme, exhibant une profonde unite des mathematiques sous leur diversite superficielle.</p></div>'
    '<h3>Axiomatiques modernes et independance</h3>'
    '<p class="resume-text">L\'axiomatique ZFC est le standard actuel. Elle comprend : extensionnalite, paire, union, parties, infini, separation, fondation, remplacement, et choix. Chaque axiome a ete longuement debattu. L\'axiome de fondation (tout ensemble est bien fonde, pas de cycles x ∈ x) exclut les ensembles non-bien-fondes mais n\'est pas utilise en mathematiques ordinaires. Des variantes sans fondation (anti-fondation de Aczel) permettent de modeliser des systemes circulaires comme les flots de donnees infinis et les semantiques des langages de programmation recursifs.</p>'
    '<p class="resume-text">Cohen (1963) introduisit le forcing — une technique pour construire de nouveaux modeles de ZF en "forcant" certaines formules a etre vraies. Il prouva que l\'hypothese du continu (CH) est independante de ZFC : ni CH ni ¬CH ne sont prouvables dans ZFC. Le forcing est aujourd\'hui un outil universel en theorie des ensembles pour prouver des independances — de nouvelles independances sont decouverts chaque annee. Des questions comme "tout ensemble de reels est-il Lebesgue-mesurable ?" sont independantes de ZFC mais decidables dans des extensions standard (ZFC + "tous les ensembles sont mesurables" est coherente avec ZF sans Choix).</p>'
    '<div class="highlight-box"><p><strong>Forcing et ordinateurs :</strong> Une connexion surprenante relie le forcing de Cohen et la semantique des langages de programmation. La completion de Scott d\'un cpo (complete partial order) utilisee en denotationnel est formellement analogue a un forcing generique. Les modeles de la logique intuitioniste correspondent aux faisceaux sur une topologie, eux-memes un type de forcing. Ces connexions, developpees par Lawvere, Tierney et Lambek, fondent la semantique categorique des langages de programmation sur les memes structures logiques que la theorie des ensembles independantiste.</p></div>'
)

ENRICHMENTS['preuves-formelles/hilbert'] = (
    '<h3>Le programme de Hilbert : vision et ambition</h3>'
    '<p class="resume-text">Le programme de Hilbert (expose a la conference internationale des mathematiciens de 1900 et developpe dans les annees 1920) visait trois objectifs : (1) Formaliser toutes les mathematiques dans un systeme formel explicite. (2) Prouver la completude de ce systeme (toute verite mathematique y serait prouvable). (3) Prouver la coherence de ce systeme par des moyens "finistes" — des arguments ne faisant reference qu\'a des objets finis et des calculs finis, sans appel a l\'infini actuel. Ce programme repondait a la crise des fondements provoquee par les paradoxes de Russell et Burali-Forti.</p>'
    '<p class="resume-text">Hilbert n\'etait pas un naive formaliste qui croyait que les mathematiques etaient de pures manipulations de symboles. Il croyait que les mathematiques parlaient d\'une realite ideale, mais que leur securite devait etre etablie par la formalisation. Son slogan "Wir müssen wissen, wir werden wissen" (Nous devons savoir, nous saurons) exprimait un optimisme encyclopedique que Godel detruira en 1931. Pourtant, une grande partie du programme — la formalisation, les preuves de completude relative, les analyses de consistance de systemes fragments — survit et constitue la logique mathematique moderne.</p>'
    '<div class="highlight-box"><p><strong>Les problemes de Hilbert :</strong> En 1900, Hilbert formula 23 problemes qui dominerent le XXe siecle. Le 2eme (coherence de l\'arithmetique) fut resolu negativement par Godel. Le 10eme (algoritme pour les equations diophantines) fut resolu negativement par Matiyasevich (1970). Le 8eme (hypothese de Riemann) reste ouvert. Ces problemes ont guide une grande partie de la mathematique du XXe siecle — certains resolus, certains transforms, certains encore ouverts, tous feconds.</p></div>'
    '<h3>L\'arithmetique finiste et ses limites</h3>'
    '<p class="resume-text">La "finistique" de Hilbert designait un fragment des mathematiques acceptable par tous, indubitable : l\'arithmetique des nombres naturels finis, sans quantificateurs infinis sur les entiers. Hilbert esperait prouver la coherence de systemes plus forts (comme l\'arithmetique de Peano ou l\'analyse) a partir de raisonnements finistes. Ackermann et von Neumann prouveret partiellement ce programme pour des fragments de l\'arithmetique. Mais le second theoreme de Godel (1931) montra que PA ne peut pas prouver sa propre coherence — donc aucun systeme finiste contenu dans PA ne peut non plus, detruisant l\'espoir central du programme.</p>'
    '<p class="resume-text">Gentzen (1936) sauva une partie du programme en prouvant la coherence de PA par induction transfinite jusqu\'a ε₀ — un raisonnement transfini mais "acceptable" pour Gentzen car il portait sur des ordinaux bien ordonnes intuitivement comprehensibles. Cette preuve demontrait que PA est coherente si on accepte l\'induction jusqu\'a ε₀, quantifiant precisement ce que PA suppose "en plus" de la finistique. Elle fonda la theorie des ordres de preuve (proof theory), programme alternatif issu des ruines du programme de Hilbert original.</p>'
    '<div class="highlight-box"><p><strong>Buts et heritage :</strong> Bien que le programme de Hilbert dans sa forme originale ait echoue, il a engendre des disciplines entires : la logique mathematique (Godel, Church, Turing, Tarski), la theorie de la calculabilite, la theorie de la complexite, la theorie des demonstrateurs automatiques, et les assistants de preuve formelle. L\'echec du programme fut le succes de la logique : en cherchant des fondations definitives, Hilbert et ses successeurs decouvrirent les limites fondamentales de la formalisation — et ce faisant creerent les outils theoriques de l\'informatique moderne.</p></div>'
    '<h3>Heritage : epsilon-calcul et methodes de Hilbert</h3>'
    '<p class="resume-text">Hilbert developpa aussi le epsilon-calcul (1922) comme outil fondationnel. L\'operateur epsilon (ε) est un "operateur de choix indefini" : εx.φ(x) designe un element quelconque satisfaisant φ (s\'il en existe un). On peut alors eliminer les quantificateurs : ∃x φ(x) ≡ φ(εx.φ(x)) et ∀x φ(x) ≡ φ(εx.¬φ(x)). Les theoremes d\'elimination des epsilons de Hilbert montrent que si une formule sans epsilon est prouvable dans le systeme avec epsilon, elle est prouvable sans epsilon — une forme de conservativite. Cet operateur est utilise en logique des ressources et en informatique pour la specification des programmes avec conditions d\'existence.</p>'
    '<p class="resume-text">Le role de Hilbert comme fondateur de la logique moderne est paradoxal : son programme echoua dans ses ambitions les plus fortes, mais ses travaux (la formalisation rigoureuse, les preuves de coherence relative, les methodes de preuve theorique) formerent le langage meme dans lequel Godel formula ses theoremes d\'incompletude. Sans Hilbert, pas de programme a demontir — et les theoremes de Godel n\'auraient pas eu de cible formelle. Hilbert forma les conditions de possibilite de sa propre refutation, l\'un des cas les plus remarquables en histoire des mathematiques ou un programme echoue en creant quelque chose de plus grand encore.</p>'
    '<div class="highlight-box"><p><strong>Bourbaki et l\'heritage formel :</strong> Le groupe Bourbaki (Weil, Dieudonne, Cartan, et al., annees 1930-) entreprit de refonder les mathematiques sur des bases axiomatiques rigoureuses, dans l\'esprit de Hilbert. Leurs Elements de mathematique couvrent l\'algebre, l\'analyse, la topologie, la theorie des ensembles en un style axiomatique uniforme. Bien que critiques pour leur aridite et leur rejet de la geometrie intuitive, les Bourbaki ont defini le style formel de la mathematique du XXe siecle et influence l\'enseignement des mathematiques "modernes" dans le monde entier.</p></div>'
)

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
count = 0
for key, extra in ENRICHMENTS.items():
    if key in pages:
        old_len = len(pages[key]['content'])
        content = pages[key]['content']
        quiz_start = content.find('<section class="content-section" id="quiz">')
        if quiz_start != -1:
            pages[key]['content'] = content[:quiz_start] + extra + content[quiz_start:]
        else:
            idx = content.rfind('</section>')
            if idx != -1:
                pages[key]['content'] = content[:idx] + extra + content[idx:]
            else:
                pages[key]['content'] = content + extra
        new_len = len(pages[key]['content'])
        print(f"  {key}: {old_len} -> {new_len}")
        count += 1

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone: {count} articles enriched.")
