#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

PATH = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/logique.json'

def insert_before_quiz(content, extra):
    quiz_start = content.find('<section class="content-section" id="quiz">')
    if quiz_start != -1:
        return content[:quiz_start] + extra + content[quiz_start:]
    idx = content.rfind('</section>')
    if idx != -1:
        return content[:idx] + extra + content[idx:]
    return content + extra

ENRICHMENTS = {}

ENRICHMENTS['logique-propositionnelle/tables-verite'] = (
    '<h3>La méthode algorithmique de construction</h3>'
    '<p class="resume-text">Construire une table de vérité est un algorithme déterministe. Pour une formule à n variables, on liste toutes les 2ⁿ combinaisons en attribuant V et F dans un ordre canonique : la colonne la plus à gauche alterne tous les 2ⁿ⁻¹ lignes, la suivante tous les 2ⁿ⁻² lignes, jusqu\'à la dernière qui alterne V/F à chaque ligne. Pour évaluer (p → q) ∧ (q → r), on calcule d\'abord p → q et q → r colonne par colonne, puis leur conjonction. Cette décomposition rend la procédure vérifiable mécaniquement.</p>'
    '<p class="resume-text">L\'implication matérielle p → q n\'est fausse que lorsque p est vrai et q est faux. Cette définition correspond à la notion de promesse non trahie : si la condition n\'est pas remplie, la promesse ne peut pas être violée. Ainsi "si la Lune est en fromage, alors 2+2=5" est logiquement vraie — résultat contre-intuitif qui sépare la logique formelle de la causalité ordinaire et motiva le développement des logiques de pertinence au XXe siècle.</p>'
    '<div class="highlight-box"><p><strong>Exemple :</strong> Pour évaluer p → (q ∧ ¬p) avec p=V, q=V : d\'abord ¬p=F, puis q ∧ ¬p=F, puis V → F=F. Pour p=F, q=V : ¬p=V, q ∧ ¬p=V, F → V=V. La formule est vraie quand p est faux (quelle que soit q), fausse quand p est vrai et q est faux — une contingence typique.</p></div>'
    '<h3>Applications : circuits logiques et BDD</h3>'
    '<p class="resume-text">Les tables de vérité sont le fondement de l\'électronique numérique. Claude Shannon démontra en 1937 que l\'algèbre de Boole décrit exactement le comportement des circuits de relais électriques, fondant théoriquement la conception des ordinateurs. Chaque porte logique (AND, OR, NOT, NAND, XOR) est définie par sa table. Un circuit combinatoire quelconque peut être spécifié par sa table de vérité, puis implémenté via la forme normale disjonctive correspondante.</p>'
    '<p class="resume-text">Les diagrammes de décision binaire (BDD), inventés par Bryant en 1986, sont une représentation compacte des fonctions booléennes qui manipule implicitement des tables de vérité astronomiques. Une fonction à 30 variables nécessiterait plus d\'un milliard de lignes ; le BDD équivalent tient souvent en quelques milliers de nœuds en exploitant les sous-expressions communes. Cette technique est essentielle pour la vérification formelle de microprocesseurs modernes — sans elle, la vérification des processeurs actuels contenant des milliards de transistors serait impossible.</p>'
    '<div class="highlight-box"><p><strong>SAT et limite exponentielle :</strong> La satisfaisabilité propositionnelle (SAT) est NP-complet. Les solveurs modernes comme Z3 ou CaDiCaL utilisent l\'algorithme CDCL (Conflict-Driven Clause Learning) pour explorer intelligemment l\'espace des affectations sans construire la table complète. Ils résolvent des instances industrielles avec des millions de variables en quelques secondes, rendant possible la vérification de protocoles cryptographiques et la synthèse de circuits intégrés.</p></div>'
    '<h3>Simplification : tableaux de Karnaugh et Quine-McCluskey</h3>'
    '<p class="resume-text">La simplification de formules logiques consiste à trouver une formule plus courte avec la même table de vérité. Les tableaux de Karnaugh (1953) visualisent cette simplification pour 2 à 4 variables en arrangeant les mintermes de façon à faire apparaître les regroupements possibles. Pour une fonction vraie sur (V,V,F),(F,V,F),(V,V,V),(F,V,V), le tableau révèle immédiatement que f = q — la variable q suffit à décrire tous les cas vrais.</p>'
    '<p class="resume-text">Pour plus de variables, l\'algorithme de Quine-McCluskey (1956) systématise la recherche de l\'expression minimale en deux phases : trouver tous les implicants premiers (termes minimaux couvrant au moins un minterme), puis sélectionner un sous-ensemble minimum couvrant tous les mintermes. Ce problème de couverture est NP-dur mais crucial pour l\'optimisation des circuits intégrés. Les outils de synthèse VLSI modernes (Synopsys, Cadence) utilisent des variantes heuristiques pour optimiser automatiquement des millions de portes logiques en minimisant la surface de silicium et la consommation d\'énergie.</p>'
    '<div class="highlight-box"><p><strong>Karnaugh en pratique :</strong> Dans la conception des UAL (unités arithmétiques et logiques) des processeurs, une simplification de quelques portes par instance, multipliée par des milliards d\'instances, représente des économies significatives. Le premier processeur commercial à 4 bits, le Intel 4004 (1971), fut conçu à la main avec des tableaux de Karnaugh — une prouesse qui prit des mois. Aujourd\'hui, les outils EDA le feraient en quelques minutes.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/connecteurs-logiques'] = (
    '<h3>Sémantique formelle et fonctions de vérité</h3>'
    '<p class="resume-text">Chaque connecteur logique est une fonction de vérité. La négation est une fonction {V,F} → {V,F}. Les connecteurs binaires sont des fonctions {V,F}² → {V,F} : il en existe exactement 16 (2^4 valeurs d\'entrée, 2 valeurs de sortie chacune). Parmi celles-ci : la conjonction (∧), la disjonction (∨), l\'implication (→), le biconditionnel (↔) et la disjonction exclusive (XOR, ⊕). La XOR vérifie a ⊕ a = 0 et a ⊕ 0 = a, ce qui en fait l\'opération fondamentale du chiffrement symétrique : message ⊕ clé = chiffré, chiffré ⊕ clé = message.</p>'
    '<p class="resume-text">L\'implication matérielle p → q est vraie dès que p est faux — une promesse ne peut être trahie que si la condition est remplie. Les "paradoxes de l\'implication matérielle" (une implication avec prémisse fausse est toujours vraie) motivèrent les logiques de pertinence (Anderson, Belnap, années 1960), où une implication n\'est valide que si prémisse et conclusion partagent des variables, modélisant une dépendance causale ou informationnelle réelle.</p>'
    '<div class="highlight-box"><p><strong>XOR et AES :</strong> L\'algorithme AES (standard mondial de chiffrement depuis 2001) utilise XOR comme opération fondamentale dans sa couche AddRoundKey. La propriété de réversibilité parfaite — (a ⊕ b) ⊕ b = a — garantit que déchiffrement est l\'opération symétrique du chiffrement. Cette propriété algébrique découle directement de la table de vérité du connecteur logique, illustrant comment la logique fondamentale devient cryptographie pratique.</p></div>'
    '<h3>Complétude fonctionnelle et la barre de Sheffer</h3>'
    '<p class="resume-text">Un ensemble de connecteurs est fonctionnellement complet s\'il permet d\'exprimer les 16 fonctions binaires. L\'ensemble {¬, ∧} est complet : p ∨ q ≡ ¬(¬p ∧ ¬q) par De Morgan. De même {¬, ∨} et {→, ⊥}. Plus remarquable : le seul connecteur NAND (non-et, ↑, barre de Sheffer, 1913) est à lui seul fonctionnellement complet. On vérifie : ¬p ≡ p ↑ p ; p ∧ q ≡ (p ↑ q) ↑ (p ↑ q) ; p ∨ q ≡ (p ↑ p) ↑ (q ↑ q). La flèche de Pierce NOR est également seule complète.</p>'
    '<p class="resume-text">Ce résultat est directement exploité en électronique numérique. En CMOS, une porte NAND à 2 entrées nécessite 4 transistors contre 6 pour une porte AND — une économie de 33 % sur des milliards de portes. Un circuit quelconque peut être implémenté uniquement avec des NAND, et les compilateurs matériels (synthèse logique) utilisent cette propriété pour transformer des descriptions de haut niveau en netlists de portes élémentaires optimisées.</p>'
    '<div class="highlight-box"><p><strong>NAND universel :</strong> Les processeurs modernes contiennent des milliards de portes NAND. L\'Apple M3 (2023) contient environ 19 milliards de transistors. La complétude fonctionnelle de NAND signifie qu\'en principe, tout calcul possible peut être réalisé avec ce seul connecteur physique — un exemple saisissant où un théorème de logique mathématique (1913) guide directement la réalité physique du silicium (2023).</p></div>'
    '<h3>Connecteurs non classiques : modalités et plurivalence</h3>'
    '<p class="resume-text">La logique modale introduit □ (nécessairement) et ◇ (possiblement), interprétables dans les structures de Kripke — ensembles de mondes possibles avec une relation d\'accessibilité. Selon les contraintes sur cette relation (réflexivité T, transitivité 4, symétrie B), on obtient les systèmes K, T, S4, S5. La logique temporelle (Clarke, Emerson, 1981) ajoute G (toujours), F (finalement), U (jusqu\'à) pour spécifier des propriétés de systèmes concurrents, fondant la vérification formelle de protocoles.</p>'
    '<p class="resume-text">Les logiques plurivalentes enrichissent l\'ensemble des valeurs de vérité. Łukasiewicz (1920) introduit une troisième valeur "indéterminé". La logique floue (Zadeh, 1965) autorise des degrés continus dans [0,1] avec ∧ = min, ∨ = max, ¬p = 1-p. Ces connecteurs flous modélisent des concepts gradués (grand, chaud, rapide) et trouvent des applications en régulation industrielle (trains Shinkansen, lave-linge intelligents), en vision par ordinateur et dans les systèmes experts médicaux où les diagnostics sont naturellement probabilistes.</p>'
    '<div class="highlight-box"><p><strong>CTL et vérification de circuits :</strong> La logique arborescente CTL est utilisée pour vérifier des processeurs entiers. Après le bug FDIV du Pentium (1994) qui coûta 475 millions de dollars à Intel, les fabricants adoptèrent la vérification formelle par model checking CTL. Des formules comme AG(¬deadlock) — "jamais de deadlock dans aucun état futur" — sont vérifiées automatiquement sur des modèles comportementaux du processeur avant fabrication.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/tautologies'] = (
    '<h3>Tautologies fondamentales et règles d\'inférence</h3>'
    '<p class="resume-text">Les tautologies classiques constituent le répertoire des vérités logiques universelles. Le tiers exclu (p ∨ ¬p), la non-contradiction ¬(p ∧ ¬p), le modus ponens ((p ∧ (p→q)) → q), le modus tollens ((¬q ∧ (p→q)) → ¬p), le syllogisme hypothétique ((p→q) ∧ (q→r)) → (p→r), et le dilemme constructif sont les outils fondamentaux du raisonnement déductif. Chacune correspond à une règle d\'inférence que les mathématiciens utilisent spontanément depuis Aristote.</p>'
    '<p class="resume-text">Le théorème de déduction établit le lien crucial entre sémantique et syntaxe : A ⊢ B (B est dérivable depuis A) si et seulement si ⊢ A → B (l\'implication est une tautologie). Ce théorème transforme des questions sur la déducibilité en questions sur les tautologies, et réciproquement. Il permet de raisonner "sous hypothèse" en logique formelle, correspondant exactement à la pratique mathématique habituelle : "Supposons A. Alors B. Donc A implique B."</p>'
    '<div class="highlight-box"><p><strong>Modus ponens et algorithmes :</strong> Le modus ponens est à la base de tout moteur d\'inférence. Le moteur Prolog, les systèmes experts médicaux (MYCIN, 1970s), et les moteurs de règles des systèmes ERP appliquent tous itérativement le modus ponens : si "patient a fièvre" et "fièvre → suspicion d\'infection", conclure "suspicion d\'infection". La chaîne avant (forward chaining) et la chaîne arrière (backward chaining) sont deux stratégies d\'application systématique de cette tautologie fondamentale.</p></div>'
    '<h3>Caractérisation algorithmique des tautologies</h3>'
    '<p class="resume-text">Décider si une formule propositionnelle est une tautologie est co-NP-complet : on peut vérifier en temps polynomial qu\'une affectation la rend fausse (certificat de non-tautologie), mais on ne connaît pas d\'algorithme polynomial général pour prouver la tautologie. La méthode des tableaux sémantiques (Beth, Hintikka, années 1950) tente de construire un modèle de ¬φ : si tous les chemins de l\'arbre aboutissent à des contradictions (branches fermées), φ est une tautologie.</p>'
    '<p class="resume-text">La résolution (Robinson, 1965) offre une autre approche : convertir ¬φ en FNC et dériver la clause vide par résolution. Les solveurs SAT modernes (MiniSat, CaDiCaL, Z3) avec l\'algorithme CDCL (Conflict-Driven Clause Learning) résolvent ces problèmes sur des instances industrielles. Introduit dans GRASP (1996) et Chaff (2001), CDCL apprend des "clauses de conflit" lors du backtracking pour ne jamais revisiter les mêmes contradictions — une amélioration décisive qui transforma le SAT de problème académique en outil industriel.</p>'
    '<div class="highlight-box"><p><strong>Complétude vs incomplétude de Gödel :</strong> Ces deux théorèmes semblent contradictoires mais parlent de choses différentes. La complétude (1930) dit que toute vérité logique universelle (valide dans toutes les structures) est prouvable. L\'incomplétude (1931) dit que certaines vérités arithmétiques (vraies dans ℕ) ne sont pas prouvables dans PA. L\'un porte sur la validité universelle, l\'autre sur la vérité dans un modèle spécifique — deux notions fondamentalement distinctes.</p></div>'
    '<h3>Tautologies et fondements axiomatiques</h3>'
    '<p class="resume-text">Les systèmes axiomatiques de la logique propositionnelle cherchent à dériver toutes les tautologies à partir d\'un petit nombre d\'axiomes via le seul modus ponens. Łukasiewicz découvrit en 1924 un système à trois axiomes suffisant pour toute la logique classique, démontrant l\'extraordinaire économie des fondements logiques. La complétude de ces systèmes — toute tautologie est démontrable — fut prouvée par Post (1921). Cette correspondance entre tautologies et théorèmes est la forme la plus simple de la complétude de Gödel.</p>'
    '<p class="resume-text">En pratique mathématique, les tautologies servent d\'outils de transformation : p → q ≡ ¬q → ¬p (contraposée) permet de changer de stratégie de démonstration ; ¬∃x P(x) ≡ ∀x ¬P(x) permet de reformuler une négation existentielle. Ces équivalences tautologiques sont les "règles de simplification" du raisonnement formel, utilisées aussi bien par les mathématiciens humains que par les assistants de preuve automatiques comme Coq, Lean ou Isabelle.</p>'
    '<div class="highlight-box"><p><strong>Prouveurs de théorèmes :</strong> L\'assistant de preuve Lean 4 a formalisé la majorité des résultats du livre "Analyse" de Rudin, produisant des preuves mécaniquement vérifiées de théorèmes de calcul différentiel et intégral. Chaque pas de ces preuves est une application d\'une tautologie ou d\'une règle d\'inférence — démontrant que les mathématiques peuvent être entièrement réduites à la manipulation formelle de symboles selon des règles logiques précises.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/formes-normales'] = (
    '<h3>FNC, FND et construction systématique</h3>'
    '<p class="resume-text">Toute formule propositionnelle est transformable en Forme Normale Conjonctive (FNC — conjonction de clauses disjonctives) ou en Forme Normale Disjonctive (FND — disjonction de termes conjonctifs). L\'algorithme en trois étapes : (1) éliminer biconditionnels et implications (p ↔ q ≡ (p→q) ∧ (q→p), p → q ≡ ¬p ∨ q), (2) pousser les négations vers les atomes via De Morgan et double négation, (3) distribuer ∧ sur ∨ pour FNC ou ∨ sur ∧ pour FND. Le résultat est une forme standardisée équivalente à la formule initiale.</p>'
    '<p class="resume-text">La FND canonique (mintermes) se lit directement sur la table de vérité : chaque ligne vraie contribue un terme — conjonction des variables, positivement si vraies dans cette ligne, négativement sinon. Pour f(p,q,r) vraie uniquement sur (V,V,F) et (F,V,V), la FND canonique est (p ∧ q ∧ ¬r) ∨ (¬p ∧ q ∧ r). Cette représentation est unique et universelle : toute fonction booléenne a une FND canonique déterminée par sa table, permettant une correspondance bijective entre fonctions et expressions normalisées.</p>'
    '<div class="highlight-box"><p><strong>Explosion combinatoire :</strong> La distribution naïve pour obtenir la FNC peut produire une formule exponentiellement plus longue. La formule (p₁∧q₁) ∨ (p₂∧q₂) ∨ … ∨ (pₙ∧qₙ) nécessite de distribuer 2ⁿ fois, produisant 2ⁿ clauses. Pour n=20, plus d\'un million de clauses pour une formule de départ de taille linéaire — d\'où l\'importance cruciale de la transformation de Tseitin pour les applications industrielles.</p></div>'
    '<h3>Transformation de Tseitin et SAT industriel</h3>'
    '<p class="resume-text">La transformation de Tseitin (1968) convertit n\'importe quelle formule en FNC équisatisfaisable (même ensemble de modèles) en temps et espace linéaires. Pour chaque sous-formule φᵢ, on introduit une variable fraîche xᵢ et des clauses de définition : xᵢ ↔ (définition de φᵢ). Par exemple, pour φᵢ = (a ∧ b), on ajoute les clauses (¬xᵢ ∨ a), (¬xᵢ ∨ b), (xᵢ ∨ ¬a ∨ ¬b) — encodant xᵢ ↔ (a ∧ b) en trois clauses de taille 3.</p>'
    '<p class="resume-text">Cette transformation est la porte d\'entrée de tous les solveurs SAT industriels. Toute vérification formelle (model checking), toute planification combinatoire, tout problème de contraintes soumis à un solveur passe par la mise en FNC Tseitin. Le solveur opère ensuite via CDCL : lors d\'une contradiction, il apprend une clause de conflit et effectue un backtrack non chronologique. Introduit dans GRASP (1996) et Chaff (2001), CDCL transforma le SAT de problème académique en outil industriel standard.</p>'
    '<div class="highlight-box"><p><strong>SAT et vérification matérielle :</strong> Après le bug FDIV du Pentium en 1994 (475 M$ de coût), Intel adopta la vérification formelle. Bounded Model Checking (Biere et al., 1999) encode la vérification de propriétés sur k pas de temps comme un problème SAT via Tseitin — prouvant l\'absence de bugs dans des processeurs contenant des milliards de transistors. Aujourd\'hui, aucun microprocesseur majeur n\'est fabriqué sans vérification formelle extensive.</p></div>'
    '<h3>Formes normales en logique du premier ordre</h3>'
    '<p class="resume-text">La forme prénexe du premier ordre place tous les quantificateurs en préfixe : (Q₁x₁)…(Qₙxₙ) φ où φ est sans quantificateurs (matrice). L\'obtenir requiert parfois de renommer des variables liées pour éviter les captures. La hiérarchie de Chomsky classe les formules prénexes par leur préfixe quantificationnel : Σ₁ (une alternance ∃∀), Π₁ (une alternance ∀∃), Σ₂ (deux alternances), etc. Cette hiérarchie correspond à la hiérarchie arithmétique de la calculabilité.</p>'
    '<p class="resume-text">La forme de Skolem élimine les quantificateurs existentiels en les remplaçant par des fonctions de Skolem appliquées aux variables universelles précédentes : ∀x∃y R(x,y) devient ∀x R(x,f(x)). La formule skolémisée est équisatisfaisable mais pas équivalente. La méthode d\'Herbrand ramène alors la satisfaisabilité du premier ordre à celle de clauses ground : si la formule skolémisée est insatisfaisable, un sous-ensemble fini de clauses ground l\'est, détectable par SAT. Cette approche fonde les démonstrateurs automatiques de théorèmes modernes comme Vampire et E-prover.</p>'
    '<div class="highlight-box"><p><strong>Démonstrateurs automatiques :</strong> Le prouveur Vampire a résolu des milliers de théorèmes de la bibliothèque Mizar, parfois avec des preuves plus courtes que les originales humaines. Il combine résolution sur formules skolémisées, stratégies de sélection de clauses, et inférence superposition. En 2019, un démonstrateur automatique (DeepMath, Google) a utilisé l\'apprentissage profond pour guider la sélection de lemmes, atteignant des performances comparables aux mathématiciens humains sur des problèmes de niveau olympiades.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/propositions'] = (
    '<h3>Grammaire formelle et induction structurelle</h3>'
    '<p class="resume-text">Le langage de la logique propositionnelle est défini inductivement. Les formules atomiques sont les variables (p, q, r, …) et les constantes ⊤ (vrai) et ⊥ (faux). Si φ et ψ sont des formules, alors ¬φ, (φ ∧ ψ), (φ ∨ ψ), (φ → ψ) et (φ ↔ ψ) sont des formules. Cette définition récursive est non-ambiguë et se code directement comme un arbre de syntaxe abstraite (AST). L\'induction structurelle permet de prouver des propriétés pour toutes les formules : vérifier pour les atomes, puis montrer la préservation par chaque connecteur.</p>'
    '<p class="resume-text">La notion de sous-formule se définit de même inductivement. Le rang d\'une formule mesure la profondeur de l\'AST. La propriété de sous-formule — centrale dans le Hauptsatz de Gentzen — garantit que les preuves en coupure-libre n\'introduisent que des sous-formules de la conclusion. Ces notions récursives permettent des raisonnements par induction sur la complexité structurelle, technique omniprésente en sémantique des langages de programmation et en théorie des types.</p>'
    '<div class="highlight-box"><p><strong>Induction structurelle et compilation :</strong> Les compilateurs modernes sont construits sur l\'induction structurelle. La génération de code pour une expression (a+b)*c procède inductivement : générer le code de a, puis de b, puis leur addition, puis multiplier par c. Chaque passe du compilateur (analyse sémantique, optimisation, génération de code) est une fonction récursive sur l\'AST du programme — directement l\'induction structurelle de la logique formelle appliquée à l\'ingénierie logicielle.</p></div>'
    '<h3>Histoire : de Boole à Shannon</h3>'
    '<p class="resume-text">La logique propositionnelle formelle a des racines stoïciennes (Chrysippe, IIIe s. av. J.-C.) mais sa formalisation moderne commence avec George Boole (1847, 1854), qui développa l\'algèbre des propositions en montrant la correspondance entre logique et calcul algébrique. Gottlob Frege, dans son Begriffsschrift (1879), créa le premier système formel complet avec quantificateurs et inférence rigoureuse. Russell et Whitehead tentatèrent dans les Principia Mathematica (1910-1913) de fonder toutes les mathématiques sur la logique — entreprise titanesque limitée par les paradoxes ensemblistes.</p>'
    '<p class="resume-text">Claude Shannon ferma la boucle en 1937 : sa thèse de master démontra que l\'algèbre de Boole décrit exactement les circuits de relais électriques à deux états. Cette réalisation — la logique abstraite de Boole devient physiquement implémentable — fonda l\'informatique numérique. Shannon avait 21 ans. C\'est probablement la thèse de master la plus influente de l\'histoire de l\'ingénierie : les ordinateurs actuels, des smartphones aux supercalculateurs, sont des réalisations physiques de la logique propositionnelle de Boole à travers les circuits de Shannon.</p>'
    '<div class="highlight-box"><p><strong>De la logique au silicium :</strong> La chaîne Boole (1854) → Frege (1879) → Shannon (1937) → Intel 4004 (1971) → Apple M3 (2023) illustre comment une abstraction mathématique devient, en moins de 170 ans, une technologie présente dans chaque poche. L\'Apple M3 contient 19 milliards de transistors réalisant des opérations booléennes à 3 GHz — 57 milliards d\'opérations logiques par seconde sur les fonctions définies par Boole en 1854.</p></div>'
    '<h3>Interprétation, satisfaction et compacité</h3>'
    '<p class="resume-text">Une interprétation v : Var → {V,F} assigne une valeur de vérité à chaque variable et s\'étend aux formules composées par les tables de vérité des connecteurs. Un ensemble Γ de formules est satisfaisable si une interprétation satisfait toutes ses formules simultanément. La conséquence logique Γ ⊨ φ signifie que toute interprétation satisfaisant Γ satisfait aussi φ — φ est "contenu informationnel" de Γ.</p>'
    '<p class="resume-text">Le théorème de compacité affirme que si tout sous-ensemble fini de Γ est satisfaisable, alors Γ est satisfaisable. Pour les ensembles finis, c\'est trivial ; pour les infinis, c\'est profond. La compacité du premier ordre permet de construire des modèles non standards des réels : Abraham Robinson (1960) ajouta des constantes représentant des infinitésimaux et utilisa la compacité pour prouver leur existence — réhabilitant rigoureusement les infinitésimaux de Leibniz et fondant l\'analyse non standard, logiquement équivalente à l\'analyse classique.</p>'
    '<div class="highlight-box"><p><strong>Compacité et graphes infinis :</strong> Le théorème de compacité prouve König : tout graphe infini et connexe ayant une quantité finie de sommets de degré infini contient un chemin infini. La preuve : pour chaque n, il existe un chemin de longueur n (satisfaisabilité des sous-ensembles finis). Par compacité, il existe un chemin infini. Sans la compacité, raisonner sur des structures infinies par des propriétés finies serait impossible — la compacité est l\'outil qui relie le fini à l\'infini en logique.</p></div>'
)

ENRICHMENTS['logique-predicats/quantificateurs'] = (
    '<h3>Sémantique de Tarski et structures formelles</h3>'
    '<p class="resume-text">La sémantique formelle des quantificateurs est définie par Tarski (1933) dans une structure M = (D, I) où D est le domaine et I interprète les symboles. La formule ∀x φ(x) est vraie si φ est satisfaite pour toute valeur d dans D. La formule ∃x φ(x) est vraie si au moins un élément satisfait φ. Cette définition récursive de la satisfaction est le fondement de toute la sémantique mathématique moderne — elle définit précisément ce que signifie "être vrai dans un modèle".</p>'
    '<p class="resume-text">L\'ordre des quantificateurs détermine le sens. ∀x∃y (y > x) est vrai dans ℝ (pour tout réel, il en existe un plus grand), mais ∃y∀x (y > x) est faux (pas de plus grand réel). La continuité est ∀ε>0 ∃δ>0 ∀x (|x-x₀|<δ → |f(x)-f(x₀)|<ε) tandis que l\'uniforme continuité est ∀ε>0 ∃δ>0 ∀x∀x₀ (|x-x₀|<δ → |f(x)-f(x₀)|<ε). La seule différence — ∃δ précède ∀x₀ — exprime que δ ne dépend pas du point, une distinction cruciale qui distingue la rectifiabilité locale de la globale.</p>'
    '<div class="highlight-box"><p><strong>Quantificateurs et calcul différentiel :</strong> Toutes les définitions fondamentales de l\'analyse reposent sur l\'ordre des quantificateurs. La définition d\'une limite : ∀ε>0 ∃δ>0 ∀x (0<|x-a|<δ → |f(x)-L|<ε). Riemann définit l\'intégrale via ∀ε>0 ∃δ>0 ∀(subdivisions de pas < δ) (|somme - I|<ε). Ces formules du premier ordre, incomprises par les étudiants au XIXe siècle, ont été rendues transparentes par la logique formelle du XXe siècle.</p></div>'
    '<h3>Logique du premier ordre : expressivité et théorèmes fondamentaux</h3>'
    '<p class="resume-text">La logique du premier ordre (LPO) quantifie sur les individus mais pas sur les ensembles ou prédicats. Elle formalise l\'arithmétique de Peano, la théorie des groupes, la géométrie euclidienne. Mais certaines propriétés lui échappent : la fermeture transitive d\'une relation, la finitude d\'un domaine, l\'existence d\'un nombre infini d\'éléments satisfaisant P — ces notions requièrent la logique du second ordre ou des infinités d\'axiomes. La décidabilité varie : la LPO sur les structures ordonnées des réels (théorie de Tarski) est décidable, mais la LPO sur l\'arithmétique est indécidable (Church 1936).</p>'
    '<p class="resume-text">Le théorème de Löwenheim-Skolem révèle que la LPO ne peut pas caractériser la cardinalité : toute théorie avec un modèle infini a des modèles de toute cardinalité infinie. On ne peut donc pas axiomatiser les réels en LPO sans modèles non standards. Abraham Robinson (1960) exploita cette propriété pour construire l\'analyse non standard : via la compacité, il construisit des extensions *ℝ contenant des infinitésimaux ε > 0 tels que ε < 1/n pour tout entier standard n, réhabilitant rigoureusement les intuitions de Leibniz.</p>'
    '<div class="highlight-box"><p><strong>Skolem paradoxale :</strong> Par Löwenheim-Skolem descendant, la théorie ZF de l\'ensemble de Cantor a un modèle dénombrable. Pourtant, ZF prouve que ℝ est non dénombrable. Le "paradoxe" de Skolem : dans ce modèle dénombrable, ℝ est "non dénombrable" au sens où il n\'existe pas de bijection entre ℝ et ℕ dans ce modèle — même si de l\'extérieur, les deux ensembles sont dénombrables. La non-dénombrabilité est relative au modèle, pas absolue — une leçon profonde sur les limites de la formalisation.</p></div>'
    '<h3>Quantificateurs généralisés et traitement du langage</h3>'
    '<p class="resume-text">Les quantificateurs ∀ et ∃ ne capturent pas toutes les quantifications naturelles. "La plupart des étudiants ont réussi", "exactement trois personnes étaient présentes" ne s\'expriment pas directement en LPO. Les quantificateurs généralisés (Mostowski 1957, Barwise et Cooper 1981) formalisent : Q_n (au moins n), Q_maj (la plupart = |A∩B| > |A\B|), Q_inf (infiniment de). En sémantique formelle (grammaire de Montague), les déterminants sont des relations entre ensembles : "tout étudiant réussit" = Étudiants ⊆ Réussites.</p>'
    '<p class="resume-text">L\'ambiguïté de portée des quantificateurs est un problème central en traitement automatique du langage. "Chaque étudiant lit un livre" a deux lectures : ∀x∃y (étudiant(x) → lit(x,y)) — chacun lit un livre différent — ou ∃y∀x (étudiant(x) → lit(x,y)) — un même livre pour tous. Les grands modèles de langage (GPT-4, Claude) apprennent implicitement ces distinctions à partir de corpus textuels, mais leurs représentations internes ne correspondent pas directement aux formules du premier ordre — une question ouverte en interprétabilité.</p>'
    '<div class="highlight-box"><p><strong>Sémantique compositionnelle :</strong> La grammaire de Montague (1970) propose que le sens d\'une phrase se compose compositionnellement à partir du sens de ses parties, suivant la structure syntaxique. "Tout homme qui aime une femme la voit" se traduit en une formule du premier ordre via des règles d\'homomorphisme entre syntaxe et sémantique. Ce programme inspire les représentations sémantiques des NLP modernes et les bases de connaissances (Freebase, Wikidata).</p></div>'
)

ENRICHMENTS['logique-predicats/variables-termes'] = (
    '<h3>Syntaxe formelle : termes et formules atomiques</h3>'
    '<p class="resume-text">En logique du premier ordre, les termes désignent des individus. Ils se forment inductivement : les variables (x, y, z) et constantes (a, b, c) sont des termes ; si t₁,…,tₙ sont des termes et f est un symbole de fonction n-aire, alors f(t₁,…,tₙ) est un terme. Dans l\'arithmétique, s(0) désigne le successeur de 0, +(s(0), s(s(0))) désigne 1+2 en notation préfixe. Les formules atomiques sont R(t₁,…,tₙ) pour un prédicat R et des termes tᵢ. Les formules complexes se construisent par connecteurs et quantificateurs.</p>'
    '<p class="resume-text">La distinction terme clos/terme ouvert est fondamentale. Un terme clos ne contient pas de variables libres (f(a,b) désigne un individu déterminé) ; un terme ouvert contient des variables (f(x,b) désigne une famille d\'individus paramétrés). Seuls les termes clos peuvent être directement interprétés dans une structure ; les termes ouverts nécessitent une assignation de valeurs aux variables. Cette distinction se retrouve en programmation : les expressions sans variables libres (termes clos) sont des constantes, les expressions avec variables libres sont des fonctions.</p>'
    '<div class="highlight-box"><p><strong>Signature et langage :</strong> Une signature L = (F, R, a) spécifie les symboles de fonctions F, de relations R, et leurs arités a. L\'arithmétique de Peano utilise L = ({0, s, +, ×}, {=}, {0,1,2,2}). La théorie des groupes utilise L = ({e, ·, ⁻¹}, {=}, {0,2,1}). Changer la signature change le langage — certaines propriétés exprimables dans un langage peuvent être inexprimables dans un autre, même pour la même structure mathématique.</p></div>'
    '<h3>Substitution, capture de variables et alpha-équivalence</h3>'
    '<p class="resume-text">La substitution φ[t/x] — remplacer x par le terme t dans φ — doit éviter la capture de variables liées. Si φ = ∀y R(x,y) et t = y, la substitution naïve donne ∀y R(y,y), perdant le sens original. Une substitution est libre pour x dans φ si aucune variable de t n\'est dans la portée d\'un quantificateur liant cette variable dans φ. Sinon, on renomme d\'abord les variables liées (alpha-conversion) avant de substituer — une procédure garantissant la correction sémantique.</p>'
    '<p class="resume-text">L\'alpha-équivalence identifie les formules ne différant que par le nom de leurs variables liées : ∀x P(x) et ∀y P(y) sont alpha-équivalentes et représentent la même affirmation. Dans les langages de programmation fonctionnelle, cela correspond au renaming des paramètres formels : (λx.x+1) est alpha-équivalente à (λy.y+1). Les indices de De Bruijn éliminent ce problème en remplaçant les variables par leur distance au quantificateur liant : λ.λ.(1 0) représente λx.λy.(x y). Coq, Lean et la plupart des assistants de preuve utilisent cette représentation en interne.</p>'
    '<div class="highlight-box"><p><strong>Indices de De Bruijn :</strong> La représentation de De Bruijn (1972) remplace les noms de variables par des indices numériques indiquant la distance au quantificateur liant. Elle élimine totalement les problèmes d\'alpha-équivalence et de capture au prix d\'une lisibilité réduite. Le kernel de Coq, visant la certification maximale, utilise cette représentation car elle simplifie les preuves de correction du substituteur et du vérificateur de types.</p></div>'
    '<h3>Unification et ses applications en informatique</h3>'
    '<p class="resume-text">L\'unification est le problème de trouver une substitution θ rendant deux termes identiques : θ(t₁) = θ(t₂). f(x,b) et f(a,y) s\'unifient avec θ = {x↦a, y↦b}. L\'algorithme d\'unification de Robinson (1965) calcule l\'unificateur le plus général (mgu), unique à renommage près. Deux termes ne s\'unifient pas si leurs têtes sont des fonctions différentes : f(x) et g(y) sont non unifiables. La complexité de l\'unification est quasi-linéaire via l\'algorithme de Paterson-Wegman (1978) utilisant une structure union-find.</p>'
    '<p class="resume-text">L\'unification est au cœur de la programmation logique (Prolog) et de l\'inférence de types en programmation fonctionnelle. En Prolog, chaque étape de résolution unifie la tête du but courant avec la tête d\'une clause : pere(tom,bob) s\'unifie avec pere(X,Y) via {X↦tom, Y↦bob}. En Haskell et ML, l\'algorithme W de Milner (1978) utilise l\'unification pour inférer le type le plus général d\'une expression — identique mathématiquement à l\'unification de Robinson mais appliqué aux types au lieu des termes.</p>'
    '<div class="highlight-box"><p><strong>Prolog et intelligence artificielle :</strong> Prolog fut développé par Alain Colmerauer et Robert Kowalski au début des années 1970. Son moteur résout des requêtes par résolution-unification récursive avec backtracking. Il fut adopté comme langage officiel du projet japonais de 5ème génération (1982-1992), visant la création d\'une IA avancée via la programmation logique. Bien que le projet n\'ait pas atteint ses objectifs, il stimula la recherche en IA et en bases de données déductives, dont des descendants directs alimentent aujourd\'hui les moteurs de recommandation.</p></div>'
)

ENRICHMENTS['preuves-formelles/recurrence'] = (
    '<h3>Fondements mathématiques du principe de récurrence</h3>'
    '<p class="resume-text">Le principe de récurrence (induction mathématique) est un axiome des entiers naturels, présent dans les axiomes de Peano (1889) : si P(0) est vraie, et si pour tout n, P(n) implique P(n+1), alors P(n) est vraie pour tout n. Ce principe est équivalent au principe du bon ordre : tout ensemble non vide d\'entiers naturels a un plus petit élément. Ces deux principes sont mutuellement démontrables dans ZF mais ne sont pas démontrables à partir de la seule logique du premier ordre sans axiome spécifique sur les naturels.</p>'
    '<p class="resume-text">L\'induction forte (ou complète) suppose P(k) pour tout k < n pour prouver P(n) — équivalente logiquement à l\'induction simple mais souvent plus commode. L\'induction transfinite étend le principe aux ensembles bien ordonnés de toute cardinalité : si P est vraie pour 0, pour tout successeur α+1 dès que vraie pour α, et pour toute limite λ dès que vraie pour tout α < λ, alors P est vraie pour tout ordinal. Gentzen (1936) utilisa l\'induction transfinite jusqu\'à ε₀ pour prouver la cohérence de l\'arithmétique de Peano — prouvant que PA est cohérente dans un méta-système légèrement plus fort.</p>'
    '<div class="highlight-box"><p><strong>Récurrence et terminaison :</strong> Prouver qu\'un programme termine revient à exhiber un variant — une quantité à valeurs dans un ensemble bien ordonné qui décroît strictement à chaque étape. Pour le tri fusion, le variant est la taille de la liste traitée. Pour l\'algorithme d\'Euclide, c\'est le plus petit des deux entiers. Le bien ordre des entiers naturels garantit que toute décroissance stricte est finie, prouvant la terminaison sans analyse cas par cas.</p></div>'
    '<h3>Variantes : récurrence structurelle et coinduction</h3>'
    '<p class="resume-text">La récurrence structurelle étend le principe aux données définies inductivement : listes, arbres, formules logiques. Pour prouver P de toutes les listes, il suffit de prouver P([]) et que P(liste) implique P(x::liste). Cette généralisation est fondamentale en programmation fonctionnelle : les preuves de propriétés des programmes suivent la structure récursive des programmes eux-mêmes. En Coq et Lean, les preuves par récurrence structurelle sont automatisées par la tactique induction qui génère les sous-buts correspondant à chaque constructeur.</p>'
    '<p class="resume-text">La coinduction est le dual de l\'induction, applicable aux structures potentiellement infinies (flots, processus). Là où l\'induction prouve qu\'une propriété est maintenue en construisant de bas en haut, la coinduction prouve des propriétés de structures infinies de haut en bas : un flot satisfait P si sa tête satisfait P₀ et sa queue satisfait P récursivement. La bisimulation — deux processus sont bisimilaires si chaque action de l\'un peut être imitée par l\'autre à l\'infini — est une propriété coinductive centrale dans la sémantique des systèmes concurrents (CCS de Milner, pi-calcul).</p>'
    '<div class="highlight-box"><p><strong>Coinduction en Coq :</strong> L\'assistant Coq supporte la coinduction pour raisonner sur des flots infinis. On peut définir le flot des nombres naturels (0,1,2,…) et prouver coinductivement que tous ses éléments sont distincts. Cette technique est utilisée pour vérifier des protocoles à durée indéterminée comme TLS/HTTPS : la propriété "la session reste sécurisée tant qu\'elle dure" est une assertion coinductive sur un flot potentiellement infini de messages.</p></div>'
    '<h3>Récurrence et complexité algorithmique</h3>'
    '<p class="resume-text">Les relations de récurrence décrivent la complexité des algorithmes diviser-pour-régner. Le tri fusion vérifie T(n) = 2T(n/2) + O(n). Le théorème maître (Cormen et al., CLRS) résout ces récurrences selon la relation entre f(n) et n^(log_b a) : si f(n) = O(n^(log_b a - ε)), alors T(n) = Θ(n^(log_b a)) ; si égaux, T(n) = Θ(n^(log_b a) log n) ; si f(n) = Ω(n^(log_b a + ε)), alors T(n) = Θ(f(n)). Pour le tri fusion : a=2, b=2, log_2(2)=1, f(n)=n — cas 2, donc T(n) = Θ(n log n).</p>'
    '<p class="resume-text">La méthode d\'Akra-Bazzi généralise le théorème maître aux récurrences asymétriques T(n) = Σ aᵢ T(n/bᵢ) + f(n). L\'algorithme de Strassen pour la multiplication matricielle vérifie T(n) = 7T(n/2) + O(n²), donnant T(n) = O(n^(log_2 7)) ≈ O(n^2.807) — meilleur que l\'O(n³) naïf. L\'algorithme de Karatsuba (multiplication d\'entiers) vérifie T(n) = 3T(n/2) + O(n), donnant O(n^(log_2 3)) ≈ O(n^1.585) au lieu de O(n²). Ces analyses révèlent des algorithmes fondamentalement plus efficaces grâce au raisonnement récursif.</p>'
    '<div class="highlight-box"><p><strong>Séquence de Goodstein et incomplétude :</strong> La séquence de Goodstein démarre depuis n=4 et croît pendant des milliards d\'étapes avant d\'atteindre 0. Ce fait est vrai dans les naturels mais non prouvable dans l\'arithmétique de Peano — il requiert l\'induction transfinie jusqu\'à ε₀. C\'est l\'exemple le plus accessible d\'un résultat combinatoire naturel indécidable dans PA, illustrant concrètement les théorèmes d\'incomplétude de Gödel au-delà des phrases autoréférentielles artificielles.</p></div>'
)

ENRICHMENTS['preuves-formelles/absurde'] = (
    '<h3>Fondements logiques de la réduction à l\'absurde</h3>'
    '<p class="resume-text">La preuve par l\'absurde (reductio ad absurdum) repose sur le tiers exclu : p ∨ ¬p est une tautologie. Pour prouver p, on suppose ¬p et on dérive une contradiction (⊥). La règle d\'inférence est ¬p → ⊥ ⊢ p. Cette règle est admissible en logique classique mais non en logique intuitionniste : Brouwer refusait les preuves d\'existence non constructives. Pour les intuitionnistes, prouver qu\'un objet ne peut pas ne pas exister ne le construit pas — seule une procédure effective de construction est acceptable.</p>'
    '<p class="resume-text">La distinction entre preuve par l\'absurde et contraposition est subtile. La contraposée prouve p → q en prouvant directement ¬q → ¬p — acceptée par les intuitionnistes car elle n\'utilise pas le tiers exclu. La preuve par l\'absurde suppose ¬p et dérive ⊥, concluant p via le tiers exclu. En logique classique les deux sont équivalentes, mais en logique intuitionniste seule la contraposée est admissible. Cette distinction a des conséquences informatiques profondes via la correspondance de Curry-Howard : la preuve par l\'absurde correspond aux continuations (callcc), la contraposée à une transformation directe de programme.</p>'
    '<div class="highlight-box"><p><strong>Curry-Howard et callcc :</strong> La correspondance de Curry-Howard identifie preuves et programmes. Une preuve par l\'absurde en logique classique correspond à un programme utilisant l\'opérateur callcc (call-with-current-continuation) en Scheme ou SML. La non-constructivité du tiers exclu devient la puissance des continuations — qui capturent le contexte d\'exécution courant et permettent de "remonter dans le temps" dans un programme.</p></div>'
    '<h3>Preuves classiques par l\'absurde</h3>'
    '<p class="resume-text">Euclide démontra l\'infinité des nombres premiers (~300 av. J.-C.) par l\'absurde : supposer une liste finie p₁,…,pₙ de tous les premiers, puis considérer N = p₁×…×pₙ + 1. N n\'est divisible par aucun pᵢ (il donne le reste 1), donc son plus petit diviseur premier n\'est pas dans la liste — contredisant l\'hypothèse de finitude. Cette démonstration, 2300 ans après, reste un modèle de clarté et d\'élégance, et a été formalisée dans tous les principaux assistants de preuve.</p>'
    '<p class="resume-text">Cantor utilisa la diagonalisation pour prouver que ℝ est non dénombrable (1874) : supposer une énumération r₁,r₂,r₃,… de tous les réels de [0,1], construire d = 0.d₁d₂d₃… avec dₙ ≠ n-ième décimale de rₙ. Ce réel d n\'est dans la liste (il diffère de rₙ en position n pour tout n) — contradiction. Ce raisonnement révolutionna les mathématiques : il prouva qu\'il existe une hiérarchie d\'infinis de "tailles" différentes, ouvrant la théorie des ensembles transfinis que Cantor développa seul, confronté à l\'incompréhension et l\'hostilité de ses contemporaires.</p>'
    '<div class="highlight-box"><p><strong>Irrationnalité de √2 :</strong> La preuve pythagoricienne (attribuée à Hippase, ~500 av. J.-C.) est l\'une des plus anciennes preuves par l\'absurde conservées. Supposer √2 = p/q irréductible. Alors 2q² = p², donc p est pair (p=2k), donc 2q² = 4k², donc q est pair — contredisant l\'irréductibilité. Selon la légende, Hippase fut noyé par les Pythagoriciens pour avoir révélé ce résultat qui détruisait leur croyance que tout est rapport de nombres entiers.</p></div>'
    '<h3>Limites philosophiques et alternatives constructives</h3>'
    '<p class="resume-text">Les mathématiciens constructivistes (Brouwer, Bishop, Martin-Löf) critiquent les preuves d\'existence par l\'absurde. La preuve classique du théorème des valeurs intermédiaires (si f(a)<0 et f(b)>0 et f continue, alors ∃c∈[a,b] f(c)=0) est non constructive par l\'absurde. La preuve constructive par dichotomie de Cauchy produit explicitement une suite de Cauchy convergeant vers c — un algorithme extractible. Cette version constructive est directement implémentable et donne la méthode de bisection numérique utilisée partout en calcul numérique.</p>'
    '<p class="resume-text">En informatique théorique, les preuves d\'existence non constructives posent un problème pratique : elles prouvent qu\'un bon algorithme existe sans le fournir. La méthode probabiliste d\'Erdős (années 1950) prouve que certaines structures combinatoires existent en montrant qu\'un processus aléatoire les produit avec probabilité positive — sans construire explicitement la structure. Ces preuves sont acceptées en combinatoire mais ne donnent pas de procédure effective, stimulant la recherche en "dérandomisation" pour obtenir des algorithmes déterministes à partir de preuves probabilistes.</p>'
    '<div class="highlight-box"><p><strong>La méthode probabiliste et la dérandomisation :</strong> Erdős prouva l\'existence de graphes avec grand nombre chromatique et grand maille — contredisant l\'intuition — par un argument probabiliste. Trouver explicitement de tels graphes nécessita des décennies. La conjecture de Derandomization postule que toute preuve probabiliste d\'existence peut être transformée en construction déterministe en temps polynomial — une question fondamentale ouverte reliant complexité computationnelle et logique constructive.</p></div>'
)

ENRICHMENTS['preuves-formelles/deduction-naturelle'] = (
    '<h3>Les règles d\'introduction et d\'élimination</h3>'
    '<p class="resume-text">La déduction naturelle (Gentzen 1935) organise les preuves autour de règles d\'introduction (construire une formule) et d\'élimination (utiliser une formule). Pour la conjonction : ∧-intro (de φ et ψ, déduire φ∧ψ) et ∧-élim (de φ∧ψ, déduire φ ou ψ). Pour l\'implication : →-intro (si en supposant φ on dérive ψ, alors φ→ψ, en "déchargeant" l\'hypothèse) et →-élim (modus ponens). Pour la disjonction : ∨-intro (de φ, déduire φ∨ψ) et ∨-élim (raisonnement par cas). Pour les quantificateurs : ∀-intro (prouver φ(x) avec x quelconque) et ∀-élim (instanciation).</p>'
    '<p class="resume-text">La règle →-intro est la plus distinctive : elle formalise le raisonnement "sous hypothèse". On ouvre une sous-dérivation en supposant φ, on dérive ψ dans ce contexte étendu, puis on "ferme" la supposition en concluant φ→ψ au niveau supérieur. Les hypothèses non déchargées forment le contexte Γ de la dérivation : Γ ⊢ φ signifie φ est dérivable à partir de Γ. Cette gestion explicite des hypothèses correspond exactement à la pratique mathématique : "Supposons que n soit pair. Alors... Donc si n est pair, n² est pair."</p>'
    '<div class="highlight-box"><p><strong>Exemple de dérivation :</strong> Preuve de p→p : (1) [p] — hypothèse. (2) p — répétition. (3) p→p — →-intro, déchargeant [p]. Cette dérivation triviale correspond au programme identité λx.x en lambda-calcul. La structure de la preuve et la structure du programme sont identiques — première instance de la correspondance de Curry-Howard.</p></div>'
    '<h3>Correspondance de Curry-Howard</h3>'
    '<p class="resume-text">La correspondance de Curry-Howard (Curry 1934, Howard 1969) est l\'une des découvertes les plus profondes du XXe siècle : les preuves en déduction naturelle correspondent exactement aux programmes du lambda-calcul typé. Les propositions correspondent aux types, les preuves aux termes, la →-intro à l\'abstraction (λx.M), le modus ponens à l\'application (M N). La normalisation des preuves (élimination des "détours" — intro suivie d\'une élim pour le même connecteur) correspond à la réduction bêta (substitution) du lambda-calcul.</p>'
    '<p class="resume-text">Cette correspondance s\'étend à des logiques plus riches. La logique du second ordre (∀ sur les prédicats) correspond au système F de Girard (1972) avec polymorphisme paramétrique — le fondement de Haskell et ML. La logique linéaire (Girard 1987) correspond à des types gérant les ressources (chaque ressource utilisée exactement une fois) — à la base du système de propriété/emprunt de Rust. La logique modale S4 correspond aux monades en Haskell. Ces connexions font de la théorie des types un pont vivant entre logique mathématique et langages de programmation.</p>'
    '<div class="highlight-box"><p><strong>Coq et certification :</strong> En Coq ou Lean, un théorème est un type et une preuve est un programme de ce type. Prouver la commutativité de l\'addition, c\'est écrire un terme de type ∀n m:ℕ, n+m=m+n. La certification formelle du compilateur C CompCert (INRIA) a produit un compilateur dont la correction est garantie par une preuve Coq de ~100 000 lignes — le programme est sa propre preuve de correction. CompCert est utilisé en avionique et systèmes critiques où les bugs de compilateur pourraient être catastrophiques.</p></div>'
    '<h3>Calcul des séquents et élimination des coupures</h3>'
    '<p class="resume-text">Gentzen proposa aussi le calcul des séquents LK (logique classique) et LJ (intuitionniste), où les preuves opèrent sur des séquents Γ ⊢ Δ. Ce formalisme plus symétrique facilite les méta-théorèmes. Le résultat central est le Hauptsatz (théorème de l\'élimination des coupures) : toute preuve peut être normalisée en une preuve sans coupure, où chaque formule introduite est une sous-formule de la conclusion ou des prémisses. La coupure correspond au lemme intermédiaire en mathématiques (invoquer un résultat déjà prouvé) : le Hauptsatz dit qu\'on peut s\'en passer, au prix d\'une preuve souvent exponentiellement plus longue.</p>'
    '<p class="resume-text">L\'élimination des coupures a des conséquences pratiques profondes. La propriété de sous-formule permet de restreindre la recherche de preuves à un espace fini pour la logique propositionnelle, fondant les algorithmes de tableau. Pour le premier ordre, elle est semi-décidable et sous-tend les démonstrateurs automatiques. Les proof nets de Girard pour la logique linéaire représentent les preuves comme des graphes plutôt que des séquences, rendant visible la structure géométrique des preuves et permettant la parallélisation implicite du calcul correspondant.</p>'
    '<div class="highlight-box"><p><strong>Proof nets et parallélisme :</strong> Girard développa les proof nets (1987) pour la logique linéaire — des graphes représentant les preuves géométriquement. Deux preuves normalisent vers le même résultat si et seulement si elles correspondent au même proof net. Cette représentation élimine la redondance séquentielle des dérivations : des sous-preuves indépendantes peuvent être exécutées en parallèle. Les proof nets inspirèrent les travaux sur la géométrie de l\'interaction, une sémantique du calcul fondée sur la théorie des jeux et les interactions entre preuves.</p></div>'
)

ENRICHMENTS['paradoxes/menteur'] = (
    '<h3>Analyse formelle et lemme de diagonalisation</h3>'
    '<p class="resume-text">Le paradoxe du menteur — "Cette phrase est fausse" — est formalisé par le lemme de diagonalisation de Gödel. Dans tout système suffisamment expressif, il existe une formule λ telle que λ est prouvablement équivalente à ¬Provable(⌈λ⌉), où ⌈λ⌉ est le numéro de Gödel de λ. Si λ est prouvable, elle affirme sa propre non-provabilité — contradiction. Si ¬λ est prouvable, le système est incohérent. Donc λ est indécidable dans tout système cohérent. Ce raisonnement est le cœur du premier théorème d\'incomplétude.</p>'
    '<p class="resume-text">Tarski (1933) montra que la vérité pour un langage L ne peut pas être définie dans L lui-même (théorème de l\'indéfinissabilité de la vérité). Tout prédicat Vrai(x) dans L supposé exprimer la vérité de L permet de construire par diagonalisation une phrase "Vrai(⌈cette phrase⌉) est faux" — le menteur. La vérité de L doit donc être définie dans un méta-langage L\' plus riche. Cette hiérarchie des langages — L₀ (objet), L₁ (méta), L₂ (méta-méta), … — est fondamentale en logique et inspire la théorie des types et la théorie des ensembles par niveaux.</p>'
    '<div class="highlight-box"><p><strong>Hiérarchie de Tarski :</strong> Pour éviter le paradoxe, Tarski stratifie le discours : "Cette phrase au niveau 0 est fausse" n\'est bien formée qu\'au niveau 1. La vérité au niveau n est définie dans le méta-langage de niveau n+1. Cette hiérarchie inspirera la théorie des types de Russell et la sémantique des langages de programmation avec réflexion (capacité d\'un programme à manipuler sa propre représentation).</p></div>'
    '<h3>Solutions contemporaines : logiques paracohérentes et points fixes</h3>'
    '<p class="resume-text">Face au paradoxe, plusieurs stratégies coexistent. Les logiques paracohérentes (da Costa, années 1960 ; Priest, 1979) abandonnent ex contradictione quodlibet (d\'une contradiction, tout suit) : la phrase λ peut être à la fois vraie et fausse sans que le système explose. Le dialéthéisme de Priest accepte des contradictions vraies (vraies et fausses simultanément) pour modéliser certains raisonnements en droit, en informatique (bases de données incohérentes) et en sémantique naturelle.</p>'
    '<p class="resume-text">Kripke (1975) proposa une solution élégante par point fixe : la vérité est définie comme le plus petit point fixe d\'un opérateur Φ sur les triplets (extension, anti-extension, cas indéterminés). Une phrase est vraie si elle est dans le point fixe, fausse si sa négation l\'est, indéterminée sinon. La phrase du menteur n\'entre ni dans l\'extension ni dans l\'anti-extension — elle est simplement "hors domaine", sans valeur de vérité. Cette approche préserve la bivalence pour les phrases non paradoxales et est considérée comme la plus satisfaisante par de nombreux logiciens.</p>'
    '<div class="highlight-box"><p><strong>Logique de révision :</strong> Gupta et Belnap (années 1980) traitent la vérité comme une notion révisable : on évalue itérativement les phrases autoréférentielles jusqu\'à un point fixe ou un cycle stable. La phrase du menteur oscille V→F→V→F… sans converger — diagnostiquée comme "instable" ou "pathologique". Les phrases non autoréférentielles convergent rapidement. Cette approche fournit un critère précis pour distinguer les phrases bien définies des paradoxes.</p></div>'
    '<h3>Impact sur l\'informatique : arrêt et autoréférence</h3>'
    '<p class="resume-text">Le problème de l\'arrêt (Turing 1936) est structurellement identique au paradoxe du menteur. Supposer un programme H(P, x) qui décide si P(x) s\'arrête. Construire D(P) = si H(P,P) dit "s\'arrête" alors boucle, sinon s\'arrête. Calculer D(D) : si H(D,D) dit "s\'arrête", alors D(D) boucle — contradiction. Si H(D,D) dit "boucle", alors D(D) s\'arrête — contradiction. Donc H n\'existe pas. Ce raisonnement diagonale est le paradoxe du menteur appliqué aux programmes, prouvant la limite fondamentale de l\'informatique.</p>'
    '<p class="resume-text">En théorie des types, les types récursifs posent des problèmes similaires. Le combinateur Y de point fixe (Y f = f (Y f)) permet la récursion générale en lambda-calcul non typé mais est illégal en lambda-calcul simplement typé — les types prohibent l\'auto-application infinie, garantissant la terminaison de tous les programmes. Le système de types de Haskell, via les types algébriques récursifs et le marqueur newtype, permet la récursion contrôlée sans paradoxe. Les types dépendants (Coq, Lean, Agda) raffinent encore davantage ce contrôle en distinguant récursion productive (terminante) et non-productive.</p>'
    '<div class="highlight-box"><p><strong>Quines et méta-programmation :</strong> Un quine est un programme qui imprime son propre code source — analogue du menteur mais non paradoxal car il ne fait qu\'assertion d\'identité syntaxique, pas de vérité ou fausseté. Les quines illustrent la différence entre auto-référence productive (méta-programmation, réflexion) et auto-référence destructive (paradoxes). En Python : s=\'s=%r;print(s%%s)\';print(s%s). La réflexion — capacité d\'un programme à modifier son propre code à l\'exécution — est un outil puissant en Lisp, Ruby, Java utilisé dans les frameworks de test, ORM, et serialisation.</p></div>'
)

ENRICHMENTS['godel/incompletude'] = (
    '<h3>Le premier théorème d\'incomplétude : construction et preuve</h3>'
    '<p class="resume-text">Le premier théorème d\'incomplétude de Gödel (1931) affirme que tout système formel F récursivement axiomatisable, cohérent et contenant l\'arithmétique de Peano contient une formule G indécidable (ni G ni ¬G ne sont prouvables dans F). La construction repose sur la numérotation de Gödel : on encode formules et preuves par des entiers (via décomposition en facteurs premiers), définissant un prédicat arithmétique Provable(n) qui est vrai si et seulement si n code une formule prouvable. Le lemme de diagonalisation produit G ≡ ¬Provable(⌈G⌉).</p>'
    '<p class="resume-text">La phrase de Gödel G est vraie dans le modèle standard ℕ : si G était prouvable, le numéro de Gödel de cette preuve existerait, mais G affirme qu\'aucune preuve n\'existe — contradiction avec la cohérence de F. Donc G est vraie mais non prouvable. Ce résultat détruisit le programme de Hilbert (1900-1930) visant à fonder toutes les mathématiques dans un système formel complet et cohérent. Pourtant, G devient prouvable dans F + {G} ou dans des méta-systèmes plus forts (ZF prouve que PA est cohérent et que G est vraie) — l\'incomplétude est relative à un système donné, pas une limitation absolue des mathématiques.</p>'
    '<div class="highlight-box"><p><strong>Numérotation de Gödel :</strong> Gödel code la formule (¬(P∧Q)) par le nombre produit de facteurs premiers : 2^code(¬) × 3^code(() × 5^code(P) × 7^code(∧) × 11^code(Q) × 13^code()). Toute formule devient un entier, toute preuve une suite d\'entiers encodée par un entier. Ce codage brillant transforme l\'assertion "cette formule est prouvable" en une propriété arithmétique de nombres entiers — rendant possible l\'auto-référence arithmétique.</p></div>'
    '<h3>Le second théorème et la cohérence</h3>'
    '<p class="resume-text">Le second théorème d\'incomplétude est encore plus radical : un système F cohérent ne peut pas prouver sa propre cohérence (l\'énoncé Cons(F) = "F ne prouve pas ⊥"). Si F prouvait Cons(F), le raisonnement de Gödel montrerait que G est prouvable — mais G affirme sa non-provabilité, contradiction avec la cohérence. Donc Cons(F) est indécidable dans F. Ce résultat ne dit pas que les mathématiques sont incohérentes, mais qu\'aucun système ne peut se certifier lui-même depuis l\'intérieur.</p>'
    '<p class="resume-text">Pour prouver la cohérence de PA, on monte dans un système plus fort : ZF prouve que PA est cohérent. Mais ZF ne peut pas prouver sa propre cohérence. Et si on ajoute "ZF est cohérent" comme axiome, ce nouveau système ne peut pas prouver sa propre cohérence, etc. Cette régression est fondamentale : la certitude absolue en mathématiques est inaccessible depuis l\'intérieur de tout système raisonnable. C\'est l\'une des leçons philosophiques les plus profondes du XXe siècle, mettant fin au projet formaliste et au rêve d\'une fondation ultime et autosuffisante.</p>'
    '<div class="highlight-box"><p><strong>Cohérence de PA par Gentzen :</strong> Gentzen (1936) prouva la cohérence de PA par induction transfinite jusqu\'à l\'ordinal ε₀ = φ(φ(φ(…))) — dans un système légèrement plus fort que PA. Cela ne viole pas le second théorème car ε₀ est un concept ensembliste transfini non capturable arithmétiquement. Ce résultat quantifie précisément la "force" de PA : elle peut prouver l\'induction sur tout ordinal inférieur à ε₀ mais pas l\'induction jusqu\'à ε₀ elle-même.</p></div>'
    '<h3>Conséquences philosophiques et mathématiques concrètes</h3>'
    '<p class="resume-text">Les théorèmes de Gödel ont transformé la philosophie des mathématiques. Pour les platonistes, la phrase de Gödel G est vraie mais non prouvable formellement — elle transcende les systèmes formels, suggérant que l\'intuition mathématique humaine accède à des vérités inaccessibles aux machines. Roger Penrose (L\'Esprit, l\'ordinateur et les lois de la physique, 1989) argua que cela prouve que l\'esprit ne peut pas être simulé par un algorithme — thèse réfutée par la plupart des logiciens (un humain ne peut pas non plus prouver G dans PA ; sa "connaissance" de la vérité de G requiert un méta-raisonnement que les machines peuvent aussi effectuer).</p>'
    '<p class="resume-text">En mathématiques concrètes, Harvey Friedman découvrit des résultats combinatoires naturels indépendants de PA. La séquence de Goodstein — partant de n=4, elle croît pendant des milliards d\'étapes avant d\'atteindre 0 — est vraie mais non prouvable dans PA ; sa preuve requiert l\'induction transfinite de Gentzen. Les théorèmes de Kirby-Paris (1982) et de Friedman (années 1990) sur certaines propriétés de Ramsey sont prouvables dans ZF mais pas dans PA. Ces résultats montrent que l\'incomplétude affecte de vraies questions mathématiques concrètes, pas seulement des phrases autoréférentielles artificielles.</p>'
    '<div class="highlight-box"><p><strong>Indépendance de ZF :</strong> L\'hypothèse du continu (CH : tout ensemble infini de réels est dénombrable ou en bijection avec ℝ) est indépendante de ZF — prouvée consistante par Gödel (1940) via les ensembles constructibles, et indépendante par Cohen (1963) via le forcing. Le problème P=NP, qui demande si tout problème vérifiable en temps polynomial est aussi résoluble en temps polynomial, pourrait lui aussi être indépendant de ZF — certains chercheurs pensent que l\'incomplétude de Gödel pourrait expliquer pourquoi ce problème résiste depuis 50 ans à toute résolution.</p></div>'
)

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
count = 0
for key, extra in ENRICHMENTS.items():
    if key in pages:
        old_len = len(pages[key]['content'])
        content = pages[key]['content']
        quiz_start = content.find('<section class="content-section" id="quiz">')
        if quiz_start != -1:
            pages[key]['content'] = content[:quiz_start] + extra + content[quiz_start:]
        else:
            idx = content.rfind('</section>')
            if idx != -1:
                pages[key]['content'] = content[:idx] + extra + content[idx:]
            else:
                pages[key]['content'] = content + extra
        new_len = len(pages[key]['content'])
        print(f"  {key}: {old_len} -> {new_len}")
        count += 1

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone: {count} articles enriched.")
