#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement des articles de chimie sous 15000 chars"""
import json

PATH = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/chimie.json'

ENRICHMENTS = {}

ENRICHMENTS['generale/liaisons'] = (
    '<h3>Theorie des orbitales moleculaires (MO)</h3>'
    '<p class="resume-text">La theorie des orbitales moleculaires (MO) offre une description plus complete des liaisons chimiques que la theorie VSEPR. Dans cette approche, les orbitales atomiques se combinent lineairement (CLOA) pour former des orbitales moleculaires delocalisees sur tout le squelette de la molecule. Les combinaisons en phase donnent des orbitales liantes (plus basses en energie que les AO originales), les combinaisons hors phase donnent des orbitales antiliantes (plus hautes en energie). L\'ordre de liaison se calcule par (electrons liants - electrons antiliants) / 2. La molecule H₂ a 2 electrons liants et 0 antiliants : ordre = 1, liaison simple stable.</p>'
    '<p class="resume-text">La theorie MO explique des phenomenes inaccessibles a la theorie de Lewis. Le dioxygene O₂ a deux electrons non apparies dans des orbitales antiliantes degenerees (π*) — il est donc paramagnetique, contrairement a la structure de Lewis qui le montre diamagnetique. Cette prediction, verifiee experimentalement, est un triomphe de la theorie MO. L\'ion H₂⁺ (un seul electron) est stable avec un ordre de liaison de 0,5 — impossible a expliquer par les structures de Lewis. Le benzene (6 electrons π delocalisees sur 6 orbitales p du cycle) a des liaisons d\'ordre 1,5, ce qui explique sa grande stabilite et sa resistance a l\'addition electrophile.</p>'
    '<div class="highlight-box"><p><strong>MO et couleur des molecules :</strong> La difference d\'energie entre HOMO (orbitale occupee la plus haute) et LUMO (orbitale vacante la plus basse) determine la longueur d\'onde de la lumiere absorbee. Les molecules conjuguees (alternance de simples et doubles liaisons) ont un gap HOMO-LUMO etroit — elles absorbent dans le visible et sont colorees. Le beta-carotene (responsable de la couleur orange des carottes) a 11 doubles liaisons conjuguees, reduisant le gap a ~2,2 eV — absorption dans le bleu-vert, couleur orange complementaire.</p></div>'
    '<h3>Liaisons en chimie des materiaux</h3>'
    '<p class="resume-text">Les proprietes macroscopiques des materiaux decoulent directement de la nature de leurs liaisons chimiques. Les metaux (liaisons metalliques : electrons delocalisees dans une mer) sont malleables, ductiles, conducteurs de chaleur et d\'electricite. Les ceramiques (liaisons ioniques ou covalentes) sont dures, fragiles, isolantes. Les polymeres (liaisons covalentes le long de chaines avec interactions Van der Waals entre chaines) sont flexibles, legers, mauvais conducteurs. Les conducteurs organiques comme le graphene (liaison pi delocalisee sur un reseau 2D) combinent les proprietes covalentes (rigidite) et metalliques (conduction) dans un materiau 2D unique.</p>'
    '<p class="resume-text">Le graphene, decouvert en 2004 par Geim et Novoselov (prix Nobel 2010), est un feuillet monoatomique de carbone sp2 avec un reseau hexagonal de liaisons pi delocalisees. Sa conductivite electronique (electrons se comportant comme des fermions sans masse, vitesse de Fermi 1/300 de c) et sa resistance mecanique (200 fois plus resistant que l\'acier a epaisseur egale) derivent directement de la structure de ses liaisons. Les nanotubes de carbone (graphene enroule) et le C₆₀ (fullerene, cage spherique) sont d\'autres allotropes issus des memes liaisons covalentes pi du carbone sp2, avec des applications en electronique, energie et medecine.</p>'
    '<div class="highlight-box"><p><strong>Liaisons et pharmaceutique :</strong> La conception de medicaments (drug design) consiste a trouver des molecules dont les liaisons forment des interactions optimales avec un site actif de proteine. Les liaisons hydrogene (2-10 kJ/mol), pi-pi (stacking aromatique, ~2-4 kJ/mol), et hydrophobes (Van der Waals) s\'additionnent pour creer des affinites nanomolaires. Le logiciel AutoDock simule ces interactions pour screener virtuellement des millions de molecules candidates — reduisant de facteur 100 le nombre de syntheses necessaires avant les essais biologiques.</p></div>'
    '<h3>Liaisons et spectroscopie</h3>'
    '<p class="resume-text">Chaque type de liaison a une signature spectroscopique caracteristique. La spectroscopie infrarouge (IR) detecte les vibrations des liaisons : etirement (stretching) et flexion (bending). La frequence de vibration v = (1/2π) √(k/μ), ou k est la constante de force de la liaison et μ la masse reduite. Les liaisons C=O absorbent vers 1700-1750 cm⁻¹, les N-H vers 3300-3500 cm⁻¹, les C-H vers 2850-3000 cm⁻¹. Ces "empreintes" permettent d\'identifier les groupes fonctionnels d\'une molecule inconnue, rendant la spectroscopie IR l\'outil de routine de tout laboratoire de chimie organique.</p>'
    '<p class="resume-text">La resonance magnetique nucleaire (RMN) sonde l\'environnement chimique des noyaux via leurs liaisons. Le deplacement chimique du proton ¹H depend de la densite electronique autour du noyau, determinee par les liaisons C-H, N-H, O-H et les substituants. Les couplages spin-spin (constante J) revelent les liaisons entre noyaux adjacents (couplage vicinal en 3 liaisons : J ≈ 7 Hz pour C-C-H gauche) et la stereochimie des liaisons (equation de Karplus). La RMN multi-dimensionnelle (NOESY, COSY, HSQC) est l\'outil definitif pour determiner la structure complete en solution de molecules jusqu\'a ~50 kDa.</p>'
    '<div class="highlight-box"><p><strong>Liaisons et RMN medicale :</strong> L\'IRM medicale (imagerie par resonance magnetique) exploite les liaisons O-H de l\'eau dans les tissus. La relaxation des protons de l\'eau (T1, T2) depend de leur environnement moleculaire — les tissus normaux et pathologiques ont des temps de relaxation differents. Cela permet de distinguer la matiere grise, la matiere blanche, et les tumeurs sans radiation ionisante. L\'IRM fonctionnelle (fIRM) detecte les variations de l\'oxygenation du sang par le signal BOLD (Blood Oxygenation Level Dependent), base sur la difference de susceptibilite magnetique entre hemoglobine oxygenee et desoxygene — une application directe de la theorie des liaisons chimiques a la medecine.</p></div>'
)

ENRICHMENTS['generale/tableau-periodique'] = (
    '<h3>Loi periodique et configuration electronique</h3>'
    '<p class="resume-text">La periodicite des proprietes chimiques decoule directement de la configuration electronique des atomes. Les electrons se repartissent dans des couches (n=1,2,3,...) et sous-couches (s, p, d, f) selon le principe d\'Aufbau, le principe de Pauli (pas deux electrons avec les memes 4 nombres quantiques), et la regle de Hund (maximiser le spin dans une sous-couche degeneree). Le nombre d\'electrons de valence (ceux de la couche externe) determine les proprietes chimiques : deux elements avec le meme nombre d\'electrons de valence ont des comportements chimiques similaires — justification formelle de la periodicite.</p>'
    '<p class="resume-text">Les anomalies dans la configuration electronique revélent la subtilite de la mecanique quantique. Le chrome (Cr, Z=24) a la configuration [Ar] 3d⁵ 4s¹ au lieu de [Ar] 3d⁴ 4s² — la demi-remplissage de la sous-couche d (5 electrons, un par orbitale) est energetiquement favorisee. De meme, le cuivre (Cu) a [Ar] 3d¹⁰ 4s¹ — le remplissage complet de 3d est plus stable. Ces anomalies affectent les proprietes catalytiques de ces metaux de transition. Le platine, le rhodium et le palladium, dont les configurations electroniques specifiques favorisent les etats d\'oxydation +2 et +4, sont les meilleurs catalyseurs pour les pots catalytiques automobiles (oxydation de CO et reduction de NOx).</p>'
    '<div class="highlight-box"><p><strong>Relativite et chimie des lourds :</strong> Pour les elements lourds (Z > 70), les electrons des couches internes se deplacent a des vitesses relativistes (~80% de c pour l\'electrons 1s de l\'or). L\'effet relativiste contracte les orbitales s et p, dilatant les d et f. L\'or (Au) absorbe la lumiere bleue a cause de la petite difference d\'energie entre les orbitales 5d et 6s, rendue petite par les effets relativistes — d\'ou sa couleur jaune caracteristique. Sans effets relativistes, l\'or serait argente comme l\'argent. La liquidite du mercure a temperature ambiante provient aussi de la contraction relativiste des couches s.</p></div>'
    '<h3>Tendances periodiques et applications</h3>'
    '<p class="resume-text">Les tendances periodiques quantitatives guident la chimie moderne. Le rayon atomique diminue de gauche a droite dans une periode (augmentation de la charge nucleaire effective Z*) et augmente de haut en bas dans un groupe (ajout de couches). L\'energie d\'ionisation (IE₁) suit la tendance inverse — les non-metaux de haut a droite ont les IE₁ les plus hautes. L\'affinite electronique (AE) mesure l\'energie degagee lors de la capture d\'un electron. La serie de Pettifor, une reorganisation du tableau perioique selon la "valence effective", predit les structures cristallines des composes binaires avec une precision remarquable.</p>'
    '<p class="resume-text">L\'electronegativite (Pauling 1932, Mulliken, Allen) mesure la tendance d\'un atome a attirer les electrons partages. La difference d\'electronegativite entre deux atomes determines le caractere ionique de leur liaison : ΔEN > 1.7 ≈ liaisons ioniques, 0.5-1.7 ≈ liaisons polaires covalentes, < 0.5 ≈ liaisons covalentes apolaires. Ces seuils, bien que empiriques, guident intuitivement la chimie. Les polymeres conducteurs (polyacetylene, polythiophene, PEDOT:PSS) exploitent une alternance d\'electronegativites pour creer des bandes d\'energie propices a la conduction — une application directe de la periodicite electronique en electronique organique.</p>'
    '<div class="highlight-box"><p><strong>Elements critiques et geopolitique :</strong> Les terres rares (lanthanides + Sc, Y) sont indispensables aux technologies vertes : les aimants permanents au neodyme-fer-bore (NdFeB) des eoliennes et vehicules electriques, les phosphores au terbium et europium des LEDs, les catalyseurs au lanthane et cerium pour le raffinage du petrole. La Chine produit 85% de ces elements. Leur configuration electronique avec des sous-couches f partiellement remplies leur donne des proprietes magnetiques et optiques uniques irremplacables, creant des dependances geopolitiques directement liees au tableau periodique.</p></div>'
    '<h3>Tableau periodique et prediction de nouveaux elements</h3>'
    '<p class="resume-text">Le tableau periodique permet de predire les proprietes d\'elements non encore syntetises. Mendeleiev predit en 1871 les proprietes de l\'eka-aluminium (gallium, decouvert 1875), de l\'eka-bore (scandium, 1879), et de l\'eka-silicium (germanium, 1886) avec une precision remarquable. Aujourd\'hui, les elements 113-118 (nihonium a oganesson, syntetises 2002-2010) ont ete nommes en 2016. Oganesson (Og, Z=118) devrait etre un gaz noble, mais les calculs relativistes suggerent qu\'il pourrait etre un solide a temperature ambiante avec des proprietes chimiques atypiques — une prediction attendant verification.</p>'
    '<p class="resume-text">Les "iles de stabilite" theoriques predisent l\'existence d\'elements super-lourds (Z=114, 120, 126) avec des durees de vie plus longues que leurs voisins, dues a des nombres magiques de protons/neutrons formant des couches nucleaires completement remplies. Le flerovium (Z=114) deja syntetise semble plus stable que prevu. Les efforts pour syntetiser Z=120 et au-dela continuent dans les grands accelerateurs (JINR Dubna, GSI Darmstadt). Ces elements super-lourds, si leurs durees de vie sont suffisantes, permettraient d\'explorer les limites de la chimie periodique et des effets relativistes pousses a l\'extreme.</p>'
    '<div class="highlight-box"><p><strong>Oganesson et effets relativistes :</strong> Les calculs ab initio de l\'oganesson (Z=118) predisent que ses electrons de valence 7p sont si fortement affectes par les effets relativistes que sa reactivite chimique serait atypique pour un gaz noble — il pourrait former des composes avec le fluor. Sa densite electronique le rendrait probablement solide a temperature ambiante. Ces predictions illustrent comment les effets relativistes, directement issus de la mecanique quantique, modifient profondement la chimie periodique au-dela de l\'uranium.</p></div>'
)

ENRICHMENTS['generale/atome'] = (
    '<h3>Modele quantique de l\'atome</h3>'
    '<p class="resume-text">Le modele quantique de l\'atome (Schrodinger 1926) decrit l\'electron par une fonction d\'onde ψ(r,θ,φ) dont le carre donne la densite de probabilite de presence. Les solutions de l\'equation de Schrodinger pour l\'atome d\'hydrogene sont les orbitales atomiques, caracterisees par trois nombres quantiques : principal (n = 1,2,3,...) donne l\'energie et la taille, azimutal (l = 0,...,n-1) donne la forme (s, p, d, f), magnetique (ml = -l,...,+l) donne l\'orientation dans l\'espace. Un quatrieme nombre quantique de spin (ms = ±1/2) est requis par la mecanique quantique relativiste de Dirac.</p>'
    '<p class="resume-text">Les orbitales ne sont pas des orbites au sens classique mais des regions de l\'espace ou la probabilite de trouver l\'electron est significative (generalement 90%). L\'orbitale 1s est une sphere centree sur le noyau. Les orbitales 2p (trois, orientees selon x, y, z) ont la forme de lobes en haltere. Les orbitales 3d ont des formes plus complexes (lobes en trefle pour dx²-y², anneau pour dz²). Ces formes determinent la geometrie des liaisons et l\'angularite des molecules. Les orbitales hybrides (sp, sp2, sp3) resultent de la combinaison lineaire des orbitales atomiques pour optimiser les recouvrements et les geometries moleculaires observees.</p>'
    '<div class="highlight-box"><p><strong>Spectroscopie atomique et astrophysique :</strong> Chaque element emet un spectre d\'emission unique — "empreinte digitale" atomique. La spectroscopie de la lumiere stellaire permet d\'identifier la composition des etoiles a des milliards d\'annees-lumiere. L\'helium fut decouvert dans le spectre solaire (1868) avant d\'etre isole sur Terre (1895). La raie a 21 cm de l\'hydrogene (transition hyperfine du spin electronique) est utilisee en radioastronomie pour cartographier la distribution de l\'hydrogene dans la Voie Lactee et detecter les molecules dans les nuages interstellaires.</p></div>'
    '<h3>Noyau atomique et radioactivite</h3>'
    '<p class="resume-text">Le noyau atomique contient protons et neutrons (nucleons) lies par l\'interaction forte. La stabilite nucleaire depend du rapport N/Z (neutrons/protons) et des nombres magiques (2, 8, 20, 28, 50, 82, 126 nucleons correspondant a des couches nucleaires completes). La radioactivite naturelle implique trois types d\'emission : alpha (²He, noyaux legers), beta (electron ou positron, via la reaction n → p + e⁻ + antineutrino), et gamma (photon gamma, re-arrangement nucleaire). La loi de decroissance radioactive N(t) = N₀ e^(-λt) definit la demi-vie T₁/₂ = ln2/λ, independante des conditions exterieures (temperature, pression, etat chimique).</p>'
    '<p class="resume-text">Les applications de la radioactivite sont nombreuses. La datation au carbone-14 (T₁/₂ = 5730 ans) permet de dater des materiaux organiques jusqu\'a ~50 000 ans. La fission nucleaire (U-235 ou Pu-239, T de reactions en chaine) produit de l\'energie dans les centrales nucleaires. La fusion nucleaire (D + T → ⁴He + n + 17,6 MeV), source d\'energie du soleil, est l\'objectif du projet ITER (Cadarache, premiere plasma a 2025). La tomographie par emission de positons (TEP) utilise des radionuclides (¹⁸F-fluorodeoxyglucose) pour imager le metabolisme cellulaire — application medicale directe de la radioactivite beta+.</p>'
    '<div class="highlight-box"><p><strong>Radioactivite et medecine nucleaire :</strong> La medecine nucleaire utilise des radioisotopes pour le diagnostic (scinti-graphie, TEP) et le traitement (radiotherapie). L\'iode-131 (T₁/₂ = 8 jours, emetteur beta et gamma) traite le cancer thyroidien : capte selectivement par la thyroide, il irradie les cellules cancereuses localement. Le technecium-99m (T₁/₂ = 6h, emetteur gamma pur a 140 keV) est l\'isotope le plus utilise en scintigraphie — sa courte demi-vie minimise l\'irradiation du patient tout en permettant l\'imagerie.</p></div>'
    '<h3>Spectroscopie atomique et analyse elementaire</h3>'
    '<p class="resume-text">La spectroscopie d\'emission atomique (ICP-OES, ICP-MS) est la technique analytique de reference pour l\'analyse elementaire en traces. L\'echantillon est vaporise et ionise dans un plasma de couplage inductif (ICP) a 6000-10 000 K. Les ions sont ensuite tries par masse (MS) ou les photons emis sont analyses par longueur d\'onde (OES). La detection atteint des concentrations de l\'ordre du ng/L (ppq) pour certains elements — permettant de detecter des contaminants en ultra-traces dans l\'eau, les aliments, et les materiaux pharmaceutiques. L\'ICP-MS multi-elementaire analyse simultanement 70+ elements en quelques minutes.</p>'
    '<p class="resume-text">La spectroscopie de fluorescence X (XRF) et la diffraction des rayons X (DRX) completent l\'arsenal analytique. La XRF identifie les elements d\'une surface sans destruction d\'echantillon — utilisee pour verifier la composition d\'alliages, analyser des oeuvres d\'art (Louvre, MET), et controler les metaux lourds dans les jouets. La DRX determine la structure cristalline des composes — Watson et Crick utiliserent les donnees DRX de Rosalind Franklin pour proposer la structure de l\'ADN en 1953. Les synchrotrons modernes (ESRF Grenoble, APS Argonne) produisent des faisceaux X brillants permettant de resoudre la structure de proteines, de materiaux nouveaux et de molecules pharmaceutiques avec une precision atomique.</p>'
    '<div class="highlight-box"><p><strong>Atome et nanotechnologie :</strong> La microscopie a effet tunnel (STM, Binnig et Rohrer, Nobel 1986) et la microscopie a force atomique (AFM) permettent d\'imager des atomes individuels avec une resolution sous-angstrom et meme de les manipuler. IBM positionna en 1989 des atomes de xenon sur du nickel pour ecrire "IBM" en atomes individuels — premiere demonstration de manipulation atomique deliberee. Les microscopes modernes permettent de realiser des reactions chimiques molecule a molecule, d\'identifier des especes intermediaires fugaces, et de syntetiser des molecules individuelles — la chimie a l\'echelle de l\'atome, envisagee par Feynman en 1959.</p></div>'
)

ENRICHMENTS['generale/stoechiometrie'] = (
    '<h3>Calculs stoechiometriques avances</h3>'
    '<p class="resume-text">La stoechiometrie quantitative s\'appuie sur le concept de reactif limitant — le reactif qui est completement consomme en premier et dont la quantite determine le rendement theorique de la reaction. Pour identifier le reactif limitant, on calcule le rapport (quantite disponible / coefficient stoechiometrique) pour chaque reactif : le plus petit rapport correspond au limitant. Si 2 mol de H₂ reagissent avec 1 mol de O₂ selon 2H₂ + O₂ → 2H₂O : avec 4 mol H₂ et 1,5 mol O₂, le rapport pour H₂ est 4/2=2, pour O₂ c\'est 1,5/1=1,5 — O₂ est limitant, et on obtiendra 2×1,5 = 3 mol H₂O.</p>'
    '<p class="resume-text">Le rendement d\'une reaction (rendement = quantite reelle / quantite theorique × 100%) est rarement 100% en pratique. Les pertes proviennent de reactions secondaires, d\'equilibres incomplets, de pertes lors du travail up (transferts, purifications), et de l\'instabilite des produits. En synthese organique multi-etapes, les rendements se multiplient : 10 etapes a 90% chacune donnent un rendement global de 0,9¹⁰ = 35%. Maximiser les rendements est donc crucial en chimie pharmaceutique — un meilleur rendement peut faire la difference entre un medicament economiquement viable et non viable.</p>'
    '<div class="highlight-box"><p><strong>Stoechiometrie et industrie chimique :</strong> La stoechiometrie est fondamentale pour l\'optimisation des procedes industriels. Le procede Haber-Bosch (N₂ + 3H₂ → 2NH₃) fonctionne a 400-500°C sous 150-300 bars. Le rapport stoechiometrique H₂/N₂ = 3 est maintenu exactement pour maximiser la conversion. Les gaz inertes (argon) s\'accumulent dans le cycle — leur purge periodique est calculee stoechiometriquement. Ce procede produit 150 millions de tonnes d\'ammoniac par an, dont 80% pour les engrais qui nourrissent la moitie de l\'humanite.</p></div>'
    '<h3>Stoechiometrie en solution : concentrations et titrages</h3>'
    '<p class="resume-text">Les calculs stoechiometriques en solution utilisent les concentrations molaires (mol/L = M). La quantite en moles n = C × V. Les titrages acide-base, redox et de precipitation utilisent la stoechiometrie pour determiner la concentration inconnue d\'une solution. Pour un titrage acide-base : a l\'equivalence, n(acide) × Ka = n(base) × Kb. Le point d\'equivalence d\'un titrage pH-metrique est detecte par l\'inflexion de la courbe pH = f(V titrant). Les titrages potentiometriques (detection electrochimique) permettent d\'automatiser l\'analyse et de detecter plusieurs equivalences successives pour les acides polyprotiques.</p>'
    '<p class="resume-text">La gravimetrie (pesee apres precipitation et filtration) est la methode stoechiometrique la plus precise. La volumetrie de Karl Fischer mesure la teneur en eau par stoechiometrie de la reaction I₂ + SO₂ + H₂O + 3 RN → (RNH)SO₄ + 2(RNH)I. Elle detecte des teneurs en eau de 10 ppm dans les solvants, les huiles, et les pharmaceutiques — essentielle pour controler la stabilite des medicaments. La stoechiometrie de la combustion dans les analyseurs elementaires (CHN-S) convertit quantitativement les elements organiques en CO₂, H₂O, N₂ et SO₂ detectes par chromatographie ou conductivite thermique.</p>'
    '<div class="highlight-box"><p><strong>Stoechiometrie dans le corps humain :</strong> La respiration cellulaire (C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP) est rigoureusement stoechiometrique. Chaque mole de glucose consomme exactement 6 moles d\'O₂ et produit 6 moles de CO₂. Le quotient respiratoire (QR = CO₂ produit / O₂ consomme) vaut 1 pour les glucides, 0,7 pour les lipides, 0,8 pour les proteines. Un QR mesuré sur un patient revele son substrat energetique dominant — utilise en nutrition clinique pour ajuster l\'alimentation des patients en reanimation.</p></div>'
    '<h3>Stoechiometrie et reaction d\'equilibre</h3>'
    '<p class="resume-text">La stoechiometrie des reactions d\'equilibre requiert la constante d\'equilibre K, liee aux concentrations a l\'equilibre. Pour aA + bB ⇌ cC + dD : K = [C]^c [D]^d / ([A]^a [B]^b). Les quotients de reaction Q et K determinent le sens de l\'evolution : si Q < K, la reaction avance en sens direct. Le principe de Le Chatelier predit la reponse d\'un equilibre a une perturbation. L\'augmentation de pression favorise les reactions qui diminuent le nombre de moles gazeuses. C\'est pourquoi la synthese de l\'ammoniac (4 mol → 2 mol gazeuses) est favorisee par haute pression, et la synthese d\'acide sulfurique 2SO₂ + O₂ → 2SO₃ (3 mol → 2 mol) aussi.</p>'
    '<p class="resume-text">La stoechiometrie quantique (thermodynamique chimique) permet de calculer les rendements theoriques en fonction de la temperature et de la pression via les energies libres de Gibbs. ΔG = ΔG° + RT ln Q = 0 a l\'equilibre. Pour le procede Haber-Bosch, ΔG° = -32,9 kJ/mol a 25°C mais +5 kJ/mol a 500°C. L\'equilibre est donc thermodynamiquement favorable a basse temperature mais la cinetique est trop lente sans catalyseur. Le catalyseur (fer avec promoteurs Al₂O₃ et K₂O) permet d\'atteindre un rendement acceptable (~15%) a 400-500°C, malgre un K deficit — un compromis cinetique-thermodynamique guide par la stoechiometrie.</p>'
    '<div class="highlight-box"><p><strong>Green chemistry et atom economy :</strong> L\'economie atomique (Trost, 1991) mesure le pourcentage de la masse des reactifs qui se retrouve dans le produit desire : AE = (Mw produit / Mw reactifs totaux) × 100%. Une reaction a 100% d\'economie atomique n\'a pas de sous-produits — ideal environnemental. La synthese de l\'ibuprofene a ete revisee par Boots-Hoechst Celanese pour passer de 6 etapes (AE = 40%) a 3 etapes (AE = 77%), reduisant de moitie les dechets par tonne produite. La stoechiometrie quantitative est l\'outil fondamental de la chimie verte pour minimiser les dechets a la source.</p></div>'
)

ENRICHMENTS['biochimie/metabolisme'] = (
    '<h3>Voies metaboliques centrales</h3>'
    '<p class="resume-text">Le metabolisme cellulaire s\'organise autour de voies biochimiques interconnectees. La glycolyse (10 reactions enzymatiques) convertit le glucose en 2 pyruvates, produisant net 2 ATP et 2 NADH. En aerobiose, le pyruvate entre dans le cycle de Krebs (acetyl-CoA via la pyruvate deshydrogenase), generant 2 GTP, 6 NADH, et 2 FADH₂ par glucose. La chaine respiratoire mitochondriale oxyde NADH (2,5 ATP/NADH) et FADH₂ (1,5 ATP/FADH₂) avec O₂ comme accepteur final — bilan total : ~30-32 ATP par glucose. Ce rendement est bien superieur a la fermentation (2 ATP) mais requiert l\'oxygene.</p>'
    '<p class="resume-text">La regulation metabolique est multi-niveaux. La regulation allosterique (modification conformationnelle par des effecteurs) ajuste l\'activite enzymatique en quelques millisecondes. La phosphorylation/dephosphorylation par kinases/phosphatases (regulation en secondes a minutes) repond aux signaux hormonaux. L\'expression genique (regulation en heures) adapte la quantite d\'enzyme aux besoins a long terme. L\'insuline et le glucagon illustrent ce multi-niveau : l\'insuline active la glycogene-synthase (phosphorylation/dePhosphorylation) et stimule l\'expression de GLUT4 (expression genique), gerant la glycemie sur plusieurs echelles de temps.</p>'
    '<div class="highlight-box"><p><strong>Metabolisme et cancer :</strong> L\'effet Warburg (1924) : les cellules cancereuses privilegient la glycolyse meme en presence d\'O₂ (glycolyse aerobie), produisant du lactate au lieu d\'entrer dans le cycle de Krebs. Ce metabolisme inefficace en ATP est compensé par une consommation massivde de glucose (visible en TEP-scan au ¹⁸F-FDG). Les oncogenes (Myc, Ras) et suppresseurs de tumeurs (p53, PTEN) reconfigurent directement les voies metaboliques. Les inhibiteurs metaboliques (2-DG, metformine) sont explores comme anticancereux.</p></div>'
    '<h3>Metabolisme lipidique et energetique</h3>'
    '<p class="resume-text">La beta-oxydation des acides gras est la voie catabolique principale des lipides. Un acide gras a 16C (palmitate) produit 7 tours de beta-oxydation, generant 7 FADH₂ + 7 NADH + 8 acetyl-CoA. Les 8 acetyl-CoA entrent dans le cycle de Krebs, produisant 16 GTP + 24 NADH + 8 FADH₂. Bilan total : environ 106 ATP par molecule de palmitate, contre 32 pour le glucose — les lipides sont donc une reserve energetique environ 2,3× plus dense que les glucides, justifiant leur role de stockage energetique a long terme.</p>'
    '<p class="resume-text">La synthese des acides gras (lipolgyse inverse) se produit dans le cytoplasme via l\'acide gras-synthase (FAS), un complexe enzymatique multienzymatique chez les eucaryotes. FAS elonge la chaine de 2 carbones par tour, utilisant malonyl-CoA (derive de l\'acetyl-CoA par acetyl-CoA carboxylase). Cette enzyme (ACC) est le point de regulation cle de la lipogenese, inhibe par glucagon et activee par insuline. FAS est surrexprimee dans de nombreux cancers et est une cible therapeutique prometteuse pour les cancers du sein et de la prostate ou la lipogenese tumorale est augmentee.</p>'
    '<div class="highlight-box"><p><strong>Obesite et metabolisme :</strong> La resistance a l\'insuline (precurseur du diabete de type 2) resulte de perturbations des voies de signalisation insulinique au niveau des recepteurs et des voies PI3K/Akt. Les ceramides et diacylglycerols (intermediaires lipidiques) accumules dans les muscles et le foie perturbent la signalisation. La metformine (principal medicament anti-diabetique) active AMPK (kinase sensible a l\'energie), qui inhibe la gluconeogenese hepatique et stimule la capture du glucose par les muscles — directement au niveau des voies metaboliques biochimiques.</p></div>'
    '<h3>Metabolomique et medecine de precision</h3>'
    '<p class="resume-text">La metabolomique etudie l\'ensemble des metabolites (<1500 Da) presentes dans une cellule, un tissu, ou un fluide biologique a un instant donne. Les plateformes analytiques combinent spectrometrie de masse (GC-MS, LC-MS/MS) et RMN ¹H pour detecter et quantifier des milliers de metabolites simultanement. Les "empreintes metaboliques" (metabolic fingerprints) discriminent des etats physiologiques et pathologiques. Le Human Metabolome Database (HMDB) repertorie >220 000 metabolites humains avec leurs voies metaboliques et concentrations normales dans les bioflids.</p>'
    '<p class="resume-text">Les applications cliniques de la metabolomique se developpent rapidement. Le depistage neonatal etendu (expanded newborn screening) detecte des erreurs innees du metabolisme (phenylcetonurie, maladie d\'urine a odeur de sirop d\'erable, acidemies organiques) en quelques heures par LC-MS/MS, permettant un traitement precoce et preventif. La metabolomique urinaire identifie des biomarqueurs specifiques de certains cancers (cancer vesical, colorectal) plus tot que les tests conventionnels. Ces applications concretisent l\'idee que le "profil metabolique" d\'un patient est un reflet en temps reel de son etat de sante metabolique global.</p>'
    '<div class="highlight-box"><p><strong>Microbiome et metabolisme :</strong> Le microbiome intestinal (10¹³ micro-organismes, 150× plus de genes que le genome humain) produit des metabolites qui influencent directement le metabolisme de l\'hote. Les acides gras a courtes chaines (AGCC : acetate, propionate, butyrate) produits par la fermentation bacterienne des fibres alimentaires activent des recepteurs (GPR41, GPR43) qui regulentla secretion d\'insuline et le metabolisme energetique. Des dysbioses du microbiome sont associees a l\'obesite, au diabete de type 2 et aux maladies inflammatoires de l\'intestin — etablissant le microbiome comme un "organe metabolique" supplementaire.</p></div>'
)

ENRICHMENTS['analytique/spectroscopie'] = (
    '<h3>Spectroscopie de masse : principe et applications</h3>'
    '<p class="resume-text">La spectrometrie de masse (MS) identifie les molecules par leur masse molaire et leur fragmentation caracteristique. L\'echantillon est ionise (ESI pour les biomolecules, EI pour les composes volatils, MALDI pour les proteines et polymeres), les ions sont separes par leur rapport masse/charge (m/z) dans un analyseur (quadrupole, piege ionique, orbitrapte, TOF), et detectes. Le spectre de masse — distribution des ions en fonction de m/z — est l\'empreinte unique de chaque molecule. La MS haute resolution (Orbitrap, FTICR) mesure les masses avec une precision < 5 ppm, permettant d\'identifier la formule moleculaire exacte C_xH_yN_zO_w.</p>'
    '<p class="resume-text">Le couplage chromatographie-masse (GC-MS, LC-MS/MS) est l\'outil dominant en chimie analytique moderne. GC-MS (composes volatils, derives silyles) analyse les residus de pesticides dans les aliments jusqu\'a 0,01 mg/kg, les pollutants organiques dans l\'air et l\'eau, et les profils des huiles essentielles. LC-MS/MS (triple quadrupole) quantifie les medicaments dans le plasma sanguin avec des limites de detection de ng/mL, essentiels pour la pharmacocinetique et le controle antidopage. Les analyseurs proteomiques (nano-LC-Orbitrap) identifient des milliers de proteines dans une seule analyse en 60 minutes.</p>'
    '<div class="highlight-box"><p><strong>MALDI-TOF et diagnostics cliniques :</strong> Le MALDI-TOF MS (Matrix-Assisted Laser Desorption/Ionization - Time Of Flight) identifie les bacteries pathogenes par leur profil proteique caracteristique en 10 minutes, contre 24-48h pour les methodes microbiologiques traditionnelles. L\'instrument Vitek MS (bioMerieux) est deploye dans des milliers d\'hopitaux mondialement pour le diagnostic des infections bacteriennes, accelerant la prescription d\'antibiotiques adaptes et reduisant la mortalite par septicemie.</p></div>'
    '<h3>Spectroscopie vibrationnelle : IR et Raman</h3>'
    '<p class="resume-text">La spectroscopie IR et Raman sont complementaires. L\'IR detecte les vibrations qui changent le moment dipolaire — actives pour les groupes polaires (C=O, O-H, N-H). Le Raman detecte les vibrations qui changent la polarisabilite — actives pour les liaisons symetriques (C=C, S-S, C-C dans les cycles). Les deux techniques donnent une image complete de la structure vibrationnelle. L\'IR-ATR (Attenuated Total Reflectance) permet d\'analyser des echantillons solides ou liquides sans preparation, directement sur la surface. Le Raman confocal couplé a un microscope permet de cartographier la composition chimique avec une resolution spatiale de ~1 micron.</p>'
    '<p class="resume-text">Les spectromètres IR et Raman portatifs revolutionnent le controle sur le terrain. Des appareils comme l\'AGILENT 4100 ExoScan (IR-ATR, 1 kg) ou le Thermo Scientific TruScan (Raman disperse) identifient en 30 secondes les matieres premieres pharmaceutiques, les explosifs, les drogues illicites, et les contrefacons. Les douaniers et la police les utilisent pour le controle frontalier. En chantier archeologique, le Raman portable identifie les pigments des peintures rupestres et des oeuvres d\'art sans echantillonnage — une revolution pour la conservation du patrimoine.</p>'
    '<div class="highlight-box"><p><strong>Spectroscopie Raman et chirurgie :</strong> La spectroscopie Raman intraoperatoire permet aux neurochirurgiens de distinguer en temps reel les cellules tumorales du tissu sain pendant l\'exerese d\'une glioblastome. Les spectres Raman des tissus normaux et tumoraux different systematiquement en raison des differences de composition moleculaire (lipides, proteines, nucleotides). Des sondes Raman miniaturisees guidees par fibre optique sont testees en essais cliniques pour ameliorer les marges de resection tumorale — directement la spectroscopie vibrationnelle appliquee a la chirurgie guidee.</p></div>'
    '<h3>Spectroscopie UV-Vis et applications</h3>'
    '<p class="resume-text">La spectroscopie d\'absorption UV-Visible est l\'une des techniques analytiques les plus utilisees en raison de sa simplicite et de sa polyvalence. La loi de Beer-Lambert A = ε × l × C (absorbance = coefficient d\'extinction molaire × longueur de trajet × concentration) permet de quantifier toute espece absorbante. Les cofacteurs enzymatiques (NADH : ε = 6220 M⁻¹cm⁻¹ a 340 nm, FAD a 450 nm), les proteines (a 280 nm via Trp et Tyr), et les acides nucleiques (a 260 nm) se dosent directement. Les methodes enzymatiques couplaes (reaction enzymatique produisant ou consommant NAD(P)H) permettent de doser des metabolites non chromophores comme le glucose ou le lactate.</p>'
    '<p class="resume-text">La spectroscopie differentielle et derivative augmente la resolution spectrale. La differentiation du 2eme ordre des spectres UV-Vis permet de separer des contributions qui se recouvrent, d\'identifier des conformations proteiques, et de quantifier des melanges complexes. La spectroscopie de dichroisme circulaire (DC) utilise la difference d\'absorption de la lumiere circulairement polaris (gauche vs droite) pour caracteriser la structure secondaire des proteines (helices alpha, feuillets beta, structures desordonnees) et la configuration absolue de molecules chirales — essentielle pour l\'industrie pharmaceutique ou l\'enantiomere actif doit etre distinct de l\'enantiomere inactif ou toxique.</p>'
    '<div class="highlight-box"><p><strong>Controle qualite pharmaceutique :</strong> Les Pharmacopees europeenne et americaine (USP) exigent des controles spectroscopiques stricts des medicaments : identification par IR et UV, dosage par HPLC-UV, controle des impuretes a < 0,1% par LC-MS. Une comprimit d\'aspirine (acide acetylsalicylique) doit contenir 500 mg ± 5% avec < 0,1% de phenol (impurete de synthese). Ces specifications sont verifiables en 10 minutes par spectroscopie et chromatographie — la stoechiometrie et la spectroscopie appliquees a la securite des medicaments.</p></div>'
)

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
count = 0
for key, extra in ENRICHMENTS.items():
    if key in pages:
        old_len = len(pages[key]['content'])
        content = pages[key]['content']
        quiz_start = content.find('<section class="content-section" id="quiz">')
        if quiz_start != -1:
            pages[key]['content'] = content[:quiz_start] + extra + content[quiz_start:]
        else:
            idx = content.rfind('</section>')
            if idx != -1:
                pages[key]['content'] = content[:idx] + extra + content[idx:]
            else:
                pages[key]['content'] = content + extra
        new_len = len(pages[key]['content'])
        print(f"  {key}: {old_len} -> {new_len}")
        count += 1

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone: {count} articles enriched.")
