import json

# Final pass — add ~2000 chars to each article still below 15000

FINAL_ADDITIONS = {
"traites/droits-de-lhomme": """
<h3>Les entreprises et les droits humains</h3>
<p class="resume-text">Les <strong>Principes directeurs des Nations Unies relatifs aux entreprises et aux droits de l'homme</strong> (Principes Ruggie, 2011) ont établi un cadre de référence fondé sur trois piliers : l'obligation de l'État de protéger les droits humains, la responsabilité des entreprises de les respecter, et l'accès des victimes à des voies de recours. Ces principes, non contraignants mais très influents, ont inspiré des législations nationales (loi française sur le devoir de vigilance, 2017 ; loi allemande sur la chaîne d'approvisionnement, 2021) et des directives européennes qui imposent aux grandes entreprises une diligence raisonnable sur leurs impacts en matière de droits humains et d'environnement dans toutes leurs chaînes d'approvisionnement mondiales.</p>
<p class="resume-text">La tension entre <strong>souveraineté nationale et universalité des droits</strong> reste vive. Certains États (Chine, Russie, mais aussi des démocraties du Sud global) contestent le caractère universel des droits humains tels que définis par l'Occident, soulignant le primat des droits économiques et sociaux sur les droits civils et politiques, la collectivité sur l'individu, ou la diversité culturelle sur les normes universelles. Cette tension se manifeste dans les votes au Conseil des droits de l'homme et dans les négociations sur de nouveaux instruments internationaux.</p>
""",
"traites/desarmement-nucleaire": """
<h3>Contrôle des armements conventionnels</h3>
<p class="resume-text">Parallèlement aux armes nucléaires, le contrôle des <strong>armements conventionnels</strong> fait l'objet de traités internationaux. Le Traité sur le commerce des armes (TCA, 2014) oblige les États exportateurs à évaluer si leurs ventes d'armements risquent de servir à commettre des violations graves des droits humains ou du droit humanitaire. Le traité est ratifié par une centaine d'États, mais les principaux exportateurs (États-Unis, Russie, Chine) n'y participent pas ou de façon limitée. La Convention d'Ottawa sur les mines antipersonnel (1997) et la Convention sur les armes à sous-munitions (2008) ont établi des interdictions totales de catégories d'armes, avec un succès partiel : les grandes puissances militaires restent hors de ces régimes.</p>
<p class="resume-text">Les <strong>armes légères et de petit calibre</strong> (ALPC) — kalachnikovs, pistolets, lance-roquettes portatifs — sont les véritables « armes de destruction massive » des conflits contemporains : elles tuent chaque année 500 000 personnes dans le monde, principalement dans les pays en développement. Le Programme d'action des Nations Unies sur les ALPC (2001) et l'Instrument international de traçage tentent de réduire les flux illicites, mais se heurtent à la prolifération mondiale de ces armes, au trafic clandestin et aux intérêts commerciaux des producteurs.</p>
""",
"traites/droit-de-la-mer": """
<h3>Les câbles sous-marins et la sécurité numérique des mers</h3>
<p class="resume-text">Les <strong>câbles sous-marins</strong> transportent plus de 95% du trafic internet mondial et constituent une infrastructure critique de l'économie numérique mondiale. Plus de 400 câbles actifs parcourent les fonds océaniques pour un réseau de 1,3 million de kilomètres. Leur protection juridique relève de la CNUDM (protection contre les dommages délibérés) et d'accords techniques multilatéraux, mais reste insuffisante face aux menaces contemporaines : sabotage, espionnage (les agences de renseignement ont développé des capacités d'interception sous-marine), risques naturels (séismes, glissements de terrain sous-marins).</p>
<p class="resume-text">Les incidents récents — sabotage du gazoduc Nord Stream (2022), ruptures de câbles en mer Rouge et en mer Baltique (2024) — ont mis en lumière la vulnérabilité de ces infrastructures et la difficulté de les attribuer et de les protéger. Les États côtiers ont un droit de juridiction limité sur les câbles dans leurs eaux territoriales et leurs ZEE. En haute mer, la protection dépend principalement de conventions pénales bilatérales et multilatérales souvent peu appliquées. La protection des câbles sous-marins est devenue une priorité stratégique pour les États-Unis et l'OTAN.</p>
""",
"conflits/droit-humanitaire": """
<h3>Le droit à l'assistance humanitaire</h3>
<p class="resume-text">Le <strong>droit à l'assistance humanitaire</strong> pour les civils victimes de conflits armés est consacré par les Conventions de Genève et leurs Protocoles, mais son accès est souvent entravé par les belligérants. Les acteurs humanitaires (CICR, ONU, ONG) négocient des accès avec toutes les parties au conflit, ce qui implique parfois de traiter avec des groupes armés non étatiques ou des acteurs désignés comme terroristes. Ces négociations créent des tensions avec les politiques gouvernementales de lutte antiterroriste.</p>
<p class="resume-text">L'<strong>aide humanitaire comme arme de guerre</strong> — le blocage délibéré de l'aide pour affamer ou soumettre une population — est un crime de guerre selon le Statut de Rome. Les sièges de villes (Leningrad 1941-1944, Sarajevo 1992-1995, Ghouta syrienne 2013-2018) sont des exemples historiques de cette stratégie. Les couloirs humanitaires négociés pour évacuer des civils ou livrer de l'aide dans des zones assiégées sont souvent instrumentalisés politiquement par les belligérants, soulevant des dilemmes éthiques pour les humanitaires entre accessibilité et compromission.</p>
""",
"conflits/terrorisme-international": """
<h3>Le financement du terrorisme</h3>
<p class="resume-text">La lutte contre le <strong>financement du terrorisme</strong> est devenue un pilier de la stratégie antiterroriste depuis le 11 septembre 2001. Le Groupe d'action financière (GAFI/FATF), fondé en 1989 pour lutter contre le blanchiment d'argent, a étendu son mandat au financement du terrorisme. Il publie des listes de pays non-coopératifs (liste grise, liste noire) dont l'inscription crée des pressions diplomatiques et commerciales. Les systèmes de paiement informels (hawala, cryptocurrency) et les États aux réglementations laxistes restent des vecteurs de financement difficiles à contrôler.</p>
<p class="resume-text">La résolution 2462 du Conseil de sécurité (2019) appelle les États à criminaliser le financement du terrorisme et à coopérer pour geler les avoirs des organisations terroristes. Les listes de sanctions du Conseil de sécurité (comités Al-Qaïda et Daech) ont permis de geler des milliards de dollars d'avoirs liés à des organisations terroristes. Mais l'efficacité de ces mesures est limitée : les organisations terroristes s'adaptent en utilisant des méthodes de financement décentralisées, des façades commerciales légales et des cryptomonnaies.</p>
""",
"organisations-internationales/otan-et-alliances": """
<h3>L'OTAN et la gestion des crises du XXIe siècle</h3>
<p class="resume-text">L'OTAN a conduit deux grandes opérations hors zone (out-of-area) qui ont mis à l'épreuve sa cohésion. L'<strong>opération en Afghanistan</strong> (ISAF/Resolute Support, 2003-2021) est la plus longue et la plus coûteuse de l'histoire de l'Alliance : 130 000 soldats de 50 pays au pic, 1 000 milliards de dollars dépensés par les États-Unis, et un retrait final qui laissa les talibans reprendre le pouvoir en 72 heures. L'opération en <strong>Libye</strong> (2011), pour protéger les civils menacés par Kadhafi, fut saluée comme un succès militaire mais déboucha sur le chaos politique, ce qui refroidit l'enthousiasme pour de nouvelles interventions humanitaires.</p>
<p class="resume-text">Après la guerre d'Ukraine, l'OTAN a adopté son nouveau <strong>concept stratégique</strong> (Madrid, 2022) qui désigne la Russie comme « la menace la plus directe et la plus importante à la sécurité des Alliés ». Pour la première fois depuis la fin de la Guerre froide, l'Alliance a adopté des plans de défense régionaux détaillés pour chaque flanc. Les discussions sur un éventuel déploiement de troupes permanentes dans les pays baltes (remplaçant la présence en rotation actuelle) illustrent l'évolution vers une posture plus défensive et robuste face à la Russie.</p>
""",
"organisations-internationales/organisations-regionales": """
<h3>La CEDEAO face aux crises sahéliennes</h3>
<p class="resume-text">La <strong>Communauté économique des États de l'Afrique de l'Ouest</strong> (CEDEAO, 15 membres) a développé une capacité d'intervention dans les conflits régionaux depuis son rôle au Libéria (ECOMOG, 1990) et en Sierra Leone. Elle a suspendu et menacé des sanctions plusieurs pays ayant connu des coups d'État (Mali 2021, Guinée 2021, Burkina Faso 2022, Niger 2023). La réponse au coup d'État au Niger (juillet 2023) — ultimatum militaire et menace d'intervention — a montré les limites de son autorité face à une junte soutenue par ses voisins sahéliens eux-mêmes gouvernés par des militaires (Mali, Burkina Faso).</p>
<p class="resume-text">La rupture du Mali, du Burkina Faso et du Niger avec la CEDEAO (annonce de retrait en janvier 2024) et leur rapprochement avec la Russie (groupe Wagner devenu Africa Corps) illustre une recomposition géopolitique majeure au Sahel. Ces pays ont expulsé les soldats français et tournent le dos aux partenariats sécuritaires occidentaux, créant un vide diplomatique que Moscou cherche à combler. La CEDEAO se retrouve devant le dilemme de maintenir la pression (au risque de pousser ces pays hors de l'organisation) ou d'assouplir sa posture démocratique pour préserver l'unité régionale.</p>
""",
"organisations-internationales/ong-et-societe-civile": """
<h3>La résilience des sociétés civiles sous pression autoritaire</h3>
<p class="resume-text">La société civile internationale fait face à une vague de restrictions légales dans de nombreux pays depuis les années 2010. Des lois sur les « agents étrangers » (Russie, 2012 ; Hongrie, 2017) obligent les ONG recevant des financements étrangers à se déclarer comme tels, les stigmatisant et les soumettant à des contrôles accrus. Des lois antiterroristes élargies sont utilisées pour poursuivre des militants des droits humains, des journalistes et des responsables d'ONG dans des pays aussi divers que la Chine, l'Inde, l'Égypte ou Israël. L'espace civique mondial s'est réduit dans plus de 150 pays selon l'organisation CIVICUS.</p>
<p class="resume-text">Face à ces restrictions, la société civile développe des stratégies d'adaptation : numérisation des activités, réseaux distribués difficiles à décapiter, plaidoyer via des coalitions internationales, utilisation des mécanismes onusiens (Conseil des droits de l'homme, rapporteurs spéciaux) comme espace de liberté. La <strong>coalition globale de la société civile</strong> autour des ODD, de la COP climatique et des négociations sur le traité des pandémies montre la capacité d'adaptation des ONG à trouver des espaces de participation dans les interstices du multilatéralisme.</p>
""",
"conflits/resolution-des-conflits": """
<h3>Les ressources naturelles et les conflits armés</h3>
<p class="resume-text">La relation entre ressources naturelles et conflits armés est complexe et documentée. Le <strong>Processus de Kimberley</strong> (2003), qui certifie que les diamants exportés ne financent pas des conflits armés (« diamants de sang »), est un exemple de régulation internationale visant à couper les financements des groupes armés. L'Initiative pour la transparence des industries extractives (ITIE) impose aux pays membres de publier les revenus tirés des ressources pétrolières, gazières et minières, limitant les possibilités de détournement qui alimentent les conflits.</p>
<p class="resume-text">Le règlement européen sur les <strong>minéraux de conflit</strong> (2021), inspiré de la section 1502 du Dodd-Frank Act américain, oblige les importateurs européens d'étain, tantale, tungstène et or à vérifier que leurs approvisionnements ne financent pas des groupes armés, notamment dans l'est de la RDC. Ces mécanismes de traçabilité se développent à mesure que la demande en métaux critiques pour la transition énergétique (cobalt, lithium, terres rares) suscite de nouveaux risques de conflits dans les régions productrices.</p>
""",
"traites/droit-des-traites": """
<h3>Les accords informels et la soft law</h3>
<p class="resume-text">La diplomatie contemporaine recourt de plus en plus à des instruments <strong>non contraignants</strong> — déclarations politiques, accords de gentlemen, codes de conduite, mémorandums d'entente (MOU), lignes directrices — que les juristes regroupent sous le terme de soft law. Ces instruments permettent de sceller des accords rapidement, sans les délais de ratification des traités formels, et avec plus de souplesse pour s'adapter à l'évolution des situations. L'Accord de Paris sur le climat, les objectifs des G7/G20, les accords de Minsk sur l'Ukraine sont des exemples d'instruments à mi-chemin entre le politique et le juridiquement contraignant.</p>
<p class="resume-text">La multiplication de la soft law soulève des questions théoriques fondamentales : si les États respectent voluntairement ces normes non contraignantes, c'est qu'elles ont une effectivité comparable au droit dur. Inversement, le choix du format non contraignant peut signaler que les parties ne s'engagent pas véritablement. La frontière entre soft law et hard law n'est pas statique : des normes initialement non contraignantes peuvent évoluer en droit coutumier contraignant si elles sont suivies par une pratique générale accompagnée de l'opinio juris (conviction d'obligation juridique).</p>
""",
"traites/droit-international-environnemental": """
<h3>La protection des océans et des forêts</h3>
<p class="resume-text">La <strong>Convention-cadre sur la diversité biologique</strong> a fixé en 2022 l'objectif de protéger 30% des terres et 30% des eaux d'ici 2030. Cet objectif ambitieux implique une extension significative des aires marines protégées (AMP) et des parcs nationaux dans le monde entier, en accord avec les populations autochtones qui gèrent souvent les zones les plus riches en biodiversité. Le traité BBNJ sur la haute mer (2023) crée le cadre pour la désignation d'AMP au-delà des zones de juridiction nationale — une avancée majeure pour la protection des 50% de la planète que représente la haute mer.</p>
<p class="resume-text">La <strong>déforestation</strong> est l'un des principaux facteurs de la crise climatique et de biodiversité. La Déclaration de Glasgow sur les forêts (COP26, 2021), signée par 140 pays représentant 90% des forêts mondiales, engage à mettre fin à la déforestation d'ici 2030. Mais les engagements volontaires ont souvent déçu dans le passé. Le mécanisme REDD+ (Réduction des émissions dues à la déforestation et à la dégradation des forêts) vise à rémunérer les pays en développement pour la conservation de leurs forêts, mais sa mise en oeuvre bute sur des problèmes de mesure, de permanence et de gouvernance des droits fonciers.</p>
""",
"cooperation/mondialisation": """
<h3>La mondialisation et les droits des travailleurs</h3>
<p class="resume-text">La mondialisation a soulevé des tensions profondes sur les <strong>droits des travailleurs</strong>. Les chaînes de valeur mondiales fragmentées permettent aux entreprises de localiser leurs activités dans les pays où le coût du travail est le plus bas et la réglementation sociale la moins contraignante — une logique de course vers le bas (race to the bottom) qui met en concurrence les travailleurs de différents pays. La catastrophe du Rana Plaza (Bangladesh, 2013 — 1 135 morts dans l'effondrement d'un immeuble de confection textile) a mis en lumière les conditions de travail dans les chaînes d'approvisionnement de la fast fashion.</p>
<p class="resume-text">Les <strong>accords commerciaux de nouvelle génération</strong> (CETA, JEFTA, TPP) incluent des chapitres sur les droits du travail et l'environnement — une avancée par rapport aux accords purement commerciaux du GATT. Mais leur mise en oeuvre et leurs mécanismes d'application restent faibles. L'<strong>Organisation internationale du travail</strong> (OIT), avec ses Normes internationales du travail (conventions et recommandations), offre un cadre de référence universel — mais ratifier une convention ne garantit pas son application effective, comme le montrent les nombreux cas de violations signalés chaque année.</p>
""",
"cooperation/institutions-financieres": """
<h3>La régulation financière internationale</h3>
<p class="resume-text">La crise financière de 2008 a conduit à une réforme profonde de la régulation financière internationale. Le <strong>Conseil de stabilité financière</strong> (CSF), créé par le G20 en 2009, coordonne la réglementation financière mondiale entre régulateurs nationaux et organisations internationales (BRI, FMI, Banque mondiale, IOSCO). Les accords de <strong>Bâle III</strong> (2010-2017) ont relevé les exigences de fonds propres des banques et introduit des coussins de capital contracycliques. La régulation des produits dérivés, des hedge funds et du shadow banking a été renforcée dans les principaux pays développés.</p>
<p class="resume-text">La <strong>finance verte</strong> et la prise en compte des risques climatiques dans la régulation financière sont devenues des priorités du CSF. Les recommandations de la Task Force on Climate-related Financial Disclosures (TCFD) visent à obliger les entreprises et les institutions financières à divulguer leurs expositions aux risques climatiques, permettant aux marchés de mieux les intégrer dans les prix. La taxonomie verte européenne définit quelles activités économiques peuvent être qualifiées de durables — un outil de régulation qui influence les flux de capitaux vers les investissements verts.</p>
""",
"cooperation/developpement-international": """
<h3>L'éducation et la santé comme investissements stratégiques</h3>
<p class="resume-text">L'<strong>éducation</strong> est unanimement reconnue comme le déterminant le plus puissant du développement humain à long terme. Le Programme Education For All (EFA) et l'ODD4 visent une éducation de qualité et inclusive pour tous. Malgré des progrès significatifs (le taux d'alphabétisation mondial est passé de 64% en 1990 à 87% en 2022), 250 millions d'enfants sont encore hors de l'école et la qualité de l'éducation reste insuffisante dans de nombreux pays. La pandémie de Covid-19 a provoqué la plus grande perturbation scolaire de l'histoire : 1,6 milliard d'élèves privés d'école au plus fort de la crise, avec des pertes d'apprentissage qui pourront prendre une génération à rattraper.</p>
<p class="resume-text">La <strong>santé mondiale</strong> est un bien public international au sens économique du terme : les pandémies ignorent les frontières, et un système de santé défaillant dans un pays peut créer des risques pour tous. L'expérience d'Ebola (2014-2016) et surtout du Covid-19 a souligné les faiblesses du Règlement sanitaire international (RSI, 2005) et la nécessité d'un financement pérenne des capacités sanitaires dans les pays à revenus faibles et intermédiaires. Les négociations sur un Accord sur les pandémies (traité de l'OMS) illustrent les difficultés à renforcer la gouvernance sanitaire mondiale face aux préoccupations souverainistes.</p>
""",
"cooperation/geopolitique-de-lenergie": """
<h3>L'AIEA et la non-prolifération nucléaire</h3>
<p class="resume-text">L'<strong>Agence internationale de l'énergie atomique</strong> (AIEA, Vienne), créée en 1957, est le gardien du système de non-prolifération nucléaire. Elle conduit des inspections dans les pays signataires du TNP pour vérifier que les matières nucléaires civiles ne sont pas détournées vers des programmes d'armement. Son système de garanties repose sur des rapports d'État sur les matières nucléaires, des inspections régulières et des inspections spéciales en cas de doute. L'AIEA a su détecter des programmes clandestins (Irak avant 1991, Libye, Iran depuis 2002) mais a aussi manqué des violations (Irak jusqu'en 1991, Corée du Nord).</p>
<p class="resume-text">Le <strong>dossier nucléaire iranien</strong> est le cas le plus complexe de la non-prolifération contemporaine. Le Plan d'action global conjoint (JCPOA, 2015) négocié par les P5+1 limitait le programme nucléaire iranien en échange de la levée des sanctions. Le retrait américain (2018) et le non-retour malgré les négociations ont conduit l'Iran à s'affranchir progressivement des contraintes du JCPOA, enrichissant l'uranium à 60% (seuil militaire : 90%). La communauté internationale craint que l'Iran n'ait atteint une capacité de breakout (production rapide d'une arme) sans pour autant avoir décidé de franchir le pas.</p>
""",
"cooperation/gouvernance-mondiale": """
<h3>La gouvernance de la santé mondiale</h3>
<p class="resume-text">L'<strong>Organisation mondiale de la santé</strong> (OMS), agence spécialisée de l'ONU fondée en 1948, est le principal acteur de la gouvernance sanitaire mondiale. Avec un budget d'environ 6 milliards de dollars par an (dont 80% de contributions volontaires conditionnées à des projets spécifiques), elle est chroniquement sous-financée par rapport à ses mandats. La pandémie de Covid-19 a révélé ses faiblesses : dépendance aux informations des États membres, lenteur de la déclaration d'urgence de santé publique internationale, influence excessive de certains donateurs.</p>
<p class="resume-text">Les négociations pour un <strong>Traité sur les pandémies</strong> (Accord de prévention, de préparation et de riposte aux pandémies, PPPR), engagées en 2021 à l'OMS, visent à combler les lacunes révélées par le Covid-19 : accès équitable aux vaccins et aux médicaments, partage des données génomiques et des pathogènes, renforcement des capacités sanitaires dans tous les pays. Ces négociations se sont révélées plus difficiles que prévu, divisées sur la propriété intellectuelle des vaccins (pays du Sud demandant des dérogations TRIPS), la surveillance épidémiologique et la souveraineté sanitaire. Un accord partiel a été adopté en 2024, plus limité qu'espéré.</p>
""",
"organisations-internationales/systeme-des-nations-unies": """
<h3>Les femmes à l'ONU et la parité dans la gouvernance mondiale</h3>
<p class="resume-text">La parité de genre dans les postes de direction au sein du système onusien a progressé lentement. L'ONU compte une Secrétaire générale adjointe (Amina Mohammed, Nigeria), et plusieurs chefs d'agences sont des femmes (UNICEF, HCR). Antonio Guterres a pris des engagements formels de parité à tous les niveaux de direction — un objectif encore loin d'être atteint dans certaines parties du système. La <strong>Commission de la condition de la femme</strong> (CSW) est le principal organe intergouvernemental de l'ONU pour l'égalité de genre, produisant des normes et des recommandations suivies dans de nombreux pays.</p>
<p class="resume-text">La <strong>réforme de financement de l'ONU</strong> est un enjeu de gouvernance majeur. Le budget ordinaire est financé par des quotes-parts calculées sur le PIB national, mais les fonds fiduciaires — qui permettent aux donateurs de diriger leurs contributions vers des activités spécifiques — représentent une part croissante des ressources totales. Cette « bilatéralisation » du financement multilatéral fragmente les priorités et réduit la capacité de l'ONU à mener des politiques cohérentes selon les priorités définies collectivement par les États membres plutôt que par quelques grands donateurs.</p>
""",
"organisations-internationales/union-europeenne": """
<h3>L'euro et la politique économique européenne</h3>
<p class="resume-text">L'<strong>Union économique et monétaire</strong> est le pilier le plus intégré — et le plus contesté — de la construction européenne. La création de l'euro a éliminé les risques de change au sein de la zone, réduit les coûts de transaction et imposé une discipline financière, mais a aussi privé les États membres des instruments d'ajustement que sont le taux de change et la politique monétaire nationale. La crise de la zone euro (2010-2015) a révélé les fragilités d'une union monétaire sans union budgétaire : des pays comme la Grèce, l'Irlande ou le Portugal ne pouvaient dévaluer pour restaurer leur compétitivité et ont dû subir des ajustements douloureusement déflationnistes.</p>
<p class="resume-text">La réponse à la crise a progressivement renforcé l'architecture de la zone euro : le Mécanisme européen de stabilité (MES), l'Union bancaire (supervision bancaire unique par la BCE, résolution des défaillances bancaires), le programme OMT (Outright Monetary Transactions) de la BCE — « whatever it takes » de Mario Draghi. Le fonds NextGenerationEU (2021), finançant la relance post-Covid par une dette commune européenne, est le pas le plus ambitieux vers une capacité budgétaire européenne commune. La pression pour une union des marchés de capitaux et une union des marchés énergétiques s'est accélérée avec les crises géopolitiques de 2022.</p>
""",
"conflits/theories-du-conflit": """
<h3>Vers une théorie des relations internationales non-occidentale ?</h3>
<p class="resume-text">Le champ des Relations Internationales est dominé par des théories produites dans des universités américaines et britanniques, développées pour rendre compte de l'expérience européenne et atlantique des XVIIe-XXe siècles. Des chercheurs du monde entier questionnent ce qu'ils appellent la colonialité du savoir en RI : les catégories centrales (État souverain, anarchie, balance of power) présupposent un monde d'États westphaliens qui ne correspond pas à l'expérience de nombreuses régions du monde (Afrique précoloniale, Asie du système tributaire sino-centré, monde arabo-islamique).</p>
<p class="resume-text">Des théories alternatives émergent : la <strong>théorie des RI chinoises</strong> (école de Tsinghua, Yan Xuetong, théorie de la hiérarchie internationale basée sur la moralité politique), la <strong>théorie postcoloniale</strong> (rôle structurant du colonialisme dans le système international actuel), la <strong>théorie décoloniale</strong> (comment les catégories conceptuelles occidentales naturalisent des rapports de domination). Ces perspectives enrichissent le champ sans pour autant supplanter les paradigmes dominants, ce qui illustre que la production du savoir en RI reste elle-même un terrain de concurrence entre puissances intellectuelles.</p>
""",
"diplomatie/negociation-internationale": """
<h3>La diplomatie de la contrainte : ultimatum et brinkmanship</h3>
<p class="resume-text">La diplomatie n'est pas seulement l'art du compromis : elle inclut aussi la communication stratégique de la détermination et de la capacité à faire usage de la force si nécessaire. La <strong>diplomatie coercitive</strong> (Alexander George) vise à convaincre un adversaire de cesser une action ou d'accepter certaines conditions par la menace de la force plutôt que par son emploi effectif. Elle requiert une menace crédible (capacité et volonté perçues de mettre à exécution la menace) et une demande claire avec une porte de sortie honorable pour l'adversaire.</p>
<p class="resume-text">Le <strong>brinkmanship</strong> (jeu avec le feu, au bord du gouffre) consiste à amener l'adversaire au seuil de la guerre pour le forcer à céder. Dulles et Kissinger ont théorisé et pratiqué cette approche durant la Guerre froide. Son application requiert une juste évaluation des lignes rouges adverses et de la tolérance au risque de chaque partie. Mal calibrée, cette stratégie peut conduire à des catastrophes non voulues : les mécanismes d'escalade peuvent prendre le pas sur les décisions rationnelles des dirigeants, comme l'illustre la cascade de mobilisations qui conduisit à la Première Guerre mondiale en août 1914.</p>
""",
"diplomatie/histoire-de-la-diplomatie": """
<h3>La diplomatie des femmes : une longue invisibilisation</h3>
<p class="resume-text">L'histoire de la diplomatie a longtemps été une histoire exclusivement masculine. Les premières femmes ambassadrices ne sont nommées qu'au XXe siècle : Alexandra Kollontaï en Norvège (1923) pour l'URSS, Clare Booth Luce en Italie (1953) pour les États-Unis. En France, la diplomatie ne s'ouvre pleinement aux femmes qu'en 1972. Aujourd'hui, les femmes représentent environ 20% des ambassadeurs dans le monde, avec de grandes disparités régionales. Le plafond de verre demeure particulièrement épais aux postes les plus stratégiques.</p>
<p class="resume-text">Pourtant, les femmes ont toujours joué un rôle diplomatique, souvent dans l'ombre ou via des canaux non officiels. Les <strong>femmes souveraines</strong> (Cléopâtre, Élisabeth Ire, Catherine de Russie) ont conduit leur propre diplomatie. Les <strong>salons littéraires</strong> du XVIIe-XVIIIe siècles, tenus principalement par des femmes, étaient de véritables espaces d'influence diplomatique où se formaient les opinions des élites. La <strong>diplomatie des mariages dynastiques</strong> — organiser des unions pour sceller des alliances — faisait des femmes royales des instruments et parfois des actrices de la politique internationale. La recherche historique récente redécouvre ces contributions longtemps invisibilisées.</p>
""",
"diplomatie/droit-diplomatique": """
<h3>La cyberdiplomatie et les nouvelles normes internationales</h3>
<p class="resume-text">La <strong>cyberdiplomatie</strong> cherche à établir des normes de comportement responsable des États dans le cyberespace. Des groupes d'experts gouvernementaux (GGE) de l'ONU ont produit plusieurs rapports (2013, 2015, 2021) reconnaissant que le droit international s'applique au cyberespace, que les États ne doivent pas conduire ou soutenir délibérément des cyberattaques contre des infrastructures critiques, et qu'ils doivent respecter les droits humains en ligne. Ces normes non contraignantes ont une portée limitée face à la réalité des cyberattaques étatiques quotidiennes.</p>
<p class="resume-text">La tension entre <strong>internet comme espace libre global</strong> et <strong>internet comme espace de souveraineté nationale</strong> structure les débats de cyberdiplomatie. Les démocraties libérales défendent un internet ouvert, interopérable et gouverné par un modèle multi-parties prenantes. La Russie et la Chine prônent la « souveraineté numérique » et le droit des États à contrôler leur espace numérique national, s'appuyant sur l'Union internationale des télécommunications (UIT) pour promouvoir une gouvernance plus intergouvernementale de l'internet. Ces visions opposées reflètent des différences profondes sur la démocratie, les libertés civiles et l'ordre mondial.</p>
""",
"diplomatie/diplomatie-economique": """
<h3>Les zones économiques spéciales et la diplomatie du développement</h3>
<p class="resume-text">Les <strong>zones économiques spéciales</strong> (ZES) sont un instrument de diplomatie économique popularisé par la Chine depuis Shenzhen (1980) et exporté massivement à l'étranger via la BRI. Ces zones offrent des avantages fiscaux et réglementaires pour attirer les investissements étrangers, avec des résultats variables selon les contextes nationaux. Les ZES chinoises en Éthiopie (zone industrielle de Hawassa), en Zambie, au Pakistan (CPEC) et dans d'autres pays créent des enclaves économiques liées aux chaînes de valeur chinoises, soulevant des questions sur les modèles de développement économique et la dépendance technologique.</p>
<p class="resume-text">La <strong>négociation des accords d'investissement</strong> est un champ majeur de la diplomatie économique moderne. Les <strong>traités bilatéraux d'investissement</strong> (TBI), qui garantissent aux investisseurs étrangers une protection contre la nationalisation et un accès à l'arbitrage international, ont proliféré depuis les années 1990 (plus de 3 000 en vigueur). La multiplication des plaintes d'investisseurs contre des États (sous le mécanisme ISDS — Investor-State Dispute Settlement) pour des milliards de dollars d'indemnités a suscité une réaction : l'UE a proposé la création d'une Cour multilatérale des investissements permanente pour remplacer les tribunaux arbitraux ad hoc.</p>
""",
}

def enrich_page(content, extra_html):
    idx = content.rfind('</section>')
    if idx == -1:
        return content + extra_html
    return content[:idx] + extra_html + content[idx:]

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

enriched = 0
for key, extra in FINAL_ADDITIONS.items():
    if key in data['pages']:
        page = data['pages'][key]
        original_len = len(page['content'])
        page['content'] = enrich_page(page['content'], extra)
        new_len = len(page['content'])
        print(f'  {key}: {original_len} -> {new_len} chars')
        enriched += 1

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Final check
with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
course_pages = [(k, len(p['content'])) for k,p in data['pages'].items() if p.get('type') in ('course','lesson')]
above_15k = sum(1 for k,l in course_pages if l >= 15000)
above_14k = sum(1 for k,l in course_pages if l >= 14000)
below = [(k,l) for k,l in course_pages if l < 14000]
print(f'\nFINAL STATE: {above_15k}/{len(course_pages)} >= 15k, {above_14k}/{len(course_pages)} >= 14k')
for k,l in sorted(below, key=lambda x: x[1]):
    print(f'  SHORT: {l} {k}')
print(f'\nTotal enriched: {enriched}')
