#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Deuxième passe linguistique.json — tous les articles < 15000 chars"""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/linguistique.json'

PASS2 = {
    'phonetique/appareil-phonatoire': """<h3>La phonation et ses pathologies</h3>
<p class="resume-text">La phoniatrie, branche médicale étudiant la voix et la parole, s'appuie directement sur la compréhension de l'appareil phonatoire. Les pathologies vocales — dysphonies (altérations de la qualité de la voix), aphonies (perte totale de la voix), nodules des cordes vocales — touchent particulièrement les professionnels de la voix : chanteurs, enseignants, avocats, comédiens. Le traitement combine rééducation orthophonique (travail sur la posture, la respiration abdominale, la détente laryngée) et parfois intervention chirurgicale. Les progrès de l'imagerie vidéolaryngoscopique permettent désormais de visualiser en temps réel les mouvements des cordes vocales pendant la phonation, révolutionnant le diagnostic et la pédagogie vocale.</p>
<div class="highlight-box"><strong>Voix chantée vs voix parlée</strong> : La voix chantée utilise les mêmes structures que la voix parlée, mais avec un contrôle musculaire beaucoup plus précis. Les chanteurs d'opéra développent des résonateurs amplificateurs naturels (masque, poitrine) qui leur permettent de projeter leur voix sans amplification dans de grandes salles. La technique du bel canto italien, développée aux XVIIe-XVIIIe siècles, a codifié ces techniques corporelles que les sciences phonatoires modernes ont permis d'expliquer sur le plan anatomique.</div>
<h3>Évolution phylogénétique de la phonation humaine</h3>
<p class="resume-text">L'appareil phonatoire humain présente une particularité unique parmi les primates : le larynx est positionné beaucoup plus bas dans la gorge que chez les autres singes. Cette descente du larynx, qui s'est produite au cours de l'évolution de notre espèce (Homo sapiens), a créé un pharynx allongé formant une chambre de résonance permettant la production d'une grande variété de sons. Mais cette adaptation a un coût biologique : elle nous expose à un risque d'étouffement inexistant chez nos cousins primates, car la nourriture et l'air partagent la même voie. Cette évolution, associée aux développements neurologiques du contrôle fin des muscles phonatoires, est considérée comme l'un des prérequis anatomiques du langage articulé.</p>""",

    'phonetique/voyelles-consonnes': """<h3>Les systèmes vocaliques dans les langues du monde</h3>
<p class="resume-text">Les systèmes vocaliques varient considérablement d'une langue à l'autre. Certaines langues ont des systèmes très réduits : l'abkhaze (langue du Caucase) n'a que deux phonèmes vocaliques distinctifs. À l'opposé, des langues comme l'anglais britannique standard peuvent distinguer jusqu'à 20 voyelles (dont les diphtongues). Le français distingue 13 à 16 voyelles selon les dialectes. Cette variation n'est pas aléatoire : les systèmes vocaliques suivent des principes de dispersion maximale dans l'espace acoustique (théorie de la dispersion-focalisation de Schwartz et al.), ce qui explique pourquoi les systèmes à 3 voyelles contiennent presque universellement /a/, /i/, /u/ — les voyelles les plus distinctives.</p>
<div class="highlight-box"><strong>Voyelles cardinales de Jones</strong> : Le phonéticien britannique Daniel Jones (1881-1967) a établi le système des voyelles cardinales comme référence internationale pour la description phonétique. Les 8 voyelles cardinales primaires forment les repères d'un espace articulatoire normé, permettant à tout phonéticien de décrire les sons d'une langue par référence à ces points fixes. Ce système, adopté par l'IPA, reste la base de l'enseignement de la phonétique mondiale.</div>
<h3>L'apprentissage des phonèmes étrangers</h3>
<p class="resume-text">L'acquisition des voyelles et consonnes d'une langue étrangère est l'un des défis majeurs de l'apprentissage linguistique. La théorie de l'assimilation perceptive (Pat Kuhl) explique pourquoi les adultes ont du mal à percevoir des distinctions phonémiques absentes de leur langue maternelle : les sons étrangers sont inconsciemment assimilés aux catégories phonémiques natives. Le Japonais distingue mal /r/ et /l/ en anglais car ces deux sons tombent dans la même catégorie phonémique en japonais. Les recherches en neurolinguistique montrent que cette rigidité perceptive s'installe progressivement entre 6 et 12 mois, avant même les premiers mots.</p>""",

    'phonetique/phonemes-allophones': """<h3>La commutation et les paires minimales</h3>
<p class="resume-text">La méthode des paires minimales est l'outil fondamental pour identifier les phonèmes d'une langue. Deux mots forment une paire minimale s'ils ne diffèrent que par un seul son, permettant de démontrer que ce son a une valeur distinctive : « pain » vs « bain » prouve que /p/ et /b/ sont des phonèmes distincts en français. Cette méthode, formalisée par le phonologue Nikolaï Troubetskoï dans ses Principes de phonologie (1939), reste au cœur de l'analyse phonologique structurale. La commutation systématique dans toutes les positions (initiale, médiane, finale) permet de dresser le tableau phonémique complet d'une langue.</p>
<div class="highlight-box"><strong>Phonèmes marginaux</strong> : Certains phonèmes n'apparaissent que dans des mots empruntés ou des contextes très limités, créant des phonèmes « marginaux ». En français, /ŋ/ (comme dans « camping ») n'existe que dans des emprunts à l'anglais et à d'autres langues. Ces phonèmes périphériques témoignent du contact entre langues et de l'évolution phonologique en cours dans la langue.</div>
<h3>Phonologie non linéaire et structures prosodiques</h3>
<p class="resume-text">La phonologie non linéaire, développée dans les années 1970-80 (John Goldsmith, Morris Halle, Michael Kenstowicz), a révolutionné la conception des phonèmes en montrant que les traits phonologiques ne s'organisent pas simplement en séquence linéaire. Les représentations autosegmentales permettent de rendre compte de phénomènes comme les tons (en langues tonales) qui se propagent indépendamment des segments, les harmonies vocaliques (où toutes les voyelles d'un mot partagent une propriété comme l'arrondissement), ou les structures syllabiques qui contraignent la distribution des phonèmes. Cette approche a enrichi considérablement la compréhension de la structure interne des mots.</p>""",

    'phonetique/prosodie': """<h3>La prosodie de la conversation</h3>
<p class="resume-text">La prosodie joue un rôle central dans la gestion des tours de parole en conversation. Les locuteurs utilisent des signaux prosodiques pour indiquer qu'ils veulent conserver la parole (continuité intonative, accélération du débit), céder leur tour (chute de la voix, allongement final), ou inviter l'interlocuteur à prendre la parole (intonation montante, pause). Ces conventions prosodiques sont en partie universelles, en partie culturellement variables. Les malentendus interculturels peuvent résulter de différences prosodiques : ce qui semble une interruption impolie dans une culture peut être un signal d'engagement et d'intérêt actif dans une autre.</p>
<div class="highlight-box"><strong>Prosodie et émotion</strong> : Les émotions modifient systématiquement les paramètres prosodiques. La colère se manifeste typiquement par une voix haute et tendue, un débit rapide, des accents forts. La tristesse par une voix basse et monotone, un débit lent, une chute finale marquée. Ces corrélats acoustiques des émotions sont suffisamment universels pour permettre la reconnaissance émotionnelle cross-culturelle, même sans compréhension du contenu sémantique — une observation utilisée dans les systèmes de synthèse vocale expressive.</div>
<h3>Prosodie et traitement automatique de la parole</h3>
<p class="resume-text">Le traitement automatique de la parole (TAP) — reconnaissance vocale, synthèse vocale, traduction automatique de la parole — doit modéliser la prosodie pour atteindre une qualité naturelle. Les systèmes de synthèse vocale comme les assistants vocaux (Siri, Alexa, Google Assistant) utilisent des modèles prosodiques appris sur de vastes corpus pour générer une intonation naturelle. La prosodie aide aussi la reconnaissance automatique : les signaux prosodiques permettent de délimiter les unités syntaxiques, de distinguer questions et affirmations, de résoudre certaines ambiguïtés lexicales. Les progrès récents des réseaux de neurones profonds ont considérablement amélioré la modélisation prosodique.</p>""",

    'phonetique/phonologie-processus': """<h3>Les processus phonologiques dans l'acquisition</h3>
<p class="resume-text">Les enfants en cours d'acquisition du langage utilisent systématiquement des processus phonologiques simplificateurs qui réduisent les mots à des formes plus simples. L'effacement des consonnes finales (« ga » pour « gâteau »), la réduplication (« dada » pour « cheval »), la substitution de fricatives par des occlusives (« poulette » pour « fourchette »), et la harmonie consonantique (« gogotte » pour « carotte ») sont des processus universels, présents dans toutes les langues. Ces processus disparaissent progressivement entre 2 et 4 ans, à mesure que le système phonologique de l'enfant se complexifie. Leur persistance au-delà de cet âge peut signaler un trouble phonologique.</p>
<div class="highlight-box"><strong>Neutralisation et archiphonème</strong> : La neutralisation est un processus par lequel une opposition phonémique est annulée dans certains contextes. En allemand, les consonnes finales de syllabes se « dévoisent » : /b/, /d/, /g/ deviennent /p/, /t/, /k/ en position finale (Auslautverhärtung). Cette neutralisation est représentée par un archiphonème, symbole de l'opposition neutralisée. En français, l'opposition /e/~/ɛ/ tend à se neutraliser en syllabe ouverte dans de nombreux dialectes.</div>
<h3>Phonologie et orthographe</h3>
<p class="resume-text">Les systèmes d'écriture alphabétiques reposent sur une correspondance entre graphèmes et phonèmes, mais cette correspondance est rarement bijective. L'anglais est célèbre pour ses irrégularités orthographiques : le même graphème peut correspondre à plusieurs phonèmes (« ea » dans « bread », « sea », « break ») et le même phonème peut s'écrire de plusieurs façons (le son /i:/ dans « seat », « see », « ceiling », « field »). Le français, bien qu'historiquement plus régulier, présente lui aussi des complexités (les lettres muettes, les liaisons, les accents). La réforme orthographique est un enjeu sociolinguistique et éducatif majeur dans de nombreuses sociétés.</p>""",

    'morphologie/morphemes': """<h3>Les morphèmes zéro et la morphologie implicite</h3>
<p class="resume-text">La morphologie reconnaît l'existence de morphèmes à réalisation phonologique nulle, appelés morphèmes zéro. En anglais, le pluriel de « sheep » est « sheep » (morphème zéro de pluriel), par opposition à « dogs » (morphème /z/ de pluriel). En français, la marque du pluriel nominal est souvent un morphème zéro à l'oral : « le chat » / « les chats » (même prononciation). Cette notion, apparemment paradoxale (un morphème sans réalisation), est justifiée par la cohérence paradigmatique : l'absence d'une marque dans un contexte où d'autres formes du paradigme en portent une est elle-même significative.</p>
<div class="highlight-box"><strong>Morphèmes discontinus</strong> : Certains morphèmes sont discontinus, c'est-à-dire qu'ils se manifestent en deux parties séparées. En arabe, les racines consonantiques (trilitères) s'intercalent avec des schèmes vocaliques : la racine k-t-b (« écrire ») produit kataba (« il a écrit »), kitab (« livre »), katib (« écrivain »), maktab (« bureau »). Ce type de morphologie non-concaténative pose des défis théoriques à la conception linéaire des morphèmes.</div>
<h3>Frontières de morphèmes et perception lexicale</h3>
<p class="resume-text">La segmentation des mots en morphèmes est une compétence métalinguistique qui se développe avec l'alphabétisation. Les enfants apprennent à analyser des mots comme « improbable » en im- + probable, ou « anticonstitutionnel » en ses constituants morphémiques. Cette conscience morphologique facilite la compréhension de nouveaux mots : quelqu'un qui connaît le préfixe pré- et le mot « voir » peut inférer le sens de « prévoir ». Des recherches en psycholinguistique montrent que les lecteurs compétents accèdent aux morphèmes constituants lors de la reconnaissance des mots complexes, même pour des mots familiers dont ils n'ont jamais analysé la structure.</p>""",

    'morphologie/flexion': """<h3>La flexion et l'accord syntaxique</h3>
<p class="resume-text">La flexion est au service de l'accord syntaxique : elle permet aux mots d'une phrase de manifester leurs relations grammaticales par des marques formelles. En français, l'accord en genre et nombre entre déterminant, adjectif et nom (« les belles fleurs rouges ») est purement syntaxique et redondant — l'information de pluralité n'est portée qu'une fois sémantiquement mais plusieurs fois morphologiquement. Cette redondance sert de sécurité dans la communication et permet la récupération du message même en cas de bruit ou d'inattention. Les langues à accord riche facilitent certains types de traitement syntaxique (la résolution des ambiguïtés de référence pronominale, par exemple) au prix d'un système flexionnel plus complexe à acquérir.</p>
<div class="highlight-box"><strong>Déclin de la flexion en histoire des langues</strong> : L'évolution historique des langues montre souvent une tendance à la réduction de la flexion. Le latin avait 6 cas et 3 genres. Le français médiéval avait encore 2 cas (nominatif/régime). Le français moderne a éliminé les cas nominaux. Cette tendance analytique (remplacement de la morphologie flexionnelle par des auxiliaires et prépositions) est observable dans de nombreuses familles linguistiques. Cependant certaines langues maintiennent des systèmes flexionnels complexes depuis des millénaires.</div>
<h3>Paradigmes flexionnels et irrégularités</h3>
<p class="resume-text">Les paradigmes flexionnels présentent presque universellement des irrégularités qui résistent à la régularisation. Les verbes les plus fréquents d'une langue tendent à être les plus irréguliers : en français, « être », « avoir », « aller », « faire » ; en anglais, « be », « have », « go », « do ». Cette corrélation entre fréquence et irrégularité s'explique par le fait que les formes très fréquentes sont apprises et stockées comme unités individuelles plutôt que par règle générative, et qu'elles résistent mieux à l'analogie uniformisatrice. La fréquence élevée assure que les locuteurs entendent et utilisent régulièrement les formes irrégulières, les préservant de la régularisation.</p>""",

    'morphologie/derivation': """<h3>La productivité dérivationnelle et ses limites</h3>
<p class="resume-text">Tous les affixes dérivationnels ne sont pas également productifs. En français, le suffixe -tion (formation, réalisation, organisation) est extrêmement productif et peut théoriquement s'attacher à presque tout verbe. En revanche, le suffixe -eur dans son sens d'agent (lecteur, chanteur, conducteur) est productif mais présente des contraintes : il ne s'attache qu'à certaines bases verbales. La productivité d'un affixe peut varier au cours du temps : certains affixes autrefois productifs deviennent « fossiles » (le préfixe mé- dans « méfait », « méchant »). Mesurer la productivité morphologique — avec des indices comme la proportion de hapax legomena (mots n'apparaissant qu'une fois dans un corpus) — est un champ actif de la morphologie quantitative.</p>
<div class="highlight-box"><strong>Dérivation et changement sémantique</strong> : Les dérivés développent souvent des sens qui s'éloignent du mot de base. « Libraire » n'est plus seulement « qui s'occupe de livres » mais désigne spécifiquement un commerçant. « Musique » a engendré « musicien », « musical », « musicologie », « musicalité » — chacun avec son propre champ sémantique. Ce phénomène de spécialisation ou généralisation sémantique des dérivés explique pourquoi la dérivation ne produit pas toujours des sens parfaitement compositionnels.</div>
<h3>Morphologie dérivationnelle et créativité lexicale</h3>
<p class="resume-text">La dérivation est l'un des principaux moteurs de la créativité lexicale dans les langues modernes. L'explosion technologique du XXe siècle a nécessité la création de milliers de termes : « informatisation », « numérisation », « désindustrialisation », « mondialisation » utilisent tous le suffixe -isation pour convertir des bases nominales en noms d'action. Les néologismes morphologiques obéissent à des règles : ils ne sont pas arbitraires mais respectent les contraintes de sélection des affixes. L'étude de ces néologismes révèle les règles implicites que les locuteurs appliquent inconsciemment et les zones de productivité active du système morphologique.</p>""",

    'morphologie/composition': """<h3>La composition en langue de spécialité</h3>
<p class="resume-text">Les langues de spécialité (sciences, technique, médecine, droit) recourent massivement à la composition pour créer une terminologie précise. La terminologie médicale combine des éléments greco-latins : cardiologie (cœur + étude), ostéoporose (os + porosité), gastroentérologie. La terminologie informatique crée des composés hybrides : wi-fi, web-design, open-source. Ces formations témoignent de la flexibilité des processus compositionnels et de leur capacité à s'adapter aux besoins terminologiques des domaines techniques. L'Union Européenne dispose d'un réseau de terminologues (IATE — Interactive Terminology for Europe) qui normalise et harmonise ces créations néologiques.</p>
<div class="highlight-box"><strong>Composition exocentrique</strong> : Les composés endocentriques ont une tête qui détermine leur catégorie sémantique (« porte-monnaie » est un type de porte-quelque-chose). Mais les composés exocentriques n'ont pas de tête explicite : un « rouge-gorge » n'est pas un type de gorge rouge, c'est un oiseau caractérisé par sa gorge rouge. Ces composés bahuvrihi (terme sanskrit signifiant « dont le riz est abondant », c'est-à-dire « riche ») posent des défis pour l'analyse compositionnelle et montrent que les sens des composés ne sont pas toujours pleinement compositionnels.</div>
<h3>Les mots-valises et la créativité morphologique</h3>
<p class="resume-text">Les mots-valises (portmanteau words) sont des créations qui fusionnent deux mots en tronquant l'un ou les deux : « brunch » (breakfast + lunch), « courriel » (courrier + électronique), « informatique » (information + automatique), « franglais » (français + anglais). Ces formations hybrides occupent une place à la frontière entre composition et troncation. Très présents dans le langage informel et les néologismes médiatiques, ils reflètent une créativité morphologique jouant sur les structures sonores et sémantiques simultanément. Lewis Carroll (Alice au pays des merveilles) en était un maître : « galimafré » (galloping + triumphant), et Humpty Dumpty explique à Alice la logique de ces « mots-portmanteau ».</p>""",

    'morphologie/typologie-morphologique': """<h3>Continuum typologique et langues mixtes</h3>
<p class="resume-text">La classification morphologique des langues en types purs (isolant, agglutinant, fusionnel, incorporant) est une simplification : toutes les langues présentent des caractéristiques mixtes. Le français est principalement analytique-isolant (nombreuses structures à auxiliaires) mais conserve des éléments fusionnels dans sa morphologie verbale. L'anglais était autrefois nettement fusionnel (comme l'allemand moderne) et a évolué vers plus d'isolement. Ces transitions rappellent que les types morphologiques ne sont pas des catégories fixes mais des points sur un continuum, et que les langues évoluent d'un type vers un autre au cours de leur histoire.</p>
<div class="highlight-box"><strong>Indice synthétique</strong> : Le morphologue Joseph Greenberg (1915-2001) a proposé des indices quantitatifs pour mesurer le type morphologique. L'indice de synthèse mesure le rapport morphèmes/mots dans un corpus : un indice proche de 1 indique une langue isolante (un morphème par mot), un indice élevé (3-4) indique une langue polysynthétique. Ces mesures permettent des comparaisons quantitatives plus précises que les typologies qualitatives traditionnelles.</div>
<h3>Morphologie et traitement automatique du langage naturel</h3>
<p class="resume-text">La complexité morphologique d'une langue a des implications directes pour le traitement automatique du langage naturel (TALN). Les langues morphologiquement complexes comme le turc, le finnois ou l'arabe posent des défis spécifiques pour la lemmatisation (réduction à la forme de base), l'analyse en parties du discours, et la traduction automatique. Une forme verbale turque peut encoder en un seul mot l'information que plusieurs mots séparés exprimeraient en anglais. Les morphologues computationnels ont développé des analyseurs morphologiques basés sur des transducteurs à états finis qui décomposent ces formes complexes en leurs constituants morphémiques.</p>""",

    'syntaxe/constituants-syntagmes': """<h3>Les tests syntaxiques de constituance</h3>
<p class="resume-text">Les linguistes utilisent plusieurs tests opérationnels pour identifier les constituants syntaxiques d'une phrase. Le test de commutation (substitution d'un groupe par un pronom : « les étudiants travaillent » → « ils travaillent ») montre que « les étudiants » est un constituent. Le test de déplacement (topicalisation, clivage) : « C'est les étudiants qui travaillent » montre que « les étudiants » peut être extrait comme unité. Le test de coordination : « les étudiants et les professeurs travaillent » montre que deux syntagmes nominaux peuvent être coordonnés. L'application systématique de ces tests permet de vérifier empiriquement les hypothèses sur la structure des phrases.</p>
<div class="highlight-box"><strong>Syntagmes non-projectifs</strong> : Dans la plupart des théories, un syntagme est projectif : tous ses éléments forment un bloc continu dans la chaîne linéaire. Mais certaines constructions semblent violer ce principe : la dislocation à gauche en français (« Le livre, je l'ai lu ») ou les constructions à longue distance. Ces phénomènes ont alimenté des débats théoriques majeurs sur la représentation de la structure syntaxique.</div>
<h3>Syntagmes et ambiguïté structurale</h3>
<p class="resume-text">L'ambiguïté structurale illustre l'importance de la constituency : une même séquence de mots peut avoir deux analyses en constituants différentes, donnant deux significations distinctes. « J'ai vu l'homme avec le télescope » est ambigu : ai-je utilisé le télescope pour voir l'homme, ou ai-je vu un homme qui portait un télescope ? L'ambiguïté tient à l'attachement du syntagme prépositionnel « avec le télescope » : il peut s'attacher au verbe « voir » (complément circonstanciel) ou au syntagme nominal « l'homme » (complément du nom). Ces ambiguïtés, exploitées par l'humour et la publicité, révèlent la richesse structurale des langues naturelles.</p>""",

    'syntaxe/fonctions-syntaxiques': """<h3>Fonctions syntaxiques et marquage casuel</h3>
<p class="resume-text">Les fonctions syntaxiques — sujet, objet direct, objet indirect — sont exprimées différemment selon les langues. Les langues à cas (latin, russe, allemand, finnois) les marquent morphologiquement sur les groupes nominaux eux-mêmes. Les langues analytiques (français, anglais) les marquent par l'ordre des mots et les prépositions. Cette distinction entre langues nominatif-accusatif (où le sujet d'un verbe transitif et le sujet d'un verbe intransitif sont marqués pareil) et langues ergatif-absolutif (où l'objet d'un transitif et le sujet d'un intransitif partagent la même marque) reflète des organisations fonctionnelles profondes de l'information dans la phrase.</p>
<div class="highlight-box"><strong>Diathèse et alternances argumentales</strong> : La voix passive transforme la structure argumentale d'un verbe transitif : l'objet devient sujet, le sujet devient complément d'agent optionnel. Ces alternances diathétiques (actif/passif, moyen, causatif, réfléchi) permettent de profiler différents participants de l'événement selon leur importance informationnelle. Le passif en particulier permet d'omettre l'agent (stratégie de dépersonnalisation prisée dans les textes bureaucratiques et scientifiques).</div>
<h3>La structure informationnelle et les fonctions pragmatiques</h3>
<p class="resume-text">Au-delà des fonctions purement syntaxiques, les phrases organisent l'information selon des fonctions pragmatiques : thème (ce dont on parle) vs rhème (ce qu'on en dit), donné (information connue) vs nouveau (information nouvelle). Ces distinctions se manifestent syntaxiquement par l'ordre des mots, les constructions de topicalisation, les clivées, l'accentuation prosodique. En français, la dislocation à gauche (« Le livre, je l'ai lu ») thématise l'élément déplacé. Ces constructions permettent aux locuteurs d'organiser leur message en tenant compte de ce que l'interlocuteur sait déjà.</p>""",

    'syntaxe/grammaire-generative': """<h3>Le programme minimaliste de Chomsky</h3>
<p class="resume-text">Depuis les années 1990, le programme minimaliste (Chomsky 1995) cherche à réduire la grammaire générative à ses éléments essentiels, en posant la question : qu'est-ce que le langage humain doit nécessairement avoir pour remplir ses fonctions d'interface avec la pensée et avec les systèmes externalisés (phonologie et sens) ? Le programme minimise les opérations syntaxiques à une seule opération fondamentale, Merge (fusion), qui combine deux éléments syntaxiques en une unité plus grande. Cette économie théorique vise à expliquer les propriétés du langage humain par des principes de computation optimale, en dialogue avec les sciences cognitives et la biologie évolutive du langage.</p>
<div class="highlight-box"><strong>Paramètres et variation typologique</strong> : La théorie Principes & Paramètres explique la variation entre langues par des paramètres binaires (on/off) que l'enfant fixe sur la base de l'input. Le paramètre du sujet nul (pro-drop) distingue l'espagnol et l'italien (qui admettent les phrases sans sujet lexical : « Parla italiano ») du français et l'anglais (qui l'exigent). Ce cadre permet de connecter l'acquisition du langage (l'enfant fixe les paramètres) et la grammaire comparée (les langues diffèrent par leurs valeurs paramétriques).</div>
<h3>Critiques et alternatives à la grammaire générative</h3>
<p class="resume-text">La grammaire générative a suscité des critiques majeures depuis les années 1970. Les fonctionnalistes (Simon Dik, Talmy Givón) reprochent à Chomsky d'abstraire la syntaxe de son contexte communicatif : la structure des phrases ne peut être comprise indépendamment de leurs fonctions dans l'interaction. Les cognitivistes (Ronald Langacker, Leonard Talmy) critiquent la séparation entre syntaxe et sémantique, et proposent une Grammaire Cognitive où les structures syntaxiques sont des constructions symboliques intégrant forme et signification. La Construction Grammar (Adele Goldberg) développe cette approche en proposant que la grammaire est un réseau de constructions — des paires forme-sens appris directement.</p>""",

    'syntaxe/subordination-coordination': """<h3>Types de subordination et iconicité syntaxique</h3>
<p class="resume-text">La subordination comprend plusieurs types selon le rôle de la subordonnée dans la phrase principale. Les complétives (« Je crois que tu as raison ») fonctionnent comme objet du verbe principal. Les relatives (« L'homme que j'ai vu ») modifient un syntagme nominal. Les circonstancielles (temporelles, causales, conditionnelles, concessives) expriment des relations adverbiales. Ces types de subordination ont des propriétés syntaxiques très différentes : les relatives sont contraintes par l'Îlot-relative (impossibilité d'extraire un élément d'une relative), les complétives suivent des contraintes liées au mode verbal (indicatif ou subjonctif en français).</p>
<div class="highlight-box"><strong>Parataxe et hypotaxe</strong> : La parataxe (juxtaposition de propositions sans marqueur explicite) et l'hypotaxe (subordination explicitement marquée) sont deux stratégies de construction du discours. Le style paratactique est associé aux registres oraux et narratifs populaires (« Il est parti, il a oublié ses clefs »). Le style hypotactique est associé aux registres écrits et formels (« Étant parti sans vérifier, il avait oublié ses clefs »). Cette variation stylistique reflète des différences dans les exigences cognitives de traitement et dans les conventions rhétoriques des genres discursifs.</div>
<h3>Connecteurs discursifs et cohérence textuelle</h3>
<p class="resume-text">Au niveau du texte, la coordination et la subordination contribuent à la cohérence discursive. Les connecteurs (« donc », « cependant », « en effet », « par conséquent ») marquent les relations logiques entre propositions et segments du texte. La théorie de la rhétorique du discours (Rhetorical Structure Theory, Mann & Thompson 1988) analyse les textes comme des structures hiérarchiques de relations rhétoriques (élaboration, justification, contraste, etc.). Cette approche a des applications en traitement automatique du texte (résumé automatique, analyse de sentiment, cohérence textuelle) et en pédagogie de l'écriture.</p>""",

    'syntaxe/ordre-mots-universaux': """<h3>L'ordre des mots et la théorie des universaux</h3>
<p class="resume-text">Joseph Greenberg, dans son article fondateur de 1963, a établi 45 universaux de l'ordre des mots sur la base d'un échantillon de 30 langues. Ses universaux implicationnels indiquent des corrélations statistiques : si une langue est SOV (objet avant verbe), alors ses postpositions sont plus probables que ses prépositions. Si une langue est VSO, alors ses adjectifs suivent probablement le nom. Ces corrélations reflètent un principe de cohérence typologique (harmonie des têtes) : les langues tendent à placer systématiquement les têtes syntaxiques avant ou après leurs compléments. Ce principe d'harmonie a une explication fonctionnelle (facilite le traitement incrémental de la phrase) et une explication formelle (correspond à un paramètre unique dans certaines théories).</p>
<div class="highlight-box"><strong>Ordre des mots en évolution</strong> : L'ordre des mots change au cours du temps. L'anglais moderne (SVO) est issu de l'anglais ancien (SOV comme l'allemand actuel). Ce changement, qui a commencé aux alentours du XIe siècle, est associé à la simplification de la morphologie casuelle anglo-saxonne : quand les marques de cas ont disparu, l'ordre des mots est devenu le principal marqueur des relations grammaticales. Ce changement illustre une interdépendance typologique entre morphologie et syntaxe.</div>
<h3>L'ordre des mots pragmatiquement conditionné</h3>
<p class="resume-text">Dans de nombreuses langues, l'ordre des mots n'est pas uniquement déterminé par des facteurs grammaticaux mais aussi par des facteurs pragmatiques et informationnels. En japonais ou en latin, l'ordre des constituants majeurs est relativement libre, mais les locuteurs placent tendanciellement les éléments connus en début et les éléments nouveaux en fin de proposition. Ces variations s'expliquent par des principes de structure informationnelle : thème avant rhème, donné avant nouveau. La distinction entre langues à ordre libre (où l'ordre est pragmatiquement conditionné) et langues à ordre fixe (où l'ordre est grammaticalement contraint) est une dimension typologique majeure.</p>""",

    'semantique/sens-reference': """<h3>Théories de la référence et noms propres</h3>
<p class="resume-text">La philosophie du langage a développé plusieurs théories de la référence pour les noms propres. La théorie descriptiviste (Frege, Russell) soutient que les noms propres sont des descriptions abrégées : « Aristote » signifie quelque chose comme « le philosophe grec qui a enseigné Alexandre le Grand ». La théorie causaliste-historique (Saul Kripke, dans Naming and Necessity, 1972) argumente que les noms propres sont des désignateurs rigides : « Aristote » désigne la même personne dans tous les mondes possibles, indépendamment de ses propriétés. Cette théorie a des conséquences importantes pour la compréhension de l'identité, de la nécessité et de l'essence.</p>
<div class="highlight-box"><strong>Sens et signification : Frege</strong> : La distinction fregeenne entre Sinn (sens) et Bedeutung (référence) reste fondamentale. « L'étoile du matin » et « l'étoile du soir » ont la même Bedeutung (Vénus) mais un Sinn différent (le mode de présentation est différent). Cette distinction explique l'asymétrie de l'identité : « L'étoile du matin est l'étoile du soir » est informatif (une découverte empirique), alors que « L'étoile du matin est l'étoile du matin » est trivial (tautologie analytique).</div>
<h3>Présuppositions et implicatures</h3>
<p class="resume-text">La sémantique distingue le contenu asserté d'un énoncé de ses présuppositions (contenus tenus pour acquis, qui ne sont pas annulés par la négation) et de ses implicatures (contenus inférés). « Jean a arrêté de fumer » présuppose que Jean fumait : la présupposition survit à la négation (« Jean n'a pas arrêté de fumer » présuppose aussi qu'il fumait). Les implicatures conversationnelles de Grice (1975) sont des inférences liées aux principes de coopération : « Peux-tu passer le sel ? » implique conventionnellement une requête, bien que la signification littérale soit une question sur les capacités physiques.</p>""",

    'semantique/relations-lexicales': """<h3>Les réseaux lexicaux et WordNet</h3>
<p class="resume-text">WordNet, créé par George Miller et Christiane Fellbaum à Princeton dans les années 1980-90, est une base de données lexicale qui organise les mots en synsets (ensembles de synonymes) reliés par des relations sémantiques : hyperonymie, hyponymie, méronymie, antonymie. Traduit ou adapté en une quarantaine de langues (EuroWordNet, WOLF pour le français), WordNet est devenu une ressource fondamentale du traitement automatique du langage naturel : désambiguïsation lexicale, expansion de requêtes, mesures de similarité sémantique. Son architecture en réseau sémantique a influencé les modèles de la mémoire sémantique en psychologie cognitive.</p>
<div class="highlight-box"><strong>Polysémie vs homonymie</strong> : La distinction entre polysémie (un mot avec plusieurs sens liés) et homonymie (deux mots différents de même forme) est théoriquement importante mais empiriquement difficile à tracer. « Feuille » (de papier vs d'arbre) est-il polysémique ou homonyme ? Les critères incluent : l'étymologie commune (polysémie), la motivation sémantique perçue (polysémie), la divergence de traductions dans d'autres langues (homonymie). Les dictionnaires tranchent souvent empiriquement sans critère uniformisé.</div>
<h3>Les champs lexicaux et l'organisation du vocabulaire</h3>
<p class="resume-text">La théorie des champs lexicaux (Wörter und Sachen, Jost Trier 1931) postule que le vocabulaire d'une langue s'organise en champs sémantiques cohérents où les mots se délimitent mutuellement. La façon dont différentes langues découpent un domaine sémantique révèle leur organisation cognitive : le champ des couleurs (Berlin et Kay, 1969), des termes de parenté, des verbes de mouvement. Les études translinguistiques sur ces découpages lexicaux ont contribué au débat sur le relativisme linguistique : la structure du vocabulaire d'une langue influence-t-elle la perception et la pensée de ses locuteurs ?</p>""",

    'semantique/semantique-phrase': """<h3>La compositionnalité et ses limites</h3>
<p class="resume-text">Le principe de compositionnalité (principe de Frege) stipule que le sens d'une expression complexe est une fonction du sens de ses parties et de leur mode de combinaison. Ce principe est au fondement de la sémantique formelle et permet d'expliquer comment les locuteurs comprennent des phrases qu'ils n'ont jamais entendues. Mais il a des limites : les expressions idiomatiques (« casser les pieds », « avoir le cafard ») ne respectent pas la compositionnalité, leur sens étant non dérivable des sens des mots qui les composent. Les constructions métaphoriques conventionnalisées (« le temps passe ») non plus. La sémantique doit donc combiner compositionnalité et mécanismes non compositionnels.</p>
<div class="highlight-box"><strong>Sémantique vériconditionnelle</strong> : La sémantique formelle, issue de la logique (Frege, Tarski, Montague), analyse le sens des phrases par leurs conditions de vérité : connaître le sens de « Il pleut » c'est savoir dans quelles circonstances cette phrase est vraie. Cette approche, prolongée par la Grammaire de Montague, a permis un traitement formel rigoureux des quantificateurs, des modaux et des temps verbaux, mais elle a été critiquée pour négliger les dimensions pragmatiques et cognitives du sens.</div>
<h3>Sémantique des événements et la structure aspectuelle</h3>
<p class="resume-text">La sémantique des événements (Donald Davidson) analyse les propositions comme quantifiant sur des événements : « Jean a couru rapidement dans le parc » est analysé comme « il existe un événement de course, dont Jean est l'agent, qui s'est passé dans le parc, et qui était rapide ». Cette décomposition permet de rendre compte compositionnellement des adverbes et des compléments circonstanciels. La structure aspectuelle (Aktionsart) distingue les prédicats statifs (savoir), activités (courir), accomplissements (construire une maison), et achèvements (trouver une clé), avec des propriétés aspectuelles différentes (compatibilité avec des progressifs, des compléments de durée, etc.).</p>""",

    'semantique/metaphore-metonymie': """<h3>La théorie conceptuelle de la métaphore</h3>
<p class="resume-text">George Lakoff et Mark Johnson, dans Metaphors We Live By (1980), ont montré que les métaphores ne sont pas des ornements stylistiques mais des structures conceptuelles fondamentales qui organisent notre pensée. La métaphore conceptuelle LE TEMPS C'EST DE L'ARGENT se manifeste dans des expressions comme « perdre du temps », « gagner du temps », « investir son temps », « économiser du temps ». Ces métaphores orientationnelles (LE BON C'EST EN HAUT : « il est au sommet de sa carrière »), structurales (LA VIE EST UN VOYAGE) et ontologiques (personnification) révèlent comment nous comprenons des domaines abstraits en termes de domaines concrets plus familiers.</p>
<div class="highlight-box"><strong>Métaphore morte et motivation lexicale</strong> : Les métaphores meurent quand leur image source n'est plus perçue : « comprendre » (saisir par l'esprit) vient du latin comprehendere (saisir physiquement), métaphore aujourd'hui opaque. La lexicalisation efface progressivement la conscience de la motivation métaphorique originale. L'étymologie retrouve ces métaphores mortes et révèle comment le vocabulaire abstrait s'est construit sur des bases concrètes et corporelles.</div>
<h3>Métaphore et traitement automatique</h3>
<p class="resume-text">La détection et l'interprétation automatique des métaphores est un défi majeur pour le traitement automatique du langage naturel. Les systèmes doivent distinguer les emplois littéraux des emplois métaphoriques (« l'entreprise a coulé » = a sombré financièrement vs a coulé physiquement), interpréter des métaphores nouvelles jamais vues, et comprendre comment les métaphores contribuent au sens global d'un texte. Des corpus annotés (VU Amsterdam Metaphor Corpus, MIPVU) ont permis le développement de systèmes automatiques. Les grands modèles de langue (LLM) semblent avoir acquis implicitement une sensibilité aux métaphores conventionnelles, mais restent limités pour les métaphores créatives.</p>""",

    'semantique/pragmatique': """<h3>La pragmatique et la communication intentionnelle</h3>
<p class="resume-text">La pragmatique s'intéresse à comment les locuteurs communiquent plus que ce qu'ils disent littéralement. La théorie de la pertinence (Sperber et Wilson, 1986) propose que la communication humaine est fondamentalement un processus d'inférence : le locuteur crée une intention d'informer manifeste, et l'interlocuteur cherche l'interprétation la plus pertinente en minimisant son effort cognitif et en maximisant les effets cognitifs. Cette théorie unifie la pragmatique autour d'un seul principe (la pertinence) et explique l'implicite, le métaphorique, l'ironique comme des cas d'une même stratégie inférentielle.</p>
<div class="highlight-box"><strong>Les actes de langage indirects</strong> : Les actes de langage indirects (Searle) sont des énoncés dont la force illocutoire réelle diffère de la forme syntaxique. « Tu peux me passer le sel ? » est syntaxiquement une question (sur les capacités de l'interlocuteur) mais pragmatiquement une requête. Ces décalages forment/fonction sont conventionnalisés dans chaque langue et culture. Leur maîtrise est cruciale pour la politesse : les requêtes directes (impératif) peuvent être perçues comme impolis là où une forme indirecte est attendue.</div>
<h3>Pragmatique interactionnelle et analyse de la conversation</h3>
<p class="resume-text">L'analyse de la conversation (Harvey Sacks, Emmanuel Schegloff, Gail Jefferson) étudie les mécanismes de l'interaction en face-à-face comme un système organisé : la prise de tours de parole, les séquences question-réponse, les réparations (corrections de malentendus), les organisations préférentielles (préférence pour l'acceptation sur le refus dans les paires adjacentes d'invitation/réponse). Ces mécanismes sont largement universels mais varient dans leurs réalisations culturelles. Cette tradition, née aux États-Unis dans les années 1960-70, a influencé l'analyse du discours, la sociolinguistique interactionnelle et la pragmatique interculturelle.</p>""",

    'sociolinguistique/variation-linguistique': """<h3>La sociolinguistique variationniste</h3>
<p class="resume-text">La sociolinguistique variationniste, fondée par William Labov dans les années 1960-70, étudie les relations systématiques entre variables sociales (classe, âge, genre, appartenance ethnique) et variables linguistiques. Les études classiques de Labov à New York (1966) et à Martha's Vineyard (1963) ont montré que la variation linguistique n'est pas aléatoire mais corrélée avec des facteurs sociaux précis. La méthode quantitative — coding des variantes dans de grands corpus de parole spontanée — permet d'identifier des règles variables statistiques. Cette approche a révolutionné la linguistique en montrant que l'hétérogénéité de la langue est structurée et systématique.</p>
<div class="highlight-box"><strong>Style et formalité</strong> : Les locuteurs adaptent leur façon de parler au contexte : style formel (entretien, discours public) vs style informel (conversation entre amis). Labov a montré que cette variation stylistique est corrélée avec le degré d'attention portée à la parole. En style surveillé (lecture de liste de mots), les locuteurs utilisent plus de formes prestige ; en style relâché (récit d'accident de voiture), les formes vernaculaires ressurgissent. Cette instabilité stylistique révèle la conscience linguistique des locuteurs et leur rapport aux normes sociales.</div>
<h3>Variation et identité sociale</h3>
<p class="resume-text">Les variables sociolinguistiques sont des ressources symboliques que les locuteurs mobilisent pour construire leur identité sociale. Les travaux de Penelope Eckert (Jocks and Burnouts, 1989) sur les adolescents d'une banlieue américaine montrent comment les choix phonologiques et lexicaux marquent l'appartenance à des groupes sociaux (sportifs populaires vs rebelles). Cette perspective interactionniste voit la variation non comme le simple reflet d'une appartenance sociale préétablie, mais comme une pratique active de positionnement identitaire. Le concept de Community of Practice (communauté de pratique) capture ces dynamiques groupales mieux que les catégories sociales traditionnelles.</p>""",

    'sociolinguistique/contact-langues': """<h3>Les langues mixtes et les créoles</h3>
<p class="resume-text">Les créoles sont des langues nées du contact entre une langue de superstrat (généralement européenne, langue des colonisateurs) et des langues de substrat (langues des esclaves ou des populations colonisées). Le créole haïtien, le créole réunionnais, le tok pisin de Papouasie-Nouvelle-Guinée : ces langues se sont stabilisées en une ou deux générations à partir de pidgins (langues de contact simplifiées sans locuteurs natifs). La théorie bioprogramme de Derek Bickerton soutient que les similitudes structurales entre créoles distants témoignent d'une grammaire universelle innée qui se manifeste quand la transmission linguistique est perturbée — thèse aujourd'hui contestée mais intellectuellement stimulante.</p>
<div class="highlight-box"><strong>Code-switching</strong> : L'alternance codique (code-switching) désigne le passage d'une langue à l'autre au sein d'une même interaction ou même phrase. « J'ai been waiting for you depuis des heures » mêle l'anglais et le français dans des patterns syntaxiquement cohérents. Le code-switching est une compétence communicative des bilingues, pas un signe de confusion ou d'incompétence. Il obéit à des règles grammaticales précises (les points de commutation correspondent aux frontières syntaxiques) et à des fonctions pragmatiques (marquer l'appartenance groupale, citer, commenter, etc.).</div>
<h3>Emprunts et calques dans les langues du monde</h3>
<p class="resume-text">Le contact linguistique produit des emprunts lexicaux (adoption d'un mot étranger : « weekend », « sushi », « wifi ») et des calques (traduction structurale d'une expression étrangère : « gratte-ciel » calque de l'américain « skyscraper », « ordinateur » calque de « computer »). La résistance aux emprunts varie selon les politiques linguistiques : l'Académie française recommande des néologismes français (« courriel » pour « email »), avec un succès limité face aux emprunts spontanés. L'islandais est célèbre pour sa politique puriste de création de néologismes natifs : « tölva » (ordinateur = chiffre + prophétesse), « sími » (téléphone = fil).</p>""",

    'sociolinguistique/politique-linguistique': """<h3>L'aménagement linguistique et ses instruments</h3>
<p class="resume-text">L'aménagement linguistique (language planning) comprend la planification du corpus (standardisation de l'orthographe, de la grammaire, du vocabulaire) et la planification du statut (décision sur les fonctions officielles et sociales des langues). Les organismes de normalisation — Académie française (fondée 1635), Office québécois de la langue française, Institut Cervantes — jouent un rôle institutionnel dans la régulation du corpus. Mais la planification du statut est souvent plus décisive : reconnaître une langue comme officielle, l'enseigner dans les écoles, l'utiliser dans l'administration, sont des décisions politiques qui peuvent sauver ou condamner une langue minoritaire.</p>
<div class="highlight-box"><strong>Revitalisation linguistique</strong> : La revitalisation du gallois au Royaume-Uni est considérée comme un modèle. Enseignement bilingue obligatoire au pays de Galles, chaîne de télévision galloise S4C, soutien à la production culturelle, enseignes bilingues : ces mesures ont contribué à stabiliser, voire augmenter, le nombre de locuteurs gallois. En revanche, la revitalisation de l'irlandais en République d'Irlande est moins concluante malgré un soutien institutionnel massif — montrant que les politiques linguistiques ne peuvent seules inverser le déclin d'une langue sans dynamique communautaire.</div>
<h3>Multilinguisme institutionnel</h3>
<p class="resume-text">L'Union Européenne est la principale organisation internationale multilingue du monde, avec 24 langues officielles de travail. Le coût de la traduction et de l'interprétation représente environ 1% du budget de l'UE. Ce multilinguisme institutionnel pose des questions de politique interne (quelles langues de travail réelles dans les couloirs ?) et de symbolique politique (égalité des langues et des peuples). La question de la langue commune de communication — souvent l'anglais de facto — crée des asymétries entre locuteurs natifs et non-natifs. Après le Brexit, la place de l'anglais dans les institutions européennes est devenue paradoxalement plus questionnée.</p>""",

    'sociolinguistique/langue-identite': """<h3>Diglossie et hiérarchies linguistiques</h3>
<p class="resume-text">La diglossie (Charles Ferguson, 1959 ; Joshua Fishman, 1967) désigne la coexistence de deux variétés d'une même langue (ou de deux langues différentes) dans une communauté, avec une répartition fonctionnelle : variété H (haute, formelle, prestige) pour les contextes officiels, écrits, religieux ; variété B (basse, familière, vernaculaire) pour la conversation quotidienne. L'arabe classique vs arabes dialectaux, le mandarin standard vs dialectes régionaux chinois, l'allemand standard vs dialectes suisses-alémaniques : ces situations diglossiques impliquent des représentations sociales différenciées des variétés, généralement positives pour H et négatives pour B — même si B est la variété affectivement la plus proche.</p>
<div class="highlight-box"><strong>Idéologies linguistiques</strong> : Les idéologies linguistiques sont des croyances et représentations sur les langues, leurs locuteurs et leur valeur sociale, qui légitiment des pratiques et des hiérarchies. L'idéologie du « standard unique » (une nation = une langue = une identité) légitime la stigmatisation des dialectes et des langues régionales. Ces idéologies sont souvent naturalistes (présentant des constructions sociales comme des faits naturels) et ont des conséquences politiques réelles sur l'éducation et les droits linguistiques.</div>
<h3>Langues et mobilisations nationalistes</h3>
<p class="resume-text">Les langues ont été au cœur des mobilisations nationalistes depuis le XIXe siècle. La standardisation du tchèque contre l'allemand des Habsbourg, la résistance du catalan sous Franco, le réveil du basque ou du breton : ces cas montrent comment la langue devient un symbole de résistance identitaire et de revendication politique. Mais le lien langue-nation n'est pas naturel : la Suisse multilingue maintient une identité nationale forte, le swahili est langue nationale de plusieurs États africains sans être la langue maternelle de la majorité. Les constructions idéologiques du lien langue-identité sont donc des choix politiques, non des nécessités sociolinguistiques.</p>""",

    'sociolinguistique/changement-linguistique': """<h3>Les mécanismes internes du changement phonétique</h3>
<p class="resume-text">Les changements phonétiques réguliers (lois phonétiques des néogrammairiens) s'expliquent en partie par des tendances articulatoires universelles : assimilation (les sons tendent à ressembler aux sons voisins), réduction en position atone, élision des segments peu saillants. La Loi de Grimm, qui explique le passage du proto-indo-européen aux langues germaniques (p → f, t → θ, k → h), est un changement en chaîne (chain shift) où la modification d'un phonème entraîne des modifications en cascade. Les changements vocaliques en chaîne documentés par Labov (Northern Cities Vowel Shift, Great Vowel Shift anglais) illustrent ces dynamiques systémiques.</p>
<div class="highlight-box"><strong>Grammaticalisation</strong> : La grammaticalisation est le processus par lequel des mots de contenu lexical deviennent des morphèmes grammaticaux. Le verbe « aller » (aller physiquement) est devenu en français un auxiliaire du futur proche (« je vais partir ») — grammaticalisation du mouvement en futurité, processus documenté dans des dizaines de langues. Le participe « ayant » a donné « quoique », « having » anglais a donné « -ing ». Ces trajectoires de grammaticalisation sont en partie universelles, révélant des tendances communes dans l'évolution des structures grammaticales.</div>
<h3>Changement linguistique et réseaux sociaux</h3>
<p class="resume-text">Lesley et James Milroy (Language and Social Networks, 1980) ont montré que la densité et la multiplicité des réseaux sociaux d'un individu sont corrélées avec sa résistance ou son adhésion aux changements linguistiques. Les individus à réseaux denses et multiplex (liés à des personnes qui se connaissent entre elles dans plusieurs contextes) tendent à maintenir les variétés locales. Les individus à réseaux lâches (liés à des personnes qui ne se connaissent pas entre elles, dans des contextes diversifiés) sont plus exposés aux innovations et les diffusent. Ces travaux ont connecté la sociolinguistique variationniste à la sociologie des réseaux.</p>""",

    'acquisition-langage/etapes-acquisition': """<h3>L'acquisition de la morphosyntaxe</h3>
<p class="resume-text">L'acquisition de la morphosyntaxe suit des stades relativement universels, avec des variations selon la langue apprise. En français, les enfants commencent par les verbes à l'infinitif et au présent simple avant d'acquérir les temps du passé (passé composé avant imparfait) et du futur. Les articles définis apparaissent avant les articles indéfinis. L'accord en genre (plus difficile) s'acquiert après l'accord en nombre. La morphologie casuelle (dans les langues qui en ont) présente ses propres séquences d'acquisition. Ces séquences reflètent en partie la fréquence dans l'input parental, en partie la complexité morphologique et sémantique des formes.</p>
<div class="highlight-box"><strong>Surgénéralisation des règles</strong> : La surgénéralisation (overregularization) est l'application d'une règle morphologique à des cas irréguliers : « j'ai faisé » au lieu de « j'ai fait », « ils disaient » au lieu de « ils dirent ». Ce phénomène, qui augmente vers 3-4 ans puis diminue, témoigne que l'enfant ne mémorise pas passivement les formes mais élabore activement des règles génératives. Il apparaît souvent après une période d'usage correct des formes irrégulières, révélant une réorganisation du système de règles.</div>
<h3>Input parental et Child Directed Speech</h3>
<p class="resume-text">Le langage adressé aux enfants (Child Directed Speech, CDS, ou « mamanais ») présente des caractéristiques universelles : hauteur de voix plus élevée, débit plus lent, intonation exagérée, phrases plus courtes et plus simples, vocabulaire réduit, nombreuses répétitions. Des recherches ont montré que ces ajustements facilitent l'acquisition : la qualité et la quantité du CDS sont corrélées avec la vitesse d'acquisition du vocabulaire et de la grammaire. Mais les cultures varient : dans certaines sociétés (Samoa, certaines cultures africaines), les adultes ne s'adressent pas directement aux jeunes enfants — et pourtant les enfants acquièrent leur langue normalement, suggérant que le CDS facilite mais n'est pas strictement nécessaire.</p>""",

    'acquisition-langage/theories-acquisition': """<h3>L'approche connexionniste et les modèles de réseau</h3>
<p class="resume-text">Les modèles connexionnistes (Rumelhart & McClelland, 1986) simulent l'acquisition du langage par des réseaux de neurones artificiels qui apprennent des patterns statistiques à partir de l'input sans représentations symboliques explicites. Leur modèle du passé des verbes anglais a montré qu'un réseau pouvait acquérir les verbes irréguliers et réguliers, reproduire la surgénéralisation et son déclin, sans jamais représenter explicitement la règle du passé régulier. Malgré des critiques (Pinker & Prince 1988), ces modèles ont inauguré l'approche statistique de l'acquisition, préfigurant les grands modèles de langue actuels. La tension entre approches à base de règles et approches probabilistes reste un débat central.</p>
<div class="highlight-box"><strong>Nativisme : preuves et contre-preuves</strong> : L'argument principal du nativisme est la pauvreté du stimulus (poverty of the stimulus) : l'enfant acquiert des connaissances linguistiques abstraites (comme la structure dépendante) sur la base d'un input insuffisant pour les induire purement par statistique. Les anti-nativistes répondent que les calculs statistiques sur l'input réel (beaucoup plus riche que ce que Chomsky supposait) permettent d'inférer ces abstractions. Le débat reste ouvert et stimule des recherches empiriques de plus en plus précises sur l'input disponible aux enfants.</div>
<h3>La théorie socio-interactionniste de Vygotski</h3>
<p class="resume-text">Lev Vygotski (1896-1934) a proposé que le développement du langage est fondamentalement social : le langage se développe d'abord dans l'interaction avec les adultes (langage social), puis s'intériorise en langage intérieur (parole pour soi). Son concept de Zone de Développement Proximal (ZDP) désigne ce que l'enfant peut accomplir avec l'aide d'un adulte compétent mais pas encore seul — zone où l'enseignement est le plus efficace. Cette perspective a des conséquences pédagogiques importantes : l'interaction guidée avec un locuteur plus compétent (étayage, scaffolding) accélère le développement linguistique. Cette approche a influencé les méthodologies d'enseignement des langues secondes centrées sur l'interaction.</p>""",

    'acquisition-langage/periode-critique': """<h3>Périodes sensibles et windows d'acquisition</h3>
<p class="resume-text">La notion de période critique a été nuancée en faveur de « périodes sensibles » (sensitive periods) : des fenêtres temporelles où l'apprentissage est optimisé mais pas exclusif. Différents aspects du langage ont des périodes sensibles différentes : la phonologie est la plus contrainte (clôture à la puberté), la morphosyntaxe est moyennement contrainte, le lexique et la pragmatique restent accessibles toute la vie. Les recherches de Patricia Kuhl montrent que les « statistiques phonétiques » de la langue maternelle s'installent entre 6 et 12 mois — précocement mais pas encore à la fermeture définitive. Cette graduation explique pourquoi les apprenants tardifs réussissent mieux en vocabulaire qu'en accent.</p>
<div class="highlight-box"><strong>Le cas des apprenants tardifs</strong> : Les études d'imagerie cérébrale (fMRI) montrent que les bilingues tardifs (ayant appris leur L2 après la puberté) activent des zones légèrement différentes pour leur L2 que pour leur L1, alors que les bilingues précoces (acquisition simultanée) montrent des activations largement superposées. Cette différence neurologique est cependant de taille modeste, et les bilingues tardifs atteignant la fluence native ne sont pas si rares — suggérant que la période critique est un gradient, non une rupture brutale.</div>
<h3>Implications pour l'éducation linguistique</h3>
<p class="resume-text">La recherche sur la période critique a des implications directes pour les politiques éducatives. Elle justifie l'exposition précoce aux langues étrangères dès la maternelle : les enfants acquièrent la phonologie plus facilement avant 7 ans. Elle explique pourquoi les programmes d'immersion (où les enfants sont scolarisés dans une langue seconde) sont particulièrement efficaces pour la phonologie et l'accent. Mais elle nuance aussi les attentes : un adulte apprenant une langue étrangère peut atteindre un niveau très élevé en grammaire et vocabulaire même si l'accent natif lui restera généralement inaccessible. La compétence communicative ne requiert pas d'accent natif.</p>""",

    'acquisition-langage/troubles-langage': """<h3>La dysphasie et les troubles spécifiques du langage</h3>
<p class="resume-text">Les troubles spécifiques du développement du langage (TSDL, anciennement dysphasie) affectent le développement linguistique en l'absence de déficience intellectuelle, de perte auditive, de trouble neurologique acquis ou de trouble envahissant du développement. Les enfants touchés présentent des retards en production et/ou compréhension du langage, des difficultés morphosyntaxiques (usage des temps verbaux, des marqueurs de pluriel), des problèmes de mémoire phonologique à court terme. Ils représentent 7-8% des enfants d'âge préscolaire. La prise en charge orthophonique précoce et intensive est le traitement principal ; les interventions parent-enfant augmentant la qualité et la quantité des interactions langagières ont montré leur efficacité.</p>
<div class="highlight-box"><strong>Aphasie de Broca vs Wernicke</strong> : Les deux syndromes aphasiques classiques illustrent la dissociation entre production et compréhension. L'aphasie de Broca (lésion du gyrus frontal inférieur gauche) : parole non fluente, agrammatisme, compréhension relativement préservée. L'aphasie de Wernicke (lésion du gyrus temporal supérieur gauche) : parole fluente mais paraphasies nombreuses, compréhension très perturbée. Ces dissociations ont soutenu les modèles à double voie du traitement du langage et continuent d'inspirer les théories neurolinguistiques.</div>
<h3>Bégaiement et troubles de la fluence</h3>
<p class="resume-text">Le bégaiement touche environ 1% de la population adulte mondiale, avec une forte prédominance masculine (4:1). Il se manifeste par des répétitions de sons ou syllabes, prolongations et blocages qui interrompent la fluence de la parole. Ses causes sont multifactorielles : génétiques (prédisposition héréditaire clairement établie), neurologiques (différences dans les circuits de production de la parole), et psychologiques (l'anxiété de communication augmente la sévérité). Les traitements incluent la thérapie comportementale (modification de la fluence), la thérapie d'acceptation (réduire la honte et l'évitement), et des médicaments. La stimulation magnétique transcrânienne et les aides électroniques (oreillette de feedback retardé) offrent des perspectives prometteuses.</p>""",

    'acquisition-langage/langage-cerveau': """<h3>Plasticité cérébrale et récupération après lésion</h3>
<p class="resume-text">Le cerveau adulte conserve une plasticité fonctionnelle significative, particulièrement après des lésions acquises. Les patients aphasiques peuvent récupérer des fonctions linguistiques par réorganisation du réseau langagier : l'hémisphère droit peut partiellement suppléer l'hémisphère gauche lésé, des zones périphériques peuvent être recrutées. Cette récupération est favorisée par la rééducation orthophonique intensive, notamment les thérapies basées sur la contrainte et l'induction du mapping (Constraint-Induced Aphasia Therapy). Les neurosciences cognitives cherchent à identifier les biomarqueurs prédictifs de la récupération pour personnaliser les interventions.</p>
<div class="highlight-box"><strong>Neurosciences du bilinguisme</strong> : Les bilingues montrent des différences cérébrales structurales et fonctionnelles par rapport aux monolingues : une densité de matière grise plus élevée dans les zones préfrontales liées au contrôle exécutif, une connectivité renforcée entre régions langagières. Des recherches suggèrent que le bilinguisme retarderait l'apparition des symptômes de la démence d'environ 4-5 ans (hypothèse de la réserve cognitive). Cette hypothèse reste débattue mais soulève la question des bénéfices cognitifs de la gestion de deux systèmes linguistiques.</div>
<h3>Interfaces entre le langage et les autres fonctions cognitives</h3>
<p class="resume-text">Le langage n'est pas un module entièrement isolé mais interagit avec de nombreux systèmes cognitifs. La mémoire de travail phonologique (boucle phonologique de Baddeley) sous-tend l'apprentissage du vocabulaire et la compréhension de phrases longues. Les fonctions exécutives (contrôle inhibiteur, flexibilité) sont cruciales pour le contrôle du langage chez les bilingues. Les émotions modulent le traitement lexical (effet de supériorité des mots émotionnellement chargés). L'attention sélective détermine quels aspects de l'input linguistique sont traités en profondeur. Ces interactions ont des implications pour la rééducation : travailler sur les fonctions exécutives peut améliorer les performances linguistiques, et vice versa.</p>""",
}


def enrich_content(content, new_html):
    quiz_marker = '<section class="content-section" id="quiz">'
    idx = content.find(quiz_marker)
    if idx != -1:
        return content[:idx] + new_html + content[idx:]
    last_section = content.rfind('</section>')
    if last_section != -1:
        return content[:last_section] + new_html + content[last_section:]
    return content + new_html


def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    pages = data.get('pages', {})
    modified = 0
    skipped = 0

    for key, html in PASS2.items():
        if key not in pages:
            print(f'SKIP (not found): {key}')
            skipped += 1
            continue

        page = pages[key]
        current_content = page.get('content', '') or ''

        if len(current_content) >= 15000:
            print(f'SKIP (already >= 15000): {key} ({len(current_content)} chars)')
            skipped += 1
            continue

        new_content = enrich_content(current_content, html)
        pages[key]['content'] = new_content
        status = 'OK' if len(new_content) >= 15000 else 'PARTIAL'
        print(f'{status}: {key} ({len(current_content)} -> {len(new_content)} chars)')
        modified += 1

    data['pages'] = pages

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'\nDone: {modified} articles enriched, {skipped} skipped.')


if __name__ == '__main__':
    main()
