#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement des articles de la discipline Environnement."""

import json
import re

FILE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/environnement.json"

ENRICHMENTS = {
"changement-climatique/effet-de-serre": """
<h3>Les rétroactions climatiques : des amplificateurs du réchauffement</h3>
<p class="resume-text">Le système climatique ne réagit pas passivement au forçage radiatif : il met en jeu des rétroactions qui amplifient ou atténuent le réchauffement initial. La rétroaction vapeur d'eau est la plus puissante — lorsque la température augmente, l'évaporation s'intensifie, augmentant la vapeur d'eau atmosphérique (elle-même un GES), ce qui amplifie encore le réchauffement. On estime qu'elle double environ l'effet du CO₂ seul.</p>
<p class="resume-text">La rétroaction albédo-glace constitue une autre boucle positive : la fonte des glaces et des neiges réduit la surface réfléchissante de la Terre (l'albédo), exposant des océans et des sols sombres qui absorbent davantage d'énergie solaire. Dans l'Arctique, cette rétroaction est particulièrement forte : la région se réchauffe deux à quatre fois plus vite que la moyenne mondiale, un phénomène appelé amplification arctique.</p>
<p class="resume-text">À l'inverse, certaines rétroactions sont négatives : l'augmentation de la couverture nuageuse dans certaines régions peut réfléchir davantage de rayonnement solaire, limitant partiellement le réchauffement. Cependant, les nuages exercent également un effet de serre, et leur rôle global reste l'une des plus grandes sources d'incertitude dans les modèles climatiques.</p>
<div class="highlight-box"><p>La sensibilité climatique — le réchauffement attendu pour un doublement du CO₂ — est estimée entre 2,5 °C et 4 °C selon le GIEC (rapport AR6, 2021), les rétroactions étant responsables de l'essentiel de cette amplification.</p></div>

<h3>Mesurer le CO₂ : de Mauna Loa aux carottes de glace</h3>
<p class="resume-text">La surveillance continue du CO₂ atmosphérique a débuté en 1958 à l'observatoire de Mauna Loa (Hawaï), à l'initiative du scientifique Charles David Keeling. La courbe de Keeling, devenue l'une des icônes de la science climatique, montre une montée inexorable de la concentration en CO₂, entrecoupée d'oscillations saisonnières dues à la respiration des végétaux de l'hémisphère Nord.</p>
<p class="resume-text">Pour remonter plus loin dans le temps, les climatologues analysent les bulles d'air piégées dans les carottes de glace extraites de l'Antarctique et du Groenland. La carotte de Vostok, longue de 3 623 mètres, a permis de reconstituer 420 000 ans d'histoire climatique, révélant la corrélation étroite entre température et concentration en CO₂ au fil des cycles glaciaires-interglaciaires. Les niveaux actuels de CO₂ sont sans précédent depuis au moins 3 millions d'années.</p>
<div class="highlight-box"><p>Les carottes de glace antarctiques montrent que les niveaux actuels de CO₂ (>420 ppm) dépassent tout ce qui a été enregistré au cours des 800 000 dernières années, dont la valeur maximale naturelle était d'environ 300 ppm.</p></div>

<h3>L'effet de serre dans le système solaire : perspectives comparatives</h3>
<p class="resume-text">L'étude des atmosphères planétaires offre une perspective saisissante sur l'effet de serre. Vénus, notre voisine, possède une atmosphère composée à 96 % de CO₂ et une pression atmosphérique 90 fois supérieure à celle de la Terre. Son effet de serre incontrôlé maintient une température de surface de 464 °C, suffisante pour faire fondre le plomb — un exemple extrême d'emballement climatique.</p>
<p class="resume-text">Mars, à l'opposé, a une atmosphère ténue (0,6 % de la pression terrestre), également composée principalement de CO₂. Malgré ce GES, l'effet de serre martien est minimal en raison de la faible densité atmosphérique, résultant en des températures moyennes de -60 °C. Ces comparaisons planétaires soulignent que c'est la quantité totale de GES dans l'atmosphère, et non leur seule composition, qui détermine l'intensité de l'effet de serre.</p>
<div class="highlight-box"><p>Vénus illustre un scénario d'emballement climatique : son effet de serre a évaporé ses océans primitifs, libérant encore plus de vapeur d'eau et de CO₂, dans une boucle positive irréversible qui a transformé une planète potentiellement habitable en enfer volcanique.</p></div>
""",

"changement-climatique/rechauffement-global": """
<h3>Les preuves multiples du réchauffement climatique</h3>
<p class="resume-text">Le réchauffement climatique se manifeste par un faisceau convergent de preuves issues de disciplines différentes. Les relevés thermométriques directs, collectés depuis le XIXe siècle sur l'ensemble du globe, indiquent un réchauffement moyen de 1,1 °C depuis l'ère préindustrielle (1850-1900). Les 10 années les plus chaudes jamais enregistrées se situent toutes après 2010, et 2023 a établi un nouveau record absolu avec un réchauffement de 1,45 °C.</p>
<p class="resume-text">Au-delà des températures de surface, les indicateurs sont nombreux : la montée du niveau des mers (environ 20 cm depuis 1900, avec une accélération récente à 3,6 mm/an), la réduction de la couverture glaciaire (la banquise arctique estivale a perdu 40 % de sa superficie depuis 1979), le recul des glaciers continentaux sur tous les continents, et l'acidification des océans (pH passé de 8,2 à 8,1 depuis l'ère industrielle, soit une augmentation de 26 % de l'acidité).</p>
<div class="highlight-box"><p>Chaque décennie depuis les années 1980 a été plus chaude que la précédente. La période 2011-2020 a été la plus chaude de l'ère instrumentale, et les projections indiquent que la limite de 1,5 °C fixée par l'Accord de Paris pourrait être franchie dès les années 2030.</p></div>

<h3>Attribution scientifique : démêler causes naturelles et anthropiques</h3>
<p class="resume-text">L'une des avancées majeures de la climatologie est la science de l'attribution, qui permet de quantifier la contribution humaine au changement climatique. Les modèles climatiques peuvent distinguer le signal anthropique (émissions de GES et aérosols) du bruit naturel (variabilité solaire, volcans, oscillations océaniques). Ces analyses démontrent que le réchauffement observé depuis 1950 ne peut s'expliquer que par l'influence humaine — la probabilité que le réchauffement soit d'origine naturelle est inférieure à 1 sur un million.</p>
<p class="resume-text">L'attribution s'applique désormais aussi aux événements extrêmes individuels. La canicule européenne de 2003, qui a tué 70 000 personnes, a été rendue au moins deux fois plus probable par le changement climatique. Les inondations de 2021 en Allemagne et Belgique (184 morts) ont été rendues 1,2 à 9 fois plus probables. Ce type d'analyse, appelé "weather attribution", transforme le changement climatique d'une abstraction statistique en une réalité concrète et mesurable pour chaque catastrophe météorologique.</p>
<div class="highlight-box"><p>La science de l'attribution a établi que le changement climatique d'origine humaine a déjà multiplié par 5 la fréquence des vagues de chaleur extrêmes et augmenté de 20 % l'intensité des précipitations extrêmes dans les régions touchées.</p></div>

<h3>Les points de basculement : seuils critiques du système climatique</h3>
<p class="resume-text">Au-delà de certains seuils de réchauffement, le système climatique peut basculer de manière irréversible vers un nouvel état. Ces points de basculement (tipping points) sont particulièrement préoccupants car ils peuvent déclencher des cascades : le dégel du pergélisol libère du méthane, ce qui accélère le réchauffement, qui fait fondre davantage de glace, etc. Parmi les points de basculement identifiés : l'effondrement de la calotte glaciaire ouest-antarctique (irréversible dès +1,5 °C selon certaines études), la déstabilisation du pergélisol sibérien (libérerait jusqu'à 1 700 Gt de carbone), et le dépérissement de l'Amazonie.</p>
<p class="resume-text">Une étude de 2022 publiée dans Science identifie 16 points de basculement climatiques majeurs, dont 5 pourraient être déclenchés au niveau de réchauffement actuel (1,1 °C). Ces interactions entre points de basculement pourraient conduire à un "état de serre" de la Terre, où le réchauffement s'emballe sans intervention supplémentaire humaine, rendant une grande partie de la planète inhospitalière.</p>
<div class="highlight-box"><p>La calotte du Groenland contient suffisamment de glace pour élever le niveau des mers de 7 mètres. Sa fonte totale, possible sur plusieurs siècles si le réchauffement dépasse 1,5-2 °C, menacerait toutes les villes côtières mondiales, dont Shanghai, Miami, Amsterdam et Dacca.</p></div>

<h3>Impacts régionaux différenciés : une planète à deux vitesses</h3>
<p class="resume-text">Le réchauffement global ne se distribue pas uniformément : les régions polaires se réchauffent deux à quatre fois plus vite que la moyenne mondiale. Les pays les plus vulnérables — petits États insulaires du Pacifique, delta du Bangladesh, Sahel africain — sont souvent ceux qui ont le moins contribué aux émissions historiques. Cette injustice climatique est au cœur des négociations internationales : les pays les plus riches et les plus émetteurs doivent-ils compenser les pertes et préjudices subis par les nations les plus vulnérables ?</p>
<p class="resume-text">En Europe, les projections indiquent une augmentation des sécheresses méditerranéennes, des inondations en Europe du Nord et des canicules plus fréquentes et intenses. La France pourrait connaître des étés semblables à la canicule de 2003 tous les deux ans d'ici 2050 dans un scénario de réchauffement à +4 °C. Les Alpes pourraient perdre 80 % de leur volume glaciaire d'ici 2100, menaçant les ressources en eau de millions de personnes et l'économie du ski.</p>
<div class="highlight-box"><p>Les petits États insulaires comme Tuvalu ou Kiribati pourraient disparaître sous les eaux d'ici la fin du siècle : leur altitude maximale dépasse à peine 3 mètres. Certains ont déjà entamé des négociations avec l'Australie et la Nouvelle-Zélande pour accueillir leurs populations déplacées.</p></div>
""",

"changement-climatique/consequences-climatiques": """
<h3>L'intensification des événements extrêmes</h3>
<p class="resume-text">Le changement climatique ne se traduit pas seulement par une hausse progressive des températures : il redistribue et intensifie les phénomènes météorologiques extrêmes. Dans un air plus chaud, l'atmosphère retient davantage de vapeur d'eau (environ 7 % supplémentaires par degré de réchauffement, selon la loi de Clausius-Clapeyron), alimentant des précipitations plus intenses. Simultanément, les régions déjà arides subissent des sécheresses plus profondes, car l'évaporation accrue assèche davantage les sols.</p>
<p class="resume-text">Les cyclones tropicaux, bien que leur fréquence totale ne devrait pas nécessairement augmenter, devraient devenir plus intenses et atteindre des latitudes plus élevées. L'ouragan Harvey (2017) a déversé sur Houston des précipitations rendues 15 % plus intenses par le réchauffement climatique. Les tempêtes hivernales européennes (comme Lothar et Martin en 1999) pourraient également s'intensifier dans certains scénarios. Les vagues de chaleur marines — élévation soudaine de la température des océans — menacent les récifs coralliens et les écosystèmes marins côtiers.</p>
<div class="highlight-box"><p>Chaque fraction de degré de réchauffement supplémentaire compte : à +1,5 °C, 14 % de la population mondiale sera exposée à des vagues de chaleur sévères au moins une fois tous les 5 ans. À +2 °C, cette proportion monte à 37 %.</p></div>

<h3>La montée des eaux : une menace pour les civilisations côtières</h3>
<p class="resume-text">L'élévation du niveau des mers résulte de deux mécanismes : la dilatation thermique des eaux océaniques (qui se dilatent lorsqu'elles se réchauffent) et la fonte des glaces continentales (glaciers de montagne, calotte du Groenland, calotte antarctique). Depuis 1900, le niveau des mers a monté d'environ 20 centimètres. L'accélération est préoccupante : le taux actuel d'élévation (3,6 mm/an) est deux fois supérieur à celui observé au XXe siècle.</p>
<p class="resume-text">Les projections du GIEC pour 2100 varient selon les scénarios d'émissions : de 0,3 à 1 mètre dans les scénarios les plus optimistes, mais potentiellement 2 mètres ou plus si l'instabilité des calottes polaires se révèle plus importante que prévu. Une élévation d'un mètre menacerait directement 145 millions de personnes vivant sous ce seuil, notamment dans les deltas du Bangladesh, du Nil, du Mékong et du Mississippi. Les îles Maldives, dont l'altitude moyenne est de 1,5 mètre, pourraient devenir inhabitables avant 2100.</p>
<div class="highlight-box"><p>Des villes comme Miami (Floride), Jakarta (Indonésie) et Shanghai sont déjà confrontées à des inondations côtières croissantes. Jakarta s'enfonce également en raison du pompage des eaux souterraines, à un rythme de 25 cm par an dans certains quartiers — forçant l'Indonésie à déplacer sa capitale à Nusantara.</p></div>

<h3>Sécurité alimentaire et hydrique : les risques pour les populations vulnérables</h3>
<p class="resume-text">L'agriculture mondiale est particulièrement sensible aux modifications du climat. Les rendements du blé et du maïs ont déjà diminué de 5 à 10 % par degré de réchauffement dans les régions tropicales. Certaines études projettent des baisses de rendement allant jusqu'à 25 % pour ces cultures d'ici 2050 dans les pays en développement les plus exposés. Le Sahel africain, le sous-continent indien et l'Amérique centrale font face à une double menace : des sécheresses plus fréquentes et des pluies moins prévisibles perturbant les cycles agricoles traditionnels.</p>
<p class="resume-text">La cryosphère est le "château d'eau" de nombreuses régions : les glaciers himalayens alimentent en eau douce environ 2 milliards de personnes en Asie. Leur recul accéléré crée d'abord une augmentation temporaire du débit des rivières (fonte accrue), puis une réduction progressive à mesure que le volume glaciaire diminue — la menace du "pic de l'eau glaciaire". La même dynamique affecte les Andes, où Lima et d'autres villes dépendent des glaciers pour leur approvisionnement en eau.</p>
<div class="highlight-box"><p>Le changement climatique est désormais reconnu comme un multiplicateur de menaces pour la sécurité : selon le Pentagone américain et l'Union européenne, il exacerbe les tensions géopolitiques en aggravant la concurrence pour l'eau, les terres arables et les ressources alimentaires, augmentant les risques de conflits et de migrations forcées.</p></div>
""",

"changement-climatique/accords-de-paris": """
<h3>De Rio à Paris : l'histoire des négociations climatiques internationales</h3>
<p class="resume-text">La diplomatie climatique internationale a débuté en 1992 à Rio de Janeiro, avec l'adoption de la Convention-cadre des Nations unies sur les changements climatiques (CCNUCC), ratifiée par 197 parties. Ce traité fondateur reconnaissait la responsabilité des pays industrialisés dans le réchauffement et introduisait le principe de "responsabilités communes mais différenciées". Les Conférences des Parties (COP) annuelles, organisées depuis 1995, constituent le cadre de négociation permanent.</p>
<p class="resume-text">Le Protocole de Kyoto (1997) constitua la première tentative d'engagement contraignant : les pays développés s'engageaient à réduire leurs émissions de 5 % par rapport à 1990 d'ici 2012. Mais ses limites étaient structurelles : les États-Unis, premier émetteur mondial à l'époque, ne l'ont jamais ratifié ; la Chine et l'Inde, comme pays en développement, n'avaient aucun objectif de réduction. La conférence de Copenhague en 2009 (COP15) fut un échec retentissant, les négociations s'effondrant faute de consensus sur un traité post-Kyoto ambitieux.</p>
<div class="highlight-box"><p>L'Accord de Paris (2015) a été adopté par consensus par 196 parties lors de la COP21, un record de participation. Son architecture diffère fondamentalement du Protocole de Kyoto : les engagements nationaux (NDC) sont déterminés par chaque pays, mais doivent être révisés à la hausse tous les 5 ans.</p></div>

<h3>L'architecture de l'Accord de Paris : forces et faiblesses</h3>
<p class="resume-text">L'Accord de Paris repose sur un mécanisme de "cliquet" (ratchet mechanism) : les Contributions déterminées au niveau national (NDC) sont révisées tous les 5 ans, chaque cycle devant être plus ambitieux que le précédent. Cette approche "bottom-up" contraste avec Kyoto et permet l'inclusion de tous les pays, y compris les grands émergents. L'accord fixe deux seuils de température : limiter le réchauffement à 2 °C, et "poursuivre les efforts" pour le maintenir à 1,5 °C.</p>
<p class="resume-text">Cependant, les NDC soumises restent largement insuffisantes : si tous les pays respectaient leurs engagements actuels, le réchauffement se stabiliserait autour de 2,5-3 °C d'ici 2100. L'accord manque par ailleurs de mécanismes contraignants — aucune sanction n'est prévue en cas de non-respect. Le financement climatique pour les pays en développement (100 milliards de dollars par an promis, non atteints avant 2022) demeure une source de tensions récurrentes dans les négociations.</p>
<div class="highlight-box"><p>Le retrait des États-Unis de l'Accord de Paris sous la présidence Trump (2017-2020), puis leur retour sous Biden (2021), a illustré la fragilité des engagements climatiques face aux alternances politiques nationales — une limite structurelle de l'accord.</p></div>

<h3>Les mécanismes de financement climatique : entre promesses et réalité</h3>
<p class="resume-text">Le financement climatique est au cœur des tensions Nord-Sud dans les négociations. Les pays développés ont promis en 2009 de mobiliser 100 milliards de dollars par an à partir de 2020 pour aider les pays en développement à s'adapter et à réduire leurs émissions. Cet objectif n'a été officiellement atteint qu'en 2022, avec deux ans de retard, et la nature exacte de ce "financement" — prêts, dons, investissements privés — est elle-même disputée.</p>
<p class="resume-text">La COP27 (Sharm el-Sheikh, 2022) a établi un fonds pour les "pertes et préjudices" (loss and damage), une victoire symbolique pour les pays vulnérables qui subissent des dommages irréversibles. La COP28 (Dubaï, 2023) a vu pour la première fois un accord mentionner explicitement la "transition hors des combustibles fossiles", une avancée majeure bien que la formulation reste ambiguë. Un nouvel objectif de financement post-2025, appelé NCQG, est en négociation pour remplacer les 100 milliards.</p>
<div class="highlight-box"><p>Les pays les moins avancés (PMA), qui représentent moins de 1 % des émissions mondiales, sont souvent les plus vulnérables aux impacts climatiques. Leur adaptation nécessite des financements estimés à 300 milliards de dollars par an d'ici 2030 — des montants bien supérieurs aux engagements actuels des pays développés.</p></div>
""",

"pollution/pollution-air": """
<h3>Les polluants atmosphériques : classification et sources</h3>
<p class="resume-text">La pollution atmosphérique se compose d'un cocktail complexe de substances nocives. Les particules fines (PM2,5 et PM10) sont parmi les plus dangereuses : les PM2,5, d'un diamètre inférieur à 2,5 micromètres, pénètrent profondément dans les alvéoles pulmonaires et passent dans la circulation sanguine. Leurs sources sont multiples : combustion incomplète (moteurs diesel, centrales à charbon, feux de biomasse), usure des pneumatiques et des freins, poussières industrielles. En France, la pollution aux particules fines serait responsable de 40 000 décès prématurés par an.</p>
<p class="resume-text">Les oxydes d'azote (NOₓ), principalement émis par les véhicules et les centrales thermiques, sont précurseurs de l'ozone troposphérique et des particules secondaires. L'ozone (O₃) au niveau du sol, formé par réaction photochimique entre NOₓ et composés organiques volatils sous l'effet des UV, est un puissant irritant respiratoire et cause des dommages aux cultures agricoles. Le dioxyde de soufre (SO₂), émis par la combustion du charbon et la fusion des métaux, forme des pluies acides dévastatrices pour les forêts et les lacs.</p>
<div class="highlight-box"><p>L'Organisation mondiale de la santé estime que 99 % de la population mondiale respire un air ne respectant pas ses lignes directrices en matière de qualité. La pollution atmosphérique cause environ 7 millions de décès prématurés par an, plus que le paludisme et le sida réunis.</p></div>

<h3>Les épisodes de pollution : smog, nuages toxiques et catastrophes industrielles</h3>
<p class="resume-text">L'histoire industrielle est jalonnée de catastrophes liées à la pollution atmosphérique. Le "Grand Smog" de Londres (décembre 1952) est le plus meurtrier : en cinq jours, un mélange de brouillard et de fumée de charbon a tué entre 4 000 et 12 000 personnes, conduisant au Clean Air Act britannique de 1956. Donora (Pennsylvanie, 1948) avait déjà préfiguré cette catastrophe : 20 morts et 7 000 malades dans une vallée industrielle piégée par une inversion thermique.</p>
<p class="resume-text">La catastrophe de Bhopal (Inde, 1984) reste la pire catastrophe industrielle de l'histoire : la fuite de 40 tonnes d'isocyanate de méthyl depuis une usine Union Carbide a tué immédiatement 3 000 personnes et causé des centaines de milliers de victimes à long terme. Plus récemment, les incendies de forêt de Californie (2020) et d'Australie (2019-2020) ont généré des panaches de fumée contenant des particules fines et des composés organiques toxiques qui se sont propagés sur des milliers de kilomètres.</p>
<div class="highlight-box"><p>La "ceinture de feu" industrielle en Asie du Sud-Est génère des épisodes de pollution cataclysmiques : lors des incendies de forêt de Sumatra et Bornéo en 2015, le nuage de fumée a couvert 6 millions de km², exposant 60 millions de personnes à des niveaux de pollution 100 fois supérieurs aux seuils de sécurité.</p></div>

<h3>Solutions et politiques de lutte contre la pollution atmosphérique</h3>
<p class="resume-text">La lutte contre la pollution de l'air a connu des succès notables dans les pays développés. Les normes antipollution pour les véhicules (Euro 6 en Europe, CAFE standards aux États-Unis) ont drastiquement réduit les émissions de NOₓ et de particules par véhicule depuis les années 1970. Les filtres à particules et les catalyseurs ont transformé les pots d'échappement. La conversion des centrales électriques du charbon vers le gaz naturel, puis les énergies renouvelables, a réduit les émissions de SO₂ et NOₓ des secteurs énergétiques.</p>
<p class="resume-text">Les zones à faibles émissions (ZFE) se multiplient dans les métropoles européennes : Paris, Londres, Madrid, Amsterdam ont instauré des restrictions de circulation pour les véhicules les plus polluants, parfois controversées socialement. Pékin a connu des améliorations spectaculaires : la concentration de PM2,5 a baissé de 55 % entre 2013 et 2022 grâce à la fermeture d'industries polluantes, à la conversion au gaz naturel et au développement des énergies renouvelables. Ces succès montrent que la pollution atmosphérique est réversible avec des politiques adaptées.</p>
<div class="highlight-box"><p>L'électrification des transports représente une opportunité majeure pour la qualité de l'air urbain : un véhicule électrique n'émet pas de NOₓ ni de particules fines à l'échappement (bien que les freins et pneumatiques restent une source). Dans les villes européennes, les transports représentent 40 % des émissions de NOₓ.</p></div>
""",

"pollution/metaux-lourds": """
<h3>Mercure, plomb, cadmium : les métaux lourds dans l'environnement</h3>
<p class="resume-text">Les métaux lourds sont des éléments métalliques de haute densité atomique, toxiques même à faibles concentrations. Le plomb (Pb) est l'un des polluants historiques les mieux documentés : son utilisation comme additif dans l'essence (tétraéthylplomb), généralisée de 1920 à 2000, a contaminé les sols, l'air et la chaîne alimentaire à l'échelle mondiale. Des études épidémiologiques ont montré que l'exposition chronique au plomb dans l'enfance réduit le quotient intellectuel et augmente les comportements agressifs — une hypothèse controversée mais de plus en plus soutenue pour expliquer la hausse puis la baisse de la criminalité aux États-Unis au XXe siècle.</p>
<p class="resume-text">Le mercure (Hg) est particulièrement insidieux car il se bioamplifie dans les chaînes alimentaires aquatiques : les bactéries anaérobies convertissent le mercure inorganique en méthylmercure, une forme organique qui s'accumule dans les organismes marins. Les grands prédateurs comme le thon, l'espadon et le requin peuvent concentrer du méthylmercure à des niveaux mille fois supérieurs à ceux de l'eau environnante. La catastrophe de Minamata (Japon, 1956-1968), causée par les rejets mercuriels d'une usine chimique, a tué des centaines de personnes et en a atteint des milliers d'autres de troubles neurologiques graves.</p>
<div class="highlight-box"><p>L'amalgame dentaire, composé à 50 % de mercure, est encore utilisé dans de nombreux pays. Bien que les expositions soient faibles pour les patients, sa fabrication, son utilisation et son élimination représentent une source significative de contamination mercurielle. La Convention de Minamata (2013) vise à éliminer progressivement son utilisation mondiale.</p></div>

<h3>Polluants organiques persistants (POP) et perturbateurs endocriniens</h3>
<p class="resume-text">Les polluants organiques persistants (POP), codifiés par la Convention de Stockholm (2001), sont des composés chimiques résistants à la dégradation biologique et chimique, capables de se bioaccumuler dans les tissus adipeux. La douzaine "sale" initiale comprend des pesticides comme le DDT et l'aldrine, des sous-produits industriels comme les dioxines et furanes, et des composés industriels comme les polychlorobiphényles (PCB). Bien qu'interdits dans la plupart des pays depuis les années 1970-1980, ces substances sont encore détectées dans les écosystèmes polaires, les sédiments marins et les tissus des mammifères marins.</p>
<p class="resume-text">Les perturbateurs endocriniens (PE) constituent une préoccupation croissante : ces substances imitent, bloquent ou perturbent les hormones naturelles de l'organisme. Les bisphénols A (BPA, utilisé dans les plastiques), les phtalates (plastifiants), les parabènes (conservateurs cosmétiques) et les perfluorés (PFAS, utilisés dans les revêtements antiadhésifs) sont désormais détectés dans l'urine de la quasi-totalité des adultes dans les pays industrialisés. Leurs effets sur la fertilité masculine, le développement neurologique et le risque de cancer font l'objet de recherches intensives.</p>
<div class="highlight-box"><p>Les PFAS (substances per- et polyfluoroalkylées), surnommés "polluants éternels", se dégradent extrêmement lentement dans l'environnement. Ils ont été détectés dans les eaux de pluie au-dessus du Pôle Sud, dans le lait maternel humain et dans les organismes des animaux les plus reculés. Une étude de 2022 a montré que l'eau de pluie mondiale dépasse désormais les limites de sécurité pour les PFAS.</p></div>

<h3>Dépollution et remédiation des sites contaminés</h3>
<p class="resume-text">La remédiation des sites contaminés par les métaux lourds est un défi technique et économique majeur. Les techniques traditionnelles — excavation et mise en décharge — sont coûteuses et se contentent de déplacer le problème. Des approches plus innovantes émergent : la phytoremédiation utilise des plantes hyperaccumulatrices capables d'absorber les métaux du sol dans leurs tissus (l'Arabette des dames accumule du zinc et du cadmium ; certains fougères accumulent l'arsenic). Ces plantes sont ensuite récoltées et incinérées, permettant de récupérer les métaux.</p>
<p class="resume-text">La bioremédiaton exploite des microorganismes capables de dégrader ou d'immobiliser les contaminants. Des bactéries sulfato-réductrices précipitent les métaux lourds en sulfures insolubles dans les eaux acides de mine. Des champignons mycorhiziens peuvent séquestrer les métaux dans leurs filaments. En France, l'ADEME gère un inventaire des sites et sols pollués (base BASOL) recensant plus de 7 000 sites, dont environ 1 500 nécessitent une intervention urgente. Les coûts de remédiation se chiffrent en milliards d'euros.</p>
<div class="highlight-box"><p>Le bassin minier du Nord-Pas-de-Calais, inscrit au patrimoine mondial de l'UNESCO en 2012 pour son histoire industrielle, illustre le double héritage de l'industrie lourde : des paysages culturels remarquables mais aussi des sols contaminés par 300 ans d'extraction charbonnière, avec des concentrations en plomb et en arsenic dépassant les normes à proximité des anciens terrils.</p></div>
""",

"biodiversite/rewilding": """
<h3>Les fondements écologiques du rewilding</h3>
<p class="resume-text">Le rewilding, ou ré-ensauvagement, repose sur la théorie des cascades trophiques et du rôle des espèces ingénieurs d'écosystème. Dans une cascade trophique, la présence ou l'absence d'un prédateur au sommet modifie toute la structure de l'écosystème en dessous. L'expérience la plus célèbre est la réintroduction des loups dans le parc de Yellowstone (Wyoming) en 1995 : après 70 ans d'absence, les 41 loups réintroduits ont modifié les comportements alimentaires des élans, qui évitaient désormais les zones ouvertes où les loups chassaient. Les rives des rivières, surpâturées depuis des décennies, ont pu se revégétaliser, ce qui a stabilisé les berges, réduit l'érosion et modifié même le cours des rivières — un phénomène décrit comme une "cascade trophique géomorphologique".</p>
<p class="resume-text">Les mégaherbivores jouent également un rôle structurant crucial : les éléphants d'Afrique créent des clairières et des points d'eau qui profitent à des centaines d'espèces ; les castors construisent des barrages qui créent des zones humides, régulent le débit des rivières et augmentent la biodiversité locale de 50 % dans certaines études. Le retour de ces "ingénieurs d'écosystème" est au cœur de la philosophie rewilding.</p>
<div class="highlight-box"><p>La réintroduction des loups à Yellowstone est devenue un cas d'école mondial : en 25 ans, les populations de castors, de loutres, de buses, d'ours et même de poissons ont augmenté, illustrant comment la restauration d'une seule espèce peut régénérer un écosystème entier.</p></div>

<h3>Les grands projets de rewilding en Europe</h3>
<p class="resume-text">L'Europe abrite plusieurs projets ambitieux de rewilding. Rewilding Europe, fondé en 2011, travaille dans dix régions prioritaires : les Carpates roumaines, la péninsule ibérique, la région de Velebit en Croatie, le delta du Danube, le Laponia en Suède, etc. En Roumanie, la forêt de Dobruja accueille le plus grand troupeau de bisons d'Europe en liberté (plus de 100 individus), espèce qui avait disparu à l'état sauvage en 1927.</p>
<p class="resume-text">En Écosse, le projet de "Great Rewilding" vise à restaurer les forêts calédonniennes de pins sylvestres qui couvraient jadis 1,5 million d'hectares et n'en couvrent plus que 180 000. La réintroduction des castors (2009), des pygargues à queue blanche (2019) et le projet de retour du lynx (en débat) représentent des étapes successives de ce processus. Aux Pays-Bas, la réserve d'Oostvaardersplassen a expérimenté depuis 1990 une forme radicale de rewilding avec des grands herbivores (chevaux de Konik, bœufs Heck), suscitant un débat éthique intense autour de la gestion ou non-gestion des animaux en surpopulation.</p>
<div class="highlight-box"><p>En France, le loup (Canis lupus) est revenu naturellement depuis l'Italie en 1992, sans réintroduction humaine. Sa présence dans les Alpes, le Jura, les Vosges et les Pyrénées est désormais avérée, avec environ 1 000 individus. Sa coexistence avec l'élevage ovin reste un enjeu territorial et politique majeur.</p></div>

<h3>Tensions et controverses autour du rewilding</h3>
<p class="resume-text">Le rewilding ne fait pas l'unanimité. Les éleveurs, en premier lieu, s'y opposent fréquemment : le retour des loups, des ours et des lynx engendre des prédations sur les troupeaux domestiques, même si des systèmes de protection (chiens patous, parcs électriques, bergers) et des compensations financières existent. En France, l'ours brun des Pyrénées, dont la population a été renforcée par des réintroductions depuis 1996, suscite des conflits intenses entre défenseurs de l'environnement et éleveurs de montagne.</p>
<p class="resume-text">Des questions philosophiques profondes se posent également : quelle "nature sauvage" voulons-nous restaurer ? Celle d'avant l'agriculture (8 000 ans) ? D'avant les humains modernes (300 000 ans) ? D'avant les extinctions de la mégafaune de la fin du Pléistocène (10 000 ans) ? Certains partisans du "Pleistocene rewilding" proposent d'utiliser des espèces proches parents ou de dé-éteindre des espèces via la biologie de synthèse (projet de résurrection du mammouth laineux par la société Colossal Biosciences). Ces propositions rencontrent un scepticisme scientifique et éthique considérable.</p>
<div class="highlight-box"><p>Le programme européen LIFE cofinance de nombreux projets de rewilding. La stratégie de l'UE pour la biodiversité 2030 prévoit la restauration de 20 % des terres et des mers européennes dégradées, dont des zones de rewilding strict représentant au moins 10 % du territoire — un objectif ambitieux qui implique des changements profonds dans l'utilisation des terres.</p></div>
""",

"biodiversite/zones-protegees": """
<h3>La géographie des aires protégées : de Yellowstone au réseau mondial</h3>
<p class="resume-text">La première aire protégée moderne, le parc national de Yellowstone (États-Unis, 1872), a inauguré un modèle qui s'est diffusé dans le monde entier. Aujourd'hui, le réseau mondial d'aires protégées couvre environ 17 % des terres émergées et 8 % des océans, selon la base de données mondiale WDPA (World Database on Protected Areas). Cependant, cette couverture géographique masque de profondes inégalités : certains pays, comme le Costa Rica ou la Namibie, protègent plus de 25 % de leur territoire, tandis que d'autres, notamment dans les régions les plus riches en biodiversité, restent largement sous-protégés.</p>
<p class="resume-text">L'objectif "30x30" adopté lors de la COP15 sur la biodiversité à Montréal (2022) vise à protéger 30 % des terres et des mers d'ici 2030. Cet objectif ambitieux nécessite de doubler la surface protégée actuelle. Sa mise en œuvre soulève des questions sur la qualité des protections : une aire protégée sur le papier mais dépourvue de moyens de surveillance (les "parcs fantômes") offre peu de bénéfices réels pour la biodiversité.</p>
<div class="highlight-box"><p>Seulement 42 % des espèces terrestres menacées ont leur aire de distribution couverte à plus de 50 % par des zones protégées. Pour atteindre les objectifs de protection de la biodiversité, la qualité et la connectivité des aires protégées importent autant que leur superficie totale.</p></div>

<h3>Efficacité des aires protégées : entre succès et défis</h3>
<p class="resume-text">Les preuves scientifiques de l'efficacité des aires protégées s'accumulent. Une méta-analyse de 2019 (Fuller et al.) a montré que les parcs nationaux bien gérés contiennent en moyenne deux fois plus d'espèces et trois fois plus d'individus que les zones adjacentes non protégées. Le programme de surveillance REDD+ (Réduction des émissions liées à la déforestation) a démontré que les forêts protégées dans des parcs nationaux subissent deux à trois fois moins de déforestation que les forêts non protégées à caractéristiques similaires.</p>
<p class="resume-text">Cependant, des problèmes persistent. Les "aires protégées papier" — légalement désignées mais sans moyens de gestion ni d'application — sont trop nombreuses. Les braconniers, les orpailleurs illégaux, les défricheurs et les extracteurs de ressources opèrent dans de nombreux parcs officiellement protégés. Au Brésil, la déforestation dans les parcs nationaux amazoniens a augmenté sous des gouvernements défavorables à la conservation. En Afrique centrale, les écogardes de nombreuses réserves font face à des milices armées liées à des réseaux criminels transnationaux.</p>
<div class="highlight-box"><p>La "fortification" (fortress conservation) — la création de réserves naturelles en expulsant les communautés locales qui y vivaient — a longtemps été le modèle dominant, avec des conséquences sociales désastreuses. Une approche plus récente, la conservation communautaire (OECM), reconnaît que les communautés autochtones gèrent souvent mieux leurs territoires que les gestionnaires extérieurs.</p></div>

<h3>Corridors écologiques et connectivité : au-delà des îles de biodiversité</h3>
<p class="resume-text">La biogéographie insulaire, développée par Robert MacArthur et E.O. Wilson dans les années 1960, a démontré que la taille et l'isolement d'un habitat déterminent le nombre d'espèces qu'il peut contenir. Une réserve isolée dans un "océan" de terres agricoles ou urbaines se comporte comme une île : les espèces s'y éteignent progressivement sans possibilité de recolonisation depuis l'extérieur. C'est pourquoi la notion de corridor écologique, reliant les noyaux de biodiversité, est devenue centrale dans la planification de la conservation.</p>
<p class="resume-text">Le projet de corridor Y2Y (Yellowstone to Yukon) vise à relier par des couloirs verts les zones sauvages depuis le parc de Yellowstone jusqu'au Yukon canadien, permettant aux grizzlis, loups et autres grands mammifères de se déplacer librement sur 3 200 km. En Europe, le réseau Natura 2000 — le plus grand réseau coordonné d'aires protégées au monde avec 27 000 sites couvrant 18 % du territoire européen — tente de créer une connectivité écologique à l'échelle continentale. Les "passages à faune" (écoducs) construits au-dessus ou en dessous des autoroutes contribuent à maintenir la connectivité pour les espèces terrestres.</p>
<div class="highlight-box"><p>En France, la "Trame verte et bleue" (TVB), introduite par les lois Grenelle (2007-2010), vise à reconstituer un réseau écologique national en identifiant et préservant les corridors terrestres (trame verte) et aquatiques (trame bleue). Son intégration dans les documents d'urbanisme locaux est cependant inégale selon les territoires.</p></div>
""",

"ressources-naturelles/eau-douce": """
<h3>La distribution inégale de l'eau douce sur la planète</h3>
<p class="resume-text">L'eau douce représente seulement 2,5 % de l'eau présente sur Terre, dont 68,7 % est emprisonnée dans les glaces et les calottes polaires, et 30,1 % constitue les eaux souterraines. Moins de 1 % de l'eau douce mondiale est directement accessible dans les lacs, rivières et zones humides de surface. Cette rareté relative est aggravée par une distribution géographique extrêmement inégale : le Brésil, la Russie, le Canada, la Chine, les États-Unis, l'Indonésie, l'Inde, le Pérou et la Colombie détiennent à eux seuls 60 % des ressources mondiales en eau douce renouvelable, tandis que des pays comme l'Égypte, la Jordanie ou Israël survivent avec une fraction infime de ce qui est nécessaire.</p>
<p class="resume-text">La demande mondiale en eau a été multipliée par six au cours du XXe siècle, sous l'effet de la croissance démographique, de l'agriculture irriguée et du développement industriel. L'agriculture représente environ 70 % des prélèvements mondiaux en eau douce, l'industrie 19 % et les usages domestiques 11 %. La culture du riz, du coton et du blé sont particulièrement gourmandes en eau : produire 1 kg de riz nécessite 1 500 à 2 000 litres d'eau ; 1 kg de coton, 10 000 litres ; 1 kg de bœuf, jusqu'à 15 000 litres selon les modes d'élevage.</p>
<div class="highlight-box"><p>La mer d'Aral (Asie centrale) illustre tragiquement la surexploitation des ressources en eau : détournée pour irriguer les cultures de coton soviétiques depuis les années 1960, cette quatrième mer intérieure du monde a perdu 90 % de sa superficie et de son volume en 50 ans, transformant une région fertile en désert salin et détruisant une industrie de pêche qui employait 60 000 personnes.</p></div>

<h3>Les aquifères souterrains : ressource précieuse et vulnérable</h3>
<p class="resume-text">Les aquifères souterrains représentent la principale réserve d'eau douce liquide accessible, mais leur recharge est souvent très lente — des milliers à des millions d'années pour les "eaux fossiles" des aquifères profonds. L'aquifère du Sahara (SASS), qui s'étend sous l'Algérie, la Tunisie et la Libye, contient environ 60 000 km³ d'eau accumulée depuis 10 000 à 100 000 ans, pendant les périodes humides du Pléistocène. Son exploitation actuelle pour l'agriculture n'est pas renouvelable — c'est une ressource minière non régénérable à l'échelle humaine.</p>
<p class="resume-text">L'Ogallala Aquifer, sous les Grandes Plaines américaines, irrigue 30 % des terres agricoles des États-Unis et représente 30 % de l'eau souterraine utilisée pour l'irrigation dans le pays. Son niveau baisse de 1 à 3 mètres par an dans certaines régions, menaçant à terme la "grenier à blé" américain. En Inde, la surexploitation des eaux souterraines alimente la crise de l'eau : dans certains États comme le Punjab et le Haryana, le niveau des nappes chute de plus de 50 cm par an, rendant le forage de puits de plus en plus profonds et coûteux pour les agriculteurs.</p>
<div class="highlight-box"><p>La NASA utilise les satellites GRACE (Gravity Recovery and Climate Experiment) pour mesurer les variations du champ gravitationnel terrestre, permettant de cartographier les fluctuations des nappes phréatiques. Ces mesures ont révélé que 21 des 37 principaux aquifères mondiaux sont en état de surexploitation avancée.</p></div>

<h3>Les conflits de l'eau : une ressource géopolitique du XXIe siècle</h3>
<p class="resume-text">L'eau est une ressource transfrontalière partagée par 263 bassins versants internationaux, couvrant 60 % des terres émergées. La gestion partagée de ces ressources crée des tensions potentielles entre États en compétition. Le Nil, partagé par 11 pays, est au cœur d'un conflit diplomatique majeur : le Grand Barrage de la Renaissance éthiopien (GERD), dont le remplissage a commencé en 2020, menace de réduire le débit du Nil vers l'Égypte et le Soudan. L'Égypte considère la question comme existentielle — le Nil fournit 97 % de ses ressources en eau douce.</p>
<p class="resume-text">Le Tigre et l'Euphrate, partagés par la Turquie, la Syrie et l'Irak, sont l'objet d'un autre conflit chronique : les grands barrages turcs (GAP, projet d'Anatolie du Sud-Est) ont considérablement réduit le débit atteignant l'Irak et la Syrie. L'Inde et la Chine partagent plusieurs fleuves himalayens (Brahmaputre, Indus), et les projets hydrauliques chinois en amont alimentent les tensions avec les pays en aval. Le concept de "diplomatie de l'eau" cherche à transformer ces compétitions potentiellement conflictuelles en coopération transfrontalière.</p>
<div class="highlight-box"><p>Environ 2 milliards de personnes manquent d'accès à l'eau potable sûre, et 3,6 milliards connaissent une pénurie d'eau au moins un mois par an. Le droit à l'eau et à l'assainissement a été reconnu comme un droit humain fondamental par l'ONU en 2010, mais sa mise en œuvre reste très inégale à travers le monde.</p></div>
""",

"ressources-naturelles/energies-fossiles": """
<h3>Formation et géologie des combustibles fossiles</h3>
<p class="resume-text">Les combustibles fossiles — charbon, pétrole et gaz naturel — sont le résultat d'une transformation géologique de matière organique sur des millions d'années. Le charbon s'est formé principalement au Carbonifère (359-299 Ma), lorsque d'immenses forêts tropicales couvraient les régions équatoriales de la Pangée. La lignine, composant structurel des arbres, ne pouvait pas encore être dégradée efficacement par les bactéries (les enzymes adéquates n'avaient pas encore évolué), ce qui a permis l'accumulation de tourbe, progressivement compressée et transformée en houille sous l'effet de la chaleur et de la pression.</p>
<p class="resume-text">Le pétrole et le gaz naturel proviennent principalement de la dégradation de matière organique marine — algues, plancton, bactéries — déposée au fond des mers dans des environnements anoxiques (sans oxygène). Sur des millions d'années, cette "roche-mère" kérogène a été soumise à une maturation thermique (la "fenêtre à huile" se situe entre 60 et 120 °C), produisant des hydrocarbures liquides et gazeux qui ont migré vers des roches-réservoirs poreuses scellées par des trappes géologiques. L'ère d'or de la formation pétrolière correspond au Jurassique et au Crétacé supérieur.</p>
<div class="highlight-box"><p>Les réserves mondiales prouvées de pétrole représentent environ 1 700 milliards de barils, soit environ 50 ans de consommation au rythme actuel. Mais ces chiffres sont politiques autant que techniques : les pays de l'OPEP ont intérêt à majorer leurs réserves pour obtenir des quotas de production plus élevés, ce qui rend les estimations officielles sujettes à caution.</p></div>

<h3>La géopolitique des énergies fossiles : or noir et dépendances stratégiques</h3>
<p class="resume-text">Le pétrole a profondément reconfiguré la géopolitique mondiale au XXe siècle. La nationalisation des ressources pétrolières (Iran en 1951, Irak en 1972, Venezuela en 1976) et la création de l'OPEP (1960) ont transformé des pays en développement en acteurs géopolitiques majeurs. Les chocs pétroliers de 1973 (embargo arabe suite à la guerre du Kippour) et 1979 (révolution iranienne) ont démontré la vulnérabilité des économies industrialisées et déclenché les premières politiques d'efficacité énergétique.</p>
<p class="resume-text">La "malédiction des ressources" (resource curse) décrit le paradoxe par lequel les pays richement dotés en ressources naturelles connaissent souvent une croissance économique plus faible, des institutions plus corrompues et plus de conflits que les pays moins dotés. Des pays comme le Nigeria, l'Angola, la République du Congo ou le Venezuela illustrent ce phénomène : leurs revenus pétroliers ont financé des élites politiques kleptocratiques plutôt que le développement humain. La transparence des revenus pétroliers, promue par l'Initiative pour la transparence des industries extractives (ITIE), cherche à briser ce cycle.</p>
<div class="highlight-box"><p>Les pétroles non conventionnels — huiles de schiste (shale oil), sables bitumineux, pétrole offshore en eaux profondes — ont transformé le paysage énergétique mondial dans les années 2010. La "révolution du shale" américain a fait des États-Unis le premier producteur mondial de pétrole dès 2018, reconfigurant les équilibres géopolitiques du marché pétrolier et affaiblissant l'influence de l'OPEP.</p></div>

<h3>La transition énergétique : décarbonation d'un système fossile</h3>
<p class="resume-text">Décarboner l'économie mondiale implique de remplacer les énergies fossiles, qui représentent encore 80 % de l'énergie primaire mondiale, par des sources bas-carbone. La transition est en cours mais inégale : les énergies renouvelables (solaire, éolien) connaissent une croissance exponentielle, mais elles s'ajoutent encore largement à la demande énergétique croissante plutôt que de remplacer les fossiles. L'AIE (Agence internationale de l'énergie) estime que pour limiter le réchauffement à 1,5 °C, aucun nouveau projet de développement de combustibles fossiles ne devrait être approuvé après 2021 — une conclusion politiquement explosive.</p>
<p class="resume-text">L'industrie fossile fait face à un risque d'actifs échoués (stranded assets) : si les politiques climatiques sont mises en œuvre, une partie des réserves prouvées de pétrole, gaz et charbon ne pourra jamais être brûlée. Ces "actifs carbone" représentent une valeur de plusieurs dizaines de milliers de milliards de dollars au bilan des entreprises et des États exportateurs — leur dépréciation brutale pourrait déclencher une crise financière majeure. Le concept de "bulle carbone" est désormais pris au sérieux par les régulateurs financiers, dont la Banque centrale européenne.</p>
<div class="highlight-box"><p>Le charbon est le combustible fossile le plus émetteur de CO₂ par unité d'énergie et le plus meurtrier en termes de pollution atmosphérique locale. Malgré cela, il représente encore 27 % de la production mondiale d'électricité. La sortie du charbon est l'objectif le plus urgent de la transition énergétique, mais elle rencontre des résistances socio-économiques dans les régions minières dépendantes.</p></div>
""",

"ressources-naturelles/minerais-metaux": """
<h3>L'économie mondiale des minerais : chaînes d'approvisionnement et concentration géographique</h3>
<p class="resume-text">Les minerais et métaux sont les matières premières indispensables à l'économie moderne et à la transition énergétique. Leur extraction est géographiquement concentrée dans quelques pays qui détiennent des positions dominantes sur certains marchés. La République démocratique du Congo produit 70 % du cobalt mondial, métal essentiel aux batteries lithium-ion des véhicules électriques. La Chine contrôle 85 % de la production mondiale de terres rares (néodyme, dysprosium, etc.), indispensables aux aimants permanents des éoliennes et des moteurs électriques. Le Chili et le Pérou représentent environ 40 % de la production mondiale de cuivre.</p>
<p class="resume-text">Cette concentration géographique crée des vulnérabilités géopolitiques : l'embargo chinois sur les terres rares vers le Japon en 2010 (lors d'un différend territorial) a mis en évidence le risque de dépendances stratégiques. Les pays importateurs tentent de diversifier leurs approvisionnements et de développer des alternatives. L'Union européenne a élaboré une liste de matières premières critiques (actuellement 34 substances), dont l'approvisionnement est jugé économiquement important et à risque élevé de rupture.</p>
<div class="highlight-box"><p>La transition vers les énergies renouvelables et les véhicules électriques va considérablement augmenter la demande en certains minerais : selon l'AIE, un véhicule électrique nécessite 6 fois plus de minerais critiques qu'un véhicule thermique. La demande de lithium pourrait être multipliée par 40 d'ici 2040, celle de cobalt et de nickel par 20.</p></div>

<h3>Impacts environnementaux et sociaux de l'extraction minière</h3>
<p class="resume-text">L'extraction minière est parmi les activités industrielles les plus impactantes sur l'environnement. Les mines à ciel ouvert (open-pit mining), utilisées pour le cuivre, le fer, le charbon et les sables bitumineux, créent des excavations gigantesques visibles depuis l'espace et génèrent d'immenses quantités de déchets stériles. La mine de Bingham Canyon (Utah), plus grande excavation artificielle du monde, fait 4 km de diamètre et 1,2 km de profondeur. Le drainage acide minier (AMD) — l'acidification et la contamination en métaux lourds des eaux de ruissellement depuis les déchets miniers — contamine les cours d'eau pendant des siècles après la fermeture des mines.</p>
<p class="resume-text">Les conditions sociales dans les mines artisanales de cobalt en RDC ont suscité une prise de conscience internationale : des enfants de moins de 10 ans travaillent dans des mines de subsistance pour extraire le cobalt à la main, dans des conditions dangereuses et sans équipements de protection. Ces pratiques alimentent les chaînes d'approvisionnement des géants technologiques. Des organisations comme Global Witness et Amnesty International ont documenté ces conditions, poussant les entreprises à auditer leurs fournisseurs et à développer des technologies de batteries sans cobalt.</p>
<div class="highlight-box"><p>La catastrophe de Brumadinho (Brésil, janvier 2019) illustre les risques des digues de résidus miniers : la rupture d'une digue appartenant à la compagnie Vale a libéré 12 millions de mètres cubes de boues toxiques, tuant 270 personnes et polluant la rivière Paraopeba. Cette catastrophe a suivi celle de Mariana (2015), également due à Vale et à BHP Billiton, qui avait contaminé 600 km du fleuve Doce.</p></div>

<h3>L'économie circulaire appliquée aux métaux : recycler pour réduire l'extraction</h3>
<p class="resume-text">Le recyclage des métaux offre d'immenses avantages environnementaux par rapport à l'extraction primaire. La production d'aluminium recyclé consomme 95 % moins d'énergie que la production à partir de bauxite ; celle d'acier recyclé, 75 % moins. Le recyclage du cuivre permet d'économiser 85 % de l'énergie nécessaire à son extraction. Ces avantages énergétiques se traduisent par d'importantes réductions des émissions de GES et de la pollution.</p>
<p class="resume-text">Cependant, les taux de recyclage des métaux dits "technologiques" — indium, germanium, tellure, gallium, terres rares — restent très faibles (souvent moins de 1 %). La complexité des assemblages électroniques modernes rend leur désassemblage et leur séparation extrêmement difficiles. Les déchets électroniques (e-waste) constituent le flux de déchets à la croissance la plus rapide au monde : 54 millions de tonnes en 2019, dont seulement 17,4 % ont été recyclés dans des conditions documentées. Le reste prend le chemin de décharges en Afrique de l'Ouest ou en Asie du Sud-Est, où des travailleurs informels exposés à des substances toxiques en extraient les métaux précieux.</p>
<div class="highlight-box"><p>L'"extraction urbaine" (urban mining) — la récupération des métaux précieux et rares des équipements électroniques en fin de vie — devient une industrie à part entière. La ville de Tokyo a ainsi "miné" ses déchets électroniques pour fabriquer les médailles des Jeux Olympiques 2020 entièrement à partir de métaux recyclés, une première mondiale symbolique.</p></div>
""",

"ressources-naturelles/sol-ressource": """
<h3>La formation des sols : des millénaires d'évolution biologique et géologique</h3>
<p class="resume-text">Le sol est un système vivant complexe, fruit d'interactions entre la roche-mère, le climat, les organismes vivants, le relief et le temps — les cinq facteurs de la pédogenèse identifiés par Hans Jenny en 1941. La formation de 1 cm de sol nécessite entre 100 et 1 000 ans selon les conditions climatiques. Un profil de sol mature, ou solum, se compose de plusieurs horizons superposés : l'horizon O (matière organique non décomposée), l'horizon A (humus et minéraux), l'horizon B (accumulation de minéraux lessivés) et l'horizon C (roche altérée). Ces horizons témoignent d'une longue histoire pédogénétique.</p>
<p class="resume-text">La matière organique des sols — l'humus — est au cœur de la fertilité. Elle résulte de la décomposition partielle des résidus végétaux et animaux par une communauté biologique extraordinairement diverse : les sols agricoles contiennent en moyenne 1 milliard de bactéries, 100 000 champignons, 10 000 protozoaires et 1 000 nématodes par gramme de sol sec. Les vers de terre, "ingénieurs des sols" par excellence, améliorent la structure du sol par leur fouissage, augmentent sa porosité et sa capacité de rétention en eau.</p>
<div class="highlight-box"><p>Un gramme de sol sain contient plus de bactéries que la population humaine mondiale. Cette biodiversité microbienne, encore largement inconnue (plus de 95 % des espèces microbiennes du sol n'ont jamais été cultivées en laboratoire), est à la base de tous les cycles biogéochimiques terrestres.</p></div>

<h3>La dégradation des sols : une crise silencieuse</h3>
<p class="resume-text">La dégradation des sols est qualifiée de "crise silencieuse" de l'environnement, moins médiatisée que le changement climatique ou la déforestation mais aux conséquences potentiellement aussi graves. Selon la FAO, environ 33 % des sols mondiaux sont modérément à fortement dégradés, et 12 millions d'hectares de terres productives sont perdus chaque année à la désertification et à la dégradation. Les principales causes sont l'érosion hydrique et éolienne, la salinisation des terres irriguées, la compaction par les engins agricoles lourds, l'acidification et l'appauvrissement en matière organique.</p>
<p class="resume-text">L'érosion hydrique est particulièrement dévastatrice : une pluie intense sur un sol nu (après labour ou après récolte) peut emporter plusieurs tonnes de terre par hectare. La "dust bowl" (cuvette de poussière) des années 1930 aux États-Unis est l'exemple historique le plus célèbre : la mise en culture à grande échelle des Grandes Plaines, combinée à une sécheresse prolongée, a produit des tempêtes de poussière catastrophiques qui ont transformé des millions d'hectares en désert et contraint à l'exode 3,5 millions de personnes. Cet épisode a conduit à la création du Soil Conservation Service américain et aux premières politiques de conservation des sols.</p>
<div class="highlight-box"><p>La salinisation affecte environ 1 milliard d'hectares dans le monde et rend hors d'usage 1 à 2 millions d'hectares de terres irriguées chaque année. Elle résulte de l'irrigation avec des eaux salines sans drainage adéquat : l'eau s'évapore, laissant des sels en surface qui inhibent la germination et la croissance des plantes. La "mer Blanche" des terres salinisées dans certaines régions d'Asie centrale témoigne de ce désastre agricole.</p></div>

<h3>L'agriculture régénératrice : restaurer les sols pour l'avenir</h3>
<p class="resume-text">L'agriculture régénératrice désigne un ensemble de pratiques visant à améliorer la santé et la résilience des sols plutôt que de simplement les exploiter. Ses principes clés incluent : le couvert végétal permanent (limiter les périodes de sol nu), la diversification des rotations (inclure des légumineuses fixatrices d'azote), l'apport régulier de matière organique (compost, fumier), la réduction ou l'élimination du labour (non-labour ou travail superficiel), et l'intégration des animaux dans les rotations (pâturage tournant intensif).</p>
<p class="resume-text">Le "carbon farming" ou agriculture de séquestration carbone propose d'utiliser les sols agricoles comme puits de carbone : en augmentant leur teneur en matière organique, ils peuvent stocker davantage de CO₂ atmosphérique. L'initiative "4 pour 1000", lancée par la France à la COP21 en 2015, propose d'augmenter de 0,4 % par an la teneur en carbone des sols mondiaux, ce qui compenserait les émissions mondiales de CO₂. Si cette compensation complète est considérée comme irréaliste par la communauté scientifique, l'objectif de tendre vers une agriculture moins émettrice et plus stockeuse de carbone est largement partagé.</p>
<div class="highlight-box"><p>Le comté de Marin (Californie) a lancé l'un des premiers programmes publics de paiement pour services écosystémiques liés aux sols agricoles : les éleveurs qui adoptent des pratiques de pâturage régénérateur reçoivent des paiements proportionnels au carbone stocké dans leurs sols, mesuré par des carottes de sol analysées en laboratoire. Ce modèle est étudié par de nombreux gouvernements comme outil de politique agricole.</p></div>
""",

"ressources-naturelles/surexploitation": """
<h3>Les frontières planétaires : les limites de la biosphère</h3>
<p class="resume-text">Le concept de "limites planétaires", formalisé en 2009 par Johan Rockström et ses collègues du Stockholm Resilience Centre, identifie neuf processus biophysiques dont la stabilité est essentielle au maintien d'un "espace opérationnel sûr pour l'humanité". Ces limites définissent des seuils au-delà desquels des changements brusques et potentiellement irréversibles du système Terre pourraient se produire. En 2023, une mise à jour publiée dans Science Advances conclut que six des neuf limites ont déjà été franchies : changement climatique, intégrité de la biosphère, changements d'utilisation des terres, cycles biogéochimiques (azote et phosphore), eau douce et introduction d'entités nouvelles (polluants synthétiques).</p>
<p class="resume-text">La surexploitation des ressources naturelles est intimement liée à ces franchissements. Le taux d'extinction actuel des espèces (estimé entre 100 et 1 000 fois le taux naturel de fond) traduit une érosion rapide de l'intégrité biosphérique. L'excès d'azote et de phosphore dans les cycles biogéochimiques — résultant principalement de la production d'engrais de synthèse et de l'élevage intensif — provoque l'eutrophisation des écosystèmes aquatiques, créant des "zones mortes" comme celle du golfe du Mexique (22 000 km², aussi grande que le New Jersey).</p>
<div class="highlight-box"><p>L'empreinte écologique de l'humanité dépasse désormais la biocapacité de la Terre : nous consommons chaque année l'équivalent de 1,7 planète Terre. Le "Jour du dépassement" (Earth Overshoot Day), calculé par le Global Footprint Network, est passé du 31 décembre (1970) au 2 août (2023), signifiant que nous avons épuisé les ressources renouvelables de l'année en seulement 7 mois.</p></div>

<h3>La surpêche : effondrement des stocks halieutiques mondiaux</h3>
<p class="resume-text">La pêche industrielle mondiale a transformé les océans au cours du XXe siècle. La FAO estime que 34 % des stocks de poissons commerciaux sont exploités à des niveaux biologiquement non durables (en surexploitation), 60 % sont pleinement exploités (au maximum), et seuls 6 % restent sous-exploités. L'effondrement de la morue de Terre-Neuve (1992) est devenu le symbole de la surpêche : après des siècles d'abondance et malgré des avertissements scientifiques répétés, le gouvernement canadien a fermé la pêcherie en urgence en 1992. Trente ans plus tard, les stocks ne se sont toujours pas rétablis.</p>
<p class="resume-text">La pêche illégale, non réglementée et non déclarée (pêche INN) représente 15 à 30 % des captures mondiales, soit jusqu'à 26 millions de tonnes par an, d'une valeur de 10 à 23 milliards de dollars. Les chalutiers industriels de certains pays pratiquent la pêche INN à grande échelle dans les eaux des pays en développement qui n'ont pas les moyens de surveiller leurs ZEE. Les technologies de surveillance satellitaire (systèmes AIS, Vessel Monitoring Systems) et les bases de données mondiales des navires (Global Fishing Watch) permettent une meilleure détection, mais l'application des règles reste insuffisante.</p>
<div class="highlight-box"><p>Les subventions mondiales à la pêche atteignent 35 milliards de dollars par an, dont 22 milliards de subventions "nuisibles" qui encouragent la surcapacité et la surpêche (carburant subventionné, ports, construction de navires). Ces subventions sont concentrées dans quelques grands pays : Chine (7,2 Md$), Union européenne (3,8 Md$), États-Unis (3,2 Md$).</p></div>

<h3>La déforestation : liquidation du capital naturel forestier</h3>
<p class="resume-text">Les forêts couvrent environ 31 % des terres émergées (4 milliards d'hectares), mais leur superficie diminue chaque année. La déforestation nette mondiale est d'environ 10 millions d'hectares par an (FAO, 2020), soit approximativement la superficie du Portugal. Les forêts tropicales, qui abritent 50 à 75 % de la biodiversité terrestre tout en couvrant moins de 10 % des terres, sont les plus menacées. L'Amazonie brésilienne, le bassin du Congo, les forêts de Bornéo et de Sumatra subissent les pressions les plus intenses.</p>
<p class="resume-text">Les causes de la déforestation sont principalement agricoles : l'agriculture représente 73 % de la déforestation tropicale, dont l'élevage bovin (41 %), les cultures commerciales comme le soja (9 %), l'huile de palme (7 %) et d'autres produits de base. La déforestation en Amazonie brésilienne a été multipliée par deux sous la présidence Bolsonaro (2019-2022), atteignant 11 000 km² par an, avant de baisser significativement sous Lula. La déforestation en RDC, motivée par l'agriculture de subsistance et la production de charbon de bois, est la plus rapide d'Afrique.</p>
<div class="highlight-box"><p>Les forêts stockent environ 861 gigatonnes de carbone — plus que l'atmosphère entière (830 Gt de CO₂). La déforestation tropicale émet chaque année environ 4,8 Gt de CO₂, représentant 12 % des émissions mondiales de GES. Protéger et restaurer les forêts est donc une priorité climatique autant qu'une priorité pour la biodiversité.</p></div>
""",

"solutions-durables/energies-renouvelables": """
<h3>La révolution solaire : de la niche technologique à la source d'énergie dominante</h3>
<p class="resume-text">L'énergie solaire photovoltaïque (PV) a connu une trajectoire de coût sans précédent dans l'histoire de l'énergie : son coût a baissé de 99 % depuis 1976, et de 90 % au cours de la seule décennie 2010-2020. En 2023, l'énergie solaire PV est devenue la source d'électricité la moins chère jamais construite dans la majorité des pays du monde, selon l'AIE. Cette chute de coût résulte de la loi de Swanson (analogue à la loi de Moore pour les semi-conducteurs) : chaque doublement de la capacité installée mondiale réduit le coût des modules PV d'environ 20 %.</p>
<p class="resume-text">Les technologies solaires se diversifient : le solaire photovoltaïque de toiture (rooftop solar) démocratise la production d'énergie, permettant à chaque ménage ou entreprise de devenir producteur. Le solaire thermique concentré (CSP) utilise des miroirs pour concentrer le rayonnement solaire afin de produire de la chaleur, puis de l'électricité via une turbine, avec la possibilité de stockage thermique permettant une production nocturne. L'agrivoltaïsme installe des panneaux solaires au-dessus de cultures agricoles, permettant une double utilisation des terres tout en réduisant l'évapotranspiration et en maintenant les rendements de certaines cultures.</p>
<div class="highlight-box"><p>En 2023, la Chine a installé autant de capacité solaire PV en un an que la capacité totale installée mondiale en 2022. La puissance solaire installée mondiale a dépassé 1 000 GW en 2022, produisant environ 5 % de l'électricité mondiale, contre moins de 0,1 % en 2005.</p></div>

<h3>L'éolien : de la côte à la haute mer</h3>
<p class="resume-text">L'énergie éolienne, deuxième source d'énergie renouvelable après l'hydroélectricité, s'est développée en deux phases. Les parcs éoliens terrestres (onshore), moins coûteux, ont dominé jusqu'aux années 2010. L'éolien offshore, en mer, offre des vents plus forts et plus réguliers, une moindre opposition locale et la possibilité d'installer des machines de plus grande taille. Une éolienne offshore moderne peut atteindre 15-20 MW de puissance (rotors de 220 m de diamètre), soit 60 fois plus qu'une éolienne des années 1990. Le Royaume-Uni est leader mondial de l'éolien offshore, avec des parcs comme Hornsea Two (1,3 GW, 165 turbines, au large du Yorkshire).</p>
<p class="resume-text">L'éolien flottant représente la prochaine frontière : les éoliennes posées sur des plateformes flottantes ancrées permettent d'atteindre des profondeurs supérieures à 60 mètres, ouvrant des zones maritimes inaccessibles aux structures fondées sur le fond. La Norvège, avec son expertise dans les plateformes pétrolières offshore, est à la pointe de cette technologie. La France a annoncé des appels d'offres pour des parcs éoliens flottants en Méditerranée, dans des zones où les profondeurs rendent impossible l'éolien posé.</p>
<div class="highlight-box"><p>Le Danemark, pionnier de l'éolien, a produit en 2023 environ 88 % de son électricité à partir du vent, dépassant parfois 100 % de sa consommation et exportant l'excédent vers ses voisins. Ce résultat, obtenu grâce à une politique de long terme cohérente depuis les années 1970, est devenu un modèle international.</p></div>

<h3>Les défis du stockage et de l'intégration des énergies variables</h3>
<p class="resume-text">Le principal défi des énergies renouvelables variables (solaire et éolien) est leur intermittence : elles produisent de l'électricité quand le vent souffle ou quand le soleil brille, pas nécessairement quand la demande est la plus forte. L'intégration massive de ces sources dans les réseaux électriques nécessite des solutions de stockage, de flexibilité et d'interconnexion. Les batteries lithium-ion, dont le coût a chuté de 97 % depuis 1991, s'imposent pour le stockage de court terme (quelques heures). Les batteries de stockage stationnaire (comme les Megapack de Tesla) commencent à être déployées à grande échelle, remplaçant les centrales thermiques de pointe.</p>
<p class="resume-text">Pour le stockage saisonnier (surplus d'été à utiliser en hiver), d'autres technologies sont nécessaires. L'hydrogène vert, produit par électrolyse de l'eau avec de l'électricité renouvelable, est candidat au stockage et au transport de l'énergie à longue distance. STEP (Stations de Transfert d'Énergie par Pompage) reste la technologie de stockage d'énergie la plus déployée mondialement (85 % de la capacité mondiale de stockage d'électricité). La gestion intelligente de la demande (demand response), les véhicules électriques comme batteries mobiles (V2G, Vehicle-to-Grid) et les interconnexions transnationales complètent la boîte à outils de la transition.</p>
<div class="highlight-box"><p>L'Australie du Sud a vécu en septembre 2016 une panne d'électricité totale (blackout) liée à une combinaison de météo extrême et de fragilités du réseau. En réponse, elle a installé en 100 jours la plus grande batterie lithium-ion du monde de l'époque (100 MW/129 MWh, Tesla Powerwall). Devenue rentable dès la première année, elle a inspiré des projets similaires dans le monde entier.</p></div>
""",

"solutions-durables/economie-circulaire": """
<h3>Les principes fondateurs de l'économie circulaire</h3>
<p class="resume-text">L'économie circulaire repose sur trois principes directeurs, formalisés par la Fondation Ellen MacArthur : éliminer les déchets et la pollution dès la conception (design out waste), maintenir les produits et matériaux en circulation à leur plus haute valeur, et régénérer les systèmes naturels. Elle s'oppose à l'économie linéaire "extraire-produire-jeter" qui a dominé l'industrialisation et repose sur l'idée que les "déchets" d'un processus sont les ressources d'un autre.</p>
<p class="resume-text">La notion de "cradle to cradle" (du berceau au berceau), développée par l'architecte William McDonough et le chimiste Michael Braungart, distingue deux cycles : le cycle biologique, où les matières organiques retournent à la biosphère par compostage ou digestion anaérobie, et le cycle technique, où les matériaux synthétiques circulent en boucle fermée sans jamais devenir des déchets. Concrètement, cela implique de concevoir des produits facilement réparables, démontables, et dont les composants peuvent être réutilisés, rénovés ou recyclés sans perte de qualité.</p>
<div class="highlight-box"><p>L'économie circulaire représente une opportunité économique majeure : la Fondation Ellen MacArthur estime que la transition vers un modèle circulaire en Europe pourrait générer une économie nette de matériaux de 600 milliards d'euros par an d'ici 2030 et créer 580 000 emplois supplémentaires.</p></div>

<h3>Éco-conception et durée de vie des produits</h3>
<p class="resume-text">L'éco-conception intègre les critères environnementaux dès la phase de conception d'un produit, en analysant son cycle de vie complet (ACV) : extraction des matières premières, fabrication, distribution, utilisation, fin de vie. Elle cherche à réduire l'impact environnemental à chaque étape. Un exemple de réussite : Fairphone, fabricant néerlandais de smartphones, a conçu un téléphone modulaire dont les composants peuvent être remplacés individuellement par l'utilisateur, prolongeant significativement la durée de vie comparativement aux smartphones conventionnels scellés et irréparables.</p>
<p class="resume-text">L'obsolescence programmée — la pratique consistant à réduire volontairement la durée de vie d'un produit pour forcer son remplacement — est dans le collimateur des législateurs. L'Union européenne a adopté en 2021 le "droit à la réparation", obligeant les fabricants d'appareils électroménagers à fournir des pièces de rechange pendant 10 ans. L'indice de réparabilité, introduit en France en 2021 puis transformé en indice de durabilité, informe les consommateurs sur la capacité à réparer les produits électroniques. Des plateformes comme iFixit ou les repair cafés popularisent la culture de la réparation.</p>
<div class="highlight-box"><p>Allonger la durée de vie d'un smartphone de 1 à 4 ans réduit son empreinte carbone annuelle de 40 %. Plus de 80 % de l'impact environnemental d'un smartphone se concentre dans sa fabrication (extraction des minerais, assemblage), pas dans son usage. Réparer et garder son téléphone plus longtemps est l'action individuelle la plus efficace pour réduire l'empreinte numérique.</p></div>

<h3>Symbioses industrielles et parcs éco-industriels</h3>
<p class="resume-text">La symbiose industrielle est une forme concrète d'économie circulaire à l'échelle d'un territoire : les déchets et sous-produits d'une entreprise deviennent les ressources d'une autre. Le parc industriel de Kalundborg (Danemark), fonctionnel depuis les années 1960 et devenu un modèle mondial, illustre cette approche : la centrale électrique fournit sa vapeur résiduelle à une raffinerie de pétrole et à une usine pharmaceutique (Novo Nordisk), ses cendres volantes à un cimentier et à des agriculteurs locaux, et ses eaux de refroidissement à un pisciculture. Au total, 30 flux d'échange ont été identifiés, réduisant les déchets et les consommations d'eau, d'énergie et de matières.</p>
<p class="resume-text">En France, les démarches d'écologie industrielle et territoriale (EIT) se multiplient : la plateforme industrialo-portuaire de Dunkerque, l'un des plus grands sites de France, a développé une symbiose entre son usine sidérurgique (ArcelorMittal), sa centrale électrique (Engie) et plusieurs industries chimiques. Des flux de gaz sidérurgiques, de vapeur, d'eau industrielle et de matières sont échangés entre les acteurs, générant des économies de CO₂ estimées à 500 000 tonnes par an. La région Hauts-de-France est l'une des pionnières de ces démarches en France.</p>
<div class="highlight-box"><p>Selon l'ADEME, une démarche d'écologie industrielle et territoriale bien conduite permet des économies de 15 à 40 % sur les consommations d'énergie et de matières premières des entreprises participantes, tout en créant des liens de coopération qui renforcent la résilience économique locale.</p></div>
""",

"solutions-durables/agroecologie": """
<h3>Les fondements scientifiques de l'agroécologie</h3>
<p class="resume-text">L'agroécologie est à la fois une science, un ensemble de pratiques agricoles et un mouvement social. Comme science, elle applique les concepts et principes de l'écologie — interdépendances, cycles biogéochimiques, dynamiques de populations — aux systèmes agricoles. Elle considère la ferme non comme une usine à produire des aliments mais comme un écosystème géré, dont la santé et la résilience sont des objectifs autant que la productivité. Les pionniers de l'agroécologie incluent le botaniste et agriculteur japonais Masanobu Fukuoka ("la révolution du brin de paille"), le botaniste russe I.G. Taranov et, plus récemment, le biologiste américain Miguel Altieri à Berkeley.</p>
<p class="resume-text">Ses principes fondamentaux comprennent la diversification (polycultures, agroforesterie, rotations complexes), la réduction des intrants externes (engrais de synthèse, pesticides), la valorisation des processus écologiques (fixation biologique de l'azote, pollinisation naturelle, régulation biologique des ravageurs) et la connaissance des particularités locales (pédologie, microclimat, savoir agricole traditionnel). L'agroécologie propose de "travailler avec la nature plutôt que contre elle", selon la formule de Sir Albert Howard, précurseur de l'agriculture biologique.</p>
<div class="highlight-box"><p>Une méta-analyse de 2018 publiée dans Nature Sustainability, portant sur 52 études comparant l'agriculture biologique et conventionnelle, conclut que l'agriculture biologique produit en moyenne 20 % moins mais utilise 45 % moins d'énergie, émet 20 % moins de GES et génère 30 % plus de biodiversité par unité de surface.</p></div>

<h3>Pratiques agroécologiques : exemples concrets et résultats</h3>
<p class="resume-text">L'agroforesterie intègre des arbres dans les systèmes agricoles, créant des synergies entre cultures, élevage et arbres. Dans le Sahel, le programme FMNR (Farmer Managed Natural Regeneration) a régénéré 5 millions d'hectares de terres dégradées au Niger en permettant aux agriculteurs de laisser repousser les souches d'arbres indigènes, améliorant la fertilité des sols, réduisant l'érosion et augmentant les rendements des cultures intercalaires de 18 à 23 %. En Europe, les systèmes bocagers et les haies champêtres fournissent des habitats pour les auxiliaires des cultures (prédateurs naturels des ravageurs), réduisant le besoin de pesticides.</p>
<p class="resume-text">La gestion intégrée des ravageurs (IPM, Integrated Pest Management) combine des méthodes biologiques, mécaniques, culturelles et chimiques (en dernier recours) pour contrôler les parasites agricoles. La lutte biologique utilise des prédateurs naturels (coccinelles contre les pucerons, trichogrammes contre les chenilles) ou des biopesticides (Bacillus thuringiensis, champignons entomopathogènes). Au Vietnam, la mise en œuvre de l'IPM dans les rizières a réduit l'utilisation d'insecticides de 75 % tout en maintenant les rendements, générant des économies de 1 à 2 milliards de dollars par an pour les agriculteurs.</p>
<div class="highlight-box"><p>Les systèmes agroforestiers couvrent environ 1 milliard d'hectares dans le monde, représentant 43 % des terres agricoles. Ils stockent en moyenne 50 tonnes de carbone par hectare de plus que les systèmes monoculturaux équivalents, faisant de l'agroforesterie l'une des solutions d'atténuation du changement climatique les plus rentables disponibles.</p></div>

<h3>Débats et limites : peut-on nourrir le monde avec l'agroécologie ?</h3>
<p class="resume-text">La question centrale du débat sur l'agroécologie est celle de sa capacité à nourrir une population mondiale de 10 milliards d'habitants en 2050. Les partisans de l'agriculture intensive conventionnelle soutiennent que les hauts rendements à l'hectare sont indispensables pour éviter de défricher davantage de terres naturelles, et que réduire les intrants réduira mécaniquement les productions. Les partisans de l'agroécologie rétorquent que ces comparaisons ne tiennent pas compte des pertes post-récolte (30-40 % des aliments produits ne sont jamais consommés), du gaspillage alimentaire et de la surconsommation dans les pays riches.</p>
<p class="resume-text">Des études récentes tentent de réconcilier ces perspectives. Une modélisation publiée dans Nature Communications (2017) conclut qu'une transition vers 100 % d'agriculture biologique mondiale nécessiterait une augmentation des surfaces agricoles de 16 à 33 % pour maintenir les niveaux de production actuels — une augmentation incompatible avec la conservation de la biodiversité. Mais cette conclusion dépend fortement des régimes alimentaires : si la consommation de viande dans les pays riches diminuait de 50 %, l'agroécologie pourrait nourrir le monde sur les surfaces actuelles. La transition alimentaire et la transition agricole sont donc indissociables.</p>
<div class="highlight-box"><p>La France est un laboratoire de l'agroécologie à grande échelle : le plan Ecophyto vise à réduire l'utilisation des pesticides de 50 % d'ici 2030. Le réseau des GIEE (Groupements d'Intérêt Économique et Environnemental) rassemble des agriculteurs qui expérimentent collectivement des pratiques agroécologiques sur leurs exploitations, bénéficiant d'un cadre légal et financier favorable depuis la loi d'avenir agricole de 2014.</p></div>
""",

"solutions-durables/villes-durables": """
<h3>L'urbanisation mondiale : défi et opportunité pour la durabilité</h3>
<p class="resume-text">En 2007, pour la première fois dans l'histoire de l'humanité, plus de la moitié de la population mondiale vivait dans des villes. En 2050, cette proportion devrait atteindre 68 %, soit 6,7 milliards de citadins. Cette urbanisation massive se concentre dans les pays en développement : d'ici 2050, l'Asie et l'Afrique abriteront 90 % de la croissance urbaine mondiale. Des mégalopoles comme Lagos (Nigeria), Kinshasa (RDC) ou Dhaka (Bangladesh) devront accueillir des dizaines de millions d'habitants supplémentaires en quelques décennies, dans des contextes de ressources et de gouvernance souvent limités.</p>
<p class="resume-text">Les villes sont responsables de 75 % des émissions mondiales de CO₂ et consomment 60 à 80 % de l'énergie mondiale — mais elles concentrent également les innovations, les capacités financières et les compétences techniques qui permettent de concevoir des solutions. Une ville dense et bien planifiée peut être paradoxalement plus sobre en énergie et en ressources qu'un habitat dispersé : les habitants d'appartements urbains consomment en moyenne moins d'énergie pour le chauffage, se déplacent moins en voiture et ont une empreinte carbone inférieure aux habitants des zones périurbaines ou rurales dans les pays riches.</p>
<div class="highlight-box"><p>New York, malgré son image de métropole énergivore, a l'une des empreintes carbone par habitant les plus basses des États-Unis, grâce à sa densité, son réseau de métro et la quasi-absence de voiture individuelle pour les déplacements quotidiens. Un New-Yorkais émet en moyenne 6 tonnes de CO₂ par an, contre 13 tonnes pour un Américain moyen.</p></div>

<h3>Mobilité urbaine durable : des transports décarbonés</h3>
<p class="resume-text">La mobilité représente 30 à 40 % des émissions de CO₂ des villes et constitue une priorité pour les politiques urbaines climatiques. Les stratégies de mobilité durable suivent le modèle "Éviter-Transférer-Améliorer" : éviter les déplacements inutiles (télétravail, mixité fonctionnelle des quartiers), transférer les déplacements vers des modes moins émissifs (marche, vélo, transports en commun), améliorer les technologies des véhicules restants (électrification). Les "villes des 15 minutes", popularisées par Carlos Moreno et adoptées comme objectif par Paris, Amsterdam et d'autres métropoles, cherchent à organiser l'espace urbain pour que chaque résident puisse accéder à pied ou à vélo à ses besoins quotidiens en moins de 15 minutes.</p>
<p class="resume-text">Les transports en commun à haut niveau de service (métro, tramway, BRT - Bus Rapid Transit) sont l'épine dorsale de la mobilité urbaine durable. Bogotá (Colombie) a transformé sa mobilité avec TransMilenio, le plus grand réseau BRT du monde, et son réseau de 550 km de pistes cyclables, réduisant les temps de trajet et les émissions de polluants. Amsterdam et Copenhague ont investi pendant des décennies dans des infrastructures cyclables de qualité : 62 % des déplacements domicile-travail se font à vélo à Copenhague, évitant l'émission de 90 000 tonnes de CO₂ par an.</p>
<div class="highlight-box"><p>La congestion automobile coûte à Paris 4 milliards d'euros par an en perte de temps et de productivité selon l'Inrix Traffic Scorecard. La mise en place de péages urbains à congestion (comme à Londres depuis 2003, Stockholm depuis 2006, ou Singapore depuis 1975) a réduit la circulation de 10 à 30 % dans les zones concernées, avec des effets positifs sur la qualité de l'air et les finances publiques.</p></div>

<h3>Nature en ville : les infrastructures vertes et bleues</h3>
<p class="resume-text">Les infrastructures vertes (parcs, forêts urbaines, jardins, toits et murs végétalisés) et bleues (rivières, canaux, zones humides, bassins de rétention) jouent un rôle croissant dans la durabilité urbaine. Elles fournissent une palette de services écosystémiques : régulation thermique (un arbre adulte peut réduire la température de l'air jusqu'à 8 °C par évapotranspiration), absorption des eaux pluviales (réduisant les risques d'inondations urbaines), séquestration de CO₂, filtration des polluants atmosphériques et amélioration du bien-être des habitants (les études montrent une corrélation entre proximité de la végétation et santé mentale).</p>
<p class="resume-text">Singapour a développé une vision ambitieuse de "Cité dans un jardin" : depuis les années 1960, la cité-État a planté plus de 2 millions d'arbres et vise à couvrir 80 % de ses bâtiments de végétation d'ici 2030 (toits verts, jardins suspendus, façades végétalisées). La forêt de Supertrees du Gardens by the Bay, structures arboriformes de 25 à 50 mètres de hauteur, génèrent de l'énergie solaire et collectent les eaux de pluie. Medellín (Colombie), anciennement considérée comme l'une des villes les plus dangereuses du monde, a planté 30 "corridors verts" de 17 km de long, réduisant la température locale de 4 °C dans les zones concernées.</p>
<div class="highlight-box"><p>Le concept de "ville éponge" (sponge city), développé en Chine et appliqué dans 30 villes pilotes depuis 2015, vise à absorber les eaux pluviales naturellement plutôt que de les évacuer rapidement. Wuhan, régulièrement touchée par des inondations, a investi dans des zones humides, des toits verts, des revêtements perméables et des jardins pluviaux. Ces solutions d'infrastructures vertes coûtent en général 30 à 50 % moins cher que les équivalents techniques en béton.</p></div>
""",

"solutions-durables/geo-ingenierie": """
<h3>Géo-ingénierie solaire : principes et controverses</h3>
<p class="resume-text">La gestion du rayonnement solaire (Solar Radiation Management, SRM) désigne un ensemble de techniques visant à réduire l'énergie solaire atteignant la surface terrestre, refroidissant ainsi la planète. La technique la plus étudiée est l'injection de particules soufrées dans la stratosphère (SAI, Stratospheric Aerosol Injection) : des avions spécialement modifiés injecteraient des millions de tonnes de dioxyde de soufre ou de carbonate de calcium à 20-25 km d'altitude. Ces particules diffuseraient une partie du rayonnement solaire, reproduisant artificiellement l'effet de refroidissement observé après de grandes éruptions volcaniques comme le Pinatubo (1991, qui a refroidi le climat mondial de 0,5 °C pendant deux ans).</p>
<p class="resume-text">D'autres approches SRM incluent la gestion de la brillance des nuages marins (Marine Cloud Brightening), qui consisterait à pulvériser de l'eau de mer dans les nuages bas pour les rendre plus réfléchissants, et l'augmentation de la réflectivité de la surface terrestre (peindre les toits en blanc, utiliser des cultures à feuilles plus brillantes). Ces techniques sont théoriquement capables de refroidir rapidement le climat — en quelques semaines ou mois — contrairement à la réduction des émissions, dont les effets se mesurent en décennies.</p>
<div class="highlight-box"><p>L'éruption du Pinatubo (Philippines) en juin 1991 a injecté 20 millions de tonnes de SO₂ dans la stratosphère, réduisant l'insolation mondiale de 2,5 % et la température globale de 0,5 °C pendant 1-2 ans. Cet "expérience naturelle" est l'une des principales sources d'information sur les effets potentiels de l'injection d'aérosols stratosphériques.</p></div>

<h3>Risques et dilemmes éthiques de la géo-ingénierie</h3>
<p class="resume-text">La géo-ingénierie soulève des questions techniques, éthiques et politiques profondes. Sur le plan technique, le principal risque de la SAI est "l'effet d'arrêt" : si l'injection est stoppée brusquement (guerre, effondrement économique, désaccord politique), le réchauffement supprimé se produirait très rapidement, en quelques années, ce qui serait bien plus difficile à gérer que le réchauffement graduel évité — c'est le "problème du bras cassé". De plus, les aérosols stratosphériques pourraient réduire les précipitations monsoonales en Asie et en Afrique, menaçant l'agriculture de milliards de personnes.</p>
<p class="resume-text">Sur le plan éthique, la géo-ingénierie pose la question de la gouvernance mondiale : qui décide d'intervenir sur le climat ? Un État pourrait agir unilatéralement — les coûts sont à la portée d'une puissance moyenne (quelques milliards de dollars par an) — sans le consentement des pays qui en subiraient les effets secondaires. Le "risque moral" est également invoqué : l'existence d'un "plan B" technique réduirait-elle l'urgence politique de décarboner ? Enfin, la SRM traite le symptôme (la chaleur) sans la cause (le CO₂) — l'acidification des océans se poursuivrait.</p>
<div class="highlight-box"><p>En 2021, le projet SCoPEx (Stratospheric Controlled Perturbation Experiment) de l'Université Harvard, qui prévoyait de lâcher un très petit ballon de calcaire dans la stratosphère (100 g de CaCO₃), a été suspendu après l'opposition d'un comité autochtone sami en Suède (où le vol devait avoir lieu) et de nombreux scientifiques. Cet épisode illustre les défis de gouvernance des expériences de géo-ingénierie, même à très petite échelle.</p></div>

<h3>Captage et stockage de carbone : entre nécessité et faisabilité</h3>
<p class="resume-text">Le captage et stockage géologique de carbone (CSC ou CCS) consiste à capturer le CO₂ à la source d'émission (centrale électrique, cimenterie, aciérie) et à le comprimer et l'injecter dans des formations géologiques profondes (aquifères salins, gisements de pétrole épuisés). La technologie est éprouvée à petite échelle : le projet Sleipner (Norvège, depuis 1996) injecte environ 1 million de tonnes de CO₂ par an dans un aquifère salin sous la mer du Nord. Cependant, le déploiement à grande échelle reste limité : en 2023, la capacité mondiale de captage représente moins de 0,1 % des émissions mondiales.</p>
<p class="resume-text">Le captage direct dans l'air (DAC, Direct Air Capture) aspire le CO₂ de l'atmosphère ambiante, sans nécessiter de source d'émission concentrée. L'entreprise islandaise Climeworks a inauguré en 2021 l'usine Orca (4 000 t CO₂/an), puis l'usine Mammoth (36 000 t/an) en 2024. Ces capacités sont minuscules comparées aux 37 milliards de tonnes émises annuellement, et le coût actuel (400-1000 $/t CO₂) est prohibitif à grande échelle. La plupart des scénarios GIEC nécessitant de maintenir le réchauffement sous 1,5 °C supposent un déploiement massif de DAC ou de BECCS (Bioénergie avec CCS) — des technologies non encore prouvées à l'échelle requise.</p>
<div class="highlight-box"><p>La biomasse avec captage et stockage du carbone (BECCS) combinerait des centrales brûlant de la biomasse (qui absorbe le CO₂ en poussant) avec le captage du CO₂ émis à la combustion, créant théoriquement des "émissions négatives". Cependant, les surfaces agricoles nécessaires pour produire suffisamment de biomasse représenteraient une concurrence majeure avec la production alimentaire et la conservation des forêts — un dilemme d'utilisation des terres non résolu.</p></div>
"""
}

def inject_content(existing_content, new_paragraphs):
    """Insert new paragraphs before the closing </section> of the contenu section."""
    # Find the contenu section and inject before its closing tag
    pattern = r'(</section>\s*\n?\s*<section[^>]*id="quiz")'
    replacement = new_paragraphs + r'\1'
    result = re.sub(pattern, replacement, existing_content)
    if result == existing_content:
        # If quiz section not found, try injecting before last </section>
        # Find the last occurrence of </section> before any quiz
        idx = existing_content.rfind('</section>')
        if idx != -1:
            result = existing_content[:idx] + new_paragraphs + existing_content[idx:]
    return result

with open(FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

modified = 0
for key, enrichment in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        if page.get('type') in ('course', 'lesson'):
            original_len = len(page['content'])
            page['content'] = inject_content(page['content'], enrichment)
            new_len = len(page['content'])
            print(f"  {key}: {original_len} -> {new_len} chars (+{new_len-original_len})")
            modified += 1

print(f"\nTotal modified: {modified} pages")

with open(FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("JSON saved successfully.")
