import json

ENRICHMENTS = {
"diplomatie/histoire-de-la-diplomatie": """
<h3>Le Concert des nations et la diplomatie du XIXe siècle</h3>
<p class="resume-text">Le <strong>Congrès de Vienne</strong> (1814-1815) inaugura une ère de diplomatie multilatérale systématique. Les grandes puissances européennes se réunissaient périodiquement pour régler les crises avant qu'elles ne dégénèrent en conflits. Ce Concert européen maintint une paix relative pendant près d'un siècle. Il introduisit aussi des innovations institutionnelles durables : hiérarchie des représentants diplomatiques, inviolabilité des ambassades, règles de préséance protocolaire.</p>
<p class="resume-text">La <strong>Conférence de La Haye</strong> de 1899, convoquée par le tsar Nicolas II, marqua un tournant : pour la première fois, des puissances extra-européennes (États-Unis, Mexique, Chine, Japon) participèrent à des négociations de droit international. La conférence créa la Cour permanente d'arbitrage, première institution juridictionnelle internationale permanente.</p>
<div class="highlight-box"><p>Le terme <strong>diplomate</strong> apparaît en français à la fin du XVIIIe siècle. La France du Roi-Soleil est considérée comme le berceau de la diplomatie moderne : Louis XIV imposa le français comme langue diplomatique universelle, statut qu'il conserva jusqu'au XXe siècle.</p></div>
<h3>La diplomatie au XXe siècle : institutionnalisation et multilatéralisme</h3>
<p class="resume-text">La Première Guerre mondiale démontra l'échec de la diplomatie secrète des alliances entremêlées. Le président américain Woodrow Wilson proposa ses <strong>Quatorze Points</strong> (1918), dont le principe de la diplomatie ouverte et la création d'une Société des Nations. Bien que les États-Unis n'adhèrent finalement pas à la SDN, celle-ci représenta une innovation majeure : une organisation permanente chargée de maintenir la paix par la négociation collective.</p>
<p class="resume-text">Après 1945, l'<strong>ONU</strong> institutionnalisa la diplomatie multilatérale à une échelle sans précédent. Le Conseil de sécurité, l'Assemblée générale et les agences spécialisées créèrent un système diplomatique permanent. La Guerre froide bipolarisa la diplomatie mondiale : chaque bloc développa ses propres institutions et usa intensivement de la diplomatie secrète pour ses opérations clandestines.</p>
<div class="highlight-box"><p>La <strong>crise des missiles de Cuba</strong> (1962) : 13 jours de négociations secrètes entre Kennedy et Khrouchtchev évitèrent une guerre nucléaire. Cette crise conduisit à l'installation du téléphone rouge reliant directement la Maison Blanche au Kremlin.</p></div>
<h3>La diplomatie contemporaine : multiplication des acteurs</h3>
<p class="resume-text">La diplomatie du XXIe siècle se caractérise par une <strong>fragmentation des acteurs</strong>. Aux diplomates professionnels s'ajoutent désormais les ONG, les firmes multinationales, les think tanks et les diasporas organisées. Cette diplomatie de réseaux complexifie la négociation mais enrichit aussi les ressources disponibles.</p>
<p class="resume-text">La <strong>diplomatie numérique</strong> a transformé la communication diplomatique. Les ministres des Affaires étrangères s'adressent directement à des millions de followers, court-circuitant parfois les canaux officiels. La pandémie de Covid-19 a généralisé la diplomatie par vidéoconférence, réduisant les coûts mais aussi la richesse des interactions informelles.</p>
<p class="resume-text">Les <strong>nouvelles frontières diplomatiques</strong> incluent la cyberdiplomatie, la diplomatie climatique (négociations COP depuis 1995), la diplomatie spatiale et la diplomatie des données autour de l'intelligence artificielle. Ces domaines exigent des diplomates une expertise technique croissante et une collaboration avec des scientifiques.</p>
<div class="highlight-box"><p>La <strong>diplomatie de la soft power</strong> — terme forgé par Joseph Nye — désigne l'influence exercée par la culture, les valeurs et les institutions plutôt que par la force. Les Alliances françaises, le British Council, le Goethe-Institut ou les Instituts Confucius chinois sont des instruments de cette diplomatie culturelle qui prépare le terrain pour les négociations formelles.</p></div>
<h3>La formation et le métier de diplomate</h3>
<p class="resume-text">La <strong>carrière diplomatique</strong> suit généralement un parcours institutionnel strict. En France, l'Institut national du service public forme les cadres du Quai d'Orsay. Aux États-Unis, le Foreign Service Institute prépare les diplomates du Département d'État. Ces formations combinent droit international, économie, langues étrangères, histoire des relations internationales et protocole.</p>
<p class="resume-text">Le diplomate moderne doit maîtriser des compétences diversifiées : négociation et médiation, analyse politique, communication publique et gestion de crise. L'intelligence émotionnelle et la capacité à établir des relations de confiance durables restent des atouts irremplaçables que nulle technologie ne peut remplacer.</p>
""",

"diplomatie/droit-diplomatique": """
<h3>Les privilèges et immunités diplomatiques : fondements et controverses</h3>
<p class="resume-text">Les <strong>privilèges diplomatiques</strong> reposent sur la Convention de Vienne sur les relations diplomatiques (1961), ratifiée par 193 États. Ce traité codifie des pratiques coutumières vieilles de plusieurs siècles : inviolabilité de la personne du diplomate et de sa résidence, exemption d'impôts et de poursuites pénales dans l'État d'accueil, liberté de communication avec le gouvernement d'envoi.</p>
<p class="resume-text">L'<strong>immunité diplomatique</strong> suscite régulièrement des controverses. Des diplomates ont invoqué leur immunité après des accidents graves ou des agressions. L'État d'envoi peut lever l'immunité de son représentant, mais il est rare qu'il le fasse spontanément. La solution habituelle est la déclaration de persona non grata, qui oblige l'État d'envoi à rappeler son diplomate.</p>
<div class="highlight-box"><p>En 1984, la policière Yvonne Fletcher fut tuée par balle devant l'ambassade libyenne à Londres. Les diplomates libyens bénéficièrent de l'immunité et quittèrent le Royaume-Uni sans être poursuivis — cas emblématique des tensions entre souveraineté diplomatique et justice.</p></div>
<h3>La valise diplomatique et la communication sécurisée</h3>
<p class="resume-text">La <strong>valise diplomatique</strong> est un conteneur inviolable utilisé pour transporter des communications et des objets entre une ambassade et son gouvernement. Selon la Convention de Vienne, elle ne peut être ouverte ni retenue par les autorités de l'État de transit. Cette inviolabilité absolue a parfois été abusée : des États ont utilisé des valises diplomatiques pour transporter des armes ou des personnes séquestrées.</p>
<p class="resume-text">Les révélations <strong>WikiLeaks</strong> (2010), qui ont publié 250 000 câbles diplomatiques américains, ont montré la vulnérabilité des systèmes de communication chiffrés et provoqué une crise diplomatique majeure dans des dizaines de pays. Ces révélations ont accéléré la modernisation des protocoles de sécurité informatique dans les ministères des affaires étrangères du monde entier.</p>
<h3>Le droit consulaire : protéger les ressortissants à l'étranger</h3>
<p class="resume-text">Le <strong>droit consulaire</strong> est régi par la Convention de Vienne sur les relations consulaires (1963). Les consulats ont pour mission principale de protéger les ressortissants de l'État d'envoi : délivrer des passeports et visas, authentifier des documents, assister les ressortissants arrêtés. L'article 36 impose à l'État d'accueil d'informer tout ressortissant étranger arrêté de son droit à contacter son consulat.</p>
<p class="resume-text">La Cour internationale de Justice a rendu plusieurs arrêts importants sur les violations de l'article 36. Dans l'affaire <strong>LaGrand</strong> (2001), elle a condamné les États-Unis pour n'avoir pas informé deux ressortissants allemands condamnés à mort de leur droit consulaire. Dans l'affaire <strong>Avena</strong> (2004), le Mexique a obtenu que 51 de ses ressortissants dans les couloirs de la mort américains soient informés de leurs droits.</p>
<h3>L'asile diplomatique et les réfugiés politiques</h3>
<p class="resume-text">L'<strong>asile diplomatique</strong> — accorder refuge dans une ambassade à une personne poursuivie dans l'État d'accueil — n'est pas reconnu en droit international universel. Il est pratiqué surtout en Amérique latine, fondé sur des conventions régionales. Les cas célèbres incluent le cardinal Mindszenty réfugié à l'ambassade américaine à Budapest de 1956 à 1971, et Julian Assange réfugié à l'ambassade équatorienne à Londres de 2012 à 2019.</p>
<p class="resume-text">Le droit d'asile diplomatique crée des tensions juridiques profondes : l'État d'accueil conteste généralement sa légitimité et peut encercler l'ambassade pour empêcher toute sortie. Ces situations peuvent durer des années, créant des impasses diplomatiques inextricables entre obligations de souveraineté et engagements humanitaires.</p>
<div class="highlight-box"><p>L'affaire <strong>Julian Assange</strong> illustre la complexité du droit diplomatique moderne : réfugié à l'ambassade équatorienne à Londres pendant 7 ans (2012-2019), il bénéficia de l'asile diplomatique accordé par l'Équateur malgré les pressions britanniques — un cas sans précédent dans l'histoire diplomatique occidentale.</p></div>
""",

"diplomatie/negociation-internationale": """
<h3>Les styles de négociation selon les cultures</h3>
<p class="resume-text">La recherche interculturelle a identifié des <strong>styles de négociation nationaux</strong> distincts. Les négociateurs américains valorisent la rapidité, les résultats concrets et les contrats détaillés. Les Japonais privilégient le consensus interne, les relations à long terme et évitent les confrontations directes. Les Français utilisent la rhétorique et le débat de principes avant les concessions pratiques.</p>
<p class="resume-text">Ces différences culturelles peuvent provoquer des malentendus coûteux. Un silence dans une négociation signifie accord en Finlande, réflexion au Japon, désaccord en France. Une offre initiale très basse est attendue dans certaines cultures mais perçue comme insultante dans le contexte nord-européen. Le <strong>high-context communication</strong> (messages implicites) des cultures asiatiques s'oppose au <strong>low-context communication</strong> (explicite, directe) des cultures anglophones.</p>
<div class="highlight-box"><p>La <strong>méthode Harvard de négociation</strong>, développée par Roger Fisher et William Ury dans <em>Getting to Yes</em> (1981), propose de se concentrer sur les <em>intérêts</em> (pourquoi on veut quelque chose) plutôt que sur les <em>positions</em> (ce qu'on demande), pour trouver des solutions créatives satisfaisant toutes les parties.</p></div>
<h3>Les techniques de négociation diplomatique</h3>
<p class="resume-text">Les <strong>négociations multilatérales</strong> dans les grandes conférences internationales obéissent à des procédures complexes. Les blocs de négociation (G77, Union européenne, AOSIS pour les petits États insulaires) permettent à des dizaines d'États de coordonner leurs positions. Le <strong>text-based negotiation</strong> — travailler sur un texte commun en ajoutant, supprimant ou mettant entre crochets des formules — est la méthode standard dans ces enceintes.</p>
<p class="resume-text">Parmi les tactiques classiques : la <strong>fenêtre de tir</strong> (exploiter une opportunité politique éphémère), le <strong>lien d'issues</strong> (conditionner un accord sur un sujet à un accord sur un autre), le <strong>single negotiating text</strong> (présenter un texte unique de compromis pour éviter la cacophonie des contre-propositions).</p>
<div class="highlight-box"><p>Les <strong>Accords d'Oslo</strong> (1993) furent négociés secrètement en Norvège pendant neuf mois entre l'OLP et Israël, à l'insu des États-Unis. Cette discrétion était indispensable : les négociateurs des deux camps auraient été politiquement vulnérables si leurs concessions avaient été connues prématurément.</p></div>
<h3>La médiation et les bons offices dans les conflits</h3>
<p class="resume-text">Quand la négociation directe échoue, des tiers interviennent. La <strong>médiation</strong> implique un médiateur actif qui propose des solutions et peut faire pression sur les parties. Les <strong>bons offices</strong> se limitent à faciliter le contact entre parties qui refusent de se parler directement. La <strong>Norvège</strong> a développé une expertise de médiation remarquable (Oslo, Sri Lanka, Colombie, Philippines) en combinant discrétion et réseau d'ONG.</p>
<p class="resume-text">Les médiateurs les plus efficaces combinent plusieurs atouts : la légitimité (statut reconnu par toutes les parties), les ressources (capacité à offrir des incitations), la neutralité perçue et la connaissance du dossier. La <strong>Suisse</strong> assure traditionnellement la représentation des intérêts d'États qui ont rompu leurs relations diplomatiques.</p>
<div class="highlight-box"><p>L'<strong>Accord de Dayton</strong> (1995), qui mit fin à la guerre en Bosnie, fut négocié en 21 jours à la base aérienne de Wright-Patterson en Ohio. L'isolement des délégations, coupées de leurs capitales et des médias, était délibéré : il forçait les chefs de délégation à prendre des décisions sans consulter leur opinion publique.</p></div>
<h3>La diplomatie coercitive et les sanctions</h3>
<p class="resume-text">La diplomatie ne se limite pas à la persuasion : elle inclut aussi des formes de <strong>pression légitimée</strong>. Les <strong>sanctions économiques</strong> (embargo commercial, gel d'avoirs, interdiction de voyager) sont un instrument de coercition non militaire dont l'usage s'est multiplié depuis 1990. Le Conseil de sécurité de l'ONU en a imposé contre des dizaines d'États et d'entités.</p>
<p class="resume-text">L'efficacité des sanctions reste débattue. Des études montrent qu'elles réussissent davantage lorsqu'elles sont ciblées (smart sanctions visant les dirigeants, pas les populations), soutenues par une large coalition internationale et accompagnées d'une porte de sortie diplomatique claire. Elles ont échoué à changer le comportement de Cuba ou de la Corée du Nord, mais ont contraint l'Afrique du Sud de l'apartheid et aidé à dénouer la crise nucléaire libyenne de 2003.</p>
""",

"diplomatie/diplomatie-economique": """
<h3>Les outils de la diplomatie économique</h3>
<p class="resume-text">La <strong>diplomatie économique</strong> mobilise un arsenal varié d'instruments. Les <strong>accords commerciaux préférentiels</strong> offrent des avantages tarifaires en échange d'engagements politiques ou économiques. Les <strong>agences de promotion des exportations</strong> — Bpifrance, UK Export Finance, US Export-Import Bank — fournissent des financements et des garanties que le secteur privé ne peut offrir pour des marchés risqués, permettant à des entreprises nationales de remporter de grands contrats d'infrastructure dans des pays en développement.</p>
<div class="highlight-box"><p>La <strong>Belt and Road Initiative</strong> (BRI) chinoise, lancée en 2013, illustre la diplomatie économique à grande échelle : plus de 1 000 milliards de dollars investis dans des infrastructures dans 140 pays. Ses critiques parlent de <em>diplomatie de la dette</em> quand des pays surendettés accordent des concessions stratégiques en échange de rééchelonnements.</p></div>
<h3>Négociations commerciales multilatérales et bilatérales</h3>
<p class="resume-text">Le <strong>GATT</strong> (1947) puis l'<strong>OMC</strong> (1995) ont structuré les négociations commerciales multilatérales en cycles successifs. Ces négociations impliquent des milliers de diplomates et d'experts sectoriels qui négocient simultanément des dizaines de sujets — tarifs douaniers, subventions agricoles, propriété intellectuelle, services, marchés publics.</p>
<p class="resume-text">Face à l'enlisement du Doha Round, les grandes puissances se sont tournées vers les <strong>accords bilatéraux et régionaux</strong> : CETA (UE-Canada), JEFTA (UE-Japon), RCEP (Asie-Pacifique, 15 pays). Ces accords permettent des avancées plus rapides mais créent un enchevêtrement de règles différentes qui complique la vie des entreprises exportatrices.</p>
<div class="highlight-box"><p>Le <strong>CETA</strong> (Accord économique et commercial global UE-Canada) a failli échouer en octobre 2016 à cause du veto du parlement de la Wallonie belge — révélant comment des traités commerciaux négociés au niveau européen peuvent être bloqués par des entités sub-nationales.</p></div>
<h3>La géoéconomie : l'économie comme instrument de puissance</h3>
<p class="resume-text">La <strong>géoéconomie</strong> désigne l'utilisation des instruments économiques à des fins géopolitiques. La Chine a utilisé sa position de premier importateur de terres rares pour faire pression sur le Japon lors d'un différend territorial (2010). La Russie a coupé ses livraisons de gaz à l'Ukraine lors de crises politiques, affectant aussi l'Europe occidentale.</p>
<p class="resume-text">Les États-Unis ont développé une <strong>weaponization of finance</strong> en excluant des États et des entités du système financier international basé sur le dollar. L'exclusion de la Russie du système SWIFT en 2022 après l'invasion de l'Ukraine en est l'illustration la plus récente. Cette arme est cependant à double tranchant : elle incite les pays sanctionnés à développer des alternatives qui pourraient à terme affaiblir la domination du dollar.</p>
<div class="highlight-box"><p>Le <strong>Chips Act</strong> américain (2022) et le contrôle des exportations de semi-conducteurs avancés vers la Chine illustrent une nouvelle forme de diplomatie économique : en interdisant à des entreprises comme ASML ou TSMC de fournir certaines technologies à la Chine, les États-Unis visent à ralentir la montée en puissance technologique chinoise.</p></div>
<h3>L'aide au développement comme instrument diplomatique</h3>
<p class="resume-text">L'<strong>aide publique au développement</strong> (APD) mélange objectifs humanitaires et calculs diplomatiques. Les pays donateurs utilisent l'aide pour renforcer leur influence, sécuriser des approvisionnements en ressources naturelles, créer des marchés pour leurs exportations, stabiliser des régions d'où partent les flux migratoires, ou récompenser des alliés politiques.</p>
<p class="resume-text">L'entrée massive de la <strong>Chine</strong> dans l'aide au développement depuis les années 2000 a bouleversé le paysage. Avec ses prêts à grande échelle pour des infrastructures, souvent assortis de conditions plus flexibles que celles du FMI ou de la Banque mondiale, la Chine a gagné une influence considérable en Afrique, en Asie du Sud-Est et en Amérique latine.</p>
""",

"diplomatie/diplomatie-culturelle": """
<h3>Les instruments de la diplomatie culturelle</h3>
<p class="resume-text">La <strong>diplomatie culturelle</strong> mobilise un ensemble d'institutions et de pratiques. Les <strong>centres culturels</strong> implantés à l'étranger — Alliances françaises (837 dans 132 pays), British Council (100 pays), Goethe-Institut (98 pays), Institut Cervantes (90 pays) — offrent des cours de langue, des expositions et servent de vitrine culturelle nationale. Ces institutions entretiennent des liens durables avec les élites intellectuelles et politiques locales.</p>
<p class="resume-text">Les <strong>bourses d'études</strong> constituent un investissement diplomatique à long terme particulièrement efficace. Le programme <strong>Fulbright</strong> américain (créé en 1946) a financé les études de 400 000 personnes dans 160 pays, dont 61 prix Nobel et 89 chefs d'État. Les anciens boursiers deviennent souvent des relais d'influence dans leurs pays — professeurs, journalistes, fonctionnaires — qui maintiennent des connexions durables avec le pays donateur.</p>
<div class="highlight-box"><p>L'<strong>Institut Confucius</strong>, réseau de centres culturels chinois implanté dans les universités du monde entier (plus de 500 dans 160 pays), a suscité des controverses croissantes. Plusieurs universités américaines, britanniques et australiennes ont fermé leurs instituts Confucius, soupçonnés de promouvoir la propagande du Parti communiste chinois.</p></div>
<h3>Le cinéma et les industries culturelles comme vecteurs d'influence</h3>
<p class="resume-text">Hollywood n'est pas seulement une industrie du divertissement : c'est un instrument de <strong>soft power</strong> américain. Les films hollywoodiens diffusent des représentations du mode de vie américain et des valeurs de liberté individuelle dans le monde entier. Les Américains ont fait du libre accès aux marchés cinématographiques un enjeu de leurs négociations commerciales, s'opposant aux quotas de films européens.</p>
<p class="resume-text">La France a théorisé l'<strong>exception culturelle</strong> pour protéger ses industries culturelles de la concurrence américaine. La <strong>Convention de l'UNESCO sur la diversité culturelle</strong> (2005), adoptée par 148 pays contre 2 (États-Unis et Israël), légitimise le droit des États à soutenir leurs industries culturelles et à les exclure des accords de libre-échange.</p>
<div class="highlight-box"><p>La <strong>Corée du Sud</strong> offre un exemple remarquable de diplomatie culturelle réussie : la <em>Korean Wave</em> (Hallyu) — K-pop, dramas, webtoons — a transformé l'image du pays à l'échelle mondiale. Le succès de BTS, de Parasite (Oscar du meilleur film 2020) ou de Squid Game a une valeur diplomatique et économique mesurable pour Séoul.</p></div>
<h3>La diplomatie du patrimoine et de la mémoire</h3>
<p class="resume-text">Le <strong>patrimoine culturel</strong> est un enjeu diplomatique sensible. Les demandes de restitution d'objets culturels pillés à l'époque coloniale divisent profondément les musées occidentaux et les pays d'origine. La Grèce réclame depuis des décennies le retour des <strong>marbres du Parthénon</strong> conservés au British Museum. Le Bénin et d'autres pays africains réclament le retour de bronzes et d'autres œuvres pillées.</p>
<p class="resume-text">L'<strong>UNESCO</strong> joue un rôle central dans la diplomatie du patrimoine. La liste du <strong>Patrimoine mondial</strong> (1153 sites dans 167 pays en 2023) est un enjeu diplomatique car l'inscription apporte prestige international et revenus touristiques. La <strong>protection du patrimoine en temps de conflit</strong> est devenu un enjeu humanitaire majeur après la destruction de Palmyre par Daech (2015) et le dynamitage des Bouddhas de Bamiyan (2001).</p>
""",
}

def enrich_page(content, extra_html):
    idx = content.rfind('</section>')
    if idx == -1:
        return content + extra_html
    return content[:idx] + extra_html + content[idx:]

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

enriched = 0
for key, extra in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        original_len = len(page['content'])
        page['content'] = enrich_page(page['content'], extra)
        new_len = len(page['content'])
        print(f'  {key}: {original_len} -> {new_len} chars')
        enriched += 1

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'\nEnriched {enriched} articles.')
