#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrichit les articles de linguistique.json
"""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/linguistique.json'

ENRICHMENTS = {
    'phonetique/voyelles-consonnes': """<h3>La variation phonétique inter-langues</h3><p class="resume-text">La diversité des inventaires phonétiques à travers les langues du monde est remarquable. Le !Kung (langue khoïsane d'Afrique australe) possède plus de cent phonèmes consonantiques, dont de nombreux clics. Le hawaïen n'en a que treize. Le mandarin distingue quatre tons lexicaux, le cantonais six à neuf. Cette diversité témoigne de la plasticité du système phonatoire humain.</p><p class="resume-text">L'Alphabet Phonétique International (API/IPA), mis au point par l'Association Phonétique Internationale à partir de 1886, permet de noter avec précision les sons de toutes les langues du monde. Chaque symbole correspond à un son précis, défini articulatoirement. Cet outil indispensable des linguistes, des orthophonistes et des concepteurs de méthodes de langues est fondé sur les critères articulatoires (lieu et mode d'articulation, voisement).</p><div class="highlight-box"><p>La langue taa (ou !Xóõ) d'Afrique australe possède le plus grand inventaire phonémique connu : environ 58 consonnes et 31 voyelles. À l'opposé, le pirahã d'Amazonie n'aurait que 8 consonnes et 3 voyelles selon certaines analyses.</p></div>""",

    'phonetique/appareil-phonatoire': """<h3>La phonation et les sources acoustiques</h3><p class="resume-text">La production de la parole implique trois mécanismes distincts. La phonation laryngienne est la source d'énergie principale : les cordes vocales (ou plis vocaux), deux replis muqueux, vibrent en s'ouvrant et se fermant rapidement sous la pression du flux d'air pulmonaire. Cette vibration crée une onde sonore quasi-périodique qui est ensuite filtrée par les cavités de résonance supraglottiques (pharynx, bouche, nasopharynx).</p><p class="resume-text">La théorie source-filtre de Gunnar Fant (1960) modélise la production vocale comme la combinaison d'une source (le larynx) et d'un filtre (le conduit vocal). Les formants — zones d'amplification des fréquences — déterminent la qualité des voyelles. F1 (premier formant) varie avec le degré d'aperture, F2 avec la position antéropostérieure de la langue. C'est ce modèle qui fonde les synthèses vocales et la reconnaissance automatique de la parole.</p><div class="highlight-box"><p>La dysphonie (troubles de la voix) et la dysarthrie (troubles de l'articulation) sont des pathologies qui touchent différentes composantes de l'appareil phonatoire. La phonochirurgie, la rééducation orthophonique et les implants cochléaires relèvent tous d'une connaissance fine de l'anatomie et de la physiologie de la parole.</p></div>""",

    'morphologie/morphemes': """<h3>Les classes de morphèmes et leur comportement syntaxique</h3><p class="resume-text">La distinction entre morphèmes libres (qui peuvent constituer un mot à eux seuls : « chat », « grand ») et morphèmes liés (qui ne peuvent apparaître qu'attachés à une base : « -ment », « re- », « -s » du pluriel) est fondamentale. Les morphèmes grammaticaux liés sont particulièrement importants pour la typologie des langues : les langues agglutinantes (turc, swahili) accumulent des morphèmes distincts de façon transparente, les langues fusionnelles (latin, russe) fondent plusieurs informations grammaticales dans un seul morphème opaque.</p><p class="resume-text">En anglais, le morphème -ed peut signaler le passé régulier (« walked »), mais des formes irrégulières (« went », « ate ») révèlent que la forme de surface ne laisse pas toujours voir la structure morphologique profonde. La morphologie lexicale étudie la formation des mots, la morphologie flexionnelle étudie les variations de forme imposées par la syntaxe (conjugaison, déclinaison, accord).</p><div class="highlight-box"><p>Le concept de morphème nul (ou morphème zéro) est utile pour analyser des cas où une information grammaticale est exprimée par l'absence de marque : « mouton » au singulier s'oppose à « moutons » au pluriel, mais le singulier ne porte aucune marque — on postule un morphème zéro de singulier.</p></div>""",

    'phonetique/prosodie': """<h3>La prosodie de l'énoncé et les actes de parole</h3><p class="resume-text">Au-delà du mot, la prosodie organise l'ensemble de l'énoncé. L'intonation — la mélodie de la phrase — signale le type d'acte de parole : montante pour une question en français, descendante pour une affirmation. Mais cette relation n'est pas universelle : en chinois mandarin, la mélodie au niveau du mot (tons lexicaux) prime sur l'intonation phrastique.</p><p class="resume-text">Les groupes intonatifs découpent l'énoncé en unités prosodiques correspondant à des unités d'information. Les pauses, allongements et ruptures mélodiques marquent les frontières de ces groupes. La structure prosodique interagit avec la structure syntaxique et informationnelle : le focus informationnel (l'information nouvelle) reçoit généralement un accent plus fort en français et en anglais.</p><div class="highlight-box"><p>Dans une langue à tons comme le mandarin, chaque syllabe porte un ton lexical (plat, montant, descendant-montant, descendant) qui distingue des mots différents. « Ma » peut signifier « mère », « chanvre », « cheval » ou « gronder » selon le ton. La prosodie est ici phonémique, ce qui complique considérablement l'apprentissage pour des locuteurs de langues non-tonales.</p></div>""",

    'phonetique/phonologie-processus': """<h3>Les processus phonologiques majeurs</h3><p class="resume-text">Les processus phonologiques sont des transformations régulières qui opèrent sur les séquences de phonèmes. L'assimilation fait ressembler un phonème à son voisin : en latin, le préfixe « in- » devient « im- » devant [p] (impossible) et « il- » devant [l] (illégal), car le lieu d'articulation s'adapte. La dissimilation est le phénomène inverse : pour éviter la répétition d'un son, un phonème change de forme.</p><p class="resume-text">La métathèse est le déplacement d'un son dans le mot : en espagnol médiéval, « parabola » est devenu « palabra » par inversion du [l] et du [r]. L'élision supprime un phonème dans certains contextes : le « e » caduc du français (« j'le dis » pour « je le dis »). L'épenthèse insère un phonème pour faciliter l'articulation : en roumain, « albu » (blanc) s'est transformé en « alb » par aphérèse, ou des consonnes de transition apparaissent pour faciliter le passage entre deux sons difficiles à enchaîner.</p><div class="highlight-box"><p>La règle phonologique peut s'écrire formellement : A → B / X___Y (« A devient B dans le contexte X___Y »). Ces règles rendent compte de la variation allophonique systématique et permettent de distinguer ce qui relève du système (phonologique) et ce qui relève de la réalisation (phonétique).</p></div>""",

    'morphologie/flexion': """<h3>La flexion nominale : cas, genre et nombre</h3><p class="resume-text">La flexion nominale exprime les catégories grammaticales du nom. Le nombre (singulier/pluriel, et dans certaines langues le duel, le triel, le pluriel inclusif/exclusif) est présent dans la plupart des langues. Le genre grammatical (masculin/féminin en français, masculin/féminin/neutre en allemand) est une catégorie arbitraire qui structure les accords dans la phrase.</p><p class="resume-text">La déclinaison casuelle est absente du français moderne mais fondamentale en latin (six cas : nominatif, vocatif, accusatif, génitif, datif, ablatif), en allemand (quatre cas), en finnois (quinze cas) et en hongrois (dix-huit cas). Les cas encodent les relations grammaticales et sémantiques du nom avec le verbe et les autres constituants : le nominatif marque le sujet, l'accusatif l'objet direct, le datif l'objet indirect, le génitif la possession.</p><div class="highlight-box"><p>Le finnois et le hongrois sont des langues agglutinantes à riche flexion nominale. En finnois, le mot « talo » (maison) peut prendre quinze formes casuelles différentes : talossa (dans la maison), talosta (hors de la maison), taloon (vers la maison), etc. Ces distinctions remplacent les prépositions des langues analytiques.</p></div>""",

    'phonetique/phonemes-allophones': """<h3>La commutation et l'identification des phonèmes</h3><p class="resume-text">La méthode de commutation permet d'identifier les phonèmes d'une langue. En substituant un son à un autre dans un mot, si le sens change, les deux sons sont des phonèmes distincts (paires minimales). En français, [p] et [b] sont des phonèmes distincts car « pas » et « bas » ont des sens différents. En anglais, [l] et [r] sont distincts (« light » ≠ « right »), ce qui n'est pas le cas en japonais.</p><p class="resume-text">La distribution complémentaire est la signature de l'allophonie : si deux sons n'apparaissent jamais dans le même contexte phonétique, ils sont vraisemblablement des allophones du même phonème. Le [h] aspiré de l'anglais apparaît en début de syllabe devant voyelle ; le [ŋ] n'apparaît qu'en fin de syllabe. Ces deux sons sont en distribution complémentaire — mais ils sont quand même traités comme des phonèmes distincts par les anglophones natifs.</p><div class="highlight-box"><p>La phonologie expérimentale utilise des techniques d'eye-tracking, de neuroimagerie et de réaction-temps pour sonder les représentations phonologiques mentales des locuteurs. Ces recherches remettent parfois en question des distinctions théoriques classiques et révèlent la dynamique des catégories phonologiques dans le traitement de la parole en temps réel.</p></div>""",

    'morphologie/typologie-morphologique': """<h3>Les types morphologiques et leur distribution géographique</h3><p class="resume-text">La classification morphologique des langues distingue plusieurs types idéaux. Les langues isolantes (ou analytiques) comme le mandarin ou le vietnamien ont des mots invariables, et les relations grammaticales sont exprimées par l'ordre des mots et des particules séparées. Les langues agglutinantes comme le turc ou le swahili construisent des mots complexes par l'ajout de morphèmes distincts et transparents.</p><p class="resume-text">Les langues fusionnelles comme le latin ou le russe condensent plusieurs informations grammaticales dans un seul morphème non analysable. Les langues polysynthétiques comme l'inuktitut ou le mohawk expriment dans un seul mot ce que d'autres langues expriment dans une phrase entière, en incorporant des arguments nominaux dans le complexe verbal. Ces types ne sont pas exclusifs : une même langue peut combiner des caractéristiques de plusieurs types.</p><div class="highlight-box"><p>L'hypothèse de la dérive (Sapir, 1921) suggère que les langues évoluent tendanciellement des types fusionnels vers les types analytiques. L'anglais illustre cette évolution : du vieil-anglais richement fléchi au niveau morphologique, il est passé à une langue presque analytique en 1000 ans. Le français a suivi un chemin similaire depuis le latin.</p></div>""",

    'syntaxe/constituants-syntagmes': """<h3>Les tests de constituance</h3><p class="resume-text">En syntaxe, la constituance ne s'affirme pas a priori mais se teste expérimentalement. Plusieurs tests permettent d'identifier les constituants. La pronominalisation : si un groupe de mots peut être remplacé par un pronom, c'est un constituant (« Le grand chat gris mange » → « Il mange »). La dislocation : si un groupe peut être mis en tête de phrase (« Ce chat, il mange »), c'est un constituant. La question : la réponse à une question est toujours un constituant (« Qui mange ? — Le grand chat gris »).</p><p class="resume-text">Ces tests ne donnent pas toujours des résultats concordants, car la constituance syntaxique interagit avec la structure informationnelle et prosodique. En français, la dislocation peut porter sur des éléments qui ne sont pas des constituants syntaxiques canoniques (« Ce que j'aime, c'est le cinéma »). Les désaccords entre tests révèlent les zones de friction entre différents niveaux d'organisation grammaticale.</p><div class="highlight-box"><p>La notion de syntagme (ou groupe, phrase en anglais : Noun Phrase, Verb Phrase, etc.) est au cœur de la grammaire générative de Chomsky. La règle de réécriture XP → Spec X' puis X' → X Comp exprime que tout syntagme est la projection d'une tête lexicale entourée d'un spécifieur et d'un complément.</p></div>""",

    'syntaxe/fonctions-syntaxiques': """<h3>Les fonctions syntaxiques dans la perspective typologique</h3><p class="resume-text">La distinction entre sujet, objet et oblique n'est pas universelle de la même façon. Dans les langues à marquage de l'absolutif-ergatif (basque, géorgien, langues australiennes), l'agent d'un verbe transitif (ergatif) est traité différemment du sujet d'un verbe intransitif (absolutif), qui reçoit le même traitement que le patient du verbe transitif. Ce système s'oppose au système nominatif-accusatif des langues indo-européennes où le sujet est unifié quelle que soit la transitivité du verbe.</p><p class="resume-text">Les langues à « sujets nuls » (pro-drop) comme l'espagnol, l'italien ou le japonais permettent l'omission du pronom sujet quand il est récupérable contextuellement. Ces langues ont généralement une morphologie verbale riche qui encode le sujet. Le français est intermédiaire : les pronoms sujets sont obligatoires en français standard, mais en français oral relâché, les clitiques peuvent être omis (« Sais pas »).</p><div class="highlight-box"><p>La notion de thème/rhème (ou topic/focus, ou donné/nouveau) est distincte des fonctions syntaxiques mais interagit avec elles. Le sujet grammatical coïncide souvent avec le thème (l'information connue), mais pas toujours. En français, la dislocation et les constructions impersonnelles permettent de dissocier fonction syntaxique et organisation informationnelle.</p></div>""",

    'morphologie/composition': """<h3>Les types de composés et leur structure interne</h3><p class="resume-text">La composition est l'un des mécanismes les plus productifs d'enrichissement du lexique. On distingue les composés endocentriques, où la tête sémantique est à l'intérieur du composé (« chou-fleur » est un type de chou), des composés exocentriques ou bahuvrihi, où le référent n'est pas désigné par l'un des constituants (« pied-noir » désigne une personne, non un pied). Les composés coordonnatifs (copulatifs) combinent deux éléments de même statut sémantique (« sourd-muet »).</p><p class="resume-text">La distinction entre composé et syntagme est souvent délicate. En allemand, la composition est un processus très productif et les composés s'écrivent en un seul mot (« Donaudampfschifffahrtsgesellschaft » — compagnie de navigation à vapeur du Danube). En anglais, l'orthographe hésite entre « notebook », « note book » et « note-book » selon les dictionnaires et les périodes. Ces variations orthographiques témoignent du continuum entre composition et syntagme libre.</p><div class="highlight-box"><p>Les néologismes par composition sont particulièrement fréquents dans les domaines techniques et scientifiques. Les termes médicaux combinent souvent des racines grecques et latines : « cardiomyopathie » (cardia, myos, pathos). L'anglais, langue dominante dans les sciences, crée aussi des composés de façon intensive : « crowdsourcing », « freemium », « blockchain ».</p></div>""",

    'semantique/sens-reference': """<h3>Frege, la Sinn et la Bedeutung</h3><p class="resume-text">La distinction fondatrice de Gottlob Frege (1892) entre Sinn (sens) et Bedeutung (référence) reste au cœur de la philosophie du langage. La référence est l'objet désigné par une expression ; le sens est le « mode de présentation » de cet objet. L'étoile du matin et l'étoile du soir ont la même référence (la planète Vénus) mais des sens différents. Ce constat explique que la proposition « L'étoile du matin est l'étoile du soir » soit informative, alors que « Vénus est Vénus » est triviale.</p><p class="resume-text">Les descriptions définies (« le président de la République ») et les noms propres posent des problèmes théoriques différents. Russell a analysé les descriptions définies comme des quantificateurs existentiels, évitant d'avoir à postuler une référence pour des descriptions comme « le roi actuel de France ». Kripke, dans La logique des noms propres (1980), défend au contraire que les noms propres sont des « désignateurs rigides » qui référent au même individu dans tous les mondes possibles.</p><div class="highlight-box"><p>La théorie des actes de langage (Austin, Searle) montre que les énoncés ne font pas que référer et prédire : ils accomplissent des actions. « Je promets de venir » n'est pas vrai ou faux — c'est un acte illocutoire qui crée une obligation. Cette perspective pragmatique complète les théories sémantico-référentielles.</p></div>""",
}

def insert_before_quiz(content, new_html):
    quiz_section = '<section class="content-section" id="quiz">'
    contenu_close = '</section>'

    quiz_idx = content.find(quiz_section)
    if quiz_idx == -1:
        return content

    contenu_end_idx = content.rfind(contenu_close, 0, quiz_idx)
    if contenu_end_idx == -1:
        return content

    return content[:contenu_end_idx] + new_html + contenu_close + content[quiz_idx:]

def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for page_key, new_html in ENRICHMENTS.items():
        if page_key in data['pages']:
            page = data['pages'][page_key]
            if page.get('type') == 'course':
                old_len = len(page['content'])
                page['content'] = insert_before_quiz(page['content'], new_html)
                new_len = len(page['content'])
                print(f"Enriched {page_key}: {old_len} -> {new_len} chars (+{new_len-old_len})")
                enriched_count += 1
        else:
            print(f"WARNING: page not found: {page_key}")

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nDone: {enriched_count} pages enriched.")

if __name__ == '__main__':
    main()
