import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

enrichments = {}

enrichments['robotique/capteurs-et-perception'] = (
    '<h3>Capteurs de proximité et de distance</h3>'
    '<p class="resume-text">Les <strong>capteurs LIDAR</strong> (Light Detection And Ranging) émettent des impulsions laser et mesurent le temps de retour (Time of Flight) pour calculer la distance à chaque obstacle. Un LIDAR rotatif (Velodyne HDL-64E) génère 1,3 million de points par seconde dans un rayon de 120m, créant une carte 3D précise à ±2 cm. Les véhicules autonomes et les robots mobiles utilisent le LIDAR comme capteur principal de perception de l\'environnement, bien que son coût (initialement 75 000$) ait fortement baissé avec la production en masse.</p>'
    '<p class="resume-text">Les <strong>capteurs ultrasoniques</strong> émettent des ultrasons (40-200 kHz) et mesurent l\'écho pour détecter les obstacles jusqu\'à 5-8 m. Économiques, robustes et insensibles à la lumière, ils équipent les capteurs de recul automobiles, les détecteurs de niveau dans les cuves et les robots domestiques (Roomba). Leur résolution angulaire limitée (15-30°) et leur sensibilité aux surfaces poreuses (absorption des ultrasons) les rendent moins précis que le LIDAR ou la caméra stéréo.</p>'
    '<p class="resume-text">Les <strong>caméras stéréoscopiques</strong> (deux caméras espacées) reconstituent la profondeur à partir de la disparité entre les images gauche et droite, mimant la vision binoculaire humaine. Le ZED (Stereolabs) et l\'Intel RealSense offrent des cartes de profondeur couleur jusqu\'à 20m. Les caméras à temps de vol (ToF, ex. Microsoft Azure Kinect) mesurent le déphasage entre une lumière infrarouge modulée émise et reçue pour chaque pixel, générant une image de profondeur haute résolution à 30 images/s.</p>'
    '<div class="highlight-box"><p>Un véhicule autonome Tesla utilise 8 caméras, 12 capteurs ultrasoniques et (selon la version) un LIDAR — traitant plus de 2000 images par seconde pour détecter et classer tous les objets sur la route en temps réel.</p></div>'
    '<h3>Capteurs proprioceptifs et centrales inertielles</h3>'
    '<p class="resume-text">Les <strong>encodeurs optiques</strong> mesurent la rotation des arbres motorisés avec une précision de 0,001° à 0,0001°. Le disque codeur strié (ou code Gray absolu) module un faisceau lumineux traversant le disque en rotation. Les encodeurs incrémentaux fournissent des impulsions comptées par logiciel ; les encodeurs absolus donnent la position en toutes circonstances (même après coupure d\'alimentation). Ces capteurs équipent tous les axes des robots industriels pour la précision de positionnement.</p>'
    '<p class="resume-text">Les <strong>centrales inertielles</strong> (IMU — Inertial Measurement Unit) combinent accéléromètres 3 axes et gyroscopes 3 axes pour mesurer l\'accélération linéaire et la vitesse angulaire. L\'intégration de ces mesures donne la position et l\'orientation relative (navigation à l\'estime). Les IMU MEMS modernes (MPU-6050, ICM-42688) tiennent dans un cube de 3mm et coûtent quelques euros. La dérive de l\'estimation de position croît avec le temps — d\'où la fusion avec GPS, magnétomètre et vision pour les systèmes de navigation.</p>'
    '<p class="resume-text">La <strong>fusion de capteurs</strong> (sensor fusion) combine les données de plusieurs capteurs complémentaires pour estimer l\'état du robot avec une précision et une robustesse supérieures à chaque capteur seul. Le filtre de Kalman (EKF, UKF) est l\'algorithme de fusion le plus utilisé : il minimise l\'erreur d\'estimation en pondérant les mesures par leur précision respective. La fusion LIDAR + caméra + IMU permet une localisation précise à 5 cm dans des environnements non couverts par le GPS.</p>'
    '<div class="highlight-box"><p>Un drone de livraison Amazon Prime Air fusionne les données de LIDAR, caméras, IMU et GPS pour naviguer à 25 m/s en évitant automatiquement les obstacles, les lignes électriques et les autres drones.</p></div>'
    '<h3>Vision par ordinateur et reconnaissance d\'objets</h3>'
    '<p class="resume-text">Les <strong>réseaux de neurones convolutifs</strong> (CNN) ont révolutionné la vision par ordinateur depuis 2012. AlexNet, VGG, ResNet ont successivement amélioré la précision de classification sur ImageNet (1,2 million d\'images, 1000 catégories). Les architectures modernes (EfficientNet, Vision Transformer) atteignent 90%+ de précision et s\'exécutent en temps réel sur des GPU embarqués (NVIDIA Jetson). La détection d\'objets (YOLO, SSD) localise et classe simultanément des dizaines d\'objets en une seule passe du réseau.</p>'
    '<p class="resume-text">La <strong>segmentation sémantique</strong> assigne une catégorie à chaque pixel de l\'image (routes, piétons, véhicules, panneaux, bâtiments). Elle est indispensable pour la conduite autonome et la navigation en intérieur. Les architectures U-Net (médical), DeepLab (extérieur) et Mask R-CNN (instances individuelles) sont les standards du domaine. Ces modèles nécessitent des données d\'entraînement annotées manuellement — un travail considérable (plusieurs mois d\'annotation manuelle pour un dataset de conduite).</p>'
    '<p class="resume-text">La <strong>reconstruction 3D par vision</strong> (Structure from Motion, SLAM visuel) permet à un robot de construire une carte de son environnement tout en se localisant dedans. ORB-SLAM3, LSD-SLAM et d\'autres algorithmes open-source atteignent des performances comparables au LIDAR dans les environnements texturés. La vidéo d\'un smartphone peut ainsi générer un modèle 3D précis d\'un espace intérieur — technologie utilisée dans les outils de modélisation de bâtiments (Matterport, FARO).</p>'
    '<div class="highlight-box"><p>Les réseaux de neurones convolutifs de détection d\'objets (YOLO) identifient et localisent en temps réel 80 catégories d\'objets en une seule image — une performance qui demandait 30 minutes de calcul il y a 15 ans.</p></div>'
)

enrichments['robotique/actionneurs-et-commande'] = (
    '<h3>Moteurs électriques et variateurs</h3>'
    '<p class="resume-text">Les <strong>moteurs brushless DC</strong> (BLDC) sont devenus le standard des robots modernes. Sans balais (commutation électronique par un contrôleur ESC), ils ont une durée de vie quasi-illimitée, un rendement de 90-95% et un rapport puissance/poids excellent. Les moteurs BLDC de frameless (sans carter) s\'intègrent directement dans les articulations robotiques. Les moteurs de drones DJI atteignent 10 kW/kg — 5 fois plus que les moteurs thermiques — grâce aux aimants permanents NdFeB (néodyme-fer-bore).</p>'
    '<p class="resume-text">Les <strong>moteurs à courant continu à couple direct</strong> (Direct Drive) éliminent le réducteur pour un positionnement plus précis (pas de jeu, pas d\'élasticité du réducteur) et un couple crête plus élevé. Les robots cobots (Universal Robots, KUKA LBR iiwa) utilisent des moteurs à couple élevé avec des réducteurs harmoniques à jeu nul. La mesure du couple en bout d\'axe (capteurs de couple 6 axes) permet une collaboration sûre avec les humains en détectant les contacts involontaires.</p>'
    '<p class="resume-text">Les <strong>actionneurs hydrauliques</strong> offrent les meilleurs rapports force/poids pour les applications nécessitant de grandes forces (robots de construction, exosquelettes militaires). Un vérin hydraulique de 50mm de diamètre développe 200 kN à 100 bars. La précision est assurée par des servoválves électrohydrauliques à réponse en fréquence de 100 Hz. Les robots Atlas (Boston Dynamics) utilisant des actionneurs hydrauliques légers ont montré des capacités de saut et de salto arrière impressionnantes avant de migrer vers l\'électrique.</p>'
    '<div class="highlight-box"><p>Les moteurs à aimants NdFeB (néodyme-fer-bore) ont une densité d\'énergie 10 fois supérieure aux aimants ferrite — une avancée qui a rendu possibles les drones, véhicules électriques et robots modernes.</p></div>'
    '<h3>Commande des robots : cinématique et dynamique</h3>'
    '<p class="resume-text">La <strong>cinématique directe</strong> d\'un robot calcule la position et l\'orientation de l\'effecteur (outil) en fonction des angles articulaires. La matrice de transformation homogène enchaîne les rotations et translations de chaque articulation selon la convention de Denavit-Hartenberg. Pour un robot 6 axes, la résolution des 6 équations non linéaires de la cinématique inverse (trouver les angles pour atteindre une pose donnée) peut avoir 16 solutions — les algorithmes choisissent la solution la plus proche de la configuration actuelle.</p>'
    '<p class="resume-text">La <strong>dynamique des robots</strong> calcule les couples moteurs nécessaires pour produire un mouvement donné en tenant compte des effets d\'inertie, de Coriolis, de centrifugation et de gravité. L\'algorithme de Newton-Euler récursif permet ce calcul en temps réel (1 ms sur processeur moderne). La commande en couple calculé (computed torque control) annule la dynamique du robot par prédiction et la remplace par une dynamique de référence linéaire simple à commander.</p>'
    '<p class="resume-text">La <strong>commande adaptative et robuste</strong> compense les incertitudes de modèle et les perturbations. La commande par mode glissant (SMC) assure la convergence vers la trajectoire désirée même en présence de fortes perturbations. La commande d\'impédance (impedance control) régule la relation force-déplacement plutôt que la position, rendant le robot conforme et sûr au contact. Ces stratégies sont indispensables pour les robots chirurgicaux (da Vinci) où la précision et la sécurité au contact sont critiques.</p>'
    '<div class="highlight-box"><p>Le bras robotique chirurgical da Vinci permet des interventions mini-invasives avec 7 degrés de liberté et une précision de ±1 mm — filtrant les tremblements du chirurgien et échelle de mouvement 1:3.</p></div>'
    '<h3>Actionneurs à compliance et robots souples</h3>'
    '<p class="resume-text">Les <strong>actionneurs en série élastiques</strong> (SEA) introduisent un ressort en série entre le moteur et la charge. Cette compliance délibérée amortit les chocs, permet la mesure de couple (par déflexion du ressort) et rend le robot sûr au contact. Les robots humanoïdes Atlas (Boston Dynamics) et les exosquelettes de rééducation (Ekso) utilisent des SEA pour marcher et interagir de façon naturelle avec leur environnement.</p>'
    '<p class="resume-text">La <strong>robotique souple</strong> (soft robotics) utilise des matériaux élastomères et des actionneurs pneumatiques pour créer des robots déformables capables de s\'adapter à leur environnement. Les tentacules pneumatiques en silicone (Festo Bionic Cobot), les grippers soft-gripper imitent les invertébrés (pieuvres, vers) pour saisir des objets fragiles (fruits, œufs) sans les abîmer. Ces robots tolérent les chocs et les déformations importantes, idéaux pour les environnements non structurés.</p>'
    '<p class="resume-text">Les <strong>muscles artificiels</strong> incluant les actionneurs en polymère électroactif (EAP), les alliages à mémoire de forme (NiTi), les polymères gonflables et les câbles à traction par moteurs distaux (câbles de Bowden) cherchent à mimer la légèreté et la puissance des muscles biologiques. Les alliages NiTi (Nitinol) se contractent de 4-8% lors du chauffage au-dessus de leur température de transformation, mais leur lenteur et leur faible efficacité énergétique limitent les applications aux actionneurs à cycle lent.</p>'
    '<div class="highlight-box"><p>Les robots soft-gripper en silicone peuvent saisir un œuf cru sans le casser ou une feuille de papier sans la plier — une dextérité impossible avec les pinces rigides conventionnelles.</p></div>'
)

enrichments['robotique/ia-embarquee'] = (
    '<h3>Apprentissage par renforcement pour la robotique</h3>'
    '<p class="resume-text">L\'<strong>apprentissage par renforcement</strong> (RL) entraîne un agent à prendre des décisions séquentielles en maximisant une récompense cumulative. En robotique, l\'agent (le robot) interagit avec l\'environnement (simulation ou réel), observe l\'état, exécute une action et reçoit une récompense. L\'algorithme PPO (Proximal Policy Optimization), SAC (Soft Actor-Critic) ou TD3 apprennent progressivement la politique optimale. OpenAI a montré un robot main réalisant le Rubik\'s Cube en utilisant uniquement le RL, entraîné en simulation et transféré au réel (sim-to-real transfer).</p>'
    '<p class="resume-text">Le <strong>transfert simulation-réel</strong> (Sim2Real) est le verrou majeur du RL en robotique. Les politiques entraînées en simulation parfaite échouent sur le vrai robot (différences de frottement, délais, bruit). Les techniques de <strong>domain randomization</strong> (variation aléatoire des paramètres de simulation pendant l\'entraînement) rendent la politique robuste aux incertitudes de modèle. L\'<strong>imitation learning</strong> (apprentissage par imitation de démonstrations humaines) accélère considérablement l\'entraînement en partant de comportements déjà corrects.</p>'
    '<p class="resume-text">L\'<strong>apprentissage par renforcement distribué</strong> utilise des centaines ou des milliers d\'instances parallèles pour accélérer l\'exploration. AlphaGo (Google DeepMind) a démontré que le RL à très grande échelle peut surpasser l\'expertise humaine même dans des domaines de grande complexité combinatoire. Ces techniques sont maintenant appliquées à la locomotion robotique (robots marcheurs), à la manipulation (préhension multi-doigts) et à la navigation en environnements complexes.</p>'
    '<div class="highlight-box"><p>Boston Dynamics a entraîné le robot Spot à marcher sur terrain accidenté en simulant des millions d\'interactions physiques — une tâche qui aurait pris des années de programmation manuelle.</p></div>'
    '<h3>SLAM et navigation autonome</h3>'
    '<p class="resume-text">Le <strong>SLAM</strong> (Simultaneous Localization and Mapping) permet à un robot de construire une carte de son environnement inconnu tout en se localisant dedans en temps réel. Les approches basées sur les filtres (EKF-SLAM, FastSLAM) et les approches par graphe d\'optimisation (g2o, iSAM) sont les deux grandes familles. SLAM 3D avec LIDAR (Cartographer, LOAM) crée des cartes 3D précises utilisées pour la navigation de véhicules autonomes et robots de livraison en intérieur.</p>'
    '<p class="resume-text">La <strong>planification de trajectoire</strong> trouve le chemin optimal entre deux configurations en évitant les obstacles. L\'algorithme A* (recherche heuristique sur graphe) est optimal pour les grilles 2D. Le RRT (Rapidly-exploring Random Tree) et ses variantes (RRT*, BIT*) planifient efficacement dans des espaces de configuration à haute dimension (robots multi-articulés). La planification en temps réel nécessite des cartes en mémoire et des algorithmes d\'incrémental ou anytime (solution améliorable avec le temps disponible).</p>'
    '<p class="resume-text">Le <strong>navigation multi-robot</strong> coordonne des flottes de robots (entrepôts Amazon, usines Tesla) sans collision. Les systèmes centralisés calculent les trajectoires de tous les robots simultanément ; les systèmes distribués (CBS — Conflict-Based Search) résolvent les conflits localement entre paires de robots. Le déploiement de plus de 200 000 robots dans les entrepôts Amazon nécessite des algorithmes de planification qui s\'exécutent en quelques millisecondes pour des milliers d\'agents.</p>'
    '<div class="highlight-box"><p>Les entrepôts Amazon utilisent plus de 200 000 robots Kiva/Proteus pour déplacer les étagères vers les opérateurs — réduisant les déplacements humains de 20 km à 3 km par shift et multipliant la cadence de préparation de commandes par 3.</p></div>'
    '<h3>Traitement embarqué et edge AI</h3>'
    '<p class="resume-text">Les <strong>accélérateurs neuromorphiques</strong> (NPU — Neural Processing Unit) sont spécialement conçus pour exécuter les réseaux de neurones efficacement. Le chip Apple Neural Engine exécute 38 trillions d\'opérations par seconde avec 11 watts — 100 fois plus efficace qu\'un GPU de bureau pour les inférences. Les NVIDIA Jetson Orin (275 TOPS, 15W) équipent les robots autonomes et véhicules qui nécessitent une IA puissante dans un budget énergétique contraint.</p>'
    '<p class="resume-text">La <strong>quantification et la distillation</strong> des modèles réduisent leur taille pour les déployer sur des processeurs embarqués à ressources limitées. La quantification en INT8 (entiers 8 bits au lieu de flottants 32 bits) réduit la taille du modèle par 4 et l\'accélère sans perte significative de précision. La distillation de connaissance entraîne un petit modèle (l\'élève) à imiter le comportement d\'un grand modèle pré-entraîné (le professeur), transférant les connaissances dans un format plus compact et rapide.</p>'
    '<p class="resume-text">L\'<strong>IA générative pour la robotique</strong> (RT-2, SayCan, PaLM-E) permettent aux robots d\'interpréter des instructions en langage naturel et de les traduire en séquences d\'actions. Un robot peut recevoir l\'instruction "apporte-moi le snack le moins calorique" et planifier autonomement la recherche, l\'identification et le transport de l\'objet. Ces modèles fondationnels pré-entraînés sur de grandes quantités de données internet puis affinés pour la robotique représentent la prochaine révolution de la robotique généraliste.</p>'
    '<div class="highlight-box"><p>Le robot RT-2 de Google DeepMind peut interpréter des instructions en langage naturel et exécuter des tâches de manipulation complexes jamais vues lors de l\'entraînement — un pas majeur vers la robotique généraliste.</p></div>'
)

enrichments['robotique/robots-industriels'] = (
    '<h3>Architecture et cinématique des bras industriels</h3>'
    '<p class="resume-text">Un <strong>robot industriel à 6 axes</strong> (KUKA, ABB, FANUC, Yaskawa) simule le bras humain avec 6 degrés de liberté : épaule (3 axes), coude (1 axe) et poignet sphérique (3 axes). Les 3 premiers axes positionnent l\'effecteur dans l\'espace ; les 3 derniers orientent l\'outil. Cette architecture donne accès à n\'importe quelle position et orientation dans l\'espace de travail. Les robots sériels ont un espace de travail étendu mais une rigidité limitée ; les robots parallèles (Delta, hexapode Stewart) sont rigides et rapides mais à espace de travail réduit.</p>'
    '<p class="resume-text">La <strong>précision de répétabilité</strong> (pas de précision absolue) des robots industriels est de ±0,02 à ±0,10 mm selon la gamme. La précision absolue (capacité à atteindre n\'importe quel point avec cette précision sans étalonnage) est bien moindre (±1 à ±5 mm) à cause des flexibilités des liaisons et des erreurs de calibration. Pour les applications haute précision (assemblage optique, chirurgie), des systèmes de métrologie externe (laser tracker, vision) compensent ces erreurs en boucle fermée.</p>'
    '<p class="resume-text">Les <strong>robots cobots</strong> (robots collaboratifs, Universal Robots, KUKA LBR, ABB YuMi) sont conçus pour travailler en sécurité à côté des humains sans cage de protection. Ils intègrent la mesure de couple sur chaque axe, limitent leur vitesse et force, et détectent les contacts par arrêt soft ou déviation. Leur programmation par apprentissage (guidage à la main, teach pendant intuitif, logiciel no-code) réduit les délais de déploiement de semaines à heures.</p>'
    '<div class="highlight-box"><p>Un robot de soudure FANUC Arc Mate peut effectuer 10 000 points de soudure par shift avec une répétabilité de ±0,08 mm, sans pause ni fatigue — mais sa programmation initiale prend 1 à 2 semaines d\'ingénierie.</p></div>'
    '<h3>Applications industrielles avancées</h3>'
    '<p class="resume-text">Le <strong>soudage automatisé</strong> représente 30% des applications de robots industriels. La soudure MIG/MAG (fil fourré en continu), TIG (électrode non consommable) et laser sont robotisables. Les robots de soudure asservis visuellement (seam tracking par capteur laser ou vision) s\'adaptent en temps réel aux variations de joint. La qualité de soudure robotisée est plus constante que la soudure manuelle : taux de défaut réduit de 70%, productivité doublée à triplée.</p>'
    '<p class="resume-text">La <strong>peinture et le revêtement</strong> utilisent des robots multiaxes équipés de pistolets électrostatiques atomiseurs rotatifs. La trajectoire du robot est optimisée pour minimiser le taux de déchet de peinture (overspray) et maximiser l\'uniformité du film. Les lignes de peinture automobiles (Dürr, ABB) peignent une carrosserie en 3 minutes avec un film de 80-100 μm d\'épaisseur et un rendement de transfert de 80% (contre 50% en pulvérisation conventionnelle).</p>'
    '<p class="resume-text">L\'<strong>usinage robotique</strong> (fraisage, perçage, ponçage par robot) étend les capacités des machines CNC classiques à de grandes pièces (aérostructures, carrosseries de composites) impossibles à traiter en centre d\'usinage. La rigidité limitée des robots (comparée aux fraiseuses) est compensée par des stratégies de coupe adaptatives (réduction de la passe, trajectoires optimisées) et la mesure de force pour adapter les paramètres de coupe en temps réel.</p>'
    '<div class="highlight-box"><p>Une ligne de montage automobile moderne comprend 500 à 1000 robots industriels — Volkswagen à Wolfsburg en compte plus de 2000, capables d\'assembler une nouvelle Volkswagen Golf toutes les 65 secondes.</p></div>'
    '<h3>Systèmes de production flexibles et Industrie 4.0</h3>'
    '<p class="resume-text">Les <strong>AGV</strong> (Automated Guided Vehicles) et <strong>AMR</strong> (Autonomous Mobile Robots) assurent la logistique interne des usines et entrepôts. Les AGV suivent des pistes magnétiques ou laser prédéfinies ; les AMR naviguent de façon autonome par SLAM. Les AMR (MiR, Locus Robotics, Fetch) s\'intègrent avec les WMS (Warehouse Management Systems) pour optimiser les flux en temps réel. L\'entrepôt Ocado en Angleterre a déployé 3500 robots AMR sur une grille 3D pour préparer les commandes e-commerce.</p>'
    '<p class="resume-text">Le <strong>digital twin</strong> (jumeau numérique) d\'une cellule robotique ou d\'une usine entière permet de simuler, programmer et optimiser en virtuel avant de déployer en réel. Siemens NX, Dassault DELMIA, ABB RobotStudio simulent les cinématiques, collisions, temps de cycle et flux logistiques. Les lignes de production BMW et Tesla utilisent des digital twins de leurs usines entières pour planifier les extensions de capacité et former les opérateurs en réalité virtuelle.</p>'
    '<p class="resume-text">Les <strong>technologies de communication industrielle</strong> (OPC-UA, MQTT, 5G industriel) permettent l\'intégration des robots dans l\'écosystème Industrie 4.0. La connectivité temps réel entre robots, machines, capteurs et systèmes MES/ERP permet l\'optimisation continue de la production (Overall Equipment Effectiveness — OEE), la maintenance prédictive (analyse des données vibratoires et thermiques des réducteurs) et la traçabilité complète (chaque pièce liée à sa séquence de fabrication).</p>'
    '<div class="highlight-box"><p>L\'usine Tesla de Fremont en Californie compte plus de 1000 robots industriels — mais Elon Musk a reconnu avoir sur-robotisé en 2018, réintroduisant des opérateurs humains pour les tâches d\'assemblage complexes que les robots ne maîtrisent pas encore.</p></div>'
)

enrichments['robotique/drones'] = (
    '<h3>Aérodynamique et mécanique du vol des drones</h3>'
    '<p class="resume-text">Un <strong>quadrirotor</strong> génère la portance par ses quatre hélices. En faisant varier la vitesse de chaque rotor, il contrôle les 4 degrés de liberté du vol (altitude, tangage, roulis, lacet). Deux rotors tournent dans un sens et deux dans l\'autre pour annuler le couple de réaction. L\'équation de mouvement du quadrirotor (forces de portance proportionnelles au carré de la vitesse des rotors) est la base de tous les contrôleurs de vol. La commande de bas niveau (attitude, vitesse) tourne typiquement à 400-1000 Hz sur le contrôleur de vol.</p>'
    '<p class="resume-text">Les <strong>effets aérodynamiques</strong> complexifient la commande en conditions réelles. L\'effet sol (ground effect) augmente la portance de 10-30% près du sol. Le vortex ring state (descente verticale rapide) réduit dangeureusement la portance. Le vent latéral perturbe la trajectoire. Les perturbations provoquées par les tourbillons de sillage (wake turbulence) des autres drones imposent des distances de sécurité dans les flottes UTM (Unmanned Traffic Management). La modélisation aérodynamique précise par CFD (Computational Fluid Dynamics) est nécessaire pour les drones à grande vitesse (250 km/h).</p>'
    '<p class="resume-text">Les <strong>drones à voilure fixe</strong> (ailes portantes, planeurs motorisés) sont plus efficaces énergétiquement que les multirotors pour les vols de longue durée et longue distance. Le rapport portance/traînée (finesse aérodynamique) d\'un planeur peut atteindre 40:1, signifiant qu\'il avance de 40m pour 1m de descente. Les drones à décollage vertical et atterrissage (VTOL), combinant décollage en multirotor et croisière en vol plané, offrent la flexibilité des deux configurations — déployés par les armées et les services de livraison longue distance.</p>'
    '<div class="highlight-box"><p>Le drone solaire Zephyr S (Airbus) a volé en continu pendant 25 jours à 21 km d\'altitude en 2018 — un record d\'endurance pour un engin sans pilote à propulsion solaire, grâce à sa finesse aérodynamique de 38.</p></div>'
    '<h3>Systèmes de contrôle et pilotage autonome</h3>'
    '<p class="resume-text">Le <strong>contrôleur de vol</strong> (Flight Controller) est le cerveau du drone. Les cartes de contrôle open-source (ArduPilot, PX4) implémentent des boucles PID cascadées pour contrôler l\'attitude (tangage/roulis/lacet) puis la vitesse puis la position. La fréquence de la boucle interne (attitude) est de 400-1000 Hz ; la boucle externe (position GPS) tourne à 50-100 Hz. Les algorithmes de contrôle modernes (LQR, MPC) améliorent les performances en présence de vent fort ou de charges perturbantes.</p>'
    '<p class="resume-text">La <strong>détection et évitement d\'obstacles</strong> (DAA — Detect And Avoid) est la capacité critique pour l\'intégration des drones dans l\'espace aérien civil. Les capteurs (LIDAR, stéréovision, acoustique) détectent les obstacles, les algorithmes de planification locale (DWA — Dynamic Window Approach, VFH+) dévient la trajectoire en temps réel. Pour les drones civils au-delà de la vue (BVLOS), la réglementation exige une performance DAA équivalente au pilote humain — un défi technique encore non entièrement résolu.</p>'
    '<p class="resume-text">Les <strong>essaims de drones</strong> (swarms) coordonnent des centaines ou des milliers d\'engins pour des missions collectives (cartographie, spectacles lumineux, logistique d\'urgence). Les algorithmes de comportements émergents (inspirés des bancs de poissons et murmures d\'étourneaux) permettent une coordination distribuée sans communication centrale. Intel a coordonné 2000 drones LED pour des spectacles lumineux en temps réel, positionnés à ±30 cm par GPS différentiel.</p>'
    '<div class="highlight-box"><p>Le spectacle d\'ouverture des Jeux olympiques de Tokyo 2021 utilisait 1824 drones Intel coordonnés pour former des drapeaux et des pictogrammes dans le ciel — chacun positionné à ±30 cm de précision par GPS différentiel.</p></div>'
    '<h3>Applications civiles et militaires</h3>'
    '<p class="resume-text">L\'<strong>inspection d\'infrastructures</strong> par drones (ponts, pylônes électriques, éoliennes, pipelines, réseaux ferrés) remplace les inspecteurs humains en hauteur. Un drone équipé d\'une caméra 4K et d\'un zoom optique 30x inspecte 20 fois plus rapidement qu\'une équipe humaine avec nacelle élévatrice. Les algorithmes de traitement d\'image automatique (détection de fissures, mesure de déflexion, identification de rouille) permettent d\'analyser des milliers d\'images en quelques heures.</p>'
    '<p class="resume-text">La <strong>livraison par drone</strong> (Wing de Google, Prime Air d\'Amazon, Zipline pour le médical) déploie des services commerciaux dans plusieurs pays. Zipline, spécialisé dans la livraison médicale (vaccins, sang, médicaments) en Afrique subsaharienne, a effectué plus de 1 million de livraisons commerciales au Rwanda et au Ghana depuis 2016 — dans des zones inaccessibles par route. Les drones VTOL à voilure fixe de Zipline livrent des colis parachutés sur une cible circulaire de 3m depuis 60m d\'altitude.</p>'
    '<p class="resume-text">Les <strong>drones militaires</strong> (UAS — Unmanned Aerial Systems) vont du nano-drone d\'observation (Black Hornet, 18g) au MALE (Medium Altitude Long Endurance, Predator, Reaper) capable de missions de 27h à 14km d\'altitude. Les UCAV (Unmanned Combat AV) disposent de capacités d\'armement et d\'autonomie croissantes. Le conflit ukrainien a démontré l\'impact décisif des drones commerciaux modifiés (Mavic3 équipé de grenades), transformant la doctrine militaire mondiale.</p>'
    '<div class="highlight-box"><p>Zipline (livraison médicale par drone) a effectué plus d\'un million de livraisons commerciales en Afrique — chaque drone volant à 110 km/h largue une boîte médicale sur une cible de 3m de précision depuis 60m d\'altitude.</p></div>'
)

# Apply enrichments
count = 0
for key, extra in enrichments.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (robotique section)")
