#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Second pass: enrichit tous les articles mythologie.json < 15000 chars.
"""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/mythologie.json'
QUIZ_MARKER = '<section class="content-section" id="quiz">'

PASS2 = {
    'mythologies-antiques/mythologie-grecque': """<h3>La géographie mythologique de la Grèce</h3>
<p class="resume-text">La géographie physique de la Grèce est indissociable de sa mythologie. Le mont Olympe, plus haute montagne de Grèce (2917 m), est le séjour des dieux. Delphes, sur les pentes du Parnasse, est le nombril (omphalos) du monde. Le détroit de Corinthe sépare le monde de la mort des vivants. L'île de Lesbos est associée à Sappho et aux Muses. Cette sacralisation du paysage transforme chaque lieu en récit et chaque récit en lieu.</p>
<p class="resume-text">Les Jeux olympiques (fondés en 776 av. J.-C., selon la tradition) honoraient Zeus à Olympie tous les quatre ans. Pendant leur durée, une trêve sacrée (ekecheiria) suspendait les guerres entre cités. Ces jeux mêlaient compétition sportive, rituels religieux et affirmation d'une identité culturelle commune (panhellénisme). Les vainqueurs (olympioniques) étaient célébrés comme demi-dieux dans leurs cités.</p>
<div class="highlight-box"><p>Le mythe de Prométhée — qui vole le feu aux dieux pour le donner aux hommes — est l'une des métaphores les plus fécondes de la civilisation. Eschyle (Prométhée enchaîné), Marx, Shelley (Frankenstein), Camus : chaque époque a réinterprété ce mythe pour penser les rapports entre connaissance, technique et condition humaine.</p></div>
<h3>Mythe et philosophie : de la muthos au logos</h3>
<p class="resume-text">Le passage du « muthos » (récit mythique) au « logos » (discours rationnel) est souvent présenté comme la grande révolution intellectuelle de la Grèce archaïque (VIe siècle av. J.-C.). Thalès, Anaximandre, Xénophane critiquent les dieux d'Homère et cherchent des explications naturelles aux phénomènes cosmiques. Mais ce passage est progressif et jamais total : Platon use constamment du mythe pour illustrer des vérités philosophiques que la démonstration ne peut atteindre.</p>
<p class="resume-text">Les mythes grecs ne sont pas de simples récits naïfs : ils contiennent une sagesse pratique sur les passions, les limites de l'homme, les dangers de l'hybris. L'histoire de Narcisse (s'aimer soi-même jusqu'à la mort) ou d'Icare (vouloir s'élever trop haut) sont des avertissements psychologiques d'une acuité permanente. La mythologie grecque reste un réservoir inépuisable de métaphores pour penser la condition humaine.</p>""",

    'mythologies-antiques/mythologie-romaine': """<h3>Les fêtes et le calendrier religieux romain</h3>
<p class="resume-text">Le calendrier romain était ponctué de fêtes religieuses (feries) en l'honneur des différents dieux. Les Lupercales (15 février) étaient des rites de purification et de fertilité associés à Lupercus/Pan. Les Saturnales (17-23 décembre) inversaient l'ordre social : les maîtres servaient leurs esclaves, les cadeaux circulaient librement — une survivance des saturnales dans notre Noël moderne. Les Florales (fin avril) honoraient la déesse Flore avec des jeux et des spectacles.</p>
<p class="resume-text">Les Luperci, prêtres de Lupercus, couraient nus à travers Rome en fouettant les femmes avec des lanières de peau pour favoriser leur fécondité. Ces rites archaïques, incompréhensibles pour les Romains de l'époque classique, témoignent d'un fond religieux préhistorique que les couches successives de mythologie grecque et de philosophie stoïcienne n'avaient pas entièrement recouvert.</p>
<div class="highlight-box"><p>Ovide, dans ses Métamorphoses (8 ap. J.-C.), réunit 250 récits mythologiques organisés autour du thème de la transformation. Cette œuvre encyclopédique a été la principale source de la mythologie gréco-romaine pour la littérature et l'art occidentaux, de Dante à Shakespeare en passant par Velázquez et Picasso.</p></div>
<h3>Mort et afterlife dans la Rome antique</h3>
<p class="resume-text">Les Romains croyaient que les morts vivaient dans les Enfers (Inferi) et que leurs âmes (manes) pouvaient interagir avec les vivants. Les Lemuria (9, 11, 13 mai) permettaient aux mânes malveillants d'être apaisés et chassés. Les Parentalia (13-21 février) honoraient les ancêtres par des libations et des offrandes sur les tombes. Ces fêtes révèlent une conception des rapports entre morts et vivants comme une relation permanente d'obligation mutuelle.</p>
<p class="resume-text">L'Elysée romain (paradise des héros), le Tartare (punition des impies) et les Champs Asphodel (destin ordinaire) reproduisent le modèle grec. Virgile, dans le livre VI de l'Énéide, décrit la descente d'Énée aux Enfers pour rencontrer son père Anchise — une vision eschatologique qui influencera profondément la Divine Comédie de Dante, qui choisit justement Virgile comme guide dans les Enfers et le Purgatoire.</p>""",

    'mythologies-antiques/mythologie-nordique': """<h3>Le Ragnarök : la fin et le renouveau</h3>
<p class="resume-text">Le Ragnarök (« Destin des puissances » ou « Crépuscule des dieux ») est l'apocalypse nordique : la fin du monde actuel et la naissance d'un nouveau. Les signes précurseurs incluent trois hivers consécutifs sans été (Fimbulwinter), la dissolution des liens familiaux et sociaux, et la libération des forces du chaos. Loki et ses enfants monstrueux (le loup Fenrir, le serpent de Midgard Jörmungandr, et Hel) se rebellent contre les dieux.</p>
<p class="resume-text">Dans la bataille finale, les dieux affrontent leurs ennemis : Odin est dévoré par Fenrir (qui sera tué par Víðarr), Thor tue Jörmungandr mais succombe à son venin, Freyr tombe face à Surtr sans son épée magique. Yggdrasil tremble, la terre plonge dans la mer. Puis une nouvelle terre emerge, plus fertile et belle. Baldur revient des morts, quelques dieux survivent, et les hommes recommencent. Cette vision cyclique — destruction et renaissance — est propre à la cosmologie nordique.</p>
<div class="highlight-box"><p>Loki est le personnage le plus ambigu du panthéon nordique : trickster (esprit farceur) tantôt allié tantôt ennemi des dieux. C'est lui qui cause la mort de Baldur (le dieu lumineux) en guidant la main aveugle d'Höðr. Enchaîné jusqu'au Ragnarök comme punition, il préfigure le Satan judéo-chrétien — et des personnages comme Flatteur dans Le Voyage du Pèlerin, ou Iago chez Shakespeare.</p></div>
<h3>Cosmologie : les neuf mondes et Yggdrasil</h3>
<p class="resume-text">Au centre de la cosmologie nordique s'élève Yggdrasil, le frêne cosmique dont les racines plongent dans trois sources sacrées : Urðarbrunnr (puits du Destin), Mímisbrunnr (puits de la Sagesse, d'où Odin boit en sacrifiant un œil) et Hvergelmir (source primordiale). Les neuf mondes s'organisent autour de cet arbre : Ásgarðr (dieux), Miðgarðr (hommes), Jötunheimr (géants), Vanaheimr (Vanes), Álfheimr (elfes clairs), Svartálfaheimr (elfes noirs), Niðavellir (nains), Muspellsheim (feu) et Hel (morts ordinaires).</p>
<p class="resume-text">Odin s'est lui-même pendu à Yggdrasil pendant neuf jours et neuf nuits, percé par sa propre lance, se sacrifiant à lui-même pour acquérir la connaissance des runes. Les runes ne sont pas seulement un alphabet : ce sont des forces cosmiques que celui qui les maîtrise peut invoquer. Cette quête de sagesse par la souffrance et le sacrifice de soi est un motif profondément nordique qui résonne dans l'éthique du guerrier et du skald.</p>""",

    'mythologies-antiques/mythologie-egyptienne': """<h3>Les animaux sacrés et la zoolâtrie</h3>
<p class="resume-text">La religion égyptienne est célèbre pour ses dieux à tête animale. Ces représentations ne sont pas de simples naïvetés primitives : elles expriment une vision du monde où les animaux incarnent des qualités divines. Le faucon (Horus) symbolise la vigilance et la royauté ; le chacal (Anubis) est associé à la mort et à l'embaumement ; l'ibis (Thot) représente la sagesse et l'écriture ; le chat (Bastet) est protecteur du foyer. Chaque animal souligne un aspect du dieu qu'il représente.</p>
<p class="resume-text">Les temples abritaient des animaux sacrés vivants : le taureau Apis à Memphis était le ba (âme) visible du dieu Ptah. À sa mort, il était embaumé avec les honneurs royaux et enterré dans le Sérapeum. Des nécropoles entières étaient consacrées aux animaux sacrés momifiés : ibis, babouins, chats, crocodiles, cobras, béliers. Ces pratiques témoignent d'une vision du sacré profondément enracinée dans la nature et ses manifestations.</p>
<div class="highlight-box"><p>La découverte de la Pierre de Rosette en 1799 (et son déchiffrement par Champollion en 1822) a ouvert la porte à la compréhension des hiéroglyphes et à la redécouverte de la civilisation égyptienne. Cette révolution en égyptologie est l'une des plus grandes de l'histoire des sciences humaines.</p></div>
<h3>L'héritage égyptien dans la culture mondiale</h3>
<p class="resume-text">La fascination de l'Occident pour l'Égypte antique (l'Égyptomanie) commence avec Alexandre le Grand et se poursuit à travers Rome (Cléopâtre, l'obélisque sur la place Saint-Pierre à Rome), la Renaissance (l'hermétisme néoplatonicien), la campagne de Napoléon (Description de l'Égypte, 1809-1828), la découverte de Toutânkhamon (1922) jusqu'aux films d'Hollywood et aux pyramides de Las Vegas. L'Égypte antique reste l'une des civilisations les plus fascinantes pour l'imagination mondiale.</p>
<p class="resume-text">La tradition hermétique — ensemble de textes philosophiques et spirituels attribués à Hermès Trismégiste (IIe-IIIe siècle ap. J.-C.) — prétend transmettre la sagesse de l'Égypte ancienne. L'alchimie, la franc-maçonnerie, le rosicrucisme et de nombreux courants ésotériques occidentaux puisent dans ce fonds égyptisant pour construire une « philosophia perennis » antérieure aux religions révélées.</p>""",

    'mythologies-antiques/mythologie-mesopotamienne': """<h3>Cosmogonie et genèse de l'ordre du monde</h3>
<p class="resume-text">Dans la vision mésopotamienne du monde, les dieux ont créé les hommes pour leur service : « nourrir les dieux et les libérer du travail » selon l'Atrahasis (XVIIIe siècle av. J.-C.). Cette vision anthropologique radicale — l'homme comme serviteur des dieux — contraste avec la vision biblique (l'homme créé à l'image de Dieu) ou platonicienne (l'homme doué de raison). Elle reflète une société où la servitude institutionnelle (esclavage, redevances aux temples) était fondamentale.</p>
<p class="resume-text">Les dieux mésopotamiens sont capricieux, en proie aux passions humaines et parfois indifférents au destin des hommes. Ils peuvent décider de leur destruction pour des raisons futiles (le Déluge de l'Atrahasis est déclenché par le bruit que font les hommes en dormant). Cette vision d'un divin imprévisible et parfois hostile explique l'importance de la divination dans la civilisation mésopotamienne : déchiffrer les signes du destin pour anticiper la volonté des dieux.</p>
<div class="highlight-box"><p>La bibliothèque d'Assurbanipal à Ninive (VIIe siècle av. J.-C.) contenait plus de 30 000 tablettes d'argile, dont l'Épopée de Gilgamesh. Sa destruction lors de la chute de Ninive (612 av. J.-C.) fit disparaître pendant 2500 ans ce patrimoine littéraire. Sa redécouverte au XIXe siècle par Austen Henry Layard et sa traduction par George Smith (qui pleura en lisant l'épisode du Déluge) furent une sensation mondiale.</p></div>
<h3>Divination et astronomie</h3>
<p class="resume-text">La divination babylonienne était une science minutieuse : les présages extraits des entrailles des animaux sacrifiés (haruspicine), des éclipses, des positions des astres et des comportements des animaux formaient des corpus encyclopédiques de milliers d'observations. Cette logique du signe — tout phénomène naturel est un message des dieux — a produit l'astronomie babylonienne, la plus précise de l'Antiquité avant les Grecs.</p>
<p class="resume-text">Les Babyloniens ont développé l'astrologie — l'influence des astres sur les destinées individuelles — qui sera transmise aux Grecs et influencera profondément la pensée médiévale et renaissante. Ils ont calculé les éclipses avec une grande précision, identifié les planètes visibles à l'œil nu et développé un système de notation positionnelle en base 60 que nous utilisons encore (60 secondes dans une minute, 360 degrés dans un cercle).</p>""",

    'grandes-religions/islam': """<h3>La vie du Prophète Mohammed</h3>
<p class="resume-text">Mohammed ibn Abdallah naît à La Mecque vers 570 ap. J.-C. dans la tribu des Quraysh. Orphelin élevé par son grand-père puis son oncle Abu Talib, il devient commerçant et épouse à 25 ans Khadija, une veuve prospère qui sera sa première croyante. En 610, lors d'une retraite sur le mont Hira, il reçoit la première révélation de l'ange Jibrîl (Gabriel) : « Lis au nom de ton Seigneur qui a créé... »</p>
<p class="resume-text">Face à la persécution des Mecquois, il émigre à Médine en 622 (l'Hégire, point de départ du calendrier islamique). À Médine, il organise la première communauté musulmane (umma), réconcilie les tribus et établit la Constitution de Médine — considérée comme l'un des premiers documents constitutionnels de l'histoire. En 630, il reprend La Mecque pacifiquement et détruit les idoles de la Kaaba.</p>
<div class="highlight-box"><p>Le Miraj (ascension nocturne) est l'un des récits les plus fascinants de la tradition islamique : Mohammed est transporté de La Mecque à Jérusalem (Isra), puis monte aux sept cieux, rencontre les prophètes antérieurs et s'approche de Dieu jusqu'à la limite au-delà de laquelle nul ne peut aller. Ce voyage nocturne est commémoré lors de la fête de Laylat al-Miraj.</p></div>
<h3>La civilisation islamique classique</h3>
<p class="resume-text">L'empire islamique (VIIe-XIIIe siècle) a produit l'une des civilisations les plus brillantes de l'histoire humaine. Bagdad, capitale abbasside, accueille la Maison de la Sagesse (Bayt al-Hikma) où des savants musulmans, chrétiens et juifs traduisent et commentent la philosophie grecque, les mathématiques indiennes et la médecine perse. Ces travaux seront transmis à l'Europe médiévale et contribueront à la Renaissance.</p>
<p class="resume-text">Al-Khawarizmi (IXe siècle) invente l'algèbre (son nom donne le mot « algorithme »). Ibn Sina (Avicenne) systématise la médecine arabe dans le Canon. Ibn al-Haytham développe l'optique géométrique. Al-Biruni mesure la circonférence de la terre avec une précision étonnante. Omar Khayyam résout des équations cubiques et réforme le calendrier persan. La liste des contributions scientifiques de la civilisation islamique classique est immense et souvent méconnue en Occident.</p>""",

    'grandes-religions/bouddhisme': """<h3>Bouddha : vie et Éveil</h3>
<p class="resume-text">Siddhartha Gautama naît vers 563 av. J.-C. (ou 480 selon d'autres traditions) dans la famille royale des Shakya au Népal actuel. Selon la légende, sa naissance s'accompagne de présages prophétiques : l'ascète Asita prédit qu'il sera soit un grand roi soit un bouddha (un éveillé). Son père, voulant éviter la seconde option, l'élève dans un luxe extrême en le coupant de toute vision de souffrance.</p>
<p class="resume-text">À 29 ans, lors de quatre sorties de son palais, Siddhartha rencontre successivement un vieillard, un malade, un mort et un ascète. Ces « quatre signes » le confrontent à la réalité de la souffrance universelle (dukkha) et lui révèlent la voie du renoncement. Il abandonne femme, enfant et trône pour chercher la libération. Après six années d'ascèse extrême qui faillit le tuer, il choisit la « voie du milieu » et s'assied sous l'arbre Bodhi à Bodh Gaya (Inde), où il atteint l'Éveil (Bodhi) à 35 ans.</p>
<div class="highlight-box"><p>Le concept de nirvana (extinction de la soif, du désir et de l'ignorance) est souvent mal compris. Ce n'est pas un néant : c'est la cessation de la souffrance par la suppression de ses causes. Certains textes décrivent le nirvana comme « non-né, non-devenu, non-fait, non-conditionné » — une réalité qui dépasse les catégories conceptuelles ordinaires.</p></div>
<h3>La diffusion du bouddhisme en Asie</h3>
<p class="resume-text">Après le parinirvana du Bouddha (mort définitive, vers 483 av. J.-C.), ses disciples se réunissent au premier concile de Rajagriha pour compiler ses enseignements. La diffusion du bouddhisme s'accélère sous le règne d'Ashoka (IIIe siècle av. J.-C.), grand emperor Maurya converti après la sanglante bataille de Kalinga : il envoie des missionnaires bouddhistes en Asie du Sud-Est, en Asie centrale et en Grèce.</p>
<p class="resume-text">En Chine, le bouddhisme arrive au Ier siècle ap. J.-C. et se fusionne avec le taoïsme pour créer le Chan (qui deviendra le Zen au Japon). Au Tibet (VIIe siècle), il se mêle au chamanisme bön pour produire le bouddhisme vajrayana. En Asie du Sud-Est, le theravada s'établit comme religion d'État en Thaïlande, Birmanie, Cambodge et Sri Lanka. Chaque pays a développé des formes distinctives adaptées à sa culture.</p>""",

    'textes-sacres/bible': """<h3>Les manuscrits et la critique textuelle</h3>
<p class="resume-text">La transmission manuscrite de la Bible est l'une des plus étudiées de l'histoire. Pour l'Ancien Testament, les manuscrits hébraïques les plus anciens complets datent du Xe siècle ap. J.-C. (codex d'Alep, codex de Leningrad). La découverte des manuscrits de la mer Morte à Qumrân (1947-1956) a fourni des textes du Ier siècle av. J.-C. qui confirment la stabilité du texte massorétique transmis pendant mille ans.</p>
<p class="resume-text">Le Nouveau Testament existe en plus de 5800 manuscrits grecs partiels ou complets — plus que tout autre texte de l'Antiquité. Les variantes entre manuscrits (environ 300 000) sont surtout mineures (orthographe, ordre des mots), mais certaines sont significatives (la pericope adulterae en Jean 7:53-8:11, la finale longue de Marc 16:9-20 sont des additions tardives). La critique textuelle cherche à reconstruire le texte original à partir de tous ces témoins.</p>
<div class="highlight-box"><p>La Septante (LXX) est la traduction grecque de l'Ancien Testament réalisée à Alexandrie (IIIe-IIe siècle av. J.-C.) pour les Juifs de la diaspora hellénophone. Elle fut la Bible des premiers chrétiens et introduit des nuances théologiques importantes : le mot grec parthenos (vierge) dans Isaïe 7:14 (là où l'hébreu dit alma = jeune femme) a fondé la doctrine de la naissance virginale du Christ.</p></div>
<h3>La Bible et les sciences modernes</h3>
<p class="resume-text">Les relations entre Bible et sciences modernes ont été souvent conflictuelles. Le procès de Galilée (1633) oppose le géocentrisme biblique au système héliocentriste copernicien. Darwin (1859) confronte la création en six jours au lent développement de l'évolution. Ces conflits ont parfois été exagérés : beaucoup de grands scientifiques (Mendel, Lemaître, Collins) étaient ou sont croyants et ne voyaient pas de contradiction de principe entre foi et science.</p>
<p class="resume-text">Le créationnisme (ou « Intelligent Design ») cherche à défendre une lecture littérale de la Genèse face au consensus scientifique évolutionniste. Ce mouvement, surtout présent aux États-Unis, illustre une interprétation fondamentaliste qui refuse la distinction entre vérité historique-scientifique et vérité théologique-symbolique. La grande majorité des théologiens catholiques, protestants et juifs acceptent l'évolution et considèrent les récits bibliques de la création comme des textes symboliques sur la signification de l'existence humaine.</p>""",

    'textes-sacres/tripitaka': """<h3>L'Abhidhamma et la psychologie bouddhiste</h3>
<p class="resume-text">L'Abhidhamma Pitaka développe une psychologie d'une précision remarquable. Il identifie 89 types distincts de conscience (citta), 52 facteurs mentaux (cetasika), et analyse comment ces éléments se combinent pour produire les états mentaux ordinaires et extraordinaires (méditation, Éveil). Cette cartographie détaillée de l'expérience psychique a été comparée à la phénoménologie husserlienne et est aujourd'hui explorée dans le dialogue entre bouddhisme et neurosciences.</p>
<p class="resume-text">La tradition Abhidharma a donné naissance à des écoles philosophiques distinctes. La Sarvastivada (qui affirme que tous les dharmas existent dans les trois temps — passé, présent, futur) s'opposait à la Theravada sur cette question de l'ontologie du temps. Ces débats philosophiques subtils témoignent d'une tradition de rigueur intellectuelle qui a influencé le développement du bouddhisme Mahayana et de la philosophie Madhyamaka de Nagarjuna.</p>
<div class="highlight-box"><p>Le Mind and Life Institute, fondé par le dalaï-lama et Francisco Varela, organise depuis 1987 des dialogues entre contemplatifs bouddhistes et scientifiques occidentaux. Ces rencontres ont produit des recherches fascinantes sur la neuroplasticité de la méditation, la nature de la conscience et la relation entre perception et réalité.</p></div>""",

    'textes-sacres/vedas': """<h3>Le Mahabharata et le Ramayana</h3>
<p class="resume-text">Les deux grandes épopées indiennes — le Mahabharata (environ 100 000 distiques, le plus long poème du monde) et le Ramayana (environ 24 000 distiques) — bien que classées dans la smriti (tradition humaine) plutôt que dans la shruti (révélation), exercent une influence populaire considérable. Le Mahabharata raconte la guerre entre deux branches cousines de la famille royale Kuru — les Pandavas et les Kauravas — guerre dont la Bhagavad-Gita constitue un épisode central.</p>
<p class="resume-text">Le Ramayana de Valmiki décrit l'enlèvement de Sita par le démon Ravana et la reconquête de Lanka par Rama avec l'aide de l'armée des singes conduite par Hanuman. Ces récits ont façonné la culture, l'art, le théâtre (Kathakali, wayang kulit), la danse et la politique de toute l'Asie du Sud et du Sud-Est. La série télévisée Ramayana diffusée en Inde (1987-1988) rassemblait chaque dimanche matin des dizaines de millions de spectateurs qui s'agenouillaient devant leur télévision.</p>
<div class="highlight-box"><p>La Bhagavad-Gita, insérée dans le Mahabharata, est le texte le plus lu de l'hindouisme. Son dialogue entre Krishna et Arjuna sur un champ de bataille est une méditation sur le devoir (dharma), l'action sans attachement au fruit (karma-yoga), la dévotion (bhakti) et la connaissance (jnana). Gandhi en portait toujours une copie et la considérait comme son « dictionnaire de conduite ».</p></div>""",

    'textes-sacres/coran': """<h3>L'impact du Coran sur la pensée mondiale</h3>
<p class="resume-text">Le Coran a suscité une tradition de commentaires (tafsir) qui constitue l'une des plus vastes littératures d'exégèse de l'histoire humaine. Les grandes questions de l'exégèse coraniques — le sens littéral versus le sens métaphorique, la cohérence interne du texte, la relation entre les versets mecquois et médinois, l'abrogation (naskh) — ont mobilisé des générations de savants. L'exégèse contemporaine (Mohammed Arkoun, Nasr Hamid Abu Zayd, Amina Wadud) applique des méthodes herméneutiques modernes au texte coranique.</p>
<p class="resume-text">La philosophie islamique médiévale (kalam, falsafa) a développé ses propres questions à partir du texte coranique : la création du monde (éternelle ou dans le temps ?), les attributs de Dieu, le libre arbitre et la prédestination, la nature du Bien et du Mal. Ces débats, souvent très techniques, ont mis en contact la philosophie grecque et la théologie islamique et produit des penseurs comme al-Farabi, Ibn Sina (Avicenne) et Ibn Rushd (Averroès).</p>
<div class="highlight-box"><p>La question de la « création du Coran » (khalq al-Quran) a été une controverse théologique majeure au IXe siècle : le Coran est-il incréé (attribut éternel de Dieu) ou créé (dans le temps) ? Le calife abbassie al-Ma'mun imposa la position mu'tazilite (Coran créé) par une inquisition (mihna). La position contraire — Coran incréé — finit par s'imposer, avec des conséquences durables sur la conception de l'autorité scripturaire dans l'islam sunnite.</p></div>""",

    'textes-sacres/torah': """<h3>La Torah et le droit international contemporain</h3>
<p class="resume-text">Certains principes de la Torah ont eu une influence directe sur le développement du droit occidental et international. Le principe du « tu ne tueras pas » et ses limitations théologiques ont alimenté les débats sur la peine de mort et la guerre juste. La tradition du jubilé (libération des esclaves et remise des dettes tous les cinquante ans, Lévitique 25) a inspiré des mouvements sociaux modernes de réduction de la dette des pays pauvres.</p>
<p class="resume-text">Les Lois de Noé (sheva mitsvot Bnei Noach) — sept commandements que la tradition rabbinique considère comme obligatoires pour toute l'humanité (non seulement les Juifs) — constituent une forme de droit naturel universel dans la tradition juive. Ces sept lois (notamment l'interdiction du meurtre, du vol, de la débauche, de l'idolâtrie, du blasphème, de la souffrance animale, et l'obligation d'établir des tribunaux) ont été citées dans des discussions sur les fondements du droit international.</p>
<div class="highlight-box"><p>La notion juive de tikkun olam (réparation/réfection du monde) a connu une fortune considérable dans le judaïsme libéral et progressiste américain depuis les années 1970. Elle est devenue une justification théologique de l'engagement social et politique : chaque acte juste contribue à la réparation d'un monde brisé depuis l'origine (selon la cosmologie lurianique).</p></div>""",

    'spiritualite/mysticisme-chretien': """<h3>La mystique contemporaine</h3>
<p class="resume-text">La mystique chrétienne connaît un renouveau au XXe siècle. Thomas Merton (1915-1968), moine trappiste américain, a ouvert le dialogue entre contemplation chrétienne et bouddhisme zen. Ses livres (La Nuit privée d'étoiles, L'Expérience intérieure) ont touché des millions de lecteurs. Sa mort accidentelle en Thaïlande, lors d'une rencontre avec des maîtres bouddhistes, est perçue comme symbolique de ce dialogue interreligieux.</p>
<p class="resume-text">Simone Weil (1909-1943), philosophe et mystique française, a vécu une expérience du Christ lors d'une récitation du Pater Noster. Sa pensée — qui articule l'attention spirituelle, la souffrance des opprimés et l'amour divin — a influencé aussi bien les théologiens que les philosophes politiques. Sa mort par refus de se nourrir par solidarité avec les Français rationnés est une forme extrême de mystique incarnée dans le monde.</p>
<div class="highlight-box"><p>L'expérience de la « nuit obscure » décrite par Jean de la Croix résonne dans la psychologie contemporaine : des états de vide intérieur, de perte de sens et d'éloignement de Dieu similaires à la dépression ont été analysés comme des étapes de croissance spirituelle. La distinction entre dépression pathologique et nuit obscure purificatrice est délicate et suscite des recherches au carrefour de la psychologie et de la spiritualité.</p></div>""",

    'spiritualite/soufisme': """<h3>Le sama et la musique sacrée</h3>
<p class="resume-text">Le sama (« écoute » en arabe) est la pratique d'écoute de musique sacrée dans les confréries soufies. Il peut provoquer des états de transe (hal) considérés comme signes de l'amour divin. Les derviches tourneurs de la Mawlawiyya (confrérie fondée par les disciples de Rumi) pratiquent une danse méditative circulaire (sema), les bras étendus, la tête inclinée, qui symbolise la rotation des planètes autour du soleil. Cette pratique est aujourd'hui inscrite au patrimoine immatériel de l'UNESCO.</p>
<p class="resume-text">La musique qawwali du Pakistan et de l'Inde du Nord est la forme la plus connue du sama en Occident. Nusrat Fateh Ali Khan, qui l'a popularisée dans les années 1990, collaborait avec Peter Gabriel et figurait sur des bandes originales de films hollywoodiens. La qawwali combine des poèmes en ourdou, hindi et persan sur des rythmes répétitifs intenses, créant une atmosphère d'extase collective recherchée tant par des croyants que par des auditeurs profanes.</p>
<div class="highlight-box"><p>Rumi écrit : « Je suis entre les deux mains de l'Aimé comme une flûte de roseau. Quand il soufflera en moi, je produirai de la musique. » Cette image de l'instrument de Dieu résume la vision soufie de l'humain : un creux ouvert à l'inspiration divine, souffrant de sa séparation d'avec son origine mais capable de beauté lorsqu'il s'y abandonne.</p></div>""",

    'spiritualite/kabbale': """<h3>La Kabbale et la philosophie contemporaine</h3>
<p class="resume-text">La pensée kabbalistique a nourri plusieurs courants philosophiques contemporains. Emmanuel Levinas, philosophe lituanien français, s'est appuyé sur la tradition talmudique et kabbalistique pour développer une éthique de la responsabilité infinie envers l'Autre (Autrui). Son concept d'infini — l'Autre est toujours plus que ce que je peux saisir — résonne avec la pensée apophatique de la Kabbale sur l'Ein Sof (l'Infini divin sans attributs).</p>
<p class="resume-text">Walter Benjamin, philosophe marxiste et mystique, s'est profondément imprégné de la Kabbale lurianique et de la pensée messianique juive. Son concept de « temps du maintenant » (Jetztzeit) — un éclair de reconnaissance où le passé opprimé peut être rédimé — est une laïcisation du tikun olam kabbalistique. Gershom Scholem, son ami, voit dans ce passage de la catégorie mystique au politique une caractéristique fondamentale de la modernité juive.</p>
<div class="highlight-box"><p>Le Golem de Prague — créature d'argile animée par l'inscription du mot « emet » (vérité) sur son front, selon la légende du Maharal de Prague (XVIe siècle) — est une métaphore de la créativité humaine, de ses pouvoirs et de ses limites. Les analyses modernes y voient une préfiguration du robot et de l'intelligence artificielle : qu'est-ce qu'une créature faite par l'homme ? Peut-elle avoir une âme ?</p></div>""",

    'spiritualite/meditation': """<h3>La méditation dans les traditions abrahamiques</h3>
<p class="resume-text">Si la méditation est souvent associée aux traditions orientales, les religions abrahamiques ont aussi leurs propres traditions contemplatives. La lectio divina chrétienne (lecture, méditation, prière, contemplation de textes sacrés) est pratiquée dans les monastères depuis le Ve siècle. La prière hésychaste orthodoxe (répétition du nom de Jésus synchronisée avec la respiration) présente des similitudes frappantes avec le mantra bouddhiste ou soufi.</p>
<p class="resume-text">Dans le judaïsme, la hitbonenut (introspection contemplative) du mouvement Habad-Loubavitch est une technique de méditation sur les concepts théologiques. La contemplation des lettres hébraïques (otiyot) dans la tradition kabbalistique est une forme de méditation sur le langage divin. Dans l'islam, le dhikr soufi et la muraqaba (vigilance du cœur) sont des pratiques méditatives ancestrales intégrées dans la vie quotidienne de millions de croyants.</p>
<div class="highlight-box"><p>La question de la relation entre méditation et prière suscite des débats théologiques passionnants. Pour certains contemplatifs chrétiens, toute méditation sans référence à un Dieu personnel est insuffisante ou même dangereuse. Pour d'autres, la contemplation silencieuse est une façon de s'ouvrir à ce qui dépasse les mots et les concepts — une rencontre avec l'ineffable qui transcende les différences religieuses.</p></div>""",

    'spiritualite/chamanisme': """<h3>Chamanisme et art préhistorique</h3>
<p class="resume-text">David Lewis-Williams a proposé une théorie influente selon laquelle les peintures rupestres paléolithiques (Lascaux, Altamira, Chauvet) seraient des représentations d'expériences visionnaires chamanique. Les entoptiques (formes géométriques vues lors de transe) — grilles, spirales, points, lignes — se retrouvent dans les grottes et dans les premières phases des états modifiés de conscience. Selon cette théorie, les chamanes préhistoriques peignaient leurs visions sur les parois des grottes.</p>
<p class="resume-text">Cette hypothèse est débattue mais stimulante : elle ouvre la possibilité que le chamanisme soit l'une des formes les plus anciennes d'expression spirituelle humaine, peut-être antérieure à toutes les religions organisées. Des récentes découvertes en archéologie (utilisation rituelle de plantes psychoactives dès 10 000 ans av. J.-C.) semblent appuyer l'ancienneté des pratiques chamaniques dans l'histoire humaine.</p>
<div class="highlight-box"><p>La crise climatique et l'effondrement de la biodiversité donnent une actualité nouvelle aux traditions chamaniques qui voient dans la nature un tissu d'esprits et de relations sacrées. Des anthropologues, des écologues et des militants environnementaux s'intéressent aux cosmologies autochtones comme sources d'une éthique de la relation humain-nature différente de celle qui a conduit à la crise écologique actuelle.</p></div>""",

    'philosophie-religieuse/thomas-aquin': """<h3>La conception thomiste de l'âme et du corps</h3>
<p class="resume-text">Thomas d'Aquin rompt avec la conception platonicienne de l'âme (une substance spirituelle emprisonnée dans un corps) pour adopter la psychologie aristotélicienne : l'âme est la forme du corps, principe d'organisation et d'animation. Cette vision hylemorphique (matière + forme) lui permet d'affirmer l'unité substantielle de l'être humain : je ne suis pas une âme qui a un corps, je suis une âme-corps.</p>
<p class="resume-text">Cette anthropologie a des conséquences importantes sur sa théologie : la résurrection corporelle n'est pas anecdotique mais essentielle, car l'homme sans corps n'est pas pleinement homme. La béatitude finale (la vision bienheureuse de Dieu) est une activité intellective qui requiert la totalité de la personne. Cette vision s'oppose au dualisme gnostique ou manichéen qui dévalorise le corps et la matière.</p>
<div class="highlight-box"><p>Le débat contemporain entre philosophie analytique de la religion (Plantinga, Swinburne) et naturalism (Quine, Dennett) continue les questions thomistes sur l'existence de Dieu, la nature de l'âme et les rapports entre foi et raison. Les « arguments cosmologiques » de William Lane Craig sont directement inspirés des cinq voies de Thomas d'Aquin, adaptées au contexte de la cosmologie moderne.</p></div>""",

    'philosophie-religieuse/averroes': """<h3>La philosophie politique d'Averroès</h3>
<p class="resume-text">Dans son Commentaire de la République de Platon, Averroès développe une philosophie politique où le philosophe est le vrai guide de la cité. Il déplore l'absence de femmes philosophes dans la société islamique de son temps et affirme que les femmes capables de sagesse devraient accéder à toutes les fonctions sociales. Cette position féministe avant la lettre est remarquable dans le contexte médiéval.</p>
<p class="resume-text">Pour Averroès, la loi religieuse est adaptée à la compréhension du peuple : l'élite philosophique accède à la vérité par la démonstration, la classe des théologiens par la dialectique, le peuple par la rhétorique et l'image. Cette hiérarchie épistémologique n'est pas méprisante : chaque niveau correspond à une capacité réelle. Mais elle implique que le philosophe est le seul à comprendre le vrai sens de la loi religieuse, dont il connaît les fondements rationnels que le peuple ne peut percevoir.</p>
<div class="highlight-box"><p>L'interdiction des œuvres d'Averroès par le calife almohade al-Mansur (1195) et son exil témoignent des tensions entre philosophie et religion dans l'Occident islamique du XIIe siècle. Ces œuvres furent sauvées par leur traduction en latin et en hébreu, paradoxe de l'histoire intellectuelle : le plus grand commentateur arabe d'Aristote fut mieux conservé et diffusé en Europe chrétienne que dans le monde arabe.</p></div>""",

    'philosophie-religieuse/maimonide': """<h3>Maïmonide et la rationalisation de la loi</h3>
<p class="resume-text">La Mishné Torah de Maïmonide (1168-1178) est une œuvre juridique sans précédent : il réorganise l'ensemble de la loi orale juive (Talmud, codes postérieurs) en un système logique et hiérarchique, en hébreu clair et accessible. Son ambition est de permettre à tout Juif instruit de connaître directement la loi sans avoir à parcourir l'océan talmudique. Cette systématisation est saluée comme un chef-d'œuvre mais critiquée par des rabbins qui y voient une usurpation de l'autorité rabbinique et une réduction de la Torah à un code.</p>
<p class="resume-text">Dans le Guide des égarés, Maïmonide soutient que les commandements rituels (sacrifices, lois alimentaires, calendrier) ont des raisons historiques et pédagogiques : ils ont éloigné les anciens Juifs de l'idolâtrie égyptienne et cananéenne, habitué à l'adoration d'un seul Dieu et préparé à la prophétie. Cette approche historique et fonctionnelle de la loi rituelle est novatrice et controversée : elle semble subordonner la loi divine à des considérations historiques contingentes.</p>
<div class="highlight-box"><p>Les « huit degrés de la charité » de Maïmonide constituent l'une des théories éthiques les plus élaborées du Moyen Âge. Au plus bas degré : donner à regret. Au plus haut : donner à quelqu'un les moyens de subvenir lui-même à ses besoins, en l'aidant à trouver un emploi ou en lui prêtant de l'argent — une anticipation remarquable des théories modernes du développement et de l'autonomisation (empowerment).</p></div>""",

    'philosophie-religieuse/pascal': """<h3>Pascal et la modernité</h3>
<p class="resume-text">Pascal anticipe des thèmes profondément modernes. Son analyse du « divertissement » (divertissement dans les deux sens — diversion et amusement) : l'homme s'abrutit dans les activités sociales pour ne pas faire face à sa condition de « roseau pensant » exposé à l'infini. Cette critique de la superficialité sociale préfigure la société du spectacle de Debord, l'inauthenticité heideggérienne et la culture du divertissement analysée par Neil Postman (Se distraire à en mourir).</p>
<p class="resume-text">La méditation pascalienne sur les deux infinis — l'infiniment grand (l'univers) et l'infiniment petit (l'atome) — illustre la fragilité et la grandeur de l'homme face à l'immensité du cosmos. « Qu'est-ce que l'homme dans la nature ? Un néant à l'égard de l'infini, un tout à l'égard du néant, un milieu entre rien et tout. » Cette formule anticipe l'angoisse existentielle moderne devant l'insignifiance cosmique et la conscience humaine comme lieu unique de sens.</p>
<div class="highlight-box"><p>Les Provinciales ont inventé la polémique moderne : argumentation serrée, humour corrosif, ironie féroce, exemples concrets tirés de cas réels. Voltaire reconnaîtra leur influence sur son propre style satirique. Cette rhétorique polémique, utilisée pour défendre une cause religieuse, deviendra le langage des Lumières pour attaquer les institutions religieuses — un paradoxe que Pascal, qui aimait les paradoxes, aurait apprécié.</p></div>""",

    'philosophie-religieuse/kierkegaard': """<h3>Kierkegaard et la psychologie</h3>
<p class="resume-text">Les analyses kierkegaardiennes de l'angoisse, du désespoir et de l'authenticité ont profondément influencé la psychologie du XXe siècle. Rollo May (Le Sens de l'angoisse) et Viktor Frankl (Logothérapie) s'inscrivent dans cette filiation existentielle. La psychologie humaniste d'Abraham Maslow valorise l'actualisation de soi — concept proche de l'ipséité kierkegaardienne. La notion de « mauvaise foi » sartrien est un concept frère du désespoir kierkegaardien.</p>
<p class="resume-text">La théorie de l'attachement (Bowlby, Ainsworth) retrouve certaines intuitions kierkegaardiennes : la sécurité ontologique — se sentir suffisamment aimé pour pouvoir exister en toute singularité — est la condition d'une vie authentique. Le manque d'amour fondateur produit des formes de désespoir (dépression, narcissisme, anxiété d'abandon) qui résonnent avec les analyses de La Maladie à la mort.</p>
<div class="highlight-box"><p>Kierkegaard a vécu une relation douloureuse avec Régine Olsen, qu'il a fiancée puis abandonnée sans explication publique. Cette rupture a été au cœur de nombreuses œuvres (Ou bien... Ou bien, Répétition, Le Journal du séducteur). Certains y voient une incapacité à l'intimité, d'autres un sacrifice de l'amour humain à la vocation spirituelle. Sa lettre finale à Régine, écrite peu avant sa mort, reste l'un des documents les plus émouvants de la correspondance philosophique.</p></div>""",

    'religions-monde/taoisme': """<h3>Le taoïsme religieux et ses institutions</h3>
<p class="resume-text">Parallèlement au taoïsme philosophique de Laozi et Zhuangzi, un taoïsme religieux s'est développé à partir du IIe siècle ap. J.-C. Le mouvement des Maîtres Célestes (Zhang Daoling, 142 ap. J.-C.) fonde le premier grand mouvement taoïste institutionnel, avec des prêtres ordonnés, des rites de guérison et une organisation ecclésiastique. Le taoïsme de la Voie de la Paix (Taipingjing) et le mouvement des Turbans Jaunes illustrent la dimension millénariste et sociale du taoïsme religieux.</p>
<p class="resume-text">L'alchimie taoïste (waidan = alchimie externe, neidan = alchimie interne) cherchait l'immortalité physique par des pratiques corporelles et des préparations chimiques. Si l'alchimie externe a conduit à la découverte de la poudre noire (gunpowder) et à des avancées en chimie, l'alchimie interne (cultivation du cinnabre intérieur, exercices respiratoires, pratiques sexuelles rituelles) a développé des techniques de santé et de longévité toujours pratiquées aujourd'hui sous forme de qi gong, tai-chi et médecine traditionnelle chinoise.</p>
<div class="highlight-box"><p>Le concept de wu wei (non-agir) ne signifie pas passivité mais action spontanée en harmonie avec la nature des choses — comme l'eau qui s'écoule sans forcer, usant les rochers les plus durs. Cette vision du leadership non-interventionniste a influencé la pensée politique de Lao Tseu (le meilleur gouvernant est celui dont le peuple ignore l'existence) et résonne dans les théories modernes du management par l'exemple plutôt que par le commandement.</p></div>""",

    'religions-monde/shintoisme': """<h3>Shinto et arts japonais</h3>
<p class="resume-text">L'esthétique du shinto imprègne les arts japonais. Le concept de musubi (lien vital, énergie créatrice des kami) nourrit l'art de l'arrangement floral (ikebana), qui est une méditation sur la croissance naturelle et non une simple décoration. L'architecture des jardins japonais (karesansui, jardins de pierres zen; tsukiyama, jardins de collines) cherche à recréer la présence des kami dans un espace miniaturisé.</p>
<p class="resume-text">La poterie japonaise (Raku, Bizen, Shigaraki) valorise les imperfections, les accidents de cuisson, la texture naturelle de l'argile — une esthétique du wabi-sabi (beauté de l'imparfait et de l'éphémère) qui reflète une vision shintoïste de la nature comme source de beauté intrinsèque. Le théâtre nô (XIVe siècle), fondé par Zeami Motokiyo, met souvent en scène des kami, des fantômes et des esprits de la nature dans des drames de hantise et de réconciliation.</p>
<div class="highlight-box"><p>Le manga et l'anime japonais, qui atteignent des audiences mondiales, sont imprégnés de thèmes shintoïstes et bouddhistes. Les films de Miyazaki Hayao (Princesse Mononoké, Mon voisin Totoro, Le Voyage de Chihiro) mettent en scène des kami, des esprits de la nature et la tension entre monde humain et monde naturel sacré. Ces œuvres transmettent une vision du monde japonaise à des milliards de spectateurs à travers le monde.</p></div>""",

    'religions-monde/sikhisme': """<h3>La philosophie sikhiste : Waheguru et l'égalité</h3>
<p class="resume-text">La théologie sikhiste est monothéiste et affirme l'absolue unicité de Dieu (Waheguru ou Ik Onkar). Dieu n'est pas seulement transcendant (au-delà du monde) mais immanent (présent dans toute la création). Cette vision panthéïste-monothéiste s'exprime dans le concept de Hukam (la Volonté divine qui régit l'univers) et de Nadar (la Grâce divine qui permet la libération).</p>
<p class="resume-text">L'égalité radicale est au cœur du sikhisme : rejet du système des castes (jati) qui stratifie la société indienne, égalité des sexes (les femmes peuvent être prêtresses, granthis), fraternité universelle entre tous les êtres humains. Cette vision sociale progressiste s'est concrétisée dans des pratiques comme le langar (repas communautaire gratuit), le seva (service désintéressé) et l'accueil de tous dans les gurdwaras, sans distinction de religion ou de statut.</p>
<div class="highlight-box"><p>Guru Gobind Singh a institué le Khalsa en 1699 lors de la fête de Baisakhi. Il demanda cinq volontaires à s'offrir à la mort — symbole ultime de dévotion. Lorsqu'ils sortirent indemnes de sa tente (selon la tradition), il déclara la formation du Khalsa (la communauté des Purs). Ces cinq « chères aimées » (Panj Pyare) représentèrent les premières initiations à la cérémonie amrit (baptême sikh).</p></div>""",

    'religions-monde/jainisme': """<h3>L'ascèse jaïne et la pratique monastique</h3>
<p class="resume-text">Le moine jaïn digambara (nu) représente l'idéal ascétique le plus exigeant du jaïnisme. Il n'a aucune possession, mange une seule fois par jour en cuisant ses mains en bol, se déplace pieds nus (même l'hiver), s'arrache les cheveux à la main lors de son initiation (kesha-loch) et pratique la mort volontaire par jeûne (sallekhana/santhara) lorsque son corps ne peut plus servir la libération de l'âme.</p>
<p class="resume-text">Les moines shvetambara (vêtus de blanc) sont moins stricts mais gardent toujours la bouche couverte d'un tissu (muhpati) et portent un balai pour déplacer les insectes. Les laïcs jaïns pratiquent le végétarisme strict (souvent aussi le véganisme), s'abstiennent de certaines professions violentes (agriculture, boucherie) et s'engagent dans le ahimsa au quotidien. Cette éthique quotidienne de non-violence différencie le jaïnisme des autres religions indiennes.</p>
<div class="highlight-box"><p>Vardhamana Mahavira a atteint l'omniscience (kevala-jnana) après 12 ans d'ascèse intense — pendant lesquels il endurait les morsures d'animaux et les violences humaines sans réagir. Cette persévérance stoïque face à la souffrance est un idéal éthique que Gandhi a transformé en stratégie politique de résistance non-violente (satyagraha) contre l'empire britannique.</p></div>""",

    'religions-monde/zoroastrisme': """<h3>Le zoroastrisme et la pensée dualiste</h3>
<p class="resume-text">Le dualisme cosmique zoroastrien (bien/mal, lumière/ténèbres) a exercé une fascination permanente sur la philosophie occidentale. Le manichéisme (IIIe siècle ap. J.-C.), fondé par Mani qui se considérait comme le dernier prophète après Zoroastre, Bouddha et Jésus, développe un dualisme encore plus radical : la matière entière est mauvaise, le but de la vie est de libérer la lumière emprisonnée dans la chair. Ce système attira Augustin de Thagaste pendant neuf ans avant sa conversion au christianisme.</p>
<p class="resume-text">Le catharisme médiéval (Albigeois, XIIe-XIIIe siècle), le paulicianisme arménien et le bogomilisme balkanique sont souvent décrits comme des héritiers du dualisme mazdéen. Cette généalogie est débattue, mais il est clair que la question du mal — pourquoi un Dieu bon a-t-il créé un monde mauvais ? — traverse toutes les traditions religieuses et reçoit dans le zoroastrisme une réponse d'une cohérence et d'une franchise remarquables : parce qu'il y a un autre dieu, mauvais, qui combat le bon dieu.</p>
<div class="highlight-box"><p>La survie du zoroastrisme jusqu'à nos jours, malgré 1400 ans de domination islamique en Iran, témoigne d'une résilience remarquable. Les communautés zoroastriennes d'Iran et d'Inde (Parsis) maintiennent des traditions vivantes tout en s'adaptant à la modernité. Des jeunes Iraniens en quête d'identité culturelle pré-islamique se réclament du zoroastrisme, témoignant de son rôle de marqueur identitaire national iranien.</p></div>""",
}

def enrich_content(content, new_html):
    """Insère new_html juste avant la section quiz."""
    quiz_marker = '<section class="content-section" id="quiz">'
    idx = content.find(quiz_marker)
    if idx != -1:
        return content[:idx] + new_html + content[idx:]
    last_section = content.rfind('</section>')
    if last_section != -1:
        return content[:last_section] + new_html + content[last_section:]
    return content + new_html


def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    pages = data.get('pages', {})
    modified = 0
    skipped = 0

    for key, html in PASS2.items():
        if key not in pages:
            print(f'SKIP (not found): {key}')
            skipped += 1
            continue

        page = pages[key]
        current_content = page.get('content', '') or ''

        if len(current_content) >= 15000:
            print(f'SKIP (already >= 15000): {key} ({len(current_content)} chars)')
            skipped += 1
            continue

        new_content = enrich_content(current_content, html)
        pages[key]['content'] = new_content
        print(f'OK: {key} ({len(current_content)} -> {len(new_content)} chars)')
        modified += 1

    data['pages'] = pages

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'\nDone: {modified} articles enriched, {skipped} skipped.')


if __name__ == '__main__':
    main()
