import json, re, sys

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def enrich_contenu(content, new_blocks):
    marker = '<section class="content-section" id="quiz">'
    idx = content.find(marker)
    if idx == -1:
        idx = content.rfind('</section>')
    return content[:idx] + new_blocks + content[idx:]

# ===== journalisme/photojournalisme =====
k = 'journalisme/photojournalisme'
extra = (
    '<h3>Ethique et mise en scene : les limites de l\'objectivite photographique</h3>'
    '<p class="resume-text">La photographie est souvent presentee comme un enregistrement neutre du reel, mais elle est en realite le resultat de <strong>choix deliberes</strong> : le cadrage (ce qui est inclus ou exclu), l\'instant decisif (Henri Cartier-Bresson), la profondeur de champ, la lumiere, l\'angle de prise de vue. Susan Sontag (<em>Sur la photographie</em>, 1977 ; <em>Devant la douleur des autres</em>, 2003) a analyse comment la photographie peut a la fois susciter l\'empathie et creer une distance, comment l\'abondance d\'images de souffrance peut conduire a l\'anesthesie morale plutot qu\'a la mobilisation.</p>'
    '<p class="resume-text">Des scandales ont ebranle la credibilite du photojournalisme : la photo de Mussolini (dont les hommes en arriere-plan ont ete effaces), la photo du soldat albanais de Brian Walski (montage de deux photos), le debat sur la mise en scene de certaines images de conflits. World Press Photo a revise ses regles en 2015 pour exclure les retouches substantielles. La question fondamentale reste : jusqu\'ou peut-on retoucher une image d\'information tout en preservant son caractere documentaire ?</p>'
    '<div class="highlight-box"><p>Susan Sontag : photographier la souffrance d\'autrui est un acte politique et ethique. L\'abondance d\'images de violence peut finir par anesthesier plutot que mobiliser.</p></div>'
    '<h3>Les grandes agences et la mondialisation de l\'image</h3>'
    '<p class="resume-text">Le photojournalisme mondial est structure par quelques grandes <strong>agences de presse photographique</strong> : Magnum Photos (fondee en 1947 par Cartier-Bresson, Capa, Seymour et Rodger — une cooperative unique ou les photographes conservent leurs droits), Reuters Pictures, Associated Press Images, AFP Photo, Getty Images. Ces agences distribuent les images a des milliers de medias dans le monde, creant une visualite partagee : les memes photos illustrent les memes evenements sur tous les continents, avec des consequences sur la construction d\'une culture visuelle globale.</p>'
    '<p class="resume-text">Magnum Photos represente un modele unique : cooperative de photographes qui controlent leurs droits, leurs archives et leur ligne editoriale. Les membres (au nombre strict, elus par cooptation) jouissent d\'une liberte editoriale rare. Des photographes comme Sebastiao Salgado (<em>Migrations</em>, <em>Workers</em>), James Nachtwey (guerres et genocides), Dorothea Lange (Grande Depression) ont produit des oeuvres photographiques qui transcendent le reportage pour atteindre une dimension artistique et documentaire durable.</p>'
    '<div class="highlight-box"><p>Magnum Photos (1947) : une cooperative de photographes qui ont refuse de ceder leurs droits aux journaux. Un modele de resistance economique qui a permis une independance artistique et editoriale unique.</p></div>'
    '<h3>Photojournalisme de guerre et trauma</h3>'
    '<p class="resume-text">La <strong>photographie de guerre</strong> a un pouvoir unique : rendre visible ce que les mots ne peuvent transmettre. La photo de la petite fille au napalm (Nick Ut, Vietnam, 1972), l\'homme du char place Tian\'anmen (1989), la photo de l\'enfant syrien Aylan Kurdi echoue sur la plage (2015) ont eu un impact politique immediat et durable. Mais ce pouvoir pose des questions : la photo de Kevin Carter d\'un enfant affame menace par un vautour (Soudan, 1993, prix Pulitzer) a suscite une controverse mondiale sur le role du photographe — temoin ou acteur humanitaire ?</p>'
    '<p class="resume-text">Les photojournalistes qui couvrent les conflits armees sont exposes a des <strong>traumatismes psychologiques</strong> severes (PTSD, syndrome de stress post-traumatique). Dario Mitidieri, Reza Deghati et d\'autres ont temoigne de la dissociation necessaire pour photographier l\'horreur. Des organisations comme la Dart Center for Journalism and Trauma (Columbia University) offrent du soutien et forment les journalistes a prendre soin de leur sante mentale. La couverture ethique du trauma exige aussi de considerer le consentement et la dignite des personnes photographiees dans les situations de vulnerabilite extreme.</p>'
    '<div class="highlight-box"><p>Kevin Carter, auteur de la photo du vautour et de l\'enfant somalien (Pulitzer 1994), s\'est suicide trois mois apres avoir recu le prix. Son histoire illustre le trauma des photojournalistes de guerre et la question morale du temoignage face a la souffrance.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== journalisme/avenir-du-journalisme =====
k = 'journalisme/avenir-du-journalisme'
extra = (
    '<h3>La crise du modele economique et les reponses emergentes</h3>'
    '<p class="resume-text">Entre 2008 et 2024, la presse ecrite a perdu en moyenne 70 % de ses recettes publicitaires au profit des plateformes numeriques (Google, Facebook). Aux Etats-Unis, plus de 2 500 journaux locaux ont ferme depuis 2005, creant des <strong>deserts d\'information</strong> (news deserts) — des zones geographiques privees de toute couverture journalistique locale. Ces zones sont vulnerables a la corruption locale, a la desinformation et au declin de la participation civique. En France, la presse regionale a perdu 40 % de ses lecteurs depuis 2000.</p>'
    '<p class="resume-text">Plusieurs modeles alternatifs emergent : les <strong>fondations a but non lucratif</strong> (ProPublica, The Guardian Foundation, Mediapart coop) financees par des dons, fondations et abonnements ; les <strong>cooperatives de lecteurs</strong> (Le Monde appartient partiellement a ses lecteurs depuis 2010) ; le <strong>financement participatif</strong> (Kickstarter, Ulule) pour des projets d\'enquete specifiques ; les <strong>micro-abonnements</strong> et les paywall poreux qui permettent un acces partiel. Aucun modele ne s\'est encore impose comme successeur du modele publicitaire de masse.</p>'
    '<div class="highlight-box"><p>Les deserts d\'information sont une menace democratique reelle : quand il n\'y a plus de journaliste local, les conseils municipaux deviennent opaques, les marches publics non surveilles, la corruption plus facile.</p></div>'
    '<h3>Journalisme de solutions et journalisme constructif</h3>'
    '<p class="resume-text">Le <strong>journalisme de solutions</strong> (solutions journalism) ne nie pas les problemes mais cherche a couvrir les reponses qui fonctionnent : non seulement l\'echec scolaire, mais les pedagogies innovantes qui le reduisent ; non seulement la violence urbaine, mais les programmes de prevention qui marchent. Le Solutions Journalism Network (SJN), fonde en 2013, a developpe une methodologie rigoureuse et forme des milliers de journalistes. Cette approche ne sacrifie pas le spirit critique — elle l\'applique aussi aux solutions, en questionnant leur replicabilite et leurs limites.</p>'
    '<p class="resume-text">Le <strong>journalisme d\'engagement</strong> (engaged journalism) cherche a reetablir le lien entre les medias et leurs communautes, en consultant les lecteurs sur les sujets a traiter, en organisant des evenements publics, en co-construisant certains contenus. Cette approche, portee par des medias comme De Correspondent (Pays-Bas) ou El Diario (Espagne), repense la relation journaliste-lecteur comme un partenariat plutot qu\'une transmission verticale. Elle repond a la defiance croissante du public envers les medias etablis.</p>'
    '<div class="highlight-box"><p>De Correspondent (Pays-Bas) a lance son modele sans publicite, finance uniquement par ses abonnes, en promettant du journalisme lent et approfondi. Avec 75 000 membres, il prouve qu\'une autre economie de l\'information est possible.</p></div>'
    '<h3>Intelligence artificielle : menace et outil pour le journalisme</h3>'
    '<p class="resume-text">Les <strong>grands modeles de langage</strong> (LLM) comme GPT-4 ou Gemini peuvent rediger des articles financiers, sportifs ou meteorologiques a partir de donnees structurees — AP, Bloomberg et Reuters utilisent deja ces outils pour des milliers d\'articles routiniers. Cette automatisation libere les journalistes humains pour le reportage approfondi, l\'investigation et l\'analyse — mais supprime aussi des emplois et souleve des questions de qualite et de fiabilite (les LLM peuvent halluciner des faits). Plusieurs redactions ont adopte des chartes editoriales encadrant l\'usage de l\'IA.</p>'
    '<p class="resume-text">L\'IA offre aussi des <strong>outils d\'investigation</strong> puissants : analyse de masse de documents (centaines de milliers de PDF en quelques heures), detection d\'anomalies dans des bases de donnees, traduction automatique de sources etrangeres, identification de faux comptes et de campagnes de desinformation coordonnees. Le Washington Post (Heliograf), Le Monde et d\'autres ont investi dans des equipes tech-journalisme hybrides. L\'enjeu est d\'utiliser l\'IA comme amplificateur des capacites journalistiques, sans abandonner le jugement editorial humain qui reste la colonne vertebrale du metier.</p>'
    '<div class="highlight-box"><p>L\'Associated Press publie des milliers d\'articles generes par IA chaque trimestre pour les resultats d\'entreprises et les matches sportifs mineurs. Cela libere ses journalistes pour l\'investigation — et illustre comment l\'IA transforme le journalisme sans le remplacer entierement.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== medias-numeriques/histoire-internet =====
k = 'medias-numeriques/histoire-internet'
extra = (
    '<h3>La gouvernance d\'Internet : tensions et enjeux</h3>'
    '<p class="resume-text">Internet n\'est pas governe par une seule autorite mondiale, mais par un ecosysteme d\'organisations techniques : l\'ICANN (Internet Corporation for Assigned Names and Numbers, qui gere les noms de domaine et adresses IP), l\'IETF (Internet Engineering Task Force, qui definit les protocoles techniques), le W3C (World Wide Web Consortium, normes du Web). Ce modele de <strong>gouvernance multi-parties prenantes</strong>, qui inclut gouvernements, entreprises, societe civile et techniciens, est a la fois sa force (absence de censure centralisee) et sa faiblesse (difficulte de coordonner des reponses mondiales aux menaces comme la desinformation).</p>'
    '<p class="resume-text">Le <strong>debat sur la neutralite du Net</strong> oppose deux visions : la neutralite (les fournisseurs d\'acces traitent tous les paquets de donnees egalement, sans discrimination selon leur source ou leur contenu) versus la gestion du trafic (permettre aux FAI de prioriser certains services, potentiellement au detriment de concurrents). Aux Etats-Unis, la FCC a aboli la neutralite du Net en 2017 sous Trump puis l\'a retablie en 2024 sous Biden. En Europe, le reglement du 2015 garantit la neutralite. L\'enjeu est fondamental : sans neutralite, les FAI pourraient avantager leurs propres services ou ceux des plus offrants.</p>'
    '<div class="highlight-box"><p>La neutralite du Net est le principe selon lequel toutes les donnees circulent egalement sur Internet. Sans elle, un FAI pourrait ralentir Netflix pour favoriser son propre service de streaming — transformant Internet en cable TV payant.</p></div>'
    '<h3>Fracture numerique et inegalites d\'acces</h3>'
    '<p class="resume-text">En 2024, <strong>2,6 milliards de personnes</strong> (soit un tiers de l\'humanite) n\'ont pas acces a Internet. La fracture numerique (digital divide) a plusieurs dimensions : acces physique (infrastructure de reseau absent dans les zones rurales et pays pauvres), acces economique (cout des equipements et des abonnements), acces competences (litteratie numerique), acces langue (75 % des contenus web sont en anglais, alors qu\'il est langue maternelle de 5 % de la population mondiale). Cette fracture reproduit et amplifie les inegalites economiques et educatives preexistantes.</p>'
    '<p class="resume-text">Des initiatives cherchent a combler ce fosse : <strong>Internet.org</strong> (Meta) a ete critique pour avoir cree un Internet a deux vitesses (donnant acces gratuit uniquement aux services Meta) ; <strong>Starlink</strong> (SpaceX) offre un acces satellite haut debit aux zones rurales et isolees ; les reseaux <strong>mesh</strong> communautaires permettent a des quartiers de creer leurs propres reseaux locaux a bas cout. L\'ONU a declare l\'acces a Internet un droit fondamental en 2016, reconnaissant son role indispensable dans l\'exercice de la liberte d\'expression, de l\'acces a l\'information et du developpement economique.</p>'
    '<div class="highlight-box"><p>L\'ONU (2016) : l\'acces a Internet est un droit fondamental. Couper deliberement l\'acces a Internet d\'une population est une violation des droits humains — pratique pourtant courante lors de contestations politiques (Birmanie, Iran, Ethiopie).</p></div>'
    '<h3>Web 3.0, metavers et horizons futurs</h3>'
    '<p class="resume-text">Le <strong>Web 3.0</strong> designe une vision decentralisee d\'Internet s\'appuyant sur la blockchain, les cryptomonnaies et les NFT (jetons non fongibles). L\'idee centrale est de restituer aux utilisateurs la propriete de leurs donnees et de leurs contenus, sans intermediaires centralises (GAFAM). Cependant, les promesses du Web 3.0 se heurtent a des obstacles pratiques : complexite technique, consommation energetique des blockchains, speculation financiere et nombreuses arnaques (rug pulls). Le bilan reste mitige entre innovation reelle et discours marketing.</p>'
    '<p class="resume-text">Le concept de <strong>metavers</strong> — espaces virtuels persistants et immersifs combines au monde physique — est porte par Meta (Horizon Worlds), Microsoft (Mesh), Epic Games (Fortnite) et de nombreuses startups. Ses applications potentielles touchent l\'education (cours en realite virtuelle), le travail collaboratif a distance, le divertissement et le commerce. Cependant, les difficultes techniques (casques lourds et couteux, latence, mal des transports virtuel), la fragmentation des ecosystemes et les questions de vie privee freinent un deploiement de masse. L\'avenir d\'Internet reste ouvert et conteste.</p>'
    '<div class="highlight-box"><p>Le metavers n\'est pas une invention de Meta : le terme vient du roman Snow Crash de Neal Stephenson (1992). La SF imagine souvent l\'avenir des technologies de communication bien avant les ingenieurs.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved batch 3 (3 articles)")
