#!/usr/bin/env python3
"""Enrichissement des articles de communication.json"""
import json
import re

ENRICHMENTS = {
    "theorie-communication/modeles-fondateurs": """<h3>L'ère numérique et les nouveaux modèles</h3><p class="resume-text">Les modèles classiques de la communication se révèlent insuffisants face aux réalités numériques. Le modèle de <strong>Castells</strong> (« Communication Power », 2009) intègre les réseaux comme infrastructure fondamentale de la communication contemporaine. Pour Castells, le pouvoir se joue dans les réseaux : qui contrôle les nœuds (gatekeepers numériques) et les connexions entre réseaux détient le pouvoir de programmation et de connexion dans la société en réseau. Meta, Alphabet et Apple sont les exemples contemporains de ce pouvoir nodal.</p><p class="resume-text">La <strong>théorie des usages et gratifications</strong> (Katz, Blumler, Gurevitch, 1974) inversa la perspective des effets médiatiques en se demandant « que font les gens avec les médias ? » plutôt que « que font les médias aux gens ? ». Les individus choisissent activement les médias selon leurs besoins : information, divertissement, identité personnelle, intégration sociale. Cette approche, actualisée pour les réseaux sociaux, explique pourquoi TikTok satisfait le besoin de divertissement et d'identité, tandis que LinkedIn satisfait le besoin professionnel et de statut.</p><div class="highlight-box"><p>Le modèle de Castells (2009) place les réseaux au cœur du pouvoir contemporain : contrôler les algorithmes de Meta ou Google, c'est détenir le pouvoir de programmer ce que des milliards voient.</p></div>""",

    "theorie-communication/semiologie-et-signes": """<h3>La sémiologie à l'ère des images et du numérique</h3><p class="resume-text">La <strong>sémiologie visuelle</strong> est devenue une discipline majeure dans un monde saturé d'images. Roland Barthes distinguait dans l'image publicitaire le message dénoté (ce qui est représenté littéralement), le message connoté (les associations culturelles et symboliques) et le message linguistique (texte qui ancre et relaie l'image). Cette analyse s'applique parfaitement aux visuels des réseaux sociaux : une photo Instagram d'une influenceuse dans un café parisien code simultanément un style de vie, des valeurs aspirationnelles et une identité sociale.</p><p class="resume-text">Les <strong>emojis</strong>, développés au Japon en 1999 par Shigetaka Kurita, constituent un nouveau système sémiologique universel : 3 300 symboles utilisés 10 milliards de fois par jour, formant un langage visuel mondial transcendant les barrières linguistiques. L'Unicode Consortium (organisation à but non lucratif) décide des nouveaux emojis et de leurs représentations, exerçant un pouvoir normatif considérable sur la communication visuelle mondiale. Les débats sur la diversité des emojis (nuances de peau, familles non traditionnelles) illustrent que les systèmes de signes sont toujours des constructions sociales et politiques.</p><div class="highlight-box"><p>Les emojis, utilisés 10 milliards de fois par jour dans le monde, constituent le système sémiologique visuel le plus universel jamais créé, transcendant les 7 000 langues humaines.</p></div>""",

    "theorie-communication/communication-de-masse": """<h3>Les théories des médias à l'ère numérique</h3><p class="resume-text">Les théories classiques des effets médiatiques se reconfigurent dans l'environnement numérique. La <strong>chambre d'écho</strong> (Eli Pariser, « The Filter Bubble », 2011) décrit comment les algorithmes de personnalisation enferment les utilisateurs dans des univers informationnels homogènes, ne renforçant que leurs croyances préexistantes. Contrairement à l'agenda-setting des médias de masse (qui proposait le même menu à tous), les plateformes numériques créent des agendas individualisés, fragmentant l'espace public commun.</p><p class="resume-text">La <strong>théorie de la cultivation</strong> de George Gerbner (1969) postulait que les grands consommateurs de télévision développent une vision du monde correspondant aux réalités télévisuelles (surestimation de la violence, du crime). Transposée aux réseaux sociaux, cette théorie explique comment l'exposition répétée à certains contenus (complotisme, extrémisme politique) peut cultiver des perceptions déformées de la réalité sociale. Les travaux de Jonathan Haidt sur les effets des médias sociaux sur la santé mentale des adolescentes s'inscrivent dans cette lignée.</p><div class="highlight-box"><p>Jonathan Haidt (NYU) a documenté une augmentation de 150 % des dépressions chez les adolescentes américaines depuis 2012, corrélée avec l'adoption massive d'Instagram et la culture des « likes ».</p></div>""",

    "theorie-communication/communication-interpersonnelle": """<h3>Communication interpersonnelle et numérique</h3><p class="resume-text">La communication interpersonnelle est profondément transformée par la médiatisation numérique. La <strong>Computer-Mediated Communication</strong> (CMC) étudie les spécificités des échanges via les technologies numériques. Les travaux de Joseph Walther (hyperpersonal model, 1996) montrent paradoxalement que la communication asynchrone en ligne peut être plus intime et idéalisée que la communication en face-à-face : l'absence de signaux non verbaux permet une gestion plus soignée de la présentation de soi, conduisant à une idéalisation mutuelle.</p><p class="resume-text">L'<strong>intelligence émotionnelle</strong> (Salovey et Mayer, 1990 ; popularisée par Goleman, 1995) désigne la capacité à percevoir, comprendre, gérer et utiliser ses émotions et celles des autres. Elle est aujourd'hui reconnue comme un prédicteur plus fiable du succès professionnel que le QI dans les métiers relationnels. Les techniques d'écoute active (reformulation, validation émotionnelle, questions ouvertes), développées par Carl Rogers dans le cadre de la psychothérapie, ont été adaptées aux contextes professionnels, éducatifs et diplomatiques.</p><div class="highlight-box"><p>Daniel Goleman a popularisé l'idée que l'intelligence émotionnelle (IE) compte davantage que le QI dans la réussite professionnelle — une thèse soutenue par des méta-analyses portant sur 500 000 personnes.</p></div>""",

    "theorie-communication/rhetorique-et-persuasion": """<h3>Persuasion et manipulation à l'ère numérique</h3><p class="resume-text">Les techniques de persuasion classiques sont amplifiées et parfois détournées par les technologies numériques. Le <strong>nudge</strong> (« coup de pouce »), théorisé par Thaler et Sunstein (prix Nobel 2017), utilise l'architecture des choix pour orienter les comportements sans interdire ni imposer : une cafétéria qui place les fruits en entrée réduit la consommation de desserts sans rien interdire. Transposé au numérique, le nudge design est omniprésent : notifications push, couleurs des boutons, mise en page des formulaires, défaut des options. Ces micro-décisions de design influencent des millions de comportements quotidiens.</p><p class="resume-text">La <strong>propagande computationnelle</strong> (Woolley, Howard, 2016) désigne l'utilisation automatisée d'algorithmes et de bots pour manipuler l'opinion publique à grande échelle. Cambridge Analytica a utilisé les données de 87 millions de profils Facebook pour cibler des électeurs américains avec des messages personnalisés en 2016. Les « opérations d'influence » (termes de l'OTAN) combinent faux comptes, deepfakes et amplification algorithmique pour polariser les débats politiques. La distinction entre persuasion légitime et manipulation devient un enjeu démocratique central.</p><div class="highlight-box"><p>Cambridge Analytica a ciblé 87 millions de profils Facebook en 2016 avec des messages personnalisés selon le type psychologique (OCEAN) — le premier cas documenté de micro-ciblage politique à grande échelle.</p></div>""",

    "journalisme/histoire-de-la-presse": """<h3>L'éclatement du modèle journalistique contemporain</h3><p class="resume-text">Le modèle économique de la presse traditionnelle est en crise structurelle depuis les années 2000. L'effondrement des recettes publicitaires, capturées par Google et Meta (qui absorbent 60 % des revenus publicitaires numériques mondiaux), a provoqué la fermeture de 2 200 journaux américains entre 2005 et 2022 et la suppression de 57 % des emplois journalistiques dans le pays. La France n'est pas épargnée : les grands quotidiens régionaux survivent grâce aux aides à la presse et aux regroupements. Cette crise a créé des « déserts médiatiques » — régions entières sans journaux locaux — avec des effets documentés sur la désinformation locale et la participation civique.</p><p class="resume-text">Face à cette crise, de nouveaux modèles émergent. Le <strong>journalisme de solutions</strong> (Constructive Institute, fondé à Aarhus en 2017) se focalise sur des réponses aux problèmes sociaux plutôt que sur les catastrophes. Le <strong>journalisme de données</strong> (data journalism), popularisé par The Guardian et Le Monde, utilise les ensembles de données massives pour révéler des tendances invisibles. Les <strong>pure players</strong> (Mediapart, Arrêt sur Images, The Intercept) proposent un modèle abonnement sans publicité qui préserve l'indépendance éditoriale. La newsletter personnalisée (Substack) offre à des journalistes individuels la possibilité de monétiser directement leur audience.</p><div class="highlight-box"><p>Mediapart, fondé en 2008 par Edwy Plenel, est le premier pure player français rentable : 230 000 abonnés payants, 100 % financé par abonnements sans publicité ni subventions.</p></div>""",

    "journalisme/deontologie-journalistique": """<h3>Déontologie et vérification à l'ère des fake news</h3><p class="resume-text">Le <strong>fact-checking</strong> est devenu une pratique journalistique à part entière face à la prolifération de fausses informations. Des organisations spécialisées — PolitiFact (2007, États-Unis), Les Décodeurs du Monde, CheckNews de Libération, Africa Check — vérifient les déclarations des responsables politiques et les informations virales. L'International Fact-Checking Network (IFCN) fédère 150 organisations de fact-checking dans 65 pays. Leurs limites sont réelles : études montrant que les corrections et démentis n'effacent pas toujours l'effet des fausses informations (« backfire effect »).</p><p class="resume-text">La <strong>protection des sources</strong> est un pilier de la déontologie journalistique mis à l'épreuve par la surveillance numérique. Les révélations de Snowden (2013) ont montré que les métadonnées téléphoniques permettaient d'identifier les sources sans déchiffrer les communications. Les journalistes utilisent désormais des outils cryptographiques (Signal, Tor, SecureDrop créé par Aaron Swartz et The New Yorker) pour protéger leurs sources. Les poursuites judiciaires contre Julian Assange (WikiLeaks) ont posé la question des limites de la liberté de la presse dans la publication de documents classifiés.</p><div class="highlight-box"><p>SecureDrop, le système de dépôt anonyme de documents utilisé par plus de 80 médias mondiaux, a permis la publication des Panama Papers, des FinCEN Files et de nombreuses autres enquêtes majeures.</p></div>""",

    "journalisme/journalisme-investigation": """<h3>Le journalisme d'investigation à l'ère des mégafuites</h3><p class="resume-text">La révolution numérique a engendré des <strong>fuites massives</strong> de données sans précédent dans l'histoire du journalisme. Les Panama Papers (2016 : 11,5 millions de documents, 2,6 téraoctets), les Paradise Papers (2017 : 13,4 millions de documents) et les Pandora Papers (2021 : 11,9 millions de documents) ont révélé les mécanismes de l'évasion fiscale à l'échelle mondiale. Ces investigations du Consortium international des journalistes d'investigation (ICIJ) mobilisent des centaines de journalistes dans 80 pays et nécessitent des outils spécialisés de traitement de données massives (algorithmes d'analyse de réseaux, OSINT).</p><p class="resume-text">L'<strong>enquête collaborative</strong> transnationale est le modèle d'avenir du journalisme d'investigation. Bellingcat, fondé par Eliot Higgins en 2014, a révolutionné l'Open Source Intelligence (OSINT) : utilisant uniquement des sources ouvertes (images satellite, réseaux sociaux, photos publiées involontairement), l'organisation a identifié les auteurs du crash du MH17 (2014), des empoisonnements Skripal (2018) et des frappes chimiques en Syrie. Ces techniques géolocalisent des événements à partir de détails visuels (végétation, architecture, ombres), démocratisant une forme d'enquête jadis réservée aux services de renseignement.</p><div class="highlight-box"><p>Bellingcat a identifié les agents du GRU russe responsables de l'empoisonnement des Skripal (2018) en 72 heures, uniquement via des sources ouvertes — une performance que les services de renseignement officiels ont mis des mois à confirmer.</p></div>""",

    "journalisme/photojournalisme": """<h3>L'image à l'ère de la désinformation visuelle</h3><p class="resume-text">Le photojournalisme contemporain est confronté à une crise de confiance sans précédent. La manipulation numérique des images (Photoshop depuis 1990, deepfakes depuis 2017) rend difficile la distinction entre authenticité et fiction. Des cas emblématiques jalonnent l'histoire récente : la photo retouchée du photographe de l'AFP Brian Walski (Irak, 2003), les images composites révélées lors des guerres de Gaza et d'Ukraine. Les grandes agences (Reuters, AFP, AP) ont renforcé leurs chartes éthiques : aucune manipulation au-delà des ajustements d'exposition et de couleur autorisés en chambre noire.</p><p class="resume-text">La <strong>vérification des images</strong> (Image Verification) est une compétence journalistique cruciale. Des outils comme Google Reverse Image Search, TinEye, InVID et Forensically permettent de détecter les manipulations et de géolocaliser les images. La plateforme Witness, fondée par Peter Gabriel (chanteur de Genesis) en 1992, forme des citoyens du monde entier à documenter les violations des droits de l'homme par l'image. Le Visual Investigations team du New York Times, utilisant imagerie satellite, reconstruction 3D et analyse de vidéos, a reconstitué l'attaque de Khashoggi, les frappes en Afghanistan et l'assaut du Capitole.</p><div class="highlight-box"><p>Le Visual Investigations team du New York Times a reconstruit en 3D l'assaut du Capitole (2021) à partir de 500 heures de vidéos publiques — un exemple emblématique du journalisme visuel de données.</p></div>""",

    "journalisme/avenir-du-journalisme": """<h3>L'intelligence artificielle et l'avenir de la profession</h3><p class="resume-text">L'intelligence artificielle transforme radicalement la profession journalistique. Des outils comme le Automated Insights (USA Today, Associated Press) génèrent des articles financiers et sportifs automatiques depuis 2014 : l'AP publie 3 000 articles automatiques par trimestre sur les résultats des entreprises cotées. L'<strong>IA générative</strong> (GPT-4, Claude) peut rédiger des articles, résumer des documents volumineux et traduire en temps réel. Ces outils soulèvent des questions éthiques sur l'attribution, la transparence et l'emploi : le média américain CNET a discrètement publié des dizaines d'articles IA avant d'être exposé.</p><p class="resume-text">Face à ces défis, la valeur ajoutée journalistique se déplace vers l'<strong>enquête, l'analyse et la confiance</strong>. Les lecteurs recherchent des journalistes qu'ils reconnaissent et en qui ils ont confiance plutôt que des articles anonymes. Le modèle des newsletters personnelles (Substack, Beehiiv) permet aux journalistes de construire une relation directe et payante avec leur audience. La transparence sur les méthodes journalistiques — montrer les sources, expliquer les choix éditoriaux — devient un argument commercial différenciant dans un paysage médiatique saturé de désinformation.</p><div class="highlight-box"><p>Associated Press publie 3 000 articles financiers par trimestre générés automatiquement par l'IA — libérant ses journalistes pour des enquêtes à plus forte valeur ajoutée.</p></div>""",

    "medias-numeriques/histoire-internet": """<h3>De l'ARPANET à l'intelligence artificielle générative</h3><p class="resume-text">L'histoire d'internet s'accélère exponentiellement. Après le Web 1.0 (lecture seule, 1991-2004), le Web 2.0 (participation, réseaux sociaux, 2004-2015) et les plateformes dominantes (2015-2022), nous entrons dans l'ère du <strong>Web 3.0</strong> et de l'IA générative. ChatGPT (OpenAI, lancé en novembre 2022) a atteint 100 millions d'utilisateurs en deux mois — le produit technologique à la croissance la plus rapide de l'histoire. Cette IA générative repose sur des Large Language Models (LLM) entraînés sur des milliards de documents, capables de générer textes, images, vidéos et codes informatiques.</p><p class="resume-text">La <strong>concentration du pouvoir numérique</strong> est un enjeu démocratique central. Cinq entreprises (Apple, Microsoft, Alphabet/Google, Amazon, Meta) capitalisaient ensemble plus de 10 000 milliards de dollars en 2024, soit davantage que le PIB de l'Allemagne, du Japon et de la France réunis. Cette concentration soulève des enjeux antitrust (démantèlement potentiel de Google pour abus de position dominante dans la recherche, enquête en 2024), de fiscalité (accord sur un taux minimum mondial de 15 % pour les multinationales, en vigueur en 2024) et de souveraineté numérique (cloud souverain européen, GAIA-X).</p><div class="highlight-box"><p>Les Big Five du numérique (Apple, Microsoft, Alphabet, Amazon, Meta) représentent plus de 10 000 milliards de dollars de capitalisation — plus que les PIB combinés de l'Allemagne, du Japon et de la France.</p></div>""",

    "medias-numeriques/reseaux-sociaux": """<h3>Les réseaux sociaux entre influence et régulation</h3><p class="resume-text">La régulation des réseaux sociaux est devenue un enjeu politique majeur mondial. L'Union européenne a adopté le <strong>Digital Services Act</strong> (DSA, 2023), qui oblige les très grandes plateformes (plus de 45 millions d'utilisateurs en Europe) à lutter contre les contenus illicites, à donner accès aux données aux chercheurs et à interdire le ciblage publicitaire des mineurs. C'est la réglementation la plus ambitieuse au monde en matière de plateformes numériques et elle inspire des législations similaires en Australie, au Royaume-Uni et au Canada.</p><p class="resume-text">Le rachat de Twitter par Elon Musk (44 milliards de dollars, octobre 2022, renommé X) a été une expérience grandeur nature sur les conséquences de la modération des contenus. La réduction de 80 % des équipes de modération, la réintégration de comptes bannis et la monétisation des abonnements « checkmarks » ont provoqué une augmentation documentée des contenus haineux et la fuite d'annonceurs. Cet épisode a illustré comment la structure de modération d'une plateforme de 250 millions d'utilisateurs détermine directement la qualité de l'espace public numérique.</p><div class="highlight-box"><p>Le Digital Services Act européen (2023) est la première loi au monde à imposer des obligations de transparence algorithmique aux grandes plateformes — un modèle que 40 pays étudient pour leur propre législation.</p></div>""",

    "medias-numeriques/algorithmes-et-filtres": """<h3>La gouvernance algorithmique comme enjeu de pouvoir</h3><p class="resume-text">Les algorithmes de recommandation sont devenus des <strong>architectures du débat public</strong> dont les concepteurs sont rarement connus du grand public. YouTube recommande automatiquement 70 % de ce que ses utilisateurs regardent ; TikTok peut multiplier par 1 000 la diffusion d'une vidéo en quelques heures. Ces systèmes optimisant l'engagement (temps passé, interactions) favorisent structurellement les contenus émotionnels, polarisants et sensationnels. Frances Haugen, lanceuse d'alerte ex-Meta (2021), a fourni des milliers de documents internes montrant que les ingénieurs de Facebook savaient que leurs algorithmes amplifiaient la haine et la désinformation.</p><p class="resume-text">La <strong>transparence algorithmique</strong> est au cœur des débats sur la régulation numérique. Le DSA européen exige que les grandes plateformes offrent une option de fil d'actualité non algorithmique (chronologique). La recherche académique sur les algorithmes est entravée par les accès restreints aux données : la « Sovereign Tech Fund » allemande et l'initiative ADM (Algorithmic Data for Society) cherchent à développer des audits algorithmiques indépendants. Le « droit d'explication » des décisions algorithmiques, inscrit dans le RGPD, reste difficile à mettre en pratique concrètement.</p><div class="highlight-box"><p>Les documents internes de Meta, révélés par Frances Haugen en 2021, montrent que Facebook savait que son algorithme amplifie haine et désinformation — mais avait choisi de ne pas modifier ses paramètres d'engagement.</p></div>""",

    "medias-numeriques/desinformation": """<h3>Contre-mesures et résilience informationnelle</h3><p class="resume-text">Face à la désinformation systémique, des stratégies de défense émergent à plusieurs niveaux. La <strong>prébunking</strong> (inoculation) est une technique prouvée : exposer les gens à des versions affaiblies de manipulations avant qu'ils les rencontrent les rend plus résistants (comme un vaccin). L'application Bad News (jeu en ligne créé par l'Université de Cambridge, 1,5 million de participants) simule le rôle de producteur de désinformation pour développer la capacité critique des utilisateurs. En Finlande, une éducation aux médias systématique à l'école (Media Literacy) depuis 2016 a rendu le pays le plus résilient à la désinformation en Europe selon les études EUDisinfoLab.</p><p class="resume-text">La <strong>modération de contenu</strong> à l'échelle industrielle est une réalité peu connue du grand public. Meta emploie 40 000 modérateurs de contenus (principalement externalisés en Inde, aux Philippines et au Kenya), exposés quotidiennement à des contenus traumatisants. Des procès intentés par d'anciens modérateurs (règlement de 52 millions de dollars par Meta en 2020) ont mis en lumière les conditions de travail de ces « travailleurs de l'ombre » du web. L'IA générative rend cette modération encore plus difficile : 500 000 fausses images peuvent être produites en une journée.</p><div class="highlight-box"><p>La Finlande, qui a intégré l'éducation aux médias dans tous les cursus scolaires depuis 2016, est classée premier pays d'Europe pour la résistance à la désinformation — un modèle étudié par l'UNESCO.</p></div>""",

    "medias-numeriques/culture-numerique": """<h3>L'économie de l'attention et les créateurs</h3><p class="resume-text">L'<strong>économie de l'attention</strong> (Herbert Simon, 1971 ; Herbert A. Simon a théorisé dès 1971 que dans un monde d'information abondante, c'est l'attention humaine qui devient la ressource rare) structure la compétition entre les plateformes numériques. Chaque application se bat pour capter des minutes de vie humaine. Tristan Harris, ancien designer de Google et fondateur du Center for Humane Technology, a révélé les techniques de « captologie » (science de la persuasion informatique) : notifications variables, likes, streaks (séries), scrolling infini, toutes héritées de la conception des machines à sous de Las Vegas.</p><p class="resume-text">L'<strong>économie des créateurs</strong> (creator economy) représente plus de 250 milliards de dollars en 2024 et implique 200 millions de créateurs de contenu dans le monde. Des plateformes comme YouTube (partage des revenus publicitaires depuis 2007), Twitch (abonnements et donations), OnlyFans (contenus exclusifs), Patreon (abonnements) et Substack (newsletters payantes) permettent à des individus de vivre de leur audience. Cette désintermédiation remet en cause les modèles traditionnels du divertissement, du journalisme et de l'éducation, créant de nouvelles formes de célébrité et d'influence indépendantes des médias traditionnels.</p><div class="highlight-box"><p>L'économie des créateurs pèse 250 milliards de dollars en 2024 : MrBeast (YouTube, 300 millions d'abonnés) génère plus de revenus que la plupart des chaînes de télévision nationales.</p></div>""",

    "publicite/histoire-publicite": """<h3>La révolution publicitaire numérique</h3><p class="resume-text">La publicité programmatique a révolutionné l'industrie publicitaire depuis les années 2010. Le <strong>Real-Time Bidding</strong> (RTB) est une enchère automatique qui se déroule en 100 millisecondes à chaque chargement de page web : des centaines d'annonceurs misent simultanément pour afficher leur publicité à un utilisateur spécifique, dont le profil (age, sexe, localisation, centres d'intérêt, historique d'achats) a été modélisé par les data brokers. Google (via DV360) et Meta dominent ce marché : en 2023, la publicité numérique représente 65 % des dépenses mondiales (741 milliards de dollars sur 1 140 milliards total).</p><p class="resume-text">La <strong>fin des cookies tiers</strong>, annoncée par Google (repoussée à 2025), représente un bouleversement majeur pour l'industrie. Ces traceurs permettaient de suivre les internautes sur des milliers de sites ; leur disparition oblige le secteur à développer des alternatives (Privacy Sandbox de Google, contextual advertising, first-party data). Le RGPD européen (2018) a déjà transformé le paysage : les consentements obligatoires ont réduit de 40 % les données disponibles pour le ciblage en Europe. L'<strong>advertising cookieless</strong> pousse les marques à investir dans des données propriétaires et des médias de confiance.</p><div class="highlight-box"><p>En 100 millisecondes (temps d'un clignement d'œil), le Real-Time Bidding fait s'affronter des centaines d'annonceurs pour chaque publicité affichée — un marché de 300 milliards de dollars annuels entièrement automatisé.</p></div>""",

    "publicite/comportement-consommateur": """<h3>Neuromarketing et décision d'achat</h3><p class="resume-text">Le <strong>neuromarketing</strong>, né au début des années 2000, utilise les neurosciences (IRM fonctionnelle, EEG, eye-tracking, galvanomètre cutané) pour mesurer les réactions cérébrales et physiologiques des consommateurs face aux publicités, packagings et expériences de marque. Les travaux de Damasio sur les émotions dans la prise de décision ont révélé que les décisions d'achat sont largement inconscientes et émotionnelles : les scanners cérébraux montrent qu'une marque puissante comme Apple active les mêmes zones du cerveau que les symboles religieux chez ses fans.</p><p class="resume-text">Les <strong>biais cognitifs</strong>, catalogués par Kahneman et Tversky (prix Nobel 2002 pour Kahneman), sont systématiquement exploités par le marketing. L'ancrage (un prix barré sert de référence même arbitraire), la rareté artificielle (« plus que 3 en stock ! »), la preuve sociale (« 10 000 clients satisfaits »), la réciprocité (l'échantillon gratuit crée une obligation de retour), l'aversion à la perte (« vous perdrez si vous n'achetez pas »). Ces biais, documentés en laboratoire, sont la grammaire invisible de toute interface commerciale numérique.</p><div class="highlight-box"><p>Les IRM fonctionnelles utilisées en neuromarketing montrent que la marque Apple active les mêmes zones du cerveau que les symboles religieux chez ses utilisateurs les plus fidèles — révélant l'appartenance tribale derrière l'acte d'achat.</p></div>""",

    "publicite/marketing-digital": """<h3>L'ère du marketing d'influence et de l'IA</h3><p class="resume-text">Le <strong>marketing d'influence</strong> est devenu un secteur de 24 milliards de dollars en 2024, avec des nano-influenceurs (1 000-10 000 abonnés, taux d'engagement 8-10 %) souvent plus efficaces que les méga-influenceurs (millions d'abonnés, taux d'engagement < 1 %). Les marques B2C allouent en moyenne 20 % de leur budget marketing aux influenceurs. La réglementation s'est durcie : depuis 2023, en France, l'ARPP et la DGCCRF imposent la mention #Pub ou #Partenariat commercial pour tout contenu sponsorisé, sous peine d'amendes.</p><p class="resume-text">L'<strong>IA générative</strong> révolutionne le marketing digital. Des outils comme Midjourney, DALL-E et Stable Diffusion permettent de créer en minutes des visuels publicitaires personnalisés pour chaque segment de clientèle. Les A/B tests automatisés génèrent et testent des milliers de variantes d'une publicité. Les chatbots de marque (powered by GPT-4) offrent un service client 24/7 personnalisé. L'IA réduit les coûts de création de 60 à 80 %, mais soulève des questions sur la créativité, l'emploi des créatifs et l'authenticité des communications de marque.</p><div class="highlight-box"><p>L'IA générative a réduit de 70 % le temps de production de contenus publicitaires en 2024 — Coca-Cola a créé une publicité télévisée entièrement générée par IA pour Noël 2023, suscitant autant d'enthousiasme que de controverses.</p></div>""",

    "publicite/branding-identite": """<h3>Le branding à l'ère de l'authenticité et de la purpose</h3><p class="resume-text">Le concept de <strong>brand purpose</strong> (raison d'être de la marque) s'est imposé comme stratégie différenciante depuis les années 2010. La campagne « Real Beauty » de Dove (2004), qui utilisait des vraies femmes non retouchées, avait lancé la tendance du « purpose marketing ». Patagonia, qui reverse 1 % de son chiffre d'affaires à des causes environnementales depuis 1986 et qui a cédé sa propriété à des fondations environnementales en 2022 (décision de Yvon Chouinard), est l'exemple extrême d'une marque dont l'identité est indissociable de ses valeurs. Ces stratégies attirent les consommateurs soucieux d'éthique mais exposent les marques au « greenwashing » si leurs actes ne correspondent pas à leurs discours.</p><p class="resume-text">Les <strong>crises de réputation</strong> à l'ère des réseaux sociaux peuvent détruire des décennies de branding en quelques heures. Le concept de « cancel culture » désigne la mobilisation collective pour boycotter une marque, une personnalité ou une entreprise après une conduite jugée inacceptable. Les crises de H&M (publicité accusée de racisme, 2018), de Gillette (publicité sur la masculinité toxique, 2019) ou de Bud Light (partenariat avec une influenceuse trans, 2023) illustrent la complexité du branding dans un environnement polarisé. La communication de crise préventive et la « social listening » (veille des conversations sur les réseaux) sont devenus des fonctions stratégiques.</p><div class="highlight-box"><p>En 2022, Yvon Chouinard a donné Patagonia (3 milliards de dollars) à une fondation environnementale, déclarant « La Terre est notre seul actionnaire » — un cas extrême de brand purpose qui a généré 4 milliards de retombées médiatiques gratuites.</p></div>""",

    "publicite/ethique-publicitaire": """<h3>Vers une publicité responsable</h3><p class="resume-text">La <strong>publicité responsable</strong> est devenue un enjeu commercial autant qu'éthique. La prise de conscience des effets environnementaux de la publicité (incitation à la surconsommation, greenwashing) nourrit un mouvement de « décroissance publicitaire » : la ville de Grenoble a interdit la publicité dans l'espace public en 2014 ; São Paulo l'avait fait dès 2007 (« Clean City Law »). En France, la loi Climat et résilience (2021) interdit la publicité pour les énergies fossiles et prévoit une charte des bonnes pratiques pour réduire le greenwashing.</p><p class="resume-text">La protection des <strong>consommateurs vulnérables</strong>, notamment les enfants et adolescents, est au cœur des régulations publicitaires contemporaines. Le DSA européen interdit le ciblage publicitaire des mineurs basé sur des données personnelles. L'Advertising Standards Authority britannique a interdit les publicités qui perpétuent des stéréotypes de genre nuisibles (2019). La loi française de 2023 sur l'influence commerciale crée un cadre légal pour les influenceurs, interdisant la promotion de chirurgie esthétique, de jeux d'argent et de produits financiers risqués aux moins de 18 ans.</p><div class="highlight-box"><p>São Paulo (11 millions d'habitants) a adopté en 2007 la « Lei Cidade Limpa » qui a retiré 15 000 panneaux publicitaires de la ville — et 70 % des habitants ont soutenu cette mesure dans les sondages qui ont suivi.</p></div>""",

    "relations-publiques/fondements-rp": """<h3>Les relations publiques à l'ère des réseaux sociaux</h3><p class="resume-text">Les réseaux sociaux ont profondément transformé la pratique des relations publiques. Le modèle traditionnel (communiqué de presse → journaliste → publication) est concurrencé par la communication directe des marques vers leurs audiences via leurs propres canaux (owned media). Le « <strong>brand journalism</strong> » désigne cette pratique par laquelle les entreprises produisent des contenus éditoriaux de qualité (Red Bull Media House, Michelin Guide) pour attirer une audience fidèle sans passer par les médias traditionnels.</p><p class="resume-text">La <strong>veille e-réputation</strong> (social listening) est devenue une fonction stratégique en relations publiques. Des outils comme Brandwatch, Talkwalker ou Mention analysent en temps réel des millions de mentions sur les réseaux sociaux, permettant de détecter une crise naissante avant qu'elle s'emballe. La règle des « 7 R » de la communication numérique (Répondre, Rectifier, Reconnaître, Reformuler, Rassurer, Remercier, Respecter) guide les pratiques de gestion de crise en ligne. La transparence radicale — reconnaître rapidement les erreurs plutôt que les minimiser — est devenue la stratégie de communication de crise la plus efficace à l'ère des réseaux sociaux.</p><div class="highlight-box"><p>Red Bull Media House produit du contenu pour 600 millions d'abonnés sur ses propres canaux (YouTube, magazines, podcasts) — un empire médiatique qui surpasse de nombreux groupes de presse traditionnels.</p></div>""",

    "relations-publiques/communication-crise": """<h3>Anatomie d'une crise et gestion de l'information</h3><p class="resume-text">La <strong>gestion de crise</strong> à l'ère des réseaux sociaux obéit à une temporalité radicalement accélérée. La « golden hour » des RP de crise — la première heure décisive pour maîtriser le récit — est devenue la « golden minute » : les vidéos virales peuvent atteindre 10 millions de vues en deux heures, avant toute communication officielle. L'affaire United Airlines (2017, passager expulsé de force filmé) a montré comment une vidéo de 31 secondes peut effacer en quelques heures des milliards de capitalisation boursière et forcer le changement de politique d'une entreprise.</p><p class="resume-text">La <strong>communication en situation d'urgence</strong> (natural disaster communication, crise sanitaire) suit des protocoles spécifiques. La gestion communicationnelle du Covid-19 par différents pays a illustré les effets de la communication de crise sur l'adhésion du public aux mesures sanitaires. La clarté des messages, la cohérence des porte-paroles, la transparence sur l'incertitude (reconnaître ce qu'on ne sait pas) et la communication ciblée selon les publics sont les piliers de la communication de crise institutionnelle efficace, documentés par les études de l'OMS et des Centres de contrôle des maladies (CDC).</p><div class="highlight-box"><p>La vidéo du passager expulsé d'un vol United Airlines (2017) a atteint 100 millions de vues en 48h et coûté 1,4 milliard de dollars en capitalisation boursière — l'exemple emblématique de crise virale à l'ère des smartphones.</p></div>""",

    "relations-publiques/relations-presse": """<h3>Relations presse et nouveaux médias</h3><p class="resume-text">Le paysage médiatique fragmenté oblige les professionnels des relations presse à diversifier leurs cibles. Aux journalistes des médias traditionnels s'ajoutent les <strong>journalistes de pure players</strong> (Médiapart, BFM TV), les podcasteurs (200 millions de podcasts actifs dans le monde), les YouTubeurs et influenceurs spécialisés, les newsletters à forte audience (Morning Brew, 4 millions d'abonnés) et les expert-auteurs de LinkedIn (LinkedIn Newsletters). Chaque format a ses codes, ses délais et ses angles spécifiques : un communiqué de presse standard est inadapté à une newsletter spécialisée ou à un compte TikTok éducatif.</p><p class="resume-text">La <strong>mesure des retombées presse</strong> a évolué des simples équivalents publicitaires (EAP, critiqués pour leur manque de pertinence) vers des indicateurs plus qualitatifs : tonalité de la couverture (positive/négative/neutre), messages clés repris, portée réelle vs portée théorique, engagement généré (partages, commentaires), impact sur la réputation mesuré par enquêtes de notoriété. Les outils d'intelligence artificielle (Kantar, Meltwater, Onclusive) permettent désormais une analyse sémantique automatique de la tonalité de l'intégralité de la couverture médiatique d'une entreprise en temps réel.</p><div class="highlight-box"><p>Morning Brew, newsletter américaine fondée par deux étudiants en 2015, compte 4 millions d'abonnés et a été rachetée 75 millions de dollars — illustrant l'émergence des newsletters comme médias à part entière.</p></div>""",

    "relations-publiques/communication-interne": """<h3>Communication interne et transformation des organisations</h3><p class="resume-text">La communication interne a gagné un statut stratégique à l'heure du travail hybride et de la guerre des talents. La <strong>pandémie</strong> a constitué un test grandeur nature : les entreprises capables de maintenir engagement et sens du collectif à distance ont démontré une communication interne plus sophistiquée. Les outils collaboratifs (Slack, Microsoft Teams, Notion) ont transformé les pratiques de communication interne, mais ont aussi généré une « infobésité » numérique : les cadres américains consacrent en moyenne 4 heures par jour à leurs emails professionnels.</p><p class="resume-text">Le concept d'<strong>employer branding</strong> (marque employeur) positionne l'entreprise comme une marque à destination des candidats et employés potentiels. La réputation employeur, mesurée par des plateformes comme Glassdoor (2 millions d'avis d'employés), est devenue un facteur déterminant de recrutement pour les talents. Les « Chief People Officers » et « Head of Employee Experience » incarnent cette montée en puissance de l'expérience collaborateur. Les scandales RH (Uber, WeWork, Twitter/X post-acquisition Musk) illustrent à quel point la communication interne défaillante se transforme rapidement en crise externe de réputation.</p><div class="highlight-box"><p>Glassdoor, avec plus de 100 millions d'avis sur 2 millions d'entreprises, a renversé le rapport de force employeur/employé : 84 % des candidats consultent les avis avant un entretien.</p></div>""",

    "relations-publiques/communication-politique": """<h3>La communication politique à l'ère des réseaux sociaux</h3><p class="resume-text">La campagne d'Obama en 2008 avait inauguré l'ère du digital politique (1 million de followers Twitter, 2 millions de donateurs en ligne). La campagne Trump en 2016, avec Cambridge Analytica et le micro-ciblage Facebook, a marqué une rupture plus profonde : la personnalisation radicale des messages politiques selon les profils psychologiques. En 2024, la <strong>désinformation politique générée par l'IA</strong> (deepfakes de candidats, fausses citations, clones vocaux) est devenue une menace systémique : 50 pays ont organisé des élections nationales et 30 ont été touchés par des campagnes de désinformation documentées.</p><p class="resume-text">La <strong>communication de rupture</strong> — qui transgresse les codes habituels pour créer un effet de surprise — est devenue un avantage compétitif en politique. Emmanuel Macron (interviews YouTube avec des créateurs, débats Facebook live), Volodymyr Zelensky (communication directe en treillis depuis Kyiv face aux caméras de smartphones), ou Javier Milei (TikTok en Argentine) illustrent cette adaptation des leaders politiques aux codes des plateformes numériques. La communication politique contemporaine nécessite de maîtriser simultanément le discours, l'image, le format court (TikTok, Reels), la réactivité en temps réel et la gestion des crises numériques.</p><div class="highlight-box"><p>La communication de Zelensky depuis le début de l'invasion russe est étudiée dans les écoles de communication du monde entier : selfies vidéo nocturnes, format parlant directement à la caméra, cohérence des messages — un master class de communication de crise.</p></div>""",
}


def enrich_content(content: str, extra_html: str) -> str:
    quiz_pattern = r'(<section class="content-section" id="quiz">)'
    match = re.search(quiz_pattern, content)
    if match:
        insert_pos = match.start()
        return content[:insert_pos] + '\n' + extra_html + '\n' + content[insert_pos:]
    else:
        last_section = content.rfind('</section>')
        if last_section >= 0:
            return content[:last_section] + extra_html + '\n' + content[last_section:]
    return content


def main():
    filepath = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json'

    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for key, enrichment in ENRICHMENTS.items():
        if key in data['pages']:
            page = data['pages'][key]
            if page.get('type') == 'course':
                original_len = len(page['content'])
                page['content'] = enrich_content(page['content'], enrichment)
                new_len = len(page['content'])
                print(f"  {key}: {original_len} -> {new_len} chars (+{new_len - original_len})")
                enriched_count += 1
        else:
            print(f"  WARNING: key not found: {key}")

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nEnriched {enriched_count} articles in communication.json")

    # Final summary
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    sizes = [len(p['content']) for p in data['pages'].values() if p.get('type') == 'course']
    print(f"Final stats: min={min(sizes)}, max={max(sizes)}, avg={sum(sizes)//len(sizes)}")


if __name__ == '__main__':
    main()
