#!/usr/bin/env python3
"""Enrichissement des articles histoire-art — ajout d'une section h3 supplémentaire dans #contenu."""
import json, re, sys, os

sys.stdout.reconfigure(encoding='utf-8')
BASE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content'

# ── Contenus d'enrichissement ────────────────────────────────────────────────
# Chaque entrée : clé JSON → HTML à insérer AVANT </section> du bloc #contenu
# (juste avant la balise fermante du dernier div/section du contenu)

ENRICHMENTS = {

"art-prehistorique/art-egyptien": """<h3>L'écriture hiéroglyphique comme art total</h3><p class="resume-text">En Égypte ancienne, l'écriture et l'art étaient indissociables. Les hiéroglyphes — du grec « écriture sacrée » — sont eux-mêmes des œuvres figuratives : chaque signe représente un être ou un objet du monde réel. Gravés dans la pierre ou tracés au calame sur le papyrus, ils ornent les temples et les tombes de compositions savamment agencées, où texte et image se complètent pour former un tout sémantique.</p><p class="resume-text">Le <em>Canon de Turin</em>, le <em>Livre des Morts</em> et les <em>Textes des Pyramides</em> illustrent la richesse de cette tradition scribale. Les scribes étaient parmi les artisans les plus respectés : formés dans des maisons de vie (<em>per-ankh</em>), ils maîtrisaient les trois écritures — hiéroglyphique, hiératique et démotique — et savaient composer textes et vignettes en un équilibre visuel harmonieux.</p><div class="highlight-box"><p>La pierre de Rosette (196 av. J.-C.), gravée en trois écritures, a permis à Champollion de déchiffrer les hiéroglyphes en 1822, ouvrant l'Égypte antique à la recherche moderne.</p></div>""",

"art-prehistorique/art-mesopotamien": """<h3>L'art de la glyptique et des arts du métal</h3><p class="resume-text">Au-delà des monuments colossaux, la Mésopotamie a excellé dans les arts mineurs d'une sophistication remarquable. La métallurgie de l'or et du bronze a produit des chefs-d'œuvre comme la lyre d'Ur, dont la caisse est ornée d'une tête de taureau en or et lapis-lazuli. Ces instruments funéraires témoignent d'une conception de l'au-delà où la musique joue un rôle central.</p><p class="resume-text">La céramique peinte, dès le Ve millénaire, développe un répertoire de motifs géométriques et animaliers qui annoncent l'iconographie classique mésopotamienne. La poterie d'Obeid, avec ses figures d'animaux stylisés, précède et prépare le développement de la sculpture monumentale sumérienne.</p><p class="resume-text">L'art mésopotamien trouve aussi sa pleine expression dans les tablettes d'argile illustrées. L'Épopée de Gilgamesh, le plus ancien texte littéraire connu, est ainsi transmis sur des tablettes cunéiformes ornées de colophons et de vignettes, unissant la tradition scribal et la création visuelle dans un même objet culturel.</p><div class="highlight-box"><p>La lyre d'Ur, datant de 2600 av. J.-C. environ et conservée au musée de l'Université de Pennsylvanie, est l'un des plus anciens instruments de musique décorés jamais découverts.</p></div>""",

"art-prehistorique/art-grec": """<h3>La céramique et les arts décoratifs grecs</h3><p class="resume-text">La céramique grecque constitue l'un des domaines les mieux documentés de l'art antique. Les ateliers attiques ont produit des vases aux formes codifiées — amphore, cratère, hydrie, lécythe — dont les décors peints constituent une véritable chronique de la mythologie et de la vie quotidienne. La transition de la figure noire (VIIe-VIe siècle) à la figure rouge (à partir de 530 av. J.-C.) marque une révolution technique permettant un rendu plus détaillé de l'anatomie.</p><p class="resume-text">Le style géométrique (IXe-VIIIe siècle), le style orientalisant (VIIe siècle), puis les périodes archaïque, classique et hellénistique jalonnent une évolution constante vers une plus grande liberté expressive. Les peintres de vases sont parfois connus par leur nom — Exékias, Euphronios, le Peintre de Berlin — et leurs œuvres font l'objet d'attributions savantes depuis le XIXe siècle.</p><p class="resume-text">L'orfèvrerie grecque, les bronzes votifs et les terres cuites de Tanagra complètent ce panorama d'un artisanat d'art au niveau technique exceptionnel, exporté dans toute la Méditerranée antique grâce aux réseaux commerciaux grecs.</p><div class="highlight-box"><p>Le vase François (570 av. J.-C.), conservé à Florence, représente plus de 200 figures mythologiques sur une hauteur de 66 cm — un sommet du récit visuel dans la céramique antique.</p></div>""",

"art-prehistorique/art-romain": """<h3>Le portrait et le récit triomphal</h3><p class="resume-text">Rome a porté l'art du portrait à un sommet inédit dans l'Antiquité. Le portrait républicain, dit <em>veriste</em>, ne cherchait pas à idéaliser le modèle mais à en restituer fidèlement les traits, y compris les rides et les imperfections, signe de l'<em>auctoritas</em> acquise par l'expérience. Les portraits en cire des ancêtres (<em>imagines maiorum</em>), portés lors des funérailles aristocratiques, témoignent de cette tradition du souvenir littéral.</p><p class="resume-text">Avec l'Empire, le portrait devient instrument de propagande. Auguste inaugure le type du prince juvénile et idéalisé, figé dans la force de l'âge pour mieux symboliser la pérennité du régime. Sous Hadrien, les empereurs adoptent la barbe grecque et un regard tourné vers l'idéal philosophique. Avec les soldats-empereurs du IIIe siècle, le réalisme reprend ses droits, traduisant la crise et la brutalité du temps.</p><p class="resume-text">La colonne Trajane, inaugurée en 113 apr. J.-C. et haute de 30 mètres, représente en spirale continue les deux campagnes de Dacie. Avec plus de 2 500 figures en bas-relief, elle constitue un document historique et artistique sans équivalent, ancêtre des bandes dessinées narratives.</p><div class="highlight-box"><p>La colonne Trajane déploie une frise narrative de 190 mètres de long qui représente environ 155 scènes avec 2 500 figures — la plus grande bande dessinée de l'Antiquité.</p></div>""",

"art-prehistorique/lascaux": """<h3>Techniques et interprétations de l'art pariétal</h3><p class="resume-text">Les artistes de Lascaux et de ses contemporains maîtrisaient une palette technique remarquable. Les pigments utilisés — ocres jaunes et rouges à base d'oxyde de fer, noirs au manganèse ou au charbon de bois — étaient broyés, mélangés à des liants organiques (graisse animale, sève végétale) et appliqués au doigt, à la brosse végétale ou soufflés à travers des os creux. Cette technique de soufflage permet des effets de dégradé d'une finesse surprenante.</p><p class="resume-text">La datation des peintures pariétales a considérablement progressé grâce à la technique du carbone 14, puis à la méthode uranium-thorium. Lascaux est daté d'environ 17 000 ans, mais d'autres sites sont plus anciens encore : Chauvet remonte à 36 000 ans, et les cupules de Blombos Cave en Afrique du Sud à 75 000 ans, repoussant les origines de l'expression symbolique humaine.</p><p class="resume-text">L'interprétation de ces œuvres demeure un champ de débat intense. Les théories principales incluent la magie de chasse (Breuil), le chamanisme et les états altérés de conscience (Clottes, Lewis-Williams), la transmission de connaissances écologiques, et l'hypothèse d'un art pour l'art. Aucune théorie ne fait consensus, ce qui témoigne de la complexité de la pensée symbolique des Homo sapiens du Paléolithique.</p><div class="highlight-box"><p>La grotte de Chauvet, découverte en 1994, contient les peintures pariétales datées les plus anciennes connues (environ 36 000 ans) et révèle des techniques aussi sophistiquées que celles de Lascaux.</p></div>""",

"art-medieval/art-byzantin": """<h3>Les arts de cour et le luxe byzantin</h3><p class="resume-text">Au-delà des monuments religieux, Byzance excella dans les arts de cour d'un raffinement extrême. L'ivoire sculpté byzantin, notamment les diptyques consulaires et les boîtes à reliques, atteint une densité iconographique exceptionnelle. Les émaux cloisonnés (technique <em>champlevé</em> et <em>cloisonné</em>), développés à Constantinople, servirent à orner les reliquaires, les couronnes et les reliures d'évangéliaires envoyés dans toute la chrétienté comme cadeaux diplomatiques.</p><p class="resume-text">Les textiles byzantins, tissés de soie et d'or, étaient parmi les biens de luxe les plus prisés du Moyen Âge. Les ateliers impériaux de Constantinople produisaient des soieries aux motifs d'animaux affrontés hérités des traditions sassanides, diffusées dans tout le monde médiéval par les routes commerciales. La soie de pourpre — couleur réservée à l'empereur — était synonyme de pouvoir absolu.</p><p class="resume-text">Les manuscrits enluminés byzantins, dont les plus beaux exemples sont conservés à la Bibliothèque nationale de Paris et à la Bibliothèque du Vatican, allient la tradition du texte sacré à la peinture miniature la plus raffinée. Le <em>Ménologe de Basile II</em> (vers 1000) contient 430 miniatures d'une qualité incomparable.</p><div class="highlight-box"><p>Les émaux byzantins de la Pala d'Oro à Venise, assemblés entre le Xe et le XIVe siècle, constituent l'un des ensembles les plus précieux de l'orfèvrerie médiévale mondiale.</p></div>""",

"art-medieval/art-gothique": """<h3>La lumière comme théologie : vitraux et mystique gothique</h3><p class="resume-text">L'architecture gothique est indissociable d'une théologie de la lumière développée par l'abbé Suger de Saint-Denis au XIIe siècle. S'inspirant du néo-platonisme pseudo-dionysien, Suger voyait dans la lumière filtrée par les vitraux colorés une manifestation de la lumière divine — la <em>lux nova</em> — capable d'élever l'âme vers Dieu. Cette conviction théologique a directement motivé les innovations structurelles permettant d'agrandir les fenêtres.</p><p class="resume-text">La statuaire gothique connaît une évolution remarquable du XIIe au XIVe siècle. Les personnages, d'abord rigides et frontaux comme à Chartres, gagnent progressivement en naturalisme et en expressivité. Les portails sculptés des cathédrales constituent de véritables encyclopédies imagées de la théologie chrétienne, accessibles à une population en grande partie analphabète.</p><p class="resume-text">La peinture gothique, au-delà des vitraux, se développe dans les manuscrits enluminés. L'atelier parisien du Maître Honoré, puis celui de Jean Pucelle au début du XIVe siècle, introduisent des innovations comme la modélisation des volumes par la grisaille et l'influence italienne, préfigurant le réalisme de la peinture flamande du siècle suivant.</p><div class="highlight-box"><p>La Sainte-Chapelle de Paris (1248), avec ses 1 113 m² de vitraux représentant plus de 1 000 scènes bibliques, est l'exemple le plus accompli du programme lumineux gothique.</p></div>""",

"art-medieval/art-roman": """<h3>Sculpture romane et symbolisme animal</h3><p class="resume-text">L'art roman s'est imposé comme le premier style international de l'art européen, unifiant sous une même esthétique les régions d'Europe occidentale reliées par les routes de pèlerinage. Saint-Jacques-de-Compostelle, Rome, Jérusalem et les tombes de saints locaux drainaient des milliers de pèlerins, stimulant la construction d'églises-haltes et la commande d'œuvres d'art destinées à instruire et à impressionner.</p><p class="resume-text">Le bestiaire roman, cet étrange peuple de monstres et d'animaux fantastiques qui peuple les chapiteaux et les tympans, est souvent mal compris. Ces créatures hybrides — chimères, dragons, sirènes, satyres — ne sont pas de simples décorations mais un langage symbolique complexe, héritier de la tradition morale du <em>Physiologus</em> grec. Le lion symbolise le Christ ou la résurrection, le basilic le diable, l'aigle saint Jean l'Évangéliste.</p><p class="resume-text">Les grands chantiers romans ont également développé la peinture murale. Les fresques de Saint-Savin-sur-Gartempe, de Sant Climent de Taüll en Catalogne ou de Berzé-la-Ville en Bourgogne témoignent d'une tradition picturale monumentale d'une grande qualité, parallèle aux miniatures des scriptoria.</p><div class="highlight-box"><p>La tapisserie de Bayeux (vers 1077), longue de 70 mètres, est un chef-d'œuvre de la broderie médiévale qui raconte la conquête normande de l'Angleterre en 58 scènes.</p></div>""",

"art-medieval/manuscrits-enlumines": """<h3>Les grands foyers d'enluminure et leur influence</h3><p class="resume-text">L'enluminure médiévale présente une grande diversité régionale selon les foyers de production. L'Irlande et l'Angleterre insulaire (VIIe-IXe siècles) développèrent un style ornamental unique, caractérisé par des entrelacs zoomorphes d'une complexité vertigineuse. Le Livre de Kells (vers 800), produit dans un monastère irlandais ou écossais, est le sommet de cette tradition : ses pages de tapis et ses initiales historiées défient la compréhension par leur densité iconographique.</p><p class="resume-text">La France capétienne du XIIIe siècle constitue un autre foyer majeur, avec les ateliers parisiens qui produisent des psautiers et des livres d'heures destinés à la haute aristocratie. Le Psautier de Saint Louis, commandé pour le roi vers 1260, allie l'architecture gothique de ses encadrements architecturés à une peinture aux couleurs vives et aux personnages expressifs.</p><p class="resume-text">Les Très Riches Heures du duc de Berry (début XVe siècle), enluminées par les frères Limbourg, marquent le sommet de l'art de la miniature et annoncent la peinture de la Renaissance flamande. Leurs scènes de calendrier représentant les travaux des mois constituent un document irremplaçable sur la vie quotidienne et l'art du paysage médiéval.</p><div class="highlight-box"><p>Le Livre de Kells (vers 800) a été voté « le plus beau livre du monde » par le magazine Time en 1999. Il compte parmi les trésors de la Bibliothèque du Trinity College de Dublin.</p></div>""",

"art-medieval/vitraux": """<h3>Les grandes compositions narratives : de Chartres à la Sainte-Chapelle</h3><p class="resume-text">Les verrières de Chartres (XIIe-XIIIe siècles) constituent un ensemble exceptionnel de 176 fenêtres représentant plus de 4 000 personnages. Organisées selon un programme iconographique cohérent, elles parcourent l'histoire sainte de la Genèse à l'Apocalypse, en intégrant les vies de saints et les portraits des donateurs laïcs — guildes de marchands, nobles et membres du clergé — à des emplacements précis selon leur rang.</p><p class="resume-text">La technique du vitrail a évolué considérablement au fil des siècles. Le verre grisaille, utilisé dans les monastères cisterciens en réaction à la richesse ornementale de Clairvaux, crée des effets de transparence sobre. La peinture sur verre à l'aide de la grisaille (oxyde de fer et de manganèse) permet dès le XIIIe siècle des dégradés et des carnations plus réalistes. L'invention du verre doublé au XIVe siècle enrichit encore la palette des verriers.</p><p class="resume-text">Les arts du vitrail ont connu un renouveau remarquable au XIXe siècle avec le mouvement néogothique, et au XXe siècle grâce à des artistes comme Marc Chagall (cathédrale de Reims, synagogue de Jérusalem) ou Henri Matisse (chapelle du Rosaire à Vence), qui ont réinterprété ce médium dans un esprit résolument moderne.</p><div class="highlight-box"><p>La rose nord de la cathédrale Notre-Dame de Paris (1250) mesure 13 mètres de diamètre et représente les prophètes de l'Ancien Testament autour de la Vierge — un chef-d'œuvre de la composition rayonnante gothique.</p></div>""",

"renaissance/leonard-de-vinci": """<h3>L'inventeur et l'ingénieur : l'art au service de la science</h3><p class="resume-text">Léonard de Vinci est l'archétype de l'<em>uomo universale</em> de la Renaissance. Ses carnets — dont on conserve environ 7 000 pages dispersées dans plusieurs bibliothèques d'Europe — révèlent un esprit qui ne dissociait jamais l'observation du dessin. L'anatomie, l'hydraulique, l'aéronautique, l'optique, la géologie : chaque domaine est abordé avec la même rigueur graphique et la même insatiable curiosité.</p><p class="resume-text">Ses études anatomiques, réalisées sur des cadavres humains à une époque où cette pratique était risquée, ont produit les représentations les plus précises du corps humain de la Renaissance. Ses dessins du fœtus in utero, des muscles du bras ou du cœur anticipent les planches d'anatomie des siècles suivants. Cette connaissance intime du corps humain nourrit directement sa peinture, conférant à ses personnages un naturel du mouvement et une vérité expressive inégalés.</p><p class="resume-text">Ses projets d'ingénierie — machine volante, tank, pont rotatif, ville idéale — témoignent d'une imagination projective sans équivalent. Bien que peu de ces inventions aient été réalisées de son vivant, plusieurs ont été construites à titre expérimental au XXe siècle et se sont révélées fonctionnelles, prouvant la validité de ses intuitions.</p><div class="highlight-box"><p>Les carnets de Léonard sont écrits en écriture spéculaire de droite à gauche, probablement pour protéger ses idées et parce qu'il était gaucher. Le Codex Leicester, acheté par Bill Gates en 1994 pour 30,8 millions de dollars, est le plus célèbre de ces carnets.</p></div>""",

"renaissance/michel-ange": """<h3>Poète, architecte et théologien de la matière</h3><p class="resume-text">Michel-Ange est souvent réduit à ses chefs-d'œuvre sculptés et peints, mais il fut aussi un architecte majeur et un poète de premier rang. Son travail sur la place du Capitole à Rome, la basilique Saint-Pierre (dont il prend la direction à 71 ans) et la Bibliothèque Laurentienne de Florence a profondément marqué l'architecture de la Renaissance tardive et du Maniérisme. Son escalier de la Bibliothèque Laurentienne, avec ses marches lobées « en forme de vagues », anticipe les libertés formelles du Baroque.</p><p class="resume-text">Sa conception de la sculpture comme libération de la forme emprisonnée dans le marbre — le fameux concept de <em>non-finito</em> — est l'une des idées les plus originales de l'histoire de l'art. Ses esclaves (1513-1516, Louvre) semblent littéralement se dégager de la pierre, mi-libérés mi-prisonniers, dans une tension dramatique qui préfigure l'expressionnisme moderne. Michel-Ange voyait dans l'acte sculptural un processus spirituel d'extraction de la forme idéale préexistante.</p><p class="resume-text">Ses 302 poèmes, longtemps négligés, révèlent un esprit torturé par le conflit entre la beauté charnelle et la piété néoplatonicienne. Ses sonnets adressés à Tommaso de' Cavalieri et à Vittoria Colonna sont parmi les plus beaux de la littérature italienne de la Renaissance, unissant le désir, la mort et la grâce divine dans une langue d'une intensité exceptionnelle.</p><div class="highlight-box"><p>Michel-Ange a peint seul le plafond de la Sixtine — soit 500 m² de fresques avec plus de 300 figures — en à peine quatre ans (1508-1512), refusant toute aide de ses assistants pour les figures principales.</p></div>""",

"renaissance/raphael": """<h3>L'organisation du travail et l'héritage de Raphaël</h3><p class="resume-text">Raphaël fut le premier peintre de la Renaissance à organiser sa production selon un modèle quasi-industriel. Ses ateliers romains, à l'apogée de sa carrière, employaient des dizaines d'élèves et assistants. Raphaël concevait les compositions, dessinait les cartons (dessins préparatoires grandeur nature) et laissait ses collaborateurs — Giovanni da Udine, Giulio Romano, Gianfrancesco Penni — réaliser une grande partie des peintures murales. Cette méthode a influencé tous les grands ateliers des siècles suivants.</p><p class="resume-text">Son œuvre de tapisseries, commandée par Léon X pour la Chapelle Sixtine, illustre les Actes des Apôtres et constitue l'un des ensembles les plus influents de toute l'histoire de l'art décoratif européen. Les cartons originaux, conservés au Victoria and Albert Museum de Londres, ont servi de modèles aux manufactures de Bruxelles, Paris, Mortlake et Rome pendant plusieurs siècles.</p><p class="resume-text">La mort prématurée de Raphaël à 37 ans, le Vendredi Saint 1520, a provoqué une consternation générale dans la Rome cultivée. Son influence sur la peinture européenne — du classicisme français au néoclassicisme anglais, en passant par les Préraphaélites victoriens qui réagissaient contre lui — demeure l'une des plus durables de toute l'histoire de l'art occidental.</p><div class="highlight-box"><p>Raphaël a réalisé plus de 300 dessins préparatoires pour les seules Chambres du Vatican — les Stanze — témoignant d'une méthode de travail d'une rigueur exceptionnelle.</p></div>""",

"renaissance/quattrocento": """<h3>Les mécènes et les institutions : l'économie de l'art florentin</h3><p class="resume-text">Le miracle artistique florentin du XVe siècle n'aurait pas été possible sans l'imbrication d'une économie prospère, d'institutions civiques actives et d'une culture du mécénat. Les guildes (Arte della Lana, Arte della Calimala), les confréries religieuses et les grandes familles marchandes rivalisaient pour commander les œuvres les plus prestigieuses, faisant de Florence un laboratoire permanent d'expérimentation artistique.</p><p class="resume-text">Cosme de Médicis et son petit-fils Laurent le Magnifique ont élevé le mécénat à un outil de pouvoir politique sophistiqué. Leur académie néoplatonicienne réunissait les plus grands intellectuels de l'époque — Marsile Ficin, Pic de la Mirandole, Politien — et nourrissait les artistes d'une culture humaniste qui se traduit directement dans les œuvres. Le programme iconographique du Printemps de Botticelli, d'une complexité symbolique extrême, est le fruit de ces échanges entre savants et peintres.</p><p class="resume-text">Les grandes institutions publiques florentines — l'Orsanmichele, la cathédrale Santa Maria del Fiore, le Baptistère — ont été les terrains de concours qui ont forgé les artistes du Quattrocento. Les portes du Baptistère, commandées par la guilde des marchands de laine, ont opposé Brunelleschi et Ghiberti dans le célèbre concours de 1401, moment fondateur de la Renaissance artistique.</p><div class="highlight-box"><p>Le concours de 1401 pour les portes du Baptistère de Florence est considéré comme le « moment zéro » de la Renaissance artistique : les deux panneaux d'essai de Brunelleschi et Ghiberti, conservés au Bargello, restent deux des œuvres les plus étudiées de toute la période.</p></div>""",

"renaissance/renaissance-nordique": """<h3>Réforme protestante et révolution de l'image</h3><p class="resume-text">La Renaissance nordique est indissociable de la Réforme protestante (1517-) qui a radicalement transformé le statut et la fonction des images en Europe du Nord. La théologie luthérienne, puis calviniste, condamna les images religieuses dans les espaces de culte, précipitant des vagues d'iconoclasme qui détruisirent des milliers d'œuvres d'art. Cette révolution religieuse a paradoxalement favorisé l'émergence d'une peinture profane, de genre et de portrait, libérée de la tutelle de l'Église.</p><p class="resume-text">Lucas Cranach l'Ancien, ami intime de Luther, fut le grand peintre de la Réforme. Il produisit des milliers d'images luthériennes diffusées par la gravure — portraits de Luther, allégories de la Loi et de la Grâce, retables réformés — tout en continuant à peindre des nus et des portraits de cour pour les princes. Cette double pratique illustre la complexité des transitions artistiques de l'époque.</p><p class="resume-text">Les Flandres, restées catholiques sous domination espagnole, maintinrent une tradition de peinture religieuse tout en développant la peinture de genre, le paysage et la nature morte. Pieter Bruegel l'Ancien, avec ses scènes paysannes philosophiques et ses paysages d'hiver, créa un langage visuel original qui influença directement le siècle d'or hollandais.</p><div class="highlight-box"><p>Dürer fut le premier artiste nordique à se représenter en autoportrait de face (1500), s'attribuant une pose traditionnellement réservée aux images du Christ — geste audacieux qui exprime la nouvelle dignité de l'artiste à la Renaissance.</p></div>""",

"art-moderne/impressionnisme": """<h3>La révolution du regard et l'héritage impressionniste</h3><p class="resume-text">L'impressionnisme n'est pas seulement une révolution technique mais une révolution du regard. Les impressionnistes ont changé ce que signifie « voir » en peinture : au lieu de représenter ce que l'on sait d'un objet (sa forme permanente, sa couleur locale), ils ont cherché à peindre ce que l'œil voit effectivement dans des conditions particulières d'éclairage et d'atmosphère. Cette distinction, d'apparence simple, a ouvert un abîme entre la peinture traditionnelle et l'art moderne.</p><p class="resume-text">Le marché de l'art impressionniste illustre l'un des retournements les plus spectaculaires de l'histoire culturelle. Moqués et refusés par le Salon officiel dans les années 1870-1880, les impressionnistes ont dû créer leur propre réseau de vente, animé par le marchand Paul Durand-Ruel. Ce dernier, en exportant leur travail aux États-Unis dès 1886, a contribué à leur reconnaissance internationale. Un siècle plus tard, leurs œuvres atteignent des prix records dans les salles de ventes mondiales.</p><p class="resume-text">L'influence de la photographie et de la gravure japonaise (<em>ukiyo-e</em>) sur l'impressionnisme est fondamentale. Les estampes de Hiroshige, Hokusai et Utamaro, découvertes en France après l'ouverture du Japon en 1854, ont révélé aux impressionnistes d'autres manières d'organiser l'espace, de choisir les points de vue insolites et de simplifier les formes. Monet, Degas et Van Gogh collectionnaient passionnément ces estampes.</p><div class="highlight-box"><p>Paul Durand-Ruel, premier marchand à croire en l'impressionnisme, a perdu une fortune avant d'en gagner une. L'exposition qu'il organisa à New York en 1886 fut un triomphe commercial qui sauva sa galerie et consacra le mouvement aux États-Unis.</p></div>""",

"art-moderne/post-impressionnisme": """<h3>Quatre visions, quatre destins : la divergence post-impressionniste</h3><p class="resume-text">Ce qui unit Cézanne, Van Gogh, Gauguin et Seurat sous l'étiquette « post-impressionnisme », c'est paradoxalement leur divergence radicale. Chacun a tiré de l'impressionnisme une leçon différente et l'a poussée à son terme logique. Cézanne voulait « refaire Poussin sur nature » — réconcilier la rigueur classique avec la vérité optique impressionniste. Van Gogh voulait que la couleur exprime l'émotion pure. Gauguin cherchait à retrouver une spiritualité primitive que la civilisation avait étouffée. Seurat voulait fonder la peinture sur une science rigoureuse de la perception.</p><p class="resume-text">La vie de Vincent van Gogh est devenue l'un des mythes fondateurs de la modernité artistique. Sa correspondance avec son frère Théo — plus de 800 lettres conservées, publiées et traduites dans le monde entier — est un document exceptionnel sur la pensée d'un artiste, ses sources d'inspiration, ses doutes et sa conception de la peinture. Van Gogh n'a vendu qu'une seule toile de son vivant ; aujourd'hui, ses œuvres sont parmi les plus chères jamais vendues.</p><p class="resume-text">L'œuvre de Cézanne a exercé une influence déterminante sur le XXe siècle. Picasso et Braque l'appelaient « le père de nous tous » ; Matisse conserva jusqu'à sa mort les <em>Trois baigneuses</em> qu'il avait achetées à grand sacrifice. La décomposition cézannienne des formes en plans géométriques est le germe direct du cubisme et, au-delà, de l'abstraction géométrique.</p><div class="highlight-box"><p>Paul Cézanne a réalisé plus de 60 versions de la montagne Sainte-Victoire entre 1882 et 1906, traitant le même motif comme un problème de structure picturale à résoudre — une obsession qui est le fondement conceptuel de l'art moderne.</p></div>""",

"art-moderne/cubisme": """<h3>Le cubisme analytique, synthétique et ses ramifications</h3><p class="resume-text">Le cubisme se développe en deux grandes phases bien distinctes. Le cubisme analytique (1908-1912) déconstruit les formes en facettes multiples représentant simultanément différents points de vue, jusqu'à une quasi-abstraction. Les palettes se resserrent sur les bruns, gris et ocres, toute couleur séduisante étant écartée au profit de l'analyse formelle pure. Les tableaux de cette période sont parmi les plus difficiles à « lire » de toute l'histoire de la peinture.</p><p class="resume-text">Le cubisme synthétique (1912-1914) opère un retournement : au lieu de décomposer la réalité perçue, il construit des représentations à partir d'éléments simples — plans colorés, fragments de journaux, papiers collés. L'invention du collage par Braque en 1912 (avec ses papiers peints imitant le bois et le marbre) introduit des matériaux extra-picturaux dans la peinture, ouvrant la voie à tous les arts mixtes du XXe siècle.</p><p class="resume-text">Le cubisme a engendré de multiples mouvements dans toute l'Europe : le futurisme italien (qui y ajoute le dynamisme et la vitesse), le constructivisme russe (qui en tire une abstraction géométrique au service de la révolution), le vorticisme anglais, De Stijl hollandais. En France, les cubistes orphiques de Robert Delaunay introduisent la couleur et la lumière dans le langage cubiste, préfigurant l'abstraction lyrique.</p><div class="highlight-box"><p>La première exposition cubiste à laquelle participent plusieurs artistes simultanément (Salon des Indépendants, 1911) provoque un scandale public. Guillaume Apollinaire, défenseur acharné du mouvement, invente le terme « cubisme » dans ses écrits critiques.</p></div>""",

"art-moderne/surrealisme": """<h3>Le surréalisme international et ses héritages</h3><p class="resume-text">Le surréalisme est, de tous les mouvements d'avant-garde du XXe siècle, celui qui s'est le plus largement diffusé à l'échelle mondiale et le plus profondément imprégné la culture populaire. Des films publicitaires aux pochettes d'albums, des illustrations de mode aux effets spéciaux cinématographiques, le vocabulaire visuel surréaliste est aujourd'hui omniprésent dans l'iconosphère contemporaine. Cette diffusion témoigne de la puissance de l'imagerie onirique et du désir de subversion que le mouvement a su cristalliser.</p><p class="resume-text">Le surréalisme a également embrassé des traditions artistiques non-occidentales que les avant-gardes européennes redécouvraient. L'art des Amérindiens, collecté passionnément par Breton et Ernst lors de leur exil new-yorkais (1940-1945), les arts océaniens et africains, les arts populaires européens ont nourri un surréalisme élargi et synchrétique. Cette ouverture a fait du surréalisme un mouvement presque mondial, avec des branches mexicaine (Remedios Varo, Leonora Carrington), tchèque, japonaise et égyptienne.</p><p class="resume-text">La contribution des femmes artistes au surréalisme a longtemps été minimisée au profit des figures masculines dominantes. Meret Oppenheim, Dorothea Tanning, Kay Sage, Toyen, Remedios Varo et Leonora Carrington ont pourtant produit certaines des œuvres les plus radicales et les plus personnelles du mouvement, apportant des perspectives sur le désir, le corps et l'identité que les surréalistes masculins ne pouvaient exprimer.</p><div class="highlight-box"><p>La rétrospective Dali au Centre Pompidou en 1979 attira 840 000 visiteurs — un record historique qui consacra définitivement le surréalisme comme l'un des mouvements les plus populaires auprès du grand public.</p></div>""",

"art-moderne/art-abstrait": """<h3>Les grandes familles de l'abstraction et leurs tensions</h3><p class="resume-text">L'art abstrait n'est pas un mouvement uniforme mais un territoire traversé de tensions permanentes entre deux pôles. L'abstraction géométrique — Mondrian, Malevitch, Albers — cherche à atteindre des vérités universelles par l'épuration formelle et la rigueur constructive. L'abstraction lyrique ou expressionniste — Kandinsky dans ses phases tardives, Gorky, De Kooning — privilégie l'expression émotionnelle directe, le geste et la trace comme signes intérieurs.</p><p class="resume-text">L'expressionnisme abstrait américain (New York School, années 1940-1950) constitue le premier mouvement d'avant-garde né aux États-Unis et le premier à s'imposer mondialement. Jackson Pollock (technique du dripping sur toile au sol), Mark Rothko (voiles de couleur vibrants), Franz Kline (calligraphies noires monumentales) et Barnett Newman (« zips » verticaux) ont chacun développé un vocabulaire singulier à partir du postulat commun de l'abstraction comme expression existentielle.</p><p class="resume-text">En Europe, le mouvement Cobra (1948-1951, Copenhague-Bruxelles-Amsterdam) associait expressionnisme nordique et art primitif dans une peinture énergique et colorée. En France, le Tachisme et la peinture informelle (Soulages, Hartung, Wols) exploraient d'autres voies d'une abstraction gestuelle plus contemplative que dramatique. Pierre Soulages, avec son exploration de l'« outrenoir » — lumière réfléchie par des surfaces noires texturées — a poussé la peinture abstraite vers des territoires médiatifs et presque mystiques.</p><div class="highlight-box"><p>Pierre Soulages, mort en 2022 à 102 ans, a inventé le concept d'« outrenoir » : une couleur au-delà du noir qui ne réfléchit que la lumière ambiante. Le musée Soulages de Rodez (2014) lui est entièrement consacré.</p></div>""",

"art-contemporain/pop-art": """<h3>Le pop art européen et la critique du consumérisme</h3><p class="resume-text">Si le pop art américain tend à regarder la culture de masse avec une fascination esthétique souvent ambigu, le pop art britannique — qui a précédé et en partie inspiré le mouvement américain — adopte une posture plus critique. Les artistes du groupe Independent Group (Lawrence Alloway, Richard Hamilton, Eduardo Paolozzi), réunis à l'Institute of Contemporary Arts de Londres dès 1952, analysaient la culture populaire américaine comme un phénomène culturel nouveau, fascinant et inquiétant à la fois.</p><p class="resume-text">Richard Hamilton, avec son petit collage <em>Just What Is It That Makes Today's Homes So Different, So Appealing?</em> (1956) — un intérieur domestique peuplé de magazines, d'un culturiste et d'une pin-up, surmonté d'une sucette géante portant le mot « POP » — est souvent présenté comme le premier manifeste pop. David Hockney, Allen Jones et Peter Blake ont chacun développé des approches distinctes de ce rapport à la culture populaire.</p><p class="resume-text">En France, le Nouveau Réalisme (Klein, Arman, Tinguely, Christo), fondé en 1960 par le critique Pierre Restany, constitue une réponse européenne aux questions que pose la société de consommation. Arman accumule des objets de rebut dans des vitrines transparentes, Tinguely construit des machines auto-destructrices, Christo emballe des bâtiments entiers — autant de façons de poser la question du statut de l'objet dans le capitalisme avancé.</p><div class="highlight-box"><p>Andy Warhol, roi du pop art américain, a déclaré : « Dans le futur, tout le monde sera célèbre pendant 15 minutes. » Cette formule, prononcée en 1968, est devenue l'une des prophéties les plus citées sur la société du spectacle et l'ère des réseaux sociaux.</p></div>""",

"art-contemporain/minimalisme": """<h3>Minimalisme et phénoménologie : l'expérience de l'espace</h3><p class="resume-text">Le minimalisme s'est accompagné d'une réflexion théorique intense sur l'expérience esthétique. Les artistes minimalistes ont lu la phénoménologie de Merleau-Ponty et les théories de la perception gestaltiste pour conceptualiser ce qu'ils cherchaient à provoquer. Leur art voulait impliquer le spectateur dans une relation physique et temporelle à l'œuvre, insistant sur l'expérience vécue du corps dans l'espace plutôt que sur la contemplation d'un objet de beauté autonome.</p><p class="resume-text">Donald Judd, théoricien autant qu'artiste, a articulé la notion de « specific objects » — objets qui ne sont ni peinture ni sculpture au sens traditionnel, mais des présences physiques existant dans le même espace réel que le spectateur. Ses empilements de boîtes industrielles en acier galvanisé et plexiglas coloré, répétitifs et précis, engagent une relation directe entre la matérialité des surfaces et la lumière ambiante.</p><p class="resume-text">Dan Flavin, avec ses dispositions de tubes fluorescents commerciaux, transforme l'espace en expérience lumineuse colorée où l'œuvre et l'environnement deviennent indissociables. James Turrell, à la croisée du minimalisme et du Land Art, construit des espaces architecturaux où la lumière elle-même devient la matière unique — poussant la réduction minimaliste à son point ultime.</p><div class="highlight-box"><p>James Turrell travaille depuis 1974 à transformer le cratère volcanique Roden Crater en Arizona en un observatoire céleste architectural. Ce projet en cours, l'une des œuvres d'art les plus ambitieuses jamais conçues, intègre des chambres taillées dans la roche où la lumière du soleil, de la lune et des étoiles est perçue comme un phénomène artistique.</p></div>""",

"art-contemporain/art-conceptuel": """<h3>Du concept à l'institution : l'art conceptuel et le système de l'art</h3><p class="resume-text">L'art conceptuel a profondément transformé les institutions du monde de l'art. En remettant en question l'objet comme support nécessaire de l'art, il a élargi le champ de ce qui peut constituer une œuvre : un texte, une performance, une idée, un processus, une relation sociale. Cette expansion a ouvert l'art à des pratiques radicalement nouvelles — l'art de la performance, le Land Art, l'art relationnel, l'art Internet — qui n'auraient pas été pensables sans la critique conceptualiste de l'objet.</p><p class="resume-text">Les institutions muséales elles-mêmes sont devenues l'objet de la critique conceptuelle. Hans Haacke, depuis les années 1970, produit des œuvres qui exposent les relations entre les musées, leurs mécènes et les pouvoirs économiques et politiques. Andrea Fraser performe des rôles institutionnels (guide de musée, conférencière) pour révéler les codes et les rapports de pouvoir à l'œuvre dans les espaces culturels. Cette critique institutionnelle a forcé les musées à réfléchir à leurs propres pratiques.</p><p class="resume-text">L'art conceptuel a également posé des questions cruciales sur la valeur et l'authenticité. Si l'idée est l'œuvre, qu'est-ce qui est vendu ? Qu'est-ce qui est exposé ? Les « certificats d'authenticité » vendus par certains artistes conceptuels — donnant droit de matérialiser une idée — ont créé un marché de l'immatériel qui préfigurait étrangement les NFT du XXIe siècle.</p><div class="highlight-box"><p>En 2021, Maurizio Cattelan a vendu pour 6,2 millions de dollars une œuvre intitulée <em>Comedian</em> (2019) — une banane scotchée à un mur. Cette transaction, héritière directe de la logique conceptualiste, a relancé le débat sur les frontières de l'art contemporain.</p></div>""",

"art-contemporain/art-numerique": """<h3>Intelligence artificielle et nouvelles questions de l'art</h3><p class="resume-text">L'émergence des outils d'intelligence artificielle générative (DALL-E, Midjourney, Stable Diffusion) à partir de 2022 a posé de nouvelles questions fondamentales à la communauté artistique. Ces systèmes, entraînés sur des milliards d'images sans toujours obtenir le consentement des artistes dont ils s'inspirent, brouillent les frontières entre la création, la synthèse et la reproduction. La question de la paternité, du droit d'auteur et de la valeur de la compétence technique est au cœur des débats actuels.</p><p class="resume-text">Des artistes comme Refik Anadol transforment de vastes ensembles de données numériques — archives d'images, données météorologiques, signaux neuronaux — en installations visuelles immersives qui matérialisent des structures invisibles du monde contemporain. Ses œuvres pour le MoMA de New York ou l'exposition universelle de Dubaï illustrent comment l'art numérique peut réconcilier esthétique, data science et espace public.</p><p class="resume-text">Les NFT (<em>non-fungible tokens</em>), apparus comme vecteur commercial de l'art numérique en 2020-2021, ont connu une trajectoire fulgurante et une correction brutale. Au-delà de la spéculation, ils ont posé une question légitime : comment certifier l'unicité et la propriété d'une œuvre numérique reproductible à l'infini ? Cette question, non résolue, reste au cœur du marché de l'art numérique.</p><div class="highlight-box"><p>En mars 2021, l'artiste Beeple a vendu une œuvre d'art numérique (un fichier JPG compilant 5 000 images créées sur 13 ans) pour 69,3 millions de dollars via la maison Christie's — le troisième prix le plus élevé jamais atteint par un artiste vivant.</p></div>""",

"art-contemporain/installations": """<h3>L'art de l'installation : spectateur, espace et relation</h3><p class="resume-text">L'art de l'installation transforme radicalement la relation entre l'œuvre et le spectateur. Dans la peinture ou la sculpture traditionnelle, le spectateur se tient devant l'objet et le contemple à distance. Dans l'installation, il est à l'intérieur de l'œuvre, il la traverse, il l'active par sa présence. Cette mutation phénoménologique — du regardeur au participant — est l'une des transformations les plus profondes de l'art des cinquante dernières années.</p><p class="resume-text">Les grands espaces muséaux ont fourni aux artistes des terrains d'expérimentation monumentaux. La Turbine Hall de la Tate Modern à Londres, inaugurée en 2000, accueille chaque année une installation géante. Olafur Eliasson y a placé un soleil artificiel (The Weather Project, 2003), Doris Salcedo a fissuré le sol en béton (Shibboleth, 2007), Ai Weiwei y a répandu 100 millions de graines de tournesol en porcelaine (Sunflower Seeds, 2010) — autant d'œuvres qui impliquent le corps du visiteur dans une expérience physique collective.</p><p class="resume-text">L'art relationnel théorisé par Nicolas Bourriaud dans les années 1990 pousse encore plus loin cette logique en faisant de la relation sociale elle-même le médium artistique. Rirkrit Tiravanija cuisine pour les visiteurs dans l'espace de la galerie, Thomas Hirschhorn crée des « kiosques » dans des quartiers défavorisés, Tino Sehgal conçoit des situations interactives sans aucun objet matériel — autant de pratiques qui remettent en question toute la chaîne de production, distribution et réception de l'art.</p><div class="highlight-box"><p>L'installation <em>Rain Room</em> de Random International (2012), dans laquelle il pleut sans jamais mouiller les visiteurs qui se déplacent à l'intérieur, a généré des files d'attente de plusieurs heures lors de ses présentations à la Barbican Gallery de Londres et au MoMA de New York.</p></div>""",

"analyse-oeuvres/la-joconde": """<h3>Postérité, reproductions et hypervisibilité</h3><p class="resume-text">La Joconde est aujourd'hui l'œuvre d'art la plus visitée, la plus reproduite et la plus reconnue du monde. Cette hypervisibilité, loin d'être naturelle, est le résultat d'une histoire complexe de scandales, de reproductions et d'investissements institutionnels. Le vol de la toile par Vincenzo Peruggia en 1911, retrouvée deux ans plus tard à Florence, a transformé la Joconde en fait divers mondial et en obsession médiatique, lui conférant une célébrité sans précédent à l'ère de la presse de masse.</p><p class="resume-text">Marcel Duchamp, en ajoutant une moustache à une reproduction de la Joconde en 1919 (<em>L.H.O.O.Q.</em>), a lancé une tradition de détournements qui n'a jamais cessé. Warhol, Banksy et d'innombrables artistes et publicitaires ont depuis décliné ce visage en millions de variations. Cette multiplication constitue paradoxalement une forme d'hommage et de destruction simultanés : plus l'œuvre est reproduite, moins on la voit vraiment.</p><p class="resume-text">Au Louvre, la Joconde repose derrière une vitre blindée, à l'abri derrière une balustrade, dans une salle reconçue pour gérer les foules. La plupart des visiteurs la photographient avec leur téléphone depuis plusieurs mètres de distance — sans jamais vraiment la regarder. Cette mise en scène de l'hypervisibilité est devenue un commentaire involontaire sur la relation moderne à l'œuvre d'art originale à l'ère de la reproduction numérique.</p><div class="highlight-box"><p>La Joconde mesure seulement 77 × 53 cm — beaucoup plus petite que ce qu'imaginent les visiteurs qui, déçus par sa taille, réagissent souvent avec incrédulité devant « la peinture la plus célèbre du monde ».</p></div>""",

"analyse-oeuvres/guernica": """<h3>Guernica : réception, voyages et pouvoir politique</h3><p class="resume-text">L'histoire de Guernica après sa création est aussi riche que l'œuvre elle-même. Refusant de laisser la toile en Espagne franquiste, Picasso la déposa au MoMA de New York en 1939 avec mission de la restituer à l'Espagne lors du rétablissement de la démocratie. Pendant quarante ans, Guernica fut un symbole de l'exil : elle voyagea dans le monde entier pour des expositions de solidarité avec la résistance espagnole, collectant des fonds et fédérant l'opinion internationale.</p><p class="resume-text">En 1974, un activiste anti-Vietnam asperge la toile de peinture rouge au MoMA — protestation contre la guerre du Vietnam en usant du tableau le plus célèbre de l'histoire du pacifisme. L'œuvre, heureusement protégée par son vernis, est restaurée. Cet incident illustre comment Guernica est devenu un espace de projection pour toutes les causes pacifistes, parfois malgré elle.</p><p class="resume-text">La toile est restituée à l'Espagne démocratique en 1981, six ans après la mort de Franco. Elle est d'abord présentée au Prado, sous une vitre blindée et gardée par la Guardia Civil — ironie d'une œuvre anti-autoritaire gardée par des représentants de l'État. Elle est transférée au Musée Reina Sofía de Madrid en 1992, où elle est aujourd'hui exposée dans les conditions qui lui donnent toute son ampleur.</p><div class="highlight-box"><p>Une reproduction de Guernica est accrochée à l'entrée de la salle du Conseil de sécurité de l'ONU à New York. En 2003, lors de la conférence de presse précédant la guerre d'Irak, Colin Powell fit couvrir la tapisserie d'un rideau bleu — épisode révélateur du pouvoir symbolique de l'œuvre.</p></div>""",

"analyse-oeuvres/nuit-etoilee": """<h3>Van Gogh à Saint-Rémy : création sous contrainte</h3><p class="resume-text">La Nuit étoilée est peinte en juin 1889 depuis la fenêtre de la chambre de Van Gogh à l'asile Saint-Paul-de-Mausole, à Saint-Rémy-de-Provence, où l'artiste s'est volontairement interné en mai 1889 après l'épisode de l'oreille coupée. Loin d'être une période de paralysie créatrice, son séjour de douze mois à Saint-Rémy a été l'une des plus productives de sa vie : il y peint environ 150 tableaux et réalise plus de 100 dessins.</p><p class="resume-text">Van Gogh peint La Nuit étoilée de mémoire, sans modèle direct — pratique inhabituelle pour lui qui travaillait généralement sur le motif. Il écrit à son frère Théo qu'il cherche à exprimer l'émotion produite par la contemplation du ciel nocturne plutôt qu'à le reproduire fidèlement. Cette affirmation de la primauté de l'expression sur la description est un manifeste en miniature de la modernité expressionniste.</p><p class="resume-text">L'analyse spectrale de la toile a révélé que Van Gogh utilisait des pigments de grande qualité — dont certains peu stables — et que sa technique de superposition de couches épaisses (<em>impasto</em>) atteint ici une complexité maximale. Des études récentes ont montré que les spirales de la Nuit étoilée présentent des structures fractales similaires à la turbulence fluide décrite par l'équation de Kolmogorov — une convergence troublante entre intuition artistique et description mathématique de la nature.</p><div class="highlight-box"><p>Une étude publiée en 2006 dans la revue <em>Physical Review Letters</em> a démontré que les tourbillons de La Nuit étoilée reproduisent avec une précision étonnante les propriétés mathématiques de la turbulence fluide, suggérant que Van Gogh avait intuitivement saisi une structure fondamentale de la physique.</p></div>""",

"analyse-oeuvres/liberte-guidant-peuple": """<h3>De la révolution de Juillet à l'icône républicaine</h3><p class="resume-text">La Liberté guidant le peuple (1830) est née dans la chaleur de l'événement : Delacroix commence le tableau quelques semaines après les Trois Glorieuses (27-29 juillet 1830) qui ont renversé Charles X. Dans une lettre à son frère, il écrit : « J'ai entrepris un sujet moderne, une barricade. » L'œuvre est donc d'abord un tableau de presse — une mise en image de l'actualité — avant de devenir un symbole universel.</p><p class="resume-text">La figure de Marianne, la République française personnifiée, puise directement dans la tradition de l'allégorie antique que la Révolution avait réactivée. Delacroix hybride deux traditions : la Victoire ailée de la sculpture antique (Nike de Samothrace) et la réalité physique des combattants parisiens. En plaçant une allégorie au milieu d'une scène historique réaliste, il invente un genre nouveau qui sera massivement repris par la peinture politique du XIXe siècle.</p><p class="resume-text">Le tableau a une histoire institutionnelle complexe. Acheté par Louis-Philippe en 1831, il est rapidement jugé trop subversif et mis en réserve jusqu'en 1848, où la Seconde République le réexpose. Saisi par Napoléon III, oublié, réapparu, il entre finalement au Louvre en 1874. Reproduit sur les billets de 100 francs entre 1978 et 1995, il est aujourd'hui l'une des images fondatrices de l'identité visuelle française.</p><div class="highlight-box"><p>Le personnage en chapeau haut-de-forme à gauche de la composition est souvent identifié à Delacroix lui-même — ce qui ferait de l'artiste bourgeois un combattant des barricades. Cette hypothèse, ni confirmée ni infirmée, ajoute une dimension autobiographique à l'œuvre.</p></div>""",

"analyse-oeuvres/nympheas": """<h3>Monet à Giverny : le jardin comme œuvre totale</h3><p class="resume-text">Le jardin de Giverny, que Monet conçoit et transforme pendant quarante ans, est lui-même une œuvre d'art au sens plein du terme. Monet achète la propriété en 1890 et y fait réaliser un jardin d'eau en détournant un bras de l'Epte, plantant des nénuphars exotiques importés du Japon et d'Amérique du Sud, construisant le pont japonais et les saules pleureurs. Il écrit : « Mon plus beau chef-d'œuvre est mon jardin. » Le jardin n'est pas le prétexte de la peinture — c'est son pendant matériel, une composition végétale et aquatique qui dialogue avec les tableaux.</p><p class="resume-text">Le cycle des Nymphéas présenté à l'Orangerie, installé dans deux salles ovales selon les instructions de Monet et inauguré en 1927 à sa mort, constitue une expérience artistique totale unique. Ces 8 panneaux, longs au total de 91 mètres, immergent le spectateur dans un paysage de lumière et d'eau sans horizon ni ligne de fuite. André Masson appelait ces salles « la Sixtine de l'impressionnisme » ; les expressionnistes abstraits américains, notamment Mark Rothko, s'y sont explicitement référés comme source d'inspiration pour leurs grands formats.</p><p class="resume-text">La cécité progressive de Monet, diagnostiquée dès 1912, ajoute une dimension tragique et fascinante à sa production tardive. Il continue à peindre malgré une vision fortement altérée, utilisant les étiquettes de tubes et l'emplacement mémorisé des couleurs sur sa palette. Certains historiens de l'art voient dans les tonalités de jaune et d'orange des dernières toiles une conséquence directe de la cataracte, qui jaunit la vision.</p><div class="highlight-box"><p>Les panneaux des Nymphéas de l'Orangerie couvrent une surface totale de 200 m². Monet a travaillé à leur réalisation pendant les douze dernières années de sa vie, en pleine Première Guerre mondiale, comme offrande à la paix.</p></div>""",
}

# ── Injection dans le JSON ────────────────────────────────────────────────────
def inject_content(content_html, extra_html):
    """Insert extra_html just before the closing </section> of the #contenu section."""
    # Find the #contenu section and its closing tag
    # Pattern: find the contenu section and insert before its </section>
    # The contenu section ends before the quiz section starts
    marker = '<section class="content-section" id="quiz">'
    if marker in content_html:
        return content_html.replace(marker, extra_html + marker)
    # Fallback: append before last </section>
    idx = content_html.rfind('</section>')
    if idx != -1:
        return content_html[:idx] + extra_html + content_html[idx:]
    return content_html + extra_html


path = os.path.join(BASE, 'histoire-art.json')
with open(path, 'r', encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
modified = 0
skipped = 0

for key, extra_html in ENRICHMENTS.items():
    if key not in pages:
        print(f'MISSING: {key}')
        continue
    page = pages[key]
    if page.get('type') != 'course':
        print(f'SKIP (not course): {key}')
        skipped += 1
        continue
    old_len = len(page['content'])
    page['content'] = inject_content(page['content'], extra_html)
    new_len = len(page['content'])
    print(f'  {key}: {old_len} → {new_len} (+{new_len-old_len})')
    modified += 1

print(f'\nTotal modifié : {modified}, ignoré : {skipped}')

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Fichier sauvegardé.')
