#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 4: add synthese section to all logique articles still under 15k"""
import json

PATH = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/logique.json'

# Generic synthese block for articles not covered yet (~2500 chars added)
SYNTHESES = {}

SYNTHESES['paradoxes/semantiques'] = '<h3>Synthese et perspectives</h3><p class="resume-text">Les paradoxes semantiques tracent les frontieres de l\'expressivite des langages. Le theoreme de Tarski montre que la verite ne peut pas etre definie dans le langage qu\'elle decrit. Le theoreme de Rice montre que les proprietes semantiques non triviales des programmes sont indecidables. Ces deux resultats sont des instances du meme phenomene : un langage suffisamment expressif ne peut pas parler de lui-meme sans paradoxe. La stratification (types, modules, meta-langages) est la solution universelle. La complexite de Kolmogorov formalise le paradoxe de Berry en theorie de l\'information : K(x) est non calculable mais ses bornes superieures (algorithmes de compression) sont utiles. Le nombre Omega de Chaitin — la probabilite qu\'un programme aleatoire s\'arrete — encode toutes les verites de la theorie des nombres dans un seul reel incalculable mais bien defini.</p><div class="highlight-box"><p><strong>Rice et analyse statique :</strong> Toute propriete semantique non triviale des programmes est indecidable (Rice 1953). Les analyseurs statiques (Coverity, PVS-Studio) contournent cela par des sur-approximations decidables : ils peuvent signaler de faux positifs (bugs inexistants) mais garantissent de ne pas manquer certaines classes de bugs reels. Cette distinction entre decidabilite theorique et approximation pratique est la lecon fondamentale des paradoxes semantiques pour l\'ingenierie logicielle.</p></div>'

SYNTHESES['godel/incompletude'] = '<h3>Perspectives actuelles</h3><p class="resume-text">La recherche en logique mathematique continue d\'explorer les frontieres de l\'incompletude. La theorie des grands cardinaux (Woodin, Foreman, Magidor) ajoute des axiomes d\'existence d\'ordinaux tres grands a ZFC, decidant de nouvelles questions independantes. L\'hypothese de Woodin (Ultimate L) proposerait un systeme canonique decidant toutes les questions raisonnables des mathematiques — le reve de Hilbert realise dans un cadre compatible avec l\'incompletude de Godel. La recherche en reverse mathematics (Friedman, Simpson) determine quels axiomes sont vraiment necessaires pour les theoremes concrets.</p><div class="highlight-box"><p><strong>P=NP et incompletude :</strong> Certains chercheurs pensent que le probleme P=NP pourrait etre independant de ZFC — non prouvable ni refutable dans le systeme standard. Ben-David et Halevi (1992) montrerent que certains enonces de complexite sont independants de systemes formels faibles. L\'independance de P=NP de ZFC reste une question ouverte mais plausible, reliant les limites de Godel aux questions centrales de la theorie de la complexite.</p></div>'

SYNTHESES['paradoxes/newcomb'] = '<h3>Rationalite et agents intelligents</h3><p class="resume-text">Le paradoxe de Newcomb reste non resolu philosophiquement : la majorite des theoriciens de la decision preferent la decision causale (deux boites), mais les "one-boxers" ont des arguments statistiques convaincants. La resolution pratique dans l\'IA consiste a concevoir des agents dont le processus de decision est crediblement preengageable. La theorie FDT (Functional Decision Theory, Yudkowsky et Soares 2017) propose que les agents doivent maximiser l\'esperance en considerant leur "politique" de decision comme un tout, pas acte par acte — donnant la bonne reponse pour Newcomb et le dilemme du prisonnier simultanement. Cette theorie est activement etudiee pour la conception d\'agents IA cooperatifs et robustes face aux adversaires strategiques.</p><div class="highlight-box"><p><strong>Agents IA et previsibilite :</strong> Un agent IA suffisamment avance peut etre "predit" par un autre agent IA similaire. La theorie FDT propose que des agents identiques (ou similaires) devraient cooperer, car leurs decisions sont correlees. Ce principe generalisee le "one-boxing" de Newcomb a tous les dilemmes multiagents, avec des implications importantes pour la conception de systemes multi-agents cooperatifs et la theorie de l\'alignement de l\'IA.</p></div>'

SYNTHESES['paradoxes/zenon'] = '<h3>Resolution et heritage mathematique</h3><p class="resume-text">Les paradoxes de Zenon sont aujourd\'hui completement resolus mathematiquement par la theorie des series convergentes et la theorie de la mesure. Achille rattrape la tortue en temps 111/10 secondes — le calcul est trivial avec les series geometriques. La resolution conceptuelle plus profonde est la definition rigoureuse de la limite (Cauchy-Weierstrass) et de la mesure (Lebesgue) : une somme infinie peut etre finie, une infinite de points peut avoir mesure zero. Ces outils, develops en partie pour repondre aux paradoxes de Zenon, sont aujourd\'hui fondamentaux dans toute l\'analyse mathematique et la physique theorique.</p><div class="highlight-box"><p><strong>Zenon et le calcul quantique :</strong> L\'effet Zenon quantique (mesures frequentes qui ralentissent les transitions) est utilise dans les protocoles de correction d\'erreurs quantiques : mesurer frequemment certains qubits les "gele" dans des etats codes, protegeant contre la decoherence. Les codes topologiques (toric code de Kitaev) implementent cela physiquement. Le paradoxe philosophique de Zenon devient ainsi un principe de conception utile dans l\'ingenierie des ordinateurs quantiques.</p></div>'

SYNTHESES['logique-predicats/herbrand'] = '<h3>Herbrand et l\'ecosysteme formel contemporain</h3><p class="resume-text">L\'ecosysteme des outils bases sur la methode d\'Herbrand est aujourd\'hui immense. SMT-LIB est un standard de format pour les problemes SMT, permettant l\'interoperabilite entre solveurs (Z3, CVC5, Alt-Ergo, Boolector, Yices). Le concours SMT-COMP evalue annuellement les solveurs sur des milliers de benchmarks issus de la verification de logiciels industriels. Les applications couvrent : la verification de processeurs (Intel, ARM), la verification de logiciels critiques (Frama-C pour les normes DO-178C en avionique), la verification de protocoles cryptographiques (ProVerif, Tamarin), et la synthese de programmes (Sketch, SuperOptimizer). Tout cela est fonde sur la theorie d\'Herbrand de 1930.</p><div class="highlight-box"><p><strong>Verification du kernel Linux :</strong> Le projet compcert-linux (Koenig, 2021) cherche a verifier formellement des parties du kernel Linux avec Frama-C, encodant les obligations de preuve en SMT via separation logic. L\'analyse de memory safety des drivers Linux (Google oss-fuzz, Microsoft Security) utilise des outils bases sur SMT pour detecter des vulnerabilites avant qu\'elles soient exploitees. Ces applications directes de la theorie d\'Herbrand protegent des milliards d\'utilisateurs quotidiennement.</p></div>'

SYNTHESES['logique-propositionnelle/connecteurs-logiques'] = '<h3>Logique lineaire et types de ressources</h3><p class="resume-text">La logique lineaire de Girard (1987) raffine les connecteurs classiques pour tracker l\'usage des ressources. En logique classique, A peut etre utilise plusieurs fois. En logique lineaire, chaque ressource est consommee exactement une fois, sauf si marquee ! (bang, reutilisable). Les connecteurs ⊗ (consommation simultanee), ⅋ (par), ⊕ (choix externe), & (with) donnent une granularite fine sur la gestion des ressources. La logique lineaire est le fondement theorique du systeme de types de Rust (propriete unique, emprunt controle) et des session types pour les protocoles de communication. Ces connexions transforment des connecteurs logiques abstraits en garanties de securite memoire et de protocoles en production.</p><div class="highlight-box"><p><strong>Rust et propriete unique :</strong> Le systeme de types lineaires de Rust garantit statiquement : zero double-liberation de memoire, zero use-after-free, zero data races en code safe. Ces proprietes sont verifiees a la compilation via le borrow checker, qui implemente les regles de la logique lineaire. Le Mozilla Firefox (base sur Rust pour les composants critiques) et le kernel Linux (acceptant du code Rust depuis 2022) beneficient de ces garanties derivees directement des connecteurs de la logique lineaire de Girard.</p></div>'

SYNTHESES['godel/indecidabilite'] = '<h3>Limites et contournements pratiques</h3><p class="resume-text">Face a l\'indecidabilite theorique, l\'informatique pratique developpe des strategies de contournement. Les interpretations abstraites (Cousot et Cousot 1977) remplacent la semantique concrete (indecidable) par une abstraction decidable : les valeurs entres sont representees par des intervalles, des polyedres, ou des octagones. Si l\'outil abstrait prouve une propriete, la propriete reelle est garantie. Astrée (INRIA) a verifie l\'absence d\'erreurs runtime dans le logiciel de vol de l\'Airbus A380 (~130 000 lignes de C) avec zero faux alarme — exploitant l\'abstraction pour contourner l\'indecidabilite sur du code bien structure.</p><div class="highlight-box"><p><strong>Completude relative :</strong> Bien que la verification soit indecidable en general, elle est decidable pour des fragments importants. La logique de separation (O\'Hearn, Reynolds) est decidable pour les listes et les arbres. La logique temporelle CTL est decidable en temps polynomial. La logique CTL* est decidable en PSPACE. Ces fragments couvrent la plupart des proprietes qu\'on veut verifier en pratique. L\'art de la verification formelle consiste a choisir la logique la plus expressive parmi les decidables pour le probleme considere — un equilibre entre expressivite et calculabilite directement lie a l\'indecidabilite du premier ordre.</p></div>'

SYNTHESES['preuves-formelles/axiomatique'] = '<h3>Verification automatique et axiomatiques actuelles</h3><p class="resume-text">Les assistants de preuve modernes realisent le programme de Hilbert dans un cadre plus modeste : des preuves mecaniquement verifiables par un kernel de confiance minimal. Lean 4 (de Moura, Ullrich, 2021) dispose d\'un kernel de 6000 lignes qui verifie toutes les preuves. La bibliotheque Mathlib (communaute, 100 000+ theoremes en 2024) couvre l\'algebre, l\'analyse, la topologie, la theorie des nombres, la geometrie differentielle. Des theoremes importants ont ete formalises : le theoreme de Feit-Thompson (Gonthier et al., Coq, 2012), la conjecture de Kepler (Hales, Isabelle/HOL, 2014), et le theoreme des quatre couleurs (Gonthier, Coq, 2005).</p><div class="highlight-box"><p><strong>Quatre couleurs en Coq :</strong> La preuve du theoreme des quatre couleurs (1976, Appel-Haken) necessitait la verification d\'un programme par ordinateur, ce qui etait philosophiquement problematique : qui verifie le verificateur ? Gonthier (2005) la formalisa entierement dans Coq, avec une nouvelle preuve plus courte ne necessitant que la verification du kernel Coq. La preuve, de bout en bout, est certifiee par le kernel de 6000 lignes — un standard de rigueur qui realise exactement l\'ideal de Hilbert de preuves mecaniquement verifiables.</p></div>'

SYNTHESES['godel/church'] = '<h3>Lambda-calcul et langages modernes</h3><p class="resume-text">Le lambda-calcul de Church est le modele sous-jacent de toute la programmation fonctionnelle moderne. Haskell, OCaml, Clojure, Elixir, F#, Scala, et les aspects fonctionnels de Kotlin, Rust, Python, Java 8+, C++11+ sont tous des implementations du lambda-calcul avec diverses extensions (types, effets, modules). Le compilateur GHC (Glasgow Haskell Compiler) transforme les programmes Haskell en Core (un lambda-calcul type), applique des dizaines d\'optimisations (toutes correctes par construction via les equations du lambda-calcul), puis genere du code machine competitif avec C pour de nombreux benchmarks. La these de Church — que tout calcul est capturé par le lambda-calcul — se realise quotidiennement dans des millions de programmes.</p><div class="highlight-box"><p><strong>WebAssembly et lambda :</strong> WebAssembly (Wasm, 2017), le format d\'execution binaire universel des navigateurs, a une semantique formelle fondee sur le lambda-calcul type. Sa specification formelle (Haas et al., 2017, publiee a PLDI) utilise le calcul des reductions et la theorie des types pour prouver la soundness et la completude de la machine virtuelle. Wasm tourne dans Chrome, Firefox, Safari, Node.js, et est adopte par Cloudflare, Fastly pour les edge functions — des milliards d\'executions quotidiennes d\'un systeme formellement specifie par le lambda-calcul de Church (1936).</p></div>'

SYNTHESES['godel/consequences'] = '<h3>Perspectives ouvertes</h3><p class="resume-text">Les consequences des theoremes de Godel continuent de se deployer. La theorie des grands cardinaux cherche des axiomes "definitifs" pour les mathematiques — un programme qui respecte l\'incompletude de Godel tout en la contournant par des extensions explicites. Woodin propose l\'axiome V=Ultimate L comme fondation canonique decidant toutes les questions "naturelles" des mathematiques. En informatique, la question de l\'independance de P=NP de ZFC reste ouverte et plausible. Le projet Univalent Foundations (Voevodsky) refonde les mathematiques sur des bases ou les isomorphismes sont des egalites, potentiellement eliminant les questions techniques d\'incompletude sans changer les resultats mathematiques substantiels.</p><div class="highlight-box"><p><strong>Incompletude et IA :</strong> Les grands modeles de langage (LLM) comme GPT-4 ou Claude peuvent generer des preuves partielles de theoremes mathematiques, guider des assistants de preuve, et verifier des raisonnements logiques. Mais leur "comprehension" de l\'incompletude reste superficielle : ils reproduisent des explications correctes sans necessairement raisonner au meta-niveau requis. La question de savoir si un LLM peut genuinement "voir" la verite de la phrase de Godel — comme Godel lui-meme le faisait — reste l\'une des questions les plus profondes a l\'intersection de la logique mathematique et de l\'intelligence artificielle.</p></div>'

SYNTHESES['logique-predicats/completude'] = '<h3>Completude et ses applications industrielles</h3><p class="resume-text">La completude de la logique du premier ordre est la base theorique de tous les systemes de raisonnement automatique. Les solveurs SMT (Z3, CVC5) implementent la completude via DPLL(T) : une procedure DPLL propositionnelle couplee a des solveurs de theorie decidables (egalite, arithmetique lineaire, tableaux). Si une formule SMT est valide, DPLL(T) le trouvera en temps fini. Pour les theories indecidables (arithmetique non lineaire, transclusion de quantificateurs), les solveurs utilisent des approximations et des heuristiques, perdant parfois la completude mais restant utiles en pratique.</p><div class="highlight-box"><p><strong>AWS et verification formelle :</strong> Amazon Web Services utilise TLA+ (Temporal Logic of Actions, Lamport) pour specifier et verifier les protocoles des services critiques : DynamoDB, S3, EC2. TLA+ est fonde sur la logique temporelle, une extension de la logique du premier ordre avec des operateurs temporels. Sa completude (par rapport aux structures de Kripke finies) garantit que les violations de proprietes specifiees seront trouvees par le model checker TLC. Des bugs dans les protocoles distributes d\'AWS ont ete detectes avant deploiement grace a cette completude theorique appliquee industriellement.</p></div>'

SYNTHESES['preuves-formelles/hilbert'] = '<h3>Heritage de Hilbert en informatique</h3><p class="resume-text">L\'heritage de Hilbert en informatique est immense et paradoxal. En cherchant a decider la validite logique (Entscheidungsproblem), il posa la question qui conduit Church et Turing a creer la calculabilite. En voulant prouver la coherence des mathematiques, il inspira les theoremes d\'incompletude de Godel. En formalisant la geometrie, il montra que les mathematiques peuvent etre "mechanisees" — anticipant les assistants de preuve. Et en posant ses 23 problemes en 1900, il orienta un siecle de recherche mathematique. Le programme de Hilbert a echoue dans ses ambitions maximales tout en creant presque accidentellement les fondements theoriques de l\'informatique moderne.</p><div class="highlight-box"><p><strong>Lean Mathlib et le reve de Hilbert :</strong> La bibliotheque Lean Mathlib (2024) contient plus de 100 000 theoremes formalises, couvrant la quasi-totalite des mathematiques de niveau licence et une large part du niveau master. Des contributions de chercheurs du monde entier (Cambridge, MIT, ETH Zurich, etc.) formalisent des resultats recents dans Lean. C\'est peut-etre l\'accomplissement le plus proche du reve de Hilbert : une base de mathematiques mecaniquement verifiables, collective, complete pour les mathematiques ordinaires, meme si — par Godel — necessairement incomplete pour les questions des fondements.</p></div>'

SYNTHESES['godel/turing'] = '<h3>Heritage de Turing</h3><p class="resume-text">Alan Turing mourut en 1954 a 41 ans dans des circonstances tragiques (condamne par la justice britannique pour homosexualite). Sa rehabilitation posthume inclut des excuses officielles du gouvernement britannique (2009) et la grace royale (2013). Son effigie figure sur le billet de 50 livres sterling depuis 2021. Le prix Turing (ACM, 1966) est le "Nobel de l\'informatique". Ses travaux fondateurs — calculabilite, test de Turing, morphogenese, cryptanalyse — continuent d\'influencer des pans entiers de la recherche. La machine de Turing reste le standard de reference pour definir ce qu\'est un algorithme, et sa these de 1936 est probablement le papier le plus important de l\'histoire de l\'informatique.</p><div class="highlight-box"><p><strong>Morphogenese et biologie computationnelle :</strong> Les equations de reaction-diffusion de Turing (1952) predisent la formation de motifs biologiques (rayures, taches) par l\'interaction de deux substances chimiques (activateur et inhibiteur). Ces equations ont ete validees experimentalement en 2012 pour la formation des rides sur le palais des souris. Les simulations de morphogenese de Turing sont aujourd\'hui utilisees en biologie developpementale, en cosmetologie (design de motifs), et en architecture biomimetique. C\'est l\'une des contributions les plus surprenantes de l\'informatique a la biologie — issue directement du fondateur de la calculabilite.</p></div>'

SYNTHESES['logique-predicats/modeles'] = '<h3>Theorie des modeles et geometrie algebrique</h3><p class="resume-text">L\'application la plus spectaculaire de la theorie des modeles moderne en mathematiques est la preuve par Hrushovski de la conjecture de Mordell-Lang (1996) : sur un corps algebriquement clos, l\'intersection d\'un sous-groupe d\'un groupe algebrique avec une sous-variete est une reunion finie de translates de sous-groupes. La preuve utilise la theorie des modeles stables (structures de "pseudo-finitude" derivees de la theorie des corps algebriquement clos) pour reduire un probleme de geometrie algebrique a un probleme de theorie des modeles, puis pour le resoudre. Cette preuve improbable etonne encore les mathematiciens par sa methode radicalement non standard.</p><div class="highlight-box"><p><strong>ACFA et geometrie diophantienne :</strong> ACFA (algebrically closed fields with automorphism) est la theorie model-theorique des corps munis d\'un automorphisme de Frobenius. Sa theorie est omega-stable (par Chatzidakis et Hrushovski, 1999), permettant d\'appliquer les outils de la stabilite. Des applications en geometrie diophantienne (conjecture de Manin-Mumford, prouvee par Hrushovski via ACFA) et en dynamique arithmetique (orbites de morphismes de Frobenius) montrent que la theorie des modeles n\'est pas seulement une theorie des fondements mais un outil actif de recherche en mathematiques pures.</p></div>'

SYNTHESES['paradoxes/menteur'] = '<h3>Le paradoxe du menteur aujourd\'hui</h3><p class="resume-text">La paradoxe du menteur reste l\'un des problemes philosophiques les plus actifs. La logique de revision de Gupta-Belnap, les logiques paracohérentes de Priest, et la semantique de point fixe de Kripke offrent trois approches incompatibles mais chacune coherente. Le debat porte desormais sur les fondements : doit-on modifier la logique classique (paracohérence), stratifier le langage (Tarski), ou accepter l\'indetetermination (Kripke) ? Des travaux recents (Field 2008, Priest 2006) proposent des theories non-classiques completes ou le paradoxe du menteur est traitable — mais au prix de modifications substantielles de la logique et des mathematiques ordinaires.</p><div class="highlight-box"><p><strong>Semantique des LLMs :</strong> Un grand modele de langage qui dit "cette phrase que je genere est fausse" produit un paradoxe pragmatique : il genere et evalue simultanement la phrase. Les LLMs semblent capables de detecter les paradoxes du menteur dans des contextes clairs, mais echouent sur des versions deguisees. Cette fragilite suggere qu\'ils n\'ont pas de theorie metalinguistique robuste — contrairement a la hierarchie de Tarski qui traite explicitement les niveaux de langage. Comprendre comment les LLMs traitent l\'autoreference semantique est une question ouverte en interpretabilite et securite de l\'IA.</p></div>'

SYNTHESES['paradoxes/russell'] = '<h3>Fondements modernes : ZFC, HoTT et types</h3><p class="resume-text">Aujourd\'hui, les mathematiques ordinaires sont formalisees dans ZFC, dont la coherence est generalement acceptee (bien que non prouvable dans ZFC lui-meme). La theorie des types de Martin-Lof (MLTT) et sa variante Homotopy Type Theory (HoTT) offrent une alternative foundationnelle ou les paradoxes de type Russell sont evites par construction (les types sont stratifies). L\'axiome d\'univalence de Voevodsky (deux types isomorphes sont propositionnellement egaux) resoud des questions de canonicite qui embarrassaient ZFC (quel modele des entiers utiliser ?). HoTT est completement formalisee dans Agda et partiellement dans Lean, materialisant une alternative viable a ZFC pour les fondements.</p><div class="highlight-box"><p><strong>Homotopy Type Theory :</strong> En HoTT, les identites sont les chemins dans des espaces topologiques. Deux preuves du meme theoreme sont "egales" si elles sont connectees par un homotopie. L\'axiome d\'univalence dit que les structures isomorphes sont definitionnellement egales — eliminant la question "quelle implementation specifique des entiers utilisons-nous ?" car toutes les implementations isomorphes sont la meme chose. Ce fondement alternatif a ZFC evite entierement le paradoxe de Russell tout en etant suffisamment riche pour formaliser l\'algebre et l\'analyse modernes.</p></div>'

SYNTHESES['logique-propositionnelle/tautologies'] = '<h3>Tautologies en IA et apprentissage</h3><p class="resume-text">Les tautologies jouent un role dans l\'apprentissage automatique via la logique tensorielle et les reseaux de neurones symboliques. Les reseaux de neurones pour la satisfaction propositionnelle (NeuroSAT, Selsam et al., 2019) apprennent a predire la satisfaisabilite d\'une formule en FNC directement a partir des clauses, sans aucune heuristique manuelle. Ils generalisent sur des familles de problemes et servent de guides pour les solveurs CDCL en suggerant des affectations initiales prometteuses. Des variantes hybrides (combinant apprentissage et resolution) atteignent des performances competitives sur des benchmarks industriels, ouvrant la voie a des solveurs SAT apprenants.</p><div class="highlight-box"><p><strong>Preuves automatiques en geometrie :</strong> Le systeme GEX (Coelho et Dufourd, 2011) prouve automatiquement des theoremes de geometrie euclidienne par la methode des coordonnees et la reduction a des tautologies propositionnelles. Des theoremes comme "les angles d\'un triangle somment a pi" ou "les medianes se croisent au barycentre" sont reduits a des verifications algebriques de tautologies. Cette approche, directement fondee sur les tautologies de Boole, permet de verifier automatiquement les exercices geometriques des lycees — une application pedagogique concrete des tautologies de la logique formelle.</p></div>'

SYNTHESES['logique-propositionnelle/formes-normales'] = '<h3>FNC et resolveurs modernes</h3><p class="resume-text">Le concours annuel SAT Competition (depuis 2002) mesure les progres des solveurs SAT sur des benchmarks industriels en FNC Tseitin. Les meilleures performances actuelles (CaDiCaL, Kissat, Glucose) resolvent des instances avec des millions de variables en quelques secondes. Les techniques d\'apprentissage de clauses (CDCL) ont ete ameliorees par le LBD (Literal Block Distance, Audemard et Simon, 2009) qui qualifie les clauses apprises par leur "cohesion", permettant une gestion plus intelligente de la base de clauses. Des extensions comme PB-SAT (pseudo-boolean), MaxSAT (optimisation), et #SAT (comptage) generalisent la FNC standard aux problemes d\'optimisation et de comptage, avec des applications en bioinformatique et en cryptanalyse.</p><div class="highlight-box"><p><strong>Cryptanalyse et SAT :</strong> De nombreuses attaques cryptographiques se reduisent a des problemes SAT sur des formules en FNC Tseitin. La factorisation d\'un entier RSA-512 a ete encodee en SAT et partiellement resolue (Jovanovic et Janicic, 2012) bien que de taille insuffisante pour menacer RSA-2048. Les tests de resistance des S-boxes de l\'AES contre les attaques differentielles et lineaires sont verifiables par des solveurs SAT. La FNC Tseitin transforme des questions de cryptographie en problemes combinatoires que les solveurs explorent plus efficacement que la recherche exhaustive.</p></div>'

SYNTHESES['logique-predicats/quantificateurs'] = '<h3>Quantificateurs en verification de programmes</h3><p class="resume-text">La logique de separation (O\'Hearn, Reynolds, Yang, 2001) etend le premier ordre avec un operateur de "conjonction separante" (A * B : A et B valides sur des parties disjointes de la memoire). Les formules de separation avec quantificateurs permettent de specifier les structures de donnees recursives (listes, arbres, graphes) de maniere modulaire. La separation logic est la base de l\'analyse Infer (Facebook/Meta, 2015) et de ses derivees (Google Kani, AWS Dafny). Infer detecte des centaines de bugs de memoire par jour dans les bases de code de Facebook, Instagram, WhatsApp — applications directes des quantificateurs de la logique du premier ordre combines aux operateurs de separation.</p><div class="highlight-box"><p><strong>Infer et Facebook :</strong> Infer (Calcagno, Distefano, 2015) analyse incrementalement les changements de code et detecte des bugs de null-dereference, de fuite de memoire, et de race condition en quelques secondes, integre dans le pipeline CI/CD. Il a detecte des dizaines de milliers de bugs dans les applications iOS et Android de Facebook avant leur deploiement. Son algorithme est une abstraction de la separation logic avec des invariants inductifs sur les quantificateurs de tas. C\'est l\'application industrielle la plus massive de la logique du premier ordre avec quantificateurs a la verification de code de production.</p></div>'

SYNTHESES['logique-propositionnelle/propositions'] = '<h3>Propositions et langages formels</h3><p class="resume-text">Les formules propositionnelles sont aussi la base de la logique temporelle lineaire LTL et de la logique arborescente CTL, utilisees pour la verification de systemes reactifs. Une formule LTL G(p → Fq) (toujours, si p alors finalement q) peut etre traduite en automate de Büchi, permettant la verification par model checking. Les outils SPIN (Bell Labs, Holzmann) et NuSMV (CMU, FBK-irst) utilisent cette reduction pour verifier des protocoles concurrents. La logique propositionnelle est ainsi le noyau commun a toutes ces extensions, dont les connecteurs additionnels (G, F, X, U) s\'ajoutent au substrat booleen pour exprimer des proprietes temporelles.</p><div class="highlight-box"><p><strong>SPIN et protocoles :</strong> SPIN (Gerard Holzmann, Bell Labs) a ete utilise pour verifier les protocoles de communication du programme spatial Deep Space 1 de NASA, les protocoles de bus de terrain industriels, et des composants du noyau Linux. Sa logique de specification (Promela + LTL) est directement fondee sur la logique propositionnelle etendue avec operateurs temporels. Les proprietes comme "le systeme ne se bloque jamais" (absence de deadlock) se traduisent en formules LTL que SPIN verifie exhaustivement sur un modele du systeme.</p></div>'

SYNTHESES['logique-predicats/variables-termes'] = '<h3>Termes et representation de la connaissance</h3><p class="resume-text">Les termes du premier ordre sont la base de la representation de la connaissance en logique. Les langages de frames (KL-ONE, 1977), les logiques de description (DL, 1985), et OWL (Web Ontology Language, 2004) sont tous des fragments du premier ordre avec des termes et des predicats. Wikidata (2012) contient 100 millions d\'items representes comme des termes avec des proprietes-predicats ; SPARQL les interroge via des formules du premier ordre. Les moteurs de recherche semantiques (Google Knowledge Graph, 2012) utilisent des schemas de type OWL pour comprendre les requetes en langage naturel — directement les variables et termes de la logique du premier ordre sous-tendant le raisonnement automatique.</p><div class="highlight-box"><p><strong>Knowledge Graphs et IA :</strong> Les graphes de connaissances (Freebase, Wikidata, DBpedia) stockent des milliards de faits sous forme de triplets (sujet, predicat, objet) — exactement les formules atomiques R(t₁, t₂) du premier ordre. Le raisonnement sur ces graphes (inforence de liens, completion de KB) utilise des techniques comme TransE, RotatE (apprentissage de plongements de termes) qui apprennent implicitement des regularites correspondant aux axiomes de la logique du premier ordre. Les LLMs recents integrent des graphes de connaissances pour ameliorer leur factualite et leur raisonnement — fusionnant apprentissage statistique et representatin logique.</p></div>'

SYNTHESES['preuves-formelles/recurrence'] = '<h3>Induction et preuves de programmes</h3><p class="resume-text">La logique de Floyd-Hoare (Floyd 1967, Hoare 1969) formalise les preuves de correction de programmes par des invariants de boucle — une forme d\'induction sur le nombre d\'iterations. Trouver l\'invariant est generalement la partie creative de la preuve. Les outils de synthese d\'invariants (Daikon, Houdini) inferent automatiquement des invariants candidats a partir de traces d\'execution ou de templates predefined. Les solveurs SMT verifient ensuite ces invariants. Cette approche semi-automatique permet de verifier des programmes industriels en un temps raisonnable, alliant la puissance de la recurrence formelle a la capacite des machines a verifier mecaniquement les details.</p><div class="highlight-box"><p><strong>VeriFast et separation :</strong> VeriFast (Jacobs et al., KU Leuven) est un verificateur deductif pour C et Java base sur la separation logic et la recurrence structurelle. Il a ete utilise pour verifier le systeme de fichiers en boucle du kernel Linux, des protocoles de communication embarques, et des algorithmes de structure de donnees concurrents. Chaque preuve VeriFast est une preuve par recurrence structurelle sur la structure des donnees, verifiee par un solveur SMT. Cette chaine — recurrence formelle, separation logic, SMT — est representatif de l\'etat de l\'art de la verification de logiciels critiques.</p></div>'

SYNTHESES['preuves-formelles/absurde'] = '<h3>Absurde et verification</h3><p class="resume-text">La preuve par l\'absurde est omnipresente dans la verification formelle. Prouver qu\'un systeme n\'a pas de deadlock se fait souvent par l\'absurde : supposer qu\'un deadlock existe, construire un chemin menant a ce deadlock dans le modele du systeme, et montrer que ce chemin implique une violation d\'un invariant — contradiction. Les model checkers (SPIN, NuSMV) explorent tous les contre-exemples possibles pour une propriete de surete, c\'est-a-dire les chemin par l\'absurde. Si aucun contre-exemple n\'existe, la propriete est prouvee — un raisonnement entierement base sur la recherche exhaustive de contradictions.</p><div class="highlight-box"><p><strong>CEGAR et raffinement :</strong> Counterexample-Guided Abstraction Refinement (CEGAR, Clarke et al., 2000) est une technique de verification qui utilise les contre-exemples (preuves par l\'absurde echouees) pour raffiner l\'abstraction du systeme. Si un faux contre-exemple est trouve (un chemin dans l\'abstraction qui n\'existe pas dans le systeme concret), il est utilise pour affiner l\'abstraction — la rendant plus precise pour eliminer ce faux positif. Ce cycle iteratif d\'abstraction et de raffinement est l\'outil dominant de la verification automatique de logiciels et materiel modernes, directement fonde sur le raisonnement par l\'absurde.</p></div>'

SYNTHESES['preuves-formelles/deduction-naturelle'] = '<h3>Assistants de preuve et deduction automatisee</h3><p class="resume-text">Les assistants de preuve interactifs modernes (Coq, Lean 4, Isabelle/HOL, Agda) implemenent la deduction naturelle de Gentzen avec des extensions (types dependants, induction, coinduction). L\'utilisateur guide la preuve par des "tactiques" qui appliquent des regles de deduction naturelle : intro pour introduire une implication, apply pour appliquer un lemme (modus ponens), induction pour l\'induction structurelle, simp pour la simplification par reecriture. Les prouveurs automatiques (omega, ring, linarith, nlinarith, norm_num) decidennt automatiquement des sous-buts arithmetiques en invoquant des solveurs SMT. Cette collaboration homme-machine realise le programme de Gentzen dans un outil quotidien de recherche.</p><div class="highlight-box"><p><strong>Lean et mathematiques de recherche :</strong> Le theoreme de Fermat-Wiles (1995, "le dernier theoreme de Fermat") a ete formalisee dans Lean 4 par un groupe international en 2024. Cette preuve, longue de 200 pages dans la version originale de Wiles, a ete traduite en quelques milliers de lignes de deduction naturelle Lean verifiees mecaniquement. Cet accomplissement — probablement le theoreme le plus difficile jamais formalisee — montre que la deduction naturelle de Gentzen (1935) est aujourd\'hui un outil pratique pour la mathematique de pointe.</p></div>'

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
count = 0
for key, extra in SYNTHESES.items():
    if key in pages:
        old_len = len(pages[key]['content'])
        if old_len < 15000:
            content = pages[key]['content']
            quiz_start = content.find('<section class="content-section" id="quiz">')
            if quiz_start != -1:
                pages[key]['content'] = content[:quiz_start] + extra + content[quiz_start:]
            else:
                idx = content.rfind('</section>')
                if idx != -1:
                    pages[key]['content'] = content[:idx] + extra + content[idx:]
                else:
                    pages[key]['content'] = content + extra
            new_len = len(pages[key]['content'])
            print(f"  {key}: {old_len} -> {new_len}")
            count += 1

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone: {count} articles enriched.")
