#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrichit tous les articles de mythologie.json en ajoutant du contenu
avant la section id="quiz".
"""

import json
import re

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/mythologie.json'
QUIZ_MARKER = '<section class="content-section" id="quiz">'

ENRICHMENTS = {
    'mythologies-antiques/mythologie-grecque': """<h3>L'Olympe et le panthéon grec</h3>
<p class="resume-text">Les douze dieux olympiens forment la cour divine par excellence : Zeus (roi des dieux, maître de la foudre), Héra (reine, déesse du mariage), Poséidon (dieu des mers), Déméter (déesse des moissons), Athéna (déesse de la sagesse et de la guerre), Apollon (dieu du soleil, des arts et de la prophétie), Artémis (déesse de la chasse), Arès (dieu de la guerre), Aphrodite (déesse de l'amour), Héphaïstos (dieu du feu et de la forge), Hermès (messager des dieux) et Dionysos (dieu du vin et de l'extase). Ce panthéon reflète les valeurs et les tensions de la société grecque archaïque.</p>
<p class="resume-text">Les dieux grecs sont anthropomorphes et profondément humains dans leurs passions : ils s'aiment, se jalousent, se vengent, mentent et interviennent dans les affaires humaines. Cette proximité avec les hommes distingue la religion grecque des religions orientales, où le divin est souvent plus transcendant et mystérieux. Zeus lui-même est soumis au destin (Moïra), et les dieux ne peuvent s'y soustraire.</p>
<div class="highlight-box"><p>L'Oracle de Delphes, consacré à Apollon, était le plus célèbre sanctuaire de Grèce. Ses prophéties ambiguës ont orienté des décisions politiques et militaires pendant des siècles. La formule inscrite au fronton du temple — « Connais-toi toi-même » — résume l'idéal éthique grec.</p></div>
<h3>Héros, Travaux et épopées</h3>
<p class="resume-text">Héraclès (Hercule pour les Romains) est le héros grec par excellence. Ses douze travaux — tuer le lion de Némée, capturer le taureau de Crète, dérober les pommes d'or des Hespérides — représentent le triomphe de la raison humaine sur les forces animales et cosmiques. Chaque travail est une métaphore de la maîtrise de soi et de la vertu héroïque.</p>
<p class="resume-text">Ulysse (Odyssée) incarne un autre idéal : la ruse, l'intelligence pratique (mètis) et la résistance aux épreuves. Son voyage de retour vers Ithaque, parsemé de rencontres avec Circé, les Cyclopes, les Sirènes et Charybde et Scylla, est une méditation sur la tentation, la fidélité et la quête de l'identité. L'Iliade et l'Odyssée d'Homère constituent le socle de toute la littérature occidentale.</p>
<div class="highlight-box"><p>Les Tragiques grecs — Eschyle, Sophocle, Euripide — ont réinterprété les mythes pour en faire des explorations de la condition humaine. Œdipe qui tue son père et épouse sa mère sans le savoir, Médée qui assassine ses propres enfants par vengeance : ces figures illustrent la démesure (hubris) que punit inexorablement le destin.</p></div>
<h3>Cosmogonie et eschatologie</h3>
<p class="resume-text">La Théogonie d'Hésiode raconte la naissance des dieux et de l'ordre cosmique. Au commencement était le Chaos, puis Gaïa (la Terre), Éros (l'Amour), le Tartare et l'Érèbe. De Gaïa et Ouranos (le Ciel) naissent les Titans, puis Zeus renverse son père Cronos pour établir l'ordre olympien. Ce récit de succession dynastique — Ouranos, Cronos, Zeus — illustre une vision cyclique et conflictuelle du pouvoir.</p>
<p class="resume-text">Les Enfers grecs (Hadès) sont un monde complexe et nuancé. Les âmes des défunts traversent le Styx sur la barque de Charon, et selon leurs actions, elles sont jugées par Minos, Éaque et Rhadamanthe. Les Champs Élysées accueillent les héros vertueux, le Tartare punit les grands criminels, et l'asphodèle reçoit les âmes ordinaires. Ce jugement moral des morts est une innovation majeure de la pensée grecque.</p>
<h3>Héritage dans la culture occidentale</h3>
<p class="resume-text">La mythologie grecque a imprégné l'art occidental depuis la Renaissance. Botticelli peint la naissance de Vénus, Rubens les enlèvements mythologiques, Wagner compose des opéras inspirés des traditions nordiques et antiques. La psychanalyse freudienne s'empare des mythes : le complexe d'Œdipe, les pulsions dionysiaques, la figure du héros solaire (Jung avec ses archétypes) les mobilise pour cartographier l'inconscient humain.</p>
<p class="resume-text">Aujourd'hui, du cinéma d'Hollywood aux jeux vidéo, les dieux et héros grecs restent présents dans l'imaginaire mondial. Percy Jackson, Wonder Woman, God of War : la vitalité de ces mythes tient à leur capacité à incarner des conflits universels — amour et mort, liberté et destin, orgueil et sagesse. Ils constituent un langage symbolique partagé par des milliards d'êtres humains à travers les siècles.</p>""",

    'mythologies-antiques/mythologie-romaine': """<h3>Adoption et transformation du panthéon grec</h3>
<p class="resume-text">La mythologie romaine est souvent décrite comme dérivée du grec, mais cette vision simpliste masque une réalité plus complexe. Rome avait ses propres divinités archaïques — Janus (dieu des commencements et des portes), Saturne (dieu de l'agriculture et du temps), les Lares et Pénates (dieux du foyer domestique) — avant d'adopter les dieux grecs. Cette appropriation s'effectue à partir du IIIe siècle av. J.-C. par un processus d'interpretatio romana : chaque dieu grec est identifié à un équivalent romain.</p>
<p class="resume-text">Jupiter (Zeus), Junon (Héra), Minerve (Athéna) constituent la triade capitoline, coeur du culte civique romain. Mars n'est pas seulement un dieu de la guerre mais aussi un protecteur de l'agriculture ; Mercure est le dieu du commerce autant que des voyageurs. Ces nuances témoignent d'une adaptation des mythes aux valeurs pratiques de la société romaine.</p>
<div class="highlight-box"><p>Le culte impérial romain transforme les empereurs divinisés en personnages mythologiques : Auguste est présenté comme un descendant de Vénus et d'Énée. L'Énéide de Virgile légitime cette généalogie divine en reliant Troie à Rome par l'intermédiaire du héros troyen Énée.</p></div>
<h3>Romulus, Rémus et la fondation de Rome</h3>
<p class="resume-text">Le mythe fondateur romain raconte la naissance miraculeuse de jumeaux — Romulus et Rémus — d'une vestale et du dieu Mars. Abandonnés sur les rives du Tibre, ils sont allaités par une louve avant d'être recueillis par un berger. Adultes, ils fondent une nouvelle cité, mais un conflit éclate sur son emplacement : Romulus tue Rémus et donne son nom à Rome.</p>
<p class="resume-text">Ce mythe de fratricide fondateur est riche de sens : il justifie la violence nécessaire à toute fondation politique, ancre la cité dans le sacré (le fondateur est fils d'un dieu) et établit l'autorité du premier roi. Les historiens modernes voient dans ce récit la trace de conflits entre factions lors de la fondation historique de Rome au VIIIe siècle av. J.-C.</p>
<div class="highlight-box"><p>L'enlèvement des Sabines — où les premiers Romains enlèvent les femmes du peuple voisin pour assurer la pérennité de leur cité — est un mythe qui justifie l'expansion de Rome par la nécessité biologique. Il illustre la tension entre violence fondatrice et intégration des peuples conquis.</p></div>
<h3>Énée et la translatio imperii</h3>
<p class="resume-text">L'Énéide de Virgile (29-19 av. J.-C.) construit une généalogie mythique pour Rome en la rattachant à la guerre de Troie. Énée, fils d'Aphrodite/Vénus et du Troyen Anchise, fuit Troie en flammes emportant son père et ses dieux pénates. Après de longues pérégrinations (inspirées de l'Odyssée), il arrive dans le Latium et fonde la lignée dont naîtra Rome.</p>
<p class="resume-text">Cette construction mythologique sert une finalité politique évidente : légitimer le pouvoir d'Auguste en l'ancrant dans un passé héroïque et divin. La romanisation du monde méditerranéen se présente ainsi non comme une conquête brutale mais comme l'accomplissement d'une destinée divine — fatum — inscrite depuis la chute de Troie.</p>
<h3>Cultes à mystères et survivances mythologiques</h3>
<p class="resume-text">Rome fut aussi le lieu d'adoption de nombreux cultes orientaux : Isis et Osiris d'Égypte, Mithra de Perse, Cybèle de Phrygie. Ces cultes à mystères, réservés aux initiés, promettaient une vie après la mort et une relation personnelle avec le divin. Ils préfigurent le christianisme qui finira par les supplanter. Les Saturnales — fêtes en l'honneur de Saturne où l'ordre social était temporairement inversé — survivent dans le carnaval médiéval et modern.</p>""",

    'mythologies-antiques/mythologie-nordique': """<h3>Les sources littéraires : Eddas et sagas</h3>
<p class="resume-text">La mythologie nordique nous est parvenue principalement à travers deux sources islandaises médiévales. L'Edda poétique (ou Edda ancien) est une collection d'hymnes et de poèmes mythologiques compilés vers 1270 mais remontant souvent au Xe-XIe siècle. L'Edda en prose de Snorri Sturluson (vers 1220) est un manuel de poésie scaldique qui présente les mythes de façon systématique.</p>
<p class="resume-text">Ces textes ont été composés après la christianisation de la Scandinavie (Xe-XIe siècle) par des auteurs chrétiens qui cherchaient à préserver un patrimoine culturel tout en l'adaptant à leur vision du monde. Cette tension explique certaines ambiguïtés : des éléments chrétiens se glissent parfois dans des récits préchrétiens, et inversement.</p>
<div class="highlight-box"><p>Les skalds — poètes de cour nordiques — utilisaient un langage poétique très codifié appelé kenning : « cheval de la mer » pour désigner un bateau, « tempête des épées » pour une bataille. Ces métaphores sont souvent fondées sur les mythes et permettent de reconstituer des récits aujourd'hui perdus.</p></div>
<h3>Les Nornes et le destin</h3>
<p class="resume-text">Les Nornes — Urð (le passé), Verðandi (le présent) et Skuld (le futur) — tissent les destins de dieux et d'hommes au pied de Yggdrasil. Contrairement à la conception grecque où le destin est un décret divin immuable, le destin nordique est un tissu vivant façonné par les actes passés. Même les dieux sont soumis au Wyrd, et Odin lui-même ne peut empêcher le Ragnarök.</p>
<p class="resume-text">Cette vision tragique imprègne toute la littérature des sagas : les héros connaissent souvent leur mort à l'avance mais l'affrontent avec courage, car la gloire du combat vaut mieux que la survie dans le déshonneur. C'est l'essence du courage héroïque nordique, que Wagner immortalisera dans son cycle de l'Anneau des Nibelungen au XIXe siècle.</p>
<div class="highlight-box"><p>La Völuspá (Prophétie de la voyante) est le poème mythologique le plus célèbre de l'Edda. Une völva (voyante) y décrit à Odin la création du monde, l'âge d'or, la chute, le Ragnarök et la renaissance d'un monde nouveau — une vision eschatologique d'une puissance poétique extraordinaire.</p></div>
<h3>Héros et Valkyries</h3>
<p class="resume-text">Les Valkyries sont des servantes d'Odin qui parcourent les champs de bataille pour choisir les guerriers morts qui rejoindront le Valhalla. Leur nom signifie « celles qui choisissent les morts ». Dans le Valhalla, les Einherjar (élus) festoient et s'entraînent au combat en attendant le Ragnarök où ils combattront aux côtés des dieux.</p>
<p class="resume-text">Sigurd (Siegfried dans les traditions germaniques) est le héros humain par excellence des sagas nordiques : il tue le dragon Fáfnir, boit son sang et comprend le langage des oiseaux, réveille la Valkyrie Brynhildr endormie par Odin, et est finalement trahi et assassiné. Son destin tragique illustre l'impossibilité d'échapper au Wyrd même pour le plus grand des héros.</p>
<h3>Héritage dans la culture moderne</h3>
<p class="resume-text">La mythologie nordique connaît un renouveau extraordinaire dans la culture contemporaine. Tolkien s'en est directement inspiré pour construire la Terre du Milieu (les Elfes, les Nains, l'arbre-monde). Richard Wagner l'a adaptée dans L'Anneau des Nibelungen (1876). Marvel Comics a popularisé Thor et Loki dans le monde entier. Les jeux vidéo (God of War, Assassin's Creed Valhalla) en font une toile de fond épique.</p>
<p class="resume-text">Cette vitalité tient à la richesse thématique de cette mythologie : le sacrifice de soi pour la connaissance (Odin se pend à Yggdrasil), la trahison fraternelle (Loki et Baldr), le courage devant une mort inévitable, la fin du monde comme renouveau. Ces thèmes universels résonnent dans toutes les cultures et toutes les époques.</p>""",

    'mythologies-antiques/mythologie-egyptienne': """<h3>La cosmogonie héliopolitaine</h3>
<p class="resume-text">La cosmogonie héliopolitaine place Atoum (ou Rê-Atoum) au centre de la création : émergeant de l'océan primordial Noun, il crée Shou (l'air) et Tefnout (l'humidité) par expectoration. De Shou et Tefnout naissent Geb (la Terre) et Nout (le Ciel), puis Osiris, Isis, Seth et Nephthys. Chaque ville égyptienne avait sa propre cosmogonie : à Hermopolis, huit dieux primordiaux (l'Ogdoade) créent le monde ; à Memphis, le dieu Ptah crée par la parole et la pensée.</p>
<p class="resume-text">Le soleil effectue chaque nuit une traversée des Enfers (Douat) dans sa barque avant de renaître à l'aube sous le nom de Khepri (le scarabée, symbole de renaissance). Cette victoire perpétuelle de la vie sur la mort symbolise le renouveau quotidien du cosmos. La lutte nocturne contre le serpent Apophis — personnification du chaos — est remportée chaque nuit par Rê, garantissant le retour de l'aube.</p>
<div class="highlight-box"><p>La Maât — concept fondamental de la civilisation égyptienne — désigne à la fois la vérité, la justice et l'ordre cosmique. Le pharaon est le garant de la Maât : ses victoires militaires, ses constructions monumentales et ses rites religieux maintiennent l'ordre du monde contre les forces du chaos.</p></div>
<h3>Le cycle d'Osiris</h3>
<p class="resume-text">Le mythe d'Osiris est le récit fondateur de la religion égyptienne. Osiris, roi juste et civilisateur, est assassiné et démembré par son frère Seth, dieu du chaos. Sa sœur et épouse Isis réunit les morceaux de son corps, le ressuscite temporairement et conçoit Horus, l'héritier légitime. Osiris devient alors le maître du royaume des morts.</p>
<p class="resume-text">Horus affronte Seth dans de longs combats mythiques — les « Querelles d'Horus et de Seth » — qui symbolisent la lutte perpétuelle entre l'ordre et le chaos. La victoire de Horus restaure l'ordre cosmique. Le pharaon vivant est assimilé à Horus, le pharaon mort à Osiris : cette identification divine structure toute la conception royale égyptienne.</p>
<div class="highlight-box"><p>Le mythe d'Osiris a influencé de nombreuses traditions méditerranéennes. Les cultes à mystères gréco-romains d'Isis se répandirent dans tout le monde romain. Des parallèles ont été tracés avec la résurrection chrétienne, bien que ces comparaisons soient aujourd'hui nuancées par les historiens des religions.</p></div>
<h3>Le Livre des Morts et l'au-delà</h3>
<p class="resume-text">Les Égyptiens croyaient que l'âme du défunt (composée du Ka, du Ba et de l'Akh) devait traverser un jugement dans la salle des Deux-Maât. Le cœur du mort était pesé contre la plume de Maât. Si le cœur était plus lourd que la plume, Ammout, la dévoreuse (lion-hippopotame-crocodile), le détruisait. Si la balance s'équilibrait, le défunt accédait au paradis de l'Aaru.</p>
<p class="resume-text">Le Livre des Morts (plus exactement « Livre de la sortie vers le jour ») est une collection de formules magiques et d'hymnes glissés dans les tombeaux pour guider le défunt. Ces textes témoignent d'une réflexion élaborée sur la morale, la justice et la destinée de l'âme. Le chapitre 125, la « Confession négative », liste 42 péchés que le mort affirme ne pas avoir commis — un véritable code éthique de la vie juste.</p>
<h3>Art, architecture et mythologie</h3>
<p class="resume-text">Les pyramides sont des machines cosmiques : leur forme reproduit le monticule primordial (la Ben-Ben) qui a émergé des eaux de Noun au commencement. Les temples reproduisent le cosmos avec leur structure concentrique allant de l'espace ouvert (la cour) à l'obscurité du sanctuaire où réside la statue du dieu. Les hiéroglyphes sont eux-mêmes des images sacrées : écrire un dieu, c'est l'invoquer.</p>""",

    'mythologies-antiques/mythologie-mesopotamienne': """<h3>L'Épopée de Gilgamesh</h3>
<p class="resume-text">L'Épopée de Gilgamesh est l'une des plus anciennes œuvres littéraires de l'humanité. Gilgamesh, roi d'Uruk, est décrit comme deux tiers divin et un tiers humain. L'envoi d'Enkidu — son double sauvage — par les dieux pour le calmer se transforme en amitié profonde. Ensemble, ils accomplissent des exploits : tuer le géant Humbaba dans la forêt de cèdres, terrasser le Taureau céleste envoyé par Ishtar.</p>
<p class="resume-text">La mort d'Enkidu plonge Gilgamesh dans le deuil et la prise de conscience de sa propre mortalité. Il part alors à la recherche de l'immortalité, traverse les eaux de la mort pour rencontrer Uta-Napishtim, le seul mortel à avoir obtenu la vie éternelle. Uta-Napishtim lui révèle l'emplacement d'une plante d'immortalité que Gilgamesh trouve mais se fait voler par un serpent. Gilgamesh rentre à Uruk, les mains vides mais reconcilié avec sa condition mortelle.</p>
<div class="highlight-box"><p>L'Épopée de Gilgamesh contient l'un des récits de Déluge les plus anciens : Uta-Napishtim raconte comment les dieux décidèrent d'inonder la terre et comment il construisit un bateau pour sauver sa famille et les animaux. Les parallèles avec le Déluge biblique de Noé sont frappants et témoignent d'une transmission culturelle entre Mésopotamie et monde hébreu.</p></div>
<h3>La descente d'Inanna aux Enfers</h3>
<p class="resume-text">L'un des mythes sumériens les plus fascinants raconte la descente d'Inanna, reine du ciel, dans le monde souterrain gouverné par sa sœur Ereshkigal. À chacune des sept portes des Enfers, Inanna est dépouillée d'un attribut de sa puissance — couronne, parure, vêtements — jusqu'à ce qu'elle comparaisse nue devant sa sœur, qui la condamne à mort.</p>
<p class="resume-text">Sa servante Ninshubur alerte les dieux, et Enki crée deux êtres androgynes chargés de la ranimer avec la nourriture et l'eau de vie. Inanna revient du royaume des morts, mais les lois infernales exigent qu'un substitut prenne sa place : ce sera son époux Dumuzi, qui descend à son tour aux Enfers pour six mois de l'année, expliquant ainsi le rythme des saisons.</p>
<div class="highlight-box"><p>La descente d'Inanna est l'un des premiers mythes de mort et de résurrection connus, illustrant la cyclicité de la nature et la puissance des divinités féminines dans le monde mésopotamien. Cette structure narrative — descente, mort symbolique, résurrection — se retrouvera dans de nombreuses autres traditions.</p></div>
<h3>L'Enuma Elish et la création</h3>
<p class="resume-text">L'Enuma Elish (« Quand en haut... ») est l'épopée de création babylonienne récitée lors de la fête du Nouvel An. Au commencement, seuls existaient Apsu (les eaux douces) et Tiamat (les eaux salées, chaos marin primordial). De leur mélange naissent les premiers dieux. Marduk, champion des dieux de Babylone, tue Tiamat, divise son corps en deux pour créer le ciel et la terre, et crée les hommes avec le sang d'un dieu rebelle pour qu'ils servent les dieux.</p>
<p class="resume-text">Ce mythe légitime la suprématie de Babylone et de son dieu tutélaire Marduk : la création du monde est présentée comme une victoire de l'ordre babylonien sur le chaos. Les tablettes d'argile découvertes à Ninive, Nippur et Ur ont révélé un univers littéraire d'une richesse insoupçonnée. Les travaux de déchiffrement du cunéiforme au XIXe siècle ont permis de redécouvrir ce patrimoine fondateur.</p>""",

    'grandes-religions/christianisme': """<h3>La théologie du salut et la Trinité</h3>
<p class="resume-text">Le christianisme repose sur la conviction que Jésus de Nazareth est le Fils de Dieu incarné, mort sur la croix pour le salut de l'humanité et ressuscité trois jours après. Cette sotériologie (théologie du salut) est le cœur de la foi chrétienne : la mort rédemptrice du Christ réconcilie l'humanité pécheresse avec Dieu. La résurrection est la preuve de la victoire sur la mort et la promesse de la résurrection des morts à la fin des temps.</p>
<p class="resume-text">La doctrine de la Trinité — Dieu est un en trois personnes (le Père, le Fils et le Saint-Esprit) — a été formulée progressivement lors des conciles œcuméniques des IVe et Ve siècles. Le concile de Nicée (325) condamne l'arianisme (qui niait la divinité pleine du Christ) et formule le Credo de Nicée, encore récité dans la liturgie catholique et orthodoxe. Ces débats théologiques ont mobilisé toute l'intelligence philosophique de l'Antiquité tardive.</p>
<div class="highlight-box"><p>Saint Paul, apôtre et théologien, a joué un rôle décisif dans la transformation du mouvement juif de Jésus en religion universelle. Ses épîtres — Galates, Romains, Corinthiens — développent une théologie de la grâce, de la foi et de la liberté chrétienne qui demeure fondatrice pour le protestantisme.</p></div>
<h3>Les grandes traditions chrétiennes</h3>
<p class="resume-text">Le Grand Schisme de 1054 divise le christianisme en Église catholique romaine (fidèle à Rome) et Église orthodoxe (dont le centre est Constantinople). Les différences portent sur la procession du Saint-Esprit (le Filioque), l'autorité du pape et certaines pratiques liturgiques. Les Croisades et les conquêtes de Constantinople par les Ottomans (1453) approfondissent le fossé entre les deux traditions.</p>
<p class="resume-text">La Réforme protestante du XVIe siècle (Luther, Calvin, Zwingli) remet en cause l'autorité de Rome, le rôle des saints, le purgatoire et les indulgences. Luther affirme le principe du « sola scriptura » (la Bible seule fait autorité), « sola fide » (le salut par la foi seule) et « sola gratia » (le salut par la grâce de Dieu seule). Ces divisions ont profondément marqué l'histoire politique et culturelle de l'Europe.</p>
<div class="highlight-box"><p>Le concile Vatican II (1962-1965) est un tournant décisif pour le catholicisme : réforme de la liturgie (messe en langues vernaculaires), dialogue œcuménique avec les autres religions chrétiennes, reconnaissance de la liberté religieuse. Ces réformes suscitent encore des débats dans l'Église catholique.</p></div>
<h3>L'art et la culture chrétienne</h3>
<p class="resume-text">Le christianisme a produit un patrimoine artistique et intellectuel d'une richesse incomparable : les cathédrales gothiques, la Pietà de Michel-Ange, les Passions de Bach, la Divine Comédie de Dante, la philosophie scolastique de Thomas d'Aquin. La Bible a été le livre le plus traduit, imprimé et diffusé de l'histoire de l'humanité.</p>
<p class="resume-text">Aujourd'hui, le christianisme compte environ 2,4 milliards de fidèles, soit un tiers de l'humanité. Sa géographie s'est déplacée : les chrétiens les plus nombreux vivent désormais en Afrique subsaharienne, en Amérique latine et en Asie du Sud-Est. Les Pentecôtistes et les Évangéliques représentent la branche la plus dynamique, avec une croissance spectaculaire dans les pays du Sud global.</p>""",

    'grandes-religions/judaisme': """<h3>La Torah et l'Alliance</h3>
<p class="resume-text">Le judaïsme est fondé sur l'Alliance (brit) entre Dieu et le peuple d'Israël, scellée par la révélation de la Torah au Sinaï. Cette Alliance est à la fois un engagement divin (Dieu protège et guide son peuple) et une obligation humaine (Israël observe les commandements). La Torah, au sens strict, désigne les cinq premiers livres de la Bible hébraïque (Pentateuque) ; au sens large, elle englobe l'ensemble de la tradition juridique et spirituelle juive.</p>
<p class="resume-text">Les 613 commandements (mitsvot) de la Torah régissent tous les aspects de la vie : alimentation (kashrout), sexualité, commerce, agriculture, rites. Cette omniprésence du droit religieux dans la vie quotidienne est ce qui distingue fondamentalement le judaïsme des autres religions abrahamiques. L'observance des mitsvot n'est pas une contrainte mais une façon de sanctifier le quotidien et d'actualiser constamment l'Alliance avec Dieu.</p>
<div class="highlight-box"><p>Le Talmud — vaste compilation de discussions rabbiniques (IIe-VIe siècle) sur la loi orale — est avec la Bible le texte fondateur du judaïsme rabbinique. Sa méthode dialectique — exposer les opinions contradictoires, les discuter, rarement les trancher — a façonné un mode de pensée qui valorise le questionnement sur la certitude.</p></div>
<h3>Les courants du judaïsme contemporain</h3>
<p class="resume-text">Le judaïsme orthodoxe maintient l'observance stricte de la loi halakhique traditionnelle. Il se subdivise entre le judaïsme « moderne orthodoxe » (qui accepte l'engagement dans la société contemporaine) et le judaïsme ultra-orthodoxe (haredi), qui maintient un mode de vie séparé des influences modernes. Le judaïsme réformé, né en Allemagne au XIXe siècle, adapte la tradition aux conditions de la modernité.</p>
<p class="resume-text">Le mouvement conservateur (ou masorti), né aux États-Unis, cherche une voie médiane entre orthodoxie et réforme. Le judaïsme reconstructionniste, fondé par Mordecai Kaplan, conçoit le judaïsme comme une civilisation évolutive plutôt qu'une révélation divine. Ces différents courants coexistent souvent en tension, notamment sur les questions de la conversion, du mariage et de l'ordination des femmes.</p>
<div class="highlight-box"><p>La Shoah (1941-1945), genocide de six millions de Juifs par le régime nazi, est l'événement traumatique central du judaïsme contemporain. Elle a provoqué une profonde réflexion théologique (où était Dieu ?) et renforcé la centralité de l'État d'Israël, fondé en 1948, dans l'identité juive mondiale.</p></div>
<h3>La mystique juive : Kabbale et hassidisme</h3>
<p class="resume-text">La Kabbale est la tradition mystique du judaïsme. Le Zohar (XIIIe siècle), attribué à Rabbi Shimon bar Yochaï mais probablement composé par Moïse de Léon, est son texte fondamental. La Kabbale développe une théologie complexe des séfirot — dix émanations de Dieu organisées en un arbre cosmique — et une herméneutique qui cherche le sens caché derrière les lettres et les chiffres de la Torah.</p>
<p class="resume-text">Le hassidisme, fondé par le Baal Shem Tov au XVIIIe siècle en Ukraine, est un mouvement de renouveau mystique qui met l'accent sur la joie, la dévotion et l'accessibilité de Dieu à tous, y compris aux plus humbles. Ses récits de rabbins (rebbes) dotés de pouvoirs miraculeux constituent un corpus de littérature populaire d'une grande richesse.</p>""",

    'grandes-religions/hindouisme': """<h3>La diversité de l'hindouisme</h3>
<p class="resume-text">L'hindouisme est moins une religion unifiée qu'une famille de traditions religieuses partageant certains textes sacrés (Vedas, Upanishad, Bhagavad-Gîtâ), des pratiques (puja, yoga, pèlerinage) et des concepts communs (karma, dharma, moksha). Il n'y a pas de fondateur, pas de credo central, pas d'autorité ecclésiastique unique. Cette diversité est précisément ce qui le distingue des religions abrahamiques.</p>
<p class="resume-text">On distingue généralement trois grandes traditions dévotionnelles (bhakti) : le vishnouisme (dévotion à Vishnu et ses avatars, dont Krishna et Rama), le shivaïsme (dévotion à Shiva, dieu de la destruction et de la transformation) et le shaktisme (dévotion à la Déesse-Mère sous ses multiples formes : Durga, Kali, Lakshmi). Ces traditions coexistent pacifiquement, se mêlent localement et partagent de nombreuses pratiques rituelles.</p>
<div class="highlight-box"><p>La Bhagavad-Gîtâ (« Chant du Bienheureux »), extrait du Mahâbhârata, est le texte le plus lu de l'hindouisme. Dans un champ de bataille, le guerrier Arjuna hésite à combattre ses proches. Krishna lui révèle le dharma (devoir), le karma (l'action et ses fruits) et les voies de la libération (jnana-yoga, bhakti-yoga, karma-yoga). Ce texte a inspiré Gandhi, Thoreau, Emerson et des générations de chercheurs spirituels en Occident.</p></div>
<h3>Le cycle cosmique et les avatars de Vishnu</h3>
<p class="resume-text">L'hindouisme conçoit le temps en cycles cosmiques immenses. Un « jour de Brahma » dure 4,32 milliards d'années, une période de création et de dissolution. Quatre yugas (âges) se succèdent dans un cycle déclinant : le Satya-yuga (âge d'or), le Treta-yuga, le Dvapara-yuga et le Kali-yuga (l'âge actuel de déclin). À la fin du Kali-yuga, Vishnu s'incarnera une dernière fois sous la forme de Kalki pour détruire le mal et recommencer le cycle.</p>
<p class="resume-text">Vishnu descend sur terre à chaque âge sous la forme d'un avatar pour restaurer le dharma. Les dix avatars principaux (dashavatara) incluent la tortue, le sanglier, l'homme-lion, le nain, Parashurama (Rama à la hache), Rama (héros de Ramayana), Krishna, Bouddha et Kalki. L'inclusion du Bouddha comme avatar de Vishnu illustre la capacité de l'hindouisme à absorber d'autres traditions religieuses.</p>
<div class="highlight-box"><p>Le temple hindou n'est pas seulement un lieu de culte : c'est une image du cosmos. Son plan reproduit le Mont Méru (montagne cosmique), son tour (shikhara) pointe vers le ciel, et la statue du dieu dans le sanctuaire intérieur (garbhagriha, « chambre du ventre ») reçoit les hommages des fidèles. Construire un temple est en soi un acte de création cosmique.</p></div>
<h3>Les voies de la libération</h3>
<p class="resume-text">Le moksha (libération du cycle des réincarnations) est le but ultime de la vie humaine. Plusieurs voies y mènent : le jnana-yoga (voie de la connaissance), qui consiste à réaliser l'identité de l'atman individuel avec le Brahman universel ; le bhakti-yoga (voie de la dévotion), qui cherche l'union avec Dieu par l'amour et la prière ; le karma-yoga (voie de l'action), qui consiste à agir sans attachement aux fruits de l'action.</p>
<p class="resume-text">Le yoga, dans sa dimension spirituelle, est bien plus que les postures physiques popularisées en Occident. Le Raja-yoga (yoga royal) de Patanjali est un système de discipline mentale en huit membres (ashtanga) visant l'arrêt des fluctuations mentales (chitta vritti nirodha). Cette pratique millénaire a influencé la psychologie moderne et les thérapies de pleine conscience (mindfulness).</p>""",

    'textes-sacres/bible': """<h3>L'Ancien Testament : structure et contenu</h3>
<p class="resume-text">La Bible hébraïque (appelée Tanakh dans la tradition juive) se structure en trois parties : la Torah (les cinq livres de Moïse), les Nevi'im (les prophètes : Josué, Juges, Samuel, Rois, puis Isaïe, Jérémie, Ézéchiel et les douze petits prophètes) et les Ketuvim (les écrits : Psaumes, Proverbes, Job, le Cantique des cantiques, Ruth, Lamentations, Ecclésiaste, Esther, Daniel, Esdras, Néhémie et les Chroniques). Cette partition reflète une hiérarchie de l'inspiration divine.</p>
<p class="resume-text">La composition de la Bible hébraïque s'est étalée sur environ mille ans (du IXe au IIe siècle av. J.-C.). L'hypothèse documentaire, développée par Julius Wellhausen au XIXe siècle, distingue quatre sources dans le Pentateuque : le Yahviste (J), l'Élohiste (E), le Deutéronomiste (D) et le Sacerdotal (P). Cette démarche critique a révolutionné l'étude biblique mais reste débattue.</p>
<div class="highlight-box"><p>Le livre de Job est l'un des textes philosophiques les plus puissants de la Bible : un homme juste est frappé de malheurs sans raison. Le débat avec ses amis théologiens, puis la réponse divine « du fond du tourbillon », pose la question du mal et de la souffrance des innocents avec une radicalité sans équivalent dans les autres textes bibliques.</p></div>
<h3>Le Nouveau Testament et les Évangiles</h3>
<p class="resume-text">Le Nouveau Testament comprend 27 livres, rédigés en grec au premier siècle : quatre Évangiles (Matthieu, Marc, Luc, Jean), les Actes des Apôtres (suite de Luc), quatorze épîtres de Paul, plusieurs épîtres d'autres apôtres, et l'Apocalypse de Jean. Le canon du Nouveau Testament a été fixé progressivement entre le IIe et le IVe siècle.</p>
<p class="resume-text">Les Évangiles synoptiques (Matthieu, Marc, Luc) présentent des récits semblables de la vie de Jésus. L'Évangile de Jean, plus tardif et théologique, s'ouvre sur le Prologue (« Au commencement était le Verbe ») qui identifie Jésus au Logos grec — une synthèse de la pensée hébraïque et de la philosophie hellénistique. Des évangiles non canoniques (Philippe, Thomas, Marie-Madeleine) ont été retrouvés à Nag Hammadi en 1945.</p>
<div class="highlight-box"><p>Le Sermon sur la montagne (Matthieu 5-7) est le discours éthique fondamental du christianisme : les Béatitudes (« Heureux les pauvres en esprit... »), l'amour des ennemis, le Notre Père, l'avertissement contre le jugement d'autrui. Ces enseignements ont inspiré des figures comme François d'Assise, Gandhi et Tolstoï.</p></div>
<h3>La Bible dans la culture occidentale</h3>
<p class="resume-text">La Bible est le livre le plus traduit de l'histoire : elle existe dans plus de 700 langues complètes et des milliers de langues partiellement traduites. La traduction latine de la Vulgate par saint Jérôme (fin IVe siècle) a été le texte de référence pendant mille ans. La traduction de Luther en allemand (1534) a non seulement rendu la Bible accessible au peuple mais contribué à la standardisation de la langue allemande moderne.</p>
<p class="resume-text">L'influence de la Bible sur la littérature, l'art et la musique occidentaux est inépuisable. Milton (Le Paradis perdu), Dante (La Divine Comédie), Shakespeare (ses allusions bibliques innombrables), Bach (les Passions), Haendel (Le Messie), Rembrandt (ses peintures du Vieux Testament) : la Bible a fourni à la civilisation occidentale une grande partie de son imaginaire symbolique.</p>""",

    'textes-sacres/tripitaka': """<h3>Structure du Tipitaka pâli</h3>
<p class="resume-text">Le Tipitaka (« Trois corbeilles ») est le canon scripturaire du bouddhisme theravada, rédigé en pâli, langue apparentée au sanskrit. La première corbeille, le Vinaya Pitaka, contient les règles monastiques : 227 règles pour les moines, 311 pour les nonnes, ainsi que les récits de leur promulgation par le Bouddha. Ces règles couvrent tous les aspects de la vie communautaire (sangha), de l'alimentation au vêtement en passant par la résolution des conflits.</p>
<p class="resume-text">Le Sutta Pitaka (deuxième corbeille) rassemble les discours du Bouddha classés en cinq nikaya (collections). Le Dhammapada (« Sentier de la Dhamma »), l'un des textes les plus populaires, offre 423 versets sur la nature de l'esprit et la pratique éthique. Le Sutta Nipata contient certains des textes les plus anciens, dont l'Atthakavagga qui expose un non-attachement radical à toute doctrine.</p>
<div class="highlight-box"><p>L'Abhidhamma Pitaka est la troisième corbeille, la plus philosophique et la plus aride. Elle analyse les phénomènes mentaux et physiques en catégories fondamentales (dhamma), développant une psychologie et une ontologie bouddhistes d'une précision extrême. Ces textes ont été commentés pendant des siècles par des érudits theravada et constituent le fondement de la philosophie bouddhiste.</p></div>
<h3>Les Jataka et la littérature narrative</h3>
<p class="resume-text">Les Jataka (environ 547 récits) racontent les vies antérieures du Bouddha, illustrant le développement progressif des vertus (paramita) à travers de nombreuses existences. Ces récits — où le futur Bouddha apparaît sous forme d'animal, de dieu ou d'homme — sont parmi les textes les plus lus et les plus illustrés du bouddhisme. Ils constituent un fonds narratif commun à toute l'Asie du Sud et du Sud-Est.</p>
<p class="resume-text">Le Mahayana développa ses propres sutras, non inclus dans le Tipitaka pâli mais vénérés comme parole du Bouddha dans les traditions chinoises, japonaises, coréennes et tibétaines. Le Sutra du Cœur (Hannya Shingyo), récité quotidiennement dans les monastères zen, tient en quelques lignes : « La forme est vide, le vide est forme. » Le Sutra du Lotus (Saddharmapundarika) est le texte fondamental du bouddhisme japonais Tendai et Nichiren.</p>
<h3>Transmission et commentaires</h3>
<p class="resume-text">Le canon pâli aurait été transmis oralement pendant plusieurs siècles avant d'être mis par écrit au Ier siècle av. J.-C. au Sri Lanka. Cette tradition de récitation collective assure une remarquable cohérence textuelle. Buddhaghosa (Ve siècle) est le grand commentateur du Tipitaka pâli : son Visuddhimagga (« Chemin de la purification ») synthétise toute la doctrine theravada et demeure un texte de référence pour les pratiquants d'aujourd'hui.</p>
<p class="resume-text">Les traductions du canon bouddhiste en chinois (IIe-Xe siècle) constituent l'un des plus grands projets de traduction de l'histoire humaine. Xuanzang, moine chinois du VIIe siècle, fit le voyage jusqu'en Inde pour rapporter des textes — son périple inspira le roman classique chinois Le Voyage en Occident (Singe). Ces traductions permirent au bouddhisme de s'adapter aux catégories philosophiques chinoises et de générer de nouvelles traditions.</p>""",

    'spiritualite/mysticisme-chretien': """<h3>Les pères du désert et la mystique orientale</h3>
<p class="resume-text">Le mysticisme chrétien commence avec les Pères du désert (IIIe-Ve siècle) d'Égypte et de Syrie. Antoine le Grand, considéré comme le père du monachisme, s'établit dans le désert égyptien pour fuir le monde et chercher Dieu dans la solitude. Les Apophtegmes des Pères du désert — courtes maximes de sagesse — témoignent d'une spiritualité sobre, centrée sur la vigilance de l'esprit (nepsis) et le combat contre les démons intérieurs.</p>
<p class="resume-text">Pseudo-Denys l'Aréopagite (Ve-VIe siècle) forge le langage de la mystique chrétienne en s'inspirant du néoplatonisme. Sa Théologie mystique décrit un chemin vers Dieu par dé-négation progressive : pour rejoindre l'Un divin, il faut dépasser toutes les images, tous les concepts, même les plus sublimes. Cette voie apophatique influence profondément toute la mystique médiévale orientale et occidentale.</p>
<div class="highlight-box"><p>La prière hésychaste, développée dans le monachisme orthodoxe (Grégoire Palamas, XIVe siècle), utilise la répétition de la « prière de Jésus » (« Seigneur Jésus Christ, Fils de Dieu, aie pitié de moi, pécheur ») synchronisée avec la respiration pour atteindre une paix intérieure (hésychia) et la vision de la lumière divine incréée du Thabor.</p></div>
<h3>La mystique rhénane</h3>
<p class="resume-text">Maître Eckhart (1260-1328), dominicain allemand, est la figure centrale de la mystique rhénane. Ses sermons en langue vulgaire développent une théologie de l'étincelle divine (Fünklein) dans l'âme, point de contact entre l'humain et le divin. L'union mystique consiste à « dépouiller » l'âme de tout ce qui n'est pas Dieu pour que la naissance du Verbe (Gottesgeburt) se produise dans le fond de l'âme.</p>
<p class="resume-text">Ses disciples, Henri Suso et Johannes Tauler, développent ses intuitions dans un sens plus concret et pastoral. Leurs sermons touchent un public large, notamment des communautés de femmes mystiques (béguines). Cette spiritualité du fond de l'âme (Seelengrund) annonce la Réforme luthérienne et influence profondément Hegel, Schelling et la mystique moderne.</p>
<div class="highlight-box"><p>Hildegard von Bingen (1098-1179) est une figure extraordinaire : abbesse, théologienne, compositrice, médecin et mystique, elle a reçu des visions prophétiques dès l'enfance. Son Scivias (« Connais les voies ») illustré de miniatures somptueuses inaugure une tradition de mystique visionnaire et préfigure la grande tradition des béguines rhénanes.</p></div>
<h3>La mystique carmélitaine</h3>
<p class="resume-text">Thérèse d'Avila (1515-1582) et Jean de la Croix (1542-1591) sont les deux grands mystiques du Carmel réformé espagnol. Thérèse décrit dans Le Château intérieur sept demeures concentriques correspondant aux étapes de l'oraison, culminant dans l'union transformante avec Dieu. Son autobiographie (La Vie) est un chef-d'œuvre de la littérature spirituelle et psychologique.</p>
<p class="resume-text">Jean de la Croix exprime l'itinéraire mystique dans des poèmes d'une beauté formelle rare (La Nuit obscure, Le Cantique spirituel) et dans des traités commentant ces poèmes. La nuit obscure de l'âme — période de sécheresse, de doute et d'abandon apparent de Dieu — est selon lui une étape nécessaire de purification avant l'union. Son langage poético-théologique a influencé toute la spiritualité occidentale moderne.</p>""",

    'spiritualite/soufisme': """<h3>Les origines et les premiers maîtres</h3>
<p class="resume-text">Le soufisme (tasawwuf) est la dimension mystique de l'islam, dont les origines remontent aux premiers siècles de l'hégire. Les premiers soufis — Hasan al-Basri (IIe siècle), Rabi'a al-'Adawiyya (mort 801) — étaient des ascètes qui cherchaient une relation personnelle et intime avec Dieu au-delà du simple respect de la loi. Rabi'a est célèbre pour ses poèmes sur l'amour divin pur, dégagé de toute crainte de l'enfer ou espoir du paradis.</p>
<p class="resume-text">Junayd de Baghdad (IXe siècle) développe la doctrine de la fana (annihilation du soi dans Dieu) et du baqa (subsistance en Dieu) qui deviendra centrale dans la théorie soufie. Hallaj (857-922), exécuté pour avoir prononcé « Ana'l-Haqq » (« Je suis la Vérité/Dieu »), incarne le paradoxe de la mystique : l'amour de Dieu peut conduire à dépasser les limites de ce que la théologie légale admet.</p>
<div class="highlight-box"><p>Mawlana Jalal ad-Din Rumi (1207-1273) est le plus grand poète mystique de la langue persane. Son Masnavi (six livres de 25 000 distiques) est souvent appelé « le Coran persan ». Ses poèmes célèbrent l'amour divin comme séparation douloureuse d'avec Dieu et aspiration au retour : « Écoute la flûte de roseau raconter l'histoire des séparations... »</p></div>
<h3>Les confréries soufies (tariqas)</h3>
<p class="resume-text">À partir du XIIe siècle, le soufisme s'organise en confréries (tariqas) structurées autour d'une chaîne initiatique (silsila) remontant au Prophète. Chaque tariqa a ses pratiques propres : la Qadiriyya (fondée par Abd al-Qadir al-Jilani) est la plus répandue en Afrique et en Asie ; la Naqshbandiyya pratique un dhikr silencieux et est influente en Asie centrale et parmi les Kurdes ; la Mawlawiyya (les derviches tourneurs) est fondée par les disciples de Rumi.</p>
<p class="resume-text">Le dhikr (invocation répétée des noms divins ou de formules coraniques) est la pratique centrale du soufisme. Il peut être vocal ou mental, individuel ou collectif, accompagné de musique sacrée (sama') ou de danse. La musique qawwali, popularisée en Occident par Nusrat Fateh Ali Khan, est une forme de sama' de la tradition chishtiyya d'Inde du Nord.</p>
<div class="highlight-box"><p>Ibn Arabî (1165-1240), né à Murcia en al-Andalus, est le théosophe mystique le plus influent de l'islam. Sa doctrine de l'Unité de l'Être (wahdat al-wujud) affirme que seul Dieu existe réellement, et que le monde n'est que la manifestation de ses Noms et Attributs. Cette doctrine panentéiste a été accusée de panthéisme et suscite encore des controverses dans le monde musulman.</p></div>
<h3>Soufisme et culture</h3>
<p class="resume-text">L'influence culturelle du soufisme est considérable. La poésie mystique persane de Hafez, Sa'di, Attar et Rumi a produit des chefs-d'œuvre qui continuent d'être récités et chantés aujourd'hui. L'architecture des couvents soufis (khanqas, zawiyas, tekkes) a enrichi le patrimoine architectural islamique. Les confréries soufies ont joué un rôle décisif dans l'islamisation pacifique de l'Afrique subsaharienne, de l'Anatolie et de l'Asie du Sud-Est.</p>
<p class="resume-text">Dans la modernité, le soufisme attire de nombreux Occidentaux en quête de spiritualité. Inayat Khan a fondé un ordre soufi universel accessible aux non-musulmans. Des écrivains comme Henry Corbin ont fait connaître la pensée Ibn Arabî à un public philosophique. Le soufisme est à la fois un héritage vivant de l'islam classique et une ressource pour le dialogue interreligieux contemporain.</p>""",

    'spiritualite/kabbale': """<h3>Les origines et les textes fondateurs</h3>
<p class="resume-text">La Kabbale (de l'hébreu qabbalah : « réception, tradition ») désigne la tradition mystique ésotérique du judaïsme. Elle se distingue du rationalisme philosophique de Maïmonide et de la tradition rabbinique légaliste en affirmant que la Torah contient des dimensions cachées accessibles par des méthodes d'interprétation spéciales. Les origines de la Kabbale remontent à la littérature hékhaloïte (IIIe-VIIe siècle), qui décrit les ascensions mystiques vers le Trône divin (Merkabah).</p>
<p class="resume-text">Le Sefer Yetzirah (« Livre de la Création »), texte énigmatique attribué à Abraham, décrit la création du monde par les 22 lettres de l'alphabet hébreu et les 10 séfirot (nombres primordiaux). Ces séfirot — Kether (Couronne), Chokhmah (Sagesse), Binah (Intelligence), et ainsi de suite jusqu'à Malkuth (Royaume) — constituent l'arbre de vie, diagramme cosmologique au cœur de la Kabbale.</p>
<div class="highlight-box"><p>Le Zohar (« Livre du Splendeur »), apparu en Espagne au XIIIe siècle et attribué à Rabbi Shimon bar Yochaï, est le texte central de la Kabbale. Écrit en araméen, il prend la forme d'un commentaire midrashique sur la Torah, explorant les dimensions symboliques et mystiques du texte biblique à travers le prisme des séfirot.</p></div>
<h3>La Kabbale de Safed</h3>
<p class="resume-text">Après l'expulsion des Juifs d'Espagne (1492), Safed (en Galilée) devient le centre de la renaissance kabbalistique. Isaac Luria (1534-1572), dit l'Ari (le Lion), développe une théologie kabbalistique nouvelle : le tsimtsoum (contraction de Dieu pour faire place à la création), la shevira (rupture des vases cosmiques qui répand les étincelles divines dans le monde), et le tikun (restauration cosmique que l'homme accomplit par ses actes vertueux).</p>
<p class="resume-text">Cette cosmologie lurianique transforme profondément le judaïsme : chaque acte humain a une dimension cosmique ; observer les commandements contribue à la réparation du monde (tikun olam) ; le mal dans le monde est la conséquence de la rupture des vases. Cette vision dynamique et responsabilisante de l'existence humaine influencera profondément le hassidisme et, plus tard, des courants de théologie juive contemporaine.</p>
<div class="highlight-box"><p>La guematria est la pratique kabbalistique d'interprétation par la valeur numérique des lettres hébraïques. Chaque lettre a une valeur numérique ; les mots de même valeur sont mis en relation. Ainsi, les mots « amour » (ahavah) et « un » (ehad) ont la même valeur (13), ce qui signifie que l'amour est l'essence de l'unité divine.</p></div>
<h3>Influence et diffusion</h3>
<p class="resume-text">La Kabbale chrétienne, développée à la Renaissance par Pic de la Mirandole et Johannes Reuchlin, cherche à réconcilier mystique juive et christianisme. Elle influencera la Rose-Croix, la franc-maçonnerie et l'ésotérisme occidental moderne. Au XXe siècle, Gershom Scholem renouvelle l'étude académique de la Kabbale et révèle sa dimension subversive et anarchisante au cœur du judaïsme.</p>
<p class="resume-text">La Kabbale populaire contemporaine, diffusée notamment par le Centre de la Kabbale à Hollywood (qui a attiré des célébrités comme Madonna), a suscité des controverses dans le monde juif sur les risques de décontextualisation et de commercialisation d'une tradition ésotérique complexe. Elle témoigne néanmoins d'un intérêt croissant pour la spiritualité ésotérique dans les sociétés sécularisées.</p>""",

    'spiritualite/meditation': """<h3>Les techniques méditatives : diversité des traditions</h3>
<p class="resume-text">La méditation désigne un ensemble de pratiques psychomentales visant à modifier les états de conscience et à cultiver des qualités psychologiques (attention, compassion, équanimité). Sa diversité est remarquable : le samatha (méditation de stabilisation) et le vipassana (méditation d'insight) dans le bouddhisme theravada, le zazen du zen japonais, le yoga nidra hindou, la contemplation chrétienne (lectio divina, prière de silence), le dhikr soufi, la méditation transcendantale, le mindfulness clinique.</p>
<p class="resume-text">Ces pratiques partagent certains mécanismes fondamentaux : la focalisation de l'attention (sur la respiration, un mantra, une image), l'observation sans jugement des phénomènes mentaux, et une posture corporelle (assis, couché, en marche) qui favorise l'éveil intérieur. Mais leurs objectifs diffèrent : extinction de l'ego, union à Dieu, insight sur l'impermanence, simple réduction du stress.</p>
<div class="highlight-box"><p>La méditation vipassana, popularisée par S.N. Goenka, consiste à observer systématiquement les sensations corporelles avec équanimité, sans réaction. Cette technique, issue du bouddhisme theravada birman, est pratiquée dans des retraites de dix jours (Noble Silence) dans le monde entier et constitue la base de nombreuses thérapies cognitives modernes.</p></div>
<h3>Neurosciences de la méditation</h3>
<p class="resume-text">Depuis les années 1990, les neurosciences étudient les effets de la méditation sur le cerveau. Les travaux de Richard Davidson (Université du Wisconsin), en collaboration avec le dalaï-lama, ont montré que les méditants experts présentent une activité accrue dans le cortex préfrontal gauche (associé aux émotions positives) et une activité réduite dans l'amygdale (réponse au stress). Les mesures EEG révèlent des ondes gamma de grande amplitude chez les méditants avancés.</p>
<p class="resume-text">Des études sur le cerveau de moines bouddhistes tibétains ayant médité des dizaines de milliers d'heures montrent des modifications structurales : épaississement du cortex insulaire (conscience corporelle), augmentation de la matière grise dans les régions liées à l'attention et à l'empathie. Ces découvertes ont contribué à la légitimation scientifique de la méditation et à son intégration dans la médecine et la psychologie.</p>
<div class="highlight-box"><p>La Mindfulness-Based Stress Reduction (MBSR), développée par Jon Kabat-Zinn à l'Université du Massachusetts dans les années 1970, est le programme de méditation le mieux validé scientifiquement. Il s'inspire du bouddhisme mais se présente de façon laïque et a été intégré dans les protocoles hospitaliers du monde entier pour traiter la douleur chronique, l'anxiété et la dépression.</p></div>
<h3>Méditation et psychologie occidentale</h3>
<p class="resume-text">La rencontre entre la méditation orientale et la psychologie occidentale a produit plusieurs courants thérapeutiques. La thérapie cognitive basée sur la pleine conscience (MBCT) prévient les rechutes dépressives. La thérapie d'acceptation et d'engagement (ACT) utilise des principes bouddhistes pour modifier la relation au vécu intérieur. La Gestalt-thérapie et la psychologie humaniste ont intégré des pratiques contemplatives.</p>
<p class="resume-text">Le mouvement du « bouddhisme engagé », porté par Thich Nhat Hanh, lie la pratique méditative à l'engagement social et politique. La méditation n'est pas une fuite du monde mais une façon de l'habiter plus pleinement et de répondre avec justesse à ses souffrances. Cette vision nourrit des mouvements sociaux contemporains qui intègrent la pleine conscience dans leur pratique militante.</p>""",

    'spiritualite/chamanisme': """<h3>Le chaman : rôle, initiation et techniques</h3>
<p class="resume-text">Le terme « chaman » vient du toungouse (Sibérie) : saman désigne celui qui sait ou celui qui voit. Le chaman est un spécialiste du sacré qui peut entrer à volonté dans des états modifiés de conscience pour accéder au monde des esprits, diagnostiquer et traiter les maladies, assurer la chasse ou la fertilité, guider les âmes des morts. Il se distingue du prêtre (médiateur institutionnel) et du devin (consultant) par sa capacité à voyager lui-même dans l'autre monde.</p>
<p class="resume-text">L'initiation chamanique implique souvent une « mort et résurrection symbolique » : longue maladie, isolement, visions terrifiantes, démembrement mystique par les esprits, puis renaissance avec de nouveaux pouvoirs. Cette initiation peut être transmise héréditairement ou survenir spontanément lors d'une crise existentielle. Les chamans portent généralement des insignes symbolisant leurs auxiliaires spirituels (animaux tutélaires, masques, tambour).</p>
<div class="highlight-box"><p>Le tambour est l'instrument universel du chaman : son rythme régulier (entre 4 et 7 battements par seconde) induit des états de transe favorisant les voyages spirituels. Des recherches ethnomusicologiques et neuropsychologiques ont montré que ce rythme affecte les ondes thêta du cerveau, facilitant les états de conscience modifiée.</p></div>
<h3>Distribution géographique et variantes</h3>
<p class="resume-text">Le chamanisme n'est pas confiné à la Sibérie : des pratiques analogues existent chez les peuples amérindiens (les deux Amériques), les San d'Afrique australe, les Aborigènes d'Australie, les peuples finno-ougriens d'Europe du Nord, les populations mongoles et toungouses d'Asie centrale. Mircea Eliade, dans son ouvrage fondateur Le Chamanisme et les techniques archaïques de l'extase (1951), a proposé une définition transculturelle fondée sur l'extase et le voyage de l'âme.</p>
<p class="resume-text">Cette universalité est débattue : certains anthropologues préfèrent parler de « complexes chamaniques » locaux plutôt que d'une seule catégorie. Les pratiques varient considérablement : le machi mapuche du Chili n'est pas le idjit sibérien. Mais la structure du voyage extatique, le rôle des auxiliaires spirituels et la fonction thérapeutique du chaman constituent un fil commun reconnaissable.</p>
<div class="highlight-box"><p>Les Yage (ou ayahuasca) des peuples amazoniens, la peyotl des Huichols du Mexique, l'ibogaïne des Bwiti du Gabon : les plantes enthéogènes jouent un rôle central dans de nombreuses traditions chamaniques comme vecteurs de révélation et de guérison. Leur usage rituel est intégré dans un cadre symbolique et communautaire qui contraste avec la consommation récréative occidentale.</p></div>
<h3>Néo-chamanisme et chamanimse contemporain</h3>
<p class="resume-text">Michael Harner, anthropologue américain, a développé dans les années 1970 le « Voyage Chamanique Central » — une méthode standardisée pour induire des voyages chamaniques à travers le rythme du tambour — accessible à tous dans le cadre de la « Fondation pour les Études Chamaniques ». Ce néo-chamanisme occidental est critiqué pour son appropriation culturelle mais témoigne d'une quête spirituelle réelle dans les sociétés sécularisées.</p>
<p class="resume-text">Dans de nombreuses communautés autochtones, le chamanisme traditionnel connaît un renouveau : en lien avec les mouvements de décolonisation, les peuples amérindiens, sibériens et océaniens réaffirment leurs pratiques spirituelles comme éléments d'identité culturelle et de résistance politique. Ce renouveau pose des questions délicates sur l'authenticité, la transmission et les droits culturels.</p>""",

    'philosophie-religieuse/thomas-aquin': """<h3>La synthèse foi-raison</h3>
<p class="resume-text">Thomas d'Aquin (1225-1274) représente l'aboutissement de la scolastique médiévale : sa Summa Theologica tente une synthèse totale de la philosophie aristotélicienne et de la théologie chrétienne. Là où certains théologiens voyaient une contradiction irréductible entre foi et raison, Thomas affirme leur complémentarité : la raison peut démontrer l'existence de Dieu et les fondements de la morale, mais la révélation apporte des vérités supérieures (Trinité, Incarnation) inaccessibles à la seule raison.</p>
<p class="resume-text">Les cinq voies (quinque viae) pour démontrer l'existence de Dieu constituent l'argument cosmologique classique. La première voie part du mouvement : tout ce qui se meut est mû par autre chose ; il ne peut y avoir une régression à l'infini, donc il existe un premier moteur immobile — qui est Dieu. Les autres voies partent de la causalité efficiente, de la contingence, des degrés de perfection et de l'ordre téléologique du monde.</p>
<div class="highlight-box"><p>La distinction thomiste entre esse (être) et essentia (essence) est fondamentale : en Dieu seul, l'être et l'essence coïncident (Dieu est son propre être — ipsum esse subsistens). Dans les créatures, l'essence ne détermine pas l'existence : une créature peut ne pas exister. Cette distinction ontologique est la clé de voûte de la métaphysique thomiste.</p></div>
<h3>Éthique et loi naturelle</h3>
<p class="resume-text">La philosophie morale de Thomas d'Aquin est fondée sur la loi naturelle : la raison humaine, reflétant la loi éternelle de Dieu, peut découvrir les principes moraux fondamentaux par la seule lumière naturelle. Le premier principe pratique est « Fais le bien et évite le mal ». De ce principe découlent des normes concrètes sur la vie, la société, la justice. Cette conception a influencé le droit naturel moderne et la doctrine sociale de l'Église catholique.</p>
<p class="resume-text">Thomas distingue quatre types de loi : la loi éternelle (la raison divine gouvernant l'univers), la loi naturelle (participation des créatures raisonnables à la loi éternelle), la loi humaine positive (les lois des sociétés) et la loi divine révélée (les commandements de la Bible). Une loi humaine qui contredit la loi naturelle perd son caractère obligatoire : « Une loi injuste n'est pas une loi. »</p>
<div class="highlight-box"><p>La néoscolastique thomiste, relancée par Léon XIII avec l'encyclique Aeterni Patris (1879), a dominé la formation philosophique et théologique catholique jusqu'au concile Vatican II. Jacques Maritain et Étienne Gilson ont développé un thomisme modernisé en dialogue avec la phénoménologie et l'existentialisme du XXe siècle.</p></div>
<h3>Influence durable</h3>
<p class="resume-text">L'influence de Thomas d'Aquin dépasse de loin le catholicisme. Sa théorie de la connaissance (l'intellect humain abstrait les formes à partir des données sensorielles) anticipe certains aspects du cognitivisisme contemporain. Sa distinction entre les domaines de la raison et de la foi a contribué à définir l'espace de la pensée laïque. Ses commentaires d'Aristote ont préservé et transmis la philosophie grecque à l'Occident médiéval.</p>""",

    'philosophie-religieuse/pascal': """<h3>L'apologétique fragmentée des Pensées</h3>
<p class="resume-text">Les Pensées de Pascal sont les fragments d'une apologie du christianisme que leur auteur n'a jamais achevée. Pascal travaillait à convaincre les libertins (les incroyants cultivés du XVIIe siècle) de la vérité du christianisme, non par des preuves rationnelles mais en les confrontant à la misère et à la grandeur de l'homme. La condition humaine — « roseau pensant » — est son point de départ : l'homme est à la fois infiniment petit dans l'univers et capable de le penser.</p>
<p class="resume-text">La distinction entre l'esprit de géométrie et l'esprit de finesse est centrale : les vérités mathématiques sont démontrables par la raison, mais les vérités humaines et religieuses requièrent une intelligence plus intuitive et sensible. Le cœur a ses raisons que la raison ne connaît pas : la foi n'est pas irrationnelle, mais elle dépasse les preuves logiques et relève d'une expérience personnelle de Dieu.</p>
<div class="highlight-box"><p>Le pari de Pascal est l'un des arguments philosophiques les plus discutés de l'histoire. Si Dieu existe et que vous croyez, vous gagnez tout (la vie éternelle) ; si Dieu n'existe pas et que vous croyez, vous ne perdez que des plaisirs limités. Le calcul des probabilités justifie le pari sur l'existence de Dieu. Voltaire et d'autres ont critiqué cet argument comme réducteur de la foi à une stratégie intéressée.</p></div>
<h3>La géométrie et la physique</h3>
<p class="resume-text">Pascal est aussi un scientifique majeur. Ses travaux sur la pression atmosphérique (le baromètre de Pascal, l'expérience du Puy de Dôme en 1648) réfutent l'adage aristotélicien selon lequel la nature a horreur du vide. Sa machine arithmétique (la Pascaline), ancêtre des calculatrices, lui vaut d'être cité comme précurseur de l'informatique. Le triangle arithmétique qui porte son nom était connu avant lui, mais il en a développé toutes les applications combinatoires.</p>
<p class="resume-text">Le problème des partis (comment diviser équitablement les enjeux quand un jeu de hasard est interrompu) a conduit à sa correspondance avec Fermat et à la naissance du calcul des probabilités. Cette révolution mathématique a profondément modifié la pensée humaine : quantifier l'incertitude est devenu possible, ouvrant la voie aux actuaires, aux assurances et à la statistique moderne.</p>
<div class="highlight-box"><p>La mémorial de Pascal (1654), texte retrouvé cousu dans son habit après sa mort, témoigne de son « nuit de feu » — une expérience mystique intensive de deux heures qui a transformé sa vie. « Feu. Dieu d'Abraham, Dieu d'Isaac, Dieu de Jacob, non des philosophes et des savants. Certitude, certitude, sentiment, joie, paix. » Ce texte bouleversant révèle la dimension mystique d'un des plus grands savants de son siècle.</p></div>
<h3>Jansénisme et Port-Royal</h3>
<p class="resume-text">Pascal est profondément lié au courant janséniste, centré sur l'abbaye de Port-Royal des Champs. Le jansénisme insiste sur la grâce divine (sans laquelle l'homme ne peut rien), la faiblesse radicale de la volonté humaine depuis le péché originel, et la prédestination. Cette théologie, inspirée d'Augustin, s'opposait au molinisme jésuite, plus optimiste sur les capacités de la nature humaine.</p>
<p class="resume-text">Les Provinciales (1656-1657) sont une polémique brillante et souvent ironique contre la morale laxiste que Pascal attribue aux jésuites (probabilisme, casuistique, direction d'intention). Ce pamphlet — chef-d'œuvre de la prose française — contribua à la condamnation des jésuites sous Louis XIV et influença Voltaire dans son art de la polémique. Pascal est ainsi à la fois un mystique chrétien et le précurseur de la prose satirique des Lumières.</p>""",

    'philosophie-religieuse/kierkegaard': """<h3>Les trois stades de l'existence</h3>
<p class="resume-text">Søren Kierkegaard (1813-1855) développe une philosophie de l'existence organisée autour de trois stades. Le stade esthétique est celui de l'homme qui vit pour la jouissance, la variété et l'immédiateté : Don Juan en est le type, vivant d'amour en amour sans engagement. L'angoisse de la répétition et le désespoir devant la vacuité de cette existence peuvent conduire à un saut vers le stade éthique.</p>
<p class="resume-text">Au stade éthique, l'homme se soumet à la loi morale universelle et s'engage dans ses responsabilités (mariage, profession, devoir). Socrate en est le modèle. Mais cette morale universelle ne suffit pas à combler le vide existentiel : une tension demeure entre les exigences de l'universel et la singularité irréductible de chaque existence. Le désespoir de ne pouvoir accomplir totalement la loi morale peut conduire au troisième saut.</p>
<div class="highlight-box"><p>Le stade religieux implique le « saut dans la foi » — un acte absurde du point de vue de la raison, par lequel l'individu singulier entre en rapport direct avec Dieu. Abraham acceptant de sacrifier Isaac est le paradigme de ce stade : il obéit à un commandement divin qui contredit la morale universelle (ne pas tuer son fils). La foi kierkegaardienne est paradoxale, non rationnelle, profondément personnelle.</p></div>
<h3>L'angoisse et le désespoir</h3>
<p class="resume-text">Le Concept d'angoisse (1844) est une analyse existentielle de la liberté humaine. L'angoisse n'est pas la peur d'un objet précis mais le « vertige de la liberté » : la conscience que je suis libre de choisir, que mes choix engagent mon être, et que je peux me perdre comme me trouver dans cette liberté. Cette angoisse est liée à la possibilité du péché et à la conscience de ma finitude.</p>
<p class="resume-text">La Maladie à la mort (1849) analyse le désespoir comme la condition de celui qui ne parvient pas à être lui-même. Le désespoir peut prendre des formes multiples : ne pas vouloir être soi-même (fuir son ipséité dans la conformité), vouloir être un autre soi (fuir sa finitude dans l'illusion), ou vouloir se désespérer de lui-même (le désespoir conscient et orgueilleux). La guérison est dans la transparence du rapport à soi en Dieu.</p>
<div class="highlight-box"><p>Kierkegaard publie la plupart de ses œuvres sous des pseudonymes (Victor Eremita, Johannes Climacus, Anti-Climacus...) correspondant à différentes perspectives existentielles. Cette stratégie de communication indirecte vise à forcer le lecteur à s'engager personnellement, à ne pas accepter passivement une vérité mais à la s'approprier.</p></div>
<h3>Influence sur l'existentialisme</h3>
<p class="resume-text">Kierkegaard est considéré comme le père de l'existentialisme. Heidegger emprunte les concepts d'angoisse, d'authenticité et d'être-vers-la-mort. Sartre reprend la structure du choix libre et de la mauvaise foi. Jaspers développe les situations limites comme révélatrices de la transcendance. Même Camus, agnostique, dialogue avec la pensée kierkegaardienne sur l'absurde.</p>
<p class="resume-text">Au XXe siècle, la théologie dialectique de Karl Barth et la théologie existentielle de Bultmann s'inspirent directement de Kierkegaard pour renouveler le protestantisme. Sa critique de la « chrétienté » — une foi confortable et sociale qui n'exige rien — résonne dans les réveils évangéliques contemporains. Sa philosophie du singulier contre l'universel hégélien est une ressource permanente pour toute pensée qui résiste au conformisme et à la dissolution de l'individu dans la masse.</p>""",

    'religions-monde/shintoisme': """<h3>Les kami et la cosmogonie shintoïste</h3>
<p class="resume-text">Le shinto (« voie des kami ») est la religion autochtone du Japon. Les kami sont des divinités ou des puissances sacrées qui habitent la nature — montagnes, rivières, rochers, arbres — mais aussi des ancêtres divinisés et des personnages historiques exceptionnels. Il existe en principe « huit millions de kami » (yaoyorozu no kami), expression qui signifie simplement une multitude innombrable.</p>
<p class="resume-text">La cosmogonie shintoïste est racontée dans le Kojiki (712) et le Nihon Shoki (720) : les deux divinités primordiales Izanagi et Izanami créent les îles du Japon en agitant leur lance dans l'océan primordial. Leur union produit ensuite les kami de la nature. Amaterasu, déesse du soleil, est la kami suprême et ancêtre mythique de la famille impériale. Sa retraite dans une grotte plonge le monde dans les ténèbres ; les autres kami la font rire pour qu'elle sorte — première représentation théâtrale de l'histoire japonaise.</p>
<div class="highlight-box"><p>Le sanctuaire d'Ise, dédié à Amaterasu, est le sanctuaire le plus sacré du Japon. Il est reconstruit à l'identique toutes les vingt années selon une tradition millénaire (shikinen sengu) qui commence en 690 — symbolisant la renaissance éternelle et la pureté rituelle. La prochaine reconstruction aura lieu en 2033.</p></div>
<h3>Rites de pureté et cycle des saisons</h3>
<p class="resume-text">La notion de purification (misogi) est fondamentale dans le shinto : le mal moral et rituel (kegare) souille l'âme et éloigne des kami. Les rites de purification — ablutions d'eau (temizu), prières (norito), offrandes (shinsen) — rétablissent l'harmonie avec le sacré. La pureté rituelle n'est pas liée au péché moral chrétien mais à une conception de l'intégrité vitale qui peut être altérée par le contact avec la mort, le sang ou la maladie.</p>
<p class="resume-text">Les matsuri (fêtes shintoïstes) scandent le calendrier japonais : Oshogatsu (Nouvel An), Hinamatsuri (fête des filles), Kodomo no Hi (fête des garçons), Tanabata (fête des étoiles), Obon (commémoration des ancêtres). Ces fêtes articulent le temps cosmique (solstices, équinoxes, cycles lunaires) et le temps social, renforçant le lien entre communauté humaine et monde des kami.</p>
<div class="highlight-box"><p>Le torii — portique vermillon qui marque l'entrée des sanctuaires shintoïstes — est l'un des symboles les plus reconnaissables du Japon. Il matérialise le passage entre le monde profane et l'espace sacré. Les torii flottants du sanctuaire d'Itsukushima (île de Miyajima) sont l'une des « trois vues du Japon » les plus photographiées.</p></div>
<h3>Shinto, nationalisme et modernité</h3>
<p class="resume-text">Le shinto d'État (kokka shinto), imposé par le gouvernement de Meiji à partir de 1868 jusqu'en 1945, transforme le shinto en religion nationale liée au culte impérial. Cette instrumentalisation politique a contribué à la montée du nationalisme japonais et a été abolie par le décret américain de 1945 après la défaite. Cette histoire traumatique explique la prudence des Japonais contemporains vis-à-vis de tout mélange entre religion et État.</p>
<p class="resume-text">Aujourd'hui, le shinto coexiste avec le bouddhisme dans la vie quotidienne japonaise : naissances et mariages au sanctuaire shinto, funérailles au temple bouddhiste. Cette « double appartenance » religieuse, caractéristique du Japon, illustre une conception syncrétiste du sacré très différente des exclusivismes religieux occidentaux.</p>""",

    'religions-monde/jainisme': """<h3>L'ahimsa et l'éthique jaïne</h3>
<p class="resume-text">Le jaïnisme (du sanskrit jina, « victorieux ») est l'une des religions les plus anciennes et les plus originales de l'Inde. Son principe central est l'ahimsa (non-violence absolue envers tous les êtres vivants), porté à son degré d'exigence maximal. Les moines jaïns digambara (« vêtus d'espace », c'est-à-dire nus) portent un tissu devant la bouche pour ne pas avaler d'insectes et balaient le sol devant leurs pas pour ne pas écraser de fourmis.</p>
<p class="resume-text">Cette non-violence découle d'une ontologie pluraliste : il existe d'innombrables âmes (jiva) dans l'univers, des êtres à une seule sense (les plantes) jusqu'aux êtres à cinq sens (les humains). Toutes ces âmes sont fondamentalement égales et aspirent à la libération. Le karma est conçu comme une matière subtile qui s'attache à l'âme lors d'actions violentes ou passionnées, alourdissant son cycle de réincarnations.</p>
<div class="highlight-box"><p>Mahavira (599-527 av. J.-C.) est considéré comme le 24e et dernier tirthankara (« passeur de gué ») — un être humain qui a atteint la libération et enseigné le chemin aux autres. Son enseignement, contemporain du Bouddha, insiste sur l'ascèse extrême, la non-violence et la vérité multiperspective (anekantavada).</p></div>
<h3>La philosophie jaïne : anekantavada et syadvada</h3>
<p class="resume-text">L'anekantavada (non-absolutisme ou « non-unilatéralité ») est la doctrine épistémologique fondamentale du jaïnisme : la réalité est multidimensionnelle et aucune perspective unique ne peut l'épuiser. Cette doctrine conduit au syadvada (doctrine du peut-être) : toute affirmation sur la réalité doit être conditionnée par « peut-être » (syat). Une chose peut être à la fois existante et non-existante, permanente et impermanente, selon le point de vue adopté.</p>
<p class="resume-text">Cette philosophie pluraliste est remarquablement tolérante sur le plan religieux et politique : elle reconnaît la validité partielle de toutes les perspectives. Les comparatistes voient dans l'anekantavada une préfiguration du perspectivisme nietzschéen et un antidote philosophique au dogmatisme et à l'intolérance. Gandhi, influencé par le jaïnisme, s'en inspire dans sa conception du dialogue politique.</p>
<div class="highlight-box"><p>Les temples jaïns de Dilwara (Rajasthan, XIe-XIIIe siècle) sont considérés comme parmi les plus beaux de l'Inde pour leurs sculptures en marbre blanc d'une finesse incroyable. Le temple de Ranakpur (XVe siècle), avec ses 1444 colonnes toutes différentes, est un chef-d'œuvre architectural témoignant de la richesse mécénale des marchands jaïns.</p></div>
<h3>Le jaïnisme contemporain</h3>
<p class="resume-text">Avec environ 5 millions de fidèles (principalement au Gujarat et au Rajasthan), le jaïnisme est une minorité religieuse indienne mais son influence économique et culturelle est disproportionnée à son nombre. Les marchands jaïns ont joué un rôle important dans le développement du commerce indien et une réputation d'intégrité et de rigueur éthique dans les affaires.</p>
<p class="resume-text">L'éthique jaïne de non-violence et de souci de toute forme de vie résonne avec les préoccupations écologiques contemporaines. Des penseurs comme Satish Kumar ont développé une écologie inspirée du jaïnisme. La pratique du végétarisme strict, l'évitement du gaspillage et le respect de toutes les formes de vie constituent un mode de vie qui préfigure certains aspects de la pensée environnementale moderne.</p>""",

    'religions-monde/zoroastrisme': """<h3>La réforme de Zarathoustra</h3>
<p class="resume-text">Le zoroastrisme est l'une des religions les plus anciennes du monde, fondée par le prophète Zarathoustra (Zoroastre en grec) dans les steppes de l'Asie centrale, peut-être entre 1500 et 1000 av. J.-C. (les dates sont très discutées). Zarathoustra réforme la religion indo-iranienne traditionnelle en élevant un seul dieu, Ahura Mazda (le Seigneur Sage), au rang de divinité suprême et créatrice.</p>
<p class="resume-text">La vision de Zarathoustra est dualiste : Ahura Mazda (le bien, la lumière, la vérité) est en lutte cosmique contre Angra Mainyu (Ahriman, l'esprit destructeur, le mal, le mensonge). Cette lutte eschatologique a une fin : à la fin des temps, le bien triomphera définitivement. Les hommes sont des combattants dans cette guerre cosmique, libres de choisir leur camp par leurs pensées (humata), leurs paroles (hukhta) et leurs actes (hvarshta).</p>
<div class="highlight-box"><p>Les Gathas, hymnes attribués à Zarathoustra lui-même, sont écrits dans une langue archaïque très proche du sanskrit védique. Ces seize poèmes, inclus dans l'Avesta (le texte sacré zoroastrien), constituent le plus ancien témoignage direct d'une pensée théologique monothéiste dans l'histoire humaine.</p></div>
<h3>Influence sur les religions abrahamiques</h3>
<p class="resume-text">L'influence du zoroastrisme sur le judaïsme, le christianisme et l'islam est considérable. Le dualisme bien/mal, la résurrection des morts, le jugement dernier, le paradis et l'enfer, les anges et les démons, le Messie sauveur : tous ces concepts présents dans les religions abrahamiques seraient au moins partiellement influencés par le contact avec le zoroastrisme lors de la captivité babylonienne (VIe siècle av. J.-C.).</p>
<p class="resume-text">Nietzsche choisit Zarathoustra comme porte-parole de sa philosophie dans Ainsi parlait Zarathoustra (1883-1885) — non par affinité doctrinale mais parce que c'est un réformateur religieux radical. Il y voit l'archétype du prophète qui ose remettre en question les valeurs établies. Ironiquement, Nietzsche attribue à Zarathoustra l'invention du bien et du mal qu'il entend maintenant « dépasser ».</p>
<div class="highlight-box"><p>Le feu sacré est le symbole central du zoroastrisme : dans les temples du feu (Atash Behram), la flamme sacrée brûle en permanence depuis des siècles (certains feux n'ont pas été éteints depuis 1500 ans). Ce feu ne représente pas Ahura Mazda lui-même mais sa lumière et sa pureté. Les prêtres portent un masque pour ne pas le souiller de leur souffle.</p></div>
<h3>Les Parsis : une diaspora persistante</h3>
<p class="resume-text">Après la conquête de la Perse par les Arabes (VIIe siècle) et l'islamisation progressive, des communautés zoroastriennes fuient en Inde et s'y établissent (VIIIe-Xe siècle) : ce sont les Parsis (Perses). Concentrés principalement à Mumbai (Bombay), les Parsis ont joué un rôle économique et culturel considérable dans l'Inde moderne : les familles Tata (industrie) et Godrej (conglomérat) sont parsis. Zubin Mehta, Freddie Mercury (Queen) et Homi J. Bhabha (physicien nucléaire) sont d'origine parsi.</p>
<p class="resume-text">La pratique des « tours du silence » (dakhma) expose les corps des défunts aux vautours pour éviter de souiller les éléments sacrés (terre, eau, feu). Dans la Mumbai moderne, où les vautours ont quasi disparu, cette pratique est devenue problématique et suscite des débats au sein de la communauté. Avec environ 60 000 Parsis en Inde (en déclin démographique), le zoroastrisme est aujourd'hui en voie d'extinction en Inde mais survit en Iran (Iraniens zoroastriens : environ 25 000).</p>""",

    'textes-sacres/coran': """<h3>La composition et la structure du Coran</h3>
<p class="resume-text">Le Coran (« la Récitation ») est organisé en 114 sourates (chapitres) classées approximativement de la plus longue à la plus courte — et non chronologiquement. La sourate la plus longue (Al-Baqara, 286 versets) traite de nombreux sujets juridiques et narratifs ; la plus courte (Al-Kawthar, 3 versets) est un hymne de gratitude. Chaque sourate (sauf la neuvième) commence par la basmala : « Au nom de Dieu, le Tout Miséricordieux, le Très Miséricordieux ».</p>
<p class="resume-text">La langue coranique est considérée comme un miracle en soi (i'jaz al-Quran) : son style poétique sublime, ses assonances et son rythme sont inimitables selon la théologie islamique. D'où l'impossibilité théologique de la traduction : toute version dans une autre langue n'est qu'une « interprétation des sens », jamais le Coran lui-même. La mémorisation intégrale du Coran (hafiz) est un idéal et un titre de prestige dans le monde musulman.</p>
<div class="highlight-box"><p>La standardisation du texte coranique fut réalisée sous le calife Uthman (644-656) : des copies officielles furent envoyées dans les grandes villes de l'empire, et les variantes furent détruites. Ce travail de canonisation assura une remarquable stabilité textuelle sur quatorze siècles, avec des variations mineures limitées à sept modes de récitation (qira'at).</p></div>
<h3>Les sciences coraniques</h3>
<p class="resume-text">L'interprétation du Coran (tafsir) est une discipline savante complexe mobilisant la linguistique arabe, la connaissance des occasions de révélation (asbab al-nuzul), la hiérarchie des versets (certains versets médinois abrogent des versets mecquois antérieurs) et la relation avec les hadiths prophétiques. Les grands tafsir médiévaux (Tabari, Ibn Kathir) font plusieurs dizaines de volumes.</p>
<p class="resume-text">La récitation coranique (tilawa) est un art musical sacré développé selon des règles précises (tajwid). Les grandes compétitions internationales de récitation coranique rassemblent des milliers de participants. Les récitants célèbres — comme Abd al-Basit Abd al-Samad ou Mishary Rashid al-Afasy — sont des stars dans le monde musulman. La récitation est considérée comme une forme d'adoration physique, engageant le souffle et le corps.</p>
<div class="highlight-box"><p>Le Coran fait de nombreuses références à des personnages bibliques : Abraham (Ibrahim), Moïse (Moussa), Jésus (Issa), Marie (Maryam). Jésus est honoré comme prophète et Messie mais non comme Fils de Dieu. La sourate Maryam (19) est entièrement consacrée à Marie, et en fait l'une des figures féminines les plus citées dans le Coran.</p></div>
<h3>Le Coran et la civilisation islamique</h3>
<p class="resume-text">Le Coran a généré une civilisation entière. L'obligation de lire la Parole divine a stimulé l'alphabétisation et l'enseignement dans tout le monde islamique. La calligraphie arabe, née de la nécessité de transcrire le Coran avec beauté, a produit un art géométrique et abstrait d'une richesse unique. L'architecture des mosquées est pensée comme un espace de méditation sur la Parole divine.</p>
<p class="resume-text">Les savants islamiques médiévaux ont développé des sciences linguistiques — grammaire arabe, lexicologie, rhétorique — principalement pour comprendre et interpréter le Coran avec précision. La tradition des madrasa (écoles religieuses) a assuré pendant des siècles une transmission du savoir coranique et des sciences islamiques de génération en génération, constituant l'un des premiers systèmes d'enseignement institutionnel de l'histoire.</p>""",

    'textes-sacres/torah': """<h3>La structure interne de la Torah</h3>
<p class="resume-text">La Torah se divise en cinq livres distincts dont chacun a une tonalité propre. La Genèse (Bereshit) raconte les origines du monde et des patriarches Abraham, Isaac et Jacob. L'Exode (Shemot) narre l'esclavage en Égypte, la libération par Moïse et la révélation du Sinaï. Le Lévitique (Vayikra) est un code cultuel et rituel centré sur le sacerdoce. Les Nombres (Bamidbar) chroniquent l'errance de quarante ans dans le désert. Le Deutéronome (Devarim) est le grand discours testamentaire de Moïse avant son entrée en Terre promise.</p>
<p class="resume-text">Cette architecture narrative n'est pas linéaire : la Torah entremêle récit, loi, généalogie et poésie. Les répétitions et variantes internes ont conduit les exégètes modernes à distinguer plusieurs sources rédactionnelles (hypothèse documentaire : J, E, D, P) dont la composition s'étalerait sur plusieurs siècles. Cette critique historique, développée par Wellhausen au XIXe siècle, est acceptée dans la recherche académique mais rejetée par le judaïsme orthodoxe qui affirme la révélation divine de l'ensemble de la Torah.</p>
<div class="highlight-box"><p>La révélation du Sinaï est l'événement fondateur du judaïsme : Dieu y délivre les Dix Commandements (Décalogue) à Moïse, établissant l'alliance (brit) qui définit le peuple d'Israël comme « peuple élu ». Le texte biblique précise que la voix divine était entendue par tout le peuple — une révélation publique et collective, non pas une expérience mystique individuelle.</p></div>
<h3>L'exégèse juive : du peshat au sod</h3>
<p class="resume-text">La tradition rabbinique a développé quatre niveaux d'interprétation de la Torah, résumés par l'acronyme PaRDeS : le peshat (sens littéral), le remez (sens allégorique), le derash (sens homilétique, utilisé dans les midrashim) et le sod (sens mystique, kabbalistique). Cette pluralité herméneutique fait de la Torah un texte inépuisable, toujours susceptible de nouvelles lectures.</p>
<p class="resume-text">Le Talmud, compilation de discussions rabbiniques (Ier-VIe siècle), commente la Torah ligne à ligne. Les responsa médiévaux et les commentaires de Rachi (1040-1105, dont la clarté pédagogique est inégalée) et de Maïmonide (XIIe siècle) constituent des strates d'interprétation qui enrichissent continuellement le sens du texte fondateur. L'étude de la Torah (talmud Torah) est en elle-même une obligation religieuse dans le judaïsme, quel que soit son résultat pratique.</p>
<div class="highlight-box"><p>Le midrash est un genre littéraire d'interprétation créative de la Bible : il comble les silences du texte, amplifie les récits, tire des leçons morales des histoires bibliques. Ces interprétations haggadiques (narratives) n'ont pas le même statut normatif que la halakha (loi), mais leur richesse d'imagination spirituelle et narrative est inépuisable.</p></div>
<h3>La Torah dans la vie juive</h3>
<p class="resume-text">Le rouleau de la Torah (Sefer Torah) est l'objet le plus sacré du judaïsme. Sa copie à la main par un scribe (sofer) est soumise à des règles strictes : une seule erreur peut rendre le rouleau impropre à l'usage rituel. Chaque semaine, une paracha (portion) est lue à la synagogue, permettant de parcourir la Torah en un an (et de recommencer indéfiniment). La fête de Simchat Torah célèbre l'achèvement et le recommencement de ce cycle annuel.</p>
<p class="resume-text">La bar et bat mitsva (à 13 ans pour les garçons, 12 ans pour les filles) marque l'entrée dans la responsabilité religieuse : le jeune Juif lit publiquement la Torah pour la première fois. Ce rite de passage est à la fois religieux, familial et culturel. Dans les familles moins pratiquantes, il demeure souvent le seul contact formel avec la tradition hébraïque, devenant un vecteur de transmission identitaire.</p>""",

    'textes-sacres/vedas': """<h3>La structure des Vedas et le rituel védique</h3>
<p class="resume-text">Les quatre Vedas se subdivisent chacun en quatre parties : les Samhita (collections d'hymnes et de formules), les Brahmana (textes en prose expliquant les rituels), les Aranyaka (« textes des forêts », pour ermites et ascètes) et les Upanishad (discussions philosophiques sur l'âme et l'absolu). L'ensemble constitue la shruti — « ce qui a été entendu » des sages (rishi) en état de méditation — par opposition à la smriti — « ce dont on se souvient », la tradition humaine incluant les épopées et les Puranas.</p>
<p class="resume-text">Le rituel védique (yajna) est une science complexe mobilisant des officiants spécialisés (hotri pour réciter le Rig-Véda, udgatar pour le Sama-Véda, adhvaryu pour l'Yajur-Véda). Le feu sacrificiel (agni) est le médiateur entre les hommes et les dieux. Ces rituels élaborés — dont certains duraient plusieurs années — ont conduit au développement des mathématiques (géométrie des autels sacrificiels, Sulba Sutras) et de la grammaire sanskrite systématisée par Panini.</p>
<div class="highlight-box"><p>Le Rig-Véda contient 1028 hymnes dont certains datent de 1500 av. J.-C. environ. Son hymne de la création (Nasadiya Sukta, X.129) pose des questions métaphysiques d'une audace remarquable : « Qui sait vraiment ? Qui peut l'affirmer ici ? D'où est-il né, d'où vient cette création ? Les dieux eux-mêmes sont venus après sa création. Alors qui sait d'où elle a surgi ? »</p></div>
<h3>Les Upanishad et la révolution philosophique</h3>
<p class="resume-text">Les Upanishad (VIIIe-IVe siècle av. J.-C.) opèrent un tournant radical dans la pensée indienne : au lieu du rituel externe, elles valorisent la connaissance intérieure (jnana). Leur concept central est l'identité entre Atman (l'âme individuelle) et Brahman (l'absolu impersonnel). « Tat tvam asi » — « Tu es Cela » — exprime cette équivalence fondamentale. Cette réalisation directe est la libération (moksha) du cycle des réincarnations.</p>
<p class="resume-text">Les principales Upanishad (Brihadaranyaka, Chandogya, Taittiriya) développent des dialogues entre maîtres et disciples sur la nature du moi, du rêve, du sommeil profond et de la mort. Le père qui explique à son fils l'essence invisible qui pénètre toute chose (tat tvam asi, Chandogya 6.12-13) constitue l'une des plus belles scènes pédagogiques de la littérature mondiale.</p>
<div class="highlight-box"><p>Schopenhauer, qui découvrit les Upanishad en 1814 dans la traduction latine d'Anquetil-Duperron, déclara que c'était la « lecture la plus profitable et la plus élevée qui soit possible au monde ». Sa philosophie de la volonté universelle et de la délivrance par la suppression du vouloir-vivre doit beaucoup à la pensée upanishadique.</p></div>
<h3>Transmission orale et enseignement du sanskrit</h3>
<p class="resume-text">La transmission orale des Vedas a produit des techniques de mémorisation d'une précision extraordinaire. Les brahmanes récitaient les textes en avant, en arrière, par paires de mots, par groupes de mots, en échangeant les syllabes — toutes ces variantes permettant de vérifier l'intégrité du texte mémorisé. Cette tradition orale, maintenue pendant 3000 ans, est reconnue depuis 2003 par l'UNESCO comme patrimoine culturel immatériel de l'humanité.</p>
<p class="resume-text">La grammaire de Panini (IVe siècle av. J.-C.), l'Ashtadhyayi, est la description la plus complète et la plus systématique d'une langue jamais réalisée dans l'Antiquité. Ses 3959 sutras décrivent le sanskrit avec une précision structurale qui anticipe la linguistique moderne et les grammaires génératives. Les orientalistes européens du XIXe siècle (William Jones, Max Müller) ont découvert le sanskrit et reconnu ses affinités avec les langues européennes, donnant naissance à la linguistique comparatiste indo-européenne.</p>""",
}

def enrich_content(content, new_html):
    """Insère new_html juste avant la section quiz."""
    quiz_marker = '<section class="content-section" id="quiz">'
    idx = content.find(quiz_marker)
    if idx != -1:
        return content[:idx] + new_html + content[idx:]
    # Si pas de quiz, insérer avant la dernière balise </section>
    last_section = content.rfind('</section>')
    if last_section != -1:
        return content[:last_section] + new_html + content[last_section:]
    return content + new_html


def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    pages = data.get('pages', {})
    modified = 0
    skipped = 0

    for key, html in ENRICHMENTS.items():
        if key not in pages:
            print(f'SKIP (not found): {key}')
            skipped += 1
            continue

        page = pages[key]
        current_content = page.get('content', '') or ''

        # Check if already enriched (avoid duplicate injection)
        if len(current_content) >= 15000:
            print(f'SKIP (already >= 15000 chars): {key} ({len(current_content)} chars)')
            skipped += 1
            continue

        new_content = enrich_content(current_content, html)
        pages[key]['content'] = new_content
        print(f'OK: {key} ({len(current_content)} -> {len(new_content)} chars)')
        modified += 1

    data['pages'] = pages

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'\nDone: {modified} articles enriched, {skipped} skipped.')


if __name__ == '__main__':
    main()
