import json, sys

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/anthropologie.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']

def replace_course_content(content, new_inner_html):
    """Replace everything inside <div class="course-content"> in the contenu section."""
    marker_start = '<section class="content-section" id="contenu">'
    idx_section = content.find(marker_start)

    cc_open = '<div class="course-content">'
    idx_cc_open = content.find(cc_open, idx_section)

    idx_end_cc = content.find('\n      </div>\n    </section>', idx_cc_open)
    if idx_end_cc == -1:
        idx_end_cc = content.find('\n      </div>\n\n    </section>', idx_cc_open)

    new_content = (
        content[:idx_cc_open + len(cc_open)] +
        '\n' + new_inner_html + '\n      </div>\n    </section>' +
        content[idx_end_cc + len('\n      </div>\n    </section>'):]
    )
    return new_content

# ============================================================
# physique/adaptations
# ============================================================
adaptations_content = """<h3>Adaptations biologiques et coévolution gène-culture</h3>
<p>Les <strong>adaptations biologiques</strong> humaines illustrent comment l'évolution naturelle a façonné notre espèce en réponse à des pressions environnementales très variées. Une particularité de l'Homo sapiens est la <strong>coévolution gène-culture</strong> : des comportements culturels (l'élevage laitier, l'agriculture, la cuisson des aliments) modifient les pressions de sélection naturelle, qui modifient à leur tour les fréquences alléliques dans les populations, qui permettent de nouveaux comportements culturels — une boucle de rétroaction positive. La persistance de la lactase en est l'exemple le plus clair : la domestication des bovins laitiers il y a ~10 000 ans a fortement favorisé les individus capables de digérer le lactose à l'âge adulte, et en ~350 générations (~7000 ans), la fréquence de cet allèle est passée de quasi nulle à 80-95 % en Europe du Nord et chez certaines populations pastorales africaines.</p>
<div class="highlight-box"><p><strong>Convergence évolutive :</strong> La persistance de la lactase est apparue indépendamment au moins quatre fois : chez les éleveurs européens (variante -13910*T), chez les pasteurs est-africains Maasai, Beja et Fulani (variantes -13907*G, -13915*G, -14010*C). C'est un exemple frappant de convergence évolutive guidée par une pratique culturelle identique dans des populations génétiquement distinctes.</p></div>

<h3>Pigmentation de la peau et rayonnement ultraviolet</h3>
<p>La couleur de la peau suit un <strong>gradient latitudinal</strong> remarquablement bien corrélé avec l'intensité des rayonnements UV. Près de l'équateur, une peau riche en mélanine (pigment produit par les mélanocytes) protège deux molécules critiques : l'<strong>acide folique</strong> (vitamine B9, essentielle au développement du tube neural embryonnaire) et, indirectement, l'ADN cellulaire. Aux hautes latitudes, où les UV sont moins intenses, une peau claire permet de maximiser la photosynthèse de la <strong>vitamine D</strong> (indispensable à l'absorption du calcium et au système immunitaire) avec un ensoleillement réduit. Cette hypothèse de Jablonski et Chaplin (2000) est largement acceptée, même si d'autres facteurs (camouflage, sélection sexuelle) ont pu jouer.</p>
<p>Génétiquement, la pigmentation est contrôlée par au moins 150 gènes, mais quelques variants ont des effets majeurs : <strong>MC1R</strong> (récepteur de la mélanocortine 1, déterminant pour la rédeur et les phéotypes « peau claire »), <strong>SLC24A5</strong> et <strong>SLC45A2</strong> (transporteurs ioniques responsables d'une large fraction de la dépigmentation en Europe). Fait remarquable : la dépigmentation des populations d'Europe s'est produite récemment (il y a ~5000-10 000 ans seulement selon les analyses génomiques) et a été soumise à une sélection positive intense.</p>

<h3>Adaptation à l'altitude : trois solutions distinctes</h3>
<p>Les hautes altitudes imposent une hypoxie (manque d'oxygène), un rayonnement UV accru et un froid intense. Trois grandes populations humaines ont développé des adaptations distinctes à ces conditions, révélant la richesse des solutions évolutives :</p>
<p><strong>Les Tibétains</strong> (Plateau tibétain, ~4500 m en moyenne) portent une variante du gène <strong>EPAS1</strong> (codant pour le facteur induit par l'hypoxie HIF-2α) héritée des <strong>Dénisoviens</strong> par hybridation il y a >30 000 ans. Cette variante limite l'augmentation de l'hémoglobine en altitude — évitant l'épaississement du sang qui augmenterait les risques de thrombose — et améliore l'efficacité d'utilisation de l'oxygène.</p>
<p><strong>Les Andins</strong> (Bolivie, Pérou) ont des adaptations différentes : saturation en oxygène plus élevée, capacité pulmonaire accrue, et une augmentation modérée de l'hémoglobine. Le gène <strong>EGLN1</strong> y joue un rôle important. <strong>Les Éthiopiens des hauts plateaux</strong> (Amhara, Oromo) maintiennent une saturation normale en oxygène malgré l'altitude, par des mécanismes encore mal compris impliquant probablement des modifications de la réactivité vasculaire. Cette triple convergence — trois populations, trois altitudes comparables, trois solutions génétiques — est un cas d'école de l'évolution parallèle.</p>

<h3>Thermorégulation et règles écogeographiques</h3>
<p>Les populations humaines illustrent deux règles écogeographiques classiques, formulées au XIX<sup>e</sup> siècle chez les mammifères homéothermes : la <strong>règle de Bergmann</strong> (les individus sont plus massifs dans les populations vivant en milieu froid, augmentant le ratio volume/surface et réduisant les pertes de chaleur) et la <strong>règle d'Allen</strong> (les appendices — membres, oreilles — sont plus courts en milieu froid, réduisant là encore les pertes de chaleur). Ces tendances sont observables chez l'humain, même si la mobilité culturelle (vêtements, chauffage) atténue la pression de sélection thermique.</p>
<p>Les <strong>Inuits</strong> et autres populations arctiques ont développé des adaptations métaboliques spécifiques à un régime riche en graisses animales : des variants des gènes <strong>FADS1</strong> et <strong>FADS2</strong> (codant pour des enzymes du métabolisme des acides gras polyinsaturés) leur permettent de métaboliser efficacement les oméga-3 à longue chaîne du poisson et des mammifères marins. Leur taux métabolique basal est significativement plus élevé que des populations de latitudes tempérées de corpulence comparable.</p>

<h3>Résistance aux maladies infectieuses</h3>
<p>La pression évolutive exercée par les agents infectieux a laissé des traces génomiques majeures dans les populations humaines. La <strong>drépanocytose</strong> (anémie falciforme) est l'exemple classique : l'allèle HbS en hétérozygotie confère une résistance partielle au <em>Plasmodium falciparum</em> (malaria), ce qui a maintenu sa fréquence élevée (jusqu'à 30 % en Afrique subsaharienne, dans les zones de paludisme intense) malgré les effets graves de l'homozygotie. D'autres exemples incluent la <strong>thalassémie</strong> (résistance au paludisme en Méditerranée) et la <strong>mutation CCR5-Δ32</strong> (résistance à la peste bubonique, et à moindre titre au VIH, dans les populations d'Europe du Nord).</p>
<div class="highlight-box"><p><strong>L'héritage génétique de la peste :</strong> Des analyses génomiques récentes (étude publiée dans <em>Nature</em> en 2022) montrent que les épidémies de peste noire du XIV<sup>e</sup> siècle ont exercé une pression de sélection suffisamment intense pour modifier de façon mesurable les fréquences alléliques de certains gènes immunitaires en Europe — notamment dans les voies de signalisation de l'interleukine-4 et du TNF-α.</p></div>

<h3>Sélection récente et adaptations en cours</h3>
<p>Les méthodes de génomique des populations (scans de sélection, analyse des haplotypes longs, études GWAS) permettent d'identifier les gènes soumis à une sélection positive récente chez l'humain. Les résultats sont fascinants : des adaptations au régime alimentaire (amidon, lactose), à l'altitude et à la pigmentation, mais aussi au <strong>cycle circadien</strong> (les populations aux longues périodes de nuit auraient des variants de gènes d'horloge biologique), à la <strong>résistance à l'alcool</strong> (variants de l'alcool déshydrogénase ADH1B fortement sélectionnés en Asie orientale et au Proche-Orient avec le développement de l'agriculture et de la fermentation) et à la <strong>taille corporelle</strong>. Ces études montrent que l'évolution humaine n'est pas terminée — notre espèce continue de s'adapter biologiquement, même si la culture atténue souvent les pressions de sélection les plus directes.</p>"""

pages['physique/adaptations']['content'] = replace_course_content(
    pages['physique/adaptations']['content'],
    adaptations_content
)
print(f"physique/adaptations: {len(pages['physique/adaptations']['content'])} chars")

# ============================================================
# physique/primatologie
# ============================================================
primatologie_content = """<h3>La primatologie comme miroir de l'humain</h3>
<p>La <strong>primatologie</strong> étudie les primates non humains — singes, grands singes et prosimiens — dans une double perspective : comprendre la biologie et le comportement de ces espèces pour elles-mêmes, et éclairer l'évolution de notre propre espèce. En observant nos plus proches parents biologiques, nous accédons à des « fenêtres évolutives » sur des traits que nous supposons partager avec nos ancêtres communs : la vie en groupe, la coopération, la tromperie, l'empathie, l'apprentissage social. La primatologie est ainsi à la fois zoologie, éthologie, anthropologie et biologie évolutive.</p>
<div class="highlight-box"><p><strong>Jane Goodall à Gombe (1960) :</strong> Lorsque Jane Goodall observe pour la première fois des chimpanzés fabriquer et utiliser des outils (des tiges de végétaux pour extraire des termites), son directeur Louis Leakey télégraphie : « Now we must redefine tool, redefine Man, or accept chimpanzees as humans. » Cette découverte révolutionne la primatologie et la conception de ce qui définit l'humanité.</p></div>

<h3>Classification et phylogénie des primates</h3>
<p>L'ordre des primates comprend environ 500 espèces, réparties en deux grands groupes. Les <strong>prosimiens</strong> (ou Strepsirhiniens) — lémuriens, loris, galagos, tarsiers — sont les plus basaux phylogénétiquement ; ils conservent des caractères ancestraux comme le rhinarium humide et les griffes de toilettage. Les <strong>simiens</strong> (ou Haplorhiniens) se divisent en singes du Nouveau Monde (<em>Platyrrhini</em> : capucins, ouistitis, singes-araignées), singes de l'Ancien Monde (<em>Cercopithecidae</em> : macaques, babouins, colobes) et hominidés (<em>Hominidae</em> : gibbons, orangs-outans, gorilles, chimpanzés, bonobos, et l'humain).</p>
<p>Le temps de divergence entre <em>Homo sapiens</em> et <em>Pan troglodytes/Pan paniscus</em> est estimé à 6-7 millions d'années par les horloges moléculaires et les données paléontologiques (le plus ancien candidat hominidé est <em>Sahelanthropus tchadensis</em>, ~7 Ma, Tchad). La similitude génomique entre humain et chimpanzé est de ~98,7 % en termes de séquences codantes, mais la régulation de l'expression des gènes et les variations structurales (CNV, inversions) peuvent expliquer des différences phénotypiques importantes.</p>

<h3>Organisation sociale et systèmes d'appariement</h3>
<p>Les primates présentent une grande diversité de systèmes sociaux, ce qui en fait des modèles précieux pour tester les théories évolutives sur la coopération et la compétition. Les gorilles (<em>Gorilla gorilla</em>) vivent en harems : un mâle dominant (dos argenté) entouré de plusieurs femelles et leurs jeunes. Les chimpanzés (<em>Pan troglodytes</em>) forment des communautés fission-fusion de 20 à 150 individus, où les sous-groupes se forment et se défont selon les ressources disponibles. Les bonobos (<em>Pan paniscus</em>) ont une société matriarcale à faible violence — les femelles contrôlent l'accès aux ressources et les tensions sont souvent résolues par des contacts sexuels. Les gibbons (<em>Hylobatidae</em>) sont monogames et territoriaux — ils chantent en duo pour affirmer leur lien de couple et défendre leur territoire.</p>
<p>Cette diversité soulève des questions fondamentales sur le système social originel des hominidés : nos ancêtres étaient-ils plutôt comme des chimpanzés (mâle dominant, compétition entre groupes) ou comme des bonobos (société moins violente, dominance féminine) ? Les données anatomiques (dimorphisme sexuel, taille des testicules, morphologie des canines) suggèrent que les premiers hominidés avaient une organisation intermédiaire entre ces deux extrêmes.</p>

<h3>Culture et transmission sociale chez les primates</h3>
<p>L'une des découvertes les plus fascinantes de la primatologie des dernières décennies est la démonstration de <strong>cultures</strong> — au sens strict de comportements acquis socialement et variables entre populations — chez plusieurs espèces. Une étude publiée dans <em>Nature</em> en 1999 (Whiten et al.) a synthétisé les observations de sept sites de recherche sur les chimpanzés d'Afrique pour documenter 39 comportements « culturels » — présents dans certaines populations et absents dans d'autres sans raison écologique évidente : cassage de noix avec des pierres (Bossou, Guinée), pêche aux termites avec des bâtons (Gombe, Tanzanie), usage de feuilles comme éponges (Mahale, Tanzanie), « botte » d'herbe brandie comme objet symbolique (Bossou).</p>
<div class="highlight-box"><p><strong>Transmission culturelle expérimentale :</strong> Des expériences contrôlées (Whiten et al., 2005, <em>Nature</em>) ont démontré que les chimpanzés apprennent préférentiellement par imitation des techniques de compagnons de rang social élevé — exactement comme les humains. Une technique introduite artificiellement dans un groupe se propage ensuite de façon fidèle, y compris quand l'individu « modèle » n'est plus présent.</p></div>

<h3>Cognition, théorie de l'esprit et langage</h3>
<p>Les grands singes possèdent des capacités cognitives remarquables. La <strong>reconnaissance de soi dans un miroir</strong> (Gordon Gallup, 1970) — signe d'une conscience de soi minimale — est observée chez les chimpanzés, bonobos, orangs-outans et gorilles, mais pas chez les singes à queue. La <strong>théorie de l'esprit</strong> — la capacité à attribuer des états mentaux à autrui — est débattue pour les grands singes : des expériences récentes (Krupenye et al., 2016, <em>Science</em>) montrent que les chimpanzés, bonobos et orangs-outans anticipent les actions d'un agent humain sur la base de ses croyances, même fausses — ce qui impliquerait une forme de théorie de l'esprit.</p>
<p>Les projets de communication inter-espèces ont montré que des grands singes peuvent acquérir et utiliser des éléments de <strong>langue des signes américaine</strong> (projet Washoe, Gardner, 1966), des <strong>lexigrammes</strong> sur clavier (Kanzi le bonobo, Sue Savage-Rumbaugh, années 1980) ou des symboles (projet NIM). Ces résultats sont vivement débattus : les grands singes utilisent-ils réellement des symboles linguistiques ou simplement des associations conditionnées ? Kanzi, qui a acquis des lexigrammes naturellement en observant sa mère, est considéré comme le cas le plus convaincant de proto-langage chez un non-humain.</p>

<h3>Primatologie et conservation</h3>
<p>Toutes les espèces de grands singes sont aujourd'hui classées comme <strong>menacées ou en danger critique d'extinction</strong> par l'UICN. Les principaux facteurs sont la destruction de l'habitat (déforestation en Afrique tropicale, Bornéo, Sumatra), le braconnage (viande de brousse, trafic de bébés pour animaux de compagnie), les maladies (Ebola a décimé certaines populations de gorilles et chimpanzés) et les conflits armés perturbant les zones protégées. Les populations de chimpanzés sont passées de plusieurs millions à moins de 300 000 individus au XX<sup>e</sup> siècle. La primatologie contribue à la conservation en fournissant des données sur les besoins écologiques et comportementaux des espèces, en formant des gardes forestiers locaux et en sensibilisant l'opinion internationale.</p>

<h3>Éthique de la recherche sur les primates</h3>
<p>La proximité biologique et cognitive des grands singes avec l'humain soulève des questions éthiques fondamentales. La plupart des pays développés ont interdit les expériences biomédicales invasives sur les grands singes (chimpanzés, bonobos, gorilles, orangs-outans). Les États-Unis, dernier pays à utiliser des chimpanzés en recherche biomédicale à grande échelle, ont officiellement mis fin à ces pratiques en 2015. Le projet « Great Ape Project » (Peter Singer, Paola Cavalieri, 1993) a lancé un plaidoyer pour l'octroi de droits juridiques aux grands singes — à ce jour, seule l'Espagne a adopté en 2008 une résolution parlementaire en ce sens. Ces débats soulèvent la question philosophique fondamentale de ce qui fonde les droits moraux : l'appartenance à l'espèce humaine, ou certaines capacités cognitives et émotionnelles partagées par d'autres êtres ?</p>"""

pages['physique/primatologie']['content'] = replace_course_content(
    pages['physique/primatologie']['content'],
    primatologie_content
)
print(f"physique/primatologie: {len(pages['physique/primatologie']['content'])} chars")

# ============================================================
# ethnologie/autochtones
# ============================================================
autochtones_content = """<h3>Qui sont les peuples autochtones ? Définitions et enjeux</h3>
<p>La notion de <strong>peuples autochtones</strong> (ou « peuples premiers », « peuples indigènes ») désigne des groupes qui ont des liens historiques avec les terres qu'ils occupaient avant la colonisation, ont maintenu leurs propres systèmes sociaux, culturels et économiques distincts, et s'identifient eux-mêmes comme distincts de la société dominante dans laquelle ils vivent. La <strong>Déclaration des Nations Unies sur les droits des peuples autochtones</strong> (DNUDPA, adoptée en 2007 après 20 ans de négociations) reconnaît leurs droits collectifs à l'autodétermination, à leurs terres, territoires et ressources, et à la préservation de leur culture et de leur identité. L'ONU estime à 476 millions le nombre d'autochtones dans le monde (environ 6 % de la population mondiale), répartis dans plus de 90 pays — représentant 5000 cultures distinctes et plus de 4000 des 7000 langues du monde.</p>
<div class="highlight-box"><p><strong>Définition auto-identitaire :</strong> Une des avancées majeures de la DNUDPA est la reconnaissance que les peuples autochtones définissent eux-mêmes leur appartenance — aucun État ne peut décider unilatéralement qui est ou n'est pas autochtone. Ce principe tranche avec des siècles de définitions imposées par les colonisateurs.</p></div>

<h3>Les peuples de l'Arctique : Inuits et Yupik</h3>
<p>Les peuples circumpolaires — Inuits (Canada, Alaska, Groenland, Sibérie), Yupik (Alaska et Sibérie), Chukchi et Nenets (Sibérie) — ont développé sur des millénaires des cultures d'une sophistication remarquable adaptées aux conditions arctiques extrêmes. La technologie traditionnelle inuit témoigne d'une ingéniosité exceptionnelle : le <strong>kayak</strong> (embarcation à armature de bois ou d'os recouverte de peau de phoque) est hydrodynamiquement si performant que son design a influencé le kayak moderne ; les <strong>lunettes de neige</strong> (lamelles d'os ou d'ivoire percées de fines fentes) préviennent la cécité des neiges ; l'<strong>igloo</strong> (maison de neige) maintient une température intérieure de +10 à +20°C en dehors de températures de -30°C grâce aux propriétés isolantes de la neige.</p>
<p>Le droit international arctique (Convention de l'ONU sur le droit de la mer, accords bilatéraux) est aujourd'hui bousculé par le <strong>réchauffement climatique</strong> qui transforme radicalement les conditions de vie des peuples circumpolaires : recul de la banquise, modification des routes migratoires des animaux, thawing (dégel) du permafrost déstabilisant les infrastructures. L'Inuit Circumpolar Council (ICC), organisation transnationale représentant quelque 180 000 Inuits, a porté en 2005 une pétition devant la Commission interaméricaine des droits de l'homme, accusant les États-Unis de violer les droits inuits par leur politique climatique.</p>

<h3>Les peuples d'Amazonie : gardiens de la forêt</h3>
<p>L'Amazonie abrite plus de 400 groupes autochtones distincts, représentant une extraordinaire diversité linguistique et culturelle. Certains groupes demeurent en <strong>isolement volontaire</strong> (Awá-Guajá, Pirahã, Jarawa en Inde) — des sociétés qui ont délibérément coupé tout contact avec le monde extérieur, parfois en réponse à des épidémies dévastatrices ou à des violences coloniales. La politique brésilienne officielle depuis 1988 est la non-contact — FUNAI (Fondation nationale de l'Indien) surveille ces groupes par avion sans interférence directe.</p>
<p>Les savoirs botaniques des peuples amazoniens sont d'une richesse considérable : leur connaissance de milliers de plantes médicinales, alimentaires et rituelles représente un capital intellectuel collectif qui a contribué à de nombreux médicaments modernes (curare → relaxants musculaires, quinine → antipaludéen, coca → anesthésiques locaux). La question de la <strong>biopiraterie</strong> — l'appropriation par des multinationales de savoirs traditionnels sans compensation ni consentement — est un enjeu juridique et éthique central des droits autochtones contemporains.</p>

<h3>Les Aborigènes d'Australie : 65 000 ans de présence</h3>
<p>Les Aborigènes d'Australie sont l'une des plus anciennes populations humaines vivant en continuité sur un même territoire — les estimations génomiques indiquent une présence d'au moins 50 000 à 65 000 ans en Australie. Leurs systèmes culturels sont d'une complexité remarquable : les <strong>songlines</strong> (chemins du rêve) sont des routes traditionnelles à travers le pays, mémorisées sous forme de chants, de danses et de peintures, qui servent à la fois de cartes géographiques, de récits cosmogoniques et de cadastres territoriaux. Les <strong>systèmes de parenté</strong> australiens sont parmi les plus complexes au monde, avec des sections et des sous-sections régissant les alliances matrimoniales et les obligations cérémonielles.</p>
<div class="highlight-box"><p><strong>Les politiques d'assimilation forcée :</strong> De 1910 à 1970, le gouvernement australien a systématiquement retiré les enfants aborigènes de leurs familles pour les placer dans des pensionnats ou des foyers blancs — la « génération volée » (<em>Stolen Generations</em>). En 2008, le Premier ministre Kevin Rudd a présenté des excuses officielles au Parlement. Les conséquences traumatiques de ces politiques continuent d'affecter les communautés autochtones.</p></div>

<h3>Les peuples San d'Afrique australe : premiers Homo sapiens</h3>
<p>Les peuples San (Bochimans) du Kalahari (Botswana, Namibie, Afrique du Sud) descendent de l'une des lignées humaines les plus anciennes connues par la génomique — les analyses d'ADN mitochondrial placent leur divergence parmi les premières ramifications de l'arbre phylogénétique d'Homo sapiens, il y a plus de 100 000 ans. Chasseurs-cueilleurs dont le mode de vie est adapté depuis des millénaires au désert du Kalahari, ils possèdent une connaissance encyclopédique de la flore et de la faune locales, des techniques de chasse sophistiquées (dont le pistage, une forme de cognition spatiale et inférentielle remarquable documentée par Louis Liebenberg), et un corpus de croyances chamaniques parmi les plus anciens attestés dans l'art rupestre.</p>

<h3>Droits des peuples autochtones et enjeux contemporains</h3>
<p>Malgré la DNUDPA, les peuples autochtones restent parmi les populations les plus marginalisées au monde : niveaux de pauvreté, de mortalité infantile et de suicides significativement plus élevés que les populations non autochtones ; sur-représentation dans les systèmes carcéraux ; perte accélérée des langues ancestrales (une langue autochtone disparaît en moyenne toutes les deux semaines dans le monde). Les enjeux contemporains incluent les droits fonciers (concessions minières, barrages hydroélectriques empiétant sur les terres traditionnelles), la revitalisation linguistique, la décolonisation des musées (restitution des restes humains et objets sacrés), et la participation aux décisions climatiques mondiales — les autochtones étant souvent les premiers affectés par le changement climatique malgré une empreinte carbone minimale.</p>"""

pages['ethnologie/autochtones']['content'] = replace_course_content(
    pages['ethnologie/autochtones']['content'],
    autochtones_content
)
print(f"ethnologie/autochtones: {len(pages['ethnologie/autochtones']['content'])} chars")

# ============================================================
# ethnologie/mondialisation
# ============================================================
mondialisation_content = """<h3>La mondialisation culturelle : diffusion, résistance, hybridation</h3>
<p>La <strong>mondialisation culturelle</strong> désigne l'accélération de la circulation des idées, des pratiques, des biens culturels et des personnes à l'échelle planétaire. Si l'échange culturel est aussi vieux que l'humanité (les routes de la soie, les empires coloniaux, les missions religieuses), le phénomène contemporain se distingue par sa vitesse (internet, médias globaux), son asymétrie (domination de certains centres producteurs — Hollywood, Sony, Google — sur les périphéries) et son amplitude (elle touche des sociétés auparavant isolées). Les anthropologues sont divisés sur ses effets : certains voient dans la mondialisation une <strong>homogénéisation culturelle</strong> menaçant la diversité humaine ; d'autres soulignent les processus d'<strong>hybridation</strong> et de réappropriation créative qui produisent de nouvelles formes culturelles originales.</p>
<div class="highlight-box"><p><strong>McDonaldisation ou glocalization ?</strong> La sociologie de George Ritzer (<em>The McDonaldization of Society</em>, 1993) postule une homogénéisation mondiale par les logiques d'efficacité, calculabilité et prévisibilité des firmes multinationales. Roland Robertson (<em>Glocalization</em>, 1992) répond que le global est toujours adapté au local — le McDonald's de Dehli ne sert pas de bœuf, celui de Paris a une carte distincte, celui de Jakarta des spécialités locales.</p></div>

<h3>Acculturation et ses formes</h3>
<p>L'<strong>acculturation</strong> désigne le processus de transformation culturelle résultant du contact continu entre deux cultures. Le terme, introduit par Powell en 1880 et théorisé par Redfield, Linton et Herskovits (1936), recouvre des phénomènes très divers. Le psychologue John Berry (1997) distingue quatre stratégies d'acculturation adoptées par les individus en situation de contact interculturel : l'<strong>assimilation</strong> (adoption de la culture dominante, abandon de la culture d'origine), l'<strong>intégration</strong> (participation aux deux cultures), la <strong>séparation</strong> (maintien de la culture d'origine sans contact avec la dominante) et la <strong>marginalisation</strong> (perte des deux cultures). Ces stratégies ne sont pas des choix libres — elles dépendent largement des politiques des États d'accueil (assimilationnisme à la française vs multiculturalisme canadien) et des rapports de force entre groupes.</p>

<h3>Créolisation et cultures hybrides</h3>
<p>La notion de <strong>créolisation</strong>, empruntée à la linguistique (les langues créoles émergent du contact de plusieurs langues, avec simplification et innovations propres), a été étendue aux cultures par Édouard Glissant (<em>Poétique de la Relation</em>, 1990) et Ulf Hannerz. Pour Glissant, la créolisation n'est pas une simple addition mais une alchimie imprévisible — les cultures en contact produisent quelque chose de nouveau, irréductible à ses composantes. La musique <strong>soca</strong> (Caraïbes), le <strong>zouk</strong>, le <strong>cumbia</strong>, le <strong>reggaeton</strong> illustrent ces synthèses créatives : des rythmes africains, des harmonies européennes, des instruments et des formes de danse qui n'appartiennent pleinement à aucune des traditions sources. Ces genres sont aujourd'hui eux-mêmes mondialisés, créant de nouvelles hybridations en cascade.</p>
<p>La <strong>World Music</strong> est un exemple instructif de la complexité de ces processus : inventée comme catégorie commerciale par des producteurs britanniques en 1987 pour commercialiser les musiques non occidentales, elle a fourni une plateforme à des musiciens africains, latinos, indiens — mais a aussi suscité des critiques sur l'exotisation, la récupération commerciale et la dépossession créative.</p>

<h3>Revitalisation culturelle et identitaire</h3>
<p>Face à la mondialisation homogénéisante, de nombreux groupes réagissent par des mouvements de <strong>revitalisation culturelle</strong> — la réactivation délibérée d'éléments culturels menacés ou abandonnés. Ces mouvements prennent des formes diverses : renaissance linguistique (hébreu, maori, gallois, basque, breton), réappropriation de pratiques traditionnelles (tatouages polynésiens, cérémonies chamaniques), réinvention de fêtes et rituels (Día de los Muertos commercialisé puis revendicqué par les Mexicains), production d'une littérature et d'un cinéma en langues minoritaires.</p>
<p>Ces revitalisations sont souvent alimentées par le paradoxe que les outils mêmes de la mondialisation — internet, réseaux sociaux, diasporas connectées — sont utilisés pour diffuser et préserver les cultures menacées. Des applications mobiles de langues autochtones, des plateformes de streaming consacrées au cinéma indigène, des archives numériques de musiques traditionnelles témoignent de cette <strong>mondialisation par le bas</strong>.</p>

<h3>Tourisme, patrimoine et marchandisation culturelle</h3>
<p>Le tourisme culturel — qui représente plus de 40 % du tourisme mondial — est l'une des formes les plus ambivalentes de la rencontre interculturelle. D'un côté, il peut générer des revenus pour les communautés locales, favoriser la fierté identitaire et financer la conservation du patrimoine. De l'autre, il crée des risques de <strong>folklorisation</strong> — la transformation de pratiques vivantes en spectacles exotiques figés pour le regard touristique — et de <strong>gentrification culturelle</strong> (les populations locales chassées par la hausse des prix dans les quartiers historiques valorisés). Dean MacCannell (<em>The Tourist</em>, 1976) a montré que le touriste est toujours à la recherche d'une « authenticité » qui est en réalité une construction — les hôtes apprennent à mettre en scène leur culture pour répondre aux attentes des visiteurs (ce qu'Erving Goffman appellerait la « coulisse » vs la « scène »).</p>
<div class="highlight-box"><p><strong>Les Masaï au Kenya :</strong> Les guerriers masaï vendent depuis les années 1970 leur image (vêtements rouges, colliers colorés, sauts rituels) à l'industrie touristique et à la publicité mondiale. Cette marchandisation est à la fois une source de revenus et un vecteur de folklorisation qui peut réifier des pratiques en mutation. Des organisations masaï négocient désormais des droits à l'image collectifs — une forme de propriété intellectuelle collective.</p></div>

<h3>Flux migratoires et diasporas transnationales</h3>
<p>Les <strong>diasporas</strong> — communautés dispersées qui maintiennent des liens avec leur pays d'origine — sont des acteurs majeurs de la mondialisation culturelle. La diaspora indienne (30 millions de personnes), chinoise (60 millions), africaine (200 millions de personnes d'ascendance africaine dans les Amériques) produisent des cultures transnationales irréductibles à aucun État-nation. Les envois de fonds (<em>remittances</em>) des migrants vers leurs pays d'origine représentent globalement davantage que l'aide publique au développement. Les diasporas transmettent aussi dans les deux sens des pratiques culturelles : la cuisine italienne à New York influence la cuisine italienne en Italie, le hip-hop afro-américain est réinterprété en Afrique de l'Ouest et revient transformé aux États-Unis (afrobeats). Ces flux bidirectionnels complexifient les catégories de « culture authentique » et de « culture importée ».</p>"""

pages['ethnologie/mondialisation']['content'] = replace_course_content(
    pages['ethnologie/mondialisation']['content'],
    mondialisation_content
)
print(f"ethnologie/mondialisation: {len(pages['ethnologie/mondialisation']['content'])} chars")

# Save
with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/anthropologie.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved batch 2")
