#!/usr/bin/env python3
"""Fifth pass: neuro-imagerie + conscience pages + second pass on all short pages."""
import json

PATH = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/neurosciences.json"

with open(PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def inject(key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

# ── neuro-imagerie ────────────────────────────────────────────────────────────

inject('neuro-imagerie/irm-fonctionnelle', """
<h3>L'analyse des données IRMf et le problème des comparaisons multiples</h3>
<p class="resume-text">Une acquisition IRMf typique produit environ 100 000 voxels (unités de volume 2-3 mm³) sur 200-300 volumes temporels — soit des millions de tests statistiques pour identifier les régions activées. Le problème des comparaisons multiples est critique : avec un seuil de p < 0,05 non corrigé, 5 000 voxels seraient « significatifs » par hasard. La correction de Bonferroni (division du seuil par le nombre de tests) est trop conservatrice dans ce contexte de tests corrélés spatialement. La méthode FWE (family-wise error) utilisant la théorie des champs aléatoires gaussiens et la méthode FDR (false discovery rate) constituent les approches standard.</p>
<p class="resume-text">Une étude célèbre de Bennett et al. (2009) a montré, en analysant les données IRMf d'un <strong>saumon mort</strong>, des régions « significativement activées » lors de la présentation de photos d'émotions humaines — sans correction pour comparaisons multiples. Cette démonstration humoristique mais pédagogiquement précieuse a accéléré l'adoption des corrections statistiques rigoureuses et alimenté les discussions sur la reproductibilité des résultats en neuroimagerie.</p>
<div class="highlight-box"><p><strong>Reproductibilité :</strong> Une méta-analyse de 2020 (Botvinik-Nezer et al.) a soumis le même jeu de données IRMf à 70 équipes indépendantes. Leurs résultats variaient considérablement : selon l'équipe, entre 4 et 22 des 9 hypothèses testées étaient confirmées. Cette diversité souligne l'importance du pré-enregistrement des hypothèses et des analyses en neuroimagerie.</p></div>

<h3>La connectivité fonctionnelle et les réseaux au repos</h3>
<p class="resume-text">Biswal et al. ont montré en 1995 que les fluctuations lentes du signal BOLD (< 0,1 Hz) au repos sont fortement corrélées entre régions fonctionnellement reliées — même chez un sujet ne faisant rien. Ces corrélations de « connectivité fonctionnelle » révèlent des réseaux intrinsèques stables : le réseau du mode par défaut (médial préfrontal, cingulaire postérieur, précuneus), le réseau de contrôle exécutif (CPFdl bilatéral, pariétal), le réseau sensorimoteur, le réseau visuel. Ces réseaux au repos reflètent l'organisation anatomique sous-jacente et sont perturbés de manière caractéristique dans la schizophrénie, la dépression et la maladie d'Alzheimer.</p>
<p class="resume-text">L'<strong>IRM de connectivité structurelle</strong> (diffusion tensor imaging, DTI) cartographie les faisceaux de matière blanche en mesurant la diffusion anisotrope des molécules d'eau le long des axones myélinisés. Combinée à l'IRMf, elle permet de distinguer connectivité structurelle (quelles régions sont anatomiquement connectées) et fonctionnelle (quelles régions s'activent ensemble), révélant des dissociations importantes : deux régions peuvent être fonctionnellement corrélées sans connexion directe (via un relais thalamique) ou anatomiquement connectées sans corrélation fonctionnelle au repos.</p>
""")

inject('neuro-imagerie/eeg', """
<h3>Les sources cérébrales du signal EEG et la localisation</h3>
<p class="resume-text">Le signal EEG enregistré au scalp est généré principalement par les <strong>courants dipolaires des dendrites apicales</strong> des neurones pyramidaux corticaux organisés en colonnes. Lorsque des milliers de neurones pyramidaux s'activent de manière synchrone et orientés parallèlement, leurs courants s'additionnent pour produire un signal macroscopique mesurable. La résolution spatiale de l'EEG est faible (~ 1-2 cm) en raison du problème inverse : plusieurs configurations de sources peuvent produire le même pattern scalp — le problème inverse n'a pas de solution unique.</p>
<p class="resume-text">Les algorithmes de localisation de sources (LORETA, MUSIC, beamforming) estiment la distribution des sources corticales sous-jacentes en combinant les données EEG avec des contraintes anatomiques issues de l'IRM. Ces méthodes permettent d'atteindre une précision spatiale de 5-10 mm dans des conditions optimales, bien en deçà de l'IRMf mais avec une résolution temporelle incomparable (1 ms versus ~1 s). L'EEG haute densité (256 électrodes) améliore significativement la localisation spatiale.</p>
<div class="highlight-box"><p><strong>EEG et interfaces cerveau-machine :</strong> Les EEG peuvent contrôler des prothèses, des ordinateurs et des fauteuils roulants par décodage des intentions motrices. Le paradigme P300-speller permet à des patients paralysés d'épeler des mots à raison de 5-10 caractères par minute en détectant la composante P300 (pic positif à 300 ms après le stimulus cible). Des BCI (brain-computer interfaces) EEG portables sont désormais commercialisés pour la communication assistée.</p></div>

<h3>Les rythmes EEG et leurs bases neurales</h3>
<p class="resume-text">Les différentes bandes de fréquence EEG reflètent des états cognitifs et des mécanismes neuraux distincts. Les ondes <strong>delta</strong> (0,5-4 Hz), dominantes en sommeil profond, sont générées par des oscillations intrinsèques thalamocorticales ; elles reflètent la consolidation mnésique. Les ondes <strong>thêta</strong> (4-8 Hz) de l'hippocampe et du cortex frontal accompagnent la navigation spatiale, la mémoire de travail et la méditation. Les ondes <strong>alpha</strong> (8-12 Hz), découvertes par Hans Berger en 1929, sont maximales lors de la relaxation les yeux fermés et reflètent l'inhibition des cortex non engagés.</p>
<p class="resume-text">Les ondes <strong>bêta</strong> (15-30 Hz) accompagnent la pensée active et le maintien d'un état moteur stable. Leur amplitude est réduite lors de la préparation motrice (désynchronisation motrice événementielle) et restaurée après le mouvement. Les ondes <strong>gamma</strong> (30-80 Hz), les plus difficiles à mesurer en raison de leur faible amplitude et de leur contamination par les artefacts myographiques, sont associées aux liaisons perceptuelles et aux états attentionnels focaux. Les oscillations haute fréquence (> 80 Hz) sont visibles en EEG intracrânien mais rarement au scalp.</p>
""")

inject('neuro-imagerie/tep', """
<h3>Les traceurs TEP et leurs applications cliniques</h3>
<p class="resume-text">La richesse de la TEP vient de la diversité de ses traceurs. Le <strong>[18F]-FDG</strong> (fluorodésoxyglucose) marque la consommation de glucose, reflet de l'activité métabolique : utilisé en oncologie pour détecter les tumeurs hypermétaboliques, en neurologie pour diagnostiquer les démences (hypométabolisme temporopariétal dans la maladie d'Alzheimer). Le <strong>[15O]-eau</strong> permet de mesurer le débit sanguin cérébral régional en temps quasi-réel, avec des acquisitions de 60 secondes par condition — précurseur de l'IRMf. L'<strong>[18F]-DOPA</strong> permet de visualiser l'intégrité des terminaisons dopaminergiques striatales, quantifiant la perte précoce dans la maladie de Parkinson et différenciant les syndromes parkinsoniens.</p>
<p class="resume-text">Les traceurs amyloïdes (Pittsburgh Compound B [11C-PiB], <sup>18</sup>F-florbetapir, <sup>18</sup>F-florbetaben) se lient spécifiquement aux plaques amyloïdes de la maladie d'Alzheimer, permettant leur détection in vivo des années avant l'apparition des symptômes cliniques. Les traceurs tau (<sup>18</sup>F-flortaucipir) permettent de cartographier les dépôts de protéine tau, dont la distribution prédit mieux que l'amyloïde le déclin cognitif. Ces traceurs amyloïdes et tau sont aujourd'hui intégrés dans les critères diagnostiques révisés de la maladie d'Alzheimer (critères A/T/N).</p>
<div class="highlight-box"><p><strong>TEP et psychiatrie :</strong> La TEP au [18F]-fallypride, traceur des récepteurs D2/D3 dopaminergiques, a révélé une réduction de 10-30 % de la densité des récepteurs D2 striataux chez les personnes dépendantes à l'alcool, à la cocaïne ou aux opioïdes — éclairant le mécanisme de la tolérance et fournissant un biomarqueur objectif de la neuroadaptation addictive.</p></div>

<h3>Les développements récents : TEP simultanée avec IRM</h3>
<p class="resume-text">Les systèmes TEP/IRM hybrides, commercialisés depuis 2010, permettent l'acquisition simultanée des deux modalités dans le même scanner. L'IRM fournit les informations anatomiques de haute résolution et corrige les artefacts de mouvement et d'atténuation des tissus nécessaires à la reconstruction TEP. En retour, la TEP apporte la spécificité moléculaire que l'IRM seule ne peut fournir. Ces systèmes permettent d'étudier simultanément, chez le même sujet dans la même session, la densité des récepteurs dopaminergiques (TEP) et les fluctuations du réseau de récompense (IRMf) lors d'une tâche d'anticipation de gain.</p>
<p class="resume-text">La TEP totale corps (total-body PET), avec un champ de vue de 194 cm couvrant l'organisme entier, est la dernière génération de scanners TEP. Elle permet de mesurer simultanément la distribution d'un traceur dans le cerveau, le cœur, le foie et les reins avec une sensibilité 40 fois supérieure aux systèmes conventionnels, ouvrant la voie à des études systémiques cerveau-corps et à une réduction de la dose de radioactivité injectée d'un facteur 10.</p>
""")

inject('neuro-imagerie/magnetoencephalographie', """
<h3>Les principes physiques et les capteurs SQUID</h3>
<p class="resume-text">La magnétoencéphalographie (MEG) mesure les champs magnétiques infimes générés par les courants des dendrites apicales des neurones pyramidaux. Ces champs, de l'ordre du femtotesla (10⁻¹⁵ T — soit un milliard de fois plus faible que le champ magnétique terrestre), nécessitent des capteurs d'une sensibilité extrême : les SQUIDs (superconducting quantum interference devices), des jonctions Josephson superconductrices fonctionnant à -269°C (hélium liquide). Un système MEG typique comprend 200-300 capteurs SQUID disposés dans un casque adapté à la morphologie crânienne, opérant dans une salle blindée magnétiquement.</p>
<p class="resume-text">Contrairement à l'EEG, la MEG est peu affectée par la résistance des tissus (crâne, cuir chevelu) qui brouille le signal électrique. Elle est particulièrement sensible aux sources corticales <strong>tangentielles</strong> (dans les sillons corticaux, perpendiculaires au scalp), là où l'EEG est aveugle. Les deux modalités sont complémentaires et souvent utilisées conjointement (EEG-MEG combiné) pour une localisation optimale des sources. Des systèmes MEG à capteurs OPM (optically pumped magnetometers) à température ambiante sont en développement, promettant des dispositifs portables et moins coûteux.</p>
<div class="highlight-box"><p><strong>MEG et épilepsie chirurgicale :</strong> La MEG est approuvée cliniquement pour la cartographie préchirurgicale de l'épilepsie : elle localise avec précision les foyers épileptiques et les aires eloquentes (langage, motricité) à préserver lors de la résection. Sa résolution temporelle (1 ms) est essentielle pour tracer la propagation des décharges épileptiques en temps réel.</p></div>

<h3>Oscillations cérébrales et couplage phase-amplitude</h3>
<p class="resume-text">La MEG révèle avec précision la dynamique des oscillations cérébrales grâce à sa haute résolution temporelle. Le <strong>couplage phase-amplitude</strong> (PAC) est un phénomène particulièrement étudié : la phase d'une oscillation lente (thêta, 4-8 Hz) module l'amplitude d'une oscillation rapide (gamma, 30-80 Hz). Dans l'hippocampe, la phase des oscillations thêta organise les décharges en séquences ordonnées — la précession de phase — permettant d'encoder l'ordre temporel des événements dans un épisode mémoriel.</p>
<p class="resume-text">Ce couplage thêta-gamma, mesurable en MEG au scalp grâce à des algorithmes dédiés, augmente lors de tâches de mémoire de travail et est réduit chez les patients schizophrènes. Le couplage entre oscillations lentes du cortex préfrontal et oscillations rapides hippocampiques sous-tend la synchronisation top-down permettant au cortex de « requêter » l'hippocampe lors du rappel mémoriel — une fenêtre sur la communication inter-régionale que seule la haute résolution temporelle de la MEG rend accessible.</p>
""")

inject('neuro-imagerie/optogenetique', """
<h3>La dissection causale des circuits neuronaux</h3>
<p class="resume-text">L'optogénétique, développée par Edward Boyden et Karl Deisseroth (prix Lasker 2021), permet de <strong>contrôler causalement</strong> l'activité de types cellulaires spécifiques avec une précision temporelle milliseconde. En exprimant une channelrhodopsine (protéine canal sensible à la lumière bleue, activatrice) ou une halorhodopsine (canal chlorure sensible à la lumière jaune, inhibitrice) sous le contrôle d'un promoteur spécifique d'un type cellulaire, on peut activer ou inhiber sélectivement les interneurones PV+, les neurones dopaminergiques, ou les neurones de projection corticaux — pendant qu'un animal se comporte librement.</p>
<p class="resume-text">Cette révolution méthodologique a permis de tester causalement des hypothèses impossibles à vérifier avec les corrélations de neuroimagerie. Activer les neurones de place de l'hippocampe correspondant à un lieu précis pendant le sommeil améliore sélectivement le souvenir de la navigation dans ce lieu — prouvant causalement le rôle de la réactivation pendant le sommeil dans la consolidation mnésique. Réactiver pendant le sommeil une assemblée de neurones encodant un souvenir désagréable tout en supprimant les signaux de récompense peut modifier la valence émotionnelle du souvenir chez la souris — démonstration saisissante de la malléabilité mnésique.</p>
<div class="highlight-box"><p><strong>Applications cliniques en développement :</strong> L'optogénétique thérapeutique commence à atteindre l'humain. GenSight Biologics a obtenu en 2021 une preuve de concept de restauration partielle de la vision chez un patient atteint de rétinite pigmentaire, en exprimant une channelrhodopsine dans les cellules ganglionnaires de la rétine. Les vecteurs viraux (AAV) nécessaires à l'expression des opsines dans les cellules humaines sont maintenant en essais cliniques pour plusieurs pathologies rétiniennes.</p></div>

<h3>Les nouvelles opsines et l'expansion du toolkit optogénétique</h3>
<p class="resume-text">La palette d'opsines disponibles s'est considérablement élargie depuis la channelrhodopsine originale. Les <strong>opsines rouges</strong> (ChrimsonR, ReaChR) sont activées par une lumière moins phototoxique et pénétrant plus profondément dans les tissus. Les <strong>opsines inhibitrices chlorure</strong> (GtACR1/2) sont 10 fois plus efficaces que la halorhodopsine. Les <strong>opsines à étapes</strong> (step-function opsins, SFO) restent ouvertes des secondes à des minutes après une brève impulsion lumineuse, permettant une modulation prolongée de l'excitabilité sans éclairage continu.</p>
<p class="resume-text">L'optogénétique s'étend désormais au-delà du contrôle électrique : les <strong>récepteurs-opsines chimères</strong> (OptoGPCR, OptoXR) permettent d'activer des voies de signalisation intracellulaire spécifiques (AMPc, IP3, Rho GTPases) avec une lumière, déclenchant des effets métaboliques à long terme dans des types cellulaires définis. Ces outils permettent de disséquer les contributions respectives des différentes voies de signalisation d'un même neurotransmetteur dans un comportement complexe.</p>

<h3>La combinaison optogénétique-imagerie et les thérapies futures</h3>
<p class="resume-text">La combinaison de l'optogénétique avec l'imagerie calcique (GCaMP) permet simultanément de contrôler et d'enregistrer l'activité neuronale dans le même circuit : on peut activer une cellule et observer comment son activation se propage dans le réseau, ou inhiber un neurone et mesurer son impact sur l'ensemble du réseau. Ces approches <em>all-optical</em> révèlent la structure causale des circuits avec une résolution cellulaire et temporelle sans précédent.</p>
<p class="resume-text">La perspective de thérapies optogénétiques pour des maladies psychiatriques (dépression résistante, troubles obsessionnels compulsifs) est explorée précliniquement. Chez la souris, l'activation des neurones dopaminergiques de l'ATV produit un effet antidépresseur robuste dans des modèles d'impuissance acquise. La stimulation des neurones infralimbiques préfrontaux réverses les comportements dépressifs. Ces cibles, si elles peuvent être atteintes de manière sûre chez l'humain via des vecteurs viraux et une fibre optique implantée, représentent la prochaine frontière des neurotechnologies thérapeutiques.</p>
""")

print("Neuro-imagerie pages done.")
for key in ['neuro-imagerie/irm-fonctionnelle','neuro-imagerie/eeg','neuro-imagerie/tep','neuro-imagerie/magnetoencephalographie','neuro-imagerie/optogenetique']:
    print(f"  {key}: {len(pages[key]['content'])} chars")

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved.")
