#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement botanique-zoologie - batch 2 (ornithologie + biologie-marine)."""

import json, re

FILE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/botanique-zoologie.json"

ENRICHMENTS = {
"ornithologie/diversite-oiseaux": """
<h3>L'origine des oiseaux : les dinosaures à plumes</h3>
<p class="resume-text">Les oiseaux sont des dinosaures theropodes à plumes qui ont survécu à l'extinction de masse du Crétacé-Paléogène. Cette conclusion, longtemps débattue, est aujourd'hui solidement étayée par la paléontologie et la génomique. L'Archaeopteryx, découvert en Bavière en 1861 et daté de 150 Ma, présente des caractères intermédiaires entre dinosaures theropodes et oiseaux modernes : plumes, furcula ("os de la chance"), empreintes d'ailes, mais aussi dents, griffes aux ailes et longue queue osseuse. Des centaines de dinosaures à plumes découverts depuis en Chine (Formation de Yixian, Liaoning) ont considérablement enrichi notre compréhension de la transition dinosaures-oiseaux.</p>
<p class="resume-text">La diversification des oiseaux modernes (Neornithes) a explosé après l'extinction K-Pg : en 15 millions d'années, la quasi-totalité des ordres actuels sont apparus. Cette radiation adaptative spectaculaire a produit les 10 000 espèces actuelles, des manchots incapables de voler aux colibris qui battent des ailes 80 fois par seconde, des autruches de 150 kg aux astérides de 2 grammes. Les analyses phylogénomiques récentes ont révélé des surprises : les flamants sont les plus proches parents des grèbes, et les coucous sont liés aux grues plutôt qu'aux perroquets.</p>
<div class="highlight-box"><p>L'Archaeopteryx était doté de plumes noires (révélé par analyse des mélanosomes fossiles en 2012), capable de voler activement (structure des plumes asymétriques comme les oiseaux modernes), mais grimpait aussi probablement aux arbres (griffes courbées). C'était un animal à la frontière entre deux mondes — ni dinosaure ni oiseau moderne, mais un "chaînon intermédiaire" qui illustre parfaitement la continuité de l'évolution.</p></div>

<h3>Adaptation au vol : l'anatomie aérienne</h3>
<p class="resume-text">L'anatomie des oiseaux est entièrement optimisée pour le vol. Le squelette est pneumatisé (os creux renforcés par des trabécules internes), réduisant le poids sans sacrifier la résistance. La furcula (clavicules soudées) agit comme ressort élastique qui stocke et restitue de l'énergie lors du battement d'ailes. Le sternum possède un bréchet (crête osseuse) d'où s'insèrent les puissants muscles pectoraux qui représentent jusqu'à 25 % du poids corporel chez les espèces à vol actif. Les plumes, extensions épidermiques à base de kératine, combinent légèreté, résistance et aérodynamisme grâce à leur structure en barbes, barbules et crochets (hamuli).</p>
<p class="resume-text">Les différentes formes d'ailes reflètent différentes stratégies de vol : ailes longues et étroites des albatros (vol plané dynamique au-dessus des vagues), ailes larges et fendues des rapaces thermiciens (vol plané en montées d'air chaud), ailes courtes et arrondies des passereaux forestiers (manoeuvrabilité entre les branches), ailes en faucille des martinets (vol rapide à haute altitude). Le martin-pêcheur a inspiré le nez des trains Shinkansen japonais à grande vitesse : sa forme effilée lui permet de plonger dans l'eau sans projeter de vague, et une ingénieure a transposé ce principe pour réduire la vague sonore des trains passant dans des tunnels.</p>
<div class="highlight-box"><p>Le martinet noir (Apus apus) est le champion de l'endurance aérienne : il ne se pose jamais en dehors de la nidification. Des études de bio-logging avec des géolocalisateurs ont montré qu'un jeune martinet peut voler sans interruption pendant 10 mois (octobre à août de l'année suivante), dormant en vol et se nourrissant à la surface des thermiques. Sur une vie de 20 ans, un martinet parcourt l'équivalent de 6 voyages vers la Lune.</p></div>
""",

"ornithologie/migration-oiseaux": """
<h3>Les routes migratoires mondiales : les voies de passage</h3>
<p class="resume-text">La migration des oiseaux s'organise selon des couloirs migratoires mondiaux (flyways) qui concentrent les déplacements saisonniers. La voie de passage de l'Atlantique Est relie l'Europe et l'Asie du Nord à l'Afrique subsaharienne, canalisant des millions d'oiseaux à travers des "goulots d'étranglement" comme le détroit de Gibraltar (où jusqu'à 300 000 rapaces traversent en une journée d'automne) et la mer Rouge. La voie de passage centrale de l'Asie relie la Sibérie à l'Asie du Sud. Ces concentrations font de certains points géographiques des sites d'observation ornithologique majeurs et des zones de conservation critiques.</p>
<p class="resume-text">La migration nocturne est la règle pour la plupart des passereaux migrateurs : ils naviguent la nuit guidés par les étoiles, et s'alimentent et se reposent en journée. Cette stratégie réduit le risque de prédation par les rapaces diurnes et permet d'exploiter les thermiques moins développés la nuit pour certaines espèces. Des études radar ornithologique ont révélé que des milliards d'oiseaux migrent chaque nuit au-dessus de l'Europe en automne — une "rivière silencieuse" invisible pour la plupart des humains mais détectable sur les radars météorologiques.</p>
<div class="highlight-box"><p>L'impact des tours de communication et des fenêtres illuminées la nuit sur les oiseaux migrateurs est documenté : attirés par les lumières des villes lors de nuits nuageuses, des millions d'oiseaux meurent chaque année en heurtant des vitrages ou des structures. Aux États-Unis, des programmes "Lights Out" demandent aux propriétaires de bâtiments d'éteindre leurs lumières pendant les nuits de migration intense (détectées par radar) pour réduire ces mortalités.</p></div>

<h3>L'énergie de la migration : carburant et stratégies d'escale</h3>
<p class="resume-text">La migration est un exploit énergétique. Les oiseaux accumulent des réserves de graisses (jusqu'à doubler leur poids corporel) avant le départ, qui leur servent de carburant. Le rouge-gorge (Erithacus rubecula) peut parcourir 700 km en une nuit en consommant 5 % de son poids en graisse. La bécassine des marais (Gallinago gallinago) vole sans escale de 3 500 km au-dessus de l'Atlantique. La barge à queue noire (Limosa lapponica baueri) détient le record absolu : elle vole sans escale de 11 000 km depuis l'Alaska jusqu'en Nouvelle-Zélande, en 8 à 9 jours — consommant plus de 50 % de sa masse corporelle en carburant lipidique.</p>
<p class="resume-text">Les escales migratoires sont des étapes critiques où les oiseaux doivent refaire leurs réserves rapidement. La qualité et la disponibilité des zones d'escale (zones humides côtières, prairies, forêts) sont des facteurs limitants pour de nombreuses espèces. Le bécasseau maubèche (Calidris canutus) dépend de la baie du Delaware (États-Unis) en mai pour se gaver d'œufs de limule (Limulus polyphemus), doublant son poids en deux semaines avant de terminer sa migration vers l'Arctique. La surpêche des limules (utilisées en médecine) a provoqué une chute dramatique des bécasseaux maubèches — une interdépendance trophique sur 5 000 km de distance.</p>
<div class="highlight-box"><p>Des bio-loggers miniaturisés (géolocalisateurs, GPS, accéléromètres) ont révolutionné notre connaissance de la migration. Un moucherolle tyrannique (Tyrannus tyrannus) de 40 grammes équipé d'un géolocalisateur de 0,5 g a été suivi depuis le Canada jusqu'en Amazonie (5 000 km), révélant des routes insoupçonnées et des escales dans des zones menacées de déforestation — informations précieuses pour définir les priorités de conservation.</p></div>
""",

"ornithologie/chant-oiseaux": """
<h3>La production du chant : le syrinx, organe vocal unique</h3>
<p class="resume-text">Le chant des oiseaux est produit par le syrinx, un organe vocal unique aux oiseaux situé à la bifurcation de la trachée en deux bronches. Contrairement au larynx des mammifères (situé en haut de la trachée), le syrinx permet aux oiseaux oscines (passereaux chanteurs) de produire deux sons simultanément indépendants — un de chaque bronche — créant des harmonies impossibles pour les mammifères. Les muscles syringeaux des oscines sont parmi les plus développés et les plus nombreux de l'anatomie aviaire ; chez le rouge-gorge, ils représentent 0,5 % du poids corporel mais sont capables de variations extrêmement rapides (notes de moins de 10 ms).</p>
<p class="resume-text">L'apprentissage du chant chez les oscines suit un processus remarquablement parallèle à l'acquisition du langage chez l'humain. Il existe une période sensible tôt dans la vie pendant laquelle les jeunes oiseaux "mémorisent" le chant d'un tuteur (généralement le père ou un voisin). Ils passent ensuite par une phase de chant subsong (gazouillement exploratoire) avant d'affiner progressivement leur chant vers le modèle mémorisé. Des études de neuro-imagerie ont identifié les centres cérébraux du chant (HVC, RA, Area X), qui présentent des analogies fonctionnelles avec les régions du langage du cerveau humain — ce qui fait des oiseaux chanteurs un modèle précieux pour la recherche sur les troubles du langage.</p>
<div class="highlight-box"><p>Le lyrebird superbe (Menura novaehollandiae) d'Australie est le plus virtuose imitateur du règne animal : il copie avec une fidélité stupéfiante les chants d'autres oiseaux, mais aussi des sons environnementaux incluant des tronçonneuses, des déclencheurs d'appareils photo, des klaxons et même la mélodie d'une flûte entendue dans sa forêt. Ces imitations sont intégrées dans ses chants de parade nuptiale, avec lesquels il séduit les femelles.</p></div>

<h3>Fonction et diversité des vocalises : plus que du chant</h3>
<p class="resume-text">Les vocalises des oiseaux remplissent plusieurs fonctions distinctes. Le chant territorial (émis généralement par les mâles adultes) défend le territoire contre les congénères et attire les femelles. Les cris d'alarme (calls) avertissent les congénères de la présence d'un prédateur — et sont souvent compris par des espèces différentes qui partagent les mêmes prédateurs. Les contacts calls maintiennent la cohésion du groupe en vol. Les cris de nourrissage signalent la disponibilité de nourriture. Ces vocalises ont des structures acoustiques différentes adaptées à leur fonction : les cris d'alarme face aux rapaces aériens sont des sons aigus et longs difficiles à localiser (protection de l'émetteur) ; les cris d'alarme face aux prédateurs terrestres sont brefs et percheurs (permettant une localisation rapide pour que les congénères s'éloignent de la source du danger).</p>
<p class="resume-text">Le dialecte géographique dans le chant des oiseaux est un phénomène culturel bien documenté. Des mésanges d'une même espèce en France chantent différemment selon les régions — des dialectes transmis culturellement de génération en génération. Des expériences de déplacement d'individus entre régions montrent que les jeunes oiseaux adoptent le dialecte local, tandis que les adultes conservent souvent leur dialecte d'origine. Ces dialectes peuvent jouer un rôle dans la sélection sexuelle (les femelles préférant les mâles au dialecte local) et contribuer à une différenciation génétique progressive entre populations.</p>
<div class="highlight-box"><p>Les études de "bioacoustique urbaine" montrent que les oiseaux chanteurs adaptent leurs chants aux villes : les rouges-gorges de Glasgow chantent la nuit (quand le bruit de la circulation est moindre) ; les merlots de villes européennes chantent à des fréquences plus élevées pour se faire entendre au-dessus du bruit de fond grave des véhicules. Ces adaptations comportementales rapides (en quelques générations) illustrent la plasticité phénotypique face à la pollution sonore urbaine.</p></div>
""",

"ornithologie/nidification": """
<h3>Diversité des nids : de la simplicité au chef d'œuvre architectural</h3>
<p class="resume-text">Les nids d'oiseaux présentent une diversité remarquable de formes, matériaux et localisations, reflet des pressions évolutives exercées par les prédateurs, le parasitisme de couvée, le climat et la disponibilité des ressources. Les grèbes construisent des plates-formes flottantes de végétation aquatique amarrées aux roseaux. Le fou de Bassan amasse algues et déchets en une masse compactée par sa fiente. Le tisserand (famille Ploceidae) tresse des structures sphériques suspendues à des branches fines, avec une entrée dirigée vers le bas pour décourager les serpents. Le maçon (Furnarius rufus) d'Amérique du Sud construit un nid en argile d'un kilogramme en forme de four avec chambre intérieure à l'abri des intempéries.</p>
<p class="resume-text">La nidification en colonie (colonies de goélands, de hérons, de fous, de flamants) présente des avantages : protection collective contre les prédateurs, information partagée sur les sites de nourrissage. Mais elle crée aussi des contraintes sanitaires (accumulation de déchets, parasites) et sociales (vols d'œufs entre voisins). Certaines espèces nichent en cavités (mésanges, pics, chouettes) qui offrent une protection thermique et contre les prédateurs, mais dont la disponibilité peut être limitante — d'où l'intérêt des nichoirs artificiels pour compenser le déficit de vieux arbres à cavités dans les forêts gérées.</p>
<div class="highlight-box"><p>Le nid de l'aigle fauve (Aquila rapax) peut peser plusieurs tonnes et faire 2 mètres de diamètre après des décennies de construction et de réutilisation. Le nid le plus lourd jamais enregistré appartenait à un aigle chauve (Haliaeetus leucocephalus) en Floride : 2,7 tonnes et 2,9 m de diamètre. Ces édifices partagés entre générations constituent de véritables micro-habitats pour des dizaines d'espèces qui y vivent en commensaux.</p></div>

<h3>La reproduction et les soins parentaux</h3>
<p class="resume-text">Les oiseaux investissent considérablement dans les soins parentaux. L'incubation (maintenir les œufs à la température optimale de 37-38 °C) peut durer de 11 jours (colibris) à 80 jours (kiwi, qui pond un œuf représentant 20 % de son poids corporel — le plus grand œuf par rapport à la taille de la femelle dans le règne animal). Le macareux moine (Fratercula arctica) incube son unique œuf pendant 39 à 45 jours en se relevant pour le retourner régulièrement. La plaque incubatrice (zone de plumes du ventre très vascularisée) transfère directement la chaleur corporelle aux œufs.</p>
<p class="resume-text">Le développement post-éclosion distingue deux stratégies : les nidicoles (altriciales) naissent nus, aveugles et incapables de se nourrir seuls (passeaux, rapaces) et requièrent des semaines à des mois de soins intenses ; les nidifuges (précociales) naissent couverts de duvet, les yeux ouverts, et peuvent se déplacer et se nourrir presque immédiatement (canards, poules, bécasseaux). La stratégie nidicole permet un développement cérébral plus prolongé, associé à de meilleures capacités cognitives — les corvides (nidicoles) sont parmi les oiseaux les plus intelligents.</p>
<div class="highlight-box"><p>Le coucou commun (Cuculus canorus) est le parasite de couvée le plus étudié d'Europe : il pond ses œufs dans les nids d'autres espèces (en 10 secondes pendant que le propriétaire s'absente) et ses poussins expulsent les œufs et poussins légitimes. La course évolutive entre le coucou (qui imite de mieux en mieux les œufs de son hôte) et l'hôte (qui reconnaît de mieux en mieux les œufs fraudeurs) est un exemple classique de coévolution en bras de fer.</p></div>

<h3>Le parasitisme de couvée et autres stratégies alternatives</h3>
<p class="resume-text">Le parasitisme de couvée, où une espèce confie ses œufs aux soins d'une autre, a évolué indépendamment chez plusieurs familles d'oiseaux (coucous, vacher, indicateur). Chez le vacher à tête brune (Molothrus ater) d'Amérique du Nord, les femelles pondent dans les nids de plus de 220 espèces hôtes différentes sans mimétisme d'œuf — une stratégie de volume plutôt que de précision. Les hôtes qui reconnaissent et rejettent les œufs parasites (oiseaux à forte reconnaissance) sont favorisés par sélection naturelle, forçant le parasite à adapter son mimétisme. Cette course évolutive a produit des œufs de coucou européen si parfaitement mimétiques qu'ils trompent souvent l'œil humain.</p>
<p class="resume-text">Des stratégies intermédiaires existent : le dumping d'œufs intraspecifique (des femelles pondent discrètement dans les nids de congénères) est fréquent chez les fuligules et les bernaches. La nidification coopérative (auxiliaires qui aident les reproducteurs à élever les jeunes sans être eux-mêmes parents) est pratiquée par de nombreuses espèces tropicales (geais du Mexique, merlebleus) : les auxiliaires, souvent des enfants de l'année précédente, augmentent le succès reproducteur des parents en portant de la nourriture aux poussins et en défendant le territoire.</p>
<div class="highlight-box"><p>L'indicateur de miel (Indicator indicator) d'Afrique communique avec les Boran (chasseurs-cueilleurs du Kenya) : en émettant un cri spécifique et en voletant en zigzag, il guide les humains vers les ruches sauvages pour partager le butin. Cette interaction mutualiste entre un oiseau sauvage et l'homme — unique dans le règne animal pour ce degré de coopération volontaire — est documentée depuis des siècles et fait l'objet d'études scientifiques récentes.</p></div>
""",

"ornithologie/conservation-oiseaux": """
<h3>Les menaces pesant sur l'avifaune mondiale</h3>
<p class="resume-text">Les oiseaux sont parmi les groupes fauniques les mieux suivis grâce à des réseaux de bénévoles et de scientifiques. Les tendances sont alarmantes : le rapport "State of the World's Birds" de BirdLife International (2022) estime que 49 % des espèces d'oiseaux ont des populations en déclin. En Europe, les oiseaux communs des milieux agricoles ont perdu 57 % de leurs effectifs en 40 ans. La France a perdu 25 % de ses oiseaux en 15 ans, avec des effondrements dramatiques pour des espèces autrefois communes : alouette des champs (-62 %), bruant proyer (-59 %), perdrix grise (-70 %). La destruction et la dégradation des habitats (agriculture intensive, urbanisation, drainage des zones humides) sont les premières causes.</p>
<p class="resume-text">La pollution lumineuse désoriente les migrateurs nocturnes ; la pollution sonore masque les signaux de communication et d'alarme ; les collisions avec les infrastructures tuent chaque année entre 100 et 900 millions d'oiseaux aux États-Unis (vitres, câbles électriques, éoliennes, pylônes) et plusieurs dizaines de millions en Europe. Les chats errants et domestiques seraient responsables de 1 à 4 milliards de morts aviaires par an en Amérique du Nord. Les pesticides déciment les insectes, base alimentaire de la plupart des oiseaux insectivores et de leurs poussins.</p>
<div class="highlight-box"><p>Le déclin du rollier d'Europe (Coracias garrulus), un des plus beaux oiseaux d'Europe, illustre les liens entre agriculture et oiseaux : nichant dans des cavités arborées des paysages ouverts méditerranéens, il se nourrit d'orthoptères (criquets, sauterelles) dont les populations ont effondré avec l'intensification agricole. En France, sa population est passée de plusieurs milliers de couples dans les années 1950 à moins de 50 couples aujourd'hui.</p></div>

<h3>Les succès de conservation : les raisons d'espérer</h3>
<p class="resume-text">Face aux tendances alarmantes, des succès de conservation réels existent et montrent que l'extinction n'est pas une fatalité avec des politiques adaptées. Le vautour percnoptère (Neophron percnopterus) bénéficie d'un plan de conservation coordonné à l'échelle eurafricaine (Espagne, France, Balkans, Afrique) incluant des abreuvoirs, des parcs d'équarrissage, la réduction de l'empoisonnement et des programmes de réintroduction. Les effectifs européens se sont stabilisés. Le gypaète barbu (Gypaetus barbatus), réintroduit dans les Alpes depuis 1986, compte désormais plus de 250 individus en Europe — un exemple de réintroduction réussie à l'échelle d'un continent.</p>
<p class="resume-text">Le milan royal (Milvus milvus), symbole de l'ornithologie européenne, a bénéficié au Royaume-Uni d'une réintroduction spectaculaire depuis 1989 : l'espèce, éteinte en Angleterre depuis 200 ans, compte maintenant plus de 6 000 couples après la réintroduction de 93 individus gallois et espagnols. En France, les effectifs ont doublé en 20 ans grâce à des mesures de lutte contre l'empoisonnement et à la protection des sites de nidification. Ces succès illustrent l'efficacité des mesures de protection quand elles sont maintenues sur le long terme.</p>
<div class="highlight-box"><p>L'ONCFS (Office national de la chasse et de la faune sauvage), devenu l'OFB (Office français de la biodiversité), coordonne depuis les années 1990 des programmes nationaux de dénombrement des oiseaux communs (STOC-EPS, suivi temporel des oiseaux communs) impliquant 1 200 bénévoles formés qui effectuent chaque année des points d'écoute standardisés. Ces données constituent une des bases de suivi des oiseaux les plus riches d'Europe, fournissant des indicateurs clés pour les politiques de biodiversité.</p></div>

<h3>Science participative et ornithologie citoyenne</h3>
<p class="resume-text">L'ornithologie est la science naturelle qui bénéficie le plus de la science participative (science citoyenne). Les ligues pour la protection des oiseaux (LPO en France, RSPB au Royaume-Uni, Audubon Society aux États-Unis) mobilisent des millions de bénévoles dans des programmes de surveillance : comptages des oiseaux des jardins, recensements de rapaces en migration, suivis de colonies de reproduction, atlas des oiseaux nicheurs. En France, le programme STOC-EPS (1989-présent) avec ses 1 200 points d'écoute annuels est la base de données sur les oiseaux communs la plus longue d'Europe.</p>
<p class="resume-text">L'application eBird, développée par l'Université Cornell depuis 2002, a révolutionné la collecte de données ornithologiques mondiales : plus de 800 000 observateurs dans 200 pays enregistrent leurs observations en temps réel, créant une base de données de plusieurs milliards d'occurrences. Ces données alimentent des modèles de distribution d'espèces, des prévisions de migration en temps réel et des analyses de tendances de population à l'échelle mondiale. La citizen science ornithologique produit désormais plus de données que l'ensemble de la recherche professionnelle — un changement de paradigme dans la surveillance de la biodiversité.</p>
<div class="highlight-box"><p>Le Grand Comptage des Oiseaux des Jardins (GCOJ), organisé chaque hiver par la LPO, mobilise des centaines de milliers de participants en France qui observent et comptent pendant une heure les oiseaux qui fréquentent leurs jardins. Ces données massives permettent de suivre les tendances des espèces communes et de détecter les variations inhabituelles liées aux conditions météorologiques ou aux maladies — une contribution irremplaçable à la biodiversité monitoring.</p></div>
""",

"biologie-marine/ecosystemes-marins": """
<h3>Zonation des écosystèmes marins : de la côte aux profondeurs</h3>
<p class="resume-text">Les océans sont organisés en zones définies par la profondeur, la lumière et la distance à la côte. La zone intertidale (ou zone de balancement des marées) est l'une des plus stressantes de l'océan : les organismes y subissent alternativement immersion et émersion, chaleur et froid, dessiccation et humidité, salinité variable. Elle a produit des adaptations remarquables : les patelles (Patella spp.) peuvent résister à 45 °C pendant plusieurs heures, les anatifes (cirripèdes) se ferment hermétiquement lors de l'émersion. La zonation verticale de cet habitat (différentes espèces à différentes hauteurs selon leur tolérance) est un exemple pédagogique classique d'organisation des communautés.</p>
<p class="resume-text">La zone néritique (plateau continental, 0-200 m) est la plus productive des océans : elle reçoit la lumière solaire nécessaire à la photosynthèse et est enrichie en nutriments par les apports fluviaux et les remontées d'eaux profondes (upwellings). Les grandes pêcheries mondiales (morue, hareng, anchois, sardine) sont concentrées sur les plateaux continentaux. La zone pélagique hauturière s'étend au-delà du plateau et représente le plus grand habitat de la planète : 1 400 millions de km³ d'eau. La zone bathyale (200-4 000 m) et abyssale (4 000-6 000 m) sont privées de lumière et caractérisées par une pression colossale, une température froide (2-4 °C) et une faible disponibilité en nourriture.</p>
<div class="highlight-box"><p>Les upwellings côtiers — remontées d'eaux froides et riches en nutriments des profondeurs vers la surface, causées par les vents et la rotation de la Terre — représentent moins de 1 % de la surface des océans mais produisent environ 20 % des captures mondiales de poisson. Les zones d'upwelling les plus productives (Pérou-Chili, Californie, Afrique du Nord-Ouest, Afrique du Sud) sont des hotspots de vie marine conditionnés par les courants atmosphériques et océaniques.</p></div>

<h3>Les courants marins : circulation globale et régulation climatique</h3>
<p class="resume-text">La circulation thermohaline (ou circulation méridionale de retournement de l'Atlantique, AMOC) est un système de courants océaniques à l'échelle planétaire, souvent métaphorisé comme un "tapis roulant" océanique. Les eaux de surface chaudes des tropiques voyagent vers les pôles où elles se refroidissent et s'alourdissent (plus denses car plus froides et plus salées après évaporation), plongent vers les profondeurs et reviennent lentement vers les tropiques en profondeur. Ce circuit complet prend environ 1 000 à 2 000 ans. La composante atlantique (Gulf Stream - AMOC) transporte 25 fois le débit de tous les fleuves mondiaux réunis et apporte à l'Europe occidentale une chaleur qui lui confère un climat 5 à 10 °C plus doux que des régions aux mêmes latitudes en Amérique du Nord.</p>
<p class="resume-text">Le changement climatique menace l'AMOC : la fonte des glaces du Groenland injecte de grandes quantités d'eau douce moins dense dans l'Atlantique Nord, perturbant le mécanisme de plongée des eaux. Des études récentes indiquent que l'AMOC est à son niveau le plus faible depuis au moins 1 600 ans, et certains modèles projettent un effondrement partiel d'ici la fin du siècle dans les scénarios de forte émission — ce qui pourrait paradoxalement refroidir l'Europe de 5 à 10 °C tout en accélérant le réchauffement global.</p>
<div class="highlight-box"><p>Les océans absorbent environ 30 % du CO₂ émis par les activités humaines et plus de 90 % de l'excès de chaleur. Cette capacité d'absorption, qui nous protège du réchauffement climatique, a un coût : l'acidification des océans (pH passé de 8,2 à 8,1 en 200 ans, soit une augmentation de 26 % de l'acidité) et le réchauffement des eaux de surface (hausse de 0,6 °C depuis 1969) menacent des écosystèmes marins entiers.</p></div>
""",

"biologie-marine/recifs-coralliens": """
<h3>La biologie du corail : l'animal qui construit des continents</h3>
<p class="resume-text">Les coraux constructeurs de récifs sont des cnidaires (polypes) vivant en symbiose obligatoire avec des algues unicellulaires photosynthétiques appelées zooxanthelles (dinoflagellés du genre Symbiodinium). Cette symbiose est au cœur de la productivité des récifs : les zooxanthelles fournissent jusqu'à 90 % de l'énergie du corail via la photosynthèse, en échange d'une protection, de CO₂ et de nutriments. Le corail, en retour, construit son squelette calcaire (aragonite) à une vitesse de 1 à 10 cm par an selon les espèces — la Grande Barrière de Corail australienne (346 000 km²) est la plus grande structure biologique jamais construite sur Terre, visible depuis l'espace.</p>
<p class="resume-text">Les récifs coralliens sont des systèmes hautement oligotrophes (pauvres en nutriments) qui maintiennent néanmoins une productivité et une biodiversité extraordinaires grâce à des cycles biogéochimiques extrêmement efficaces. Ce paradoxe, connu comme le "paradoxe de Darwin", a été résolu : les récifs recyclent les nutriments en circuits très courts via des réseaux trophiques complexes, avec peu de pertes vers l'eau environnante. La sponge loop (boucle des éponges), décrite récemment, montre que les éponges absorbent le mucus translucide des coraux (invisible mais très abondant) et le transforment en particules organiques consommables par les invertébrés du récif.</p>
<div class="highlight-box"><p>Les récifs coralliens couvrent moins de 0,1 % de la surface des océans mais abritent environ 25 % de toutes les espèces marines décrites (plus de 1 million d'espèces, dont beaucoup non encore décrites). Ils fournissent des services ecosystémiques estimés à 375 milliards de dollars par an : pêche, protection des côtes, tourisme, pharmacologie (de nombreux médicaments ont été développés à partir d'organismes récifaux).</p></div>

<h3>Le blanchissement des coraux : mécanismes et conséquences</h3>
<p class="resume-text">Le blanchissement (bleaching) des coraux se produit quand le stress thermique (dépassement de 1 à 2 °C au-dessus du maximum habituel pendant plusieurs semaines) provoque l'expulsion des zooxanthelles par le polype. Sans leurs algues symbiotiques, les coraux perdent leur couleur et jusqu'à 90 % de leur énergie. Si le stress cesse rapidement, les coraux peuvent récupérer leurs zooxanthelles et survivre. Mais si le blanchissement dure plus de 8 semaines, la mort du corail est quasiment inévitable. L'acidification des océans affaiblit également les squelettes calcaires des coraux en réduisant la disponibilité des ions carbonate nécessaires à la calcification.</p>
<p class="resume-text">Les épisodes de blanchissement massif se multiplient avec le changement climatique : la Grande Barrière de Corail a connu des événements majeurs en 1998, 2002, 2016, 2017, 2020 et 2022, tuant dans certaines zones plus de 50 % des coraux. L'UICN a classifié en 2021 les coraux constructeurs de récifs (Millepora et Acropora) comme "en danger critique" à l'échelle mondiale. À +1,5 °C de réchauffement, 70 à 90 % des récifs coralliens seraient dégradés ; à +2 °C, plus de 99 % disparaîtraient — faisant des récifs l'écosystème le plus sensible au changement climatique.</p>
<div class="highlight-box"><p>Des équipes de scientifiques australiens travaillent sur la "sélection assistée" de coraux résistants à la chaleur : ils identifient des génotypes naturellement plus tolérants aux températures élevées et les propagent sur les récifs dégradés. Des projets de coraux génétiquement modifiés (zooxanthelles thermotolérantes) sont également en cours d'expérimentation — une course contre la montre pour sauver un écosystème menacé à l'échelle de décennies.</p></div>
""",

"biologie-marine/plancton": """
<h3>La classification du plancton : de la taille au rôle</h3>
<p class="resume-text">Le plancton regroupe tous les organismes de l'océan qui dérivent passivement avec les courants, incapables de nager contre eux. Cette définition fonctionnelle recouvre une extraordinaire diversité biologique. Le phytoplancton (algues microscopiques) comprend les diatomées (cellules de silice aux formes géométriques élaborées), les dinoflagellés (certains bioluminescents), les coccolithophores (calcaires, produisant des dépôts de craie) et les cyanobactéries (bactéries photosynthétiques). Le zooplancton hétérotrophe comprend les copépodes (crustacés microscopiques dominant la biomasse animale océanique), les krill (crustacés de 1-6 cm qui nourrissent les baleines et manchots), les méduses et leurs larves, les chaetognathes, les salpes et les larves de nombreux animaux benthiques.</p>
<p class="resume-text">La classification par taille est aussi utilisée en écologie marine : le femtoplancton (virus : 0,02-0,2 µm), le picoplancton (bactéries, petites algues : 0,2-2 µm), le nanoplancton (2-20 µm), le microplancton (20-200 µm, dont la plupart des diatomées), le mésoplancton (200 µm-2 cm, dont le krill), le macroplancton (2-20 cm, dont les grands copépodes et méduses) et le mégaplancton (>20 cm, comme les grandes méduses et les pyrosomes). La distinction taille/biologie est importante car les relations trophiques planctioniques ne suivent pas toujours les taxonomies classiques.</p>
<div class="highlight-box"><p>En 2003, la découverte par Craig Venter de l'expédition Sorcerer II a révélé une diversité bactérienne océanique stupéfiante : en séquençant l'ADN total de l'eau de mer, ils ont identifié plus de 1,2 million de gènes nouveaux dans un seul litre d'eau, appartenant à des milliers d'espèces bactériennes auparavant inconnues. Cette "genomique métagénomique" a révolutionné notre vision de la diversité microbienne océanique.</p></div>

<h3>La productivité primaire océanique : les pâturages bleus</h3>
<p class="resume-text">Le phytoplancton est responsable d'environ 50 % de la photosynthèse mondiale, produisant chaque année autant d'oxygène que toutes les forêts et prairies terrestres réunies. Sa distribution n'est pas uniforme : les zones océaniques les plus productives correspondent aux régions où les nutriments (azote, phosphore, silicium pour les diatomées, fer) sont disponibles en surface. Les upwellings côtiers, les zones frontales entre masses d'eau différentes et les mers polaires en été sont les "pâturages bleus" de l'océan mondial.</p>
<p class="resume-text">La limitation par le fer dans certaines zones océaniques a conduit à des expériences de "fertilisation en fer" à grande échelle : ajouter des nanoparticules de sulfate de fer dans les eaux polaires pour stimuler le phytoplancton et espérer augmenter l'absorption de CO₂ atmosphérique (océan comme puits de carbone). Ces expériences (IRONEX, SOIREE, LOHAFEX) ont provoqué des efflorescences phytoplanctoniques spectaculaires, mais les bénéfices en termes de séquestration de carbone ont été décevants : une grande partie du carbone fixé est remis en circulation rapidement par le zooplancton plutôt que de couler vers les profondeurs.</p>
<div class="highlight-box"><p>Les marées rouges (HAB, Harmful Algal Blooms) sont des proliférations massives de phytoplancton (souvent des dinoflagellés toxiques comme Alexandrium ou Karenia brevis) qui peuvent teinter la mer de rouge ou de brun et produire des toxines bioaccumulables. Ces toxines se concentrent dans les coquillages filtreurs (moules, huîtres), causant des intoxications humaines graves (paralytique, diarrhéique, amnésique). Le changement climatique et l'eutrophisation côtière augmentent la fréquence et l'étendue géographique des HAB.</p></div>

<h3>Le pompe biologique à carbone : rôle climatique du plancton</h3>
<p class="resume-text">La pompe biologique à carbone est le processus par lequel le phytoplancton absorbe le CO₂ atmosphérique via la photosynthèse, le transforme en matière organique, et lorsque ces organismes meurent ou sont consommés, une fraction de ce carbone coule vers les profondeurs (séquestration sur des centaines à des milliers d'années). Cette pompe soustrait environ 11 gigatonnes de carbone de l'atmosphère chaque année. Sans elle, la concentration atmosphérique en CO₂ serait environ 200 ppm plus élevée qu'elle ne l'est.</p>
<p class="resume-text">Le krill antarctique (Euphausia superba) joue un rôle clé dans cette pompe : des nuages de krill qui descendent vers les profondeurs la nuit pour éviter les prédateurs, puis remontent en surface de jour, transportent du carbone en profondeur via leurs fèces et excrétion d'ammonium — une migration verticale qui équivaut à pomper du carbone hors de la zone photique. Le krill antarctique représente une biomasse totale de 379 millions de tonnes, l'une des plus grandes de la planète, et constitue la base alimentaire des baleines, manchots, phoques et poissons du Southern Ocean.</p>
<div class="highlight-box"><p>Le Tara Oceans, projet scientifique franco-international (2009-2013), a prélevé des milliers d'échantillons plancioniques dans tous les océans du monde et séquencé leur ADN. Les résultats publiés en 2015 dans Science ont révélé que les réseaux trophiques plancioniques sont beaucoup plus complexes qu'on ne le pensait, impliquant des millions d'interactions entre virus, bactéries, protistes et métazoaires — et que la composition de ces communautés est déterminée largement par la température et la disponibilité en nutriments.</p></div>
""",

"biologie-marine/abysses": """
<h3>Les conditions extrêmes des grandes profondeurs</h3>
<p class="resume-text">Les grandes profondeurs océaniques (au-delà de 4 000 m) constituent le plus grand habitat de la planète et l'un des moins connus. Leurs conditions physiques sont extrêmes : pression colossale (400 à 1 100 atmosphères, soit 40 000 à 110 000 kPa), température quasi-constante de 2-4 °C (sauf aux évents hydrothermaux), obscurité totale, et rareté de la nourriture. Malgré ces conditions, la vie abyssale est d'une diversité insoupçonnée. Des estimations récentes suggèrent que les sédiments abyssaux abritent entre 10 millions et 10 milliards d'espèces de nématodes, la grande majorité encore non décrites.</p>
<p class="resume-text">Les adaptations des organismes abyssaux à la pression sont remarquables. Les poissons des grandes profondeurs ont des membranes cellulaires enrichies en acides gras insaturés (plus fluides à haute pression), des muscles contenant de l'oxyde de triméthylamine (TMAO) qui compense l'effet de dénaturation des protéines par la pression, et des squelettes souvent réduits ou absents. La pression permet des solutions physicochimiques originales : certains crustacés abyssaux utilisent l'acide lactique comme "cryprotecteur" — leur hémolymphe ne gèle pas même à des températures proches de zéro.</p>
<div class="highlight-box"><p>En 2012, le réalisateur James Cameron a plongé seul jusqu'au fond de la Fosse des Mariannes (10 898 m de profondeur) à bord du submersible Deepsea Challenger. Il a observé des crevettes, des anémones et des holothuries à cette profondeur record — confirmant que la vie s'adapte aux conditions les plus extrêmes. La pression à cette profondeur est équivalente à être écrasé par 50 avions de ligne empilés.</p></div>

<h3>Les évents hydrothermaux : oasis de vie sans soleil</h3>
<p class="resume-text">La découverte en 1977 des évents hydrothermaux (cheminées noires, "black smokers") dans la Zone de Fracture des Galápagos a bouleversé notre compréhension de la vie sur Terre. Ces fissures du fond océanique, où l'eau de mer s'infiltre, est chauffée à 300-400 °C par la chaleur magmatique, se charge en minéraux (sulfures, métaux), puis remonte sous forme de panaches ("fumée noire" de sulfure de fer précipitant). À leur contact, des communautés biologiques prospèrent sans lumière solaire, basées sur la chimiosynthèse : des bactéries utilisent l'énergie chimique des sulfures d'hydrogène pour fixer le CO₂, formant la base d'un réseau trophique indépendant du soleil.</p>
<p class="resume-text">La faune des évents hydrothermaux comprend des espèces uniques et spectaculaires : le ver tubicole géant Riftia pachyptila (jusqu'à 2,4 m de long, sans bouche ni tube digestif, nourri par des bactéries chimiosynthétiques endosymbiotes dans son trophosome), des crevettes aveugles munies de photorécepteurs dorsaux capables de détecter la lumière infrarouge des évents, des crabes yéti couverts de bactéries chimiosynthétiques sur leurs pattes, et des poulpes de Dumbo. Ces communautés sont éphémères : un évent actif dure quelques décennies à des siècles avant de se déplacer, forçant les espèces à disperser leurs larves sur de longues distances.</p>
<div class="highlight-box"><p>La découverte des évents hydrothermaux a modifié notre vision de la vie dans le cosmos : si la vie peut exister sans lumière solaire, alimentée par l'énergie chimique géothermique, des océans souterrains sous la glace d'Europe (lune de Jupiter) ou d'Encelade (lune de Saturne) pourraient abriter de la vie. L'astrobiologie considère désormais ces mondes océaniques comme des cibles prioritaires dans la recherche de vie extraterrestre.</p></div>

<h3>Les neiges marines et les chutes de baleines</h3>
<p class="resume-text">La neige marine (marine snow) est la pluie de particules organiques qui tombe continuellement des eaux de surface vers les profondeurs : fragments de phytoplancton mort, excrétats de zooplancton, mucus d'organismes filtreurs. Cette neige organique est la principale source de nourriture des écosystèmes abyssaux et joue un rôle crucial dans la pompe biologique à carbone. Des organismes filtrent la neige marine à chaque profondeur, créant des flux verticaux de matière organique qui appauvrissent les eaux en nutriments de surface et enrichissent les fonds.</p>
<p class="resume-text">Les "chutes de baleine" (whale falls) sont des événements rares et importants pour les écosystèmes abyssaux : quand une baleine meurt, son cadavre coule lentement vers le fond et devient un oasis de nourriture extraordinaire dans un environnement qui en manque cruellement. Les premières "décomposeurs" (requins dormeurs, hagfishes, crabes) dévorent les tissus mous en quelques mois. Puis des polychètes et crustacés consomment le cadavre plus lentement. Enfin, des bactéries chimiosynthétiques colonisent les os lipidiques (riches en graisses) pendant des décennies, créant une mini-communauté évento-hydrothermal. Une seule baleine bleue peut nourrir cet écosystème pendant 70 ans.</p>
<div class="highlight-box"><p>L'exploitation minière des fonds marins représente une menace émergente pour les écosystèmes abyssaux. Les nodules polymétalliques (riches en manganèse, cobalt, nickel et cuivre) qui tapissent les plaines abyssales sont convoités pour la transition énergétique (ils contiennent des métaux nécessaires aux batteries). Mais leur extraction détruirait des habitats qui ont mis des millions d'années à se constituer et dont certains organismes ne vivent nulle part ailleurs.</p></div>
""",

"biologie-marine/mammiferes-marins": """
<h3>La diversité des mammifères marins : retour à la mer</h3>
<p class="resume-text">Les mammifères marins représentent environ 130 espèces réparties en cinq ordres : les cétacés (baleines, dauphins, marsouins), les carnivores marins (phoques, lions de mer, morses, loutres de mer, ours polaire), les siréniens (dugong, lamantins) et — parfois inclus — les loutres de rivière. Ces ordres ont des origines évolutives différentes mais ont tous secondairement colonisé le milieu marin depuis des ancêtres terrestres. Les cétacés descendent d'artiodactyles (groupe comprenant les hippopotames, les ruminants) qui ont commencé leur adaptation aquatique il y a 50 millions d'années (Pakicetus, ancêtre aquatique des cétacés). Les pinnipèdes (phoques, otaries) descendent d'ursidés ou de mustélidés selon les sous-familles.</p>
<p class="resume-text">L'adaptation aux milieux marins a produit des convergences évolutives remarquables entre groupes distants. La forme fuselée (hydrodynamique) est partagée par les dauphins, les ichtyosaures (reptiles marins disparus) et les requins — trois lignées convergentes sans lien évolutif proche. La plongée apnéique profonde a évolué indépendamment chez les cétacés (cachalot à 3 000 m) et les pinnipèdes (éléphant de mer à 2 000 m) avec des adaptations similaires : rate gigantesque stockant des érythrocytes riches en hémoglobine, myoglobine musculaire très concentrée (muscles bruns-noirs), réflexe de plongée (bradycardie, vasoconstriction périphérique).</p>
<div class="highlight-box"><p>L'éléphant de mer du Nord (Mirounga angustirostris) fait partie des plongeurs les plus impressionnants : il peut descendre à 2 000 mètres de profondeur et retenir son souffle pendant 2 heures. Pendant sa migration de 18 000 km, il passe 90 % de son temps en mer sous l'eau, ne dormant que quelques minutes par heure. Des capteurs biologiques ont révélé qu'il dort en descendant lentement en spirale — un "sommeil en chute libre" au milieu de l'océan.</p></div>

<h3>Communication et cognition des cétacés</h3>
<p class="resume-text">Les cétacés possèdent parmi les systèmes de communication les plus sophistiqués du règne animal. L'écholocation des odontocètes (dauphins, cachalots, belugas) utilise des clics ultrasoniques produits dans le complexe "melon" de leur front (tissu adipeux focalisant les sons) et reçus via la mandibule inférieure : ce sonar biologique permet de localiser des proies à des centaines de mètres, de distinguer des objets de quelques millimètres et de "voir" à travers les corps des congénères (les dauphins peuvent détecter la gestation d'une femelle). La résolution spatiale de leur sonar est supérieure à celle des meilleurs radars militaires.</p>
<p class="resume-text">Les mysticètes (baleines à fanons) communiquent par des chants de basse fréquence qui peuvent voyager sur des milliers de kilomètres dans le canal SOFAR (Sound Fixing And Ranging), une couche océanique à 1 000 m de profondeur où les sons se propagent particulièrement loin. La baleine à bosse (Megaptera novaeangliae) est célèbre pour ses chants complexes qui évoluent continuellement : tous les mâles d'un même bassin océanique chantent la même "chanson" à un moment donné, mais cette chanson change progressivement au fil de la saison, se propageant d'ouest en est comme une vague culturelle. Ces chants, dont la durée peut atteindre 20 heures, sont une forme de communication culturelle unique dans le règne animal.</p>
<div class="highlight-box"><p>Le chant de la "Baleine 52 Hz" (surnommée "the loneliest whale") est émis à une fréquence de 52 Hz au lieu des 15-25 Hz habituels des baleines bleues — une fréquence trop haute pour être perçue par les autres baleines bleues. Découverte en 1992 par des hydrophones de la Marine américaine, elle a été repérée chaque année depuis lors, se déplaçant seule dans le Pacifique Nord. Son identité taxonomique reste inconnue, et son histoire a inspiré un documentaire (2021) et de nombreuses réflexions sur la solitude et la communication.</p></div>

<h3>Conservation des mammifères marins : menaces et espoirs</h3>
<p class="resume-text">Les mammifères marins ont été décimés par la chasse commerciale au XIXe et XXe siècles. La baleine bleue (Balaenoptera musculus), le plus grand animal ayant jamais existé (jusqu'à 33 m, 190 tonnes), a vu ses populations mondiales réduites de 98 % par la chasse industrielle, passant de 350 000 individus à moins de 10 000 au nadir dans les années 1960. Le moratoire international sur la chasse commerciale (Commission baleinière internationale, 1986) a permis une lente récupération de certaines populations, mais d'autres restent critiquement menacées. La Vaquita (Phocoena sinus), un petit marsoin du golfe de Californie, compte moins de 10 individus en 2024 — le cétacé le plus menacé du monde.</p>
<p class="resume-text">Les menaces actuelles des mammifères marins incluent les captures accidentelles dans les engins de pêche (bycatch) — principale cause de mortalité pour de nombreuses espèces de dauphins et de phoques — le bruit sous-marin (interférant avec la communication des cétacés et causant des échouages de baleines lors d'exercices militaires sonar), la pollution chimique (les PFAS, PCB et mercure s'accumulent dans les tissus adipeux des grands prédateurs), les collisions avec les navires, et le changement climatique (disparition de la banquise arctique pour les ours polaires, modifications des proies pour les baleines).</p>
<div class="highlight-box"><p>La réintroduction de la loutre de mer (Enhydra lutris) sur les côtes de Californie après sa quasi-extinction par la chasse au XVIIIe-XIXe siècle a démontré son rôle d'espèce-clé de voûte : la loutre mange les oursins, qui sans prédateur prolifèrent et dévorent les forêts de kelp (algues géantes). Avec le retour des loutres, les oursins sont régulés, le kelp se régénère, abritant des centaines d'espèces et absorbant du CO₂. Ce "cercle vertueux" illustre l'importance des prédateurs apex pour la santé des écosystèmes marins.</p></div>
"""
}

def inject_before_quiz(content, new_text):
    pattern = r'(</section>\s*\n\n<section[^>]*id="quiz")'
    result = re.sub(pattern, new_text + r'\1', content)
    if result == content:
        pattern2 = r'(</section>\s*<section[^>]*id="quiz")'
        result = re.sub(pattern2, new_text + r'\1', content)
    return result

with open(FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

modified = 0
for key, enrichment in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        if page.get('type') in ('course', 'lesson'):
            orig = len(page['content'])
            page['content'] = inject_before_quiz(page['content'], enrichment)
            new = len(page['content'])
            print(f"  {key}: {orig} -> {new} (+{new-orig})")
            modified += 1

with open(FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone. {modified} pages modified.")
with open(FILE, 'r', encoding='utf-8') as f:
    check = json.load(f)
pages = check['pages']
short = [(k, len(pages[k].get('content',''))) for k in pages if pages[k].get('type') in ('course','lesson') and len(pages[k].get('content','')) < 10000]
print(f"Pages still < 10000: {len(short)}")
for k,l in short:
    print(f"  {l:6d} | {k}")
print("JSON valid.")
