import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

# Generic booster blocks per hub topic - tailored to each page's theme
boosters = {
'energie/energies-renouvelables': (
    '<h3>Prospective et scénarios de transition énergétique</h3>'
    '<p class="resume-text">Les <strong>scénarios de transition énergétique</strong> (IEA Net Zero 2050, RTE Futurs Énergétiques 2050) modélisent les trajectoires pour atteindre la neutralité carbone. En France, le scénario NégaWatt propose 100% de renouvelables d\'ici 2050 via sobriété (réduction de la consommation), efficacité (meilleure utilisation de l\'énergie) et renouvelables. Le scénario RTE "M23" maintient un socle nucléaire renouvelé (nouveau nucléaire EPR2 + SMR) combiné à un déploiement massif d\'éolien et de solaire. Ces scénarios montrent que la décarbonation totale est techniquement possible mais exige des investissements considérables (30-40 milliards d\'euros/an en France).</p>'
    '<p class="resume-text">L\'<strong>agrivoltaïsme</strong> combine la production agricole et la production solaire sur les mêmes parcelles. Les panneaux surélevés (2-3 m de hauteur) permettent les cultures et le pâturage sous les panneaux. Les premiers retours montrent des co-bénéfices : réduction de l\'évapotranspiration (eau économisée), protection contre les intempéries (gel, grêle), revenus diversifiés pour les agriculteurs. La France vise 6 GW d\'agrivoltaïsme en 2027, encadrés par la loi d\'accélération des énergies renouvelables de 2023.</p>'
    '<div class="highlight-box"><p>L\'agrivoltaïsme peut réduire les besoins en eau d\'irrigation de 20 à 30% sous les panneaux — un co-bénéfice précieux dans un contexte de sécheresses récurrentes liées au changement climatique.</p></div>'
),
'energie/stockage-energie': (
    '<h3>Économie du stockage et modèles d\'affaires</h3>'
    '<p class="resume-text">Les <strong>revenus des systèmes de stockage</strong> proviennent de plusieurs sources : arbitrage (achat d\'électricité bon marché pour revendre lors des pics), services systèmes (régulation de fréquence, réserves rapides), capacité (rémunération de la disponibilité), et tarification par pic (peak shaving, réduction de la puissance souscrite). La combinaison de ces flux (value stacking) est nécessaire pour rentabiliser les systèmes de stockage. Les logiciels de gestion (BEMS — Battery Energy Management System) optimisent en temps réel les décisions charge/décharge.</p>'
    '<p class="resume-text">Le <strong>stockage derrière le compteur</strong> (BTM — Behind The Meter) chez les industriels et les particuliers connaît une croissance explosive. Les batteries domestiques (Tesla Powerwall, SMA Sunny Boy Storage, Enphase IQ Battery) couplées aux panneaux solaires permettent l\'autoconsommation maximale. Les industriels gros consommateurs investissent dans des BESS (Battery Energy Storage Systems) de plusieurs MWh pour effacer leurs pics de puissance et éviter les coûts de dépassement.</p>'
    '<div class="highlight-box"><p>Le coût du stockage par batterie Li-ion en application stationnaire a atteint 100 $/kWh en 2024 — en dessous du seuil de rentabilité pour de nombreuses applications réseau. D\'ici 2030, les prévisions tablent sur 60 $/kWh.</p></div>'
),
'mecanique/dynamique-des-systemes': (
    '<h3>Simulation multi-physique et jumeau numérique</h3>'
    '<p class="resume-text">La <strong>simulation multi-physique</strong> couplée (mécanique + thermique + électromagnétique + fluide) est indispensable pour les systèmes complexes. Un moteur électrique se chauffe (thermique), ce qui change ses propriétés magnétiques (électromagnétique), ce qui modifie son couple (mécanique), ce qui change sa vitesse et donc ses pertes. Ces couplages nécessitent des solveurs co-simulation (FMI — Functional Mock-up Interface) qui font dialoguer des logiciels spécialisés (ANSYS Maxwell + Fluent + Mechanical). La co-simulation est le standard de conception dans l\'automobile électrique et la robotique.</p>'
    '<p class="resume-text">Le <strong>jumeau numérique</strong> (digital twin) d\'un système mécanique est un modèle numérique synchronisé en temps réel avec son homologue physique via des capteurs IoT. GE Digital utilise des jumeaux numériques de turbines à gaz (400 capteurs, mise à jour toutes les 5 min) pour détecter les anomalies de vibration, prédire la durée de vie des aubes et planifier la maintenance. Siemens déploie des jumeaux numériques de lignes de production pour optimiser les cadences et simuler les changements de configuration avant leur déploiement.</p>'
    '<div class="highlight-box"><p>GE a créé des jumeaux numériques pour plus de 300 000 actifs industriels (moteurs d\'avion, turbines, compresseurs) — réduisant les pannes non planifiées de 10 à 25% et les coûts de maintenance de 5 à 10%.</p></div>'
),
'mecanique/machines-et-mecanismes': (
    '<h3>Actionneurs innovants et mécanismes du futur</h3>'
    '<p class="resume-text">Les <strong>actionneurs piézoélectriques</strong> génèrent des déplacements nanométriques à kilométriques (amplifiés) avec une réponse en fréquence de plusieurs kHz. Les micro-actionneurs piézo (PZT) positionnent les têtes de lecture des disques durs avec une précision de 10 nm. Les tables de translation piézo (PI, Physik Instrumente) permettent des positionnements sub-nanométriques pour la microscopie et la lithographie. Les moteurs ultrasoniques piézo (utilisés dans les appareils photo pour l\'autofocus silencieux) développent de forts couples à basse vitesse sans réducteur.</p>'
    '<p class="resume-text">Les <strong>alliages à mémoire de forme</strong> (SMA — Shape Memory Alloys, NiTi ou Nitinol) changent de forme lorsque leur température franchit un seuil de transformation martensitique. Ils peuvent se contracter de 8% en longueur sous l\'effet de la chaleur, développant des contraintes de 500 MPa. Utilisés dans les stents cardiaques (se déploient à la température corporelle), les actionneurs d\'ailerons d\'avion adaptatifs et les gouvernes de petits drones, les SMA offrent un actionnement compact et silencieux au prix d\'une réponse lente.</p>'
    '<div class="highlight-box"><p>Le Nitinol (alliage nickel-titane à mémoire de forme) est utilisé dans 3 millions de stents cardiaques posés chaque année — il se comprime pour être guidé dans les artères, puis se déploie spontanément à la température du corps.</p></div>'
),
'energie/energie-nucleaire': (
    '<h3>Radioprotection et gestion des déchets radioactifs</h3>'
    '<p class="resume-text">La <strong>radioprotection</strong> protège les travailleurs et le public des rayonnements ionisants. Le principe ALARA (As Low As Reasonably Achievable) vise à maintenir l\'exposition au rayonnement aussi basse que raisonnablement possible. Les doses sont mesurées en millisieverts (mSv) : 1 mSv/an est la limite légale pour le public en France (hors médical) ; les travailleurs du nucléaire sont limités à 20 mSv/an sur 5 ans. La surveillance par dosimétrie passive (films, TLD) et active (appareils électroniques) assure le suivi continu des expositions.</p>'
    '<p class="resume-text">La <strong>filière de gestion des déchets radioactifs</strong> (FED) classe les déchets par activité et durée de vie. Les déchets TFA (Très Faible Activité, vêtements, outils) vont en surface (Cires). Les déchets FMA (Faible et Moyenne Activité) sont stockés à Soulaines (Aube). Les déchets FAVL (Faible Activité, Vie Longue) ont besoin d\'un stockage intermédiaire. Les déchets HA/MAVL (Haute Activité ou Vie Longue) iront dans le stockage géologique profond CIGÉO à Bure — une installation dimensionnée pour des dizaines de milliers d\'années de confinement.</p>'
    '<div class="highlight-box"><p>La France produit chaque année 2,2 kg de déchets radioactifs de haute activité par habitant — mais la quasi-totalité du volume (90%) est de déchets TFA ou FMA-VC peu dangereux. Seuls 3% en volume sont de haute activité, mais ils représentent 95% de la radioactivité totale.</p></div>'
),
'mecanique/resistance-des-materiaux': (
    '<h3>Normes et codes de conception</h3>'
    '<p class="resume-text">Les <strong>Eurocodes</strong> (EN 1990 à EN 1999) constituent le cadre normatif européen pour la conception des structures. L\'Eurocode 3 (structures en acier) et l\'Eurocode 2 (béton armé) sont les plus utilisés en génie civil. L\'Eurocode 8 (parasismique) s\'applique dans les zones de risque sismique. Ces normes prescrivent les combinaisons de charges, les coefficients partiels de sécurité et les méthodes de vérification aux états limites. Leur harmonisation européenne facilite la libre circulation des ingénieurs et des produits de construction.</p>'
    '<p class="resume-text">En <strong>mécanique industrielle</strong>, les codes ASME (American Society of Mechanical Engineers) régissent la conception des appareils à pression (chaudières, récipients sous pression, tuyauteries). L\'ASME VIII Division 1 (appareils à pression courants) et Division 2 (analyse par contraintes) permettent deux niveaux de conception. En France, la réglementation ESP (Équipements Sous Pression, Directive 2014/68/UE) transpose ces exigences. La certification CE des ESP requiert l\'intervention d\'un organisme notifié (Apave, Bureau Veritas) pour le contrôle et les essais.</p>'
    '<div class="highlight-box"><p>Les Eurocodes structuraux sont utilisés dans 27 pays européens et au-delà — leur harmonisation a représenté 30 ans de travaux de comités techniques réunissant des centaines d\'ingénieurs et chercheurs de toute l\'Europe.</p></div>'
),
'mecanique/tribologie': (
    '<h3>Tribologie à l\'échelle micro et nano</h3>'
    '<p class="resume-text">La <strong>nanotribologie</strong> étudie le frottement et l\'usure à l\'échelle des atomes et des molécules. Le microscope à force atomique (AFM) mesure des forces de frottement de quelques piconewtons entre une pointe nanométrique et une surface. Ces expériences révèlent que le frottement à l\'échelle atomique n\'obéit pas toujours aux lois macroscopiques de Coulomb : il dépend de la commensurabilité cristallographique des surfaces (superlubricity entre des surfaces incommensurables), de l\'orientation des molécules de lubrifiant et des liaisons chimiques interfaciales.</p>'
    '<p class="resume-text">La <strong>superlubrification</strong> (superlubricity) est un état de quasi-absence de frottement (coefficient de frottement < 0,01) observé entre des surfaces incommensurables (graphène sur h-BN, graphite sur graphite orienté différemment) ou des surfaces recouvertes de molécules spécifiques. En conditions ambiantes, des équipes de l\'Argonne National Laboratory ont démontré la superlubrification entre une microsphère de diamant et du graphène sur DLC, avec un coefficient de frottement de 0,004 — des perspectives révolutionnaires pour les micromécanismes et les MEMS.</p>'
    '<div class="highlight-box"><p>La superlubrification entre deux couches de graphène incommensurables donne un coefficient de frottement de 0,001 — mille fois moins que l\'acier sur acier huilé. Des microactionneurs exploitant ce phénomène pourraient transformer les MEMS.</p></div>'
),
'mecanique/forces-et-mouvements': (
    '<h3>Mécanique des fluides computationnelle (CFD)</h3>'
    '<p class="resume-text">La <strong>CFD</strong> (Computational Fluid Dynamics) simule les écoulements de fluides en résolvant numériquement les équations de Navier-Stokes. La discretisation du domaine fluide en millions de cellules (maillage) et l\'utilisation de modèles de turbulence (k-ε, k-ω, LES) permettent de calculer les champs de vitesse, pression et température. Les logiciels ANSYS Fluent, OpenFOAM et Star-CCM+ sont standards dans l\'aéronautique, l\'automobile, l\'énergie et le biomédical. Une simulation CFD d\'un avion complet peut nécessiter 100 millions de cellules et plusieurs jours de calcul sur des supercalculateurs.</p>'
    '<p class="resume-text">En <strong>ingénierie du vent</strong>, la CFD et les souffleries physiques permettent d\'optimiser la forme des bâtiments, ponts et ouvrages pour réduire les charges de vent et les effets aérodynamiques néfastes. Les couches limites atmosphériques, les effets de recirculation entre bâtiments et les zones de dépression (aspiration) sont cartographiés pour concevoir des enveloppes architecturales sûres et confortables. Le confort des piétons en espace urbain (vitesses de vent locales amplifiées par les bâtiments hauts) est maintenant un critère de conception obligatoire dans certaines villes.</p>'
    '<div class="highlight-box"><p>La simulation CFD d\'une voiture de Formule 1 (200 millions de cellules, modélisation des 4 pneus en contact, des déflecteurs et du diffuseur) prend 24h sur un cluster de 1000 cœurs — et l\'équipe en fait des dizaines par semaine pour optimiser chaque détail aérodynamique.</p></div>'
),
'mecanique/dynamique-des-systemes': (
    '<h3>Identification et commande avancée</h3>'
    '<p class="resume-text">L\'<strong>identification de systèmes</strong> consiste à construire un modèle mathématique d\'un système dynamique à partir de données d\'entrée-sortie mesurées, sans connaissance a priori des équations physiques. Les méthodes des moindres carrés, du sous-espace (MOESP, N4SID) et les réseaux de neurones (NARX — Non-linear AutoRegressive with eXogenous inputs) permettent d\'identifier des modèles fiables pour des systèmes complexes difficiles à modéliser analytiquement. Ces modèles sont ensuite utilisés pour synthétiser des contrôleurs.</p>'
    '<p class="resume-text">La <strong>commande prédictive basée sur modèle</strong> (MPC — Model Predictive Control) optimise en ligne la trajectoire de commande future en résolvant un problème d\'optimisation contraint à chaque instant. Elle gère naturellement les contraintes physiques (limitations de débit, de tension, de couple), les couplages entre variables et les retards. Le MPC équipe les processus chimiques (raffineries, cimenteries), les véhicules autonomes (planification de trajectoire), les robots (anticipation des obstacles) et les bâtiments intelligents (optimisation énergétique).</p>'
    '<div class="highlight-box"><p>La commande prédictive (MPC) d\'une raffinerie Shell a réduit les coûts de production de 3% et augmenté le rendement de 2% — sur un site traitant 200 000 barils/jour, cela représente plusieurs millions d\'euros d\'économies annuelles.</p></div>'
),
'genie-civil/structures-porteuses': (
    '<h3>Structures textiles et tensostructures</h3>'
    '<p class="resume-text">Les <strong>tensostructures</strong> utilisent des membranes textiles (PTFE/fibre de verre, ETFE) tendues par des câbles ou gonflées par pression pour couvrir de grandes surfaces avec un minimum de matière. Les couvertures des stades olympiques (Munich 1972 : Frei Otto), des aéroports (Denver International Airport) et des centres commerciaux exploitent ces principes. La membrane d\'ETFE gonflable (coussin bi-couche) est transparente, légère (100 fois moins qu\'un vitrage équivalent), isolante thermiquement et auto-nettoyante.</p>'
    '<p class="resume-text">L\'<strong>ingénierie des façades</strong> conçoit des enveloppes de bâtiment qui intègrent performance thermique, acoustique, lumineuse et structurale. Les façades double-peau (cavity walls), les murs rideaux de verre stratifiés (structural glazing), les pare-soleils mobiles et les façades végétalisées transforment l\'enveloppe en élément actif de gestion de l\'énergie. Les façades photovoltaïques intégrées (BIPV) combinent protection climatique et production d\'énergie.</p>'
    '<div class="highlight-box"><p>Le Stade national de Pékin (Bird\'s Nest, JO 2008) utilise une structure en acier de 42 000 tonnes formant un nid entrelacé — conçu par Herzog & de Meuron et l\'ingénieur Arup, c\'est l\'une des structures les plus complexes jamais réalisées.</p></div>'
),
'genie-civil/beton-arme': (
    '<h3>Contrôle qualité et pathologies du béton</h3>'
    '<p class="resume-text">Le <strong>contrôle qualité du béton frais</strong> (slump test, essai d\'affaissement) mesure la maniabilité du béton avant mise en œuvre. Sur béton durci, les essais de carottage (prélèvement de cylindres pour essais de compression), de rebondissement (marteau Schmidt) et d\'impulsion ultrasonique évaluent la résistance et l\'homogénéité in situ. Le contrôle des enrobages (couverture de béton sur les armatures) est crucial : un enrobage insuffisant (moins de 25 mm en environnement courant) expose les armatures à la corrosion.</p>'
    '<p class="resume-text">Les <strong>pathologies du béton</strong> les plus courantes incluent la réaction alkali-silice (RAS, gonflement et fissuration de bétons contenant de la silice réactive), l\'attaque sulfatique (gonflement et délitement par les sulfates présents dans les eaux souterraines ou sols), l\'alcali-réaction et le délitement gel-dégel (cycles répétés d\'expansion de l\'eau lors de la congélation). Le diagnostic de ces pathologies (pétrographie, analyse chimique, mesures de déformation) conditionne le choix du traitement de réhabilitation.</p>'
    '<div class="highlight-box"><p>La réaction alkali-silice a fissuré plus de 200 ponts en France — une pathologie silencieuse pendant 10-20 ans avant de se manifester, qui nécessite des évaluations régulières pour prévenir l\'effondrement des ouvrages affectés.</p></div>'
),
'genie-civil/ponts': (
    '<h3>Ponts remarquables et records</h3>'
    '<p class="resume-text">Les <strong>records de portée</strong> des ponts illustrent les progrès de l\'ingénierie. Le pont suspendu Akashi-Kaikyo (Japon, 1998, 1991 m de portée centrale) détient le record mondial. Le pont à haubans Russky (Russie, 2012, 1104 m) dépasse le Millau (2004) pour les ponts routiers à haubans. Le viaduc de Millau (France, 2004), avec ses piliers atteignant 343 m de hauteur (plus haut que la Tour Eiffel), est le pont routier le plus haut du monde. Ces ouvrages témoignent de la synergie entre ingénierie des matériaux, calcul numérique et techniques de construction innovantes.</p>'
    '<p class="resume-text">Les <strong>ponts à histoire</strong> combinent exploit technique et symbole culturel. Le Golden Gate (San Francisco, 1937) reste l\'un des ponts les plus photographiés du monde. Le pont du Gard (Antiquité romaine, aqueduc à 3 niveaux de 49 m de haut) illustre la maîtrise constructive des Romains. Le Millau (2004, 2460 m de long) réconcilie performance et esthétique épurée, conçu avec l\'architecte Norman Foster pour s\'intégrer harmonieusement dans le paysage de l\'Aveyron.</p>'
    '<div class="highlight-box"><p>Le pont Akashi-Kaikyo (Japon) a été conçu pour résister au séisme du niveau 7 sur l\'échelle JMA et aux typhons à 286 km/h — lors du séisme de Kobe (1995) pendant sa construction, les fondations se sont écartées de 1 m sans dommage pour la structure.</p></div>'
),
'genie-civil/fondations': (
    '<h3>Géotechnique du changement climatique</h3>'
    '<p class="resume-text">Le <strong>changement climatique</strong> modifie les conditions géotechniques de nombreux sites. La montée du niveau des mers menace les fondations côtières et les berges des fleuves (érosion, salinisation des nappes phréatiques). Les sécheresses prolongées provoquent le <strong>retrait-gonflement des argiles</strong> (RGA) : le dessèchement des couches superficielles d\'argile entraîne leur retrait, causant des tassements différentiels qui fissurent les fondations superficielles des maisons individuelles. En France, le RGA a causé plus de 5 milliards d\'euros de dommages sur la décennie 2010-2020.</p>'
    '<p class="resume-text">Le <strong>dégel du pergélisol</strong> (permafrost) menace les fondations des infrastructures en régions arctiques et subarctiques. Le réchauffement climatique déstabilise les couches superficielles autrefois gelées en permanence, créant des affaissements (thermokarst), des glissements de terrain et une perte de portance des fondations. Les villes sibériennes, les pipelines arctiques et les routes de l\'Alaska subissent déjà des dommages significatifs. Les solutions incluent des fondations thermiquement isolées, la ventilation active des sous-sols et la migration des infrastructures vers des zones plus stables.</p>'
    '<div class="highlight-box"><p>En France, 10 millions de maisons sont exposées au retrait-gonflement des argiles — une menace géotechnique aggravée par les sécheresses répétées du changement climatique, qui provoque des fissures en façade et dans les fondations.</p></div>'
),
'genie-civil/construction-parasismique': (
    '<h3>Intelligence artificielle et monitoring sismique</h3>'
    '<p class="resume-text">L\'<strong>alerte précoce aux séismes</strong> (EEW — Earthquake Early Warning) détecte les ondes P (premières et moins destructrices) pour alerter la population quelques secondes avant l\'arrivée des ondes S et de surface (plus destructrices). Le Japon (J-ALERT), le Mexique et la Californie ont des systèmes EEW opérationnels. 10 à 30 secondes d\'avertissement suffisent pour ralentir les trains, ouvrir les portes des casernes de pompiers et alerter les usines chimiques. L\'IA améliore la discrimination séismes/explosions et réduit les fausses alarmes.</p>'
    '<p class="resume-text">Le <strong>monitoring post-sismique rapide</strong> utilise des capteurs MEMS sur les bâtiments (ShakeMap, DYFI — Did You Feel It?) pour cartographier les intensités ressenties et prioriser les inspections. Les algorithmes de machine learning analysent les données de monitoring structurel pour classer automatiquement les bâtiments en "à inspecter immédiatement", "à inspecter sous 72h" ou "sans dommage apparent". Cette triage automatique accélère considérablement la mobilisation des ressources d\'inspection après un séisme majeur.</p>'
    '<div class="highlight-box"><p>Le réseau d\'alerte sismique japonais J-ALERT a donné 60 secondes d\'avertissement à Tokyo avant les grandes ondes du séisme de Tohoku (2011) — permettant d\'arrêter les shinkansen et d\'ouvrir les portes de secours dans les immeubles avant l\'arrivée des secousses les plus violentes.</p></div>'
),
'electronique/signaux-numeriques': (
    '<h3>Intelligence artificielle et traitement du signal</h3>'
    '<p class="resume-text">Les <strong>réseaux de neurones récurrents</strong> (RNN, LSTM) et les transformeurs (Transformer) révolutionnent le traitement des séquences temporelles (signaux audio, vidéo, time series). Les systèmes de reconnaissance vocale (Google Speech, Apple Siri) convertissent la parole en texte avec une précision supérieure à l\'humain dans les conditions idéales. Les transformeurs (GPT, BERT, Whisper) traitent le signal audio sur plusieurs secondes de contexte simultanément, capturant les dépendances à longue portée impossible pour les LSTM.</p>'
    '<p class="resume-text">Le <strong>radar FMCW</strong> (Frequency-Modulated Continuous Wave) est omniprésent dans les systèmes embarqués modernes. Les radars 77 GHz des véhicules autonomes (Bosch, Continental, Texas Instruments) mesurent simultanément la distance (par décalage de fréquence), la vitesse (par effet Doppler) et l\'angle (par antennes multiples MIMO) des objets dans un rayon de 250 m. Le traitement numérique du signal (FFT 2D, CFAR, algorithmes de pistage) extrait les cibles du bruit de fond en temps réel.</p>'
    '<div class="highlight-box"><p>Les radars 77 GHz du système ADAS de voiture traitent 40 000 échos par seconde pour identifier les véhicules, piétons et obstacles à 250 m — fonctionnant par pluie, brouillard et nuit, là où les caméras sont aveugles.</p></div>'
),
'electronique/microprocesseurs': (
    '<h3>Architecture des calculateurs haute performance</h3>'
    '<p class="resume-text">Les <strong>supercalculateurs</strong> (HPC — High Performance Computing) combinent des milliers à des millions de processeurs reliés par des interconnexions ultra-rapides (InfiniBand HDR : 200 Gbit/s par lien, latence < 1 μs). Le supercalculateur Frontier (Oak Ridge, USA, 2022) est le premier à dépasser l\'exaflop (10¹⁸ flops) avec 37 376 GPU AMD MI250X. Ces machines simulent le climat, les collisions de particules, les réactions nucléaires et plient des protéines (AlphaFold2 de DeepMind a résolu 200 millions de structures protéiques).</p>'
    '<p class="resume-text">L\'<strong>informatique quantique</strong> exploite la superposition et l\'intrication des qubits pour résoudre certains problèmes exponentiellement plus vite que les ordinateurs classiques. IBM Quantum (433 qubits), Google Sycamore et IonQ développent des processeurs quantiques qui pourraient casser les cryptographies actuelles (RSA) et simuler des molécules complexes (découverte de médicaments, matériaux). La correction d\'erreur quantique (nécessitant des centaines de qubits physiques par qubit logique) reste le défi majeur avant les applications pratiques à grande échelle.</p>'
    '<div class="highlight-box"><p>Le supercalculateur Frontier (USA, 2022) dépasse l\'exaflop — soit 10¹⁸ opérations par seconde, l\'équivalent de chaque personne sur Terre effectuant 125 millions de calculs par seconde simultanément.</p></div>'
),
'electronique/composants-electroniques': (
    '<h3>Électronique de puissance et applications</h3>'
    '<p class="resume-text">L\'<strong>électronique de puissance</strong> convertit et contrôle l\'énergie électrique avec des composants de commutation (IGBT, SiC MOSFET, GaN HEMT) opérant à des fréquences croissantes (1 kHz à 1 MHz). Les véhicules électriques embarquent des convertisseurs DC-DC (12V/400V), des chargeurs embarqués (OBC — On-Board Charger) et des onduleurs de traction (400V DC → AC triphasé pour le moteur). Le SiC (carbure de silicium) remplace progressivement le silicium : 3 fois plus résistant en tension, 3 fois plus conducteur thermiquement, permettant des températures de jonction de 175°C contre 150°C pour le Si.</p>'
    '<p class="resume-text">Les <strong>semiconducteurs grand gap</strong> (WBG — Wide Bandgap : SiC et GaN) opèrent à des tensions, températures et fréquences impossibles pour le silicium. Le GaN sur Si (gallium nitride on silicon, 100-650V) domine les chargeurs rapides pour son efficacité à haute fréquence. Le SiC (Wolfspeed, STMicroelectronics, Rohm) remplace les IGBT dans les onduleurs de traction des voitures électriques (Tesla Model 3 : premier véhicule de série avec onduleur SiC). Ces technologies réduisent les pertes de conversion de 20 à 50%.</p>'
    '<div class="highlight-box"><p>Les semiconducteurs SiC des onduleurs de traction Tesla Model 3 réduisent les pertes de conversion de 30% par rapport au silicium conventionnel — améliorant l\'autonomie de 5 à 10% à puissance de batterie égale.</p></div>'
),
'electronique/circuits-analogiques': (
    '<h3>Conception de circuits RF modernes</h3>'
    '<p class="resume-text">Les <strong>circuits RF 5G</strong> (Sub-6 GHz et mmWave 24-40 GHz) posent des défis de conception inédits. La technologie mmWave (ondes millimétriques) nécessite des antennes réseau en phases (phased arrays) avec des centaines d\'éléments pour compenser les pertes de propagation élevées à ces fréquences et orienter électroniquement le faisceau (beamforming). Les MMIC (Monolithic Microwave Integrated Circuit) en GaN ou AsGa intègrent LNA, PA, déphaseurs et commutateurs dans des puces de quelques mm² capables d\'opérer à 40 GHz.</p>'
    '<p class="resume-text">Les <strong>résonateurs MEMS RF</strong> (micro-résonateurs électromécaniques à ultrasons) peuvent remplacer les filtres céramiques et à cristaux dans les circuits mobiles. Leur intégration sur puce (CMOS compatible) et leurs performances (facteur Q élevé, faible bande passante, petites dimensions) les rendent attrayants pour les filtres des bandes sub-6 GHz de la 5G. Les technologies FBAR (Film Bulk Acoustic Resonator) et SMR (Solidly Mounted Resonator) sont déjà commercialisées dans des filtres RF pour les smartphones haut de gamme.</p>'
    '<div class="highlight-box"><p>Un smartphone 5G haut de gamme contient plus de 100 filtres RF pour gérer simultanément 4G, 5G Sub-6 GHz, 5G mmWave, WiFi 6E, Bluetooth 5.3, GPS, NFC et UWB sans interférences mutuelles.</p></div>'
),
'electronique/systemes-embarques': (
    '<h3>Systèmes embarqués dans la mobilité du futur</h3>'
    '<p class="resume-text">Les <strong>calculateurs de conduite autonome</strong> (Orin de NVIDIA, EyeQ5 de Mobileye, ACAM d\'Aptiv) intègrent des NPU, GPU, CPU et DSP dans un SoC de 7 à 5 nm traitant jusqu\'à 254 TOPS. L\'architecture redondante (fail-operational) permet de continuer à conduire en mode dégradé si un calculateur tombe en panne. Les interfaces capteurs (caméra, radar, LiDAR) nécessitent des interfaces série à très haut débit (GMSL, FPD-Link, MIPI CSI-2) et une synchronisation temporelle précise entre tous les capteurs (PPS — Pulse Per Second, IEEE 1588).</p>'
    '<p class="resume-text">Les <strong>mises à jour OTA</strong> (Over-the-Air) transforment les véhicules en plateformes logicielles évolutives. Tesla a été pionnier en permettant d\'améliorer les performances de freinage, d\'ajouter de nouvelles fonctions et de corriger des bugs de sécurité sans intervention en atelier. Ces mises à jour nécessitent des architectures logicielles robustes (rollback automatique en cas d\'échec, double partition A/B, signature cryptographique), des liens de communication sécurisés et une validation rigoureuse avant déploiement sur des millions de véhicules.</p>'
    '<div class="highlight-box"><p>Tesla a mis à jour à distance la distance de freinage de 300 000 Model 3 et Model Y via une mise à jour OTA logicielle — évitant un rappel physique en atelier et démontrant la puissance des architectures logicielles automobiles modernes.</p></div>'
),
'materiaux/metaux-et-alliages': (
    '<h3>Superalliages et matériaux extrêmes</h3>'
    '<p class="resume-text">Les <strong>superalliages à base cobalt</strong> (Haynes 188, Stellite) résistent à l\'oxydation et maintiennent leur résistance jusqu\'à 1100°C. Ils équipent les tuyères de postcombustion des réacteurs militaires (températures supérieures à 1700°C avec refroidissement) et les chemises de fours industriels. Les <strong>aciers maraging</strong> (martensitiques vieillissants) atteignent 2000 MPa de résistance à rupture tout en restant soudables — utilisés dans les arbres de turbine, les roues dentées de F1 et les outils d\'injection plastique.</p>'
    '<p class="resume-text">Le <strong>magnésium</strong> (densité 1,74 g/cm³, le plus léger des métaux structuraux) offre une résistance spécifique comparable à l\'aluminium. Ses alliages (AZ31, AZ91, WE43) s\'imposent dans les boîtiers d\'ordinateurs portables, les volants de direction et les jantes automobiles. Sa faible rigidité (module 45 GPa) et sa relative fragilité (hexagonal compact) limitent ses applications structurales. Les traitements de surface (anodisation plasma électrolytique, peinture époxy) protègent les pièces magnésium de la corrosion galvanique.</p>'
    '<div class="highlight-box"><p>Les aubes de turbine en superalliage monocristallin (absence totale de joints de grains) opèrent à des températures supérieures à leur point de fusion apparent grâce au refroidissement interne par air — un paradoxe de l\'ingénierie thermique des matériaux.</p></div>'
),
'materiaux/polymeres': (
    '<h3>Polymères fonctionnels et intelligents</h3>'
    '<p class="resume-text">Les <strong>polymères conducteurs</strong> (polyaniline, polypyrrole, PEDOT:PSS) combinent les propriétés électroniques des métaux avec la mise en œuvre des plastiques. Ils sont utilisés dans les électrodes flexibles (écrans OLED, cellules solaires organiques), les capteurs électrochimiques (dosage du glucose), les actionneurs électroactifs et les revêtements antistatiques. Leur conductivité (100 S/cm) reste 100 fois inférieure au cuivre, mais leur légèreté et transparence optique les rendent irremplaçables dans certaines applications.</p>'
    '<p class="resume-text">Les <strong>hydrogels intelligents</strong> sont des réseaux polymères gonflés d\'eau qui répondent à des stimuli (pH, température, lumière, champ électrique) par un changement de volume réversible. Le PNIPAM (poly-N-isopropylacrylamide) se rétracte au-dessus de 32°C (proche de la température corporelle). Ces matériaux sont développés pour les lentilles de contact auto-humidifiantes, la libération contrôlée de médicaments, les robots souples actionnés thermiquement et les actuateurs biocompatibles pour la chirurgie mini-invasive.</p>'
    '<div class="highlight-box"><p>Les hydrogels de polyacrylamide sont utilisés dans les couches super-absorbantes (SAP — Super Absorbent Polymer) : 1 gramme peut absorber jusqu\'à 500 grammes d\'eau — une prouesse de chimie des polymères réticulés aux applications sanitaires planétaires.</p></div>'
),
'materiaux/ceramiques': (
    '<h3>Céramiques biomédicales</h3>'
    '<p class="resume-text">L\'<strong>hydroxyapatite</strong> (Ca₁₀(PO₄)₆(OH)₂) est le minéral constitutif de l\'os et des dents humains. Les céramiques d\'hydroxyapatite synthétiques (HA) et les phosphates tricalciques (TCP) sont utilisés comme substituts osseux et revêtements d\'implants métalliques. L\'HA favorise l\'adhésion et la prolifération des cellules osseuses (ostéoconduction), permettant une intégration biologique rapide. Les revêtements HA plasma-sprayés sur les prothèses de hanche en titane créent une interface os-métal solide sans ciment acrylique.</p>'
    '<p class="resume-text">Les <strong>bioverres</strong> (45S5 Bioglass® de Larry Hench, 1969) sont des verres silicatés bioactifs qui se lient chimiquement à l\'os par formation d\'une couche d\'hydroxyapatite carbonatée en milieu physiologique. Ils sont utilisés en chirurgie osseuse (comblement de défauts, régénération parodontale) et en chirurgie ORL (reconstruction de l\'oreille moyenne). Les bioverres résorbables se dissolvent progressivement au rythme de la régénération osseuse, libérant des ions silicium qui stimulent la formation d\'os nouveau.</p>'
    '<div class="highlight-box"><p>Le Bioglass 45S5 (inventé en 1969) a été implanté dans plus de 1 million de patients depuis sa mise sur le marché — le premier matériau synthétique à se lier chimiquement à l\'os, révolutionnant la chirurgie orthopédique et maxillo-faciale.</p></div>'
),
'materiaux/composites': (
    '<h3>Composites naturels et bio-composites</h3>'
    '<p class="resume-text">Les <strong>composites à fibres naturelles</strong> (lin, chanvre, bambou, sisal dans des matrices bio-sourcées ou époxy) suscitent un intérêt croissant pour les applications à moindre performance mécanique avec bilan carbone réduit. Les fibres de lin (rigidité 50-70 GPa, similaire au verre E) ont une empreinte carbone 5 fois inférieure aux fibres de verre. Des tableaux de bord automobiles, des panneaux intérieurs de trains et des éoliennes à petite échelle utilisent déjà des composites lin-époxy. La durabilité humide (absorption d\'eau des fibres végétales) reste la limitation principale.</p>'
    '<p class="resume-text">Les <strong>matériaux bio-inspirés</strong> imitent les structures naturelles hautement optimisées. La nacre (couches parallèles d\'aragonite liées par des protéines) est 3000 fois plus résistante que l\'aragonite seule grâce au chemin de fissure en labyrinthe. Les os (hiérarchie de nanocomposites collagène-hydroxyapatite sur 7 niveaux d\'organisation) combinent rigidité et résilience de façon incomparable. Ces structures inspirent des matériaux "tough" (céramiques renforcées par architecture nacre, composites à interfaces contrôlées) qui dépassent les compromis conventionnels des matériaux de construction.</p>'
    '<div class="highlight-box"><p>La nacre est 3000 fois plus résistante à la fissuration que l\'aragonite (calcium pur dont elle est faite) — grâce à son architecture en "briques et mortier" qui force la fissure à zigzaguer entre 1000 couches d\'aragonite avant de traverser la coque.</p></div>'
),
'materiaux/nanomateriaux': (
    '<h3>Perspectives et enjeux éthiques des nanotechnologies</h3>'
    '<p class="resume-text">Les <strong>nanotechnologies et la société</strong> soulèvent des questions éthiques et de gouvernance. La convergence NBIC (Nanotechnologies, Biotechnologies, Informatique, Sciences cognitives) ouvre des perspectives de renforcement humain (human enhancement) qui dépassent la thérapeutique : mémoires augmentées, interfaces cerveau-machine, nanomédicaments de longévité. Ces perspectives, encore spéculatives, alimentent des débats sur les inégalités d\'accès (enhancement réservé aux riches), la surveillance (nanoparticules traceuses) et la dignité humaine.</p>'
    '<p class="resume-text">La <strong>réglementation des nanotechnologies</strong> évolue rapidement en Europe. Le règlement REACH couvre les nanomatériaux depuis 2018 (définition officielle : matériau dont 50% des particules ont une dimension inférieure à 100 nm). Les fabricants doivent déclarer les nanomatériaux et soumettre une évaluation de risques. Le règlement cosmétique (CE 1223/2009) impose une notification spécifique des nanoingredients. La réglementation des nanomédicaments (nanoparticules thérapeutiques) relève de l\'EMA et des autorités de santé nationales, avec des exigences d\'essais cliniques spécifiques.</p>'
    '<div class="highlight-box"><p>Plus de 1800 produits de consommation contiennent des nanomatériaux déclarés — des crèmes solaires (TiO₂ nano) aux peintures antimicrobiennes (Ag nano) en passant par les textiles autonettoyants et les emballages alimentaires antibactériens.</p></div>'
),
'robotique/capteurs-et-perception': (
    '<h3>Perception tactile et haptique</h3>'
    '<p class="resume-text">La <strong>peau électronique</strong> (e-skin) intègre des centaines de capteurs de pression, température et vibration sur une surface flexible, imitant les récepteurs cutanés humains. Les technologies incluent les réseaux de transistors organiques en couche mince sur polyimide, les nanocomposites piézo-résistifs (graphène, nanotubes de carbone dans PDMS) et les capteurs capacitifs en grille. La peau électronique est développée pour les robots collaboratifs (détection de contacts sur toute la surface), les prothèses sensorielles (retour sensoriel au porteur) et les vêtements de santé connectés.</p>'
    '<p class="resume-text">Les <strong>gants haptiques</strong> et les interfaces force-retour permettent à l\'opérateur d\'un robot à distance de "sentir" ce que le robot manipule. Le gant CyberGrasp (Immersion Corporation) applique des forces sur chaque doigt pour simuler la résistance d\'objets virtuels. Dans la télé-chirurgie (robot da Vinci), le retour de force informerait le chirurgien de la résistance des tissus sans avoir à observer directement. Le retard de communication (latence > 150 ms pour les distances intercontinentales) limite actuellement la télé-chirurgie à distance.</p>'
    '<div class="highlight-box"><p>Les capteurs tactiles barométriques GelSight (MIT Media Lab) révèlent la microgeométrie de surface d\'un objet saisi avec une résolution de 5 μm — permettant à un robot de distinguer la texture d\'un tissu ou la rugosité d\'une surface métallique au toucher.</p></div>'
),
'robotique/actionneurs-et-commande': (
    '<h3>Moteurs et actionneurs pour les véhicules électriques</h3>'
    '<p class="resume-text">Les <strong>moteurs de traction des véhicules électriques</strong> (IPM — Interior Permanent Magnet motor) sont des moteurs synchrones à aimants permanents NdFeB intégrés dans le rotor. La position des aimants (enfouis ou surfaciques) influence le profil de couple et la plage de fonctionnement à puissance constante (field weakening). Tesla utilise des moteurs IPM à bobinage hairpin (barres de cuivre en forme de U) qui améliorent le facteur de remplissage de 50 à 70% et la conductivité thermique par rapport aux bobinages filaires conventionnels.</p>'
    '<p class="resume-text">Le <strong>contrôle vectoriel</strong> (Field Oriented Control — FOC) décompose les courants du moteur AC en composantes indépendantes : une composante de flux (magnetizing) et une composante de couple (torque generating). En contrôlant ces deux composantes indépendamment dans le référentiel tournant du rotor, on obtient un contrôle de couple aussi réactif que pour un moteur DC, avec la robustesse et la puissance du moteur AC. Le FOC est implémenté dans tous les variateurs modernes (Industrie 4.0, VE, drones).</p>'
    '<div class="highlight-box"><p>Le moteur de traction du Tesla Model S Plaid atteint 1020 ch (754 kW) avec un rendement de 94% — contre 30-40% pour un moteur thermique équivalent. Ses 3 moteurs IPM atteignent 20 000 tr/min grâce à un bobinage carbone-fibre ultra-résistant.</p></div>'
),
'robotique/ia-embarquee': (
    '<h3>Robotique et apprentissage continu</h3>'
    '<p class="resume-text">L\'<strong>apprentissage continu</strong> (continual learning) permet aux robots de s\'adapter à de nouveaux environnements et tâches sans oublier les précédentes (catastrophic forgetting). Les algorithmes de Elastic Weight Consolidation (EWC), Progressive Neural Networks et Memory Replay protègent les connaissances acquises tout en permettant l\'acquisition de nouveaux comportements. Cette capacité est fondamentale pour des robots déployés dans des environnements changeants sur de longues durées (service à domicile, inspection industrielle).</p>'
    '<p class="resume-text">La <strong>robotique en nuage</strong> (cloud robotics) déleste les calculs intensifs (traitement du langage, reconnaissance d\'objets à large vocabulaire, planification complexe) vers des serveurs distants, permettant à des robots légers et économiques d\'accéder à des capacités de traitement quasi-illimitées. Le défi est la latence (100-500 ms pour un aller-retour réseau) qui limite les tâches de contrôle temps-réel. Les architectures hybrides (traitement temps-réel embarqué + traitement lent en nuage) combinent les avantages des deux approches.</p>'
    '<div class="highlight-box"><p>Le système de conduite autonome Waymo One traite 1 mégaoctet de données capteurs par seconde localement, complété par des cartes haute définition mises à jour depuis le cloud — une architecture hybride embarqué-nuage qui combine réactivité locale et intelligence globale.</p></div>'
),
'robotique/robots-industriels': (
    '<h3>Métrologie robotique et contrôle qualité automatisé</h3>'
    '<p class="resume-text">La <strong>métrologie robotisée</strong> utilise des bras robotiques portant des capteurs de mesure (têtes de mesure Renishaw, scanners 3D par lumière structurée) pour inspecter automatiquement des pièces usinées. Un robot 6 axes avec une tête de mesure par palpation peut mesurer des centaines de points en quelques minutes avec une précision de ±5 μm. Pour les grandes pièces (carrosseries automobiles, fuselages aéronautiques), des laser trackers et des photogrammétrie fixent les pièces avec une précision de ±50 μm dans un volume de plusieurs mètres.</p>'
    '<p class="resume-text">Le <strong>contrôle non destructif robotisé</strong> (NDT automatisé) utilise des robots pour déplacer les capteurs ultrasoniques, radiographiques (X ou neutrons) ou de courants de Foucault sur des pièces complexes. Airbus inspecte automatiquement les panneaux de fuselage composite avec des robots à ultrasons phased array. Les algorithmes de traitement du signal (DAS — Delay and Sum, TFM — Total Focusing Method) génèrent des images volumiques 3D des défauts internes en temps réel.</p>'
    '<div class="highlight-box"><p>Les robots d\'inspection ultrasonique automatisée d\'Airbus inspectent un panneau de fuselage composite de 4m² en 20 minutes — une tâche qui prendrait plusieurs heures à des techniciens qualifiés avec les mêmes performances de détection.</p></div>'
),
'robotique/drones': (
    '<h3>Éthique et enjeux sociaux des drones</h3>'
    '<p class="resume-text">La <strong>vie privée et la surveillance</strong> sont les enjeux éthiques centraux de la démocratisation des drones. Un drone commercial avec une caméra 4K à 30x zoom peut filmer des fenêtres à 300 m de distance. La réglementation européenne (Open UAS) interdit le survol des personnes sans consentement et des zones résidentielles en catégorie A3 (moins de 4 kg). Les systèmes de détection anti-drones (geofencing, C-UAS — Counter-UAS, intercepteurs RF) se développent pour protéger les espaces sensibles (aéroports, prisons, stades, centrales nucléaires).</p>'
    '<p class="resume-text">L\'<strong>usage militaire des drones</strong> pose des questions éthiques sur la létalité autonome. Les LAWS (Lethal Autonomous Weapons Systems) — drones capables de sélectionner et d\'engager des cibles sans intervention humaine — font l\'objet de débats à l\'ONU. Le Comité International de la Croix-Rouge et de nombreux pays appellent à une réglementation internationale. Le conflit ukrainien a démontré l\'efficacité déstabilisante des drones commerciaux modifiés, mais aussi les risques de prolifération et d\'utilisation par des acteurs non-étatiques.</p>'
    '<div class="highlight-box"><p>Les drones autonomes létaux (LAWS) sont au cœur d\'un débat international — le CICR et 30 pays appellent à un traité d\'interdiction des armes létales autonomes, tandis que d\'autres grandes puissances refusent tout encadrement contraignant.</p></div>'
),
}

count = 0
for key, extra in boosters.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            status = "OK" if new_len >= 15000 else "still under"
            print(f"{key}: {old_len} -> {new_len} ({status})")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (third pass boosters)")
