#!/usr/bin/env python3
"""Final pass: add targeted paragraphs to each page still under 15000 chars."""
import json

PATH = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/neurosciences.json"

with open(PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def inject(key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

extras = {
'conscience/conscience-de-soi': """
<h3>Les troubles de la conscience de soi en psychiatrie</h3>
<p class="resume-text">La <strong>dépersonnalisation</strong> (sentiment d'être étranger à soi-même, comme un observateur de sa propre vie) et la <strong>déréalisation</strong> (sentiment que le monde extérieur est irréel) sont des phénomènes transitoires fréquents (jusqu'à 70 % de la population générale lors d'états de stress intense) et des syndromes psychiatriques chroniques (trouble dissociatif dépersonnalisation-déréalisation). Neurobiologiquement, la dépersonnalisation implique une hyperactivation du cortex préfrontal modulant à la baisse l'activité limbique, produisant un défaut de résonance émotionnelle avec l'expérience corporelle et interpersonnelle. Une inhibition transcranienne du cortex préfrontal droit (TMS) peut réduire temporairement les symptômes.</p>
<p class="resume-text">La schizophrénie altère profondément la conscience de soi : les patients peuvent ne pas reconnaître leurs propres pensées (pensée imposée) ou actions (sentiment de non-agentivité) comme leur appartenant. Ces symptômes du premier rang de Schneider correspondent à des anomalies dans le sentiment d'agentivité, probablement liées à une défaillance du signal de copie d'efférence (efference copy) qui normalement prédit les conséquences sensorielles de nos propres actions et les distingue des actions externes.</p>
""",
'neuro-imagerie/eeg': """
<h3>Le neurofeedback EEG et ses applications cliniques</h3>
<p class="resume-text">Le neurofeedback entraîne les sujets à modifier volontairement leur activité EEG en leur fournissant un retour en temps réel. Le protocole SMR (sensorimotor rhythm, 12-15 Hz) est utilisé dans le traitement du TDAH : en renforçant le rythme SMR et en supprimant les thêta frontaux (marqueurs d'inattention), les patients améliorent leurs performances attentionnelles sans médication. Des méta-analyses montrent une taille d'effet modérée à robuste pour les symptômes d'inattention, bien que la question du contrôle placebo reste débattue. Le protocole alpha-thêta, développé pour les sportifs de haut niveau et les musiciens, vise à induire un état de relaxation alerte optimal.</p>
<p class="resume-text">Des avancées récentes explorent le neurofeedback basé sur des biomarqueurs plus fins. Le neurofeedback des oscillations gamma dans les régions frontales est testé pour la schizophrénie — ciblant le déficit de synchronisation gamma (liée aux interneurones PV+ déficients). Le neurofeedback du nœud postérieur du DMN (cortex cingulaire postérieur) est exploré pour la dépression, visant à réduire la rumination et l'auto-référence excessive. Ces approches restent expérimentales mais représentent une voie vers des interventions neurobiologiquement ciblées sans effets secondaires pharmacologiques.</p>
""",
'neuro-imagerie/magnetoencephalographie': """
<h3>La MEG et l'étude du langage en temps réel</h3>
<p class="resume-text">La MEG est particulièrement précieuse pour l'étude du traitement langagier grâce à sa haute résolution temporelle. Le suivi continu de l'activité cérébrale lors de la lecture révèle une cascade précise : traitement visuel initial en 100 ms, reconnaissance des mots écrits dans la « boîte aux lettres » fusiforme en 150 ms, activation sémantique dans le gyrus temporal médial en 200 ms, intégration syntaxique préfrontale en 300-400 ms. Cette chronométrie fine, impossible à obtenir avec l'IRMf seule, révèle que la compréhension du langage est un processus dynamique en cascade et non un traitement séquentiel en étapes discrètes.</p>
<p class="resume-text">La décodage du langage imaginé (inner speech) par MEG est une frontière active de la recherche BCI. Des patients atteints de SLA (sclérose latérale amyotrophique), incapables de parler ou de bouger, peuvent générer des patterns MEG distincts pour différentes phonèmes imaginés. Des décodeurs entraînés sur ces patterns permettent une communication limitée mais réelle. La combinaison MEG haute densité, IA de décodage et apprentissage continu vise à terme un système de communication à débit conversationnel pour les patients locked-in.</p>
""",
'neuro-imagerie/tep': """
<h3>La TEP et la recherche sur les maladies neurodégénératives</h3>
<p class="resume-text">La TEP joue un rôle central dans la compréhension et le suivi des maladies neurodégénératives. Dans la maladie de Parkinson, les traceurs dopaminergiques (DAT-SPECT, [18F]-DOPA TEP) révèlent la perte précoce de terminaisons striatales des neurones de la substantia nigra, permettant un diagnostic différentiel fiable avec les syndromes parkinsoniens non dopaminergiques (PSP, MSA) qui ont un pronostic et un traitement différents. Dans la chorée de Huntington, la perte des neurones striataux GABA-ergiques est visible au FDG-TEP comme un hypométabolisme striataux sévère des années avant les symptômes.</p>
<p class="resume-text">La TEP à l'alpha-synucléine, protéine agrégée dans les corps de Lewy (Parkinson, démence à corps de Lewy), est en développement clinique actif — plusieurs traceurs sont en phase 2-3 d'essais. Son approbation permettrait de différencier les synuclénopathies des tauopathies in vivo, une distinction cruciale pour les essais cliniques d'immunothérapies ciblant ces protéines spécifiques. La médecine moléculaire des maladies neurodégénératives converge vers un paradigme de diagnostic précoce par TEP, de stratification thérapeutique et de suivi de réponse au traitement.</p>
""",
'neuro-imagerie/irm-fonctionnelle': """
<h3>L'IRMf à ultra-haute résolution et le mésocircuit cortical</h3>
<p class="resume-text">Les IRM à 7 Tesla, maintenant en usage clinique dans certains centres, offrent une résolution spatiale de 0,5-0,7 mm³, permettant de distinguer des couches corticales individuelles et des colonnes corticales chez l'humain in vivo. Ces études mésoscopiques révèlent les patterns laminaires de l'activation corticale : une activation préférentielle de la couche IV indique une entrée thalamique (information bottom-up) ; une activation des couches superficielles I-III indique une influence top-down cortico-corticale. Ces distinctions lamaires, invisibles aux IRM conventionnelles, permettent de tester directement les prédictions des modèles computationnels de codage prédictif in vivo.</p>
<p class="resume-text">L'IRMf à champ ultra-fort s'accompagne de défis techniques majeurs : inhomogénéités du champ magnétique amplifiées, dépôt de puissance radiofréquence accru, artefacts de susceptibilité magnétique plus importants. Des techniques de correction spécialisées (shimming dynamique, acquisition multi-bandes, correction de distorsion) sont nécessaires pour exploiter le gain en signal et en résolution. Le développement de bobines de surface à 7T et d'algorithmes de reconstruction d'images avancés est un domaine de recherche très actif, avec des applications cliniques croissantes en épilepsie, tumeurs cérébrales et maladies neurodégénératives.</p>
""",
'neuroanatomie/cortex-cerebral': """
<h3>Le cortex préfrontal et les fonctions exécutives</h3>
<p class="resume-text">Le cortex préfrontal (CPF), qui représente 29 % de la surface corticale chez l'humain (versus 17 % chez le chimpanzé et 7 % chez le chat), est le siège des fonctions exécutives : planification, flexibilité cognitive, inhibition des réponses automatiques, mémoire de travail. Le CPF dorsolatéral (CPFdl) maintient et manipule les représentations en mémoire de travail via des oscillations gamma et des activations toniques. Le CPF ventromédial (CPFvm) intègre valeur émotionnelle et décision. Le CPF orbitofrontal (OFC) code la valeur subjective des options et la flexibilité des préférences. Le CPF antérieur (frontopolaire, aire 10 de Brodmann) sous-tend les intentions prospectives et le multitasking.</p>
<p class="resume-text">L'immaturité prolongée du CPF est une caractéristique évolutive humaine remarquable : la myélinisation complète des faisceaux de matière blanche préfrontaux n'est pas achevée avant l'âge de 25 ans. Cette myélinisation tardive corrèle avec le développement lent des capacités d'autocontrôle, de prise de perspective et de planification à long terme. Elle constitue une fenêtre de plasticité étendue — les expériences et environnements de l'adolescence façonnent durablement l'architecture fonctionnelle du CPF adulte, avec des implications majeures pour les politiques éducatives et de santé publique.</p>
""",
'neuroanatomie/tronc-cerebral': """
<h3>Les réflexes du tronc cérébral et leur valeur diagnostique</h3>
<p class="resume-text">Les réflexes du tronc cérébral — dont l'intégrité est testée au chevet du patient — permettent de localiser les lésions et d'évaluer l'état de conscience. Le <strong>réflexe pupillaire à la lumière</strong> (nerf optique II → mésencéphale → oculomoteur III → sphincter pupillaire) évalue l'intégrité mésencéphalique. Le <strong>réflexe cornéen</strong> (V → pont → VII → orbiculaire de l'œil) évalue l'intégrité pontique. Le <strong>réflexe oculo-céphalique</strong> (vestibulaire → pont → VI et III) évalue la connexion vestibulo-oculomotrice. L'<strong>absence de réflexes du tronc cérébral</strong>, associée au coma et à l'apnée, constitue le critère neurologique de la mort cérébrale dans la plupart des législations.</p>
<p class="resume-text">Le <strong>locked-in syndrome</strong>, causé par une lésion du pont ventral (infarctus basilaire, sclérose latérale amyotrophique avancée), illustre la distinction cruciale entre conscience et comportement moteur. Le patient est totalement paralysé (quadriplégie, anarthrie) mais pleinement conscient, avec seulement les mouvements oculaires verticaux et les clignements préservés. Ces patients peuvent communiquer via des BCI oculomoteurs ou EEG/MEG. Jean-Dominique Bauby, atteint de locked-in syndrome en 1995, a dicté son autobiographie « Le Scaphandre et le Papillon » en clignant de l'œil gauche — lettre par lettre, avec une patience transcendante.</p>
""",
'computationnelle/reseaux-neuronaux': """
<h3>La robustesse et la redondance dans les réseaux biologiques</h3>
<p class="resume-text">Les réseaux neuronaux biologiques font preuve d'une robustesse remarquable face aux perturbations. Détruire aléatoirement 50 % des neurones d'un réseau biologique n'effondre pas ses fonctions — grâce à la redondance massive et aux mécanismes de compensation homéostatique. Cette robustesse est liée à l'architecture petit-monde et scale-free : les hubs sont vulnérables aux attaques ciblées, mais la majorité des nœuds périphériques peuvent être perdus sans désintégration globale. La maladie d'Alzheimer suit d'ailleurs ce pattern : elle attaque d'abord les hubs du DMN (cortex entorhinal, hippocampe, cingulaire postérieur), provoquant un effondrement disproportionné des fonctions mnésiques et exécutives.</p>
<p class="resume-text">L'<strong>homéostasie synaptique</strong> est un mécanisme régulateur global qui compense la dérive des poids synaptiques : si toutes les synapses sont potentiées sans limite, le réseau saturerait en hyperactivité. La théorie de l'homéostasie synaptique de Tononi et Cirelli propose que le sommeil sert notamment à normaliser vers le bas (downscale) l'ensemble des poids synaptiques potentiés pendant l'éveil, restaurant l'efficacité du signal et économisant l'énergie. Des preuves convergentes d'électrophysiologie, de microscopie électronique et de modélisation soutiennent cette théorie unifiée du sommeil et de la plasticité.</p>
""",
'conscience/etats-modifies': """
<h3>Les drogues dissociatives et l'altération de l'intégration consciente</h3>
<p class="resume-text">La kétamine et la phéncyclidine (PCP), antagonistes des récepteurs NMDA, produisent un état dissociatif caractéristique : analgésie, amnésie, sentiment de flotter hors de son corps, hallucinations visuelles, distorsion du temps. Ces effets résultent du blocage des récepteurs NMDA dans les interneurones GABAergiques inhibiteurs, levant l'inhibition et produisant une désinhibition paradoxale de l'activité glutamatergique corticale. L'EEG montre une augmentation des oscillations gamma frontales et une désorganisation de la cohérence inter-régionale. Ces perturbations s'approchent de celles observées dans la schizophrénie, faisant de la kétamine un modèle pharmacologique de psychose utile pour la recherche.</p>
<p class="resume-text">Les <strong>expériences de mort imminente</strong> (EMI), rapportées par 10-20 % des personnes réanimées d'un arrêt cardiaque, comportent des éléments récurrents : tunnel de lumière, reviviscence de l'existence entière, sentiment de paix, sortie du corps. Des enregistrements EEG per-cardiac arrest ont montré une activation gamma intense dans les premières secondes suivant l'arrêt cardiaque, avant que l'activité corticale ne s'effondre. Jimo Borjigin a proposé que cette « tempête cérébrale » terminale pourrait être le substrat neurologique de certaines EMI — une hypothèse fascinante mais dont la relation causale avec les rapports subjectifs reste à démontrer rigoureusement.</p>
""",
'conscience/theories-conscience': """
<h3>Les prédictions testables et la neuro-phénoménologie</h3>
<p class="resume-text">Un défi majeur pour toute théorie de la conscience est de générer des prédictions expérimentalement falsifiables qui distinguent les théories concurrentes. Le projet Templeton-funded « Adversarial Collaboration » entre champions de l'IIT et de la GNWT, mené de 2019 à 2023, est exemplaire : des prédictions ont été pré-enregistrées, les expériences menées par des laboratoires neutres, et les résultats rendus publics même si inconfortables pour les deux camps. Cette démarche scientifique rigoureuse, rare dans un domaine aussi complexe, a produit des données nuancées qui enrichissent les deux théories plutôt que d'en invalider une définitivement.</p>
<p class="resume-text">La <strong>neuro-phénoménologie</strong>, proposée par Francisco Varela, cherche à mettre en dialogue systématique les descriptions phénoménologiques de première personne (rapports subjectifs détaillés selon la méthode husserlienne) avec les données neuroscientifiques de troisième personne. Des méditants experts entraînés à l'introspection fine fournissent des descriptions de haute précision de leurs états conscients, permettant de les corréler avec des signatures EEG ou MEG spécifiques. Cette approche exigeante sur le plan méthodologique pourrait ouvrir la voie à une science de la conscience qui prend au sérieux la subjectivité irréductible de l'expérience sans la réduire à des données objectives.</p>
""",
'conscience/libre-arbitre': """
<h3>La volonté, l'intention et le sentiment d'agentivité</h3>
<p class="resume-text">L'<strong>agentivité</strong> — le sentiment d'être l'auteur de ses propres actions — est une expérience subjective construite activement par le cerveau, pas un reflet direct de la causalité réelle. Des études de Patrick Haggard montrent que l'intervalle temporel subjectif entre une action volontaire et son effet sonore est compressé par rapport à l'intervalle objectif — le cerveau lie causalement les deux événements en les rapprochant subjectivement. Cette « liaison intentionnelle » est absente pour les mouvements passifs, suggérant qu'elle reflète spécifiquement le sentiment d'agentivité motrice.</p>
<p class="resume-text">La stimulation cérébrale profonde du noyau sous-thalamique chez des patients parkinsoniens peut, dans de rares cas, provoquer des comportements stéréotypés (rires compulsifs, comportements semi-automatiques) que les patients reconnaissent comme non voulus mais qu'ils peuvent parfois commencer à « s'approprier » rétrospectivement comme intentionnels. Ces dissociations entre comportement, sentiment d'agentivité et attribution causale rétrospective illustrent que la volonté consciente est une narration construite post-hoc par les systèmes préfrontaux sur une action qui a déjà commencé à s'organiser dans les circuits moteurs et sous-corticaux.</p>
""",
'conscience/sommeil-reves': """
<h3>Les parasomnies et les frontières entre sommeil et éveil</h3>
<p class="resume-text">Les <strong>parasomnies</strong> illustrent la fluidité des états de conscience. Le somnambulisme, l'éveil confusionnel et les terreurs nocturnes surviennent en éveillant partiellement un cerveau en sommeil lent profond : les systèmes moteur et végétatif sont activés (le patient marche, parle, peut se blesser) pendant que le cortex associatif reste en sommeil profond (aucune mémoire de l'épisode). L'<strong>arrêt du sommeil REM</strong> (REM sleep behavior disorder) inverses ce pattern : les patients « jouent » physiquement leurs rêves en raison d'un défaut d'atonie musculaire — un marqueur précoce de synucléinopathie (Parkinson, démence à corps de Lewy) qui précède les symptômes de 10-15 ans.</p>
<p class="resume-text">La <strong>paralysie du sommeil</strong>, présente dans 20-40 % de la population au moins une fois, survient lors de transitions entre sommeil REM et éveil : le cerveau s'éveille mais l'atonie REM persiste. Le sujet est conscient mais incapable de bouger, souvent accompagné d'hallucinations hypnagogiques réalistes (présence d'une entité malveillante, pression sur la poitrine). Ce phénomène purement neurobiologique — désynchro nisation de la récupération motrice et de l'éveil cortical — explique des expériences culturellement interprétées comme « visites de démons nocturnes » (succubes, incubes, vieux de la nuit) dans toutes les cultures à travers l'histoire.</p>
""",
'neuroanatomie/systeme-limbique': """
<h3>L'axe HPA et le stress chronique</h3>
<p class="resume-text">L'axe hypothalamo-hypophyso-surrénalien (HPA) est le principal système de réponse au stress. Face à une menace, l'hypothalamus libère la CRH (corticotropin-releasing hormone), qui stimule l'hypophyse à libérer l'ACTH, qui stimule les glandes surrénales à libérer le cortisol. Le cortisol mobilise les réserves énergétiques, supprime la réponse immunitaire non urgente et potentialise la mémoire émotionnelle via l'amygdale. Ce système est normalement régulé par une rétroaction négative : le cortisol inhibe l'hypothalamus et l'hypophyse pour limiter sa propre libération.</p>
<p class="resume-text">Le stress chronique désensibilise cette rétroaction négative, produisant une hypercortisolémie persistante qui est <strong>neurotoxique</strong> pour l'hippocampe. Les récepteurs aux glucocorticoïdes (GR) abondants dans les neurones hippocampiques, lorsque sur-stimulés chroniquement, inhibent la neurogénèse et réduisent la densité des épines dendritiques. Le volume hippocampique est réduit de 10-15 % chez les patients dépressifs chroniques, les anciens combattants avec TSPT, et les sujets ayant subi des maltraitances dans l'enfance — une atrophie partiellement réversible par les antidépresseurs et l'exercice physique, qui stimulent le BDNF et restaurent la neurogénèse.</p>
""",
'neuroanatomie/cervelet': """
<h3>Le cervelet et les maladies génétiques : ataxies spinocérébelleuses</h3>
<p class="resume-text">Les <strong>ataxies spinocérébelleuses</strong> (SCA) sont un groupe de maladies neurodégénératives à transmission autosomique dominante, causant une atteinte progressive du cervelet et du tronc cérébral. La SCA1, 2, 3 (maladie de Machado-Joseph) et 6 sont causées par des expansions de triplets CAG dans des gènes codant des protéines contenant des répétitions polyglutamine. Ces expansions créent des protéines anormalement longues qui s'agrègent dans les noyaux des cellules de Purkinje, perturbant la transcription et causant leur mort progressive.</p>
<p class="resume-text">La SCA3 est la forme la plus fréquente d'ataxie spinocérébelleuse dans le monde. Elle débute vers 30-40 ans par un trouble de la marche progressif, une ataxie des membres, et évolue vers une dysarthrie et une dysphagie. Aucun traitement neuroprotecteur n'est disponible, mais des essais d'ARN antisens (ASO) ciblant spécifiquement l'ARNm du gène muté ATXN3 sont en cours de développement préclinique, avec l'espoir de ralentir ou stopper la neurodégénérescence en réduisant l'expression de la protéine pathologique. Ces approches de médecine génique ciblée représentent l'espoir thérapeutique pour les ataxies héréditaires.</p>
""",
'neuroanatomie/moelle-epiniere': """
<h3>La plasticité médullaire et la régénération nerveuse</h3>
<p class="resume-text">Le système nerveux central adulte se régénère peu après une lésion, contrairement au système nerveux périphérique. Plusieurs obstacles moléculaires expliquent cette différence : les détritus myéliniques (MAG, Nogo-A, OMgp) inhibent la croissance axonale via les récepteurs NgR et PIR-B sur les neurones lésés. Le tissu cicatriciel (gliose réactive) forme une barrière physique et chimique. L'absence de facteurs de croissance suffisants dans l'environnement de la lésion limite la réponse régénérative intrinsèque, bien que les neurones du SNC en aient la capacité si ces obstacles sont levés.</p>
<p class="resume-text">Des stratégies de régénération nerveuse sont en développement actif. L'anticorps anti-Nogo-A (ATI355, Novartis) a montré des bénéfices moteurs dans les lésions médullaires cervicales incomplètes en phase 2. Les cellules souches neurales transplantées dans la zone lésée peuvent différencier en oligodendrocytes remyélinisants et en interneurones créant des ponts synaptiques. La combinaison de stimulation épidurale, de cellules souches et de rééducation intensive représente l'approche combinatoire la plus prometteuse, avec des essais cliniques de phase 2-3 en cours dans plusieurs centres mondiaux spécialisés.</p>
""",
'neurochimie/dopamine': """
<h3>La dopamine dans la schizophrénie et au-delà</h3>
<p class="resume-text">L'hypothèse dopaminergique de la schizophrénie, formulée dans les années 1960 après la découverte que les antipsychotiques bloquent les récepteurs D2, reste le cadre dominant mais a évolué. La version moderne distingue une <strong>hyperdopaminergie sous-corticale</strong> striatale (associée aux symptômes positifs, hallucinations et délires) d'une <strong>hypodopaminergie préfrontale</strong> (associée aux symptômes négatifs et cognitifs). La TEP montre une augmentation de la synthèse de dopamine striatale et une libération exagérée lors de stimulations amines chez les patients schizophrènes et leurs proches non malades, suggérant une vulnérabilité dopaminergique héréditaire.</p>
<p class="resume-text">Au-delà de la psychose, la dérégulation dopaminergique est impliquée dans la bipolarité, le TDAH (hypofonctionnement préfrontal), la dépression (hypofonctionnement mésolimbique), les troubles du comportement alimentaire (dysrégulation dopaminergique dans les réponses hédoniques à la nourriture) et les jeux pathologiques. Le récepteur D3, concentré dans le système limbique, est une cible thérapeutique émergente — des antagonistes D3 sélectifs sont en développement pour réduire la rechute dans les addictions sans les effets extrapyramidaux liés au blocage D2 striataux.</p>
""",
'neurochimie/serotonine': """
<h3>La psychédéliques et la thérapeutique assistée</h3>
<p class="resume-text">La renaissance de la recherche sur les psychédéliques classiques (LSD, psilocybine, mescaline, DMT), interrompue dans les années 1970 après leur prohibition, produit des résultats cliniques remarquables. Des essais randomisés de <strong>thérapie assistée par psilocybine</strong> pour la dépression résistante (Imperial College, Johns Hopkins, NYU) montrent des rémissions durables chez 50-70 % des patients après seulement 1-2 sessions supervisées — une efficacité sans équivalent dans la psychiatrie actuelle. Ces effets semblent liés à une réduction de l'activité du DMN (dissolution de l'ego), une augmentation de la flexibilité cognitive et des aperçus mystiques rapportés par les patients comme parmi les expériences les plus significatives de leur vie.</p>
<p class="resume-text">Les mécanismes moléculaires au-delà de l'agonisme 5-HT2A incluent des effets sur la plasticité synaptique : la psilocybine augmente la densité des épines dendritiques dans le cortex préfrontal de souris dans les 24h suivant l'administration, et cet effet persiste un mois. Ce « plastogène » sérotoninergique ouvre une fenêtre de plasticité qui, combinée à la psychothérapie, permettrait de « dégeler » des patterns cognitifs rigides associés à la dépression, l'addiction et les TOC. La FDA a accordé le statut de « Breakthrough Therapy » à la psilocybine pour la dépression résistante et la thérapie assistée par MDMA pour le TSPT — accélérant leur développement clinique.</p>
""",
'neurochimie/synapses': """
<h3>La transmission synaptique à travers le développement</h3>
<p class="resume-text">Durant le développement prénatal, le GABA est paradoxalement excitateur (dépolarisant) plutôt qu'inhibiteur. Ce renversement, qui se produit autour de la naissance, est dû au changement d'expression des cotransporteurs de chlorure : chez le fœtus, le NKCC1 concentre le chlorure à l'intérieur de la cellule, si bien que l'ouverture des canaux GABA-A permet la sortie de chlorure et dépolarise la cellule ; après la naissance, le KCC2 extrait le chlorure, inversant le gradient et rendant le GABA inhibiteur. Cette période de GABA excitateur est cruciale pour le développement des circuits : elle génère des vagues d'activité spontanées qui guident la synaptogenèse et le raffinement des connexions.</p>
<p class="resume-text">La <strong>synaptogenèse postnatale</strong> atteint son pic entre 2 et 5 ans, produisant un cerveau hypersuperbranché : chaque neurone cortical du jeune enfant a 2 fois plus de synapses qu'à l'âge adulte. L'adolescence est caractérisée par un <strong>élagage synaptique</strong> massif (synaptic pruning), éliminant les connexions peu utilisées selon le principe « use it or lose it » et raffinant les circuits. Ce processus, médié par la microglie (qui phagocyte les synapses marquées par le complément C3/C1q) et les astrocytes, est perturbé dans la schizophrénie : des études post-mortem et de génomique montrent un élagage excessif dans le CPFdl, pouvant expliquer la réduction de la densité synaptique préfrontale caractéristique de la maladie.</p>
""",
'neurochimie/neurotransmetteurs': """
<h3>La modulation neuroendocrinienne : ocytocine et vasopressine</h3>
<p class="resume-text">L'<strong>ocytocine</strong> et la <strong>vasopressine</strong>, produites dans le noyau paraventriculaire et supraoptique de l'hypothalamus, sont libérées dans le sang (régulation périphérique) et dans le cerveau via des projections axonales (neuromodulation centrale). L'ocytocine facilite les comportements d'attachement, la confiance sociale, l'allaitement et le lien mère-enfant. La vasopressine (ADH) régule la pression artérielle et, dans le cerveau, module l'agressivité et les comportements territoriaux. Les campagnols des prairies, monogames, ont une densité de récepteurs à la vasopressine striato-limbique bien supérieure aux campagnols des montages, polygames — suggérant que ces récepteurs codent la fidélité de couple chez ces rongeurs.</p>
<p class="resume-text">L'ocytocine intranasale, qui peut atteindre le cerveau en partie via les projections olfactives, améliore la reconnaissance des expressions émotionnelles, augmente la confiance dans les jeux économiques et réduit l'anxiété sociale. Cependant, ses effets ne sont pas universellement positifs : elle renforce aussi le comportement pro-endogroupe et peut accroître l'hostilité envers l'exogroupe (biais d'endogroupe). Des essais cliniques d'ocytocine pour le trouble du spectre autistique, initialement prometteurs, ont produit des résultats mitigés dans les essais plus larges, soulignant la complexité de cette modulation neuroendocrinienne du comportement social.</p>
""",
'computationnelle/modelisation': """
<h3>L'apprentissage machine pour l'analyse des données de neuroimagerie</h3>
<p class="resume-text">L'intelligence artificielle transforme l'analyse des données de neuroimagerie. Des algorithmes de <strong>décodage cérébral</strong> (brain decoding) prédisent à partir des patterns d'activation IRMf les stimuli visuels observés, les pensées ou les états mentaux d'un sujet avec une précision croissante. Yoshida et al. (2023) ont démontré qu'un modèle de diffusion entraîné sur des paires données IRMf-images peut reconstruire des images mentalement imaginées avec une fidélité étonnante — approchant un décodage visuel cortical de précision millimétrée.</p>
<p class="resume-text">Les <strong>réseaux de neurones convolutifs</strong> (CNN) atteignent des performances surhumaines dans la segmentation automatique des structures cérébrales à l'IRM (hippocampe, noyaux gris, cortex laminaire) et dans la détection précoce de pathologies (plaques MS, leucoaraiose, microhémorragies). Des modèles de fondation (foundation models) entraînés sur des milliers d'IRM cérébraux (BrainAGE, UKBioBank) peuvent prédire l'âge biologique cérébral d'un individu à ± 2 ans et détecter des anomalies subtiles précédant les symptômes cliniques, ouvrant la voie à un dépistage neuropathologique populationnel à grande échelle.</p>
""",
'computationnelle/ia-bio-inspiree': """
<h3>Le neuroscience computationnelle comme validation des théories</h3>
<p class="resume-text">Au-delà de l'inspiration, les architectures d'IA servent d'outil de test des théories neuroscientifiques. La théorie du codage prédictif prédit que le cerveau minimise l'erreur de prédiction hiérarchiquement. L'implémentation de cette théorie dans des réseaux d'apprentissage profond (predictive coding networks) montre que ces réseaux apprennent des représentations hiérarchiques de l'espace visuel similaires à celles du cortex visuel, mais avec une meilleure généralisation et robustesse aux perturbations que les CNN supervisés classiques. Ces comparaisons modèle-cerveau permettent d'identifier quels aspects de l'architecture biologique contribuent à quelles propriétés computationnelles.</p>
<p class="resume-text">Les <strong>réseaux adversariaux génératifs</strong> (GAN) offrent un modèle de perception hallucinatoire : le générateur (cortex visuel top-down) produit des prédictions ; le discriminateur (cortex visuel bottom-up) les évalue contre les entrées sensorielles. En modes extrêmes, le générateur peut « halluciner » des percepts sans entrée sensorielle réelle — analogue aux hallucinations psychotiques où le système de génération de prédictions s'emballe. Des travaux récents modélisent les hallucinations schizophréniques comme un biais excessif vers les priors internes (attentes) au détriment des données sensorielles — formalisé dans le cadre bayésien de l'inférence active de Friston.</p>
""",
'computationnelle/apprentissage-hebbien': """
<h3>La plasticité homéostatique et la stabilité des réseaux hebbiens</h3>
<p class="resume-text">L'apprentissage hebbien pur est instable : les poids synaptiques croissent sans limite, un phénomène appelé « emballement hebbien ». Des mécanismes de plasticité homéostatique stabilisent les réseaux en régulant dynamiquement l'excitabilité neuronale. La <strong>mise à l'échelle synaptique</strong> (synaptic scaling), décrite par Gina Turrigiano, ajuste globalement tous les poids synaptiques d'un neurone pour maintenir son taux de décharge moyen autour d'une valeur cible : si le neurone est trop silencieux, toutes ses synapses sont renforcées proportionnellement ; si trop actif, toutes sont affaiblies. Ce mécanisme multiplicatif préserve les différences relatives de poids (donc les informations apprises) tout en normalisant l'activité absolue.</p>
<p class="resume-text">La règle de Oja (1982) introduit un terme de décroissance normalisateur dans la règle hebbienne, garantissant la convergence vers les composantes principales des données d'entrée (analyse en composantes principales, ACP). La règle de BCM (Bienenstock-Cooper-Munro, 1982) introduit un seuil de modification glissant : la synapse est potentiée si l'activité postsynaptique dépasse un seuil θ, déprimée en dessous. Ce seuil θ lui-même s'adapte au niveau moyen d'activité — si l'activité est chroniquement élevée, θ monte, rendant la LTD plus facile ; si basse, θ descend, facilitant la LTP. Cette règle capture à la fois la plasticité et l'homéostasie dans un formalisme élégant.</p>
""",
'computationnelle/neurones-formels': """
<h3>Les architectures d'attention et le traitement parallèle</h3>
<p class="resume-text">L'architecture <strong>Transformer</strong>, dominante en IA depuis 2017, peut être vue comme une version radicalement parallèle et flexible du réseau neuronal formel. Là où les neurones de McCulloch-Pitts sont des unités fixes, le mécanisme d'attention du Transformer calcule dynamiquement les poids d'importance entre tous les éléments d'une séquence à chaque étape de traitement. Cette flexibilité permet au modèle de traiter des dépendances à longue distance dans les séquences (comme les dépendances grammaticales dans les phrases longues) que les RNN classiques peinent à capturer.</p>
<p class="resume-text">La <strong>plausibilité biologique</strong> des architectures actuelles reste un sujet de débat. La rétropropagation du gradient, algorithme d'entraînement dominant, nécessite la transmission d'informations en sens inverse dans le réseau — ce qui n'a pas d'équivalent biologique direct. Des alternatives biologiquement plausibles sont proposées : le perturbation local de poids (weight perturbation), l'apprentissage ciblé par propagation (target propagation), et le codage prédictif comme algorithme d'apprentissage. Ces alternatives, moins efficaces computationnellement pour l'instant, pourraient néanmoins capturer des aspects essentiels de l'apprentissage biologique que la rétropropagation ignore.</p>
""",
}

for key, html in extras.items():
    inject(key, html)

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Final check
short = [(k, len(v.get('content',''))) for k,v in pages.items() if v.get('type') in ['course','lesson'] and len(v.get('content','')) < 15000]
total = [(k, len(v.get('content',''))) for k,v in pages.items() if v.get('type') in ['course','lesson']]
print(f"Total course pages: {len(total)}")
print(f"Pages under 15k: {len(short)}")
if short:
    for k,n in sorted(short, key=lambda x:x[1]):
        print(f"  {k}: {n} (needs +{15000-n})")
else:
    print("All pages >= 15000 chars!")
avg = sum(n for _,n in total)/len(total)
print(f"Average content length: {avg:.0f} chars")
