import json

ENRICHMENTS = {
"organisations-internationales/systeme-des-nations-unies": """
<h3>L'architecture institutionnelle de l'ONU</h3>
<p class="resume-text">L'<strong>ONU</strong> repose sur six organes principaux. L'<strong>Assemblée générale</strong> réunit les 193 États membres (un État, une voix) et délibère sur toutes les questions touchant à la paix, la sécurité, le développement et les droits humains. Ses résolutions sont recommandatoires sauf pour les questions budgétaires et d'admission de nouveaux membres. Le <strong>Conseil de sécurité</strong>, composé de 15 membres (5 permanents dotés du droit de veto : États-Unis, Russie, Chine, France, Royaume-Uni et 10 membres élus), est seul compétent pour prendre des décisions contraignantes en matière de paix et de sécurité.</p>
<p class="resume-text">La <strong>Cour internationale de Justice</strong> (CIJ), siège à La Haye, règle les différends juridiques entre États. Le <strong>Secrétariat</strong>, dirigé par le Secrétaire général, est le bras exécutif de l'organisation. Le <strong>Conseil économique et social</strong> (ECOSOC) coordonne les travaux des agences spécialisées. Le <strong>Conseil de tutelle</strong>, chargé de superviser les territoires non autonomes, est désormais inactif depuis la décolonisation.</p>
<div class="highlight-box"><p>Le <strong>droit de veto</strong> au Conseil de sécurité a été utilisé 293 fois depuis 1946 jusqu'en 2023. La Russie/URSS détient le record avec 143 vetos, suivie des États-Unis (89). Ce mécanisme, conçu pour assurer l'adhésion des grandes puissances, est régulièrement critiqué pour paralyser l'ONU lors des conflits où une grande puissance est impliquée.</p></div>
<h3>Les agences spécialisées et le système onusien</h3>
<p class="resume-text">Le système onusien dépasse largement le siège de New York. Les <strong>agences spécialisées</strong> — organisations autonomes liées à l'ONU par des accords — couvrent tous les domaines : l'<strong>OMS</strong> pour la santé mondiale (siège à Genève), la <strong>FAO</strong> pour l'alimentation et l'agriculture (Rome), l'<strong>UNESCO</strong> pour l'éducation, la science et la culture (Paris), l'<strong>OIT</strong> pour le travail (Genève), l'<strong>OACI</strong> pour l'aviation civile (Montréal), la <strong>Banque mondiale</strong> et le <strong>FMI</strong> pour le développement et la finance internationale (Washington).</p>
<p class="resume-text">Les <strong>programmes et fonds</strong> de l'ONU (UNICEF, PNUD, UNHCR, PNUE) opèrent sous l'autorité de l'Assemblée générale et du Conseil économique et social. Le <strong>PNUD</strong> (Programme des Nations Unies pour le développement) est le principal acteur onusien du développement humain, publie l'indice de développement humain (IDH) annuel et coordonne l'aide technique dans 170 pays. Le <strong>HCR</strong> (Haut-Commissariat aux réfugiés) protège plus de 100 millions de déplacés dans le monde.</p>
<div class="highlight-box"><p>Le <strong>budget ordinaire</strong> de l'ONU est d'environ 3,2 milliards de dollars par an (2023), financé par les contributions des États membres selon leur part dans le revenu national brut mondial. Les États-Unis contribuent 22%, la Chine 15,2%, le Japon 8,0%, l'Allemagne 6,1%. Les opérations de maintien de la paix (casques bleus) représentent un budget séparé d'environ 6 milliards de dollars.</p></div>
<h3>Les opérations de maintien de la paix</h3>
<p class="resume-text">L'ONU a déployé 71 opérations de maintien de la paix depuis 1948 (ONUST en Palestine). Actuellement, environ 87 000 personnes (militaires, policiers et civils) servent sous le drapeau bleu de l'ONU dans une douzaine de missions à travers le monde : Congo, Mali, Soudan du Sud, Liban (FINUL), Chypre (UNFICYP), Sahara occidental. Ces missions coûtent environ 6 milliards de dollars par an.</p>
<p class="resume-text">Les opérations de maintien de la paix reposent sur trois principes fondateurs : le <strong>consentement des parties</strong> au conflit, l'<strong>impartialité</strong> des forces onusiennes, et le <strong>non-recours à la force</strong> sauf en légitime défense. Ces principes, issus de l'ère de la Guerre froide, ont été progressivement adaptés pour permettre des missions plus robustes, notamment la brigade d'intervention de la MONUSCO au Congo, autorisée à mener des opérations offensives contre les groupes armés.</p>
""",

"organisations-internationales/union-europeenne": """
<h3>Histoire et élargissements de l'Union européenne</h3>
<p class="resume-text">L'Union européenne trouve ses origines dans les traumatismes des deux guerres mondiales. La <strong>CECA</strong> (Communauté européenne du charbon et de l'acier, 1951), proposée par Robert Schuman et Jean Monnet, posa les bases en mettant en commun la production d'acier et de charbon — les matières premières de la guerre — entre la France, l'Allemagne, l'Italie et le Benelux. Les traités de Rome (1957) créèrent la CEE (Communauté économique européenne) et l'Euratom, élargissant l'intégration économique.</p>
<p class="resume-text">L'UE a connu six vagues d'élargissement : Royaume-Uni, Irlande, Danemark (1973) ; Grèce (1981) ; Espagne, Portugal (1986) ; Autriche, Finlande, Suède (1995) ; dix pays d'Europe centrale et orientale plus Chypre et Malte (2004) ; Bulgarie et Roumanie (2007) ; Croatie (2013). Le Brexit (2020) marque la première sortie d'un État membre. L'UE compte aujourd'hui 27 membres, avec plusieurs candidats officiels (Ukraine, Moldavie, pays des Balkans occidentaux).</p>
<div class="highlight-box"><p>Le <strong>traité de Maastricht</strong> (1992) est un tournant majeur : il crée l'Union européenne (remplaçant la CEE), institue la citoyenneté européenne, prépare l'Union économique et monétaire (euro) et ajoute des compétences en politique étrangère et en justice-affaires intérieures. C'est le passage d'une communauté économique à une union politique.</p></div>
<h3>Les institutions européennes et leurs rôles</h3>
<p class="resume-text">L'UE dispose d'un système institutionnel original, ni fédéral ni interétatique classique. Le <strong>Parlement européen</strong> (705 députés élus au suffrage universel direct depuis 1979) co-légifère avec le Conseil et vote le budget. Le <strong>Conseil de l'UE</strong> réunit les ministres des États membres par domaine politique (agriculture, finances, etc.) et représente les intérêts nationaux. Le <strong>Conseil européen</strong> rassemble les chefs d'État et de gouvernement pour définir les orientations politiques générales.</p>
<p class="resume-text">La <strong>Commission européenne</strong> (27 commissaires, un par État membre) est le gouvernement exécutif de l'UE : elle propose la législation, gère le budget, négocie les accords commerciaux et veille au respect du droit européen. La <strong>Cour de justice de l'UE</strong> (Luxembourg) interprète le droit européen et tranche les litiges entre États membres et institutions. La <strong>Banque centrale européenne</strong> (Francfort) conduit la politique monétaire de la zone euro (20 membres).</p>
<div class="highlight-box"><p>La <strong>zone euro</strong>, créée en 1999 (billets et pièces en 2002), regroupe 20 des 27 États membres. Elle a traversé une grave crise de la dette souveraine (2010-2015) en Grèce, Irlande, Portugal, Espagne et Chypre. La création du Mécanisme européen de stabilité et les programmes d'assistance financière conditionnelle ont sauvé la zone euro mais au prix d'une austérité sévère dans les pays aidés.</p></div>
<h3>Les défis contemporains de l'intégration européenne</h3>
<p class="resume-text">L'UE fait face à plusieurs défis majeurs. Le <strong>Brexit</strong> (référendum 2016, sortie effective 2020) a été un traumatisme institutionnel qui a renforcé les forces eurosceptiques dans plusieurs pays membres. La <strong>crise migratoire</strong> (2015-2016, puis 2022-2023 avec les réfugiés ukrainiens) a exacerbé les tensions entre États membres sur le partage des responsabilités. La <strong>crise de l'État de droit</strong> en Hongrie et en Pologne a poussé l'UE à développer des mécanismes de conditionnalité budgétaire.</p>
<p class="resume-text">Face à la pandémie de Covid-19, l'UE a réalisé un saut fédéral significatif en créant le fonds <strong>NextGenerationEU</strong> (750 milliards d'euros), financé par une dette commune européenne — une première historique. La guerre en Ukraine (2022) a accéléré l'intégration en matière de défense (Boussole stratégique) et d'énergie (diversification des approvisionnements), tout en plaçant l'élargissement aux Balkans et à l'Ukraine au centre de l'agenda politique.</p>
""",

"organisations-internationales/otan-et-alliances": """
<h3>L'OTAN : structure, décision et opérations</h3>
<p class="resume-text">L'<strong>OTAN</strong> (Organisation du traité de l'Atlantique Nord), fondée en 1949 par 12 membres fondateurs, compte aujourd'hui 32 membres (Finlande et Suède ayant rejoint l'Alliance en 2023-2024 après l'invasion russe de l'Ukraine). Le <strong>Conseil de l'Atlantique Nord</strong>, où siègent les ambassadeurs permanents des 32 membres, est l'organe décisionnel suprême. Les décisions s'y prennent par consensus, ce qui confère à chaque allié un droit de veto informel.</p>
<p class="resume-text">La structure militaire intégrée comprend le <strong>SACEUR</strong> (Supreme Allied Commander Europe), traditionnellement un général américain, qui commande les forces alliées en Europe depuis le Grand Quartier Général des puissances alliées en Europe (SHAPE) à Mons (Belgique). L'objectif des 2% du PIB consacrés à la défense, adopté au sommet du Pays de Galles (2014), est devenu un point de friction récurrent, notamment avec l'Allemagne — qui l'a finalement atteint en 2024 après des années de retard.</p>
<div class="highlight-box"><p>L'<strong>article 5</strong> du traité de Washington stipule qu'une attaque armée contre un membre est considérée comme une attaque contre tous. Il n'a été invoqué qu'une seule fois dans l'histoire de l'OTAN : le 12 septembre 2001, au lendemain des attentats du 11 septembre. Cette décision conduit à l'engagement de l'OTAN en Afghanistan (2003-2021).</p></div>
<h3>Les autres alliances régionales</h3>
<p class="resume-text">L'OTAN n'est pas la seule alliance de sécurité collective. En Asie-Pacifique, les États-Unis maintiennent un réseau d'alliances bilatérales (hub-and-spokes) avec le Japon, la Corée du Sud, l'Australie, les Philippines et la Thaïlande. L'<strong>ANZUS</strong> (1951) lie les États-Unis, l'Australie et la Nouvelle-Zélande. L'<strong>AUKUS</strong> (2021) approfondit la coopération de défense entre ces derniers, notamment pour fournir des sous-marins à propulsion nucléaire à l'Australie — décision qui a provoqué une grave crise diplomatique avec la France.</p>
<p class="resume-text">La <strong>Ligue arabe</strong> (22 membres), le <strong>Conseil de coopération du Golfe</strong> (CCG), l'<strong>ASEAN</strong> en Asie du Sud-Est, l'<strong>Union africaine</strong> et l'<strong>OEA</strong> en Amérique se sont dotés de mécanismes de sécurité collective, avec des degrés d'intégration et d'efficacité variables. La Russie a créé l'<strong>Organisation du traité de sécurité collective</strong> (OTSC) avec plusieurs ex-républiques soviétiques, mais son prestige a été entamé par son incapacité à intervenir efficacement lors des crises au Kazakhstan (2022) et entre l'Arménie et l'Azerbaïdjan.</p>
<div class="highlight-box"><p>L'invasion russe de l'Ukraine en 2022 a revitalisé l'OTAN, perçue comme « en mort cérébrale » par Macron en 2019. Elle a provoqué la candidature rapide de la Finlande et de la Suède (longtemps neutres), l'augmentation significative des budgets de défense européens et le déploiement de bataillons multinationaux dans tous les pays frontaliers de la Russie.</p></div>
""",

"organisations-internationales/organisations-regionales": """
<h3>L'Union africaine : ambitions et défis</h3>
<p class="resume-text">L'<strong>Union africaine</strong> (UA), fondée en 2002 pour remplacer l'Organisation de l'unité africaine (OUA, 1963), regroupe 55 États membres. Elle est dotée d'une Commission (exécutif), d'un Parlement pan-africain, d'un Conseil de paix et de sécurité et d'une Cour africaine des droits de l'homme. Son ambition déclarée est la création d'une zone de libre-échange continentale africaine (ZLECAF, opérationnelle depuis 2021), d'une banque centrale africaine et à terme d'une monnaie commune.</p>
<p class="resume-text">L'UA a développé une doctrine de sécurité originale : le droit d'intervenir dans un État membre en cas de génocide, crimes de guerre ou crimes contre l'humanité — une rupture avec le principe de non-ingérence de l'OUA. Elle a déployé des missions de paix au Darfour (UNAMID), en Somalie (AMISOM/ATMIS) et au Sahel. Cependant, les financements restent insuffisants : l'UA dépend encore à plus de 60% de contributions extérieures (UE, Nations Unies, États-Unis) pour ses opérations de maintien de la paix.</p>
<div class="highlight-box"><p>La <strong>Zone de libre-échange continentale africaine</strong> (ZLECAF), entrée en vigueur en 2019, est potentiellement l'une des plus grandes zones de libre-échange au monde avec 1,3 milliard de personnes et un PIB combiné de 3 400 milliards de dollars. Son plein déploiement représenterait un facteur de développement majeur pour le continent.</p></div>
<h3>L'ASEAN et l'intégration en Asie du Sud-Est</h3>
<p class="resume-text">L'<strong>ASEAN</strong> (Association des nations de l'Asie du Sud-Est, fondée en 1967, 10 membres) est un modèle original d'intégration régionale basé sur la non-ingérence, le consensus et une approche graduelle. Elle n'a pas de cour de justice supranationale ni de parlement élu. Sa force réside dans la création d'espaces de dialogue entre des pays aux régimes politiques très différents (démocraties, monarchies, régimes autoritaires) et à l'histoire conflictuelle.</p>
<p class="resume-text">L'ASEAN a progressivement élargi son agenda : zone de libre-échange (AFTA), Communauté économique ASEAN (2015), forum régional de l'ASEAN pour la sécurité. Elle est au centre d'une architecture diplomatique plus large : l'ASEAN+3 (avec Chine, Japon, Corée), l'ASEAN+6, et le Sommet de l'Asie orientale. Cependant, les tensions en mer de Chine méridionale ont mis à l'épreuve sa capacité à maintenir une position commune face aux pressions chinoises.</p>
<div class="highlight-box"><p>La <strong>« voie de l'ASEAN »</strong> (ASEAN Way) désigne une approche diplomatique privilégiant la consultation, le consensus, la non-confrontation et la non-ingérence. Cette méthode rend les décisions lentes mais assure leur légitimité. Elle a été exportée à d'autres forums régionaux, notamment dans le Pacifique.</p></div>
""",

"organisations-internationales/ong-et-societe-civile": """
<h3>Les grandes ONG internationales et leur fonctionnement</h3>
<p class="resume-text">Les <strong>organisations non gouvernementales internationales</strong> (ONGI) constituent un acteur majeur du système international, avec plus de 40 000 ONG reconnues à l'échelle internationale. Les plus influentes couvrent des domaines variés : <strong>Amnesty International</strong> (droits humains, fondée en 1961, 10 millions de membres), <strong>Greenpeace</strong> (environnement, fondée en 1971), <strong>Oxfam</strong> (développement et lutte contre la pauvreté, fondée en 1942), <strong>Médecins sans Frontières</strong> (aide médicale d'urgence, Nobel de la paix 1999), <strong>CICR</strong> (droit humanitaire, fondé en 1863 par Henry Dunant).</p>
<p class="resume-text">Les ONG remplissent plusieurs fonctions dans le système international : plaidoyer (lobbying auprès des gouvernements et organisations internationales), expertise technique (production de rapports et données indépendants), opérations humanitaires sur le terrain, et surveillance de l'application des normes internationales. Le CICR a un statut sui generis : il est la seule organisation non gouvernementale disposant d'un mandat officiel fondé sur les Conventions de Genève pour protéger les victimes des conflits armés.</p>
<div class="highlight-box"><p><strong>Médecins sans Frontières</strong> a révolutionné l'action humanitaire en affirmant le droit — voire le devoir — d'ingérence humanitaire et en témoignant publiquement des violations des droits humains même quand cela contrarie les gouvernements. Cette posture de « médecins rebelles » tranche avec la discrétion traditionnelle du CICR.</p></div>
<h3>Les réseaux transnationaux de la société civile</h3>
<p class="resume-text">Au-delà des grandes ONG, la société civile internationale s'organise en <strong>réseaux transnationaux</strong> qui jouent un rôle croissant dans la formation des normes internationales. Le Réseau international pour l'interdiction des mines antipersonnel (ICBL), né d'une coalition d'ONG, a mené campagne pendant des années et abouti à la <strong>Convention d'Ottawa</strong> (1997) signée par 164 pays — sans que les États-Unis, la Russie et la Chine ne l'aient ratifiée. Cette campagne illustre comment des coalitions d'ONG peuvent contourner les grandes puissances pour faire avancer des normes internationales.</p>
<p class="resume-text">Les <strong>forums sociaux mondiaux</strong> (depuis Porto Alegre en 2001) ont créé des espaces de délibération alternatifs aux institutions de Bretton Woods. Les mouvements altermondialistes, bien que fragmentés, ont influencé les débats sur la mondialisation et poussé les institutions internationales (FMI, Banque mondiale, OMC) à intégrer des préoccupations sociales et environnementales dans leurs mandats.</p>
<div class="highlight-box"><p>Le <strong>lobbying des ONG</strong> aux Nations Unies est formalisé par le statut consultatif auprès de l'ECOSOC. Plus de 5 800 ONG bénéficient de ce statut, leur permettant d'assister aux réunions intergouvernementales, de soumettre des déclarations écrites et d'intervenir oralement. Cette ouverture a transformé la diplomatie multilatérale, la rendant moins exclusive mais aussi plus complexe à gérer.</p></div>
""",

"conflits/theories-du-conflit": """
<h3>Le réalisme et ses variantes</h3>
<p class="resume-text">Le <strong>réalisme</strong> est la théorie dominante des Relations Internationales depuis Thucydide. Il postule que les États sont les acteurs principaux du système international, que ce système est anarchique (sans autorité supérieure), et que les États cherchent avant tout à assurer leur survie et à maximiser leur puissance. Le <strong>néoréalisme</strong> (Kenneth Waltz, <em>Theory of International Politics</em>, 1979) affine cette analyse en distinguant la structure du système international (répartition des capacités entre les grands acteurs) de la politique étrangère des États particuliers.</p>
<p class="resume-text">Le <strong>réalisme offensif</strong> (John Mearsheimer) soutient que les grandes puissances cherchent non seulement à survivre mais à maximiser leur part relative de la puissance mondiale, poussées par l'incertitude des intentions des autres États. Pour Mearsheimer, l'hégémonie régionale est l'objectif stratégique ultime de toute grande puissance — ce qui explique selon lui les tensions autour de l'ascension de la Chine. Le <strong>réalisme défensif</strong> (Jack Snyder, Charles Glaser) considère au contraire que la recherche de sécurité, et non la maximisation de la puissance, est le moteur principal de la politique étrangère.</p>
<div class="highlight-box"><p>Le <strong>dilemme de sécurité</strong> est un concept central du réalisme : les mesures défensives qu'un État prend pour renforcer sa sécurité sont perçues comme offensives par les autres États, qui se sentent menacés et augmentent à leur tour leurs armements, ce qui diminue la sécurité de tous. La course aux armements USA-URSS pendant la Guerre froide en est l'exemple classique.</p></div>
<h3>Le libéralisme et l'institutionnalisme</h3>
<p class="resume-text">Le <strong>libéralisme internationaliste</strong> (Kant, Wilson, puis Keohane et Nye) conteste le postulat réaliste d'un système international immuablement conflictuel. Il met en avant les forces qui favorisent la coopération : interdépendance économique (les États commercialement intégrés ont moins d'incitations à se faire la guerre), démocratie (les démocraties libérales ne se font pas la guerre entre elles — la « paix démocratique »), et organisations internationales (elles réduisent les coûts de transaction et fournissent des informations qui permettent la coopération).</p>
<p class="resume-text">L'<strong>institutionnalisme néolibéral</strong> (Robert Keohane, <em>After Hegemony</em>, 1984) reconnaît l'anarchie internationale mais montre que les institutions internationales permettent malgré tout la coopération en réduisant l'incertitude, en créant des précédents et en réprimant les comportements de passager clandestin. Cette théorie fournit les bases intellectuelles du projet d'intégration européenne et du multilatéralisme commercial.</p>
<div class="highlight-box"><p>La <strong>théorie de la paix démocratique</strong> — formulée par Michael Doyle dans les années 1980 à partir de Kant — est l'une des relations empiriques les plus robustes en Relations Internationales : on ne recense aucune guerre entre deux démocraties libérales établies. Cette observation a fortement influencé la politique étrangère américaine (promotion de la démocratie comme outil de sécurité) et l'élargissement de l'UE.</p></div>
<h3>Le constructivisme et les théories critiques</h3>
<p class="resume-text">Le <strong>constructivisme</strong> (Alexander Wendt, <em>Social Theory of International Politics</em>, 1999) rejette le matérialisme des théories réalistes et libérales. Pour Wendt, l'anarchie internationale n'a pas de contenu intrinsèque : « l'anarchie est ce que les États en font ». Les identités et les intérêts des États ne sont pas donnés mais construits socialement à travers les interactions. La Russie et les États-Unis possèdent tous deux des armes nucléaires, mais cela représente des menaces très différentes pour Washington selon qu'il s'agit de la Russie ou du Royaume-Uni — les capacités matérielles n'ont de sens qu'à travers les identités et les représentations.</p>
<p class="resume-text">Les <strong>théories critiques</strong> (école de Francfort, féminisme, postcolonialisme) questionnent les présupposés des théories mainstream. Les théories féministes montrent que la politique internationale est structurée par des hiérarchies de genre : les guerres sont décidées presque exclusivement par des hommes, les femmes sont les principales victimes des conflits et sont largement absentes des négociations de paix. Les théories postcoloniales rappellent que les catégories conceptuelles des RI (souveraineté, État, droit international) ont été forgées par l'Occident et naturalisent des rapports de domination hérités du colonialisme.</p>
""",

"conflits/guerres-modernes": """
<h3>La révolution dans les affaires militaires</h3>
<p class="resume-text">La <strong>Révolution dans les affaires militaires</strong> (RMA) désigne la transformation de la guerre par les technologies de l'information depuis les années 1980-1990. La guerre du Golfe (1991) a marqué une rupture : la supériorité technologique américaine (guidage de précision, supériorité aérienne, renseignement en temps réel) a permis une victoire éclair contre une armée conventionnelle irakienne pourtant nombreuse. Les missiles de croisière Tomahawk, les bombes guidées laser et les avions furtifs F-117 ont inauguré la guerre « chirurgicale ».</p>
<p class="resume-text">Les <strong>drones armés</strong> ont transformé les opérations militaires depuis les années 2000. Les Prédateurs et Reapers américains ont conduit des milliers de frappes en Afghanistan, Pakistan, Yémen et Libye — souvent contre des individus désignés (targeted killings). Cette forme de guerre à distance pose des questions éthiques et juridiques fondamentales : quelle est la légalité de frappes sur le territoire d'États souverains sans déclaration de guerre ? Quelle est la définition juridique d'un « combattant ennemi » justifiant son élimination ?</p>
<div class="highlight-box"><p>La guerre en <strong>Ukraine</strong> (depuis 2022) combine des éléments de guerre totale conventionnelle (blindés, artillerie, front de tranchées rappelant 1914) et de guerre technologique de pointe (drones FPV, missiles hypersoniques, guerre électronique, cyberattaques). Elle illustre que la RMA n'a pas rendu la guerre de haute intensité obsolète.</p></div>
<h3>Les guerres asymétriques et la contre-insurrection</h3>
<p class="resume-text">Depuis la fin de la Guerre froide, les conflits armés sont majoritairement des <strong>guerres asymétriques</strong> opposant des armées régulières à des acteurs non étatiques (guérillas, organisations terroristes, milices). Les États-Unis ont engagé des ressources considérables en Afghanistan (2001-2021) et en Irak (2003-2011) sans parvenir à vaincre des insurrections disposant de bien moindres ressources. Cette expérience a relancé la réflexion sur la <strong>contre-insurrection</strong> (COIN) et la nécessité de gagner les cœurs et les esprits des populations civiles.</p>
<p class="resume-text">La <strong>doctrine COIN</strong> du général Petraeus, déployée en Irak (2007-2008) et en Afghanistan, combina opérations militaires ciblées et investissements dans la reconstruction économique et politique. Elle a obtenu des résultats en Irak (la « Surge » et le Réveil des tribus sunnites) mais échoué à terme en Afghanistan, montrant les limites de l'ingénierie sociale externalisée. La théorie du <strong>Small Wars</strong> (petites guerres), forgée par les marines américains en Amérique centrale dans les années 1930, a connu une renaissance après 2001.</p>
""",

"conflits/terrorisme-international": """
<h3>Les vagues du terrorisme international</h3>
<p class="resume-text">Le politologue David Rapoport a théorisé les <strong>quatre vagues du terrorisme international</strong>. La première (1880-1920) est la vague anarchiste, marquée par les assassinats de dirigeants (président américain McKinley, tsar Alexandre II, archiduc François-Ferdinand). La deuxième (1920-1960) est la vague anticoloniale, avec des groupes comme l'Irgoun juif en Palestine mandataire ou le FLN algérien. La troisième (1960-1990) est la vague de la gauche révolutionnaire (Brigades rouges, Action directe, IRA, OLP). La quatrième (depuis 1979) est la vague djihadiste, déclenchée par la révolution iranienne et l'invasion soviétique de l'Afghanistan.</p>
<p class="resume-text">Le <strong>11 septembre 2001</strong> a représenté un changement qualitatif dans le terrorisme international : pour la première fois, une organisation non étatique (Al-Qaïda) frappait une grande puissance sur son propre sol avec des moyens conventionnels (avions civils détournés) pour un effet dévastateur (3 000 morts, effondrement des Twin Towers). Les attentats ont provoqué la plus grande réorganisation du système de sécurité américain depuis la Guerre froide et l'invocation de l'article 5 de l'OTAN.</p>
<div class="highlight-box"><p><strong>Al-Qaïda</strong> a innové sur le plan organisationnel en adoptant une structure en réseau décentralisé : pas de hiérarchie rigide mais des cellules autonomes partageant une idéologie commune et un financement. Cette structure rend l'organisation difficile à démanteler mais aussi moins efficace pour les opérations complexes nécessitant une coordination centrale.</p></div>
<h3>L'État islamique (Daech) et le terrorisme de la troisième génération</h3>
<p class="resume-text">L'<strong>État islamique</strong> (Daech/ISIS), qui contrôlait un territoire grand comme la Grande-Bretagne entre 2014 et 2019, représenta une évolution majeure du djihadisme : d'une organisation terroriste clandestine à un proto-État disposant de revenus fiscaux, d'une administration et d'une armée régulière. Sa stratégie médiatique sophistiquée — vidéos HD de haute qualité diffusées sur les réseaux sociaux — lui permit de recruter des milliers de candidats étrangers du monde entier.</p>
<p class="resume-text">La défaite territoriale de Daech (2019) n'a pas mis fin à la menace : l'organisation a muté en réseau clandestin, continuant des attaques en Irak, Syrie, Afrique subsaharienne et Europe. Le <strong>terrorisme inspiré</strong> (« loup solitaire ») pose des défis particuliers aux services de renseignement : des individus radicalisés seuls via internet commettent des attentats avec des moyens rudimentaires (véhicule-bélier, couteau) sans lien avec une organisation structurée.</p>
""",

"conflits/droit-humanitaire": """
<h3>Les Conventions de Genève et leurs protocoles additionnels</h3>
<p class="resume-text">Le <strong>droit international humanitaire</strong> (DIH) repose sur quatre Conventions de Genève (1949), ratifiées par 196 États, et deux Protocoles additionnels (1977). La Première Convention protège les blessés et malades des forces armées en campagne ; la Deuxième, les naufragés ; la Troisième établit le statut des prisonniers de guerre (PoW) ; la Quatrième protège les civils en temps de guerre. Ces textes définissent les normes minimales de traitement des personnes ne participant plus aux hostilités.</p>
<p class="resume-text">Les <strong>Protocoles additionnels de 1977</strong> ont étendu le DIH aux conflits armés non internationaux (guerre civile) et renforcé la protection des civils, notamment en prohibant les attaques directes contre eux et en imposant le principe de proportionnalité (les dommages collatéraux civils ne doivent pas être excessifs par rapport à l'avantage militaire attendu). Le troisième protocole (2005) a créé le cristal rouge, signe de protection alternatif à la croix rouge et au croissant rouge.</p>
<div class="highlight-box"><p>Les <strong>Conventions de Genève</strong> font partie du <em>jus in bello</em> (droit dans la guerre), distinct du <em>jus ad bellum</em> (droit à la guerre). Cette distinction est fondamentale : même une guerre injuste doit être conduite selon les règles humanitaires ; et même une guerre juste doit respecter les limites imposées par le DIH. Les deux régimes fonctionnent indépendamment.</p></div>
<h3>Crimes de guerre, crimes contre l'humanité et génocide</h3>
<p class="resume-text">Le <strong>Statut de Rome</strong> (1998), qui crée la <strong>Cour pénale internationale</strong> (CPI), définit quatre catégories de crimes : le <strong>génocide</strong> (actes commis avec l'intention de détruire en tout ou en partie un groupe national, ethnique, racial ou religieux), les <strong>crimes contre l'humanité</strong> (actes graves commis dans le cadre d'une attaque généralisée ou systématique contre une population civile), les <strong>crimes de guerre</strong> (violations graves du DIH), et le <strong>crime d'agression</strong>. La CPI, dont le siège est à La Haye, n'est saisie que lorsque les États ne peuvent ou ne veulent pas juger eux-mêmes les auteurs.</p>
<p class="resume-text">Les <strong>tribunaux pénaux internationaux ad hoc</strong> pour l'ex-Yougoslavie (TPIY, 1993) et le Rwanda (TPIR, 1994) ont constitué une avancée majeure dans la répression des crimes internationaux. Le TPIY a jugé plus de 160 personnes, dont Slobodan Milosevic (décédé avant le verdict) et Ratko Mladic. Ces juridictions ont développé la jurisprudence sur les crimes de guerre et les crimes contre l'humanité, notamment la définition du viol comme crime de guerre.</p>
""",

"conflits/resolution-des-conflits": """
<h3>Les mécanismes formels de règlement pacifique des différends</h3>
<p class="resume-text">La <strong>Charte des Nations Unies</strong> (article 33) liste les méthodes pacifiques de règlement des différends : négociation, enquête, médiation, conciliation, arbitrage, règlement judiciaire, recours aux organismes régionaux. Ces méthodes se distinguent par leur degré de formalisme et le caractère contraignant de leur résultat. La négociation directe est la plus souple ; la décision judiciaire est la plus contraignante mais aussi la moins utilisée, les États répugnant à soumettre des différends politiques sensibles à des juges internationaux.</p>
<p class="resume-text">La <strong>Cour internationale de Justice</strong> (CIJ), organe judiciaire principal des Nations Unies, règle les différends entre États qui ont accepté sa juridiction. Elle a rendu des arrêts importants sur les frontières maritimes (délimitation des ZEE), les différends frontaliers terrestres et les violations du droit international. Ses arrêts sont contraignants pour les parties, mais le Conseil de sécurité est en théorie chargé de les faire appliquer — un mécanisme peu efficace quand un membre permanent est partie au différend.</p>
<div class="highlight-box"><p>L'<strong>arbitrage international</strong> est souvent préféré à la CIJ pour les différends commerciaux et d'investissement. La Cour permanente d'arbitrage (La Haye) et la Chambre de commerce internationale (Paris) règlent chaque année des milliers de litiges entre États et entreprises. L'affaire de la mer de Chine méridionale (2016), où le Tribunal arbitral de l'UNCLOS a jugé illégales les prétentions chinoises, illustre à la fois la force et les limites de l'arbitrage : la Chine a refusé de participer et de reconnaître la sentence.</p></div>
<h3>La consolidation de la paix après les conflits</h3>
<p class="resume-text">La <strong>consolidation de la paix</strong> (peacebuilding) désigne l'ensemble des activités destinées à prévenir le retour à la violence après un conflit. Elle va bien au-delà du maintien de la paix militaire : reconstruction institutionnelle (refonte des forces armées et de police, réforme du secteur judiciaire), réconciliation (commissions Vérité et Réconciliation), justice transitionnelle (jugement des auteurs de violations), réintégration des combattants démobilisés, retour des réfugiés, reconstruction économique.</p>
<p class="resume-text">La <strong>Commission de consolidation de la paix</strong> de l'ONU (créée en 2005) coordonne les efforts internationaux dans les pays sortant de conflit. Elle a été saisie pour le Burundi, la Sierra Leone, la Guinée-Bissau, le Libéria et la République centrafricaine. L'expérience montre que la consolidation de la paix est un processus de long terme (10-20 ans) qui exige une présence internationale durable, des ressources considérables et une forte appropriation nationale — sans quoi le risque de rechute dans le conflit reste élevé.</p>
""",

"traites/droit-des-traites": """
<h3>La conclusion et l'entrée en vigueur des traités</h3>
<p class="resume-text">La <strong>Convention de Vienne sur le droit des traités</strong> (1969) codifie les règles coutumières régissant la conclusion, l'interprétation et la terminaison des traités internationaux. Un traité passe par plusieurs étapes : la <strong>négociation</strong> (rédaction du texte), l'<strong>adoption</strong> (accord sur le texte), l'<strong>authentification</strong> (signature, qui atteste le texte définitif), la <strong>ratification</strong> (engagement définitif de l'État, souvent après approbation parlementaire interne), et enfin l'<strong>entrée en vigueur</strong> (une fois le nombre minimum de ratifications atteint).</p>
<p class="resume-text">Les États peuvent formuler des <strong>réserves</strong> lors de la ratification, excluant ou modifiant l'effet de certaines dispositions à leur égard — dans la limite de leur compatibilité avec l'objet et le but du traité. Cette pratique permet à des États aux systèmes juridiques différents d'adhérer à un traité commun tout en préservant leurs spécificités. Les États-Unis ont largement utilisé les réserves pour ratifier des traités de droits humains tout en limitant leurs obligations domestiques.</p>
<div class="highlight-box"><p>Le <strong>traité entre Égypte et Israël</strong> (1979, Camp David) est resté longtemps secret dans ses annexes militaires. Il démontre comment les traités bilatéraux sensibles comportent souvent des parties classifiées connues seulement des parties signataires — pratique admise en droit international même si elle contrarie le principe wilsonien de diplomatie ouverte.</p></div>
<h3>L'interprétation et l'application des traités</h3>
<p class="resume-text">La Convention de Vienne établit trois méthodes d'interprétation des traités. L'<strong>interprétation textuelle</strong> (sens ordinaire des termes dans leur contexte) est la règle de base. L'<strong>interprétation téléologique</strong> (objet et but du traité) permet d'adapter le texte à des situations non prévues par les rédacteurs. Les <strong>travaux préparatoires</strong> (négociations, projets préliminaires) sont des moyens complémentaires d'interprétation quand le texte reste ambigu.</p>
<p class="resume-text">L'<strong>évolution des traités</strong> est un défi permanent. Certains traités contiennent des mécanismes d'amendement formels ; d'autres évoluent par la pratique des parties (droit coutumier) ou par l'interprétation évolutive des juridictions. La Cour européenne des droits de l'homme a développé la doctrine du traité « instrument vivant » : la Convention européenne doit être interprétée à la lumière des conditions actuelles, pas seulement de l'intention des rédacteurs de 1950. Cette approche permet d'étendre les protections à de nouvelles situations (internet, bioéthique, changement climatique) mais suscite aussi des critiques pour son activisme judiciaire.</p>
""",

"traites/desarmement-nucleaire": """
<h3>Le Traité sur la non-prolifération (TNP) et ses tensions</h3>
<p class="resume-text">Le <strong>TNP</strong> (1968, entré en vigueur en 1970, 191 États parties) repose sur trois piliers : non-prolifération (les États non nucléaires s'engagent à ne pas acquérir d'armes nucléaires), désarmement (les États nucléaires s'engagent à négocier de bonne foi le désarmement complet), et accès à l'énergie nucléaire civile (tous les États ont le droit d'utiliser pacifiquement le nucléaire sous supervision de l'AIEA). Ce traité reconnaît officiellement cinq États détenteurs d'armes nucléaires : États-Unis, Russie, Chine, France, Royaume-Uni.</p>
<p class="resume-text">La tension fondamentale du TNP est l'asymétrie entre ses obligations : les États non nucléaires ont renoncé définitivement aux armes atomiques en échange d'une promesse de désarmement par les États nucléaires — promesse très partiellement tenue. La Conférence d'examen de 2015 a échoué faute de consensus, reflétant les frustrations croissantes des États non nucléaires face au maintien et à la modernisation des arsenaux des grandes puissances.</p>
<div class="highlight-box"><p>L'<strong>Inde, le Pakistan et Israël</strong> n'ont jamais signé le TNP et possèdent des armes nucléaires. La <strong>Corée du Nord</strong> a annoncé son retrait du TNP en 2003 et a procédé à six essais nucléaires (2006-2017). Ces cas révèlent les limites du régime de non-prolifération face à des États déterminés à acquérir la bombe pour des raisons de sécurité nationale.</p></div>
<h3>Des traités de limitation à la réduction des arsenaux</h3>
<p class="resume-text">Les traités de limitation et de réduction des armements nucléaires ont connu des avancées significatives puis un recul inquiétant. Les accords <strong>SALT</strong> (1972, 1979) plafonnèrent les arsenaux stratégiques américains et soviétiques. Le traité <strong>INF</strong> (1987) élimina pour la première fois une catégorie entière d'armes : tous les missiles à portée intermédiaire (500-5500 km). Les traités <strong>START</strong> (1991, 2010) ont réduit les ogives stratégiques déployées à 1 550 par partie.</p>
<p class="resume-text">Ce mouvement de désarmement s'est inversé depuis 2010. Les États-Unis se sont retirés du traité ABM (2002), permettant le déploiement de défenses antimissiles. Les États-Unis puis la Russie se sont retirés du traité INF (2019). La Russie a suspendu sa participation au New START en 2023 après l'invasion de l'Ukraine. La Chine refuse tout dialogue sur ses arsenaux, en pleine expansion. Le risque d'une nouvelle course aux armements nucléaires, multipolarisée cette fois, est pris très au sérieux par les experts en désarmement.</p>
""",

"traites/droit-de-la-mer": """
<h3>La CNUDM : une constitution pour les océans</h3>
<p class="resume-text">La <strong>Convention des Nations Unies sur le droit de la mer</strong> (CNUDM, 1982, entrée en vigueur en 1994) est souvent qualifiée de « constitution des océans ». Elle établit un cadre juridique complet pour tous les espaces marins : mer territoriale (12 milles nautiques), zone contiguë (24 miles), <strong>zone économique exclusive</strong> (ZEE, 200 miles), plateau continental, haute mer et Zone internationale des fonds marins. La ZEE confère à l'État côtier des droits souverains sur les ressources biologiques et minérales — un enjeu économique considérable.</p>
<p class="resume-text">Les <strong>détroits internationaux</strong> et passages archipélagiques font l'objet de régimes spécifiques de transit. Le passage en transit dans les détroits (Hormuz, Malacca, Bosphore) ne peut être suspendu par l'État riverain, garantissant la liberté de navigation pour les navires de commerce et de guerre. Ces règles ont des implications stratégiques majeures : le détroit d'Ormuz, par où transit 20% du pétrole mondial, est au cœur des tensions entre Iran et États-Unis.</p>
<div class="highlight-box"><p>La <strong>mer de Chine méridionale</strong> est le théâtre du différend maritime le plus explosif du XXIe siècle. La Chine revendique environ 90% de cette mer via la « ligne en neuf tirets », construisant des îles artificielles et y installant des bases militaires. Cette revendication a été jugée contraire à la CNUDM par le Tribunal arbitral en 2016 — que la Chine a rejeté. L'enjeu est considérable : pêche, hydrocarbures, et surtout contrôle d'une des routes commerciales les plus fréquentées du monde.</p></div>
<h3>Les ressources marines et leur gouvernance</h3>
<p class="resume-text">La CNUDM a créé l'<strong>Autorité internationale des fonds marins</strong> (AIFM, siège à Kingston, Jamaïque) pour gérer les ressources minérales des fonds marins internationaux — nodules polymétalliques, encroûtements cobaltifères, sulfures hydrothermaux. Ces ressources, qui contiennent des métaux critiques (manganèse, nickel, cobalt, cuivre) indispensables aux batteries et aux technologies vertes, font l'objet d'un intérêt croissant. Des premières exploitations commerciales pourraient commencer dans les années 2030, soulevant des questions environnementales sur les impacts des écosystèmes abyssaux.</p>
<p class="resume-text">En 2023, l'ONU a adopté le <strong>Traité sur la haute mer</strong> (accord sur la biodiversité au-delà des juridictions nationales, BBNJ), après vingt ans de négociations. Ce traité crée un cadre pour la création d'aires marines protégées en haute mer, le partage des avantages tirés des ressources génétiques marines, et les études d'impact environnemental. Il représente une avancée majeure pour la gouvernance des océans qui couvrent 65% de la surface terrestre mais ne bénéficiaient d'aucune protection formelle.</p>
""",

"traites/droit-international-environnemental": """
<h3>Du droit des espèces au droit climatique</h3>
<p class="resume-text">Le <strong>droit international de l'environnement</strong> a émergé dans les années 1960-1970, stimulé par la prise de conscience des crises écologiques globales. La Conférence de Stockholm (1972) posa les premiers principes (pollueur-payeur, prévention, participation). La Convention sur le commerce international des espèces menacées (<strong>CITES</strong>, 1973) interdit le commerce des espèces en danger. La Convention de Montréal (1987), qui a conduit à l'élimination progressive des chlorofluorocarbones responsables du trou dans la couche d'ozone, est souvent citée comme le traité environnemental le plus réussi.</p>
<p class="resume-text">La <strong>Convention-cadre des Nations Unies sur les changements climatiques</strong> (CCNUCC, 1992) a initié un processus de négociations qui a conduit au Protocole de Kyoto (1997, obligations de réduction pour les seuls pays développés), puis à l'<strong>Accord de Paris</strong> (2015). L'Accord de Paris adopte une architecture bottom-up : chaque État fixe ses propres contributions nationales déterminées (NDC) selon le principe de responsabilités communes mais différenciées et de capacités respectives. Cet accord universel (195 signataires) est juridiquement contraignant pour le processus mais non pour les objectifs chiffrés.</p>
<div class="highlight-box"><p>L'<strong>Accord de Paris</strong> (2015) vise à maintenir le réchauffement en dessous de 2°C par rapport aux niveaux préindustriels, et si possible en dessous de 1,5°C. Son architecture innovante — contributions volontaires mais examen collectif tous les cinq ans (mécanisme de cliquet) — tente de concilier ambition climatique et souveraineté nationale. Le retrait puis le retour des États-Unis illustre sa fragilité politique.</p></div>
<h3>Les tensions Nord-Sud dans la gouvernance environnementale</h3>
<p class="resume-text">La négociation internationale sur l'environnement est traversée par une tension structurelle entre pays développés et pays en développement. Les premiers sont responsables de l'essentiel des émissions historiques de CO2 ; les seconds aspirent à se développer sans les contraintes imposées à posteriori. Le <strong>principe des responsabilités communes mais différenciées</strong>, inscrit dans la CCNUCC, reconnaît cette asymétrie historique mais son application concrète reste disputée.</p>
<p class="resume-text">Les fonds climatiques — Fonds vert pour le climat (FVC), Fonds d'adaptation — sont censés mobiliser des ressources pour aider les pays vulnérables à s'adapter aux changements climatiques et à financer leur transition énergétique. L'engagement des pays développés à mobiliser 100 milliards de dollars par an pour le climat (promesse de Copenhague 2009) n'a été atteint qu'en 2022. Les <strong>pertes et dommages</strong> — compensations pour les impacts climatiques inévitables dans les pays les plus vulnérables — ont été reconnues à la COP27 (2022) avec la création d'un fonds spécifique, marquant une avancée historique.</p>
""",

"traites/droits-de-lhomme": """
<h3>L'architecture universelle des droits humains</h3>
<p class="resume-text">La <strong>Charte internationale des droits de l'homme</strong> comprend trois textes fondamentaux : la Déclaration universelle des droits de l'homme (DUDH, 1948), le Pacte international relatif aux droits civils et politiques (PIDCP, 1966) et le Pacte international relatif aux droits économiques, sociaux et culturels (PIDESC, 1966). Ces deux pactes sont contraignants et créent des mécanismes de contrôle (Comité des droits de l'homme, Comité des droits économiques, sociaux et culturels).</p>
<p class="resume-text">Le système onusien des droits humains comprend également le Conseil des droits de l'homme (CDH, créé en 2006, siège à Genève), qui remplace la Commission des droits de l'homme. Son mécanisme d'<strong>Examen périodique universel</strong> (EPU) soumet tous les États membres de l'ONU à un examen de leurs pratiques tous les 4,5 ans — une innovation importante car elle couvre universellement tous les États, sans exception. Les missions spéciales (rapporteurs spéciaux) enquêtent sur des situations ou thématiques particulières.</p>
<div class="highlight-box"><p>La <strong>Déclaration universelle des droits de l'homme</strong> (10 décembre 1948) a été rédigée en réaction aux atrocités de la Seconde Guerre mondiale. Son adoption fut précédée de négociations intenses entre visions occidentales libérales (droits individuels), soviétique (droits collectifs et économiques) et non-occidentales. En 2018, les Nations Unies ont adopté le Pacte mondial pour les migrations, premier accord intergouvernemental sur la gouvernance des migrations.</p></div>
<h3>Les systèmes régionaux de protection des droits humains</h3>
<p class="resume-text">Les systèmes régionaux offrent souvent une protection plus effective que les mécanismes universels car ils bénéficient d'une plus grande cohésion culturelle et institutionnelle. La <strong>Cour européenne des droits de l'homme</strong> (CEDH, Strasbourg) est le système le plus développé : plus de 800 millions de personnes relevant de sa juridiction, plus de 20 000 arrêts rendus depuis 1959, droit de recours individuel. La CEDH a joué un rôle transformateur sur les législations des États membres (abolition de la peine de mort, droits des détenus, protection des minorités).</p>
<p class="resume-text">La <strong>Cour interaméricaine des droits de l'homme</strong> (CIADH, San José) a développé une jurisprudence pionnière sur les disparitions forcées, les massacres et les droits des peuples autochtones, s'appuyant sur l'expérience des dictatures militaires latino-américaines des années 1970-1980. La <strong>Cour africaine des droits de l'homme et des peuples</strong> (Arusha) est plus récente et son effectivité reste limitée.</p>
""",

"cooperation/mondialisation": """
<h3>Les vagues de la mondialisation</h3>
<p class="resume-text">Les historiens distinguent généralement plusieurs phases de mondialisation. La <strong>première mondialisation</strong> (1870-1914) fut une période d'intégration commerciale et financière intense, portée par la vapeur, le télégraphe et l'étalon-or. Les flux commerciaux représentaient une part du PIB mondial similaire à celle des années 1980. Cette mondialisation fut brutalement interrompue par la Première Guerre mondiale, la Grande Dépression et la Deuxième Guerre mondiale — montrant que la mondialisation n'est pas un processus irréversible.</p>
<p class="resume-text">La <strong>mondialisation contemporaine</strong> (depuis les années 1980) se distingue par plusieurs caractéristiques : la rapidité des flux d'information (internet, communication instantanée), la fragmentation des chaînes de valeur mondiales (une voiture est assemblée avec des composants de 40 pays), la prédominance des services dans les échanges, et la financiarisation de l'économie mondiale (les flux financiers dépassent de très loin les flux commerciaux). Elle est portée par les politiques de libéralisation commerciale, la révolution des technologies de l'information et la baisse des coûts de transport.</p>
<div class="highlight-box"><p>La <strong>grande fragmentation</strong> de l'économie mondiale post-Covid (relocalisation, friendshoring, nearshoring) et les tensions géopolitiques entre États-Unis et Chine menacent de diviser l'économie mondiale en sphères économiques concurrentes — ce que le FMI appelle la <em>geoeconomic fragmentation</em>. Une telle division pourrait coûter jusqu'à 7% du PIB mondial selon certaines estimations.</p></div>
<h3>Les critiques de la mondialisation</h3>
<p class="resume-text">La mondialisation a fait l'objet de critiques vigoureuses depuis les années 1990. Les altermondialistes (Forum social mondial, ATTAC) dénoncent une mondialisation bénéficiant aux multinationales au détriment des travailleurs et des États sociaux. L'économiste Joseph Stiglitz (<em>La grande désillusion</em>, 2002) a critiqué de l'intérieur les politiques d'ajustement structurel du FMI imposées aux pays en développement. Dani Rodrik a formulé le <strong>trilemme de la mondialisation</strong> : on ne peut avoir simultanément une hyper-mondialisation, la démocratie nationale et la souveraineté nationale — il faut choisir deux des trois.</p>
<p class="resume-text">Les études économiques montrent que si la mondialisation a réduit la pauvreté absolue dans les pays émergents (notamment en Chine et en Asie du Sud-Est) et baissé les prix à la consommation pour les ménages aisés des pays développés, elle a aussi contribué à l'augmentation des inégalités au sein des pays riches, en désindustrialisant des régions entières (Rust Belt américaine, bassins industriels européens). Ce backlash social a alimenté les populismes nationalistes et eurosceptiques des années 2010.</p>
""",

"cooperation/institutions-financieres": """
<h3>Le FMI et la Banque mondiale : origines et missions</h3>
<p class="resume-text">Le <strong>FMI</strong> et la <strong>Banque mondiale</strong> ont été créés à la <strong>Conférence de Bretton Woods</strong> (juillet 1944) pour construire un ordre économique international stable après la catastrophe de la Grande Dépression et de la Seconde Guerre mondiale. Le FMI devait assurer la stabilité du système monétaire international (taux de change fixes ajustables, convertibilité des monnaies) et fournir des crédits à court terme aux pays en difficulté de balance des paiements. La Banque internationale pour la reconstruction et le développement (BIRD, bras de la Banque mondiale) devait financer la reconstruction européenne puis le développement des pays pauvres.</p>
<p class="resume-text">La fin du système de Bretton Woods (1971, Nixon suspendant la convertibilité du dollar en or) n'a pas entraîné la disparition du FMI, qui s'est réinventé. Depuis les années 1980, il s'est spécialisé dans la gestion des crises financières des pays en développement, en accordant des prêts conditionnels à des programmes d'ajustement structurel (privatisation, déréglementation, rigueur budgétaire). Ces programmes, fondés sur le « Consensus de Washington », ont été très contestés pour leur impact social et leur uniformité.</p>
<div class="highlight-box"><p>Les <strong>droits de tirage spéciaux</strong> (DTS) du FMI sont une monnaie internationale de réserve créée en 1969. Leur valeur est calculée sur un panier de cinq monnaies (dollar, euro, yuan, yen, livre sterling). En 2021, pour répondre à la crise du Covid, le FMI a alloué 650 milliards de dollars de DTS à ses membres — la plus grande création monétaire internationale de l'histoire.</p></div>
<h3>Les nouvelles institutions financières internationales</h3>
<p class="resume-text">L'ascension de la Chine et des BRICS a conduit à la création d'institutions financières alternatives. La <strong>Nouvelle Banque de développement</strong> (NBD, 2015) des BRICS (Brésil, Russie, Inde, Chine, Afrique du Sud) est conçue comme une alternative à la Banque mondiale, sans conditionnalité de gouvernance. La <strong>Banque asiatique d'investissement dans les infrastructures</strong> (AIIB, 2016), initiée par la Chine avec 105 membres, finance les projets d'infrastructure en Asie et au-delà. Ces institutions reflètent le souhait des puissances émergentes de réformer la gouvernance économique mondiale qui reste dominée par les occidentaux dans les institutions de Bretton Woods.</p>
<p class="resume-text">Le <strong>G20</strong>, créé en 1999 au niveau des ministres des finances puis hissé au niveau des chefs d'État lors de la crise de 2008, est devenu le principal forum de coordination économique mondiale, remplaçant le G7/G8 comme instance de gouvernance économique globale. Il réunit les 20 pays les plus importants économiquement, représentant 85% du PIB mondial, 75% des échanges commerciaux et les deux tiers de la population mondiale. La coordination du G20 lors de la crise financière de 2008-2009 (stimulus budgétaires coordonnés, renforcement des fonds propres des banques) est considérée comme un succès de la gouvernance économique mondiale.</p>
""",

"cooperation/developpement-international": """
<h3>Les théories du développement et leur évolution</h3>
<p class="resume-text">La théorie du développement a connu plusieurs révolutions paradigmatiques depuis 1945. La <strong>modernisation</strong> (Rostow, <em>Les étapes de la croissance économique</em>, 1960) voyait le développement comme un processus linéaire d'imitation des sociétés industrialisées occidentales. La <strong>théorie de la dépendance</strong> (Prebisch, Frank, Cardoso), développée en Amérique latine dans les années 1960-1970, renversait cette analyse : le sous-développement n'est pas un retard mais le résultat de l'intégration périphérique dans un capitalisme mondial inégal qui transfère les richesses du Sud vers le Nord.</p>
<p class="resume-text">Le <strong>Consensus de Washington</strong> (Washington Consensus), formulé en 1989 par l'économiste John Williamson, recommandait dix mesures libérales aux pays en développement : rigueur budgétaire, privatisation, libéralisation commerciale, déréglementation. Ces prescriptions du FMI et de la Banque mondiale ont dominé les années 1990 et ont été vigoureusement critiquées après les crises asiatique et argentine. L'<strong>approche par les capacités</strong> d'Amartya Sen (<em>Development as Freedom</em>, 1999) a renouvelé la réflexion en définissant le développement non comme la croissance du PIB mais comme l'expansion des libertés réelles des individus.</p>
<div class="highlight-box"><p>Les <strong>Objectifs du Millénaire pour le développement</strong> (OMD, 2000-2015) ont été partiellement atteints : la pauvreté extrême a été réduite de moitié, la mortalité infantile a diminué des deux tiers. Leurs successeurs, les <strong>Objectifs de développement durable</strong> (ODD, 2015-2030), définissent 17 objectifs et 169 cibles pour un développement « durable, inclusif et universel » — s'appliquant aux pays riches comme aux pays pauvres.</p></div>
<h3>Les acteurs du développement international</h3>
<p class="resume-text">Le paysage de l'aide au développement s'est considérablement diversifié. Aux acteurs traditionnels (Banque mondiale, FAO, PNUD, bilatéraux comme l'AFD française ou USAID américain), se sont ajoutés des fondations philanthropiques (Bill & Melinda Gates Foundation, dont le budget dépasse celui de l'OMS), des fonds émergents des pays BRICS, des ONG opérationnelles et des entreprises privées investissant dans le développement. Cette pluralité crée des risques de fragmentation et de manque de coordination mais aussi une plus grande variété d'approches.</p>
<p class="resume-text">L'<strong>efficacité de l'aide</strong> est débattue depuis les travaux de William Easterly (<em>Les illusions de l'aide occidentale</em>, 2006) qui critique l'aide top-down planifiée, et de Dambisa Moyo (<em>L'aide fatale</em>, 2009) qui soutient que l'aide crée des dépendances et sape le développement endogène. Leurs thèses sont contestées par des chercheurs comme Jeffrey Sachs ou par les études d'impact d'Abhijit Banerjee et Esther Duflo (Prix Nobel 2019) qui montrent l'efficacité d'interventions ciblées et évaluées rigoureusement (éducation, vaccins, transferts monétaires conditionnels).</p>
""",

"cooperation/geopolitique-de-lenergie": """
<h3>L'OPEP et la géopolitique du pétrole</h3>
<p class="resume-text">L'<strong>OPEP</strong> (Organisation des pays exportateurs de pétrole, fondée en 1960) regroupe aujourd'hui 13 membres (Arabie Saoudite, Iran, Iraq, Koweït, Venezuela, etc.) auxquels s'ajoutent les membres de l'<strong>OPEP+</strong> (dont la Russie, le Kazakhstan, le Mexique). Ensemble, ils contrôlent environ 80% des réserves prouvées mondiales de pétrole et 40% de la production. Les décisions de l'OPEP sur les quotas de production ont des effets immédiats sur les prix mondiaux du pétrole et donc sur l'économie mondiale.</p>
<p class="resume-text">Le <strong>choc pétrolier de 1973</strong> (embargo arabe après la guerre du Kippour) a quadruplé les prix du pétrole en quelques mois, provoquant la première grande récession de l'après-guerre en Occident et déclenchant une révolution dans la politique énergétique (économies d'énergie, nucléaire, recherche de sources alternatives). Il a montré que l'énergie était une arme géopolitique majeure. La « malédiction des ressources » (resource curse) — le paradoxe par lequel l'abondance de ressources naturelles est souvent associée à la faiblesse des institutions démocratiques et au sous-développement économique — a été theorisée après ces crises.</p>
<div class="highlight-box"><p>Le <strong>gaz naturel</strong> est devenu un enjeu géopolitique central en Europe après l'invasion russe de l'Ukraine. L'Allemagne, dépendante à 55% du gaz russe, a dû opérer une révolution énergétique express (Energiewende accélérée), construire des terminaux GNL en urgence et diversifier ses approvisionnements. Cette crise a démontré les risques de la dépendance énergétique à l'égard d'un pays hostile.</p></div>
<h3>La transition énergétique et ses enjeux géopolitiques</h3>
<p class="resume-text">La transition vers les énergies renouvelables crée de nouvelles géographies de puissance énergétique. Si elle réduit la dépendance aux hydrocarbures fossiles concentrés dans quelques régions (Moyen-Orient, Russie), elle crée de nouvelles dépendances aux <strong>métaux critiques</strong> : lithium (Bolivie, Chili, Argentine — le « triangle du lithium »), cobalt (République démocratique du Congo — 70% des réserves mondiales), terres rares (Chine — 85% de la production mondiale). La compétition pour ces ressources est en train de devenir un nouvel axe de la géopolitique mondiale.</p>
<p class="resume-text">La <strong>Chine</strong> a pris une avance considérable dans les industries des énergies renouvelables : premier producteur de panneaux solaires, d'éoliennes et de batteries pour véhicules électriques. Cette domination industrielle lui confère une influence croissante dans la transition énergétique mondiale. En réponse, les États-Unis (Inflation Reduction Act, 2022) et l'Union européenne (Green Deal, Net-Zero Industry Act) déploient des politiques industrielles massives pour développer leurs capacités domestiques dans les technologies vertes — créant des tensions commerciales au sein du bloc occidental.</p>
""",

"cooperation/gouvernance-mondiale": """
<h3>La crise de la gouvernance mondiale</h3>
<p class="resume-text">La <strong>gouvernance mondiale</strong> désigne l'ensemble des mécanismes formels et informels par lesquels les acteurs internationaux coordonnent leurs comportements face aux problèmes globaux. Elle repose sur un réseau complexe d'institutions internationales, de traités, de normes et de pratiques diplomatiques. Ce système, construit après 1945 sous hégémonie américaine, fait face depuis les années 2000 à une crise de légitimité et d'efficacité.</p>
<p class="resume-text">Plusieurs facteurs alimentent cette crise. La <strong>montée des puissances non occidentales</strong> (Chine, Inde, Brésil, Turquie) qui ne se reconnaissent pas dans des institutions qui leur accordent une représentation insuffisante et reflètent des valeurs qu'elles ne partagent pas toutes. Le <strong>retour du nationalisme</strong> dans des démocraties établies (Brexit, populisme américain, euroscepticisme). L'<strong>émergence de problèmes transnationaux</strong> (changement climatique, pandémies, cybersécurité, migrations) qui dépassent les capacités des institutions existantes et exigent une coopération que les États peinent à fournir.</p>
<div class="highlight-box"><p>Le <strong>Sommet pour l'avenir</strong> de l'ONU (septembre 2024) a tenté d'adopter un Pacte pour l'avenir réformant la gouvernance mondiale pour le XXIe siècle. Ses principaux chantiers : réforme du Conseil de sécurité (pour mieux représenter l'Afrique, l'Asie et l'Amérique latine), renforcement de la gouvernance numérique mondiale, et mécanismes de financement climatique. Ces réformes se heurtent aux résistances des puissances établies soucieuses de préserver leurs positions.</p></div>
<h3>Les propositions de réforme de la gouvernance mondiale</h3>
<p class="resume-text">De nombreuses réformes de la gouvernance mondiale sont proposées. La <strong>réforme du Conseil de sécurité</strong> est réclamée depuis les années 1990 : le G4 (Allemagne, Japon, Inde, Brésil) plaide pour des sièges permanents supplémentaires. L'Afrique demande deux sièges permanents (positions d'Ezulwini). Les États-Unis et la Chine s'y opposent de facto. La réforme des institutions de Bretton Woods pour mieux représenter les pays émergents progresse lentement : la Chine est devenue le troisième plus grand actionnaire du FMI et de la Banque mondiale, reflétant son poids économique croissant.</p>
<p class="resume-text">Des propositions plus ambitieuses évoquent une <strong>Assemblée parlementaire aux Nations Unies</strong> (APNU) qui représenterait directement les peuples plutôt que les gouvernements, ou un <strong>Parlement mondial</strong>. D'autres plaident pour renforcer le rôle des villes dans la gouvernance mondiale (le C40 des grandes métropoles pour le climat), ou pour une <strong>gouvernance de l'internet</strong> plus multilatérale face à la domination des entreprises américaines et chinoises. Ces propositions peinent à se concrétiser face aux résistances des États soucieux de leur souveraineté, mais elles alimentent un débat intellectuel fécond sur l'avenir de l'ordre international.</p>
""",
}

def enrich_page(content, extra_html):
    idx = content.rfind('</section>')
    if idx == -1:
        return content + extra_html
    return content[:idx] + extra_html + content[idx:]

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

enriched = 0
for key, extra in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        original_len = len(page['content'])
        page['content'] = enrich_page(page['content'], extra)
        new_len = len(page['content'])
        print(f'  {key}: {original_len} -> {new_len} chars')
        enriched += 1

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'\nEnriched {enriched} articles.')
