#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement des articles de la discipline Agriculture."""

import json, re

FILE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/agriculture.json"

ENRICHMENTS = {
"agronomie/science-du-sol": """
<h3>La classification mondiale des sols : diversité et répartition</h3>
<p class="resume-text">Les sols sont extraordinairement diversifiés à l'échelle planétaire. La classification internationale WRB (World Reference Base for Soil Resources) reconnaît 32 groupes de référence principaux. Les Ferralsols, sols des régions tropicales humides altérés sur des millions d'années, sont riches en oxydes de fer et d'aluminium mais pauvres en nutriments disponibles — paradoxalement, les forêts les plus productives du monde (Amazonie, Congo) poussent sur ces sols peu fertiles. Les Chernozems, terres noires d'Ukraine et d'Amérique du Nord, sont les plus fertiles : leur horizon humifère peut atteindre 1 à 1,5 mètre d'épaisseur, contenant 10 à 16 % de matière organique accumulée sous les steppes depuis l'ère glaciaire.</p>
<p class="resume-text">Les Podzols des régions boréales se forment sous conifères : l'acidité produit un lessivage intense qui crée un horizon blanchi cendré caractéristique. Les Vertisols argileux, fréquents dans les régions semi-arides, se crevassent profondément en saison sèche et se gonflent en saison humide, rendant leur travail mécanique difficile mais garantissant un auto-mélange (pédoturbation). Les Histosols ou tourbières sont des sols organiques exceptionnels qui stockent deux fois plus de carbone que toutes les forêts du monde réunies, sur seulement 3 % des terres émergées.</p>
<div class="highlight-box"><p>Les Chernozems d'Ukraine et de Russie (la "ceinture noire") produisent environ 25 % du blé exporté mondialement. Ces sols sont tellement précieux que lors des invasions napoléoniennes, certains témoignages rapportent que les soldats en emportaient dans leurs bottes comme souvenir — et des écrivains ukrainiens modernes ont documenté que, pendant la guerre en Ukraine (2022), les envahisseurs auraient littéralement volé de la terre fertile par camions entiers.</p></div>

<h3>Microbiologie des sols : la vie invisible qui nourrit les plantes</h3>
<p class="resume-text">Le réseau trophique du sol est d'une complexité fascinante. Un gramme de sol sain contient environ 1 milliard de bactéries appartenant à 10 000 espèces différentes, 100 000 champignons, 10 000 protozoaires et 1 000 nématodes. Les bactéries fixatrices d'azote — Rhizobium en symbiose avec les légumineuses, Azotobacter et Azospirillum en vie libre — convertissent l'azote atmosphérique (N₂) en ammoniac (NH₃) assimilable par les plantes, fournissant gratuitement ce que l'industrie des engrais produit à grand coût d'énergie.</p>
<p class="resume-text">Les mycorhizes — symbioses entre champignons et racines végétales — sont l'une des associations les plus anciennes et importantes de la biosphère terrestre (elles ont facilité la colonisation des terres émergées par les plantes il y a 450 millions d'années). Les filaments fongiques (hyphes) étendent considérablement le réseau de prélèvement des racines : elles peuvent accéder à des pores du sol trop petits pour les radicelles, et fonctionnent comme un "internet du sol" connectant différentes plantes entre elles et permettant des échanges de nutriments et même de signaux d'alarme. Les plantes qui bénéficient de mycorhizes sont généralement plus résistantes à la sécheresse, aux maladies et aux métaux lourds.</p>
<div class="highlight-box"><p>Les pesticides fongicides et certains herbicides (notamment le glyphosate) ont un impact négatif sur les champignons mycorhiziens du sol. Des méta-analyses montrent que les parcelles en agriculture conventionnelle intensive contiennent en moyenne 50 % moins de biomasse fongique que les parcelles en agriculture biologique voisines — avec des conséquences potentielles sur la disponibilité des nutriments et la résistance aux maladies racinaires.</p></div>
""",

"agronomie/nutrition-des-plantes": """
<h3>Les éléments nutritifs essentiels : macroéléments et microéléments</h3>
<p class="resume-text">Les plantes ont besoin de 17 éléments essentiels pour compléter leur cycle de vie. Les macroéléments (nécessaires en grandes quantités) comprennent : l'azote (N), constituant des protéines, des acides nucléiques et de la chlorophylle ; le phosphore (P), indispensable aux transferts d'énergie (ATP, ADP) et aux membranes cellulaires (phospholipides) ; le potassium (K), régulateur de l'ouverture des stomates et de la turgescence cellulaire ; le calcium (Ca), composant des parois cellulaires et second messager ; le magnésium (Mg), atome central de la molécule de chlorophylle ; et le soufre (S), constituant de certains acides aminés (cystéine, méthionine).</p>
<p class="resume-text">Les microéléments (nécessaires en infimes quantités mais indispensables) incluent le fer (Fe), cofacteur de nombreuses enzymes et de la synthèse de chlorophylle ; le manganèse (Mn) et le zinc (Zn), cofacteurs enzymatiques ; le bore (B), essentiel à la formation des parois et à la reproduction ; le cuivre (Cu), composant de plastocyanine dans la photosynthèse ; le molybdène (Mo), cofacteur des nitrogénases et nitrate-réductases ; et le chlore (Cl), impliqué dans la photosynthèse. Les carences en l'un quelconque de ces éléments se manifestent par des symptômes spécifiques reconnaissables à la couleur, à la forme et à la distribution des lésions foliaires.</p>
<div class="highlight-box"><p>La loi du minimum de Liebig (1840) stipule que la croissance des plantes est limitée non par la ressource la plus abondante, mais par la ressource la plus rare. Si le phosphore disponible est insuffisant, même un sol riche en azote ne permettra pas une croissance optimale — d'où l'importance d'une fertilisation équilibrée plutôt que simplement abondante.</p></div>

<h3>Cycles biogéochimiques agricoles : azote et phosphore</h3>
<p class="resume-text">Le cycle de l'azote est fondamental pour l'agriculture : l'azote atmosphérique (78 % de l'air) est inaccessible aux plantes supérieures. Il doit être fixé biologiquement (par les bactéries) ou industriellement (procédé Haber-Bosch) en ammoniaque, puis nitrité et nitrate par nitrification bactérienne, absorbé par les plantes, et retourné au sol par décomposition des matières organiques ou par dénitrification (retour à N₂). Le développement des engrais azotés synthétiques depuis les années 1950 a permis de multiplier les rendements agricoles, mais crée aussi une "fuite d'azote" massive : nitrates dans les nappes, protoxyde d'azote (N₂O, puissant GES) dans l'atmosphère, eutrophisation des eaux.</p>
<p class="resume-text">Le cycle du phosphore est différent : contrairement à l'azote, il n'existe pas de réservoir atmosphérique. Le phosphore mined des roches sédimentaires (phosphorites) est utilisé comme engrais, absorbé partiellement par les plantes, et pour une grande partie, il se retrouve dans les rivières et les océans où il précipite dans les sédiments — un cycle extrêmement lent. Les réserves mondiales de phosphate minérable, concentrées principalement au Maroc (qui détient 70 % des réserves mondiales), sont finies. La récupération du phosphore à partir des eaux usées et du compost devient une priorité agronomique pour l'agriculture durable du XXIe siècle.</p>
<div class="highlight-box"><p>Le procédé Haber-Bosch, qui synthétise industriellement l'ammoniaque à partir de l'azote atmosphérique (N₂ + 3H₂ → 2NH₃), consomme environ 1 à 2 % de l'énergie mondiale et émet environ 450 Mt de CO₂ par an. Pourtant, il permet de nourrir environ 4 milliards de personnes supplémentaires par rapport à ce que l'agriculture naturelle pourrait supporter — on estime que sans engrais de synthèse, la population mondiale supportable serait d'environ 4 milliards d'habitants.</p></div>

<h3>Stratégies de fertilisation durable : diagnostic et précision</h3>
<p class="resume-text">La fertilisation de précision cherche à apporter les bons nutriments, aux bonnes doses, au bon moment et au bon endroit. Les analyses de sol, réalisées par prélèvement et analyse en laboratoire, donnent un état des stocks nutritifs et permettent de raisonner les apports. Les outils de l'agriculture de précision — capteurs NDVI (Indice de Végétation par Différence Normalisée) embarqués sur drones ou satellites, capteurs de chlorophylle, analyses foliaires — permettent de moduler les apports à l'échelle infra-parcellaire, réduisant les pertes par lessivage et les coûts.</p>
<p class="resume-text">Les sources organiques d'azote (fumier, compost, engrais verts, lisier) libèrent les nutriments progressivement par minéralisation microbienne, réduisant les risques de lessivage comparativement aux engrais minéraux solubles. Les légumineuses (luzerne, trèfle, soja, pois) fixent l'azote atmosphérique gratuitement via leurs symbioses avec Rhizobium et peuvent enrichir le sol de 50 à 300 kg N/ha/an. La biofumigation — incorporation de crucifères riches en glucosinolates comme engrais verts — libère des composés soufrés qui inhibent certains pathogènes du sol (nématodes, champignons), réduisant le besoin en pesticides.</p>
<div class="highlight-box"><p>La directive européenne Nitrates (1991) impose des restrictions sur l'épandage des engrais azotés dans les "zones vulnérables" pour protéger les eaux souterraines. En Bretagne, région d'élevage intensif, les nitrates ont contaminé de nombreuses nappes phréatiques et provoqué des phénomènes d'algues vertes sur les côtes — un exemple emblématique des effets non désirés de la fertilisation intensive sans gestion des pertes.</p></div>
""",

"agronomie/rotations-et-assolements": """
<h3>Histoire des rotations culturales : de l'assolement médiéval à l'agronomie moderne</h3>
<p class="resume-text">Les rotations culturales ont une longue histoire. Le système d'assolement triennal médiéval, généralisé en Europe du Nord à partir du VIIIe siècle, divise les terres en trois parties : blé d'hiver, culture de printemps (orge, avoine), jachère. Ce système permettait de maintenir la fertilité des terres tout en assurant une production régulière. La jachère, parfois décriée comme improductive, avait une double fonction essentielle : laisser le sol se recharger en azote par l'activité bactérienne et interrompre les cycles des maladies et ravageurs.</p>
<p class="resume-text">La révolution agricole du XVIIIe siècle, initiée en Angleterre, a introduit la rotation Norfolk (blé — navet — orge — trèfle), qui supprime la jachère en la remplaçant par des cultures améliorantes. Le trèfle enrichit le sol en azote ; le navet fournit de la nourriture pour le bétail en hiver, dont le fumier enrichit à son tour le sol. Cette rotation, diffusée par des pionniers comme Jethro Tull et Lord Townshend, a permis des augmentations spectaculaires de rendements et l'essor de l'élevage en confinement hivernal.</p>
<div class="highlight-box"><p>La monoculture de maïs intensive pratiquée dans la "corn belt" américaine a conduit à une recrudescence de la chrysomèle des racines du maïs (Diabrotica virgifera), un ravageur dont la larve s'attaque aux racines. L'adoption d'une simple rotation maïs-soja a presque éliminé ce problème sans insecticide — illustrant le pouvoir des rotations comme outil de gestion intégrée des ravageurs.</p></div>

<h3>Les effets biochimiques et biologiques des rotations</h3>
<p class="resume-text">Les rotations culturales exercent des effets complexes sur la biologie du sol. L'alternance d'espèces végétales aux rhizodépôts (sécrétions racinaires) différents modifie les communautés microbiennes du sol. Certaines séquences culturales favorisent la suppression biologique des pathogènes : des sols cultivés en blé pendant plusieurs années développent une "suppressivité" naturelle contre le piétin-échaudage (Gaeumannomyces graminis) — les bactéries productrices d'antibiotiques (Pseudomonas fluorescens) prolifèrent en réponse aux glucosinolates libérés par la plante malade.</p>
<p class="resume-text">La diversité des résidus de récolte apportés par des espèces différentes enrichit la faune du sol : les vers de terre prolifèrent avec les légumineuses (riches en protéines), les collemboles et acariens avec les céréales (riches en lignine). Cette diversité biologique améliore la structure du sol, sa capacité de rétention en eau et sa résistance à l'érosion. Des études à long terme (Rothamsted, Angleterre, depuis 1843 ; Versailles, France) ont mesuré ces effets sur plus d'un siècle, montrant que les rotations maintiennent mieux la matière organique que les monocultures même fertilisées.</p>
<div class="highlight-box"><p>Les cultures de couverture hivernales (moutarde, phacélie, avoine, vetch), semées après récolte pour couvrir le sol pendant la période froide, réduisent le lessivage des nitrates de 50 à 80 %, limitent l'érosion, maintiennent l'activité biologique du sol et fournissent un couvert végétal pour la faune. En France, les couverts végétaux sont obligatoires entre deux cultures principales dans les zones vulnérables nitrates depuis 2012.</p></div>

<h3>Rotations et gestion des adventices sans herbicides</h3>
<p class="resume-text">Les adventices (mauvaises herbes) s'adaptent aux systèmes culturaux répétitifs : les populations de vulpin des champs (Alopecurus myosuroides) et de ray-grass anglais (Lolium perenne) résistants aux herbicides se sont développées dans les systèmes de monoculture de céréales d'hiver d'Europe du Nord. Les rotations brisent les cycles des adventices en alternant des cultures d'hiver et de printemps (avec des fenêtres de désherbage mécanique différentes), des espèces couvrantes et peu couvrantes, des cultures hautes et basses.</p>
<p class="resume-text">La rotation avec des légumineuses à croissance dense (luzerne, soja, pois) ombrage efficacement le sol, réduisant la germination des adventices sensibles à la lumière. Le labour, traditionnellement utilisé pour enfouir les graines d'adventices, peut être partiellement remplacé par des rotations bien conçues incluant des cultures couvrantes étouffantes. Dans les systèmes de production biologique sans herbicides chimiques, la conception des rotations pour la gestion des adventices est souvent la compétence technique la plus critique.</p>
<div class="highlight-box"><p>Une étude comparative de 24 ans à Iowa State University (Régime d'eau et de sol, Marsden Farm) a montré que des rotations longues de 3 et 4 cultures nécessitant peu ou pas d'herbicides ont produit des rendements équivalents aux rotations maïs-soja standard, tout en réduisant les pertes en nitrates de 40 %, la consommation d'herbicides de 90 % et les coûts de production de 30 %.</p></div>
""",

"agronomie/protection-des-cultures": """
<h3>Les principaux bioagresseurs des cultures : identification et cycles</h3>
<p class="resume-text">Les cultures agricoles font face à un vaste éventail de bioagresseurs. Les champignons pathogènes sont responsables de la majorité des maladies des plantes : la rouille du blé (Puccinia triticina), le mildiou de la vigne et de la pomme de terre (Plasmopara viticola, Phytophthora infestans), la septoriose du blé (Zymoseptoria tritici) et le botrytis (Botrytis cinerea). Ces pathogènes ont causé des catastrophes historiques : la famine irlandaise de 1845-1852, déclenchée par l'attaque du mildiou (Phytophthora infestans) sur les pommes de terre, a tué environ un million de personnes et poussé un autre million à émigrer.</p>
<p class="resume-text">Les insectes ravageurs combinent des dommages directs (défoliation, succion de sève, galeries dans les fruits) et indirects (transmission de virus végétaux par les pucerons et cicadelles). Les nématodes parasites des racines (Meloidogyne spp.) causent des dommages difficiles à détecter jusqu'à la récolte, réduisant les rendements de 5 à 20 % selon les cultures. Les rongeurs (campagnols des champs, mulots) et les oiseaux causent des pertes significatives dans certaines cultures. La résistance génétique aux bioagresseurs, intégrée dans les variétés via la sélection, est la première ligne de défense et la plus économique.</p>
<div class="highlight-box"><p>La rouille Ug99 (Puccinia graminis f. sp. tritici race TTKSK), identifiée en Ouganda en 1999, est une souche de rouille du blé capable de contourner 80 % des gènes de résistance présents dans les variétés mondiales. Son expansion potentielle vers les grands bassins producteurs d'Asie et d'Europe représente l'une des plus grandes menaces pour la sécurité alimentaire mondiale, mobilisant un effort international de sélection variétale d'urgence.</p></div>

<h3>Pesticides : modes d'action, risques et résistances</h3>
<p class="resume-text">Les pesticides sont classés selon leur cible (insecticides, fongicides, herbicides, nématicides, rodenticides) et leur mode d'action biochimique. Les organophosphorés et carbamates (insecticides) inhibent l'acétylcholinestérase, enzyme essentielle à la transmission nerveuse. Les néonicotinoïdes (imidaclopride, thiaméthoxame) se lient aux récepteurs nicotiniques de l'acétylcholine des insectes, causant une stimulation nerveuse permanente puis la mort. Leur persistance dans le sol et leur présence dans le pollen et le nectar des fleurs ont été liées aux effondrements de colonies d'abeilles (Colony Collapse Disorder), conduisant à leur interdiction en Europe pour les cultures en plein champ depuis 2018.</p>
<p class="resume-text">La résistance aux pesticides est une évolution rapide : quand un pesticide élimine 99,9 % d'une population, les 0,1 % résistants se reproduisent librement, transmettant leurs gènes de résistance. Des populations de doryphores résistants à tous les insecticides autorisés existent déjà dans certaines régions. L'ambroisie à feuilles d'armoise (Ambrosia artemisiifolia) est une adventice envahissante résistante à plusieurs herbicides en Europe. La gestion de la résistance implique la rotation des modes d'action, l'utilisation des seuils économiques de nuisibilité (ne traiter que si le risque économique dépasse le coût du traitement) et l'intégration de méthodes alternatives.</p>
<div class="highlight-box"><p>Le glyphosate (Roundup), herbicide le plus vendu au monde, est au cœur d'un débat scientifique et juridique intense : le CIRC (Centre international de Recherche sur le Cancer) l'a classé "probablement cancérogène pour l'homme" en 2015, tandis que l'EFSA (Autorité européenne de sécurité alimentaire) et l'EPA américaine concluent qu'il est sans risque aux doses d'exposition normales. Des milliers de procès aux États-Unis ont abouti à des condamnations de Bayer (propriétaire de Monsanto) pour des milliards de dollars.</p></div>

<h3>Protection intégrée des cultures (PIC) : combiner les méthodes</h3>
<p class="resume-text">La protection intégrée des cultures (PIC ou IPM) est une approche qui combine toutes les méthodes disponibles de gestion des bioagresseurs — biologiques, culturales, mécaniques, génétiques et chimiques (en dernier recours) — pour maintenir les populations de nuisibles sous les seuils économiques de nuisibilité, tout en minimisant les risques pour la santé humaine et l'environnement. Elle repose sur la surveillance régulière des parcelles (comptages d'insectes, notations de maladies), la connaissance des biologies des bioagresseurs et l'utilisation des seuils de traitement.</p>
<p class="resume-text">La lutte biologique est un pilier de la PIC : introduction ou conservation de prédateurs et parasitoïdes naturels des ravageurs. Le trichogramme (Trichogramma spp.), un micro-hyménoptère parasitoïde des œufs de lépidoptères ravageurs, est l'un des auxiliaires les plus utilisés au monde, notamment contre la pyrale du maïs en Europe. Les lâchers de Bacillus thuringiensis (Bt), bactérie produisant des protéines insecticides spécifiques, sont utilisés en agriculture biologique contre les chenilles. La confusion sexuelle utilise des diffuseurs de phéromones synthétiques pour perturber l'accouplement des tordeuses et cochenilles dans les vergers.</p>
<div class="highlight-box"><p>En France, le plan Ecophyto, lancé en 2008 suite au Grenelle de l'Environnement, visait à réduire l'utilisation des pesticides de 50 % en 10 ans. Malgré plusieurs révisions, les objectifs n'ont pas été atteints : l'utilisation a même augmenté certaines années. Cette difficile transition illustre la complexité du changement de pratiques agricoles face aux pressions économiques, climatiques (mauvaises années sanitaires) et sociales.</p></div>
""",

"agronomie/agriculture-de-precision": """
<h3>Technologies de positionnement et de cartographie : le GPS au service des champs</h3>
<p class="resume-text">L'agriculture de précision repose sur des technologies de localisation et de cartographie qui permettent de connaître la variabilité spatiale des parcelles. Le GPS (Global Positioning System), rendu accessible aux agriculteurs dans les années 1990 (la précision civile a été améliorée de 100 m à 1-3 m en 2000 avec la désactivation de la "disponibilité sélective" par les États-Unis), a ouvert la voie aux autoguidages des tracteurs. Aujourd'hui, le guidage centimétrique RTK (Real-Time Kinematic) permet à un tracteur de suivre un itinéraire précis à 2-3 cm près, améliorant la qualité du travail (semis alignés, réduction des chevauchements et des manques) et diminuant la fatigue du conducteur.</p>
<p class="resume-text">La cartographie de variabilité des sols est l'étape fondatrice : conductivité électromagnétique des sols (appareil EM38, qui mesure la teneur en argile, en eau et en matière organique sans contact), analyses de sol géoréférencées (une analyse tous les 2 ha), mesure du potentiel d'oxydo-réduction des sols inondés. Ces cartes révèlent les hétérogénéités des parcelles, permettant de moduler les semences, les fertilisants et les traitements selon les zones. Une parcelle apparemment homogène peut cacher une variabilité importante en potentiel agronomique.</p>
<div class="highlight-box"><p>Les drones agricoles ont connu une adoption rapide depuis 2015 : équipés de capteurs multispectraux (visible, proche infrarouge, thermique), ils permettent de cartographier l'état sanitaire des cultures, de détecter les zones de stress hydrique ou nutritionnel, de mesurer la biomasse et les rendements prévisionnels. En Chine, les drones sont devenus le principal mode d'application des traitements phytosanitaires dans les rizières — plus de 200 000 drones agricoles y sont en service.</p></div>

<h3>Capteurs, données et intelligence artificielle : la ferme connectée</h3>
<p class="resume-text">L'internet des objets (IoT) agricole se développe rapidement : des capteurs autonomes mesurent en continu l'humidité du sol à plusieurs profondeurs, la température, le pH, les teneurs en nitrates. Des stations météorologiques connectées fournissent des données locales indispensables aux modèles de prévision des maladies. Ces données, collectées en temps réel et transmises via les réseaux cellulaires ou LoRaWAN (réseau basse consommation longue portée), permettent une irrigation de précision (uniquement quand et où le sol est sec), réduisant la consommation d'eau de 30 à 50 % dans les systèmes d'irrigation par goutte-à-goutte.</p>
<p class="resume-text">L'intelligence artificielle transforme l'analyse des données agronomiques. Des modèles de machine learning entraînés sur des millions d'images peuvent identifier avec précision les maladies des plantes à partir de photos de smartphones (applications comme PlantVillage, développée par la Penn State University, est utilisée par des millions d'agriculteurs en Afrique subsaharienne). Des algorithmes d'apprentissage profond analysent des images satellites pour estimer les rendements avant récolte, gérer des flottes de robots désherbeurs autonomes, ou prévoir les besoins en intrants à l'échelle d'un bassin versant.</p>
<div class="highlight-box"><p>Le "robot désherbeur" Dino, développé par la startup française Naio Technologies, utilise la vision par ordinateur et la GPS pour identifier et sarcler mécaniquement les adventices entre les rangs de légumes en plein champ, sans produits chimiques. Ce type de robot, représentatif d'une nouvelle génération d'outils de l'agriculture de précision, réduit la pénibilité du travail agricole tout en répondant aux exigences croissantes de réduction des herbicides.</p></div>

<h3>Modulation intra-parcellaire : appliquer moins pour produire mieux</h3>
<p class="resume-text">La modulation intra-parcellaire (VRT, Variable Rate Technology) consiste à faire varier les doses d'intrants (semences, engrais, pesticides) selon la position GPS dans la parcelle, en fonction des cartes de variabilité préalablement établies. Une zone de sol profond et fertile recevra moins d'engrais qu'une zone superficielle ; une zone avec historique de maladies racinaires pourra être protégée par un fongicide de sol à dose plus élevée ; une zone plus argileuse sera semée moins dense pour éviter la compétition excessive entre plants.</p>
<p class="resume-text">La pulvérisation localisée (spot spraying) est l'une des applications les plus prometteuses : au lieu d'épandre des herbicides sur toute la parcelle, des capteurs optiques (ou la vision par ordinateur) détectent en temps réel les adventices et déclenchent la pulvérisation uniquement là où elles se trouvent. La startup australienne See and Spray (rachetée par John Deere), puis plusieurs concurrents européens, ont développé des barres de pulvérisation équipées de caméras et d'IA capables de réduire la consommation d'herbicides de 70 à 90 % comparativement à un traitement total de la parcelle.</p>
<div class="highlight-box"><p>L'agriculture de précision n'est pas réservée aux grandes exploitations : des outils simples comme les outils de gestion des intrants par cartes de prescription, les applications de diagnostic de maladies par smartphone, et les prévisions météo locales améliorées sont accessibles à des petits agriculteurs dans le monde entier. Des projets pilotes en Éthiopie et au Kenya montrent des augmentations de rendements de 20 à 30 % avec des interventions simples de précision.</p></div>
""",

"permaculture/fondements-de-la-permaculture": """
<h3>Les origines intellectuelles : de Bill Mollison à David Holmgren</h3>
<p class="resume-text">La permaculture est née en Australie dans les années 1970, de la rencontre intellectuelle entre Bill Mollison, enseignant en psychologie environnementale à l'Université de Tasmanie, et David Holmgren, son étudiant en design paysager. Leur livre fondateur, "Permaculture One" (1978), proposait un système de design pour créer des environnements humains productifs et durables en imitant les écosystèmes naturels. Le terme "permaculture" est une contraction de "permanent agriculture" initialement, puis "permanent culture" — élargissant le concept au-delà de l'agriculture pour englober une philosophie de conception de toute activité humaine.</p>
<p class="resume-text">Bill Mollison a fondé en 1981 le Permaculture Institute of Australia et a formé des milliers de praticiens qui ont diffusé la permaculture dans le monde entier à travers le cours de conception en permaculture (PDC, Permaculture Design Certificate). David Holmgren a développé une perspective plus philosophique et systémique, notamment dans "Permaculture : Principles and Pathways Beyond Sustainability" (2002), où il articule les 12 principes de la permaculture qui sont devenus la référence conceptuelle internationale. Ces principes incluent "Observer et interagir", "Collecter et stocker l'énergie", "Obtenir un rendement", "Utiliser des ressources renouvelables".</p>
<div class="highlight-box"><p>La permaculture est présente dans plus de 130 pays, avec des adaptations aux contextes locaux remarquables : des jardins de permaculture sahéliens utilisant des demi-lunes en sol pour collecter l'eau de pluie, des toits-jardins en permaculture dans les métropoles asiatiques, des fermes-écoles en Amérique latine intégrant des pratiques indigènes ancestrales dans un cadre permaculturel.</p></div>

<h3>Les trois éthiques fondamentales</h3>
<p class="resume-text">La permaculture repose sur trois éthiques fondamentales, considérées comme le fondement moral de toute conception : Prendre soin de la Terre (Earth Care), Prendre soin des personnes (People Care), et Partage équitable (Fair Share ou Return of Surplus). Ces éthiques ne sont pas des règles mais des orientations qui doivent guider toutes les décisions de conception.</p>
<p class="resume-text">"Prendre soin de la Terre" implique de travailler avec les processus naturels plutôt que contre eux, de régénérer les sols, les eaux et les écosystèmes dégradés. "Prendre soin des personnes" signifie subvenir à ses propres besoins et à ceux de sa communauté, en valorisant les savoir-faire locaux et en construisant la résilience collective. "Partage équitable" (initialement "Remettre les surplus") invite à limiter sa consommation au nécessaire et à redistribuer les surplus — d'énergie, de nourriture, de connaissances — vers les systèmes humains et naturels qui en ont besoin. Ces éthiques sont une réponse directe aux valeurs de l'économie capitaliste industrielle (accumulation, compétition, extraction).</p>
<div class="highlight-box"><p>Ces trois éthiques sont souvent présentées comme une "éthique de la permanence" en réponse aux crises du XXIe siècle. Dans des pays comme Cuba (qui a développé une agriculture largement permaculturelle par nécessité après la chute de l'URSS et l'embargo américain), ou au Zimbabwé (avec les projets de Zephaniah Phiri pour la collecte des eaux de pluie), la permaculture a démontré sa capacité à transformer des situations de pénurie en abondance relative.</p></div>

<h3>La permaculture en zones urbaines et péri-urbaines</h3>
<p class="resume-text">La permaculture urbaine adapte ses principes aux contraintes et opportunités de la ville. Les jardins partagés permaculturels intègrent des mares pour l'humidité et la faune auxiliaire, des spirales aromatiques (élévations en spirale permettant différentes expositions et humidités), des buttes en lasagne (couches alternées de matières organiques favorisant le lombric et la fertilité), des murs de chaleur (murs sombres qui accumulent la chaleur solaire) pour créer des microclimats favorables à des cultures plus sensibles au froid.</p>
<p class="resume-text">La "transition town" (ville en transition), initiée à Totnes (Angleterre) en 2006 par Rob Hopkins, étudiant en permaculture, applique les principes permaculturels à l'échelle d'une ville pour préparer la "descente énergétique" post-pétrole : jardins communautaires, monnaies locales, habitat partagé, réseau de troc de compétences. Le mouvement Transition est désormais présent dans 50 pays avec plus de 1 000 initiatives. La permaculture fournit ici un cadre conceptuel et des outils pratiques pour penser la résilience territoriale à différentes échelles.</p>
<div class="highlight-box"><p>La ville de Todmorden (Angleterre) a lancé en 2008 le projet "Incredible Edible" : planter des fruits et légumes comestibles dans tous les espaces publics — ronds-points, devant la gare, les parkings, les cimetières. Devenu viral, ce projet a inspiré des centaines de villes dans le monde et transformé Todmorden en destination touristique, illustrant l'impact communautaire d'une démarche permaculturelle appliquée au tissu urbain.</p></div>
""",

"permaculture/foret-jardin": """
<h3>Architecture et strates d'une forêt-jardin</h3>
<p class="resume-text">La forêt-jardin (ou jardin-forêt, food forest) est un système agroforestier qui reproduit la structure verticale d'une forêt naturelle en sélectionnant des espèces utiles à l'homme à chaque strate. La strate canopée (10-15 m) comprend les grands arbres fruitiers (noyer, châtaignier, poirier ancien, pommier haute-tige) ; la strate sous-canopée (5-8 m), les arbres fruitiers semi-nains et les arbres à feuilles caduques (noyer de Grenoble, prunier, cerisier) ; la strate arbustive (1-3 m), les arbustes à petits fruits (groseillier, cassissier, myrtillier, sureau, cornouiller), les bambous et les rosiers rugueux ; la strate herbacée, les plantes vivaces comestibles (consoude, rhubarbe, ail des ours, achillée, origan) ; la strate couvre-sol, les plantes rampantes et étalées (thym, fraisier, cresson) ; la strate racinaire, les légumes-racines vivaces (topinambour, crosne du Japon, scorsonère) ; et parfois une strate grimpante (kiwi, houblon, vigne).</p>
<p class="resume-text">L'assemblage de ces strates crée un microenvironnement favorable : l'ombrage réduit l'évapotranspiration et maintient l'humidité du sol ; les strates basses protègent les racines des arbres du compactage et de l'érosion ; les plantes azotofixatrices (aulne, robinier, légumineuses arbustives) enrichissent le sol en azote ; les plantes accumulatrices de minéraux (consoude, orties) pompent les minéraux profonds et les rendent disponibles en surface lors de leur décomposition.</p>
<div class="highlight-box"><p>Robert Hart, ingénieur britannique, a créé dans les années 1960 dans le Shropshire (Angleterre) l'une des premières forêts-jardins documentées en Europe tempérée. Son jardin de seulement 500 m² produisait une abondance de fruits, légumes et herbes aromatiques en nécessitant très peu d'entretien une fois établi — inspirant directement les praticiens de la permaculture du monde entier.</p></div>

<h3>Conception et implantation d'une forêt-jardin</h3>
<p class="resume-text">La conception d'une forêt-jardin commence par l'observation du site : expositions, pentes, sols, zones humides, vents dominants, microclimats. La zonation permaculturelle (de la zone 0, la maison, à la zone 5, le sauvage non géré) guide l'emplacement selon la fréquence d'utilisation et d'entretien : les herbes aromatiques et les légumes quotidiens seront proches de la cuisine (zone 1), les arbres fruitiers à récolte saisonnière plus loin (zone 2-3). La séquence d'implantation est critique : commencer par les arbres porteurs, puis les arbustes, puis les herbacées — une forêt-jardin mûre met 5 à 10 ans à s'établir pleinement.</p>
<p class="resume-text">Les guildes végétales sont des associations synergiques d'espèces qui se soutiennent mutuellement : autour d'un pommier, on plantera de l'ail des ours (répulsif contre les pucerons), de la consoude (accumulatrice de potassium et paillis), du bourrache (pollinisateur attracteur), du thym (antagoniste fongique), et des capucines (piège à pucerons éloignant les colonies du pommier). Ces associations complexes réduisent les besoins en traitement et en fertilisation tout en augmentant la biodiversité du jardin.</p>
<div class="highlight-box"><p>La forêt-jardin de Martin Crawford à Dartington (Royaume-Uni), sur 2 hectares, est l'une des forêts-jardins tempérées les mieux documentées au monde. Après 20 ans de développement, elle produit chaque année des centaines de kg de fruits, légumes et herbes, nécessitant seulement 1 à 2 heures de travail par semaine pour la maintenance — soit une productivité de travail exceptionnellement élevée comparée à un jardin conventionnel.</p></div>

<h3>La forêt-jardin dans le contexte alimentaire mondial</h3>
<p class="resume-text">Les forêts-jardins ne sont pas une invention occidentale : elles sont une forme traditionnelle d'agriculture pratiquée depuis des millénaires sous les tropiques. Les "jardins multistrates" des paysans balinais, les huertos familiares mexicains, les agroforêts à damar en Indonésie (qui ressemblent si bien à des forêts naturelles qu'elles ont longtemps été cartographiées comme telles), les jardins Kantu en Amazonie — tous partagent les mêmes principes de diversité, de verticalité et de productivité durable sans intrants externes.</p>
<p class="resume-text">Des études comparatives montrent que les forêts-jardins tropicales (homegardens) peuvent produire une diversité alimentaire supérieure aux champs agricoles conventionnels sur la même surface, tout en fournissant des services écosystémiques additionnels (régulation climatique, stockage carbone, habitat pour la faune). Dans des contextes de vulnérabilité alimentaire, la forêt-jardin familiale représente un filet de sécurité essentiel : ses espèces pérennes continuent de produire même en années de sécheresse ou de conflit, contrairement aux cultures annuelles.</p>
<div class="highlight-box"><p>Le projet "Forêts nourricières" en France, porté par plusieurs associations et collectivités, plante des forêts-jardins communautaires dans des espaces publics urbains et péri-urbains. La ville de Montpellier a inauguré en 2017 une forêt comestible de 6 000 m² avec 175 espèces fruitières et aromatiques accessible librement à tous les habitants — une incarnation concrète du principe de "partage équitable" permaculturel.</p></div>
""",

"elevage/zootechnie-generale": """
<h3>Les systèmes d'élevage à travers le monde : diversité et adaptations</h3>
<p class="resume-text">L'élevage mondial présente une diversité remarquable de systèmes, reflet des adaptations aux conditions locales. L'élevage pastoral nomade, pratiqué par les Peuls au Sahel, les Mongols en Asie centrale, les Massaïs en Afrique de l'Est ou les Touaregs au Sahara, est un système extensive millénaire qui maximise l'utilisation de ressources fourragères dispersées et variables. Ces systèmes, longtemps sous-estimés par les développeurs, sont aujourd'hui reconnus pour leur résilience et leur efficacité d'utilisation des ressources arides. L'élevage transhumant (alpages d'été, plaines d'hiver) représente une autre forme d'adaptation aux contraintes saisonnières des zones de montagne.</p>
<p class="resume-text">À l'opposé, l'élevage industriel hors-sol (porc, volaille, bovins laitiers) concentre des dizaines de milliers d'animaux dans des bâtiments fermés, avec une alimentation importée et des conditions de vie standardisées. Ce système maximise la productivité par animal et par travailleur, mais génère des externalités environnementales considérables (pollution azotée, émissions de GES, risque sanitaire) et des questions éthiques sur le bien-être animal. Entre ces deux extrêmes, les systèmes mixtes agriculture-élevage, prédominants en Afrique subsaharienne et en Asie du Sud, intègrent la traction animale, la fertilisation organique et la production alimentaire dans des systèmes circulaires.</p>
<div class="highlight-box"><p>L'élevage est responsable de 14,5 % des émissions mondiales de GES selon la FAO (2013), dont plus de la moitié provient de l'élevage bovin (méthane de la fermentation entérique et déjections). Le bétail occupe 70 % des terres agricoles mondiales (en comptant les terres cultivées pour l'alimentation animale) pour ne produire que 20 % des calories et 37 % des protéines consommées par l'humanité.</p></div>

<h3>La génétique animale : sélection et amélioration des races</h3>
<p class="resume-text">La sélection génétique des animaux d'élevage a transformé leurs performances au cours du XXe siècle. La vache Holstein, race laitière prédominante dans les élevages intensifs, produit aujourd'hui en moyenne 10 000 à 12 000 litres de lait par lactation — soit 10 fois plus que la production d'une vache du début du XIXe siècle. Le poulet de chair moderne (Gallus gallus domesticus), sélectionné depuis les années 1950, atteint son poids de vente (2,5 kg) en 42 jours contre 120 jours pour un poulet traditionnel. Ces performances spectaculaires ont été obtenues par sélection intense sur des critères de production, souvent au détriment de la santé et de la robustesse des animaux.</p>
<p class="resume-text">La génomique animale, rendue accessible par les puces à ADN et le séquençage de nouvelle génération, révolutionne la sélection : la sélection génomique permet de calculer la valeur génétique d'un animal dès sa naissance (ou même en embryon) à partir d'un seul échantillon de sang ou de tissu, sans attendre ses propres performances ou celles de sa descendance. Cette technique, adoptée massivement en bovins laitiers à partir de 2009, a accéléré le progrès génétique d'un facteur 2 à 3. Elle est maintenant étendue aux bovins allaitants, aux porcins, aux ovins et aux volailles.</p>
<div class="highlight-box"><p>La conservation des races locales et des races rustiques est un enjeu de biodiversité animale : sur les 8 800 races d'animaux d'élevage recensées dans le monde, environ 25 % sont considérées comme menacées. Ces races, adaptées à des conditions locales particulières (chaleur, parasites, alimentation pauvre), représentent un patrimoine génétique irremplaçable face aux crises sanitaires et climatiques futures — la diversité génétique est la base de la résilience.</p></div>

<h3>Alimentation animale et efficacité de conversion</h3>
<p class="resume-text">L'alimentation représente 60 à 70 % des coûts de production en élevage intensif. L'efficacité de conversion alimentaire (ECA) mesure la quantité d'aliment nécessaire pour produire 1 kg de gain de poids : environ 1,5 à 2 pour les poulets de chair, 2,5 à 3 pour les porcs, 7 à 10 pour les bovins à l'engraissement. Ces différences reflètent les différences métaboliques (les ruminants convertissent moins efficacement les céréales que les mono-gastriques, mais peuvent valoriser les fourrages et coproduits), le type de tissu formé (les animaux à croissance rapide déposent plus de muscle que de graisse) et les conditions d'élevage.</p>
<p class="resume-text">La formulation des rations par informatique (Linear Programming) optimise le mélange d'aliments disponibles pour atteindre les besoins nutritionnels des animaux au moindre coût. Les additifs alimentaires — vitamines, minéraux, acides aminés de synthèse (lysine, méthionine), enzymes (phytases pour améliorer la digestibilité du phosphore des céréales), probiotiques — permettent d'ajuster les rations à moindre coût tout en améliorant les performances. Les antibiotiques facteurs de croissance, utilisés massivement pendant des décennies pour améliorer les performances des poulets et porcs, ont été interdits en Europe depuis 2006 pour limiter le développement des résistances aux antibiotiques chez les bactéries.</p>
<div class="highlight-box"><p>Les insectes comestibles comme alimentation animale représentent une alternative prometteuse : les larves de mouche soldat noire (Hermetia illucens) peuvent être élevées sur des déchets organiques et valorisées comme source de protéines et de lipides pour l'alimentation des volailles, des porcs et des poissons. Leur efficacité de conversion est deux fois supérieure à celle des poulets, leur empreinte carbone 100 fois inférieure à celle du bœuf, et elles valorisent des déchets organiques autrement perdus.</p></div>
""",

"elevage/bien-etre-animal": """
<h3>Les cinq libertés : cadre fondateur du bien-être animal</h3>
<p class="resume-text">Le cadre des "cinq libertés", développé par le Farm Animal Welfare Council britannique dans les années 1960-1970, est devenu la référence internationale pour évaluer le bien-être des animaux d'élevage. Ces cinq libertés sont : être à l'abri de la faim, de la soif et de la malnutrition (accès à une alimentation adéquate) ; être à l'abri de l'inconfort physique et thermique (environnement approprié) ; être à l'abri de la douleur, des blessures et des maladies (prévention et traitement des affections) ; pouvoir exprimer les comportements propres à son espèce (espace et compagnie d'autres animaux) ; et être à l'abri de la peur et de la détresse (conditions et traitement évitant la souffrance mentale).</p>
<p class="resume-text">Ces cinq libertés, initialement définies pour les animaux de ferme, ont progressivement été étendues à d'autres contextes : animaux de compagnie, animaux de zoo, animaux utilisés dans la recherche scientifique. La reconnaissance que les animaux d'élevage sont des "êtres sentients" — capables d'éprouver des émotions et de souffrir — est désormais inscrite dans le droit européen (Traité de Lisbonne, 2007, article 13) et dans les législations de nombreux pays, fondant une obligation morale et juridique de protection.</p>
<div class="highlight-box"><p>Le Cambridge Declaration on Consciousness (2012), signé par un groupe de neuroscientifiques éminents lors d'une conférence présidée par Stephen Hawking, déclare que "les humains ne sont pas seuls à posséder les substrats neurologiques qui génèrent la conscience. Les animaux non humains, incluant tous les mammifères et oiseaux, et de nombreuses autres créatures, possèdent ces substrats neurologiques." Cette déclaration a renforcé la base scientifique des préoccupations éthiques concernant le bien-être animal.</p></div>

<h3>Systèmes d'élevage et bien-être : des compromis difficiles</h3>
<p class="resume-text">L'élevage industriel intensif est confronté à des critiques croissantes sur le plan du bien-être animal. Les poulets de chair modernes, sélectionnés pour une croissance hyper-rapide, développent fréquemment des myopathies musculaires, des problèmes locomoteurs et des maladies cardiovasculaires liés à leur croissance extrêmement rapide. Les truies en gestation, longtemps confinées dans des cases de mise bas individuelles trop étroites pour se retourner, ont été sujet d'une mobilisation importante qui a conduit à des réformes législatives en Europe. L'engraissement des oies et canards par gavage, pratique ancestrale pour le foie gras, est désormais interdit dans une quinzaine de pays.</p>
<p class="resume-text">À l'inverse, des systèmes plus extensifs comme l'élevage plein air, l'élevage biologique ou les labels "bien-être animal" offrent aux animaux davantage d'espace, la possibilité d'exprimer leurs comportements naturels et une moindre densité de population réduisant le risque de maladies et d'agressions. Ces systèmes sont généralement plus coûteux en terme de surface foncière et de coût de production, et produisent à des rendements inférieurs — d'où une tension avec les impératifs économiques et d'accessibilité alimentaire pour les populations à faibles revenus.</p>
<div class="highlight-box"><p>L'œuf à double utilisation est une innovation récente répondant à une critique majeure du bien-être animal en aviculture : l'élimination à la naissance des poussins mâles (indésirables en production laitière) à raison de 7 milliards d'individus par an dans le monde. Des techniques de sexage de l'œuf avant incubation (analyse spectroscopique à J9 ou détection d'estrogènes à J3) permettent de trier les œufs avant l'éclosion. Depuis 2022, le sexage in ovo est obligatoire en Allemagne et en France, mettant fin à l'euthanasie des poussins mâles à la naissance.</p></div>

<h3>Bien-être animal et transition alimentaire : vers une consommation responsable</h3>
<p class="resume-text">Les préoccupations pour le bien-être animal alimentent une transformation des comportements alimentaires dans les sociétés développées. La consommation de viande en France a baissé de 12 % entre 2010 et 2020, et la part des végétariens et flexitariens augmente régulièrement. Les labels de bien-être animal (Label Rouge, Agriculture Biologique, "Bleu-Blanc-Cœur", certification RSPCA en Grande-Bretagne) permettent aux consommateurs informés de choisir des produits issus d'élevages plus respectueux, en acceptant un surcoût. L'émergence des protéines alternatives — viande cultivée in vitro, protéines végétales (tofu, seitan, légumineuses), insectes — propose des options qui contournent totalement les questions de bien-être animal en élevage traditionnel.</p>
<p class="resume-text">La viande cultivée (ou viande in vitro) consiste à produire des fibres musculaires à partir de cellules souches animales en culture, sans abattage. Le premier burger de viande cultivée, préparé par Mark Post à Maastricht en 2013, avait coûté 250 000 euros à produire. Les coûts sont désormais descendus à quelques dizaines d'euros par kg, et plusieurs entreprises (Eat Just, Upside Foods, Aleph Farms) ont obtenu des autorisations commerciales à Singapour et aux États-Unis. L'impact environnemental potentiel est controversé : si la viande cultivée évite les émissions de méthane des ruminants, sa production intensive en milieu stérile nécessite des quantités considérables d'énergie.</p>
<div class="highlight-box"><p>La directive européenne 2010/63/UE sur la protection des animaux utilisés à des fins scientifiques impose le principe des "3R" : Remplacer les animaux par des méthodes alternatives quand c'est possible, Réduire le nombre d'animaux utilisés, Raffiner les méthodes pour minimiser la souffrance. L'Union européenne est leader mondial de la réglementation du bien-être animal, avec une législation couvrant les animaux d'élevage, les animaux de compagnie, les animaux de zoo et les animaux de laboratoire.</p></div>
""",

"viticulture/histoire-de-la-vigne": """
<h3>Les origines de la viticulture : de la Transcaucasie à la Méditerranée</h3>
<p class="resume-text">La vigne cultivée (Vitis vinifera subsp. vinifera) est issue d'une espèce sauvage (Vitis vinifera subsp. sylvestris) dont les vestiges génétiques et archéologiques pointent vers le Caucase comme centre de domestication. Des pépins de raisin cultivé et des restes de pressoirs ont été retrouvés en Géorgie (site de Gadachrili Gora) datés d'environ 6 000 à 8 000 avant J.-C. Des jarres de céramique contenant des résidus de tartrate de calcium, signe fervent de la fermentation du raisin, ont été découvertes en Iran (site de Hajji Firuz Tepe, environ 5 400 av. J.-C.) et en Arménie (cave de Areni-1, 4 100 av. J.-C.), la plus ancienne cave à vin du monde.</p>
<p class="resume-text">La viticulture s'est propagée vers la Mésopotamie, l'Égypte et la Méditerranée orientale avec les civilisations sumérienne, égyptienne et phénicienne. Les Phéniciens, grands navigateurs du premier millénaire av. J.-C., ont diffusé la viticulture tout autour du bassin méditerranéen. Les Grecs l'ont apportée en Gaule méridionale (Massalia, actuelle Marseille, vers 600 av. J.-C.), et les Romains l'ont étendue à tout l'empire, notamment dans les vallées du Rhône, de la Loire, de la Moselle et du Rhin — les grandes régions viticoles françaises actuelles.</p>
<div class="highlight-box"><p>L'ADN de cépages modernes révèle des histoires surprenantes : le Cabernet Sauvignon, cépage roi de Bordeaux, est un croisement naturel entre Cabernet Franc et Sauvignon Blanc, probablement survenu au XVIIe siècle dans les vignobles bordelais. Le Pinot Noir, cépage noble de Bourgogne, est génétiquement l'un des plus anciens cépages cultivés en Europe, avec une présence documentée dans les vignobles romains.</p></div>

<h3>La crise phylloxérique : catastrophe et reconstruction du vignoble mondial</h3>
<p class="resume-text">Le phylloxéra (Daktulosphaira vitifoliae), un puceron minuscule originaire d'Amérique du Nord, a ravagé les vignobles européens en un véritable cataclysme : introducé en Europe dans les années 1860 par des plants américains importés à des fins expérimentales, il a détruit en 30 ans plus des deux tiers du vignoble européen. Le phylloxéra s'attaque aux racines de Vitis vinifera (vigne européenne), auxquelles elle est très sensible, alors que les espèces américaines (Vitis labrusca, Vitis riparia) ont co-évolué avec cet insecte et lui sont résistantes.</p>
<p class="resume-text">La solution, découverte par le botaniste Jules-Émile Planchon et le vigneron montpelliérain Gustave Foëx dans les années 1870, a consisté à greffer les cépages européens (porte-greffe noble) sur des racines de vignes américaines (porte-greffe résistant). Cette pratique du greffage, révolutionnaire et initialement contestée par des vignerons refusant de "dénaturer" leurs vins, est devenue universelle : aujourd'hui, pratiquement tous les vignobles mondiaux sont plantés sur porte-greffe américains ou hybrides. Quelques exceptions subsistent dans des sols sableux (où le phylloxéra ne peut pas se déplacer) : une partie du Colares au Portugal, certaines vignes de Chypre et des vignes centenaires des Pouilles en Italie sont encore sur leurs propres racines.</p>
<div class="highlight-box"><p>La crise phylloxérique a eu des conséquences socio-économiques majeures : en France, des millions de vignerons ont été ruinés, précipitant l'exode rural et les grandes grèves viticoles de 1907 dans le Languedoc. Elle a également indirectement favorisé la fraude (vins de raisins secs ou de betterave), conduisant à l'instauration des premières appellations d'origine contrôlée (AOC) au début du XXe siècle.</p></div>

<h3>Cépages et terroirs : la diversité ampélographique mondiale</h3>
<p class="resume-text">La vigne cultivée comprend environ 10 000 variétés recensées (cépages), dont les origines génétiques sont cartographiées grâce aux analyses ADN. La France est l'une des pays les plus riches en cépages autochtones : Pinot Noir, Chardonnay, Cabernet Sauvignon, Merlot, Syrah, Riesling, Grenache — autant de cépages devenus mondiaux. Le concept de "cépage international" versus "cépage local" cristallise un débat sur la standardisation des goûts : depuis les années 1980, la mondialisation viticole a vu des cépages à succès commercial (Merlot, Chardonnay, Cabernet Sauvignon) s'imposer au détriment des variétés locales dans de nombreuses régions.</p>
<p class="resume-text">Le terroir, concept français difficilement traduisible dans d'autres langues, désigne l'ensemble des facteurs naturels et humains qui confèrent à un vin ses caractéristiques spécifiques : géologie et pédologie (types de sols et de roches), topographie (altitude, pente, exposition), microclimat (températures, précipitations, brouillards), et le savoir-faire viti-vinicole accumulé sur des générations. Des recherches géochimiques ont montré que certains composés aromatiques du vin (mercaptans, terpènes) sont directement influencés par la composition minérale des sols, donnant une base scientifique partielle au concept empirique de terroir.</p>
<div class="highlight-box"><p>Les changements climatiques modifient profondément la viticulture : les vendanges commencent en France 2 à 3 semaines plus tôt qu'il y a 50 ans, les degrés alcooliques des vins augmentent, et les cépages traditionnels souffrent de la chaleur dans des régions comme la Vallée du Rhône. Des vignerons avant-gardistes plantent des cépages méridionaux plus résistants à la chaleur (Carignan, Cinsault), ou remontent en altitude pour trouver des températures plus fraîches — adaptation nécessaire pour préserver l'identité des vins face au changement climatique.</p></div>
""",

"viticulture/cycle-de-la-vigne": """
<h3>Les stades phénologiques : un calendrier précis de la vie de la vigne</h3>
<p class="resume-text">Le cycle végétatif de la vigne suit une succession de stades phénologiques caractéristiques, qui varient selon le cépage, le millésime et le terroir. Le débourrement (gonflement puis ouverture des bourgeons, en mars-avril dans l'hémisphère nord) marque le réveil de la végétation après le repos hivernal. La sortie des feuilles (mai) est suivie de la floraison (juin), phase critique : la pollinisation est anémophile (par le vent) et auto-fécondante pour la plupart des cépages, mais les conditions météorologiques (pluie, froid, vent fort) peuvent perturber la nouaison et réduire la récolte future.</p>
<p class="resume-text">La véraison, qui survient en juillet-août selon les cépages, marque le début de la maturation : les baies, jusqu'ici vertes et dures, changent de couleur (rouge-noir pour les cépages rouges, dorés pour les blancs) et commencent à s'enrichir en sucres tout en perdant leur acidité. La proportion sucres/acidité est l'indicateur principal de la maturité technologique utilisé pour fixer la date des vendanges. La maturité phénolique (tannins et composés aromatiques) et la maturité sanitaire (état sanitaire des baies, risque de pourriture) sont des paramètres complémentaires tout aussi importants.</p>
<div class="highlight-box"><p>L'échelle BBCH (Biologische Bundesanstalt, Bundessortenamt und CHemische Industrie), développée en Allemagne, codifie les stades phénologiques de toutes les espèces végétales de manière standardisée, de 00 (repos) à 99 (sénescence). Pour la vigne, le code BBCH-09 correspond au débourrement, BBCH-60 à la floraison, BBCH-81 à la véraison et BBCH-89 à la maturité optimale. Cette standardisation facilite la comparaison des données phénologiques entre régions et millésimes.</p></div>

<h3>Taille et conduite de la vigne : former et équilibrer le cep</h3>
<p class="resume-text">La taille de la vigne, effectuée en hiver, est l'opération viticole la plus structurante : elle détermine la charge en raisins (nombre de grappes), la vigueur végétative (croissance des pousses), et donc l'équilibre entre la production de fruits et la croissance végétative. Deux grandes familles de taille coexistent : la taille courte (Gobelet, Cordon de Royat), qui laisse des coursonnes portant 1 à 3 yeux, et la taille longue (Guyot simple ou double, Sylvoz), qui laisse une ou deux baguettes de 6 à 12 yeux. La taille Guyot est la plus répandue en France, permettant une maîtrise fine de la charge.</p>
<p class="resume-text">Le palissage et la conduite de la vigne complètent la taille : le relevage et l'attachage des rameaux en cours de végétation optimisent l'exposition foliaire au soleil (photosynthèse) et l'aération des grappes (réduction des maladies cryptogamiques). L'ébourgeonnage (suppression des bourgeons superflus), le rognage (coupe des apex des pousses en cours de végétation) et l'effeuillage (suppression de feuilles autour des grappes) sont des opérations vertes destinées à affiner l'équilibre végétatif en cours de saison. Ces opérations manuelles représentent la grande majorité des heures de travail à la vigne et sont difficilement mécanisables — un frein à la compétitivité économique des vignobles de qualité.</p>
<div class="highlight-box"><p>La taille mécanique prépruneuse, qui coupe mécaniquement une grande partie des sarments avant la taille manuelle de finition, réduit le temps de taille de 40 à 60 % selon les études. L'enjambeur à taille mécanique totale (avec sécateurs électroniques ou thermiques guidés par des algorithmes de reconnaissance visuelle) représente l'étape suivante — des prototypes fonctionnent déjà dans des vignobles expérimentaux en Bordeaux et en Champagne.</p></div>

<h3>Climatologie viticole : le millésime comme expression du terroir et du temps</h3>
<p class="resume-text">Le millésime — l'année de récolte — est l'expression des conditions climatiques de l'année sur la qualité du raisin. Un millésime "grand" est généralement caractérisé par : un printemps sec et chaud (bonne floraison et développement sans maladies), un été chaud avec des nuits fraîches permettant l'accumulation d'arômes, et une fin de saison sèche permettant une maturation lente et complète. Les millésimes exceptionnels comme 2005 et 2015 en Bordeaux, ou 2005 et 2019 en Bourgogne, sont ceux qui conjuguent idéalement ces conditions.</p>
<p class="resume-text">Le changement climatique remodèle la cartographie de la qualité viticole mondiale : des régions autrefois trop froides pour la viticulture de qualité (Angleterre, Scandinavie, Canada) deviennent viticoles, tandis que les régions traditionnelles chaudes (Languedoc, Vallée du Rhône, Rioja) souffrent de sécheresses et de vendanges précoces. L'adaptation inclut la remontée en altitude des vignobles, l'adoption de cépages plus tardifs résistants à la chaleur, les techniques d'ombrage partiel (agrivoltaïsme viticole), et des pratiques d'irrigation d'appoint raisonnée dans des régions où l'irrigation de la vigne était historiquement interdite.</p>
<div class="highlight-box"><p>Les archives de dates de vendanges en France (recueillies dans les registres paroissiaux et de confréries) depuis 1354 sont l'une des plus longues séries climatiques continues au monde. Leur analyse montre que les vendanges de 2003, 2022 et 2023 sont les plus précoces de ces 7 siècles, confirmant l'accélération du réchauffement climatique et son impact direct sur le cycle de la vigne.</p></div>
""",

"viticulture/viticulture-durable": """
<h3>La viticulture biologique : principes et conversion</h3>
<p class="resume-text">La viticulture biologique, réglementée en Europe par le règlement CE 834/2007 et précisée pour la viticulture par le règlement CE 203/2012, interdit l'utilisation d'engrais de synthèse, d'herbicides, d'insecticides et de fongicides de synthèse. Elle autorise des intrants d'origine naturelle ou minérale : cuivre et soufre comme fongicides (bien que le cuivre, toxique pour les vers de terre et les micro-organismes, soit plafonné à 4 kg/ha/an dans l'UE), préparations biodynamiques, engrais organiques. La France est devenue le premier producteur mondial de vins biologiques, avec plus de 15 % du vignoble certifié bio en 2022.</p>
<p class="resume-text">La conversion en viticulture biologique dure 3 ans pendant lesquels le vigneron applique les pratiques biologiques mais ne peut pas encore apposer le logo bio sur ses bouteilles. Cette période de transition est souvent la plus difficile : les rendements baissent tandis que les coûts augmentent. Des études à long terme (notamment celles du Domaine de la Romanée-Conti en Bourgogne ou du CIVB à Bordeaux) montrent que les vignes biologiques développent un système racinaire plus profond et plus diversifié, une meilleure résistance au stress hydrique, et une expression du terroir souvent plus marquée.</p>
<div class="highlight-box"><p>La biodynamie, créée par Rudolf Steiner dans les années 1920 et développée pour la viticulture par des pionniers comme Nicolas Joly (Coulée de Serrant, Loire), ajoute aux pratiques biologiques une dimension cosmologique : travaux viticoles calés sur le calendrier lunaire, préparations à base de bouse de vache dans une corne de vache enterrée, tisanes d'ortie et de camomille. Si la dimension spirituelle est controversée, de nombreux vignerons biodynamiques remarquent des améliorations de la vitalité des sols et de la régularité des vendanges.</p></div>

<h3>Enherbement, travail du sol et gestion de la vigueur</h3>
<p class="resume-text">L'enherbement inter-rangs — laisser ou semer de l'herbe entre les rangs de vignes — est une pratique de viticulture durable qui offre de nombreux avantages : réduction de l'érosion des sols sur les terrains en pente, amélioration de la structure du sol par l'action des racines des graminées, limitation de la vigueur végétative excessive (la compétition herbe-vigne pour l'eau et l'azote modère la croissance des pousses), favoriser la faune auxiliaire (insectes prédateurs des ravageurs, oiseaux insectivores). Des plantes à fleurs (phacélie, moutarde, bourrache) sont parfois semées pour attirer les pollinisateurs et les auxiliaires naturels.</p>
<p class="resume-text">Le travail mécanique du sol (labour inter-rangs) reste une alternative à l'herbicide pour désherber sous le rang. Il stimule l'activité biologique du sol et améliore l'infiltration de l'eau, mais présente l'inconvénient de la formation d'une "semelle de labour" (couche compactée sous la profondeur de travail) et de la perturbation des réseaux mycorhiziens. Des outils de travail intercep (travailler sous le rang entre les ceps) comme les interceps, vignes-net ou les robots autonomes interrangs se développent pour remplacer l'herbicide sous le rang.</p>
<div class="highlight-box"><p>La sécheresse historique de 2022 en France a mis en évidence les avantages des vignes biologiques sur les vignes conventionnelles : des études de terrain ont montré que les vignes biologiques, dont le système racinaire explore plus profondément le sol grâce à l'absence d'herbicides qui maintiennent les racines en surface, ont mieux résisté au stress hydrique extrême de l'été 2022.</p></div>

<h3>Les certifications et labels en viticulture durable</h3>
<p class="resume-text">Au-delà du bio, de nombreuses certifications de viticulture durable ont émergé pour distinguer des degrés et des aspects différents de durabilité. En France, la Haute Valeur Environnementale (HVE) est une certification nationale à trois niveaux qui valorise la biodiversité, la protection phytosanitaire, la gestion des fertilisants et la gestion de l'eau. Son niveau 3 est compatible avec une démarche de viticulture durable sans atteindre nécessairement le plein bio. L'écocertification Terra Vitis est spécifique à la viticulture et impose des pratiques raisonnées documentées.</p>
<p class="resume-text">La certification biodynamique Demeter ou Biodyvin va au-delà du bio et impose des pratiques biodynamiques strictes. Les cahiers des charges des interprofessions viticoles (Bordeaux, Champagne, Alsace) intègrent de plus en plus des critères environnementaux dans leurs engagements volontaires. La certification Viticulteurs en développement durable des Pays de la Loire (VDPL) est un exemple de démarche interprofessionnelle régionale. Ces certifications multiples, parfois déroutantes pour les consommateurs, reflètent la diversité des approches de durabilité et la vitalité de la réflexion sur l'avenir du vignoble dans un contexte de changement climatique.</p>
<div class="highlight-box"><p>Le vignoble champenois est particulièrement avancé dans sa démarche de durabilité collective : le plan de développement durable Champagne (CIVC) regroupe 16 000 vignerons et 360 maisons dans une démarche de progrès environnemental commun, visant la neutralité carbone et zéro phytosanitaire problématique. La Champagne est ainsi devenue une référence mondiale de la viticulture durable à grande échelle.</p></div>
""",

"jardinage/legumes-et-familles-botaniques": """
<h3>Les Solanacées : la famille des vitamines et des alcaloïdes</h3>
<p class="resume-text">La famille des Solanacées (Solanaceae) rassemble quelques-uns des légumes les plus cultivés au monde, tous originaires d'Amérique. La tomate (Solanum lycopersicum), introduite en Europe au XVIe siècle mais longtemps considérée comme ornementale et toxique (la plante contient effectivement de la solanine), est aujourd'hui le légume le plus consommé au monde. Le poivron et le piment (Capsicum annuum et C. chinense) doivent leurs propriétés piquantes à la capsaïcine, molécule qui active les récepteurs TRPV1 de la douleur — leur piquant se mesure en unités Scoville (SHU).</p>
<p class="resume-text">La pomme de terre (Solanum tuberosum), domestiquée dans les Andes il y a environ 8 000 ans, nourrit aujourd'hui plus d'un milliard de personnes. L'aubergine (Solanum melongena), originaire d'Inde et introduite en Europe par les Arabes au Moyen Âge, est l'une des rares Solanacées à avoir été domestiquée en Asie. La physalis (Physalis peruviana), fruit exotique de plus en plus cultivé en France, est une autre représentante. Toutes ces plantes contiennent des alcaloïdes (solanine, tomatine, capsaïcine) qui constituent leurs défenses naturelles contre les herbivores — un exemple d'évolution convergente des défenses chimiques.</p>
<div class="highlight-box"><p>La rotation est essentielle pour les Solanacées, qui partagent de nombreux pathogènes : Phytophthora infestans (mildiou) attaque tomates ET pommes de terre ; Alternaria solani (alternariose) affecte plusieurs membres de la famille. Ne jamais les faire se succéder sur le même sol — respecter un délai d'au moins 3-4 ans entre deux cultures de la même famille.</p></div>

<h3>Les Cucurbitacées : concombres, courges et melons</h3>
<p class="resume-text">Les Cucurbitacées (Cucurbitaceae) sont les légumes à tiges rampantes ou grimpantes par excellence. La courgette (Cucurbita pepo), la courge musquée (Cucurbita moschata), le potimarron et le potiron (Cucurbita maxima) sont des cultivars de plusieurs espèces domestiquées en Amérique centrale et en Amérique du Sud. Le concombre (Cucumis sativus), originaire d'Inde, et le melon (Cucumis melo) sont domestiqués depuis l'Antiquité en Asie. La pastèque (Citrullus lanatus), originaire d'Afrique subsaharienne, a été cultivée en Égypte ancienne il y a plus de 5 000 ans.</p>
<p class="resume-text">Les Cucurbitacées sont des plantes à croissance rapide et vorace : elles produisent d'énormes fruits en peu de temps grâce à une photosynthèse très active. Leurs fleurs sont monoïques (pieds séparés en fleurs mâles et femelles sur la même plante) et nécessitent la pollinisation par les insectes. L'absence d'abeilles provoque la non-fécondation des fleurs femelles et la chute des petits fruits. En serre, la pollinisation est parfois assurée manuellement ou par des bourdons introduits dans l'espace de culture.</p>
<div class="highlight-box"><p>Les courges d'hiver (potimarron, courge butternut, courge de Hubbard) peuvent être conservées plusieurs mois à température ambiante grâce à leur peau épaisse et leur faible teneur en eau. Cette conservation naturelle a été précieuse pour les populations amérindiennes qui les cultivaient et les consommaient tout au long de l'hiver — une solution de stockage alimentaire efficace sans réfrigération.</p></div>

<h3>Les Apiaceae (Ombellifères) et les Asteraceae (Composées)</h3>
<p class="resume-text">Les Apiacées (anciennement Ombellifères) se reconnaissent à leurs fleurs en ombelles (comme des parasols à plusieurs étages). Elles comprennent la carotte (Daucus carota), le céleri (Apium graveolens), le persil (Petroselinum crispum), l'aneth (Anethum graveolens), le fenouil (Foeniculum vulgare), le cerfeuil (Anthriscus cerefolium) et le panais (Pastinaca sativa). Leurs fleurs attirent de nombreux insectes pollinisateurs et parasitoïdes, faisant des Apiaceae en fleur un atout précieux pour la biodiversité du jardin. Les Apiaceae sauvages comprennent aussi des espèces très toxiques comme la grande cigüe (Conium maculatum), ce qui justifie de ne jamais consommer d'espèces inconnues de cette famille.</p>
<p class="resume-text">Les Astéracées (Composées) regroupent des légumes aux inflorescences complexes composées de nombreuses petites fleurs (capitules). La laitue (Lactuca sativa), l'artichaut (Cynara scolymus), le topinambour (Helianthus tuberosus), l'endive et la chicorée (Cichorium intybus), le scorsonère (Scorzonera hispanica) et l'oseille des murailles en font partie. Elles contiennent souvent de l'inuline (notamment artichaut et topinambour), un prébiotique fermentable par la flore intestinale qui explique leur intérêt nutritionnel et leurs effets... gazeux notoires.</p>
<div class="highlight-box"><p>Les fleurs des Apiaceae et Asteraceae sont particulièrement attractives pour les parasitoïdes (guêpes microscopiques qui pondent dans les ravageurs). Planter du persil, du fenouil, de la carotte ou de l'aneth laissés monter en fleurs dans le potager attire des prédateurs naturels des pucerons, aleurodes et chenilles — une stratégie d'horticulture compagne ("companion planting") soutenue par des études scientifiques.</p></div>

<h3>Associations bénéfiques au jardin : la science du compagnonnage végétal</h3>
<p class="resume-text">Le compagnonnage végétal (companion planting) est l'art d'associer des espèces végétales qui se bénéficient mutuellement. Les bases scientifiques de ces associations sont réelles, même si nombre d'affirmations traditionnelles manquent de preuves expérimentales robustes. L'association classique des "Trois Sœurs" amérindiennes (maïs, haricot grimpant, courge) est un exemple validé : le maïs sert de tuteur au haricot, le haricot fixe l'azote atmosphérique bénéfiant au maïs et à la courge, la courge couvre le sol réduisant les mauvaises herbes et l'évaporation.</p>
<p class="resume-text">La répulsion des insectes ravageurs par des plantes aromatiques est partiellement fondée : les composés volatils du basilic (estragol, linalool) repoussent certains aleurodes et pucerons sur les tomates voisines dans des conditions contrôlées. L'ail (Allium sativum) libère des composés soufrés (allicine) qui inhibent la croissance de certains champignons pathogènes. Les capucines (Tropaeolum majus) agissent comme "plantes-pièges" attirant les pucerons sur elles plutôt que sur les cultures voisines. Ces effets sont réels mais leur efficacité varie selon les conditions, les densités de plantation et les espèces impliquées.</p>
<div class="highlight-box"><p>Des études récentes ont quantifié les effets du compagnonnage : planter du basilic à 30 cm des tomates réduit les dépôts d'œufs d'aleurodes de 40 à 60 % dans des essais contrôlés (Dogen et al., 2018). La semoule de maïs en paillis réduit les maladies fongiques du gazon. Ces résultats encouragent des recherches plus systématiques sur les interactions allélopathiques entre plantes cultivées.</p></div>
""",

"jardinage/verger-et-fruitiers": """
<h3>La sélection et la plantation des arbres fruitiers</h3>
<p class="resume-text">Le choix des variétés fruitières est une décision aux conséquences décennales. Les critères à considérer incluent l'adaptation au climat local (résistance au gel pour les zones à hiver rigoureux, tolérance à la chaleur pour le midi), la résistance aux maladies (variétés résistantes à la tavelure du pommier, à la cloque du pêcher, à la rouille du poirier), les pollinisateurs nécessaires (la majorité des fruitiers sont auto-incompatibles et nécessitent une deuxième variété compatible pour la fécondation croisée), et la période de maturité (étaler les récoltes de juillet à novembre pour les pommes par exemple).</p>
<p class="resume-text">Le porte-greffe est aussi critique que la variété : il détermine la vigueur de l'arbre (du super-nain M27 au vigoureux franc de pépins), sa précocité d'entrée en production, sa tolérance aux sols (certains porte-greffe tolèrent les sols humides ou calcaires), sa résistance aux nématodes et sa durée de vie. Les porte-greffes nanifiants (M9, M106 pour le pommier) permettent une densité de plantation élevée et des récoltes précoces, mais nécessitent irrigation et palissage. Les arbres greffés sur franc (semis du même espèce) sont plus vigoureux, rustiques et longévifs mais entrent en production plus tard.</p>
<div class="highlight-box"><p>La collection nationale de pommiers du INRAE (Institut national de recherche pour l'agriculture) à Angers conserve plus de 2 000 variétés de pommiers anciens, dont beaucoup ont disparu des vergers commerciaux. Cette biodiversité génétique est une ressource précieuse pour les sélectionneurs cherchant des résistances naturelles aux maladies ou des adaptations à des conditions climatiques extrêmes.</p></div>

<h3>La taille des arbres fruitiers : former, maintenir, rajeunir</h3>
<p class="resume-text">La taille des arbres fruitiers poursuit trois objectifs : former le jeune arbre en lui donnant une charpente équilibrée et aérée, maintenir l'équilibre entre croissance végétative et fructification à l'âge adulte, et rajeunir un arbre vieilli pour stimuler de nouveaux bois fructifères. Les principales formes de conduite sont : la forme libre (gobelet, fuseau, axe central) qui privilégie la luminosité et la facilité de travail, et la forme palissée (espalier, palmette, U double) qui maximise l'utilisation de l'espace en limitant la largeur et optimise l'ensoleillement.</p>
<p class="resume-text">La taille d'été (ébourgeonnage, pincement) complète la taille hivernale : supprimer les gourmands (pousses vigoureuses à croissance verticale qui épuisent l'arbre sans produire de fruits), rabattre les pousses latérales pour favoriser la formation de boutons floraux, éclaircir le feuillage pour améliorer l'aération et l'ensoleillement des fruits. L'éclaircissage des fruits (suppression manuelle ou chimique d'une partie des fruits en formation) est pratiqué en production professionnelle pour améliorer le calibre et la qualité des fruits restants au détriment du nombre.</p>
<div class="highlight-box"><p>Un pommier haute-tige bien entretenu peut vivre et produire pendant 80 à 100 ans. Ces vieux vergers de haute-tige, longtemps abandonnés au profit de vergers intensifs à basse-tige plus productifs, sont reconnus aujourd'hui pour leur valeur patrimoniale et écologique : ils abritent une biodiversité exceptionnelle (oiseaux cavernicoles comme la chevêche d'Athéna, chauves-souris, nombreux insectes saproxyliques dans les vieux bois). Des programmes de conservation et de replantation de vergers haute-tige se développent en France.</p></div>

<h3>Gestion organique de la santé des fruitiers</h3>
<p class="resume-text">La gestion sanitaire des fruitiers sans pesticides de synthèse repose sur plusieurs stratégies complémentaires. La résistance variétale est le premier levier : des variétés de pommiers comme "Ariane", "Chantecler" ou "Topaz" sont résistantes ou tolérantes à la tavelure (Venturia inaequalis), maladie fongique principale du pommier, réduisant considérablement le besoin de traitements. Les traitements préventifs à base de cuivre et de soufre sont les seuls fongicides autorisés en biologie, mais doivent être utilisés parcimonieusement en raison de leurs effets sur la faune du sol.</p>
<p class="resume-text">La lutte biologique contre les ravageurs est opérationnelle dans le verger : les trichogrammes (micro-guêpes parasitoïdes) sont lâchés contre les œufs de tordeuses ; les nématodes entomopathogènes (Steinernema carpocapsae) sont utilisés contre les larves de carpocapse hivernant dans les écorces ; les kaolins (argiles fines) forment un film répulsif sur les fruits contre les pontes de cochenilles et psylles. La confusion sexuelle par diffuseurs de phéromones synthétiques est la méthode phare du verger biologique intensif contre le carpocapse (ver du fruit) et les tordeuses orientales.</p>
<div class="highlight-box"><p>Le paillage des vergers (copeaux de bois, paille, broyat de déchets verts) autour des arbres offre de nombreux avantages : maintient l'humidité du sol (réduction de l'irrigation de 30 à 50 %), inhibe les adventices, améliore la structure du sol, fournit un habitat pour la faune auxiliaire (carabes prédateurs de larves, vers de terre). Cependant, un excès de paillis humide peut favoriser certains ravageurs (limaces, mulots) et des maladies du collet — il doit être maintenu à distance du tronc.</p></div>
""",

"jardinage/jardinage-ecologique": """
<h3>La conception d'un jardin écologique : principes de base</h3>
<p class="resume-text">Le jardinage écologique ne se réduit pas à l'absence de produits chimiques — c'est une approche systémique qui cherche à créer un écosystème jardinier résilient, productif et favorable à la biodiversité. Ses principes fondamentaux s'inspirent de l'écologie : diversifier les espèces (polyculteurs plutôt que monocultures) pour augmenter la résilience, favoriser les boucles courtes (composter les déchets du jardin pour fertiliser le sol), travailler avec les cycles naturels (rythmes saisonniers, cycles de l'eau, cycles des nutriments), et créer des habitats variés pour accueillir la faune auxiliaire.</p>
<p class="resume-text">La conception du jardin doit intégrer plusieurs éléments structurants : une mare ou un point d'eau (habitat pour les amphibiens prédateurs de limaces, zone de ponte pour les libellules, abreuvoir pour les oiseaux), des haies et des brise-vents d'espèces indigènes (aubépine, sureau, troène, cornouiller) qui abritent les auxiliaires, des andains de bois morts et de pierres (abri pour les hérissons, les carabes, les lézards), des zones de végétation spontanée non gérée (ortie, pissenlit, ronce) qui accueillent des insectes spécialistes.</p>
<div class="highlight-box"><p>Un programme de recherche de l'Université d'Exeter (UK) a montré que les jardins privés urbains abritent en moyenne 2 fois plus d'espèces d'invertébrés que les parcs urbains, en raison de leur plus grande diversité structurale (strates multiples, zones non gérées, variété végétale). La mosaïque de jardins privés constitue un réseau écologique urbain de première importance.</p></div>

<h3>Gestion de l'eau au jardin : collecter, économiser et recycler</h3>
<p class="resume-text">L'eau est la ressource la plus limitante dans de nombreux jardins, et sa gestion raisonnée est centrale dans le jardinage écologique. La récupération des eaux de pluie (cuve sous la gouttière) est le premier geste : une maison de 100 m² de toiture collecte en moyenne 60 litres d'eau par m² de pluie annuelle, soit 6 000 litres par an dans une région à pluviométrie de 600 mm — de quoi couvrir les besoins d'un potager de taille modeste. Le paillage des cultures réduit l'évaporation du sol de 50 à 70 %, maintient la fraîcheur racinaire et supprime les adventices : un triple bénéfice.</p>
<p class="resume-text">L'arrosage au goutte-à-goutte est deux à trois fois plus efficace que l'arrosage par aspersion : il délivre l'eau directement à la base des plantes, sans pertes par évaporation foliaire ni ruissellement. Des systèmes simples de goutte-à-goutte enterré (buried drip irrigation) avec des tuyaux poreux enterrés à 15-20 cm de profondeur sont particulièrement efficaces : l'eau s'infiltre directement dans la zone racinaire sans aucune évaporation de surface. Dans les jardins méditerranéens, des ollas (jarres en terre cuite poreuse enterrées et remplies d'eau) permettent une irrigation passive et ultra-efficace — une technique ancestrale encore utilisée dans de nombreux pays semi-arides.</p>
<div class="highlight-box"><p>Le compostage des déchets verts du jardin et des déchets organiques de cuisine permet de produire un amendement riche qui améliore la structure du sol, sa capacité de rétention en eau et sa vie biologique — réduisant d'autant les besoins en arrosage et en fertilisation. Un ménage de 4 personnes peut produire 200 à 300 kg de compost par an, soit suffisamment pour amender un potager de 50 m².</p></div>

<h3>Encourager la biodiversité utile : de la théorie à la pratique</h3>
<p class="resume-text">La biodiversité du jardin est un service gratuit de régulation biologique si on lui donne les conditions pour s'exprimer. Les oiseaux insectivores (mésanges, rougegorges, fauvettes) consomment des centaines d'insectes ravageurs par jour : une mésange nourrit ses poussins avec jusqu'à 800 chenilles par jour. Les installer nécessite des nichoirs adaptés et des arbustes à baies (sorbier, viorne, sureau) pour les nourrir en hiver. Les chauve-souris, souvent méconnues, consomment jusqu'à 3 000 insectes par nuit (moustiques, papillons nocturnes, chironomes) — un nichoir à chauve-souris accroché sous les toits est un auxiliaire précieux et entièrement gratuit.</p>
<p class="resume-text">Les abeilles sauvages (halictus, osmies, andrènes — plus de 1 000 espèces en France) sont des pollinisateurs souvent plus efficaces que l'abeille domestique pour de nombreuses cultures. Des hôtels à insectes (fagots de tiges creuses de sureau ou de bambou, blocs de bois percés) offrent des sites de nidification pour les osmies et les chéilostomes. Planter des fleurs à floraison étalée (de mars à octobre) assure une source continue de nectar et de pollen : crocus et Hellébore en mars, bourrache et ciboulette en mai, phacélie en juillet, sauges et nepetas en été, asters et sédum en automne.</p>
<div class="highlight-box"><p>L'"effet bord" (ou effet lisière) est un principe écologique applicable au jardin : les zones de transition entre deux habitats différents (haie-pelouse, mare-jardin, potager-prairie) concentrent la biodiversité. Aménager ces transitions de façon progressive (une bande de prairie fleurie entre le potager et la haie, par exemple) multiplie les niches écologiques et donc le nombre d'espèces animales et végétales accueillies dans le jardin.</p></div>
""",

"jardinage/calendrier-du-jardinier": """
<h3>Le calendrier du jardinier : entre règles générales et adaptations locales</h3>
<p class="resume-text">Le calendrier du jardinier traditionnel, fondé sur des observances comme les saints de glace (Mamert, Pancrace, Gervais — 11, 12, 13 mai), la lune montante ou descendante, ou les dictons régionaux ("À la Sainte-Luce, le froid avance ou recule"), reflète des siècles d'observation empirique des cycles saisonniers. Bien que certaines de ces observances n'aient pas de base scientifique solide (l'influence de la lune sur la germination est controversée), d'autres reflètent des réalités climatiques réelles : les saints de glace correspondent statistiquement à une période de retour froid en Europe du Nord liée à l'afflux d'air arctique en mai.</p>
<p class="resume-text">Le jardinage de précision moderne utilise des indicateurs plus objectifs : la température du sol (les semis en plein air ne sont possibles que quand le sol atteint 8-10 °C pour les légumes rustiques, 12-15 °C pour les cultures chaudes), les prévisions météorologiques sur 10-15 jours, et les données phénologiques locales (floraison des lilas = fin des gelées tardives dans de nombreuses régions de France). Ces outils permettent d'adapter le calendrier aux conditions réelles de l'année plutôt que de suivre aveuglément des dates fixes.</p>
<div class="highlight-box"><p>Le changement climatique reconfigure le calendrier du jardinier : les dernières gelées printanières arrivent 2 à 3 semaines plus tôt qu'il y a 50 ans dans de nombreuses régions françaises, permettant des plantations de tomates et de cucurbitacées plus précoces. En revanche, les sécheresses estivales plus intenses nécessitent des techniques d'économie d'eau plus élaborées et le choix de variétés plus résistantes à la chaleur.</p></div>

<h3>Les semis : de la graine à la plantule</h3>
<p class="resume-text">La germination est le processus par lequel l'embryon dormant reprend sa croissance active. Elle nécessite la présence simultanée d'eau, d'une température adéquate et (pour certaines espèces photosensibles) de lumière ou d'obscurité. La dormance des graines — mécanisme évolutif pour éviter la germination dans des conditions défavorables — peut être levée par des traitements spécifiques : stratification froide et humide (2-5 °C pendant 4-8 semaines) pour les arbres et arbustes des zones tempérées, scarification mécanique (ponçage de la tégument) pour les légumineuses à graine dure, traitement à l'eau bouillante pour certains acacias.</p>
<p class="resume-text">La qualité des semences est déterminante : le taux de germination diminue avec l'âge des graines (bien que certaines, comme les courges et les tomates, restent viables 4-6 ans ; d'autres, comme le poireau et l'oignon, ne gardent une bonne germination que 1-2 ans). Les graines issues de variétés populations (à pollinisation libre) peuvent être récoltées et ressemées chaque année, transmettant leur génotype de génération en génération. Les hybrides F1, majoritaires dans le commerce, ne peuvent pas être ressemés : leurs graines produisent des plantes très différentes et souvent moins performantes.</p>
<div class="highlight-box"><p>Le mouvement des "semences paysannes" défend la liberté de sauver, échanger et vendre des semences de variétés anciennes et locales. Ce mouvement s'oppose à la privatisation du vivant via les certificats d'obtention végétale (COV) qui accordent un monopole commercial sur les nouvelles variétés. En France, le réseau Graines de Troc, les associations Kokopelli et RSP (Réseau Semences Paysannes) conservent et diffusent des milliers de variétés potagères menacées de disparition.</p></div>

<h3>Gestion du sol vivant : compost, paillage et non-travail</h3>
<p class="resume-text">Le sol vivant est la ressource première du jardinier écologique. Sa santé se mesure à la présence abondante de vers de terre (un ver de terre par litre de sol sain), à la présence de mycorhizes et de champignons décomposeurs visibles (mycélium blanc dans les couches superficielles), à une bonne structure grumeleuse (agrégats stables qui ne se dispersent pas dans l'eau) et à une odeur de forêt (produite par la géosmine, molécule produite par les Actinomycètes). Ces indicateurs biologiques simples permettent d'évaluer la santé du sol sans analyse chimique.</p>
<p class="resume-text">Le compostage maison transforme les déchets organiques en or brun. Un composteur bien conduit — mélange équilibré de "verts" (tontes, épluchures, marc de café, riches en azote) et de "bruns" (feuilles mortes, broyat de bois, cartons, riches en carbone), maintenu humide mais pas gorgé d'eau, retourné régulièrement pour l'aération — produit un compost mûr en 3 à 6 mois. Appliqué en paillis ou incorporé légèrement en surface, ce compost nourrit les micro-organismes du sol et améliore progressivement sa structure et sa fertilité.</p>
<div class="highlight-box"><p>La technique du "No-Dig" (sans bêchage), popularisée par le jardinier britannique Charles Dowding, consiste à n'opérer aucun travail du sol mais à empiler des couches de compost en surface. Les résultats de ses 30 ans d'expérimentation comparative montrent des rendements égaux ou supérieurs aux parcelles bêchées, une réduction du salissement par les adventices, et une meilleure structure et fertilité du sol sur le long terme — une remise en question radicale du dogme du jardinage traditionnel.</p></div>
"""
}

def inject_before_quiz(content, new_text):
    pattern = r'(</section>\s*\n\n<section[^>]*id="quiz")'
    result = re.sub(pattern, new_text + r'\1', content)
    if result == content:
        pattern2 = r'(</section>\s*<section[^>]*id="quiz")'
        result = re.sub(pattern2, new_text + r'\1', content)
    return result

with open(FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

modified = 0
skipped = 0
for key, enrichment in ENRICHMENTS.items():
    if key in data['pages']:
        page = data['pages'][key]
        if page.get('type') in ('course', 'lesson'):
            orig_len = len(page['content'])
            page['content'] = inject_before_quiz(page['content'], enrichment)
            new_len = len(page['content'])
            print(f"  {key}: {orig_len} -> {new_len} (+{new_len-orig_len})")
            modified += 1
    else:
        print(f"  MISSING: {key}")
        skipped += 1

with open(FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone. {modified} pages modified, {skipped} skipped.")

# Verify
with open(FILE, 'r', encoding='utf-8') as f:
    check = json.load(f)
pages = check['pages']
course_pages = [(k, len(pages[k].get('content',''))) for k in pages if pages[k].get('type') in ('course','lesson')]
short = [(k,l) for k,l in course_pages if l < 10000]
print(f"Pages still < 10000 chars: {len(short)}")
for k,l in short:
    print(f"  {l:6d} | {k}")
print("JSON validation: OK")
