#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/litterature-fr.json'

ADDITIONS = {
    'classicisme/racine-corneille': '<h3>Le héros cornélien face au héros racinien</h3><p class="resume-text">L\'opposition entre le héros cornélien et le héros racinien est l\'une des grandes catégories de la critique littéraire classique française. Chez Corneille (Le Cid, Horace, Cinna), le héros se définit par sa capacité à surmonter ses passions au profit d\'un idéal — la gloire, l\'honneur, la raison d\'État. La volonté triomphe, même douloureusement. Chez Racine (Andromaque, Phèdre, Bajazet), le héros est au contraire prisonnier de ses passions, dévoré par un amour qui le conduit à la destruction. La tragédie racinienne est celle de l\'impuissance — on ne choisit pas qui on aime, on ne peut pas ne pas aimer. Cette opposition a structuré des décennies de lectures scolaires et critiques.</p><h3>Racine et la psychologie des passions</h3><p class="resume-text">Jean Racine (1639-1699) est souvent présenté comme le premier grand psychologue de la littérature française. Dans Phèdre (1677), il explore avec une précision clinique remarquable le mécanisme de la passion coupable : la honte, le déni, l\'aveu arraché, l\'auto-destruction. Dans Britannicus, il peint la naissance du tyran en Néron sous l\'influence mortifère de sa mère Agrippine. Dans Bérénice, il fait de la séparation amoureuse inévitable un sujet de tragédie à part entière, prouvant que les larmes n\'ont pas besoin du sang. Ses personnages sont les ancêtres directs de la littérature psychologique moderne.</p><div class="highlight-box"><strong>La Comédie-Française</strong> : Fondée en 1680 par Louis XIV pour institutionnaliser l\'héritage classique, la Comédie-Française joue encore aujourd\'hui les pièces de Molière, Racine et Corneille. Les Fables de La Fontaine sont apprises par cœur à l\'école primaire depuis des siècles. La formation classique reste au cœur des programmes de littérature française, faisant des élèves français les lecteurs privilégiés d\'un héritage que peu d\'autres littératures peuvent égaler en cohérence et en rayonnement international.</div>',

    'moyen-age/poesie-medievale': '<h3>Les troubadours et l\'amour courtois</h3><p class="resume-text">Les troubadours (en langue d\'oc) et les trouvères (en langue d\'oïl) ont inventé au XIIe-XIIIe siècles un nouveau langage de l\'amour qui a façonné toute la lyrique occidentale. La fin\'amor est un amour codifié : le chevalier-poète se place dans une relation de service envers la dame, belle, noble, et généralement inaccessible. L\'amour non partagé ou impossible est la condition même de l\'inspiration poétique. Cette esthétique du désir sublimé a traversé les siècles : on la retrouve chez Pétrarque, dans le blason Renaissance, jusqu\'aux chansons d\'amour modernes.</p><h3>François Villon, poète maudit avant la lettre</h3><p class="resume-text">François Villon (1431-après 1463) est l\'un des rares poètes du Moyen Âge dont la vie aventureuse est aussi connue que l\'œuvre. Étudiant parisien, meurtrier, voleur, condamné à mort puis gracié, exilé : sa vie turbulente nourrit une poésie d\'une intensité autobiographique exceptionnelle. La Ballade des pendus, écrite alors qu\'il attendait l\'exécution, est un chef-d\'œuvre de la méditation sur la mort et la décomposition. Rimbaud, Apollinaire, Brassens : Villon a inspiré tous ceux qui ont fait de la marginalité une posture poétique.</p><div class="highlight-box"><strong>Philologie médiévale</strong> : La plupart des textes médiévaux ne sont parvenus jusqu\'à nous que par des manuscrits copiés à la main. La philologie médiévale — science de l\'édition critique des textes anciens — a permis depuis le XIXe siècle de reconstituer ces textes, de comparer les variantes entre manuscrits. Ces travaux ont redécouvert un patrimoine que la Renaissance avait largement méprisé au profit de l\'Antiquité, et que le Romantisme du XIXe siècle a réhabilité avec enthousiasme.</div>',

    'moyen-age/chanson-geste': '<h3>La Chanson de Roland et l\'identité française</h3><p class="resume-text">La Chanson de Roland, composée vers 1080 et transcrite dans le manuscrit d\'Oxford (vers 1100), est considérée comme le premier chef-d\'œuvre de la littérature française. Elle raconte la mort héroïque de Roland, neveu de Charlemagne, à Roncevaux — un épisode historique mineur transformé en épopée nationale. La trahison de Ganelon, la fidélité d\'Olivier, le refus orgueilleux de Roland de sonner du cor avant qu\'il soit trop tard : ces éléments ont nourri un récit fondateur de l\'idéal chevaleresque français. Chanté par des jongleurs lors des croisades pour galvaniser les troupes, le texte illustre comment l\'épopée forge l\'identité collective en sélectionnant et magnifiant certains moments du passé.</p><h3>La représentation de l\'ennemi dans les chansons de geste</h3><p class="resume-text">Les Sarrasins des chansons de geste sont une construction idéologique qui dit plus sur la mentalité des croisés que sur l\'islam réel. Présentés comme adorateurs d\'idoles — erreur théologique grossière, l\'islam étant rigoureusement iconoclaste — ils sont l\'image inversée du chevalier chrétien. Et pourtant, certaines chansons accordent aux Sarrasins des vertus guerrières admirables, créant une tension entre la nécessité propagandiste de démoniser l\'ennemi et la fascination pour un adversaire digne. Cette ambivalence préfigure les représentations plus nuancées de l\'Orient dans la littérature des croisades.</p><div class="highlight-box"><strong>Cycle arthurien</strong> : Les chansons de geste relatives à Charlemagne (matière de France) coexistent avec le cycle arthurien (matière de Bretagne), d\'origine celtique. Lancelot, Guenièvre, Perceval, le Graal : ces figures ont été christianisées et romanisées par des auteurs comme Chrétien de Troyes (XIIe s.), dont les romans courtois ont eu une influence immense sur la littérature européenne médiévale et sur toute la fantasy contemporaine.</div>',

    'classicisme/la-fontaine': '<h3>La Fontaine et la tradition ésopique</h3><p class="resume-text">Jean de La Fontaine (1621-1695) s\'inscrit dans une longue tradition de la fable animalière remontant à Ésope (VIe siècle av. J.-C.). Mais il les transforme radicalement : là où la fable ésopique est sobre et didactique, La Fontaine crée de véritables petits poèmes dramatiques, avec des dialogues vivants, des portraits pittoresques et une grande variété de mètres. La dédicace au Dauphin, fils de six ans de Louis XIV, inscrit un projet pédagogique au cœur du recueil : les Fables sont présentées comme une école de la sagesse pour le futur roi, une éducation aux réalités du pouvoir, de la flatterie et de la prudence.</p><h3>La postérité des Fables</h3><p class="resume-text">Les Fables de La Fontaine occupent une place unique dans la culture française : apprises par cœur à l\'école primaire depuis le XVIIIe siècle, elles ont imprégné le langage quotidien de citations et d\'allusions (« se faire patte de velours », « la raison du plus fort est toujours la meilleure »). Elles ont inspiré des illustrateurs depuis Gustave Doré jusqu\'à des bandes dessinées contemporaines. Des compositeurs comme Gabriel Fauré ou Francis Poulenc en ont mis en musique. Cette ubiquité culturelle en fait un cas unique de texte littéraire devenu patrimoine vivant, présent dans la mémoire collective de millions de Français.</p><div class="highlight-box"><strong>Politique et société dans les Fables</strong> : Sous l\'apparente légèreté de ses fables animalières, La Fontaine offre une critique acérée de la société de son temps. Les puissants dévorent les faibles, la flatterie triomphe de la sincérité, la ruse l\'emporte sur la force. Le lion est souvent cruel et arbitraire comme un monarque absolu. Cette critique sociale voilée a rendu les Fables suspectes à certains et appréciées de tous : chacun pouvait y lire ce qu\'il voulait.</div>',

    'classicisme/moliere': '<h3>Molière et la querelle du Tartuffe</h3><p class="resume-text">Tartuffe (1664-1669) est la pièce la plus controversée de Molière. Le personnage d\'un faux dévot qui s\'introduit dans une famille bourgeoise pour s\'emparer de ses biens déclencha l\'ire des dévots, qui obtinrent l\'interdiction de la pièce. Cinq ans de lutte politique avant la représentation publique de 1669. Cet épisode illustre la puissance subversive du théâtre comique et la capacité de Molière à utiliser le rire pour dénoncer les hypocrisies sociales les plus enracinées.</p><h3>Molière dans la culture mondiale</h3><p class="resume-text">Molière est avec Shakespeare le dramaturge le plus joué dans le monde. En France, « Molière » est synonyme de théâtre — le français est parfois appelé « la langue de Molière ». Les Molières (équivalent français des Tony Awards) distinguent chaque année les meilleures productions théâtrales. Ses pièces sont au programme scolaire dans des dizaines de pays. Cette universalité tient à ce que les vices qu\'il dénonce — hypocrisie, avarice, vanité — n\'ont pas vieilli et restent aisément reconnaissables dans n\'importe quelle culture contemporaine.</p><div class="highlight-box"><strong>La mort de Molière en scène</strong> : Molière mourut (1673) lors de la quatrième représentation du Malade imaginaire — il jouait le rôle d\'un malade imaginaire alors qu\'il était réellement mourant. Cette anecdote, l\'une des plus célèbres de l\'histoire du théâtre, illustre ironiquement le destin d\'un auteur qui avait passé sa vie à satiriser les médecins quacks et leurs patients crédules.</div>',

    'xixe/romantisme': '<h3>Le romantisme et la révolution politique</h3><p class="resume-text">Le romantisme français est indissociable de la politique révolutionnaire et post-révolutionnaire. Les romantiques de la première génération (Chateaubriand) sont souvent réactionnaires. La seconde génération (Hugo, Lamartine, Vigny) est libérale et républicaine. Hugo devient le poète de la Révolution de 1848, puis s\'exile sous Napoléon III pendant 19 ans. Les Misérables (1862), roman des damnés de la terre, illustre comment le romantisme tardif fusionne l\'esthétique lyrique avec l\'engagement politique au service des opprimés.</p><h3>Le roman historique romantique</h3><p class="resume-text">Walter Scott est le grand inspirateur du roman historique romantique français. Notre-Dame de Paris (Hugo, 1831), Cinq-Mars (Vigny), Les Chouans (Balzac) : ces romans font vivre des périodes historiques révolues avec un souci de la couleur locale et du détail archéologique que le Siècle des lumières n\'avait pas. Hugo reconstruit le Paris médiéval avec une érudition au service de l\'imagination. Cette conjonction d\'histoire et de fiction reste l\'une des formes romanesques les plus populaires jusqu\'à nos jours.</p><div class="highlight-box"><strong>Hernani (1830) : la bataille</strong> : La première représentation d\'Hernani de Victor Hugo le 25 février 1830 est devenue légendaire. Les partisans de Hugo (Théophile Gautier en gilet rouge, Balzac, Nerval) s\'opposèrent bruyamment aux classiques dans la salle de la Comédie-Française. Cette bataille symbolise le conflit générationnel entre les tenants des règles classiques et les romantiques réclamant la liberté artistique totale.</div>',

    'moyen-age/roman-courtois': '<h3>Chrétien de Troyes et la naissance du roman</h3><p class="resume-text">Chrétien de Troyes (actif vers 1160-1190) est généralement considéré comme le fondateur du roman en prose versifiée française et l\'inventeur du roman arthurien. Ses cinq romans — Érec et Énide, Lancelot ou le Chevalier de la charrette, Perceval ou le Conte du Graal (inachevé) — ont créé un univers cohérent d\'aventures chevaleresques et de quêtes spirituelles qui a engendré une tradition littéraire européenne pendant cinq siècles. La Matière de Bretagne qu\'il inaugure est l\'une des sources narratives les plus fécondes de la culture occidentale.</p><h3>La femme dans le roman courtois</h3><p class="resume-text">La figure féminine dans le roman courtois est paradoxale : à la fois objet du désir et sujet du pouvoir symbolique. La dame est inaccessible, hautaine, dispensatrice de grâce — elle détient le pouvoir dans la relation amoureuse, contrairement à la réalité sociale médiévale où les femmes sont soumises à l\'autorité du père puis du mari. Cette inversion symbolique a été interprétée diversement : idéalisation de la femme, reflet de la puissance réelle de certaines grandes dames. Les études de genre ont montré les ambiguïtés de ce « pouvoir » féminin purement symbolique.</p><div class="highlight-box"><strong>Tristan et Iseut</strong> : Le roman de Tristan et Iseut (XIIe siècle) est le grand récit de l\'amour passion dans la tradition européenne. Le philtre d\'amour bu par accident transforme un amour interdit en passion absolue, supérieure à tous les obstacles sociaux. Denis de Rougemont a vu dans ce mythe la matrice de la conception occidentale de l\'amour : la fascination pour l\'amour impossible, le romantisme de l\'obstacle et de la mort.</div>',

    'classicisme/voltaire-rousseau': '<h3>L\'Encyclopédie et le projet des Lumières</h3><p class="resume-text">L\'Encyclopédie ou Dictionnaire raisonné des sciences, des arts et des métiers (1751-1772), dirigée par Diderot et d\'Alembert avec la collaboration de Voltaire et Rousseau, est le monument emblématique des Lumières françaises. Son projet est politique autant qu\'intellectuel : rassembler et diffuser tout le savoir humain pour éclairer les esprits et réduire le pouvoir de l\'Église et des superstitions. Ses 28 volumes ont été censurés, interdits, saisis. Et pourtant, 25 000 exemplaires circulèrent en Europe.</p><h3>Voltaire et la lutte pour la tolérance</h3><p class="resume-text">Voltaire (1694-1778) est l\'archétype de l\'intellectuel engagé. Exilé en Angleterre après une bastonnade commanditée par le chevalier de Rohan (1726), il revient converti à l\'empirisme de Locke et à la physique de Newton. L\'affaire Calas (1762) révèle pleinement le Voltaire combattant : son Traité sur la Tolérance (1763), qui obtient la réhabilitation posthume de Calas, reste l\'un des textes fondateurs du combat pour les droits humains. Sa formule « Écrasez l\'infâme ! » dirigée contre le fanatisme religieux résume un combat de toute une vie.</p><div class="highlight-box"><strong>Les salons littéraires</strong> : Les salons tenus par des femmes de la haute bourgeoisie — Mme du Deffand, Julie de Lespinasse, Mme Geoffrin, Suzanne Necker — ont été les lieux centraux de circulation des idées des Lumières. Ces salonnières orientaient les discussions, finançaient des projets : Mme Geoffrin a largement subventionné l\'Encyclopédie. Ce réseau informel a joué un rôle capital que l\'institution académique officielle, plus conservatrice, n\'aurait pas permis.</div>',

    'xixe/realisme-naturalisme': '<h3>Balzac et la Comédie humaine</h3><p class="resume-text">Honoré de Balzac (1799-1850) a entrepris l\'une des œuvres romanesques les plus ambitieuses de la littérature mondiale : La Comédie humaine, une série de 90 romans et nouvelles liés par des personnages récurrents et formant un tableau complet de la société française. Rastignac, Vautrin, le père Goriot : ces personnages traversent plusieurs romans, vieillissent, évoluent. Cette technique du retour des personnages est une innovation narrative majeure qui donne à l\'œuvre une dimension encyclopédique. Balzac voulait faire en littérature ce que les naturalistes faisaient en biologie : cataloguer les espèces humaines dans leur milieu social.</p><h3>L\'affaire Dreyfus et l\'engagement de Zola</h3><p class="resume-text">Émile Zola (1840-1902) illustre le passage du naturalisme à l\'engagement politique par son célèbre « J\'accuse…! » (1898). La lettre ouverte au président de la République prend la défense d\'Alfred Dreyfus — officier juif condamné à tort — et dénonce les responsables de l\'injustice dans un contexte d\'antisémitisme virulent. Cette prise de position courageuse (Zola fut condamné et dut s\'exiler) a défini pour des générations le modèle de l\'intellectuel engagé dans la vie politique.</p><div class="highlight-box"><strong>Le procès de Madame Bovary</strong> : Publié en feuilleton dans La Revue de Paris (1856), Madame Bovary déclenche un procès pour outrage aux bonnes mœurs. Flaubert est acquitté, mais le procès révèle les tensions entre la liberté artistique du roman réaliste et les normes bourgeoises de la moralité. Le même mois, Baudelaire est condamné pour Les Fleurs du Mal — deux affaires marquant la résistance officielle à une nouvelle conception de la littérature.</div>',

    'classicisme/lumieres': '<h3>Montesquieu et la séparation des pouvoirs</h3><p class="resume-text">Charles-Louis de Secondat, baron de Montesquieu (1689-1755), est l\'auteur de L\'Esprit des lois (1748), l\'œuvre politico-philosophique la plus influente du siècle des Lumières. Sa théorie de la séparation des pouvoirs — législatif, exécutif, judiciaire — s\'appuie sur l\'observation du régime politique anglais. Cette théorie a inspiré les constituants américains de 1787 (Madison cite Montesquieu dans The Federalist Papers) et les révolutionnaires français de 1789. Elle reste le fondement théorique des démocraties constitutionnelles modernes.</p><h3>L\'héritage révolutionnaire des Lumières</h3><p class="resume-text">La relation entre les Lumières et la Révolution française est complexe et débattue. La Déclaration des Droits de l\'Homme et du Citoyen (1789) s\'inspire directement des philosophes : les droits naturels de Locke, la volonté générale de Rousseau, la séparation des pouvoirs de Montesquieu. Mais les philosophes n\'ont pas voulu la Révolution — la plupart étaient réformistes. Voltaire admirait le despotisme éclairé de Frédéric II et de Catherine II. C\'est une lecture sélective de leurs œuvres qui a fourni la justification idéologique des révolutionnaires.</p><div class="highlight-box"><strong>Rousseau contre les philosophes</strong> : Jean-Jacques Rousseau (1712-1778) occupe une place ambiguë parmi les philosophes des Lumières : il partage leur critique de l\'intolérance, mais s\'oppose à leur confiance dans le progrès des sciences et des arts. Son Premier Discours (1750) affirme que les sciences et les arts ont corrompu les mœurs. Le Contrat social (1762) est la base de la philosophie politique républicaine et démocratique. L\'Émile révolutionne la pédagogie en proposant une éducation naturelle respectueuse de l\'enfant.</div>',

    'moyen-age/rabelais': '<h3>Le rire comme philosophie chez Rabelais</h3><p class="resume-text">Rabelais (vers 1494-1553) place le rire au cœur de son projet philosophique et littéraire. Le prologue de Gargantua compare ses livres aux silènes — boîtes grotesques qui contiennent des trésors précieux. Ce rire rabelaisien n\'est pas simple amusement mais mode de connaissance : le comique carnavalesque (étudié par Mikhaïl Bakhtine) renverse les hiérarchies, démasque les impostures, libère de la peur. La philosophie du Thélème (« Fais ce que tu voudras ») exprime une confiance fondamentale dans la nature humaine éclairée par l\'éducation humaniste.</p><h3>La langue de Rabelais</h3><p class="resume-text">La langue de Rabelais est elle-même un monument de créativité linguistique de la Renaissance française. Ses romans sont un laboratoire lexical où coexistent vieux français, latin savant, dialectes régionaux, néologismes et jargons professionnels. L\'adjectif « pantagruélique » et le nom « Gargantua » — passés en plusieurs langues pour désigner quelque chose d\'énorme — témoignent de l\'impact de son imaginaire sur le vocabulaire commun. La langue de Rabelais exprime une jubilation du langage comme énergie vitale.</p><div class="highlight-box"><strong>L\'humanisme de la Renaissance</strong> : Rabelais est un humaniste au sens plein du terme — il maîtrise le latin, le grec, l\'hébreu, la médecine, le droit. La liste encyclopédique des livres de la bibliothèque Saint-Victor (satire des scolastiques) témoigne d\'une curiosité insatiable qui est la marque de l\'humanisme renaissant. Ses romans sont traversés par des débats intellectuels contemporains : la querelle des femmes, les réformes de l\'éducation, la médecine paracelsienne.</div>',

    'moyen-age/montaigne': '<h3>L\'essai comme genre nouveau</h3><p class="resume-text">Michel de Montaigne (1533-1592) invente avec les Essais (1580, 1588, posthume 1595) un genre littéraire entièrement nouveau : le texte en prose qui explore un sujet par la réflexion personnelle, l\'anecdote et l\'auto-observation. « Chaque homme porte la forme entière de l\'humaine condition » : c\'est en s\'étudiant lui-même que Montaigne prétend atteindre une vérité universelle. Le projet est philosophique et littéraire à la fois — c\'est la première grande autobiographie intellectuelle de la littérature française.</p><h3>L\'influence mondiale de Montaigne</h3><p class="resume-text">L\'influence de Montaigne sur la culture mondiale est considérable et se déploie dans des directions très diverses. Shakespeare a lu Montaigne dans la traduction de John Florio (1603) et s\'en est inspiré pour Hamlet et La Tempête. Pascal a écrit ses Pensées comme une réfutation de Montaigne. Au XXe siècle, Virginia Woolf lui consacre un essai admiratif, Stefan Zweig le lit pendant l\'exil nazi comme un compagnon de crise. Sa devise — « Que sais-je ? » — est restée l\'emblème de l\'humilité intellectuelle et de la pensée critique.</p><div class="highlight-box"><strong>Montaigne et les guerres de religion</strong> : Montaigne rédige ses Essais dans un contexte de guerres civiles religieuses d\'une violence extrême — huit guerres civiles entre 1562 et 1598, ponctuées par le massacre de la Saint-Barthélemy (1572). Montaigne, catholique modéré ayant des amis protestants, joue un rôle de médiateur et défend une tolérance pragmatique. Sa critique du fanatisme religieux est une prise de position courageuse dans un contexte de violence déchaînée.</div>',

    'xxe/proust': '<h3>La mémoire involontaire et la révolution proustienne</h3><p class="resume-text">Marcel Proust (1871-1922) a révolutionné le roman occidental avec À la recherche du temps perdu (7 volumes, 1913-1927). Sa découverte centrale — la mémoire involontaire, déclenchée par des sensations (la madeleine trempée dans le thé, les pavés irréguliers) — affirme que seule cette mémoire sensorielle permet d\'atteindre le temps passé dans sa vérité. Cette poétique de la sensation fait du roman proustien non pas un récit linéaire mais une exploration de la texture du temps et de l\'identité du sujet.</p><h3>Proust et le monde de l\'art</h3><p class="resume-text">La Recherche est traversée par une philosophie de l\'art : seul l\'art véritable peut arracher le temps à sa fuite. Le personnage du compositeur Vinteuil (inspiré de Fauré), du peintre Elstir (inspiré de Monet), de l\'écrivain Bergotte reflètent les réflexions de Proust sur la création artistique. Sa connaissance de la peinture hollandaise (Vermeer), de la musique wagnérienne, de l\'architecture gothique enrichit le texte d\'une profusion d\'œuvres d\'art réelles ou fictives qui font de la Recherche un traité esthétique autant qu\'un roman.</p><div class="highlight-box"><strong>La réception de Proust</strong> : La première édition de Du côté de chez Swann (1913) fut refusée par la NRF — Gide, qui le regretta toute sa vie — et publiée à compte d\'auteur. La Recherche est traduite en une quarantaine de langues et fait l\'objet d\'une industrie critique considérable. L\'adjectif « proustien » désigne dans plusieurs langues toute expérience de mémoire sensorielle intense — preuve de l\'entrée du romancier dans le langage commun de la culture mondiale.</div>',

    'xixe/flaubert-zola': '<h3>Madame Bovary et le bovarysme</h3><p class="resume-text">Madame Bovary (1857) de Gustave Flaubert est l\'un des romans les plus étudiés et les plus influents de la littérature mondiale. Emma Bovary — femme de médecin de province frustrée par l\'écart entre ses rêves romantiques et la médiocrité de sa vie — est devenue un archétype universel. Le philosophe Jules de Gaultier a forgé le terme « bovarysme » pour désigner « la puissance que détient l\'homme de se concevoir autre qu\'il n\'est » — cette tendance humaine à se projeter dans un idéal romanesque décalé de la réalité.</p><h3>L\'héritage du réalisme dans le roman contemporain</h3><p class="resume-text">Le réalisme de Flaubert et Zola a façonné le roman occidental pendant plus d\'un siècle. La technique du style indirect libre de Flaubert a influencé Henry James, Virginia Woolf et James Joyce. En France, le réalisme reste une référence permanente : contre le Nouveau Roman des années 1950-60 qui le rejette comme naïf, pour la littérature de terrain contemporaine (Édouard Louis, François Bon). Ce dialogue permanent avec le réalisme est constitutif de la littérature française moderne.</p><div class="highlight-box"><strong>Zola et Germinal</strong> : Germinal (1885), roman des mineurs du Nord, est l\'une des descriptions les plus puissantes de la misère ouvrière. La documentation que Zola accumule avant d\'écrire — descentes dans les mines, lectures de rapports d\'enquête — fonde le réalisme naturaliste sur une ethnographie du monde du travail. Au Bonheur des Dames décrit la révolution commerciale des grands magasins. Cette ambition encyclopédique fait de Zola le Balzac de la IIIe République.</div>',

    'xixe/hugo': '<h3>Les Misérables et la question sociale</h3><p class="resume-text">Les Misérables (1862) est l\'œuvre la plus lue de Victor Hugo et l\'un des romans les plus traduits du monde. Son propos est explicitement politique et social : plaidoyer pour les pauvres, les exclus, les enfants abandonnés. Jean Valjean, condamné pour avoir volé un pain, incarne la victime d\'une justice aveugle. Ce roman-fleuve est une cathédrale narrative dont la puissance émotionnelle explique ses adaptations incessantes en films, comédies musicales et bandes dessinées depuis 160 ans.</p><h3>Hugo et la création culturelle contemporaine</h3><p class="resume-text">L\'influence de Victor Hugo sur la culture populaire mondiale est sans équivalent dans la littérature française. Les Misérables ont été adaptés en 55 films, en comédie musicale (Broadway 1987), en séries télévisées, en mangas japonais. Notre-Dame de Paris a inspiré Disney et une comédie musicale française. La cathédrale elle-même doit en partie sa survie au roman de Hugo : le roman a suscité un mouvement de restauration qui a sauvé la cathédrale de la démolition — preuve du pouvoir de la littérature sur la réalité matérielle.</p><div class="highlight-box"><strong>Victor Hugo en exil</strong> : Après le coup d\'État de Napoléon III (1851), Victor Hugo refuse l\'amnistie et s\'exile pendant 19 ans. De Guernesey, il publie Les Châtiments (1853), pamphlet politique en vers contre « Napoléon le Petit », et Les Contemplations (1856), marqué par la mort de sa fille Léopoldine (noyée en 1843). Ce long exil volontaire en fait une figure de résistance morale et politique — un modèle pour tous les intellectuels en exil du XXe siècle.</div>',

    'xxe/nouveau-roman': '<h3>Le Nouveau Roman et la crise du récit</h3><p class="resume-text">Le Nouveau Roman (terme lancé par le journaliste Émile Henriot en 1957) regroupe des auteurs très différents — Nathalie Sarraute, Alain Robbe-Grillet, Michel Butor, Claude Simon — qui partagent une même insatisfaction avec les conventions du roman réaliste du XIXe siècle. Pour eux, le roman traditionnel avec ses personnages psychologiques cohérents, son narrateur omniscient est une mystification. Il faut renouveler les formes romanesques pour rendre compte d\'une expérience du monde fragmentée, opaque, répétitive.</p><h3>Claude Simon et le prix Nobel</h3><p class="resume-text">Claude Simon (1913-2005), prix Nobel de littérature en 1985, est l\'un des romanciers français les plus importants du XXe siècle. Ses romans — La Route des Flandres (1960), Les Géorgiques (1981) — explorent la mémoire de la guerre à travers une prose dense qui refuse la narration linéaire au profit d\'une reconstruction fragmentaire de l\'expérience. Le Nobel a consacré la légitimité internationale d\'un auteur difficile, exigeant, que la génération précédente avait parfois découragé les lecteurs d\'aborder.</p><div class="highlight-box"><strong>L\'OuLiPo</strong> : L\'OuLiPo (Ouvroir de Littérature Potentielle, fondé en 1960 par Raymond Queneau et François Le Lionnais) explore la contrainte formelle comme moteur de créativité. Écrire un roman de 300 pages sans la lettre e (La Disparition de Perec, 1969) ; composer un roman dont chaque chapitre suit une partie d\'échecs (La Vie mode d\'emploi de Perec, 1978) : ces expériences questionnent la nature même de la création littéraire et anticipent les enjeux de la génération automatique de texte par l\'intelligence artificielle.</div>',

    'xxe/existentialisme': '<h3>Sartre et la philosophie de l\'engagement</h3><p class="resume-text">Jean-Paul Sartre (1905-1980) est la figure centrale de l\'existentialisme français. Sa formule « l\'existence précède l\'essence » — l\'homme n\'a pas de nature prédéfinie, il se crée lui-même par ses choix — est le point de départ d\'une philosophie de la liberté et de la responsabilité radicales. « L\'homme est condamné à être libre » : pas de Dieu pour définir notre essence, pas de nature humaine pour excuser nos actes. Cette philosophie, populaisée dans L\'Existentialisme est un humanisme (1945), a eu un retentissement mondial.</p><h3>Camus et l\'absurde</h3><p class="resume-text">Albert Camus (1913-1960) développe une philosophie de l\'absurde souvent associée à tort à l\'existentialisme sartrien. La rupture avec Sartre (1952, lors du débat sur les camps soviétiques) révèle deux postures irréconciliables : Sartre, marxiste proche du PC, sacrifie la justice présente à la révolution future ; Camus, méditerranéen né en Algérie, refuse tout sacrifice de l\'homme réel sur l\'autel d\'une idéologie abstraite. Cette querelle a marqué la vie intellectuelle française des années 1950 et reste d\'une actualité brûlante.</p><div class="highlight-box"><strong>Simone de Beauvoir</strong> : Simone de Beauvoir (1908-1986) applique les catégories existentialistes à la condition féminine dans Le Deuxième Sexe (1949) : « On ne naît pas femme : on le devient. » La féminité n\'est pas une essence biologique mais une construction sociale. Ce texte fondateur du féminisme contemporain a eu un impact mondial considérable, inspirant les mouvements féministes de la deuxième vague des années 1960-70 aux États-Unis et en Europe.</div>',

    'xxe/contemporaine': '<h3>Annie Ernaux et l\'autosociobiographie</h3><p class="resume-text">Annie Ernaux (née en 1940), prix Nobel de littérature 2022, a développé l\'« auto-socio-biographie » — une forme littéraire qui explore sa propre vie non comme confession intime mais comme matériau d\'une enquête sur les déterminismes sociaux et les trajectoires de classe. Dans La Place (1984), elle reconstruit la vie de son père ouvrier-commerçant en adoptant une écriture blanche, neutre — pour ne pas trahir un père qui ne lisait pas de littérature. Ce projet fait d\'Ernaux l\'héritière à la fois de Flaubert, de Bourdieu et de Beauvoir.</p><h3>Le numérique et les nouvelles formes de littérature</h3><p class="resume-text">Les nouvelles technologies ont transformé les pratiques littéraires depuis les années 2000. L\'autoédition numérique a ouvert la publication à des milliers d\'auteurs sans intermédiaire éditorial. Wattpad (plateforme de fiction participative avec 90 millions d\'utilisateurs) et la fanfiction témoignent d\'une culture littéraire participative nouvelle. Ces mutations posent des questions sur la définition même de la littérature et sur la valeur de la médiation éditoriale traditionnelle dans l\'ère numérique.</p><div class="highlight-box"><strong>La rentrée littéraire</strong> : La France publie chaque année environ 500 romans lors de la rentrée littéraire de septembre, une institution unique au monde. Les grands prix — Goncourt, Renaudot, Femina, Médicis — couronnent des œuvres qui voient leurs ventes décuplées overnight. Cette institutionnalisation de la vie littéraire maintient une attention publique sur la littérature mais favorise certains types de romans au détriment d\'autres — créant un équilibre difficile entre prestige et diversité.</div>',

    'xxe/francophone': '<h3>Aimé Césaire et la Négritude</h3><p class="resume-text">Aimé Césaire (1913-2008), poète et homme politique martiniquais, est avec Léopold Sédar Senghor et Léon-Gontran Damas le fondateur du mouvement de la Négritude (années 1930-40). Contre l\'assimilation culturelle coloniale, la Négritude revendique fièrement l\'identité noire et l\'héritage africain. Le Cahier d\'un retour au pays natal (1939) est le manifeste poétique de ce mouvement. La Lettre des romanciers pour une littérature-monde en français (Le Monde, 2007), signée par 44 auteurs, prolonge ce combat pour une littérature française décentrée de Paris.</p><h3>La littérature du Maghreb</h3><p class="resume-text">La littérature maghrébine de langue française — Kateb Yacine (Nedjma, 1956), Assia Djebar, Tahar Ben Jelloun (La Nuit sacrée, Goncourt 1987), Leïla Slimani — explore la complexité de l\'identité post-coloniale : entre langue française et langues maternelles (arabe, berbère), entre tradition et modernité, entre les deux rives de la Méditerranée. Cette littérature a introduit des thèmes nouveaux (la guerre d\'Algérie, l\'identité féminine) et des sensibilités qui ont contribué à la décentration de la littérature française.</p><div class="highlight-box"><strong>Patrick Chamoiseau et la créolisation</strong> : Patrick Chamoiseau (né en 1953) est l\'une des voix les plus importantes de la littérature antillaise. Son roman Texaco (1992, Prix Goncourt) créolise le français, intègre des mots créoles, joue avec les rythmes d\'une culture orale afro-antillaise. Cette créolisation de la langue française — théorisée par Édouard Glissant comme alternative à l\'assimilation — est l\'une des voies les plus fécondes d\'un renouvellement du roman français depuis les années 1990.</div>',

    'xixe/baudelaire': '<h3>Baudelaire et la modernité poétique</h3><p class="resume-text">Charles Baudelaire (1821-1867) est le poète de la modernité par excellence — non pas parce qu\'il célèbre le progrès mais parce qu\'il est le premier à faire de la ville moderne, de ses foules et de sa laideur, la matière d\'une haute poésie. Le baudelairien « flâneur » — observateur solitaire de la foule parisienne — est devenu l\'archétype du sujet urbain moderne. Sa revendication que l\'art doit saisir « le transitoire, le fugitif, le contingent » (Le Peintre de la vie moderne, 1863) a défini un programme esthétique dont les symbolistes et les surréalistes ont hérité.</p><h3>Baudelaire et les arts</h3><p class="resume-text">Baudelaire est aussi le plus grand critique d\'art français du XIXe siècle. Ses Salons révèlent Delacroix comme génie romantique, défendent Courbet et Daumier. Sa traduction des œuvres d\'Edgar Poe en français (1856-1865) est remarquablement fidèle et a durablement installé Poe dans la culture française — au point que Poe est souvent mieux connu et estimé en France qu\'aux États-Unis. Cette sensibilité aux arts visuels et à la musique (il est l\'un des premiers à reconnaître le génie de Wagner en France) fait de Baudelaire un critique artistique autant qu\'un poète.</p><div class="highlight-box"><strong>Les Correspondances et le symbolisme</strong> : Le sonnet des Correspondances (1857) est peut-être le poème français le plus influent du XIXe siècle. « Les parfums, les couleurs et les sons se répondent » : cette synesthésie poétique — les sens communiquent entre eux dans une unité secrète du monde — est le fondement du symbolisme. Mallarmé, Verlaine, Rimbaud, puis les poètes symbolistes européens ont exploré cette correspondance secrète entre l\'intériorité du sujet et le monde sensible.</div>',
}


def enrich_content(content, new_html):
    quiz_marker = '<section class="content-section" id="quiz">'
    idx = content.find(quiz_marker)
    if idx != -1:
        return content[:idx] + new_html + content[idx:]
    last_section = content.rfind('</section>')
    if last_section != -1:
        return content[:last_section] + new_html + content[last_section:]
    return content + new_html


with open(INPUT_FILE, 'r', encoding='utf-8') as f:
    data = json.load(f)

pages = data.get('pages', {})
modified = 0
skipped = 0

for key, html in ADDITIONS.items():
    if key not in pages:
        print(f'SKIP (not found): {key}')
        skipped += 1
        continue

    page = pages[key]
    current_content = page.get('content', '') or ''

    if len(current_content) >= 15000:
        print(f'SKIP (already >= 15000): {key} ({len(current_content)} chars)')
        skipped += 1
        continue

    new_content = enrich_content(current_content, html)
    pages[key]['content'] = new_content
    status = 'OK' if len(new_content) >= 15000 else 'PARTIAL'
    print(f'{status}: {key} ({len(current_content)} -> {len(new_content)} chars)')
    modified += 1

data['pages'] = pages

with open(INPUT_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'\nDone: {modified} articles enriched, {skipped} skipped.')
