#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichit tous les articles de linguistique.json pour atteindre ~15000 chars."""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/linguistique.json'
QUIZ_MARKER = '<section class="content-section" id="quiz">'

ENRICHMENTS = {
    'phonetique/appareil-phonatoire': """<h3>La voix et ses pathologies</h3>
<p class="resume-text">Les troubles de la voix (dysphonie) affectent environ 7% de la population mondiale à un moment de leur vie. La laryngite, les nodules vocaux (affection professionnelle des enseignants et chanteurs), les paralysies des cordes vocales et les cancers du larynx illustrent la vulnérabilité de cet instrument délicat. L'orthophonie travaille avec des exercices de rééducation vocale pour restaurer une phonation efficace et indolore.</p>
<p class="resume-text">Les techniques modernes d'imagerie (nasofibroscopie, stroboscopie laryngée, électroglottographie) permettent d'observer le larynx en temps réel pendant la phonation. Ces outils cliniques et de recherche ont révolutionné notre compréhension de la production vocale et permis de développer des interventions chirurgicales microscopiques (phonochirurgie) d'une précision extrême. La synthèse vocale et les prothèses vocales électroniques offrent des solutions aux patients dont les cordes vocales ont été ablates.</p>
<div class="highlight-box"><p>Le castrat, voix d'homme castré avant la puberté pour conserver le registre de soprane avec une puissance de poumons adultes, fut la star de l'opéra baroque aux XVIIe-XVIIIe siècles. La castration empêche l'action des androgènes sur le larynx, préservant les cordes vocales courtes tout en permettant le développement du thorax. Farinelli (1705-1782) était le plus célèbre ; sa voix couvrait trois octaves.</p></div>
<h3>L'acoustique de la parole et la reconnaissance vocale</h3>
<p class="resume-text">L'acoustique de la parole étudie les propriétés physiques du signal sonore : fréquence fondamentale (hauteur), intensité (volume), durée, et structure spectrale (formants). Les spectrogrammes — représentations visuelles de l'énergie acoustique en fonction du temps et de la fréquence — permettent d'analyser objectivement le signal de parole. Les formants F1 (hauteur basse) et F2 (hauteur haute) permettent d'identifier les voyelles avec précision.</p>
<p class="resume-text">La reconnaissance automatique de la parole (ASR) repose sur des modèles statistiques qui associent des séquences acoustiques à des séquences de mots. Les assistants vocaux (Siri, Alexa, Google Assistant) utilisent des réseaux de neurones profonds entraînés sur des millions d'heures de parole. Ces systèmes atteignent aujourd'hui des taux d'erreur inférieurs à 5% dans des conditions d'usage favorable — comparables aux performances humaines. Ils peinent encore avec les accents marqués, les dialectes et les environnements bruités.</p>
<h3>Diversité des organes articulatoires dans les langues du monde</h3>
<p class="resume-text">Les langues du monde exploitent des lieux d'articulation variés. Les clics des langues khoïsanes (comme le !Kung ou le zoulou) utilisent un mécanisme vélaire : une pression d'air créée entre le dos de la langue et le voile du palais produit une aspiration lors de la détente d'un contact antérieur. Les consonnes pharyngales de l'arabe impliquent une constriction au niveau du pharynx. Les labio-dentales sonores (comme le [v] de « vin ») et les interdentales (le [θ] anglais de « think ») illustrent la diversité articulatoire.</p>
<p class="resume-text">Les tons lexicaux, présents dans plus de la moitié des langues du monde (mandarin, cantonais, vietnamien, yoruba, thaï), utilisent la hauteur mélodique pour distinguer des mots différents. En mandarin, « mā » (ton plat, mère), « má » (ton montant, chanvre), « mǎ » (ton descendant-montant, cheval), « mà » (ton descendant, gronder) sont quatre mots distincts écrits avec les mêmes lettres. Cette dimension de la phonologie, absente du français et de l'anglais, est fondamentale pour des milliards de locuteurs dans le monde.</p>""",

    'phonetique/voyelles-consonnes': """<h3>Le quadrilatère vocalique et les systèmes de voyelles</h3>
<p class="resume-text">Le quadrilatère vocalique de l'API représente les voyelles selon deux axes : le degré d'aperture (ouverture de la mâchoire) et le lieu d'articulation antéropostérieur (position de la masse de la langue). Les quatre voyelles cardinales primaires sont [i] (fermée antérieure), [u] (fermée postérieure), [a] (ouverte centrale) et [ɑ] (ouverte postérieure). Les autres voyelles se positionnent entre ces poles, formant un espace phonétique continu que chaque langue découpe différemment.</p>
<p class="resume-text">Le français distingue les voyelles nasales ([ɑ̃] dans « vent », [ɛ̃] dans « vin », [ɔ̃] dans « bon ») qui n'existent pas en anglais standard. Le polonais a des voyelles nasales différentes. L'allemand oppose les voyelles longues aux voyelles courtes (quantité vocalique). Le japonais n'a que cinq voyelles. Cette diversité montre que les systèmes vocaliques sont des constructions conventionnelles qui varient considérablement d'une langue à l'autre, même si les voyelles cardinales [i], [a], [u] sont quasi-universelles.</p>
<div class="highlight-box"><p>Le « Great Vowel Shift » anglais (XIVe-XVIIe siècle) est un changement systématique qui a modifié toutes les voyelles longues de l'anglais. Avant le shift, « mouse » se prononçait comme le français « mousse » ; « time » comme « teem ». Ce changement explique en grande partie les difficultés de la prononciation anglaise : l'orthographe conserve la prononciation ancienne tandis que la prononciation a radicalement changé.</p></div>
<h3>Les consonnes : modes et lieux d'articulation</h3>
<p class="resume-text">Le mode d'articulation décrit la façon dont le flux d'air est modifié : les occlusives (arrêt complet puis relâchement : [p], [b], [t], [d], [k], [g]), les fricatives (constriction créant de la turbulence : [f], [v], [s], [z], [ʃ], [ʒ]), les affriquées (combinaison d'occlusif et fricatif : [tʃ] en anglais « church », [dʒ] en « judge »), les nasales (air passe par le nez : [m], [n], [ɲ]), les liquides (latérales [l] et rhotiques [r]) et les semi-voyelles (ou approximantes : [w], [j]).</p>
<p class="resume-text">La distinction voisé/non-voisé (présence ou absence de vibration des cordes vocales) est phonémique dans de nombreuses langues : [p] est non-voisé, [b] est voisé ; [f] est non-voisé, [v] est voisé. Mais en mandarin, cette distinction n'existe pas pour les occlusives : la distinction porte sur l'aspiration (souffle d'air supplémentaire). En anglais, [p] aspiré (comme dans « pin ») et [p] non aspiré (comme dans « spin ») sont des allophones du même phonème, tandis qu'ils correspondent à des phonèmes distincts en hindi et en thaï.</p>
<h3>Phonétique instrumentale et neurosciences</h3>
<p class="resume-text">La phonétique expérimentale utilise de nombreux instruments : électropalatographie (pour localiser les contacts langue-palais), vélopalatographie (pour mesurer l'aperture du voile du palais), articulographie électromagnétique (pour suivre les mouvements articulatoires en temps réel), imagerie par résonance magnétique (IRM) pour les reconstructions 3D du conduit vocal. Ces techniques permettent d'observer directement ce qui se passe dans la bouche pendant la parole, invisible à l'œil nu.</p>
<p class="resume-text">Les neurosciences de la parole ont identifié les régions cérébrales impliquées dans la production et la perception de la parole. L'aire de Broca (cortex frontal gauche) est impliquée dans la production syntaxique et phonologique. L'aire de Wernicke (cortex temporal gauche) est cruciale pour la compréhension. Les lésions de ces zones produisent respectivement l'aphasie de Broca (parole difficile mais compréhension préservée) et l'aphasie de Wernicke (fluidité préservée mais incompréhensible et mauvaise compréhension).</p>""",

    'phonetique/phonemes-allophones': """<h3>La phonologie en réseau : approches cognitives</h3>
<p class="resume-text">La phonologie de gouvernement (Kaye, Lowenstamm, Vergnaud) et la phonologie optimale (Prince, Smolensky) ont succédé à la phonologie générative standard pour rendre compte de phénomènes phonologiques complexes. La phonologie optimale (OT) postule que les formes de surface résultent d'une compétition entre contraintes universelles : une forme gagne si elle satisfait mieux que les autres le classement des contraintes spécifiques à la langue. Cette approche a produit des analyses élégantes des phénomènes d'harmonie vocalique, de syllabation et d'assimilation.</p>
<p class="resume-text">Les modèles exemplaristes (Pierrehumbert) proposent que les phonèmes ne sont pas des abstractions mentales mais des nuages de représentations mémorisées d'occurrences phonétiques réelles. Chaque fois qu'on entend un [a], le souvenir acoustique de cette occurrence s'ajoute à la représentation mentale du phonème /a/. Cette vision probabiliste de la phonologie, inspirée de la psychologie cognitive et de l'apprentissage automatique, challenge les conceptions classiques de l'abstraction phonologique.</p>
<div class="highlight-box"><p>L'effet McGurk (découvert en 1976) illustre l'interaction entre vision et audition dans la perception de la parole : si on entend /ba/ mais on voit une bouche qui articule /ga/, on perçoit /da/. Cette illusion audiovisu elle montre que la perception de la parole est multimodale et que le cerveau intègre plusieurs sources d'information pour construire la représentation phonémique.</p></div>
<h3>La perception catégorielle et les frontières phonémiques</h3>
<p class="resume-text">Un phénomène remarquable de la perception de la parole est la perception catégorielle : bien que les signaux acoustiques varient de façon continue (le VOT — Voice Onset Time — du début de la vibration des cordes vocales varie de façon graduée), les auditeurs perçoivent des catégories discrètes. Il n'y a pas de son intermédiaire entre /p/ et /b/ : à un certain seuil, la perception « bascule » catégoriquement. Cette perception catégorielle est partiellement innée (les nourrissons la montrent) mais se renforce avec l'exposition à la langue maternelle.</p>
<p class="resume-text">Des expériences cross-linguistiques ont montré que les nourrissons naissent avec une capacité à discriminer toutes les distinctions phonémiques de toutes les langues du monde, et que cette capacité se rétrécit progressivement pour se spécialiser sur les contrastes de la langue maternelle. Un nourrisson japonais de 6 mois discrimine /r/ et /l/ anglais ; un adulte japonais ne peut plus. Cette « période sensible » de la perception phonémique illustre la plasticité du système perceptif linguistique.</p>
<h3>Allophones et variation contextuelle</h3>
<p class="resume-text">Les allophones d'un même phonème peuvent être très différents acoustiquement tout en étant perçus comme « le même son » par les locuteurs natifs. En anglais, le /l/ en début de syllabe (light) est « clair » (alvéolaire latérale) tandis que le /l/ en fin de syllabe (full) est « sombre » (vélaire : la langue est relevée vers le voile du palais). Les Français entendent souvent les deux comme très différents, alors que les anglophones ne perçoivent qu'un seul /l/. Cette imperméabilité aux variations allophoniques est le signe d'une phonologie maternelle bien intégrée.</p>
<p class="resume-text">La notion d'assimilation régressive (une consonne se modifie sous l'influence de la consonne qui suit) est universelle. En français, « absence » se prononce avec un [p] dans la chaîne parlée rapide (les lèvres anticipent le [b] suivant). Le débit de parole affecte les réalisations allophoniques : en parole lente et soignée, les allophones sont moins marqués ; en parole rapide et familière, les assimilations s'intensifient et des syncopes se produisent. Cette variation stylistique témoigne de la flexibilité des représentations phonologiques.</p>""",

    'phonetique/prosodie': """<h3>Prosodie et émotions</h3>
<p class="resume-text">La prosodie est le vecteur principal des émotions dans la parole. La joie se manifeste par une voix haute, rapide, avec une grande variabilité mélodique. La tristesse est associée à une voix basse, lente, monotone. La colère produit une voix forte, haute, avec des contours mélodiques abruptes. Ces universaux prosodiques émotionnels sont reconnus cross-culturellement : des auditeurs japonais identifient les émotions dans des voix finnoises, et vice versa, même sans comprendre les mots.</p>
<p class="resume-text">Les troubles de la prosodie affective (aprosodias) accompagnent souvent les lésions de l'hémisphère droit : le patient parle d'une façon monotone, incapable de varier sa mélodie pour exprimer ou percevoir les émotions. Ces troubles sont distincts des aphasies classiques (hémisphère gauche) : le patient peut construire des phrases grammaticalement correctes mais sans couleur émotionnelle. Dans les troubles du spectre autistique, la prosodie atypique (voix robotique, intonation monotone) est souvent l'un des premiers signes observés.</p>
<div class="highlight-box"><p>Le sarcasme et l'ironie reposent presque entièrement sur la prosodie : « C'est vraiment une excellente idée » dit avec une intonation plate et descendante signifie le contraire de ce que les mots disent. Les enfants développent la sensibilité à l'intonation sarcastique vers 5-6 ans. Les patients souffrant de lésions du cortex préfrontal ont du mal à détecter le sarcasme, même quand la prosodie est nettement ironique.</p></div>
<h3>Prosodie et acquisition du langage</h3>
<p class="resume-text">Les nourrissons sont sensibles à la prosodie avant même de comprendre les mots. Dès la naissance, ils préfèrent la voix de leur mère à d'autres voix, et préfèrent entendre la langue de leur mère à d'autres langues — grâce à la prosodie perçue in utero. Le « langage bébé » (infant-directed speech ou motherese) utilisé spontanément par les adultes s'adressant aux bébés se caractérise par une mélodie exagérée, un débit ralenti et des syllabes plus nettes : ces modifications prosodiques semblent faciliter l'acquisition phonologique.</p>
<p class="resume-text">La prosodie guide le découpage de la chaîne parlée en mots et en phrases. Les pauses, allongements et ruptures mélodiques indiquent les frontières de groupes syntaxiques. Des expériences avec des langues artificielles montrent que les nourrissons de 8 mois utilisent les régularités statistiques de la prosodie pour segmenter la parole en unités. Cette capacité de « bootstrpping prosodique » est une étape fondamentale dans l'acquisition du langage.</p>
<h3>Prosodie et style</h3>
<p class="resume-text">Les différences prosodiques sont au cœur des stéréotypes dialectaux et régionaux. L'accent du Midi est reconnu par sa mélodie caractéristique et ses syllabes finales allongées. L'accent belge diffère du français de Paris par ses contours mélodiques. L'anglais britannique « Received Pronunciation » et l'anglais américain « General American » diffèrent notamment par leur rythme (syllabe-timing vs stress-timing). Ces marques prosodiques sont souvent les dernières à disparaître chez les locuteurs qui cherchent à modifier leur accent.</p>
<p class="resume-text">La prosodie du discours public (rhétorique, sermon, plaidoirie, discours politique) est minutieusement étudiée. Les grands orateurs (de Cicéron à Martin Luther King Jr.) maîtrisaient l'art de la pause, de l'accélération dramatique, du ralentissement solennel et de la progression mélodique vers un climax. Ces techniques sont enseignées dans les écoles de rhétorique et demeurent cruciales pour tout locuteur public, qu'il s'agisse d'un avocat, d'un professeur ou d'un politicien.</p>""",

    'phonetique/phonologie-processus': """<h3>L'harmonie vocalique : un processus à longue portée</h3>
<p class="resume-text">L'harmonie vocalique est un phénomène de cooccurrence de voyelles d'une même classe dans un mot. En turc, les voyelles d'un mot appartiennent toutes au groupe antérieur ou au groupe postérieur : « ev » (maison) prend l'suffixe « -ler » (« evler », maisons) car « e » est antérieure, tandis que « kız » (fille) prend « -lar » (« kızlar », filles) car « ı » est postérieure. Cette contrainte de compatibilité harmonique peut s'étendre sur plusieurs suffixes.</p>
<p class="resume-text">Le mongol, le finnois, l'hongrois, le wolof et de nombreuses langues altaïques présentent des systèmes d'harmonie vocalique d'une grande sophistication. Ces systèmes montrent que la phonologie peut opérer à un niveau plus large que le segment individuel. La théorie autosegmentale (Goldsmith, 1976) a modélisé ces phénomènes en dissociant les traits (notamment le trait de hauteur de la langue) du segment consonantique-vocalique, permettant la propagation des traits à travers plusieurs segments.</p>
<div class="highlight-box"><p>La métaphonie napolitaine est un processus remarquable par sa portée : une voyelle finale fermée ([u] ou [i]) provoque la fermeture de la voyelle tonique de la syllabe initiale, même si elles sont séparées par plusieurs syllabes. Ce phénomène de longue portée défie les conceptions locales de l'assimilation et témoigne de la réalité de constituants prosodiques suprasegmentaux.</p></div>
<h3>La syllabe et la structure prosodique</h3>
<p class="resume-text">La syllabe est l'unité phonologique minimale de la parole. Elle se compose généralement d'une attaque (consonnes initiales), d'un noyau (voyelle ou syllabe) et d'une coda (consonnes finales). Les langues diffèrent considérablement dans les structures syllabiques qu'elles autorisent. Le japonais ne permet que des syllabes de type V ou CV (ouverte), d'où la difficulté pour les Japonais avec les groupes consonantiques anglais. Le géorgien admet des attaques extrêmement complexes : « mts'vrtneli » (entraîneur) commence par six consonnes consécutives.</p>
<p class="resume-text">La structure prosodique hiérarchise la syllabe dans des constituants de plus en plus grands : syllabe → pied → mot phonologique → groupe clitique → phrase phonologique → énoncé. Cette hiérarchie prosodique, développée dans les travaux de Nespor et Vogel, permet de rendre compte d'une grande variété de phénomènes phonologiques dont les domaines d'application correspondent à ces constituants. La liaison française, par exemple, opère à l'intérieur du groupe clitique mais pas entre groupes clitiques.</p>
<h3>Changements phonologiques historiques</h3>
<p class="resume-text">Les lois phonétiques régulières — changements systématiques affectant tous les mots d'une même classe phonologique — sont le fondement de la linguistique comparative. La loi de Grimm (1822) décrit la mutation consonantique du proto-indo-européen au germanique : les occlusives aspirées deviennent des fricatives, les occlusives voisées deviennent non voisées, les non voisées deviennent des fricatives. Ainsi, le [p] latin correspond à [f] anglais (pater/father, piscis/fish), le [t] à [th] (tres/three, tenuis/thin).</p>
<p class="resume-text">Ces correspondances régulières permettent de reconstruire les langues ancestrales sans témoignage écrit. La méthode comparative a permis de reconstruire le proto-indo-européen (environ 4000 av. J.-C.) avec une précision surprenante — même si cette langue n'a jamais été écrite. Des logiciels d'apprentissage automatique permettent aujourd'hui d'appliquer ces méthodes à grande échelle pour détecter automatiquement les correspondances régulières entre langues et construire des arbres généalogiques phylogénétiques.</p>""",

    'morphologie/morphemes': """<h3>Morphologie constructionnelle et lexique mental</h3>
<p class="resume-text">Le lexique mental — l'ensemble des mots stockés dans notre mémoire — n'est pas un simple dictionnaire : il est organisé par des relations morphologiques. Les mots dérivés (préfixation, suffixation, composition) sont partiellement prédictibles à partir de la base et des affixes. Des expériences de temps de réaction montrent que les locuteurs reconnaissent plus rapidement des mots morphologiquement complexes fréquents que des mots morphologiquement simples mais rares, suggérant un accès lexical qui tient compte de la structure morphologique.</p>
<p class="resume-text">La morphologie dérivationnelle crée de nouveaux mots à partir de bases existantes. En français, le suffixe « -eur » peut créer des noms d'agent (vendeur, nageur), des noms d'instrument (aspirateur, radiateur) ou des noms de propriété (blancheur, douceur). Ces différentes valeurs sémantiques sont associées à des contraintes distributionnelles et phonologiques complexes que les locuteurs maîtrisent implicitement sans avoir été explicitement enseignés. Cette connaissance implicite est l'objet de la morphologie acquise.</p>
<div class="highlight-box"><p>La créativité morphologique spontanée dans les langues des signes est un terrain d'investigation passionnant : les signes peuvent être modifiés spatialement pour encoder des informations morphologiques (accord verbal, aspect, nombre). Cette iconicité morphologique des langues des signes montre que la morphologie peut reposer sur des analogies spatiales aussi bien que sur des affixes conventionnels arbitraires.</p></div>
<h3>Les morphèmes et la traductibilité</h3>
<p class="resume-text">La non-correspondance morphème-à-morphème entre les langues est une source majeure de difficultés de traduction. L'allemand « Schadenfreude » (joie tirée du malheur d'autrui) n'a pas d'équivalent en un seul mot français. Le japonais « Ma » désigne l'espace négatif, la pause chargée de sens — une notion sans équivalent en français. L'inuktitut peut encoder en un seul mot ce que le français exprime en une phrase entière. Ces différences structurales témoignent de la façon dont les langues découpent l'expérience humaine de façon non-universelle.</p>
<p class="resume-text">La morphologie inflectionnelle encode les informations grammaticales obligatoires dans une langue : le temps, l'aspect, le mode, la personne, le nombre, le genre, le cas. Ces catégories ne sont pas universelles : le mandarin n'a pas de flexion verbale temporelle obligatoire (le temps est exprimé par des adverbes ou le contexte). Le turc encode obligatoirement si l'information est de première main (evidentialité directe) ou rapportée (evidentialité indirecte). Ces catégories grammaticalisées révèlent ce que chaque culture juge important à exprimer obligatoirement.</p>""",

    'morphologie/flexion': """<h3>La flexion verbale et le système des temps</h3>
<p class="resume-text">Les systèmes verbaux des langues du monde varient considérablement. Le français distingue 6 temps de l'indicatif (présent, imparfait, futur simple, passé simple, passé composé, plus-que-parfait) plus les modes (subjonctif, conditionnel, impératif). Le mandarin n'a pas de flexion temporelle : le temps est exprimé par des adverbes contextuels ou des auxiliaires de phase. Le swahili encode le temps dans des préfixes verbaux avec une finesse temporelle remarquable (passé immédiat, passé d'aujourd'hui, passé d'avant-hier, etc.).</p>
<p class="resume-text">L'aspect (la façon de concevoir le déroulement interne du procès) est une catégorie souvent confondue avec le temps. L'opposition perfectif/imperfectif — action vue comme un tout achevé ou comme un déroulement en cours — est fondamentale dans les langues slaves (le russe distingue pour chaque verbe une forme perfective et une forme imperfective). En grec ancien, l'opposition aoriste/présent encode l'aspect ; en anglais, l'opposition « simple/progressive » (I worked vs. I was working) est aspectuelle.</p>
<div class="highlight-box"><p>Le subjonctif, mode exprimant la subjectivité, le doute ou la dépendance syntaxique, est en régression dans de nombreuses langues romanes mais se maintient en français littéraire et formel. Son usage correct est un marqueur social puissant : « Bien qu'il soit parti » vs. « Bien qu'il est parti ». Les études sociolinguistiques montrent que le maintien du subjonctif est corrélé au niveau d'éducation et au registre de langue.</p></div>
<h3>Accord grammatical et marquage de tête</h3>
<p class="resume-text">L'accord grammatical est un phénomène de dépendance morphologique entre constituants syntaxiques : un adjectif français s'accorde en genre et en nombre avec le nom qu'il modifie (« les grandes maisons »). En latin, les accords de cas s'étendent à travers tous les modificateurs d'un nom. En basque, le verbe s'accorde avec tous ses arguments (sujet, objet direct, objet indirect) selon un système ergatif-absolutif.</p>
<p class="resume-text">Les langues varient selon leur type de marquage : le marquage de tête (l'information grammaticale est portée par la tête du syntagme) s'oppose au marquage de dépendant (l'information est portée par les éléments subordonnés). Le français marque surtout le dépendant (l'adjectif s'accorde avec le nom-tête). Dans certaines langues amérindiennes, c'est la tête verbale qui marque toutes les relations grammaticales de la phrase, concentrant une quantité considérable d'information morphologique sur le verbe.</p>""",

    'morphologie/derivation': """<h3>Les schèmes arabes et l'entrelacement morphémique</h3>
<p class="resume-text">L'arabe et les langues sémitiques en général utilisent une morphologie d'entrelacement (non-concaténative) : une racine consonantique abstraite (généralement tri-consonantique) est entrelacée avec un schème vocalique pour former différentes dérivations. La racine k-t-b est liée à l'écriture : kataba (il a écrit), kātib (écrivain), kitāb (livre), maktab (bureau), maktaba (bibliothèque), kuttāb (école). Ce système produit des familles morphologiques d'une cohérence remarquable et permet de créer de nouveaux mots avec une régularité prédictible.</p>
<p class="resume-text">Ce type de morphologie non-concaténative est fascinant pour la théorie morphologique : les morphèmes (racine et schème) ne se succèdent pas linéairement mais s'interpénètrent. La théorie de la morphologie prosodique (McCarthy, 1979) a développé un cadre formel pour rendre compte de ces phénomènes en distinguant la grille prosodique (qui spécifie le schème) de la mélodie consonantique (la racine). Ces analyses ont renouvelé la compréhension de la morphologie comme phénomène pluridimensionnel.</p>
<div class="highlight-box"><p>Le lexique des langues modernes grossit constamment par dérivation et composition. Le français ajoute chaque année de nombreux néologismes : « covidé », « visioconférence », « ubérisation ». Ces néologismes suivent les schèmes dérivationnels productifs existants et sont généralement compréhensibles immédiatement par les locuteurs, même s'ils n'ont jamais entendu le mot. Cette compréhension immédiate révèle la puissance prédictive des règles morphologiques internalisées.</p></div>
<h3>La dérivation et les glissements sémantiques</h3>
<p class="resume-text">La dérivation ne modifie pas seulement la catégorie grammaticale ou le sens de façon mécanique : elle peut produire des glissements sémantiques parfois imprévisibles. « Papier » (nom) → « paperasse » (péjoratif de « papier »). « Amour » → « amoureux » (qui ressent de l'amour). « Vert » → « verdure » (ensemble des plantes vertes). Ces glissements montrent que la morphologie dérivationnelle interagit avec la sémantique lexicale de façons complexes qui ne sont pas totalement prédictibles.</p>
<p class="resume-text">La dérivation régressive (ou dérivation par troncation) produit des mots à partir d'autres mots par suppression d'éléments : « invasion » → « invader » en anglais (backformation), ou en français « cordon-bleu » (cuisinier expert, du ruban qui distinguait les hauts dignitaires de l'Ordre du Saint-Esprit). Ces formes rétroformées témoignent d'une réanalyse morphologique par les locuteurs, qui « déduisent » une base là où il n'y en avait pas.</p>""",

    'morphologie/composition': """<h3>La composition en allemand : un laboratoire morphologique</h3>
<p class="resume-text">L'allemand est célèbre pour ses mots composés potentiellement illimités : « Kraftfahrzeughaftpflichtversicherung » (assurance responsabilité civile automobile), « Donaudampfschifffahrtsgesellschaftskapitän » (capitaine de la compagnie de navigation à vapeur du Danube). Ces mots sont compréhensibles pour tout germanophone parce que la composition est un procédé productif et régulier. La tête du composé est toujours à droite : « Kraftfahrzeug » (véhicule motorisé) + « Haftpflicht » (responsabilité civile) + « Versicherung » (assurance) = assurance responsabilité civile automobile.</p>
<p class="resume-text">En mandarin, la composition est le procédé de formation lexicale dominant. Les mots composés (hécí) combinent deux morphèmes pour créer un nouveau concept : 电 (électricité) + 话 (parole) = 电话 (téléphone) ; 手 (main) + 机 (machine) = 手机 (téléphone portable). Cette transparence sémantique de la composition chinoise facilite la compréhension des néologismes : 电脑 (cerveau électrique) = ordinateur. Le japonais, le coréen et d'autres langues d'Asie de l'Est présentent des systèmes similaires.</p>
<div class="highlight-box"><p>La composition exocentrique (bahuvrihi) produit des mots dont le référent n'est pas la tête : « rouge-gorge » n'est pas un type de gorge mais un oiseau à gorge rouge ; « pieds-plats » désigne des personnes dont les pieds sont plats. En sanskrit, cette construction était très productive et a légué de nombreux exemples aux langues modernes. Le composé exocentrique montre que la morphologie peut créer des catégories conceptuelles qui échappent à la règle de la tête sémantique.</p></div>
<h3>Composition néoclassique et terminologies scientifiques</h3>
<p class="resume-text">La composition néoclassique utilise des éléments de grec ou de latin pour créer des termes techniques dans les sciences et les technologies : thermomètre (thermos + metron), téléphone (tele + phone), psychologie (psyche + logos). Ces éléments ne sont pas des mots libres en grec ou latin moderne mais fonctionnent comme des morphèmes liés dans les langues contemporaines. Ils constituent un vocabulaire international trans-linguistique : « micro » (petit) apparaît en anglais, français, espagnol, allemand, japonais dans les mêmes constructions terminologiques.</p>
<p class="resume-text">Les « mots-valises » (blending) combinent des parties de deux mots : « smog » (smoke + fog), « courriel » (courrier + électronique), « brunch » (breakfast + lunch), « motel » (motor + hotel). Ces formations témoignent d'une créativité morphologique qui ne respecte pas les frontières morphémiques traditionnelles. La linguistique cognitive (Fauconnier, Turner) y voit une manifestation de l'intégration conceptuelle : deux espaces mentaux fusionnent en un espace mixte qui hérite des propriétés sélectionnées de chacun.</p>""",

    'morphologie/typologie-morphologique': """<h3>La dérive linguistique et l'évolution morphologique</h3>
<p class="resume-text">Les langues n'évoluent pas de façon aléatoire : Edward Sapir (1921) a observé une « dérive » tendancielle vers les types analytiques dans de nombreuses langues. L'anglais a perdu 90% de ses flexions en mille ans (du vieil-anglais au moyen-anglais puis à l'anglais moderne). Le latin, langue fusionnelle à six cas, a évolué vers les langues romanes analytiques (prépositions + ordre des mots remplacement les cas). Cette évolution est liée à plusieurs facteurs : contact linguistique, réduction de la durée de syllabe, économie cognitive.</p>
<p class="resume-text">Inversement, des langues peuvent développer de nouvelles complexités morphologiques par grammaticalisation : des mots lexicaux deviennent progressivement des affixes grammaticaux. En français, le futur analytique « aller + infinitif » coexiste avec le futur synthétique (il va partir / il partira). Dans de nombreuses langues africaines et amérindiennes, des verbes de mouvement ou de position se sont grammaticalisés en auxiliaires d'aspect ou de mode. Ce cycle grammaticalisation → réanalyse → grammaticalisation est un moteur fondamental du changement morphologique.</p>
<div class="highlight-box"><p>Le créole est un laboratoire morphologique fascinant : né du contact entre une langue de superstrat (langue des colonisateurs) et des langues de substrat (langues des esclaves ou des indigènes), il développe rapidement une morphologie propre. Les créoles sont souvent analytiques, pauvres en flexion mais riches en prédicats et en sériaux verbaux. Ils montrent qu'une langue peut émerger de toutes pièces en une ou deux générations — avec une morphologie simplifiée mais fonctionnellement complète.</p></div>
<h3>Morphologie et mémoire</h3>
<p class="resume-text">La distinction entre règle morphologique et mémorisation lexicale est au cœur de la psycholinguistique morphologique. La théorie des deux mécanismes (Pinker) distingue les formes régulières (construites par règle : walked) des formes irrégulières (mémorisées : went). Des expériences de production (production d'un faux-passé d'un verbe inventé) et d'aphasie (les patients avec lésions du striatum font plus d'erreurs sur les réguliers ; ceux avec lésions du hippocampe sur les irréguliers) appuient cette distinction.</p>
<p class="resume-text">Les langues polysynthétiques comme l'inuktitut, le mohawk ou le nahuatl incorporent de nombreux morphèmes dans un seul mot verbal, produisant des structures qui équivalent à des phrases entières en français. « Qaangiuqatigiissitisariaqarpoq » en inuktitut signifie quelque chose comme « il y a besoin qu'ils commencent à se réunir à nouveau pour s'entraider ». Cette polymorphémie extrême pose des questions fascinantes sur la mémoire et le traitement morphologiques dans des langues très éloignées des langues européennes.</p>""",

    'syntaxe/constituants-syntagmes': """<h3>La structure de phrase et les langues OV/VO</h3>
<p class="resume-text">La typologique des ordres de mots distingue six ordres logiquement possibles (SOV, SVO, VSO, VOS, OVS, OSV) dont quatre sont réellement attestés. Les langues SOV (Sujet-Objet-Verbe) sont les plus fréquentes (environ 45% des langues du monde) : japonais, turc, coréen, latin, tibétain. Les langues SVO (Subject-Verb-Object) incluent le français, l'anglais et le mandarin (environ 42%). Les langues VSO (Verbe-Sujet-Objet) comprennent l'arabe classique, le gallois et le gaélique.</p>
<p class="resume-text">Joseph Greenberg (1963) a mis en évidence des corrélations entre l'ordre des mots et d'autres propriétés syntaxiques. Les langues SOV tendent à être postpositionnelles (les prépositions viennent après le nom), à avoir les adjectifs et les relatives avant le nom et à placer l'auxiliaire après le verbe principal. Les langues SVO tendent à être prépositionnelles et à placer les modifieurs après la tête. Ces corrélations, appelées « universaux implicationnels », suggèrent que l'ordre SOV et l'ordre SVO sont deux configurations cohérentes et économiques de la grammaire.</p>
<div class="highlight-box"><p>L'arbre syntaxique (diagramme en arbre) est la représentation standard des structures phrastiques en grammaire générative. Chaque nœud représente un constituant, chaque feuille un morphème lexical. La ramification binaire (chaque nœud a exactement deux branches) est une hypothèse forte qui simplifie la représentation et s'accorde avec certains universaux de traitement. Ces arbres permettent de visualiser des phénomènes comme la récursivité (une phrase peut contenir une phrase), fondamentale pour la généralité de la syntaxe humaine.</p></div>
<h3>La récursivité et l'infinité du langage</h3>
<p class="resume-text">La propriété la plus remarquable de la syntaxe humaine est la récursivité : une règle peut s'appliquer à son propre résultat, produisant des structures potentiellement infinies à partir d'un ensemble fini de règles. « Je sais que tu penses qu'il croit que... » peut s'étendre indéfiniment. « La maison que Pierre a construite à côté de l'immeuble que les architectes ont conçu... » est potentiellement illimitée. Cette propriété, notée par Humboldt et formalisée par Chomsky, est au cœur de l'« infinité discrète » du langage humain.</p>
<p class="resume-text">La controverse Everett/Chomsky sur la langue pirahã d'Amazonie a mis en question l'universalité de la récursivité. Daniel Everett affirme que le pirahã n'a pas de clauses relatives ou de phrases subordonnées — et donc pas de récursivité syntaxique. Si vrai, cela remettrait en cause l'universalité de la récursivité. Chomsky et ses collègues contestent cette analyse. Ce débat illustre les enjeux considérables de la linguistique descriptive pour la théorie générale du langage humain.</p>""",

    'syntaxe/fonctions-syntaxiques': """<h3>Les constructions à verbe léger et la décomposition événementielle</h3>
<p class="resume-text">Les constructions à verbe léger (CVL) combinent un verbe sémantiquement appauvri (avoir, faire, prendre, donner) avec un nom d'événement : « faire une promenade », « prendre une décision », « donner un coup de téléphone ». Contrairement à « se promener » ou « décider », ces constructions ont l'avantage de permettre des modifications internes (« faire une longue promenade »). Leur fréquence dans les langues du monde et leur résistance à la compositionnalité sémantique en font un domaine d'investigation actif en sémantique et syntaxe.</p>
<p class="resume-text">La décomposition événementielle (Vendler, Dowty) distingue quatre types d'Aktionsart (modes d'action): les états (savoir, croire), les activités (courir, travailler), les accomplissements (construire une maison) et les achèvements (trouver, éclater). Ces classes aspectuelles interagissent avec la flexion temporelle et les adverbes de manière prévisible : on dit « pendant une heure » avec les états et activités, « en une heure » avec les accomplissements. La syntaxe de l'aspect est ainsi profondément liée à la sémantique événementielle.</p>
<div class="highlight-box"><p>La construction résultative de l'anglais (« She hammered the metal flat » — elle a martelé le métal jusqu'à l'aplatir) n'existe pas en français ou en mandarin. Cette restriction cross-linguistique a donné lieu à des analyses théoriques importantes sur les limites de la compositionnalité syntaxique et sur la relation entre structure syntaxique et structure événementielle. Elle illustre comment des différences syntaxiques apparemment mineures révèlent des différences profondes dans la conceptualisation des événements.</p></div>
<h3>La voix passive et ses fonctions discursives</h3>
<p class="resume-text">La construction passive (Le livre est lu par Pierre) n'est pas seulement une variation syntaxique de l'actif (Pierre lit le livre) : elle a des fonctions discursives spécifiques. Elle permet de thématiser l'objet (mettre en position de thème ce qui serait normalement rhème), de déprécialiser l'agent (éviter de mentionner qui a fait l'action) et de structurer l'information d'une façon différente. Les langues sans morphologie passive (mandarin) compensent par d'autres constructions : topicalisation, constructions ba ou bei.</p>
<p class="resume-text">L'analyse des passifs dans les corpus montre que leur fréquence varie considérablement selon les genres textuels : les textes scientifiques et juridiques utilisent beaucoup le passif pour dépersonnaliser (« des mesures ont été prises »), tandis que les conversations spontanées l'évitent. Cette distribution discursive du passif illustre la façon dont les structures grammaticales véhiculent des significations pragmatiques et rhétoriques au-delà de leur sens propositionnel littéral.</p>""",

    'syntaxe/grammaire-generative': """<h3>Les preuves empiriques pour la grammaire universelle</h3>
<p class="resume-text">L'argument le plus fort en faveur d'une grammaire universelle innée est la vitesse et la régularité de l'acquisition du langage. Un enfant qui n'a jamais reçu d'enseignement explicite acquiert les règles complexes de sa langue maternelle en 4-5 ans. Il produit des phrases correctes qu'il n'a jamais entendues et évite systématiquement des structures incorrectes. Cette créativité réglée suggère l'existence d'un dispositif d'acquisition du langage (DAL) qui impose des contraintes sur les grammaires possibles.</p>
<p class="resume-text">Les langues des signes constituent une preuve indépendante : nées dans des communautés de sourds sans modèle préexistant, elles développent spontanément des propriétés grammaticales complexes (phonologie, morphologie, syntaxe) semblables à celles des langues vocales. La langue des signes nicaraguayenne, créée par des enfants sourds dans les années 1980 sans input adulte, a développé rapidement une grammaire complexe — une quasi-observation en temps réel de la genèse d'une langue.</p>
<div class="highlight-box"><p>Le programme minimaliste de Chomsky (depuis 1993) cherche à réduire la grammaire universelle à ses constituants minimaux : une opération de fusion (Merge) qui combine deux objets syntaxiques en un seul, et des principes d'économie qui limitent les opérations. Cette recherche du minimum est inspirée par l'idée que le langage humain devrait être optimal d'un point de vue computationnel — une hypothèse forte qui guide la recherche mais est contestée par les approches empiriques et fonctionnelles.</p></div>
<h3>La grammaire générative et la psycholinguistique</h3>
<p class="resume-text">La grammaire générative a stimulé un vaste programme de recherche psycholinguistique sur le traitement du langage. Les expériences de « click detection » (Fodor, Bever, 1965) ont montré que les auditeurs perçoivent les clicks comme appartenant aux frontières de constituants syntaxiques — preuve que les structures syntaxiques ont une réalité psychologique. Les études de « garden path » (phrases qui induisent une mauvaise analyse) révèlent les stratégies de traitement syntaxique en temps réel.</p>
<p class="resume-text">La psycholinguistique computationnelle utilise des modèles de traitement du langage pour prédire les temps de réaction et les patterns d'erreurs dans des expériences sur les humains. Les modèles de traitement syntaxique parallèle (constraint-based, Trueswell) et sériel (garden path theory, Frazier) font des prédictions différentes qui peuvent être testées expérimentalement. Cette interaction entre théorie linguistique abstraite et expérimentation psychologique est l'un des domaines les plus dynamiques de la science du langage.</p>""",

    'syntaxe/subordination-coordination': """<h3>La subordination en typologique mondiale</h3>
<p class="resume-text">La typologie des relatives est l'un des domaines les mieux étudiés de la linguistique cross-linguistique. On distingue les relatives pré-nominales (japonais, coréen, turc : le relativiseur précède le nom tête), les relatives post-nominales (français, anglais, arabe), et les relatives corrélatives (hindi, bengali : une structure bipartite où les deux propositions sont liées par un pronom relatif et un coréférent). L'accessibilité des positions relativisables varie systématiquement : la position sujet est la plus facilement relativisée dans toutes les langues (Keenan & Comrie, 1977).</p>
<p class="resume-text">La subordination en série verbale est typique des langues d'Afrique de l'Ouest et d'Asie du Sud-Est : plusieurs verbes se succèdent dans une même proposition sans marque de subordination explicite, partageant certains arguments. En twi (Ghana) : « Il a pris le couteau, a coupé la viande, est parti ». Ces constructions, difficiles à analyser dans le cadre génératif standard, illustrent la diversité des moyens syntaxiques pour exprimer des relations complexes entre événements.</p>
<div class="highlight-box"><p>La distinction entre coordination et subordination est moins tranchée qu'il n'y paraît. Les constructions asyndètes (juxtaposition sans connecteur), les constructions participiales et gérondives, et les constructions absolues (le temps ayant passé...) se situent entre les deux catégories. La grammaire des constructions (Fillmore, Goldberg) propose d'analyser ces zones grises en termes de constructions conventionnelles ayant leurs propres propriétés sémantiques et syntaxiques.</p></div>
<h3>Le discours indirect et la citation</h3>
<p class="resume-text">Le discours indirect libre (DIL) est une construction fascinante qui mêle les voix du narrateur et du personnage : « Elle était fatiguée. Allait-elle encore devoir tout recommencer ? » Cette construction, étudiée par Bally et Banfield, n'a pas de marqueur syntaxique explicite : on ne sait pas si c'est le narrateur ou le personnage qui parle. Ce mélange de points de vue est une ressource stylistique majeure de la littérature moderne (Flaubert en est le maître) qui n'a pas d'équivalent précis dans de nombreuses langues non-européennes.</p>
<p class="resume-text">Les constructions de citation directe et indirecte illustrent les interactions complexes entre syntaxe, prosodie et pragmatique. La citation directe en français utilise des guillemets à l'écrit et une variation prosodique (rupture de la mélodie narrative) à l'oral. La citation indirecte implique un changement de perspective énonciative (« il a dit qu'il viendrait » vs. « il a dit je viens »). Ces transformations révèlent la sophistication des systèmes grammaticaux pour représenter les actes de parole dans le discours rapporté.</p>""",

    'syntaxe/ordre-mots-universaux': """<h3>Les universaux statistiques et les typologies probabilistes</h3>
<p class="resume-text">Au-delà des universaux absolus (qui s'appliquent à toutes les langues sans exception), les linguistes distinguent des universaux statistiques (tendances très fortes mais non sans exception). Le projet WALS (World Atlas of Language Structures), qui documente les propriétés de plus de 2500 langues, a révélé des corrélations statistiques très fortes entre propriétés typologiques — par exemple entre l'ordre OV et la postposition, ou entre l'ordre VO et la préposition — sans que ces corrélations soient absolues.</p>
<p class="resume-text">La linguistique probabiliste (Bresnan, Manning) utilise des méthodes statistiques et computationnelles pour modéliser les préférences d'ordre dans les langues à ordre libre. En allemand, l'ordre des arguments dépend de nombreux facteurs : le poids phonologique (les syntagmes longs tendent à être placés en fin de phrase), la définitude (les définis précèdent les indéfinis), le statut discursif (les éléments donnés précèdent les nouveaux). Ces facteurs interagissent de façon probabiliste, non déterministe — un phénomène mieux capturé par des modèles graduels que par des règles catégorielles.</p>
<div class="highlight-box"><p>Le warlpiri, langue australienne, et le lardil présentent un ordre des mots extrêmement libre : un morphème d'accord verbal s'accorde avec tous les arguments simultanément, rendant l'ordre des constituants redondant pour l'identification grammaticale. Ces langues à ordre libre extrême (« free word order ») montrent que l'ordre des mots n'est pas une propriété universelle du langage humain mais une solution conventionnelle parmi d'autres pour encoder les relations grammaticales.</p></div>
<h3>Ordre des mots et pragmatique</h3>
<p class="resume-text">Même dans des langues à ordre relativement fixe comme le français, l'ordre peut varier pour des raisons pragmatiques (focus, topicalisation, contraste). « C'est Marie que j'aime » (clivée) vs. « Marie, je l'aime » (dislocation gauche) vs. « J'aime Marie » (phrase canonique) encodent différents états informationnels. Ces constructions ne sont pas de simples variantes stylistiques : elles signalent des présuppositions et des implications différentes sur ce qui est supposé connu et ce qui est présenté comme nouveau.</p>
<p class="resume-text">L'analyse des données de corpus montre que les langues à ordre libre comme le russe ou le latin utilisent effectivement des ordres différents dans des contextes discursifs différents. Le latin place les éléments focaux en fin de phrase (position la plus saillante). Le russe utilise l'ordre pour structurer l'information en thème (début) et rhème (fin). Cette pragmatique de l'ordre des mots est une ressource grammaticale que les locuteurs exploitent intuitivement dans la production et la compréhension du discours.</p>""",

    'semantique/sens-reference': """<h3>La distinction sens/référence et les noms propres</h3>
<p class="resume-text">La distinction frégéenne sens/référence (Sinn/Bedeutung) est illustrée de façon célèbre par « l'Étoile du Matin » et « l'Étoile du Soir » : les deux expressions désignent la même planète (Vénus = même référence) mais ont des sens différents (description distinctes). Cette distinction est fondamentale : deux expressions peuvent avoir le même référent mais des sens différents (coréférence), ou le même sens mais des référents distincts (sens général vs. extension).</p>
<p class="resume-text">Les noms propres sont problématiques pour la théorie sémantique. Selon Frege, ils ont un sens (mode de présentation) et une référence (l'individu). Selon Kripke (1980), les noms propres sont des « désignateurs rigides » : ils désignent le même individu dans tous les mondes possibles, sans médiation de descriptions. Cette vision — controversée — implique que les noms propres n'ont pas de sens descriptif, seulement une relation causale avec leur référent. Le débat Frege-Kripke est l'un des plus importants de la philosophie du langage du XXe siècle.</p>
<div class="highlight-box"><p>Les contextes opaques (intensionnels) créent des problèmes pour la co-référence. « Lois Lane pense que Superman peut voler » est vrai ; « Lois Lane pense que Clark Kent peut voler » est faux — même si Superman = Clark Kent. Dans les contextes de croyance, de désir, de possibilité, la substitution de co-référentiels n'est pas valide : on est dans un contexte opaque où le sens (pas seulement la référence) est pertinent.</p></div>
<h3>Sémantique lexicale et réseaux de mots</h3>
<p class="resume-text">Le lexique mental est organisé en réseaux de relations sémantiques : synonymie, antonymie, hyponymie (inclusion sémantique), méronymie (relation partie-tout). WordNet, base de données lexico-sémantique développée par George Miller à Princeton, organise les mots anglais en « synsets » (ensembles de synonymes) reliés par ces relations. Cette ressource est utilisée dans le traitement automatique du langage pour des tâches comme la désambiguïsation du sens et le résumé automatique.</p>
<p class="resume-text">La sémantique distributionnelle (« on connaît un mot à la compagnie qu'il tient ») postule que le sens d'un mot peut être représenté par la distribution de ses co-occurrences dans les corpus. Les modèles vectoriels de représentation des mots (word2vec, GloVe, BERT) encodent chaque mot comme un vecteur dans un espace à haute dimension où les mots sémantiquement proches sont géométriquement proches. Ces représentations distribuées sont la base des modèles de langage contemporains qui alimentent les applications d'intelligence artificielle.</p>""",

    'semantique/relations-lexicales': """<h3>La polysémie et la désambiguïsation</h3>
<p class="resume-text">La polysémie est la norme plutôt que l'exception dans les lexiques naturels. George Miller a estimé que les 10 000 mots les plus fréquents de l'anglais ont en moyenne 7 sens distincts. La désambiguïsation du sens (Word Sense Disambiguation ou WSD) est l'un des problèmes les plus difficiles du traitement automatique du langage : déterminer automatiquement quel sens d'un mot polysémique est utilisé dans un contexte donné. Les modèles actuels atteignent environ 80% de précision, contre 90% pour les humains.</p>
<p class="resume-text">La polysémie n'est pas aléatoire : elle suit des patterns réguliers de glissement sémantique. Le transfert métaphorique (un verbe physique devient un verbe mental : « saisir une idée », « peser le pour et le contre »), la métonymie (la cause pour l'effet : « poison » peut désigner la personne qui empoisonne), la spécialisation (un terme général devient spécialisé dans un domaine) et la généralisation sont les principaux mécanismes de la polysémie régulière.</p>
<div class="highlight-box"><p>La lexicologie cognitive (Cruse, Langacker, Geeraerts) propose de remplacer la polysémie discète (sens 1, sens 2, sens 3...) par une conception en réseau de similarités et de prototypes. Les sens d'un mot forment une structure en réseau où les différents sens sont reliés par des chaînes de ressemblance, sans nécessairement partager un noyau sémantique commun — une structure dite de « ressemblance de famille » au sens de Wittgenstein.</p></div>
<h3>Les relations de sens en traduction</h3>
<p class="resume-text">Les relations lexicales sont au cœur des difficultés de traduction. La lacune lexicale — l'absence dans une langue d'un mot correspondant à un mot d'une autre langue — révèle des découpages conceptuels différents. L'allemand « Gemütlichkeit » (combinaison indissociable de chaleur, de convivialité et de bien-être) n'a pas d'équivalent en français. Le portugais « saudade » (nostalgie teintée de mélancolie et d'espoir) résiste à la traduction. Le japonais « ikigai » (raison d'être, source de sens) n'a pas d'équivalent exact.</p>
<p class="resume-text">La traductologie (Vinay, Darbelnet, Nida) a développé une taxonomie des stratégies de traduction face aux lacunes lexicales : emprunt (garder le mot étranger), calque (traduction littérale de la structure), équivalence fonctionnelle (trouver un équivalent pragmatique dans la langue cible), amplification (gloser le sens en plusieurs mots). Ces stratégies illustrent les tensions entre fidélité sémantique et naturalité dans la langue cible qui traversent toute la théorie et la pratique de la traduction.</p>""",

    'semantique/semantique-phrase': """<h3>Les présuppositions et les implicatures</h3>
<p class="resume-text">La présupposition est une information que l'énoncé présuppose comme vraie sans l'affirmer explicitement. « J'ai arrêté de fumer » présuppose que j'ai fumé. « Mon chat a encore renversé la poubelle » présuppose que le chat a déjà renversé la poubelle auparavant. La présupposition survit à la négation : « Je n'ai pas arrêté de fumer » présuppose toujours que j'ai fumé. Ce comportement — appelé « projection » — distingue la présupposition de l'assertion ordinaire.</p>
<p class="resume-text">L'implicature conversationnelle (Grice, 1975) est une signification inférée à partir du contexte et des maximes de conversation (quantité, qualité, relation, manière). « Elle a un ami » implique conventionnellement (en contexte) qu'elle a un ami intime (petit ami). Mais si on demande « Pierre est-il possible pour le poste ? » et qu'on répond « Il a une belle écriture », l'implicature est que Pierre n'est pas qualifié pour le poste (violation apparente de la maxime de relation). Ces implicatures sont révocables : « Il a une belle écriture, et d'ailleurs il est excellent dans tout. »</p>
<div class="highlight-box"><p>Le problème du « donkey sentence » de Geach (1962) : « Si un paysan possède un âne, il le bat » — comment analyser « il le bat » quand « un âne » est dans la subordonnée conditionnelle ? Le pronom « le » ne peut pas être analysé comme une variable liée par un quantificateur existentiel standard, ni comme une description définie. Ce problème a donné naissance à la théorie des représentations du discours (DRT) et à la sémantique dynamique, qui analysent la sémantique au niveau du discours plutôt que de la phrase isolée.</p></div>
<h3>La sémantique compositionnelle et ses limites</h3>
<p class="resume-text">Le principe de compositionnalité (Frege) affirme que le sens d'une phrase complexe est une fonction du sens de ses parties et de la façon dont elles sont combinées. Ce principe est le fondement de la sémantique formelle (Montague, Heim & Kratzer). Il permet de prédire le sens d'une phrase nouvelle à partir du sens des mots et des règles syntaxiques. Sa puissance est immense : avec un lexique fini et des règles compositionnelles finies, on peut comprendre une infinité de phrases nouvelles.</p>
<p class="resume-text">Mais la compositionnalité a des limites. Les idiomes (« casser les pieds », « tirer les vers du nez ») ont un sens non compositionnel. Les constructions résultatives et directionnelles de l'anglais (« She sang the audience to sleep ») défient une compositionnalité stricte. Les effets pragmatiques (ironie, métaphore) modifient le sens compositionnel. La tension entre compositionnalité et usage contextuel est au cœur de la recherche en sémantique et pragmatique contemporaines.</p>""",

    'semantique/metaphore-metonymie': """<h3>La théorie conceptuelle de la métaphore : applications et critiques</h3>
<p class="resume-text">La théorie conceptuelle de la métaphore (Lakoff & Johnson, 1980) a inspiré de nombreuses applications. En linguistique politique, des travaux ont analysé les métaphores du discours migratoire (« vagues » d'immigration, « invasion ») ou du discours économique (la « crise » comme maladie, la croissance comme organisme vivant). Ces métaphores ne sont pas neutres : elles cadrent les problèmes d'une façon qui prédispose à certaines solutions et pas d'autres — une perspective adoptée dans les études de framing politique (Lakoff, Luntz).</p>
<p class="resume-text">En médecine, l'analyse des métaphores que les patients utilisent pour décrire leur maladie (une « bataille » contre le cancer, une « invasion » de microbes) révèle des schèmes cognitifs qui influencent leur rapport à la maladie et au traitement. Susan Sontag (La Maladie comme métaphore, 1978) a analysé comment les métaphores de la tuberculose au XIXe siècle (romantique, artistique) et du cancer au XXe siècle (invasion, pollution) conditionnent les attitudes sociales envers ces maladies et leurs victimes.</p>
<div class="highlight-box"><p>Les métaphores mortes — expressions métaphoriques dont on ne perçoit plus le sens littéral originel — révèlent les strates historiques du changement sémantique. « Comprendre » vient de « prendre ensemble » (cum + prehendere). « Problème » vient du grec « ce qui est projeté devant ». « Calculer » vient du latin « calculus » (petit caillou utilisé pour compter). Ces étymologies illustrent comment la sémantique concrète et corporelle est à l'origine de concepts abstraits — un argument en faveur de la thèse incarnée du langage.</p></div>
<h3>Métonymie et économie cognitive</h3>
<p class="resume-text">La métonymie est un mécanisme de référence par contiguïté : on utilise un terme pour en désigner un autre avec lequel il est en contact ou proximité conceptuelle. Les types classiques incluent la partie pour le tout (synecdoque : « les voiles » pour les bateaux), le contenant pour le contenu (« boire un verre »), le producteur pour le produit (« lire du Proust »), le lieu pour l'institution (« Bruxelles a décidé »), l'effet pour la cause (« je commande une Bordeaux » — un vin de Bordeaux).</p>
<p class="resume-text">La pragmatique de la métonymie repose sur le principe d'économie et de saillance cognitive (Langacker). Dire « passer à la caisse » pour « payer » est plus court et activé une représentation typique de l'action. Dire « Picasso a été vendu aux enchères » active le schème de production-produit. La métonymie est ainsi un outil de compression référentielle qui exploite les connaissances partagées entre locuteur et interlocuteur sur les structures prototypiques des événements et des objets du monde.</p>""",

    'semantique/pragmatique': """<h3>Les actes de parole indirects et la politesse</h3>
<p class="resume-text">La théorie de la politesse (Brown & Levinson, 1987) distingue la « face positive » (le désir d'être apprécié et reconnu) et la « face négative » (le désir d'autonomie et de ne pas être imposé). Les actes de parole menaçants pour la face (FTAs : face threatening acts) — comme les ordres, les critiques, les demandes — sont atténués par des stratégies de politesse. Un ordre direct (« Fermez la fenêtre ! ») est remplacé par une question (« Pourriez-vous fermer la fenêtre ? ») ou une formulation impersonnelle (« Il y a un courant d'air »).</p>
<p class="resume-text">La politesse linguistique varie considérablement selon les cultures. Le japonais dispose de trois systèmes de niveaux de politesse (teineigo, sonkeigo, kenjogo) avec des formes verbales et nominales distinctes selon le statut relatif des interlocuteurs. L'arabe a des formules de politesse élaborées pour chaque situation (salutations, remerciements, condoléances). Les cultures à « haute distance » (high-power distance) valorisent la déférence verticale, tandis que les cultures à « faible distance » (low-power distance) préfèrent les interactions horizontales informelles.</p>
<div class="highlight-box"><p>La compétence pragmatique — la capacité à utiliser le langage de façon appropriée dans son contexte social — se développe progressivement chez l'enfant et est souvent déficitaire dans certains troubles (autisme, syndrome d'Asperger, certaines aphasies). Cette compétence implique de comprendre les intentions communicatives au-delà du sens littéral, de respecter les tours de parole, d'adapter son discours à son interlocuteur et de reconnaître les actes de parole indirects.</p></div>
<h3>La pragmatique interculturelle</h3>
<p class="resume-text">La pragmatique interculturelle (Wierzbicka, Blum-Kulka) étudie comment les normes de communication varient selon les cultures et produisent des malentendus interculturels. Des études comparatives sur les stratégies de remerciement, de refus ou de demande montrent que même des actes de parole apparemment universels sont réalisés différemment selon les cultures. Les Israéliens sont souvent perçus comme directs (voire impolis) par des Américains, parce que leurs stratégies de demande sont moins indirectes. Les Japonais semblent souvent évasifs à des Occidentaux parce qu'ils évitent les refus directs.</p>
<p class="resume-text">La pragmatique interculturelle a des applications directes dans la communication d'entreprise internationale, la diplomatie et l'enseignement des langues. Les apprenants de L2 font souvent des « fautes » pragmatiques — utiliser des formules directes de leur L1 dans la L2 — qui sont perçues comme impolitesses par les locuteurs natifs, même quand leur grammaire est parfaite. L'enseignement explicite de la compétence pragmatique est aujourd'hui reconnu comme une composante essentielle de l'enseignement des langues secondes.</p>""",

    'sociolinguistique/variation-linguistique': """<h3>La sociolinguistique de William Labov : New York et Martha's Vineyard</h3>
<p class="resume-text">William Labov est le fondateur de la sociolinguistique variationniste. Son étude pionnière à Martha's Vineyard (1963) a montré que la centralisation des voyelles /ay/ et /aw/ était utilisée par les anciens insulaires comme marqueur d'identité locale face à l'invasion des touristes estivaux. Cette étude a inauguré l'analyse quantitative de la variation linguistique et l'idée que la variation n'est pas aléatoire mais systématique et socialement significative.</p>
<p class="resume-text">Son étude de New York (The Social Stratification of English in New York City, 1966) a montré que la réalisation du /r/ post-vocalique variait systématiquement selon la classe sociale, le style de discours et le contexte formel/informel. Les classes moyennes, conscientes de leur insécurité linguistique, surcompensaient en utilisant plus de /r/ prestige que les classes supérieures dans les styles les plus formels — le phénomène de l'hypercorrection. Ces études ont établi les méthodes et les questions de la sociolinguistique variationniste.</p>
<div class="highlight-box"><p>Le paradoxe de l'observateur (Labov) : le chercheur veut observer le vernaculaire naturel, mais sa présence modifie le comportement linguistique des enquêtés. Pour contourner ce paradoxe, Labov a utilisé des techniques d'entretien qui amènent les locuteurs à oublier le contexte formel de l'enquête : poser des questions émotionnellement engageantes (« Avez-vous jamais été en danger de mort ? »), faire raconter des histoires, observer les interactions informelles.</p></div>
<h3>Le genre et la variation linguistique</h3>
<p class="resume-text">Les recherches sociolinguistiques ont mis en évidence des différences systématiques de style linguistique entre hommes et femmes. Deborah Tannen (Vous ne me comprenez pas, 1990) a popularisé l'idée que les femmes utilisent le langage pour créer des liens (rapport talk) tandis que les hommes l'utilisent pour établir un statut (report talk). Ces généralisations sont discutées et contextualisées : les différences de style sont moins liées au sexe biologique qu'au genre social, au contexte et au pouvoir.</p>
<p class="resume-text">Des études récentes montrent que les femmes adoptent généralement les innovations linguistiques plus tôt que les hommes — ce qui confirme et nuance l'image traditionnelle des femmes comme conservatrices linguistiques. En réalité, les femmes sont à la fois plus sensibles aux formes de prestige (convergeant vers la norme standard dans les contextes formels) et plus innovatrices dans les vernaculaires locaux (adoptant les nouvelles formes de la langue populaire). Cette apparente contradiction s'explique par la sensibilité accrue des femmes à la valeur sociale des variables linguistiques.</p>""",

    'sociolinguistique/contact-langues': """<h3>Les pidgins et les créoles comme laboratoires linguistiques</h3>
<p class="resume-text">Les pidgins sont des variétés linguistiques réduites développées spontanément pour la communication entre locuteurs de langues différentes sans langue commune. Ils se caractérisent par un vocabulaire limité, une grammaire simplifiée et une phonologie réduite. Le pidgin ne devient langue maternelle de personne : c'est une langue de contact situationnelle. Le tok pisin (Papouasie-Nouvelle-Guinée), le pidgin chinois-anglais du XIXe siècle, le petit nègre colonial illustrent ces caractéristiques.</p>
<p class="resume-text">Quand un pidgin devient la langue maternelle d'une nouvelle génération (généralement en contexte de plantation coloniale où les esclaves de différentes langues doivent communiquer), il se créolise : le vocabulaire s'enrichit, la grammaire se complexifie, la phonologie se stabilise. Le haïtien créole, le papiamento (Caraïbes), le tok pisin natif, le mauricien créole illustrent cette créolisation. Derek Bickerton (Language Bioprogram Theory, 1981) a proposé que les créoles partagent des propriétés grammaticales universelles qui reflètent une grammaire de base humaine.</p>
<div class="highlight-box"><p>La langue des signes nicaraguayenne est un cas unique de créolisation observable en temps réel : créée par des enfants sourds dans les années 1980 à Managua, sans modèle adulte, elle a développé en deux générations une grammaire complexe avec des marqueurs d'aspect et des structures morphologiques absents de la première génération. Ce cas a fourni des arguments importants sur la créativité grammaticale innée des enfants.</p></div>
<h3>L'emprunt lexical et la résistance puriste</h3>
<p class="resume-text">Toutes les langues empruntent du vocabulaire à d'autres langues avec lesquelles elles sont en contact. L'anglais est exceptionnellement ouvert à l'emprunt (50% de son vocabulaire est d'origine française ou latine, 8% scandinave) ; le français plus résistant mais non imperméable (« football », « week-end », « shopping »). La résistance puriste (Académie française, commissions de terminologie québécoise) cherche à remplacer les emprunts par des calques ou des néologismes internes : « courriel » pour email, « baladeur » pour walkman, « logiciel » pour software.</p>
<p class="resume-text">La sociolinguistique critique des emprunts examine les rapports de pouvoir dans le contact linguistique. Les emprunts vont généralement de la langue dominante vers la langue dominée, pas l'inverse. L'anglicisation du français, du japonais ou du mandarin est souvent présentée comme une menace identitaire. Mais l'emprunt peut aussi être une ressource créative : le verlan français (mot inversé), les langues des SMS ou la langue de l'internet créent des hybrides linguistiques qui témoignent de la vitalité des langues en contact.</p>""",

    'sociolinguistique/politique-linguistique': """<h3>La planification du corpus et la standardisation</h3>
<p class="resume-text">La planification du corpus porte sur la forme même de la langue : orthographe, grammaire, vocabulaire. La création d'une orthographe standardisée pour une langue à tradition orale, la réforme orthographique d'une langue existante (comme la réforme de l'orthographe française proposée en 1990 et progressivement adoptée), ou la modernisation du vocabulaire (création de termes techniques) sont des interventions sur le corpus. Ces décisions sont politiquement sensibles : la réforme allemande de l'orthographe de 1996 a provoqué un tollé.</p>
<p class="resume-text">La codification du swahili comme langue nationale de Tanzanie par Julius Nyerere dans les années 1960 est un exemple réussi de planification linguistique : le swahili, déjà lingua franca de l'Afrique de l'Est, a été enrichi, standardisé et promu comme langue d'enseignement et d'administration. Ce choix délibéré d'une langue africaine (non d'une langue européenne coloniale) est une décision à la fois linguistique et politique affirmant l'indépendance culturelle du pays.</p>
<div class="highlight-box"><p>La revitalisation du cornique, langue celtique de Cornouailles déclarée morte en 1777 avec le décès de son dernier locuteur natif, est un exemple de renaissance linguistique. Des efforts de standardisation de l'orthographe, de développement pédagogique et de promotion médiatique ont conduit à la reconnaissance du cornique par le Conseil de l'Europe en 2002. Aujourd'hui, quelques centaines de locuteurs utilisent le cornique activement — un « revenant » linguistique remarquable.</p></div>
<h3>Multilinguisme institutionnel et droits linguistiques</h3>
<p class="resume-text">De nombreux États gèrent plusieurs langues officielles avec des politiques variées. La Suisse a quatre langues nationales (allemand, français, italien, romanche) avec un principe de territorialité : chaque région utilise sa langue. La Belgique a des régions unilingues (Wallonie francophone, Flandre néerlandophone) et bilingue (Bruxelles). Le Canada a le bilinguisme officiel fédéral (anglais-français) mais des politiques provinciales très différentes (le Québec est officiellement unilingue français).</p>
<p class="resume-text">Les droits linguistiques sont reconnus comme droits de l'homme par la Déclaration universelle des droits linguistiques (Barcelone, 1996), non ratifiée par la plupart des États. Le droit à l'éducation dans sa langue maternelle, le droit d'utiliser sa langue devant les tribunaux et les administrations, le droit à la culture dans sa langue : ces droits sont souvent en tension avec les impératifs d'intégration nationale et d'efficacité administrative. Les conflits linguistiques (en Catalogne, en Ukraine, au Sri Lanka) montrent que ces questions dépassent largement le domaine linguistique.</p>""",

    'sociolinguistique/langue-identite': """<h3>Langue et nationalisme au XIXe siècle</h3>
<p class="resume-text">Le nationalisme du XIXe siècle a fait de la langue un marqueur d'identité nationale fondamental. Johann Gottfried Herder affirme que chaque nation a son « esprit du peuple » (Volksgeist) exprimé dans sa langue. Les frères Grimm collectent les contes populaires allemands et développent la linguistique comparatiste pour prouver l'unité du peuple allemand. La standardisation du hindi, du tchèque, du norvégien, du finnois ou du letton au XIXe siècle sont autant d'entreprises nationalistes qui font d'une variété dialectale la langue officielle d'une nation en formation.</p>
<p class="resume-text">Le sionisme linguistique a réussi l'exploit de ressusciter l'hébreu comme langue vernaculaire vivante. Eliezer Ben-Yehuda (1858-1922) s'est consacré à la modernisation de l'hébreu biblique, créant des milliers de néologismes pour les réalités de la vie moderne. Ses méthodes — forcer sa famille à n'utiliser que l'hébreu, refuser de parler toute autre langue — étaient extrêmes mais efficaces. Aujourd'hui, 9 millions de personnes parlent l'hébreu moderne comme langue maternelle, une renaissance linguistique sans précédent dans l'histoire.</p>
<div class="highlight-box"><p>La mort des langues est une crise silencieuse : des quelque 7000 langues parlées dans le monde, la moitié devrait disparaître d'ici la fin du siècle. Chaque quinzaine, une langue s'éteint avec son dernier locuteur. Ces langues emportent avec elles des écologies cognitives uniques, des classifications du monde, des textures culturelles irremplaçables. Des projets de documentation (Endangered Languages Project, ELDP) s'efforcent d'archiver ces langues avant leur disparition.</p></div>
<h3>Code-switching et identité plurilingue</h3>
<p class="resume-text">Le code-switching — l'alternance entre deux langues dans une même conversation, voire dans une même phrase — est une pratique courante chez les bilingues et les multilingues. « J'ai vu María yesterday, elle était totally stressed out » mélange naturellement l'anglais et l'espagnol (Spanglish). Ce comportement n'est pas une défaillance linguistique mais une ressource communicative sophistiquée qui marque l'identité bilingue, la solidarité communautaire et les nuances pragmatiques.</p>
<p class="resume-text">Des recherches menées en milieu scolaire montrent que le code-switching entre la langue d'enseignement et la langue maternelle est une stratégie d'apprentissage efficace (translanguaging) : utiliser les ressources de toutes ses langues pour construire le sens. Cette approche, développée par Cen Williams pour le gallois et généralisée par Ofelia Garcia, conteste les politiques d'immersion stricte qui interdisent l'usage de la langue maternelle en classe et témoigne d'une vision du multilinguisme comme richesse et non comme problème.</p>""",

    'sociolinguistique/changement-linguistique': """<h3>Les nouvelles perspectives sur le changement en temps réel</h3>
<p class="resume-text">Les études en temps réel (real-time studies) suivent l'évolution d'une variable linguistique sur plusieurs décennies dans la même communauté. Des études longitudinales à Martha's Vineyard, à Philadelphie (Labov), en Norvège et au Danemark ont montré que les changements phonologiques progressent en vagues à travers la société, partant généralement des classes moyennes plutôt que des classes inférieures ou supérieures. Ce modèle de « middle out » du changement contraste avec les conceptions traditionnelles qui attribuaient les changements à imitation des classes supérieures ou à l'abandon des normes par les classes inférieures.</p>
<p class="resume-text">L'internet et les réseaux sociaux ont ouvert de nouveaux terrains d'investigation pour le changement linguistique. Les études sur l'anglais de Twitter ou de Facebook montrent des variations et des innovations linguistiques qui se propagent beaucoup plus rapidement que dans les communautés en face-à-face traditionnelles. Les émojis, les acronymes (LOL, BTW), les néologismes viraux circulent à une vitesse sans précédent. Ces phénomènes posent la question de si les réseaux sociaux accélèrent le changement linguistique ou créent simplement de nouvelles variétés de registres écrits informels.</p>
<div class="highlight-box"><p>La grammaticalisation du futur français illustre le changement en temps réel : le futur synthétique (il partira) est progressivement remplacé par le futur périphrastique (il va partir) dans la parole spontanée. Des études de corpus montrent que cette substitution est déjà très avancée dans les conversations informelles mais résiste dans les registres formels et l'écrit. On observe ainsi un changement en cours, avec ses zones de variabilité stylistique caractéristiques de la transition.</p></div>
<h3>Changement linguistique et contact</h3>
<p class="resume-text">Le contact entre langues est l'un des moteurs les plus puissants du changement linguistique. L'influence du vieux norrois sur le moyen anglais a profondément modifié la grammaire et le lexique anglais. L'influence de l'arabe sur le persan, du persan sur l'ourdou, du français sur le créole haïtien illustrent des strates de contact qui se superposent dans la structure même des langues. Ces influences peuvent être lexicales (emprunt de mots), phonologiques (adoption de sons étrangers) ou même grammaticales (calque de constructions syntaxiques).</p>
<p class="resume-text">Les situations de contact intense (bilinguisme massif, diglossie, migrations) peuvent produire des convergences structurales (Sprachbund) entre langues non apparentées. Les langues des Balkans (grec, bulgare, roumain, albanais, macédonien) partagent de nombreuses caractéristiques grammaticales (article postposé, fusion du génitif et du datif, futur périphrastique) malgré des origines indépendantes. Ces phénomènes de convergence montrent que la parenté génétique n'est pas le seul facteur déterminant de la structure d'une langue : la géographie linguistique a son importance.</p>""",

    'acquisition-langage/etapes-acquisition': """<h3>L'acquisition bilingue simultanée</h3>
<p class="resume-text">Les enfants élevés dans des familles bilingues acquièrent deux langues simultanément sans difficultés cognitives majeures. Les études longitudinales (Meisel, Volterra & Taeschner, De Houwer) montrent que le système bilingue se développe de façon distincte dès les premières productions : les nourrissons bilingues distinguent les deux phonologies très tôt et évitent systématiquement les mélanges dans les contextes où une seule langue est attendue. Le code-switching précoce, longtemps interprété comme signe de confusion, est maintenant vu comme un comportement communicatif stratégique.</p>
<p class="resume-text">Le concept de « masse critique de l'input » est crucial pour l'acquisition bilingue : chaque langue doit recevoir une quantité suffisante d'input pour se développer pleinement. Des études suggèrent qu'environ 25-30% du temps d'exposition à une langue est nécessaire pour son développement optimal. Cette information est importante pour les familles bilingues qui cherchent à maintenir une langue minoritaire face à la dominance de la langue de l'environnement scolaire et social.</p>
<div class="highlight-box"><p>Les « sur-extensions » de l'enfant — appeler tous les hommes « papa », tous les animaux à quatre pattes « chien » — révèlent les mécanismes de catégorisation conceptuelle à l'œuvre dans l'acquisition. L'enfant construit des catégories sur la base de traits saillants et les applique trop largement. Les « sous-extensions » (utiliser « chien » uniquement pour son propre chien) révèlent l'attachement du mot à un référent particulier. Ces erreurs sont transitoires et informatifs sur le développement lexical.</p></div>
<h3>Les stades morphosyntaxiques</h3>
<p class="resume-text">Roger Brown (1973) a identifié cinq stades d'acquisition morphosyntaxique basés sur la longueur moyenne des énoncés (LME) en anglais. Au stade I (LME 1-2), les énoncés se réduisent aux mots de contenu (télégraphique). Aux stades II-V, les morphèmes grammaticaux sont acquis dans un ordre remarkablement constant : le participe présent (-ing), la préposition in/on, le pluriel régulier (-s), la possession (-'s), le verbe être (copule), l'article, le passé irrégulier, le passé régulier, le verbe être auxiliaire. Cet ordre d'acquisition est partiellement lié à la fréquence mais aussi à la complexité sémantique et formelle.</p>
<p class="resume-text">L'acquisition de la négation en français passe par des stades prévisibles : d'abord « non » en tête ou en queue de phrase (« Non faire », « Veux pas »), puis la double négation (ne...pas) avec omission de « ne » (« Je veux pas »), puis la forme complète (« Je ne veux pas »). Ces stades reflètent une analyse progressive de la structure morphosyntaxique de la langue, qui n'est pas simplement une imitation des formes adultes entendues mais une construction active de règles sur la base des données de l'input.</p>""",

    'acquisition-langage/theories-acquisition': """<h3>Le débat inné/acquis dans l'acquisition du langage</h3>
<p class="resume-text">Le débat entre nativisme (Chomsky, Pinker) et empirisme (Tomasello, constructivisme) est l'une des controverses les plus fécondes des sciences cognitives. Pour les nativistes, l'universalité des propriétés grammaticales, la vitesse de l'acquisition et le fait que les enfants produisent des structures correctes sans correction explicite suggèrent un dispositif inné. Pour les empiristes, l'usage linguistique (le fait d'interagir avec des locuteurs dans des contextes communicatifs réels) et l'apprentissage statistique suffisent à expliquer l'acquisition.</p>
<p class="resume-text">Les études sur les enfants sauvages (Victor de l'Aveyron, Genie) et les enfants sourd-aveugles (Helen Keller) apportent des données précieuses mais difficilement interprétables : leur développement linguistique atypique peut refléter des effets de la privation sociale autant que l'absence d'input linguistique proprement dit. Les langues des signes développées spontanément par des enfants sourds sans accès à une langue des signes adulte (comme la langue des signes nicaraguayenne) constituent l'argument empirique le plus fort pour une faculté langagière innée.</p>
<div class="highlight-box"><p>Le test de Strange Situation d'Ainsworth et Bowlby a mis en évidence que la sécurité de l'attachement précoce prédit la richesse du développement langagier. Les enfants avec un attachement sécure interagissent plus avec leurs parents, qui leur fournissent plus d'input linguistique varié. Cette relation entre attachement et langage illustre comment le développement cognitif, affectif et social sont étroitement liés dans les premières années.</p></div>
<h3>L'apprentissage statistique et les modèles computationnels</h3>
<p class="resume-text">Les recherches de Jenny Saffran (1996) ont montré que des nourrissons de 8 mois peuvent segmenter le flux de parole en « mots » en utilisant des probabilités de transition statistiques entre syllabes : si « bi » est suivi de « ku » avec une probabilité élevée dans la langue entendue, ces deux syllabes forment probablement un mot. Ces résultats ont relancé les approches statistiques de l'acquisition et suggèrent que le cerveau infantile est un puissant ordinateur statistique, sensible aux régularités de distribution dans l'input.</p>
<p class="resume-text">Les modèles de réseaux de neurones profonds (comme GPT-4 ou BERT) entraînés sur de grandes quantités de texte ont relancé le débat sur l'inné et l'acquis : si des systèmes purement statistiques peuvent acquérir des compétences grammaticales complexes à partir de données massives, est-il encore nécessaire de postuler une grammaire universelle innée ? Les linguistes nativistes répondent que ces modèles requièrent des ordres de grandeur d'input plus importants que les enfants et ne généralisent pas de la même façon — mais le débat reste ouvert et fécond.</p>""",

    'acquisition-langage/periode-critique': """<h3>Les périodes sensibles dans l'acquisition bilinguisme</h3>
<p class="resume-text">Au-delà de la période critique pour la L1, des périodes sensibles ont été identifiées pour l'acquisition d'une L2. L'accquisition précoce d'une L2 (avant 7-8 ans) conduit généralement à une prononciation native, tandis que les apprenants tardifs ont presque toujours un accent étranger. Cette différence pour la phonologie contraste avec la morphosyntaxe où les adultes peuvent atteindre des niveaux très élevés, voire « natifs », de compétence.</p>
<p class="resume-text">Des études d'imagerie cérébrale (fMRI) ont montré que les bilingues précoces (apprenants de L2 avant 7 ans) traitent les deux langues dans les mêmes régions corticales, tandis que les bilingues tardifs activent des régions légèrement différentes pour la L2. Cette différence de représentation corticale est liée à la maîtrise atteinte, pas seulement à l'âge d'acquisition. Des bilingues tardifs très compétents montrent des patterns d'activation proches des bilingues précoces — ce qui nuance l'interprétation de la période critique.</p>
<div class="highlight-box"><p>Chelsea est une Américaine dont la surdité profonde congénitale non diagnostiquée l'a privée de tout input linguistique jusqu'à l'âge de 32 ans. Après avoir reçu des aides auditives et suivi un enseignement intensif, elle a développé un vocabulaire important mais une grammaire très limitée, sans flexion verbale ni structure syntaxique complexe. Ce cas est souvent cité comme preuve de la période critique pour l'acquisition de la grammaire.</p></div>
<h3>Implications pédagogiques de la période critique</h3>
<p class="resume-text">Les implications pédagogiques de la période critique sont complexes et souvent mal comprises. L'argument selon lequel il faut commencer l'enseignement précoce des langues étrangères est correct pour la phonologie mais doit être nuancé pour la grammaire et le vocabulaire. Des enfants de 10-12 ans apprennent souvent plus vite les structures grammaticales que des enfants de 5-6 ans, même si ceux-ci atteignent finalement une meilleure prononciation.</p>
<p class="resume-text">La politique d'immersion totale (tout-L2 dès la maternelle) est fondée sur les avantages de l'exposition précoce à la phonologie de la L2. Les programmes d'immersion canadiens (français pour les anglophones, anglais pour les francophones) ont montré des résultats positifs : les élèves atteignent de bonnes compétences en L2 sans retard en L1. Ces programmes sont influencés par les recherches sur la période critique mais aussi par des considérations sociales, économiques et politiques sur la valeur du bilinguisme dans la société.</p>""",

    'acquisition-langage/troubles-langage': """<h3>La dyslexie : bases neurologiques et prises en charge</h3>
<p class="resume-text">La dyslexie développementale affecte 5-10% des enfants scolarisés. Elle se manifeste par des difficultés dans le décodage phonologique (associer des graphèmes à des phonèmes) qui rendent la lecture laborieuse. Des recherches d'imagerie cérébrale (Shaywitz, Démonet) ont identifié un défaut de fonctionnement dans les aires pariéto-temporale et occipito-temporale gauches liées au traitement phonologique. Les dyslexiques « compensent » en suractivant les régions frontales et les voies de traitement droit.</p>
<p class="resume-text">La prise en charge de la dyslexie repose sur une rééducation phonologique intensive (méthode Orton-Gillingham, programme ABRACADABRA) qui entraîne explicitement la conscience phonémique et la correspondance graphème-phonème. Les dispositifs pédagogiques (temps supplémentaire aux examens, supports numériques, correcteurs orthographiques) permettent aux personnes dyslexiques de compenser leurs difficultés. Des personnalités comme Einstein, Léonard de Vinci, Thomas Edison, Richard Branson sont réputées dyslexiques — ce qui a contribué à déconstruire le stigmate associé à ce trouble.</p>
<div class="highlight-box"><p>L'aphasie de Broca, causée par une lésion du cortex frontal gauche, produit une parole hachée, laborieuse, agrammaticale mais relativement compréhensible : les patients comprennent le langage mais peinent à le produire. L'aphasie de Wernicke, causée par une lésion du cortex temporal postérieur gauche, produit une parole fluente mais incompréhensible (jargon aphasique) avec une mauvaise compréhension. Ces deux formes dissociées d'aphasie ont fourni les premières preuves neuroanatomiques de la localisation du langage.</p></div>
<h3>Les troubles du spectre autistique et le langage</h3>
<p class="resume-text">Les troubles du spectre autistique (TSA) incluent des profils linguistiques très variés : certains enfants autistes restent non-verbaux toute leur vie ; d'autres développent un langage parfaitement grammatical mais présentent des déficits pragmatiques (difficultés à maintenir une conversation, incompréhension de l'ironie et des sous-entendus, discours centré sur ses propres intérêts). L'écholalie (répétition mécanique de ce que l'interlocuteur vient de dire) est fréquente dans les TSA et peut être fonctionnelle (retarder, combler, affirmer) ou non-fonctionnelle.</p>
<p class="resume-text">Les systèmes de communication alternatives et améliorées (CAA) — pictogrammes PECS, tablettes numériques, synthèse vocale — ont transformé la vie de nombreuses personnes non-verbales ou avec des difficultés de communication sévères. Ces outils permettent à des personnes autistes, paralysées cérébrales ou présentant d'autres troubles moteurs ou cognitifs d'accéder à la communication et d'exprimer leurs besoins, désirs et pensées. Stephen Hawking et son synthétiseur vocal est l'exemple le plus célèbre de l'impact de ces technologies.</p>""",

    'acquisition-langage/langage-cerveau': """<h3>La neuroimagerie du langage et ses limites</h3>
<p class="resume-text">L'imagerie par résonance magnétique fonctionnelle (IRMf) a révolutionné la neurologie du langage en permettant d'observer l'activité cérébrale pendant des tâches linguistiques. Ces études confirment la latéralisation gauche du langage (90% des droitiers, 70% des gauchers) et ont affiné la cartographie des fonctions linguistiques au-delà des régions de Broca et Wernicke. Cependant, l'IRMf mesure des variations de flux sanguin (réponse hémodynamique) qui sont un proxy indirect et temporellement peu précis de l'activité neuronale réelle.</p>
<p class="resume-text">L'électroencéphalographie (EEG) offre une résolution temporelle fine (milliseconde) mais une résolution spatiale médiocre. Des potentiels évoqués comme le N400 (composante négative à 400ms après un mot sémantiquement incongru : « Je bois mon café avec du sucre et un chapeau ») et le P600 (à 600ms après une violation syntaxique) ont été des outils précieux pour étudier le traitement linguistique en temps réel. La combinaison IRMf + EEG permet d'obtenir une résolution spatio-temporelle plus complète.</p>
<div class="highlight-box"><p>La découverte des « neurones miroirs » chez le macaque (Rizzolatti, 1992) puis leur identification probable chez l'humain a suscité une vague d'hypothèses sur leur rôle dans le langage. L'hypothèse du « miroir linguistique » (Rizzolatti, Arbib) suggère que le langage a évolué à partir de systèmes moteurs de reconnaissance d'actions. Bien que séduisante, cette hypothèse est aujourd'hui considérée comme trop spéculative par la majorité des neurolinguistes.</p></div>
<h3>Le langage chez les autres primates</h3>
<p class="resume-text">Des expériences d'enseignement du langage des signes à des chimpanzés (Washoe, 1966) et de bonobos (Kanzi) ont montré que ces primates peuvent apprendre un vocabulaire de centaines de signes ou de lexigrammes et combiner des symboles pour exprimer des concepts nouveaux. Kanzi a acquis des compétences de compréhension du langage parlé remarquables. Ces expériences ont alimenté le débat sur l'unicité du langage humain.</p>
<p class="resume-text">Cependant, les linguistes notent des limitations importantes : les primates n'acquièrent pas spontanément de syntaxe productive, leur utilisation des symboles reste souvent contextuelle plutôt que référentielle, et ils ne montrent pas de créativité grammaticale comparable aux enfants humains. La double articulation (combinaison de phonèmes en morphèmes et de morphèmes en phrases) reste spécifiquement humaine. Ces recherches sugge néanmoins que les précurseurs cognitifs du langage (intentionnalité communicative, symbolisation) sont présents chez les grands singes, ouvrant des fenêtres sur l'évolution du langage humain.</p>""",
}

def enrich_content(content, new_html):
    quiz_marker = '<section class="content-section" id="quiz">'
    idx = content.find(quiz_marker)
    if idx != -1:
        return content[:idx] + new_html + content[idx:]
    last_section = content.rfind('</section>')
    if last_section != -1:
        return content[:last_section] + new_html + content[last_section:]
    return content + new_html


def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    pages = data.get('pages', {})
    modified = 0
    skipped = 0

    for key, html in ENRICHMENTS.items():
        if key not in pages:
            print(f'SKIP (not found): {key}')
            skipped += 1
            continue

        page = pages[key]
        current_content = page.get('content', '') or ''

        if len(current_content) >= 15000:
            print(f'SKIP (already >= 15000): {key} ({len(current_content)} chars)')
            skipped += 1
            continue

        new_content = enrich_content(current_content, html)
        pages[key]['content'] = new_content
        status = 'OK' if len(new_content) >= 15000 else 'PARTIAL'
        print(f'{status}: {key} ({len(current_content)} -> {len(new_content)} chars)')
        modified += 1

    data['pages'] = pages

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'\nDone: {modified} articles enriched, {skipped} skipped.')


if __name__ == '__main__':
    main()
