import json, re, sys

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def enrich_contenu(content, new_blocks):
    marker = '<section class="content-section" id="quiz">'
    idx = content.find(marker)
    if idx == -1:
        idx = content.rfind('</section>')
    return content[:idx] + new_blocks + content[idx:]

# ===== theorie-communication/communication-interpersonnelle =====
k = 'theorie-communication/communication-interpersonnelle'
extra = (
    '<h3>Analyse transactionnelle et positions de vie</h3>'
    '<p class="resume-text">L\'<strong>analyse transactionnelle</strong> (Eric Berne, <em>Des jeux et des hommes</em>, 1964) propose un modele de la communication interpersonnelle fonde sur trois etats du moi : le Parent (normes, valeurs, comportements introjetes des figures parentales), l\'Adulte (traitement rationnel de l\'information, ici et maintenant) et l\'Enfant (sentiments, besoins, comportements spontanes ou adaptes de l\'enfance). Toute communication est une transaction entre ces etats. Une transaction complementaire (Parent-Enfant, Adulte-Adulte) permet la communication fluide ; une transaction croisee cree un conflit.</p>'
    '<p class="resume-text">Thomas Harris popularisa le concept de <strong>positions de vie</strong> : Je suis OK/Tu es OK (position saine, ouverture a l\'autre), Je suis OK/Tu n\'es pas OK (arrogance, condescendance), Je ne suis pas OK/Tu es OK (soumission, complexe d\'inferiorite), Je ne suis pas OK/Tu n\'es pas OK (desespoir, nihilisme). Ces positions colorent inconsciemment toutes nos interactions. L\'objectif therapeutique est d\'atteindre la position OK-OK, base d\'une communication authentique et respectueuse.</p>'
    '<div class="highlight-box"><p>L\'analyse transactionnelle d\'Eric Berne : nous jouons des jeux psychologiques dans nos interactions quotidiennes. En prendre conscience est le premier pas vers une communication plus authentique.</p></div>'
    '<h3>Negociation et gestion des conflits</h3>'
    '<p class="resume-text">La <strong>Communication Non Violente</strong> (CNV), developpee par Marshall Rosenberg (<em>Les mots sont des fenetres ou des murs</em>, 1999), propose un processus en quatre etapes pour transformer les conflits en connexion : Observer sans evaluer (decrire les faits sans jugement), Exprimer ses Sentiments (en prenant responsabilite de ses emotions), Identifier ses Besoins (les besoins universels sous-jacents aux emotions) et formuler une Demande concrete, realiste et ouverte. La CNV distingue les demandes (ouvertes au refus) des exigences (imposees).</p>'
    '<p class="resume-text">La <strong>methode Harvard</strong> de negociation (Roger Fisher, William Ury, <em>Getting to Yes</em>, 1981) distingue les positions (ce que les parties disent vouloir) des interets (pourquoi elles le veulent). Une negociation efficace cherche les interets sous les positions, invente des options de gain mutuel et s\'appuie sur des criteres objectifs. Cette approche, utilisee en diplomatie internationale, en mediation familiale et en negociation commerciale, a revolutionne la pratique de la resolution de conflits.</p>'
    '<div class="highlight-box"><p>La CNV de Rosenberg : derriere toute critique ou exigence se cache un besoin non exprime. Identifier ce besoin transforme le conflit en dialogue.</p></div>'
    '<h3>Communication interculturelle et chocs culturels</h3>'
    '<p class="resume-text">La <strong>communication interculturelle</strong> etudie comment les differences culturelles affectent les interactions. Geert Hofstede a identifie six dimensions culturelles qui varient selon les pays : la distance hierarchique (acceptation des inegalites de pouvoir), l\'individualisme vs collectivisme, la masculinite vs feminite, l\'aversion a l\'incertitude, l\'orientation a long terme vs court terme, et l\'indulgence vs la retenue. Ces dimensions expliquent de nombreux malentendus dans les equipes internationales et les negociations commerciales transculturelles.</p>'
    '<p class="resume-text">Le <strong>choc culturel</strong> (Kalervo Oberg, 1960) designe le stress et la desorientation ressentis lors d\'une immersion dans une nouvelle culture. Il se deroule en quatre phases : lune de miel (enthousiasme), frustration (choc), adaptation (ajustement progressif) et integration (aisance biculturelle). Comprendre ce processus est essentiel pour les expatries, les migrants, les travailleurs humanitaires et les etudiants en mobilite internationale. La competence interculturelle — capacite a communiquer efficacement a travers les differences — est aujourd\'hui une competence professionnelle majeure.</p>'
    '<div class="highlight-box"><p>Hofstede : la dimension individualisme/collectivisme est l\'une des plus decisives en communication internationale. Un Americain et un Japonais peuvent parler la meme langue et se comprendre tres mal.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== theorie-communication/rhetorique-et-persuasion =====
k = 'theorie-communication/rhetorique-et-persuasion'
extra = (
    '<h3>La rhetorique moderne et les figures de style</h3>'
    '<p class="resume-text">La <strong>Nouvelle Rhetorique</strong> de Chaim Perelman et Lucie Olbrechts-Tyteca (<em>Traite de l\'argumentation</em>, 1958) restaura la rhetorique comme discipline academique apres des siecles de discredit. Perelman distingua la demonstration (logique formelle, valide par sa forme) de l\'argumentation (cherchant a obtenir l\'adhesion d\'un auditoire particulier). Il identifia trois types d\'arguments : les arguments quasi-logiques (analogies, paradoxes), les arguments fondes sur la structure du reel (lien de causalite, argument pragmatique) et les arguments qui fondent cette structure (exemple, illustration, modele).</p>'
    '<p class="resume-text">Les <strong>figures de style</strong> ne sont pas des ornements decoratifs mais des strategies argumentatives. La metaphore structure la comprehension : parler d\'un debat comme d\'une guerre (<em>vos arguments sont indefendables</em>, <em>il a attaque mes positions</em>) impose une frame cognitive combative. L\'anaphore (repetition en debut de phrase) cree un effet de matraquage emotionnel. La litote dit moins pour signifier plus. L\'ironie cree une connivence avec l\'auditoire complice. George Lakoff a montre que les metaphores conceptuelles structurent profondement notre pensee politique.</p>'
    '<div class="highlight-box"><p>George Lakoff : les metaphores conceptuelles ne sont pas des figures de style — elles structurent notre pensee. Appeler une loi de protection sociale une <em>charge fiscale</em> ou un <em>investissement social</em> produit des reactions politiques radicalement differentes.</p></div>'
    '<h3>Propagande, desinformation et contre-rhetorique</h3>'
    '<p class="resume-text">La <strong>propagande</strong> est une forme de communication persuasive qui cherche a influencer les attitudes et comportements d\'un grand nombre de personnes en s\'appuyant sur des techniques rhetorico-psychologiques : appel a l\'autorite, au groupe, a la peur, au patriotisme ; repetition des slogans ; simplification manichéenne (nous/eux). Jacques Ellul (<em>Propagandes</em>, 1962) distingua la propagande d\'agitation (qui mobilise pour l\'action immediate) de la propagande d\'integration (qui consolide les valeurs et l\'identite d\'un groupe).</p>'
    '<p class="resume-text">La <strong>rhetorique democratique</strong> exige la contre-rhetorique : la capacite a identifier les sophismes (ad hominem, pente glissante, faux dilemme, generalisation abusive, homme de paille), a verifier les faits et a evaluer la qualite des arguments. L\'education aux medias et a l\'information (EMI) vise a developper ces competences critiques. Le philosophe <strong>Stephen Toulmin</strong> a propose un modele d\'argumentation pratique — donnee, affirmation, justification, appui, refutation possible, qualificateur — qui permet d\'analyser et de construire des arguments valides dans des contextes quotidiens.</p>'
    '<div class="highlight-box"><p>Le modele de Toulmin : un bon argument articule une donnee, une affirmation, une justification et anticipe les refutations possibles. C\'est la base de tout raisonnement rigoureux.</p></div>'
    '<h3>Rhetorique numerique et nouveaux enjeux persuasifs</h3>'
    '<p class="resume-text">Le <strong>Web 2.0</strong> a transforme la rhetorique en multipliant les emetteurs et les formats : posts, tweets, stories, videos courtes, podcasts. La <strong>rhetorique numerique</strong> (Andrew Feenberg, James Crosswhite) etudie les nouvelles strategies persuasives adaptees aux environnements en ligne : economy d\'attention, viralite, engagement emotionnel, personnalisation algorithmique. Le clickbait, les titres sensationnalistes et les images choc exploitent les biais cognitifs (curiosite, indignation, peur) pour maximiser les clics et les partages.</p>'
    '<p class="resume-text">Les <strong>dark patterns</strong> en UX design et les techniques de neuromarketing numerique (A/B testing, eye-tracking, personnalisation predite par IA) constituent une forme de persuasion algorithmique qui echappe a la conscience du sujet. Shoshana Zuboff (<em>L\'Age du capitalisme de surveillance</em>, 2019) analyse comment les plateformes collectent les donnees comportementales pour predire et influencer les comportements d\'achat, electoraux et sociaux. Cette persuasion invisible pose des questions ethiques fondamentales sur l\'autonomie et la deliberation democratique.</p>'
    '<div class="highlight-box"><p>Shoshana Zuboff : le capitalisme de surveillance ne vend pas seulement des publicites — il vend des certitudes comportementales. La prediction du comportement est la nouvelle matiere premiere de l\'economie numerique.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== journalisme/histoire-de-la-presse =====
k = 'journalisme/histoire-de-la-presse'
extra = (
    '<h3>La presse sous controle : censure, liberte et luttes de pouvoir</h3>'
    '<p class="resume-text">L\'histoire de la presse est indissociable des luttes pour la <strong>liberte d\'expression</strong>. L\'Areopagitica de John Milton (1644) est le premier grand plaidoyer contre la censure, exigeant la liberte de publier sans autorisation prealable. En France, la Declaration des droits de l\'homme et du citoyen (1789) proclame la liberte de communication des pensees. Mais cette liberte reste fragile : Napoleon reinstaure la censure, la presse alternant sous les regimes successifs entre liberte et controle jusqu\'a la loi fondatrice du 29 juillet 1881 qui etablit la liberte de la presse en droit francais.</p>'
    '<p class="resume-text">Les grands moments de la presse d\'opinion marquent l\'histoire politique : J\'Accuse de Zola (1898) dans L\'Aurore mobilise l\'opinion dans l\'Affaire Dreyfus ; les journaux clandestins de la Resistance (Combat, Liberation, Franc-Tireur) maintiennent la flamme democratique sous l\'Occupation. La presse partisane (organes de partis politiques) a longtemps structure le paysage mediatique francais, avant le basculement vers une presse d\'information generaliste apolitique au cours du XXe siecle.</p>'
    '<div class="highlight-box"><p>La loi du 29 juillet 1881 sur la liberte de la presse est le texte fondateur du journalisme francais. Elle etablit que toute publication est libre et fixe les limites (diffamation, injure, incitation a la haine).</p></div>'
    '<h3>L\'ere des magazines et de la presse specialisee</h3>'
    '<p class="resume-text">Parallelement a la presse quotidienne d\'information generale, se developpent au XXe siecle des <strong>presses specialisees</strong> aux logiques editoriales distinctes : presse feminine (Elle fonde en 1945, Marie Claire), presse masculine, presse economique et financiere (Les Echos, 1908), presse scientifique de vulgarisation (Science & Vie, 1913 ; Pour la Science), presse sportive, presse regionale, magazines culturels. Cette specialisation reflete la segmentation croissante des publics et des marches publicitaires.</p>'
    '<p class="resume-text">L\'invention du <strong>magazine</strong> americain (Time, 1923 ; Life, 1936 ; Newsweek, 1933) inaugure un nouveau format : hebdomadaire, illustre, synthetique, accessible. Life popularise le photojournalisme et cree une culture visuelle de masse. Le Reader\'s Digest (1922) invente la synthese et la lisibilite pour les classes moyennes. Ces modeles exportes mondialement transforment les pratiques de lecture et les attentes vis-a-vis de l\'information : brievete, illustration, angle narratif, personnalisation.</p>'
    '<div class="highlight-box"><p>Life Magazine (1936-1972) a invente le photojournalisme comme narration visuelle : une seule photographie pouvait raconter une guerre, une vie, une epoque. Son influence sur la communication visuelle contemporaine reste immense.</p></div>'
    '<h3>Presse et democratie : un lien fondamental</h3>'
    '<p class="resume-text">La presse libre est consideree comme le <strong>quatrieme pouvoir</strong> — expression popularisee par Edmund Burke — aux cotes des pouvoirs legislatif, executif et judiciaire. Sa fonction democratique est triple : informer les citoyens, controler les pouvoirs (watchdog journalism) et offrir un forum de deliberation publique. Le classement mondial de la liberte de la presse etabli par Reporters sans Frontieres (RSF) mesure chaque annee dans 180 pays les conditions d\'exercice du journalisme : independance editorial, securite des journalistes, acces a l\'information.</p>'
    '<p class="resume-text">La <strong>concentration des medias</strong> est un enjeu majeur pour la pluralite democratique. En France, neuf milliardaires controlent la quasi-totalite des grands medias nationaux (Bolloré : CNews, Europe 1 ; Arnault : Le Parisien, Les Echos ; Niel, Pigasse, Berge : Le Monde, L\'Obs). Cette concentration souleve des questions sur l\'independance editoriale et les conflits d\'interets. Le modele des medias publics (BBC, France Televisions, Arte) vise a garantir un service d\'information independant des logiques commerciales et des pressions politiques.</p>'
    '<div class="highlight-box"><p>Reporters sans Frontieres : en 2024, seulement un tiers des pays du monde offre des conditions satisfaisantes a la liberte de la presse. Le journalisme est une profession dangereuse : plus de 500 journalistes sont emprisonnes dans le monde.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== journalisme/deontologie-journalistique =====
k = 'journalisme/deontologie-journalistique'
extra = (
    '<h3>Sources, verification et processus editorial</h3>'
    '<p class="resume-text">La <strong>verification de l\'information</strong> est le coeur du metier journalistique. La regle des deux sources independantes — ne publier une information que si elle est confirmee par au moins deux sources independantes — est un standard professionnel fondamental, bien que souvent mis sous pression par la concurrence et la vitesse. Bob Woodward, celebre pour son travail sur le Watergate, a formule le principe : suivre l\'argent (follow the money) pour decouvrir les corruptions dissimulees sous la bureaucratie.</p>'
    '<p class="resume-text">La <strong>hierarchisation des sources</strong> distingue les sources primaires (documents officiels, temoins directs, experts), les sources secondaires (autres medias, communiques de presse) et les sources anonymes (tres utiles pour les enquetes sensibles mais exigeant une vigilance accrue). La protection des sources journalistiques est un droit fondamental consacre par la Cour europeenne des droits de l\'homme : sans cette protection, les lanceurs d\'alerte et les informateurs n\'oseraient pas s\'exprimer, appauvrissant considerablement l\'information d\'interet public.</p>'
    '<div class="highlight-box"><p>La regle des deux sources independantes : un seul temoignage, si credible soit-il, ne suffit pas. L\'information doit etre croisee, verifiee, contextualisee avant publication.</p></div>'
    '<h3>Les limites de la deontologie : pressions et compromissions</h3>'
    '<p class="resume-text">Les journalistes exercent dans un contexte de <strong>pressions multiples</strong> : economiques (le proprietaire du media, les annonceurs publicitaires), politiques (le pouvoir en place, les groupes de pression), ideologiques (les convictions personnelles, l\'air du temps) et temporelles (la course a l\'exclusivite, le cycle de l\'information continue). Pierre Bourdieu (<em>Sur la television</em>, 1996) a analyse comment le champ journalistique est structure par ces pressions, conduisant a des phenomenes d\'autocensure, d\'homogeneisation des perspectives et de sensationnalisme.</p>'
    '<p class="resume-text">L\'<strong>objectivite journalistique</strong> est souvent critiquee comme une illusion : tout journaliste fait des choix (quoi couvrir, comment cadrer, qui interviewer, quoi citer) qui refletent une perspective. La notion de <strong>biais mediatique</strong> designe l\'ecart systematique entre la realite et sa representation mediatique, qu\'il soit lie aux valeurs du journaliste, a la structure de la redaction ou aux contraintes economiques du media. L\'alternative proposee est le journalisme de solutions (ou constructif), qui ne nie pas la subjectivite mais la rend transparente et l\'oriente vers l\'utilite sociale.</p>'
    '<div class="highlight-box"><p>Bourdieu : l\'homogeneisation mediatique n\'est pas un complot mais un effet de structure. La competition pour l\'audience conduit tous les medias vers les memes sujets, les memes angles, les memes tetes.</p></div>'
    '<h3>Regulation, autoregulation et nouvelles instances</h3>'
    '<p class="resume-text">La <strong>regulation des medias</strong> oscille entre regulation publique (le CSA, devenu Arcom en France, qui encadre l\'audiovisuel) et autoregulation professionnelle. Le Conseil de presse, institution independante presente dans de nombreux pays (mais pas en France, malgre plusieurs tentatives), est compose de journalistes, d\'editeurs et de representants du public pour traiter les plaintes et definir des standards. En Scandinavie, les conseils de presse fonctionnent efficacement depuis un siecle, contribuant a la confiance du public envers les medias.</p>'
    '<p class="resume-text">L\'essor des <strong>medias en ligne</strong> a complexifie le paysage de la regulation : qui est journaliste, qui ne l\'est pas ? Les blogueurs, les youtubeurs d\'information, les comptes Twitter influents pratiquent-ils du journalisme ? La carte de presse (en France, delivree par la CCIJP) n\'est pas obligatoire pour exercer mais confere un statut juridique specifique et des droits (protection des sources, acces aux zones de presse). La question de la reconnaissance et de la formation des journalistes en ligne est au coeur des debats contemporains sur la regulation des medias numeriques.</p>'
    '<div class="highlight-box"><p>L\'Arcom (Autorite de regulation de la communication audiovisuelle et numerique, creee en 2022) etend ses competences aux grandes plateformes numeriques — un enjeu majeur pour la regulation des contenus en ligne.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

# ===== journalisme/journalisme-investigation =====
k = 'journalisme/journalisme-investigation'
extra = (
    '<h3>Le journalisme collaboratif transnational</h3>'
    '<p class="resume-text">La revelation des <strong>Panama Papers</strong> (2016) a inaugure une nouvelle ere du journalisme d\'investigation collaborative. Plus de 370 journalistes de 76 pays, coordonnes par le Consortium international des journalistes d\'investigation (ICIJ), ont analyse 11,5 millions de documents en 14 mois avant publication simultanee mondiale. Cette coordination transnationale a rendu impossible les represailles juridiques locales et permis une couverture de 200 pays et territoires. Les Pandora Papers (2021) ont suivi le meme modele avec 600 journalistes et 2,9 teraoctets de donnees.</p>'
    '<p class="resume-text">Le <strong>datajournalisme</strong> (journalisme de donnees) utilise les techniques d\'analyse statistique, de visualisation et de programmation pour explorer de grandes masses de donnees et en extraire des informations d\'interet public. Des outils comme Python, R, Tableau ou QSIG permettent de cartographier la corruption, d\'analyser les votes parlementaires, de visualiser les flux financiers. Le Guardian Data Blog, pionnier du genre, a montre comment la pedagogie visuelle peut rendre accessible des informations complexes a un large public.</p>'
    '<div class="highlight-box"><p>Les Panama Papers : 11,5 millions de documents, 370 journalistes, 76 pays, une coordination de 14 mois — et l\'evasion fiscale mondiale mise a nu. Le journalisme colaboratif a change d\'echelle.</p></div>'
    '<h3>Contraintes juridiques et dangers du metier</h3>'
    '<p class="resume-text">Le journalisme d\'investigation affronte des <strong>obstacles juridiques</strong> considerables : poursuites en diffamation (libel tourism, pratique de poursuivre dans les juridictions les plus favorables aux plaignants), injonctions preventives de publication (super-injunctions), plaintes SLAPP (Strategic Lawsuit Against Public Participation) — poursuites abusives visant non a obtenir gain de cause mais a epuiser financierement les medias et les journalistes. La directive europeenne anti-SLAPP (2024) vise a proteger les journalistes et militants contre ces abus processuels.</p>'
    '<p class="resume-text">Sur le terrain, le journalisme d\'investigation peut etre <strong>dangereux</strong> : Jamal Khashoggi, journaliste saoudien du Washington Post, a ete assassine a l\'ambassade saoudienne d\'Istanbul en 2018. Daphne Caruana Galizia, journaliste d\'investigation maltaise qui enquetait sur les Panama Papers locaux, a ete tuee par une voiture piegee en 2017. Reporters sans Frontieres recense plus de 50 journalistes tues chaque annee, la plupart dans des zones de conflit ou en raison d\'enquetes sur la corruption et le crime organise.</p>'
    '<div class="highlight-box"><p>Les SLAPP (poursuites abusives) sont une arme juridique contre le journalisme d\'investigation : non pour gagner le proces, mais pour ruiner financierement le media et decourager toute enquete future.</p></div>'
    '<h3>L\'avenir de l\'investigation : IA et journalisme forensique</h3>'
    '<p class="resume-text">L\'<strong>intelligence artificielle</strong> transforme les methodes d\'investigation : les outils de reconnaissance de visages, d\'analyse audio et video (Bellingcat), de verification de geolocalisation par images satellites (Google Earth, Sentinel Hub), de detection de deepfakes et d\'analyse de metadonnees permettent des enquetes que les journalistes ne pouvaient pas conduire seuls il y a dix ans. Le <strong>journalisme forensique</strong> (forensic journalism) utilise ces technologies pour documenter des crimes de guerre, des mensonges gouvernementaux et des manipulations d\'images sur les reseaux sociaux.</p>'
    '<p class="resume-text">Paradoxalement, l\'IA menace aussi l\'investigation en facilitant la <strong>fabrication de preuves</strong> : deepfakes audio et video, documents falsifies realistes, faux comptes convaincants. La course entre les outils de creation et de detection de contenus falsifies s\'accelere. Des organisations comme le Digital Forensic Research Lab de l\'Atlantic Council ou le Media Manipulation Casebook de Harvard cataloguent ces nouvelles menaces et developpent des contre-mesures. La litteratie numerique et forensique devient une competence fondamentale pour tout journaliste contemporain.</p>'
    '<div class="highlight-box"><p>Bellingcat a montre que le journalisme forensique open source — utiliser des images satellites, des videos geolocalisees et des donnees publiques — peut documenter des crimes de guerre mieux que certains services de renseignement.</p></div>'
)
pages[k]['content'] = enrich_contenu(pages[k]['content'], extra)
print(f"{k}: {len(pages[k]['content'])} chars")

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/communication.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved batch 2 (5 articles)")
