import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

enrichments = {}

enrichments['genie-civil/structures-porteuses'] = (
    '<h3>Types de structures porteuses</h3>'
    '<p class="resume-text">Les <strong>structures en treillis</strong> sont constituées de barres rectilignes reliées par des nœuds articulés. Chaque barre ne travaille qu\'en traction ou compression pure — sans flexion. Les ponts en treillis (Pratt, Warren, Howe) et les charpentes métalliques industrielles exploitent cette efficacité. La méthode des nœuds et la méthode des sections permettent de calculer les efforts dans chaque barre. Le viaduc de Millau illustre la complémentarité des câbles (traction pure) et des piliers en béton (compression).</p>'
    '<p class="resume-text">Les <strong>portiques</strong> sont des structures où les poteaux et les poutres ont des joints rigides. Contrairement aux treillis, les barres travaillent simultanément en compression, cisaillement et flexion. Le portique hyperstatique distribue les charges de façon plus efficace. Les <strong>câbles et arcs</strong> exploitent les propriétés des matériaux : le câble travaille en traction pure (idéal pour l\'acier), l\'arc en compression pure (idéal pour la pierre et le béton). Les ponts suspendus (câbles porteurs) et les voûtes romaines illustrent ces principes.</p>'
    '<div class="highlight-box"><p>Le Viaduct de Millau, avec ses pylônes de 343 m et son tablier en béton précontraint, est la démonstration moderne que câbles, béton et acier peuvent être combinés pour franchir des vallées de plusieurs centaines de mètres.</p></div>'
    '<h3>Méthodes d\'analyse des structures</h3>'
    '<p class="resume-text">La <strong>méthode des éléments finis</strong> (MEF) est l\'outil numérique universel pour l\'analyse des structures. Elle discrétise la structure en éléments reliés par des nœuds et résout le système K·u = F (raideur × déplacements = forces). Les logiciels Robot, ETABS, SAP2000 et ANSYS permettent d\'analyser des structures à milliers de degrés de liberté. Les simulations non-linéaires modélisent la fissuration du béton, la plastification de l\'acier et les grands déplacements.</p>'
    '<p class="resume-text">L\'<strong>analyse dynamique</strong> des structures est indispensable en ingénierie sismique. Le spectre de réponse donne l\'accélération spectrale en fonction de la période propre. L\'analyse temporelle directe (pas à pas) simule la réponse de la structure à l\'historique de l\'accélération sismique. Ces analyses permettent de vérifier que les déformations plastiques (rotules plastiques) se forment dans les zones prévues et que la structure ne s\'effondre pas.</p>'
    '<p class="resume-text">Le <strong>calcul aux états limites</strong> (Eurocode 2 et 3 en Europe) distingue les états limites ultimes (ELU, ruine) et de service (ELS, fissurations, déformations). Aux ELU, les charges sont majorées (facteur 1,35 à 1,5) et les résistances minorées. Les coefficients partiels de sécurité visent un taux de défaillance de 10⁻⁶ par an — une probabilité comparable à celle d\'être frappé par la foudre.</p>'
    '<div class="highlight-box"><p>Les logiciels d\'éléments finis modernes peuvent modéliser en quelques heures le comportement sismique d\'un gratte-ciel de 100 étages avec des millions de degrés de liberté — un calcul qui aurait pris des années à la main.</p></div>'
    '<h3>Matériaux de construction et durabilité</h3>'
    '<p class="resume-text">L\'<strong>acier de construction</strong> (S235, S355) offre résistance élevée et excellente ductilité. La ductilité est cruciale en sismique : elle permet de se déformer plastiquement sans rupture fragile. Les assemblages boulonnés à haute résistance (HR) et soudés sont dimensionnés avec soin — les concentrations de contraintes et défauts de soudure sont les sources premières de fatigue. Les aciers inoxydables (grades 316, 2205 duplex) sont utilisés dans les environnements corrosifs (offshore, coastal).</p>'
    '<p class="resume-text">Le <strong>béton haute performance</strong> (BHP, résistance supérieure à 60 MPa) réduit les sections de piliers et allonge les portées. Les BHP sont obtenus par réduction du rapport eau/ciment, ajout de fumée de silice et plastifiants. Les BUHP (Ultra-Haute Performance, supérieur à 150 MPa), comme le Ductal®, contiennent des fibres métalliques leur conférant une résistance à la flexion sans armatures passives. Ces matériaux révolutionnent la conception des structures légères.</p>'
    '<p class="resume-text">La <strong>durabilité des structures</strong> est un enjeu économique et environnemental majeur. La corrosion des armatures du béton armé coûte des milliards d\'euros par an en Europe. Les solutions incluent les armatures en acier inoxydable, les revêtements époxy, le béton à ultra-faible porosité et la protection cathodique. La durée de vie prévue d\'un pont est de 100 ans — une exigence qui impose une conception robuste face aux agents agressifs dès l\'origine.</p>'
    '<div class="highlight-box"><p>La corrosion des infrastructures en béton armé coûte plus de 300 milliards d\'euros par an dans le monde — plus que le budget de construction de nouvelles infrastructures dans de nombreux pays.</p></div>'
)

enrichments['genie-civil/beton-arme'] = (
    '<h3>Comportement du béton et des armatures</h3>'
    '<p class="resume-text">Le <strong>béton</strong> est excellent en compression (résistance fc\' de 25 à 100 MPa) mais très faible en traction (environ 1/10 de la compression). Les armatures d\'acier placées dans les zones tendues compensent cette faiblesse. En flexion, la zone supérieure est comprimée (béton seul) et la zone inférieure est tendue (armatures). Le <strong>module d\'élasticité</strong> du béton (E ≈ 30 GPa) est 7 fois plus faible que celui de l\'acier (210 GPa), conduisant au concept de section homogène dans les calculs.</p>'
    '<p class="resume-text">Le <strong>fluage</strong> est la déformation différée du béton sous charge constante : sur 50 ans, le béton peut se déformer 2 à 3 fois plus que sa déformation initiale. Ce phénomène crée des redistributions d\'efforts dans les structures hyperstatiques et des pertes dans les câbles de précontrainte. Le <strong>retrait</strong> (perte d\'eau au séchage) provoque des fissurations précoces des dalles et voiles — d\'où l\'importance des joints de dilatation et des armatures minimales de retrait.</p>'
    '<div class="highlight-box"><p>Le retrait du béton et le fluage sont responsables de la plupart des fissurations prématurées des structures — une bonne conception prévoit des armatures de retrait, des joints et des délais de mise en charge.</p></div>'
    '<h3>Dimensionnement en flexion et cisaillement</h3>'
    '<p class="resume-text">Le <strong>dimensionnement en flexion simple</strong> d\'une section rectangulaire équilibre le moment résistant (couple béton-acier) avec le moment sollicitant. La condition de ductilité limite le taux d\'armature maximum pour garantir une rupture progressive par plastification de l\'acier plutôt qu\'un écrasement brutal du béton. Les tables d\'abaque ou les formules d\'Eurocode 2 permettent de calculer l\'aire d\'armature nécessaire.</p>'
    '<p class="resume-text">Le <strong>cisaillement</strong> crée des contraintes diagonales de traction que le béton seul ne peut reprendre. Les <strong>étriers</strong> (armatures transversales fermées) résistent à ce cisaillement. Le modèle du treillis (Ritter-Mörsch) représente le béton comprimé par des bielles diagonales et les étriers par des membrures tendues. Les poutres sans étriers risquent la rupture par cisaillement — brutale et sans avertissement — d\'où les armatures de cisaillement minimales imposées par les règlements.</p>'
    '<p class="resume-text">Les <strong>fondations</strong> transmettent les charges au sol. Les semelles isolées (sous poteaux), semelles filantes (sous murs), radiers généraux et pieux sont choisis selon la résistance du sol et les charges. Le poinçonnement des dalles sous poteaux (analogue du cisaillement sur poutres) est une rupture fragile à vérifier soigneusement. Les armatures de poinçonnement (têtes de cisaillement, goujons) sont indispensables dans les structures post-tendues et les dalles champignons sans poutres.</p>'
    '<div class="highlight-box"><p>La rupture d\'un pont par cisaillement (sans armatures transversales) est soudaine et sans signe avant-coureur — contre une rupture en flexion progressive par plastification des armatures : les règlements imposent donc un minimum d\'étriers même pour les charges faibles.</p></div>'
    '<h3>Béton précontraint et grandes portées</h3>'
    '<p class="resume-text">La <strong>précontrainte</strong> introduit des compressions dans le béton avant chargement. En prétension, des câbles tendus avant bétonnage transfèrent leur effort par adhérence. En post-tension, les câbles sont tendus après durcissement par des vérins et bloqués par des ancres. Le béton précontraint permet de grandes portées sans fissuration (ponts à poutres préfabriquées jusqu\'à 40 m, ponts construits en encorbellements successifs jusqu\'à 200 m).</p>'
    '<p class="resume-text">Les <strong>pertes de précontrainte</strong> (frottement, recul d\'ancrage, fluage, retrait, relaxation des aciers) réduisent de 15 à 25% l\'effort initial. Les câbles de précontrainte en acier haute résistance (1860 MPa) minimisent l\'impact relatif de ces pertes. Les réservoirs d\'eau, les enceintes de réacteurs nucléaires et les silos utilisent la précontrainte circulaire pour reprendre la pression interne sans fissuration.</p>'
    '<p class="resume-text">La <strong>construction par encorbellements successifs</strong> construit le tablier depuis les piles de part et d\'autre sans échafaudage au sol. Des équipages mobiles (coffrages autoperçants) coulent un voussoir de 3-5 m toutes les 1-2 semaines. Cette méthode est idéale pour les ponts en vallée profonde ou en milieu maritime. Le pont de Normandie (856 m de portée centrale) et le viaduc de Millau ont été construits ainsi.</p>'
    '<div class="highlight-box"><p>Le viaduc de Millau utilise des tabliers en béton précontraint pour ses travées de 342 m de long — sans précontrainte, les armatures passives nécessaires pèseraient plusieurs fois le poids du béton.</p></div>'
)

enrichments['genie-civil/ponts'] = (
    '<h3>Typologies de ponts</h3>'
    '<p class="resume-text">Le choix du type de pont dépend de la portée, du sol de fondation, du contexte et du budget. Pour les portées courtes (moins de 30 m), les <strong>poutres préfabriquées</strong> posées sur appuis sont les plus économiques. Les portées moyennes (30-150 m) conviennent aux ponts à tablier mixte acier-béton. Les <strong>ponts à haubans</strong> (câbles rectilignes depuis des pylônes jusqu\'au tablier) atteignent 1104 m de portée (pont de Russky, Russie). Les <strong>ponts suspendus</strong> (câbles porteurs paraboliques) détiennent le record avec 1991 m (Akashi-Kaikyo, Japon).</p>'
    '<p class="resume-text">Les <strong>ponts en arc</strong> exploitent la compression du béton ou de l\'acier pour franchir des gorges profondes (New River Gorge, USA, 518 m en acier). Les ponts en arc à tablier inférieur (through arch) permettent de passer sous l\'arc pour les viaducs urbains. Les <strong>ponts à voussoirs préfabriqués</strong> assemblent en hauteur des éléments préfabriqués en usine, permettant une construction rapide (autoroutes urbaines, LGV).</p>'
    '<div class="highlight-box"><p>Le Golden Gate (1280 m de portée, San Francisco, 1937) et l\'Akashi-Kaikyo (1991 m, Japon, 1998) illustrent l\'évolution de la portée des ponts suspendus en 60 ans — grâce aux progrès de la métallurgie et de l\'analyse structurale.</p></div>'
    '<h3>Construction et pathologies des ponts</h3>'
    '<p class="resume-text">La <strong>construction par encorbellements successifs</strong> (free cantilever) avance le tablier depuis les piles sans échafaudage au sol — idéale pour les ponts en vallée profonde ou en milieu maritime. Le <strong>lançage</strong> assemble le tablier métallique ou mixte en arrière-culée, puis le pousse par vérins sur des appuis provisoires. Le <strong>levage par grands modules</strong> assemble au sol des sections de plusieurs centaines de tonnes, levées par grues flottantes — standard pour les ponts maritimes asiatiques.</p>'
    '<p class="resume-text">Les <strong>appareils d\'appui</strong> (pot en élastomère, pendule sismique, amortisseurs) permettent les mouvements thermiques (dilatation de 100 mm pour 100 m entre été et hiver) et assurent la durabilité. Les joints de chaussée résistent à 100 millions de cycles de fatigue (passage de camions) tout en assurant l\'étanchéité. Leur entretien régulier est essentiel pour la durabilité de l\'ouvrage.</p>'
    '<p class="resume-text">Les <strong>pathologies courantes</strong> incluent la corrosion des armatures (béton carbonaté ou chloruré), les fissurations de fatigue dans les tabliers métalliques, l\'affouillement des fondations (érosion du lit de rivière autour des piles) et les tassements différentiels. L\'effondrement du pont de Gênes (Morandi, 2018, 43 victimes) a rappelé l\'importance de l\'entretien : les haubans en béton précontraint avaient subi une dégradation progressive non détectée.</p>'
    '<div class="highlight-box"><p>L\'effondrement du pont Morandi à Gênes (2018, 43 victimes) a conduit à un audit de 2000 ponts en Italie — rappelant que l\'entretien des infrastructures est une question de sécurité publique et non une dépense discrétionnaire.</p></div>'
    '<h3>Inspection et réhabilitation</h3>'
    '<p class="resume-text">Les <strong>inspections de ponts</strong> sont méthodiques et régulières. En France, le système IQOA classe les ponts de 1 (bon état) à 3U (danger immédiat). Les inspections visuelles sont complétées par l\'auscultation non destructive : ultrasons, thermographie infrarouge, radar géophysique (GPR) pour détecter les défauts cachés (armatures corrodées, vides de béton). Les drones permettent l\'inspection des éléments inaccessibles (dessous de tablier, zones sous câbles) à moindre coût.</p>'
    '<p class="resume-text">La <strong>réhabilitation</strong> des ponts anciens mobilise des techniques variées : injection d\'époxy dans les fissures, collage de plats de carbone (PRFC) pour renforcer la flexion, déviateurs extérieurs pour ajouter de la précontrainte, remplacement des appuis par des isolateurs sismiques. La réhabilitation coûte souvent 30-50% d\'un pont neuf — mais préserve l\'ouvrage existant et son histoire. Les ponts du 19e siècle (Garabit, pont Maria Pia de Gustave Eiffel) sont réhabilités plutôt que remplacés pour leur valeur patrimoniale.</p>'
    '<p class="resume-text">Le <strong>monitoring structurel</strong> (SHM — Structural Health Monitoring) installe des capteurs permanents (accéléromètres, jauges de déformation, inclinomètres, thermomètres) sur les ouvrages importants. L\'analyse continue des données détecte les évolutions anormales (fréquences propres qui changent, déformations qui croissent) bien avant qu\'elles deviennent visibles. L\'intelligence artificielle appliquée au SHM commence à permettre la maintenance prédictive des ponts — un enjeu crucial pour les 500 000 ponts français.</p>'
    '<div class="highlight-box"><p>Le monitoring continu du pont du Rion-Antirion (Grèce) surveille en permanence ses 5 câbles, 4 pylônes et tablier avec 200 capteurs connectés — permettant de détecter tout comportement anormal avant qu\'il devienne dangereux.</p></div>'
)

enrichments['genie-civil/fondations'] = (
    '<h3>Reconnaissances géotechniques</h3>'
    '<p class="resume-text">Avant toute conception de fondation, une <strong>campagne de reconnaissance du sol</strong> est indispensable. Les sondages combinent forages (carottes prélevées pour analyses), essais in situ (pénétromètre statique CPT, pressiomètre Ménard, SPT) et prospections géophysiques (sismique réfraction, tomographie électrique). Les <strong>paramètres clés</strong> sont la cohésion c et l\'angle de frottement interne φ (capacité portante), le module d\'Young (tassements) et le coefficient de perméabilité k (écoulements). La Tour de Pise illustre les conséquences d\'une reconnaissance insuffisante : un tassement différentiel de 5,5 m dû à une couche d\'argile molle asymétrique sous la fondation.</p>'
    '<p class="resume-text">Les <strong>problèmes géotechniques spéciaux</strong> incluent les sols gonflants (argiles expansives qui soulèvent les fondations), les sols liquéfiables (sables saturés qui perdent leur résistance sous vibration sismique), les glissements de terrain et les sols karstiques (cavités dissolutionnelles dans les calcaires). La liquéfaction a causé des dégâts considérables lors du séisme de Niigata (Japon, 1964) et des séismes de Christchurch (Nouvelle-Zélande, 2010-2011).</p>'
    '<div class="highlight-box"><p>La Tour de Pise doit son inclinaison à une couche d\'argile molle asymétrique sous sa fondation — un tassement différentiel de 5,5 m sur 8 siècles, aujourd\'hui stabilisé par extraction contrôlée de sol sous le côté le moins tassé.</p></div>'
    '<h3>Fondations profondes : pieux et techniques spéciales</h3>'
    '<p class="resume-text">Les <strong>pieux</strong> transmettent les charges aux couches portantes profondes par frottement latéral et résistance de pointe. Les pieux forés (grands diamètres, 0,6-2 m) et les pieux battus ou vibrés (petits diamètres, 0,3-0,6 m) sont les deux grandes familles. La capacité portante est calculée par méthodes pressiométriques (Ménard) et validée par essais de chargement statique. Les fondations du Burj Khalifa reposent sur 194 pieux de 1,5 m de diamètre et 43 m de profondeur dans le calcaire poreux.</p>'
    '<p class="resume-text">Les <strong>techniques de renforcement des sols</strong> incluent les colonnes ballastées (inclusions rigides de gravier compacté pour les sols mous), le jet grouting (injection de ciment à haute pression pour consolider le sol), les colonnes de sol-ciment et les micro-pieux (100-300 mm, pour les espaces confinés ou sous bâtiments existants). Ces techniques permettent d\'intervenir sur des sols initialement impropres à la construction.</p>'
    '<p class="resume-text">Les <strong>ouvrages de soutènement</strong> (parois moulées, rideaux de palplanches, butons, tirants d\'ancrage) permettent les excavations profondes en milieu urbain. La paroi moulée est excavée sous boue bentonitique puis bétonnée — elle sert simultanément d\'écran étanche, de soutènement et de fondation. La méthode observationnelle adapte les mesures de soutènement en temps réel grâce à l\'instrumentation (inclinomètres, jauges, cibles topographiques).</p>'
    '<div class="highlight-box"><p>Les fondations du Burj Khalifa (828 m, Dubai) nécessitent 194 pieux de 1,5 m de diamètre et 43 m de longueur — 45 000 tonnes de béton pour supporter une tour qui pèse 500 000 tonnes.</p></div>'
    '<h3>Tassements et consolidation</h3>'
    '<p class="resume-text">Les <strong>tassements des sols argileux</strong> se produisent progressivement (consolidation primaire) par expulsion de l\'eau interstitielle sous pression. L\'<strong>essai œdométrique</strong> mesure la compressibilité d\'un échantillon de sol sous charge axiale et drainée. Le temps de consolidation, proportionnel au carré de l\'épaisseur de la couche drainée, peut être de plusieurs années pour les argiles épaisses. Les drains verticaux (préfabriqués) accélèrent la consolidation en divisant par 100 le chemin de drainage.</p>'
    '<p class="resume-text">Les <strong>tassements différentiels</strong> (différence de tassement entre deux points d\'une structure) sont plus dommageables que les tassements uniformes. Ils fissurent les maçonneries, bloquent les portes et penchent les structures. La limitation des tassements différentiels est l\'une des principales contraintes du dimensionnement des fondations. Le radier général (dalle en béton sous toute l\'emprise de l\'ouvrage) homogénéise les tassements. Les semelles sur micropieux, plus rigides, réduisent aussi les différentiels.</p>'
    '<p class="resume-text">La <strong>gestion de l\'eau souterraine</strong> (rabattement de nappe) est souvent nécessaire lors des fouilles profondes. Les pompes immergées dans des puits ou les pointes filtrantes abaissent temporairement la nappe phréatique. Le rabattement modifie les contraintes effectives dans le sol (consolidation autour de la fouille), peut tasser les constructions riveraines et nécessite un suivi piézométrique continu. Les injections de gel (cryogénie) ou de silicate de soude peuvent geler ou consolider le sol pour des fouilles ponctuelles à très haute pression d\'eau.</p>'
    '<div class="highlight-box"><p>La construction du Grand Paris Express nécessite 200 km de tunnels et des dizaines de stations profondes — chaque fouille en milieu urbain dense mobilise géotechniciens, hydrogéologues et ingénieurs structures pour éviter tout impact sur les bâtiments riverains.</p></div>'
)

enrichments['genie-civil/construction-parasismique'] = (
    '<h3>Ingénierie sismique : aléa et spectre de réponse</h3>'
    '<p class="resume-text">L\'<strong>aléa sismique</strong> caractérise la probabilité d\'occurrence d\'un séisme d\'intensité donnée en un site. Les cartes d\'aléa (Eurocode 8) donnent l\'accélération de référence agR pour une probabilité de dépassement de 10% en 50 ans (période de retour 475 ans). Le <strong>spectre de réponse élastique</strong> donne l\'accélération spectrale maximale en fonction de la période propre de la structure. Les ingénieurs calculent la période propre de leur bâtiment (T ≈ 0,075H³/⁴) pour lire l\'accélération de dimensionnement correspondante.</p>'
    '<p class="resume-text">Le <strong>comportement ductile</strong> est la clé de la résistance sismique. La conception parasismique accepte la plastification des éléments structuraux lors d\'un fort séisme — mais impose que cette plastification se fasse de façon contrôlée et ductile. Le <strong>facteur de comportement q</strong> réduit les forces sismiques de conception en échange d\'une exigence de ductilité accrue dans les détails de ferraillage. Pour les structures en béton armé à haute ductilité (DCH), q peut atteindre 5 à 6 — on conçoit pour 5 fois moins de force mais avec des exigences de ferraillage strictes.</p>'
    '<div class="highlight-box"><p>Le séisme de Kobe (1995, 6400 victimes) a conduit au refonte des codes parasismiques japonais — les bâtiments construits après 1981 ont globalement bien résisté, contrairement aux structures plus anciennes non conçues pour la ductilité.</p></div>'
    '<h3>Systèmes de contreventement sismique</h3>'
    '<p class="resume-text">Les <strong>voiles de contreventement</strong> en béton armé reprennent les forces horizontales sismiques. Leur disposition en plan symétrique (sans excentricité entre centre de masse et centre de rigidité) évite les effets de torsion qui amplifient les déformations locales. Les noyaux centraux (escaliers, ascenseurs) sont des contreventements efficaces. Le principe <strong>poteaux forts / poutres faibles</strong> garantit que les rotules plastiques se forment en priorité dans les poutres, préservant la stabilité verticale même après plastification généralisée.</p>'
    '<p class="resume-text">Les <strong>cadres résistants aux moments</strong> (moment-resisting frames, MRF) utilisent la rigidité des nœuds poteaux-poutres. Les détails de ferraillage des zones de rotule potentielle (armatures confinantes, crosse des aciers longitudinaux) sont primordiaux pour assurer la ductilité nécessaire. Les <strong>contreventements excentriques</strong> (EBF) en acier introduisent un lien ductile (fusible) dans la diagonale qui plastifie avant le flambement, dissipant l\'énergie sismique de façon contrôlée.</p>'
    '<p class="resume-text">L\'<strong>isolation sismique à la base</strong> (appareils en élastomère fretté ou pendules à glissement) allonge la période propre de la structure de 0,3 s à 3 s. En se déplaçant dans le spectre vers les périodes longues (zone de moindre énergie), l\'accélération de la structure peut être réduite d\'un facteur 5 à 10. Les hôpitaux, musées et bâtiments gouvernementaux stratégiques au Japon, en Californie et en Nouvelle-Zélande utilisent largement cette technique.</p>'
    '<div class="highlight-box"><p>La Tour Taipei 101 (509 m) possède le plus grand amortisseur de masse accordée au monde : une sphère de 660 tonnes suspendue à 87 m de câbles oscillant en opposition au vent et aux séismes pour réduire de 40% les accélérations aux étages supérieurs.</p></div>'
    '<h3>Comportement post-sismique et résilience</h3>'
    '<p class="resume-text">La <strong>performance sismique</strong> est désormais exprimée en termes de niveaux de performance (occupation immédiate, sécurité de la vie, prévention de l\'effondrement) associés à des niveaux de séisme (fréquent, rare, très rare). L\'approche PBSD (Performance-Based Seismic Design) permet aux ingénieurs et maîtres d\'ouvrage de négocier explicitement le niveau de dommage acceptable — un hôpital doit rester opérationnel après un séisme rare, tandis qu\'un immeuble résidentiel peut subir des dommages réparables.</p>'
    '<p class="resume-text">La <strong>résilience sismique</strong> intègre non seulement la résistance structurale mais aussi la rapidité de récupération. Le temps de remise en service d\'une infrastructure (pont, hôpital, centrale électrique) après un séisme peut être réduit par la conception préventive (redondance, préfabrication facilitant le remplacement rapide des éléments endommagés, systèmes de détection rapide des dommages). La Nouvelle-Zélande et le Chili ont développé des stratégies de résilience sismique urbaine après leurs récents séismes majeurs.</p>'
    '<p class="resume-text">Les <strong>techniques de réhabilitation sismique</strong> des bâtiments existants incluent l\'ajout de voiles ou de contreventements métalliques, le confinement des poteaux par chemisage en béton, acier ou PRFC (fibres de carbone), et l\'isolation sismique par remplacement des appuis existants. Ces interventions sont classées par rapport coût-efficacité (réduction du risque / coût de l\'intervention). Les séismes de Christchurch (2010-2011) ont conduit à la démolition de 60% des bâtiments du centre-ville, imposant une réflexion profonde sur les critères de réhabilitation vs remplacement.</p>'
    '<div class="highlight-box"><p>Le séisme de Christchurch (2011, Nouvelle-Zélande) a démontré que des bâtiments "conformes au code sismique" peuvent subir des dommages irréparables — conduisant à l\'introduction de critères de performance au-delà de la simple survie des occupants.</p></div>'
)

# Apply enrichments
count = 0
for key, extra in enrichments.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (genie-civil section)")
