#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrichit les articles de mythologie.json en ajoutant du contenu
dans la section id="contenu".
"""

import json
import re

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/mythologie.json'

# Nouveaux contenus à injecter, par clé de page
# On insère juste avant </section> de la section contenu
ENRICHMENTS = {
    'mythologies-antiques/mythologie-mesopotamienne': """<h3>La descente d'Inanna aux Enfers</h3><p class="resume-text">L'un des mythes sumériens les plus fascinants raconte la descente d'Inanna, reine du ciel, dans le monde souterrain gouverné par sa sœur Ereshkigal. À chaque des sept portes des Enfers, Inanna est dépouillée d'un attribut de sa puissance — couronne, parure, vêtements — jusqu'à ce qu'elle comparaisse nue devant sa sœur, qui la condamne à mort.</p><p class="resume-text">Sa servante Ninshubur alerte les dieux, et Enki crée deux êtres androgynes chargés de la ranimer avec la nourriture et l'eau de vie. Inanna revient du royaume des morts, mais les lois infernales exigent qu'un substitut prenne sa place : ce sera son époux Dumuzi, qui descend à son tour aux Enfers pour six mois de l'année, expliquant ainsi le rythme des saisons.</p><div class="highlight-box"><p>La descente d'Inanna est l'un des premiers mythes de mort et de résurrection connus, illustrant la cyclicité de la nature et la puissance des divinités féminines dans le monde mésopotamien.</p></div><h3>Héritage et transmission</h3><p class="resume-text">La mythologie mésopotamienne a exercé une influence considérable sur les cultures voisines. Le récit du Déluge, les motifs de création et de lutte cosmique se retrouvent dans la Bible hébraïque, les textes cananéens et même certains éléments grecs. Les premiers scribes babyloniens ont développé une tradition de commentaires et d'exégèse des textes sacrés qui annonce les grandes traditions herméneutiques du monde antique.</p><p class="resume-text">Les tablettes d'argile découvertes à Ninive, Nippur et Ur ont révélé un univers littéraire d'une richesse insoupçonnée. Les travaux de déchiffrement du cunéiforme au XIXe siècle ont permis de redécouvrir ce patrimoine et de comprendre les racines les plus profondes de la civilisation occidentale.</p>""",

    'mythologies-antiques/mythologie-egyptienne': """<h3>Le cycle d'Osiris</h3><p class="resume-text">Le mythe d'Osiris est le récit fondateur de la religion égyptienne. Osiris, roi juste et civilisateur, est assassiné et démembré par son frère Seth, dieu du chaos. Sa sœur et épouse Isis réunit les morceaux de son corps, le ressuscite temporairement et conçoit Horus, l'héritier légitime. Osiris devient alors le maître du royaume des morts.</p><p class="resume-text">Horus affronte Seth dans de longs combats mythiques qui symbolisent la lutte perpétuelle entre l'ordre (maât) et le chaos. La victoire de Horus restaure l'ordre cosmique. Ce cycle mort-résurrection-jugement structure toute la vision égyptienne du cosmos et de l'au-delà.</p><div class="highlight-box"><p>Le mythe d'Osiris a influencé de nombreuses traditions méditerranéennes et orientales, notamment les cultes à mystères gréco-romains qui célèbrent des dieux mourants et ressuscitant.</p></div><h3>Le Livre des Morts et la pesée de l'âme</h3><p class="resume-text">Les Égyptiens croyaient que l'âme du défunt devait traverser un jugement dans la salle des Deux-Maât. Le cœur du mort était pesé contre la plume de Maât (la vérité et la justice). Si le cœur était plus lourd que la plume, Ammout, la dévoreuse, le détruisait. Si la balance s'équilibrait, le défunt accédait au paradis de l'Aaru.</p><p class="resume-text">Le Livre des Morts, collection de formules magiques et d'hymnes, était glissé dans les tombeaux pour guider le défunt. Ces textes témoignent d'une réflexion élaborée sur la morale, la justice et la destinée de l'âme, bien antérieure aux grandes traditions philosophiques grecques.</p><h3>Cosmogonie et symbolisme solaire</h3><p class="resume-text">La cosmogonie héliopolitaine place Atoum (ou Rê-Atoum) au centre de la création : émergeant de l'océan primordial Noun, il crée Shou (l'air) et Tefnout (l'humidité) par expectoration. De Shou et Tefnout naissent Geb (la Terre) et Nout (le Ciel), puis Osiris, Isis, Seth et Nephthys. Le soleil effectue chaque nuit une traversée des Enfers dans sa barque avant de renaître à l'aube, symbolisant la victoire perpétuelle de la vie sur la mort.</p>""",

    'mythologies-antiques/mythologie-nordique': """<h3>L'arbre-monde Yggdrasil et les neuf mondes</h3><p class="resume-text">Au centre de la cosmologie nordique s'élève Yggdrasil, le frêne cosmique dont les racines plongent dans trois sources sacrées : Urðarbrunnr (le puits du Destin, gardé par les Nornes), Mímisbrunnr (le puits de la Sagesse, d'où Odin a bu en sacrifiant un œil) et Hvergelmir (la source primordiale). Les neuf mondes s'organisent autour de cet arbre, dont Ásgarðr (domaine des dieux), Miðgarðr (monde des hommes), Jötunheimr (monde des géants) et Hel (royaume des morts).</p><p class="resume-text">Un écureuil, Ratatoskr, monte et descend le long du tronc en transportant des messages entre l'aigle qui surveille les branches et le serpent Níðhöggr qui ronge les racines. Quatre cerfs broutent les feuilles, et une chèvre produit de l'hydromel. Yggdrasil illustre une conception organique du cosmos, vivant et fragile, voué à périr lors du Ragnarök.</p><div class="highlight-box"><p>Odin s'est lui-même pendu à Yggdrasil pendant neuf jours et neuf nuits, se sacrifiant à lui-même pour acquérir la connaissance des runes — un acte de sacrifice chamanique fondateur de la sagesse divine.</p></div><h3>Les Nornes et le destin</h3><p class="resume-text">Les Nornes — Urð (le passé), Verðandi (le présent) et Skuld (le futur) — tissent les destins de dieux et d'hommes. Contrairement à la conception grecque, le destin nordique n'est pas un décret divin immuable mais un tissu vivant façonné par les actes passés. Même les dieux sont soumis au Wyrd (le destin), et Odin lui-même ne peut empêcher le Ragnarök.</p><p class="resume-text">Cette vision tragique imprègne toute la littérature des sagas : les héros connaissent souvent leur mort à l'avance mais l'affrontent avec courage, car la gloire du combat vaut mieux que la survie dans le déshonneur. C'est l'essence du courage héroïque nordique, que Wagner immortalisera dans ses opéras du XIXe siècle.</p>""",

    'philosophie-religieuse/maimonide': """<h3>La doctrine des attributs négatifs</h3><p class="resume-text">L'une des contributions philosophiques les plus originales de Maïmonide est sa théorie des attributs négatifs (via negativa). Selon lui, toute affirmation positive sur Dieu est impropre : dire que Dieu est « bon » ou « sage » au sens habituel de ces termes réduirait Dieu à une catégorie humaine. Il faut donc parler de Dieu par la négation : Dieu n'est pas mauvais, n'est pas ignorant.</p><p class="resume-text">Cette approche apophatique permet de préserver l'absolue transcendance divine tout en maintenant un discours religieux cohérent. Elle anticipe des développements importants de la théologie négative chrétienne (Maître Eckhart, Nicolas de Cues) et influence encore aujourd'hui les philosophes de la religion.</p><div class="highlight-box"><p>Le Guide des égarés de Maïmonide (1190) s'adresse aux intellectuels juifs perturbés par le conflit apparent entre la philosophie aristotélicienne et la révélation biblique. Son objectif est de montrer que foi et raison sont réconciliables.</p></div><h3>La loi, l'éthique et la politique</h3><p class="resume-text">Maïmonide fut aussi un juriste et un médecin de renom. Sa Mishné Torah codifie l'ensemble de la loi orale juive (halakha) de façon systématique — une entreprise sans précédent. Il y affirme que les commandements divins ont une rationalité intrinsèque : ils visent à perfectionner l'âme et le corps, à créer une société juste et à disposer l'homme à la contemplation philosophique.</p><p class="resume-text">Cette rationalisation de la loi religieuse est novatrice et controversée. Certains rabbins lui reprochent de réduire la Torah à un simple code légal, alors qu'elle est d'abord révélation divine. Ce débat entre légalisme et mystique traverse toute l'histoire du judaïsme postérieur.</p><h3>Influence durable</h3><p class="resume-text">Thomas d'Aquin cite Maïmonide (qu'il nomme « Rabbi Moyses ») dans la Somme théologique. Spinoza, Leibniz et Kant sont également redevables à sa démarche de rationalisation théologique. Au XXe siècle, Leo Strauss a montré que la pensée politique de Maïmonide sur les rapports entre philosophie et loi révélée est d'une actualité permanente.</p>""",

    'textes-sacres/torah': """<h3>La structure interne de la Torah</h3><p class="resume-text">La Torah se divise en cinq livres distincts dont chacun a une tonalité propre. La Genèse (Bereshit) raconte les origines du monde et des patriarches. L'Exode (Shemot) narre l'esclavage en Égypte, la libération par Moïse et la révélation du Sinaï. Le Lévitique (Vayikra) est un code cultuel et rituel centré sur le sacerdoce. Les Nombres (Bamidbar) chroniquent l'errance de quarante ans dans le désert. Le Deutéronome (Devarim) est le grand discours testamentaire de Moïse avant son entrée en Terre promise.</p><p class="resume-text">Cette architecture narrative n'est pas linéaire : la Torah entremêle récit, loi, généalogie et poésie. Les répétitions et variantes internes ont conduit les exégètes modernes à distinguer plusieurs sources rédactionnelles (hypothèse documentaire : J, E, D, P) dont la composition s'étalerait sur plusieurs siècles.</p><div class="highlight-box"><p>La révélation du Sinaï est l'événement fondateur du judaïsme : Dieu y délivre les Dix Commandements à Moïse, établissant l'alliance (brit) qui définit le peuple d'Israël comme « peuple élu ».</p></div><h3>L'exégèse juive : du peshat au sod</h3><p class="resume-text">La tradition rabbinique a développé quatre niveaux d'interprétation de la Torah, résumés par l'acronyme PaRDeS : le peshat (sens littéral), le remez (sens allégorique), le derash (sens homilétique) et le sod (sens mystique, kabbalistique). Cette pluralité herméneutique fait de la Torah un texte inépuisable, toujours susceptible de nouvelles lectures.</p><p class="resume-text">Le Talmud, compilation de discussions rabbiniques (Ier-VIe siècle), commente la Torah ligne à ligne. Les responsa médiévaux et les commentaires de Rachi (XIe siècle) ou de Maïmonide (XIIe siècle) constituent des strates d'interprétation qui enrichissent continuellement le sens du texte fondateur.</p><h3>La Torah dans la vie juive</h3><p class="resume-text">Le rouleau de la Torah (Sefer Torah) est l'objet le plus sacré du judaïsme. Sa copie à la main par un scribe (sofer) est soumise à des règles strictes : une seule erreur peut rendre le rouleau impropre à l'usage rituel. Chaque semaine, une paracha (portion) est lue à la synagogue, permettant de parcourir la Torah en un an.</p>""",

    'philosophie-religieuse/averroes': """<h3>La théorie de l'intellect et l'intellect agent universel</h3><p class="resume-text">La contribution la plus influente d'Averroès concerne sa théorie de l'intellect. Commentant Aristote, il distingue l'intellect passif (individuel, mortel) de l'intellect agent (séparé, universel, éternel). Pour Averroès, l'intellect agent est unique et commun à toute l'humanité : il n'existe qu'un seul intellect actif que tous les hommes partagent.</p><p class="resume-text">Cette doctrine, appelée « monopsychisme », eut des conséquences théologiques considérables : si l'intellect actif est universel, l'immortalité individuelle de l'âme devient problématique. Les averroïstes latins du XIIIe siècle (Siger de Brabant, Boèce de Dacie) en tirèrent des conclusions que l'Église condamna en 1270 et 1277.</p><div class="highlight-box"><p>La doctrine averroïste de la « double vérité » — selon laquelle philosophie et théologie peuvent aboutir à des conclusions contraires sans que l'une invalide l'autre — est en réalité une caricature : Averroès affirmait que la vérité est une, mais accessible par des voies différentes selon le niveau intellectuel du croyant.</p></div><h3>L'averroïsme latin et son influence</h3><p class="resume-text">Les traductions latines des commentaires d'Averroès (XIIe-XIIIe siècles) révolutionnent l'université médiévale. Il devient « le Commentateur » par excellence, l'autorité suprême sur Aristote. Thomas d'Aquin consacre une partie de son Traité de l'unité de l'intellect à réfuter son monopsychisme.</p><p class="resume-text">À la Renaissance, le courant averroïste padouan (Pietro Pomponazzi, Agostino Nifo) perpétue une lecture naturaliste d'Aristote qui influencera Galilée et le développement des sciences modernes. Spinoza et Leibniz reconnaissent également leur dette envers les grandes synthèses philosophiques du monde arabe médiéval.</p><h3>Le philosophe et la cité</h3><p class="resume-text">Dans son commentaire de la République de Platon, Averroès développe une philosophie politique où le philosophe est le vrai guide de la cité. La loi religieuse, pour lui, n'est pas opposée à la raison mais en est la version adaptée au peuple : l'élite philosophique accède à la vérité par la démonstration, le commun des croyants par la rhétorique et l'image.</p>""",

    'grandes-religions/islam': """<h3>Les piliers de l'islam et la pratique quotidienne</h3><p class="resume-text">L'islam repose sur cinq obligations fondamentales : la profession de foi (shahada — « Il n'y a de dieu qu'Allah, et Mohammed est son prophète »), la prière canonique cinq fois par jour (salat), l'aumône légale (zakat — environ 2,5 % des biens), le jeûne du mois de Ramadan (sawm) et le pèlerinage à La Mecque au moins une fois dans sa vie si les moyens le permettent (hajj). Ces piliers structurent le temps quotidien, annuel et biographique du croyant.</p><p class="resume-text">La prière dans l'islam n'est pas seulement une communion personnelle avec Dieu : c'est un acte liturgique codifié, accompagné de purifications rituelles (wudu), de postures précises (rak'a) et d'orientations spatiales (qibla vers La Mecque). La mosquée est à la fois lieu de culte, centre d'enseignement et espace de sociabilité.</p><div class="highlight-box"><p>La révélation coranique s'est déroulée sur vingt-trois ans (610-632 ap. J.-C.), divisée entre les sourates mecquoises (plus poétiques, centrées sur la foi et le Jugement) et les sourates médinoises (plus législatives, traitant de la communauté et du droit).</p></div><h3>Les courants de l'islam</h3><p class="resume-text">Le sunnisme (85-90 % des musulmans) reconnaît la légitimité des quatre premiers califes et s'appuie sur les six recueils de hadiths canoniques. Le chiisme (10-15 %) considère que la direction de la communauté revient aux descendants d'Ali ibn Abi Talib, cousin et gendre du Prophète. Le chiisme duodécimain (majoritaire en Iran, Irak) attend le retour du douzième imam, occultation divine.</p><p class="resume-text">Le soufisme, courant mystique transconfessionnel, cherche une union intime avec Dieu par la méditation, le dhikr (invocation répétée des noms divins) et la poésie. Les confréries soufies (tariqas) ont joué un rôle capital dans l'islamisation de l'Afrique subsaharienne et de l'Asie centrale.</p>""",

    'religions-monde/taoisme': """<h3>Le Dao De Jing et la pensée de Laozi</h3><p class="resume-text">Le Dao De Jing (Tao Te King), attribué à Laozi (VIe-Ve siècle av. J.-C.), est l'un des textes les plus traduits au monde. Ses 81 chapitres d'une brièveté lapidaire exposent une vision du monde fondée sur le Dao (la Voie) : principe innommable et inépuisable dont surgit la réalité. « Le Dao qui peut être nommé n'est pas l'éternel Dao. »</p><p class="resume-text">Le De (la Vertu) est la manifestation du Dao dans les êtres et les choses. Le sage taoïste cultive le De non par effort mais par abandon spontané : wu wei (non-agir) ne signifie pas passivité, mais action fluide en accord avec la nature des choses, sans résistance ni forcément.</p><div class="highlight-box"><p>La pensée de Laozi est fondamentalement anti-autoritaire : le meilleur gouvernant est celui dont le peuple ignore presque l'existence, tant son action est légère et non intrusive. Cette vision politique a fasciné des penseurs aussi différents que Tolstoï et les libertariens contemporains.</p></div><h3>Zhuangzi et le taoïsme littéraire</h3><p class="resume-text">Zhuangzi (IVe siècle av. J.-C.) radicalise la pensée taoïste dans un style littéraire éblouissant, mêlant paraboles, dialogues absurdes et méditations poétiques. Son texte le plus célèbre — « Je rêvais d'être un papillon ; maintenant éveillé, je ne sais si je suis un homme qui rêvait d'être papillon, ou un papillon qui rêve d'être homme » — illustre la dissolution des frontières entre les êtres et la relativité de toutes les perspectives.</p><p class="resume-text">Zhuangzi récuse l'utilité sociale prônée par les confucéens. L'arbre inutile vit plus longtemps que l'arbre utile ; le cuisinier qui découpe le bœuf avec une parfaite fluidité illustre la maîtrise taoïste. Le taoïsme littéraire nourrit l'esthétique chinoise classique : peinture, calligraphie, jardins.</p><h3>Le taoïsme religieux</h3><p class="resume-text">Parallèlement au taoïsme philosophique, un taoïsme religieux s'est développé à partir du IIe siècle ap. J.-C. avec des rites, un panthéon d'immortels (xian), des pratiques alchimiques et des techniques d'immortalité (nei dan — alchimie intérieure). Aujourd'hui encore vivant en Chine et dans la diaspora, le taoïsme religieux intègre médecine traditionnelle, géomancie (feng shui) et pratiques martiales (tai-chi, qi gong).</p>""",

    'religions-monde/sikhisme': """<h3>Les Dix Gourous et la formation du sikhisme</h3><p class="resume-text">Le sikhisme a été fondé au Pendjab (actuel Pakistan/Inde) par Gourou Nanak (1469-1539), qui prêcha l'unité de Dieu (Ik Onkar — « Il n'y a qu'un seul Dieu »), l'égalité de tous les êtres humains et le rejet des castes. Sa démarche syncrétique puisait dans l'hindouisme et l'islam tout en affirmant une voie originale.</p><p class="resume-text">La lignée de dix gourous s'étale jusqu'à Gourou Gobind Singh (1666-1708), qui institua le Khalsa — la confrérie des sikhs initiés — et décréta que le Guru Granth Sahib, le livre saint, serait désormais le gourou éternel et vivant. Ce passage de l'autorité personnelle à l'autorité scripturaire est unique dans les grandes religions.</p><div class="highlight-box"><p>Le Guru Granth Sahib rassemble les hymnes des six premiers gourous sikhs, mais aussi ceux de poètes hindous (Kabir, Ravidas) et musulmans (Sheikh Farid). Ce recueil multiconfessionnel incarne la vision universaliste du sikhisme.</p></div><h3>Les Cinq K et l'identité sikh</h3><p class="resume-text">Les sikhs du Khalsa portent cinq symboles physiques appelés les Cinq K (panj kakars) : les cheveux non coupés (kesh) recouverts d'un turban, un peigne de bois (kangha), un bracelet d'acier (kara), un sous-vêtement (kachha) et un kirpan (couteau rituel symbolisant la défense de la justice). Ces symboles affirment une identité visible et un engagement éthique.</p><p class="resume-text">Le langar, repas communautaire servi gratuitement dans chaque gurdwara (temple sikh), est une institution concrète d'égalité sociale : tous s'assoient côte à côte, sans distinction de caste, de religion ou de statut social. Les gurdwaras accueillent aussi bien les pèlerins que les sans-abri.</p><h3>Le sikhisme contemporain</h3><p class="resume-text">Avec environ 25-30 millions de fidèles, le sikhisme est la cinquième religion mondiale. La diaspora sikh, présente en Grande-Bretagne, au Canada et aux États-Unis, est réputée pour son dynamisme économique et sa tradition de service (seva). Le Temple d'Or d'Amritsar, baigné dans un bassin sacré, demeure le cœur spirituel de la communauté mondiale.</p>""",

    'grandes-religions/bouddhisme': """<h3>Les Quatre Nobles Vérités et le Noble Chemin octuple</h3><p class="resume-text">Le premier sermon du Bouddha à Bénarès expose les Quatre Nobles Vérités : la souffrance est inhérente à l'existence (dukkha) ; elle a une cause — le désir et l'attachement (tanha) ; elle peut cesser (nirvana) ; il existe un chemin pour y parvenir. Ce chemin octuple comprend la compréhension juste, l'intention juste, la parole juste, l'action juste, les moyens d'existence justes, l'effort juste, la pleine conscience juste et la concentration juste.</p><p class="resume-text">Ce chemin n'est ni ascétisme extrême ni hédonisme — c'est la voie du milieu. Le Bouddha avait lui-même expérimenté les deux extrêmes avant d'atteindre l'Éveil sous l'arbre Bodhi à Bodh Gaya. La pratique méditative (dhyana) est au cœur de cette voie : elle permet d'observer le flux des pensées sans s'y identifier et de réaliser l'impermanence (anicca) de toute chose.</p><div class="highlight-box"><p>Le concept de non-soi (anatman) est l'une des doctrines les plus radicales du bouddhisme : il n'existe pas de « moi » permanent et substantiel. Ce que nous appelons « moi » n'est qu'un agrégat (skandha) de processus corporels et mentaux en perpétuel changement.</p></div><h3>Les grandes écoles bouddhistes</h3><p class="resume-text">Le Theravada (« Voie des Anciens »), dominant en Asie du Sud-Est, met l'accent sur la pratique monastique et l'idéal de l'arhat, celui qui atteint le nirvana pour lui-même. Le Mahayana (« Grand Véhicule »), répandu en Chine, Corée, Japon et Vietnam, valorise l'idéal du bodhisattva, qui renonce au nirvana pour aider tous les êtres à s'éveiller.</p><p class="resume-text">Le Vajrayana (bouddhisme tantrique), pratiqué au Tibet, en Mongolie et au Japon (école Shingon), intègre des rituels ésotériques, des mandalas, des mantra et des pratiques de visualisation pour accélérer l'Éveil. Le dalaï-lama est considéré comme la réincarnation du bodhisattva Avalokiteshvara, bouddha de la compassion.</p>""",

    'textes-sacres/vedas': """<h3>La structure des Vedas et le rituel védique</h3><p class="resume-text">Les quatre Vedas se subdivisent chacun en quatre parties : les Samhita (collections d'hymnes et de formules), les Brahmana (textes en prose expliquant les rituels), les Aranyaka (« textes des forêts », pour ermites) et les Upanishad (discussions philosophiques sur l'âme et l'absolu). L'ensemble constitue la shruti — « ce qui a été entendu » des sages en état de méditation — par opposition à la smriti — « ce dont on se souvient », la tradition humaine.</p><p class="resume-text">Le rituel védique (yajna) est une science complexe mobilisant des officiants spécialisés (hotri pour réciter le Rig-Véda, udgatar pour le Sama-Véda, adhvaryu pour l'Yajur-Véda). Le feu sacrificiel (agni) est le médiateur entre les hommes et les dieux. Ces rituels élaborés ont conduit au développement des mathématiques (géométrie des autels) et de la grammaire sanskrite (Panini).</p><div class="highlight-box"><p>Le Rig-Véda contient 1028 hymnes dont certains datent de 1500 av. J.-C. environ. Ses hymnes célèbrent les dieux naturels — Indra (la foudre), Varuna (l'ordre cosmique), Agni (le feu) — et expriment une interrogation métaphysique profonde sur l'origine du monde.</p></div><h3>Les Upanishad et la révolution philosophique</h3><p class="resume-text">Les Upanishad (VIIIe-IVe siècle av. J.-C.) opèrent un tournant radical : au lieu du rituel externe, elles valorisent la connaissance intérieure (jnana). Leur concept central est l'identité entre Atman (l'âme individuelle) et Brahman (l'absolu impersonnel). « Tat tvam asi » — « Tu es Cela » — exprime cette équivalence fondamentale.</p><p class="resume-text">Les principales Upanishad (Brihadaranyaka, Chandogya, Taittiriya) développent des dialogues entre maîtres et disciples sur la nature du moi, du rêve, du sommeil profond et de la mort. Ces textes ont nourri toutes les grandes écoles de philosophie hindoue et exercé une fascination sur des penseurs occidentaux comme Schopenhauer et Emerson.</p>""",

    'textes-sacres/coran': """<h3>La composition et la structure du Coran</h3><p class="resume-text">Le Coran (« la Récitation ») est organisé en 114 sourates (chapitres) classées approximativement de la plus longue à la plus courte — et non chronologiquement. Chaque sourate (sauf la neuvième) commence par la basmala : « Au nom de Dieu, le Tout Miséricordieux, le Très Miséricordieux ». Cette formule structure le temps et l'espace du texte.</p><p class="resume-text">La langue coranique est considérée comme un miracle en soi (i'jaz al-Quran) : son style poétique sublime, ses assonances et son rythme sont inimitables. D'où l'impossibilité théologique de la traduction : toute version dans une autre langue n'est qu'une « interprétation des sens », jamais le Coran lui-même. La mémorisation intégrale du Coran (hafiz) est un idéal et un titre de prestige dans le monde musulman.</p><div class="highlight-box"><p>La standardisation du texte coranique fut réalisée sous le calife Uthman (644-656) : des copies officielles furent envoyées dans les grandes villes de l'empire, et les variantes furent détruites. Ce travail de canonisation assura une remarquable stabilité textuelle sur quatorze siècles.</p></div><h3>Les sciences coraniques et l'exégèse</h3><p class="resume-text">L'interprétation du Coran (tafsir) est une discipline savante complexe mobilisant la linguistique arabe, la connaissance des occasions de révélation (asbab al-nuzul), la hiérarchie des versets (certains versets médinois abrogent des versets mecquois antérieurs) et la relation avec les hadiths prophétiques. Les grands tafsir médiévaux (Tabari, Ibn Kathir) font plusieurs dizaines de volumes.</p><p class="resume-text">L'exégèse contemporaine se divise entre tenants d'une lecture littéraliste (salafisme), partisans d'une herméneutique historico-critique (Fazlur Rahman, Mohammed Arkoun) et courants mystiques (soufis) qui cherchent le sens intérieur caché derrière la lettre. Ces débats sont au cœur des discussions sur l'islam et la modernité.</p>""",
}

def insert_before_quiz(content, new_html):
    """Insère new_html juste avant la section quiz."""
    # Pattern to find the quiz section
    quiz_section = '<section class="content-section" id="quiz">'
    contenu_close = '</section>'

    # Find end of contenu section (just before quiz)
    quiz_idx = content.find(quiz_section)
    if quiz_idx == -1:
        # No quiz section, find end of contenu section
        return content

    # Find the closing </section> just before quiz
    # The contenu section ends with </section> right before the quiz section
    # We need to insert before that closing tag
    contenu_end_idx = content.rfind(contenu_close, 0, quiz_idx)
    if contenu_end_idx == -1:
        return content

    return content[:contenu_end_idx] + new_html + contenu_close + content[quiz_idx:]

def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for page_key, new_html in ENRICHMENTS.items():
        if page_key in data['pages']:
            page = data['pages'][page_key]
            if page.get('type') == 'course':
                old_len = len(page['content'])
                page['content'] = insert_before_quiz(page['content'], new_html)
                new_len = len(page['content'])
                print(f"Enriched {page_key}: {old_len} -> {new_len} chars (+{new_len-old_len})")
                enriched_count += 1
        else:
            print(f"WARNING: page not found: {page_key}")

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nDone: {enriched_count} pages enriched.")

if __name__ == '__main__':
    main()
