#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrichit les derniers articles de linguistique.json
"""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/linguistique.json'

ENRICHMENTS = {
    'sociolinguistique/langue-identite': """<h3>Langue et construction nationale</h3><p class="resume-text">La relation entre langue et identité nationale est une construction historique récente. Au XVIIIe siècle, Herder développe l'idée que chaque peuple a une âme (Volksgeist) qui s'exprime dans sa langue et sa littérature. Ce romantisme linguistique fonde les mouvements nationalistes du XIXe siècle qui cherchent à faire coïncider frontières politiques et frontières linguistiques. La standardisation d'une langue nationale, avec ses académies, ses dictionnaires et ses grammaires prescriptives, est un acte politique autant qu'intellectuel.</p><p class="resume-text">La France, avec l'édit de Villers-Cotterêts (1539) imposant le français dans les actes officiels, et la Révolution qui veut « anéantir les patois », illustre ce processus de construction de l'unité nationale par la langue. Les linguistes distinguent langue et dialecte non par des critères purement linguistiques (un dialecte peut être mutuellement intelligible avec la langue standard) mais politiques : « une langue est un dialecte avec une armée et une flotte » (Max Weinreich).</p><div class="highlight-box"><p>Le revivalisme linguistique — la renaissance de langues minoritaires ou en danger — est un phénomène sociopolitique puissant. L'hébreu moderne, le gallois, le catalan, le breton, le māori ont bénéficié de politiques actives de revitalisation. Le cas de l'hébreu est unique : langue morte comme langue maternelle depuis des siècles, elle est devenue en quelques décennies la langue quotidienne d'un État moderne.</p></div>""",

    'acquisition-langage/langage-cerveau': """<h3>Les aires du langage et la latéralisation cérébrale</h3><p class="resume-text">Le langage est principalement traité dans l'hémisphère gauche du cerveau, chez 95 % des droitiers et environ 70 % des gauchers. Les lésions de l'aire de Broca (région frontale inférieure gauche) produisent l'aphasie de Broca : la compréhension est relativement préservée mais la production est lente, laborieuse et agrammatique. Les lésions de l'aire de Wernicke (région temporale postérieure gauche) produisent l'aphasie de Wernicke : la production est fluide mais incohérente, parsemée de paraphasies et de néologismes.</p><p class="resume-text">La neuroimagerie fonctionnelle (IRMf, TEP) a affiné ces localisations et révélé la complexité du réseau cérébral du langage. Le traitement phonologique active les régions temporales supérieures, le traitement syntaxique mobilise les régions frontales et temporales antérieures, le traitement sémantique s'appuie sur un réseau temporo-pariétal étendu. Le faisceau arqué, voie de connexion entre les aires de Broca et de Wernicke, joue un rôle crucial dans la répétition et la mémoire verbale de travail.</p><div class="highlight-box"><p>L'étude des patients aphasiques a fourni des informations cruciales sur l'organisation cérébrale du langage bien avant les techniques d'imagerie. Paul Broca (1861) et Karl Wernicke (1874) ont associé des déficits linguistiques précis à des lésions cérébrales localisées, fondant ainsi la neuropsychologie du langage.</p></div>""",

    'sociolinguistique/variation-linguistique': """<h3>La variation sociale et la stratification sociolinguistique</h3><p class="resume-text">William Labov, dans ses études classiques sur le dialecte new-yorkais (1966), a montré que la variation linguistique est hautement structurée socialement. La prononciation du [r] post-vocalique dans des mots comme « floor » ou « car » varie systématiquement selon la classe sociale, le contexte formel/informel et l'âge du locuteur. Les locuteurs des classes moyennes montrent une hypercorrection en situation formelle : ils surpassent les classes supérieures dans l'usage de la variante de prestige.</p><p class="resume-text">La sociolinguistique variationniste de Labov introduit la notion de variable sociolinguistique : un trait linguistique dont la réalisation couvre plusieurs variantes en distribution avec des facteurs sociaux et stylistiques. La méthode quantitative (comptage des occurrences de chaque variante dans des contextes contrôlés) permet de dégager des régularités que l'introspection ne révèle pas. Cette approche a transformé la linguistique en une discipline empirique rigoureuse.</p><div class="highlight-box"><p>Le paradoxe de l'observateur (Labov) : la présence du chercheur modifie le comportement linguistique des locuteurs qui adoptent un style plus formel. Pour observer la vernaculaire authentique, Labov a utilisé des entretiens semi-structurés avec des digressions émotionnelles et des récits de dangers de mort qui suspendent l'attention stylistique consciente.</p></div>""",

    'acquisition-langage/etapes-acquisition': """<h3>L'acquisition de la grammaire et les erreurs systématiques</h3><p class="resume-text">L'acquisition grammaticale suit des étapes remarquablement similaires à travers les langues. Après le stade des mots isolés (12-18 mois), l'enfant entre dans le stade télégraphique (2-3 ans) : il produit des énoncés de deux ou trois mots structurés mais sans mots grammaticaux (articles, prépositions, auxiliaires). Puis la grammaire émerge progressivement : d'abord les structures simples, ensuite les constructions complexes (relatives, interrogatives, passif).</p><p class="resume-text">Les erreurs systématiques des enfants sont particulièrement révélatrices. La surgénéralisation (« j'ai prendu », « je suis allé-ais ») montre que l'enfant n'imite pas mécaniquement les adultes mais construit des règles générales qu'il applique même aux formes irrégulières. Ces erreurs sont la preuve d'un apprentissage actif, non d'une simple imitation. Elles disparaissent progressivement à mesure que l'enfant acquiert les exceptions.</p><div class="highlight-box"><p>Roger Brown (1973) a suivi longitudinalement l'acquisition de l'anglais chez trois enfants (Adam, Eve et Sarah). Il a montré que 14 morphèmes grammaticaux sont acquis dans un ordre quasi-identique chez tous les enfants, quelle que soit la fréquence de ces morphèmes dans le discours des parents. Cet ordre d'acquisition dépend de la complexité sémantique et morphologique des formes.</p></div>""",

    'acquisition-langage/troubles-langage': """<h3>Les troubles développementaux du langage</h3><p class="resume-text">Le trouble développemental du langage (TDL, anciennement dysphasie) affecte environ 7 % des enfants. Ces enfants présentent des difficultés persistantes d'acquisition du langage sans cause auditive, neurologique ou intellectuelle identifiable. Ils peinent à maîtriser la morphologie flexionnelle (les terminaisons verbales et nominales), produisent des erreurs syntaxiques atypiques et ont souvent un vocabulaire réduit. Les formes les plus sévères persistent à l'âge adulte.</p><p class="resume-text">La dyslexie développementale est un trouble de l'apprentissage de la lecture qui touche 5-15 % des lecteurs. Contrairement à une idée reçue, elle n'est pas due à des inversions de lettres ou à un déficit visuel, mais principalement à un déficit phonologique : les enfants dyslexiques ont du mal à segmenter les mots en phonèmes et à faire correspondre graphèmes et phonèmes. Les bases neurobiologiques (atypies dans les régions temporo-pariétales gauches) et génétiques sont de mieux en mieux documentées.</p><div class="highlight-box"><p>Le mutisme sélectif est un trouble anxieux où l'enfant parle normalement dans certains contextes (maison, famille) mais est incapable de parler dans d'autres (école, milieux sociaux étrangers). Il ne s'agit pas d'un trouble du langage au sens strict mais d'un trouble anxieux qui interfère avec l'utilisation du langage. Il répond bien aux thérapies comportementales et cognitives.</p></div>""",

    'acquisition-langage/periode-critique': """<h3>Les études sur les enfants sauvages et les cas de privation sévère</h3><p class="resume-text">Les études sur des enfants privés d'exposition linguistique normale pendant les années critiques apportent des témoignages poignants et précieux. Le cas de Genie (1970), enfant californienne séquestrée et privée de tout contact linguistique jusqu'à l'âge de 13 ans, a montré qu'après la puberté, l'acquisition de la grammaire reste sévèrement limitée malgré une exposition intensive. Elle a acquis un vocabulaire substantiel mais ses structures syntaxiques n'ont jamais atteint le niveau adulte normal.</p><p class="resume-text">Les études sur les sourds tardifs — personnes qui perdent l'ouïe après avoir acquis la langue orale et accèdent à la langue des signes à l'âge adulte — confirment que l'acquisition d'une grammaire complète est difficile après la puberté. En revanche, les sourds exposés à la langue des signes dès la naissance l'acquièrent selon les mêmes étapes et délais que les entendants acquièrent la langue orale, confirmant que le cerveau est également spécialisé pour les langues visuelles-gestuelles.</p><div class="highlight-box"><p>Les études d'adoption internationale apportent des données naturelles sur la période critique. Les enfants adoptés avant 6-7 ans atteignent généralement un niveau natif dans la langue d'adoption. Après 12-15 ans, l'accent étranger persiste souvent, la morphologie reste difficile à maîtriser parfaitement. Mais des apprentissages tardifs très performants existent, montrant que la période critique fixe des probabilités, non des impossibilités absolues.</p></div>""",

    'acquisition-langage/theories-acquisition': """<h3>L'approche connexionniste et les modèles computationnels</h3><p class="resume-text">Les modèles connexionnistes (réseaux de neurones artificiels) ont relancé le débat empirisme/nativisme dans les années 1980. Rumelhart et McClelland (1986) ont montré qu'un réseau de neurones simple pouvait apprendre les formes régulières et irrégulières du passé anglais et faire les mêmes erreurs de surgénéralisation que les enfants — sans règles explicites. Pour eux, l'acquisition se fait par renforcement statistique des associations, sans mécanismes linguistiques spécifiques.</p><p class="resume-text">Les tenants de la grammaire générative ont critiqué ces modèles : ils fonctionnent grâce à des patterns statistiques présents dans les données d'entraînement mais ne généralisent pas à des structures véritablement nouvelles. Le débat reste ouvert. Les grands modèles de langage (GPT, BERT) ont récemment ravivé ces discussions : ces systèmes, entraînés sur d'énormes corpus textuels, reproduisent des comportements linguistiques complexes. Leur existence informe-t-elle le débat sur la nécessité d'une grammaire universelle innée ?</p><div class="highlight-box"><p>L'approche de l'input-based learning (Tomasello, 2003) propose que l'enfant n'a pas besoin d'une grammaire universelle innée mais de capacités cognitives générales de détection de patterns et d'imitation intentionnelle. Les constructions grammaticales sont apprises item par item avant d'être généralisées. Cette position s'appuie sur des études développementales montrant une progression plus lente et plus progressive que ne le prédit le nativisme chomskyen.</p></div>""",

    'sociolinguistique/changement-linguistique': """<h3>Les mécanismes du changement : diffusion et changement par contact</h3><p class="resume-text">Le changement linguistique ne se produit pas uniformément dans l'ensemble d'une communauté. Il émerge généralement chez certains groupes sociaux (souvent les jeunes adultes, les classes moyennes en mobilité sociale) puis se diffuse progressivement selon une courbe en S : lente adoption initiale, accélération dans la phase médiane, puis ralentissement à l'approche de la saturation. Cette diffusion suit souvent les réseaux sociaux denses et les axes de communication.</p><p class="resume-text">Le changement par contact est particulièrement important dans l'histoire des langues. L'anglais a massivement emprunté au français normand après 1066 (60 % du vocabulaire de base anglais est d'origine romane), tout en conservant sa grammaire germanique. Le balkan sprachbund illustre une convergence grammaticale entre langues non apparentées (grec, albanais, roumain, bulgare) vivant dans la même aire géographique depuis des siècles.</p><div class="highlight-box"><p>La loi de Grimm (1822) a montré que les correspondances phonétiques entre les langues indo-européennes sont régulières et systématiques : le [p] du latin correspond au [f] du germanique (pater/father, piscis/fish). Cette régularité a permis de reconstruire le proto-indo-européen et de fonder la linguistique historique comparée comme science rigoureuse.</p></div>""",

    'sociolinguistique/politique-linguistique': """<h3>La glottophagie et la mort des langues</h3><p class="resume-text">La mort d'une langue est toujours la mort d'une vision du monde. On estime que 50 à 90 % des 7000 langues actuellement parlées pourraient disparaître d'ici la fin du XXIe siècle, victimes de la mondialisation, de l'urbanisation et des politiques éducatives centralistes. L'UNESCO maintient un atlas des langues en danger qui classe les langues de « vulnérables » à « éteintes ».</p><p class="resume-text">Robert Lafont a forgé le concept de « glottophagie » pour désigner le processus par lequel une langue dominante engloutit progressivement les langues locales. Le processus passe par la diglossie (coexistence d'une variété haute/langue nationale et d'une variété basse/langue régionale), puis par la réduction du domaine d'usage de la variété basse, puis par l'abandon intergénérationnel. Les politiques de revitalisation (immersion scolaire, production culturelle, valorisation symbolique) peuvent inverser ce processus — le catalan et le gallois en sont des exemples relativement réussis.</p><div class="highlight-box"><p>L'aménagement linguistique (language planning) distingue la planification du statut (quelle langue pour quelles fonctions officielles ?) de la planification du corpus (standardisation, orthographe, terminologie). Les controverses sur la réforme de l'orthographe française illustrent les tensions entre efficacité communicative, patrimoine culturel et identité nationale que toute politique linguistique doit négocier.</p></div>""",

    'semantique/relations-lexicales': """<h3>Les réseaux lexicaux et l'organisation du lexique mental</h3><p class="resume-text">Le lexique mental n'est pas un dictionnaire alphabétique mais un réseau complexe d'associations. Les expériences d'amorçage lexical (priming) montrent que l'activation d'un mot facilite la reconnaissance de mots sémantiquement proches : après « médecin », le traitement de « infirmière » est accéléré. Ces effets d'amorçage révèlent la structure associative du lexique mental.</p><p class="resume-text">WordNet, base de données lexicale développée à Princeton par George Miller depuis les années 1990, organise le lexique anglais en synsets (ensembles de synonymes) reliés par des relations sémantiques hiérarchiques (hyponymie, méronymie) et autres (antonymie, causation). Cette ressource, disponible pour de nombreuses langues (EuroWordNet), est fondamentale pour le traitement automatique des langues naturelles (TALN) et la recherche en sémantique lexicale.</p><div class="highlight-box"><p>La polysémie — le fait qu'un même mot ait plusieurs sens liés — doit être distinguée de l'homonymie — deux mots de sens non liés qui partagent la même forme sonore. « Souris » (animal / dispositif d'ordinateur) est polysémique : les deux sens sont liés par métaphore. « Vase » (récipient) et « vase » (boue) sont homonymes : les deux mots ont des étymologies distinctes et des sens sans lien.</p></div>""",
}

def insert_before_quiz(content, new_html):
    quiz_section = '<section class="content-section" id="quiz">'
    contenu_close = '</section>'

    quiz_idx = content.find(quiz_section)
    if quiz_idx == -1:
        return content

    contenu_end_idx = content.rfind(contenu_close, 0, quiz_idx)
    if contenu_end_idx == -1:
        return content

    return content[:contenu_end_idx] + new_html + contenu_close + content[quiz_idx:]

def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for page_key, new_html in ENRICHMENTS.items():
        if page_key in data['pages']:
            page = data['pages'][page_key]
            if page.get('type') == 'course':
                old_len = len(page['content'])
                page['content'] = insert_before_quiz(page['content'], new_html)
                new_len = len(page['content'])
                print(f"Enriched {page_key}: {old_len} -> {new_len} chars (+{new_len-old_len})")
                enriched_count += 1
        else:
            print(f"WARNING: page not found: {page_key}")

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nDone: {enriched_count} pages enriched.")

if __name__ == '__main__':
    main()
