#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Enrichit les articles restants de mythologie.json
"""

import json

INPUT_FILE = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/mythologie.json'

ENRICHMENTS = {
    'philosophie-religieuse/pascal': """<h3>L'apologétique et les « Pensées »</h3><p class="resume-text">Les Pensées sont un projet apologétique inachevé : Pascal voulait convaincre les libertins cultivés de son époque de l'existence de Dieu et de la vérité du christianisme. Sa stratégie est originale : il commence par décrire la misère de l'homme sans Dieu (divertissement, ennui, incapacité au bonheur), puis montre que seul le christianisme rend compte de cette condition contradictoire — l'homme est à la fois grand et misérable parce qu'il est une nature déchue.</p><p class="resume-text">Le célèbre « roseau pensant » résume cette anthropologie : « L'homme n'est qu'un roseau, le plus faible de la nature ; mais c'est un roseau pensant. Il ne faut pas que l'univers entier s'arme pour l'écraser : une vapeur, une goutte d'eau suffit pour le tuer. Mais, quand l'univers l'écraserait, l'homme serait encore plus noble que ce qui le tue, parce qu'il sait qu'il meurt et l'avantage que l'univers a sur lui. »</p><div class="highlight-box"><p>La nuit du 23 novembre 1654 : Pascal vit une extase mystique de deux heures qu'il transcrit sur un parchemin cousu dans sa veste — le « Mémorial ». Cet événement transforme le savant en mystique et oriente toute son apologétique vers l'expérience du Dieu d'Abraham, d'Isaac et de Jacob plutôt que du « Dieu des philosophes ».</p></div><h3>Les contributions scientifiques</h3><p class="resume-text">Avant ses Pensées, Pascal fut l'un des savants les plus brillants de son siècle. À seize ans, il rédige un Essai sur les coniques qui éblouit Descartes. Il construit la première machine à calculer mécanique (la Pascaline). Ses expériences sur le vide et la pression atmosphérique (expérience du Puy-de-Dôme, 1648) confirment la théorie de Torricelli et réfutent l'axiome scolastique selon lequel « la nature a horreur du vide ».</p><p class="resume-text">En mathématiques, il développe le triangle arithmétique (triangle de Pascal) et, avec Fermat, pose les bases du calcul des probabilités — ironie de l'histoire, c'est cet outil qu'il mobilise dans son pari sur l'existence de Dieu. La pensée de Pascal illustre l'unité profonde entre rigueur scientifique et exigence spirituelle.</p>""",

    'philosophie-religieuse/thomas-aquin': """<h3>La synthèse scolastique et les Cinq Voies</h3><p class="resume-text">Thomas d'Aquin opère dans la Somme théologique une synthèse monumentale entre la révélation chrétienne et la philosophie aristotélicienne. Contre les théologiens augustiniens qui refusaient de contaminer la foi par la philosophie, il affirme que la raison naturelle peut connaître certaines vérités sur Dieu (son existence, son unicité) sans la révélation, qui complète et élève cette connaissance naturelle.</p><p class="resume-text">Les Cinq Voies (quinquae viae) sont cinq arguments a posteriori pour démontrer l'existence de Dieu : le mouvement (tout ce qui est mû est mû par autre chose, donc il faut un premier moteur immobile), la causalité efficiente (toute cause est causée, donc il faut une cause première non causée), la contingence (les choses contingentes doivent dépendre d'un être nécessaire), les degrés de perfection (les degrés relatifs impliquent un maximum absolu) et l'ordre téléologique (l'ordre naturel des êtres non intelligents suppose une intelligence ordonnatrice).</p><div class="highlight-box"><p>Thomas distingue raison et foi non comme contradictoires mais comme complémentaires : la raison prépare la foi (préambules de la foi), et la foi élève la raison vers des vérités inaccessibles à la philosophie seule (trinité, incarnation, résurrection). Cette architecture intellectuelle a structuré toute la théologie catholique ultérieure.</p></div><h3>L'éthique et la loi naturelle</h3><p class="resume-text">La morale thomiste est fondée sur le concept de loi naturelle : la raison humaine peut découvrir, à partir de la nature des choses, les normes de conduite conformes à la fin de l'homme. Cette loi naturelle participe de la loi éternelle divine et fonde un droit naturel universel, commun à toutes les cultures. Ce concept a profondément influencé la pensée politique occidentale, du droit canonique médiéval à la Déclaration des droits de l'homme.</p><p class="resume-text">Son traité De regno développe une philosophie politique inspirée d'Aristote : la société politique est naturelle à l'homme (animal politique), le bien commun doit primer sur les intérêts particuliers, et la monarchie tempérée est préférable à la démocratie ou à la tyrannie. Thomas reconnaît cependant un droit de résistance à la tyrannie manifeste.</p>""",

    'philosophie-religieuse/kierkegaard': """<h3>Les trois stades de l'existence</h3><p class="resume-text">Kierkegaard décrit trois stades de l'existence humaine. Le stade esthétique est celui de la jouissance immédiate, de la séduction et de la variation : Don Juan en est l'archétype. L'esthète fuit le désespoir dans le plaisir, mais il finit par s'ennuyer de tout et sombre dans une mélancolie profonde. Le stade éthique est celui du devoir, de l'engagement et de la continuité : le fonctionnaire marié, figure du Juge Wilhelm dans L'Alternative, en est le représentant.</p><p class="resume-text">Le stade religieux dépasse les deux premiers par un « saut » irrationnel vers la foi. Abraham qui accepte de sacrifier Isaac illustre ce saut : il transgresse l'éthique universelle (l'interdiction du meurtre) au nom d'une relation absolue avec Dieu qui ne se justifie pas rationnellement. Cette « suspension téléologique de l'éthique » est l'essence du religieux kierkegaardien.</p><div class="highlight-box"><p>Kierkegaard invente la notion de « stade de l'existence » pour remplacer les catégories abstraites de Hegel. Contre le système hégélien qui prétend tout intégrer dans la raison, il affirme que l'existence individuelle — la subjectivité singulière, irréductible à aucun universel — est la réalité première.</p></div><h3>L'angoisse, le désespoir et la liberté</h3><p class="resume-text">Dans Le Concept d'angoisse, Kierkegaard analyse l'angoisse comme le vertige de la liberté : l'homme est angoissé non par une menace définie mais par la possibilité infinie de ses propres choix. L'angoisse est la condition de la liberté humaine — elle précède la culpabilité et annonce la responsabilité.</p><p class="resume-text">La Maladie à la mort développe une psychologie du désespoir comme perte du soi. Le désespoir n'est pas tristesse superficielle mais refus d'être soi-même : soit on refuse sa propre existence, soit on veut être soi mais sans Dieu. Seule la foi authentique réconcilie l'homme avec lui-même en l'ancrant dans son rapport à l'Absolu. Ces analyses influenceront directement Heidegger, Sartre et tout l'existentialisme du XXe siècle.</p>""",

    'grandes-religions/christianisme': """<h3>La christologie et les conciles œcuméniques</h3><p class="resume-text">La question centrale du christianisme est celle de la nature du Christ : comment concilier son humanité et sa divinité ? Les conciles œcuméniques des IVe et Ve siècles ont forgé la doctrine officielle. Le concile de Nicée (325) affirme que le Fils est « consubstantiel » au Père, contre l'arianisme qui en faisait une créature inférieure. Le concile de Chalcédoine (451) définit le Christ comme « une seule personne en deux natures, sans confusion ni séparation ».</p><p class="resume-text">Ces formules en grec philosophique (homoousios, hypostase, physis) ont provoqué des schismes durables. Les Églises nestoriennes d'Orient et les Églises copte, éthiopienne et arménienne (miaphysites) se séparèrent de Rome et de Constantinople sur des nuances christologiques qui paraissent subtiles mais qui engagent une vision globale de la personne humaine et du salut.</p><div class="highlight-box"><p>L'Incarnation est le dogme central du christianisme : Dieu s'est fait homme dans la personne de Jésus-Christ. Cette affirmation implique que la matière et l'histoire sont capables de porter le divin — ce qui distingue profondément le christianisme du platonisme et du gnosticisme.</p></div><h3>Les grandes traditions chrétiennes</h3><p class="resume-text">Le schisme de 1054 sépare le christianisme latin (Rome) et le christianisme oriental (Constantinople). La Réforme du XVIe siècle (Luther, Calvin, Zwingli) fragmente l'Occident chrétien et fonde le protestantisme, centré sur la sola scriptura, la sola fide et le sacerdoce universel. Le catholicisme réaffirme ses positions au concile de Trente (1545-1563) et amorce une réforme interne.</p><p class="resume-text">Aujourd'hui, le christianisme est la religion la plus répandue au monde avec 2,4 milliards de fidèles. Le centre de gravité s'est déplacé vers l'Afrique, l'Amérique latine et l'Asie, où les formes pentecôtistes et évangéliques connaissent une croissance spectaculaire. Le Vatican II (1962-1965) a engagé le catholicisme dans un dialogue œcuménique et interreligieux sans précédent.</p>""",

    'grandes-religions/judaisme': """<h3>L'histoire du peuple juif et la diaspora</h3><p class="resume-text">L'histoire juive est rythmée par une alternance d'enracinement et d'exil. Après la destruction du Premier Temple par Nabuchodonosor (587 av. J.-C.) et l'exil babylonien, le retour sous Cyrus permet la reconstruction. La destruction du Second Temple par Rome (70 ap. J.-C.) est le traumatisme fondateur du judaïsme rabbinique : sans Temple, sans sacrifices, la prière, l'étude de la Torah et les bonnes œuvres deviennent les nouvelles formes du service divin.</p><p class="resume-text">La diaspora juive s'étend sur tout le bassin méditerranéen et au-delà. Les deux grands pôles intellectuels médiévaux sont la Babylonie (où s'élabore le Talmud babylonien) et al-Andalus (où Maïmonide, Juda Halévi et Samuel Ibn Nagrela produisent une culture judéo-arabe exceptionnelle). Les expulsions d'Angleterre (1290), de France (1394) et d'Espagne (1492) redessinent la géographie juive mondiale.</p><div class="highlight-box"><p>Le Talmud babylonien (Ve-VIe siècle ap. J.-C.), compilé dans les académies de Sura et Pumbedita, est le texte de référence du judaïsme rabbinique. Son étude (lomdus) — dialectique, rigoureuse, ouverte à la contradiction — a forgé une culture intellectuelle distinctive qui valorise le questionnement et le débat.</p></div><h3>La philosophie et la mystique juives</h3><p class="resume-text">Le néoplatonisme juif médiéval (Salomon ibn Gabirol, XIe siècle) et le rationalisme aristotélicien (Maïmonide, XIIe siècle) représentent deux grandes réponses au défi philosophique grec. La Kabbale, développée en Provence et en Espagne aux XIIe-XIIIe siècles, propose une mystique des structures divines (les dix séfirot de l'Arbre des séfirot) qui influencera la Renaissance chrétienne (Pic de la Mirandole) et la philosophie moderne (Leibniz).</p><p class="resume-text">Le hassidisme, mouvement mystique populaire fondé au XVIIIe siècle par le Baal Shem Tov en Ukraine, déplace l'accent de l'étude savante vers la joie, la prière fervente et la présence divine dans chaque acte quotidien. La figure du tsaddik (maître charismatique) devient centrale dans cette spiritualité qui se transmet en dynasties dynastiques encore vivantes aujourd'hui.</p>""",

    'spiritualite/soufisme': """<h3>Les maîtres fondateurs et les grandes confréries</h3><p class="resume-text">Le soufisme prend son essor dès le VIIIe siècle avec des figures comme Rabi'a al-Adawiyya (717-801), mystique basrienne qui substitue à la crainte de l'enfer et au désir du paradis un amour pur de Dieu pour Dieu lui-même. Al-Hallaj (858-922), exécuté pour avoir proclamé « Ana'l-Haqq » (Je suis la Vérité/Dieu), incarne le mystique martyr dont l'extase dépasse les frontières du discours orthodoxe.</p><p class="resume-text">Les grandes confréries (tariqas) se développent à partir du XIIe siècle. La Qadiriyya, fondée par Abd al-Qadir al-Jilani à Bagdad (XIIe siècle), est l'une des plus répandues. La Mevleviyya, fondée par les disciples de Rumi à Konya (XIIIe siècle), est célèbre pour ses derviches tourneurs (sama) dont la rotation rituelle symbolise l'orbite des sphères célestes et la circulation de l'amour divin.</p><div class="highlight-box"><p>Rumi (Jalal ad-Din Rumi, 1207-1273) est l'un des plus grands poètes mystiques de l'humanité. Son Masnavi, long poème narratif en persan de 25000 distiques, explore les thèmes de l'amour, de la séparation et de l'union avec le divin. Il est aujourd'hui l'un des poètes les plus lus au monde, notamment en traduction anglaise.</p></div><h3>Doctrine et pratique soufies</h3><p class="resume-text">La voie soufie (tariqa) est un itinéraire spirituel progressif dont les grandes stations (maqamat) — repentir, ascèse, crainte, espérance, amour, contemplation — mènent vers l'union (fana, annihilation du moi dans le divin) et la subsistance en Dieu (baqa). Le maître (cheikh, pir) guide le disciple (murid) pas à pas, en adaptant les exercices spirituels à son état intérieur.</p><p class="resume-text">La musique et la poésie jouent un rôle central dans de nombreuses confréries. Le sama (audition musicale) déclenche des états d'extase (hal) qui favorisent le rapprochement avec le divin. Cette pratique a suscité des controverses avec les théologiens légalistes, mais Ibn Arabi et al-Ghazali l'ont théoriquement légitimée. L'héritage soufi imprègne profondément la littérature, la musique et l'architecture islamiques.</p>""",

    'spiritualite/kabbale': """<h3>L'arbre des séfirot et la structure du divin</h3><p class="resume-text">La Kabbale décrit la structure divine à travers dix séfirot (émanations), organisées en un schéma appelé l'Arbre des séfirot. De haut en bas : Keter (la Couronne, l'Infini), Hokhma (la Sagesse), Bina (la Compréhension), Hesed (la Bonté), Gevura (la Force), Tiferet (la Beauté, le cœur de l'arbre), Netzah (la Victoire), Hod (la Gloire), Yesod (le Fondement) et Malkut (le Règne, la présence divine dans le monde).</p><p class="resume-text">Ces séfirot sont à la fois des aspects de Dieu et des structures de la réalité. L'étude de leurs interactions, correspondances et équilibres permet de comprendre les déséquilibres du monde et d'agir rituellement pour les corriger (tikkoun olam — réparation du monde). Chaque lettre hébraïque, chaque commandement, chaque événement cosmique s'inscrit dans ce réseau symbolique.</p><div class="highlight-box"><p>Le Zohar (Le Livre de la Splendeur), attribué par la tradition à Rabbi Shimon bar Yohai (IIe siècle) mais rédigé en réalité par Moïse de Léon en Espagne vers 1280-1286, est le texte fondamental de la Kabbale. Composé en araméen, c'est un commentaire narratif et mystique du Pentateuque d'une richesse symbolique extraordinaire.</p></div><h3>La Kabbale lourianique et l'influence sur la modernité</h3><p class="resume-text">La Kabbale lourianique, développée par Isaac Louria (1534-1572) à Safed en Galilée, est la grande refondation de la pensée kabbalistique. Elle introduit les concepts de tsimtsum (contraction de Dieu pour faire place au monde), de shvirat hakelim (brisure des vases contenant la lumière divine) et de tikkoun (processus de réparation cosmique par la pratique religieuse humaine).</p><p class="resume-text">Ces concepts ont exercé une influence considérable sur la philosophie et la théologie. Pic de la Mirandole intègre des éléments kabbalistiques dans sa philosophie de la dignité humaine. Leibniz, Hegel et Schelling sont redevables à certaines structures kabbalistiques. Au XXe siècle, Gershom Scholem a réhabilité la Kabbale comme courant majeur de l'histoire intellectuelle juive, contre les Lumières qui l'avaient reléguée dans le domaine de la superstition.</p>""",

    'spiritualite/mysticisme-chretien': """<h3>Maître Eckhart et la mystique rhénane</h3><p class="resume-text">Maître Eckhart (1260-1328), dominicain rhénan, développe une mystique spéculative d'une radicalité philosophique sans égale dans le christianisme médiéval. Sa doctrine du « Fond de l'âme » (Seelengrund) affirme qu'il existe dans l'âme humaine une étincelle divine (funkelîn) où l'union avec Dieu est possible sans médiation. Dans la Naissance de Dieu dans l'âme, Dieu se génère lui-même éternellement dans le fond de l'âme pure.</p><p class="resume-text">La bulle In agro dominico (1329) condamna 28 propositions tirées de ses sermons. La postérité le réhabilita : Jean Tauler et Henri Suso, ses disciples, perpétuèrent la mystique rhénane. Jan van Ruusbroec, Nicolas de Cues et plus tard Jacob Böhme sont dans sa dette. Hegel et Schopenhauer le citent admirativement ; Heidegger le commente longuement.</p><div class="highlight-box"><p>La « théologie négative » d'Eckhart affirme que Dieu transcende toute catégorie conceptuelle : il n'est ni bon ni sage au sens habituel de ces termes. Cette voie apophatique, héritée du Pseudo-Denys l'Aréopagite, cherche à préserver l'absolue altérité divine en refusant toute analogie trop facile entre Dieu et les créatures.</p></div><h3>Thérèse d'Avila, Jean de la Croix et la mystique espagnole</h3><p class="resume-text">Thérèse d'Avila (1515-1582) décrit dans le Château intérieur sept demeures de l'âme correspondant aux étapes de la vie contemplative, de la prière des débutants jusqu'au mariage mystique. Docteure de l'Église, elle est aussi la cofondatrice (avec Jean de la Croix) de la réforme carmélite. Sa façon de conjuguer expérience mystique personnelle et direction spirituelle concrète en fait un modèle unique.</p><p class="resume-text">Jean de la Croix (1542-1591) décrit la purification de l'âme à travers la « nuit obscure des sens » et la « nuit obscure de l'esprit » : dépouillée de toutes ses attaches et représentations, l'âme atteint l'union transformante avec Dieu. Ses poèmes — le Cantique spirituel, la Nuit obscure — sont considérés comme les sommets de la poésie mystique en langue castillane.</p>""",

    'religions-monde/shintoisme': """<h3>Les kami et la cosmologie shintô</h3><p class="resume-text">Le shintô reconnaît une multitude de kami — esprits ou forces sacrées — présents dans les éléments naturels (montagnes, rivières, rochers, arbres), les ancêtres et les empereurs. Le Nihon Shoki (720) et le Kojiki (712) relatent les mythes fondateurs : Izanagi et Izanami, les divinités primordiales, créent les îles du Japon en remuant l'océan primordial avec une lance. De leur union naissent les innombrables kami du panthéon japonais.</p><p class="resume-text">Amaterasu, déesse du soleil, est la divinité suprême et l'ancêtre mythique de la famille impériale. Sa dispute avec son frère Susanoo (dieu des tempêtes) provoque son enfermement dans une grotte et l'obscurcissement du monde. Les autres kami la font sortir par la ruse et la danse, symbolisant le retour de la lumière et l'harmonie restaurée.</p><div class="highlight-box"><p>La notion de « pureté rituelle » (kiyome) est centrale dans le shintô. La souillure (kegare) — liée au sang, à la mort, aux maladies — doit être purifiée par des rites de purification (harae) et des ablutions (misogi). Cette obsession de la pureté structure profondément l'esthétique et l'hygiène sociale japonaise.</p></div><h3>Architecture sacrée et rites saisonniers</h3><p class="resume-text">Le sanctuaire shintô (jinja) est construit selon des principes architecturaux précis qui expriment la pureté et la présence du kami. La grande porte torii marque le passage du monde profane au monde sacré. Le Grand Sanctuaire d'Ise, dédié à Amaterasu, est reconstruit à l'identique tous les vingt ans depuis le VIIe siècle — pratique unique qui incarne la conception japonaise d'une pureté perpétuellement renouvelée.</p><p class="resume-text">Le calendrier shintô est rythmé par les matsuri (fêtes sacrées) qui célèbrent les saisons, les récoltes et les événements cosmiques. Le shintô d'État (1868-1945), instrumentalisé pour légitimer le nationalisme impérial, a été officiellement aboli après 1945. Le shintô contemporain, dépolitisé, reste profondément ancré dans la vie quotidienne japonaise : purification des voitures neuves, bénédiction des nouveaux immeubles, rites de passage.</p>""",

    'religions-monde/jainisme': """<h3>L'ahimsa et l'éthique jaina</h3><p class="resume-text">L'ahimsa (non-violence) est le premier et le plus important des vœux jains. Pour les moines, elle implique une attention extrême à ne tuer aucun être vivant, fût-ce un insecte : porter un masque pour ne pas avaler de moustiques, balayer le chemin avant de marcher. Pour les laïcs, l'ahimsa exclut les professions liées à la violence (guerre, chasse, boucherie) et impose un régime végétarien strict.</p><p class="resume-text">Cette éthique de la non-violence a exercé une influence profonde sur la culture indienne. Gandhi reconnaît explicitement sa dette envers le jainisme. La doctrine de l'anekantavada (pluralisme ou non-absoluité de la vérité) affirme que toute affirmation n'est vraie que sous un certain angle (naya), ce qui impose une épistémologie de la modestie et du dialogue que certains philosophes contemporains rapprochent du perspectivisme ou du pragmatisme.</p><div class="highlight-box"><p>Le jainisme distingue l'âme (jiva) de la matière (ajiva). Les karmas sont littéralement des particules matérielles qui s'attachent à l'âme par les passions et les actions. La délivrance (moksha) est la séparation complète de l'âme et de la matière, permettant à l'âme de s'élever jusqu'au sommet de l'univers (loka) où elle demeure en parfaite quiétude.</p></div><h3>Mahavira et la tradition des Tirthankaras</h3><p class="resume-text">Le jainisme reconnaît vingt-quatre Tirthankaras (« faiseurs de gué »), libérateurs qui ont trouvé le chemin de la délivrance et en ont montré la voie. Le dernier, Mahavira (VIe siècle av. J.-C., contemporain du Bouddha), est le réformateur et codificateur de la doctrine. Il pratiqua douze ans d'ascèse extrême avant d'atteindre l'omniscience (kevala jnana) et l'illumination complète.</p><p class="resume-text">Le jainisme se divise en deux grandes branches : les Digambaras (« vêtus d'espace », nudité rituelle pour les moines) et les Shvetambaras (« vêtus de blanc »). Malgré leur faible nombre (environ 4-5 millions de fidèles, principalement dans le Gujarat et le Rajasthan), les jains ont exercé une influence culturelle et économique considérable en Inde.</p>""",

    'religions-monde/zoroastrisme': """<h3>Le dualisme zoroastrien et la lutte cosmique</h3><p class="resume-text">La révélation de Zarathoustra (Zoroastre) pose un dualisme radical : Ahura Mazda (le Seigneur Sage, principe du Bien) s'oppose à Angra Mainyu (l'Esprit destructeur, principe du Mal). Cette opposition n'est pas symétrique : Ahura Mazda est incréé et omniscient, Angra Mainyu est une force créée et destinée à être vaincue à la fin des temps lors de la Frashokereyi (Rénovation du monde).</p><p class="resume-text">Le zoroastrisme est ainsi la première grande religion monothéiste de l'histoire, précédant le judaïsme exilique dans la systématisation d'un dualisme cosmique. L'exil babylonien (VIe siècle av. J.-C.) a vu un dialogue intense entre Juifs et Zoroastriens qui a influencé le développement de la démonologie, de l'eschatologie et du messianisme hébreux.</p><div class="highlight-box"><p>Les Gathas, hymnes composés par Zarathoustra lui-même en vieux-avestique, sont les textes les plus anciens de la tradition zoroastrienne. Leur langue archaïque et leur densité philosophique ont fasciné les philologues modernes. Nietzsche choisira la figure de Zarathoustra pour son propre projet philosophique dans Ainsi parlait Zarathoustra.</p></div><h3>Cosmologie, eschatologie et influence</h3><p class="resume-text">La cosmologie zoroastrienne divise le temps en quatre cycles de 3000 ans. Dans le cycle actuel, les forces du Mal ont envahi le monde créé par Ahura Mazda. Chaque être humain est engagé dans cette lutte par ses pensées, paroles et actes (la triade fondamentale humata, hukhta, hvarshta). À la mort individuelle, l'âme traverse le pont Chinvat : les justes accèdent au paradis (vahishtem ahu), les mauvais tombent en enfer.</p><p class="resume-text">L'influence du zoroastrisme sur les trois religions abrahamiques (judaïsme, christianisme, islam) est considérable : le concept de Satan, les anges et démons, le jugement dernier, le paradis et l'enfer, la résurrection des morts et le messie salvateur sont autant de thèmes dont la forme zoroastrienne précède les formes abrahamiques. Les Parsis, communauté zoroastrienne réfugiée en Inde après la conquête arabe de la Perse (VIIe siècle), maintiennent vivante cette tradition millénaire.</p>""",

    'spiritualite/chamanisme': """<h3>Le voyage chamanique et les techniques d'extase</h3><p class="resume-text">Le chamanisme, tel que Mircea Eliade l'a défini dans son œuvre fondatrice Le Chamanisme et les techniques archaïques de l'extase (1951), est une technique d'extase permettant au spécialiste religieux (le chamane) de voyager entre les plans de l'univers — le monde supérieur (ciel), le monde intermédiaire (terre) et le monde inférieur (royaume des morts). Ce voyage se fait en état modifié de conscience, induit par le tambour, le chant, la danse ou des plantes psychoactives.</p><p class="resume-text">Le chamane sert d'intermédiaire entre la communauté et les esprits. Il guérit en récupérant l'âme d'un malade ravie par un esprit, accompagne les morts vers l'au-delà, consulte les esprits tutélaires pour la chasse ou la pluie, et dénoue les désordres cosmiques qui perturbent la vie de la communauté. Sa vocation s'accompagne souvent d'une maladie initiatique (« maladie chamanique ») suivie d'une mort symbolique et d'une renaissance.</p><div class="highlight-box"><p>Le chamanisme sibérien (Toungouses, Yakoutes, Bouriates) est considéré comme la forme « classique » décrite par Eliade. Mais des pratiques analogues existent sur tous les continents : chamanes amérindiens, machi (Mapuche du Chili), sangoma (Afrique australe), bomoh (Malaisie). La diversité des formes ne doit pas masquer une structure commune.</p></div><h3>Chamanisme et science contemporaine</h3><p class="resume-text">Les neurosciences et la psychologie contemporaine s'intéressent aux états modifiés de conscience chamanique. Michael Harner a développé dans les années 1970 le « néochamanisme » occidental, adapté pour des non-Autochtones pratiquant des voyages guidés par le tambour. Ce mouvement, controversé, soulève des questions sur l'appropriation culturelle et l'authenticité des pratiques.</p><p class="resume-text">Les ethnobotanistes ont étudié les plantes utilisées dans les rituels chamaniques (ayahuasca en Amazonie, peyotl en Amérique du Nord, iboga en Afrique centrale). La recherche sur les effets thérapeutiques de ces substances en psychiatrie (dépression, SSPT, addictions) connaît un regain d'intérêt depuis les années 2000, réhabilitant scientifiquement certaines pratiques chamanique de guérison.</p>""",

    'textes-sacres/bible': """<h3>La formation du canon biblique</h3><p class="resume-text">La Bible chrétienne résulte d'un long processus de canonisation. L'Ancien Testament (Bible hébraïque) fut canonisé progressivement : la Torah au IVe siècle av. J.-C., les Prophètes au IIe siècle av. J.-C., les Écrits entre le IIe siècle av. J.-C. et le IIe siècle ap. J.-C. Le Nouveau Testament fut définitivement fixé au IVe siècle (lettre de saint Athanase, 367 ; concile de Carthage, 397).</p><p class="resume-text">Les différentes confessions chrétiennes n'ont pas exactement le même canon. Les catholiques incluent sept livres deutérocanoniques (Tobie, Judith, Maccabées, etc.) que les protestants rejettent en les qualifiant d'apocryphes. Les Orthodoxes éthiopiens possèdent un canon encore plus large. Ces différences canoniques reflètent des traditions ecclésiologiques distinctes sur l'autorité de l'Église et de l'Écriture.</p><div class="highlight-box"><p>La Septante — traduction grecque de la Bible hébraïque réalisée à Alexandrie (IIIe-IIe siècle av. J.-C.) — a joué un rôle capital : c'est elle que cite le Nouveau Testament, et c'est sur elle que s'appuient les premiers Pères de l'Église. Elle comprend les livres deutérocanoniques, ce qui explique leur présence dans la Bible catholique.</p></div><h3>L'herméneutique biblique moderne</h3><p class="resume-text">La critique historico-critique, née au XVIIIe siècle (Jean Astruc, Richard Simon, puis Wellhausen pour l'Ancien Testament et les recherches sur le Jésus historique pour le Nouveau), a révolutionné la lecture de la Bible. Elle distingue les couches rédactionnelles, identifie les sources, situe les textes dans leur contexte historique et littéraire.</p><p class="resume-text">La théologie biblique contemporaine cherche à articuler l'approche scientifique et la lecture croyante. Les méthodes synchroniques (narratologie, sémiotique, lecture canonique) s'ajoutent aux méthodes diachroniques. Paul Ricœur, avec sa philosophie de l'interprétation et du récit, a fourni des outils conceptuels pour penser la « polysémie » des textes bibliques et leur capacité à « dire plus » que ce que l'auteur originel entendait.</p>""",

    'textes-sacres/tripitaka': """<h3>Les trois corbeilles et leur contenu</h3><p class="resume-text">Le Tripitaka (Pali : Tipitaka) se divise en trois ensembles. Le Vinaya Pitaka (corbeille de la Discipline) rassemble les règles monastiques : 227 règles pour les moines (bhikkhu), 311 pour les moniales, avec leurs explications narratives (vibhanga) et les règles d'organisation de la communauté (khandhaka). Chaque règle est accompagnée du récit de l'incident qui l'a motivée.</p><p class="resume-text">Le Sutta Pitaka (corbeille des Discours) est la plus volumineuse : elle rassemble les sermons attribués au Bouddha historique, organisés en cinq Nikaya (recueils). Le Dhammapada, l'un des textes bouddhistes les plus lus au monde, en est extrait. L'Abhidhamma Pitaka (corbeille de la Doctrine Supérieure) est une analyse systématique et abstraite des facteurs psycho-cosmiques (dhamma) — la « philosophie scolastique » du bouddhisme Theravada.</p><div class="highlight-box"><p>Le canon Pali du Theravada représente une version parmi d'autres des enseignements du Bouddha. Le bouddhisme Mahayana possède ses propres sutras (en sanskrit et en chinois), composés entre le Ier siècle av. J.-C. et le Ve siècle ap. J.-C. : Sutra du Cœur, Sutra du Diamant, Sutra du Lotus. Ces textes ne prétendent pas rapporter les paroles historiques du Bouddha, mais une révélation plus profonde.</p></div><h3>Transmission et commentaires</h3><p class="resume-text">La transmission du Tripitaka fut d'abord orale. Les moines mémorisaient et récitaient les textes lors de conciles bouddhistes (premier concile à Rajagriha, 483 av. J.-C., juste après la mort du Bouddha). La mise par écrit eut lieu au Ier siècle av. J.-C. au Sri Lanka, à Aluvihara, sur des feuilles de palmier.</p><p class="resume-text">La tradition commentatoriale bouddhiste est considérable. Buddhaghosa (Ve siècle ap. J.-C.) rédige le Visuddhimagga (Chemin de la Purification), synthèse magistrale de la doctrine Theravada qui reste une référence incontournable. En Chine, au Japon et au Tibet, des traditions exégétiques autonomes se développent, donnant naissance à des écoles distinctes (Chan/Zen, Tiantai, Huayan, Tibétain).</p>""",
}

def insert_before_quiz(content, new_html):
    """Insère new_html juste avant la section quiz."""
    quiz_section = '<section class="content-section" id="quiz">'
    contenu_close = '</section>'

    quiz_idx = content.find(quiz_section)
    if quiz_idx == -1:
        return content

    contenu_end_idx = content.rfind(contenu_close, 0, quiz_idx)
    if contenu_end_idx == -1:
        return content

    return content[:contenu_end_idx] + new_html + contenu_close + content[quiz_idx:]

def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for page_key, new_html in ENRICHMENTS.items():
        if page_key in data['pages']:
            page = data['pages'][page_key]
            if page.get('type') == 'course':
                old_len = len(page['content'])
                page['content'] = insert_before_quiz(page['content'], new_html)
                new_len = len(page['content'])
                print(f"Enriched {page_key}: {old_len} -> {new_len} chars (+{new_len-old_len})")
                enriched_count += 1
        else:
            print(f"WARNING: page not found: {page_key}")

    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nDone: {enriched_count} pages enriched.")

if __name__ == '__main__':
    main()
