import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

enrichments = {}

enrichments['materiaux/metaux-et-alliages'] = (
    '<h3>Structure cristalline et propriétés des métaux</h3>'
    '<p class="resume-text">Les métaux sont caractérisés par leur <strong>structure cristalline</strong> : les atomes s\'organisent en réseaux réguliers (cubique face centrée CFC pour le cuivre et l\'aluminium, cubique centré CC pour le fer alpha, hexagonal compact HC pour le titane). Cette structure détermine la plasticité du métal : les structures CFC ont de nombreux systèmes de glissement et sont très ductiles, tandis que les structures HC ont une ductilité plus limitée.</p>'
    '<p class="resume-text">Les <strong>dislocations</strong> sont des défauts linéaires dans le réseau cristallin qui rendent la déformation plastique bien plus facile que ne le prédirait la théorie de glissement rigide. Le mécanisme de mouvement des dislocations explique pourquoi les métaux réels sont 1000 fois plus déformables que les cristaux parfaits. Le <strong>durcissement par écrouissage</strong> (déformation à froid) augmente la densité de dislocations qui se gênent mutuellement, durcissant progressivement le métal.</p>'
    '<p class="resume-text">Les <strong>traitements thermiques</strong> modifient profondément les propriétés des aciers. La trempe (refroidissement rapide depuis la zone austénitique) forme de la martensite, une phase très dure et fragile. Le revenu (chauffage modéré après trempe) réduit les contraintes internes et améliore la ténacité. La trempe + revenu produit des aciers avec la meilleure combinaison résistance-ténacité — c\'est le traitement standard des pièces mécaniques à hautes performances.</p>'
    '<div class="highlight-box"><p>Un acier traité thermiquement peut passer de 200 MPa (recuit) à 2000 MPa (trempe-revenu) tout en conservant la même composition chimique — les traitements thermiques sont le levier le plus puissant du métallurgiste.</p></div>'
    '<h3>Alliages légers : aluminium, titane, magnésium</h3>'
    '<p class="resume-text">Les <strong>alliages d\'aluminium</strong> (série 2xxx Al-Cu, 7xxx Al-Zn-Mg) offrent une résistance spécifique (résistance/densité) comparable à l\'acier à un tiers de sa masse. La série 7075 (Al-Zn-Mg-Cu) atteint 500 MPa en résistance à rupture avec une densité de 2,8 g/cm³. Le traitement de durcissement structural (vieillissement T6 : mise en solution + trempe + maturation artificielle) produit des précipités fins qui bloquent le mouvement des dislocations.</p>'
    '<p class="resume-text">Le <strong>titane</strong> (Ti-6Al-4V est l\'alliage le plus utilisé) combine haute résistance (900 MPa), faible densité (4,5 g/cm³) et résistance à la corrosion exceptionnelle. La biocompatibilité du titane (il s\'intègre à l\'os par ostéointégration) en fait le matériau de choix pour les implants orthopédiques (prothèses de hanche et de genou) et les implants dentaires. Dans l\'aéronautique, le titane remplace l\'acier dans les structures chaudes (nacelles de réacteurs).</p>'
    '<p class="resume-text">Les <strong>superalliages à base nickel</strong> (Inconel, Hastelloy, Waspaloy) maintiennent leur résistance jusqu\'à 1000-1100°C, soit 80% de leur température de fusion. Cette propriété remarquable provient des précipités gamma-prime (Ni₃Al) cohérents avec la matrice, qui bloquent efficacement le glissement des dislocations à haute température. Ces alliages équipent les aubes de turbines des réacteurs aéronautiques et des centrales à gaz.</p>'
    '<div class="highlight-box"><p>Les aubes de turbine en superalliage monocristallin (absence de joints de grains) de réacteur aéronautique opèrent à des températures supérieures à leur point de fusion grâce au refroidissement interne par air — un défi de fabrication exceptionnel.</p></div>'
    '<h3>Corrosion et protection</h3>'
    '<p class="resume-text">La <strong>corrosion électrochimique</strong> se produit lorsque deux métaux de potentiels différents sont en contact en présence d\'un électrolyte (eau salée). Le métal anodique (moins noble) se dissout ; le métal cathodique (plus noble) est protégé. La série galvanique classe les métaux par potentiel : le zinc corrode en protégeant l\'acier (galvanisation), tandis que le cuivre accélère la corrosion du fer.</p>'
    '<p class="resume-text">La <strong>protection cathodique</strong> impose un potentiel négatif sur la structure métallique à protéger (pipelines enterrés, coques de navires, piliers de ponts). Des anodes sacrificielles en zinc ou aluminium (moins nobles que l\'acier) se corrodent à la place de la structure. Les courants impressés (ICCP) imposent le potentiel de protection via des sources de courant extérieures. Ces systèmes protègent des milliers de km de pipelines sous-marins.</p>'
    '<p class="resume-text">Les <strong>revêtements anti-corrosion</strong> créent une barrière physique entre le métal et l\'environnement. La peinture époxy-polyuréthane est standard dans l\'industrie maritime et pétrolière. La galvanisation à chaud (immersion dans le zinc fondu) protège les charpentes métalliques, garde-fous et pylônes. L\'anodisation de l\'aluminium crée une couche d\'alumine dure et étanche, colorable — présente sur toutes les façades architecturales en aluminium.</p>'
    '<div class="highlight-box"><p>La corrosion coûte environ 3% du PIB mondial chaque année — soit plus de 2000 milliards d\'euros. Les investissements en protection anti-corrosion ont un retour sur investissement moyen de 1:25.</p></div>'
)

enrichments['materiaux/polymeres'] = (
    '<h3>Structure et synthèse des polymères</h3>'
    '<p class="resume-text">Les <strong>polymères</strong> sont de longues chaînes macromoléculaires formées par la répétition de motifs élémentaires (monomères). Le polyéthylène (PE) est formé par polymérisation de l\'éthylène ; le polypropylène (PP), le polystyrène (PS), le PVC et le PET sont les autres grands thermoplastiques de grande consommation. La <strong>polymérisation par addition</strong> (propagation de radicaux libres ou anionique/cationique) et la <strong>polymérisation par condensation</strong> (formation d\'eau ou d\'autre sous-produit) sont les deux voies principales.</p>'
    '<p class="resume-text">La <strong>masse moléculaire moyenne</strong> et la distribution des masses (indice de polydispersité) déterminent les propriétés mécaniques et rhéologiques. Les polymères à haute masse moléculaire (UHMWPE, masse molaire de 3-6 millions g/mol) ont des propriétés mécaniques remarquables — résistance à l\'abrasion 10 fois supérieure à l\'acier — utilisés dans les prothèses articulaires et les blindages. La cristallinité (fraction des chaînes organisées en cristallites) joue également un rôle majeur : un HDPE très cristallin est rigide, un LDPE peu cristallin est souple.</p>'
    '<p class="resume-text">La <strong>température de transition vitreuse</strong> Tg est la température au-dessous de laquelle un polymère amorphe passe de l\'état caoutchoutique (segments moléculaires mobiles) à l\'état vitreux (rigide et fragile). Elle détermine la température d\'usage : le polycarbonate (Tg = 147°C) reste rigide à des températures élevées, tandis que le caoutchouc naturel (Tg = -70°C) reste flexible jusqu\'à des températures très basses.</p>'
    '<div class="highlight-box"><p>Les plastiques représentent aujourd\'hui 380 millions de tonnes produites par an dans le monde — mais leur persistance dans l\'environnement (siècles à millénaires pour certains) est devenue un défi planétaire.</p></div>'
    '<h3>Élastomères et caoutchoucs</h3>'
    '<p class="resume-text">Les <strong>élastomères</strong> sont des polymères capables de grandes déformations réversibles (jusqu\'à 800% d\'allongement) grâce à la grande mobilité de leurs chaînes moléculaires et aux réticulations qui les retiennent. Le caoutchouc naturel (polyisoprène) vulcanisé (réticulé par le soufre, procédé Goodyear, 1839) est la base des pneumatiques. Le caoutchouc synthétique (SBR, NBR, EPDM) offre des propriétés adaptées à des usages spécifiques.</p>'
    '<p class="resume-text">Les <strong>pneumatiques modernes</strong> sont un chef-d\'œuvre de technologie polymère. La bande de roulement (SBR chargé en silice pour un meilleur grip mouillé), la carcasse (fils de polyester ou Kevlar noyés dans le caoutchouc), la ceinture de triangulation (fils d\'acier), l\'inner liner (butyle imperméable) et les talons (fils d\'acier) sont autant de couches aux fonctions précises. L\'optimisation multi-physique (adhérence, résistance au roulement, durée de vie) mobilise des simulations numériques poussées.</p>'
    '<p class="resume-text">Les <strong>élastomères thermoplastiques</strong> (TPE, TPU) combinent les propriétés mécaniques des élastomères avec la mise en œuvre facile des thermoplastiques (injection, extrusion). Ils ne nécessitent pas de vulcanisation et sont recyclables. Le polyuréthane thermoplastique (TPU) est utilisé dans les semelles de chaussures, les câbles flexibles et les gaines de protection. Les TPE styréniques (SBS, SEBS) servent dans les joints de porte automobiles et les emballages souples.</p>'
    '<div class="highlight-box"><p>Un pneumatique de voiture contient plus de 200 composants différents et environ 30 types de caoutchoucs — son développement mobilise des simulations numériques et des tests d\'endurance sur des centaines de milliers de kilomètres.</p></div>'
    '<h3>Polymères haute performance et bioplastiques</h3>'
    '<p class="resume-text">Les <strong>polymères haute performance</strong> résistent à des conditions extrêmes. Le PEEK (polyétheréthercétone, Tg = 143°C, résistance à 100 MPa) est utilisé dans les pièces mécaniques aéronautiques et les implants médicaux en remplacement du métal. Le PTFE (Téflon) avec son coefficient de frottement quasi-nul (0,04) équipe les revêtements anti-adhésifs et les joints étanches dans les industries chimiques. La polyimide (Kapton) supporte 400°C en continu dans les circuits imprimés flexibles et les câbles spatiaux.</p>'
    '<p class="resume-text">Les <strong>résines thermodurcissables</strong> (époxy, polyester, phénoliques) se solidifient de façon irréversible lors de leur réticulation. Une fois réticulées, elles ne ramollissent pas à la chaleur. L\'époxy est la matrice des matériaux composites carbone (avions, voitures de course, éoliennes). Sa rigidité (E = 3-5 GPa), sa résistance à l\'humidité et son adhérence sur les fibres en font le choix standard pour les applications structurales hautes performances.</p>'
    '<p class="resume-text">Les <strong>bioplastiques</strong> sont soit biosourcés (fabriqués à partir de ressources renouvelables : PLA depuis le maïs, PHB depuis des bactéries) soit biodégradables (dégradation en conditions contrôlées). Le PLA (polylactide) est le bioplastique le plus produit : utilisé en impression 3D, emballages alimentaires et sutures médicales résorbables. Les limites actuelles (sensibilité à l\'humidité, températures d\'usage faibles) sont progressivement levées par les recherches en ingénierie moléculaire.</p>'
    '<div class="highlight-box"><p>Le Kevlar (polyamide aromatique) a une résistance spécifique 5 fois supérieure à l\'acier — un gramme de fibres peut résister à une force équivalente à un poids de 3 kg. Les gilets pare-balles en Kevlar exploitent cette propriété remarquable.</p></div>'
)

enrichments['materiaux/ceramiques'] = (
    '<h3>Structure et propriétés des céramiques</h3>'
    '<p class="resume-text">Les <strong>céramiques</strong> sont des matériaux inorganiques non-métalliques constitués de liaisons covalentes et/ou ioniques. Ces liaisons fortes et directionnelles confèrent aux céramiques leur dureté élevée (9 sur l\'échelle de Mohs pour le corindon, Al₂O₃), leur résistance à la température et leur faible réactivité chimique. En contrepartie, l\'absence de mobilité des dislocations (liaisons directionnelles) rend les céramiques intrinsèquement <strong>fragiles</strong> — elles ne se déforment pas plastiquement avant rupture.</p>'
    '<p class="resume-text">La <strong>ténacité à la rupture</strong> K_IC des céramiques (0,5 à 5 MPa·√m) est bien plus faible que celle des aciers (20 à 100 MPa·√m). Cette fragilité, combinée à la présence inévitable de défauts microstructuraux (pores, inclusions, microfissures), rend le dimensionnement en rupture probabiliste. La <strong>mécanique de la rupture statistique</strong> (distribution de Weibull) décrit la probabilité de rupture en fonction de la contrainte appliquée et du volume sollicité — donnée essentielle pour les pièces céramiques de sécurité.</p>'
    '<p class="resume-text">La <strong>résistance thermique</strong> des céramiques est exceptionnelle. L\'alumine (Al₂O₃) fond à 2050°C, la magnésie (MgO) à 2852°C, la zircone (ZrO₂) à 2700°C. Les céramiques réfractaires garnissent les fours métallurgiques, les fours cimentiers et les réacteurs chimiques. Le quartz (SiO₂) est la base du verre — un matériau céramique amorphe utilisé dans les fenêtres, l\'optique et les fibres optiques.</p>'
    '<div class="highlight-box"><p>Les tuiles de protection thermique de la navette spatiale (briques de silice HRSI) résistaient à 1260°C en surface tout en restant froides à la main 1 cm plus loin — une performance d\'isolation thermique sans équivalent.</p></div>'
    '<h3>Céramiques techniques et avancées</h3>'
    '<p class="resume-text">Le <strong>carbure de silicium</strong> (SiC) combine dureté extrême (9,5 Mohs), conductivité thermique élevée (120 W/m·K) et résistance aux hautes températures. Les disques de frein en carbone-SiC (Porsche, Ferrari) pèsent moitié moins que l\'acier et résistent mieux à l\'échauffement intense au freinage. Les composites CMC (Ceramic Matrix Composites) à fibres SiC dans matrice SiC équipent les aubes de turbine de nouvelle génération (CFM LEAP), permettant de réduire le refroidissement et d\'augmenter le rendement.</p>'
    '<p class="resume-text">La <strong>zircone partiellement stabilisée</strong> (PSZ, ZrO₂ + CaO ou Y₂O₃) exploite une transformation de phase martensitique pour renforcer la ténacité. Lorsqu\'une fissure se propage, la transformation de phase en zone de pointe de fissure consomme de l\'énergie et freine l\'avancée. Ce mécanisme (transformation toughening) élève K_IC à 8-12 MPa·√m — record pour les céramiques. La zircone yttriée est le matériau de choix pour les prothèses dentaires et les couronnes céramiques.</p>'
    '<p class="resume-text">Les <strong>céramiques piézoélectriques</strong> (PZT — titano-zirconate de plomb) convertissent énergie mécanique en énergie électrique et vice versa. Les capteurs ultrasoniques (contrôle non destructif, imagerie médicale échographique), les actionneurs piézoélectriques (positionnement nanométrique, injecteurs common rail diesel) et les générateurs d\'énergie vibratoire utilisent le PZT. Les bimorphes piézoélectriques sont utilisés comme micro-actionneurs dans les têtes d\'impression à jet d\'encre.</p>'
    '<div class="highlight-box"><p>La zircone dentaire (Zr02 yttriée) est aujourd\'hui utilisée dans des millions de prothèses dentaires et couronnes — elle résiste à la mastication tout en étant biocompatible et esthétiquement proche de la dent naturelle.</p></div>'
    '<h3>Verres techniques et vitrocéramiques</h3>'
    '<p class="resume-text">Le <strong>verre borosilicaté</strong> (Pyrex, Duran) a un faible coefficient de dilatation thermique (3,3 × 10⁻⁶/K contre 9 × 10⁻⁶/K pour le verre sodique), lui conférant une excellente résistance aux chocs thermiques. Il est utilisé dans la verrerie de laboratoire, les plats allant au four et les télescopes astronomiques. Le miroir du télescope spatial Herschel (3,5m de diamètre) est en verre Zerodur® (dilatation quasi-nulle), poli à ±10 nm de précision.</p>'
    '<p class="resume-text">Le <strong>verre trempé</strong> (chauffé puis refroidi brutalement) présente des compressions en surface et des tractions internes. Les compressions superficielles empêchent la propagation des microfissures superficielles — la résistance est multipliée par 4 à 5. En cas de rupture, le verre trempé se fragmente en petits morceaux inoffensifs (vitres de voiture latérales). Le verre feuilleté (feuillets liés par un polymère PVB ou EVA) reste en place lors de la rupture (pare-brise).</p>'
    '<p class="resume-text">Les <strong>vitrocéramiques</strong> (Zerodur, Pyroceram, Robax) sont des verres partiellement cristallisés par traitement thermique contrôlé. Les nanocristaux inclus dans la matrice amorphe modifient les propriétés selon la composition : résistance aux chocs thermiques pour les plaques de cuisson (Schott Ceran), coefficient de dilatation quasi nul pour les supports de miroirs optiques (Zerodur). Ce matériau hybride verre-céramique cumule les avantages des deux familles.</p>'
    '<div class="highlight-box"><p>Le verre Corning Gorilla Glass (aluminosilicate échangé ioniquement) équipe plus de 8 milliards d\'écrans de smartphones — sa résistance aux rayures et aux chutes dépasse de loin celle du verre sodique classique.</p></div>'
)

enrichments['materiaux/composites'] = (
    '<h3>Mécanismes de renforcement et architectures</h3>'
    '<p class="resume-text">Un <strong>matériau composite</strong> associe au moins deux constituants de natures différentes pour obtenir des propriétés supérieures à celles des constituants séparés. La règle des mélanges donne les propriétés dans l\'axe des fibres : E_composite = Vf × Ef + Vm × Em. Une fibre de carbone haute résistance (E = 230 GPa, résistance = 4500 MPa, densité = 1,8 g/cm³) noyée dans une matrice époxy crée un stratifié plus rigide et plus résistant que l\'aluminium à densité deux fois plus faible.</p>'
    '<p class="resume-text">L\'<strong>architecture des fibres</strong> détermine le comportement directionnel du composite. Les stratifiés unidirectionnels (UD) sont optimaux dans une direction mais faibles transversalement. Les tissus bidirectionnels (0°/90°) ou quadraxiaux (0°/45°/-45°/90°) donnent des propriétés quasi-isotropes en plan. La séquence d\'empilement (lay-up) doit être équilibrée et symétrique pour éviter les couplages membrane-flexion qui déformeraient la pièce lors de la polymérisation.</p>'
    '<p class="resume-text">Les <strong>résines thermodurcissables</strong> (époxy, polyester vinylester, phénolique) sont les matrices les plus utilisées en composites structuraux. L\'époxy offre la meilleure combinaison rigidité, adhérence sur fibre et résistance à l\'humidité. Les résines thermoplastiques (PEEK/CF, PA/CF) permettent le soudage, le reformage à chaud et le recyclage thermomécanique — un avantage décisif pour les futures réglementations en économie circulaire.</p>'
    '<div class="highlight-box"><p>Le Boeing 787 Dreamliner est composé à 50% en masse de matériaux composites — une première pour un avion de ligne, permettant une économie de carburant de 20% par rapport aux structures métalliques équivalentes.</p></div>'
    '<h3>Procédés de fabrication des composites</h3>'
    '<p class="resume-text">La <strong>mise en œuvre par voie humide</strong> (drapage manuel, infusion sous vide) consiste à imprégner les fibres sèches de résine liquide et à polymériser en étuve ou autoclave. L\'autoclave (four sous pression, 6 bars, 180°C) comprime les plis et chasse les bulles pour obtenir des taux de porosité inférieurs à 0,5% — standard aéronautique. Le procédé RTM (Resin Transfer Molding) injecte la résine sous pression dans un moule fermé contenant les fibres sèches, assurant un meilleur contrôle des tolérances géométriques.</p>'
    '<p class="resume-text">L\'<strong>enroulement filamentaire</strong> dépose des mèches de fibres imprégnées de résine sur un mandrin rotatif selon des angles programmés. Les tubes de carbone (mâts de voilier, arbres de transmission de F1), les réservoirs cylindriques (bouteilles de GNV, tuyaux haute pression) et les tubes de fusées sont typiquement produits ainsi. Le procédé est continu, rapide et économique pour les pièces de révolution.</p>'
    '<p class="resume-text">La <strong>fabrication additive de composites</strong> (FFF avec fibres continues : Markforged, Continuous Fiber Fabrication) dépose simultanément des fibres de carbone ou de verre et une matrice thermoplastique couche par couche. Ce procédé ouvre la voie à des pièces composites de géométrie complexe sans moule, avec des propriétés mécaniques comparables au stratifié conventionnel pour les applications non structurales. La robotisation du drapage (placement automatique de fibres, AFP/ATL) réduit le coût de fabrication des grandes pièces aéronautiques.</p>'
    '<div class="highlight-box"><p>Les pales d\'éoliennes de 75 m de long sont parmi les plus grandes structures composites jamais fabriquées — elles sont moulées en une seule pièce par infusion de résine époxy sur des fibres de verre et de carbone.</p></div>'
    '<h3>Durabilité et contrôle non destructif</h3>'
    '<p class="resume-text">Les composites sont sensibles à l\'<strong>impact basse vitesse</strong> (chute d\'outil, grêle) qui crée des délaminations invisibles en surface mais qui réduisent drastiquement la résistance en compression. Le contrôle par ultrasons (C-scan, phased array) détecte ces défauts subsurfaciques en cartographiant l\'atténuation des ondes ultrasoniques. La thermographie infrarouge active (chauffage + imagerie IR) révèle les délaminations par les anomalies de diffusion thermique.</p>'
    '<p class="resume-text">Le <strong>vieillissement humide</strong> des composites époxy est un enjeu majeur. L\'eau diffuse dans la matrice (jusqu\'à 3-5% en masse à saturation), plastifie la résine et réduit la température de transition vitreuse. Sur les avions opérant en atmosphère tropicale, l\'absorption d\'humidité peut réduire les propriétés en compression de 15-20%. Les certifications aéronautiques imposent des tests en condition chaude et humide (CTHI) pour valider les marges de sécurité.</p>'
    '<p class="resume-text">La <strong>réparation des composites</strong> est une activité industrielle majeure. Les dommages superficiels (rayures, éclats) sont réparés par patches collés ou co-polymérisation de préimprégnés. Les dommages structuraux (fractures, délaminations profondes) nécessitent des réparations Scarfed (biseau progressif pour restaurer la continuité des fibres). Les nouvelles technologies de réparation comprennent les patchs chauffants portables et la réparation par fabrication additive de fibres continues.</p>'
    '<div class="highlight-box"><p>Le contrôle non destructif par ultrasons d\'une aile d\'Airbus A350 (composite carbone-époxy) génère des téraoctets de données à analyser — les algorithmes d\'intelligence artificielle commencent à automatiser l\'interprétation de ces signaux complexes.</p></div>'
)

enrichments['materiaux/nanomateriaux'] = (
    '<h3>Nanomatériaux carbonés : graphène et nanotubes</h3>'
    '<p class="resume-text">Le <strong>graphène</strong> est une monocouche d\'atomes de carbone organisés en réseau hexagonal. Isolé en 2004 par Geim et Novoselov (Nobel 2010) par clivage mécanique du graphite, il présente des propriétés remarquables : module d\'Young de 1 TPa (le plus élevé mesuré), résistance à rupture de 130 GPa, conductivité électrique supérieure au cuivre et conductivité thermique supérieure au diamant. Ces propriétés exceptionnelles font du graphène un matériau phare de la nanotechnologie.</p>'
    '<p class="resume-text">Les <strong>nanotubes de carbone</strong> (NTC) sont des feuillets de graphène enroulés en cylindre de diamètre nanométrique (1-50 nm) et de longueur micrométriques ou plus. Les nanotubes monoparois (SWCNT) ont des propriétés électroniques uniques (métalliques ou semi-conducteurs selon l\'angle d\'enroulement). Incorporés dans des matrices polymères à des fractions volumiques de 0,1-1%, ils améliorent considérablement la conductivité électrique, la résistance mécanique et la résistance au feu des composites.</p>'
    '<p class="resume-text">Les <strong>applications industrielles</strong> des nanomatériaux carbonés progressent. Les raquettes de tennis et de badminton en composite CNT-carbone offrent un meilleur amorti vibratoire. Les batteries Li-ion à anode en graphène-silicium promettent une densité énergétique doublée. Les revêtements à base de graphène sur acier réduisent la corrosion de 90%. Les capteurs de gaz ultra-sensibles en graphène détectent une molécule unique dans un million d\'autres.</p>'
    '<div class="highlight-box"><p>Une feuille de graphène d\'un atome d\'épaisseur peut supporter un chat adulte avant de se rompre — sa résistance mécanique (130 GPa) dépasse tous les matériaux connus.</p></div>'
    '<h3>Nanocomposites et nanorevêtements</h3>'
    '<p class="resume-text">Les <strong>nanocomposites à argile</strong> (smectites, montmorillonite) dispersent des feuillets nanométriques d\'argile dans une matrice polymère. Avec seulement 3-5% en masse de nanochargés, la rigidité augmente de 40%, la résistance à la flamme s\'améliore et la perméabilité aux gaz diminue de 50%. Ces nanocomposites nylon-argile équipent les réservoirs d\'essence des véhicules Toyota (Nylon6-argile depuis 1991) et les barquettes alimentaires à haute barrière.</p>'
    '<p class="resume-text">Les <strong>nanorevêtements</strong> déposés par ALD (Atomic Layer Deposition) ou CVD contrôlent la composition couche par couche avec une précision atomique. Une couche d\'Al₂O₃ de 10 nm déposée par ALD sur un film polymère réduit la perméabilité à l\'oxygène de 10 000 fois — permettant des emballages alimentaires ultra-barrière très minces et légers. Les revêtements TiN, CrAlN et DLC sur outils de coupe réduisent l\'usure et améliorent la productivité d\'usinage.</p>'
    '<p class="resume-text">Les <strong>nanoparticules fonctionnelles</strong> (TiO₂ photocatalytique, ZnO antimicrobien, nanoparticules d\'argent) sont intégrées dans des bétons auto-nettoyants, des textiles antibactériens et des vitrages anti-UV. Les nanoparticules d\'hydroxyapatite favorisent l\'ostéointégration dans les implants osseux. Les quantum dots (nanocristaux semiconducteurs de 2-10 nm) émettent une lumière très précise en longueur d\'onde, utilisés dans les écrans QLED (quantum LED) pour une gamme de couleurs étendue.</p>'
    '<div class="highlight-box"><p>Les nanoparticules de TiO₂ intégrées dans le ciment créent des surfaces photocatalytiques qui dégradent les polluants organiques et les oxydes d\'azote à la lumière du jour — des bâtiments qui nettoient l\'air de la ville.</p></div>'
    '<h3>Nanofabrication et perspectives</h3>'
    '<p class="resume-text">La <strong>lithographie par UV</strong> (photolithographie) est le procédé standard de fabrication des circuits intégrés. Un masque projeté sur une couche de résine photosensible crée le motif souhaité. La résolution est limitée par la longueur d\'onde de la lumière utilisée : l\'EUV (Extreme UV, 13,5 nm) permet des motifs de 7 nm, utilisés dans les processeurs les plus récents. Une machine EUV ASML NXE coûte plus de 200 millions d\'euros et est le maillon critique de toute la chaîne de fabrication des semi-conducteurs avancés.</p>'
    '<p class="resume-text">Le <strong>microscope à effet tunnel</strong> (STM) et le microscope à force atomique (AFM) permettent d\'imager et de manipuler la matière à l\'échelle atomique. IBM a montré dès 1989 qu\'il était possible de positionner des atomes individuels pour former des structures. La manipulation d\'atomes ouvre des perspectives en information quantique (qubits atomiques), stockage de données ultra-dense et chimie de précision.</p>'
    '<p class="resume-text">Les <strong>enjeux de sécurité et environnementaux</strong> des nanomatériaux sont actifs. La petite taille des nanoparticules peut les rendre capables de traverser les barrières biologiques (cutanée, pulmonaire, hémato-encéphalique). La toxicité des nanotubes de carbone (fibres nanométriques inhalées) est étudiée avec attention. La réglementation européenne REACH couvre désormais les nanomatériaux et impose leur déclaration et l\'évaluation de leur risque avant mise sur le marché.</p>'
    '<div class="highlight-box"><p>L\'intégration de nanoparticules de carbure de silicium dans l\'aluminium de fonderie double sa résistance à l\'usure et améliore la tenue en température — une innovation déjà présente dans les bielles et pistons de moteurs hautes performances.</p></div>'
)

# Apply enrichments
count = 0
for key, extra in enrichments.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (materiaux section)")
