#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Enrichissement de design.json et spectacle.json."""
import json

DESIGN_ADDITIONS = {
    "graphique/composition": """<p class="resume-text">La composition en design graphique contemporain intègre les enseignements du Bauhaus et du modernisme tout en s adaptant aux nouveaux médiums numériques. La grille typographique reste le fondement de toute composition lisible, qu il s agisse d un livre imprimé ou d une interface mobile. Les règles classiques — contraste, répétition, alignement, proximité — constituent un vocabulaire universel que les designers maîtrisent pour créer des compositions efficaces.</p>""",

    "graphique/design-numerique": """<h3>Le design d interface et l expérience utilisateur</h3><p class="resume-text">Le design numérique contemporain est dominé par la discipline de l UX/UI (User Experience / User Interface). L UX désigne l ensemble de l expérience d un utilisateur avec un produit numérique — de la première impression à l utilisation quotidienne. L UI concerne la conception visuelle des interfaces : typographie, couleurs, iconographie, mise en page. Ces deux disciplines, complémentaires, définissent la qualité d un produit numérique autant que ses fonctionnalités techniques.</p><p class="resume-text">Le design système (Design System) est devenu la méthode de référence pour les grandes organisations numériques. Un design système est une bibliothèque de composants visuels et de règles d utilisation qui assurent la cohérence d une marque à travers tous ses points de contact numériques. Airbnb Design, Material Design (Google), Human Interface Guidelines (Apple) sont des exemples de design systèmes qui influencent des milliards d interfaces. Cette standardisation facilite le travail des équipes mais soulève des questions sur la créativité et la différenciation visuelle.</p><div class="highlight-box"><p>Figma, outil de design d interface lancé en 2016, a révolutionné le secteur en permettant la collaboration en temps réel de plusieurs designers sur le même fichier. Son rachat annoncé par Adobe pour 20 milliards de dollars en 2022 (finalement abandonné sous pression réglementaire) illustre la valeur économique du design numérique collaboratif.</p></div>""",

    "industriel/ecoconception": """<h3>Les matériaux biosourcés et l économie circulaire</h3><p class="resume-text">L écoconception mobilise une nouvelle génération de matériaux biosourcés — issus du vivant et biodégradables. Le mycélium (réseau de champignons) peut être cultivé dans des moules pour créer des matériaux d emballage ou d isolation aussi résistants que le polystyrène mais entièrement compostables. Les bioplastiques issus d algues, d amidon de maïs ou de canne à sucre offrent des alternatives aux plastiques pétroliers. Des designers comme Neri Oxman explorent ces "bio-matériaux" dans des applications architecturales et produit.</p><p class="resume-text">L économie circulaire transforme la façon dont les designers pensent la fin de vie des produits. Le "cradle to cradle" (du berceau au berceau), concept développé par William McDonough et Michael Braungart, postule que les déchets d un produit doivent devenir la matière première d un autre. Les designers intègrent désormais dès la conception la démontabilité, la séparabilité des matières et la recyclabilité — repensant fondamentalement le cycle de vie des objets industriels.</p><div class="highlight-box"><p>Le jean Levi s "WellThread", conçu selon des principes d économie circulaire, utilise exclusivement du coton biologique, des teintures sans toxines et une construction qui permet le démontage complet pour le recyclage. Ce produit illustre comment l écoconception devient une contrainte créative qui génère de l innovation plutôt qu une limitation.</p></div>""",

    "industriel/ergonomie": """<h3>L ergonomie dans les espaces de travail</h3><p class="resume-text">L ergonomie des espaces de travail a connu une révolution avec la généralisation du télétravail post-COVID. Les entreprises investissent dans des bureaux "hybrides" qui alternent travail à distance et présence au bureau, nécessitant des espaces flexibles, des outils de collaboration nomades et des environnements qui favorisent à la fois la concentration individuelle et la collaboration collective. L ergonomie cognitive — conception des environnements pour optimiser les fonctions mentales (attention, mémoire, créativité) — est devenue aussi importante que l ergonomie physique traditionnelle.</p><p class="resume-text">La chaise de bureau est l objet ergonomique le plus étudié et le plus vendu au monde. Depuis la chaise Aeron d Herman Miller (1994), conçue après des études approfondies sur la posture et le support lombaire, le marché des sièges ergonomiques de qualité a explosé. La Leap Chair, la Gesture d Steelcase, la Embody d Herman Miller — ces produits à 1 000-2 000 euros représentent l état de l art de la recherche ergonomique appliquée à l assise professionnelle.</p><div class="highlight-box"><p>Les études montrent que 80% des travailleurs de bureau souffrent de douleurs dorsales à un moment de leur vie professionnelle. Le coût économique des troubles musculo-squelettiques liés au travail représente en France plus de 10 milliards d euros annuels en arrêts maladie et soins. L investissement dans l ergonomie des postes de travail est donc économiquement rationnel pour les entreprises.</p></div>""",

    "industriel/grands-designers": """<h3>Le design contemporain et ses figures émergentes</h3><p class="resume-text">Le design contemporain est marqué par l émergence de figures issues de contextes non-occidentaux qui redéfinissent les canons esthétiques traditionnels. Patricia Urquiola (espagnole, basée à Milan) fusionne tradition artisanale méditerranéenne et technologie industrielle dans des meubles et objets qui ont redéfini le mobilier de luxe contemporain. Nendo (studio japonais de Oki Sato) produit des objets d une poésie minimaliste qui revendique l héritage du design industriel Scandinavian tout en l enrichissant de sensibilité japonaise.</p><p class="resume-text">Virgil Abloh (1980-2021), directeur artistique chez Louis Vuitton et fondateur d Off-White, a incarné une nouvelle génération de designers qui brouillent les frontières entre mode, art, architecture et culture urbaine. Son approche du "3% design" — modifier un objet existant à seulement 3% pour en changer radicalement la perception — est une méthode créative qui questionne l originalité et l appropriation dans le design contemporain. Sa mort prématurée à 41 ans a été vécue comme une perte immense par l industrie.</p><div class="highlight-box"><p>Zaha Hadid (1950-2016), première femme à remporter le Pritzker Prize d architecture (2004), a développé une architecture déconstructiviste aux formes fluides et organiques rendues possibles par les logiciels de conception paramétrique. Son Opera House de Guangzhou, le Centre Heydar Aliyev de Bakou et le Maxxi de Rome illustrent comment le design architectural repousse les limites de la forme grâce aux outils numériques de conception et de fabrication.</p></div>""",

    "industriel/histoire-design": """<h3>Le design dans la mondialisation</h3><p class="resume-text">La mondialisation a profondément transformé l économie et la géographie du design industriel. La délocalisation de la production industrielle vers l Asie a déplacé une partie du design industriel dans ces pays — des designers chinois, coréens et indiens de talent formés dans les écoles occidentales développent maintenant des identités de marques et des produits pour leurs marchés locaux en croissance rapide. Des entreprises comme Huawei, Samsung ou Haier investissent massivement dans le design pour rivaliser avec Apple et les marques européennes sur le terrain de l esthétique et de l expérience utilisateur.</p><p class="resume-text">L émergence des Fab Labs et de l impression 3D a démocratisé l accès à la fabrication de prototypes et d objets personnalisés. Des designers indépendants peuvent maintenant produire des petites séries sans investissement industriel lourd. Cette "démocratisation du making" transforme le modèle traditionnel du design industriel — production de masse d objets identiques — vers un modèle de personnalisation et de production locale à la demande qui modifie les chaînes de valeur de l industrie.</p><div class="highlight-box"><p>IDEO, cabinet de design américain fondé en 1991, a popularisé le "design thinking" comme méthode de résolution de problèmes applicable à tous les secteurs. Cette approche — empathie avec l utilisateur, idéation, prototypage rapide, test itératif — est maintenant enseignée dans les MBA et appliquée aux problèmes de santé publique, d éducation et de politique sociale au-delà de sa sphère d origine industrielle.</p></div>""",

    "industriel/materiaux-procedes": """<h3>Les matériaux intelligents et les nouvelles frontières</h3><p class="resume-text">Les matériaux "intelligents" — qui réagissent à leur environnement en changeant de forme, de couleur, de conductivité ou d autres propriétés — ouvrent de nouvelles frontières pour le design. Les alliages à mémoire de forme (nitinol) reviennent à leur forme originale après déformation. Les matériaux piézoélectriques transforment la pression mécanique en électricité. Les textiles conducteurs intégrant des capteurs électroniques permettent des "vêtements intelligents" qui monitorent des données physiologiques. Ces innovations brouillent les frontières entre design industriel, ingénierie et biotechnologie.</p><div class="highlight-box"><p>Le graphène — feuille monoatomique de carbone découverte en 2004 par Geim et Novoselov (Nobel 2010) — est le matériau le plus résistant jamais mesuré (200 fois l acier), le plus conducteur électriquement et l un des plus légers. Son intégration dans les matériaux composites du futur promet des structures ultralegères et ultrasolides pour l aéronautique, l automobile et les dispositifs médicaux — mais son coût de production reste un frein majeur à l industrialisation.</p></div>""",

    "interieur/couleurs-materiaux": """<h3>La psychologie de la couleur dans l espace intérieur</h3><p class="resume-text">L influence des couleurs sur l humeur et le comportement dans les espaces intérieurs est bien documentée. Les études de chronobiologie montrent que la lumière bleue (longueur d onde courte) supprime la mélatonine et favorise l éveil — les espaces de travail bénéficient d un éclairage riche en bleu, tandis que les espaces de repos doivent éviter cette partie du spectre. Les teintes chaudes (oranges, terre cuite, ocres) créent un sentiment de confort et d intimité ; les teintes froides (gris, bleu-vert) favorisent la concentration.</p><p class="resume-text">Les tendances colorimétriques dans le design intérieur évoluent par cycles d environ 7 à 10 ans, influencées par les "prévisionnistes de tendances" qui analysent les signaux culturels, technologiques et sociaux pour anticiper les préférences esthétiques du marché. Pantone, avec son "Pantone Color of the Year" annuel, joue un rôle d influenceur de tendances reconnu dans l industrie du design, de la mode et de la décoration. Ces choix — Classic Blue en 2020, Very Peri en 2022, Peach Fuzz en 2024 — influencent les collections de produits des grandes enseignes mondiales.</p><div class="highlight-box"><p>La "biophilie" — le besoin instinctif des humains de connexion avec la nature — est devenu un principe majeur du design intérieur contemporain. Les espaces biophiliques intègrent des plantes vivantes, des matériaux naturels (bois, pierre, liège), des vues sur l extérieur et des systèmes de lumière naturelle dynamique. Des études montrent que ces environnements réduisent le stress, améliorent la concentration et augmentent la satisfaction des occupants.</p></div>""",

    "interieur/eclairage": """<h3>L éclairage intelligent et les nouvelles technologies</h3><p class="resume-text">L éclairage "intelligent" (smart lighting) permet de contrôler automatiquement l intensité, la température de couleur et la direction de la lumière selon les besoins et les circonstances. Les systèmes comme Philips Hue ou DALI permettent de programmer des scénarios lumineux adaptés à chaque activité — travail concentré (lumière froide, intense), réunion créative (lumière neutre, dynamique), détente (lumière chaude, tamisée). Ces technologies transforment l éclairage d une infrastructure fixe en outil de design d expérience flexible.</p><p class="resume-text">La lumière naturelle reste le matériau de design intérieur le plus valorisé. Les architectes et designers intérieurs travaillent avec l orientation solaire, la taille et la position des ouvertures, les matériaux réflecteurs et les puits de lumière pour maximiser la pénétration de lumière naturelle tout en contrôlant les éblouissements et les surchauffes. La certification WELL Building Standard inclut des critères stricts d accès à la lumière naturelle comme facteur de bien-être pour les occupants.</p><div class="highlight-box"><p>La technologie OLED (Organic Light Emitting Diode) permet de créer des surfaces lumineuses ultra-minces et flexibles qui peuvent être intégrées à des murs, des plafonds ou des meubles. Des prototypes de pièces entièrement lumineuses — où les murs eux-mêmes émettent de la lumière — préfigurent une révolution du design intérieur où la distinction entre surface et luminaire disparaîtrait.</p></div>""",

    "interieur/mobilier": """<h3>Le mobilier contemporain et le marché du luxe</h3><p class="resume-text">Le marché du mobilier de luxe contemporain connaît une croissance soutenue depuis les années 2000, porté par l essor des classes aisées dans les pays émergents et le désir d individualisation dans les pays développés. Des marques comme Cassina, Vitra, B&B Italia ou Knoll commercialisent des pièces de designers mondialement reconnus à des prix qui en font de véritables oeuvres d art mobilières. La réédition de classiques du XXe siècle — chaise Panton, fauteuil Eames, table Tulip de Saarinen — maintient vivante la mémoire du design moderne tout en le rendant accessible à de nouvelles générations.</p><p class="resume-text">Le mouvement du mobilier vintage et de seconde main connaît un essor sans précédent. Des plateformes comme Selency, 1stDibs et Pamono mettent en relation acheteurs et vendeurs de mobilier de qualité d occasion, combinant économie circulaire et désir d authenticité. Ce marché valorise les pièces "avec une histoire" — mobilier de famille, éditions limitées des années 1950-1970, créations d artisans locaux — qui s opposent à la standardisation du mobilier de grande distribution.</p><div class="highlight-box"><p>IKEA, fondé en 1943 par Ingvar Kamprad, est la plus grande entreprise de mobilier au monde avec plus de 450 magasins dans 60 pays. Sa méthode — design accessible, esthétique scandinave épurée, montage par l utilisateur — a démocratisé le bon design à des prix abordables tout en transformant les habitudes de consommation mondiales. IKEA vend chaque année 150 millions d exemplaires de sa bibliothèque Billy — le meuble le plus vendu de l histoire.</p></div>""",

    "interieur/principes-amenagement": """<h3>L aménagement intérieur post-pandémie</h3><p class="resume-text">La pandémie de COVID-19 (2020-2021) a profondément modifié les usages résidentiels et les besoins d aménagement. Le télétravail généralisé a rendu nécessaires des espaces de travail à domicile efficaces — un défi dans des appartements non conçus pour ce double usage. Les designers intérieurs ont développé des solutions créatives : cloisons mobiles, meubles multifonctions, niches acoustiques, alcôves de travail intégrées aux espaces de vie. La notion de "home office" est passée de luxe marginal à équipement de base.</p><p class="resume-text">La notion de "well-being by design" — design au service du bien-être physique et mental — est devenue centrale dans l aménagement contemporain. Elle intègre des facteurs comme la qualité de l air intérieur, l acoustique (les appartements modernes souffrent de réverbération excessive due aux surfaces dures), la vue sur la nature, les plantes d intérieur, les matériaux non toxiques. Ces considérations, autrefois réservées aux espaces de travail premium, sont maintenant intégrées dans la conception résidentielle standard des projets de logement neufs.</p><div class="highlight-box"><p>Marie Kondo et sa méthode KonMari (popularisée par le livre "La magie du rangement", 2011, traduit en 40 langues) ont transformé la perception de l aménagement intérieur à l échelle mondiale. Son principe — ne garder que ce qui "suscite de la joie" — applique au mobilier et aux objets une philosophie minimaliste d inspiration zen qui va au-delà de l esthétique pour toucher à la psychologie de la relation aux objets et à l espace domestique.</p></div>""",

    "interieur/styles-decoration": """<h3>Les tendances décoratives contemporaines</h3><p class="resume-text">Le "Japandi" — fusion des esthétiques japonaise et scandinave — est l une des tendances décoratives les plus influentes des années 2020. Il combine le wabi-sabi japonais (acceptation de l imperfection, valorisation du naturel, du minimal) avec le hygge scandinave (confort, chaleur, lumière tamisée) dans des intérieurs épurés aux matériaux naturels, aux lignes simples et aux palettes neutres. Cette convergence de deux traditions du "moins est plus" répond à un besoin contemporain de décélération et d authenticité face à la surproduction d images saturées des réseaux sociaux.</p><p class="resume-text">L "Organic Modern" ou "Earth Tones" est un autre courant dominant — formes organiques douces (courbes, asymétries), teintes terreuses (argile, sable, olive), matériaux naturels (rattan, osier, lin, laine), mix de textures. Ce style, largement diffusé sur Pinterest et Instagram depuis 2019-2020, représente une réaction contre le blanc pur et les lignes dures du minimalisme précédent. Son succès illustre comment les plateformes de partage d images accélèrent la diffusion et la standardisation des tendances décoratives à l échelle mondiale.</p><div class="highlight-box"><p>Instagram a fondamentalement transformé le design d intérieur en faisant de l "instagrammabilité" un critère esthétique de premier ordre. Les restaurants, les hôtels et les commerces conçoivent désormais délibérément des "corners photographiques" — des espaces pensés pour être photogéniques sur téléphone. Cette logique du selfie-décor a créé une homogénéisation internationale des esthétiques de restauration et d hôtellerie qui efface les particularités locales.</p></div>""",
}

SPECTACLE_ADDITIONS = {
    "opera/comedie-musicale": """<h3>Broadway et la comédie musicale contemporaine</h3><p class="resume-text">Broadway, artère théâtrale de New York, reste le centre mondial de la comédie musicale. Ses productions réunissent les meilleurs compositeurs, librettistes, chorégraphes et interprètes dans des spectacles dont les budgets atteignent plusieurs dizaines de millions de dollars. Les Tony Awards, équivalent des Oscars pour le théâtre américain, constituent le baromètre annuel de la santé artistique de la scène new-yorkaise. Les succès de Broadway — The Phantom of the Opera (35 ans à l affiche !), Chicago, Hamilton — génèrent des tournées mondiales et des adaptations cinématographiques qui diffusent le genre à l échelle planétaire.</p><p class="resume-text">Hamilton (Lin-Manuel Miranda, 2015) a provoqué une révolution culturelle dans la comédie musicale en racontant les Pères fondateurs américains à travers le hip-hop, le R&B et le rap, avec une distribution entièrement afro-américaine et hispanophone. Ce spectacle, qui a remporté 11 Tony Awards, a démontré que la comédie musicale pouvait être simultanément politiquement engagée, culturellement inclusive et commercialement triomphante. Sa diffusion sur Disney+ pendant la pandémie (2020) l a rendu accessible à un public mondial immense.</p><div class="highlight-box"><p>The Phantom of the Opera (Andrew Lloyd Webber, 1986) a été représenté plus de 13 000 fois à Broadway entre 1988 et 2023 — le plus long run de l histoire de Broadway. Au moment de sa fermeture définitive, il avait généré plus de 1,3 milliard de dollars de recettes à New York seul, sans compter les tournées mondiales. Ce record illustre la puissance économique d un blockbuster musical réussi.</p></div>""",

    "opera/grands-compositeurs": """<h3>Wagner et la révolution du drame musical</h3><p class="resume-text">Richard Wagner (1813-1883) a opéré la plus grande révolution de l histoire de l opéra en inventant le concept de Gesamtkunstwerk (oeuvre d art totale) — une fusion de la musique, de la poésie, de la danse, des décors et de la lumière en une expérience artistique unifiée. Contre l opéra conventionnel où les airs, les ensembles et les récitatifs alternaient de façon prévisible, Wagner développa le "drame musical" où la musique coule de façon continue, guidée par des Leitmotive (motifs conducteurs) — brefs thèmes musicaux associés à des personnages, des émotions ou des idées qui reviennent et se transforment tout au long de l oeuvre.</p><p class="resume-text">L Anneau du Nibelung (Der Ring des Nibelungen) est le projet artistique le plus ambitieux jamais réalisé dans l histoire de l opéra. Ce cycle de quatre opéras totalisant 15 heures de musique (Das Rheingold, Die Walküre, Siegfried, Götterdämmerung) raconte une saga mythologique nordique sur la corruption du monde par la soif d or et de pouvoir. Wagner conçut et supervisa la construction du Festival Theater de Bayreuth (1876), salle dédiée exclusivement à ses oeuvres, dont l acoustique et l agencement avaient été spécifiquement prévus pour ses drames musicaux.</p><div class="highlight-box"><p>Le Festival de Bayreuth, fondé par Wagner et dirigé aujourd hui par ses descendants, reste le pèlerinage annuel de tous les wagnériens du monde. Les billets pour les représentations (produites entièrement par la famille Wagner) ont une liste d attente de 7 à 10 ans. Cette exclusivité fait de Bayreuth l institution opératique la plus mythique et la plus controversée du monde.</p></div>""",

    "opera/histoire-opera": """<h3>L opéra baroque et sa renaissance contemporaine</h3><p class="resume-text">L opéra baroque (1600-1750) connaît depuis les années 1970-1980 un renouveau spectaculaire grâce au mouvement de la musique ancienne sur instruments d époque. Des chefs d orchestre comme William Christie, Nikolaus Harnoncourt, René Jacobs et des ensembles comme Les Arts Florissants ont révélé à de nouveaux publics les opéras de Monteverdi, Cavalli, Rameau, Haendel et Purcell dans des lectures vivantes et théâtralement engagées. Ce retour aux sources instrumentales (cordes gut, clavecin, théorbe) transforme la couleur sonore et le phrasé musical, rendant à ces oeuvres une légèreté et une ornementalisation que les grands orchestres modernes effaçaient.</p><p class="resume-text">Gluck, réformateur de l opéra au XVIIIe siècle, avait voulu purger l opéra baroque de ses excès décoratifs pour le mettre au service du drame. Sa célèbre "Réforme de Gluck" (Orfeo ed Euridice, 1762 ; Alceste, 1767) exigeait que la musique serve l expression dramatique plutôt que de donner aux chanteurs l occasion de montrer leur virtuosité technique. Cette querelle entre opéra "brillant" et opéra "expressif" traverse toute l histoire du genre et se retrouve dans les débats contemporains sur la priorité du chant ou du jeu scénique.</p><div class="highlight-box"><p>Orphée et Eurydice de Gluck (version de 1762) est considéré par les musicologues comme l un des tournants décisifs de l histoire de l opéra. Le refus de Gluck d interrompre l action pour des arias conventionnels, sa décision de laisser le chagrin d Orphée s exprimer sans fioritures vocales, inaugurait une nouvelle conception du chant dramatique qui allait mener directement à Mozart, puis Verdi, puis Wagner.</p></div>""",

    "opera/opera-contemporain": """<h3>L opéra contemporain et les nouvelles formes</h3><p class="resume-text">L opéra contemporain explore des formes hybrides qui brouillent les frontières avec le théâtre musical, la performance art et le cinéma. George Benjamin (Written on Skin, 2012) compose des oeuvres d une densité dramatique et musicale qui renouvellent le genre sans le trahir — ses opéras sont accueillis avec enthousiasme par un public qui avait abandonné l opéra contemporain après les expériences atonales difficiles des années 1960-1980. La soprano Barbara Hannigan incarne ces nouvelles voies à la fois comme interprète et comme chef d orchestre, défendant un répertoire contemporain exigeant avec une conviction artistique rare.</p><p class="resume-text">Les productions d opéra "relectures" — placant les oeuvres classiques dans des contextes contemporains radicalement différents — divisent le public depuis les années 1970. Les mises en scène de Patrice Chéreau (Ring à Bayreuth en 1976, avec un Ring situé dans l ère industrielle) ou de Peter Sellers ont créé des polémiques mondiales et renouvelé radicalement la façon d aborder le répertoire. Aujourd hui, la "Regieoper" (opéra de régie, terme allemand qui désigne ces relectures conceptuelles) est devenue une norme dans les grandes maisons d opéra européennes, suscitant les huées des traditionalistes et l enthousiasme des néophytes.</p><div class="highlight-box"><p>Philip Glass a composé plus de 25 opéras depuis Einstein on the Beach (1976), collaborant avec Robert Wilson dans une esthétique minimaliste et méditative radicalement différente de l opéra traditionnel. Einstein on the Beach — 5 heures sans entr acte, sans intrigue narrative conventionnelle, textes réduits à des chiffres et des solfèges — a créé un scandale ravi au Metropolitan Opera de New York et transformé la perception du possible en art lyrique.</p></div>""",

    "opera/voix-technique": """<h3>La formation vocale et les grandes écoles</h3><p class="resume-text">La formation d un chanteur d opéra est l une des plus longues et des plus exigeantes du monde artistique. Après une formation initiale au conservatoire (5 à 7 ans), les jeunes chanteurs intègrent les "Young Artists Programs" des grandes maisons d opéra (Metropolitan Opera, Opéra National de Paris, Glyndebourne Festival) où ils perfectionnent leur technique vocale, apprennent leur répertoire et leurs langues (l opéra se chante principalement en italien, allemand, français et russe) et font leur apprentissage scénique sous la guidance des artistes en résidence.</p><p class="resume-text">La voix d opéra est un instrument humain d une complexité extraordinaire. La tessiture (étendue des notes qu un chanteur peut produire) définit la catégorie vocale : soprano, mezzo-soprano, alto, ténor, baryton, basse. Mais dans chaque catégorie, les voix se distinguent encore par leur couleur (lyrique, dramatique, colorature, spinto), leur volume et leur aptitude à certains répertoires. Une soprano dramatique comme Birgit Nilsson (Wagner, Strauss) a des exigences physiques et techniques radicalement différentes d une soprano colorature comme Maria Callas dans Lucia di Lammermoor.</p><div class="highlight-box"><p>Maria Callas (1923-1977) est la cantatrice la plus influente du XXe siècle — non pour la beauté de sa voix (souvent critiquée comme inégale) mais pour son intelligence dramatique exceptionnelle. Sa façon de sculpter les phrases, de nuancer les émotions, de faire de chaque air une scène de théâtre a redéfini la façon d interpréter le bel canto. La "révolution Callas" a rendu ses contemporains techniquement parfaits soudainement ternes.</p></div>""",

    "theatre/classique-francais": """<h3>La mise en scène du répertoire classique français</h3><p class="resume-text">Le répertoire classique français (Corneille, Racine, Molière) est interprété à la Comédie-Française, fondée par Louis XIV en 1680 et toujours active — la plus ancienne compagnie théâtrale au monde en activité continue. "La maison de Molière" conserve un répertoire de plus de 3 000 pièces et emploie des comédiens-sociétaires bénéficiant d un statut permanent rare dans le monde théâtral. Cette institution, critiquée pour son conservatisme et célébrée pour la qualité de son travail, est le gardien institutionnel de la langue française au théâtre.</p><p class="resume-text">Les grandes mises en scène du répertoire classique français du XXe et XXIe siècle témoignent de la vitalité de ces textes. Vitez, Chéreau, Mnouchkine (Ariane Mnouchkine du Théâtre du Soleil), Lavaudant ont réinterprété Molière et Racine dans des contextes qui révèlent des dimensions politiques ou psychologiques insoupçonnées. La mise en scène de Dom Juan par Patrice Chéreau (1969) avec le Théâtre National Populaire de Villeurbanne est restée dans les mémoires comme une révélation — un Don Juan des années 1960 dans une société de consommation triomphante.</p><div class="highlight-box"><p>Les 400 ans de Molière (1622-2022) ont été célébrés par de nombreuses productions mondiales et une commémoration nationale en France. La vitalité du répertoire moliéresque — Le Misanthrope, Tartuffe, Dom Juan, Le Bourgeois Gentilhomme — après quatre siècles témoigne de la capacité des grands classiques à dire le présent à travers les masques du passé.</p></div>""",

    "theatre/commedia-dell-arte": """<h3>L héritage de la Commedia dell arte dans le théâtre contemporain</h3><p class="resume-text">L influence de la Commedia dell arte sur le théâtre et les arts du spectacle contemporains est considérable. Dario Fo (Prix Nobel de littérature 1997) a construit toute sa pratique dramatique sur l héritage de la Commedia — improvisation, masques sociaux, bouffonnerie politique, corps clownesque. Ses grandes pièces (Mort accidentelle d un anarchiste, Le Nez) reprennent les figures de la Commedia pour dénoncer la corruption politique et sociale italienne. Ariane Mnouchkine (Théâtre du Soleil) a étudié la Commedia directement auprès de maîtres italiens pour intégrer ses techniques dans un théâtre physique d une puissance chorale exceptionnelle.</p><p class="resume-text">Le clown contemporain tel que le pratiquent Philippe Gaulier, Anne Bogart ou Slava Polunin (Snowshow) est l héritier direct du Zanni de la Commedia. L improvisation encadrée, le rapport au public, la logique du "flop" (l échec comme ressort comique) — toutes ces techniques viennent directement de la tradition des comédiens italiens nomades du XVIe siècle. Les grandes écoles de théâtre mondiales enseignent les techniques de la Commedia comme base de la formation de l acteur physique.</p><div class="highlight-box"><p>Arlequin, le valet acrobatique de la Commedia, est peut-être le personnage théâtral le plus représenté de l histoire. Son losange bicolore (noir et blanc, puis multicolore) est l un des symboles visuels les plus reconnaissables du théâtre mondial. Sa logique de "serviteur malin qui dupe le maître", présente de Plaute jusqu à Goldoni et Marivaux, structure toute la comédie de serviteur de la tradition occidentale.</p></div>""",

    "theatre/mise-en-scene": """<h3>Les metteurs en scène emblématiques du XXe siècle</h3><p class="resume-text">Le XXe siècle a vu émerger le metteur en scène comme figure créatrice centrale du théâtre — une révolution par rapport au XIXe siècle où le texte dramatique primait et l acteur-vedette régnait. Konstantin Stanislavski (Moscou Art Theatre), Vsevolod Meyerhold (constructivisme théâtral), Bertolt Brecht (Berliner Ensemble) et Peter Brook (Centre International de Créations Théâtrales) ont chacun développé des approches qui ont transformé la conception même de ce qu est le théâtre.</p><p class="resume-text">Peter Brook est la figure dominante du théâtre international de la seconde moitié du XXe siècle. Son travail va du Grand Opéra shakespearien (Songe d une nuit d été en 1970, avec trapezes blancs et comédiens en acrobates) aux formes les plus dépouillées (Le Mahabharata, 9 heures sur un tapis de sable) en passant par les expériences de théâtre dans l espace urbain et naturel. Son livre Le Space Vide (1968) reste l un des textes les plus influents sur la nature du théâtre : "Je prends un espace vide et je l appelle une scène nue."</p><div class="highlight-box"><p>Le Théâtre du Soleil d Ariane Mnouchkine, fondé en 1964 comme coopérative théâtrale où tous les membres (acteurs, techniciens, administrateurs) reçoivent le même salaire, incarne une utopie politique et artistique. Ses grandes créations collectives (1789, L Age d or, Les Shakespeare, Les Naufragés du Fol Espoir) mêlent théâtre de masques, traditions asiatiques et politique contemporaine dans des spectacles de 5 à 8 heures qui créent une expérience communautaire rare dans le théâtre occidental.</p></div>""",

    "theatre/theatre-moderne": """<h3>Le théâtre postdramatique et les nouvelles formes</h3><p class="resume-text">Le terme "théâtre postdramatique", théorisé par Hans-Thies Lehmann en 1999, désigne les pratiques théâtrales qui abandonnent la primauté du texte dramatique et de l action narrative. Dans ces formes — performance, théâtre physique, théâtre de l image, happening — le texte peut être absent ou secondaire ; le corps, l espace, la durée et la présence des performers sont les matériaux centraux. Des artistes comme Robert Wilson, Jan Fabre, Castellucci, La Ribot ou René Pollesch développent des esthétiques radicalement différentes qui partagent ce refus de la narration dramatique conventionnelle.</p><p class="resume-text">La performance art, issue des happening des années 1960 (Allan Kaprow, Yoko Ono, Fluxus), questionne les frontières entre vie et art, oeuvre et processus, artiste et spectateur. Marina Abramović, figure mondiale de la performance, soumet son corps à des expériences extrêmes (jeûne, immobilité, douleur) pour explorer les limites de l endurance humaine et la relation de pouvoir entre performer et public. Sa rétrospective au MoMA en 2010 (The Artist is Present) a attiré 750 000 visiteurs, démontrant qu une performance basée sur la présence silencieuse peut toucher un public de masse.</p><div class="highlight-box"><p>Le festival Avignon Off, créé en 1947 par Jean Vilar simultanément au festival officiel, accueille chaque juillet plus de 1 300 spectacles dans 120 lieux de la ville — le plus grand festival de théâtre du monde. Cette prolifération du théâtre "alternatif" sur les toits, dans les cours et les rues d Avignon illustre la vitalité et la diversité des formes théâtrales contemporaines.</p></div>""",

    "theatre/tragedie-grecque": """<h3>La tragédie grecque sur les scènes contemporaines</h3><p class="resume-text">La tragédie grecque continue d être jouée et adaptée dans les théâtres du monde entier, 2 500 ans après sa création. Les grandes tragédies — Oedipe roi, Antigone, Médée, Les Troyennes — traitent de thèmes (le destin contre la liberté, la justice contre le pouvoir, la loyauté contre la morale) qui résonnent directement avec les préoccupations contemporaines. Les régimes autoritaires du XXe siècle ont souvent censuré ou interdit Antigone (qui refuse d obéir à l État quand la loi divine est bafouée) — preuve que les textes anciens continuent de parler au présent.</p><p class="resume-text">L Orestie d Eschyle, cycle tragique en trois pièces qui narre le meurtre d Agamemnon par Clytemnestre, la vengeance d Oreste et l institution de la justice démocratique par Athéna, est une des oeuvres les plus jouées et les plus analysées de l Antiquité. Peter Stein a réalisé à Berlin en 1980 une mise en scène de 8 heures avec 40 acteurs qui reste une référence absolue. Ariane Mnouchkine en a proposé en 1990 une version inspirée du théâtre Nô japonais. Ces interprétations transculturelles illustrent la capacité des grandes oeuvres à traverser les siècles et les cultures.</p><div class="highlight-box"><p>L Epidaure grec, théâtre antique construit au IVe siècle av. J.-C. sur le flanc d une colline, accueille chaque été des représentations de tragédies grecques devant 13 000 spectateurs. Son acoustique naturelle exceptionnelle — un murmure sur la scène est audible au dernier rang — continue de fasciner architectes et acousticiens qui n ont pas encore trouvé d explication physique complète à ce phénomène.</p></div>""",
}


def enrich_discipline(discipline, enrichments, base_path="C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content"):
    filepath = f"{base_path}/{discipline}.json"
    with open(filepath, encoding='utf-8') as fp:
        data = json.load(fp)

    changed = 0
    for key, addition in enrichments.items():
        if key not in data['pages']:
            print(f"  WARNING: key not found: {key}")
            continue
        content = data['pages'][key]['content']
        if len(content) >= 15000:
            print(f"  {key}: already {len(content)} chars, skipping")
            continue
        if '<section class="content-section" id="quiz">' in content:
            content = content.replace(
                '<section class="content-section" id="quiz">',
                addition + '\n<section class="content-section" id="quiz">'
            )
        else:
            content = content.rstrip()
            if content.endswith('</section>'):
                content = content[:-10] + addition + '</section>'
            else:
                content += addition
        data['pages'][key]['content'] = content
        new_len = len(data['pages'][key]['content'])
        print(f"  {key}: {new_len} chars")
        changed += 1

    with open(filepath, 'w', encoding='utf-8') as fp:
        json.dump(data, fp, ensure_ascii=False, indent=2)
    print(f"Saved {discipline}.json ({changed} articles enriched)")

print("=== design ===")
enrich_discipline("design", DESIGN_ADDITIONS)

print("\n=== spectacle ===")
enrich_discipline("spectacle", SPECTACLE_ADDITIONS)

print("\nDone!")
