#!/usr/bin/env python3
"""Enrich histoire pages under 15000 chars."""
import json

PATH = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/histoire.json"

with open(PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def inject(key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

inject('moyen-age/feodalite', """
<h3>Les origines de la féodalité : fragmentation carolingienne et invasions</h3>
<p class="resume-text">La féodalité médiévale émerge du triple effondrement de l'ordre carolingien : la désintégration de l'Empire de Charlemagne après les partages de Verdun (843) et de Meersen (870), l'incapacité du pouvoir central à protéger les populations face aux invasions vikings (Normandie, Angleterre, Bretagne), magyares (Pannonie, raids en Lotharingie, Italie du Nord) et sarrasines (Méditerranée), et la fragmentation du pouvoir royal au profit de l'aristocratie locale disposant des moyens de force (châteaux, cavalerie). Cette convergence de faiblesses a rendu nécessaire une restructuration de la protection et de la production à l'échelle locale.</p>
<p class="resume-text">Le système féodal émerge d'un réseau de relations personnelles fondé sur la <strong>commendatio</strong> romaine tardive et les traditions germaniques du <em>comitatus</em> (suite guerrière du chef). Le vassal se recommande à un seigneur en échange de protection et d'un fief (terre ou revenu). La cérémonie d'hommage (vassal à genoux, mains dans celles du seigneur) et la <strong>foi</strong> (serment de fidélité sur des reliques) constituent les actes fondateurs du lien féodal. Le fief est initialement précaire (révocable) mais devient héréditaire au Xe siècle, transformant les titulaires temporaires en aristocratie enracinée.</p>
<div class="highlight-box"><p><strong>Le débat historiographique :</strong> Marc Bloch, dans « La société féodale » (1939-1940), a construit le concept classique de système féodal cohérent. Des historiens comme Elizabeth Brown et Susan Reynolds ont depuis critiqué ce concept : la « féodalité » serait une construction des historiens du XVIIIe siècle plaquée rétrospectivement sur des réalités médiévales beaucoup plus diverses et moins systématiques qu'on ne le croyait.</p></div>

<h3>La hiérarchie féodale et ses tensions</h3>
<p class="resume-text">La hiérarchie féodale théorique va du roi (suzerain suprême) aux seigneurs hauts (ducs, comtes), moyens (vicomtes, châtelains) et bas (simples chevaliers), jusqu'aux serfs au bas de la pyramide. En pratique, cette pyramide est criblée de contradictions : l'hommage multiple (un vassal peut être vassal de plusieurs seigneurs simultanément), le problème de la « foi préférentielle » (laquelle des obligations prime en cas de conflit entre suzerains), et les « arrière-fiefs » créent une toile inextricable de loyautés croisées.</p>
<p class="resume-text">Les grands fiefs devenus quasi-indépendants — le duché de Normandie, le comté de Flandre, le duché de Bourgogne — illustrent comment la décentralisation féodale pouvait dépasser le cadre royal. Guillaume le Conquérant, duc normand vassal du roi de France, conquiert l'Angleterre en 1066 et crée un nouveau royaume où il est souverain, tout en restant théoriquement vassal en Normandie. Cette situation d'un roi-vassal sera source de conflits franco-anglais pendant trois siècles.</p>

<h3>La vie rurale et le servage</h3>
<p class="resume-text">L'écrasante majorité de la population médiévale vit dans les campagnes. Les <strong>paysans serfs</strong> (en France les vilains, en Angleterre les villeins) ne sont pas des esclaves au sens antique mais des hommes attachés à la terre : ils ne peuvent quitter le domaine sans autorisation, doivent des corvées (travaux gratuits sur les terres du seigneur) en plus des redevances en nature ou en argent, et acquittent le <strong>mainmorte</strong> (le seigneur hérite d'une partie de leurs biens à leur décès). Le <strong>droit de banalité</strong> oblige les paysans à utiliser (et payer) le four, le moulin et le pressoir seigneuriaux.</p>
<p class="resume-text">La <strong>grande famine</strong> de 1315-1322 et la <strong>Peste noire</strong> de 1347-1352 (emportant un tiers de la population européenne) vont paradoxalement améliorer la condition paysanne : la rareté du travail renforce le pouvoir de négociation des survivants. Les révoltes paysannes qui suivent — Jacquerie en France (1358), révolte des paysans anglais (1381) — expriment la rupture du contrat féodal traditionnel face aux tentatives seigneuriales de maintenir les anciens droits dans un monde démographiquement bouleversé.</p>
<div class="highlight-box"><p><strong>Chiffres :</strong> Au XIe siècle, environ 90 % de la population européenne vit en milieu rural. Une seigneurie typique en France du Nord couvre 500 à 2 000 hectares et compte 50 à 200 familles paysannes. La corvée représente en moyenne 2 à 3 jours de travail par semaine sur les terres du seigneur, avec des pics saisonniers (moissons) pouvant dépasser 5 jours.</p></div>

<h3>L'Église dans le système féodal</h3>
<p class="resume-text">L'Église catholique est simultanément un acteur majeur et une perturbation du système féodal. Les évêques et abbés possèdent d'immenses fiefs et sont eux-mêmes vassaux des rois et empereurs, obligés de fournir des contingents militaires (servitium debitum). La <strong>querelle des investitures</strong> (1076-1122) oppose papes et empereurs sur le droit de nommer les évêques : Grégoire VII excommunia Henri IV et le força à la pénitence de Canossa (1077), épisode symbolique de la supériorité papale sur le temporel. Le Concordat de Worms (1122) scelle un compromis : les papes investissent les évêques des fonctions spirituelles, les empereurs des fiefs temporels.</p>
<p class="resume-text">La <strong>paix de Dieu</strong> et la <strong>trêve de Dieu</strong>, promulguées par les conciles à partir du Xe siècle, cherchent à limiter la violence féodale endémique : interdiction d'attaquer paysans, clercs et marchands (paix de Dieu), puis interdiction de combattre du jeudi au lundi et pendant l'Avent et le Carême (trêve de Dieu). Ces initiatives, partiellement respectées, témoignent du rôle de régulateur social que l'Église tente de jouer face à la violence nobiliaire et de la perméabilité du système féodal aux pressions extérieures, ecclésiastiques autant que royales.</p>
""")

inject('moyen-age/empire-byzantin', """
<h3>La civilisation byzantine : héritage romain et identité grecque</h3>
<p class="resume-text">L'Empire byzantin représente une synthèse unique de l'héritage romain (droit, administration, titres impériaux), de la culture grecque (langue, philosophie, littérature) et de la foi chrétienne orthodoxe. Constantinople, fondée par Constantin en 330, est conçue comme une « Nouvelle Rome » — avec son Sénat, ses traditions de jeux du cirque (courses de chars à l'hippodrome), et sa hiérarchie administrative calquée sur le modèle romain. La langue administrative et culturelle évolue progressivement du latin au grec entre le IVe et le VIe siècle.</p>
<p class="resume-text">Le Code Justinien (<em>Corpus Juris Civilis</em>, 529-534), compilé sous l'empereur Justinien par Tribonien, est l'une des contributions les plus durables de Byzance à la civilisation occidentale. Ce recueil systématique du droit romain classique deviendra le fondement de la plupart des systèmes juridiques européens continentaux et influencera directement le Code Napoléon (1804). Justinien chercha aussi à reconquérir l'Occident perdu : ses généraux Bélisaire et Narsès récupèrent l'Afrique du Nord vandale (533-534) et l'Italie ostrogothique (535-554) au prix de guerres épuisantes qui affaiblissent durablement l'Empire.</p>
<div class="highlight-box"><p><strong>Le Schisme de 1054 :</strong> La rupture entre Rome et Constantinople formalise des divergences accumulées depuis des siècles : le <em>filioque</em> (le Saint-Esprit procède du Père ET du Fils, ajouté unilatéralement par l'Ouest), la primauté du pape, le célibat des prêtres. Le légat du pape Humbert de Moyenmoutier et le patriarche Cerularios s'excommunient mutuellement. Ce schisme, jamais totalement réparé, partage le christianisme entre l'Église catholique romaine et les Églises orthodoxes orientales.</p></div>

<h3>Les crises et les renouvaux de l'Empire</h3>
<p class="resume-text">L'histoire byzantine est rythmée par des crises graves suivies de renouvaux. Le VIIe siècle est existentiel : les armées arabes conquièrent la Syrie (636), l'Égypte (642) et l'Afrique du Nord (698), réduisant l'Empire à l'Anatolie et aux Balkans. L'Empire survit grâce au feu grégeois (mélange incendiaire projeté par des siphons), qui détruit les flottes arabes lors des sièges de Constantinople (674-678 et 717-718). Cette résistance préserve l'Europe orientale de l'islam pendant deux siècles supplémentaires.</p>
<p class="resume-text">La « renaissance macédonienne » (IXe-XIe siècle) voit un renouveau artistique, littéraire et militaire. L'armée byzantine, réorganisée autour des thèmes (circonscriptions militaires autonomes), repousse les Arabes et étend l'Empire en Syrie et Arménie. L'Université de Constantinople est refondée. L'évangélisation des Slaves (Cyrille et Méthode inventent l'alphabet cyrillique pour évangéliser les Bulgares et les Moraves) étend l'influence culturelle et religieuse byzantine vers le nord — les Rus' de Kiev adoptent le christianisme orthodoxe en 988, faisant entrer la future Russie dans l'orbite byzantine.</p>
""")

inject('moderne/renaissance', """
<h3>L'humanisme et la redécouverte de l'Antiquité</h3>
<p class="resume-text">L'humanisme renaissant ne se réduit pas à une admiration de l'Antiquité : c'est une révolution intellectuelle qui place l'être humain au centre de la réflexion. Pétrarque (1304-1374), considéré comme le « premier humaniste », exprime pour la première fois une fascination pour la personnalité individuelle et pour les classiques latins lus non plus comme autorités théologiques mais comme témoignages d'une excellence humaine à imiter. Son ascension du Mont Ventoux en 1336, relatée dans une lettre mélangeant observation naturelle et réflexion intérieure, est souvent citée comme un moment fondateur de la sensibilité moderne.</p>
<p class="resume-text">La chute de Constantinople (1453) accélère la diffusion des textes grecs en Occident : des savants byzantins fuient vers l'Italie avec leurs manuscrits. L'Académie platonicienne fondée par Cosme de Médicis à Florence, avec Marsile Ficin (traducteur de Platon et Plotin en latin), devient le foyer d'un néoplatonisme renaissant qui cherche à réconcilier philosophie grecque et théologie chrétienne. Pic de la Mirandole rédige en 1486 ses <em>900 thèses</em> et l'<em>Oratio de dignitate hominis</em> — apologie de la dignité humaine fondée sur la libre volonté d'orientation vers le divin ou le bestial.</p>
<div class="highlight-box"><p><strong>L'invention de l'imprimerie (1450-1455) :</strong> La presse à caractères mobiles de Gutenberg multiplie par 1000 la vitesse de production des livres et en réduit le coût de 90 %. Entre 1450 et 1500, 8 millions de livres sont imprimés — plus que tout ce qui avait été copié en Europe depuis la chute de Rome. Cette révolution médiatique est le vecteur principal de la diffusion des idées humanistes, puis de la Réforme protestante.</p></div>

<h3>Les arts de la Renaissance : une révolution visuelle</h3>
<p class="resume-text">La peinture renaissante révolutionne la représentation visuelle sur plusieurs fronts simultanément. La <strong>perspective linéaire</strong>, redécouverte par Brunelleschi vers 1413 et théorisée par Alberti dans le <em>De Pictura</em> (1435), permet de représenter la profondeur spatiale de manière géométriquement cohérente. Le <strong>sfumato</strong> de Léonard de Vinci (transitions imperceptibles entre ombres et lumières, sans contour net) capture la subtilité des expressions humaines — visible dans le sourire énigmatique de la Joconde. Le <strong>contrapposto</strong> de Michelangelo (torsion du corps autour d'un axe, équilibre dynamique) restitue la vie et le mouvement dans la sculpture.</p>
<p class="resume-text">L'architecture renaissante, codifiée par Vitruve (redécouvert) et Alberti, retrouve les ordres classiques (dorique, ionique, corinthien), les proportions harmoniques et les plans centralisés à coupole inspirés du Panthéon romain. Le dôme de Santa Maria del Fiore de Florence (Brunelleschi, 1420-1436), construit sans cintrage en bois grâce à une technique révolutionnaire de chevrons en épine de poisson, reste la plus grande coupole en maçonnerie jamais construite. La Basilique Saint-Pierre de Rome, dont la coupole fut conçue par Michelangelo à 72 ans, devient le symbole de la grandeur pontificale et le modèle de toute une tradition architecturale européenne.</p>

<h3>La Renaissance hors d'Italie : diffusion et adaptations</h3>
<p class="resume-text">La Renaissance se diffuse en Europe via les échanges artistiques, diplomatiques et commerciaux, mais s'adapte aux contextes locaux plutôt que de se transplanter à l'identique. En France, François Ier fait venir Léonard de Vinci (qui mourra à Amboise en 1519) et initie la Renaissance française avec les châteaux de la Loire (Chambord, 1519-1547). La Renaissance flamande, ancrée dans la tradition du réalisme minutieux des frères van Eyck, développe sa propre voie : Érasme incarne l'humanisme nordique, plus soucieux de réforme morale et religieuse que d'esthétique.</p>
<p class="resume-text">En Angleterre, la Renaissance Tudor est surtout littéraire et musicale : le règne d'Élisabeth Ire (1558-1603) voit l'apogée du théâtre élisabéthain (Shakespeare, Marlowe, Jonson) dans les nouvelles salles publiques de théâtre comme le Globe (1599). L'Espagne renaissante connaît son Siècle d'Or (Cervantes, Lope de Vega, Velázquez, Greco) qui prolonge le mouvement jusque dans le XVIIe siècle. Ces déclinaisons nationales témoignent de la richesse et de la plasticité du mouvement renaissant, qui est moins un style universel qu'une attitude partagée envers l'imitation de l'Antiquité et la valorisation de la création humaine.</p>
<div class="highlight-box"><p><strong>Copernic et la révolution scientifique :</strong> La Renaissance crée les conditions de la révolution scientifique. Copernic (1473-1543), chanoine polonais, publie en 1543 son <em>De Revolutionibus</em> proposant l'héliocentrisme. Sa thèse est initialement acceptée comme hypothèse mathématique commode, avant que Galilée (observations au télescope, 1609-1610) et Kepler (lois des orbites elliptiques, 1609-1619) ne la transforment en vérité physique, déclenchant un conflit avec l'Église qui aboutit à la condamnation de Galilée en 1633.</p></div>
""")

print("Histoire pages enriched:")
for key in ['moyen-age/feodalite','moyen-age/empire-byzantin','moderne/renaissance']:
    print(f"  {key}: {len(pages[key]['content'])} chars")

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved.")
