#!/usr/bin/env python3
"""Deuxième passe d'enrichissement pour relations-internationales.json"""
import json
import re

ENRICHMENTS = {
    "diplomatie/droit-diplomatique": """<h3>Cas contemporains et enjeux actuels</h3><p class="resume-text">Les tensions entre protection diplomatique et responsabilité pénale internationale se manifestent régulièrement. L'<strong>affaire Khashoggi</strong> (octobre 2018) a illustré les limites du droit consulaire : le journaliste saoudien a été assassiné dans le consulat saoudien d'Istanbul par des agents d'État, provoquant une crise diplomatique mondiale et soulevant la question de l'abus des locaux diplomatiques à des fins criminelles. La convention de Vienne, muette sur de tels scénarios, s'est révélée inadaptée.</p><p class="resume-text">La <strong>protection des dissidents</strong> dans les ambassades crée régulièrement des crises. Julian Assange a séjourné sept ans (2012-2019) dans l'ambassade équatorienne de Londres pour échapper à l'extradition. Edward Snowden a transité par l'aéroport de Moscou pendant 40 jours. Le cardinal Mindszenty a résidé 15 ans (1956-1971) dans l'ambassade américaine à Budapest. Ces situations révèlent les tensions entre droit d'asile, immunité diplomatique et primauté de la loi de l'État accréditaire.</p><div class="highlight-box"><p>Depuis l'affaire Khashoggi (2018), la communauté internationale débat de mécanismes de contrôle des locaux diplomatiques pour prévenir les abus tout en préservant l'immunité.</p></div>""",

    "diplomatie/histoire-de-la-diplomatie": """<h3>La diplomatie contemporaine : vers de nouvelles formes</h3><p class="resume-text">La <strong>diplomatie numérique</strong> transforme radicalement la pratique diplomatique. Les réseaux sociaux permettent aux dirigeants de communiquer directement avec les populations étrangères, contournant les chancelleries. La « Twitter diplomacy » inaugurée par Barack Obama et pratiquée de façon spectaculaire par Donald Trump (annonce de décisions majeures via tweets) a bousculé les codes de la communication diplomatique. Les plateformes numériques offrent aussi de nouvelles possibilités de manipulation et de désinformation ciblant les opinions publiques.</p><p class="resume-text">La <strong>diplomatie climatique</strong> illustre l'émergence de nouvelles formes multilatérales. Les Conférences des Parties (COP), réunissant 197 États tous les ans depuis 1995, représentent le plus grand exercice de diplomatie multilatérale permanente de l'histoire. La diplomatie de genre, le rôle des villes (C40), des entreprises (Corporate Diplomacy) et des think tanks élargissent le cercle des acteurs diplomatiques bien au-delà des seuls États.</p><div class="highlight-box"><p>La France a été la première grande puissance à nommer un Ambassadeur pour le numérique (2017), reconnaissant officiellement la diplomatie numérique comme domaine à part entière.</p></div>""",

    "diplomatie/diplomatie-culturelle": """<h3>La diplomatie numérique et les nouvelles arènes de l'influence</h3><p class="resume-text">Les <strong>plateformes numériques</strong> sont devenues des terrains de compétition géopolitique. TikTok (ByteDance, Chine), interdit ou sous surveillance dans de nombreux pays occidentaux, est soupçonné de collecte de données et d'influence sur l'opinion. Les États-Unis ont imposé à son propriétaire de le céder à un acteur non chinois. À l'inverse, les États-Unis utilisent Meta (Facebook, Instagram) et X (ex-Twitter) comme vecteurs de leurs valeurs et leur influence mondiale, suscitant des réglementations étrangères (RGPD européen, censures).</p><p class="resume-text">L'<strong>intelligence artificielle générative</strong> révolutionne la guerre de l'information. Les deepfakes — vidéos synthétiques imitant des personnalités — peuvent fabriquer des déclarations fictives de dirigeants, déstabiliser les marchés ou déclencher des crises diplomatiques. En 2023, des fausses images de l'arrestation de Donald Trump ont circulé massivement. L'authentification du contenu numérique (watermarking, C2PA) est devenue un enjeu de sécurité nationale que les diplomates intègrent désormais dans leurs négociations sur la gouvernance d'internet.</p><div class="highlight-box"><p>En 2024, lors des élections dans 60 pays, des deepfakes électoraux ont été détectés dans 30 d'entre eux, soulevant une alarme mondiale sur la diplomatie de l'ère de l'IA.</p></div>""",

    "organisations-internationales/union-europeenne": """<h3>L'Union européenne face aux crises systémiques</h3><p class="resume-text">La crise de la Covid-19 a paradoxalement renforcé l'intégration européenne : la commande commune de vaccins, inédite dans l'histoire de l'UE, et surtout l'emprunt commun de 750 milliards d'euros (NextGenerationEU) ont franchi un tabou fondateur. Pour la première fois, l'UE s'endette collectivement pour financer des dépenses communes, préfigurant une potentielle union budgétaire. La Commission von der Leyen a imposé le Pacte vert, la boussole numérique et l'autonomie stratégique comme les trois piliers de l'UE du XXIe siècle.</p><p class="resume-text">L'adhésion potentielle de l'<strong>Ukraine</strong> (candidate depuis juin 2022) constitue un défi sans précédent : avec 44 millions d'habitants (avant-guerre) et une économie agricole massive, l'Ukraine changerait fondamentalement l'équilibre au sein des institutions. Les négociations d'adhésion, ouvertes en 2024, s'annoncent comme les plus complexes de l'histoire européenne. La question du financement de la politique agricole commune et des fonds de cohésion pour un pays aussi grand sera au cœur des débats.</p><div class="highlight-box"><p>L'Ukraine, si elle rejoint l'UE, deviendrait le cinquième pays le plus peuplé et le premier producteur agricole de l'Union, redéfinissant profondément l'équilibre politique européen.</p></div>""",

    "organisations-internationales/ong-et-societe-civile": """<h3>L'espace civique sous pression mondiale</h3><p class="resume-text">L'espace d'action des organisations de la société civile se rétrécit dans de nombreuses régions du monde. L'ONG CIVICUS Monitor documente une restriction des libertés d'association, de réunion et d'expression dans 117 pays. Les outils de répression sont variés : lois sur les « agents de l'étranger » (Russie, Géorgie), restrictions du financement étranger (Inde, Égypte, Hongrie), harcèlement judiciaire des militants, surveillance numérique. La militarisation des données personnelles (logiciel Pegasus utilisé contre des journalistes et activistes) représente une menace nouvelle.</p><p class="resume-text">Face à ces pressions, la société civile se <strong>réinvente</strong>. Les mouvements sociaux numériques (#MeToo, Black Lives Matter, Fridays for Future) ont démontré la capacité de mobilisation transnationale sans structure organisationnelle formelle. L'activisme juridique climatique connaît une explosion : plus de 2 500 procès climatiques ont été intentés dans 65 pays depuis 2017, dont l'arrêt historique de la Cour suprême néerlandaise contre le gouvernement (affaire Urgenda, 2019). Ces stratégies juridiques représentent une nouvelle forme d'influence de la société civile sur les politiques publiques.</p><div class="highlight-box"><p>Le mouvement Fridays for Future a inspiré plus de 2 500 procès climatiques dans 65 pays depuis 2017 — un nouveau pouvoir d'influence de la société civile via les tribunaux.</p></div>""",

    "conflits/terrorisme-international": """<h3>L'évolution du terrorisme et les nouvelles menaces</h3><p class="resume-text">Le terrorisme jihadiste a évolué après la défaite territoriale de Daech en Irak et en Syrie (2019). L'organisation a muté en réseau décentralisé, inspirant des « loups solitaires » en Occident plutôt que de diriger des opérations centralisées. Au Sahel, les filiales d'Al-Qaïda (JNIM) et de Daech (EIGS) se disputent le contrôle de territoires abandonnés par les États. L'<strong>Afrique subsaharienne</strong> est devenue l'épicentre du terrorisme mondial : en 2023, 60 % des victimes mondiales du terrorisme étaient africaines, selon le Global Terrorism Index.</p><p class="resume-text">Le <strong>terrorisme d'extrême droite</strong> est la menace croissante dans les pays occidentaux. Les attentats de Christchurch (Nouvelle-Zélande, 2019, 51 morts), d'El Paso (États-Unis, 2019, 23 morts) et de Buffalo (2022, 10 morts) illustrent une idéologie du « Grand Remplacement » qui se diffuse via les réseaux sociaux et les forums en ligne. Les services de renseignement américains et européens considèrent désormais l'extrémisme violent interne comme une menace prioritaire, au même niveau que le terrorisme jihadiste.</p><div class="highlight-box"><p>En 2023, pour la première fois, l'Afrique subsaharienne représentait plus de 60 % des victimes mondiales du terrorisme, devant le Moyen-Orient et l'Asie du Sud.</p></div>""",

    "conflits/droit-humanitaire": """<h3>Droit humanitaire et guerres contemporaines</h3><p class="resume-text">Les conflits contemporains mettent à l'épreuve le droit international humanitaire (DIH) de façon inédite. La guerre en <strong>Ukraine</strong> (2022-) a donné lieu à la plus grande activité judiciaire internationale depuis Nuremberg : la Cour pénale internationale (CPI) a émis un mandat d'arrêt contre Vladimir Poutine pour déportation illégale d'enfants ukrainiens (mars 2023). Des dizaines de milliers de violations présumées font l'objet d'enquêtes. La collecte systématique de preuves numériques (drones, satellites, téléphones) révolutionne la justice pénale internationale.</p><p class="resume-text">La guerre de Gaza (2023-) a engendré un débat mondial sur les limites du droit à la légitime défense et le principe de proportionnalité. L'Afrique du Sud a saisi la Cour internationale de Justice (CIJ) pour génocide contre Israël en janvier 2024 — une première dans l'histoire. La CIJ a ordonné des mesures conservatoires sans qualifier la situation de génocide. Ces procédures judiciaires, même si elles aboutissent rarement à des sanctions, exercent une pression politique et symbolique considérable sur les belligérants.</p><div class="highlight-box"><p>Depuis le conflit en Ukraine, la CPI a reçu plus de 40 demandes de renvoi en deux ans — un record historique qui témoigne de la judiciarisation croissante des conflits.</p></div>""",

    "conflits/resolution-des-conflits": """<h3>Les défis de la paix durable</h3><p class="resume-text">La <strong>consolidation de la paix</strong> après les conflits est souvent aussi difficile que la négociation d'un accord. L'expérience de l'Afghanistan (2001-2021) illustre les limites des missions de paix et de reconstruction : malgré 2 400 milliards de dollars investis par les États-Unis et 20 ans de présence militaire, les Taliban ont repris le pouvoir en deux semaines après le retrait américain. Les études sur les accords de paix montrent que 50 % des conflits rechutent dans les cinq ans suivant la signature d'un traité.</p><p class="resume-text">Les mécanismes de <strong>justice transitionnelle</strong> — commissions vérité-réconciliation, procès, réparations — sont essentiels pour une paix durable. La Commission vérité et réconciliation d'Afrique du Sud (1996-2004), dirigée par Desmond Tutu, est considérée comme un modèle. En Colombie, l'accord de paix de 2016 avec les FARC a créé une Juridiction spéciale pour la paix innovante. En Gambie (depuis 2017), en Tunisie (2014-2017) et au Rwanda (tribunaux gacaca), ces processus ont contribué à reconstruire le tissu social après les atrocités.</p><div class="highlight-box"><p>La Colombie a signé l'accord de paix avec les FARC en 2016 après 52 ans de conflit armé, créant la première juridiction pénale internationale intégrée dans un accord de paix.</p></div>""",

    "traites/droit-des-traites": """<h3>La crise du multilatéralisme et les traités</h3><p class="resume-text">Le multilatéralisme traverse une crise profonde au XXIe siècle. Des États-Unis à la Russie, les retraits unilatéraux d'accords internationaux se multiplient : retrait américain de l'Accord de Paris (2017), du JCPOA nucléaire iranien (2018), du traité sur les forces nucléaires à portée intermédiaire (INF, 2019) ; retrait russe du Conseil de l'Europe (2022), suspension du traité New START (2023). Ces retraits fragilisent les régimes juridiques internationaux construits sur des décennies de négociation.</p><p class="resume-text">Face à ces crises, de nouveaux <strong>instruments juridiques innovants</strong> émergent. Le Traité sur l'interdiction des armes nucléaires (TIAN, 2021), ratifié par 70 États non nucléaires, crée une norme internationale même sans l'adhésion des puissances nucléaires. Le Traité sur la haute mer (BBNJ, 2023), négocié après 20 ans, protège la biodiversité des eaux internationales. Ces traités « asymétriques », portés par des coalitions d'États moyens et d'ONG, représentent une diplomatie normative contournant le veto des grandes puissances.</p><div class="highlight-box"><p>Le Traité sur la haute mer (BBNJ, 2023) protège les deux tiers des océans (eaux internationales) après 20 ans de négociation — la plus grande avancée du droit de la mer depuis la CNUDM de 1982.</p></div>""",

    "traites/desarmement-nucleaire": """<h3>L'état de la prolifération nucléaire aujourd'hui</h3><p class="resume-text">Le <strong>régime de non-prolifération</strong> est sous tension maximale. La Corée du Nord a procédé à 6 essais nucléaires (2006-2017) et possède entre 40 et 60 ogives nucléaires. Les négociations avec Pyongyang ont toutes échoué depuis les accords cadre de 1994. L'Iran, après avoir suspendu sa coopération avec l'AIEA et dépassé les limites du JCPOA, est considéré comme ayant acquis les capacités techniques pour produire une arme nucléaire en quelques semaines (zone seuil). Le TNP, ne prévoyant aucun mécanisme de sanction contraignant, est impuissant face à ces violations.</p><p class="resume-text">Le <strong>risque de guerre nucléaire</strong> est au plus haut depuis la Guerre froide. L'invasion de l'Ukraine a conduit la Russie à des menaces nucléaires explicites, le plus grand usage du chantage nucléaire depuis la crise de Cuba. Le Bulletin of Atomic Scientists a placé l'Horloge de l'Apocalypse à 90 secondes de minuit (2023-2025), le niveau le plus proche du désastre depuis sa création en 1947. La modernisation des arsenaux nucléaires (triade nucléaire américaine : 1 700 milliards de dollars sur 30 ans) relance la course aux armements.</p><div class="highlight-box"><p>En 2025, les neuf États dotés de l'arme nucléaire possèdent environ 12 500 têtes nucléaires, dont 9 600 en stockage opérationnel — le niveau d'alerte le plus élevé depuis 1985.</p></div>""",

    "traites/droits-de-lhomme": """<h3>Droits de l'homme et souverainisme : tensions contemporaines</h3><p class="resume-text">La tension entre souveraineté nationale et universalité des droits de l'homme s'est intensifiée. Le <strong>discours souverainiste</strong> conteste le « droit d'ingérence humanitaire » : des États comme la Chine, la Russie et de nombreux pays du Sud global affirment que les droits de l'homme sont un concept occidental utilisé comme prétexte à l'ingérence. La Chine promeut une conception alternative centrée sur les droits collectifs au développement économique plutôt que sur les libertés individuelles. Ces conceptions rivales s'affrontent dans les enceintes onusiennes.</p><p class="resume-text">La <strong>Cour pénale internationale</strong> (CPI), créée par le Statut de Rome (1998), est l'instrument central de la justice internationale. Elle a inculpé 50 personnes et obtenu 21 condamnations depuis sa création. Mais ses limites sont réelles : les États-Unis, la Russie et la Chine n'en sont pas membres. La CPI est accusée de « justice des vainqueurs » par les États africains, surreprésentés dans les inculpations. L'émission d'un mandat contre Poutine (2023) pour la première fois contre un dirigeant d'une puissance nucléaire permanente du CS a marqué un tournant symbolique majeur.</p><div class="highlight-box"><p>En 2023, la CPI a émis un mandat d'arrêt contre Vladimir Poutine — première fois dans l'histoire qu'un tel acte vise le dirigeant d'un membre permanent du Conseil de sécurité de l'ONU.</p></div>""",

    "traites/droit-international-environnemental": """<h3>L'urgence climatique et la justice environnementale</h3><p class="resume-text">Le <strong>contentieux climatique</strong> est devenu le front le plus dynamique du droit international environnemental. En 2024, l'Assemblée générale de l'ONU a demandé un avis consultatif à la Cour internationale de Justice sur les obligations des États en matière de changement climatique — une première. La Cour interaméricaine des droits de l'homme a pour la première fois reconnu un lien entre droits de l'homme et environnement (2024). Ces décisions, même non contraignantes, créent une jurisprudence internationale et exercent une pression normative considérable.</p><p class="resume-text">Le concept de <strong>dommages et pertes</strong> (loss and damage), reconnu à la COP27 de Charm el-Cheikh (2022), marque une avancée conceptuelle majeure : pour la première fois, les pays développés (principaux émetteurs historiques) reconnaissent une responsabilité financière envers les pays vulnérables qui subissent des dommages climatiques irréversibles. Le fonds créé à cet effet (géré par la Banque mondiale transitoirement) reste sous-capitalisé : 700 millions de dollars promis contre des besoins estimés à 400 milliards par an d'ici 2030.</p><div class="highlight-box"><p>Le Fonds pour les pertes et préjudices climatiques, créé à la COP27 (2022), représente une reconnaissance historique de la responsabilité financière des pays développés envers les victimes du changement climatique.</p></div>""",

    "cooperation/developpement-international": """<h3>L'aide au développement à l'épreuve du XXIe siècle</h3><p class="resume-text">L'<strong>aide publique au développement</strong> (APD) connaît une transformation profonde. Le modèle traditionnel de l'aide conditionnelle aux réformes (ajustement structurel du FMI et de la Banque mondiale dans les années 1980-1990) est remis en cause par les études empiriques qui montrent ses effets négatifs sur les services publics des pays bénéficiaires. Le consensus de Washington a cédé la place à des approches plus diversifiées : investissements dans les infrastructures, transferts conditionnels de revenus, aide budgétaire. L'objectif de 0,7 % du PIB en APD, fixé en 1970, n'est atteint que par cinq pays (Norvège, Suède, Luxembourg, Danemark et Allemagne).</p><p class="resume-text">Les <strong>migrants internationaux</strong> sont devenus les premiers bailleurs de fonds du développement : les transferts de fonds (remittances) ont atteint 800 milliards de dollars en 2022, soit plus du triple de l'APD mondiale. Ces flux, largement sous-taxés et peu réglementés, sont le moteur économique de pays entiers (Haïti : 26 % du PIB, Honduras : 27 %, Tadjikistan : 47 %). La fintech (Wave, M-Pesa) révolutionne les transferts en réduisant les frais de commission de 10 % à moins de 3 %.</p><div class="highlight-box"><p>Les remises d'argent des migrants vers leurs pays d'origine (800 milliards en 2022) représentent trois fois le montant de l'aide publique au développement mondiale et dépassent les investissements directs étrangers dans de nombreux pays.</p></div>""",

    "cooperation/gouvernance-mondiale": """<h3>La gouvernance mondiale face aux défis systémiques</h3><p class="resume-text">La <strong>gouvernance mondiale</strong> souffre d'un déficit de légitimité et d'efficacité face aux enjeux du XXIe siècle. Le G20, créé en 1999, est devenu le principal forum économique mondial mais souffre d'un manque d'institutionnalisation et d'une représentativité imparfaite (l'Afrique n'y avait qu'un seul siège jusqu'à l'entrée de l'Union africaine en 2023). Le G7, regroupant les pays industrialisés traditionnels, voit son poids économique relatif décliner : il représentait 67 % du PIB mondial en 1975, contre 43 % en 2025.</p><p class="resume-text">Les défis <strong>transnationaux</strong> (pandémies, changement climatique, cybersécurité, intelligence artificielle) requièrent une coordination mondiale qui dépasse les capacités des institutions existantes. La réforme du système de Bretton Woods (FMI, Banque mondiale) est demandée par les économies émergentes pour une meilleure représentativité. La gouvernance de l'intelligence artificielle fait l'objet d'une course normative : l'UE a adopté l'AI Act (2024), les États-Unis ont émis des décrets présidentiels, et l'ONU a créé un organe consultatif sur l'IA. La course à la régulation de l'IA est aussi une bataille pour l'influence normative mondiale.</p><div class="highlight-box"><p>L'AI Act européen (2024) est le premier cadre législatif complet sur l'intelligence artificielle au monde, établissant l'Europe comme exportatrice de normes dans la gouvernance mondiale du numérique.</p></div>""",
}


def enrich_content(content: str, extra_html: str) -> str:
    quiz_pattern = r'(<section class="content-section" id="quiz">)'
    match = re.search(quiz_pattern, content)
    if match:
        insert_pos = match.start()
        return content[:insert_pos] + '\n' + extra_html + '\n' + content[insert_pos:]
    else:
        last_section = content.rfind('</section>')
        if last_section >= 0:
            return content[:last_section] + extra_html + '\n' + content[last_section:]
    return content


def main():
    filepath = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json'

    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)

    enriched_count = 0
    for key, enrichment in ENRICHMENTS.items():
        if key in data['pages']:
            page = data['pages'][key]
            if page.get('type') == 'course':
                original_len = len(page['content'])
                page['content'] = enrich_content(page['content'], enrichment)
                new_len = len(page['content'])
                print(f"  {key}: {original_len} -> {new_len} chars (+{new_len - original_len})")
                enriched_count += 1
        else:
            print(f"  WARNING: key not found: {key}")

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nEnriched {enriched_count} articles in relations-internationales.json")


if __name__ == '__main__':
    main()
