#!/usr/bin/env python3
"""Enrich economie pages under 15000 chars."""
import json

PATH = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/economie.json"

with open(PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def inject(key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

inject('macroeconomie/politique-monetaire', """
<h3>Les canaux de transmission de la politique monétaire</h3>
<p class="resume-text">La politique monétaire agit sur l'économie réelle via plusieurs canaux de transmission. Le <strong>canal du taux d'intérêt</strong> est le plus direct : une baisse des taux directeurs réduit le coût du crédit, stimulant l'investissement des entreprises et la consommation à crédit des ménages. Le <strong>canal du crédit</strong> joue via les bilans bancaires : des taux bas augmentent la valeur des actifs des banques, leur permettant d'accorder plus de prêts. Le <strong>canal du taux de change</strong> est important en économie ouverte : des taux bas déprécient la monnaie, stimulant les exportations et renchérissant les importations.</p>
<p class="resume-text">Le <strong>canal des anticipations</strong>, formalisé par les nouveaux keynésiens, est peut-être le plus puissant. Si les agents anticipent que la banque centrale maintiendra des taux bas longtemps, les taux d'intérêt à long terme (qui reflètent la somme des taux courts futurs anticipés) baissent, stimulant l'investissement à long terme. C'est pourquoi la communication des banques centrales (forward guidance) est devenue un outil de politique monétaire à part entière : annoncer que les taux resteront bas « tant que nécessaire » modifie les anticipations et, partant, les comportements économiques actuels.</p>
<div class="highlight-box"><p><strong>Les limites des taux bas :</strong> Quand les taux directeurs atteignent le zéro (zero lower bound, ZLB), la banque centrale ne peut plus les baisser davantage. Pour contourner cette limite, des politiques non conventionnelles ont été développées : assouplissement quantitatif (QE, achat d'actifs à long terme), taux d'intérêt négatifs, et forward guidance. La BCE a pratiqué des taux négatifs de 2014 à 2022, faisant payer les banques pour déposer leurs réserves — incitation à prêter plutôt qu'à épargner.</p></div>

<h3>L'inflation : mesure, causes et conséquences</h3>
<p class="resume-text">L'inflation est mesurée par l'indice des prix à la consommation (IPC), qui suit l'évolution d'un panier représentatif de biens et services. Le déflateur du PIB mesure l'inflation sur l'ensemble de la production nationale. L'inflation sous-jacente (core inflation) exclut les postes volatils (alimentation et énergie) pour mieux capter la tendance de fond. La BCE cible une inflation « proche mais inférieure à 2 % » — niveau jugé compatible avec la stabilité des prix tout en laissant une marge de sécurité contre la déflation.</p>
<p class="resume-text">La théorie quantitative de la monnaie (MV = PT, Fisher) établit une relation de long terme entre masse monétaire et niveau des prix. Dans une version simplifiée, doubler la masse monétaire double les prix à terme. Mais les mécanismes modernes sont plus complexes : l'inflation dépend aussi des anticipations (spirale prix-salaires), des chocs d'offre (hausse du prix du pétrole), et de la structure des marchés (pouvoir de fixation des prix des entreprises). L'inflation de 2021-2023, alimentée par les ruptures de chaînes d'approvisionnement post-COVID et la guerre en Ukraine, illustre que des chocs d'offre peuvent déclencher une inflation persistante indépendamment de la politique monétaire.</p>

<h3>La politique monétaire en économie ouverte : les effets internationaux</h3>
<p class="resume-text">Dans un monde de libre circulation des capitaux, les politiques monétaires nationales ont des effets débordants (spillovers) sur les autres pays. Quand la Fed américaine relève ses taux, les capitaux mondiaux se déplacent vers les États-Unis pour profiter des rendements plus élevés, appréciant le dollar et dépréciant les autres monnaies. Les pays émergents qui empruntent en dollars subissent alors une double peine : leur dette libellée en dollars devient plus chère en monnaie locale, et la fuite des capitaux contracte leur liquidité domestique.</p>
<p class="resume-text">Le « dilemme de la trilogie impossible » (triangle de Mundell) stipule qu'une économie ouverte ne peut simultanément avoir une politique monétaire indépendante, un taux de change fixe et la libre circulation des capitaux — il faut sacrifier l'un des trois. La zone euro a choisi la monnaie unique (taux de change fixe entre membres) et la libre circulation des capitaux, renonçant aux politiques monétaires nationales. Cette configuration accroît la nécessité d'autres mécanismes d'ajustement (mobilité du travail, transferts budgétaires) qui restent insuffisamment développés dans l'UE.</p>
<div class="highlight-box"><p><strong>La crise de 2008 :</strong> La Fed a réduit ses taux de 5,25 % à 0-0,25 % en 15 mois et lancé trois programmes de QE injectant 3 500 milliards de dollars. Ces mesures sans précédent ont évité une dépression mais n'ont pas empêché la « décennie perdue » de croissance lente, soulignant les limites de la politique monétaire seule face à une crise de bilan généralisée.</p></div>

<h3>Les banques centrales numériques (MNBC)</h3>
<p class="resume-text">Les <strong>monnaies numériques de banque centrale</strong> (MNBC, CBDC en anglais) sont des versions numériques de la monnaie centrale, directement accessibles au public sans intermédiaire bancaire. Elles permettraient des paiements instantanés, des politiques de taux d'intérêt négatifs plus efficaces (impossibles à contourner par l'accumulation de cash) et l'inclusion financière des populations non bancarisées. Plus de 130 pays représentant 98 % du PIB mondial explorent des MNBC ; l'e-yuan chinois est le plus avancé avec 250 millions d'utilisateurs actifs.</p>
<p class="resume-text">Les MNBC soulèvent des questions fondamentales de politique économique. Une MNBC qui permet aux citoyens de déposer directement à la banque centrale contournerait les banques commerciales, réduisant leur financement et menaçant le modèle de transformation de maturité qui sous-tend le crédit. Des limites de détention et des taux d'intérêt distincts (pour décourager les dépôts excessifs en MNBC) sont envisagés. La question de la traçabilité des paiements (et donc de la surveillance gouvernementale potentielle) est une préoccupation majeure pour la conception des MNBC des démocraties libérales.</p>
""")

inject('macroeconomie/politique-budgetaire', """
<h3>Les multiplicateurs budgétaires : effets réels des dépenses publiques</h3>
<p class="resume-text">Le multiplicateur budgétaire mesure l'effet d'une dépense publique sur le PIB. Si l'État dépense 1 milliard d'euros, le PIB augmente de k × 1 milliard, où k est le multiplicateur. Dans le modèle keynésien simple, k = 1/(1-c), où c est la propension marginale à consommer : si les ménages consomment 80 % de leur revenu supplémentaire (c = 0,8), k = 5 — chaque euro public génère 5 euros de PIB. Dans la réalité, le multiplicateur dépend crucialement de l'état de l'économie, du régime de politique monétaire et du niveau d'endettement.</p>
<p class="resume-text">Les débats sur les multiplicateurs ont été ravivés par les politiques d'austérité post-2010. Le FMI avait estimé les multiplicateurs à ~0,5 ; ses propres recherches rétrospectives ont révélé qu'ils étaient en réalité ~1,5 pendant la crise — si bien que les coupes budgétaires dans les pays en crise ont contracté l'économie de 1,5 % pour chaque 1 % de PIB réduit, aggravant la dette en proportion du PIB. La Grèce, dont le PIB a reculé de 25 % entre 2008 et 2013, est le cas emblématique de l'austérité auto-défaite.</p>
<div class="highlight-box"><p><strong>La règle d'or budgétaire :</strong> De nombreux pays distinguent dépenses courantes (fonctionnement) et dépenses d'investissement (infrastructures, éducation). La règle d'or budgétaire autorise le déficit pour financer les investissements (dont les bénéfices s'étaleront dans le futur) tout en équilibrant les dépenses courantes — logique économique solide mais difficile à faire respecter politiquement car la distinction entre investissement et fonctionnement est souvent arbitraire dans les comptes publics.</p></div>

<h3>La dette publique : soutenabilité et dynamique</h3>
<p class="resume-text">La soutenabilité de la dette publique dépend de la dynamique entre taux d'intérêt (r) et croissance nominale (g). Si g > r, le ratio dette/PIB se stabilise même avec un déficit primaire modéré — le PIB croît plus vite que la dette. Si r > g, le ratio exploses sans excédent primaire suffisant. Cette condition r < g, longtemps considérée comme exceptionnelle, a prévalu dans la plupart des économies développées de 2010 à 2021, permettant des niveaux de dette élevés sans crise immédiate. Le retour de l'inflation et la hausse des taux depuis 2022 ont durci cette contrainte.</p>
<p class="resume-text">Olivier Blanchard a formalisé une vision plus nuancée de la dette dans son discours présidentiel à l'AEA (2019) : dans un monde où r < g durablement, la dette publique a un coût fiscal nul, voire négatif, et représente une assurance macroéconomique utile. Cette position, controversée, remet en question l'orthodoxie de la réduction de la dette publique à tout prix. La Japan, avec une dette de 260 % du PIB mais des taux proches de zéro et une inflation nulle pendant des décennies, illustre qu'une dette élevée dans une monnaie souveraine avec une banque centrale coopérative peut être soutenable indéfiniment.</p>

<h3>Les finances publiques en période de crise : les stabilisateurs automatiques</h3>
<p class="resume-text">Les <strong>stabilisateurs automatiques</strong> sont des mécanismes budgétaires qui jouent contra-cycliquement sans décision politique : en récession, les recettes fiscales chutent (moins de revenus imposables) et les dépenses sociales augmentent (chômage, aides sociales) automatiquement, soutenant la demande sans action délibérée. En expansion, l'inverse se produit, refroidissant naturellement l'économie. Les pays avec des systèmes de protection sociale développés (Europe du Nord) ont des stabilisateurs plus puissants que les économies à protection minimale (États-Unis).</p>
<p class="resume-text">Le stimulus fiscal de réponse au COVID-19 (2020-2021) a été le plus important depuis la Seconde Guerre mondiale : les États-Unis ont injecté 25 % du PIB en soutiens fiscaux, l'UE 15-20 %. Ces interventions massives ont évité une dépression profonde mais ont aussi contribué à l'inflation de 2021-2023. La rapidité et l'ampleur de la réponse fiscale, facilitée par des taux d'intérêt alors nuls, illustre que la marge de manœuvre budgétaire en temps de crise est beaucoup plus grande que les doctrines d'austérité des années 2010 le suggéraient.</p>
<div class="highlight-box"><p><strong>La théorie monétaire moderne (MMT) :</strong> Développée par Randall Wray et Stephanie Kelton, la MMT soutient que les États disposant d'une monnaie souveraine (comme les États-Unis ou le Royaume-Uni, mais pas la Grèce dans la zone euro) ne peuvent jamais faire défaut sur leur propre monnaie — ils peuvent toujours créer de la monnaie pour payer leurs dettes. La vraie contrainte est l'inflation, pas la solvabilité. Cette vision, marginale mais influente, invite à repenser le rapport à la dette publique dans les pays monétairement souverains.</p></div>

<h3>La politique budgétaire et les inégalités</h3>
<p class="resume-text">La politique fiscale est le principal levier de redistribution. Les <strong>impôts progressifs</strong> (dont le taux augmente avec le revenu) et les transferts sociaux (minima sociaux, allocations chômage, retraites) réduisent les inégalités après redistribution. Dans les pays de l'OCDE, l'impôt et les transferts réduisent le coefficient de Gini (mesure d'inégalité) d'environ un tiers en moyenne. Les États-Unis redistribuent relativement peu (Gini avant redistribution = 0,52, après = 0,39) ; les pays scandinaves redistribuent beaucoup (Gini avant ≈ 0,45, après ≈ 0,26).</p>
<p class="resume-text">L'optimum fiscal de Mirrlees (prix Nobel 1996) résout le compromis entre équité (redistribution maximale) et efficacité (préservation des incitations à travailler et investir). Son modèle prédit un taux marginal d'imposition optimal sur les très hauts revenus qui dépend de l'élasticité de l'offre de travail des riches et de l'aversion sociale aux inégalités — paramètres empiriquement débattus. Les travaux empiriques de Diamond et Saez (2011) suggèrent un taux marginal optimal de 70 % sur les revenus les plus élevés dans les pays développés, ce qui a alimenté le débat politique sur la « tax the rich » de ces dernières années.</p>
""")

inject('finance/banques', """
<h3>La crise de 2008 et la régulation post-crise</h3>
<p class="resume-text">La crise financière de 2008, déclenchée par l'effondrement du marché américain des subprimes, a révélé les failles systémiques du système bancaire mondial. L'interconnexion des banques via les produits dérivés (CDOs, CDS) a transformé une crise immobilière régionale en catastrophe financière mondiale. Lehman Brothers, quatrième banque d'investissement américaine, a fait faillite en septembre 2008 avec 640 milliards de dollars de dettes — la plus grande faillite de l'histoire américaine — provoquant un gel des marchés interbancaires mondiaux et menaçant le système financier mondial d'un effondrement en cascade.</p>
<p class="resume-text">Les accords de <strong>Bâle III</strong> (2010, mis en œuvre progressivement jusqu'en 2028) ont renforcé les exigences de capital, de liquidité et de levier pour les banques systémiques. Le ratio de fonds propres durs (Common Equity Tier 1) a été porté à 4,5 % des actifs pondérés par le risque, avec des coussins supplémentaires pour les banques d'importance systémique mondiale (G-SIBs). Le ratio de liquidité à court terme (LCR) oblige les banques à détenir suffisamment d'actifs liquides pour survivre 30 jours de stress de marché sévère. Ces réformes ont substantiellement renforcé la résilience bancaire, mais le risque systémique a migré en partie vers le secteur bancaire parallèle (shadow banking).</p>
<div class="highlight-box"><p><strong>Too big to fail :</strong> Le renflouement public des grandes banques (bail-out) lors de la crise de 2008 a soulevé un problème d'aléa moral : les banques d'importance systémique savent qu'elles seront sauvées, les incitant à prendre des risques excessifs. La directive européenne BRRD (2014) introduit le bail-in — les actionnaires et créanciers participent aux pertes avant l'État — pour réduire cet aléa moral. La faillite ordonnée de SVB (Silicon Valley Bank, 2023) a testé ces mécanismes avec des résultats mitigés.</p></div>
""")

inject('finance/commerce-international', """
<h3>Les nouvelles tensions du commerce mondial</h3>
<p class="resume-text">Le commerce international connaît depuis 2016 une période de tensions croissantes. La guerre commerciale sino-américaine, lancée par l'administration Trump en 2018, a vu les États-Unis imposer des droits de douane de 25 % sur 250 milliards de dollars d'importations chinoises, et la Chine riposter sur 110 milliards de dollars d'importations américaines. Ces barrières ont réduit les échanges bilatéraux de 25 %, augmenté les prix pour les consommateurs américains et perturbé les chaînes d'approvisionnement mondiales. Les estimations du coût net pour l'économie mondiale varient de 0,5 à 1 % du PIB mondial.</p>
<p class="resume-text">La crise COVID-19 a mis en lumière la vulnérabilité des chaînes d'approvisionnement « juste-à-temps » hyper-mondialisées. La pénurie de semi-conducteurs (2020-2022), qui a coûté 200 milliards de dollars à l'industrie automobile mondiale, et la dépendance pharmaceutique aux API (principes actifs) fabriqués en Asie ont conduit à des politiques de <strong>reshoring</strong> et de nearshoring : le CHIPS Act américain (52 milliards de dollars pour la fabrication domestique de semi-conducteurs) et le European Chips Act (43 milliards d'euros) visent à rapatrier la production stratégique.</p>
<div class="highlight-box"><p><strong>Le paradoxe de la mondialisation :</strong> Malgré ses bénéfices agrégés (réduction de la pauvreté mondiale, gains de spécialisation), la mondialisation a créé des « perdants locaux » importants — ouvriers des industries manufacturières des pays développés concurrencés par les bas salaires asiatiques. La corrélation entre l'exposition aux importations chinoises et le vote populiste dans les counties américains (Autor, Dorn, Hanson) illustre les conséquences politiques d'une mondialisation insuffisamment accompagnée socialement.</p></div>
""")

inject('finance/crypto', """
<h3>La régulation des cryptomonnaies : un défi mondial</h3>
<p class="resume-text">L'écosystème des cryptomonnaies, valorisé à plus de 2 000 milliards de dollars au pic de 2021, a opéré dans un vide réglementaire qui a favorisé les abus : fraudes, Ponzi, manipulation de marché et blanchiment d'argent. L'effondrement de FTX en novembre 2022 — la deuxième plateforme d'échange mondiale, valorisée 32 milliards de dollars en janvier 2022 et en faillite frauduleuse 10 mois plus tard — a cristallisé les appels à la régulation. Sam Bankman-Fried a été condamné à 25 ans de prison pour détournement de 8 milliards de dollars de fonds clients.</p>
<p class="resume-text">L'Union européenne a adopté le règlement <strong>MiCA</strong> (Markets in Crypto-Assets, 2023), premier cadre réglementaire complet au monde pour les cryptoactifs. Il impose des exigences de capital, de gouvernance et de transparence aux émetteurs de tokens et aux prestataires de services d'actifs numériques. Les stablecoins adossés à des monnaies fiat (USDT, USDC) sont soumis aux règles les plus strictes, requérant une réserve de 1:1 en actifs liquides. Les États-Unis restent en retard réglementaire, avec une bataille de compétence entre SEC et CFTC sur la classification des cryptoactifs.</p>
<p class="resume-text">La technologie blockchain sous-jacente, indépendamment de sa valeur spéculative, présente des applications potentielles dans les contrats intelligents (smart contracts, Ethereum), la traçabilité des chaînes d'approvisionnement, les titres de propriété dans les pays sans registres fiables, et les systèmes de vote électronique résistants à la manipulation. Les <strong>NFT</strong> (tokens non fongibles) ont connu une bulle spéculative fulminante en 2021 (69 millions de dollars pour un JPEG de Beeple) avant un effondrement de 95 % du marché en 2022 — illustration classique d'une bulle d'actifs dans un actif sans valeur intrinsèque claire.</p>
<div class="highlight-box"><p><strong>Bitcoin et environnement :</strong> Le minage de Bitcoin consomme annuellement autant d'électricité que certains pays (150 TWh/an, comparable à la Pologne). Cette consommation massive est structurelle — inhérente au mécanisme de preuve de travail (PoW). L'Ethereum a migré vers la preuve d'enjeu (PoS) en septembre 2022 (The Merge), réduisant sa consommation énergétique de 99,95 %. Cette transition illustre que des choix de conception alternatifs peuvent réconcilier cryptomonnaies et contraintes environnementales.</p></div>
""")

print("Economie pages enriched:")
short_keys = ['macroeconomie/politique-monetaire','macroeconomie/politique-budgetaire','finance/banques','finance/commerce-international','finance/crypto']
for key in short_keys:
    print(f"  {key}: {len(pages[key]['content'])} chars")

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved.")
