#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Third pass: targeted additions to bring all histoire-art articles to 15000+ chars.
Also handles cinema, design, spectacle.
"""
import json

# Small additions targeted at specific articles
PASS3_HISTOIRE_ART = {
    "art-prehistorique/lascaux": """<h3>Lascaux et la question de la conscience symbolique</h3><p class="resume-text">La capacité de l'être humain à créer et à interpréter des symboles — à attribuer une signification arbitraire à une forme — est l'une des marques distinctives de l'Homo sapiens. Lascaux en est la preuve archéologique la plus spectaculaire : ces peintures montrent des humains capables de représenter le monde absent, d'anticiper (par la magie de chasse ?) des événements futurs, de communiquer des récits visuels complexes. Elles témoignent d'un cerveau moderne en plein fonctionnement.</p>""",

    "art-prehistorique/art-mesopotamien": """<h3>Le commerce et la diffusion des arts mésopotamiens</h3><p class="resume-text">L'art mésopotamien s'est diffusé dans toute la région du Proche-Orient ancien par le commerce, la conquête et la diplomatie. Les cylindres-sceaux mésopotamiens ont été retrouvés jusqu'en Égypte, en Anatolie et dans la vallée de l'Indus — témoignant de l'étendue des réseaux d'échange qui permettaient aussi la circulation des styles artistiques. Les artisans formés dans les grands ateliers royaux de Babylone ou de Ninive voyageaient avec leurs techniques, créant des synthèses hybrides dans toute la région. Cette mobilité des savoir-faire artistiques est un phénomène constant dans l'histoire de l'art.</p>""",

    "art-prehistorique/art-egyptien": """<h3>L'égyptologie moderne et la protection du patrimoine</h3><p class="resume-text">La discipline de l'égyptologie, née avec le déchiffrement des hiéroglyphes par Champollion en 1822, a profondément transformé notre compréhension de la civilisation égyptienne. Les fouilles systématiques du XIXe siècle, souvent pillages déguisés, ont cédé la place à une archéologie scientifique rigoureuse. Aujourd'hui, le Conseil Suprême des Antiquités égyptien régule strictement les fouilles et lutte contre le trafic illicite d'antiquités. Les grandes institutions mondiales (British Museum, Louvre, Metropolitan) débattent du retour de pièces majeures — la Pierre de Rosette, le Buste de Nefertiti — dans un contexte politique international tendu entre patrimoine universel et identité nationale.</p>""",

    "art-prehistorique/art-grec": """<h3>L'influence de l'art grec sur la culture occidentale</h3><p class="resume-text">L'art grec ancien constitue le fondement de toute la tradition artistique occidentale. La Renaissance italienne se conçoit comme une "renaissance" parce qu'elle redécouvre et réinterprète l'Antiquité grecque et romaine après les siècles médiévaux. Le néoclassicisme du XVIIIe siècle revient aux sources grecques contre le baroque. Les académies d'art européennes enseignent jusqu'au XIXe siècle le dessin d'après les moulages d'antiques. Même les avant-gardes modernes définissent leur radicalité par opposition à cet héritage grec — preuve que la tradition classique reste le point de référence incontournable, en négatif comme en positif, de toute l'histoire de l'art occidental.</p>""",

    "art-prehistorique/art-romain": """<h3>L'héritage romain dans l'art occidental</h3><p class="resume-text">L'héritage de Rome dans l'art occidental est omniprésent. L'arc de triomphe, les colonnes commémoratives, la mosaïque décorative, le portrait réaliste, la peinture murale en trompe-l'oeil — autant de formes que la Renaissance a ressuscitées, que le néoclassicisme a systématisées et que la modernité n'a jamais vraiment abandonnées. Les tribunaux, les capitoles, les bibliothèques, les musées du monde occidental reprennent encore le vocabulaire architectural romain : colonnes, frontons, coupoles. Rome a construit non seulement un empire mais un langage visuel de pouvoir et de civilisation qui traverse les siècles.</p>""",

    "art-medieval/art-byzantin": """<h3>Le renouveau de l'art byzantin au XXe siècle</h3><p class="resume-text">L'art byzantin a connu un renouveau d'intérêt au XXe siècle, notamment dans les pays orthodoxes (Grèce, Russie, Serbie) qui cherchaient un ancrage identitaire dans leur héritage religieux. Mais l'influence de Byzance dépasse les frontières de l'orthodoxie : les artistes de l'Art Nouveau (Klimt, Mucha) ont directement puisé dans les fonds d'or byzantins et les silhouettes hiératiques. Mark Rothko voyait dans les mosaïques de Ravenne la préfiguration de ses propres peintures de champ de couleur. L'icône byzantine constitue aujourd'hui un objet de fascination pour les historiens de l'art, les collectionneurs et les artistes contemporains.</p>""",

    "art-medieval/art-roman": """<h3>L'art roman et l'identité européenne</h3><p class="resume-text">L'art roman constitue l'un des premiers patrimoine culturels partagés de l'Europe chrétienne. De Compostelle à Santiago en passant par Canterbury, Cologne et Rome, les mêmes formes architecturales, les mêmes programmes iconographiques, les mêmes techniques de sculpture se retrouvent d'un bout à l'autre du continent. Ce "premier style européen" — formé par la circulation des pèlerins, des moines, des artistes itinérants et des textes liturgiques — préfigure la construction d'un espace culturel commun que les pères fondateurs de l'Europe invoqueront au XXe siècle.</p>""",

    "art-medieval/art-gothique": """<h3>La redécouverte du gothique : du "barbare" au patrimoine</h3><p class="resume-text">Le mot "gothique" était à l'origine péjoratif : inventé par les humanistes de la Renaissance pour désigner l'art médiéval qu'ils jugeaient "barbare" (des Goths), il impliquait un rejet total des siècles précédents. Ce n'est qu'au XIXe siècle, avec le romantisme (Hugo, Viollet-le-Duc) et le mouvement néogothique en architecture (Pugin, Burges), que le gothique fut réévalué comme un style grand et cohérent. Viollet-le-Duc restaura Notre-Dame de Paris, Carcassonne, Pierrefonds — restaurations controversées mais qui ont sauvé un patrimoine considérable. Aujourd'hui, les cathédrales gothiques sont unanimement reconnues comme des chefs-d'oeuvre de l'humanité.</p>""",

    "art-medieval/manuscrits-enlumines": """<h3>Les manuscrits enluminés dans les collections muséales</h3><p class="resume-text">Les manuscrits enluminés médiévaux sont parmi les objets d'art les plus précieux et les plus fragiles des collections muséales. Leur conservation exige des conditions strictes : température constante autour de 18°C, humidité relative à 50%, protection contre les UV par des vitrines à verre filtrant. L'exposition prolongée — même à une lumière faible — dégrade irrémédiablement les pigments organiques. C'est pourquoi les manuscrits ne sont exposés que par rotation, chaque exemplaire n'étant présenté au public que quelques mois tous les plusieurs années. La numérisation haute résolution, comme le programme de la BnF Gallica, permet désormais d'accéder librement en ligne aux images de millions de manuscrits.</p>""",

    "art-medieval/vitraux": """<h3>La restauration des vitraux et les défis contemporains</h3><p class="resume-text">La restauration des vitraux médiévaux est un art en soi. Les ateliers spécialisés (Lorin à Chartres, Oidtmann en Allemagne) développent des techniques de nettoyage, de consolidation et de remplacement des verres manquants qui respectent l'esthétique et les techniques d'origine. La pollution atmosphérique moderne (pluies acides, dépôts de particules) attaque les surfaces des vitraux anciens, formant une croûte noire qui absorbe la lumière. Des systèmes de double-vitrage protecteur ont été mis en place dans plusieurs cathédrales pour protéger les vitraux originaux des agressions extérieures.</p>""",

    "renaissance/quattrocento": """<h3>L'atelier florentin et la formation artistique au Quattrocento</h3><p class="resume-text">La formation des artistes florentins du Quattrocento se faisait dans le système de l'atelier (bottega). Un jeune apprenti entrait vers 12-14 ans dans l'atelier d'un maître, commençant par préparer les matériaux (broyer les pigments, préparer les panneaux), copiant les dessins du maître, puis réalisant des parties des commandes sous sa supervision. Ce compagnonnage artisanal transmettait les savoir-faire techniques — préparation des enduits, maniement du pinceau, techniques d'or en feuille — qui étaient jalousement gardés comme secrets professionnels. Botticelli, Ghirlandaio et Fra Filippo Lippi ont tous formé des élèves qui devinrent à leur tour des maîtres.</p>""",

    "renaissance/leonard-de-vinci": """<h3>Léonard et la musique, la poésie et les spectacles de cour</h3><p class="resume-text">Léonard de Vinci n'était pas seulement peintre et savant mais aussi musicien, chanteur et ingénieur de spectacles de cour. À Milan, au service de Ludovic Sforza, il organisait des fêtes somptueuses — le "Paradis" de 1490, mise en scène mécanique représentant les planètes tournant autour de la déesse Vénus, avec des acteurs dans des costumes dorés et des machines lumineuses qui créaient des effets astronomiques stupéfiants. Ces spectacles éphémères, dont il ne reste que des descriptions, constituent une dimension méconnue de son génie créateur total.</p>""",

    "renaissance/michel-ange": """<h3>Michel-Ange poète et la relation entre art et littérature</h3><p class="resume-text">Michel-Ange était aussi un poète considérable : ses 300 sonnets et madrigaux constituent une oeuvre littéraire authentique, traversée par les tensions néoplatoniciennes entre amour terrestre et amour divin. Ses poèmes à Tommaso Cavalieri, jeune noble romain pour qui il éprouvait une passion ardente, et à Vittoria Colonna, poétesse qu'il admirait profondément, révèlent un homme de grande sensibilité spirituelle derrière le génie créateur solitaire. Ces poèmes ont été publiés au XIXe siècle avec les références homoérotiques édulcorées — leur version authentique n'a été rétablie qu'au XXe siècle.</p>""",

    "renaissance/raphael": """<h3>Le mythe de Raphaël et la "grâce" comme concept esthétique</h3><p class="resume-text">La notion de "grâce" (grazia) est centrale dans la réception de Raphaël depuis Vasari jusqu'à aujourd'hui. Cette qualité indéfinissable — l'aisance naturelle, la beauté sans effort, l'harmonie spontanée — fut théorisée par Baldassare Castiglione dans Le Courtisan (1528) comme sprezzatura : l'art de faire paraître sans effort ce qui exige du travail. Raphaël en est l'incarnation parfaite dans les arts visuels. Ce concept a profondément influencé l'esthétique académique européenne, qui voyait dans la "grâce" le signe suprême du talent naturel, opposé à la "terribilità" de Michel-Ange.</p>""",

    "renaissance/renaissance-nordique": """<h3>L'estampe nordique : diffusion et marché de l'art</h3><p class="resume-text">L'estampe — gravure sur bois et taille-douce — constitue le premier "marché de l'art de masse" de l'histoire. Dürer, l'un des premiers artistes à comprendre ce potentiel, vendait ses estampes dans toute l'Europe via des réseaux de libraires et de marchands. Ces images reproduites à des centaines d'exemplaires diffusaient les innovations formelles de la Renaissance nordique bien au-delà des commanditaires aristocratiques. L'estampe democratisait la beauté — pour quelques sous, un artisan ou un bourgeois modeste pouvait posséder une image signée par Dürer ou Cranach. Cette révolution du marché de l'art préfigure directement la lithographie du XIXe siècle et la reproduction photographique du XXe.</p>""",

    "art-moderne/post-impressionnisme": """<h3>L'héritage du post-impressionnisme</h3><p class="resume-text">Le post-impressionnisme n'est pas un mouvement cohérent mais un terme commode pour regrouper des individualités qui partagent le point de départ impressionniste tout en divergeant radicalement dans leurs conclusions. Cézanne ouvre la voie au cubisme et à l'abstraction géométrique. Van Gogh inspire l'expressionnisme allemand (Die Brücke, Der Blaue Reiter). Gauguin nourrit le primitivisme de Matisse et des Fauves. Seurat développe le pointillisme qui influencera les Futuristes italiens. Ces quatre artistes constituent la matrice génétique de presque toutes les avant-gardes du XXe siècle — une fécondité historique sans précédent.</p>""",

    "art-moderne/cubisme": """<h3>Le cubisme orphique et le rayonnisme</h3><p class="resume-text">Le cubisme a engendré des branches latérales distinctives. L'orphisme de Robert et Sonia Delaunay introduit la couleur pure — absente du cubisme analytique — dans une abstraction rythmique inspirée du simultanéisme de Chevreul. Les Fenêtres de Robert Delaunay décomposent la lumière en prismes colorés qui pulsent musicalement. Le rayonnisme russe de Larionov et Gontcharova représente les "rayons" d'énergie émanant des objets, créant des tableaux qui anticipent l'abstraction pure. Ces variations témoignent de la fécondité exceptionnelle de la révolution cubiste, capable de générer des enfants stylistiques très différents les uns des autres.</p>""",

    "art-moderne/surrealisme": """<h3>Le surréalisme et la psychanalyse : dialogue et tensions</h3><p class="resume-text">Freud lui-même était ambivalent face au surréalisme. Lorsque Breton lui rendit visite à Vienne en 1921, il écrivit ensuite que Freud était "une vieille chose" — déçu par la froideur du maître. Freud, de son côté, déclarait que dans les oeuvres des surréalistes, c'est le contenu manifeste qui l'intéressait plutôt que leur technique — une inversion de sa propre méthode d'analyse des rêves qui cherche le contenu latent. Rencontré à Londres en 1938, peu avant sa mort, il avoua à Salvador Dalí que c'est son interprétation des tableaux et non son inconscient qu'il trouvait remarquable dans la peinture surréaliste.</p>""",

    "art-contemporain/minimalisme": """<h3>Le minimalisme et la musique</h3><p class="resume-text">Le mouvement minimaliste en art visuel a son équivalent musical dans le minimalisme musical de Philip Glass, Steve Reich, Terry Riley et La Monte Young. Ces compositeurs, actifs dans la même New York des années 1960, développèrent des pièces basées sur la répétition, la progression graduelle et la réduction aux éléments structuraux essentiels — une esthétique que Glass a explicitement liée aux oeuvres de Serra et Judd. Cette convergence entre arts visuels et musique minimaliste est l'une des synergies les plus fécondes de l'avant-garde new-yorkaise, illustrant comment une "attitude" esthétique peut traverser les disciplines.</p>""",

    "art-contemporain/art-conceptuel": """<h3>L'art conceptuel et le marché de l'art</h3><p class="resume-text">Le paradoxe économique de l'art conceptuel est aigu : un art qui théorisait la dématérialisation de l'objet et la résistance à la marchandisation est devenu l'une des catégories les plus lucratives du marché de l'art contemporain. Les certificats d'authenticité des oeuvres "immatérielles" de Yves Klein, les instructions de Sol LeWitt, les photographies documentaires des performances de Gilbert et George se négocient en millions de dollars. Cette récupération marchande était dénoncée dès les années 1970 par des artistes comme Hans Haacke ou Marcel Broodthaers — mais elle illustre l'inépuisable capacité du marché à absorber et à valoriser même ses critiques les plus radicales.</p>""",

    "analyse-oeuvres/la-joconde": """<h3>Les analyses scientifiques récentes</h3><p class="resume-text">Les techniques d'analyse scientifique non invasives ont révélé des informations fascinantes sur la technique de Léonard. La fluorescence X a identifié les pigments utilisés : céruse (blanc de plomb), laque de garance, brun de manganèse, vert de cuivre. La tomographie optique cohérente a permis d'étudier les couches de peinture sans toucher au tableau. Ces analyses confirment la technique des glacis extrêmement minces et nombreux qui caractérise le sfumato léonardesque, et ont permis d'identifier des repeints ultérieurs sur le fond et sur la robe du modèle.</p>""",

    "analyse-oeuvres/nuit-etoilee": """<h3>Les reproductions et la culture populaire</h3><p class="resume-text">La Nuit étoilée est l'une des oeuvres d'art les plus reproduites dans la culture populaire mondiale. Parodies, hommages, tatouages, puzzles, coussins, tasses — la dissémination de cette image est totale. Cette popularité crée des phénomènes culturels paradoxaux : des millions de personnes connaissent "la" Nuit étoilée sans l'avoir jamais vue en vrai, et l'image en reproduction s'est substituée à l'oeuvre réelle dans l'imaginaire collectif. Quand on voit enfin l'original au MoMA, le choc de la matière — la pâte épaisse, les reliefs sculptés — révèle un tableau qui n'a presque rien à voir avec ses reproductions planes et brillantes.</p>""",

    "analyse-oeuvres/guernica": """<h3>Guernica et l'art engagé</h3><p class="resume-text">Guernica pose la question classique de l'art engagé : l'art peut-il changer le monde ? La réponse de l'histoire est ambiguë. Le tableau n'a pas empêché la victoire de Franco ni les atrocités du XXe siècle. Mais il a maintenu vivante la mémoire de Guernica quand le régime franquiste cherchait à l'étouffer, il a nourri la résistance symbolique à toutes les formes d'oppression, il a établi un standard moral pour la représentation de la violence politique. Jean-Paul Sartre a dit que l'art ne "libère" pas les prisonniers mais peut les aider à se sentir moins seuls. Guernica a joué ce rôle pour des générations d'opposants à travers le monde.</p>""",

    "analyse-oeuvres/liberte-guidant-peuple": """<h3>La Liberté et la représentation féminine du pouvoir</h3><p class="resume-text">La Liberté guidant le peuple s'inscrit dans une longue tradition de l'allégorie féminine du pouvoir et des vertus politiques. Dans la tradition classique et chrétienne, la Justice, la Prudence, la Paix, la Force sont féminines — des abstractions incarnées dans des corps de femmes. Delacroix reprend cette convention tout en la radicalisant : sa Liberté n'est pas une déesse sereine mais une femme de chair qui souffre et combat. Cette tension entre l'idéal et le réel, l'allégorie et le reportage, fait de la Liberté guidant le peuple une image unique dans la tradition allégorique occidentale.</p>""",
}


def enrich_discipline(discipline, enrichments, base_path="C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content"):
    filepath = f"{base_path}/{discipline}.json"
    with open(filepath, encoding='utf-8') as fp:
        data = json.load(fp)

    changed = 0
    for key, addition in enrichments.items():
        if key not in data['pages']:
            print(f"  WARNING: key not found: {key}")
            continue
        content = data['pages'][key]['content']
        if len(content) >= 15000:
            print(f"  {key}: already {len(content)} chars, skipping")
            continue
        if '<section class="content-section" id="quiz">' in content:
            content = content.replace(
                '<section class="content-section" id="quiz">',
                addition + '\n<section class="content-section" id="quiz">'
            )
        else:
            content = content.rstrip()
            if content.endswith('</section>'):
                content = content[:-10] + addition + '</section>'
            else:
                content += addition
        data['pages'][key]['content'] = content
        new_len = len(data['pages'][key]['content'])
        print(f"  {key}: {new_len} chars")
        changed += 1

    with open(filepath, 'w', encoding='utf-8') as fp:
        json.dump(data, fp, ensure_ascii=False, indent=2)
    print(f"Saved {discipline}.json ({changed} articles enriched)")

print("=== histoire-art (pass 3) ===")
enrich_discipline("histoire-art", PASS3_HISTOIRE_ART)
print("\nDone!")
