#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Second pass: brings histoire-art articles to 15000+ chars.
Also enriches cinema, design, spectacle.
"""
import json
import sys

ENRICHMENTS_PASS2 = {
    "histoire-art": {
        "art-prehistorique/lascaux": """<h3>Comparaisons internationales et art pariétal mondial</h3><p class="resume-text">Lascaux s'inscrit dans un phénomène mondial de l'art pariétal paléolithique. En Espagne, Altamira (découverte en 1879) avait été la première grotte ornée authentifiée, mais le monde académique refusa de croire à son antiquité pendant des décennies — un scientifique amateur ne pouvait pas avoir raison contre les professeurs. L'acceptation d'Altamira ouvrit ensuite la voie à la reconnaissance de Lascaux. La grotte de Chauvet (découverte en 1994 par Jean-Marie Chauvet) révèle des peintures datées de 36 000 ans, soit le double de l'âge de Lascaux, d'une sophistication technique égale — remettant en cause toute théorie d'évolution progressive.</p><p class="resume-text">L'art rupestre existe sur tous les continents habités par l'homme préhistorique. En Australie, les peintures des Aborigènes à Murujuga (Burrup Peninsula) datent de plus de 40 000 ans. En Afrique du Sud, les gravures de Blombos Cave et les peintures de Sibhudu atteignent 75 000 ans. Ces découvertes suggèrent que la capacité symbolique de l'Homo sapiens est apparue bien avant la migration vers l'Europe — peut-être dès l'émergence de l'espèce en Afrique il y a 300 000 ans.</p><div class="highlight-box"><p>La représentation d'une main en négatif — obtenue par soufflage de pigment autour d'une main posée sur la paroi — est universelle dans l'art préhistorique mondial : on la trouve à Lascaux, Altamira, Chauvet, mais aussi en Patagonie, Australie, Bornéo. Ce geste universel ("J'étais là, regardez") semble être la première expression artistique de l'humanité.</p></div>""",

        "art-prehistorique/art-mesopotamien": """<h3>L'écriture cunéiforme et la naissance de la communication visuelle</h3><p class="resume-text">Le cunéiforme, inventé en Mésopotamie vers 3200 av. J.-C., est intrinsèquement un art visuel avant d'être un système d'écriture. Les premiers signes sont des pictogrammes — représentations schématiques d'objets (tête de boeuf, poisson, grain d'orge) incisés dans l'argile avec un roseau taillé. L'évolution vers l'abstraction (les signes cunéiformes proprement dits) est un processus artistique de stylisation progressive. La belle écriture (calligraphie cunéiforme) était une compétence artistique valorisée par les scribes.</p><p class="resume-text">Les cylindres-sceaux mésopotamiens sont des chefs-d'oeuvre miniatures. Ces rouleaux de pierre dure (lapis-lazuli, calcédoine, jaspe), de 2 à 5 cm de haut, portent des scènes gravées en creux qui produisent à l'impression des images positives sur l'argile. Des milliers de ces sceaux ont été retrouvés, constituant une source iconographique exceptionnelle sur la mythologie, la vie de cour et les pratiques commerciales. La précision du travail, réalisé avec un foret de cuivre et des abrasifs, témoigne d'une maîtrise technique remarquable à l'échelle microscopique.</p><div class="highlight-box"><p>L'épopée de Gilgamesh, le plus ancien récit littéraire connu (environ 2100 av. J.-C.), relate un roi historique d'Uruk qui cherche l'immortalité après la mort de son ami Enkidu. Ce texte anticipe des thèmes bibliques (le déluge) et pose des questions existentielles — la mort, l'amitié, la gloire — que la peinture et la sculpture mésopotamiennes illustrent dans un dialogue permanent entre texte et image.</p></div>""",

        "art-prehistorique/art-egyptien": """<h3>L'art égyptien et son influence sur les civilisations suivantes</h3><p class="resume-text">L'art égyptien a exercé une influence considérable sur les civilisations qui lui ont succédé en Méditerranée. Les Grecs archaïques ont directement emprunté aux Égyptiens la statue colossale debout (kouros), la tradition des reliefs narratifs et certains motifs décoratifs (lotus, palmette, sphinx). Les Étrusques importèrent des objets égyptiens et produisirent des scarabées en imitation. Rome développa un véritable "égyptomanie" après la conquête par César en 47 av. J.-C. : des obélisques furent transportés à Rome, des temples isiaques construits, et les motifs égyptiens envahirent l'art décoratif.</p><p class="resume-text">La redécouverte de l'art égyptien par l'expédition de Bonaparte (1798-1801) a provoqué une deuxième vague d'égyptomanie en Europe. La Description de l'Égypte (1809-1828), publication monumentale de 23 volumes illustrés, mit à la disposition des artistes et architectes européens un répertoire iconographique inépuisable. Le néo-égyptien devint un style architectural à part entière, visible dans les pyramides funéraires, les obélisques de parcs urbains et les décors de théâtres du XIXe siècle.</p><div class="highlight-box"><p>Le déchiffrement des hiéroglyphes par Champollion en 1822, à partir de la Pierre de Rosette (qui présente le même texte en hiéroglyphes, démotique et grec), a ouvert l'accès à 3 000 ans de textes égyptiens restés illisibles. Pour la première fois, les inscriptions accompagnant les oeuvres d'art égyptien purent être lues — révélant une civilisation bien plus complexe que les voyageurs avaient imaginé.</p></div>""",

        "art-prehistorique/art-grec": """<h3>La peinture grecque perdue et son influence sur Rome</h3><p class="resume-text">La quasi-totalité de la grande peinture grecque a disparu. Nous la connaissons par les descriptions des auteurs anciens (Pline l'Ancien, Pausanias) et surtout par les copies romaines. Apelle, peintre officiel d'Alexandre le Grand, est décrit comme un virtuose du portrait psychologique et des effets atmosphériques. Son Aphrodite Anadyomène, représentant la déesse émergeant de la mer, fut achetée par Auguste pour une somme équivalente à la rançon d'une ville entière. Zeuxis aurait peint des raisins si réalistes que les oiseaux venaient les picorer — anecdote qui illustre l'idéal grec de la mimesis (imitation parfaite du réel).</p><p class="resume-text">L'influence de l'art grec sur Rome est si totale que les historiens parlent d'"art gréco-romain" comme d'une continuité. Après la conquête de la Grèce (146 av. J.-C.), des milliers d'oeuvres grecques originales furent transportées à Rome. Les grands sculpteurs et peintres grecs s'installèrent en Italie pour travailler pour des mécènes romains. Les ateliers romains produisirent des copies en marbre de statues grecques originales en bronze — c'est pourquoi nous connaissons la plupart des chefs-d'oeuvre grecs seulement à travers leurs copies romaines.</p><div class="highlight-box"><p>L'Élgin Marbles — les sculptures du Parthénon arrachées par Lord Elgin en 1801-1812 et conservées au British Museum — sont au coeur d'un débat contemporain sur le retour des biens culturels. La Grèce réclame leur restitution depuis les années 1980. Ce débat illustre comment le patrimoine antique continue de structurer les relations entre nations.</p></div>""",

        "art-prehistorique/art-romain": """<h3>L'art romain tardif et les prémices de l'art byzantin</h3><p class="resume-text">L'art romain tardif (IIIe-Ve siècles ap. J.-C.) opère une transition stylistique fondamentale vers l'art médiéval. Les portraits des empereurs de la Tétrarchie (vers 300 ap. J.-C.) abandonnent le naturalisme classique pour une stylisation géométrique : visages schématiques, regards fixes, corps massifs — une esthétique que l'historien de l'art Riegl a appelée la Kunstwollen (volonté d'art) de l'Antiquité tardive, non plus un art décadent mais un art nouveau répondant à d'autres exigences symboliques.</p><p class="resume-text">L'arc de Constantin (315 ap. J.-C.) illustre cette transition en mêlant des reliefs "remployés" de Trajan, Hadrien et Marc Aurèle (IIe siècle, style naturaliste) à de nouveaux reliefs constantins (style frontalisé, figures schématiques, hiérarchie de taille). Le contraste est saisissant : pas de la "décadence" mais deux esthétiques radicalement différentes répondant à des visions du monde différentes. L'art romain tardif prépare directement l'art byzantin et l'art roman médiéval.</p><div class="highlight-box"><p>La mosaïque d'Aquilée (IVe siècle ap. J.-C.), découverte sous la basilique d'Aquilée, montre la transition de l'art romain à l'art paléochrétien : des scènes de pêche et des motifs marins typiquement romains côtoient des symboles chrétiens (le poisson comme signe du Christ), illustrant comment les premiers chrétiens réutilisèrent le vocabulaire visuel romain pour exprimer leur foi nouvelle.</p></div>""",

        "art-medieval/art-byzantin": """<h3>L'iconostase et l'espace sacré byzantin</h3><p class="resume-text">L'iconostase est la cloison d'images séparant le sanctuaire (réservé au clergé) de la nef (ouverte aux fidèles) dans l'Église orthodoxe. Constituée de rangées d'icônes disposées selon un ordre théologique précis, l'iconostase est une "bible en images" — de la Déèsis (Christ en majesté entre la Vierge et saint Jean-Baptiste) aux icônes des fêtes liturgiques et des saints locaux. Cette barrière sacrée articule la séparation et la communication entre monde humain et monde divin.</p><p class="resume-text">L'art byzantin survécut à la chute de Constantinople en 1453 grâce aux Balkans, à la Russie et à l'Église copte d'Égypte. La peinture d'icônes russe atteint ses sommets avec Andreï Roublev (vers 1360-1430), dont la Trinité (vers 1411, galerie Tretiakov, Moscou) est considérée comme l'icône la plus parfaite jamais peinte. La composition en cercle des trois anges, la palette douce de bleus et de rose, la sérénité de l'expression — tout crée une harmonie contemplative d'une profondeur spirituelle exceptionnelle.</p><div class="highlight-box"><p>L'icône de la Sainte Face de Novgorod (XIIe siècle) montre le visage du Christ "non fait de main d'homme" (acheiropoïète). Selon la tradition, ces icônes n'étaient pas peintes par des artistes humains mais apparues miraculeusement — une croyance qui exprime l'aspiration à une image directement divine, sans médiation artistique humaine.</p></div>""",

        "art-medieval/art-roman": """<h3>L'art roman hors de France : Allemagne, Espagne, Italie</h3><p class="resume-text">L'art roman est un phénomène pan-européen qui présente des variantes régionales distinctes. En Allemagne rhénane, la sculpture de la cathédrale de Worms et les bronzes de Hildesheim (dont les portes commandées par l'évêque Bernward, vers 1015) témoignent d'une tradition de travail du métal d'une extraordinaire qualité. L'émaillerie mosane (région de la Meuse) produit des reliquaires et des autel portables d'un raffinement inégalé en Europe du Nord.</p><p class="resume-text">En Espagne, l'art roman se développe sous la double influence du pèlerinage de Compostelle et des contacts avec l'art islamique andalou. Les peintures murales des Pyrénées catalanes (Sant Climent de Taüll, Santa Maria de Taüll, vers 1123) constituent l'un des ensembles de peinture murale romane les mieux conservés du monde. Déposées au début du XXe siècle pour les protéger et transférées au Musée National d'Art de Catalogne, elles montrent un style d'une expressivité intense, aux couleurs vives et aux cernes noirs — parfois comparé aux icônes byzantines.</p><div class="highlight-box"><p>Le "Pantocrator" de Sant Climent de Taüll (vers 1123), aujourd'hui au MNAC de Barcelone, est l'une des images médiévales les plus reproduites. Le Christ en majesté dans une mandorle, entouré des symboles des évangélistes, regarde le fidèle d'un regard frontal d'une autorité saisissante — une image qui a traversé l'histoire de l'art roman pour nourrir l'expressionnisme du XXe siècle.</p></div>""",

        "art-medieval/art-gothique": """<h3>Le gothique international et la fin du Moyen Âge</h3><p class="resume-text">Le gothique international (vers 1380-1420) est un style de cour cosmopolite qui circule entre les grandes capitales princières d'Europe — Paris, Prague, Milan, Florence, Bourges. Il se caractérise par l'élégance des silhouettes allongées, la richesse des décors, la préciosité des matières (or, lapis-lazuli, émaux), la représentation de la nature avec une attention aux détails botaniques et zoologiques jamais vue auparavant. Ce style de luxe est porté par les grands mécènes — Jean de Berry, Gian Galeazzo Visconti, Wenceslas IV de Bohême.</p><p class="resume-text">Les Très Riches Heures du duc de Berry (vers 1415), inachevées à la mort des frères Limbourg et du duc en 1416, sont le chef-d'oeuvre absolu de l'enluminure internationale. Les miniatures des mois représentent les activités saisonnières des paysans et de la cour avec un réalisme documentaire et une sensibilité poétique qui annoncent directement la peinture flamande. Les châteaux en fond, reconnaissables (Mehun-sur-Yèvre, Vincennes, Lusignan), offrent un panorama architectural unique de la France de 1400.</p><div class="highlight-box"><p>La cathédrale de Prague (commencée en 1344 sous Charles IV) est un manifeste du gothique impérial : conçue par Matthieu d'Arras puis Peter Parler, elle intègre les innovations du gothique français dans un projet de légitimation dynastique. Les portraits sculptés de Charles IV et de ses épouses dans le triforium constituent la première galerie de portraits réalistes de l'art gothique.</p></div>""",

        "art-medieval/manuscrits-enlumines": """<h3>La transition vers l'imprimerie et la fin de l'enluminure médiévale</h3><p class="resume-text">L'invention de l'imprimerie à caractères mobiles par Gutenberg vers 1450 a progressivement mis fin à l'enluminure comme production artisanale de masse. Mais la transition fut lente : pendant plusieurs décennies, les imprimeurs laissèrent des espaces vierges dans leurs livres pour que des enlumineurs y ajoutent à la main les lettrines décorées et les miniatures. Les grands bibliophiles continuèrent à commander des manuscrits enluminés bien après que l'imprimerie les rendit "anachroniques" — signe que l'enluminure avait une valeur de prestige social irremplaçable.</p><p class="resume-text">Simon Marmion, Jean Bourdichon, Jean Clouet — les derniers grands enlumineurs de la fin du XVe siècle travaillèrent pour les cours royales et princières françaises et flamandes. Les Grandes Heures d'Anne de Bretagne, réalisées par Jean Bourdichon entre 1503 et 1508, sont le testament de l'enluminure médiévale : 49 grandes miniatures d'une précision botanique (337 plantes représentées) et d'une sensibilité poétique qui intègrent les leçons de la peinture à l'huile flamande tout en maintenant les traditions de l'art des manuscrits.</p><div class="highlight-box"><p>Les Grandes Heures d'Anne de Bretagne (1503-1508), aujourd'hui à la BNF, constituent le dernier grand chef-d'oeuvre de l'enluminure médiévale française. Le peintre Jean Bourdichon y représente 337 plantes différentes, chacune identifiable botaniquement, encadrant les prières de la reine — une fusion de science naturelle et de dévotion caractéristique de la pensée humaniste de la Renaissance.</p></div>""",

        "art-medieval/vitraux": """<h3>Les vitraux de la Renaissance et de l'époque moderne</h3><p class="resume-text">La technique du vitrail évolue considérablement à la Renaissance : l'influence de la peinture à l'huile pousse les verriers vers plus de naturalisme et de perspective illusionniste. Les vitraux de la cathédrale de Troyes (XVIe siècle) ou de Saint-Nicolas-de-Port montrent des compositions théâtrales avec architecture perspectivée et figures aux poses rhétoriques héritées de la peinture italienne — s'éloignant de la stylisation symbolique médiévale. Le verre gravé à l'acide fluorhydrique (inventé vers 1670) permet de nouvelles subtilités chromatiques mais marque aussi le début de la production industrielle.</p><p class="resume-text">La révolution du vitrail au XIXe siècle vient du mouvement Arts and Crafts et des préraphaélites anglais. William Morris et Edward Burne-Jones, collaborant depuis 1861, créent des vitraux d'un coloris et d'une composition entièrement nouveaux. Leurs figures féminines mélancoliques, leurs roses et lys stylisés, leur palette dorée anticipent le style Art Nouveau. En France, Émile Gallé et la École de Nancy réinterprètent la tradition verrière médiévale dans un style organique inspiré de la nature.</p><div class="highlight-box"><p>La reconstruction des cathédrales bombardées pendant la Première Guerre mondiale a ouvert la voie à des commandes de vitraux contemporains à de grands artistes : Matisse à Vence (1951), Chagall à Metz (1958-1968), Léger à Audincourt (1951). Ces oeuvres montrent que la tradition du vitrail s'est renouvelée au XXe siècle plutôt que de disparaître.</p></div>""",

        "renaissance/quattrocento": """<h3>L'humanisme florentin et le mécénat des Médicis</h3><p class="resume-text">Les Médicis — cosme (1389-1464) puis Laurent le Magnifique (1449-1492) — ont transformé Florence en capitale de l'humanisme européen. Cosme fonda la Bibliothèque Médicéenne et finança la première traduction latine complète de Platon par Marsile Ficin. Son Académie platonicienne, réunissant philosophes, poètes et artistes autour de discussions sur Platon et Plotin, créa un milieu intellectuel unique qui nourrit directement la peinture de Botticelli et la sculpture de Donatello.</p><p class="resume-text">Le Printemps et La Naissance de Vénus de Botticelli (vers 1482-1485) sont les premières grandes peintures mythologiques profanes de la Renaissance — des oeuvres destinées non à une église mais à une villa privée, pour un public cultivé capable d'en lire les références néoplatoniciennes. La Vénus botticellienne — née de l'écume de la mer, portée vers le rivage par les vents — est une allégorie de la Beauté idéale platonicienne descendant dans le monde sensible. Le style "en serpentine" des figures, leurs lignes ondulantes, leur mélancolie poétique définissent un idéal esthétique immédiatement reconnaissable.</p><div class="highlight-box"><p>Laurent de Médicis avait remarqué le jeune Michel-Ange et l'invita à vivre dans son palais de 1489 à 1492. Michel-Ange, alors âgé de 14-17 ans, mangea à la table de Laurent, côtoya Ficin, Polizien et Pic de la Mirandole. Cette immersion dans l'humanisme florentin façonna durablement sa vision de l'art, de la philosophie et de l'Antiquité.</p></div>""",

        "renaissance/leonard-de-vinci": """<h3>La Cène : programme iconographique et postérité</h3><p class="resume-text">La Cène de Milan (1494-1498) est l'une des oeuvres les plus analysées de l'histoire de l'art. Peinte pour le réfectoire du couvent Santa Maria delle Grazie avec une technique de détrempe et d'huile sur plâtre (non en vraie fresque), elle a commencé à se détériorer de son vivant. Les multiples restaurations successives et la pollution milanaise en ont fait un tableau presque entièrement repeint — ce que nous voyons est à 80% postérieur au XVIe siècle.</p><p class="resume-text">La composition répond à un problème iconographique précis : comment représenter simultanément l'annonce de la trahison de Judas ("l'un d'entre vous me trahira") et l'institution de l'Eucharistie ? Léonard résout ce dilemme par une lecture en "onde" des douze apôtres disposés en groupes de trois, chacun réagissant différemment à la parole du Christ au centre. Judas est représenté non séparé des autres (tradition médiévale) mais dans le troisième groupe à gauche, son visage dans l'ombre, serrant une bourse.</p><div class="highlight-box"><p>Dan Brown a prétendu dans Da Vinci Code (2003) que la figure à la droite du Christ (à gauche du spectateur) était Marie-Madeleine et non l'apôtre Jean. Cette interprétation est rejetée par la totalité des historiens de l'art : Léonard représentait Jean très jeune et efféminé dans ses dessins préparatoires. Mais le roman illustre l'extraordinaire pouvoir de fascination que la Cène exerce encore sur l'imagination collective.</p></div>""",

        "renaissance/michel-ange": """<h3>Les dernières années : le Jugement dernier et la Pietà Rondanini</h3><p class="resume-text">Le Jugement dernier (1536-1541), peint sur le mur de l'autel de la Sixtine trente ans après le plafond, révèle une vision du monde profondément transformée. Fini l'optimisme humaniste du plafond : les corps du Jugement sont lourds, tortueux, violentés par les forces qui les précipitent vers l'enfer ou les élèvent vers le paradis. Le Christ, jeune et imberbe dans la tradition classique, lève le bras en un geste de condamnation que les contemporains comparèrent au Zeus olympien. Ce changement d'humeur reflète la crise de la Réforme protestante et le Sac de Rome (1527), qui avaient profondément ébranlé la confiance humaniste.</p><p class="resume-text">La Pietà Rondanini (1552-1564), laissée inachevée à sa mort à 88 ans, est l'oeuvre la plus dépouillée et la plus moderne de Michel-Ange. Les deux figures — Marie et le Christ — sont fondues l'une dans l'autre, à peine dégagées du bloc de marbre, dans une fusion mystique qui abolit la distinction entre mère et fils, entre douleur et transcendance. Michel-Ange travaillait encore cette oeuvre six jours avant sa mort — son dernier dialogue avec la matière et avec la mort.</p><div class="highlight-box"><p>Michel-Ange a détruit la majorité de ses dessins préparatoires peu avant sa mort, souhaitant que sa renommée repose sur les oeuvres achevées plutôt que sur le travail du processus créatif. Cette destruction délibérée a privé l'histoire de l'art de milliers de témoignages sur sa méthode — et a créé la légende d'un artiste dont les oeuvres sortaient "parfaites" de l'inspiration divine.</p></div>""",

        "renaissance/raphael": """<h3>La tapisserie sistine et les arts appliqués</h3><p class="resume-text">Raphaël dessinait non seulement des tableaux et des fresques mais s'impliquait dans tous les arts : architecture, décoration intérieure, tapisserie, gravure, urbanisme. Ses cartons pour les tapisseries des Actes des Apôtres (1515-1516), commandés par le pape Léon X pour orner la Sixtine lors des grandes cérémonies, sont aujourd'hui conservés au Victoria and Albert Museum de Londres. Ces dessins monumentaux en couleurs révèlent un Raphaël grand compositeur de scènes narratives, aussi à l'aise dans le format horizontal de la tapisserie que dans la fresque murale.</p><p class="resume-text">Raphaël supervisa également la production des "Loges de Raphaël" au Vatican (1517-1519) — une galerie de 13 travées décorées de grotesques inspirés des peintures romaines redécouvertes dans la Domus Aurea de Néron. Cette décoration, réalisée en partie par ses élèves (Giovanni da Udine, Giulio Romano), invente un vocabulaire ornemental fantaisiste — arabesques, figures mythologiques, oiseaux et fleurs — qui deviendra le répertoire standard de la décoration intérieure européenne pendant trois siècles.</p><div class="highlight-box"><p>Raphaël fut le premier artiste à faire nommer "surintendant des antiquités romaines" — chargé par Léon X en 1515 d'inventorier et de protéger les vestiges antiques de Rome. Dans sa lettre au pape, il se lamentait de la destruction des monuments antiques pillés pour leurs matériaux. Ce rôle préfigure les institutions modernes de protection du patrimoine.</p></div>""",

        "renaissance/renaissance-nordique": """<h3>Bosch, Bruegel et la vision du monde nordique</h3><p class="resume-text">Jérôme Bosch (vers 1450-1516) crée un univers pictural sans équivalent — peuplé de créatures hybrides (mi-homme, mi-poisson, mi-insecte), de paysages cauchemardesques et de scènes de péché collectif d'une richesse symbolique inépuisable. Le Jardin des délices (vers 1500-1510, Prado) est son chef-d'oeuvre : un triptyque dont le panneau central représente l'humanité dans une euphorie hédoniste qui se transforme dans le volet droit en enfer technologique et musical. Les interprétations divergent depuis cinq siècles : catéchèse morale contre le péché de luxure ? Vision mystique d'un hérétique ? Traité alchimique ? Illustration d'un rêve collectif ?</p><p class="resume-text">Pieter Bruegel l'Ancien (vers 1525-1569) transpose la tradition satirique de Bosch dans un univers paysan et proverbian. La Tour de Babel (1563) transforme le récit biblique en méditation sur l'orgueil des bâtisseurs — le roi Nimrod au premier plan, ignorant du chaos que son projet génère, figure peut-être Charles Quint. Les Chasseurs dans la neige (1565) inaugure le genre du paysage hivernal habité, avec une atmosphère de silence et de froid d'une justesse poétique encore inégalée.</p><div class="highlight-box"><p>Les "proverbes flamands" — cycles de tableaux illustrant des proverbes populaires — constituent l'un des genres les plus originaux de la Renaissance nordique. Bruegel en a peint plusieurs versions : "Le Pays de Cocagne", "La Lutte entre Carnaval et Carême", "Les Jeux d'enfants" mettent en scène des dizaines de personnages illustrant simultanément les sagesses et les folies humaines dans une vision encyclopédique du monde paysan.</p></div>""",

        "art-moderne/impressionnisme": """<h3>La dissolution du mouvement et les héritages</h3><p class="resume-text">Le mouvement impressionniste s'est progressivement dissous dans les années 1880 sous les tensions internes entre ses membres. Degas et Renoir souhaitaient revenir à des valeurs classiques ; Cézanne cherchait une synthèse avec Poussin ; Gauguin partait vers les mers du Sud. Après l'exposition finale de 1886, les individualités l'emportèrent sur le collectif. Mais l'impressionnisme avait accompli sa révolution : il avait libéré la peinture de l'obligation de représenter fidèlement, ouvert la voie à toutes les avant-gardes du XXe siècle.</p><p class="resume-text">L'influence de l'impressionnisme fut mondiale et immédiate. Aux États-Unis, Mary Cassatt avait diffusé le style dès les années 1880 ; des collectionneurs américains comme le marchand Paul Durand-Ruel organisèrent des expositions à New York qui furent des succès commerciaux là où Paris avait boudé. Au Japon, les artistes Meiji qui découvraient la peinture occidentale adoptèrent l'impressionnisme comme modernité par excellence. En Scandinavie, le mouvement nationaux-romantiques s'appropria les techniques impressionnistes pour célébrer les paysages locaux.</p><div class="highlight-box"><p>Aujourd'hui, les oeuvres impressionnistes constituent la catégorie la plus valorisée du marché de l'art mondial. Les Meules de Monet ont été vendues pour 110 millions de dollars en 2019 ; les Nymphéas se négocient à des centaines de millions. Paradoxalement, un mouvement qui avait été rejeté par le marché officiel de son époque est devenu l'art le plus cher du monde.</p></div>""",

        "art-moderne/post-impressionnisme": """<h3>Le pointillisme : Seurat et la science de la couleur</h3><p class="resume-text">Georges Seurat développe le pointillisme (qu'il préférait appeler "chromoluminisme") à partir d'une lecture directe des théories scientifiques de la couleur. Ses études des travaux de Chevreul (De la loi du contraste simultané des couleurs, 1839) et d'Ogden Rood (Couleurs modernes, 1879) lui apprennent que les couleurs placées côte à côte se "mélangent" dans l'oeil du spectateur à distance, selon les principes de la synthèse additive. La Grande Jatte (1884-1886) est l'application systématique de ces principes : 2 mètres × 3, entièrement peinte en petits points de couleurs pures.</p><p class="resume-text">La paradoxe du pointillisme est que sa base scientifique est en partie erronée : Seurat croyait que les points se mélangeraient "optiquement" comme des lumières colorées, mais en réalité les pigments se mélangent partiellement en assombrissant le résultat. L'effet obtenu est néanmoins d'une grande luminosité — non par mélange optique mais par la vibration de la surface. La formalisation quasi mathématique de la composition donne aux tableaux de Seurat une qualité de frieze monumentale et d'immobilité qui contraste avec le mouvement impressionniste.</p><div class="highlight-box"><p>La Grande Jatte de Seurat a été popularisée par la comédie musicale Sunday in the Park with George de Stephen Sondheim (1984), dont la première acte est entièrement consacré à la genèse du tableau. Cette popularisation culturelle illustre comment une oeuvre peut traverser un siècle et trouver de nouvelles formes de réception dans des médias que son auteur n'aurait pas imaginés.</p></div>""",

        "art-moderne/cubisme": """<h3>Le cubisme et la sculpture : Picasso, Brancusi, Archipenko</h3><p class="resume-text">Le cubisme transforme profondément la sculpture du XXe siècle. Les constructions tridimensionnelles de Picasso (1912-1913) — assemblages de carton, tôle, fil de fer — abandonnent le principe de la sculpture comme masse pleine pour explorer l'espace vide, le plan découpé, l'assemblage de matériaux hétéroclites. Ces travaux "pauvres", que Picasso considérait comme des expériences sans lendemain, influencent directement les constructions russes (Tatlin, Rodchenko) et le mobile de Calder.</p><p class="resume-text">Constantin Brancusi (1876-1957) développe simultanément une voie vers l'abstraction en sculpture, indépendante du cubisme mais convergeant avec lui. Ses séries de L'Oiseau dans l'espace, L'Eau qui dort, la Colonne sans fin — formes polies d'une pureté formelle extrême — cherchent l'essence des choses à travers la simplification radicale. Son atelier reconstitué au Centre Pompidou est lui-même une oeuvre totale, où chaque objet est en dialogue spatial avec les autres.</p><div class="highlight-box"><p>En 1928, les douanes américaines refusèrent d'accepter l'Oiseau dans l'espace de Brancusi comme oeuvre d'art (non taxable) et prétendirent le taxer comme pièce industrielle (métal ouvré). Le procès Brancusi contre les États-Unis (1928) est le premier grand procès définissant légalement ce qu'est une oeuvre d'art — et la décision, en faveur de Brancusi, établit qu'une oeuvre d'art n'a pas besoin de ressembler à quelque chose pour être reconnue comme telle.</p></div>""",

        "art-moderne/surrealisme": """<h3>Le surréalisme en dehors de Paris : l'influence mondiale</h3><p class="resume-text">Le surréalisme s'est rapidement diffusé hors de Paris pour devenir un phénomène mondial. Au Mexique, où Breton se rendit en 1938 pour rencontrer Trotski et Frida Kahlo, un surréalisme Latin se développa avec Remedios Varo et Leonora Carrington — deux artistes européennes exilées par la guerre qui créèrent à Mexico un univers d'une originalité exceptionnelle, mêlant alchimie, féminisme et culture précolombienne. En Amérique latine, Matta, Wifredo Lam (Cuba) développèrent des variantes liées aux cultures locales et à la lutte anticoloniale.</p><p class="resume-text">L'exil en Amérique des surréalistes pendant la Seconde Guerre mondiale eut des conséquences décisives pour l'art américain. Max Ernst, André Masson, Roberto Matta s'installent à New York, où ils côtoient une jeune génération d'artistes américains (Pollock, Motherwell, Baziotes) qui assimileront la technique de l'automatisme pour développer l'expressionnisme abstrait. Le "dripping" de Pollock est directement héritier de l'automatisme surréaliste, transposé dans la gestuelle physique du corps tout entier.</p><div class="highlight-box"><p>Le Musée national d'art moderne de Paris conserve la "Boîte-en-valise" de Marcel Duchamp (1935-1941) — une valise contenant des reproductions miniatures de ses oeuvres les plus importantes. Cette oeuvre portable anticipe le concept de "musée imaginaire" et questionne l'institution muséale : si l'art peut tenir dans une valise, a-t-on besoin de palais pour le conserver ?</p></div>""",

        "art-moderne/art-abstrait": """<h3>L'expressionnisme abstrait américain</h3><p class="resume-text">L'expressionnisme abstrait new-yorkais (années 1940-1950) représente le premier mouvement d'avant-garde à émerger hors d'Europe, marquant le basculement du centre mondial de l'art de Paris vers New York. Jackson Pollock développe le "dripping" (1947) — peindre en faisant goutter et en projetant la peinture sur une toile posée au sol, en se déplaçant tout autour. Ce geste élimine le contact direct entre pinceau et toile, transformant le tableau en trace d'une danse autour de la surface, document d'une énergie corporelle.</p><p class="resume-text">Mark Rothko, Willem de Kooning, Franz Kline, Barnett Newman développèrent des voies différentes mais convergentes. Rothko crée des "colour field paintings" — grands rectangles de couleur flottants sur des fonds tonals — qui cherchent à produire une expérience transcendante proche de l'extase religieuse. Il refusait que ses tableaux soient vus de loin : "Un Rothko doit être vu à 45 centimètres pour être senti." La Chapelle Rothko à Houston (1971), entièrement consacrée à ses quatorze toiles noires sur marron, est son legs spirituel.</p><div class="highlight-box"><p>Jackson Pollock expliquait son dripping en disant : "Je suis dans le tableau." Cette immersion physique — contourner la toile, s'y enfoncer du regard, l'habiter avant de la traverser — est la traduction gestuelle de l'automatisme surréaliste. Pollock transforme l'acte de peindre en performance, anticipant la performance art de la décennie suivante.</p></div>""",

        "art-contemporain/pop-art": """<h3>Le pop art hors des États-Unis</h3><p class="resume-text">Le pop art n'est pas un phénomène exclusivement américain. En Angleterre, l'Independent Group anticipe le mouvement dès les années 1950 avec Richard Hamilton (le père fondateur) et Eduardo Paolozzi. David Hockney, dont la série de Piscines californiennes (1964-1971) superpose les techniques du dessin, de la photographie et de la peinture dans des compositions d'une clarté solaire, constitue l'un des héritages les plus durables du pop britannique. En Allemagne, Sigmar Polke et Gerhard Richter développent un "Capitalist Realism" — terme ironique qui joue sur le "réalisme socialiste" soviétique — utilisant les images publicitaires et médiatiques dans un contexte culturel différent de l'américain.</p><p class="resume-text">En France, le Nouveau Réalisme (Arman, Yves Klein, Jean Tinguely, Niki de Saint Phalle) constitue une variante européenne du pop qui s'en distingue par son rapport différent à l'objet — moins d'ironie à froid, plus d'engagement physique et émotionnel. Arman accumule des objets industriels dans des boîtes transparentes (les Accumulations) ou les détruit dans des "Colères". Yves Klein peint des "Monochromes" en bleu outremer (le fameux IKB — International Klein Blue), proposant la couleur pure comme expérience de l'infini.</p><div class="highlight-box"><p>Yves Klein a breveté en 1960 une teinte de bleu outremer particulière : l'IKB (International Klein Blue). Cette appropriation d'une couleur par un artiste est unique dans l'histoire de l'art. Le bleu Klein — un bleu d'un saturation et d'une profondeur qui donne l'impression de regarder dans le ciel ou l'infini — reste l'une des identités visuelles les plus reconnaissables de l'art du XXe siècle.</p></div>""",

        "art-contemporain/minimalisme": """<h3>Le minimalisme dans le design et la culture populaire</h3><p class="resume-text">Les principes minimalistes ont profondément influencé le design contemporain, en particulier depuis les années 1990. Apple, sous la direction artistique de Jony Ive influencé par Dieter Rams et le Bauhaus, a fait du minimalisme un impératif commercial : "less is more" devient une stratégie de marque. L'iPhone, avec ses surfaces lisses sans boutons apparents, est l'objet minimaliste le plus répandu de l'histoire. Cette universalisation du minimalisme dans les objets quotidiens est à la fois l'accomplissement et la trahison de l'ambition des artistes minimalistes des années 1960.</p><p class="resume-text">Le luxe contemporain s'exprime souvent par des codes minimalistes : intérieurs épurés, surfaces neutres, absence d'ornementation. Cette esthétique, héritée du mouvement Arts and Crafts et du Bauhaus, puis réinterprétée par le minimalisme artistique, est devenue le langage visuel d'une certaine idée de la sophistication — celle qui n'a pas besoin de se montrer. La boutique Prada de Rem Koolhaas à New York ou les hôtels Ian Schrager illustrent comment l'art minimaliste a été absorbé et récupéré par le marché de luxe.</p><div class="highlight-box"><p>Richard Serra, figure majeure du minimalisme en sculpture, a créé des installations monumentales en acier Corten qui transforment l'espace environnant. Sa Tilted Arc (1981), une plaque d'acier de 36 mètres traversant Federal Plaza à New York, fut détruite en 1989 après une polémique publique intense — l'une des rares fois dans l'histoire moderne où une oeuvre d'art public a été détruite sur décision démocratique.</p></div>""",

        "art-contemporain/art-conceptuel": """<h3>L'art conceptuel et l'institution muséale</h3><p class="resume-text">L'art conceptuel entretient une relation paradoxale avec les institutions muséales qu'il critique. Hans Haacke, figure de l'art institutionnel critique, exposait au musée des études révélant les réseaux de propriété et de pouvoir autour de ce même musée — une démarche qui conduisit le Guggenheim à annuler son exposition en 1971. Cette tension entre l'art critique et l'institution qui l'expose constitue le coeur du débat sur l'autonomie de l'art dans le système capitaliste.</p><p class="resume-text">La dématérialisation de l'art conceptuel a créé de nouveaux problèmes de conservation et d'authenticité. Comment conserver une oeuvre qui n'existe que comme instruction écrite ? Comment exposer une performance qui par définition ne peut être rejouée à l'identique ? Les musées ont développé des pratiques de "re-performance" (faire rejouer des performances historiques par de nouveaux interprètes) et de conservation des "scores" (partitions d'instructions) qui soulèvent des questions philosophiques sur l'authenticité et la reproductibilité.</p><div class="highlight-box"><p>Yoko Ono a créé des "instructions" artistiques dès 1963 dans son livre Grapefruit — des textes brefs prescrivant des actions poétiques ("Regarde la lumière jusqu'à ce qu'elle disparaisse, puis dessine-la"). Ces oeuvres anticipent les instructions de Sol LeWitt et toute la pratique des "scores" dans l'art conceptuel et la performance. Grapefruit est aujourd'hui considéré comme l'un des livres les plus influents de l'art contemporain.</p></div>""",

        "art-contemporain/installations": """<h3>L'installation et l'espace public</h3><p class="resume-text">Les installations dans l'espace public transforment la relation entre art et citoyenneté. Christo et Jeanne-Claude ont consacré leur carrière à des emballages monumentaux d'édifices publics (Pont-Neuf, Reichstag, Central Park) qui déplacent temporairement le regard quotidien sur des espaces familiers. L'Empaquetage du Reichstag (1995) — 100 000 m2 d'aluminium tissé gris-argent — a transformé l'espace politique le plus chargé d'Allemagne en objet purement esthétique pendant deux semaines, attirant 5 millions de visiteurs et suscitant un débat public sur la relation entre art, démocratie et mémoire.</p><p class="resume-text">L'art participatif et relationnel (Bourriaud) développe des installations qui ne peuvent exister sans la participation active du public. Rirkrit Tiravanija cuisine du riz dans les galeries et invite les visiteurs à manger ensemble — l'oeuvre est la situation sociale créée. Thomas Hirschhorn construit des "monuments" précaires dans des quartiers populaires, faisant travailler les habitants du quartier comme collaborateurs. Ces pratiques questionnent la valeur de l'art comme objet pour la proposer comme expérience collective.</p><div class="highlight-box"><p>L'installation Sunflower Seeds d'Ai Weiwei (Tate Modern, 2010) couvrait le sol de la Turbine Hall de 100 millions de graines de tournesol en porcelaine, fabriquées à la main par 1 600 artisans de la ville de Jingdezhen. Chaque graine était unique. L'oeuvre interrogeait à la fois la production industrielle chinoise, la masse et l'individu, et la relation entre l'objet manufacturé et l'oeuvre d'art.</p></div>""",

        "art-contemporain/art-numerique": """<h3>L'intelligence artificielle générative et le futur de l'art</h3><p class="resume-text">Les modèles génératifs d'images par IA (Midjourney, DALL-E, Stable Diffusion) ont créé en 2022-2023 une révolution sans précédent dans la production d'images. Ces systèmes, entraînés sur des milliards d'images humaines, peuvent générer sur demande textuelle des images d'une qualité visuelle équivalente à une illustration professionnelle — en quelques secondes. Cette démocratisation radicale de la production d'images soulève des questions fondamentales sur le travail des artistes, la valeur de la compétence technique et la définition même de la créativité.</p><p class="resume-text">Des artistes comme Refik Anadol transforment des données massives (archives de bibliothèques, données météorologiques, flux de réseaux sociaux) en sculptures de données visuelles — des vagues de couleur et de mouvement qui "donnent à voir" des patterns invisibles à l'oeil nu. Son installation Machine Hallucinations (2019) au MoMA de New York, utilisant des millions d'images d'architecture pour créer un espace de rêve collectif, illustre comment les artistes peuvent collaborer avec l'IA comme outil créatif plutôt que comme menace.</p><div class="highlight-box"><p>La question du droit d'auteur dans l'art généré par IA est au coeur de procès en cours (2023-2025) aux États-Unis. Des artistes poursuivent des entreprises d'IA pour avoir utilisé leurs oeuvres comme données d'entraînement sans autorisation ni rémunération. L'issue de ces procès déterminera le cadre légal de l'art numérique pour les décennies à venir.</p></div>""",

        "analyse-oeuvres/la-joconde": """<h3>La Joconde au Louvre : exposition et expérience muséale</h3><p class="resume-text">L'exposition de la Joconde au Louvre illustre les paradoxes de la muséification des oeuvres d'art célèbres. Depuis 2005, elle est présentée dans la Salle des États — la plus grande salle du musée, pouvant accueillir simultanément plusieurs centaines de visiteurs. Derrière son vitrage blindé, à 3 mètres de distance minimale, le tableau de 77 × 53 cm paraît d'une petitesse déconcertante face aux Noces de Cana de Véronèse (7 × 10 mètres) qui lui fait face. Cette asymétrie est emblématique : le plus grand tableau du Louvre n'attire qu'un regard distrait, quand le plus célèbre concentre une foule compacte de photographes.</p><p class="resume-text">Le Louvre a réfléchi à plusieurs projets de "déplacement" de la Joconde pour soulager l'encombrement. L'une des propositions envisagées (vers 2020) consistait à lui donner une salle entièrement dédiée où les visiteurs pourraient la voir en petit groupe, dans des conditions d'éclairage et de distance optimales. Ce projet se heurte à une résistance institutionnelle et politique — la Joconde dans "sa" salle est devenue un emblème du Louvre que l'on ne peut déplacer sans créer une polémique.</p><div class="highlight-box"><p>Le Louvre reçoit environ 9 millions de visiteurs annuels. On estime que 80% d'entre eux viennent principalement pour voir la Joconde — une concentration extraordinaire de l'attention sur une seule oeuvre dans un musée qui en possède 380 000. Ce phénomène illustre comment la réputation d'une oeuvre peut supplanter sa réalité visuelle dans l'expérience muséale contemporaine.</p></div>""",

        "analyse-oeuvres/nuit-etoilee": """<h3>La Nuit étoilée au MoMA : acquisition et conservation</h3><p class="resume-text">La Nuit étoilée est entrée au Museum of Modern Art de New York en 1941 par don de Lillie P. Bliss, l'une des fondatrices du musée. Son acquisition aux États-Unis avant la Seconde Guerre mondiale la mit à l'abri des destructions européennes. Elle fut immédiatement reconnue par le milieu artistique new-yorkais — en particulier par les artistes de l'expressionnisme abstrait en formation — comme un précurseur de l'art abstrait. Pollock, Rothko et De Kooning mentionnaient régulièrement Van Gogh dans leurs écrits et interviews.</p><p class="resume-text">La conservation du tableau pose des défis spécifiques liés à la technique de Van Gogh. Ses impastos épaisses — parfois un centimètre de relief — créent des contraintes mécaniques importantes lors des déplacements. Le tableau a été déposé de son châssis plusieurs fois au cours du XXe siècle pour des raisons de conservation. La recherche sur la stabilité des pigments de Van Gogh (certains jaunissent ou noircissent à la lumière) a révélé que les jaunes de chrome de certains tableaux sont plus instables que prévu — une information qui modifie l'éclairage et les conditions d'exposition.</p><div class="highlight-box"><p>La Nuit étoilée n'a quitté le MoMA qu'une seule fois depuis son entrée dans la collection en 1941 : pour l'exposition Van Gogh à Amsterdam et Otterlo en 1990. Elle est généralement considérée comme trop fragile pour voyager. Les grandes expositions Van Gogh doivent donc se passer de leur tableau le plus célèbre — ou le remplacer par une reproduction numérique à grande échelle.</p></div>""",

        "analyse-oeuvres/guernica": """<h3>Les études préparatoires et le processus créatif de Guernica</h3><p class="resume-text">Picasso a réalisé 45 études préparatoires pour Guernica, conservées au musée Reina Sofia. Ces dessins, datés jour par jour du 1er mai au 4 juin 1937, permettent de suivre en temps réel l'élaboration de la composition. Les premiers dessins montrent une composition radicalement différente : une femme avec un enfant, un taureau, un oiseau — les éléments sont présents mais dans d'autres positions et proportions. Au fil des études, la composition se resserre, les figures se fragmentent davantage, la palette se décolore vers le noir et blanc.</p><p class="resume-text">La photographe Dora Maar, amante de Picasso de 1936 à 1943, documenta le processus de création de Guernica en huit photographies prises à différents stades d'avancement. Ces photographies sont précieuses non seulement comme documents historiques mais comme oeuvres à part entière — elles montrent un tableau en devenir, une oeuvre "ouverte" que Picasso refermait progressivement. La comparaison entre les photographies et l'oeuvre finale révèle des modifications significatives de dernière minute.</p><div class="highlight-box"><p>Dans l'oeuvre terminée, Picasso intégra une solution formelle inattendue : les fleurs de papier peint représentées dans certaines études préparatoires disparurent au profit d'un fond entièrement neutre. Cette décision de supprimer tout décor "chaleureux" accentue le caractère de reportage photographique et la violence nue de la scène — un choix éditorial conscient.</p></div>""",

        "analyse-oeuvres/liberte-guidant-peuple": """<h3>Delacroix et le romantisme politique</h3><p class="resume-text">La Liberté guidant le peuple s'inscrit dans la tradition du "peintre-historien" que Delacroix revendiquait contre le néo-classicisme de David. Là où David peignait l'histoire antique comme modèle politique intemporel (Le Serment des Horaces, La Mort de Marat), Delacroix peint l'histoire contemporaine dans sa violence et son chaos — moins pour donner des leçons que pour capturer l'énergie d'un moment. Ce romantisme de l'événement, héritier de Géricault (Le Radeau de la Méduse, 1818-1819), est une révolution dans la peinture d'histoire.</p><p class="resume-text">La composition de Delacroix doit beaucoup à sa connaissance de la peinture baroque. La pyramide ascendante, la lumière dramatique, les corps convulsés au premier plan — ces éléments viennent directement de Rubens, dont Delacroix était un admirateur fervent. Mais là où Rubens célébrait la gloire des princes, Delacroix célèbre la gloire du peuple. Le même vocabulaire formel sert une signification politique radicalement différente — preuve que le style n'est jamais politiquement neutre.</p><div class="highlight-box"><p>Le bonnet phrygien porté par la Liberté est un symbole de la liberté depuis l'Antiquité romaine : les esclaves affranchis le portaient. La Révolution française l'avait réactivé comme symbole républicain. Delacroix le place sur une figure qui associe ainsi l'allégorie classique et la tradition révolutionnaire dans une image d'une puissance symbolique durable.</p></div>""",

        "analyse-oeuvres/nympheas": """<h3>La restauration et la conservation des Nymphéas</h3><p class="resume-text">La conservation des Nymphéas à l'Orangerie pose des défis uniques. Les panneaux monumentaux (2 × 12 mètres pour les plus grands) sont peints sur toile marouflée sur bois — un support composite qui se dilate et se contracte différemment selon l'humidité. Des craquelures importantes apparurent dès les années 1940. Une restauration majeure entre 2006 et 2010 a stabilisé les oeuvres, fermé les lacunes par des retouches réversibles et créé un système de climatisation capable de maintenir température et hygrométrie aux niveaux optimaux.</p><p class="resume-text">L'éclairage des Nymphéas est un enjeu crucial. Monet avait conçu les salles ovales pour une lumière naturelle zénithale depuis des verrières. La lumière naturelle variable — différente selon les saisons, les heures, le temps — participait de l'expérience prévue par l'artiste. Les modifications apportées après la Seconde Guerre mondiale avaient substitué à cette lumière naturelle un éclairage artificiel fixe. La restauration de 2006-2010 a rétabli un éclairage hybride préservant la dimension changeante de la lumière naturelle tout en contrôlant les UV dommageables.</p><div class="highlight-box"><p>Monet a légué les Grandes Décorations des Nymphéas à l'État français le 12 novembre 1918 — le lendemain de l'armistice. Ce geste simultané est symboliquement fort : le don d'un espace de paix et de contemplation à une nation sortant de la guerre. Le premier ministre Clémenceau, ami intime de Monet, avait déclaré vouloir "un poème de l'eau et de la lumière" pour offrir aux soldats de retour un lieu de repos de l'âme.</p></div>""",
    }
}

def enrich_discipline(discipline, enrichments, base_path="C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content"):
    filepath = f"{base_path}/{discipline}.json"
    with open(filepath, encoding='utf-8') as fp:
        data = json.load(fp)

    changed = 0
    for key, addition in enrichments.items():
        if key not in data['pages']:
            print(f"  WARNING: key not found: {key}")
            continue
        content = data['pages'][key]['content']
        if '<section class="content-section" id="quiz">' in content:
            content = content.replace(
                '<section class="content-section" id="quiz">',
                addition + '\n<section class="content-section" id="quiz">'
            )
        else:
            content = content.rstrip()
            if content.endswith('</section>'):
                content = content[:-10] + addition + '</section>'
            else:
                content += addition
        data['pages'][key]['content'] = content
        new_len = len(data['pages'][key]['content'])
        print(f"  {key}: {new_len} chars")
        changed += 1

    with open(filepath, 'w', encoding='utf-8') as fp:
        json.dump(data, fp, ensure_ascii=False, indent=2)
    print(f"Saved {discipline}.json ({changed} articles enriched)")

for discipline, enrichments in ENRICHMENTS_PASS2.items():
    print(f"\n=== {discipline} ===")
    enrich_discipline(discipline, enrichments)

print("\nDone!")
