#!/usr/bin/env python3
"""Enrich geographie, anthropologie, sociologie, psychologie pages under 15000 chars."""
import json

BASE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/"

def load(disc):
    with open(BASE + disc + '.json', 'r', encoding='utf-8') as f:
        return json.load(f)

def save(disc, data):
    with open(BASE + disc + '.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def inject(pages, key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

# ═══════════════════════════════════════════════════════════════
# GÉOGRAPHIE
# ═══════════════════════════════════════════════════════════════
data_geo = load('geographie')
pages_geo = data_geo['pages']

GEO_TOPUPS = {
'humaine/demographie': """
<h3>La transition démographique et ses stades</h3>
<p class="resume-text">Le modèle de la transition démographique décrit le passage d'un régime de haute natalité / haute mortalité à un régime de basse natalité / basse mortalité. Dans la phase 1 (pré-industrielle), les deux taux sont élevés et la population stagne. Dans la phase 2, la mortalité chute (hygiène, médecine, agriculture) avant la natalité, générant une explosion démographique. Dans la phase 3, la natalité baisse à son tour. Dans la phase 4, les deux taux sont bas et la croissance ralentit. Certains démographes ajoutent une phase 5 de déclin naturel, déjà visible au Japon (-0,5 %/an) et dans plusieurs pays européens.</p>
<p class="resume-text">Le <strong>dividende démographique</strong> désigne la période où la proportion de population active est maximale par rapport aux dépendants (jeunes + vieux) — fenêtre d'opportunité de croissance économique accélérée si investissements en éducation et emploi sont au rendez-vous. L'Asie de l'Est (Chine, Corée, Taïwan) a largement exploité ce dividende de 1970 à 2000 ; l'Afrique subsaharienne entre progressivement dans cette fenêtre. La Chine a épuisé son dividende et fait face au « défi du 4-2-1 » : un actif devant subvenir à 2 parents et 4 grands-parents, héritage de la politique de l'enfant unique (1979-2015).</p>
<div class="highlight-box"><p><strong>8 milliards :</strong> La population mondiale a atteint 8 milliards en novembre 2022. Les projections médianes de l'ONU prévoient un pic à 10,4 milliards vers 2086, suivi d'un déclin. Ces projections sont très sensibles aux hypothèses de fécondité en Afrique subsaharienne, seule région où les indices synthétiques de fécondité restent au-dessus de 4 enfants par femme.</p></div>
""",
'humaine/mondialisation': """
<h3>La métropolisation et les global cities</h3>
<p class="resume-text">La mondialisation concentre les fonctions de commandement économique dans un nombre restreint de <strong>villes mondiales</strong> (global cities), concept forgé par Saskia Sassen en 1991. New York, Londres, Tokyo et Paris concentrent les sièges sociaux des firmes multinationales, les services financiers avancés, les cabinets d'avocats d'affaires internationaux et les agences de communication globale. Ces villes sont moins intégrées à leur arrière-pays national qu'entre elles : un banquier londonien partage plus de modes de vie et d'intérêts avec son homologue new-yorkais qu'avec un travailleur agricole anglais.</p>
<p class="resume-text">La métropolisation accroît les inégalités territoriales. Les régions métropolitaines captent l'essentiel de la croissance économique et des innovations, tandis que les espaces ruraux et les villes moyennes décrochent. En France, la concentration de l'emploi qualifié en Île-de-France a alimenté un sentiment de « France périphérique » (Christophe Guilluy) qui s'exprime politiquement — le vote Gilets jaunes de 2018 est fortement corrélé aux territoires périphériques déconnectés des dynamiques métropolitaines. Ce divorce géographique entre « gagnants » et « perdants » de la mondialisation est l'un des ressorts majeurs des populismes contemporains.</p>
""",
'physique/hydrologie': """
<h3>Le cycle hydrologique et ses perturbations</h3>
<p class="resume-text">Le cycle de l'eau mobilise 577 000 km³ d'eau par an entre océans, atmosphère, surfaces continentales et sous-sol. Les précipitations continentales (119 000 km³/an) se répartissent entre ruissellement superficiel (43 000 km³), évapotranspiration (76 000 km³) et recharge des nappes phréatiques. Le temps de résidence de l'eau varie de 9 jours dans l'atmosphère à 10 000 ans dans les aquifères fossiles (comme le System Aquifer en Afrique du Nord). Cette hétérogénéité temporelle explique pourquoi certaines ressources en eau sont renouvelables (précipitations annuelles) et d'autres non (eaux fossiles surexploitées).</p>
<p class="resume-text">Le changement climatique intensifie le cycle hydrologique : dans un air plus chaud (+1°C augmente la capacité de l'atmosphère à retenir 7 % de vapeur d'eau, relation de Clausius-Clapeyron), les précipitations intenses s'intensifient, les sécheresses s'allongent entre elles, et les extrêmes hydrologiques (crues centennales, sécheresses millénaires) deviennent plus fréquents. La crise de l'eau est la première grande crise de ressources qui touche massivement les populations dès aujourd'hui : 2 milliards de personnes n'ont pas accès à l'eau potable sûre (OMS 2022).</p>
<div class="highlight-box"><p><strong>Les guerres de l'eau :</strong> Le Nil, partagé entre 11 pays, fait l'objet d'un conflit géopolitique croissant depuis la construction du Grand Barrage de la Renaissance éthiopien (GERD), qui peut stocker 74 milliards de m³ — menaçant le débit pour l'Égypte, qui dépend du Nil à 95 % pour son eau. Les négociations sous égide africaine et onusienne n'ont pas abouti à un accord contraignant, illustrant l'absence de gouvernance internationale de l'eau.</p></div>
""",
'physique/risques-naturels': """
<h3>La vulnérabilité et la construction sociale du risque</h3>
<p class="resume-text">Le risque naturel n'est pas qu'un phénomène géophysique : il est le produit de l'interaction entre un <strong>aléa</strong> (l'événement naturel potentiel) et une <strong>vulnérabilité</strong> (l'exposition et la fragilité des sociétés). Un séisme de même magnitude fera des milliers de morts en Haïti ou quelques dizaines en Californie — non parce que l'aléa diffère, mais parce que les constructions, les systèmes d'alerte, les capacités de réponse et la pauvreté structurelle diffèrent. Le tremblement de terre de Haïti (2010, magnitude 7,0) a tué 220 000 personnes ; celui de Christchurch, Nouvelle-Zélande (2011, magnitude 6,3), 185 personnes.</p>
<p class="resume-text">La théorie de l'amplification sociale du risque (Kasperson, 1988) montre que le risque perçu est façonné par les médias, les institutions et les réseaux sociaux, pouvant amplifier ou atténuer l'aléa objectif. La couverture médiatique intense d'une catastrophe naturelle augmente les donations humanitaires mais oriente aussi l'attention politique vers des risques médiatisés au détriment d'autres (sécheresses chroniques, érosion côtière lente) moins spectaculaires mais plus coûteux en vies sur la durée. La gestion des risques naturels est donc autant une question de communication et de gouvernance que de géophysique.</p>
""",
'humaine/urbanisation': """
<h3>Les mégapoles du Sud et les défis de l'urbanisation rapide</h3>
<p class="resume-text">Le XXIe siècle est le premier siècle majoritairement urbain de l'histoire humaine : en 2007, la population urbaine mondiale a dépassé la population rurale pour la première fois. Cette transition se déroule essentiellement dans les pays du Sud : Lagos, Kinshasa, Dhaka, Karachi concentrent des dizaines de millions d'habitants, souvent dans des conditions précaires. Lagos, qui n'existait pratiquement pas comme ville en 1950 (300 000 habitants), compte aujourd'hui plus de 15 millions d'habitants et pourrait dépasser 100 millions d'ici 2100 selon certaines projections — devenant l'une des plus grandes agglomérations jamais existées.</p>
<p class="resume-text">Les <strong>bidonvilles</strong> (slums, favelas, katchi abadis) abritent aujourd'hui plus d'un milliard de personnes, soit un sixième de l'humanité. Ces espaces informels, longtemps perçus comme pathologies à éradiquer, sont aujourd'hui mieux compris comme modes d'urbanisation par le bas, avec une économie locale dynamique et des formes d'auto-organisation sociale remarquables. Dharavi à Mumbai (1 million d'habitants sur 2,4 km²) génère un milliard de dollars de revenus informels annuels via le recyclage, le cuir, la poterie et la nourriture. Les politiques de rénovation brutale qui rasent ces quartiers sans relogement approprié détruisent du capital social et économique difficilement reconstituable.</p>
<div class="highlight-box"><p><strong>L'étalement urbain :</strong> Les villes américaines consomment en moyenne 8 fois plus d'espace par habitant que les villes européennes de même taille, en raison de la dépendance à l'automobile et du zonage monofunctional (résidentiel/commercial/industriel strictement séparés). Phoenix, Arizona (5 millions d'habitants) s'étend sur une superficie équivalente à la Suisse, avec une dépendance à 95 % à la voiture individuelle — modèle urbain aux coûts énergétiques et environnementaux élevés.</p></div>
""",
'physique/climatologie': """
<h3>Les rétroactions climatiques et la sensibilité climatique</h3>
<p class="resume-text">La sensibilité climatique — le réchauffement attendu pour un doublement des concentrations de CO₂ — est estimée entre 2,5°C et 4°C (valeur probable, GIEC AR6 2021). Cette incertitude reflète les <strong>rétroactions climatiques</strong> : mécanismes qui amplifient (rétroactions positives) ou atténuent (rétroactions négatives) le réchauffement initial. La rétroaction vapeur d'eau (l'air plus chaud contient plus de vapeur d'eau, un puissant gaz à effet de serre) amplifie le réchauffement d'un facteur 2. La rétroaction glace-albédo (la fonte des glaces expose des surfaces plus sombres qui absorbent plus de chaleur) amplifie encore. Les nuages constituent la principale incertitude : les nuages bas peuvent refroidir (réfléchissent le solaire) ou réchauffer (piègent l'infrarouge) selon leur type et altitude.</p>
<p class="resume-text">Les <strong>points de basculement</strong> (tipping points) sont des seuils au-delà desquels le système climatique bascule irréversiblement vers un nouvel état. La déstabilisation du pergélisol sibérien (libérant 1 500 GtC de carbone organique gelé), l'effondrement de la calotte glaciaire de l'Antarctique occidental (+ 3m de niveau marin), et la mort des récifs coralliens tropicaux (90 % morts au-delà de +1,5°C) sont des points de basculement potentiellement interconnectés : une cascade de basculements pourrait déclencher un réchauffement auto-entretenu dépassant les trajectoires des modèles actuels.</p>
""",
'physique/geomorphologie': """
<h3>Les processus d'érosion et le façonnement des paysages</h3>
<p class="resume-text">L'érosion est le processus par lequel les roches et sols sont désagrégés et transportés. L'<strong>altération mécanique</strong> (gélivation, haloclastie, thermoclastie) fragmente physiquement les roches sans modifier leur composition chimique. L'<strong>altération chimique</strong> (hydrolyse, carbonatation, oxydation) décompose les minéraux en argiles et sels solubles. Dans les régions tropicales humides, l'altération chimique intense produit des latérites (profils d'altération de 30-100 m) qui mobilisent le fer et l'aluminium en surface. Les karsts, façonnés par la dissolution du calcaire, sont un exemple spectaculaire d'altération chimique sculpturale.</p>
<p class="resume-text">Les <strong>glaciers</strong> sont les agents d'érosion les plus puissants : un glacier exerce une pression de 2-10 bars sur son substratum, arrachant des volumes considérables de roche (érosion basale par arrachement et abrasion). Les fjords norvégiens (jusqu'à 1 300 m de profondeur) témoignent de l'érosion glaciaire extrême dans des vallées fluviales préexistantes. La Grande Barrière de corail australienne est paradoxalement préservée par l'érosion : les courants créés par les reliefs sous-marins érodés génèrent l'upwelling de nutriments qui l'alimentent.</p>
""",
'physique/tectonique': """
<h3>Les preuves de la tectonique des plaques</h3>
<p class="resume-text">L'hypothèse de la dérive des continents, proposée par Alfred Wegener en 1912, fut longtemps rejetée par la communauté géologique faute de mécanisme explicatif. La révolution conceptuelle vient des années 1960 avec l'exploration des fonds océaniques : la symétrie magnétique de part et d'autre des dorsales médio-océaniques, enregistrée dans les basaltes lors de leur solidification, est la preuve irréfutable de l'expansion des fonds océaniques (seafloor spreading). Les bandes d'anomalies magnétiques lisibles comme un code-barres permettent de dater les fonds océaniques et de reconstruire les mouvements des plaques sur 180 millions d'années.</p>
<p class="resume-text">La <strong>subduction</strong> — plongée d'une plaque océanique dense sous une plaque continentale plus légère — génère les zones de convergence les plus actives géologiquement : volcans de la Ceinture de feu du Pacifique, fosses océaniques (Fosse des Mariannes : 11 034 m de profondeur), et séismes mégathrust (Sumatra 2004, Magnitude 9,1 ; Japon 2011, M 9,0). La subduction est aussi le moteur du cycle du carbone géologique : les carbonates sédimentaires subductés libèrent du CO₂ volcanique, refermant la boucle du carbone sur des échelles de millions d'années.</p>
""",
'geopolitique/organisations': """
<h3>La crise du multilatéralisme et les organisations régionales</h3>
<p class="resume-text">Le système multilatéral issu de 1945 (ONU, FMI, Banque mondiale, GATT devenu OMC) est sous pression croissante. Le droit de veto au Conseil de sécurité de l'ONU, exercé par la Chine et la Russie pour bloquer les résolutions sur la Syrie (plus de 16 vetos entre 2011 et 2022) et l'Ukraine, rend l'ONU paralysée face aux crises impliquant des membres permanents. L'OMC est dans l'impasse depuis l'échec du Cycle de Doha (2001-) : les négociations multilatérales ont cédé la place à un foisonnement d'accords bilatéraux et régionaux.</p>
<p class="resume-text">Face à l'impasse multilatérale, les organisations régionales prennent du poids. L'Union africaine développe ses propres mécanismes de paix et sécurité. L'ASEAN (Asie du Sud-Est) pratique un multilatéralisme de consensus qui privilégie la non-interférence. Les BRICS+ (Brésil, Russie, Inde, Chine, Afrique du Sud + 6 nouveaux membres depuis 2024) cherchent à construire un ordre multipolaire alternatif à l'hégémonie occidentale, avec notamment un projet de monnaie de réserve alternative au dollar pour les échanges bilatéraux.</p>
""",
'humaine/inegalites': """
<h3>Les inégalités mondiales : tendances récentes</h3>
<p class="resume-text">Les inégalités mondiales présentent des dynamiques contradictoires. Les inégalités <strong>entre pays</strong> ont significativement diminué depuis 1990 grâce au rattrapage économique de la Chine, de l'Inde et d'autres pays émergents : la part de la population mondiale en extrême pauvreté (< 1,90 $/jour) est passée de 36 % en 1990 à 9 % en 2019 (avant COVID). Les inégalités <strong>au sein des pays</strong> ont en revanche augmenté dans la plupart des économies développées et émergentes : le coefficient de Gini américain est passé de 0,39 en 1970 à 0,49 en 2020.</p>
<p class="resume-text">Les travaux de Branko Milanovic (courbe de l'éléphant) illustrent ces dynamiques : de 1988 à 2008, les plus fortes hausses de revenus ont bénéficié aux classes moyennes d'Asie (surtout Chine) et aux ultra-riches mondiaux, tandis que les classes moyennes des pays développés stagnaient. Cette compression des classes moyennes occidentales nourrit les ressentiments anti-élite et la défiance envers la mondialisation. L'inégalité de patrimoine est plus extrême encore : les 1 % les plus riches détiennent 37 % du patrimoine mondial (Credit Suisse 2022), les 50 % les plus pauvres seulement 0,75 %.</p>
""",
'humaine/migrations': """
<h3>Les types de migrations et leurs déterminants</h3>
<p class="resume-text">Les migrations internationales (281 millions de personnes en 2020, soit 3,6 % de la population mondiale) sont portées par un ensemble complexe de <strong>facteurs d'expulsion</strong> (push factors) dans les régions d'origine — pauvreté, chômage, insécurité, changement climatique — et de <strong>facteurs d'attraction</strong> (pull factors) dans les régions de destination — opportunités économiques, réseaux de diaspora, État de droit. Le modèle classique de Lee (1966) schématise ces forces mais sous-estime le rôle des réseaux migratoires : une fois établies, les chaînes migratoires se renforcent par l'information, l'aide à l'installation et le regroupement familial, créant des dynamiques migratoires relativement indépendantes des conditions macro-économiques.</p>
<p class="resume-text">Le changement climatique amplifie les migrations : la montée du niveau marin menace 1 milliard de personnes vivant dans des zones côtières basses d'ici 2100 ; l'extension des zones inhabitables (chaleur humide dépassant le seuil de survie humain) peut affecter des régions densément peuplées d'Asie du Sud et d'Afrique subsaharienne. La Banque mondiale estime que 216 millions de personnes pourraient devenir des migrants climatiques internes d'ici 2050 dans le seul scénario pessimiste. Le statut juridique des « réfugiés climatiques » n'existe pas dans le droit international actuel — lacune que les États insulaires du Pacifique poussent à combler.</p>
""",
}

for key, html in GEO_TOPUPS.items():
    inject(pages_geo, key, html)

save('geographie', data_geo)

short = [(k, len(v.get('content',''))) for k,v in pages_geo.items() if v.get('type') in ['course','lesson'] and len(v.get('content','')) < 15000]
print(f"Geographie: {len(short)} pages still under 15k")
if short:
    for k,n in sorted(short): print(f"  {k}: {n}")

# ═══════════════════════════════════════════════════════════════
# ANTHROPOLOGIE
# ═══════════════════════════════════════════════════════════════
data_anthr = load('anthropologie')
pages_anthr = data_anthr['pages']

ANTHR_TOPUPS = {
'physique/adaptations': """
<h3>Les adaptations physiologiques aux environnements extrêmes</h3>
<p class="resume-text">L'espèce humaine a colonisé pratiquement tous les écosystèmes terrestres grâce à une combinaison d'adaptations génétiques, physiologiques et culturelles. Les populations de haute altitude — Tibétains (plateau tibétain, ~4 500 m), Andins (Altiplano, ~3 800 m) et Éthiopiens (Simien, ~3 000 m) — ont développé des adaptations génétiques distinctes à l'hypoxie chronique. Les Tibétains portent des variants du gène EPAS1 (codant le facteur HIF-2α) hérités des Dénisoviens qui régulent la réponse à l'hypoxie sans élever l'hématocrite — évitant la viscosité sanguine excessive qui affecte les migrants non adaptés.</p>
<p class="resume-text">Les adaptations au froid des populations arctiques incluent un métabolisme basal plus élevé, une distribution différente de la graisse corporelle (favorisant les graisses brunes thermogènes), et des variants génétiques des voies de métabolisme des lipides adaptés aux régimes riches en graisses marines. La règle d'Allen (1877) prédit que les populations des régions froides ont des membres plus courts et un corps plus trapu (réduisant le rapport surface/volume et donc les pertes de chaleur) — tendance visible mais avec de nombreuses exceptions liées aux migrations récentes et aux adaptations culturelles (vêtements, habitats).</p>
<div class="highlight-box"><p><strong>La peau et l'UV :</strong> La pigmentation cutanée est le cas d'école de la sélection naturelle chez Homo sapiens. La mélanine protège des UV-B qui dégradent l'acide folique (essentiel à la fertilité) : sélection de peau foncée sous les tropiques. Mais les UV-B synthétisent également la vitamine D, essentielle au développement osseux et immunitaire : sélection de peau claire en hautes latitudes à faible ensoleillement. La distribution mondiale de la pigmentation cutanée suit précisément le gradient d'intensité UV, avec des exceptions là où l'alimentation compense (peuples arctiques à peau foncée relative car riches en vitamine D marine).</p></div>

<h3>La bipédie et l'évolution du bassin</h3>
<p class="resume-text">La bipédie est la première adaptation anatomique majeure distinguant la lignée humaine des autres primates, précédant le développement cérébral de plusieurs millions d'années. Australopithecus afarensis (Lucy, 3,2 Ma) était bipède malgré un cerveau à peine plus grand que celui d'un chimpanzé. La bipédie libère les mains pour la manipulation et l'outil, mais impose des compromis anatomiques considérables : le bassin féminin humain est le plus étroit du règne animal par rapport à la tête du nouveau-né. Ce dilemme obstétrical a sélectionné une naissance prématurée (le cerveau continue de croître après la naissance) et a rendu l'accouchement un événement social nécessitant de l'aide.</p>
<p class="resume-text">Le pied humain, unique parmi les primates, possède une voûte plantaire longitudinale et transversale qui absorbe les chocs et emmagasine l'énergie élastique lors de la marche et de la course. Les tendons du pied (achilléen, plantaire) fonctionnent comme des ressorts, restituant 50 % de l'énergie à chaque foulée. Les études biomécaniques montrent que la course à pied à longue distance chez Homo sapiens — persistence hunting (chasse à l'épuisement) — est une spécialisation évolutive unique parmi les primates, rendue possible par cette architecture podologique et les glandes sudoripares eccrine permettant la thermorégulation à l'effort.</p>

<h3>Les maladies évolutives et la médecine darwinienne</h3>
<p class="resume-text">La médecine évolutive (darwinienne) étudie pourquoi la sélection naturelle n'a pas éliminé les maladies. Certaines mutations délétères persistent car elles confèrent un avantage en hétérozygotie : le trait drépanocytaire (hétérozygote) protège contre la malaria en réduisant la survie du <em>Plasmodium</em> dans les globules rouges falciformes ; le génotype HbSS (homozygote) cause une anémie grave. Cette balancing selection maintient des fréquences élevées du gène drépanocytaire dans les populations d'origine africaine ou méditerranéenne où la malaria était endémique.</p>
<p class="resume-text">Les maladies chroniques modernes — diabète de type 2, obésité, maladies cardiovasculaires — peuvent être interprétées via l'<strong>hypothèse du génotype économe</strong> (thrifty genotype) de Neel (1962) : des gènes sélectionnés pour l'efficacité du stockage des graisses lors des famines récurrentes du Paléolithique deviennent délétères en environnement d'abondance alimentaire permanente. Cette inadéquation évolutive (evolutionary mismatch) entre notre génome adapté aux environnements ancestraux et notre mode de vie moderne est un cadre conceptuel unificateur pour de nombreuses pathologies contemporaines.</p>
""",
'physique/primatologie': """
<h3>Les sociétés de primates et leurs structures sociales</h3>
<p class="resume-text">La primatologie comparative révèle une diversité remarquable de structures sociales chez les grands singes. Les chimpanzés (<em>Pan troglodytes</em>) vivent en fission-fusion : la communauté de 30 à 150 individus se divise en sous-groupes variables selon les ressources. Les mâles dominent et forment des coalitions politiques complexes (sens propre de Frans de Waal dans <em>Politique Chimpanzé</em>, 1982). Les bonobos (<em>Pan paniscus</em>) présentent une dominance femelle et une société plus égalitaire, où les tensions sont régulées par des comportements sexuels fréquents (GG-rubbing entre femelles, copulations péno-péniennes entre mâles). Ces deux espèces équidistantes génétiquement de l'humain illustrent que nos ancêtres communs pouvaient exprimer des gammes comportementales aussi différentes.</p>
<p class="resume-text">Les gorilles (<em>Gorilla gorilla</em> et <em>G. beringei</em>) vivent en harems : un mâle dos argenté (silverback) et son groupe de femelles et jeunes. Le dimorphisme sexuel extrême (mâles 2x plus lourds) est une signature de la compétition entre mâles pour l'accès aux femelles. Les orangs-outans (<em>Pongo pygmaeus</em> et <em>P. abelii</em>) sont les seuls grands singes quasi-solitaires en dehors des périodes de reproduction, adaptés à des ressources forestières dispersées. Les gibbons (<em>Hylobatidae</em>), parents plus éloignés, vivent en couples monogames avec vocalises territoriales duetées — le seul exemple de monogamie chantée chez les primates non humains.</p>
<div class="highlight-box"><p><strong>La cognition chez les primates :</strong> Les chimpanzés utilisent des outils variés : pierres pour casser des noix (transmission culturelle documentée sur 4 300 ans par les dépôts archéologiques en Côte d'Ivoire), bâtons pour extraire les termites, feuilles comme éponges ou tampons. Ils reconnaissent leur image dans un miroir, comprennent la perspective d'autrui, et peuvent apprendre jusqu'à 400 symboles lexicaux (Kanzi le bonobo). Ces capacités montrent que les fondements de la cognition humaine ont des précurseurs primatiens bien caractérisés.</p></div>

<h3>Le registre fossile et l'évolution humaine</h3>
<p class="resume-text">L'évolution humaine est loin du schéma linéaire « singe → homme » : c'est un buisson phylogénétique dense avec de nombreuses espèces contemporaines et des hybridations interspécifiques. Outre Homo sapiens, au moins 5 espèces humaines coexistaient il y a 40 000 ans : Homo neanderthalensis en Europe et au Moyen-Orient, Homo denisova en Asie, Homo floresiensis à Florès (Indonésie), Homo luzonensis aux Philippines, et Homo naledi en Afrique du Sud. Les analyses d'ADN ancien révèlent que les ancêtres d'Homo sapiens ont eu des enfants avec les Néandertaliens (2-4 % du génome des non-Africains), les Dénisoviens (4-6 % en Mélanésie), et probablement d'autres espèces encore non identifiées.</p>
<p class="resume-text">La question de l'origine d'Homo sapiens moderne reste débattue. Le modèle « Out of Africa récent » (OAA) est largement soutenu par la génomique : une sortie d'Afrique ~65-70 000 ans BP. Mais des fossiles d'Homo sapiens archaïque datant de 300 000 ans en Afrique du Nord (Jebel Irhoud, Maroc) et de potentiels passages multiples hors d'Afrique compliquent le schéma. L'évolution humaine est un processus en réseau, non linéaire, avec des flux géniques répétés entre populations géographiquement séparées qui se rejoignaient périodiquement lors des changements climatiques.</p>
""",
'archeologie/datation': """
<h3>Les méthodes de datation et leurs domaines de validité</h3>
<p class="resume-text">La datation archéologique mobilise des méthodes aux fenêtres temporelles complémentaires. La <strong>dendrochronologie</strong> (datation par les cernes du bois) offre une précision à l'année prés pour les objets en bois conservé, avec des séquences maîtresses remontant à 14 000 ans pour le chêne européen. La <strong>palynologie</strong> (analyse des pollens fossiles dans les sédiments) reconstruit l'histoire de la végétation et du climat sur des centaines de milliers d'années. La <strong>thermoluminescence</strong> (TL) et l'<strong>OSL</strong> (optically stimulated luminescence) datent la dernière exposition à la lumière ou à la chaleur de minéraux — permettant de dater des poteries (TL) ou des sédiments de plage (OSL) sur 500 000 ans.</p>
<p class="resume-text">L'<strong>uranium-thorium</strong> (ou U-Th, déséquilibre radioactif) date les spéléothèmes (stalagmites, stalactites) et les coraux sur 500 000 ans avec une précision de ±1-2 %. La peinture de la grotte de Cueva de los Aviones (Espagne), datée à 115 000 ans par U-Th sur la croûte carbonatée recouvrant les pigments, est la plus ancienne œuvre d'art humaine actuellement connue — antérieure à l'arrivée d'Homo sapiens en Europe, ce qui indiquerait une production par des Néandertaliens. Cette découverte a bouleversé notre compréhension des capacités symboliques des Néandertaliens.</p>
""",
'archeologie/prehistoire': """
<h3>Le Néolithique et la révolution agricole</h3>
<p class="resume-text">La transition du Paléolithique au Néolithique (12 000-4 000 BP selon les régions) est souvent présentée comme un progrès linéaire, mais les données archéologiques et paléobiologiques dressent un tableau plus nuancé. Les premiers agriculteurs du Proche-Orient (croissant fertile) avaient en réalité une alimentation moins variée et moins nutritive que les chasseurs-cueilleurs contemporains, étaient plus sujets aux maladies infectieuses (zoonoses, densité de population), et travaillaient davantage d'heures quotidiennes. L'adoption de l'agriculture s'est souvent faite sous contrainte démographique ou environnementale plutôt que par choix rationnel.</p>
<p class="resume-text">La diffusion de l'agriculture en Europe (de 9 000 à 5 000 BP, du Proche-Orient vers l'Atlantique) est aujourd'hui mieux comprise grâce à la paléogénomique. Des populations distinctes ont joué des rôles complémentaires : les agriculteurs anatoliens qui migrent en Europe et « remplacent » largement les chasseurs-cueilleurs mésolithiques (en termes génétiques), les populations des steppes pontiques (Yamna) qui apportent plus tard les langues indo-européennes et des innovations comme le cheval domestique, le chariot à roues et la métallurgie du bronze — un cocktail de révolutions technologiques qui transforme les sociétés européennes entre 3 000 et 2 000 avant notre ère.</p>
""",
'archeologie/methodes': """
<h3>La stratigraphie et le principe de superposition</h3>
<p class="resume-text">La stratigraphie archéologique repose sur le principe de superposition de Steno (1669) : les couches les plus profondes sont en général les plus anciennes. Sur un site archéologique, les couches (strates) se déposent successivement, piégeant les artefacts contemporains de leur formation. La lecture stratigraphique permet donc une chronologie relative : les objets de la couche 4 sont plus anciens que ceux de la couche 3, indépendamment de toute datation absolue. Les <strong>locus</strong> (unités de fouille spatiales) et les <strong>US</strong> (unités stratigraphiques) constituent le vocabulaire opérationnel de la fouille archéologique systématique.</p>
<p class="resume-text">La fouille par décapage à la truelle ou au pinceau, couche par couche, est la méthode standard pour les sites complexes. Elle est complétée par des <strong>méthodes géophysiques non invasives</strong> : la prospection électromagnétique (magnétomètre) détecte les anomalies magnétiques des structures de combustion ; le géoradar (GPR) révèle les structures souterraines jusqu'à 2-3 m de profondeur par réflexion d'ondes radio. La prospection LiDAR aérienne a révolutionné l'archéologie du paysage : en filtrant numériquement la végétation des nuages de points LiDAR, elle révèle des structures archéologiques invisibles au sol — comme les cités mayas cachées sous la forêt du Petén guatémaltèque (découverte PACUNAM LiDAR Initiative, 2018 : 60 000 structures dont des cités inconnues).</p>
""",
'ethnologie/terrain': """
<h3>Les défis éthiques de l'ethnographie contemporaine</h3>
<p class="resume-text">L'enquête ethnographique de terrain, héritée de Bronisław Malinowski (Trobriand, 1914-1918), a été profondément transformée par les critiques postcoloniales. Talal Asad, Edward Said et les représentants des <em>Writing Culture</em> (Clifford & Marcus, 1986) ont remis en question l'autorité épistémique de l'ethnographe occidental décrivant des populations du « Sud » comme objets passifs d'étude. Ces critiques ont imposé de nouvelles pratiques : obtention du consentement éclairé des communautés, co-production de la recherche avec les acteurs locaux, restitution des résultats aux populations concernées, et réflexivité explicite sur les effets de la posture et des identités de chercheur.</p>
<p class="resume-text">L'<strong>ethnographie multi-sites</strong> (Marcus, 1995) suit un objet, un problème ou une relation à travers différents lieux géographiques plutôt que de se concentrer sur une communauté locale isolée. Elle est adaptée à l'étude des phénomènes de globalisation, des diasporas, des réseaux transnationaux et des flux culturels — questions que l'ethnographie de site fixe ne pouvait saisir. L'ethnographie numérique et en ligne, imposée par les conditions de la pandémie COVID-19, a généré un vaste débat sur la nature du terrain « à distance » et la perte des données incarnées que seule la coprésence physique permet de collecter.</p>
""",
'ethnologie/mondialisation': """
<h3>L'hybridation culturelle et la créolisation</h3>
<p class="resume-text">Face à la mondialisation, les approches homogénéisation (convergence vers une culture globale américanisée) et différentialiste (essentialisation des cultures locales figées) sont toutes deux dépassées. Le concept d'<strong>hybridation culturelle</strong> (Homi Bhabha, Néstor García Canclini) décrit les mélanges syncrétiques qui émergent aux intersections culturelles : le rap brésilien (funk carioca), le christianisme syncrétiste (Candomblé, Pentecôtisme africain), la cuisine tex-mex ou les arts martiaux afro-brésiliens (capoeira) sont des hybrides qui ne sont ni purement locaux ni purement globaux mais des créations originales nées du contact.</p>
<p class="resume-text">L'anthropologue Arjun Appadurai propose le concept de <strong>scapes</strong> pour analyser les flux globaux : ethnoscapes (mouvements de populations), mediascapes (flux médiatiques), technoscapes (diffusion technologique), finanscapes (flux financiers) et ideoscapes (flux d'idéologies). Ces scapes circulent de manière disjunctive — différentes vitesses, différentes directions selon les régions — créant des paysages culturels locaux complexes impossibles à réduire au choc de cultures monolithiques ou à une convergence uniforme vers un modèle unique.</p>
""",
'ethnologie/urbaine': """
<h3>L'anthropologie urbaine et l'étude des cultures de quartier</h3>
<p class="resume-text">L'École de Chicago (années 1920-1940) fonde l'anthropologie urbaine en appliquant les méthodes ethnographiques aux espaces urbains industriels : Robert Park, Ernest Burgess et Louis Wirth étudient les ghettos, les zones d'immigration et les cultures de rue de Chicago comme autant de communautés à ethnographier. Leur modèle des « zones concentriques » décrit la ville comme un ensemble d'anneaux de transition — zone industrielle centrale, ceintures résidentielles de différentes classes, banlieues aisées à la périphérie. Ce modèle, critiqué pour son biais centrocentrique, reste une référence dans la sociologie et l'anthropologie urbaines.</p>
<p class="resume-text">L'anthropologie des espaces publics urbains révèle comment les usages de ces espaces sont négociés, contestés et symboliquement chargés. L'étude des <strong>non-lieux</strong> (Marc Augé) — aéroports, hôtels, centres commerciaux — analyse des espaces de transit déconnectés de toute identité locale et sociale, symptômes d'une modernité de passage. En contrepoint, les travaux sur les marchés traditionnels, les fêtes de quartier et les graffitis soulignent la résistance des usages enracinés et la capacité des citadins à réapproprier symboliquement les espaces standardisés.</p>
""",
'archeologie/contemporaine': """
<h3>L'archéologie des conflits et les sites de mémoire</h3>
<p class="resume-text">L'archéologie contemporaine inclut l'étude matérielle des événements récents, y compris les conflits du XXe siècle. L'<strong>archéologie des champs de bataille</strong> de la Première Guerre mondiale — tranchées, no man's land, dépôts de munitions — est une discipline active qui combine fouilles archéologiques et identification des soldats via l'ADN ancien. Les travaux des équipes belges, françaises et allemandes sur le front de l'Yser ou la Somme révèlent les conditions matérielles de vie et de mort dans les tranchées avec une précision que les archives écrites ne peuvent égaler.</p>
<p class="resume-text">L'archéologie des camps de concentration (Sobibor, Auschwitz, Treblinka) est une démarche délicate, à l'intersection de l'éthique mémorielle et de la méthode scientifique. Les fouilles à Sobibor (2007-2012) ont retrouvé les fondations des chambres à gaz et les effets personnels des victimes, apportant des preuves archéologiques aux procès de négationnistes. Ces travaux illustrent comment l'archéologie peut contribuer à la justice transitionnelle et à la constitution de la mémoire collective, tout en soulevant des questions éthiques sur la perturbation de sites funéraires et les droits des descendants.</p>
""",
'ethnologie/autochtones': """
<h3>Les droits autochtones et la déclaration de l'ONU</h3>
<p class="resume-text">La Déclaration des Nations Unies sur les droits des peuples autochtones (DNUDPA, 2007), adoptée par 144 États, représente une avancée normative majeure pour les 476 millions d'autochtones (6 % de la population mondiale, 15 % des plus pauvres). Elle consacre le droit au consentement libre, préalable et éclairé (CLPE) pour tout projet affectant les territoires autochtones, le droit à l'autodétermination et à l'autogouvernance, et la protection des savoirs traditionnels. Son application reste très inégale : les États-Unis, le Canada, l'Australie et la Nouvelle-Zélande, qui avaient voté contre en 2007 (avant de se rallier), appliquent partiellement ces normes.</p>
<p class="resume-text">Les <strong>savoirs écologiques traditionnels</strong> (Traditional Ecological Knowledge, TEK) des peuples autochtones font l'objet d'une reconnaissance croissante dans les politiques de conservation. Les Maori de Nouvelle-Zélande ont obtenu la personnalité juridique pour la rivière Whanganui (2017) — reconnue comme entité vivante avec des droits propres, représentée par des gardiens légaux. En Amazonie, les territoires autochtones reconnus légalement sont parmi les mieux protégés contre la déforestation, avec un taux de déforestation 4 fois inférieur aux zones non protégées — argument pragmatique pour les droits autochtones au-delà de la justice culturelle.</p>
""",
'ethnologie/monographies': """
<h3>La monographie entre documentation et interprétation</h3>
<p class="resume-text">La monographie ethnographique est le genre central de la production anthropologique. Des œuvres fondatrices comme <em>Les Argonautes du Pacifique occidental</em> de Malinowski (1922), <em>The Nuer</em> d'Evans-Pritchard (1940) et <em>La Pensée sauvage</em> de Lévi-Strauss (1962) ont chacune défini une école méthodologique et théorique. L'évolution du genre reflète les mutations épistémologiques de la discipline : la monographie réaliste classique (l'ethnographe témoigne des « faits ») laisse place à des formes polyphoniques (voix multiples, y compris celles des « informateurs »), dialogiques et réflexives (l'ethnographe est lui-même un objet d'analyse).</p>
<p class="resume-text">Les <strong>controverses sur la représentation</strong> illustrent les enjeux éthiques de la monographie. Les descendants des Samoans d'étude de Margaret Mead ont contesté ses conclusions sur la sexualité adolescente tahitienne (<em>Coming of Age in Samoa</em>, 1928), accusant Derek Freeman (qui les réfuta en 1983) et Mead d'avoir tous deux projeté leurs biais sur les données. Le cas Mead/Freeman est un cas d'école des problèmes d'interprétation dans les sciences humaines et de la difficulté à vérifier des ethnographies fondées sur des interviews uniques non enregistrées dans des contextes culturellement complexes.</p>
""",
'archeologie/civilisations': """
<h3>Les grandes civilisations fluviales et leurs systèmes agraires</h3>
<p class="resume-text">Les premières civilisations urbaines émergent indépendamment dans au moins cinq régions entre 6 000 et 2 000 BP : Mésopotamie (Tigre et Euphrate), Nil, Indus, fleuve Jaune et Huang He, et (plus tard) Mésoamérique et Andes. Ces «  hydraulic civilizations » selon le concept de Karl Wittfogel nécessitent une gestion centralisée des systèmes d'irrigation pour maximiser la production agricole en zones semi-arides — ce qui favoriserait l'émergence d'États bureaucratiques despotiques contrôlant l'eau. Cette théorie hydraulique, bien qu'en partie réfutée (les irrigations mésopotamiennes précoces semblent décentralisées), capture une réalité : la maîtrise de l'eau crée des interdépendances qui poussent à la coordination politique.</p>
<p class="resume-text">La civilisation de l'Indus (Harappa et Mohenjo-daro, 2 600-1 900 BCE) reste l'une des plus mystérieuses : des dizaines de cités planifiées avec égouts, bains publics et grilles urbaines, mais aucun palais ni temple identifié, et une écriture toujours non déchiffrée. Leur déclin (~1 900 BCE) coïncide avec des preuves paléoclimatiques d'une sécheresse de plusieurs décennies liée à l'affaiblissement de la mousson — suggérant une vulnérabilité climatique comparable à celle des effondrements ultérieurs de la Méditerranée de l'Âge du Bronze (~1 200 BCE) et de l'Empire Maya classique (~900 CE).</p>
""",
'physique/genetique': """
<h3>La paléogénomique et la reconstruction des migrations humaines</h3>
<p class="resume-text">La révolution de l'ADN ancien, permise par le séquençage à haut débit depuis 2010, a transformé notre compréhension de la préhistoire humaine. Le laboratoire de Svante Pääbo (prix Nobel 2022) a séquencé le génome complet de Néandertaliens et Dénisoviens à partir d'ossements de 40 000-130 000 ans. Depuis, plus de 10 000 génomes anciens ont été séquencés, permettant de reconstituer les migrations, les brassages génétiques et les expansions démographiques avec une précision historique.</p>
<p class="resume-text">Ces données révèlent des événements migratoires majeurs invisibles dans les archives écrites : l'arrivée massive des populations des steppes pontiques en Europe (~3 000 BCE) qui apportent les langues indo-européennes et représentent jusqu'à 75 % de l'ascendance génétique des Européens du Nord actuels. La <strong>dispersion austronésienne</strong> — à partir de Taiwan vers toutes les îles du Pacifique — est retracée génétiquement avec une précision de quelques siècles, reconstituant les étapes de la plus grande expansion maritime préhistorique. Des cas d'admixture inattendue (gènes dénisoviens dans les populations d'Asie du Sud-Est insulaire, gènes néandertaliens dans certaines populations africaines via retour) complexifient continûment le schéma de l'évolution humaine.</p>
""",
}

for key, html in ANTHR_TOPUPS.items():
    inject(pages_anthr, key, html)

save('anthropologie', data_anthr)

short_a = [(k, len(v.get('content',''))) for k,v in pages_anthr.items() if v.get('type') in ['course','lesson'] and len(v.get('content','')) < 15000]
print(f"Anthropologie: {len(short_a)} pages still under 15k")
if short_a:
    for k,n in sorted(short_a): print(f"  {k}: {n}")

# ═══════════════════════════════════════════════════════════════
# SOCIOLOGIE
# ═══════════════════════════════════════════════════════════════
data_soc = load('sociologie')
pages_soc = data_soc['pages']

SOC_TOPUPS = {
'structures/inegalites': """
<h3>Les nouvelles formes d'inégalités : numérique et écologique</h3>
<p class="resume-text">Les inégalités contemporaines prennent de nouvelles formes inédites. La <strong>fracture numérique</strong> superpose des lignes de clivage sociales classiques (âge, revenu, capital culturel) : les 18-34 ans qualifiés utilisent le numérique comme multiplicateur de capital humain et social, tandis que les moins qualifiés et les seniors risquent l'exclusion des démarches administratives, de l'emploi et des relations sociales de plus en plus médiatisées en ligne. La <strong>dette de données</strong> — le prix de l'attention et des données personnelles que les plateformes extractent des utilisateurs — est inégalement conscientisée et négociée selon le capital culturel.</p>
<p class="resume-text">Les inégalités <strong>environnementales</strong> (environmental justice) articulent classe sociale, race et exposition aux nuisances écologiques. Les quartiers populaires et les communautés racisées sont surexposés à la pollution atmosphérique, aux sites industriels dangereux et aux risques d'inondation. À New York, les quartiers noirs et latinos ont subi une surmortalité COVID-19 deux fois plus élevée que les quartiers blancs aisés — effet combiné de conditions de logement (surpopulation), d'emplois essentiels non télétravaillables, et de comorbidités liées aux inégalités sanitaires chroniques. La transition énergétique risque elle-même de reproduire ces inégalités si les coûts de la décarbonation pèsent plus lourdement sur les ménages modestes.</p>
""",
'structures/classes-sociales': """
<h3>La recomposition des classes sociales à l'ère numérique</h3>
<p class="resume-text">La structure des classes sociales dans les économies développées connaît des transformations profondes depuis les années 1980. La désindustrialisation a érodé la classe ouvrière traditionnelle (ouvriers industriels qualifiés et syndiqués) au profit d'une « new working class » de services précaires (livreurs, aides à domicile, travailleurs de plateforme). Ces emplois sont souvent excluus de la protection syndicale, fragmentés géographiquement et temporellement, et masqués derrière le statut juridique d'« indépendant » — ce que Guy Standing appelle le <strong>précariat</strong> : une nouvelle classe caractérisée par l'insécurité chronique et la perte des acquis sociaux des travailleurs industriels.</p>
<p class="resume-text">La <strong>nouvelle bourgeoisie culturelle</strong> (Bourdieu) ou <strong>classe créative</strong> (Richard Florida) — professionnels de l'information, de la culture, des technologies et des services avancés — occupe une position ambiguë : revenus élevés mais parfois patrimoine limité, capital culturel supérieur au capital économique, valeurs cosmopolites progressistes mais comportements résidentiels ségrégationnistes (gentrification). L'étude des trajectoires sociales dans le numérique révèle que la « disruption » technologique reproduit souvent les inégalités d'accès aux ressources scolaires et sociales : les startups de la Silicon Valley sont fondées à 85 % par des hommes blancs ou asiatiques issus de familles aisées.</p>
""",
'fondements/socialisation': """
<h3>La socialisation différentielle selon le genre et la classe</h3>
<p class="resume-text">La socialisation n'est pas neutre : elle transmet différemment selon le genre et la classe sociale. Les recherches en sociologie de l'enfance documentent comment les garçons sont orientés vers l'extérieur, l'autonomie et la prise de risque, tandis que les filles sont socialisées vers le soin, la conformité et l'expression émotionnelle — dès la naissance, via le choix des prénoms, des vêtements, des jouets et des comportements valorisés. Ces différences de socialisation anticipent les assignations de rôles adultes (division sexuelle du travail, soin domestique) et persistent en dépit des transformations légales et des discours d'égalité.</p>
<p class="resume-text">Annette Lareau (<em>Unequal Childhoods</em>, 2003) distingue deux styles d'éducation selon la classe sociale : la <strong>cultivation concertée</strong> des classes moyennes supérieures (activités parascolaires structurées, dialogue argumentatif, apprentissage de la négociation avec les adultes en autorité) et la <strong>croissance naturelle</strong> des classes populaires (jeu libre, respect de la hiérarchie adulte, moins d'activités organisées). Ces différences de socialisation créent un capital institutionnel inégal : les enfants de classes moyennes supérieures apprennent à naviguer les institutions scolaires et professionnelles avec aisance, avantage cumulatif sur toute la trajectoire de vie.</p>
""",
'culture/medias-opinion': """
<h3>L'ère des plateformes et les nouvelles dynamiques de l'opinion</h3>
<p class="resume-text">La montée en puissance des réseaux sociaux (Facebook, Twitter/X, TikTok, YouTube) a transformé la production, la distribution et la consommation de l'information médiatique. Les <strong>algorithmes de recommandation</strong>, optimisés pour l'engagement (temps passé, clics, partages), favorisent structurellement les contenus émotionnellement chargés, controversiaux et simplificateurs. Eli Pariser a popularisé le concept de « filtre bulle » (2011) : les algorithmes personnalisent les flux au point que chaque utilisateur vit dans un univers informationnel distinct, ne voyant que des contenus confortant ses vues préexistantes.</p>
<p class="resume-text">Les <strong>fausses nouvelles</strong> (fake news, désinformation) se diffusent 6 fois plus vite que les vraies nouvelles sur Twitter, selon une étude du MIT (Vosoughi et al., 2018) portant sur 126 000 nouvelles partagées par 3 millions d'utilisateurs. Les contenus faux sont plus « nouveaux » (surprenants, incongruents avec les attentes) et suscitent plus de réactions émotionnelles — mécanismes de base de la psychologie attentionnelle exploités par l'économie de l'attention des plateformes. Les démocraties font face à un défi inédit : concilier la liberté d'expression, la protection contre la désinformation et la gouvernance d'acteurs privés dont le pouvoir d'influence dépasse celui de tous les médias traditionnels réunis.</p>
""",
'structures/institutions': """
<h3>Les institutions en crise : défiance et délégitimation</h3>
<p class="resume-text">La confiance dans les institutions (gouvernements, partis, médias, Églises, science) est en déclin structurel depuis les années 1980 dans la plupart des démocraties occidentales. L'<strong>Edelman Trust Barometer</strong> (annuel depuis 2001) documente cette érosion : en France, la confiance dans le gouvernement est passée de 58 % en 2011 à 29 % en 2023. Plusieurs mécanismes alimentent cette défiance : les scandales répétés (financiers, politiques, religieux) qui révèlent l'écart entre discours institutionnel et pratiques réelles ; la montée du niveau d'éducation qui accroît l'esprit critique ; et la multiplication des contre-pouvoirs (réseaux sociaux, lanceurs d'alerte) qui rendent les scandales plus visibles.</p>
<p class="resume-text">La <strong>théorie néo-institutionnaliste</strong> (DiMaggio et Powell, 1983) distingue trois formes d'isomorphisme par lesquelles les organisations se conforment aux pressions institutionnelles : l'isomorphisme coercitif (conformité aux règles légales), normatif (conformité aux normes professionnelles) et mimétique (imitation des organisations perçues comme légitimes en cas d'incertitude). Cette théorie explique pourquoi des organisations très différentes finissent par se ressembler — convergence des systèmes universitaires vers le modèle américain, homogénéisation des pratiques de gouvernance corporative.</p>
""",
'structures/pouvoir-domination': """
<h3>Les nouvelles formes de domination : numérique et algorithmique</h3>
<p class="resume-text">Le pouvoir algorithmique constitue une forme inédite de domination, analysée par Shoshana Zuboff dans <em>L'Âge du capitalisme de surveillance</em> (2019). Les plateformes numériques transforment les comportements humains en « données comportementales » qui alimentent des « produits de prédiction » vendus à des annonceurs et à des acteurs politiques. Cette extraction de données à la source de l'expérience humaine — et non plus seulement dans les échanges marchands — constitue selon Zuboff une nouvelle forme d'accumulation primitive du capital, comparable à l'enclosure des terres communes au XVIIe siècle.</p>
<p class="resume-text">Michel Foucault avait anticipé ces formes de pouvoir diffus avec ses analyses du <strong>panoptique</strong> (surveillance normalisatrice) et du <strong>biopouvoir</strong> (gouvernement des populations par la norme). Dans les sociétés numériques, la surveillance n'est plus l'apanage de l'État mais est exercée par des acteurs privés (plateformes, assureurs, employeurs) sur des individus qui l'acceptent et parfois la valorisent (likes, abonnés). Byung-Chul Han parle d'une société de « transparence » où chacun s'exhibe volontairement et d'une « psychopolitique » qui gouverne par la stimulation des désirs plutôt que par la répression.</p>
""",
'fondements/fait-social': """
<h3>Le fait social à l'épreuve des neurosciences</h3>
<p class="resume-text">La distinction durkheimienne entre fait social (contrainte extérieure aux individus) et fait psychologique a été challengée par les neurosciences sociales. Les <strong>neurones miroirs</strong> illustrent comment le social est biologiquement incarné : la compréhension des actions d'autrui et la contagion émotionnelle opèrent via des circuits neuraux partagés. Les normes sociales sont encodées dans les mêmes circuits de récompense/punition que les récompenses matérielles (le cortex orbitofrontal et le striatum traitent les approbations et désapprobations sociales comme des signaux de valeur).</p>
<p class="resume-text">Ces données invitent à dépasser l'opposition nature/culture qui structure trop souvent les débats entre sociologie et biologie. Bernard Lahire propose la notion de <strong>singularité sociologique</strong> : chaque individu porte en lui des dispositions socialement constituées mais qui s'articulent différemment selon le contexte. L'individu n'est pas le simple porteur d'habitus de classe mais un être de pluralité, traversé de dispositions parfois contradictoires issues de socialisations multiples (famille, école, pairs, médias) — réconciliant le niveau microsociologique et l'analyse des déterminismes macrostructuraux.</p>
""",
'structures/mobilite-sociale': """
<h3>La mobilité sociale et le paradoxe d'Aron</h3>
<p class="resume-text">La mobilité sociale désigne le déplacement d'un individu dans la hiérarchie sociale, que ce soit intergénérationnel (par rapport à la position parentale) ou intra-générationnel (au cours de sa propre vie). Les tableaux de mobilité, construits à partir d'enquêtes représentatives comparant la profession des individus à celle de leurs parents, sont l'outil standard d'analyse. En France, l'enquête FQP (Formation et Qualification Professionnelle) permet de suivre l'évolution de la mobilité sur plusieurs décennies.</p>
<p class="resume-text">Le <strong>paradoxe d'Aron-Boudon</strong> (ou effet Boudon) : même avec une égalisation des chances scolaires, les inégalités de résultats peuvent persister car les comportements rationnels stratégiques des agents — qui évaluent les coûts et bénéfices des filières selon leur position sociale — reproduisent les inégalités. Les familles de classes populaires, par aversion au risque, choisissent des orientations plus courtes et sûres même avec des résultats scolaires équivalents. La méritocratie scolaire peut ainsi légitimer les inégalités en les attribuant à des choix individuels alors qu'elles sont structurellement déterminées.</p>
""",
'fondements/action-sociale': """
<h3>L'action collective et le problème du passager clandestin</h3>
<p class="resume-text">Mancur Olson (<em>The Logic of Collective Action</em>, 1965) formalise le paradoxe de l'action collective : des individus rationnels maximisant leur intérêt individuel ne s'organisent pas spontanément pour produire des biens collectifs, même lorsqu'ils y auraient tous intérêt. Le <strong>problème du passager clandestin</strong> (free rider) : chacun a intérêt à bénéficier du bien collectif (sécurité nationale, air pur, normes syndicales) sans y contribuer, espérant que les autres prendront les coûts à leur charge. Les syndicats, partis politiques et associations font face à ce problème structurellement.</p>
<p class="resume-text">Elinor Ostrom (prix Nobel d'économie 2009) a réfuté empiriquement le « dilemme des communs » de Hardin en documentant des centaines de cas de gestion collective réussie de ressources communes (pêcheries, forêts, aquifères) par des communautés locales sans privatisation ni régulation étatique. Ses <strong>principes de gestion des communs</strong> — frontières claires, règles adaptées au contexte local, participation à l'élaboration des règles, mécanismes de sanction graduels — offrent un troisième voie entre marché et État pour la gouvernance des biens collectifs. Ces principes sont aujourd'hui appliqués à la gouvernance des biens communs numériques (Wikipedia, logiciels libres).</p>
""",
'fondements/naissance': """
<h3>La naissance de la sociologie et les précurseurs non occidentaux</h3>
<p class="resume-text">L'historiographie de la sociologie a longtemps ignoré les contributions non européennes. <strong>Ibn Khaldoun</strong> (1332-1406), savant tunisien, développe dans sa <em>Muqaddima</em> (Prolégomènes) une théorie des sociétés humaines fondée sur la « asabiyya » (cohésion de groupe, solidarité tribale) qui permettrait aux groupes nomades de conquérir et supplanter les dynasties urbaines affaiblie par le luxe et la sédentarité. Ce cycle Ibn Khaldounien de montée et déclin des dynasties est une théorie sociologique avant la lettre, fondée sur des observations empiriques des sociétés arabes et berbères du XIVe siècle.</p>
<p class="resume-text">La <strong>sociologie américaine noire</strong> est une autre tradition fondatrice occultée : W.E.B. Du Bois (<em>The Philadelphia Negro</em>, 1899) réalise la première étude sociologique empirique d'une communauté urbaine américaine — avec enquête systématique, statistiques et observations de terrain — sept ans avant les premières enquêtes de l'École de Chicago. Sa notion de <strong>double conscience</strong> (the Veil) — la conscience d'être à la fois américain et noir, de se voir à travers les yeux hostiles de l'autre — est un concept psychosociologique fondamental de la pensée du XXe siècle, précurseur des <em>subaltern studies</em> et des études postcoloniales.</p>
""",
'fondements/methodes': """
<h3>La réflexivité et les enjeux épistémiques de la sociologie</h3>
<p class="resume-text">La sociologie est une discipline réflexive : elle doit appliquer à elle-même les analyses qu'elle fait des autres sciences sociales. Bourdieu parle d'<strong>objectivation du sujet objectivant</strong> : le sociologue doit soumettre sa propre position sociale, ses intérêts académiques et ses habitus à la même analyse critique qu'il applique aux groupes étudiés. Cette réflexivité n'est pas un exercice de style mais une condition épistémique : les biais du chercheur (biais de classe, de genre, d'ethnocentrisme) contaminent ses recherches s'il ne les identifie pas explicitement.</p>
<p class="resume-text">Le débat sur les méthodes quantitatives versus qualitatives en sociologie est ancien mais reste vif. Les <strong>enquêtes statistiques</strong> (sondages, recensements, bases de données administratives) permettent de mesurer des tendances structurelles, de tester des hypothèses et de généraliser. Les <strong>méthodes qualitatives</strong> (entretiens, ethnographies, analyses de discours) accèdent aux significations vécues, aux logiques pratiques et aux phénomènes que les indicateurs standardisés occultent. La sociologie contemporaine pratique de plus en plus la <strong>triangulation</strong> — combinaison de plusieurs méthodes — pour compenser les limites de chacune et croiser les niveaux d'analyse.</p>
""",
}

for key, html in SOC_TOPUPS.items():
    inject(pages_soc, key, html)

save('sociologie', data_soc)

short_s = [(k, len(v.get('content',''))) for k,v in pages_soc.items() if v.get('type') in ['course','lesson'] and len(v.get('content','')) < 15000]
print(f"Sociologie: {len(short_s)} pages still under 15k")
if short_s:
    for k,n in sorted(short_s): print(f"  {k}: {n}")

# ═══════════════════════════════════════════════════════════════
# PSYCHOLOGIE
# ═══════════════════════════════════════════════════════════════
data_psy = load('psychologie')
pages_psy = data_psy['pages']

PSY_TOPUPS = {
'sociale/dynamique-groupes': """
<h3>La pensée de groupe et ses conditions</h3>
<p class="resume-text">Le psychologue Irving Janis a analysé en 1972 plusieurs décisions politiques catastrophiques (invasion de Cuba à la Baie des Cochons en 1961, escalade au Vietnam) pour identifier le syndrome de la <strong>pensée de groupe</strong> (groupthink) : un groupe très cohésif et motivé converge vers un consensus illusoire, supprimant les dissensions internes et sous-estimant les risques. Les symptômes incluent l'illusion d'invulnérabilité (« ça ne peut pas nous arriver »), la rationalisation collective des avertissements, la pression sur les dissidents et l'illusion d'unanimité (le silence est interprété comme accord).</p>
<p class="resume-text">Des structures de délibération peuvent prévenir la pensée de groupe : l'avocat du diable (un membre désigné pour contester la position du groupe), les groupes nominaux (génération individuelle d'idées avant la discussion collective), et la technique Delphi (sondages anonymes successifs auprès d'experts dont les résultats agrégés sont diffusés). Ces méthodes présentent l'avantage de préserver la diversité des perspectives tout en permettant leur intégration — des approches de plus en plus utilisées dans la prise de décision organisationnelle et gouvernementale.</p>
<div class="highlight-box"><p><strong>L'équilibre entre cohésion et diversité :</strong> Les groupes performants combinent cohésion sociale (confiance mutuelle, communication fluide) et diversité cognitive (points de vue différents, expertises complémentaires). Trop de cohésion sans diversité produit la pensée de groupe ; trop de diversité sans cohésion produit des conflits stériles. Trouver cet équilibre est l'enjeu central du management d'équipe et de la gouvernance démocratique.</p></div>
""",
'sociale/communication': """
<h3>La communication non verbale et ses fonctions</h3>
<p class="resume-text">La communication non verbale (CNV) transmet des informations socio-émotionnelles que le langage verbal ne peut ou ne doit pas exprimer explicitement. Paul Ekman a identifié six expressions faciales universelles — joie, tristesse, colère, peur, dégoût, surprise — présentes dans toutes les cultures humaines étudiées, y compris des populations non exposées aux médias occidentaux (Fore de Papouasie-Nouvelle-Guinée). Cette universalité suggère un substrat neurobiologique inné de l'expression émotionnelle, hérité de l'évolution des primates sociaux.</p>
<p class="resume-text">La <strong>proxémique</strong>, développée par Edward Hall, étudie les usages culturels de l'espace lors des interactions. Il distingue quatre zones : intime (< 45 cm, famille et partenaires intimes), personnelle (45-120 cm, amis), sociale (1,2-3,6 m, collègues et connaissances), publique (> 3,6 m, discours). Ces distances varient selon les cultures : les Méditerranéens et Latino-Américains maintiennent des distances interactionnelles plus courtes que les Anglo-Saxons ou les Nordiques, source fréquente de malentendus interculturels lors des premières rencontres (l'un avance, l'autre recule).</p>
""",
'sociale/prejudices': """
<h3>La menace du stéréotype et ses effets sur la performance</h3>
<p class="resume-text">Claude Steele et Joshua Aronson ont démontré en 1995 le phénomène de <strong>menace du stéréotype</strong> (stereotype threat) : simplement rappeler à un membre d'un groupe stigmatisé qu'il appartient à ce groupe avant un test suffit à dégrader ses performances, même s'il ne croit pas personnellement au stéréotype. Des étudiants noirs de Stanford, rappelés de leur appartenance raciale avant un test de raisonnement verbal, performaient significativement moins bien que leurs pairs non rappelés — écart qui disparaissait sans le rappel. Ce phénomène affecte les femmes en mathématiques, les personnes âgées en matière de mémoire, et les classes populaires en contexte universitaire.</p>
<p class="resume-text">Les interventions qui réduisent la menace du stéréotype ont été identifiées : les affirmations de soi (écrire sur ses valeurs fondamentales avant le test), la conception de l'intelligence comme malléable (growth mindset de Carol Dweck) et les modèles positifs in-group visibles réduisent la performance penalty. Ces interventions, de faible coût et scalables, ont des effets documentés sur les résultats scolaires des élèves défavorisés et des femmes dans les filières STEM — illustrant comment la psychologie sociale peut informer des politiques éducatives à impact systémique.</p>
""",
}

for key, html in PSY_TOPUPS.items():
    inject(pages_psy, key, html)

save('psychologie', data_psy)

short_p = [(k, len(v.get('content',''))) for k,v in pages_psy.items() if v.get('type') in ['course','lesson'] and len(v.get('content','')) < 15000]
print(f"Psychologie: {len(short_p)} pages still under 15k")
if short_p:
    for k,n in sorted(short_p): print(f"  {k}: {n}")

print("\nAll done!")
