import json

# Second pass enrichments for all RI articles that need more content
ENRICHMENTS2 = {
"conflits/guerres-modernes": """
<h3>La guerre hybride et les zones grises</h3>
<p class="resume-text">La <strong>guerre hybride</strong> combine de façon délibérée des moyens militaires conventionnels, des opérations irrégulières, des actions cybernétiques, des campagnes de désinformation et des pressions économiques pour atteindre des objectifs politiques tout en maintenant une ambiguïté sur la responsabilité des actions. La Russie a théorisé cette approche (doctrine Gerasimov) et l'a mise en pratique en Crimée (2014) et dans le Donbass (2014-2022) : petits hommes verts sans insignes, désinformation massive, soutien aux séparatistes, cyberattaques contre les infrastructures ukrainiennes.</p>
<p class="resume-text">Les <strong>zones grises</strong> désignent des espaces d'affrontement situés en dessous du seuil du conflit armé ouvert mais au-dessus de la compétition diplomatique normale. La Chine utilise ces méthodes en mer de Chine méridionale (milices maritimes, travaux de construction dans les eaux disputées) et Taiwan (harcèlement aérien quotidien). Ces actions sont conçues pour être trop faibles pour justifier une réponse militaire mais suffisamment continues pour modifier le rapport de forces sur le terrain.</p>
<div class="highlight-box"><p>La <strong>cyberguerre</strong> est un domaine de conflit en rapide évolution. Les attaques NotPetya (2017), attribuées à la Russie, ont causé 10 milliards de dollars de dégâts dans le monde entier. La cyberattaque contre les centrifugeuses iraniennes (Stuxnet, 2010) est le premier cas connu de sabotage physique par un logiciel malveillant, considéré comme une opération conjointe USA-Israël.</p></div>
<h3>La privatisation de la guerre : contractors et milices</h3>
<p class="resume-text">Les <strong>sociétés militaires privées</strong> (SMP) jouent un rôle croissant dans les conflits contemporains. Les États-Unis ont massivement utilisé des contractors (Blackwater/Academi, DynCorp, MPRI) en Irak et en Afghanistan : à son apogée, le nombre de contractors américains en Irak dépassait celui des soldats. La Russie a déployé le groupe Wagner en Syrie, en Libye, au Mali, en Centrafrique et au Soudan, offrant une force de déni plausible (deniability) à Moscou. Ces acteurs privés opèrent dans un vide juridique préoccupant : le Statut de Rome sur les mercenaires est mal appliqué et les SMP sont souvent immatriculées dans des paradis juridiques.</p>
""",

"traites/desarmement-nucleaire": """
<h3>Les nouvelles menaces nucléaires et la bombe sale</h3>
<p class="resume-text">Outre les arsenaux étatiques, le <strong>terrorisme nucléaire</strong> constitue une menace prise très au sérieux par les services de renseignement. Le scénario le plus probable n'est pas l'acquisition d'une bombe atomique (qui nécessite des infrastructures industrielles considérables) mais la fabrication d'une <strong>bombe sale</strong> (dirty bomb) : un engin dispersant des matières radioactives à l'aide d'explosifs conventionnels. Bien qu'elle ne provoquerait pas une explosion nucléaire, une telle bombe pourrait créer une panique et contaminer une zone urbaine de façon durable.</p>
<p class="resume-text">Le <strong>Traité sur l'interdiction des armes nucléaires</strong> (TIAN, 2017) a été adopté à l'ONU par 122 États et est entré en vigueur en 2021. Il interdit aux États signataires de développer, tester, posséder, menacer d'utiliser ou permettre le stationnement d'armes nucléaires sur leur territoire. Aucun État doté de l'arme nucléaire, ni aucun membre de l'OTAN, n'a signé ce traité, le considérant comme incompatible avec la dissuasion nucléaire. Ses partisans y voient néanmoins une avancée normative importante pour stigmatiser les armes nucléaires.</p>
<div class="highlight-box"><p>La <strong>conférence d'examen du TNP de 2022</strong> a échoué à adopter un document final, notamment en raison des désaccords sur la centrale nucléaire de Zaporijjia en Ukraine (occupée par la Russie). C'est la troisième conférence d'examen consécutive sans document final, illustrant la crise du régime de non-prolifération.</p></div>
""",

"traites/droits-de-lhomme": """
<h3>La mise en oeuvre des droits humains : le fossé entre normes et réalité</h3>
<p class="resume-text">Le défi majeur du droit international des droits humains est l'écart entre les normes adoptées et leur application effective. Les mécanismes de contrôle (comités conventionnels, rapporteurs spéciaux, EPU) produisent des recommandations mais manquent de pouvoir coercitif. Les États acceptent ou rejettent les recommandations selon leurs intérêts politiques. Les grandes puissances (Chine, Russie, États-Unis) utilisent leur influence pour bloquer les initiatives qui les visent au Conseil des droits de l'homme.</p>
<p class="resume-text">La <strong>responsabilité de protéger</strong> (R2P), adoptée par le Sommet mondial de l'ONU en 2005, établit que la communauté internationale a la responsabilité d'intervenir pour protéger les populations lorsque leur État faillit à cette obligation (génocide, crimes contre l'humanité, crimes de guerre, nettoyage ethnique). L'intervention en Libye (2011), autorisée par le Conseil de sécurité au titre de la R2P, a été controversée : ce qui commença comme une zone d'exclusion aérienne est devenu un changement de régime, poussant la Russie et la Chine à bloquer toute nouvelle résolution similaire sur la Syrie.</p>
<div class="highlight-box"><p>La <strong>Cour pénale internationale</strong> (CPI) a émis des mandats d'arrêt contre des chefs d'État en exercice : Omar el-Béchir du Soudan (2009, pour génocide et crimes contre l'humanité au Darfour) et Vladimir Poutine de Russie (2023, pour déportation illégale d'enfants ukrainiens). Ces mandats restent symboliques tant que les accusés ne sont pas livrés à la Cour, mais ils limitent leurs déplacements internationaux.</p></div>
""",

"traites/droit-de-la-mer": """
<h3>La liberté de navigation et ses contestations</h3>
<p class="resume-text">La <strong>liberté de navigation</strong> en haute mer et dans les ZEE est un principe fondamental du droit de la mer, vital pour le commerce mondial (90% du commerce international transite par la mer). Les États-Unis conduisent régulièrement des opérations de liberté de navigation (Freedom of Navigation Operations, FONOPS) dans les eaux contestées de la mer de Chine méridionale pour y affirmer le droit de passage innocent ou de transit, en défiant les revendications chinoises. Ces opérations provoquent des incidents et des escarmouches maritimes récurrents.</p>
<p class="resume-text">La <strong>piraterie maritime</strong> reste un défi à la sécurité maritime mondiale, malgré le recul spectaculaire des attaques somalies depuis 2011 grâce aux opérations navales internationales (EU Atalanta, OTAN, coalition multinationale). Les attaques des Houthis yéménites contre des navires commerciaux en mer Rouge (2023-2024), en soutien à Gaza, ont forcé de nombreux armateurs à éviter le canal de Suez et à contourner l'Afrique, perturbant les chaînes d'approvisionnement mondiales et renchérissant les coûts de transport.</p>
<div class="highlight-box"><p>Le <strong>détroit de Malacca</strong> (entre Malaisie, Singapour et Indonésie) est l'un des détroits les plus stratégiques du monde : 40% du commerce maritime mondial y transite, dont 80% des importations pétrolières du Japon et de la Corée du Sud. Sa fermeture hypothétique forcerait un détour de plusieurs milliers de kilomètres via le détroit de Lombok ou de Makassar.</p></div>
""",

"organisations-internationales/organisations-regionales": """
<h3>L'OEA et les défis démocratiques en Amérique latine</h3>
<p class="resume-text">L'<strong>Organisation des États américains</strong> (OEA, 35 membres) est l'organisation régionale la plus ancienne au monde (Charte de Bogotá, 1948). Elle est dotée d'une Charte démocratique interaméricaine (2001) permettant la suspension d'un membre dont le gouvernement démocratique serait renversé. Venezuela, Nicaragua et Cuba posent des défis récurrents à la crédibilité démocratique de l'OEA. La Mission d'observation électorale de l'OEA joue un rôle important dans la certification des élections régionales.</p>
<p class="resume-text">La <strong>Ligue arabe</strong> (22 membres, fondée au Caire en 1945) a souvent été paralysée par les divisions inter-arabes. Les Printemps arabes (2010-2011) l'ont mise à l'épreuve : la Ligue a soutenu l'intervention en Libye (résolution historique) mais a été divisée sur la Syrie. Les Accords d'Abraham (2020) normalisant les relations entre Israël et plusieurs États arabes (Émirats, Bahreïn, Maroc, Soudan) ont reconfiguré les alliances régionales, marginalisant la cause palestinienne dans les diplomaties arabes officielles.</p>
<div class="highlight-box"><p>Le <strong>Mercosur</strong> (1991, Argentine, Brésil, Uruguay, Paraguay, Venezuela suspendu) est la principale expérience d'intégration économique régionale en Amérique du Sud. Après des années de stagnation, un accord de libre-échange UE-Mercosur, négocié pendant vingt ans, a été conclu en 2024 — l'un des plus grands accords commerciaux jamais signés, couvrant 700 millions de personnes.</p></div>
""",

"organisations-internationales/otan-et-alliances": """
<h3>Le débat sur l'élargissement de l'OTAN et la sécurité européenne</h3>
<p class="resume-text">L'<strong>élargissement de l'OTAN</strong> à l'est depuis 1999 (Pologne, Hongrie, République tchèque, puis pays baltes et balkaniques) a été présenté par la Russie comme une menace existentielle — argument qu'elle a utilisé pour justifier ses interventions en Géorgie (2008) et en Ukraine (2014, 2022). Le débat académique (John Mearsheimer vs. Michael McFaul) oppose ceux qui voient dans cet élargissement une provocation stratégique imprudente à ceux qui soulignent le droit souverain des États à choisir leurs alliances et la légitimité de la protection OTAN pour des démocraties menacées.</p>
<p class="resume-text">La guerre en Ukraine a définitivement mis fin au débat sur la <strong>neutralité finlandaise et suédoise</strong>. Ces deux pays, neutres depuis respectivement 1944 et 1814, ont rejoint l'OTAN en 2023 et 2024 — la transformation géopolitique la plus significative en Europe depuis la réunification allemande. Ils apportent à l'Alliance des capacités militaires significatives, notamment la marine et l'armée de l'air finlandaises, ainsi qu'un contrôle des accès en mer Baltique devenue quasi entièrement « lac de l'OTAN ».</p>
<div class="highlight-box"><p>La <strong>budgétisation de la défense</strong> au sein de l'OTAN a été révolutionnée par la guerre en Ukraine. En 2023, pour la première fois depuis la fin de la Guerre froide, la majorité des membres européens atteignaient ou dépassaient l'objectif des 2% du PIB. L'Allemagne, longtemps la cible principale des critiques américaines, a décidé de porter son budget de défense à 100 milliards d'euros supplémentaires.</p></div>
""",

"organisations-internationales/ong-et-societe-civile": """
<h3>La diplomatie des ONG et le droit d'ingérence</h3>
<p class="resume-text">Les ONG humanitaires ont développé une doctrine d'accès aux victimes des conflits qui entre parfois en tension avec le droit international. Le <strong>droit d'ingérence humanitaire</strong>, défendu par Bernard Kouchner (cofondateur de MSF), affirme que l'urgence humanitaire peut justifier une intervention sans le consentement de l'État souverain concerné. Cette doctrine a influencé le développement de la <strong>responsabilité de protéger</strong> (R2P), adoptée à l'ONU en 2005 : la souveraineté n'est plus absolue si un État massacre sa propre population.</p>
<p class="resume-text">Les grandes ONG sont confrontées à des <strong>tensions entre efficacité opérationnelle et témoignage</strong>. Le CICR choisit la discrétion pour préserver son accès aux victimes ; MSF choisit le témoignage public au risque d'être expulsé. En 2009, MSF a quitté le Darfour après que son expulsion a suivi la dénonciation publique des crimes de guerre. Cette tension fondamentale n'est pas résoluble : elle reflète deux conceptions différentes du rôle de l'acteur humanitaire.</p>
<div class="highlight-box"><p>La <strong>digitalisation de l'action humanitaire</strong> a ouvert de nouvelles possibilités et de nouveaux risques. Les cartes collaboratives (Ushahidi lors du séisme d'Haïti 2010), les systèmes de paiement mobile, les drones d'inspection — mais aussi les risques pour la protection des données des bénéficiaires vulnérables et la cyber-sécurité des organisations humanitaires opérant dans des zones de conflit.</p></div>
""",

"conflits/droit-humanitaire": """
<h3>Les défis contemporains du droit international humanitaire</h3>
<p class="resume-text">Le DIH fait face à des défis inédits au XXIe siècle. L'essor des <strong>systèmes d'armes létaux autonomes</strong> (SALA, ou « robots tueurs ») soulève des questions fondamentales : peut-on confier à une machine la décision de tuer un être humain ? Qui est responsable si un système autonome tue des civils en violation du DIH ? Une campagne internationale pour l'interdiction préventive des SALA, soutenue par de nombreuses ONG et un nombre croissant d'États, se heurte à l'opposition des grandes puissances militaires.</p>
<p class="resume-text">La <strong>cyberguerre</strong> pose des défis d'interprétation au DIH. Les cyberattaques qui paralysent des hôpitaux, des infrastructures électriques ou des systèmes d'eau potable sont-elles des crimes de guerre ? Le Manuel de Tallinn (2013, révisé 2017), rédigé par des experts internationaux sous l'égide de l'OTAN, tente d'appliquer le DIH aux cyberopérations, mais reste un document académique sans force contraignante. Les grandes puissances refusent de reconnaître des règles précises qui limiteraient leurs capacités offensives.</p>
<div class="highlight-box"><p>Le <strong>siège de Marioupol</strong> (2022) et les destructions systématiques de villes ukrainiennes par des frappes russes ont illustré la persistance des violations massives du DIH dans les conflits contemporains. La Cour internationale de Justice, la CPI et plusieurs commissions d'enquête de l'ONU ont ouvert des procédures — mais la question de l'application effective du DIH à une grande puissance nucléaire reste entière.</p></div>
""",

"conflits/resolution-des-conflits": """
<h3>La justice transitionnelle et la réconciliation</h3>
<p class="resume-text">La <strong>justice transitionnelle</strong> désigne l'ensemble des mécanismes — judiciaires et non judiciaires — utilisés dans les sociétés sortant de conflits ou de régimes autoritaires pour traiter les violations massives des droits humains. Elle comprend les poursuites pénales (tribunaux nationaux, internationaux ou hybrides), les commissions Vérité et Réconciliation (CVR), les réparations aux victimes, les réformes institutionnelles (épuration de l'armée et de la police) et les garanties de non-répétition.</p>
<p class="resume-text">La <strong>Commission Vérité et Réconciliation d'Afrique du Sud</strong> (1996-2002), présidée par l'archevêque Desmond Tutu, est le modèle le plus influent. Elle offrait l'amnistie en échange de la vérité : les auteurs de violations pouvaient échapper aux poursuites en confessant publiquement leurs actes. Ce modèle, qui privilégie la vérité sur la justice punitive, a été importé dans des dizaines de pays (Sierra Leone, Rwanda, Colombie, Canada pour les pensionnats autochtones) avec des résultats variables. La tension entre vérité, justice, réconciliation et paix n'a pas de solution universelle.</p>
<div class="highlight-box"><p>L'Accord de paix de <strong>Colombie</strong> (2016) entre le gouvernement et les FARC est un exemple de justice transitionnelle innovante : une Juridiction Spéciale pour la Paix (JEP) peut condamner les anciens combattants à des peines alternatives (travaux d'utilité publique, restrictions de liberté) plutôt qu'à la prison, à condition qu'ils reconnaissent leurs crimes et réparent leurs victimes. Le Oui au référendum de validation l'a emporté de justesse, illustrant les résistances sociales aux compromis de la paix négociée.</p></div>
""",

"traites/droit-des-traites": """
<h3>La succession d'États et les traités</h3>
<p class="resume-text">La <strong>succession d'États</strong> soulève des questions complexes en droit international : un État qui succède à un autre (par décolonisation, sécession, dissolution ou union) est-il lié par les traités de son prédécesseur ? La Convention de Vienne sur la succession d'États en matière de traités (1978) distingue plusieurs cas selon la nature de la succession. Pour les traités de frontières, ils restent en vigueur (principe de l'uti possidetis). Pour les traités multilatéraux, les États nouvellement indépendants peuvent généralement choisir d'y adhérer ou non.</p>
<p class="resume-text">La <strong>dissolution de l'URSS</strong> (1991) et de la Yougoslavie (1991-1992) ont posé ces questions de façon aiguë. La Russie a revendiqué le statut de continuatrice de l'URSS (y compris son siège permanent au Conseil de sécurité et ses arsenaux nucléaires), tandis que les autres républiques ex-soviétiques devenaient de nouveaux États. La Tchécoslovaquie s'est « velvetement » divisée en République tchèque et Slovaquie (1993), un cas de dissolution consensuelle et pacifique relativement rare dans l'histoire.</p>
<div class="highlight-box"><p>La <strong>dénonciation des traités</strong> est un acte souverain encadré par le droit international : l'État doit respecter les procédures prévues dans le traité ou, à défaut, respecter les règles coutumières (préavis, motifs valables). Le retrait des États-Unis du traité ABM (2002), du traité INF (2019) ou de l'Accord de Paris (2017-2021) illustre comment des décisions unilatérales peuvent déstabiliser le cadre multilatéral.</p></div>
""",

"traites/droit-international-environnemental": """
<h3>La gouvernance de la biodiversité</h3>
<p class="resume-text">La <strong>Convention sur la diversité biologique</strong> (CDB, 1992) est le traité central sur la protection de la biodiversité mondiale. Elle repose sur trois objectifs : conservation de la diversité biologique, utilisation durable de ses éléments, partage juste et équitable des avantages tirés de l'exploitation des ressources génétiques. Le Protocole de Nagoya (2010) crée un mécanisme de partage des avantages pour les ressources génétiques des pays en développement — un enjeu crucial pour l'industrie pharmaceutique et agricole qui utilise des plantes traditionnelles.</p>
<p class="resume-text">Le cadre de Kunming-Montréal (COP15, décembre 2022) a fixé l'objectif de protéger 30% des terres et des mers de la planète d'ici 2030 (objectif « 30x30 »). Cet accord historique, souvent comparé à l'Accord de Paris pour son ambition, nécessite un financement de 200 milliards de dollars par an pour être atteint — dont une large part provenant des pays développés vers les pays riches en biodiversité. La cohérence entre politiques commerciales (déforestation importée via le soja et l'huile de palme) et objectifs de biodiversité reste le défi principal.</p>
<div class="highlight-box"><p>La <strong>déforestation importée</strong> — la consommation dans les pays riches de produits dont la production a détruit des forêts tropicales — est au cœur des tensions Nord-Sud dans la gouvernance de la biodiversité. Le règlement européen sur la déforestation (2023), qui interdit les importations de produits liés à la déforestation, a provoqué des protestations du Brésil, de l'Indonésie et d'autres pays producteurs.</p></div>
""",

"cooperation/mondialisation": """
<h3>Les inégalités dans la mondialisation</h3>
<p class="resume-text">L'économiste Branko Milanovic a développé la « courbe de l'éléphant » pour représenter les gagnants et perdants de la mondialisation entre 1988 et 2008. Les grands gagnants furent les classes moyennes émergentes d'Asie (notamment en Chine et en Inde) et les très riches partout dans le monde. Les grands perdants furent les classes moyennes et ouvrières des pays développés — surtout ceux exposés à la concurrence des importations à bas coût. Cette visualisation éclaire le paradoxe de la mondialisation : réductrice des inégalités mondiales entre pays, mais potentiellement génératrice d'inégalités à l'intérieur des pays riches.</p>
<p class="resume-text">La <strong>pandémie de Covid-19</strong> (2020-2021) a révélé les vulnérabilités des chaînes d'approvisionnement mondiales hyperspécialisées : pénuries de masques chirurgicaux, de semi-conducteurs, de médicaments génériques — dont la production était concentrée en Chine ou en Inde. La crise a accéléré les débats sur la « résilience » et la « souveraineté industrielle », poussant les gouvernements à diversifier et relocaliser certaines productions stratégiques.</p>
<div class="highlight-box"><p>Le <strong>commerce électronique transfrontalier</strong> (Alibaba, Amazon, Temu) a créé une nouvelle forme de mondialisation directe entre consommateurs et producteurs, contournant les intermédiaires traditionnels. Les enjeux réglementaires sont considérables : comment garantir la sécurité des produits, le respect du droit du travail et la concurrence équitable quand des millions de petits colis arrivent chaque jour des quatre coins du monde ?</p></div>
""",

"cooperation/institutions-financieres": """
<h3>Les crises financières et leur gestion internationale</h3>
<p class="resume-text">Les crises financières internationales ont testé les limites de la coopération économique mondiale. La <strong>crise asiatique</strong> (1997-1998) a frappé les dragons asiatiques (Thaïlande, Corée du Sud, Indonésie, Malaisie) via la contagion des marchés financiers. Les programmes FMI imposés aux pays concernés ont été virulemment critiqués pour leur austérité contre-productive. La réponse de la Malaisie — contrôles des capitaux et refus du FMI — fut initialement condamnée mais s'est avérée efficace, alimentant un débat sur l'orthodoxie du Washington Consensus.</p>
<p class="resume-text">La <strong>crise financière mondiale</strong> de 2008, déclenchée par l'effondrement du marché des subprimes américains et la faillite de Lehman Brothers, a provoqué la récession mondiale la plus grave depuis 1929. La coordination du G20 (stimulus budgétaires coordonnés, recapitalisation des banques, réformes réglementaires sous l'égide du Conseil de stabilité financière) a évité une dépression. Mais ses séquelles — inégalités accrues, austérité budgétaire prolongée, désenchantement démocratique — ont alimenté le populisme des années 2010.</p>
<div class="highlight-box"><p>La <strong>taxe sur les transactions financières</strong> (taxe Tobin, proposée dès 1972) est régulièrement relancée pour décourager la spéculation à court terme et financer le développement. L'UE tente depuis 2011 d'adopter une taxe sur les transactions financières à l'échelle européenne, mais se heurte aux résistances des pays à grandes places financières (Luxembourg, Irlande) et aux risques de délocalisation des marchés.</p></div>
""",

"cooperation/developpement-international": """
<h3>L'aide humanitaire et l'urgence</h3>
<p class="resume-text">L'<strong>aide humanitaire internationale</strong> représente environ 30 milliards de dollars par an. Elle est coordonnée par le Bureau de la coordination des affaires humanitaires de l'ONU (OCHA) et distribuée par un réseau d'agences onusiennes (PAM, HCR, UNICEF, OCHA) et d'ONG. Le <strong>cluster system</strong> (système en grappes) organise la coordination entre acteurs humanitaires par secteur (nourriture, abri, eau, santé). La réforme humanitaire de 2005 et le Grand Bargain de 2016 visent à améliorer l'efficacité de l'aide et à allouer plus de financements directement aux ONG locales.</p>
<p class="resume-text">Le débat sur le <strong>nexus humanitaire-développement-paix</strong> reconnaît que les réponses humanitaires d'urgence ne peuvent résoudre les crises prolongées (Syrie, Yémen, Sahel, RDC) qui s'inscrivent dans des contextes de fragilité structurelle et de conflit. Une approche plus intégrée — combinant aide d'urgence, investissement dans la résilience et soutien à la gouvernance — est prônée, mais sa mise en oeuvre se heurte à des cloisonnements institutionnels et à des logiques de financement différentes entre humanitaires et développeurs.</p>
<div class="highlight-box"><p>Les <strong>transferts monétaires conditionnels</strong> (TMC) sont devenus l'un des instruments phares de la lutte contre la pauvreté dans les pays en développement. Le programme Bolsa Família brésilien (40 millions de bénéficiaires à son apogée), Oportunidades mexicain, ou le FILET camerounais versent des aides en espèces aux ménages pauvres à condition d'inscrire leurs enfants à l'école et de respecter un calendrier vaccinal — combinant protection sociale et investissement en capital humain.</p></div>
""",

"cooperation/geopolitique-de-lenergie": """
<h3>Les nouvelles routes de l'énergie</h3>
<p class="resume-text">La <strong>révolution du gaz naturel liquéfié</strong> (GNL) a transformé la géopolitique énergétique. Contrairement au gaz de pipeline (qui lie acheteur et vendeur dans une relation bilatérale exclusive), le GNL peut être transporté par navire vers n'importe quel client disposant d'un terminal de regazéification. Les États-Unis sont devenus le premier exportateur mondial de GNL (grâce à la révolution du gaz de schiste), concurrençant le gaz russe en Europe et le gaz australien en Asie. Cette flexibilité accrue réduit le pouvoir de levier des fournisseurs monopolistiques.</p>
<p class="resume-text">La <strong>géopolitique des renouvelables</strong> dessine de nouvelles cartes de puissance. Les pays disposant d'un fort potentiel solaire ou éolien, d'espace et de ressources en eau pour l'électrolyse de l'hydrogène (Australie, Chili, Maroc, Namibie, Arabie Saoudite) pourraient devenir des exportateurs d'<strong>hydrogène vert</strong> dans une économie décarbonée. Cette transition crée des opportunités pour des pays en développement bien positionnés, mais requiert des investissements considérables et la mise en place de nouvelles filières de transport et de stockage.</p>
<div class="highlight-box"><p>Le <strong>nucléaire civil</strong> connaît un renouveau dans le contexte de la crise climatique. La France, qui tire 70% de son électricité du nucléaire, défend une énergie bas-carbone face au gaz naturel. La Russie (Rosatom) et la Chine sont les principaux constructeurs de réacteurs dans les pays émergents, utilisant leurs capacités nucléaires comme outil d'influence géopolitique et économique.</p></div>
""",

"cooperation/gouvernance-mondiale": """
<h3>La gouvernance numérique mondiale</h3>
<p class="resume-text">L'internet et les technologies numériques ont créé un nouvel espace qui nécessite des formes de gouvernance mondiale inédites. Les tentatives de gouvernance internationale de l'internet sont marquées par une tension fondamentale entre le modèle multi-parties prenantes (multistakeholder) — où États, entreprises, société civile et techniciens participent sur un pied d'égalité, défendu par les États-Unis et l'Occident — et le modèle multi-États (multilateral) — où les gouvernements auraient l'autorité principale, défendu par la Russie, la Chine et leurs alliés.</p>
<p class="resume-text">Le <strong>Forum sur la gouvernance de l'internet</strong> (FGI), créé en 2006, est une enceinte de discussion inclusive mais sans pouvoir décisionnel. L'<strong>ICANN</strong> (gestion des noms de domaine) a été internationalisée en 2016, réduisant la supervision américaine directe. La <strong>fragmentation de l'internet</strong> (splinternet) se développe : le « Great Firewall » chinois, l'internet souverain russe, les législations européennes sur les données (RGPD) créent des espaces numériques de plus en plus distincts.</p>
<div class="highlight-box"><p>L'intelligence artificielle est devenu un enjeu de gouvernance mondiale urgente. La course au leadership en IA entre États-Unis et Chine s'est intensifiée depuis la révolution des grands modèles de langage (GPT-4, Gemini). L'adoption du premier traité international sur l'IA par le Conseil de l'Europe (2024), les négociations à l'ONU sur la gouvernance de l'IA et le Summit for AI Safety (Bletchley, 2023) illustrent les premières tentatives de cadrer ce défi global.</p></div>
""",

"organisations-internationales/systeme-des-nations-unies": """
<h3>La réforme de l'ONU : enjeux et obstacles</h3>
<p class="resume-text">Les appels à la réforme de l'ONU sont aussi anciens que l'organisation elle-même. Les principales demandes portent sur la réforme du Conseil de sécurité (élargissement et remise en cause du droit de veto), le renforcement de l'Assemblée générale, l'amélioration de la coordination entre agences, et la réforme financière (financement prévisible et suffisant). Ces réformes se heurtent à l'obstacle des cinq membres permanents qui bénéficient du statu quo et peuvent bloquer tout amendement à la Charte qui requerrait leur ratification.</p>
<p class="resume-text">Le <strong>Secrétaire général de l'ONU</strong> joue un rôle de médiateur et de porte-parole de la communauté internationale, mais ses pouvoirs sont limités : il ne peut agir que dans le cadre autorisé par les États membres. Le pouvoir d'initiative diplomatique du SG — ses <strong>bons offices</strong> — a néanmoins permis des percées importantes : Kofi Annan en Côte d'Ivoire et au Kenya, Ban Ki-moon sur le changement climatique, António Guterres sur le corridor céréalier de la mer Noire (accord Ukraine-Russie, 2022). Le SG incarne aussi la responsabilité institutionnelle : Kofi Annan a reconnu l'échec de l'ONU à prévenir le génocide rwandais (1994) et le massacre de Srebrenica (1995).</p>
""",

"organisations-internationales/union-europeenne": """
<h3>L'identité européenne et ses tensions</h3>
<p class="resume-text">La construction d'une <strong>identité européenne</strong> est un projet politique autant que culturel. La citoyenneté européenne (droit de voter et de s'installer dans tout État membre), l'euro, le passeport bordeaux, la reconnaissance des diplômes, le programme <strong>Erasmus</strong> (3,5 millions d'étudiants échangés depuis 1987) sont autant d'éléments concrets de cette identité partagée. Erasmus est souvent cité comme le programme européen le plus populaire et le plus efficace pour créer un sentiment d'appartenance commune.</p>
<p class="resume-text">Pourtant, l'identité européenne coexiste avec des <strong>identités nationales, régionales et locales</strong> fortes. Le sentiment eurosceptique a progressé dans plusieurs pays, alimenté par les crises (euro, migrants, Covid) et par la perception d'un déficit démocratique des institutions bruxelloises. Le <strong>conflit entre valeurs libérales</strong> (État de droit, droits des minorités, égalité de genre) défendues par la Commission et des conceptions plus conservatrices dans certains pays membres (Hongrie, Pologne) est l'une des principales lignes de fracture internes à l'UE.</p>
""",
}

def enrich_page(content, extra_html):
    idx = content.rfind('</section>')
    if idx == -1:
        return content + extra_html
    return content[:idx] + extra_html + content[idx:]

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

enriched = 0
for key, extra in ENRICHMENTS2.items():
    if key in data['pages']:
        page = data['pages'][key]
        original_len = len(page['content'])
        page['content'] = enrich_page(page['content'], extra)
        new_len = len(page['content'])
        print(f'  {key}: {original_len} -> {new_len} chars')
        enriched += 1

with open('C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/relations-internationales.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'\nEnriched {enriched} articles.')
