#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Second pass enrichment for logique articles still under 15k chars"""
import json

PATH = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/logique.json'

# Add extra sections to shortest articles to reach ~15k chars
ENRICHMENTS = {}

ENRICHMENTS['logique-propositionnelle/tables-verite'] = (
    '<h3>Tableaux semantiques : une variante des tables de verite</h3>'
    '<p class="resume-text">Les tableaux semantiques (ou tableaux de Beth-Hintikka) sont une methode de preuve basee sur les tables de verite mais plus efficiente. Pour verifier si une formule φ est valide, on construit systematiquement un contre-modele pour ¬φ. Si toutes les branches de l\'arbre menent a des contradictions (branches fermees), φ est valide. Cette methode est incomplete si on s\'arrete trop tot, mais complete si on applique les regles exhaustivement. Son avantage sur les tables de verite : elle peut court-circuiter des sous-arbres entiers quand une contradiction est trouvee rapidement.</p>'
    '<p class="resume-text">Les regles des tableaux decoulent directement des tables de verite. Pour (A ∧ B) : si vrai, alors A et B sont tous les deux vrais (branche unique). Si faux, alors A est faux ou B est faux (bifurcation). Pour (A → B) : si faux, alors A est vrai et B est faux (branche unique). Pour (A ∨ B) : si vrai, alors A est vrai ou B est vrai (bifurcation). Ces regles peuvent se lire directement depuis les tables de verite des connecteurs, montrant que les tableaux sont une procedure optimisee de recherche dans l\'espace des tables de verite.</p>'
    '<div class="highlight-box"><p><strong>Tableaux et SAT :</strong> L\'algorithme DPLL (Davis-Putnam-Logemann-Loveland, 1962) est une variante des tableaux semantiques pour la logique propositionnelle en FNC. Il selectionne une variable, tente les deux affectations (vrai/faux), propagate les unit-clauses, et backtracke si contradiction. DPLL est le fondement de tous les solveurs SAT modernes. Sa completude decoule directement du theoreme que les tables de verite sont finies et exhaustives.</p></div>'
    '<h3>Tables de verite multi-valuees</h3>'
    '<p class="resume-text">Les logiques plurivalentes etendent les tables de verite avec plus de deux valeurs. La logique trivalente de Łukasiewicz (1920) utilise {0, 1/2, 1} avec des connecteurs definis par ¬(1/2) = 1/2, p → q = min(1, 1-p+q). La logique de Kleene (1938) utilise aussi trois valeurs mais avec des connecteurs differents adaptes a l\'evaluation paresseuse des expressions : p ∧ q = min(p,q), p ∨ q = max(p,q) avec 0 ≤ 1/2 ≤ 1. Ces logiques permettent de traiter les expressions indefinies sans erreur fatale — utile pour les bases de donnees avec valeurs nulles (SQL utilise une logique trivalente).</p>'
    '<p class="resume-text">La logique de Bochvar (1938) distingue les propositions "sensees" (vraies ou fausses) des propositions "sans sens" (comme les paradoxes du menteur). Sa table de verite introduit une troisieme valeur "ni vrai ni faux" qui se "contamine" dans tous les connecteurs : si un operande est paradoxal, le resultat est paradoxal. Cette semantique "contaminante" modelise le comportement des erreurs en programmation : si un sous-calcul provoque une exception, le resultat global est une exception — exactement la propagation des exceptions de null dans de nombreux langages.</p>'
    '<div class="highlight-box"><p><strong>SQL et logique trivalente :</strong> SQL utilise une logique trivalente (vrai, faux, NULL) pour les comparaisons. NULL = NULL est NULL (pas VRAI), NULL = 5 est NULL. La clause WHERE filtre les lignes pour lesquelles la condition est VRAIE (pas NULL). Cela genere des subtilites : SELECT * FROM t WHERE col != 5 ne retourne pas les lignes avec col = NULL, car NULL != 5 est NULL, non VRAI. Ces comportements, directement issus des tables de verite trivalentes de Kleene, sont une source frequente de bugs dans les applications utilisant des bases de donnees relationnelles.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/connecteurs-logiques'] = (
    '<h3>Algebre de Boole et dualite</h3>'
    '<p class="resume-text">L\'algebre de Boole (Boole 1854) est la structure algebrique des connecteurs logiques : un ensemble {0,1} avec les operations ∧ (produit), ∨ (somme), ¬ (complement), et les constantes 0 et 1, satisfaisant des axiomes precis. La dualite de De Morgan est fondamentale : toute loi de l\'algebre de Boole reste vraie si on echange ∧ et ∨, et 0 et 1 simultanement. Par exemple, la loi de distributivite p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r) a pour duale p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r) — les deux sont valides.</p>'
    '<p class="resume-text">Les algebres de Boole generalises (Huntington 1904) remplacent {0,1} par un ensemble quelconque avec ces operations. L\'ensemble de toutes les parties d\'un ensemble E forme une algebre de Boole avec ∩, ∪, complement. Les clopen sets d\'un espace topologique totalement disconnecte forment une algebre de Boole. Par le theoreme de Stone (1936), toute algebre de Boole est isomorphe a une algebre de clopen sets d\'un espace topologique compact Hausdorff totalement disconnecte — reliant algebra, logique et topologie dans une correspondance profonde.</p>'
    '<div class="highlight-box"><p><strong>Theoreme de Stone et spectres :</strong> La dualite de Stone (1936) etablit une equivalence de categories entre algebres de Boole et espaces de Stone (compacts, Hausdorff, totalement disconnectes). Cette dualite est un exemple fondateur de la dualite entre algebre et geometrie, precurseur des espaces schemes de Grothendieck. Elle s\'etend aux treillis distributifs (Birkhoff) et aux espaces coherents, avec des applications en semantique des domaines et en geometrie algebrique computationnelle.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/tautologies'] = (
    '<h3>Tautologies et lois de De Morgan generalisees</h3>'
    '<p class="resume-text">Les lois de De Morgan s\'etendent aux quantificateurs du premier ordre : ¬∀x φ(x) ≡ ∃x ¬φ(x) et ¬∃x φ(x) ≡ ∀x ¬φ(x). Ces equivalences sont des tautologies du premier ordre et permettent de pousser les negations a l\'interieur des quantificateurs, etape essentielle dans la transformation en forme prénexe. Les analogues pour les series sont la negation de la convergence uniforme (∃ε∀N∃n>N∃x |aₙ(x) - a(x)| ≥ ε) et le raisonnement par contraposee en analyse.</p>'
    '<p class="resume-text">Les tautologies jouent un role central dans les systemes de reecriture de termes. Un systeme de reecriture est un ensemble de regles l → r ou l et r sont des termes. Si l → r est une tautologie (l et r ont la meme table de verite), la regle preserve la semantique. Les completeurs de Knuth-Bendix orientent les tautologies comme des regles de reecriture de gauche a droite pour simplifier les termes. La question "est-ce que deux termes sont egaux dans une theorie equationnelle ?" se ramene a la reductibilite a la meme forme normale — avec la semantique garantie par les tautologies comme base des regles.</p>'
    '<div class="highlight-box"><p><strong>SAT et tautologies NP-dures :</strong> La question "est-ce une tautologie ?" est co-NP-complet. Mais certaines classes de tautologies sont decidables en temps polynomial : les tautologies de la logique propositionnelle sans negation (monotone), les tautologies de la logique propositionnelle Horn (clauses a au plus un literal positif). Les problemes SAT Horn sont decidables en temps lineaire — c\'est pourquoi Prolog utilise des clauses Horn : la resolution Horn est complete et lineaire pour les programmes Prolog sans negation.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/formes-normales'] = (
    '<h3>BDD : Formes normales symboliques</h3>'
    '<p class="resume-text">Les diagrammes de decision binaire (BDD) sont une forme normale symbolique des fonctions booleennes. Un BDD est un graphe oriente acyclique ou chaque nœud interne est etiquete par une variable et a deux fils (pour vrai et faux), et chaque feuille est 0 ou 1. Les BDD ordonnes et reduits (ROBDD) sont canoniques : deux fonctions booleennes egales ont le meme ROBDD pour un ordre fixe des variables. Cette canonicite fait des ROBDD la "forme normale des tables de verite" implicitee — exponentiellement plus compacte pour les fonctions avec structure.</p>'
    '<p class="resume-text">Les operations sur les ROBDD sont efficientes : conjonction, disjonction, complement s\'effectuent en temps polynomial. La verificacion de tautologie est triviale : une tautologie a un ROBDD reduit au nœud "1". La quantification existentielle ∃x f est calculable en temps polynomial. Ces proprietes font des ROBDD l\'outil central du Model Checking symbolique (Clarke, Emerson, Sifakis, prix Turing 2007) : les etats d\'un systeme sont representes par leur BDD caracteristique, et le model checking est une sequence d\'operations BDD — permettant de verifier des systemes avec 10²⁰ etats ou plus en manipulant des BDD de taille raisonnable.</p>'
    '<div class="highlight-box"><p><strong>SMC et Intel :</strong> Le model checking symbolique par BDD (Symbolic Model Checking, Clarke et al., 1990) permit a Intel de verifier le chipset de l\'Itanium en 2000 — un systeme avec 10^300 etats, verifiable grace aux BDD en quelques heures sur un ordinateur ordinaire. C\'est une realisation directe que les formes normales symboliques (BDD) permettent de manipuler des tables de verite astronomiques que les formes normales classiques (FNC, FND) rendraient totalement impraticables.</p></div>'
)

ENRICHMENTS['logique-propositionnelle/propositions'] = (
    '<h3>Logique classique et logique intuitioniste</h3>'
    '<p class="resume-text">La logique classique (Frege, Boole) accepte le tiers exclu (p ∨ ¬p) et la double negation (¬¬p → p). La logique intuitioniste (Brouwer 1908, Heyting 1930) les rejette : une formule n\'est vraie que si on peut la construire effectivement. En intuitionisme, p ∨ ¬p n\'est valide que si on peut soit prouver p soit prouver ¬p. De nombreux theoremes classiques (theoreme de valeur intermediaire, existence de transcendants parmi les nombres de Liouville) perdent leur validite ou doivent etre reformules constructivement.</p>'
    '<p class="resume-text">La semantique de Kripke (1963) pour la logique intuitioniste utilise des ensembles de "mondes possibles" avec une relation de preordre (l\'information s\'accroit). Une proposition p est vraie dans un monde w si p est prouve dans w. La semantique classique en est un cas particulier ou chaque monde est son propre successeur unique. Cette semantique modelise l\'enrichissement progressif de l\'information — directement liee aux treillis de Scott pour la semantique denotationnelle des langages de programmation et aux topos de Lawvere pour les fondements categoriques.</p>'
    '<div class="highlight-box"><p><strong>Agda et types dependants :</strong> Le langage Agda (base sur le lambda-calcul de Martin-Lof) est purement intuitioniste : tout programme Agda termine, et les preuves sont des programmes. La logique intuitioniste est la "bonne" logique pour la programmation : ses preuves sont toujours constructives et calculatoires. Un programme Agda prouvant l\'existence d\'un entier n avec une propriete P doit construire explicitement n et la preuve de P(n) — pas seulement arguer par l\'absurde que n "doit exister".</p></div>'
)

ENRICHMENTS['logique-predicats/quantificateurs'] = (
    '<h3>Quantificateurs en bases de donnees et langages de requete</h3>'
    '<p class="resume-text">Le langage SQL est une realisation directe de la logique du premier ordre. SELECT correspond a la projection, WHERE a la selection (formule du premier ordre), JOIN a la conjonction de predicats, EXISTS a ∃, ALL a ∀. La requete SELECT * FROM employes WHERE EXISTS (SELECT 1 FROM projets WHERE projets.manager = employes.id) exprime exactement ∃p Manager(employes.id, p), une formule existentielle du premier ordre. La theorie de la réécriture de requetes SQL utilise les equivalences du premier ordre pour optimiser les requetes sans changer leur semantique.</p>'
    '<p class="resume-text">La logique de description (DL), utilisee dans les ontologies du Web Semantique (OWL), est un fragment du premier ordre avec quantificateurs. Les concepts sont des unaires, les roles des predicats binaires. La subsomption (C ⊆ D) est decidable et calculable en temps polynomial pour de nombreux fragments DL. Les raisonneurs comme Hermit ou Pellet verifient automatiquement des ontologies medicales (SNOMED CT, 350 000 concepts) ou genomiques (Gene Ontology) pour leur coherence et calculent les hierarchies de concepts — application directe des quantificateurs du premier ordre a grande echelle.</p>'
    '<div class="highlight-box"><p><strong>SPARQL et le Web semantique :</strong> SPARQL est le langage de requete pour RDF (Resource Description Framework), le langage de description du Web semantique. Une requete SPARQL exprime un patron de graphe : SELECT ?x WHERE { ?x rdf:type :Personne ; :travaillePour :Renault }. Elle est semantiquement equivalente a ∃x (type(x, Personne) ∧ travaillePour(x, Renault)) — une formule du premier ordre. Les moteurs SPARQL evaluent ces requetes sur des graphes RDF contenant des millions de triplets, implementant directement l\'evaluation semantique du premier ordre.</p></div>'
)

ENRICHMENTS['logique-predicats/variables-termes'] = (
    '<h3>Termes et types en programmation</h3>'
    '<p class="resume-text">La theorie des types (Church 1940, Martin-Lof 1975) est une theorie des termes ou chaque terme a un type. Les termes sont les programmes, les types sont les specifications. La correspondance de Curry-Howard identifie les types avec les propositions et les termes avec les preuves. Dans ce cadre, les variables de termes sont les variables libres de la logique du premier ordre, les fonctions sont les termes fonctionnels, et l\'application de fonction est la substitution de variables. Prouver un theoreme est ecrire un programme de son type — une unification profonde entre calcul et deduction.</p>'
    '<p class="resume-text">Les types dependants (Martin-Lof, Coquand-Huet dans le Calcul des Constructions) permettent d\'exprimer des proprietes arbitraires du premier ordre dans les types. Le type Vect(n, A) represente les vecteurs de longueur n sur A — un type dependant de la valeur n. La function head : Vect(S(n), A) → A a un type qui garantit statiquement qu\'on ne prend la tete que d\'un vecteur non vide (S(n) ≥ 1). Ces garanties, exprimees dans les types, sont des formules du premier ordre verifiees par le compilateur a la compilation — eliminant des classes entieres de bugs runtime.</p>'
    '<div class="highlight-box"><p><strong>Rust et borrow checking :</strong> Le systeme de types de Rust encode, dans les types, des proprietes de durée de vie (lifetimes) des references. La formule "cette reference vit au moins aussi longtemps que l\'objet reference" est exprimee dans les types et verifiee statiquement. C\'est une forme de logique lineaire (Girard 1987) appliquee aux references memoire : chaque valeur a un proprietaire unique, les emprunts sont controles. Le resultat : zero bugs de memoire a l\'execution, garanti par les types — la theorie des termes et des variables au service de la securite memoire.</p></div>'
)

ENRICHMENTS['preuves-formelles/recurrence'] = (
    '<h3>Recurrence et verification de programmes</h3>'
    '<p class="resume-text">La logique de Floyd-Hoare (Floyd 1967, Hoare 1969) permet de prouver formellement la correction de programmes par des assertions sur les etats. Un triplet de Hoare {P} C {Q} signifie : si P est vraie avant l\'execution de C, et si C termine, alors Q est vraie apres. La regle pour les boucles while est : trouver un invariant I tel que {I ∧ B} corps {I} (l\'invariant est maintenu) et I ∧ ¬B → Q (a la sortie, la postcondition est satisfaite). Trouver l\'invariant est la difficulte principale — c\'est souvent la cle de voute de la preuve.</p>'
    '<p class="resume-text">La recurrence est omnipresente dans les preuves Hoare. Pour prouver qu\'un tri (tri-selection, tri-bulle) produit un tableau trie, l\'invariant de boucle est generallement "les premiers k elements sont tries et sont inferieurs a tous les elements restants". Cette propriete est prouvee par recurrence sur k : vraie initialement (k=0), et si vraie pour k, le pas de boucle la maintient pour k+1. Les outils de verification deductive (Frama-C pour C, Dafny pour C#, Why3) automatisent ces preuves en generant des obligations de preuve de la logique de Hoare et en les soumettant a des solveurs SMT (Z3, Alt-Ergo).</p>'
    '<div class="highlight-box"><p><strong>Dafny et verification deductive :</strong> Dafny (Microsoft Research) permet d\'annoter des programmes C# avec des preconditions, postconditions et invariants de boucle en syntaxe Hoare. Le compilateur verifie automatiquement ces annotations via Z3. Un programmeur Dafny prouvant un algorithme de tri annote : ensures IsSorted(result) et ensures multiset(result) == multiset(input) — les deux proprietes essentielles d\'un tri correct. Ces preuves a l\'interieur du code deviennent de la documentation executable, impossible a desynchroniser du code comme les commentaires ordinaires.</p></div>'
)

ENRICHMENTS['preuves-formelles/absurde'] = (
    '<h3>Double negation et semantique classique</h3>'
    '<p class="resume-text">La double negation ¬¬p → p est la forme pure du tiers exclu : si p ne peut etre faux, alors p est vrai. Cette implication distingue fondamentalement la logique classique de l\'intuitioniste. En logique classique, ¬¬p ≡ p (la double negation s\'elimine). En logique intuitioniste, ¬¬p → p n\'est pas prouvable car prouver ¬¬p (impossible de refuter p) ne construit pas une preuve de p. La traduction de Godel-Gentzen (1933) plonge la logique classique dans l\'intuitioniste : chaque formule classique A est traduite en A° ou toutes les sous-formules atomiques et toutes les disjonctions sont doublement negatives.</p>'
    '<p class="resume-text">Cette traduction montre que la logique classique est conservative sur les formules negatives : si une formule negativement traduite est prouvable classiquement, elle l\'est aussi intuitionistement. Pragmatiquement, cela signifie que tout raisonnement par l\'absurde peut etre "classifie" : soit il a un equivalent constructif direct, soit il prouve une formule fondamentalement non constructive. La theorie de la complexite computationnelle exploite cette distinction : les preuves de non-existence (par l\'absurde) sont souvent non constructives et ne donnent pas de certificat calculable.</p>'
    '<div class="highlight-box"><p><strong>Negative traduction et CPS :</strong> La traduction de Godel-Gentzen est isomorphe (via Curry-Howard) a la transformation CPS (Continuation-Passing Style) des programmes. Chaque programme direct A correspond au programme CPS (continuation) A° qui passe son resultat a une continuation au lieu de le retourner. La logique classique correspond aux programmes avec callcc, l\'intuitioniste aux programmes sans — un pont profond entre logique et semantique des langages de programmation.</p></div>'
)

ENRICHMENTS['preuves-formelles/deduction-naturelle'] = (
    '<h3>Preuves normales et normalisation</h3>'
    '<p class="resume-text">Gentzen montra que toute preuve en deduction naturelle peut etre normalisee : on peut eliminer les detours (intro suivi immediatement d\'elim pour le meme connecteur). Par exemple, une preuve qui construit A ∧ B puis en extrait A immediatement peut etre simplifiee en une preuve directe de A. La normalisation forte garantit que tout terme du lambda-calcul simplement type se reduit a une forme normale en un nombre fini de pas — c\'est la propriete fondamentale de terminaison des langages fonctionnels types.</p>'
    '<p class="resume-text">La normalisation des preuves a des consequences decidabilistiques. En logique propositionnelle intuitioniste, la normalisation est forte et les preuves en forme normale ont la propriete de sous-formule — elles n\'introduisent que des sous-formules de la conclusion. Cela rend la prouvabilite decidable : on peut rechercher les preuves en forme normale dans un espace fini. En logique du premier ordre, la normalisation n\'est pas toujours possible (il peut y avoir des preuves infiniement longues) — la prouvabilite est seulement semi-decidable.</p>'
    '<div class="highlight-box"><p><strong>Systeme F et polymorphisme :</strong> Le systeme F de Girard (1972) est la logique du second ordre intuitioniste. Son lambda-calcul correspondant (polymorphisme parametrique) normalise fortement — toute expression de type bien-forme termine. Haskell et ML utilisent une restriction de F (System F omega) pour le polymorphisme : list_length : forall a. List a -> Int. La normalisation forte de F est la garantie theorique que les types generiques bien types en Haskell ne provoquent pas de boucles infinies de typage.</p></div>'
)

ENRICHMENTS['paradoxes/menteur'] = (
    '<h3>Extensions et variantes modernes</h3>'
    '<p class="resume-text">Le paradoxe du yablo (Yablo, 1993) est un paradoxe du menteur sans autoreference directe : une suite infinie de propositions S₀, S₁, S₂, … ou Sₙ dit "tout Sₘ avec m > n est faux". Si S₀ est vraie, toutes les Sₙ suivantes sont fausses, donc S₁ est vraie — contradiction. Si S₀ est fausse, il existe un Sₘ avec m > 0 qui est vraie, et ce Sₘ mene a une contradiction similaire. Le paradoxe de Yablo montre que les paradoxes semantiques ne necessitent pas d\'autoreference directe — juste une circularite infinie potentielle — et remet en question la solution de Tarski par stratification.</p>'
    '<p class="resume-text">La logique de revision (Gupta-Belnap) s\'etend aux paradoxes de Yablo : la suite S₀, S₁, … n\'a pas de point fixe sous l\'operateur de revision, oscillant indefiniment sans stabiliser. Cette approche diagnostic precisement quelles suites autoreferentes sont stables (ont une semantique classique) et lesquelles sont pathologiques (oscillent). Les applications en base de donnees actives (triggres qui se declenchent mutuellement) et en logique de contraintes (graphes de dependances avec cycles) montrent que les paradoxes de Yablo ne sont pas seulement philosophiques mais surviennent naturellement en informatique.</p>'
    '<div class="highlight-box"><p><strong>Contrats en logique :</strong> Les contrats de programmation (preconditions, postconditions, invariants) peuvent mutuellement se referencer : un contrat de methode A verifie que le contrat de methode B est satisfait, et vice versa. Ces dependances circulaires sont l\'analogue programmatique des paradoxes de Yablo. Les systemes de verification comme Z3 ou Boogie detectent ces circularites et les gerent par des hypotheses de co-induction ou des ordres de verification, analogue aux solutions logiques des paradoxes semantiques.</p></div>'
)

ENRICHMENTS['logique-predicats/modeles'] = (
    '<h3>Modeles finis et verification formelle</h3>'
    '<p class="resume-text">En verification formelle, on s\'interesse souvent aux modeles finis de systemes : les etats sont finis, les transitions sont finies. La logique temporelle CTL (Clarke, Emerson) specifie des proprietes des traces infinies de ces systemes : AG(p) = "p est vraie dans tous les etats atteignables", EF(q) = "il existe un etat atteignable satisfaisant q". Le probleme de model checking CTL (verifier si M ⊨ φ pour un modele fini M et une formule CTL φ) est decidable en temps polynomial en |M| × |φ| — un resultat remarquable exploite industriellement.</p>'
    '<p class="resume-text">La bisimulation est la notion d\'equivalence canonique pour les modeles de systemes reactifs. Deux systemes de transitions sont bisimilaires si chaque action de l\'un peut etre imitee par l\'autre indefiniment. Un fait profond : deux systemes sont bisimilaires si et seulement s\'ils satisfont exactement les memes formules de la logique modale HML (Hennessy-Milner Logic) — un theoreme d\'adequation entre semantique operationnelle (transitions) et semantique logique (formules). Ce resultat relie la theorie des modeles pour les logiques modales a la semantique operationnelle des langages de programmation concurrents.</p>'
    '<div class="highlight-box"><p><strong>Pi-calcul et mobilite :</strong> Le pi-calcul de Milner (1992) modelise des systemes ou la topologie de communication change au cours du temps — les canaux de communication sont passes comme parametres. Sa logique associee (pi-logique modale) generalise HML pour les systemes mobiles. Des protocoles comme la delegation d\'authentification TLS, ou un tiers de confiance delègue ses droits a une autre entite, sont des systemes mobiles du pi-calcul dont les proprietes de securite sont verifiees par des outils bases sur ces logiques modales.</p></div>'
)

ENRICHMENTS['paradoxes/russell'] = (
    '<h3>Consequences formelles et theorie des categories</h3>'
    '<p class="resume-text">Le paradoxe de Russell conduit a la distinction ensemble/classe propre. Une classe propre est une "collection trop grande pour etre un ensemble" — comme la classe de tous les ensembles, la classe de tous les groupes, la classe de tous les anneaux. En theorie des categories, les objets de la categorie Set forment une classe propre (trop de structure pour etre un ensemble). Grothendieck (1957) introduisit les "univers" — des ensembles "suffisamment grands" clos par toutes les constructions ensemblistes — pour manipuler ces collections sans paradoxe. Chaque univers est un "monde" ou l\'on peut travailler sans rencontrer le paradoxe de Russell.</p>'
    '<p class="resume-text">La theorie des types homotopiques (HoTT, Voevodsky et al., 2010) refonde les mathematiques sur un systeme de types dependants oil les types sont interpretes comme des espaces topologiques et l\'egalite comme des chemins. L\'axiome d\'univalence de Voevodsky (structures isomorphes sont egales) generalise l\'extensionnalite. HoTT est coherent (pas de paradoxe de Russell) car les types sont stratifies par des "niveaux" (h-niveaux) analogues aux types de Russell, mais de maniere plus geometrique. Ce programme de "fondements non-canoniques" est formlise dans l\'assistant de preuve Agda et pourrait remplacer ZFC comme fondement standard a long terme.</p>'
    '<div class="highlight-box"><p><strong>Homotopy Type Theory :</strong> En HoTT, un theoreme dit : deux preuves du meme theoreme sont "egales" (homotopes) si elles sont connectees par un chemin dans l\'espace des preuves. L\'axiome d\'univalence dit que deux types isomorphes sont propositionnellement egaux. Cela permet de prouver des theoremes en utilisant n\'importe quelle presentation concrete d\'une structure abstraite, car toutes les presentations isomorphes sont egales par definition. C\'est un bouleversement conceptuel radical, elimenant un grand nombre de theoremes triviaux de "transport d\'egalite" qui encombrent les preuves formelles classiques.</p></div>'
)

with open(PATH, encoding='utf-8') as f:
    data = json.load(f)

pages = data['pages']
count = 0
for key, extra in ENRICHMENTS.items():
    if key in pages and len(pages[key]['content']) < 15000:
        old_len = len(pages[key]['content'])
        content = pages[key]['content']
        quiz_start = content.find('<section class="content-section" id="quiz">')
        if quiz_start != -1:
            pages[key]['content'] = content[:quiz_start] + extra + content[quiz_start:]
        else:
            idx = content.rfind('</section>')
            if idx != -1:
                pages[key]['content'] = content[:idx] + extra + content[idx:]
            else:
                pages[key]['content'] = content + extra
        new_len = len(pages[key]['content'])
        print(f"  {key}: {old_len} -> {new_len}")
        count += 1

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone: {count} articles enriched.")
