import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

# Second pass for mecanique (most underfilled)
extra_meca = {
'mecanique/machines-et-mecanismes': (
    '<h3>Conception assistée par ordinateur des mécanismes</h3>'
    '<p class="resume-text">La <strong>conception paramétrique</strong> des mécanismes utilise des logiciels CAO (CATIA, SolidWorks, Siemens NX) pour modéliser les assemblages en 3D avec des contraintes géométriques. Les liaisons cinématiques sont définies entre les pièces (pivot, glissière, sphérique) et le comportement dynamique est simulé par des outils MBS (Multi-Body Simulation) comme ADAMS ou Simscape. Ces outils permettent d\'optimiser les courbes de déplacement, vitesse et accélération de l\'effecteur sans prototypage physique coûteux.</p>'
    '<p class="resume-text">L\'<strong>analyse de tolérance</strong> (tolérance stack-up) vérifie que les jeux et interférences restent dans les limites spécifiées, compte tenu des tolérances de fabrication de chaque pièce. L\'analyse statistique (worst-case ou RSS — Root Sum Square) quantifie la probabilité que l\'assemblage final respecte les spécifications fonctionnelles. Dans l\'industrie horlogère, les mécanismes de précision exigent des tolérances de quelques micromètres sur des pièces de quelques millimètres.</p>'
    '<p class="resume-text">L\'<strong>optimisation topologique</strong> génère des formes de pièces optimales pour un minimum de matière tout en respectant les contraintes de résistance et de raideur. Les algorithmes SIMP (Solid Isotropic Material with Penalization) et BESO (Bidirectional Evolutionary Structural Optimization) créent des formes organiques imitant la biologie qui seraient impossibles à concevoir intuitivement. Ces formes sont désormais fabriquées par impression 3D métal (SLM, DMLS) dans les secteurs aéronautique et médical.</p>'
    '<div class="highlight-box"><p>Les pièces mécaniques optimisées topologiquement et imprimées en titane 3D pour les avions A350 pèsent 55% de moins que les équivalents usinés conventionnels, pour une résistance identique — une révolution dans la conception mécanique.</p></div>'
    '<h3>Mécanismes biologiques et bio-inspiration</h3>'
    '<p class="resume-text">La <strong>bio-inspiration</strong> s\'inspire des solutions mécaniques évoluées par la nature pour résoudre des problèmes d\'ingénierie. Les tendons et ligaments sont des mécanismes de transmission de force qui absorbent les chocs. Les articulations humaines (hanche, épaule) combinent faible frottement et grande mobilité. La vision multidirectionnelle des insectes, la locomotion des serpents et les ventouses des pieuvres inspirent de nouvelles conceptions de robots et de capteurs.</p>'
    '<p class="resume-text">Les <strong>ailes d\'oiseaux et d\'insectes</strong> sont des mécanismes aérodynamiques remarquablement efficaces. Le battement d\'aile crée simultanément portance et propulsion par des mécanismes de déformation passive (wings avec des nervures flexibles). Les drones à ailes battantes (ornithoptères) imitent ces mécanismes pour voler silencieusement et manœuvrer dans des espaces confinés. Le DelFly Nimble (TU Delft) effectue des acrobaties impossibles pour les multirotors grâce à ses ailes de 33 cm d\'envergure.</p>'
    '<div class="highlight-box"><p>La nageoire caudale d\'un thon produit une poussée avec une efficacité de 93% — contre 70% pour les meilleures hélices marines. Les bateaux bio-inspirés à propulsion ondulatoire atteignent des rendements similaires en laboratoire.</p></div>'
),
'mecanique/tribologie': (
    '<h3>Tribologie des transports</h3>'
    '<p class="resume-text">Les <strong>pneumatiques</strong> sont au cœur de la tribologie des transports. Le contact entre le pneu et la chaussée est fondamentalement tribologique : la déformation viscoélastique de la gomme dans les microrugosités de la chaussée génère la force d\'adhérence (grip). La physique du contact dépend de la vitesse, de la température, de la pression et de la présence d\'eau. La conception d\'une sculpture de pneu (gorges, lamelles) optimise le drainage de l\'eau (prévention de l\'aquaplaning) tout en maximisant la surface de contact au sec.</p>'
    '<p class="resume-text">Les <strong>paliers aérodynamiques</strong> (air bearings) utilisent un film d\'air sous pression pour séparer les surfaces sans contact physique — coefficient de frottement de l\'ordre de 10⁻⁵. Ces paliers ultra-précis équipent les disques durs (la tête de lecture flotte à 5 nm au-dessus du disque en rotation), les turbines à haute vitesse et les machines à mesurer de précision. Leur absence de contact les rend parfaits pour les environnements sous vide (satellitaires) ou ultra-propres (salles blanches).</p>'
    '<p class="resume-text">La <strong>tribologie des rails</strong> influence directement la sécurité et l\'efficacité ferroviaires. Le contact roue-rail (petit ellipse de Hertz de 1 cm²) supporte le poids du train (10 à 20 tonnes par essieu) avec une résistance au roulement très faible (coefficient 0,001). La friction longitudinale assure l\'accélération et le freinage ; la friction latérale guide les bogies dans les courbes. La lubrification des rails (graisseurs automatiques) réduit l\'usure latérale dans les courbes serrées des réseaux urbains.</p>'
    '<div class="highlight-box"><p>La tête de lecture d\'un disque dur flotte à 5 nm (5 milliardièmes de mètre) au-dessus d\'un disque tournant à 7200 tr/min — un exploit de tribologie qui représente une feuille de papier à l\'échelle d\'une ville.</p></div>'
    '<h3>Tribologie et développement durable</h3>'
    '<p class="resume-text">Les pertes par <strong>frottement mécanique</strong> représentent environ 23% de la consommation d\'énergie mondiale (IEA). Un tiers de cette perte se produit dans les transports, un tiers dans l\'industrie et un tiers dans la production d\'énergie. Réduire le frottement de 20% dans les moteurs et transmissions permettrait d\'économiser l\'équivalent de la production électrique de plusieurs pays européens. Cette opportunité d\'économie d\'énergie fait de la tribologie un levier majeur de la transition énergétique.</p>'
    '<p class="resume-text">Les <strong>lubrifiants biosourcés</strong> (huiles végétales estérifiées, huiles de synthèse à base de plantes) remplacent progressivement les lubrifiants pétroliers dans les applications où le risque de contamination est élevé (agriculture, industrie alimentaire, sylviculture). Leurs performances égalent souvent les lubrifiants minéraux, avec l\'avantage de la biodégradabilité et d\'un bilan CO₂ réduit. L\'enjeu est leur stabilité thermique et leur coût légèrement supérieur.</p>'
    '<div class="highlight-box"><p>Les 23% d\'énergie mondiale perdus par frottement correspondent à plus de 2 fois la production électrique mondiale — la réduction du frottement mécanique est l\'un des leviers les plus efficaces pour la décarbonation de l\'économie.</p></div>'
),
'mecanique/resistance-des-materiaux': (
    '<h3>Torsion et contraintes combinées</h3>'
    '<p class="resume-text">La <strong>torsion</strong> d\'un arbre crée des contraintes de cisaillement maximales à la surface. Pour une section circulaire pleine, la contrainte de cisaillement τ = T·r/Ip, où T est le couple, r le rayon et Ip le moment polaire d\'inertie. Les arbres creux sont plus efficaces que les pleins : à moment d\'inertie polaire égal, ils utilisent moins de matière. Les arbres de transmission des voitures (propshaft) et les mâts d\'éoliennes sont soumis simultanément à la flexion (poids propre) et à la torsion (couple transmis).</p>'
    '<p class="resume-text">Les <strong>contraintes combinées</strong> (flexion + torsion + compression) requièrent les critères de résistance de Von Mises ou de Tresca pour évaluer le risque de plastification. Les vilebrequins des moteurs à explosion sont soumis à des cycles de flexion et de torsion qui varient à chaque révolution — c\'est un problème classique de fatigue multi-axiale. La fatigue est la cause de 80-90% des ruptures mécaniques en service, bien avant l\'atteinte de la limite d\'élasticité statique.</p>'
    '<p class="resume-text">La <strong>fatigue oligocyclique</strong> (peu de cycles à contrainte élevée) et la <strong>fatigue polycyclique</strong> (millions de cycles à contrainte modérée) obéissent à des courbes S-N (Wöhler) caractéristiques de chaque matériau. La limite d\'endurance des aciers (contrainte en dessous de laquelle la durée de vie est infinie) est environ 40% de la résistance à rupture. Les concentrateurs de contraintes (entailles, trous, rayons trop petits) réduisent drastiquement la limite d\'endurance — d\'où l\'attention portée aux rayons de raccordement dans les pièces mécaniques.</p>'
    '<div class="highlight-box"><p>80 à 90% des ruptures mécaniques en service sont dues à la fatigue — non à un dépassement de la résistance statique. Les pièces se rompent après des millions de cycles bien en dessous de la limite d\'élasticité.</p></div>'
    '<h3>Méthodes expérimentales en résistance des matériaux</h3>'
    '<p class="resume-text">Les <strong>jauges de déformation</strong> (strain gauges) sont des résistances métalliques qui varient proportionnellement à la déformation de la surface sur laquelle elles sont collées. En montage de pont de Wheatstone (4 jauges), elles mesurent des déformations de quelques microdéformations avec une précision de 0,1%. Les capteurs de force (cellules de charge), les capteurs de couple et les dynamomètres sont construits à partir de jauges de déformation sur des corps élastiques calibrés.</p>'
    '<p class="resume-text">La <strong>corrélation d\'images numériques</strong> (DIC — Digital Image Correlation) mesure les champs de déformation par analyse d\'images successives d\'un spécimen sous charge. En comparant la position des motifs aléatoires (mouchetis de peinture) entre l\'état de référence et l\'état déformé, le logiciel calcule les champs de déplacement et de déformation sur toute la surface. Cette méthode sans contact permet de visualiser les concentrations de contraintes, la propagation de fissures et le comportement des assemblages hétérogènes.</p>'
    '<div class="highlight-box"><p>La corrélation d\'images numériques (DIC) peut mesurer des déplacements de quelques nanomètres sur des pièces de quelques centimètres — permettant de valider expérimentalement les simulations éléments finis à l\'échelle du micron.</p></div>'
),
'mecanique/dynamique-des-systemes': (
    '<h3>Acoustique et bruit des machines</h3>'
    '<p class="resume-text">Le <strong>bruit et les vibrations des machines</strong> (NVH — Noise, Vibration, Harshness) sont une préoccupation majeure en ingénierie automobile, ferroviaire et aéronautique. Les sources de bruit incluent les déséquilibres rotatifs (vibrations synchrones de la vitesse de rotation), les engrenages (bruit aux fréquences de denture), les roulements (signatures spectrales caractéristiques de défauts) et les écoulements aérodynamiques. La signature vibratoire d\'une machine permet de diagnostiquer les défauts émergents bien avant la panne.</p>'
    '<p class="resume-text">La <strong>maintenance prédictive</strong> par analyse vibratoire est l\'application industrielle la plus répandue de la dynamique des systèmes. Des accéléromètres sur les paliers d\'un compresseur ou d\'une turbine mesurent en continu les niveaux et spectres vibratoires. Les algorithmes de traitement du signal (FFT, démodulation d\'enveloppe, ondelettes) détectent les signatures spectrales caractéristiques des défauts de roulements (BPFO, BPFI, BSF, FTF), d\'engrenages (GMF) ou de déséquilibre. L\'intelligence artificielle améliore la robustesse de ces diagnostics.</p>'
    '<p class="resume-text">L\'<strong>isolation vibratoire</strong> protège les équipements sensibles (microscopes, IRM, plateformes de précision) ou les structures environnantes (bâtiments proches de machines lourdes). Les systèmes passifs (silentblocs en caoutchouc, ressorts pneumatiques) atténuent les vibrations au-dessus de la fréquence propre du montage. Les systèmes actifs (capteurs + actuateurs piézo + algorithmes ANC) annulent les vibrations résiduelles par interférence destructive. Les plateformes d\'isolation active atteignent une isolation de 120 dB au-delà de 10 Hz.</p>'
    '<div class="highlight-box"><p>L\'analyse vibratoire d\'un roulement de turbine permet de détecter un défaut de bague intérieure plusieurs semaines avant la panne — la maintenance prédictive économise des milliards d\'euros d\'arrêts non planifiés dans l\'industrie mondiale.</p></div>'
),
'mecanique/forces-et-mouvements': (
    '<h3>Dynamique des fluides et interactions fluide-structure</h3>'
    '<p class="resume-text">Les <strong>forces de traînée et de portance</strong> agissant sur les corps en mouvement dans un fluide sont des applications fondamentales des lois de Newton aux interactions fluide-solide. La traînée (drag) s\'oppose au mouvement ; la portance (lift) est perpendiculaire. Le coefficient de traînée Cd caractérise la forme d\'un objet : Cd = 0,5 pour une sphère, 0,3 pour une automobile familiale, moins de 0,2 pour un prototype aérodynamique. Ces forces déterminent la consommation des véhicules et les performances des aéronefs.</p>'
    '<p class="resume-text">Les <strong>vibrations induites par vortex</strong> (VIV — Vortex-Induced Vibrations) se produisent lorsque l\'écoulement autour d\'une structure cylindrique crée des allées de tourbillons alternées (allée de von Kármán) à une fréquence proche de la fréquence propre de la structure. Ce phénomène a provoqué l\'effondrement du pont de Tacoma (1940), détruit des cheminées industrielles et oblige les concepteurs de pipelines sous-marins à dimensionner les structures contre ces excitations instables.</p>'
    '<div class="highlight-box"><p>La résistance de l\'air représente 70% de la consommation énergétique d\'un cycliste à 40 km/h — d\'où l\'importance des positions aérodynamiques et des équipements streamlinés dans les épreuves contre-la-montre.</p></div>'
    '<h3>Génie des structures et conception légère</h3>'
    '<p class="resume-text">La <strong>conception légère</strong> (lightweight design) cherche à minimiser la masse d\'une structure pour une performance donnée. L\'indice de performance (stiffness/weight = E¹/²/ρ pour les poutres en flexion) classe les matériaux selon leur efficacité structurale. Les mousses métalliques et polymères, les structures en treillis lattice et les structures sandwichs (peaux résistantes + âme légère) atteignent des indices de performance qu\'aucun matériau homogène ne peut égaler.</p>'
    '<p class="resume-text">Les <strong>structures bio-inspirées</strong> imitent les solutions développées par l\'évolution : os creux à structure trabéculaire (excellent ratio résistance/poids), ailes d\'oiseaux (cambrure variable), bambou (gradient de densité). L\'impression 3D métal permet de réaliser des structures à topologie optimisée (résultat d\'algorithmes d\'optimisation topologique) imitant ces architectures biologiques, inaccessibles à l\'usinage conventionnel.</p>'
    '<div class="highlight-box"><p>L\'os trabéculaire humain (tissu spongieux de l\'intérieur des os) a un ratio résistance/masse 5 fois supérieur à l\'acier — un modèle pour les ingénieurs en conception légère qui s\'inspirent de la nature pour optimiser les structures.</p></div>'
),
}

# Second pass for all groups - adding more to pages still under target
extra_elec = {
'electronique/signaux-numeriques': (
    '<h3>Codage et compression de l\'information</h3>'
    '<p class="resume-text">La <strong>théorie de l\'information</strong> (Shannon, 1948) définit l\'entropie comme la quantité minimale d\'information nécessaire pour représenter un message. Le codage de Huffman assigne des codes binaires plus courts aux symboles les plus fréquents — c\'est la base de la compression sans perte (ZIP, PNG). Le codage arithmétique, encore plus efficace, traite la séquence entière comme un nombre réel. Ces techniques sont omniprésentes dans les systèmes numériques : chaque octet stocké ou transmis peut être compressé.</p>'
    '<p class="resume-text">Les <strong>codes correcteurs d\'erreurs</strong> ajoutent de la redondance pour détecter et corriger les erreurs de transmission ou de stockage. Les codes Reed-Solomon (CD, DVD, QR codes, communications spatiales) corrigent des erreurs en rafale. Les codes LDPC (Low-Density Parity-Check) et Turbo codes approchent la limite théorique de Shannon pour les canaux bruités — utilisés dans les standards 4G/5G. Les mémoires Flash NVM utilisent le codage BCH ou LDPC pour compenser la dégradation des cellules après des milliers de cycles d\'écriture.</p>'
    '<p class="resume-text">La <strong>compression vidéo</strong> (HEVC/H.265, AV1, VVC) exploite la redondance temporelle (différences entre images successives) et spatiale (corrélations dans une image) pour réduire le débit de plusieurs centaines de fois sans perte perceptible. Un flux 4K non compressé nécessite 6 Gbit/s ; H.265 le réduit à 15 Mbit/s pour une qualité broadcast. Ces algorithmes exécutent des transformées en cosinus discrets (DCT), des prédictions intra/inter-frame et un codage entropique en temps réel sur des milliards de pixels par seconde.</p>'
    '<div class="highlight-box"><p>Netflix transmet 15% du trafic internet mondial — rendu possible par la compression vidéo HEVC qui réduit un film 4K de 50 Go non compressé à 20-25 Go, réduisant les besoins en bande passante d\'un facteur 100.</p></div>'
),
'electronique/microprocesseurs': (
    '<h3>Sécurité matérielle et cryptographie</h3>'
    '<p class="resume-text">La <strong>cryptographie matérielle</strong> accélère les opérations cryptographiques (AES, SHA, RSA, courbes elliptiques) dans des circuits dédiés, des milliers de fois plus rapides que les implémentations logicielles. Les HSM (Hardware Security Modules) sécurisent les clés cryptographiques dans une enclave matérielle inviolable — les banques et autorités de certification les utilisent pour les opérations critiques. L\'AES-NI (New Instructions) intégré dans tous les processeurs modernes x86 (Intel, AMD) chiffre les données à la vitesse du bus mémoire (plusieurs Go/s).</p>'
    '<p class="resume-text">La <strong>mémoire sécurisée</strong> (Secure Enclave d\'Apple, TrustZone d\'ARM) isole un environnement d\'exécution sécurisé (TEE — Trusted Execution Environment) du reste du système. Les données biométriques (empreintes digitales, Face ID), les clés de paiement et les certificats d\'identité sont traités uniquement dans cet espace protégé, inaccessible au système d\'exploitation principal même s\'il est compromis.</p>'
    '<div class="highlight-box"><p>La faille Meltdown (2018) a montré que l\'isolation mémoire entre processus — garantie fondamentale de sécurité depuis 40 ans — pouvait être contournée via le cache CPU : un rappel que la sécurité hardware est aussi fragile que ses optimisations de performance.</p></div>'
),
'electronique/composants-electroniques': (
    '<h3>Technologies d\'emballage et packaging avancé</h3>'
    '<p class="resume-text">Le <strong>packaging électronique</strong> assure la protection mécanique, thermique et électrique des puces. Les boîtiers DIP (Dual In-line Package, traversants), SOIC (Surface Mount), QFP (Quad Flat Package) et BGA (Ball Grid Array) évoluent vers des packageings de plus en plus denses. Les packages BGA des processeurs modernes (Intel Core, Apple M-series) ont des milliers de billes de soudure sous le circuit, offrant une meilleure dissipation thermique et une densité de connexions supérieure.</p>'
    '<p class="resume-text">Le <strong>packaging avancé</strong> (advanced packaging) empile des chiplets de fonctions différentes (CPU + GPU + mémoire HBM + contrôleur E/S) dans un seul package via des interconnexions 3D (TSV — Through Silicon Via, microbumps). L\'AMD EPYC Genoa et l\'Intel Sapphire Rapids utilisent cette approche pour augmenter la densité fonctionnelle au-delà des limites de la lithographie. Le packaging CoWoS (Chip on Wafer on Substrate) de TSMC pour les GPU NVIDIA H100 connecte des chiplets via des interposers en silicium avec des milliers de microbumps.</p>'
    '<div class="highlight-box"><p>Le package AMD EPYC 9654 contient 12 chiplets (chacun fabriqué en 5nm chez TSMC) assemblés dans un seul package de 8 cm² — une approche qui contourne les limites de taille des wafers de lithographie avancée.</p></div>'
),
'electronique/circuits-analogiques': (
    '<h3>Mesures et instrumentation analogique</h3>'
    '<p class="resume-text">Les <strong>instruments de mesure analogiques</strong> (oscilloscopes, générateurs de fonction, analyseurs de réseau) sont les outils fondamentaux du développement électronique. Les oscilloscopes numériques modernes (Keysight, Tektronix, Rohde & Schwarz) combinent la capture d\'événements transitoires rares (séquenceur complexe, signal apériodique) avec l\'analyse spectrale FFT en temps réel. La résolution verticale (bits d\'ADC) et la bande passante (de 100 MHz à 110 GHz) définissent le domaine d\'application.</p>'
    '<p class="resume-text">Les <strong>amplificateurs lock-in</strong> (détection synchrone) extraient des signaux extrêmement faibles (nano-volts) noyés dans le bruit. En modulant le signal d\'excitation à une fréquence de référence et en démodulant à cette même fréquence, le lock-in amplifie sélectivement la composante synchrone du signal. Ces instruments équipent les laboratoires de physique pour mesurer la résistance Hall quantique, les capteurs de gaz ultra-sensibles et les instruments de spectroscopie optique.</p>'
    '<div class="highlight-box"><p>Un amplificateur lock-in peut extraire un signal de 10 nV (10 millionièmes de mV) dans un bruit de 1 V — grâce à la détection synchrone qui filtre tout bruit non cohérent avec la fréquence de référence.</p></div>'
),
'electronique/systemes-embarques': (
    '<h3>Développement et débogage des systèmes embarqués</h3>'
    '<p class="resume-text">Le <strong>débogage des systèmes embarqués</strong> utilise des sondes JTAG/SWD (Joint Test Action Group / Serial Wire Debug) qui permettent d\'accéder aux registres et à la mémoire du microcontrôleur en cours d\'exécution, de placer des points d\'arrêt matériels et de tracer l\'exécution instruction par instruction. Les outils comme GDB + OpenOCD, SEGGER J-Link et STM32CubeIDE intègrent ces fonctions dans des environnements graphiques. Les analyseurs logiques (à 16+ canaux) capturent et décodent simultanément les protocoles SPI, I2C, UART, CAN pour diagnostiquer les problèmes de communication.</p>'
    '<p class="resume-text">Les <strong>outils de profilage</strong> (profiling) mesurent le temps passé dans chaque fonction du programme, identifiant les goulots d\'étranglement. L\'instrumentation par Event Recorder (Keil MDK) ou des timers hardware génère des traces d\'exécution précises à la microseconde. L\'analyse de la couverture de code (code coverage) vérifie que tous les chemins d\'exécution ont été testés — requis par les normes de certification sécuritaire (DO-178C exige une couverture MC/DC de 100% pour les logiciels de niveau A).</p>'
    '<div class="highlight-box"><p>La norme DO-178C pour les logiciels avioniques de niveau A (panne catastrophique) exige une vérification formelle de tous les chemins d\'exécution, des tests sur cible hardware et une traçabilité complète des exigences — un processus pouvant prendre 2 à 5 ans pour un logiciel de taille modeste.</p></div>'
),
}

extra_genie = {
'genie-civil/structures-porteuses': (
    '<h3>Structures dans les conditions extrêmes</h3>'
    '<p class="resume-text">Les <strong>structures offshore</strong> (plateformes pétrolières, éoliennes en mer) sont soumises à la combinaison de vagues, courants marins, vent et, dans les zones nordiques, glace. Les plateformes auto-élévatrices (jack-ups) reposent sur des pieds en treillis d\'acier ancrés dans le fond marin. Les plateformes semi-submersibles flottent et sont stabilisées par des ancrages. Les structures TLP (Tension Leg Platform) sont ancrées par des tiges tendues verticalement, limitant les mouvements verticaux. Le calcul des charges d\'ondes (théories d\'Airy, de Stokes, de Morison) est un domaine spécialisé de l\'ingénierie offshore.</p>'
    '<p class="resume-text">Les <strong>gratte-ciels</strong> posent des défis structuraux uniques liés à leur hauteur. Le vent (forces horizontales variables avec la hauteur) et le séisme imposent des systèmes de contreventement efficaces et une flexibilité suffisante pour ne pas gêner les occupants (accélérations perçues au sommet). Le Burj Khalifa (828 m) utilise un noyau central en béton armé haute performance et des ailes en Y qui réduisent les effets du vent par décrochage progressif des tourbillons. L\'Empire State Building (443 m, 1931) avait été conçu avec un réservoir d\'amarrage pour dirigeables au sommet — jamais utilisé pour des raisons de sécurité.</p>'
    '<div class="highlight-box"><p>Le Burj Khalifa (828 m, Dubai) consomme 250 000 tonnes de béton et 55 000 tonnes d\'acier — l\'équivalent de 5 tours Eiffel en acier et de nombreux ouvrages de génie civil réunis pour soutenir cette structure unique au monde.</p></div>'
),
'genie-civil/beton-arme': (
    '<h3>Construction durable et béton bas carbone</h3>'
    '<p class="resume-text">La <strong>production de ciment clinker</strong> est responsable de 8% des émissions mondiales de CO₂ (cuisson du calcaire à 1450°C libère du CO₂ irréductible). Les stratégies de décarbonation incluent les liants alternatifs : les laitiers de hauts fourneaux (slag), les cendres volantes (fly ash) et la fumée de silice remplacent partiellement le clinker. Le géopolymère (réaction de laitier ou cendres avec une solution alcaline) peut produire un liant sans clinker, réduisant les émissions de CO₂ de 60-80%. Ces bétons alternatifs représentent un défi de normalisation et d\'acceptation industrielle.</p>'
    '<p class="resume-text">Le <strong>béton à armatures composites</strong> (BFUP — Béton Fibré à Ultra-Hautes Performances) intègre des fibres métalliques ou en verre/carbone qui distribuent les efforts et contrôlent les fissures à l\'échelle microscopique. Le BFUP permet des éléments structuraux minces (5-10 cm contre 30-50 cm en béton armé conventionnel), des formes architecturales libres et une très grande durabilité. Des passerelles en BFUP de quelques centimètres d\'épaisseur franchissent 20-30 m sans armatures passives conventionnelles.</p>'
    '<div class="highlight-box"><p>Le ciment représente 8% des émissions mondiales de CO₂ — autant que l\'aviation mondiale. Le béton bas carbone (géopolymère, alkali-activé, à fort taux de substitution clinker) est l\'un des défis environnementaux majeurs de l\'industrie de la construction.</p></div>'
),
'genie-civil/ponts': (
    '<h3>Ponts à l\'ère numérique</h3>'
    '<p class="resume-text">Le <strong>BIM</strong> (Building Information Modeling) révolutionne la conception et la gestion des ouvrages d\'art. Un modèle BIM 3D contient non seulement la géométrie mais aussi les propriétés des matériaux, les données d\'inspection, les historiques de maintenance et les pièces de rechange associées. La norme IFC (Industry Foundation Classes) assure l\'interopérabilité entre logiciels (Revit, Tekla, SCIA). En France, le programme FAIR (Fichier d\'Activité des Ingénieurs Réseaux) vise à numériser tous les ouvrages d\'art sous maîtrise d\'ouvrage nationale.</p>'
    '<p class="resume-text">La <strong>fabrication numérique</strong> (CNC, impression 3D béton) ouvre des nouvelles possibilités pour les éléments de ponts. L\'impression 3D par extrusion de béton (Contour Crafting, XTreeE) a produit les premières passerelles imprimées au monde (MX3D en acier à Amsterdam, COBOD en béton au Danemark). La fabrication additive de pont en métal par DED (Directed Energy Deposition) produit des nœuds de charpente de géométrie complexe optimisée par algorithmes.</p>'
    '<div class="highlight-box"><p>La passerelle MX3D à Amsterdam — une structure en acier entièrement imprimée en 3D par robots de soudure sur 12,5 m de long — est équipée de 100 capteurs intégrés qui transmettent en temps réel les données de charge, température et déformation.</p></div>'
),
'genie-civil/fondations': (
    '<h3>Fondations des structures offshore et spéciales</h3>'
    '<p class="resume-text">Les <strong>fondations des éoliennes offshore</strong> sont l\'un des enjeux techniques majeurs de la transition énergétique. Les monopieux (diamètre 6-10 m, foncés à 30-40 m de profondeur) sont le type dominant pour les fonds marins peu profonds. Les jackets en treillis tubulaire conviennent pour des profondeurs de 40-60 m. Les fondations gravitaires en béton (blocs massifs posés sur le fond) sont utilisées dans les zones à sol rocheux. Les flotteurs (semi-submersibles, SPAR) ancrés par lignes de mouillage s\'imposent pour les grandes profondeurs (plus de 60 m).</p>'
    '<p class="resume-text">Les <strong>fondations des tunnels et infrastructures souterraines</strong> nécessitent une gestion précise des déformations du sol lors du creusement. Le tunnelier TBM (Tunnel Boring Machine) creuse et revêt simultanément le tunnel en béton préfabriqué (voussoirs). La méthode NATM (New Austrian Tunnelling Method) utilise le terrain comme élément porteur : un soutènement flexible (béton projeté, cintres, boulons d\'ancrage) est mis en place rapidement pour stabiliser le front de taille avant la consolidation.</p>'
    '<div class="highlight-box"><p>Les tunneliers TBM creusant le Grand Paris Express atteignent 15 m de diamètre et avancent de 10 à 20 m par jour — bétonnant simultanément le revêtement avec des voussoirs préfabriqués de 6 tonnes chacun.</p></div>'
),
'genie-civil/construction-parasismique': (
    '<h3>Systèmes d\'isolation sismique avancés</h3>'
    '<p class="resume-text">Les <strong>amortisseurs de masse accordée</strong> (TMD, Tuned Mass Dampers) sont des masses suspendues accordées sur la fréquence propre de la structure pour réduire ses vibrations. Ils dissipent l\'énergie sismique et éolienne par hystérésis. Les TMD liquides (TLCD) utilisent l\'oscillation d\'un fluide dans un tube en U. Ces dispositifs réduisent les accélérations de 20 à 40% dans les hautes tours, améliorant le confort des occupants et réduisant les dommages non structuraux.</p>'
    '<p class="resume-text">Les <strong>amortisseurs visqueux et hysterétiques</strong> (métal, plomb, élastomère) dissipent l\'énergie sismique dans des zones prédéfinies. Les amortisseurs de fluide visqueux (type amortisseur hydraulique) sont placés dans les diagonales des structures ou entre la structure et ses fondations. Ils permettent de réduire les forces sismiques de 30 à 60% tout en limitant les déformations. Après un séisme, ces amortisseurs peuvent être remplacés facilement, limitant les interruptions d\'activité.</p>'
    '<div class="highlight-box"><p>Les systèmes d\'isolation sismique permettent à des hôpitaux isolés de rester opérationnels après un séisme majeur — une exigence absolue pour les infrastructures médicales en zone sismique, où les besoins de soins explosent précisément après la catastrophe.</p></div>'
),
}

extra_ener = {
'energie/thermodynamique': (
    '<h3>Thermodynamique des nouvelles technologies énergétiques</h3>'
    '<p class="resume-text">Les <strong>cycles organiques de Rankine</strong> (ORC — Organic Rankine Cycle) utilisent des fluides organiques (pentane, réfrigérants HFO) au lieu de l\'eau pour valoriser des sources de chaleur basse température (80-300°C) : déchets industriels, géothermie, chaleur des moteurs. L\'efficacité est plus faible que la vapeur d\'eau (10-20%) mais la valorisation d\'une source de chaleur gratuite permet un excellent bilan économique. Les ORC équipent les cimenteries, aciéries, incinérateurs et centrales géothermiques.</p>'
    '<p class="resume-text">La <strong>thermoélectricité</strong> (effet Seebeck) convertit directement un gradient de température en tension électrique via des semiconducteurs thermoélectriques (Bi₂Te₃, PbTe, SiGe). Le coefficient de mérite ZT détermine l\'efficacité : les meilleurs matériaux actuels ont ZT ≈ 2-3, donnant des rendements de 10-15% pour ΔT = 300°C. Les générateurs thermoélectriques (RTG) alimentent les sondes spatiales Voyager, New Horizons et Cassini avec la chaleur de la désintégration du plutonium-238 — sans aucune pièce mobile depuis des décennies.</p>'
    '<div class="highlight-box"><p>Les sondes spatiales Voyager 1 et 2, lancées en 1977, sont encore alimentées par des générateurs thermoélectriques au plutonium-238 à plus de 20 milliards de km de la Terre — aucune pièce mobile, aucune maintenance, 50 ans de fonctionnement.</p></div>'
),
'energie/energie-nucleaire': (
    '<h3>Fusion nucléaire et énergie du futur</h3>'
    '<p class="resume-text">La <strong>fusion nucléaire</strong> (inverse de la fission) libère une énergie considérable en fusionnant des noyaux légers (deutérium + tritium → hélium + neutron + 17,6 MeV). Le combustible (eau de mer pour le deutérium, lithium pour produire le tritium) est quasi-inépuisable. La fusion ne produit pas de CO₂, les déchets radioactifs sont à durée de vie courte (décennies vs millénaires pour la fission), et la réaction ne peut pas s\'emballer (pas de criticité). Le défi est de confiner un plasma à 150 millions de degrés (10 fois la température du cœur du soleil).</p>'
    '<p class="resume-text">Le <strong>projet ITER</strong> (International Thermonuclear Experimental Reactor) en cours de construction à Cadarache (France) est le plus grand tokamak du monde. Il doit démontrer la viabilité physique de la fusion en produisant 500 MW thermiques pour 50 MW de chauffage (Q = 10). Le tokamak utilise des champs magnétiques supraconducteurs (bobines en Nb₃Sn à -269°C) pour confiner le plasma. ITER implique 35 pays, un budget de 20 milliards d\'euros et une mise en service du plasma prévue en 2025.</p>'
    '<div class="highlight-box"><p>ITER (Cadarache, France) sera le plus puissant tokamak jamais construit — ses 18 aimants supraconducteurs pèsent 300 tonnes chacun et génèrent un champ magnétique 200 000 fois supérieur à celui de la Terre pour confiner un plasma à 150 millions de degrés.</p></div>'
),
'energie/energies-renouvelables': (
    '<h3>Nouvelles frontières des renouvelables</h3>'
    '<p class="resume-text">L\'<strong>éolien flottant</strong> représente la prochaine révolution de l\'éolien offshore. Les turbines posées sur des plateformes semi-submersibles, SPAR ou à lignes tendues peuvent s\'installer dans des zones de plus de 60 m de profondeur, couvrant 80% des gisements éoliens côtiers européens actuellement inexploitables. Hywind Scotland (Equinor, 5 turbines de 6 MW flottantes) est le premier parc éolien flottant commercial au monde depuis 2017. Le coût doit encore baisser de 60-70% pour atteindre la compétitivité avec l\'éolien posé.</p>'
    '<p class="resume-text">Les <strong>panneaux solaires à pérovskite</strong> promettent des cellules très efficaces (>30% en tandem avec le silicium) et fabriquables par impression à jet d\'encre sur des surfaces flexibles. Leur défi actuel est la durabilité (dégradation accélérée sous humidité et chaleur) et la présence de plomb dans certaines formulations. Des startups comme Oxford PV et Saule Technologies travaillent à la commercialisation. Les cellules pérovskite/silicium en tandem pourraient dépasser 35% de rendement en production de masse.</p>'
    '<div class="highlight-box"><p>L\'éolien flottant ouvre 80% des côtes européennes à l\'exploitation éolienne offshore — permettant de placer les turbines face aux meilleurs vents, loin des côtes, sans contrainte de profondeur d\'eau.</p></div>'
),
'energie/stockage-energie': (
    '<h3>Stockage thermique et chaleur industrielle</h3>'
    '<p class="resume-text">Le <strong>stockage intersaisonnier de chaleur</strong> (STES — Seasonal Thermal Energy Storage) permet de stocker la chaleur estivale (solaire, cogénération estivale) dans le sol ou l\'eau souterraine pour la restituer en hiver. Les aquifères (nappes d\'eau souterraine à 10-15°C naturellement) chauffés en été à 60-80°C fonctionnent comme des batteries thermiques géantes. Les champs de sondes géothermiques (BTES) injectent la chaleur dans la roche. Le système de Drake Landing (Canada) fournit 90% de l\'énergie de chauffage de 52 maisons par ce principe depuis 2007.</p>'
    '<p class="resume-text">Le <strong>Power-to-X</strong> convertit l\'électricité renouvelable excédentaire en vecteurs énergétiques stockables : hydrogène (P2H), méthane de synthèse (P2G — Power to Gas par méthanation), ammoniac (P2A) ou carburants synthétiques (P2F — Power to Fuel par Fischer-Tropsch). Ces voies permettent le stockage saisonnier (semi-annuel) qui échappe aux batteries, la décarbonation de l\'industrie chimique et la production de carburants d\'aviation durables (SAF — Sustainable Aviation Fuel).</p>'
    '<div class="highlight-box"><p>Le stockage Power-to-X (électricité → hydrogène ou méthane → stockage → reconversion) a un rendement aller-retour de seulement 25-40% — mais c\'est le seul moyen économique de stocker de l\'électricité pendant des mois pour lisser la production saisonnière des renouvelables.</p></div>'
),
'energie/reseaux-electriques': (
    '<h3>Marchés de l\'électricité et mécanismes de prix</h3>'
    '<p class="resume-text">Le <strong>marché spot de l\'électricité</strong> (EPEX Spot en Europe) détermine le prix de l\'électricité par enchères horaires. Les producteurs soumettent des offres (prix, quantité) ; les consommateurs formulent des demandes. L\'algorithme d\'appariement (market clearing) fixe le prix marginal système (PMS) qui équilibre offre et demande à chaque heure. En période de forte production renouvelable, les prix peuvent descendre en territoire négatif — signifiant que les producteurs paient pour écouler leur surplus.</p>'
    '<p class="resume-text">Les <strong>mécanismes de capacité</strong> rémunèrent les producteurs pilotables (centrales à gaz, hydraulique) pour leur disponibilité, indépendamment de leur production effective. Ces mécanismes garantissent la sécurité d\'approvisionnement en compensant la réduction de revenus des centrales de pointe déplacées par les renouvelables à coût marginal nul. La France, l\'Angleterre et d\'autres pays européens ont mis en place ces mécanismes pour maintenir une capacité de réserve suffisante.</p>'
    '<div class="highlight-box"><p>En mai 2024, l\'Espagne a produit 100% de son électricité à partir des renouvelables pendant plusieurs jours, avec des prix négatifs sur le marché spot — un signe que la transition énergétique remodèle profondément le fonctionnement des marchés électriques.</p></div>'
),
}

extra_mat = {
'materiaux/metaux-et-alliages': (
    '<h3>Métallurgie des poudres et fabrication additive</h3>'
    '<p class="resume-text">La <strong>métallurgie des poudres</strong> (frittage) comprime et chauffe des poudres métalliques sous leur point de fusion pour produire des pièces presque finies. Les pièces frittées (roulements poreux lubrifiés, engrenages, filtres) ont une porosité contrôlée utile pour la lubrification ou la filtration. La poudre de métal sphérique fine (10-50 μm) produite par atomisation gazeuse est le point de départ de l\'impression 3D métal (SLM, EBM).</p>'
    '<p class="resume-text">La <strong>fusion sur lit de poudre</strong> (SLM — Selective Laser Melting, EBM — Electron Beam Melting) est la technique d\'impression 3D métal la plus répandue pour les pièces structurales. Un laser (SLM) ou un faisceau d\'électrons (EBM) fusionne sélectivement la poudre couche par couche. La microstructure obtenue (grains colonnaires dus aux gradients thermiques élevés) diffère du coulé ou du forgé, avec des propriétés mécaniques parfois supérieures après traitement thermique post-fabrication.</p>'
    '<div class="highlight-box"><p>GE Aviation imprime les injecteurs de carburant du réacteur CFM LEAP en cobalt-chrome par SLM — une pièce unique remplace un assemblage soudé de 20 composants, 25% plus légère et 5 fois plus résistante à l\'oxydation haute température.</p></div>'
),
'materiaux/polymeres': (
    '<h3>Mise en œuvre des polymères</h3>'
    '<p class="resume-text">L\'<strong>injection plastique</strong> est le procédé de mise en forme le plus utilisé pour les thermoplastiques. Le polymère fondu (190-300°C) est injecté sous pression (500-2000 bars) dans un moule refroidi. Le cycle (injection + refroidissement + éjection) dure de 10 s à 1 min. Les tolérances dimensionnelles atteignent ±0,05 mm sur des pièces complexes. Les moules en acier inoxydable ou en alliages spéciaux coûtent 10 000 à 500 000 euros — l\'investissement est amorti sur des millions de pièces.</p>'
    '<p class="resume-text">L\'<strong>extrusion</strong> produit des profilés, tubes, feuilles et câbles en continu en forçant le polymère fondu à travers une filière de forme appropriée. L\'extrusion-soufflage crée les bouteilles PET et PEHD. L\'extrusion-laminage produit les films d\'emballage multi-couches (barrière O₂, barrière vapeur, couche d\'adhésion) qui conservent les aliments. L\'impression FDM (Fused Deposition Modeling) est une extrusion discontinue couche par couche pour les pièces personnalisées.</p>'
    '<div class="highlight-box"><p>L\'injection plastique produit 300 millions de tonnes de pièces par an dans le monde — des valves médicales stériles aux pièces automobiles en passant par les jouets et les boîtiers électroniques, ce procédé est à la base de l\'industrie manufacturière moderne.</p></div>'
),
'materiaux/ceramiques': (
    '<h3>Céramiques dans l\'électronique et l\'énergie</h3>'
    '<p class="resume-text">Les <strong>substrats céramiques</strong> (alumine Al₂O₃, nitrure d\'aluminium AlN, carbure de silicium SiC) sont indispensables en électronique de puissance. Leur combinaison de conductivité électrique nulle et de conductivité thermique élevée (AlN : 170 W/m·K) permet d\'isoler les circuits tout en évacuant les pertes thermiques. Les modules IGBT et SiC pour les variateurs de vitesse et les véhicules électriques utilisent des substrats DBC (Direct Bonded Copper) en céramique pour souder le cuivre directement sur l\'alumine.</p>'
    '<p class="resume-text">Les <strong>céramiques de batterie</strong> ouvrent des perspectives pour les batteries solid-state. Les électrolytes solides céramiques (LiLaZrO — LLZO, LIPON) ont une conductivité ionique de 10⁻⁴ à 10⁻³ S/cm, se rapprochant des électrolytes liquides, tout en bloquant les dendrites de lithium. Ces matériaux permettent d\'utiliser un anode de lithium métal pur (3x plus dense en énergie que le graphite) sans risque de court-circuit. La mise à l\'échelle de la fabrication de ces électrolytes céramiques minces et denses est le verrou technologique actuel.</p>'
    '<div class="highlight-box"><p>L\'électrolyte céramique LLZO (grenat de lithium-lanthane-zirconium) des batteries solid-state a une résistance mécanique 10 fois supérieure aux séparateurs plastiques conventionnels — et bloque physiquement les dendrites de lithium qui causent les courts-circuits.</p></div>'
),
'materiaux/composites': (
    '<h3>Composites dans la mobilité du futur</h3>'
    '<p class="resume-text">Les <strong>véhicules électriques à structure composite</strong> bénéficient doublement de l\'allègement : moins de masse à déplacer ET batterie plus petite pour la même autonomie. La BMW i3 (2013) a été le premier véhicule de grande série avec une cellule passagers entièrement en CFRP (Carbon Fibre Reinforced Polymer). La technologie de tressage de fibres de carbone sur mandrin (RTM haute pression) permet une cadence de production de 100 unités/jour — incomparable avec l\'autoclave aéronautique mais suffisant pour l\'automobile haut de gamme.</p>'
    '<p class="resume-text">L\'<strong>économie circulaire des composites</strong> est le défi majeur pour la prochaine décennie. Les composites thermodurcissables (80% du marché) ne sont pas recyclables par voie thermique. Les solutions actuelles : recyclage mécanique (broyage pour charges dans les plastiques), recyclage chimique (solvolyse à haute température pour récupérer les fibres), et transition vers les matrices thermoplastiques recyclables (PEEK/CF, PA/CF). Les réglementations européennes (Directive Véhicules Hors d\'Usage) vont contraindre les constructeurs à des taux de recyclage de 85% — incluant les composites.</p>'
    '<div class="highlight-box"><p>Un airbus A350 contient 53 tonnes de composites carbone-époxy — à sa fin de vie (après 30 ans), ces matériaux thermodurcissables ne peuvent pas être refondus, imposant des solutions de recyclage chimique encore en développement.</p></div>'
),
'materiaux/nanomateriaux': (
    '<h3>Nanotechnologies médicales et pharmaceutiques</h3>'
    '<p class="resume-text">Les <strong>nanoparticules liposomales</strong> encapsulent des médicaments dans des vésicules de lipides de 50-200 nm pour les délivrer spécifiquement aux tumeurs (effet EPR — Enhanced Permeability and Retention). Les nanoparticules de lipides sont le vecteur des vaccins à ARNm (Pfizer/BioNTech, Moderna contre le SARS-CoV-2) : elles protègent l\'ARNm fragile de la dégradation enzymatique et facilitent son entrée dans les cellules. Ces nano-vecteurs ont rendu possible une technologie vaccinale de rupture en quelques mois.</p>'
    '<p class="resume-text">Les <strong>nanocomposites osseux</strong> (hydroxyapatite nanométrique dans un polymère biodégradable) imitent la structure naturelle de l\'os (fibres de collagène + cristaux d\'apatite de 100 nm). Ces scaffolds résorbables permettent la régénération osseuse : des cellules souches se développent sur l\'architecture poreuse, sécrètent de l\'os naturel tandis que le scaffold se dégrade progressivement. Cette approche de médecine régénérative évite les greffes autologues douloureuses et les implants permanents.</p>'
    '<div class="highlight-box"><p>Les nanoparticules lipidiques des vaccins ARNm COVID-19 ont démontré que la nanotechnologie peut passer de la recherche académique à la production de milliards de doses en 12 mois — un record de rapidité pour la mise à l\'échelle d\'une technologie de rupture.</p></div>'
),
}

extra_rob = {
'robotique/capteurs-et-perception': (
    '<h3>Capteurs de force et de contact</h3>'
    '<p class="resume-text">Les <strong>capteurs de force 6 axes</strong> (force/torque sensors) mesurent simultanément les 3 forces et 3 couples agissant sur l\'effecteur robotique. Ils utilisent des jauges de déformation sur un corps élastique en aluminium ou acier. Ces capteurs permettent le contrôle d\'impédance (compliance control) pour les opérations d\'assemblage précis (insertion d\'un arbre dans un alésage), le polissage adaptatif et la collaboration humain-robot avec détection des contacts involontaires. La peau artificielle (artificial skin) distribue des centaines de tactels sur la surface d\'un robot pour détecter les contacts sur toute sa surface.</p>'
    '<p class="resume-text">Les <strong>capteurs biométriques</strong> mesurent les signaux physiologiques humains : électroencéphalogramme (EEG) pour l\'interface cerveau-ordinateur (BCI), électromyogramme (EMG) pour contrôler des prothèses myoélectriques par les signaux musculaires résiduels, photopléthysmographie (PPG) pour le rythme cardiaque. Ces capteurs permettent l\'interaction naturelle entre humains et systèmes robotiques et l\'assistance aux personnes handicapées.</p>'
    '<div class="highlight-box"><p>Les prothèses myoélectriques modernes (bras Otto Bock) lisent les signaux EMG de muscles résiduels pour contrôler jusqu\'à 10 degrés de liberté de la main — permettant de tenir un œuf ou serrer une main avec une force modulée par l\'intention musculaire.</p></div>'
),
'robotique/actionneurs-et-commande': (
    '<h3>Tendances en actionnement robotique</h3>'
    '<p class="resume-text">Les <strong>exosquelettes</strong> amplifient la force humaine ou assistent la locomotion des personnes à mobilité réduite. Les exosquelettes industriels (Sarcos Guardian XO, Ekso Works) permettent de porter des charges de 90 kg sans effort pour les opérateurs en usine ou en logistique. Les exosquelettes médicaux (ReWalk, Indego, Ekso GT) aident les personnes paraplégiques à marcher. Les défis restants sont l\'autonomie de batterie (4-8h), le poids propre et la naturalité des interactions mécaniques avec le corps humain.</p>'
    '<p class="resume-text">Les <strong>actionneurs pneumatiques à muscles artificiels</strong> (Festo Fluidic Muscle, McKibben actuator) se contractent de 25% lorsqu\'alimentés en pression, développant des forces spécifiques comparables aux muscles naturels (60 N/cm²). Leur fonctionnement silencieux, leur légèreté et leur compliance inhérente les rendent attrayants pour les robots collaboratifs et les orthèses. La commande reste complexe car leur comportement non-linéaire dépend de la longueur et de la pression.</p>'
    '<div class="highlight-box"><p>L\'exosquelette ReWalk (Argo Medical Technologies) permet à des paraplégiques de marcher grâce à des servos actionnant les hanches et genoux — synchronisés avec des capteurs d\'inclinaison qui détectent l\'intention de marche du porteur.</p></div>'
),
'robotique/ia-embarquee': (
    '<h3>Modèles fondationnels pour la robotique</h3>'
    '<p class="resume-text">Les <strong>grands modèles de langage</strong> (LLM — Large Language Models) comme GPT-4, Gemini et Claude peuvent être combinés avec des capacités robotiques pour créer des agents autonomes polyvalents. Le projet PaLM-E (Google) a montré qu\'un modèle entraîné sur texte et images peut planifier des tâches robotiques de manipulation complexes en interprétant des instructions en langage naturel. Ces modèles encodent des connaissances générales sur le monde physique qui manquent aux systèmes de contrôle robotique spécialisés.</p>'
    '<p class="resume-text">L\'<strong>apprentissage zéro-shot et few-shot</strong> permet aux robots de généraliser à des tâches jamais vues pendant l\'entraînement, à partir d\'une simple description ou d\'une seule démonstration. RT-2 (Google DeepMind) est un modèle vision-action entraîné sur des milliards d\'images internet et des données robotiques qui transfère ses connaissances générales à des tâches de manipulation — identifiant un "Pepsi trash" (terme non vu en entraînement robotique) grâce à sa compréhension du langage et de la vision.</p>'
    '<div class="highlight-box"><p>Figure AI et Boston Dynamics ont démontré des robots humanoïdes capables de répondre à des instructions vocales et de manipuler des objets inconnus grâce aux grands modèles de langage — signalant l\'émergence d\'une robotique généraliste réaliste à l\'horizon 2030.</p></div>'
),
'robotique/robots-industriels': (
    '<h3>Cobots et nouvelle génération de robots industriels</h3>'
    '<p class="resume-text">Les <strong>robots de collaboration humain-machine</strong> de nouvelle génération (Universal Robots e-Series, KUKA LBR iisy, Fanuc CRX) intègrent nativement des fonctions de sécurité sans cage : limitation de vitesse et de force, détection de collision par mesure de couple articulaire, arrêt d\'urgence catégorie 0 instantané. Leur programmation par apprentissage (guidage à la main, interface web no-code) permet à des opérateurs sans formation robotique de déployer un cobot en quelques heures. Le marché des cobots croît de 30% par an, dopé par les PME qui ne peuvent pas justifier les robots traditionnels.</p>'
    '<p class="resume-text">Les <strong>robots à intelligence artificielle intégrée</strong> (ABB GoFa avec AI vision, Fanuc AI servo system) utilisent des algorithmes d\'apprentissage pour s\'adapter automatiquement aux variations de pièces (pièces fondues avec tolérance variable, tri de colis de formes aléatoires). Le picking de colis (bin picking) par vision 3D et grasping adaptatif résout des problèmes autrefois impossibles à robotiser. Ces systèmes réduisent les temps de programmation de semaines à heures tout en gérant des variantes de produits infinies.</p>'
    '<div class="highlight-box"><p>Le marché mondial des robots industriels a atteint 553 000 unités installées en 2022 — dont 50 000 cobots, un segment qui triple tous les 4 ans à mesure que les PME et les marchés émergents adoptent la robotisation.</p></div>'
),
'robotique/drones': (
    '<h3>Réglementation et intégration dans l\'espace aérien</h3>'
    '<p class="resume-text">La <strong>réglementation européenne des drones</strong> (EU 2019/945, 2021/664) classe les drones par catégories de risque (Open, Specific, Certified). La catégorie "Open" (moins de 25 kg, vol à vue à moins de 120 m) ne nécessite qu\'une formation en ligne et l\'enregistrement de l\'appareil. La catégorie "Specific" (plus de risque) requiert une évaluation de risque SORA (Specific Operations Risk Assessment) soumise à l\'autorité nationale. La catégorie "Certified" (équivalent à l\'aviation commerciale) s\'applique aux taxis aériens eVTOL et aux drones de livraison BVLOS à grande échelle.</p>'
    '<p class="resume-text">Les <strong>taxis aériens électriques à décollage vertical</strong> (eVTOL — electric Vertical Take-Off and Landing) représentent la prochaine révolution de la mobilité urbaine. Joby Aviation, Archer, Lilium, Wisk et EHang développent des appareils certifiables pour la mobilité aérienne urbaine (UAM — Urban Air Mobility). L\'objectif est de transporter 2 à 5 passagers à 150-250 km/h sur 30-150 km avec des émissions nulles en exploitation. Les certifications FAA et EASA pour ces nouvelles catégories d\'aéronefs sont en cours.</p>'
    '<div class="highlight-box"><p>Joby Aviation vise une certification FAA et un lancement commercial de son taxi aérien eVTOL à 5 places en 2025 — capable de voler à 320 km/h sur 240 km avec un niveau sonore 100 fois inférieur à un hélicoptère thermique.</p></div>'
),
}

all_extras = {**extra_meca, **extra_elec, **extra_genie, **extra_ener, **extra_mat, **extra_rob}

count = 0
for key, extra in all_extras.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (second pass all sections)")
