import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = 'C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/ingenierie.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

MARKER = '</section>\n\n<section class="content-section" id="quiz">'

def add_to_contenu(content, extra_html):
    return content.replace(MARKER, extra_html + MARKER, 1)

enrichments = {}

enrichments['energie/thermodynamique'] = (
    '<h3>Les quatre lois de la thermodynamique</h3>'
    '<p class="resume-text">Le <strong>principe zéro</strong> établit la notion d\'équilibre thermique : si deux systèmes sont en équilibre thermique avec un troisième, ils le sont entre eux. Ce principe fonde la notion de température comme grandeur d\'état. Le <strong>premier principe</strong> (conservation de l\'énergie) stipule que la variation d\'énergie interne d\'un système est la somme de la chaleur reçue et du travail reçu : ΔU = Q + W. Il est la base de tous les bilans énergétiques en ingénierie thermique.</p>'
    '<p class="resume-text">Le <strong>deuxième principe</strong> introduit l\'entropie et le sens des évolutions. Dans un système isolé, l\'entropie ne peut qu\'augmenter ou rester constante. Ce principe interdit le mouvement perpétuel de seconde espèce. Le rendement de Carnot ηCarnot = 1 - Tfroid/Tchaud fixe la limite maximale théorique des machines thermiques — jamais atteinte en pratique.</p>'
    '<div class="highlight-box"><p>Le rendement d\'une centrale thermique est fondamentalement limité par le théorème de Carnot — une centrale fonctionnant entre 600°C et 30°C ne peut dépasser 66% de rendement théorique.</p></div>'
    '<h3>Cycles thermodynamiques des machines</h3>'
    '<p class="resume-text">Le <strong>cycle de Rankine</strong> est le cycle idéal des turbines à vapeur des centrales électriques. L\'eau est pompée, vaporisée dans la chaudière à haute pression, détendue dans la turbine (production de travail) et condensée (rejet de chaleur). Le cycle Rankine à vapeur surchauffée des centrales nucléaires françaises fonctionne entre 300°C et 30°C avec un rendement thermodynamique d\'environ 33%.</p>'
    '<p class="resume-text">Le <strong>cycle de Brayton</strong> est le cycle des turbines à gaz et des réacteurs d\'avion. L\'air est comprimé (ratio 20:1 à 40:1), mélangé au carburant et brûlé, puis détendu dans la turbine. Les turboréacteurs modernes ont des températures de sortie supérieures à 1700°C, nécessitant des aubes en superalliages refroidis à l\'air. Le cycle combiné (turbine à gaz + turbine à vapeur) atteint des rendements de 60-62%.</p>'
    '<p class="resume-text">Le <strong>cycle de Stirling</strong> est théoriquement le plus efficace pour les machines à combustion externe. Son fonctionnement silencieux (pas d\'explosion) convient aux sous-marins à propulsion anaérobie (AIP) et à la cogénération domestique. Les moteurs Stirling à hélium à haute pression sont utilisés dans les applications spatiales (générateurs RTG).</p>'
    '<div class="highlight-box"><p>Les centrales à cycle combiné (turbine à gaz + vapeur récupérée) atteignent 62% de rendement électrique — contre 33% pour une centrale nucléaire classique.</p></div>'
    '<h3>Transferts thermiques et échangeurs</h3>'
    '<p class="resume-text">La <strong>conduction thermique</strong> transfère la chaleur par agitation moléculaire dans un milieu solide ou fluide immobile. La loi de Fourier donne le flux : q = -λ·∇T, où λ est la conductivité thermique. Les métaux (λ ≈ 50-400 W/m·K) conduisent bien ; les mousses polymères (λ ≈ 0,02 W/m·K) isolent. Les échangeurs à plaques utilisent des parois minces en acier inoxydable pour maximiser les échanges entre fluides tout en minimisant la résistance thermique.</p>'
    '<p class="resume-text">La <strong>convection thermique</strong> (naturelle ou forcée) est le mode d\'échange dominant dans les fluides en mouvement. Le coefficient de convection h (en W/m²·K) caractérise l\'efficacité de l\'échange. Les ailettes (radiateurs de refroidissement) augmentent la surface d\'échange pour compenser un h faible. La convection forcée (ventilateurs, pompes) est bien plus efficace que la naturelle.</p>'
    '<p class="resume-text">Le <strong>rayonnement thermique</strong> émet de l\'énergie par ondes électromagnétiques, sans nécessiter de milieu matériel. La loi de Stefan-Boltzmann donne la puissance rayonnée : P = ε·σ·T⁴·A. L\'émissivité ε varie de 0,05 (aluminium poli) à 0,95 (surface noire mate). Les couvertures de survie (mylar aluminisé) réfléchissent 95% du rayonnement infrarouge pour préserver la chaleur corporelle.</p>'
    '<div class="highlight-box"><p>Le coefficient U d\'une paroi (conduction + convection des deux côtés) mesure ses pertes thermiques — la réglementation RE2020 impose U &lt; 0,15 W/m²·K pour les toitures des bâtiments neufs.</p></div>'
    '<h3>Machines thermiques industrielles</h3>'
    '<p class="resume-text">Les <strong>turbines à vapeur</strong> équipent les centrales nucléaires, thermiques et les industries à fort besoin de vapeur (raffineries, papeteries). Les aubes de turbine doivent résister à des contraintes thermiques (600°C) et mécaniques (centrifugation) extrêmes. Les superalliages à base nickel (Inconel, Hastelloy) et les techniques de refroidissement par film d\'air permettent de dépasser les limites des métaux conventionnels.</p>'
    '<p class="resume-text">La <strong>réfrigération par compression</strong> inverse le cycle de Rankine : un compresseur élève la pression d\'un fluide frigorigène, qui se condense (rejette de la chaleur à l\'extérieur), se détend, s\'évapore (absorbe de la chaleur utile). Le coefficient de performance (COP) d\'un réfrigérateur domestique est de 3 à 5 : pour 1 kWh d\'électricité, on extrait 3 à 5 kWh de chaleur froide. Les pompes à chaleur utilisent ce même principe à l\'envers pour chauffer.</p>'
    '<p class="resume-text">Les <strong>pompes à chaleur géothermiques</strong> utilisent la chaleur stable du sol (8-15°C à 10m de profondeur) comme source froide ou chaude. Avec un COP de 4 à 5, elles produisent 4 à 5 kWh de chaleur pour 1 kWh électrique consommé. Les sondes géothermiques verticales (100-150m de profondeur) ou les capteurs horizontaux (enterrés à 1m) constituent l\'échangeur sol-eau. Ces installations réduisent la consommation de chauffage de 70% par rapport au gaz.</p>'
    '<div class="highlight-box"><p>Un réfrigérateur à cycle de compression avec un COP de 4 produit 4 fois plus de froid que l\'équivalent d\'un refroidissement direct à l\'électricité — le cycle de Carnot explique cette efficacité remarquable.</p></div>'
)

enrichments['energie/energie-nucleaire'] = (
    '<h3>Physique nucléaire et réactions en chaîne</h3>'
    '<p class="resume-text">La <strong>fission nucléaire</strong> consiste à scinder un noyau lourd (uranium-235, plutonium-239) en deux fragments plus légers, libérant environ 200 MeV par fission, soit 2 à 3 neutrons et des rayonnements gamma. L\'énergie libérée par gramme est 2 millions de fois supérieure à celle du charbon. Pour maintenir une <strong>réaction en chaîne contrôlée</strong>, chaque fission doit en provoquer exactement une autre (facteur de multiplication k = 1, état critique).</p>'
    '<p class="resume-text">Les <strong>neutrons rapides</strong> libérés par la fission ont trop d\'énergie pour provoquer efficacement de nouvelles fissions dans l\'uranium-235. Un <strong>modérateur</strong> (eau légère, eau lourde, graphite) ralentit les neutrons jusqu\'aux vitesses thermiques (0,025 eV), où la section efficace de fission est 1000 fois plus élevée. L\'eau légère est le modérateur le plus utilisé (réacteurs PWR et BWR) — elle nécessite un enrichissement de l\'uranium à 3-5% en U-235.</p>'
    '<p class="resume-text">Le <strong>contrôle du réacteur</strong> repose sur les barres de contrôle (acier inoxydable chargé en bore) qui absorbent les neutrons sans en émettre. En cas d\'urgence, l\'insertion rapide de toutes les barres (SCRAM) arrête la fission en quelques secondes. La puissance résiduelle (chaleur de décroissance radioactive) reste cependant de l\'ordre de 7% de la puissance nominale après l\'arrêt — c\'est cette chaleur qui a causé la fusion du cœur à Fukushima lorsque le refroidissement a été perdu.</p>'
    '<div class="highlight-box"><p>1 kg d\'uranium-235 libère autant d\'énergie que 2500 tonnes de charbon — mais la gestion des déchets radioactifs représente un défi multigénérationnel sans équivalent.</p></div>'
    '<h3>Technologies des réacteurs</h3>'
    '<p class="resume-text">Les <strong>réacteurs PWR</strong> (Pressurized Water Reactor) représentent 70% du parc mondial. L\'eau du circuit primaire est maintenue liquide sous 155 bars à 320°C. Elle chauffe un circuit secondaire (vapeur) dans le générateur de vapeur, produisant la vapeur qui entraîne la turbine. Cette double boucle évite la contamination radioactive du circuit turbine. Les 56 réacteurs français (900 MWe à 1450 MWe) sont tous des PWR.</p>'
    '<p class="resume-text">Les <strong>réacteurs à neutrons rapides</strong> (RNR) utilisent des neutrons rapides sans modérateur et peuvent utiliser le plutonium comme combustible. Le sodium liquide (excellent caloporteur) est le caloporteur de référence. La technologie RNR permet théoriquement de brûler les actinides mineurs (les déchets les plus dangereux à long terme) tout en produisant de l\'énergie.</p>'
    '<p class="resume-text">Les réacteurs <strong>SMR</strong> (Small Modular Reactors, moins de 300 MWe) suscitent un intérêt croissant pour leur fabrication en usine, leur flexibilité de déploiement et leur coût d\'investissement accessible. Les designs incluent des réacteurs à eau pressurisée miniaturisés (NuScale, Rolls-Royce), des réacteurs à sels fondus et des réacteurs à haute température au gaz. Plusieurs sont en cours de certification en Europe, USA et Canada.</p>'
    '<div class="highlight-box"><p>La France produit 70% de son électricité d\'origine nucléaire avec 56 réacteurs PWR — la plus forte proportion au monde, qui lui assure l\'une des plus faibles empreintes CO₂ par kWh d\'Europe.</p></div>'
    '<h3>Cycle du combustible et gestion des déchets</h3>'
    '<p class="resume-text">Le <strong>cycle du combustible</strong> comprend l\'extraction du minerai d\'uranium, la conversion en hexafluorure d\'uranium (UF₆), l\'enrichissement isotopique par centrifugation, la fabrication des assemblages combustibles, le séjour en réacteur (4 ans typiquement), le stockage en piscine de refroidissement puis le retraitement ou le stockage définitif.</p>'
    '<p class="resume-text">Le <strong>retraitement</strong> (procédé PUREX, utilisé à La Hague en France) sépare l\'uranium et le plutonium restants du combustible usé pour les réutiliser dans du combustible MOX. La France retraite 1700 tonnes de combustible usé par an. Les déchets hautement radioactifs sont vitrifiés dans une matrice de verre borosilicaté et stockés provisoirement avant enfouissement géologique profond.</p>'
    '<p class="resume-text">Le <strong>stockage géologique profond</strong> (CIGÉO en France, à Bure) est la solution internationale pour les déchets de haute activité et vie longue. À 500m de profondeur dans une couche d\'argilite imperméable, les colis seront stockés pendant des dizaines de milliers d\'années. Tout le combustible nucléaire usé produit en France depuis 40 ans tiendrait dans un cube de 20 mètres de côté.</p>'
    '<div class="highlight-box"><p>Le processus de vitrification transforme les déchets radioactifs liquides en un solide de verre stable chimiquement pendant plus de 100 000 ans — une prouesse de chimie des matériaux pour les générations futures.</p></div>'
)

enrichments['energie/energies-renouvelables'] = (
    '<h3>Énergie solaire photovoltaïque</h3>'
    '<p class="resume-text">L\'<strong>effet photovoltaïque</strong> convertit la lumière en électricité dans les cellules semiconductrices. Les photons absorbés créent des paires électron-trou séparées par le champ électrique de la jonction P-N. Les cellules monocristallines en silicium atteignent 22-26% de rendement ; les cellules polycristallines, plus économiques, plafonnent à 17-20%. Les cellules tandem (perovskite sur silicium) dépassent 30% en laboratoire et approchent de la commercialisation.</p>'
    '<p class="resume-text">Le <strong>solaire à concentration</strong> (CSP) utilise des miroirs pour concentrer le rayonnement solaire sur un fluide caloporteur. Les centrales à tour avec des sels fondus comme caloporteur et stockage thermique intégré peuvent produire de l\'électricité 24h/24. Le stockage thermique (tank de sel fondu à 565°C) offre 10 à 15 heures d\'autonomie — un avantage majeur sur les panneaux PV classiques.</p>'
    '<div class="highlight-box"><p>Le parc photovoltaïque mondial a atteint 1 TW de puissance installée en 2022. Les coûts ont chuté de 90% en 10 ans, faisant du solaire l\'électricité la moins chère jamais produite dans l\'histoire.</p></div>'
    '<h3>Éolien terrestre et offshore</h3>'
    '<p class="resume-text">Les <strong>éoliennes à axe horizontal</strong> captent l\'énergie cinétique du vent par rotation de pales aérodynamiques. La loi de Betz fixe la limite théorique à 59% de l\'énergie cinétique disponible. La puissance varie en cube de la vitesse : doubler la vitesse du vent multiplie la puissance par 8. Les grandes éoliennes actuelles atteignent 15-18 MW avec des pales de 115 m — plus long qu\'un terrain de football.</p>'
    '<p class="resume-text">Les <strong>éoliennes offshore</strong> bénéficient de vents plus réguliers et plus forts qu\'à terre. Les éoliennes posées (monopieu, jacket) s\'installent jusqu\'à 60m de profondeur. Les éoliennes flottantes (semi-submersibles) ouvrent des zones plus profondes, couvrant 80% des façades atlantiques européennes. Leur coût a chuté de 70% depuis 2012 et continue de baisser.</p>'
    '<p class="resume-text">L\'<strong>intégration réseau</strong> des énergies renouvelables variables est le défi majeur de la transition énergétique. La prévision météorologique à court terme permet d\'anticiper la production et d\'ajuster les moyens pilotables. Le stockage (batteries, STEP) et les interconnexions transfrontalières permettent de lisser les fluctuations. Les smart grids optimisent en temps réel la consommation et la production distribuée.</p>'
    '<div class="highlight-box"><p>L\'Allemagne a produit plus de 60% de son électricité à partir des renouvelables en 2023 — mais dépend encore du gaz et du charbon pour sécuriser l\'approvisionnement en période sans vent ni soleil.</p></div>'
    '<h3>Hydraulique, géothermie et énergies marines</h3>'
    '<p class="resume-text">L\'<strong>hydroélectricité</strong> est la première source d\'électricité renouvelable mondiale (16% de la production mondiale). Les barrages-réservoirs stockent l\'énergie potentielle de l\'eau pour la restituer à la demande — contrairement au solaire et à l\'éolien, l\'hydraulique est pilotable. Les STEP (pompage-turbinage) sont le principal moyen de stockage d\'électricité à grande échelle en Europe.</p>'
    '<p class="resume-text">La <strong>géothermie haute énergie</strong> (Islande, Nouvelle-Zélande, Philippines) produit de la vapeur à 150-300°C directement utilisable pour l\'électricité. La géothermie basse énergie (30-90°C) alimente des réseaux de chaleur urbains. Les systèmes géothermiques stimulés (EGS) injectent de l\'eau dans des roches granitiques fracturées à 5km de profondeur pour en extraire la chaleur.</p>'
    '<p class="resume-text">Les <strong>énergies marines</strong> incluent les hydroliennes (courants marins), les usines marémotrices (Rance, 240 MW depuis 1966), les convertisseurs de houle et les gradients thermiques. Le potentiel est immense mais les contraintes techniques (salinité, biofouling, conditions extrêmes) restent des défis d\'ingénierie majeurs à surmonter.</p>'
    '<div class="highlight-box"><p>La centrale marémotrice de la Rance (Bretagne, 1966) est la plus ancienne encore en service — 240 MW produisant 500 GWh par an grâce aux 13,5 m de marnage de la baie.</p></div>'
)

enrichments['energie/stockage-energie'] = (
    '<h3>Batteries électrochimiques</h3>'
    '<p class="resume-text">Une <strong>batterie</strong> convertit l\'énergie chimique en énergie électrique par des réactions d\'oxydoréduction. Dans une cellule Li-ion, le lithium s\'intercale dans l\'anode de graphite lors de la charge. La cathode (NMC, LFP) et l\'anode (graphite, silicium) déterminent la densité énergétique et la durabilité. La <strong>chimie LFP</strong> (lithium fer phosphate) offre sécurité élevée, longue durée de vie (plus de 3000 cycles) et faible coût, s\'imposant dans les véhicules électriques d\'entrée de gamme et les systèmes stationnaires.</p>'
    '<p class="resume-text">La chimie <strong>NMC</strong> (nickel-manganèse-cobalt) offre une densité énergétique supérieure (250 Wh/kg vs 160 Wh/kg pour le LFP) au prix d\'une durée de vie moindre — utilisée dans les véhicules à longue autonomie. Les <strong>batteries à l\'état solide</strong> remplacent l\'électrolyte liquide inflammable par un solide, promettant densité doublée et sécurité renforcée. Toyota, QuantumScape et Solid Power visent une commercialisation dans les véhicules haut de gamme d\'ici 2027-2030.</p>'
    '<div class="highlight-box"><p>La batterie du Tesla Model S (100 kWh) pèse 625 kg et contient 8256 cellules cylindriques — un chef d\'œuvre d\'ingénierie thermique et électrique pour gérer leur équilibre et température.</p></div>'
    '<h3>Stockage mécanique et thermique</h3>'
    '<p class="resume-text">Les <strong>STEP</strong> (Stations de Transfert d\'Énergie par Pompage) représentent 95% du stockage d\'électricité mondial. En surplus de production, l\'eau est pompée vers un réservoir haut. En déficit, on turbine l\'eau pour produire de l\'électricité. Le rendement aller-retour est de 70-85%. La STEP de Grand-Maison (Alpes, 1800 MW) est la plus puissante de France.</p>'
    '<p class="resume-text">Les <strong>volants d\'inertie</strong> (flywheels) stockent l\'énergie sous forme cinétique dans un disque tournant à grande vitesse. Les volants en fibre de carbone dans des enceintes sous vide magnétique atteignent 100 000 tr/min. Leur réponse quasi-instantanée et leur durée de vie quasi-illimitée (aucune dégradation chimique) les rendent idéaux pour la stabilisation rapide des réseaux électriques.</p>'
    '<p class="resume-text">Le <strong>stockage thermique</strong> sous forme de chaleur (tanks de sel fondu, ballons d\'eau chaude, matériaux à changement de phase) est la forme de stockage la moins chère par kWh. Les réseaux de chaleur urbains avec stockage intersaisonnier permettent de stocker la chaleur estivale pour la restituer en hiver. Drake Landing (Canada) couvre 90% des besoins de chauffage d\'un quartier par ce principe.</p>'
    '<div class="highlight-box"><p>Le coût du stockage par batterie Li-ion a chuté de 1500 $/kWh en 2010 à moins de 100 $/kWh en 2024 — franchissant le seuil de rentabilité pour les applications réseau à grande échelle.</p></div>'
    '<h3>Hydrogène et piles à combustible</h3>'
    '<p class="resume-text">L\'<strong>hydrogène vert</strong> est produit par électrolyse de l\'eau avec de l\'électricité renouvelable. L\'électrolyseur à membrane PEM est compact et réactif aux variations de production renouvelable, avec un rendement de 65-75%. L\'hydrogène peut être stocké sous haute pression (700 bars), liquéfié à -253°C ou sous forme d\'ammoniac, et reconverti en électricité dans une pile à combustible.</p>'
    '<p class="resume-text">La <strong>pile à combustible PEM</strong> génère de l\'électricité par réaction entre hydrogène (anode) et oxygène (cathode) à travers une membrane sélective aux protons. Le seul déchet est de l\'eau pure. La Toyota Mirai et la Hyundai Nexo illustrent l\'usage automobile. Les piles SOFC (à oxyde solide, 600-1000°C) conviennent à la cogénération industrielle avec un rendement électrique de 60% et un rendement global de 85%.</p>'
    '<p class="resume-text">La <strong>chaîne hydrogène</strong> a un rendement aller-retour de seulement 25-35%, contre 75-85% pour les batteries. Ce désavantage est compensé par la densité énergétique massique supérieure (120 MJ/kg pour H₂), la facilité de stockage longue durée et les grandes capacités. L\'hydrogène s\'imposera pour l\'aviation, la navigation, les camions longue distance et le stockage saisonnier.</p>'
    '<div class="highlight-box"><p>L\'hydrogène a une densité d\'énergie 3 fois supérieure au kérosène en masse — mais 3000 fois inférieure en volume à pression atmosphérique, imposant de le comprimer à 700 bars ou le liquéfier à -253°C.</p></div>'
)

enrichments['energie/reseaux-electriques'] = (
    '<h3>Structure du réseau électrique</h3>'
    '<p class="resume-text">Le réseau électrique européen est le plus grand système synchrone du monde, opérant en courant alternatif à 50 Hz. La <strong>fréquence réseau</strong> est l\'indicateur de l\'équilibre production/consommation : si la consommation dépasse la production, la fréquence descend. Elle doit rester dans ±0,2 Hz pour éviter le délestage automatique. RTE (France) gère 100 000 km de lignes à très haute tension.</p>'
    '<p class="resume-text">La <strong>hiérarchie de tension</strong> permet le transport sur de longues distances avec des pertes minimales. Les centrales produisent à 10-20 kV ; des transformateurs élèvent la tension à 400 kV pour le transport sur milliers de kilomètres. La tension est ensuite abaissée en 225 kV, 90 kV, 20 kV (industries) puis 230 V (particuliers). À chaque niveau, les pertes Joule sont d\'autant plus faibles que la tension est haute.</p>'
    '<p class="resume-text">Les <strong>postes de transformation</strong> contiennent les transformateurs de puissance, les disjoncteurs (qui interrompent le courant en quelques millisecondes), les sectionneurs et les systèmes de protection. Les disjoncteurs HT (SF₆ ou vide) interrompent des courants de court-circuit de plusieurs dizaines de kiloampères. Les systèmes de protection détectent les défauts en quelques millisecondes et isolent les sections défaillantes.</p>'
    '<div class="highlight-box"><p>La panne électrique du 4 novembre 2006 a plongé dans le noir 15 millions d\'Européens en quelques secondes — une cascade de déclenchements provoquée par une erreur de manœuvre sur une ligne allemande.</p></div>'
    '<h3>Transport HVDC et smart grid</h3>'
    '<p class="resume-text">Le <strong>transport en courant continu haute tension</strong> (HVDC) est préféré pour les grandes distances (plus de 600 km) et les liaisons sous-marines. Les pertes résistives sont inférieures à l\'AC, et les deux extrémités peuvent appartenir à des réseaux AC de fréquences différentes. La liaison France-Angleterre (IFA, ±270 kV, 2000 MW) passe sous la Manche en HVDC. Les convertisseurs VSC en technologie IGBT permettent des liens multiterminaux flexibles.</p>'
    '<p class="resume-text">Le <strong>smart grid</strong> (réseau intelligent) intègre des capteurs, des compteurs communicants (Linky en France) et des systèmes d\'optimisation pour adapter la consommation à la production. L\'effacement (demand response) incite les gros consommateurs industriels à réduire temporairement leur charge lors des pointes. Les véhicules électriques (Vehicle-to-Grid, V2G) peuvent injecter de l\'énergie dans le réseau lors des pointes.</p>'
    '<p class="resume-text">La <strong>compensation réactive</strong> maintient la tension dans les limites acceptables sur le réseau. Les condensateurs en batteries fournissent de la puissance réactive capacitive. Les FACTS (Flexible AC Transmission Systems) — SVC, STATCOM — permettent une compensation dynamique quasi-instantanée pour stabiliser des lignes fortement chargées par les énergies renouvelables variables.</p>'
    '<div class="highlight-box"><p>En 2022, les énergies renouvelables représentaient 38% de la production électrique européenne — nécessitant une adaptation profonde des règles d\'équilibrage réseau conçues pour des centrales pilotables.</p></div>'
    '<h3>Efficacité énergétique et décarbonation</h3>'
    '<p class="resume-text">L\'<strong>efficacité énergétique</strong> réduit la consommation d\'énergie pour un service identique. Les moteurs électriques IE4 (Super Premium Efficiency) consomment 2-3% de moins que les IE2, ce qui représente des économies significatives pour les moteurs industriels tournant 8000 heures par an. Les variateurs de fréquence (VFD) adaptent la vitesse des pompes et ventilateurs à la demande réelle, économisant jusqu\'à 50% d\'énergie.</p>'
    '<p class="resume-text">La <strong>cogénération</strong> produit simultanément électricité et chaleur à partir d\'une même source d\'énergie primaire. Un groupe cogénération au gaz naturel convertit 40% du gaz en électricité et récupère 45% en chaleur utile, soit un rendement global de 85% contre 55% maximum pour une production séparée. Les hôpitaux, data centers et industries agroalimentaires l\'utilisent largement.</p>'
    '<p class="resume-text">La <strong>transition vers les réseaux bas-carbone</strong> transforme profondément la structure des réseaux électriques. La multiplication des producteurs décentralisés crée des flux bidirectionnels sur des réseaux historiquement conçus pour un sens unique. Les nouvelles protections adaptatives, les micro-grids autonomes et les marchés de capacité sont les outils de cette transition.</p>'
    '<div class="highlight-box"><p>RTE doit équilibrer production et consommation à chaque instant sur 100 000 km de lignes avec une précision de ±0,2 Hz — un défi croissant avec l\'intégration de 60 GW d\'éolien et de solaire variable d\'ici 2035.</p></div>'
)

# Apply enrichments
count = 0
for key, extra in enrichments.items():
    if key in data['pages']:
        p = data['pages'][key]
        if p.get('type') == 'course':
            old_len = len(p['content'])
            p['content'] = add_to_contenu(p['content'], extra)
            new_len = len(p['content'])
            print(f"{key}: {old_len} -> {new_len} chars")
            count += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nDone - {count} pages enriched (energie section)")
