#!/usr/bin/env python3
"""Fourth pass: neurochimie + neuro-imagerie + conscience pages."""
import json

PATH = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita/assets/content/neurosciences.json"

with open(PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)
pages = data['pages']

def inject(key, html):
    page = pages[key]
    content = page['content']
    if '<div class="quiz-nav">' in content:
        content = content.replace('<div class="quiz-nav">', html + '\n<div class="quiz-nav">', 1)
    else:
        idx = content.rfind('</section>')
        content = content[:idx] + html + '\n' + content[idx:]
    page['content'] = content

# ── neurochimie ───────────────────────────────────────────────────────────────

inject('neurochimie/neurotransmetteurs', """
<h3>Les cotransmetteurs et la complexité chimique synaptique</h3>
<p class="resume-text">Les neurones libèrent rarement un seul neurotransmetteur. La coexistence de plusieurs messagers chimiques dans une même terminaison synaptique — les <strong>cotransmetteurs</strong> — est la règle plutôt que l'exception. Un neurone dopaminergique peut libérer simultanément de la dopamine, du glutamate et des neuropeptides. Cette combinaison crée des effets différenciés selon les récepteurs présents sur la cellule cible et permet une modulation fine et contextuelle de la transmission synaptique.</p>
<p class="resume-text">Les <strong>neuropeptides</strong> (substance P, endorphines, NPY, VIP) forment une classe de cotransmetteurs à action lente et durable : libérés lors de stimulations intenses, ils modulent l'excitabilité des circuits sur des minutes à des heures, là où les petites molécules (glutamate, GABA) agissent en millisecondes. Cette dualité rapide/lente permet aux synapses de coder à la fois l'information précise sur l'activité instantanée et le contexte émotionnel et métabolique général.</p>
<div class="highlight-box"><p><strong>Chiffre :</strong> On compte aujourd'hui plus de 100 neurotransmetteurs et neuropeptides identifiés dans le cerveau humain. Les gaz de signalisation (oxyde nitrique NO, monoxyde de carbone CO) constituent une classe particulière : libérés par diffusion directe à travers la membrane, ils agissent rétrogradement — de la cellule postsynaptique vers la présynaptique — et jouent un rôle clé dans la LTP.</p></div>

<h3>Les récepteurs ionotropes versus métabotropes</h3>
<p class="resume-text">Les neurotransmetteurs agissent via deux grandes classes de récepteurs. Les récepteurs <strong>ionotropes</strong> (AMPA, NMDA, GABA-A, nicotiniques) sont des canaux ioniques à ouverture directe : la liaison du ligand ouvre immédiatement le pore, permettant un flux ionique en moins d'une milliseconde. Ils sous-tendent la transmission synaptique rapide, point à point. Les récepteurs <strong>métabotropes</strong> (dopaminergiques D1/D2, sérotoninergiques 5-HT1/2, mGluR, muscariniques) couplent la liaison du ligand à des protéines G intracellulaires, déclenchant des cascades de second messager (AMPc, IP3, DAG). Leurs effets sont plus lents (100 ms à plusieurs secondes), plus durables, et peuvent modifier l'expression génique.</p>
<p class="resume-text">La distribution régionale des récepteurs détermine les effets comportementaux d'un neurotransmetteur. Les récepteurs D1 dopaminergiques, couplés positivement à l'adénylate cyclase, sont concentrés dans le striatum et le cortex préfrontal. Les récepteurs D2, couplés négativement, dominent dans le striatum ventral et le cortex. Les antipsychotiques classiques bloquent les D2 striataux — réduisant les symptômes positifs de la schizophrénie — mais aussi les D2 corticaux et limbiques, causant les effets secondaires (symptômes négatifs aggravés, syndrome extrapyramidal).</p>

<h3>La synaptogenèse et le recyclage des vésicules</h3>
<p class="resume-text">La libération des neurotransmetteurs est un processus finement régulé. Un potentiel d'action arrive à la terminaison présynaptique, ouvrant les canaux calciques voltage-dépendants. L'entrée de calcium déclenche la fusion des vésicules synaptiques avec la membrane plasmique via les protéines SNARE (synaptobrévine, syntaxine, SNAP-25). Le contenu vésiculaire est libéré dans la fente synaptique en moins d'une milliseconde. La toxine botulinique agit précisément en clivant ces protéines SNARE, bloquant la libération d'acétylcholine et causant une paralysie flasque.</p>
<p class="resume-text">Après libération, les neurotransmetteurs sont rapidement éliminés de la fente synaptique par trois mécanismes : recapture dans la terminaison présynaptique via des transporteurs spécialisés (transporteur de la dopamine DAT, de la sérotonine SERT — cibles des antidépresseurs), dégradation enzymatique (acétylcholinestérase pour l'acétylcholine, MAO pour les monoamines), ou diffusion hors de la fente. Les vésicules sont recyclées localement par endocytose pour un nouveau cycle de libération.</p>
""")

inject('neurochimie/dopamine', """
<h3>Les voies dopaminergiques et leurs fonctions</h3>
<p class="resume-text">La dopamine est produite par deux noyaux principaux du tronc cérébral. La <strong>voie nigrostriatale</strong> (substantia nigra → striatum dorsal) contrôle les mouvements volontaires — sa dégénérescence cause la maladie de Parkinson. La <strong>voie mésolimbique</strong> (ATV → nucleus accumbens, amygdale, hippocampe) code la motivation, le désir et l'anticipation de la récompense — sur-activée dans les addictions. La <strong>voie mésocorticale</strong> (ATV → cortex préfrontal) module la mémoire de travail, la planification et le contrôle cognitif — hypofonctionnelle dans la schizophrénie et la dépression.</p>
<p class="resume-text">La <strong>voie tubéroinfundibulaire</strong> (hypothalamus → hypophyse) régule la sécrétion de prolactine : la dopamine inhibe normalement cette sécrétion, si bien que les antipsychotiques bloqueurs D2 provoquent une hyperprolactinémie (galactorrhée, troubles menstruels). Cette voie illustre que la dopamine, au-delà de ses fonctions cérébrales, est un régulateur neuroendocrinien systémique.</p>
<div class="highlight-box"><p><strong>Dopamine vs plaisir :</strong> Une idée fausse répandue associe la dopamine au « plaisir ». Les recherches de Kent Berridge distinguent le « wanting » (désir, médié par la dopamine mésolimbique) du « liking » (plaisir hédonique, médié par les opioïdes dans le noyau accumbens). On peut vouloir intensément quelque chose (forte dopamine) sans en éprouver de plaisir — état typique des addictions avancées.</p></div>

<h3>La dopamine dans les maladies et les traitements</h3>
<p class="resume-text">La maladie de Parkinson résulte de la perte progressive de 60-70 % des neurones dopaminergiques de la substantia nigra avant l'apparition des symptômes moteurs (tremblement de repos, rigidité, bradykinésie). La L-DOPA, précurseur de la dopamine traversant la barrière hémato-encéphalique, est le traitement pharmacologique de référence depuis 1967. Son efficacité diminue avec les années à mesure que la dénerivation progresse, et elle cause des dyskinésies après 5-10 ans de traitement chez la majorité des patients.</p>
<p class="resume-text">La stimulation cérébrale profonde (SCP) des noyaux sous-thalamiques ou du globus pallidus interne a révolutionné le traitement du Parkinson avancé depuis les années 1990 : des électrodes implantées délivrent un courant haute fréquence (130-180 Hz) qui modifie l'activité oscillatoire pathologique des ganglions de la base (oscillations bêta excessives), réduisant de 50-70 % les symptômes moteurs. Cette thérapie neuromodulatrice illustre comment la compréhension des circuits peut mener à des traitements ciblés sans les effets systémiques des médicaments.</p>

<h3>La dopamine et l'addiction</h3>
<p class="resume-text">Toutes les drogues d'abus — cocaïne, amphétamines, alcool, opioïdes, nicotine, cannabis — partagent un mécanisme commun : elles augmentent la concentration de dopamine dans le nucleus accumbens, entre 200 % et 1000 % au-dessus des valeurs basales. La cocaïne et les amphétamines bloquent le transporteur DAT ou inversent son transport ; l'alcool et les opioïdes désinhibent les neurones dopaminergiques de l'ATV en supprimant l'inhibition GABAergique interneuronale.</p>
<p class="resume-text">L'exposition répétée à ces drogues entraîne des adaptations neurobiologiques profondes : tolérance (réduction des récepteurs D2 disponibles), sensibilisation (augmentation de la réactivité à la drogue et aux signaux associés), et modification de la connectivité préfrontale-limbique rendant le contrôle inhibiteur des impulsions moins efficace. Ces adaptations persistent des mois à des années après l'arrêt de la consommation, expliquant la vulnérabilité chronique à la rechute.</p>
""")

inject('neurochimie/serotonine', """
<h3>Les noyaux du raphé et la distribution sérotoninergique</h3>
<p class="resume-text">La sérotonine est synthétisée dans les neurones des <strong>noyaux du raphé</strong>, une série de noyaux médians du tronc cérébral (raphé dorsal, médian, magnus, pallidus). Bien que ces noyaux ne contiennent que 200 000 à 300 000 neurones au total, leurs projections axonales couvrent la quasi-totalité du cerveau et de la moelle épinière. Le raphé dorsal innerve le cortex, le striatum, l'amygdale et l'hippocampe ; le raphé magnus envoie des projections descendantes vers la corne dorsale médullaire, modulant la transmission de la douleur.</p>
<p class="resume-text">La synthèse de la sérotonine (5-hydroxytryptamine, 5-HT) débute avec le tryptophane alimentaire, converti en 5-hydroxytryptophane (5-HTP) par la tryptophane hydroxylase, puis en sérotonine par la décarboxylase des acides aminés aromatiques. La disponibilité du tryptophane alimentaire influence donc directement la synthèse cérébrale de sérotonine — c'est le rationnel du régime riche en tryptophane (dinde, noix, banane) parfois recommandé pour améliorer l'humeur, bien que les effets comportementaux soient modestes.</p>
<div class="highlight-box"><p><strong>L'intestin et la sérotonine :</strong> 95 % de la sérotonine corporelle est produite dans l'intestin (cellules entérochromaffines), où elle régule le péristaltisme. Cette sérotonine intestinale ne traverse pas la barrière hémato-encéphalique, mais l'axe intestin-cerveau via le nerf vague transmette des signaux influençant l'humeur et le comportement — ce qui explique l'expression « avoir les tripes nouées » et les liens entre troubles digestifs et dépression.</p></div>

<h3>Les antidépresseurs sérotoninergiques et leur mécanisme</h3>
<p class="resume-text">Les inhibiteurs sélectifs de la recapture de la sérotonine (ISRS) — fluoxétine (Prozac), sertraline, paroxétine — bloquent le transporteur SERT, augmentant la concentration de 5-HT dans la fente synaptique. Paradoxalement, leur effet antidépresseur met 2-4 semaines à se manifester malgré l'augmentation immédiate de 5-HT, suggérant que l'effet thérapeutique ne passe pas directement par la concentration synaptique mais par des adaptations à long terme : désensibilisation des autorécepteurs 5-HT1A présynaptiques, augmentation de la neurogénèse hippocampique et remodelage synaptique progressif.</p>
<p class="resume-text">Les <strong>psychédéliques</strong> classiques (LSD, psilocybine, DMT) agissent comme agonistes des récepteurs 5-HT2A sur les neurones pyramidaux du cortex préfrontal, perturbant profondément la hiérarchie corticale et désorganisant les prédictions top-down — expliquant les hallucinations et les altérations de la conscience. La psilocybine fait l'objet d'essais cliniques prometteurs pour la dépression résistante, l'addiction à l'alcool et le trouble de stress post-traumatique, avec des effets durables après 1-2 sessions supervisées.</p>

<h3>Sérotonine, cognition et comportement social</h3>
<p class="resume-text">Au-delà de l'humeur, la sérotonine module le comportement social, l'agressivité et la tolérance à l'incertitude. L'appauvrissement expérimental en tryptophane (qui réduit la synthèse de 5-HT) augmente l'agressivité et les comportements impulsifs chez les humains sains. Les souris knock-out pour le gène du transporteur SERT (équivalent d'un traitement chronique aux ISRS) montrent une anxiété accrue, paradoxalement — illustrant que les effets à long terme de l'augmentation chronique de 5-HT sont complexes et dépendants du développement.</p>
<p class="resume-text">La <strong>distribution des récepteurs</strong> détermine l'effet comportemental : les récepteurs 5-HT1A postsynaptiques dans l'hippocampe régulent l'anxiété et la neurogénèse ; les 5-HT2C dans l'hypothalamus contrôlent l'appétit (raison pour laquelle les médicaments anti-obésité ciblaient ces récepteurs) ; les 5-HT3 dans le tronc cérébral et l'intestin contrôlent la nausée (les antagonistes 5-HT3 comme l'ondansétron sont les antiémétiques de référence en chimiothérapie).</p>
""")

inject('neurochimie/synapses', """
<h3>La plasticité synaptique à court terme</h3>
<p class="resume-text">En plus de la LTP et de la LTD (plasticité à long terme), les synapses exhibent une plasticité à court terme se manifestant sur des échelles de millisecondes à quelques secondes. La <strong>facilitation synaptique</strong> augmente la probabilité de libération lors de stimulations répétées rapprochées : le calcium résiduel de la stimulation précédente s'accumule dans la terminaison présynaptique, potentialisant la libération suivante. La <strong>dépression synaptique</strong> s'oppose à ce mécanisme : l'épuisement du pool vésiculaire disponible réduit la réponse lors de stimulations soutenues.</p>
<p class="resume-text">L'équilibre entre facilitation et dépression synaptique détermine si une synapse est un « filtre passe-bas » (déprimante, ne transmettant que les trains de basse fréquence) ou un « filtre passe-haut » (facilitante, amplifiant les rafales de haute fréquence). Cette diversité dynamique permet au réseau neuronal de traiter l'information de manière temporellement sélective — les synapses thalamocorticales utilisent la dépression pour adapter leur gain à l'intensité du stimulus continu (adaptation sensorielle).</p>
<div class="highlight-box"><p><strong>La fente synaptique :</strong> L'espace entre membrane pré et postsynaptique mesure environ 20 nm. Ce microscopique espace est occupé par une matrice protéique (molécules d'adhésion, néurexines, néuroligines) qui aligne précisément les zones actives présynaptiques avec les densités postsynaptiques et organise la position des récepteurs pour maximiser leur activation par les neurotransmetteurs libérés.</p></div>

<h3>Les synapses électriques et les jonctions gap</h3>
<p class="resume-text">Contrairement aux synapses chimiques, les <strong>synapses électriques</strong> (jonctions communicantes, gap junctions) permettent le passage direct du courant électrique entre deux cellules via des canaux protéiques (connexines). La transmission est bidirectionnelle, quasi instantanée (sans délai synaptique), et ne nécessite pas de neurotransmetteur. Les synapses électriques sont particulièrement abondantes entre interneurones GABAergiques du cortex, où elles synchronisent des populations entières d'interneurones, générant les oscillations gamma qui accompagnent les traitements cognitifs.</p>
<p class="resume-text">Le rôle des jonctions gap change durant le développement : chez le fœtus et le nouveau-né, elles sont largement répandues et permettent la propagation des vagues d'activité spontanée qui guident le câblage neuronal précoce. Avec la maturation, les synapses chimiques prennent le relais pour une signalisation plus précise et modulable. Chez l'adulte, les jonctions gap persistent dans des niches spécifiques : cellules de Purkinje cérébelleuses, cellules de la rétine, et entre cellules gliales (astrocytes) où elles forment des syncytiums fonctionnels.</p>

<h3>La transmission rétrograde et les endocannabinoïdes</h3>
<p class="resume-text">La communication synaptique n'est pas unidirectionnelle : les cellules postsynaptiques peuvent envoyer des signaux en retour vers la terminaison présynaptique — la <strong>transmission rétrograde</strong>. Les endocannabinoïdes (anandamide, 2-AG) sont les messagers rétrogrades les mieux caractérisés. Synthétisés « à la demande » dans la cellule postsynaptique lors d'une dépolarisation forte, ils diffusent en sens inverse à travers la fente synaptique pour se lier aux récepteurs CB1 présynaptiques, réduisant la libération de neurotransmetteur pour les secondes suivantes — un mécanisme de rétroaction négative homéostatique.</p>
<p class="resume-text">Le cannabis (THC) détourne ce système en activant les récepteurs CB1 de manière exogène et prolongée. Les effets cognitifs (mémoire à court terme, concentration) et sensoriels (perception altérée du temps, amplification sensorielle) reflètent la distribution des récepteurs CB1 dans le cortex préfrontal, l'hippocampe et les cortex sensoriels. La forte densité de récepteurs CB1 dans les ganglions de la base explique les effets moteurs (relaxation musculaire, ataxie) et dans le cervelet les effets sur la coordination.</p>
""")

inject('neurochimie/pharmacologie', """
<h3>La pharmacocinétique et la pharmacodynamique cérébrales</h3>
<p class="resume-text">Pour exercer un effet sur le cerveau, un médicament doit franchir la <strong>barrière hémato-encéphalique</strong> (BHE). Cette barrière, formée par les cellules endothéliales des capillaires cérébraux reliées par des jonctions serrées et enveloppées d'astrocytes, filtre sélectivement les molécules. Les molécules lipophiles de faible poids moléculaire traversent aisément (benzodiazépines, cannabis, alcool) ; les molécules polaires ou de grande taille sont bloquées (adrénaline, anticorps, nanoparticules). La L-DOPA franchit la BHE grâce à son transporteur (LAT1), là où la dopamine elle-même en est incapable.</p>
<p class="resume-text">La pharmacodynamique décrit les interactions drogue-récepteur. L'affinité mesure la force de liaison (constante Ki) ; l'efficacité (intrinsic efficacy) détermine si la liaison active ou bloque le récepteur (agoniste plein, agoniste partiel, antagoniste, agoniste inverse). Un antagoniste bloque le récepteur sans l'activer — les bêtabloquants (propranolol) sont des antagonistes des récepteurs bêta-adrénergiques, réduisant la réponse au stress sans imiter ses effets.</p>
<div class="highlight-box"><p><strong>Fenêtre thérapeutique :</strong> Le lithium, traitement de référence du trouble bipolaire depuis 1949, illustre la difficulté de la pharmacologie cérébrale : sa concentration thérapeutique (0,6-1,2 mEq/L) est proche de sa concentration toxique (> 1,5 mEq/L). Un contrôle régulier de la lithémie est obligatoire — l'une des rares instances en psychiatrie où la concentration plasmatique guide directement la dose.</p></div>

<h3>Les cibles moléculaires des psychotropes</h3>
<p class="resume-text">Les psychotropes agissent sur des cibles moléculaires précises. Les <strong>benzodiazépines</strong> (diazépam, lorazépam) potentialisent les récepteurs GABA-A en se fixant sur un site allostérique, augmentant la fréquence d'ouverture du canal chlorure — un effet anxiolytique, sédatif, anticonvulsivant et myorelaxant. Les <strong>antipsychotiques de première génération</strong> (halopéridol) bloquent les récepteurs D2, réduisant les symptômes positifs de la schizophrénie (hallucinations, délires) au prix de symptômes extrapyramidaux. Les <strong>antipsychotiques atypiques</strong> (clozapine, olanzapine) associent blocage D2 et antagonisme 5-HT2A, améliorant les symptômes négatifs (retrait social, apathie) avec moins d'effets moteurs.</p>
<p class="resume-text">Les <strong>anesthésiques généraux</strong> agissent sur plusieurs cibles simultanément : le propofol potentialise GABA-A et inhibe les canaux sodiques ; la kétamine bloque les récepteurs NMDA (antagoniste du canal). La kétamine à doses sous-anesthésiques produit un effet antidépresseur rapide (en heures, versus semaines pour les ISRS), ciblant notamment les interneurones inhibiteurs PV+ qui, une fois bloqués, génèrent une vague de glutamate dans le cortex préfrontal favorisant la synaptogenèse rapide — mécanisme radicalement différent des antidépresseurs classiques.</p>

<h3>La résistance aux médicaments et la pharmacogénomique</h3>
<p class="resume-text">La variabilité interindividuelle de réponse aux psychotropes est considérable : les ISRS n'apportent pas de bénéfice clinique significatif chez 30-50 % des patients dépressifs. La <strong>pharmacogénomique</strong> cherche à prédire cette variabilité par les génotypes des patients. Les polymorphismes du gène CYP2D6, qui code une enzyme hépatique métabolisant de nombreux psychotropes, classent les individus en métaboliseurs lents, normaux, rapides et ultra-rapides — avec des variations de concentration plasmatique allant de 1 à 10 pour la même dose.</p>
<p class="resume-text">La variation du transporteur SERT (promoteur 5-HTTLPR, allèle court versus long) a été associée à une susceptibilité accrue à la dépression en réponse au stress et à une moins bonne réponse aux ISRS, bien que ces associations restent modestes à l'échelle individuelle. Le développement de tests génomiques cliniquement validés pour guider le choix des psychotropes (psychiatrie de précision) est un domaine de recherche actif, promettant de remplacer l'essai-erreur qui gouverne encore largement la prescription psychiatrique.</p>
""")

print("Neurochimie pages done.")
for key in ['neurochimie/neurotransmetteurs','neurochimie/dopamine','neurochimie/serotonine','neurochimie/synapses','neurochimie/pharmacologie']:
    print(f"  {key}: {len(pages[key]['content'])} chars")

with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved.")
