#!/usr/bin/env python3
"""Expand lesson articles in litterature-monde.json to reach ~15000 chars"""
import json

BASE = "C:/Users/nicol/Desktop/Projets/Divers/Curiosita"

with open(f"{BASE}/assets/content/litterature-monde.json", "r", encoding="utf-8") as f:
    data = json.load(f)

extra_shakespeare = """
  <h3>Roméo et Juliette — l'amour tragique</h3>
  <p class="resume-text"><strong>Roméo et Juliette</strong> (vers 1594-1596) est peut-être la pièce la plus célèbre de Shakespeare et la plus représentée dans le monde entier. La pièce raconte le destin de deux jeunes amants issus de familles rivales de Vérone — les Montaigu et les Capulet. Leur amour naît en un instant, s'intensifie en quelques jours et se termine par la mort des deux protagonistes dans un tombeau. Shakespeare y développe un lyrisme amoureux d'une intensité inégalée : le balcon ("Mais qu'est-ce que la lumière qui perce là cette fenêtre ? C'est l'Orient et Juliette est le soleil !"), les métaphores de la lumière et de la nuit, les jeux sur le nom — "Qu'y a-t-il dans un nom ? Ce qu'on appelle une rose, sous un autre nom, sentirait aussi bon."</p>
  <p class="resume-text">La pièce est aussi une réflexion sur la vitesse et la précipitation : tout va trop vite — la rencontre, le mariage secret, la mort de Mercutio, l'exil de Roméo, le plan de Frère Laurent. Shakespeare transforme la coïncidence en tragédie du destin, suggérant que la société qui a créé la haine entre les familles est aussi coupable que la fatalité.</p>

  <h3>La langue de Shakespeare</h3>
  <p class="resume-text">Shakespeare écrit principalement en <strong>vers blanc</strong> (<em>blank verse</em>) — vers iambiques pentamètres non rimés (10 syllabes, accent sur les syllabes paires) — ponctué de passages en prose pour les scènes comiques ou les personnages de condition modeste. Cette flexibilité prosodique lui permet d'adapter le rythme au contenu : les grands monologues shakespeariens jouent constamment entre le respect et la transgression du mètre pour créer des effets de tension ou d'accélération.</p>
  <p class="resume-text">La richesse du vocabulaire shakespearien est stupéfiante : il utilise environ 30 000 mots différents dans son oeuvre — trois fois plus que la Bible de King James. Certains de ses néologismes ont immédiatement passé dans l'usage : "bedroom" (chambre à coucher), "lonely" (solitaire), "generous" (généreux), "gloomy" (sombre), "obscene" (obscène)... Il forge des mots-valises, des calques du latin et du français, des adjectifs verbaux — créant une langue en expansion permanente.</p>

  <h3>La réception de Shakespeare en France</h3>
  <p class="resume-text">Shakespeare a mis longtemps à être reconnu en France. Voltaire, qui l'avait découvert en Angleterre et l'avait d'abord admiré, le rejette ensuite comme "barbare" et "sauvage" — trop mélangé des genres comique et tragique, trop irrégulier par rapport aux règles classiques françaises. C'est le romantisme qui, avec Stendhal (<em>Racine et Shakespeare</em>, 1823) et Victor Hugo, impose finalement Shakespeare comme le modèle de la liberté dramatique contre le classicisme figé.</p>
  <p class="resume-text">L'introduction de Shakespeare en France est une bataille esthétique et idéologique : lors d'une tournée de la troupe Kemble à Paris en 1827, les romantiques français découvrent enfin Shakespeare joué en anglais, avec un enthousiasme révolutionnaire. Berlioz en tombe amoureux — de la musique et d'Harriet Smithson qui jouait Ophélie. L'influence de Shakespeare sur Victor Hugo (<em>Hernani</em>, 1830), Vigny (<em>Othello</em> adapté), Gautier et Baudelaire est immense et durable.</p>

  <h3>Mesure pour Mesure et les "problem plays"</h3>
  <p class="resume-text">En dehors des grandes tragédies et comédies, Shakespeare a écrit un groupe de pièces qu'on appelle les "problem plays" — <em>Mesure pour Mesure</em>, <em>Troïlus et Cressida</em>, <em>Tout est bien qui finit bien</em> — qui ne sont ni vraiment comiques ni vraiment tragiques, et qui posent des questions morales sans résolution satisfaisante. <em>Mesure pour Mesure</em> (1604) est particulièrement dérangeant : un gouverneur vertueux abuse de son pouvoir pour contraindre une novice, et la pièce se "résout" par un mariage forcé que personne ne souhaitait vraiment. Ces pièces semblent anticiper la sensibilité moderne, qui se méfie des résolutions trop nettes et préfère les ambiguïtés morales.</p>"""

extra_modernisme = """
  <h3>L'Imagisme et Ezra Pound</h3>
  <p class="resume-text"><strong>Ezra Pound</strong> (1885-1972) est l'organisateur du modernisme anglophone autant que son poète. Son célèbre mot d'ordre — "Make it new !" — résume l'ambition moderniste : briser avec les conventions héritées pour trouver une langue poétique adaptée au monde contemporain. L'Imagisme, mouvement poétique qu'il fonde vers 1912 avec H.D. (Hilda Doolittle) et Richard Aldington, prône la précision de l'image concrète, l'économie du langage et le rythme musical plutôt que les métaphores usées du romantisme déclinant. Son poème "In a Station of the Metro" (1913) — "The apparition of these faces in the crowd; / Petals on a wet, black bough." — est le haïku moderniste anglais par excellence.</p>
  <p class="resume-text">Pound travaille directement sur le manuscrit de <em>La Terre vaine</em> d'Eliot — il en supprime la moitié, le structurant en cinq parties. Il fait de même pour <em>Ulysse</em> de Joyce, qu'il fait publier en feuilleton dans une revue américaine. Sans Pound, le modernisme anglophone aurait eu un visage très différent. Sa propre oeuvre majeure — les <em>Cantos</em>, commencés en 1917 et jamais achevés — est un poème long hétérogène, mêlant langues multiples, périodes historiques et registres variés dans une architecture labyrinthique qui préfigure le postmodernisme.</p>

  <h3>D.H. Lawrence : le modernisme des instincts</h3>
  <p class="resume-text"><strong>D.H. Lawrence</strong> (1885-1930) représente une autre voie moderniste — non pas celle de la fragmentation intellectuelle de Joyce et Eliot, mais celle de la plongée dans les forces vitales et instinctuelles de l'existence. <em>L'Amant de Lady Chatterley</em> (1928), <em>Fils et Amants</em> (1913), <em>L'Arc-en-ciel</em> (1915) explorent la sexualité, la relation entre les hommes et les femmes, et la destruction de la vitalité humaine par l'industrialisation. Lawrence est profondément hostile à la modernité industrielle — ses romans sont habités par une nostalgie des corps, de la nature et des relations pré-industrielles. Sa prose est sensuelle, rythmique, très différente de la sécheresse éliotienne.</p>

  <h3>Joseph Conrad : le proto-modernisme colonial</h3>
  <p class="resume-text"><strong>Joseph Conrad</strong> (1857-1924), né en Pologne mais écrivant en anglais (sa troisième langue), est une figure-clé du proto-modernisme. <em>Au coeur des ténèbres</em> (1899) est une exploration du colonialisme belge au Congo racontée par un narrateur (Marlow) qui raconte à d'autres narrateurs sur un bateau — structure de récit enchâssé qui problématise la fiabilité du témoignage. Kurtz, le personnage central qu'on ne rencontre que vers la fin, est devenu une figure mythique de l'Occident confronté à ses propres ténèbres. Francis Ford Coppola adaptera le roman dans <em>Apocalypse Now</em> (1979) en transposant l'action au Vietnam.</p>
  <p class="resume-text"><strong>Lord Jim</strong> (1900) et <strong>Nostromo</strong> (1904) confirment la maîtrise de Conrad : récits fragmentés, narrateurs multiples, temporalités entrelacées, atmosphères lourdes de sens moral. Conrad préfigure le modernisme par sa technique narrative — avant même que Joyce et Woolf ne théorisent leurs méthodes.</p>

  <h3>Toni Morrison — héritière du modernisme</h3>
  <p class="resume-text"><strong>Toni Morrison</strong> (1931-2019, Nobel 1993) est la grande héritière américaine du modernisme faulknérien. <em>Beloved</em> (1987), son chef-d'oeuvre, raconte l'histoire vraie de Margaret Garner, une femme esclave qui tue sa fille pour l'empêcher d'être reconduite en esclavage. Le roman est hanté — littéralement — par le fantôme de l'enfant tuée. Morrison utilise le surnaturel, la fragmentation temporelle et les perspectives multiples de Faulkner et Woolf pour explorer la mémoire traumatique de l'esclavage. La première phrase — "124 était une maison maudite" — annonce d'emblée un univers où le passé est physiquement présent. <em>Beloved</em> a remporté le prix Pulitzer en 1988 et est considéré comme l'un des plus grands romans américains du XXe siècle.</p>"""

extra_dostoievski = """
  <h3>Les Carnets du sous-sol (1864)</h3>
  <p class="resume-text"><em>Les Carnets du sous-sol</em> est la première oeuvre pleinement dostoïevskienne — celle où la voix caractéristique de Dostoïevski se dégage enfin. Le narrateur anonyme — "l'homme du sous-sol" — est une intelligence brillante, rancunière et paralysée, qui hait tout le monde et se hait lui-même. Il s'adresse directement au lecteur dans un monologue qui contredit et se reprend sans cesse, anticipant toutes les objections possibles. C'est la première démonstration de la "polyphonie" dostoïevskienne : une voix qui se divise contre elle-même, qui ne peut jamais se stabiliser en une position unique.</p>
  <p class="resume-text">Le texte est aussi une polémique violente contre le rationalisme positiviste de l'époque — la croyance que si les hommes connaissaient vraiment leurs véritables intérêts, ils agiraient rationnellement et seraient heureux. La liberté, pour Dostoïevski, implique nécessairement la possibilité de choisir le mal — ce qui rend impossible tout utopie rationnelle.</p>

  <h3>Dostoïevski et la religion</h3>
  <p class="resume-text">La foi chrétienne orthodoxe est centrale dans l'oeuvre de Dostoïevski — mais ce n'est pas une foi simple. Dostoïevski doute, questionne, met en scène les arguments contre Dieu avec toute leur puissance. Le "Grand Inquisiteur" dans <em>Les Frères Karamazov</em> est l'exposé le plus puissant de l'athéisme humaniste jamais mis en fiction. Dostoïevski ne résout pas la question de Dieu : il la pose dans toute son acuité. La foi d'Aliocha Karamazov — simple, silencieuse, orientée vers l'action concrète d'amour — n'est pas une réponse intellectuelle aux arguments d'Ivan, mais une réponse existentielle.</p>
  <p class="resume-text">Cette tension entre le doute et la foi, entre la raison qui nie et le coeur qui affirme, est peut-être ce qui donne à ses romans leur puissance particulière : ils ne rassurent pas, ils ne convertissent pas — ils placent le lecteur au coeur de la question, face à l'abîme, et lui laissent la responsabilité de choisir.</p>

  <h3>Dostoïevski et la Saint-Pétersbourg littéraire</h3>
  <p class="resume-text">Saint-Pétersbourg joue un rôle essentiel dans l'oeuvre de Dostoïevski — presque à égalité avec ses personnages humains. La ville a été fondée par Pierre le Grand au début du XVIIIe siècle comme fenêtre de la Russie sur l'Europe, construite sur des marais, à un coût humain énorme. Elle incarne pour Dostoïevski le déchirement de la Russie entre son âme slave et l'Occident importé de force. Ses brouillards, ses canaux, ses immeubles délabrants et ses nuits blanches créent une atmosphère d'irréalité et de tension psychologique parfaitement accordée à ses romans. Dans <em>Crime et Châtiment</em>, la ville est presque un personnage : sa chaleur étouffante, ses odeurs, ses tavernes sombres, ses fonctionnaires misérables forment le décor extérieur de l'enfer intérieur de Raskolnikov.</p>

  <h3>Les adaptations de Dostoïevski au cinéma</h3>
  <p class="resume-text">Les romans de Dostoïevski ont donné lieu à de nombreuses adaptations cinématographiques majeures. <em>Crime et Châtiment</em> a été adapté par Robert Bresson (<em>Pickpocket</em>, 1959, adaptation libre), Josef von Sternberg (1935) et de nombreux réalisateurs soviétiques et russes. <em>Les Frères Karamazov</em> a été adapté par Richard Brooks (1958) et en URSS par Ivan Pyriev (1968). <strong>Akira Kurosawa</strong> a adapté <em>L'Idiot</em> (1951) dans le Japon d'après-guerre — déplaçant le prince Mychkine dans une société ravagée par la guerre, l'occupation et la pauvreté. Ces adaptations montrent la capacité des thèmes dostoïevskiens à se déplacer dans n'importe quel contexte historique ou culturel : la question de la culpabilité, de la rédemption et de la liberté est universelle.</p>"""

extra_borges = """
  <h3>Les essais de Borges</h3>
  <p class="resume-text">Borges est aussi l'un des plus grands essayistes de langue espagnole. Ses <em>Inquisitions</em> (1925), <em>Discussion</em> (1932) et <em>Autres inquisitions</em> (1952) explorent la littérature universelle avec une érudition brillante et parfois fantaisiste. Il écrit sur Homère, Dante, Cervantès, Kafka, Wells — mais aussi sur les doctrines théologiques médiévales, les paradoxes de Zénon, les miroirs, les labyrinthes. Ces essais sont aussi des fictions déguisées : leurs arguments mènent souvent vers des conclusions vertigineuses qui déplacent la frontière entre réalité et imagination.</p>

  <h3>Borges et le temps circulaire</h3>
  <p class="resume-text">L'une des obsessions centrales de Borges est le temps — et plus précisément l'idée du temps circulaire ou de l'éternel retour. Plusieurs nouvelles explorent des variations sur ce thème : dans <em>Le Jardin aux sentiers qui bifurquent</em>, le temps se ramifie ; dans <em>Le Temps circulaire</em> (essai), il revient sur lui-même ; dans <em>La Mort et la boussole</em>, le détective Lönnrot est piégé par sa propre logique dans un labyrinthe qui se referme. Cette obsession temporelle a des sources philosophiques précises que Borges cite explicitement : Nietzsche (l'éternel retour), Schopenhauer (le temps comme maya), les Upanishads hindous.</p>
  <p class="resume-text">La nouvelle <em>Le Sud</em> (1953) est souvent citée comme l'une de ses plus belles : un homme hospitalisé rêve peut-être une vie alternative — ou vit peut-être une mort différente de celle qu'il a en réalité. Comme toujours chez Borges, les deux interprétations sont également valables, et c'est précisément cette indétermination qui est l'argument philosophique de la nouvelle.</p>

  <h3>L'influence du fantastique anglais sur Borges</h3>
  <p class="resume-text">Borges a été formé autant par la littérature anglaise que par l'espagnole — son père avait une grande bibliothèque en anglais, et il a appris l'anglais avant l'espagnol. Ses grandes influences sont H.G. Wells (la science-fiction philosophique), Robert Louis Stevenson (le récit d'aventure à double sens), G.K. Chesterton (le paradoxe et la surprise intellectuelle), De Quincey (la prose poétique), et surtout <em>Les Mille et une Nuits</em> (dans la traduction de Burton), dont la structure de récit enchâssé — histoires dans les histoires, conteur dans le conteur — est le modèle de sa propre écriture labyrinthique.</p>

  <h3>Borges — une lecture mondiale</h3>
  <p class="resume-text">La réception mondiale de Borges est un phénomène culturel en soi. En France, il est traduit dans les années 1950-60 et adopté immédiatement par les intellectuels — Roger Caillois le présente, Michel Foucault lui consacre l'ouverture de <em>Les Mots et les Choses</em> (1966). En Amérique latine, son influence est ambiguë : les écrivains du boom lui sont redevables mais prennent souvent leurs distances — García Márquez lui préfère Faulkner et Rulfo. Aux États-Unis, il est découvert tardivement mais avec enthousiasme par les postmodernistes des années 1970. Au Japon, Haruki Murakami reconnaît sa dette dans chaque roman. Borges est peut-être le seul écrivain du XXe siècle dont l'influence est véritablement planétaire et transdisciplinaire — philosophes, mathématiciens, informaticiens, architectes et cinéastes se réclament tous de lui.</p>"""

extra_garcia = """
  <h3>Les nouvelles</h3>
  <p class="resume-text">Les nouvelles de García Márquez sont aussi importantes que ses romans. <em>Un monsieur très vieux avec des ailes énormes</em> (1968) est peut-être le plus pur exemple de réalisme magique : un ange tombe dans la cour d'une famille paysanne. Personne ne sait vraiment ce qu'il est. La famille le met en cage et fait payer pour le voir. L'ange n'est ni miraculeux ni particulièrement angélique : il est vieux, sale et incompréhensible. La nouvelle est une satire de la religion institutionnelle, de la curiosité humaine et de la façon dont le merveilleux devient spectacle commercial. <em>L'Incroyable et Triste Histoire de la candide Eréndira et de sa grand-mère diabolique</em> (1972) mêle la brutalité la plus réelle à la légèreté du récit oral caraïbe — on rit et on est horrifié simultanément.</p>

  <h3>Macondo — la géographie du mythe</h3>
  <p class="resume-text">Macondo, le village fictif de <em>Cent ans de solitude</em>, est devenu l'une des grandes géographies imaginaires de la littérature mondiale — comparable à Yoknapatawpha de Faulkner ou au Dublin de Joyce. García Márquez a construit un plan précis du village, numérotant les maisons, plaçant les institutions, traçant les rues. Ce réalisme documentaire ancre le mythe dans la géographie. Macondo commence comme une communauté idéale coupée du monde, traverse la découverte, la prospérité, la corruption politique, l'emprise du capitalisme étranger et finit dans la solitude et l'oubli — une allégorie de l'Amérique latine depuis la colonisation jusqu'au néocolonialisme économique.</p>

  <h3>García Márquez et ses contemporains du boom</h3>
  <p class="resume-text">Le "boom" latino-américain est autant un phénomène éditorial qu'un mouvement littéraire. L'agent Carmen Balcells et l'éditeur Carlos Barral à Barcelone jouent un rôle crucial en internationalisant des auteurs qui, jusqu'alors, ne circulaient guère hors de leurs pays. <strong>Mario Vargas Llosa</strong> (Pérou, Nobel 2010) publie <em>La Ville et les Chiens</em> (1963), roman sur la violence dans un lycée militaire. <strong>Julio Cortázar</strong> (Argentine) publie <em>Marelle</em> (1963), roman expérimental dont le lecteur peut choisir l'ordre de lecture, et <em>Cronopes et Fameux</em> (1962), textes inclassables entre fiction, prose poétique et humour surréaliste. <strong>Carlos Fuentes</strong> (Mexique) explore l'histoire mexicaine avec une virtuosité formelle qui doit autant à Faulkner qu'à la tradition orale aztèque.</p>

  <h3>L'Amour aux temps du choléra — structure narrative</h3>
  <p class="resume-text">Ce qui frappe dans <em>L'Amour aux temps du choléra</em>, c'est la façon dont García Márquez réinvente le roman d'amour en le déplaçant dans la vieillesse. La plupart des histoires d'amour se terminent soit avec la mort, soit avec le mariage — c'est-à-dire avec la jeunesse. García Márquez commence son roman à la mort du mari, quand les deux amants ont déjà passé 70 ans, et explore ce que peut être l'amour entre des corps vieillis, des mémoires encombréess et des habitudes figées. Le fleuve du Magdalena, sur lequel se déroule la scène finale, est un espace hors du temps — les deux amants voyagent indéfiniment, repoussant le moment du retour, déclarant la peste pour ne jamais accoster nulle part. L'amour comme état permanent, comme refus de la réalité : c'est peut-être la définition borgésienne que García Márquez propose ici.</p>"""

extra_japon = """
  <h3>La littérature d'Edo — le roman populaire</h3>
  <p class="resume-text">La période Edo (1603-1868) voit l'émergence d'une littérature populaire urbaine très différente du raffinement de cour de l'époque Heian. <strong>Ihara Saikaku</strong> (1642-1693) écrit des romans picaresques sur la vie des marchands, des courtisanes et des samouraïs — avec humour, réalisme et une célébration de la sensualité. <em>Vie d'une Amoureuse</em> (1682) raconte la vie d'une femme qui devient successivement épouse, concubine, prostituée de luxe et finalement vieille mendiante : un roman social d'une franchise remarquable pour l'époque.</p>
  <p class="resume-text"><strong>Ueda Akinari</strong> (1734-1809) publie <em>Contes de pluie et de lune</em> (Ugetsu monogatari, 1776), recueil de nouvelles fantastiques qui mêlent esprits, démons, revenants et désirs humains. Ces nouvelles ont influencé la littérature fantastique japonaise moderne et ont été portées à l'écran par Kenji Mizoguchi dans son film <em>Les Contes de la lune vague après la pluie</em> (1953).</p>

  <h3>Le roman Meiji et la modernisation</h3>
  <p class="resume-text">L'ère Meiji (1868-1912) voit le Japon s'ouvrir brutalement à l'Occident — et la littérature japonaise absorber en quelques décennies les formes narratives du roman occidental. <strong>Natsume Soseki</strong> (1867-1916) est le premier grand romancier moderne japonais. <em>Je suis un chat</em> (1905-1906), roman satirique narré par un chat observateur de la société bourgeoise de l'ère Meiji, est son oeuvre la plus populaire. <em>Kokoro</em> (1914), son chef-d'oeuvre, explore la solitude, la culpabilité et la désorientation d'un Japon entre deux mondes — l'ancien code de l'honneur et la modernité individualiste. Le concept de <em>jiga</em> (le moi) — inconnu dans la littérature classique japonaise — devient le sujet central du roman Meiji.</p>

  <h3>Kawabata, Mishima et l'après-guerre</h3>
  <p class="resume-text"><strong>Yasunari Kawabata</strong> (1899-1972, Nobel 1968) incarne la continuité de l'esthétique classique dans le roman moderne. <em>Pays de neige</em> (1937-1948), <em>Le Lac</em> (1954) et <em>Les Belles Endormies</em> (1961) baignent dans une atmosphère de mélancolie raffinée et de désir insaisissable. Son style — court, elliptique, fondé sur l'image sensorielle plutôt que sur le développement psychologique — est l'héritier direct du haïku. Dans son discours Nobel, il cite Dogen, Myoe et Ikkyu — trois maîtres zen du Moyen Age japonais — comme ses inspirateurs.</p>
  <p class="resume-text"><strong>Yukio Mishima</strong> (1925-1970) est son exact opposé : flamboyant, ultra-nationaliste, auteur d'une oeuvre abondante et provocatrice, il se suicide de façon rituelle (seppuku) après avoir tenté un coup d'Etat symbolique. Son chef-d'oeuvre, la tétralogie <em>La Mer de la fertilité</em> (1965-1970), est une méditation sur la réincarnation, la mort et la beauté. <strong>Haruki Murakami</strong> (né en 1949) représente la génération suivante — plus populaire, plus occidentalisée, mêlant jazz américain, littérature européenne et mythologie japonaise dans des romans d'une accessibilité et d'une profondeur uniques. <em>Kafka sur le rivage</em> (2002) et <em>1Q84</em> (2009-2010) sont ses oeuvres les plus ambitieuses.</p>"""

# Apply expansions — append before last </section>
for key, extra in [
    ("anglophone/shakespeare", extra_shakespeare),
    ("anglophone/modernisme", extra_modernisme),
    ("russe/dostoievski", extra_dostoievski),
    ("latino-americaine/borges", extra_borges),
    ("latino-americaine/garcia-marquez", extra_garcia),
    ("asiatique/japon-classique", extra_japon),
]:
    page = data["pages"][key]
    # Insert before the last </section>
    idx = page["content"].rfind("</section>")
    page["content"] = page["content"][:idx] + extra + "\n" + page["content"][idx:]

with open(f"{BASE}/assets/content/litterature-monde.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Updated. Sizes:")
for key in ["anglophone/shakespeare", "anglophone/modernisme", "russe/dostoievski",
            "latino-americaine/borges", "latino-americaine/garcia-marquez", "asiatique/japon-classique"]:
    print(f"  {key}: {len(data['pages'][key]['content'])} chars")
